### ISSUE TITLE
先输入文字然后再粘贴表格,表格的边框等样式会丢失

### ISSUE THREAD

**Issue by wadjsnkk** [wangeditor-team/wangEditor#1000]
操作:
在框中直接粘贴有边框表格(excel中复制的)是无问题的,一旦框中输入了文字换行想再粘贴表格,样式就会失效

**Comment by wangfupeng1988** [comment]
这个是在 windows 下吧？哪个浏览器？官网是否会复现这个问题？

以上这些信息，你最好都提供一下，让我以最快的效率复现问题

**Comment by wadjsnkk** [comment]
系统:windows7 uc浏览器,chrome 版本 60.0.3112.113（正式版本）都一样,在官网试了,也是一样的,麻烦您按照步骤试一下:
1.复制excle中的表格
2.先手动在wangeditor中输入一段文字,换行
3.粘贴剪切板中的表格,这个时候格式不见了(文本是有的,边框,背景色这些就没有了)

**Comment by wangfupeng1988** [comment]
好，我记录下，下次升级看一下

**Comment by wangfupeng1988** [comment]
10.0.13新增了`editor.customConfig.pasteTextHandle`可自定义过滤粘贴的内容 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
