### ISSUE TITLE
全选文字以后ctrl+c ,将光标移动到被选文字最后，ctrl+v，发现无法粘贴全选复制的文字

### ISSUE THREAD

**Issue by heroofchina** [wangeditor-team/wangEditor#1096]
1.全选文字以后ctrl+c 
2.将光标移动到被选文字最后
3.ctrl+v
4.发现无法粘贴全选复制的文字

**Comment by wangfupeng1988** [comment]
官网能复现这个问题？什么系统、什么浏览器？

**Comment by heroofchina** [comment]
官网会复现这个问题，而且我本地也会出现这个问题

**Comment by wangfupeng1988** [comment]
我在官网就没有复现，详细说明你的复现步骤。

另外：什么系统、什么浏览器？

**Comment by heroofchina** [comment]
windows & mac 在谷歌浏览器下出现这样的问题

**Comment by wangfupeng1988** [comment]
> 我在官网就没有复现，详细说明你的复现步骤

什么浏览器我问过你两遍，这个问题还要再问两遍。。。提问问题要详细说明，否则反复回复的交流成本太高了，得亏我还每一两天看一次问题，如果我一周看一次问题，这个问题岂不是要交流一个月？

**Comment by heroofchina** [comment]
我也说过几遍，windows和mac的谷歌浏览器（chrome）上面都会出现这个问题，你是否真的仔细按照我说的步骤去复现了？
步骤是这样的
1.先输入一段文字 然后ctrl+a 进行全选，
2.然后ctrl＋c 进行复制
3.将光标移动到输入的文字最末尾
4.进行ctrl＋v 粘贴
这时候你会发现 你需要ctrl＋v两次才能将内容粘贴进去

**Comment by wangfupeng1988** [comment]
跟你说一下我这边无法复现的步骤。mac os chrome 进入官网，官网编辑器默认显示`欢迎使用wangEditor 富文本编辑器，请输入内容...`。

然后找你说的，全选所有内容，ctrl+c 复制，然后点击鼠标将光标移动到最后，再 ctrl+v 粘贴，就直接粘贴上了。

**Comment by heroofchina** [comment]
我把出现的问题录屏了 发邮件给你了 请查看 谢谢

**Comment by heroofchina** [comment]
因为这里面无法上传视频 只能给你单发了 不好意思啊

**Comment by heroofchina** [comment]
[编辑器问题录屏纪录.zip](https://github.com/wangfupeng1988/wangEditor/files/1432945/default.zip)
[](url)

**Comment by heroofchina** [comment]
邮箱发送失败 打包出来吧

**Comment by qinouz** [comment]
确实 有时候 会出现 他说的  bug`````````````````

**Comment by wangfupeng1988** [comment]
我周末看一下哈，有问题会升级修改

**Comment by wangfupeng1988** [comment]
我确实确实确实未复现这个问题，用 windows chrome 62 。
用 mac 也没有复现。

这就尴尬了。。。。

**Comment by heroofchina** [comment]
可以参考我发的小视频 里面有具体的操作流程 可以看下

**Comment by zpf124** [comment]
我一次 操作就复现了这个问题， 并且不是偶尔出现，而是只要这样操作必然会出现这个bug，不过他的描述有误。

这个bug，不是剪贴板的内容没有粘贴全，而是问题出现在了 **用鼠标取消全选** 上， 实际编辑器没有识别到全选取消的操作，所以粘贴之后实际上是清空了编辑器原有内容。

随便复制一段与编辑器中内容不同的文本，全选 ，然后不需要移动到最后，鼠标单击任意位置取消全选，粘贴。
就会发现 复制的内容不是追加进去的，而是替换掉了旧的。

**Comment by heroofchina** [comment]
但是这个问题还是没有fixed掉

**Comment by wangfupeng1988** [comment]
@zpf124 

> 而是问题出现在了 用鼠标取消全选 上， 实际编辑器没有识别到全选取消的操作

没明白啥意思

**Comment by zpf124** [comment]
就是ctrl + a 全选后,左键单击不能取消全选.

**Comment by zzzeee** [comment]
![wechatimg14](https://user-images.githubusercontent.com/26219025/37083675-30080914-222b-11e8-9876-b7abed0e69cd.jpeg)
![wechatimg15](https://user-images.githubusercontent.com/26219025/37083678-34f0fa80-222b-11e8-8d69-499ce77f47cd.jpeg)
![1520414080021](https://user-images.githubusercontent.com/26219025/37083679-368b8770-222b-11e8-8bf3-ab55f91aeed0.jpg)

**Comment by zpf124** [comment]
@zzzeee 
选中一个词点击取消选中，之后粘贴一个不一样的内容试试， 你就会发现:

第一次不是只粘贴出来一个<br>, 而是 会用 剪切板内容 +<br> 替换 选中内容

**Comment by zpf124** [comment]
这已经是我想到的最明确的说明方式了....
![gif](https://user-images.githubusercontent.com/11630361/37084855-90bbf344-222e-11e8-97ba-7c09129c9e05.gif)

**Comment by zzzeee** [comment]
@zpf124  明白你的意思, 试过之后还真有, 步骤:
1.  随意输入一行文字(最好另起一行)
2. 选中文字并复制，复制后再取消选中状态
3. 再进行选中部份文字至行尾(bug的出现关键必须选择至行尾)
4. 把光标放在输入行的行尾(无选中状态), 这时再进行粘贴
5. 会把步骤3选中的部份文字替换成步骤2所复制的文字

`开源果然是个很有趣的地方`

**Comment by Null-C** [comment]
按照后面的动图，我也复现了这个bug。
windows 10 / chrome 66 / wangEditor-3.1.1

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
