### ISSUE TITLE
菜单和编辑区域分离 onfocus onblur

### ISSUE THREAD

**Issue by xtqjh** [wangeditor-team/wangEditor#1172]
使用菜单和编辑区域分离时
使用onfocus与onblur对编辑器无效果

**Comment by wangfupeng1988** [comment]
@hold-baby 看能否搞定这个问题？

**Comment by hold-baby** [comment]
好的

**Comment by hold-baby** [comment]
![image](https://user-images.githubusercontent.com/21041219/33353331-3d11c428-d4e8-11e7-92ee-83aba1125a18.png)

在源码中把标红的变量 改为 $textElem

**Comment by tanxuewei** [comment]
现在的版本已经改掉这个问题了么？什么时候上线？急

**Comment by hold-baby** [comment]
@tanxuewei 现在还没有更新 你要是急就按我说的改就行了

**Comment by tanxuewei** [comment]
@hold-baby 那计划什么时候上线呢？我现在用的是npm下载的，如果自己手动改，就要改成引入js包，先看一下你们计划发布的时间？

**Comment by hold-baby** [comment]
这个就要看 @wangfupeng1988 的计划了

**Comment by wangfupeng1988** [comment]
近期我有其他事情忙（预计还会再忙一个多月），因此更新进度慢了。最快也得这个周末看一下。
