### ISSUE TITLE
菜单与编辑器分离的问题

### ISSUE THREAD

**Issue by hdzakk** [wangeditor-team/wangEditor#1364]
菜单与编辑器时，当编辑器内容很多时，菜单栏固定，编辑器滚到一定的的距离时在点击菜单栏上的图片或者超链接是弹出的框不在可视区内了，跑到了编辑区的顶部去了。这个这么解决啊

**Comment by hdzakk** [comment]
菜单与编辑器时，当编辑器内容很多时，菜单栏固定，编辑器滚到一定的的距离时在点击菜单栏上的图片或者超链接是弹出的框不在可视区内了，跑到了编辑区的顶部去了。这个这么解决啊

**Comment by wangfupeng1988** [comment]
截个图，或者弄一个能快速复现 bug 的静态页面

**Comment by hdzakk** [comment]
在ie会出现那个问题，在Chrome浏览器会立即滚到顶部
![image](https://user-images.githubusercontent.com/11908815/37079809-db5600da-221e-11e8-983d-1e2c3cce1774.png)

**Comment by wangfupeng1988** [comment]
看你图片，你的编辑框也跟着滚动上去了？没有固定？

**Comment by UltramanWeiLai** [comment]
弹出面板的位置是基于 编辑区域的顶端的，请保证编辑区域再页面显示范围内
