### ISSUE TITLE
粘贴后在设置链接问题

### ISSUE THREAD

**Issue by hdzakk** [wangeditor-team/wangEditor#1366]
从其他地方复制一串文本到编辑器，然后在设置此文本的超链接时 a 标签上多了个style="font-size: 14px;"请问这个能去掉吗？如果是直接在编辑器输入的文本在设置链接就不会出现此问题。
![image](https://user-images.githubusercontent.com/11908815/37085061-17914d24-222f-11e8-9d53-9f405e5c27d5.png)

**Comment by wangfupeng1988** [comment]
这个`style="font-size: 14px;"`应该是粘贴时候带过来的，并不是设置链接时候生成的。

你没有关闭粘贴样式的过滤吧？文档看这里 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
