### ISSUE TITLE
复制粘贴会很卡

### ISSUE THREAD

**Issue by sunnyYanan** [wangeditor-team/wangEditor#1392]
复制一个word文档，超级卡

**Comment by wangfupeng1988** [comment]
你复制过来的内容是不是非常多？
另外，你说的“卡”，具体是怎么卡顿，详细描述一下过程。

**Comment by sunnyYanan** [comment]
内容是比较多，复制后页面跳无响应了。要等很长时间内容才显示出来，今天粗略估计2分钟左右

**Comment by wangfupeng1988** [comment]
> 跳无响应

啥意思？

另外，你试试少复制一些内容会怎样。大约复制多少字的时候，会出现卡顿情况。

**Comment by UltramanWeiLai** [comment]
复制内容过多，浏览器处理比较吃力，有卡顿是正常的，你可以分次复制或者提升电脑配置
