### ISSUE TITLE
选择字体颜色或者背景，没有生效

### ISSUE THREAD

**Issue by conan2008** [wangeditor-team/wangEditor#1393]
用提供的demo也是这个问题。但拉框选中一些文字之后，再选择颜色火背景就可以。
不知道是不是我操作的问题。

win10， chrome。

**Comment by wangfupeng1988** [comment]
你使用的最新版的吧？

以前版本，当点击不精确的时候，会遇到你说的问题，但是后来修复了

**Comment by conan2008** [comment]
开始的时候用10.0.13版本，是这个问题，然后github上package是3.1.0， 也试过了， 都是同样的问题。
而且官网上的也是这个情况，  我用chrome和ie都不行，你可以试试。

**Comment by wangfupeng1988** [comment]
> 开始的时候用10.0.13版本

这个版本好写错了，没有 v10 ，现在最高版本就是 v3.1.x

我在 chrome 上没有复现。你的意思是说：背景颜色和前景颜色，这里菜单直接就失效，不能用了？

**Comment by chenzhe-pro** [comment]
@wangfupeng1988  当鼠标光标在却不选中任何文字的时候，是失效的，非得选中文字才有效。见下图：
![image](https://user-images.githubusercontent.com/12438085/37459113-1055752c-2882-11e8-944d-1fb0d4ae08b4.png)

能不能像word那样，光标在哪一行，哪一行的文字就会被修改。

**Comment by conan2008** [comment]
@wangfupeng1988 比如我要输入红色字体，然后点击选择了红色字体，输入的时候还是原来的样子。
ps：跟上面的兄弟说的下划线，差不多一个意思

**Comment by aaronlui** [comment]
具体就是我先输入123，然后选择文字颜色为红色，接着输入456，此时456的颜色并没有变成红色

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
