### ISSUE TITLE
拷贝内容

### ISSUE THREAD

**Issue by NingMengMeng** [wangeditor-team/wangEditor#1396]
在富文本框中复制内容，光标在最后，结果第一次ctrl+v没用，再次ctrl+v才可以，IE则是换行。测试已经提了bug了，多谢多谢

**Comment by wangfupeng1988** [comment]
> 结果第一次ctrl+v没用，再次ctrl+v才可以

我试了一下，复现不稳定，你能找到稳定复现的场景吗？

> IE则是换行

IE 兼容性问题先暂时不考虑了，优先级放低一些

**Comment by wangfupeng1988** [comment]
OK 我看到了，我记录下，下次升级看一下这个问题

**Comment by harrydengchao** [comment]
+1

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
