### ISSUE TITLE
编辑器粘贴内容如果含有换行符 编辑器回显会报错

### ISSUE THREAD

**Issue by Emon0526** [wangeditor-team/wangEditor#1409]
在使用编辑器粘贴内容的时候
如果含有换行符 例如word中的换行符
发表成功后 
编辑器回显会报错
![image](https://user-images.githubusercontent.com/11533127/37583306-e4414cd8-2b8b-11e8-8089-4a7b2a5d5f0e.png)

**Comment by wangfupeng1988** [comment]
把粘贴的内容发到这里吧，另外报错信息一整行都截图给我吧。我得自己复现看一下。

**Comment by Emon0526** [comment]
@wangfupeng1988 
首先超级感谢你能回复

我们也是根据用户反馈的BUG发现这个问题的，
大部分用户发帖会通过复制word的内容
我们发现只要用户发表的内容之中有word的换行符
![image](https://user-images.githubusercontent.com/11533127/37765377-f16cca16-2dfe-11e8-9146-cd6efbbf8903.png)

比如上图中的符号
回显内容的时候就会报错
如果直接用编辑器输入换行是没问题的
我们通过删除用户发表内容中的换行符就能修复回显的问题
不知道是我们自己的问题还是编辑器的问题

报错信息除了

![](https://user-images.githubusercontent.com/11533127/37583306-e4414cd8-2b8b-11e8-8089-4a7b2a5d5f0e.png)
外在页面源码中还出现了以下代码

![image](https://user-images.githubusercontent.com/11533127/37765342-e9b1a3c8-2dfe-11e8-982b-e9abeffc5507.png)

**Comment by lydon18** [comment]
配置  editor.customConfig.pasteFilterStyle = true 不生效，比如从word中复制内容粘贴到富文本，提交的HTML内容类似
![image](https://user-images.githubusercontent.com/13651761/38287809-5cb84098-37ff-11e8-9a57-dec915e08163.png)

有很多无用标签；回显的时候无法回显
![image](https://user-images.githubusercontent.com/13651761/38287772-13a6e274-37ff-11e8-9630-2ddf249aa06c.png)
![image](https://user-images.githubusercontent.com/13651761/38287798-46cf7620-37ff-11e8-9457-2d0dd130b3f0.png)

**Comment by ShuaiYing701** [comment]
大佬 这个怎么解决的啊

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
