### ISSUE TITLE
编辑器中的粘贴问题

### ISSUE THREAD

**Issue by jay816314** [wangeditor-team/wangEditor#1410]
复制一段文本，在编辑器中，拉动鼠标全选编辑器内容，如果mouseUp的时候鼠标光标在编辑器外（bug触发点应该是这个，光标在编辑器内不会有bug），ctrl+v的时候不会完全覆盖文本，能够覆盖的内容范围似乎和拉动鼠标速度有关系，拉动越快，覆盖的内容越少。ctrl+a+v不会有此bug。
官网上的demo和使用本地旧的10月份的js均会触发。

**Comment by wangfupeng1988** [comment]
看到了，感谢反馈。我记录下，再次升级时看一下。

> 如果mouseUp的时候鼠标光标在编辑器外（bug触发点应该是这个，光标在编辑器内不会有bug）

应该就是这里的 bug

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
