### ISSUE TITLE
设置内容设置不了

### ISSUE THREAD

**Issue by WinnieWei0** [wangeditor-team/wangEditor#1420]
按照文档那样设置内容设置不了的。。。文档部分使用跟实际应用不相符，用npm安装不需要使用第一句 var E = window.wangEditor ，加油哈

**Comment by wangfupeng1988** [comment]
> 按照文档那样设置内容设置不了的。。。

具体报错或者场景说明一下，光着一句话我判断不了啥问题

**Comment by WinnieWei0** [comment]
在vue中通过后台返回数据给编辑器设置内容，没成功，不报错

**Comment by tomoya92** [comment]
如果内容里有 引号，设置内容的时候会报错

比如引入了一段代码 `console.log('hello world');`，然后通过 `editor.txt.html('${content}');` 设置内容就会报错

这种应该怎么处理呢？

**Comment by wangfupeng1988** [comment]
关键代码粘贴一下，能让我尽快复现问题。

**Comment by mariobeng** [comment]
> 在vue中通过后台返回数据给编辑器设置内容，没成功，不报错

应该是获取数据异步问题
