### ISSUE TITLE
连续插入HTML出错

### ISSUE THREAD

**Issue by TsingM** [wangeditor-team/wangEditor#1478]
插入 HTML的语句：`editor.cmd.do('insertHTML', '<p>...</p>')`
用来插入`<span>123</span>`片段时，首次插入没问题，第二次插入时会将内容去除标签插在第一次的span里面，即`<span>123123</span>`
而不是想要的同级的DOM结构：`<span>123</span><span>123</span>`

**Comment by wangfupeng1988** [comment]
插入内容，必须用`<p>`包裹

**Comment by TsingM** [comment]
改成`<p>`还是不行，会把内容自动合并在一对`<p>`里面，而不是连续多对`<p>`

**Comment by wangfupeng1988** [comment]
给我的可复现问题的 demo 吧。能复现问题就行，越简单越好。
