### ISSUE TITLE
[插入代码功能]重复编辑时格式问题

### ISSUE THREAD

**Issue by Null-C** [wangeditor-team/wangEditor#1521]
复现步骤：

**1.** 插入代码。
![image](https://user-images.githubusercontent.com/27117753/39963912-6ed57afa-56ab-11e8-8916-0d47834f2dff.png)

**2.** 光标放置在代码块中，重新激活编辑代码功能。
![image](https://user-images.githubusercontent.com/27117753/39963916-78296b48-56ab-11e8-8fd6-a20fe8891dad.png)

**3.** 此时获取的代码换行被`<br>`标签替换了。（而不是最原始的代码）
![image](https://user-images.githubusercontent.com/27117753/39963918-7c44dbf4-56ab-11e8-9635-7509983bf338.png)

这样对二次编辑代码块有些不方便。
环境： windows 10 / chrome 66 / wangEditor-3.1.1 (官网亦可复现)

**Comment by wangfupeng1988** [comment]
记下了，下次升级修改。感谢反馈。

**Comment by wangfupeng1988** [comment]
找到原因了，已经修复，下次升级时一起发布。
