### ISSUE TITLE
.txt 后缀文件,复制进来, 所有的换行,排版,都没了

### ISSUE THREAD

**Issue by lt123456** [wangeditor-team/wangEditor#1538]
.txt文件.有多个段落..... 复制 到编辑器,就变成了一个段落, 请问有参数,或者修复办法么?大神

**Comment by wangfupeng1988** [comment]
你再帮我试一下，从`<textarea>`中复制多个段落，粘贴可以吗？

**Comment by LuuFe** [comment]
输入好多字不打回车键，文本框内看的换行了，但是也没有<p></p>包裹

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
