### ISSUE TITLE
qq 10.0 浏览器兼容问题

### ISSUE THREAD

**Issue by cxcshuaige** [wangeditor-team/wangEditor#1540]
1.插入图片以后，必须改变一下光标位置才可继续输入
2.出现输入法无法切换问题，或者说是中文输入法失效

官网中此问题能复现

**Comment by wangfupeng1988** [comment]
手机的还是电脑上的？

如果是手机的，编辑器目前不支持移动版。

**Comment by cxcshuaige** [comment]
电脑上的

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
