### ISSUE TITLE
editor.txt.text(editor.txt.text().subString(0,1000))会截取到样式的代码

### ISSUE THREAD

**Issue by liyunqaing** [wangeditor-team/wangEditor#1553]
editor.txt.text(editor.txt.text().subString(0,1000))会截取到样式的代码

**Comment by wangfupeng1988** [comment]
没看明白，请把问题描述详细一些。

**Comment by liyunqaing** [comment]
@wangfupeng1988 就是我用editor.txt.text(editor.txt.text().subString(0,1000))截取前1000个文本时，会将文本前面的css代码也截取到，就是那些“加粗、字体.....”的代码

**Comment by wangfupeng1988** [comment]
你使用`editor.txt.text()`获取到的会有 css 的代码？

**Comment by HYqwf** [comment]
> 你使用`editor.txt.text()`获取到的会有 css 的代码？

editor.txt.text().subString(0,1000)这个的期望是能截取1000个字符，但是编辑器自动加入p标签后，p标签也自动算在了1000字符里。点击Backspace，获取到的又会多一些p标签、br标签等，位置出现的还特诡异
![image](https://user-images.githubusercontent.com/12951637/50329879-f3025c80-0533-11e9-9bf4-1649b0041b4c.png)

**Comment by HYqwf** [comment]
感觉编辑器可以加个配置：限制用户输入字数，感觉还蛮常用到的。期待

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
