### ISSUE TITLE
对文字进行有序列表和无序列表操作，点击撤销无法回退到之前的状态

### ISSUE THREAD

**Issue by lxdDreamFuture** [wangeditor-team/wangEditor#1561]
我在官网试了，这个问题是必现的。

让一段文字变成有序列表或无序列表后，进行撤销操作，出现了以下几种情况bug
1.文字全部消失
2.第一段文字消失，第二段还在。
3.变成了正常文字，但是再按回车换行无反应。

**Comment by wangfupeng1988** [comment]
这个问题已知。列表和撤销混在一起操作，目前是有点问题，这主要是撤销功能的问题。我会在近期升级时考虑修改。

**Comment by hfzhanghf** [comment]
请问这个问题修复了吗？ @wangfupeng1988

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
