### ISSUE TITLE
自定义的table标签 在editor中不能新增 行列，都不能显示出功能框

### ISSUE THREAD

**Issue by iaminvictus1993** [wangeditor-team/wangEditor#1562]
自定义的table标签 在editor中不能新增 行列，都不能显示出功能框

**Comment by wangfupeng1988** [comment]
> 自定义的table标签

怎么自定义的，得具体详细说下

**Comment by rianran1993** [comment]
我读取了一个含有tabel的html页面的内容， 我把这些内容的设置到editor中，点击tabel单元格，编辑器的表格按钮没有高亮，意味着不能进行表格操作。 只有通过编辑器表格按钮创建的table才支持 表格操作，比如增删行列

**Comment by wangfupeng1988** [comment]
> 我读取了一个含有tabel的html页面的内容

把这段内容发给我，我亲自试一下。现在我这里复现不了。

**Comment by wangfupeng1988** [comment]
收到，我确认后给你回复

**Comment by wangfupeng1988** [comment]
找到原因了，是编辑器的问题。下次升级时更新，注意观察升级动态。

**Comment by rianran1993** [comment]
ok, 辛苦了

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
