### ISSUE TITLE
聊天工具条 实现样式保存，内容不需要光标选择，就可以设置菜单功能

### ISSUE THREAD

**Issue by gongyuan303** [wangeditor-team/wangEditor#1577]
功能描述：通过wangeditor实现工具条，仅使用字体、颜色、字号、加粗、斜体 五个设置功能
问题描述：1、每次发消息后清空，不能保存上次设置的内容样式。
                  2、设置内容，需要选择内容，点击设置样式功能才能生效，如何不需要选择内容，点击设置功能就能直接生效样式

**Comment by GongYuan303** [comment]
可以通过763811314@qq.com回复我，谢谢
