### ISSUE TITLE
我是用的版本是3.1.1 无法粘贴图片

### ISSUE THREAD

**Issue by chenwuwen** [wangeditor-team/wangEditor#1579]
使用3.1.1版本使用QQ截图，粘贴图片没有反应，已经配置了
 editor.customConfig.pasteIgnoreImg = false
但是没有用，但是文档中是可以粘贴图片的
![image](https://user-images.githubusercontent.com/24679387/41011716-a99a6790-6970-11e8-816c-cdcc03226f91.png)

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
