### ISSUE TITLE
请问可以支持公式编辑功能吗？

### ISSUE THREAD

**Issue by Bigpawn** [wangeditor-team/wangEditor#1580]
请问可以支持公式编辑功能吗？

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈

**Comment by wangfupeng1988** [comment]
v5 已经支持 公式 https://github.com/wangeditor-team/wangEditor-plugin-formula

v5 发布在即，v4 中不会再增加新功能了
