### ISSUE TITLE
关于onchange事件第一次监听不到选中清除文本内容

### ISSUE THREAD

**Issue by Hello-Huxu** [wangeditor-team/wangEditor#1584]
首先在文本框聚焦时是可以监听到的，但是第一次操作文本框，用鼠标全选文本内容，然后backspace清除，并没有监听到，当你输入内容之后就可以监听到了

**Comment by Hello-Huxu** [comment]
好像不能贴图？操作已说明，实在想不到其他方法可以折中达到我想要的效果，所以跑来请教请教了

**Comment by maple326** [comment]
也遇到这个问题，求助

**Comment by shangjingfei** [comment]
这个问题解决了吗

**Comment by waney** [comment]
第一次修改图片最大宽度onchange也没有监听到。

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
