### ISSUE TITLE
CSS样式是否可更改的问题

### ISSUE THREAD

**Issue by velley** [wangeditor-team/wangEditor#1586]
作者您好。我是个新人，最近在尝试自己写一个个人博客。用这个富文本编辑器遇到一个问题，就是生成好的html内容无法重新定义其CSS样式，比如字号、字体、颜色等。
由于文章会用到不同的文字样式，字体有的大有的小，这样不便于在网站首页一起展示。所以我在网站首页取到所有的文章数据时，希望将所有文章的文字设置为相同的样式（比如粗细、大小、字体需要保持一致）。
可是直接通过CSS写没有效果（加上!important语句也不行），通过js来控制也没用。。。不知道有没有解决办法

**Comment by velley** [comment]
已经解决了，简单粗暴。。直接在网页上查看元素，定位到最里面的子元素然后写个CSS样式覆盖就行了。。

**Comment by gebaiwan** [comment]
能新增个引入前端样式（文章页的CSS）的接口出来，直接渲染编辑器内部的排版样式，就好了
