### ISSUE TITLE
如何给编辑器一个初始化的值（in-vue版）

### ISSUE THREAD

**Issue by xinyiPig** [wangeditor-team/wangEditor#1587]
export default {
      name: 'editor',
      data () {
        return {
          editorContent: '欢迎使用'
        }
      },
      methods: {
        getContent: function () {
            alert(this.editorContent)
        }
      },
      mounted() {
        var editor = new E(this.$refs.editor)
        editor.customConfig.onchange = (html) => {
          this.editorContent = html
        }
        editor.create()
      }
    }

以上代码只提供了获取编辑内容以及编辑器内容发生变化时候的操作，请问您能提高一个初始化编辑器内容的方法吗，我试过了给editorContent一个值，但是不会显示出来

**Comment by xinyiPig** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/404586
文档中就写了，是我太粗心
插入 HTML editor.cmd.do('insertHTML', '<p>...</p>')

**Comment by Hchunjun** [comment]
可以看看你的的代码具体怎么实现 初始化内容的么

**Comment by xinyiPig** [comment]
![image](https://user-images.githubusercontent.com/30715127/49579010-1ea71380-f986-11e8-81a8-d0d8dec44541.png)


> 可以看看你的的代码具体怎么实现 初始化内容的么。我是通过v-model做数据绑定。可以初始化数据，但是会出现#1816 这样的问题
获取内容如下图
![image](https://user-images.githubusercontent.com/30715127/49579022-2797e500-f986-11e8-9613-faf6db2042b7.png)
插入内容如下图
![image](https://user-images.githubusercontent.com/30715127/49579098-557d2980-f986-11e8-872b-552783925996.png)
一般要根据文档来用喔，好像作者没提供v-model这种绑定，你先试试
