### ISSUE TITLE
3.1.1粘贴文本过滤样式Google无效

### ISSUE THREAD

**Issue by HanTongTong** [wangeditor-team/wangEditor#1591]
wangEditor3使用手册中“编辑器会默认过滤掉复制文本中自带的样式”：
我用的Google浏览器，复制word文档中带有颜色、粗体的文字到编辑器上，发现粘贴在编辑器的文本中还是带有颜色、粗体的样式。

**Comment by feivorid** [comment]
遇到同样的问题

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
