### ISSUE TITLE
查看源代码及代码着色功能

### ISSUE THREAD

**Issue by gebaiwan** [wangeditor-team/wangEditor#1593]
--编写查看源代码JS文件
`window.wangEditor.viewsource = {
    // editor create之后调用
    init: function(editorSelector){
        $(editorSelector + " .w-e-toolbar").append('<div class="w-e-menu" title="查看源码"><i class="_wangEditor_btn_sourceview iconfont if-code" onclick="window.wangEditor.viewsource.toggleViewsource(\'' + editorSelector + '\')"></i></div>');
        var cheight = $(editorSelector + ' .w-e-text-container').outerHeight();
        $(editorSelector + ' .w-e-text').after('<textarea id="viewSource" class="d-none" style="width:100%;height:'+cheight+'px"></textarea>');
    },
toggleViewsource: function(editorSelector){
        if($(editorSelector + ' ._wangEditor_btn_sourceview').parents('.w-e-menu').hasClass('active')){
            //代码编辑器内容同步到编辑器
            CM.save();
            var source_code = $(editorSelector + ' #viewSource').val();
            editor.txt.html(source_code);
            //销毁代码编辑器
            CM.toTextArea()
        }else{
            var source_value = editor.txt.html();
            $(editorSelector + ' #viewSource').val(source_value);
            CM = CodeMirror.fromTextArea(document.getElementById("viewSource"), {
                mode:'text/html',
                lineNumbers: true,
                theme:'monokai',
                styleActiveLine: true,
                autoCloseTags:true,
                matchBrackets: true,   // 括号匹配
                lineWrapping: true,    // 自动换行
            });
        }
        $(editorSelector + ' .w-e-text').toggleClass('d-none');
        $(editorSelector + ' ._wangEditor_btn_sourceview').parents('.w-e-menu').toggleClass('active');
    }
};`
--引用所有相关文件
css
`<link rel="stylesheet" href="{{ staticDomain().'/style/js/wangEditor-plugins/fullscreen/css.css' }}">
    <link rel="stylesheet" href="{{ staticDomain().'/style/js/wangEditor-plugins/viewsource/css.css' }}">

    <link rel="stylesheet" href="{{ staticDomain().'/style/plugins/codemirror-5.38.0/lib/codemirror.css' }}">
    <link rel="stylesheet" href="{{ staticDomain().'/style/plugins/codemirror-5.38.0/theme/monokai.css' }}">`
js
`<script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/lib/codemirror.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/mode/xml/xml.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/mode/javascript/javascript.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/mode/css/css.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/mode/htmlmixed/htmlmixed.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/addon/edit/closetag.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/addon/fold/xml-fold.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/addon/selection/active-line.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/codemirror-5.38.0/addon/display/fullscreen.js' }}"></script>
    <script src="{{ staticDomain().'/style/plugins/wangEditor-3.1.1/release/wangEditor.min.js' }}"></script>
    <script src="{{ staticDomain().'/style/js/wangEditor-plugins/fullscreen/js.js' }}"></script>
    <script src="{{ staticDomain().'/style/js/wangEditor-plugins/viewsource/js.js' }}"></script>
`
--调用编辑器
`var E = window.wangEditor;
        var editor = new E('#contentParase');
        var $content = $('#content');
        editor.customConfig.uploadImgServer = '/upload';
        editor.customConfig.showLinkImg = false;
        // 开启T|关闭F粘贴样式的过滤
        editor.customConfig.pasteFilterStyle = true;
        // 忽略粘贴内容中的图片
        editor.customConfig.pasteIgnoreImg = true;
        editor.customConfig.onchange = function (html) {
            $content.val(html);
        };
        editor.create();
        //全屏按钮
        E.fullscreen.init('#contentParase');
        //查看源码
        E.viewsource.init('#contentParase');
        // 初始化 textarea 的值
        $content.val(editor.txt.html());`

**Comment by gebaiwan** [comment]
@onaug6th 这可真是为难，上面代码已经贴的很全了啊。感觉作者大神貌似放弃了这个编辑器，我改用了TUI-EDITOR。不过上面的代码是可以用的，不然我也不会贴。

**Comment by jhjade** [comment]
已经停滞太多了，主流框架支持太弱

**Comment by greetfish** [comment]
第一部分代码里面，editor.txt.html()这个editor是从哪来的，直接就使用，让人摸不着头脑
