### ISSUE TITLE
上传图片到七牛云报400

### ISSUE THREAD

**Issue by ggbonddd** [wangeditor-team/wangEditor#1599]
上传图片到七牛云报400
![image](https://user-images.githubusercontent.com/40378757/41577261-639981ba-73be-11e8-9a4b-cc07f008522d.png)
这两个都试过,还是不行
![image](https://user-images.githubusercontent.com/40378757/41577235-45b4e310-73be-11e8-844a-08bb5582d08f.png)
config.js里面 除了Uptoken_Url不知道是啥,其他都改过了

**Comment by javed119** [comment]
uptoken_url就是你获取七牛上传token的后台地址，400错误具体要看是什么error_code,详情请参照:https://developer.qiniu.com/af/manual/1484/about-child-http-status-code-to-the-account
