### ISSUE TITLE
从word粘贴文本到编辑器中格式并没有被清除

### ISSUE THREAD

**Issue by Luqir** [wangeditor-team/wangEditor#1603]
editor.customConfig.pasteFilterStyle = false，这个设置有区别，但是区别不大，格式基本还在

**Comment by chenjibin** [comment]
从word粘贴过来的内容格式特殊，现在浏览器有右键粘贴为纯文本的功能，快捷键 Ctrl + shift + v，可以完全清除从word粘贴过来的样式

**Comment by Luqir** [comment]
好的，谢谢你

**Comment by wo-xiaoxiao** [comment]
你的问题解决了没

**Comment by wxw1314** [comment]
可以用下列代码去除掉word自带的格式
editor.customConfig.pasteTextHandle = function (content) {
        if (content === '' && !content) return '';
        var str = content;
        str = str.replace(/<xml>[\s\S]*?<\/xml>/ig, '');
        return str
      };
