### ISSUE TITLE
如果把编辑器生成标签放入em标签内部，那么复制富文本内部内容，再粘贴到富文本框中会出现神奇的问题。

### ISSUE THREAD

**Issue by lk125454242** [wangeditor-team/wangEditor#1608]
如果把编辑器生成标签放入em标签内部，那么复制富文本内部内容，再粘贴到富文本框中会出现神奇的问题。
例如：
`<em><div id="divDemo"><div></em>`
这么写的话 复制内容的时候 会把父级em 甚至更高级标签复制进来。
结果就会变成这样
![1529566318296](https://user-images.githubusercontent.com/16454221/41704233-47aaf640-7568-11e8-8ea5-fdde0cc84e80.jpg)

**Comment by J-env** [comment]
我真的不想吐槽他了，真的。无语了！
IE浏览器斜体用em，无序列表和有序列表就没有设置style样式，
（这些问题不考虑网站的重置样式吗？）

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
