### ISSUE TITLE
富文本框下划线对ios不起作用  是不是text-decoration-line: underline;兼容性不好

### ISSUE THREAD

**Issue by MsAbby** [wangeditor-team/wangEditor#1616]
富文本框下划线对ios不起作用  是不是text-decoration-line: underline;兼容性不好；

**Comment by lihuangshuaige** [comment]
下划线 是text-decoration:underline;吧

**Comment by MsAbby** [comment]
下划线是text-decoration ;  wangEditor 用的是text-decoration-line ，在ios 上不显示

**Comment by UltramanWeiLai** [comment]
目前编辑器只支持pc端版本
