### ISSUE TITLE
全屏功能怎么开启

### ISSUE THREAD

**Issue by javaWiley** [wangeditor-team/wangEditor#1617]
菜单栏上面的一些参数有没有具体一点的文档解释下

**Comment by richardmyu** [comment]
引入 wangEditor-fullscreen-plugin.css 和 wangEditor-fullscreen-plugin.js 两个文件，然后在 editor.create() 之后 创建 E.fullscreen.init('#editor') 就可以了（#editor 是之前挂载编辑器实例的元素），在菜单栏最后会出现“全屏”字样，点击就会全屏

**Comment by zazzlec** [comment]
> 引入 wangEditor-fullscreen-plugin.css 和 wangEditor-fullscreen-plugin.js 两个文件，然后在 editor.create() 之后 创建 E.fullscreen.init('#editor') 就可以了（#editor 是之前挂载编辑器实例的元素），在菜单栏最后会出现“全屏”字样，点击就会全屏

vue版本的呢？

**Comment by taosiqi** [comment]
可以看看这个  原生js的的全屏预览+全屏编辑，官方只给了一个jq的版本 https://github.com/taosiqi/wangEditor-fullscreen-preview

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
