### ISSUE TITLE
设置内容后，不能换行 enter键失去作用

### ISSUE THREAD

**Issue by wo-xiaoxiao** [wangeditor-team/wangEditor#1619]
新增的时候没问题，修改的时候给设置完值，点击回车失去作用
![default](https://user-images.githubusercontent.com/33949901/42161322-1306eb06-7e2d-11e8-8067-922b58076ef2.png)
![default](https://user-images.githubusercontent.com/33949901/42161333-23a729da-7e2d-11e8-8541-b981a442eabd.png)

**Comment by javed119** [comment]
我之前遇到这个问题是由于将编辑器放在了form表单中，你可以排除一下是不是这个问题。

**Comment by wo-xiaoxiao** [comment]
我的没有放在form表单里面，但是就是感觉修改的时候掉了次接口的问题，后面把反显接口放在node端掉了就好了，就是不知奥为啥

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
