### ISSUE TITLE
自定义上传图片事件

### ISSUE THREAD

**Issue by shenwl** [wangeditor-team/wangEditor#1625]
项目用到OSS上传，‘自定义上传图片事件’的文档在   上传图片-> 上传图片到服务器下  ，建议可以单独提出来放到 ‘上传到七牛云存储’ 同一级，不知道是不是我一个人找了很久才找到

**Comment by pass13046132** [comment]
你是怎么将图片上传阿里OSS的呢？求解

**Comment by shenwl** [comment]
自定义上传图片是完全自由的，在editor.customConfig.customUploadImg= function (files, insert){}里拿到file，用自己封装的oss_uploader上传，然后在上传成功的回调里insert图片到编辑器

**Comment by banboovyue** [comment]
楼上说的很清楚
