### ISSUE TITLE
粘贴网页内容时图片转存

### ISSUE THREAD

**Issue by ahkimkoo** [wangeditor-team/wangEditor#1627]
想实现粘贴网页内容时图片转存，或者是转为base64 datauri的格式，不知道从何入手，能给一些提示吗？

**Comment by 44886** [comment]
用 editor.customConfig.customUploadImg = function (files, insert) {}

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
