### ISSUE TITLE
列表设置标题后回车退出列表，新建内容无法回到正文

### ISSUE THREAD

**Issue by irokay** [wangeditor-team/wangEditor#1628]
![1531052797570](https://user-images.githubusercontent.com/18734925/42419800-5b70cbf8-82ee-11e8-8ba7-5cb6d74a0f9c.jpg)
操作步骤：
1. 选择有序或无序列表，输入文字
2.选中列表item，选择标题，比如H1，加粗
3.回车（此时进入第二条），再次回车，退出列表（从dom结构上看，其实没有跳出列表结构）
4.书写正文，发现正文文字依然是加大加粗的
5.选中正文内容，再次选择【标题】——“正文”，发现无效（原因也是上述3条中讲到的，没有跳出列表结构）。
除非将以上列表删除，方可解决问题。
希望作者修复。
同时感谢作者开发与分享如此精美的富文本插件！

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
