### ISSUE TITLE
微信小程序富文本解析wxParse插件解析出来的字符串有乱码

### ISSUE THREAD

**Issue by zcSkr** [wangeditor-team/wangEditor#1630]
bug： 若从word/wps文档复制张贴的文本，wxParse解析节点文本有乱码导致不能正常显示

微信小程序目前只有一个wxParse插件解析富文本比较主流好用，由于wangEditor从word/wps粘贴过来的富文本内容行内标签多了一些mso-开头的属性，导致解析出来的节点文本不符合html标签格式，不能正常显示。故每次做小程序相关的后台时只能选择其他编辑器，但是喜欢wangEditor的编辑风格和轻量便捷，希望作者大大有空研究一下。

**Comment by gedongdong** [comment]
同求，wxParse解析出来的样式有问题

**Comment by yunnex-xw** [comment]
是不是 生成一些奇怪的标签或字符串 

下面这个类型的：
<h2 id="activity-name" helvetica="" neue',="" 'pingfang="" sc',="" 'hiragino="" sans="" gb',="" 'microsoft="" yahei="" ui',="" yahei',="" arial,="" sans-serif;="" font-style:="" normal;="" font-variant:="" letter-spacing:="" 0.544000029563904px;="" orphans:="" auto;="" text-align:="" start;="" text-indent:="" 0px;="" text-transform:="" none;="" white-space:="" widows:="" 1;="" word-spacing:="" -webkit-text-stroke-width:=

**Comment by yunnex-xw** [comment]
解决了没 大佬 求教啊

**Comment by zcSkr** [comment]
完全放弃了，不用wangEditor了。

**Comment by yunnex-xw** [comment]
> 完全放弃了，不用wangEditor了。

那用的是哪个富文本

**Comment by zcSkr** [comment]
之前后台用原生写 就用百度编辑器。后来用react，antd全家桶。就用
![image](https://user-images.githubusercontent.com/30515821/50271225-16af9f00-046f-11e9-951c-acfd7f3155bd.png)

**Comment by Nevermore009** [comment]
新出来一个获取富文本Json的，不知道能不能解决这个问题，大家可以 试试

**Comment by LayneYangBlack** [comment]
vue的改用什么富文本编辑器了？

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
