### ISSUE TITLE
开启粘贴样式的过滤无效

### ISSUE THREAD

**Issue by wcjinzita** [wangeditor-team/wangEditor#1636]
关闭粘贴样式的过滤
当从其他网页复制文本内容粘贴到编辑器中，编辑器会默认过滤掉复制文本中自带的样式，目的是让粘贴后的文本变得更加简洁和轻量。用户可通过editor.customConfig.pasteFilterStyle = false手动关闭掉粘贴样式的过滤。
但是，现在pasteFilterStyle 默认是true的时候，好像不起作用呢，粘贴进去的文字，还是自带样式，特别是从word里面复制的。求解答？

**Comment by phansion** [comment]
同问

**Comment by caoyuegang** [comment]
我也感觉是针对word要自己写过滤

**Comment by pyj63** [comment]
同问

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
