### ISSUE TITLE
关于编辑区英文和数字不能自动换行问题

### ISSUE THREAD

**Issue by 1127426159** [wangeditor-team/wangEditor#1638]
如下图插入中文可以正确换行，但是英文字母和数字不行
![image](https://user-images.githubusercontent.com/35327252/42732455-6b0610ee-8854-11e8-8963-c8954af905ab.png)
![image](https://user-images.githubusercontent.com/35327252/42732468-c18ca20c-8854-11e8-8052-2a1e0c200989.png)
![image](https://user-images.githubusercontent.com/35327252/42732469-cb5f6c4c-8854-11e8-917d-8ddc8d7bbe6b.png)

**Comment by SeLiNnnn** [comment]
.....请问这个问题后来怎么解决的呢
