### ISSUE TITLE
全选复制粘贴纯快捷键操作会有选中文字不被替换的问题

### ISSUE THREAD

**Issue by ljybill** [wangeditor-team/wangEditor#1644]
具体步骤是按住Ctrl/Command，然后按 A 、 C 、 V 键可复现问题
我查到的原因可能是 监听keyup事件 如果是组合键 比如 Command A 松手A的时候并不会触发，只有全松手才触发，所以并没有更新选区。

**Comment by ycgiser** [comment]
全选是经常遇到这个问题，用鼠标全选然后粘贴替换基本连三次就会遇到一次

**Comment by ljybill** [comment]
我修改源码解决了，
![image](https://user-images.githubusercontent.com/31462342/49062287-8191ff80-f24e-11e8-9a66-f2b38bae0d0b.png)
粘贴前先保存下选区

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
