### ISSUE TITLE
关于标签语义化的问题

### ISSUE THREAD

**Issue by Beats0** [wangeditor-team/wangEditor#1648]
例如加粗B,斜线I等操作，wangEditor的做法是用span加style样式
```html
<span style="font-weight: bold; font-style: italic; text-decoration-line: underline;"></span>
```
但我们想用的是
```html
<b></b>
<i></i>
<u></u>
```
等语义化的标签
#### style的不好之处
js-xss对style过滤只有开启和关闭两个操作

最难受的情况就是：
1. 开启style过滤，那么结果就是含有style的标签全部失效

2. 不开起style过滤，此时如果用户在控制台内对内容进行其他style样式修改，列如添加一个font-size:50px,那么结果就是按原文输出

issues同#1535 

所以希望能以开启标签语义化的形式解决

**Comment by UltramanWeiLai** [comment]
![Uploading image.png…]()
