### ISSUE TITLE
粘贴时候使用的正则表达式，建议调整如下

### ISSUE THREAD

**Issue by 315024900** [wangeditor-team/wangEditor#1657]
![image](https://user-images.githubusercontent.com/16681725/43116586-16e3dc42-8f3b-11e8-96cc-67f291095042.png)

### 调整替换成如下两行代码
    pasteHtml = pasteHtml.replace(/\s?data-.+?=(').+?(')/igm, '')
    pasteHtml = pasteHtml.replace(/\s?data-.+?=(").+?(")/igm, '')

### 因为原有的正则表达式会遇到这样子的情况
![image](https://user-images.githubusercontent.com/16681725/43116407-230a2194-8f3a-11e8-966a-106975c33fe3.png)
正则匹配完之后，变成了
![image](https://user-images.githubusercontent.com/16681725/43116430-4cd6ac86-8f3a-11e8-8f03-5c54a0c90270.png)

### 用文字描述就是
`<a data-click="{'rsv_snapshot':'1'}" target="_blank" class="m">百度快照</a>`

用原有的粘贴所用的正则表达式，转换就变成了
`<arsv_snapshot':'1'}"  target="_blank">百度快照</a>`

### 同理，其他类似的粘贴，也有这样的问题

**Comment by UltramanWeiLai** [comment]
感谢反馈
