### ISSUE TITLE
wangEditor可以上传图片至阿里OSS存储吗？

### ISSUE THREAD

**Issue by pass13046132** [wangeditor-team/wangEditor#1658]

**Comment by SummerSMJ** [comment]
你可以先写一个接口来接收富文本上传的图片  在接口里面上传到阿里的OSS

**Comment by pass13046132** [comment]
就不是太懂 怎么接收富文本上传的图片，这个应该怎么写

**Comment by ke-ke** [comment]
editor.customConfig.customUploadImg = function(files, insert) {
				var formdata1 = new FormData()
				formdata1.append('file', files[0])
				$.ajax({
					url: '/uploadFile',//上传图片的接口
					data: formdata1,
					processData: false,
					contentType: false,
					type: 'post',
					success: function(response) {
						if(response.success) {
							insert(response.data.url)
						} else {
							alert('上传图片失败')
						}
					},
					error: function() {
						alert('上传图片失败')
					}
				})
			}

**Comment by SummerSMJ** [comment]
你可以直接  配置一个图片接口  像这样:

editor = new E(elem, elem1);
// 使用 onchange 函数监听内容的变化，并实时更新到 state 中
editor.customConfig.onchange = html => {
    this.setState({
        editorContent: html
    })
    sessionStorage.details = html;
};
editor.customConfig.uploadImgServer = url + "/fileUpload/editor",  // 上传图片到服务器
    editor.create();


ke-ke <notifications@github.com> 于2018年8月1日周三 下午5:10写道：
