### ISSUE TITLE
中文输入法, 在输入法联想的结果中用鼠标点击某个文字, 内容出现在编辑器中, 但是没有触发onchange方法

### ISSUE THREAD

**Issue by lsh6372** [wangeditor-team/wangEditor#1660]
中午输入法, 在出现输入法联想的结果后
1.用鼠标点击某个文字, 内容出现在编辑器中, 但是没有触发onchange方法
2.直接按回车,内容出现在编辑器中, 但没有触发onchange方法

**Comment by wangxv** [comment]
[https://github.com/wangfupeng1988/wangEditor/pull/1772](url)

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
