### ISSUE TITLE
如果我想自己添加一个功能，自己改源码的思路是什么？

### ISSUE THREAD

**Issue by Yos5ef** [wangeditor-team/wangEditor#1663]
或许这个问题，闻起来比较愚蠢，但是业务需求用到上标和下标，wangEditor暂时没有这个功能，但是百度的又没有wangEditor这样轻量级，所以想自己添加一个功能，所以想问一下，又没有大佬可以指点一下，改源码的思路。

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
