### ISSUE TITLE
使用pasteTextHandle的问题

### ISSUE THREAD

**Issue by ydostyle** [wangeditor-team/wangEditor#1671]
使用了pasteTextHandle过滤元素的一些样式之后，再使用菜单栏设置标题，可以设置h1标签，但是会多个span标签，还会带上font-size，这样子，不管h1-h5都是一样的字体了，这个怎么解决

**Comment by IVANLEE99** [comment]
无法异步
pasteTextHandle

**Comment by ZhangShuangV** [comment]
怎么才能异步呀，网络图片我会转存到七牛云上，但是无法异步导致，复制后显示[object Promise]

**Comment by codedart2018** [comment]
同样异步解析出来是object promise.我也遇到这个问题了
