### ISSUE TITLE
在编辑页里的一个页面里同时存在多个编辑器时，后台返回的值不能分别为这些个编辑器赋值

### ISSUE THREAD

**Issue by HYqwf** [wangeditor-team/wangEditor#1672]
![image](https://user-images.githubusercontent.com/12951637/43496708-6cfd4df2-9571-11e8-9d59-11b86ee4021d.png)

**Comment by HYqwf** [comment]
已解决，通过给editor设置class,find可编辑区域的class,在设置text

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
