### ISSUE TITLE
我希望wangEditor能有这两个改进？

### ISSUE THREAD

**Issue by meiyouzhanghao** [wangeditor-team/wangEditor#1676]
首先，不可否认wangeditor比较好看，而且是基于DIV模式开发，不是Iframe，这个编辑器比百度editor编辑器好用，我希望能够完善两个功能（个人建议）：
第一个：wangEditor能够有查看源代码的菜单配置，这个配置在老版本上是有的，但是在新的版本里面好像是取消了，我看菜单配置是没有看到这一项，需要单独配置才有，我觉得可以在菜单里面加入这个功能，不要单独拿出来配置。
第二个：加粗功能，我今天来看了下，加粗功能竟然是用< span style="font-weight: bold;" >来加粗的，我的天，我目前在用的版本，加粗功能是用< b >标签进行加粗。希望加粗的这个功能使用< strong >标签来做，这样会更好。

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
