### ISSUE TITLE
1. 使用editor的撤销按钮，会撤销页面表单的内容。2.会影响浮动在编辑器上层的组件

### ISSUE THREAD

**Issue by sevilen** [wangeditor-team/wangEditor#1683]
![image](https://user-images.githubusercontent.com/30746521/43811260-37d6054c-9aee-11e8-9152-ed83aaa24a7c.png)

**Comment by J-env** [comment]
会撤销页面表单的内容，我也遇到了。
我的解决办法： 把编辑器代码及文件都放在 iframe中， @ReevesOvO

**Comment by UltramanWeiLai** [comment]
撤销以修复
会影响浮动在编辑器上层的组件，可以设置 菜单的 z-index 来调节
V4 即将发布，已解决该问题，感谢反馈
