### ISSUE TITLE
JSON格式的内容怎么正常显示

### ISSUE THREAD

**Issue by wzbbdsj** [wangeditor-team/wangEditor#1684]
var json = editor.txt.getJSON()  // 获取 JSON 格式的内容
 var jsonStr = JSON.stringify(json)
获取的内容存到数据库中，读取的时候怎么初始化内容呢？

**Comment by IVANLEE99** [comment]
递归set？

**Comment by 1039919361** [comment]
有没有好的解决办法？现在json格式的内容直接展示在富文本上边 有没有知道的？？？

**Comment by 1039919361** [comment]
让他展示在框框里面也可以啊！

**Comment by UltramanWeiLai** [comment]
其实循环json生成dom片段是一件很容易的事情
已记录该问题，会安排在 V4 版本中解决，感谢反馈
