### ISSUE TITLE
QQ截图粘帖图片，IE11自动转成base64编码，我想使用图片上传的方式

### ISSUE THREAD

**Issue by Dongshaojie** [wangeditor-team/wangEditor#1685]
![image](https://user-images.githubusercontent.com/2655542/43873501-54ef46ea-9bb9-11e8-8e35-57ac84791d5e.png)
1e11， QQ截图粘帖直接转成了base64编码，Chrome下是调用的图片上传接口，怎么让ie也使用图片上传的方式啊？？？

**Comment by Dongshaojie** [comment]
![je588p558 14g968 rx5o5](https://user-images.githubusercontent.com/2655542/43874275-78817250-9bbd-11e8-8e53-136655e017f2.png)
这是chrome下的效果，这才是我想要的，怎么禁止ie下自动base64转码，也使用图片上传的方式？？？

**Comment by Dongshaojie** [comment]
@wangfupeng1988

**Comment by windyzoe** [comment]
相同的问题,求解决,兼容ie11就好啊

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
