### ISSUE TITLE
黑色背景下 插入代码框无法看到输入的代码

### ISSUE THREAD

**Issue by aloneforyou** [wangeditor-team/wangEditor#1686]
我使用的amaze ui admin 模板，使用黑色背景下，在富文本编辑器中插入代码输入框中无法看到插入的代码，但是点击插入后可以显示在富文本编辑框

**Comment by aloneforyou** [comment]
![image](https://user-images.githubusercontent.com/27256289/43886845-984f7532-9bef-11e8-8f77-dda305b06905.png)

其实代码已经写进去了，但就是看不到
![image](https://user-images.githubusercontent.com/27256289/43886860-9e87bb9e-9bef-11e8-9a18-06c825eb0638.png)

**Comment by windExplorer** [comment]
try change your color of fonts or dom's background-color

**Comment by UltramanWeiLai** [comment]
你这个确定不是吧字体颜色改成了白色？

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
