### ISSUE TITLE
文字对齐没有“两端对齐”功能

### ISSUE THREAD

**Issue by cxasm** [wangeditor-team/wangEditor#1689]
作者：快点加入 文字两端对齐功能吧。目前只有左、中、右三种对齐方式。 由于没有该功能，文字总是左右缺一点，看起来很乱。其他富文本编辑器都有 两端对齐，快快加入该功能。

我的网站使用了你们的插件，希望能够快点加入该功能。

**Comment by UltramanWeiLai** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
