### ISSUE TITLE
内容被转义，怎么解决？

### ISSUE THREAD

**Issue by fallsea** [wangeditor-team/wangEditor#1690]
使用editor.txt.html() 获取编辑器内容，特殊标签自动转义了，有没有方法不做任何转义处理。

**Comment by david-yang** [comment]
我也遇到这个问题，section标签就被转义了，有什么方法解决吗？

**Comment by fallsea** [comment]
@david-yang 没解决，换其他编辑器了

**Comment by BloodUnicorn** [comment]
哪位大神解决了？请赐教
