### ISSUE TITLE
火狐浏览器下，输入阿拉伯数字，不换行，出现横向滚动条

### ISSUE THREAD

**Issue by zhaoli-Git** [wangeditor-team/wangEditor#1693]
![tim 20180815113808](https://user-images.githubusercontent.com/24937425/44130455-4c1b3eb8-a080-11e8-8b51-c48edb12ae89.png)

**Comment by hanzhongxulovefanyike** [comment]
我也遇到了  然后暂时用css控制了

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
