### ISSUE TITLE
提交内容格式问题，出现了div，而不是p

### ISSUE THREAD

**Issue by zeda668** [wangeditor-team/wangEditor#1694]
编辑多行内容，比如3行四行左右，然后选中，按删除键删掉，会小概率出现格式问题，导致提交的内容不是<p>，而是<div>：如下图
![default](https://user-images.githubusercontent.com/42436189/44201053-d8ca0380-a17a-11e8-97ca-4bdc4e259732.png)

**Comment by zeda668** [comment]
而且当文本格式变成这样之后，每一次按换行，会多生成一次<p><br></p>

**Comment by zeda668** [comment]
会多生成一次<p  ><br    > </p     >

**Comment by zeda668** [comment]
会多生成一次
![default](https://user-images.githubusercontent.com/42436189/44201338-9523c980-a17b-11e8-8642-2faaf93bd9ad.png)

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
