### ISSUE TITLE
没有滚动条的时候，滚动条的背景色还在

### ISSUE THREAD

**Issue by zcoolbb** [wangeditor-team/wangEditor#1696]
没有滚动条的时候，滚动条的背景色还在,当前版本有办法去除吗？

**Comment by zcoolbb** [comment]
改变默认的样式即可：
.w-e-text {
        overflow-y: auto;
}
告辞~~

**Comment by levinit** [comment]
我也发现了。
不过要就上important。
overflow-y: auto !important;

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
