### ISSUE TITLE
editor的菜单点击无效

### ISSUE THREAD

**Issue by HYqwf** [wangeditor-team/wangEditor#1697]
editor的菜单点击无效，审查元素好像菜单里只有图标，其它选项没有。审查元素查看菜单也是里面没有内容

![qq 20180817162340](https://user-images.githubusercontent.com/12951637/44255883-0c1f9780-a23a-11e8-8e34-a40b33dfbcfe.png)
另一个页面的编辑器就是正常的。
![qq 20180817171948](https://user-images.githubusercontent.com/12951637/44258612-fe6e1000-a241-11e8-92d8-f858a91a80e3.png)

**Comment by HYqwf** [comment]
我是写在弹层里，移到页面就没问题

**Comment by HL1998** [comment]
请问楼主解决了嘛，我也遇见同样的问题

**Comment by moonlight418** [comment]
> 请问楼主解决了嘛，我也遇见同样的问题



> 请问楼主解决了嘛，我也遇见同样的问题
