### ISSUE TITLE
视频显示问题

### ISSUE THREAD

**Issue by xixilalaha** [wangeditor-team/wangEditor#1698]
v2版本上传视频时可以修改视频显示的大小，但是V3版本里就没有看到了，是这个功能被删除了么，官方文档里也没有看到相关的信息

**Comment by itshizhan** [comment]
最好自定义一个按钮，上传本地视频或网络视频后，直接插入视频的html，这样可以随意初始化大小，修改大小

**Comment by xixilalaha** [comment]
好的，谢谢了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: itshizhan <notifications@github.com>
发送时间: Tuesday, September 11, 2018 11:52:14 AM
收件人: wangfupeng1988/wangEditor
抄送: xixilalaha; Author
主题: Re: [wangfupeng1988/wangEditor] 视频显示问题 (#1698)


最好自定义一个按钮，上传本地视频或网络视频后，直接插入视频的html，这样可以随意初始化大小，修改大小

―
