### ISSUE TITLE
非空判断的问题

### ISSUE THREAD

**Issue by He-Polaris** [wangeditor-team/wangEditor#1699]
你好,请问  我还要怎么样 才能判断输入的内容是不是空呢 ? 比如 我敲几个回车 会出现几个<p></p>但是我并不需要这些空格 ,请指教一下怎样判断

**Comment by HYqwf** [comment]
获取text()，不可以么

**Comment by He-Polaris** [comment]
谢谢回复.  如果我用.text()的话 取到的就不是富文本了  我想要去掉所有空格

**Comment by HYqwf** [comment]
获取富文本之后再自己正则去除全局空格会不会好些

**Comment by windExplorer** [comment]
正则处理一下

**Comment by He-Polaris** [comment]
好的解决了,谢谢各位老板

**Comment by MyGithub-Ljc** [comment]
@He-Polaris 问下 怎么解决的呢
