### ISSUE TITLE
一个很严重的bug

### ISSUE THREAD

**Issue by zhongziqi** [wangeditor-team/wangEditor#1701]
从word文档下copy进来的文字放到编辑器里面（苹果和window电脑下又会有差异），后端接受的是凌乱的样式
![image](https://user-images.githubusercontent.com/23629116/44334036-0d9fc880-a4a3-11e8-8fba-d46d1791b3be.png)

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
