### ISSUE TITLE
样式BUG

### ISSUE THREAD

**Issue by feixierman** [wangeditor-team/wangEditor#1703]
1. 当我对一段文字加了字体大小和颜色的样式后点设置为无序获取有序列表的时候  添加在文字上面的大小和颜色的样式被重置为默认的大小和样式了
![image](https://user-images.githubusercontent.com/42571772/44394213-43a78000-a569-11e8-96df-c17606f33573.png)
![image](https://user-images.githubusercontent.com/42571772/44394253-591caa00-a569-11e8-9b4c-387d7cec520a.png)
![image](https://user-images.githubusercontent.com/42571772/44394271-6174e500-a569-11e8-9b40-f1fa8f407d37.png)

2字体配置无效
![image](https://user-images.githubusercontent.com/42571772/44394294-70f42e00-a569-11e8-8fa2-e68fc76ab321.png)
![image](https://user-images.githubusercontent.com/42571772/44394311-79e4ff80-a569-11e8-8aa3-29d788c11b74.png)

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
