### ISSUE TITLE
建议添加销毁实例、控制光标方法

### ISSUE THREAD

**Issue by dustdu** [wangeditor-team/wangEditor#1704]
我暂时是在实例化之前将菜单和编辑两个盒子移除。还有控制光标位置，自己写的。建议添加方法

**Comment by leizhongli** [comment]
请问你是怎么控制光标位置的？

**Comment by dustdu** [comment]
> 请问你是怎么控制光标位置的？

const selection = window.getSelection()
const editorText = this.$refs.editor.querySelector('.w-e-text')
editorText .focus()
selection.selectAllChildren(editorText )
selection.collapseToStart()

我是使用 Selectio 这个API控制的

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
