### ISSUE TITLE
2个编辑器上下距离太近会导致样式问题

### ISSUE THREAD

**Issue by AlexStacker** [wangeditor-team/wangEditor#1709]
如图所示:
![image](https://user-images.githubusercontent.com/7822744/44563460-f86fb600-a790-11e8-8fe2-1ae1e8e867c1.png)
实际使用中需要将2个编辑的高度调整很小，但是上传图片的弹出框距离太近导致样式重叠且无法通过改变`z-index`修改。

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
--
