### ISSUE TITLE
输入内容不能删除

### ISSUE THREAD

**Issue by liuyuntian** [wangeditor-team/wangEditor#1710]
用v-model 绑定数据的情况下：
在编辑器中随便输入一个字或者一个字加一个空格，按backspace删除，就会发现第一个字删除不掉。
不用v-model不会有问题

**Comment by yangyingchun666** [comment]
同问，不能使用backspace键删除

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
--
