### ISSUE TITLE
markdown富文本兼容参考语雀

### ISSUE THREAD

**Issue by excxapp** [wangeditor-team/wangEditor#1713]
这个可以参考[语雀](https://www.yuque.com/)
的解决方案，可以看到编辑器都是富文本的，但是编辑出来看源码兼容markdown的格式

**Comment by mu-yu** [comment]
再加一个结合 **富文本** 和 **markdown** 的例子：[typora](https://typora.io/)，希望能够支持

**Comment by mu-yu** [comment]
还有之前有人提起过的 [pen](https://github.com/sofish/pen)

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈

**Comment by wangfupeng1988** [comment]
markdown 插件已经开发完了 https://github.com/wangeditor-team/wangEditor-plugin-md

不过只能用于 [v5](https://www.wangeditor.com/v5/) 。v5 近期会正式发布，v4 不再做功能升级了。
