### ISSUE TITLE
请问编辑器是否可以增加一个打印按钮

### ISSUE THREAD

**Issue by jakietwo** [wangeditor-team/wangEditor#1717]
最近业务需求需要打印编辑器里的文档和图片 ，自己使用js 实现的时候 滚动条不能隐藏，貌似使用
`-webkit-scrollbar: {
display: none
}`
是没有作用的 所以想问下作者 打印如何实现比较好

**Comment by itshizhan** [comment]
打印不是系统直接有吗，你是先增加一个按钮？点击打印，那不就是预览功能吗

**Comment by jakietwo** [comment]
> 打印不是系统直接有吗，你是先增加一个按钮？点击打印，那不就是预览功能吗

不是这个意思呢 ，是想打印编辑器里面的内容，如果你用浏览器自带的打印 ，格式，内容都不好控制呢

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
