### ISSUE TITLE
base64图片不显示

### ISSUE THREAD

**Issue by wwwqqq566** [wangeditor-team/wangEditor#1721]
![image](https://user-images.githubusercontent.com/18671900/45281378-39dec000-b50a-11e8-9fc7-bbdef7551457.png)
这么设置了只有，上传图片却不显示

**Comment by wwwqqq566** [comment]
发现如果鼠标不点一下div框，直接上来就上传图片的话，是有这个问题的，不知是否有聚焦这个功能。

**Comment by wwwqqq566** [comment]
找到了聚焦

**Comment by Yannanna0920** [comment]
在不在 想问下你初始化是在componentDidMount里面吗

**Comment by rogueRabbit** [comment]
@wwwqqq566 请问下怎么找到聚焦的？

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
