### ISSUE TITLE
建议增加服务器图片浏览和视频上传

### ISSUE THREAD

**Issue by qiujy** [wangeditor-team/wangEditor#1726]
体验了一下，确实很不错，**小而美**。另外提几点建议：
1. 增加服务器的图片浏览插入功能。这样能重用服务器端的图片，类似微信公众号后台编辑。
2. 增加视频的上传和服务器端浏览插入功能。现在短视频这么火，这也算是刚需了吧。
3. vue版本是否有计划开发。
4. 可以参考下[froala-editor](https://github.com/froala/wysiwyg-editor)的一些功能，感觉这个很强大。作者完善下功能，收点费用相信大家也是能承受的。

期望挻多的，有点过份了。希望作者多包涵。

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
