### ISSUE TITLE
图片上传的疑惑[Django]

### ISSUE THREAD

**Issue by Lion-Li** [wangeditor-team/wangEditor#1735]
var file = request.files['wangEditorH5File']; // 获取 h5 方式上传的文件
var file = request.files['wangEditorFormFile']; // 获取 form 方式上传的文件
var file = request.files['wangEditorPasteFile']; // 获取粘贴截图 方式上传的文件
var file = request.files['wangEditorDragFile']; // 获取拖拽上传的文件
这四个四段在Django的后台中取出都为None.

这是我在View中设置的视图
class UploadImage(LoginRequiredMixin, View):
    """图片上传"""
    def post(self, request):
        image_name = request.FILES.get('wangEditorDragFile')
        print(image_name)
        image = Image.objects.create(image=image_name)
        image.save()
        json = {
            "errno": 0,
            "data": image.image,
        }
        return HttpResponse(json)
求解

**Comment by HEYsir** [comment]
请教，你是怎么在django中集成进这个编辑器的，我使用kindeditor的方式不成功，但kindeditor没有问题

**Comment by Lion-Li** [comment]
> 请教，你是怎么在django中集成进这个编辑器的，我使用kindeditor的方式不成功，但kindeditor没有问题

我是类似于知乎那样的用法.

**Comment by Lion-Li** [comment]
@HEYsir 
// 设定图片传输的key值
editor.customConfig.uploadFileName = 'Image';

var csrftoken = Cookies.get('csrftoken');  // 从Cookie中取到csrftoken
// 头部添加csrftoken
editor.customConfig.uploadImgHeaders = {
    'X-CSRFToken': csrftoken,
};
根据文档在配置文件中加入这两部,解决了django图片上传的问题.

**Comment by nianqingying** [comment]
> > 请教，你是怎么在django中集成进这个编辑器的，我使用kindeditor的方式不成功，但kindeditor没有问题
> 
> 我是类似于知乎那样的用法.

请教，请问有知乎用法的教程吗？谢谢.
