### ISSUE TITLE
wangEditor3 不能粘贴截图

### ISSUE THREAD

**Issue by constraint** [wangeditor-team/wangEditor#1739]
使用的npm install wangeditor ，不能黏贴截图。 ctrl v不行。
但是官网上的展示是可以的，官网的demo和github上不是一个版本吗？

**Comment by z767900438** [comment]
可以粘贴的，要配置好后端

**Comment by guoxiaolong1990** [comment]
主要做前端，后端不熟。碰到同样问题。是通过自定义上传图片的
![image](https://user-images.githubusercontent.com/23189956/46134097-aaa90a80-c274-11e8-8098-c3bdaa5ddec1.png)
可以简单描述一下后端的配置吗？
