### ISSUE TITLE
关于编辑器 改善想法（意见）

### ISSUE THREAD

**Issue by peacexie** [wangeditor-team/wangEditor#1740]
### 关于编辑器 改善想法（意见）

我是就喜欢它的小巧！所以才用尽心思，想自己的需求…

* v3 版本的菜单不支持换行折叠了（因为换行之后菜单栏是在太难看）
  - 这个还是可选择好把，最好参考一下分组，同一分组内不换行；
  - 配置编辑器的工具栏，其中"-"表示换行，"|"表示分隔符:   
   http://kindeditor.net/doc3.php?cmd=config

* 全屏 & 预览 & 查看源码
  - 目前是写了一个插件，
  - 看了一下代码，其实也没几行代码；是否考虑直接集成进去
  - 是否把功能越加越多，到时候就臃肿了？

* 增加语言包
  - 如果考虑国际化，需要语言包的。

* 字体/css文件 纠结
  - 目前是全部放到：js一个文件里面；是否考虑分开文件？
  - 从某些方面维护，分开是更好维护，比如我增加一个分页符号，需要不同样式，去改js文件总觉得不好？
  - 个人也比较纠结...

**Comment by a835100635** [comment]
v4已记录，会考虑增加
--
