### ISSUE TITLE
如何处理将表格粘贴进富文本编辑器以后生成的一些自定义标签

### ISSUE THREAD

**Issue by powerProgrammerMa** [wangeditor-team/wangEditor#1743]
在某些地方例如outlook或者word里面复制一些表格到编辑器，拿出编辑器的内容发现有很多自定义标签，由于内容我还要将他用邮件发出去，但是邮件不认识这些自定义的标签，所以会导致解析错误。有没有办法过滤掉这些标签或者其他方法

**Comment by czlzy** [comment]
有什么好的解决方案吗？
