### ISSUE TITLE
急急急！react中富文本要实现编辑和修改功能  修改的时候数据还原问题！

### ISSUE THREAD

**Issue by ghost** [wangeditor-team/wangEditor#1747]
第一个问题：因为初始化这个编辑器是在componentDidMount里面 但是想要修改编辑的时候  后台返回给我的值只能在componentWillReceiveProps中去获取  而且还原值需要 editor.txt.html(modifyList?modifyList.editorContent:this.state.editorContent); 这个editorContent就是新建的时候的值  另一个是修改的值  返回的是新建时富文本的html 包括里面有base64格式的图片  我还原的时候 还是html字符串 并不是新建时的样子  
第二个问题：我在文件夹复制图片 在富文本中粘贴显示没有粘贴内容  在聊天对话中截图去复制  粘贴过去的图片 显示的是不能加载出来的图片 why????  求大神指点！谢谢！

**Comment by zooeyHuang** [comment]
第一个问题我也遇到了  就相当于你的编辑器的数据有两个来源  编辑的时候是后台返回给你的   新建的时候是空的  如果你用同一个编辑框  那么你要保证 你编辑器的初始化数据只有一个来源
