### ISSUE TITLE
图片上传后插入内容的img标签未闭合

### ISSUE THREAD

**Issue by powerProgrammerMa** [wangeditor-team/wangEditor#1750]
插入一张图片之后发现内容中img没有闭合 我手动添加闭合之后富文本直接给忽略掉了。。

**Comment by baocang** [comment]
@powerProgrammerMa  `img` 标签在HTML5里面不需要闭合，这不是一个BUG，还是关闭了算了。

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈”
