### ISSUE TITLE
示例demo无法从本地上传图片

### ISSUE THREAD

**Issue by Erchoc** [wangeditor-team/wangEditor#1752]
3000端口下图片上传只提供了网络图片地址，没提供类似官网的本地图片上传的demo？

**Comment by yoyolikeyou** [comment]
下面两个配置，使用其中一个即可显示“上传图片”的tab。但是两者不要同时使用！！！
    // editor.customConfig.uploadImgShowBase64 = true   // 使用 base64 保存图片
    // editor.customConfig.uploadImgServer = '/upload'  // 上传图片到服务器

**Comment by yoyolikeyou** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335780
 下面两个配置，使用其中一个即可显示“上传图片”的tab。但是两者不要同时使用！！！
    // editor.customConfig.uploadImgShowBase64 = true   // 使用 base64 保存图片
    // editor.customConfig.uploadImgServer = '/upload'  // 上传图片到服务器
