### ISSUE TITLE
如何在上传之前先请求从后台取到oss凭证，再上传至阿里云服务器，跪求解决办法~~

### ISSUE THREAD

**Issue by 404cat** [wangeditor-team/wangEditor#1755]
问题描述：
业务需要上传之前从后台获取oss凭证，请求的参数为文件名，然后获取到文件名后再发送到阿里云的地址。
因为请求是异步的，所以现在是在后台的参数返回之前图片就上传了，没有携带oss凭证，所以上传失败了。

> `    this.editor.customConfig.uploadImgHooks = {
        before: function(xhr, editor, files) {
            let param = {
              name: files[0].name,
              type: 1
            };
            return that.$api.common.getOSSUploadPolicy(param).then(res => {
              console.log(res);
              const {
                policy,
                oss_accesskey_id,
                callback,
                signature,
                expire,
                host,
                filename,
                dir
              } = res.data.data;
              that.editor.customConfig.uploadImgParams = {
                host,
                key: (dir ? dir + "/" : "") + filename,
                policy: policy,
                OSSAccessKeyId: oss_accesskey_id,
                success_action_status: "200", //让服务端返回200,不然，默认会返回204
                callback: callback,
                signature: signature
              };
              console.log(that.editor.customConfig.uploadImgParams);
            

> });`

我现在是在uploadImgHooks的before钩子中去发送请求获取oss凭证。但是在凭证返回之前上传已经被触发
导致上传至阿里云的数据都为空。
![image](https://user-images.githubusercontent.com/34706182/47168825-7b962e00-d334-11e8-84a4-a8ce386fbcb0.png)

如果哪位大佬知道解决办法的话，小弟跪求帮忙~~

**Comment by baocang** [comment]
upload-img.js 里面这样写的：
` // hook - before
            if (hooks.before && typeof hooks.before === 'function') {
                const beforeResult = hooks.before(xhr, editor, resultFiles)
                if (beforeResult && typeof beforeResult === 'object') {
                    if (beforeResult.prevent) {
                        // 如果返回的结果是 {prevent: true, msg: 'xxxx'} 则表示用户放弃上传
                        this._alert(beforeResult.msg)
                        return
                    }
                }
            }
`
你的before肯定是异步的，那么就不支持了。
要不你用 customUploadImg自己来处理吧。
虽然wangEditor没有给你既可以执行hooks又可以详细控制上传的方法，但直接自定义上传也是不错的做法。

**Comment by kingxg** [comment]
1.修改wangEditor.js

**Comment by kingxg** [comment]
1.修改wangEditor.js原码
