### ISSUE TITLE
内容中的table样式不对

### ISSUE THREAD

**Issue by summerclean** [wangeditor-team/wangEditor#1761]
我编辑框中内容是从数据库读取别人的内容,里面有table标签,设置的是无边框,但是前台显示时,有边框
![image](https://user-images.githubusercontent.com/29908321/47419161-259b0d80-d7ae-11e8-9e8f-bace6fbf872b.png)

**Comment by Tabxx** [comment]
开发者工具调试一下，是不是css层级不够
