### ISSUE TITLE
输入法处于中文输入法- 输入-切换输入法为英文输入法-无法通过onchange事件获取

### ISSUE THREAD

**Issue by wangxv** [wangeditor-team/wangEditor#1770]
1.输入法处于中文输入法 输入
2.切换输入法为英文输入法
结果：输入的英文（ds）无法通过onchange事件获取

![image](https://user-images.githubusercontent.com/30195186/47844578-b6e93000-ddfd-11e8-9464-d9c98db417be.png)

![image](https://user-images.githubusercontent.com/30195186/47844605-c6687900-ddfd-11e8-8d97-0952344af1ed.png)

**Comment by qilvnuanqingyou** [comment]
@wangxv 我在源码中找到了compositionstart记录输入法开始和结束的代码，console 调试过程：搜狗输入法调成中文，输入ff,然后按 shift 键，编辑区域显示的是 ff,源码中
```
this.change = function () {
                // 判断是否有变化
                var currentHtml = this.txt.html();

                if (currentHtml.length === beforeChangeHtml.length) {
                    console.log('需要比较每一个字符');
                    // 需要比较每一个字符
                    if (currentHtml === beforeChangeHtml) {
                        console.log(currentHtml,beforeChangeHtml,'一样了');
                        return;
                    }
                }
```
console的结果是`需要比较每一个字符
wangEditor.js?1a0b:4584 <p><br></p> <p><br></p> 一样了`,所以不会再进行接下来的 onchange 函数了;

如果是用电脑自带的输入法就更奇怪了，下面这段代码不会触发
```
$textContainerElem.on('click keyup', function () {
            console.log(compositionEnd,_this.change);
            // 输入法结束才出发 onchange
            compositionEnd && _this.change && _this.change();
        });
```
希望大神有空给看下，多谢了

**Comment by wangxv** [comment]
在输入法结束的时候调一次change
![image](https://user-images.githubusercontent.com/30195186/48323931-80b37800-e669-11e8-8fdb-e13fe02578f8.png)

**Comment by wangxv** [comment]
暂时官方还没有更新代码，所以可以先监听shift键
![image](https://user-images.githubusercontent.com/30195186/48324052-2c5cc800-e66a-11e8-8ba6-3771e06bb0a4.png)
![image](https://user-images.githubusercontent.com/30195186/48324068-3c74a780-e66a-11e8-8e17-9bdf0ad4e799.png)

**Comment by qilvnuanqingyou** [comment]
明白了，多谢

**Comment by withzhaoyu** [comment]
react项目在componentDidMount 声明周期钩子里这样可以避免这个bug..
`    this.refs.editorElem.addEventListener('keyup', e => {
      if (e.keyCode === 16) {
        // shift
        const timer = setTimeout(() => {
          this.setState(
            {
              editorContent: e.target.innerHTML,
            },
            () => {
              clearTimeout(timer);
            },
          );
        }, 100);
      }
    });`

**Comment by withzhaoyu** [comment]
>     this.refs.editorElem.addEventListener('keyup', e => {
      if (e.keyCode === 16) {
        // shift
        const timer = setTimeout(() => {
          this.setState(
            {
              editorContent: e.target.innerHTML,
            },
            () => {
              clearTimeout(timer);
            },
          );
        }, 100);
      }
    });
react项目在componentDidMount 声明周期钩子里这样可以避免这个bug..

**Comment by withzhaoyu** [comment]
react项目在componentDidMount 声明周期钩子里这样可以避免这个bug..
 
     this.refs.editorElem.addEventListener('keyup', e => {
      if (e.keyCode === 16) {
        // shift
        const timer = setTimeout(() => {
          this.setState(
            {
              editorContent: e.target.innerHTML,
            },
            () => {
              clearTimeout(timer);
            },
          );
        }, 100);
      }
    });
