### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by wschat** [wangeditor-team/wangEditor#1777]
wangEditor3 很好用。以下是使用 过程中碰到的一些问题：
  一、.w-e-text{overflow-y:scroll} 建议改为 .w-e-text{overflow-y:auto}，并且允许用户自定义(min-height、max-height属性)、然后去除对“.w-e-text-container”的高度限制。我觉得这样效果更佳。
  二、“source源码” 功能还是很有用的，建议增加。原因：就目前而言技术员其实编辑一篇文章很少使用富文本编辑器，比如我想直接编辑好一份html源码，再粘贴进去发布这时这功能很有用。
  三、关于图片上传，虽然提供一些自定义的上传托管函数，但是很多人都很懒，一般都比较少用，所以建议在“接口返回的数据”中增加提示信息（当然也许这个功能已经有了，我是从文档看的）
  四、超链接 link 功能 建议给 a 增加一些区别于正文的 默认样式 （例：style="color:#4f81bd"），这样更容易识别区分。
  五、“插入代码”这功能建议改进为类似“引用quote”这个功能的效果体验更佳

**Comment by lgstone** [comment]
使用中同样碰到了第一个问题, 希望能够增加支持min-height和max-height

**Comment by a835100635** [comment]
V4 即将发布，已记录，感谢反馈
