### ISSUE TITLE
如果能在demo的in-vue中加上如何引入highlightjs.js就更好了

### ISSUE THREAD

**Issue by SunQQQ** [wangeditor-team/wangEditor#1780]

**Comment by SunQQQ** [comment]
不好意思，搜了历史issues看到作者有回答过，v3版不支持高亮了。
感觉好遗憾，我确实是个程序员，但是很想用WangEditor

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈

**Comment by goku1989** [comment]
> V4 即将发布，已解决该问题，感谢反馈

V4能够支持引入highlightjs.js做高亮吗
