### ISSUE TITLE
编辑时候，列表打开后怎么关掉列表

### ISSUE THREAD

**Issue by blllld** [wangeditor-team/wangEditor#1791]
- 

- 切问

-

**Comment by blllld** [comment]
编辑时候，列表打开后怎么关掉列表
![image](https://user-images.githubusercontent.com/43157877/48534712-db580880-e8e3-11e8-82d1-645bbd60d514.png)
下面的文本只能用列表，取消不掉

**Comment by DivineWeiR** [comment]
我也是这个问题

**Comment by lutao198** [comment]
> 我也是这个问题

点回车 就退出列表了

**Comment by dongzx666** [comment]
> > 我也是这个问题
> 
> 点回车 就退出列表了

键盘回车还是列表状态啊

**Comment by tian996** [comment]
我也是这问题。设置了列表就不能取消列表。除非把文字删了重写。哪位大佬知道怎么解决的😢

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
