### ISSUE TITLE
新增【数据初始化】和【用后数据清空】功能！

### ISSUE THREAD

**Issue by demigodliu** [wangeditor-team/wangEditor#1797]
功能新增思路:

1: 一般表单提交后，我们需要及时清空表单，包括富文本内容。
2: 对于修改功能，我们需要向富文本中动态加入内容，所以我们需要一个初始化富文本数据的功能。
// 组件内修改如下
![1](https://user-images.githubusercontent.com/30372735/48761217-0e830900-ece3-11e8-873c-6d0e3e707877.png)
![2](https://user-images.githubusercontent.com/30372735/48761223-1642ad80-ece3-11e8-83d4-f5841cd0c5d6.png)

// 父组件调用修改如下
![3](https://user-images.githubusercontent.com/30372735/48761243-25c1f680-ece3-11e8-812c-1de8c0cab199.png)

**Comment by Hchunjun** [comment]
你好，我试过你的代码。发现了一个小问题。https://github.com/wangfupeng1988/wangEditor/issues/1816

**Comment by demigod-liu** [comment]
针对每次修改编辑器内容，光标都会消失跑到最后的bug修复！

1：如果你的编辑器是用在修改文章或者帖子时需要把值填入的情况，请在点击 编辑/修改 字样的按钮事件内，加入一句代码 `sessionStorage.editorInitVal = true;` 。该代码是在编辑器监听内容时告诉他，需要初始化一次内容。

2：然后把`editor.vue`中watch内部的`initData`函数修改一下即可。
```javascript
            initData(val){`
                if(!val){
                    this.editorObj.txt.clear();
                }else{
                    let bool = sessionStorage.editorInitVal == 'true' ? true : false;
                    if(bool){
                        this.editorObj.txt.html(val);
                        sessionStorage.editorInitVal = !bool; // 修改功能填充值时请及时清除缓存，避免每次都刷新编辑器内容导致光标消失。
                    }
                }
            }
```
