### ISSUE TITLE
编辑打字输入过程时不时会滚到最后或最顶部，光标会定位到文章最后

### ISSUE THREAD

**Issue by zcqno1** [wangeditor-team/wangEditor#1801]
中文拼音输入的时候，有时候打字打到一半或按删除键，编辑器就滚到最底部或最顶部，光标则定位到了最末尾，有时候会频繁出现，出现一次之后打几个字又会出现。导致编辑体验特别差。
点击菜单-无序列表时，有时候编辑器也会滚到最顶部。
其他菜单未测试是否会有同样问题。

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
