### ISSUE TITLE
表格增加拆分行，拆分列功能

### ISSUE THREAD

**Issue by liu-xinhui** [wangeditor-team/wangEditor#1810]
找了一圈富文本编辑器，wangEditor是目前在维护的最好的编辑器。都找不到可以替代的，但是我这边需要更复杂的表格（类似下图），希望能支持拆分行和合并行功能，不想用其他的呀。

![image](https://user-images.githubusercontent.com/7698511/49213643-b2656680-f3ff-11e8-8be1-5bef3f0b9171.png)

**Comment by a835100635** [comment]
V4 即将发布，已记录该问题，感谢反馈
