### ISSUE TITLE
react里面使用，为什么没有上传本地图片的功能？只有插入网络图片的功能！(版本：3.1.1)

### ISSUE THREAD

**Issue by beevivo6** [wangeditor-team/wangEditor#1811]
react里面使用，为什么没有上传本地图片的功能？只有插入网络图片的功能！(版本：3.1.1)

**Comment by NoBugNoPain** [comment]
这个一般情况下你得在后台写了接受图片参数的json才会变，我之前用markdown的时候就这样，没写图片处理也是光有传链接，wang还没测试不知道是不是一样

**Comment by beevivo6** [comment]
嗯嗯，我看了文档，需要自行配置！已经搞定！谢谢辣。。。。

**Comment by linronglang** [comment]
不行啊

**Comment by NoBugNoPain** [comment]
> 不行啊

你看wangEditor的文档有个上传图片那一节，加一段js就可以啊比如上传到服务器
在editor.create()前面加一句
` editor.customConfig.uploadImgServer = '/upload'`
就可以啊

**Comment by linronglang** [comment]
> > 不行啊
> 
> 你看wangEditor的文档有个上传图片那一节，加一段js就可以啊比如上传到服务器
> 在editor.create()前面加一句
> ` editor.customConfig.uploadImgServer = '/upload'`
> 就可以啊

嗯 这版本文档没对上 好岗嘎
