### ISSUE TITLE
选中文字进行调整H标题时有bug

### ISSUE THREAD

**Issue by larryw3i** [wangeditor-team/wangEditor#1812]
选中文字进行调整H标题时有bug，调整不了

**Comment by a54552239** [comment]
这个问题解决了吗

**Comment by linghuchong123** [comment]
> 这个问题解决了吗

好久了, 好像这个不是bug

**Comment by a54552239** [comment]
我现在选中多行文字，不能设置H标题，你是怎么解决的呢？求教一下

**Comment by linghuchong123** [comment]
> 我现在选中多行文字，不能设置H标题，你是怎么解决的呢？求教一下

H 按理来说只能一行, H就是Head的意思, 你写文章的时候应该不会有一个标题分两段的想法

**Comment by a54552239** [comment]
好吧，有道理

**Comment by linghuchong123** [comment]
> 好吧，有道理

[POYA Project](https://github.com/linghuchong123/POYA)
**求个Star**

**Comment by a54552239** [comment]
啥东东
