### ISSUE TITLE
微信文章中的图片加载失败，连防盗链都没有

### ISSUE THREAD

**Issue by FengXianGuo** [wangeditor-team/wangEditor#1817]
1，微信文章链接
https://mp.weixin.qq.com/s?__biz=MzI3Nzg3Mjk3NQ==&mid=2247488013&amp;idx=1&amp;sn=083ac3f4e977f59467753f8f5b51b439&source=41#wechat_redirect
2，复制文章内的文字和图片到wangEditor的demo中：
![image](https://user-images.githubusercontent.com/19646853/49725566-f5002c00-fca6-11e8-979b-16f57d6cd534.png)
3，即便来个防盗链也好啊
![image](https://user-images.githubusercontent.com/19646853/49725608-13febe00-fca7-11e8-9832-f9167af399ef.png)
4，求解决啊

**Comment by syhyz1990** [comment]
head里加这个标签
  <meta name="referrer" content="never">
