### ISSUE TITLE
fontSize有办法改成px单位那种吗

### ISSUE THREAD

**Issue by liusaint** [wangeditor-team/wangEditor#1823]
目前好像都是  font-size: x-large;这种形式，能自定义吗？

**Comment by dinglittle** [comment]
搭车 ,同问

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈

**Comment by TinkGu** [comment]
> V4 即将发布，已解决该问题，感谢反馈

@a835100635 具体怎么解决呢，新的配置官网文档没有涉及这块的配置

**Comment by zprao** [comment]
具体怎么解决呢？文档没有相关说明啊
