### ISSUE TITLE
图片上传大小自由缩放

### ISSUE THREAD

**Issue by junjie-zeng** [wangeditor-team/wangEditor#1826]
将代码复制到菜鸟教程上加载，图片可以进行缩放，但是网页加载却不行。

菜鸟教程
![2 y w 6uicexc3l 3et98 3](https://user-images.githubusercontent.com/46043577/50330596-d156a480-0536-11e9-9672-abd495fbb78a.png)

网页加载
![jj e n0el q2fuwk q_a6e](https://user-images.githubusercontent.com/46043577/50331012-319a1600-0538-11e9-86ab-301410885539.png)

代码
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>wangEditor demo</title>
</head>
<body>
	<div id="editor">
		<p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
	</div>
    <script src="https://cdn.bootcss.com/wangEditor/10.0.13/wangEditor.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor = new E('#editor')
        editor.customConfig.showLinkImg = false
        editor.customConfig.uploadImgShowBase64 = true   
        editor.create()
    </script>
</body>
</html>

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
