### ISSUE TITLE
菜单栏可不可以增加一个设置行高的功能

### ISSUE THREAD

**Issue by liumemgmei** [wangeditor-team/wangEditor#1834]
在使用填充背景色功能的时候，背景色的填充高度太小，效果不够理想，可以不可以增加一个设置行高的功能，即能使背景色的填充高度增加，又可以改变行距。

**Comment by gg22mm** [comment]
对这个功能需要搞搞，最基本的

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
