### ISSUE TITLE
新生成的富文本的HTML中标签过多

### ISSUE THREAD

**Issue by czyITPro** [wangeditor-team/wangEditor#1837]
大神你好：因业务需求，需要在富文本编辑器中新建一些文本内容，可能包含图片，结果发现新生成的HTML中标签过多（很多都完全一样），而实际有效信息所占比例很小，罗列部分HTML：

 </p><p class="MsoNormal"><span style="font-size:12.0pt;font-family:宋体;mso-ascii-font-family:&#10;Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:&#10;minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin">　　比如一只基金当天的净值是</span><span lang="EN-US">1.5000</span><span style="font-size:12.0pt;&#10;font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;&#10;mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:&#10;Calibri;mso-hansi-theme-font:minor-latin">元，某人想要购买</span><span lang="EN-US">1000</span><span style="font-size:12.0pt;font-family:&#10;宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:&#10;宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:Calibri;&#10;mso-hansi-theme-font:minor-latin">元的，基金的申购费率是</span><span lang="EN-US">0.15%</span><span style="font-size:12.0pt;font-family:&#10;宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:&#10;宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:Calibri;&#10;mso-hansi-theme-font:minor-latin">，</span><span lang="EN-US" style="font-size:&#10;12.0pt"><o:p></o:p></span></p><p>

这么长的一段HTML中，有效信息只有三四句话，就是说，标签所占比例太大，有没有什么好的办法，请不吝赐教，谢谢

**Comment by katanala** [comment]
富文本就是标签多，除非你自己优化（那是很复杂的），不然使用MarkDown编辑器吧。
