### ISSUE TITLE
数据保存后再次获取填充到编辑框中时，带Html标签

### ISSUE THREAD

**Issue by IATF** [wangeditor-team/wangEditor#1841]
![image](https://user-images.githubusercontent.com/20454721/50732038-289e7b00-11ad-11e9-8c80-b14a2f7bf035.png
我是通过这种方式赋值的：editor.txt.html(context); @wangfupeng1988

**Comment by IATF** [comment]
问题解决了，是我的后台在往前端发送数据的时候会自动将html标签进行转义，所以转义后的字符串赋值到context中，editor就无法正确的加载了，现在我去掉转义后就能正常显示了。

**Comment by jiajiano1** [comment]
您好，请问使用wangEditor时，可以将后台数据传到编辑框吗？

**Comment by be-best** [comment]
优秀
