### ISSUE TITLE
请问上传图片怎么设置width：100%，不然图片会超出很大一部分

### ISSUE THREAD

**Issue by danzi638** [wangeditor-team/wangEditor#1842]
请问各位大神，我在上传的图片的时候怎么设置width：100%之类的属性，不然我上传的图片预览会像这样子。
![image](https://user-images.githubusercontent.com/28698085/50733865-6791f800-11d0-11e9-808d-8039863804d5.png)
谢谢各位大神，

**Comment by syhyz1990** [comment]
给img标签设置
`css
img{
    max-width:100%
}
`
