### ISSUE TITLE
丢失焦点

### ISSUE THREAD

**Issue by qiugu** [wangeditor-team/wangEditor#1853]
使用的vue版本的编辑器，添加表格，在表格中输入文字，输入一次，焦点就丢失了，再次点击编辑，焦点跑到了首行，尝试了issue当中的get/set方法，但是因为数据是异步获取的，所以初始的时候子组件还是获取不到父组件传递过来的数据

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
