### ISSUE TITLE
laravel使用这个3.1.1版本的富文本编辑区js文件报错

### ISSUE THREAD

**Issue by tactshan** [wangeditor-team/wangEditor#1854]
// 恢复选区
    restoreSelection: function restoreSelection() {
        var selection = window.getSelection();
        selection.removeAllRanges();
        selection.addRange(this._currentRange); //这一行报wangEditor.js:3874 The given range isn't in 错document.
    },

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
