### ISSUE TITLE
iphone 编辑时切换光标粘贴内容，始终粘贴到首次的光标下

### ISSUE THREAD

**Issue by Jammly** [wangeditor-team/wangEditor#1857]
iphone 编辑时切换光标粘贴内容，始终粘贴到首次的光标下。只有在当前光标处增删内容时，才会粘贴到当前行；版本：3.1.1；iPhone时浏览器或者webview 都会出现

**Comment by q378532364** [comment]
未考虑到移动端，记录该问题，会安排在 V4 版本中解决，感谢反馈
