### ISSUE TITLE
富文本编辑器怎么实现@人弹窗跟随光标功能

### ISSUE THREAD

**Issue by chenkang15** [wangeditor-team/wangEditor#1858]
富文本编辑器怎么实现@人弹窗跟随光标功能

**Comment by suiliuli** [comment]
@功能我去年刚好实现了一下，这个需要自己修改源码。主要思路是：
1. 每次change计算光标所在位置。
2. 把@框移动到相应位置。

光标位置的计算可以通过在光标位置插入一个<span>标签，然后通过计算<span>的位置计算得到光标位置。最后删除<span>。

下面是简单代码：
`getRangeClientRect: function () {
let range = this._currentRange;
let span = document.createElement('span');
span.style.display = 'inline-block';
span.className = 'range';
range.insertNode(span);
let spanRect = span.getBoundingClientRect();
span.parentNode && span.parentNode.removeChild(span);
return spanRect;
},`

不过我是在electron内用的，其他浏览器兼容性问题没处理。

**Comment by chenkang15** [comment]
学习了，不过

> @功能我去年刚好实现了一下，这个需要自己修改源码。主要思路是：
> 
> 1. 每次change计算光标所在位置。
> 2. 把@框移动到相应位置。
> 
> 光标位置的计算可以通过在光标位置插入一个标签，然后通过计算的位置计算得到光标位置。最后删除。
> 
> 下面是简单代码：
> // 获取光标位置
> getRangeClientRect: function () {
> let range = this._currentRange
> let span = document.createElement('span')
> span.style.display = 'inline-block'
> span.className = 'range'
> range.insertNode(span)
> let spanRect = span.getBoundingClientRect()
> span.parentNode && span.parentNode.removeChild(span)
> return spanRect
> },
> 
> 不过我是在electron内用的，其他浏览器兼容性问题没处理。

学习了，谢谢。当时没做出来，是把@框位置固定到左上角了，晚点试试你的方法。

**Comment by 86driver** [comment]
> 富文本编辑器怎么实现@人弹窗跟随光标功能

老哥  你@功能是怎么实现的  可以赐教赐教吗

**Comment by chenkang15** [comment]
简单来说，我是监听键盘事件，判断输入的最后一个字符，如果是@就请求人物接口------------------ 原始邮件 ------------------
发件人: "86driver"<notifications@github.com>
发送时间: 2019年8月23日(星期五) 下午3:38
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>;
抄送: "chenkang15"<376319663@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wangfupeng1988/wangEditor] 富文本编辑器怎么实现@人弹窗跟随光标功能 (#1858)


 
富文本编辑器怎么实现@人弹窗跟随光标功能
  
老哥  你@功能是怎么实现的  可以赐教赐教吗
 
&mdash;

**Comment by ThreeStonesLee** [comment]
大佬，你做了兼容吗？可以在IE上@吗？我现在遇到了删除时不能整体删除，求大佬指导一下

**Comment by suiliuli** [comment]
> 大佬，你做了兼容吗？可以在IE浏览器上@吗？我现在遇到了删除时不能整体删除，求大佬指导一下

我是在electron里做的，不需要兼容IE。思路是一样。

不能整体删除是指@xxx 整体删除吗？
我试了好几个方案，目前用的最好的是：
用canvas画出 @xxx ，然后生成图片。以img的形式插入编辑器内。
<img src="data:image/png;base64,xxx" alt="@所有人&ensp;" class="at-img" member="all" style="height: 20px;">
发送的时候再通过正则解析img标签，生成正确的文本。

**Comment by ThreeStonesLee** [comment]
好的，谢谢大佬，感谢

**Comment by q378532364** [comment]
记录该问题，会安排在 V4 版本中解决，感谢反馈
