### ISSUE TITLE
文字与图片BUG【紧急】

### ISSUE THREAD

**Issue by baby1798** [wangeditor-team/wangEditor#1860]
复现步骤，输入一段文字，光标选中，随便添加一个样式（加粗或者是斜体），此时样式已经生效，点击空白处，上传图片。图片上传成功，但是文字不见了，可以使用官网的编辑器尝试

**Comment by qijunjun** [comment]
请问解决了？ @baby1798

**Comment by aMaz1ngZzz** [comment]
Chrome下官网demo正常啊，标注一下浏览器～
