### ISSUE TITLE
你好 想问一下上传图片的回调问题

### ISSUE THREAD

**Issue by lichunze** [wangeditor-team/wangEditor#1869]
当用户本地上传一张图片后，想去调用后台的接口，先校验用户是否可以上传，然后再去上传
我想问的是本地上传完的回调事件是什么呢

**Comment by Foodtoinvincible** [comment]
// `自主控制上传吧`
editor.customConfig.customUploadImg = function(files,inset){

  // 发送请求 
   request({
     url: url,
     type: 'POST',
     data: files,
     success: function(data){
           inset(图片链接);
     },
     error: function(error){
     }
   });
   
    
}

**Comment by li941168803** [comment]
感谢  后来文档找到了  现在已经实现了
