### ISSUE TITLE
希望增加一个按钮，然后对html有支持。

### ISSUE THREAD

**Issue by cluyun** [wangeditor-team/wangEditor#1871]
希望增加一个按钮，点击后可以把当前的文本变成html。如果文本为空则可以直接输入html，切换回来后可以看到有样式的纯文本。这个功能可以参考其他大型的富文本框编辑器，我感觉这个功能还是很重要的！！！

**Comment by q378532364** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
