### ISSUE TITLE
在安桌手机没问题，但是在苹果手机输不入内容，连光标都没有显示出来

### ISSUE THREAD

**Issue by fyy123456** [wangeditor-team/wangEditor#1872]
在安桌手机没问题，但是在苹果手机输不入内容，连光标都没有显示出来

**Comment by 1683433284** [comment]
在安桌手机没问题，但是在苹果手机输不入内容，连光标都没有显示出来

**Comment by Fntys** [comment]
我也遇到了这个问题，在react中

**Comment by lyhhhhhh** [comment]
> 在安桌手机没问题，但是在苹果手机输不入内容，连光标都没有

解决了吗老哥

**Comment by q378532364** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
