### ISSUE TITLE
复制excel中的表格到富文本编辑器，光标无法移出表格区域

### ISSUE THREAD

**Issue by qiugu** [wangeditor-team/wangEditor#1874]
在excel中复制粘贴到副文本编辑器，光标放入表格某个单元格，然后发现光标无法移出去了，就是在表格外无法编辑了

**Comment by qiugu** [comment]
此问题只在火狐中有，谷歌是可以正常将光标移动到外面

**Comment by zxh1307** [comment]
请问找到解决方案了吗

**Comment by zxh1307** [comment]
> 此问题只在火狐中有，谷歌是可以正常将光标移动到外面

请问找到解决方案了吗

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
