### ISSUE TITLE
关于工具栏部分的强烈建议

### ISSUE THREAD

**Issue by fwj722** [wangeditor-team/wangEditor#1876]
目前，工具栏部分无法换行，文档里说换行难看。但是在实际项目中，要做到浏览器自适应，那这个还必须要有换行功能，且换行还是很漂亮的。如果不换行，在工具多，浏览器宽度小的情况下，会出现工具隐藏缺失。所以强烈建议加上换行功能。

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
