### ISSUE TITLE
工具栏的强制换行出现的问题

### ISSUE THREAD

**Issue by dyt123456** [wangeditor-team/wangEditor#1877]
![image](https://user-images.githubusercontent.com/19601226/53384175-f4795680-39b4-11e9-8b9e-4f2b78b9e587.png)
后台管理需要适配小的电脑屏幕所以我让工具栏强制换行了，使用的是flex-wrap:wrap。but 当我鼠标放到工具栏时dropList就出现了问题，层级一直在下面即使我设置了z-index大于w-e-menu的z-index也是一样

**Comment by housiyu007** [comment]
同求，这个问题太伤了

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
