### ISSUE TITLE
使用源码集成到自己到项目中, 工具栏不显示

### ISSUE THREAD

**Issue by winboy99** [wangeditor-team/wangEditor#1879]
我使用react架构，将wangeditor源码集成到自己的代码中，这样便于调试，增加一些额外的配置。
目前，我使用集成后的源码，工具栏不显示。编辑框没问题可以使用。
用浏览器看下 elements, 发现工具栏的整体的高度只有1.98。工具栏的每个小图标的高度都是0。
请赐教，应该如何做。

https://gitee.com/odoowww/image/blob/master/github-issues/wangeditor-toolbar1.png
https://gitee.com/odoowww/image/blob/master/github-issues/wangeditor-toolbar2.png

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
