### ISSUE TITLE
火狐浏览器粘贴表格后无法复制多个单元格内容

### ISSUE THREAD

**Issue by conanxt** [wangeditor-team/wangEditor#1882]
火狐粘贴表格后，选择多个单元格会附带一个蓝框，此时更换背景色或文字颜色等操作无法全部生效，只会对第一个单元格生效
![default](https://user-images.githubusercontent.com/48229119/53773916-51ca5600-3f27-11e9-977e-5a980f5e884d.png)

**Comment by q378532364** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
