### ISSUE TITLE
富文本内容怎么传到php处理页面？

### ISSUE THREAD

**Issue by blmulang** [wangeditor-team/wangEditor#1886]
你好！非常感谢你的大作！让大家都轻松了许多，而且页面也很美；
但是，这里像请教个问题，这里怎么把编辑器里边的内容传给php界面；
在大佬的使用说明里是用
`document.getElementById('editBtn').addEventListener('click', function ()`
来获取编辑器里边的内容的；

我修改后想让它返回到input标签里边，然后通过form表单传给php界面；
js：
```
document.getElementById('editBtn').addEventListener('click', function () {
        // 读取 html
        var $cc=editor.txt.html()        
//      alert($cc)
	document.getElementById("content1").value=cc;
    }, false)
```
html：
```
<div id="content"></div>
	<input type="hidden" id="content1" name="content1" />
```
PHP：
`$content=var_dump($_REQUEST['content1']);`
可能是我的php获取代码错了，但是不知道怎么获取，求大佬指点啊；

**Comment by gmy5210** [comment]
你在js里面写$ 谁认识
