### ISSUE TITLE
上传图片成功但是无法显示

### ISSUE THREAD

**Issue by dongyidongyi1111** [wangeditor-team/wangEditor#1888]
首先编辑器没有获得焦点，直接点击图片按钮，上传图片，图片上传成功之后，没有显示。如果先点击一下编辑器，获得焦点以后，再上传图片，图片可正常显示，想请教一下什么原因导致的，谢谢

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
