### ISSUE TITLE
执行editor.txt.clear()清空编辑区操作,内容中还是存在两个p标签,导致光标定位在第二行

### ISSUE THREAD

**Issue by wuchenglong1992** [wangeditor-team/wangEditor#1889]
问题:监听回车事件,执行editor.txt.clear()(清空编辑区内容)操作,编辑区还是存在两个p标签,导致光标定位在第二行,然后再输入内容回车就正常定位在第二行了.
理想状态:在执行清空操作的时候编辑区只有一个p,光标定位在第一行.

**Comment by wuchenglong1992** [comment]
终于发现问题了..自己回复一下吧,只要禁止掉默认事件就可以了.....e.preventDefault(); 😓😓😓

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
