### ISSUE TITLE
最新wangEditor动态设置值的时候，会导致光标跳到末尾位置，而不是所输入的文本之后（在中间插入内容）

### ISSUE THREAD

**Issue by leizhongli** [wangeditor-team/wangEditor#1898]

**Comment by daixinghong** [comment]
我是真的想问问你搞定这个问题没有

**Comment by arnoldFang** [comment]
同样遇到了这个问题

**Comment by F2a** [comment]
同样遇到了，请问找到原因了吗解决了吗

**Comment by leizhongli** [comment]
这个问题我是自己写了一个方法控制光标的位置，官方文档啥的没有解决的方法

**Comment by leizhongli** [comment]
> 了

这个问题我是自己写了一个方法控制光标的位置，官方文档啥的没有解决的方法

**Comment by leizhongli** [comment]
> 我是真的想问问你搞定这个问题没有

这个问题我是自己写了一个方法控制光标的位置，官方文档啥的没有解决的方法

**Comment by leizhongli** [comment]
> 同样遇到了，请问找到原因了吗解决了吗

这个问题我是自己写了一个方法控制光标的位置，官方文档啥的没有解决的方法

**Comment by leizhongli** [comment]
> 同样遇到了，请问找到原因了吗解决了吗

你有找到一些解决的方法吗

**Comment by liuz666** [comment]
`<template>
    <div>
        <div id="editor" ></div>
    </div>
</template>
<script>
import WangEditor from 'wangeditor'
export default {
    name:'richText',
    props:{
        setContent:{
            type:String
        },
        isClearEditor:{
            type:Boolean,
            default:false,
        },
    },
    data(){
        return{
            editor:null,
            isChange:false,
        }
    },
    watch:{
        setContent(newVal){ //光标乱跳就是因为这里监听值，实时更新了内容。解决方案 用一个开关来控制它。
            if(!this.isChange){
                this.editor.txt.html(newVal); //设置内容
            }
            this.isChange = false;
        },
        isClearEditor(newVal){
            if(newVal){
                this.editor.txt.clear()  //清空富文本的内容
            }
        }
    },
    methods:{

    },
    mounted(){
        this.editor = new WangEditor('#editor')
        // 自定义菜单配置
        this.editor.customConfig.menus = [
            'head',
            'bold',
            'fontSize',
            'fontName',
            'italic',
            // 'underline',
            // 'strikeThrough', 
            'foreColor', 'backColor', 'link', 'list', 'justify', 'quote',  'image', 'table',  'code', 'undo', 'redo'
        ]
        this.editor.customConfig.uploadImgShowBase64 = true//img图片转成base64格式，需要的话写，不需要不写
        this.editor.customConfig.onchange  = (html) => {
            this.isChange = true;
            html = html.replace(/<table border="0"/g, '<table border="1"');//修复table样式问题
            this.$emit('changeEditVal',html);
        }
        this.editor.create()        
    }
}
</script>`

**Comment by liuz666** [comment]
你是用了vue吗？

**Comment by wang3690004** [comment]
同 遇到这个问题 在中间的文本修改内容 停顿之后 光标立刻会移动到 最末尾  暂时不知道要怎么解决  用的是vue2.5    wangeditor3.1.1版本

**Comment by liuz666** [comment]
光标乱跳的原因是：因为在VUE组件中监听了当前值，富文本框的值更新后，光标就会跳到最后。
解决方案：定义一个开关，flag = false; 然后在watch监听里面加个判断，flag==false时候，才重新赋值。最后在富文本框onchange事件哪里设置一下 flag=true;
亲测，能解决光标乱跳问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wang3690004"<notifications@github.com&gt;; 
发送时间: 2020年10月9日(星期五) 下午5:47
收件人: "wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;; 
抄送: "刘智"<1298214330@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [wangeditor-team/wangEditor] 最新wangEditor动态设置值的时候，会导致光标跳到末尾位置，而不是所输入的文本之后（在中间插入内容） (#1898)





 
同 遇到这个问题 在中间的文本修改内容 停顿之后 光标立刻会移动到 最末尾  暂时不知道要怎么解决  用的是vue2.5    wangeditor3.1.1版本

**Comment by wang3690004** [comment]
之前得做法是监听当前得值 onchange 后 会把当前的值 使用$emit 传给父组件，  后面干脆不使用监听数值，在editor层面绑定值，等到提交内容的时候 使用  this.$refs.editor 调用方法来获取editor的content 亲测 解决了。

**Comment by zhuichen** [comment]
@liuz666 谢谢，确实有用
