### ISSUE TITLE
在nuxt中报错navigator is not defined

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [wangeditor-team/wangEditor#1902]
![image](https://user-images.githubusercontent.com/23397455/55062266-88236d00-50b0-11e9-842a-071a26b9c4e4.png)

**Comment by yangfanjie97** [comment]
首先：富文本不需要ssr。
[官方解决方法：](https://zh.nuxtjs.org/faq/window-document-undefined)
![1555488805(1)](https://user-images.githubusercontent.com/35363404/56271887-12994280-612c-11e9-975a-89815a000853.jpg)

**Comment by puzzle9** [comment]
> 首先：富文本不需要ssr。
> [官方解决方法：](https://zh.nuxtjs.org/faq/window-document-undefined)
> ![1555488805(1)](https://user-images.githubusercontent.com/35363404/56271887-12994280-612c-11e9-975a-89815a000853.jpg)

在 nuxt 中 貌似用 id 获取有问题 然后发现你用 refs
