### ISSUE TITLE
写在vue项目中有些报错

### ISSUE THREAD

**Issue by Aqincheng** [wangeditor-team/wangEditor#1906]
vue.runtime.esm.js:619 [Vue warn]: Error in mounted hook (Promise/async): "Error: 错误：初始化编辑器时候未传入任何参数，请查阅文档"

found in

---> <User> at src/forum/views/forum/user.vue
       <ElMain> at packages/main/src/main.vue
         <Article> at src/forum/views/forum/article.vue
           <ElContainer> at packages/container/src/main.vue
             <App> at src/forum/App.vue
               <Root>
warn @ vue.runtime.esm.js:619
logError @ vue.runtime.esm.js:1884
globalHandleError @ vue.runtime.esm.js:1879
handleError @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1856
Promise.catch (async)
invokeWithErrorHandling @ vue.runtime.esm.js:1856
callHook @ vue.runtime.esm.js:4213
insert @ vue.runtime.esm.js:3139
invokeInsertHook @ vue.runtime.esm.js:6340
patch @ vue.runtime.esm.js:6559
Vue._update @ vue.runtime.esm.js:3942
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4473
run @ vue.runtime.esm.js:4548
flushSchedulerQueue @ vue.runtime.esm.js:4304
(anonymous) @ vue.runtime.esm.js:1980
flushCallbacks @ vue.runtime.esm.js:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1933
nextTick @ vue.runtime.esm.js:1990
queueWatcher @ vue.runtime.esm.js:4396
update @ vue.runtime.esm.js:4538
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
proxySetter @ vue.runtime.esm.js:4625
_callee$ @ App.vue:33
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.(anonymous function) @ runtime.js:97
asyncGeneratorStep @ forum.js:49229
_next @ forum.js:49231
Promise.then (async)
asyncGeneratorStep @ forum.js:49229
_next @ forum.js:49231
Promise.then (async)
asyncGeneratorStep @ forum.js:49229
_next @ forum.js:49231
(anonymous) @ forum.js:49231
(anonymous) @ forum.js:49231
mounted @ App.vue:14
invokeWithErrorHandling @ vue.runtime.esm.js:1854
callHook @ vue.runtime.esm.js:4213
insert @ vue.runtime.esm.js:3139
invokeInsertHook @ vue.runtime.esm.js:6340
patch @ vue.runtime.esm.js:6559
Vue._update @ vue.runtime.esm.js:3939
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4473
Watcher @ vue.runtime.esm.js:4462
mountComponent @ vue.runtime.esm.js:4067
./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:8409
./src/forum/main.js @ main.js:21
__webpack_require__ @ bootstrap:766
fn @ bootstrap:129
3 @ forum.js:158100
__webpack_require__ @ bootstrap:766
(anonymous) @ bootstrap:901
(anonymous) @ bootstrap:901
vue.runtime.esm.js:1888 Error: 错误：初始化编辑器时候未传入任何参数，请查阅文档
    at new Editor (wangEditor.js:4335)
    at VueComponent._callee$ (user.vue:178)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.(anonymous function) [as next] (http://127.0.0.1:8081/forum.js:1010:21)
    at asyncGeneratorStep (forum.js:49517)
    at _next (forum.js:49519)
    at forum.js:49519
    at new Promise (<anonymous>)
    at VueComponent.<anonymous> (forum.js:49519)

**Comment by hold-baby** [comment]
![image](https://user-images.githubusercontent.com/21041219/56019374-00d42b80-5d37-11e9-9a3d-3257946357c0.png)
