### ISSUE TITLE
请问作者，麻烦问一下有没有可以上传视频的demo

### ISSUE THREAD

**Issue by InfiniteGang** [wangeditor-team/wangEditor#1908]

**Comment by momokanni** [comment]
自己不会写吗？什么都干不了 什么都不会 干这行还有什么意义？

**Comment by yyccQQu** [comment]
<img width="475" alt="截屏2020-07-31 下午11 37 45" src="https://user-images.githubusercontent.com/32674176/89071001-fce27780-d386-11ea-901f-9a168e5b6001.png">
不需要例子的，直接这样用就可以了

**Comment by InfiniteGang** [comment]
你好，这个富文本编辑器对视频支持不太好，
会经常崩溃，建议视频可以分出来单独做，如果一定要用请选择 百度的富文本编辑器获取一些对视频支持好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yyccQQu <notifications@github.com&gt;
发送时间: 2020年8月1日 03:39
收件人: wangfupeng1988/wangEditor <wangEditor@noreply.github.com&gt;
抄送: InfiniteGang <1229972123@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[wangfupeng1988/wangEditor] 请问作者，麻烦问一下有没有可以上传视频的demo (#1908)





 

 不需要例子的，直接这样用就可以了
