### ISSUE TITLE
快速点击编辑器外部的提交按钮，不会触发`onchange`事件

### ISSUE THREAD

**Issue by Lenny-Hu** [wangeditor-team/wangEditor#1909]
我按文档中封装了vue组件，使用时发现一个情况，当你的编辑器在初始化时有值`123`，你删完，然后你输入一个字符`1`，然后快速点击编辑器外部的提交按钮，不会触发`onchange`事件（只要不你去输入，一直点都提交都是一样的效果），这可能导致你的服务器接口报错（提交了空数据）；我已尝试将`onchangeTimeout`设置为`20`，还是一样； 当然了，如果每次提交之前都手动调用 `editor.txt.html()`那肯定是没有任何问题的，但就是想有这个数据及时绑定的效果。

**Comment by Lenny-Hu** [comment]
我目前是采用了来解决
```
this.$refs.editor.querySelector('[contenteditable="true"]').addEventListener('blur', (event) => {
      console.log('离开前手动触发change事件', event)
      this.$editor.change()
}, false)
```

**Comment by Lenny-Hu** [comment]
好像使用`input`来代替`onchange`更好
```
element.addEventListener('input', (event) => { console.log('发送数据给父组件') })
```

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
