### ISSUE TITLE
插入代码之后光标不能自动进入正文输入 ，也就是光标跳不出代码区

### ISSUE THREAD

**Issue by soneger** [wangeditor-team/wangEditor#1911]
将代码插入之后，光标还是在代码区域，我想输入正文，这个是时候不管我怎么点击下面的区域光标都不会脱离代码区域块，输入正文只会显示在code 区域  版本是3.1.1

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
