### ISSUE TITLE
在electron应用中引入wangditor时报错wangEditor.js:4 Uncaught (in promise) TypeError: Cannot set property 'wangEditor' of undefined

### ISSUE THREAD

**Issue by itlixiaolong** [wangeditor-team/wangEditor#1914]
![image](https://user-images.githubusercontent.com/26212782/55857359-7c02d980-5b9f-11e9-9caa-0ecd4995f9c9.png)

**Comment by itlixiaolong** [comment]
![image](https://user-images.githubusercontent.com/26212782/55857337-6ab9cd00-5b9f-11e9-8464-2feb7c3bface.png)

**Comment by q378532364** [comment]
记录该问题，会安排在 V4 版本中解决，感谢反馈
