### ISSUE TITLE
怎么判断用户有没有输入内容--只有空白字符不算

### ISSUE THREAD

**Issue by dinghui1120** [wangeditor-team/wangEditor#1915]

**Comment by StringKe** [comment]
onchange 事件监听

**Comment by dinghui1120** [comment]
我的意思是用户提交的时候判断有没有输入内容
当我按多次空格时，获取的内容是下面这样的
editor.txt.html()---<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
editor.txt.text()----&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
像这种空白字符，提示用户去输入内容
不知道怎么去判断

**Comment by dinghui1120** [comment]
’<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>‘
’&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;‘

**Comment by dinghui1120** [comment]
就是都是空格占位符--& n b s p ;

**Comment by StringKe** [comment]
。。。。。。。正则替换或者 trim() 试试

**Comment by dinghui1120** [comment]
都试过了，再获取他们的长度还是有，差别不大。
你是怎么判断的呀

**Comment by StringKe** [comment]
document.createElement 然后 在调取 innertext 试试

**Comment by studyhuang1996** [comment]
正则替换 editor.txt.html().replace(/\s+/g, '') .replace(/<p>(&nbsp;)*(<br>)*<\/p>/g, '').trim()

**Comment by fujilu** [comment]
@dinghui1120 请问你最后是怎么解决的

**Comment by dinghui1120** [comment]
作者回复的你试一下，我好像换了个编辑器。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Garrett"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 上午10:43
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&gt;; 
抄送: "冰魂"<243542757@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)




@dinghui1120 请问你最后是怎么解决的

**Comment by fujilu** [comment]
换了什么编辑器？我遇到相同的问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dan Dascalescu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 上午10:54
收件人:&nbsp;"wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送:&nbsp;"夕阳"<857356255@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)



作者回复的你试一下，我好像换了个编辑器。。。 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Garrett"<notifications@github.com&amp;gt;;  
 发送时间: 2020年1月10日(星期五) 上午10:43 
 收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;gt;;  
 抄送: "冰魂"<243542757@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;;  
 主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915) 
 
 
 
 
 @dinghui1120 请问你最后是怎么解决的

**Comment by dinghui1120** [comment]
试了一下，换了也没解决，哈哈。要是有解决方法，分享下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Garrett"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 上午10:56
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&gt;; 
抄送: "冰魂"<243542757@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)



换了什么编辑器？我遇到相同的问题 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Dan Dascalescu"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年1月10日(星期五) 上午10:54 
 收件人:&amp;nbsp;"wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"夕阳"<857356255@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915) 
 
 
 
 作者回复的你试一下，我好像换了个编辑器。。。  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "Garrett"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年1月10日(星期五) 上午10:43  
  收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;amp;gt;;   
  抄送: "冰魂"<243542757@qq.com&amp;amp;gt;; "Mention"<mention@noreply.github.com&amp;amp;gt;;   
  主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)  
   
   
   
   
  @dinghui1120 请问你最后是怎么解决的

**Comment by fujilu** [comment]
额，我尝试解决，行了告诉你，你换的是哪一个编辑器
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dan Dascalescu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 中午11:08
收件人:&nbsp;"wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送:&nbsp;"夕阳"<857356255@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)



试了一下，换了也没解决，哈哈。要是有解决方法，分享下 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Garrett"<notifications@github.com&amp;gt;;  
 发送时间: 2020年1月10日(星期五) 上午10:56 
 收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;gt;;  
 抄送: "冰魂"<243542757@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;;  
 主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915) 
 
 
 
 换了什么编辑器？我遇到相同的问题  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"Dan Dascalescu"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年1月10日(星期五) 上午10:54  
  收件人:&amp;amp;nbsp;"wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"夕阳"<857356255@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)  
   
   
   
  作者回复的你试一下，我好像换了个编辑器。。。   
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "Garrett"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年1月10日(星期五) 上午10:43   
   收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "冰魂"<243542757@qq.com&amp;amp;amp;gt;; "Mention"<mention@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)   
     
     
     
     
   @dinghui1120 请问你最后是怎么解决的

**Comment by dinghui1120** [comment]
Simditor





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Garrett"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 中午11:09
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&gt;; 
抄送: "冰魂"<243542757@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)



额，我尝试解决，行了告诉你，你换的是哪一个编辑器 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Dan Dascalescu"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年1月10日(星期五) 中午11:08 
 收件人:&amp;nbsp;"wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"夕阳"<857356255@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915) 
 
 
 
 试了一下，换了也没解决，哈哈。要是有解决方法，分享下  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "Garrett"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年1月10日(星期五) 上午10:56  
  收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;amp;gt;;   
  抄送: "冰魂"<243542757@qq.com&amp;amp;gt;; "Mention"<mention@noreply.github.com&amp;amp;gt;;   
  主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)  
   
   
   
  换了什么编辑器？我遇到相同的问题   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"Dan Dascalescu"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年1月10日(星期五) 上午10:54   
   收件人:&amp;amp;amp;nbsp;"wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"夕阳"<857356255@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)   
     
     
     
   作者回复的你试一下，我好像换了个编辑器。。。    
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: "Garrett"<notifications@github.com&amp;amp;amp;amp;gt;;     
    发送时间: 2020年1月10日(星期五) 上午10:43    
    收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&amp;amp;amp;amp;gt;;     
    抄送: "冰魂"<243542757@qq.com&amp;amp;amp;amp;gt;; "Mention"<mention@noreply.github.com&amp;amp;amp;amp;gt;;     
    主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)    
       
       
       
       
    @dinghui1120 请问你最后是怎么解决的

**Comment by fujilu** [comment]
记住这个了 ，这些坑踩得我，尴尬

**Comment by fujilu** [comment]
我是把外面的标签先去掉，然后再去空格&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text&nbsp;=&nbsp;text.replace(/<[^&gt;]+&gt;/g,&nbsp;"")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text&nbsp;=&nbsp;text.replace(/&amp;nbsp;/ig,&nbsp;'');
        然后判断
&nbsp;       $.trim(text)&nbsp;==&nbsp;""

**Comment by dinghui1120** [comment]
好的，以后有机会试下，谢谢哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Garrett"<notifications@github.com&gt;; 
发送时间: 2020年1月13日(星期一) 下午3:21
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com&gt;; 
抄送: "冰魂"<243542757@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [wangfupeng1988/wangEditor] 怎么判断用户有没有输入内容--只有空白字符不算 (#1915)



我是把外面的标签先去掉，然后再去空格&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;text&amp;nbsp;=&amp;nbsp;text.replace(/<[^&amp;gt;]+&amp;gt;/g,&amp;nbsp;"") 
 &amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;text&amp;nbsp;=&amp;nbsp;text.replace(/&amp;amp;nbsp;/ig,&amp;nbsp;''); 
         然后判断 
 &amp;nbsp;       $.trim(text)&amp;nbsp;==&amp;nbsp;""

**Comment by fujilu** [comment]
不客气的

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
