### ISSUE TITLE
锚点

### ISSUE THREAD

**Issue by yffs-hub** [wangeditor-team/wangEditor#1916]
请问如何在生成的html中，为“h”标签加上id，我想添加锚点，或者有没有其他的解决方案，求指教。。。

**Comment by liuz666** [comment]
我也想问这个问题？ 可以创建锚点吗

**Comment by yang-small-fan** [comment]
> 我也想问这个问题？ 可以创建锚点吗
貌似不可以，我最后采用  node.setAttribute('id', id); 的方式写入id并创建锚点。

**Comment by yang-small-fan** [comment]
@liuz666 
貌似不可以，我最后采用 node.setAttribute('id', id); 的方式写入id并创建锚点。

**Comment by liuz666** [comment]
谢谢你的回答，我的业务场景就是添加编辑新闻时候，在富文本框中指定的位置可以插入锚点，最后用户浏览新闻的时候 就可以根据添加锚点进行跳转！




------------------ 原始邮件 ------------------
发件人: "yang-small-fan"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 下午2:17
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>; 
抄送: "刘智"<1298214330@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [wangfupeng1988/wangEditor] 锚点 (#1916)




@liuz666
 貌似不可以，我最后采用 node.setAttribute('id', id); 的方式写入id并创建锚点。

**Comment by yang-small-fan** [comment]
@liuz666 
根据你的需求，我又看了一下这个插件，感觉你可能需要在生成的html上面做文章，或者挑选其他的插件了。

**Comment by liuz666** [comment]
我以前是用的summernote 这个插件支持自定义功能按钮的，然后在自定义的按钮中绑定点击事件 保存每次插入的锚点ID最后实现过这个功能！现在不打算用这个插件了，因为要依赖的外部插件好多！




------------------ 原始邮件 ------------------
发件人: "yang-small-fan"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 下午3:10
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>;
抄送: "刘智"<1298214330@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wangfupeng1988/wangEditor] 锚点 (#1916)




@liuz666
 根据你的需求，我又看了一下这个插件，感觉你可能需要在生成的html上面做文章，或者挑选其他的插件了。

**Comment by yang-small-fan** [comment]
@liuz666 
我明白你的意思，这个插件勉强能满足你的需求，比如说，你想插入锚点时就用一个<h>标签。然后，在生成的html里面动态给所有h标签节点.setAttribute('id', id);，最后用这个id 制作锚点。当然，这不是最好的方案。

**Comment by yang-small-fan** [comment]
@liuz666 
我明白你的意思，这个插件勉强能满足你的需求，比如说，你想插入锚点时就用一个标题<H>。然后，在生成的html里面动态给所有H标签节点.setAttribute('id', id);，最后用这个id 制作锚点。当然这不是最好的方案。

**Comment by liuz666** [comment]
差不多是这个意思，在光标选中的地方插入一个锚点，然后锚点id保存下来，生成一个锚点目录！






------------------ 原始邮件 ------------------
发件人: "yang-small-fan"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 下午3:27
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>;
抄送: "刘智"<1298214330@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wangfupeng1988/wangEditor] 锚点 (#1916)




@liuz666
 我明白你的意思，这个插件勉强能满足你的需求，比如说，你想插入锚点时就用一个标题。然后，在生成的html里面动态给所有H标签节点.setAttribute('id', id);，最后用这个id 制作锚点。当然这不是最好的方案。

**Comment by ycshill** [comment]
现在这个问题没有解决吧？
