### ISSUE TITLE
wangEditor3 直接上传图片到oss？

### ISSUE THREAD

**Issue by im-zhangxi** [wangeditor-team/wangEditor#1923]
这个目前 大家有实现的吗？  能帮忙贴下代码吗？》谢谢

**Comment by AHIMOTU** [comment]
这是我写的，你可以参考一下

// 自定义上传图片事件
      this.editor.customConfig.customUploadImg = function (files, insert) {
        let client = new OSS({
          accessKeyId: ossConfig.accessKeyId,
          accessKeySecret: ossConfig.accessKeySecret,
          bucket: ossConfig.ckbucket,
          region: ossConfig.region
        })
        let file = files[0]
        const point = file.name.lastIndexOf('.')
        let suffix = file.name.substr(point)
        let fileNames = _this.$getUUID() + suffix
        // let encodeFileName = encodeURI(file.name)
        let encodeFileName = encodeURI((new Date()).getTime())
        client.multipartUpload('textEditorImage/' + fileNames, file, {
          headers: {
            'Content-Disposition': 'attachment;filename=' + encodeFileName
          }
        }).then((data) => {
          if (data.res.statusCode === 200) {
            // 上传代码返回结果之后，将图片插入到编辑器中
            insert(`http://${ossConfig.ckbucket}.${ossConfig.region}.aliyuncs.com/${data.name}`)
          }
        })
      }

**Comment by im-zhangxi** [comment]
@AHIMOTU   嗯  确实是这样，我已经实现了。 还是万分感谢你。

**Comment by yinqianhua** [comment]
@im-zhangxi 请问一下你怎么实现的？
