### ISSUE TITLE
编辑器回车后，按返回键←，会自动给文本加上<span style="font-size:1rem;"></span>的样式，官网地址不会？ 为啥？ 有解决的办法吗？

### ISSUE THREAD

**Issue by IVANLEE99** [wangeditor-team/wangEditor#1929]
![image](https://user-images.githubusercontent.com/18308725/56345116-90735180-61f1-11e9-83cf-ad104a7b6eef.png)
编辑器回车后，按返回键←，会自动给文本加上<span style="font-size:1rem;"></span>的样式，官网地址不会？
为啥？
有解决的办法吗？

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
