### ISSUE TITLE
编辑器支持html源码视图编辑

### ISSUE THREAD

**Issue by webzhongwang** [wangeditor-team/wangEditor#1932]
目前编辑器只支持文本视图编辑，望支持html源码视力编辑，且源码视图和文本视图可以相互切换

**Comment by q378532364** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈

**Comment by MIKOTO123** [comment]
> 已记录该问题，会安排在 V4 版本中解决，感谢反馈

现在还是解决了没,,,官方文档都没看到啊

**Comment by ChartWay** [comment]
> > 已记录该问题，会安排在 V4 版本中解决，感谢反馈
> 
> 现在还是解决了没,,,官方文档都没看到啊

官方不考虑解决。
遗憾。
