### ISSUE TITLE
编辑器界面模态框按钮失效

### ISSUE THREAD

**Issue by zengweishi** [wangeditor-team/wangEditor#1936]
富文本编辑器上设置提交文本后弹出模态框，如果模态框中的按钮在富文本编辑界面内，那么按钮会失效。如图：这是为什么？
![2](https://user-images.githubusercontent.com/16833206/56572870-7de28900-65f2-11e9-926b-070e573dedc6.jpg)

**Comment by be-best** [comment]
@wangfupeng1988

**Comment by chenzm080** [comment]
这应该是层面的问题吧
把模态框的z-index设置比富文本框大应该就可以了吧
