### ISSUE TITLE
实现滑动改变图片大小

### ISSUE THREAD

**Issue by dearMrYang** [wangeditor-team/wangEditor#1938]
https://github.com/wangfupeng1988/wangEditor/blob/b77696f5e81c8ec13d9d341252d6b9fa8a22db18/release/wangEditor.js#L2681

图片大小按钮改为；`<input type="range" id="input-sidler" min="0" max="100" value="100"/>`
事件```
selector: "#input-sidler", type: "input propertychange", fn: function (v) {
      var t = e._selectedImg;
      t && t.css("width", document.getElementById('input-sidler').value + '%'), !0
}
```

可以实现滑动改变图片大小

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
