### ISSUE TITLE
以组件的形式在vue项目中使用的时候，光标的bug

### ISSUE THREAD

**Issue by hafung** [wangeditor-team/wangEditor#1940]
使用官方封装的vue组件

通过onchange回调实现单向流

bug：
在一段文字当中，将光标放到段落中然后按回退键删除文字的时候，光标会自动跳到末尾

**Comment by GloamingMoon** [comment]
好像是因为 使用 v-model 设置初始值的时候 监听一直在运行，不停改变值，导致焦点位置的改变

**Comment by xiajingen** [comment]
> 好像是因为 使用 v-model 设置初始值的时候 监听一直在运行，不停改变值，导致焦点位置的改变

你有什么临时的解决方案么....

**Comment by xiajingen** [comment]
一定要删除，只要光标移到段落中去编辑文字，光标也会自动跳到最后去...........

**Comment by xiajingen** [comment]
> 好像是因为 使用 v-model 设置初始值的时候 监听一直在运行，不停改变值，导致焦点位置的改变

并没有使用v-model，是用prop单向流，用onchange回调来赋值的

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
