### ISSUE TITLE
链接处存在xss

### ISSUE THREAD

**Issue by fuxiao1** [wangeditor-team/wangEditor#1945]
拿官网举例:

链接处输入 xxx" onmouseover=alert(1)>asdf</a>

点击插入。

鼠标放在asdf字符串上边弹窗。

**Comment by fuxiao1** [comment]
链接处输入 xxx" onmouseover=alert(1)>asdf</a>

**Comment by Dieber** [comment]
我也发现了😭

**Comment by troy351** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor2/131436

**Comment by Jaggle** [comment]
有点不明白，我的项目被提示wangeditor有xss缺陷，但是我会在后端对用户的提交进行过滤（我不信任任何提交输入），毕竟用户可以对接口抓包，然后将提交内容修改成xss代码，所以我会统一在后端做过滤，这样一来，应该可以避免xss攻击吧？有谁能帮忙解释一下，先谢过了！

**Comment by q378532364** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈

**Comment by dhuiyang** [comment]
> 已记录该问题，会安排在 V4 版本中解决，感谢反馈

请问下这个问题会在什么时候修复，我这边在考虑等你的新版本或者改用其他的。

**Comment by snoopysecurity** [comment]
I think this is fixed in `v4.0.6`

**Comment by PatricioPeng** [comment]
“链接文字”处输入类似<img src=x onerror=alert`2`>仍存在xss

**Comment by uniquejava** [comment]
我顺着high vulnerability的link点进来的， 没解决咋要关闭issue?

![image](https://user-images.githubusercontent.com/1049271/124857287-9b874780-dfde-11eb-8e38-e4a3d9112be7.png)


![image](https://user-images.githubusercontent.com/1049271/124857204-72ff4d80-dfde-11eb-8580-0aca312bbedf.png)

**Comment by uniquejava** [comment]
> 已记录该问题，会安排在 V4 版本中解决，感谢反馈

都4.7.5了， high vulnerability 可以优先处理一下吗

**Comment by wangfupeng1988** [comment]
@uniquejava https://github.com/wangeditor-team/wangEditor/issues/3455
