### ISSUE TITLE
无法将以下html 设置到 editor

### ISSUE THREAD

**Issue by liweigithub** [wangeditor-team/wangEditor#1948]
1111

**Comment by liweigithub** [comment]
<html>
 <head></head>
 <body>
  <p><br /></p>
  <p> </p>

**Comment by liweigithub** [comment]
`<html>
 <head></head>
 <body>
  <p><br /></p>
  <p> </p>`

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
