### ISSUE TITLE
markdown模式下无法实现粘贴 剪切板图片

### ISSUE THREAD

**Issue by daelephant** [wangeditor-team/wangEditor#1952]
富文本中可以很好的使用粘贴图片跟功能，但是切换到markdown就无法实现

**Comment by wangfupeng1988** [comment]
markdown 插件已经开发完了 https://github.com/wangeditor-team/wangEditor-plugin-md

不过只能用于 [v5](https://www.wangeditor.com/v5/) 。v5 近期会正式发布，v4 不再做功能升级了。
