### ISSUE TITLE
搜狗中文输入法输入字母，回车，保存时没有捕捉到字母。此情况一般出现在末尾。

### ISSUE THREAD

**Issue by kexiaobo** [wangeditor-team/wangEditor#1954]

**Comment by kexiaobo** [comment]
![image](https://user-images.githubusercontent.com/48825426/57353814-4fd97900-719c-11e9-8012-40d26ce4d046.png)

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈
