### ISSUE TITLE
如何实现附件功能

### ISSUE THREAD

**Issue by hhhh12333** [wangeditor-team/wangEditor#1959]
需要上传附件  比如一些压缩包、文档之类的  要怎么实现   ？？？还有我在添加新的菜单项的时候好像实现不了

**Comment by q378532364** [comment]
附件可以自己另开上传功能实现

**Comment by wangfupeng1988** [comment]
v5 已经支持上传附件 https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment

v4 不再升级新功能了
