### ISSUE TITLE
顶部工具栏的移动端适应

### ISSUE THREAD

**Issue by coder-xsy** [wangeditor-team/wangEditor#1962]
工具栏中含有过多的操作选项之后，会超出移动端的宽度，在移动端就无法自动换行，需要手动添加flex-wrap:wrap属性设置才能自动换行

**Comment by YIJIARU** [comment]
给工具栏添加CSS属性flex-wrap : wrap

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈”
