### ISSUE TITLE
看到官网上面兼容ie10+，但是官网在ie10打开，编辑器是不能用的，请问怎么解决?

### ISSUE THREAD

**Issue by wangdedi1990** [wangeditor-team/wangEditor#1970]
[
![image](https://user-images.githubusercontent.com/28214000/58145598-49133180-7c85-11e9-96aa-6bd2d2d64c12.png)
](url)

**Comment by heyikang** [comment]
IE10+ IE10是没办法用啊

**Comment by q378532364** [comment]
换浏览器换浏览器，后面兼容我们会出方案，敬请期待

**Comment by Zefeng666** [comment]
> 换浏览器换浏览器，后面兼容我们会出方案，敬请期待
求方案。。。
