### ISSUE TITLE
body元素上有多次重复的事件绑定

### ISSUE THREAD

**Issue by Gitby-Leo** [wangeditor-team/wangEditor#1974]
在demo示例中多次触发panel时，通过getEventListeners(document.querySelector('body'))发现相同的click事件重复绑定了多次，目前是禁用了body上的click触发
要如何同时使用body和按钮X的click去关闭panel呢

**Comment by q378532364** [comment]
记录该问题，会安排在 V4 版本中解决，感谢反馈
