### ISSUE TITLE
光标自动换行问题

### ISSUE THREAD

**Issue by YuFy1314** [wangeditor-team/wangEditor#1977]
"wangeditor": "^3.1.1"

在移动端下使用:

这个bug测试于谷歌浏览器F12的手机模式和真机验证都存在此bug:

1. 首先在编辑器中第一行输入几个文字: 
![image](https://user-images.githubusercontent.com/24446694/58621241-8027b980-82fb-11e9-9fac-39300ffc6d7e.png)

2. 回车, 再从第二行输入几个文字: 
![image](https://user-images.githubusercontent.com/24446694/58621288-9b92c480-82fb-11e9-9778-f1a8cf10a2c5.png)

3. 再回到第一行中:
![image](https://user-images.githubusercontent.com/24446694/58621332-b06f5800-82fb-11e9-91da-7e4ceccd7158.png)

4. 继续在第一行输入: 
![image](https://user-images.githubusercontent.com/24446694/58621388-d7c62500-82fb-11e9-9eef-a34a9c89dc50.png)

5. 将后面输入的这四个字输入到编辑器中, 然后光标会自动跑到第二行末尾处: 
![image](https://user-images.githubusercontent.com/24446694/58621508-21167480-82fc-11e9-9ce5-2e4fcd98f0f1.png)

这么一看, 文字少无所谓, 但是一篇或半篇文章下来, 回去看到了前面某一行不合适, 想编辑的时候, 还没等输入完, 光标就会强制性到文章最底部的末尾位置, 者体验度就特别不好了

如果是打英文字母, 第一个字母刚打进第一行中, 接着后面输入的每一个字母都到了第二行中, 因为第一个字母输入完之后, 光标会强制性到第二行的末尾, 这个就更头疼了

@wangfupeng1988 用了很多时间看了api且使用了您的这款插件, 整体感觉还不错, 最起码扩展性很好, 用了很多时间清楚地描述了这个问题, 希望您可以重视一下, 在线等... 谢谢

**Comment by YuFy1314** [comment]
我在F12下看了一下输入的DOM, 也就是这两个p标签和他们的父级, 每次输入一个字符, 他们都会闪一下, 这个意思是不是监听了呢? 类似于输入一个字符就会刷新一下这个编辑器, 所以将光标移到了最后的位置
![image](https://user-images.githubusercontent.com/24446694/58622634-a3a03380-82fe-11e9-9ae9-a0047c84df54.png)

**Comment by leizhongli** [comment]
这其实不算是光标换行问题，他是每次都会把光标定位到最后的位置，我也很头疼，这个问题确实需要重视

**Comment by YuFy1314** [comment]
> 这其实不算是光标换行问题，他是每次都会把光标定位到最后的位置，我也很头疼，这个问题确实需要重视

所以我换了一个编辑器

**Comment by leizhongli** [comment]
> > 这其实不算是光标换行问题，他是每次都会把光标定位到最后的位置，我也很头疼，这个问题确实需要重视
> 
> 所以我换了一个编辑器

你现在用的啥编辑器？我之前了解 uEditor和kindEditor 是把光标定位到最前面了吧

**Comment by YuFy1314** [comment]
@leizhongli 由于我是开发的移动端项目, 用的是vue框架, 所以我用的是vue-quill-editor  比较好用

**Comment by CNMneuropathy** [comment]
没作者出来解决一下吗？

**Comment by YuFy1314** [comment]
> 没作者出来解决一下吗？

我感觉解決不了了, 换插件吧

**Comment by CNMneuropathy** [comment]
但是官网demo光标并没有出现这个问题啊。难道是因为用在vue上才有这个问题吗

**Comment by YuFy1314** [comment]
不清楚, 我是在移动端vue框架中用的, 就有这个问题

**Comment by CNMneuropathy** [comment]
我发现了，我们之所以会出现这个问题可能是在写的时候有问题，因为我们的文字P标签在变的时候，P标签外的div也会跟着变。官网的demo并不会出现这个问题

**Comment by YuFy1314** [comment]
我那个项目已经做完了, 用的别的插件, 你可以看看这个问题出在哪, 然后把解决方式写在这

**Comment by wanglin447563345** [comment]
有解决的吗   我也遇到这问题 vue监听设置内容，插入table，在table里输入文字光标会跳

**Comment by YuFy1314** [comment]
暂未解决

**Comment by yoyoluxi** [comment]
问题应该是重复更新文本内容了  所以导致了光标的移动  建议改成不可控 离开输入框后再保存

**Comment by jwchan1996** [comment]
问题的关键应该是重复更新了编辑器文本内容了（导致内容重新渲染）
我的 vue 文件如下所示，没有出现当前 issue 光标后跳的情况
```JavaScript
<template>
  <div>
    <div ref="editor" style="text-align:left"></div>
  </div>
</template>

<script>
import E from 'wangeditor'

export default {
  name: 'editor',
  //编辑器初始化html内容
  props: ['editorInitContent'],
  data () {
    return {
      Editor: null
    }
  },
  computed: {
    contentChange(){
      return this.editorInitContent
    }
  },
  watch: {
    contentChange(html){
      //编辑器显示初始化html内容
      this.Editor.txt.html(html)
    }
  },
  mounted() {
    this.initEditor()
  },
  methods: {
    initEditor(){
      this.Editor = new E(this.$refs.editor)
      this.Editor.customConfig.onchange = (html) => {
        //将数据传递给父组件
        this.$emit('editorContentChange', html)
      }
      this.Editor.create()
    }
  }
}
</script>

<style scoped>
</style>
```

**Comment by liuz666** [comment]
光标乱跳的原因是：因为在VUE组件中监听了当前值，富文本框的值更新后，光标就会跳到最后。
解决方案：定义一个开关，flag = false; 然后在watch监听里面加个判断，flag==false时候，才重新赋值。最后在富文本框onchange事件哪里设置一下 flag=true; 
亲测，能解决光标乱跳问题。

**Comment by q378532364** [comment]
V4 即将发布，已解决该问题，感谢反馈

**Comment by cshenger** [comment]
> 光标乱跳的原因是：因为在VUE组件中监听了当前值，富文本框的值更新后，光标就会跳到最后。
> 解决方案：定义一个开关，flag = false; 然后在watch监听里面加个判断，flag==false时候，才重新赋值。最后在富文本框onchange事件哪里设置一下 flag=true;
> 亲测，能解决光标乱跳问题。

我TM最后就是这么解决的
