### ISSUE TITLE
关于从word文档里粘贴过滤解决方案

### ISSUE THREAD

**Issue by flashmecn** [wangeditor-team/wangEditor#1981]
`        editor2.customConfig.pasteTextHandle = function (content) {
            var node=document.createElement("span");
            node.innerHTML=DOMPurify.sanitize(content);
            node.querySelectorAll('td,th').forEach(function(el){
                el.innerHTML=el.innerHTML.replace(/<\/?p[^>]*>/gi,'');//去除table内的P标签
            });
            node.querySelectorAll('*').forEach(function(el){
                el.removeAttribute("class");
                el.removeAttribute("style");
                el.removeAttribute("font");
                el.removeAttribute("size");
                el.removeAttribute("width");
                el.removeAttribute("height");
                el.removeAttribute("valign");
                el.removeAttribute("border");
            });
            return node.innerHTML;
        }`
使用dompurify.js先过滤一波，然后又forEach过滤了一波元素属性

**Comment by flashmecn** [comment]
> ` editor2.customConfig.pasteTextHandle = function (content) { var node=document.createElement("span"); node.innerHTML=DOMPurify.sanitize(content); node.querySelectorAll('td,th').forEach(function(el){ el.innerHTML=el.innerHTML.replace(/<\/?p[^>]*>/gi,'');//去除table内的P标签 }); node.querySelectorAll('*').forEach(function(el){ el.removeAttribute("class"); el.removeAttribute("style"); el.removeAttribute("font"); el.removeAttribute("size"); el.removeAttribute("width"); el.removeAttribute("height"); el.removeAttribute("valign"); el.removeAttribute("border"); }); return node.innerHTML; }`
> **使用dompurify.js先过滤一波，然后又forEach过滤了一波元素属性**

**Comment by flashmecn** [comment]
**这里使用了dompurify.js 并forEach所有元素，不知道有没有更好的方案？**

**Comment by flashmecn** [comment]
目的是想尽可能保留样式，并留下干净的html代码，**这里使用了dompurify.js 并forEach所有元素，不知道有没有更好的方案？**

**Comment by onaug6th** [comment]
这边发现word文档中拷出来的内容有的是在注释块里面的，可以用这个方法来去掉大部分内容
```js
//  清除注释块
pasteHtml = pasteHtml.replace(/<!--[\w\W\r\n]*?-->/gmi, '');
//  清除<w:xxx> 这样的标签
pasteHtml = pasteHtml.replace(/<(w.*).+?>/igm, '');
```

**Comment by GalinaGao123** [comment]
后面的过滤属性可以用dompurify的配置项。var clean = DOMPurify.sanitize(dirty, {FORBID_ATTR: ['style']});


我也是看了你的答案找到的dompurify的库。哈哈，非常感谢。

**Comment by q378532364** [comment]
V4 已经发布，已解决该问题，感谢反馈
