### ISSUE TITLE
粘贴腾讯文档excel出现数据丢失格式错乱问题

### ISSUE THREAD

**Issue by littlefirefly** [wangeditor-team/wangEditor#1982]
粘贴腾讯文档excel时出现了数据丢失格式错乱问题。
查看源码是
// 过滤 data-xxx 属性
pasteHtml = pasteHtml.replace(/\s?data-.+?=('|").+?('|")/igm, '');
这一段出现了问题，会将所有包含data-的html替换掉，而不只是 data-xxx 属性
我的解决方法是/\s?data-.+?=('|").+?('|")/替换为/\s+data-.+?=('|").+?('|")/ 即可

**Comment by q378532364** [comment]
V4 已经发布，已解决该问题，感谢反馈
