### ISSUE TITLE
设置高度无效，固定为300px，业余选手修改了一下

### ISSUE THREAD

**Issue by wangxu627** [wangeditor-team/wangEditor#1988]
_initDom方法内：
原代码:
$textContainerElem.css('border', '1px solid #ccc').css('border-top', 'none').css('height', "300px");

修改为:
var dftHeight = $toolbarSelector[0].clientHeight > 0 ? $toolbarSelector[0].clientHeight - 32 : 300;

$textContainerElem.css('border', '1px solid #ccc').css('border-top', 'none').css('height', dftHeight + "px");

本人菜鸟，不知道改了会不会有其他问题，目前自己能用，减的32px是上面toolbarElem的高度

使用的时候 就可以手动指定高度了,不指定的话就是默认的300
`<div id="editor_content" style="width:800px;;height:600px;"></div>`

**Comment by Jiej009** [comment]
非常有效 反正我贴进来就能用 完美解决
