### ISSUE TITLE
重复提个ISSUE，内容中的table样式不对！

### ISSUE THREAD

**Issue by yangfan0095** [wangeditor-team/wangEditor#1990]
![image](https://user-images.githubusercontent.com/21197847/59912304-59ffc000-9448-11e9-8226-38ea4bbc9de6.png)
插入表格 默认给出来 没有没有border

版本 "wangeditor": "^3.1.1",

**Comment by yangfan0095** [comment]
目前修复方法 在回调里面正则匹配 替换
```
 html = html.replace(/<table border="0"/g, '<table border="1"');

```

**Comment by tryingpzm** [comment]
啊，我也发现这个问题，只能自己先替换下了
