### ISSUE TITLE
请问编辑器只有create没有销毁吗？

### ISSUE THREAD

**Issue by Eminlin** [wangeditor-team/wangEditor#1991]
在官网中没有找到相应的销毁方法

**Comment by hiEmin** [comment]
只看到wangEditor2里面有提供销毁

**Comment by strugglebak** [comment]
没看到啊，你是在哪里看到有销毁 api 的？

**Comment by hiEmin** [comment]
> 没看到啊，你是在哪里看到有销毁 api 的？

wangEditor2 里面有提供的：
https://www.kancloud.cn/wangfupeng/wangeditor2/120001

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
