### ISSUE TITLE
删除换行时，标签变为style

### ISSUE THREAD

**Issue by VanityOfWall** [wangeditor-team/wangEditor#2003]
![TIM图片20190704114759](https://user-images.githubusercontent.com/48897610/60638624-ab00b280-9e51-11e9-8f91-93b51c48bde1.png)
![TIM图片20190704114835](https://user-images.githubusercontent.com/48897610/60638625-ab994900-9e51-11e9-9592-a5997cb811c2.png)
如第一张图所示，编辑器写入了三行文字，第一行和第三行为h1标签，第二行只是一个换行符。
然后在第三行开头删除第二行的换行符的时候，h1标签变为了span标签和style样式，是否能够保持原有的h1标签呢

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
