### ISSUE TITLE
能支持上传视频链接吗

### ISSUE THREAD

**Issue by Yan502** [wangeditor-team/wangEditor#2008]
我想在Vue 里用我改wangEditor.js 能支持视频链接上传了 可是 这个wangEditor.js不能引入到我Vue的框架来里面来

**Comment by richex-cn** [comment]
建议视频还是用类似于附件管理的形式吧，参考：<https://www.kancloud.cn/wangfupeng/wangeditor3/335785>

如果觉得麻烦可以在编辑器之外添加一个视频上传按钮，然后用 `editor.txt.append('<video src="xxx"></video>')` 追加就行。
