### ISSUE TITLE
输入内容时，焦点不在P标签内

### ISSUE THREAD

**Issue by doriswhl** [wangeditor-team/wangEditor#2011]
![image](https://user-images.githubusercontent.com/48148599/61440102-54c56080-a975-11e9-8079-89d94a8443de.png)
如图，输入内容时焦点位置不对

**Comment by YIJIARU** [comment]
解决了么？我也遇到了，这个问题导致点击换行的时候自动生成的是一个div而不是p标签，且p标签里面和P标签外面的默认样式也不一样。

**Comment by doriswhl** [comment]
解决了，我的原因是因为更新的时候没有判断是否有内容，直接复制了空值，把原来的P标签覆盖了


------------------ 原始邮件 ------------------
发件人: "YIJIARU"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 上午10:32
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>;
抄送: "王海利"<644981049@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wangfupeng1988/wangEditor] 输入内容时，焦点不在P标签内 (#2011)




解决了么？我也遇到了，这个问题导致点击换行的时候自动生成的是一个div而不是p标签，且p标签里面和P标签外面的默认样式也不一样。

**Comment by YIJIARU** [comment]
> 解决了，我的原因是因为更新的时候没有判断是否有内容，直接赋值了空值，把原来的P标签覆盖了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "YIJIARU"<notifications@github.com>; 发送时间: 2019年8月1日(星期四) 上午10:32 收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>; 抄送: "王海利"<644981049@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [wangfupeng1988/wangEditor] 输入内容时，焦点不在P标签内 (#2011) 解决了么？我也遇到了，这个问题导致点击换行的时候自动生成的是一个div而不是p标签，且p标签里面和P标签外面的默认样式也不一样。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.



> 解决了，我的原因是因为更新的时候没有判断是否有内容，直接赋值了空值，把原来的P标签覆盖了
> [...](#)
> ------------------ 原始邮件 ------------------ 发件人: "YIJIARU"<notifications@github.com>; 发送时间: 2019年8月1日(星期四) 上午10:32 收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>; 抄送: "王海利"<644981049@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [wangfupeng1988/wangEditor] 输入内容时，焦点不在P标签内 (#2011) 解决了么？我也遇到了，这个问题导致点击换行的时候自动生成的是一个div而不是p标签，且p标签里面和P标签外面的默认样式也不一样。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

谢谢，解决了问题。只是我用的文档提供的editor.txt.clear()方法，也出现这个情况。把这个方法删除就正常了。
