### ISSUE TITLE
有序列表 无需列表编辑后 撤销 内容会丢失

### ISSUE THREAD

**Issue by yangfan0095** [wangeditor-team/wangEditor#2015]
有序列表 无需列表编辑后 撤销 内容会丢失
复现步骤
官网的编辑器 
1 随便输如几行字
2 点击有序列表或无需列表 将文字变成列表
3 点击撤销会发现 输入的文字丢失了一行

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
