### ISSUE TITLE
工具菜单的样式问题

### ISSUE THREAD

**Issue by wujing080** [wangeditor-team/wangEditor#2024]
![image](https://user-images.githubusercontent.com/17642589/62034860-528abe00-b221-11e9-88a9-6f243f1188d8.png)

>  flex-wrap: wrap;
这个样式没有启用，导致页面宽度发生改变工具菜单没有换行排列

**Comment by YIJIARU** [comment]
写成行业样式或者加上!important就能生效了。本身就是flex，只需要加上flex-wrap : wrap就会换行
