### ISSUE TITLE
嵌入react项目中，报错The tag <wangeditor> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

### ISSUE THREAD

**Issue by Clrs-D** [wangeditor-team/wangEditor#2025]
完全显示不了，查看dom节点，发现是：<wangeditor></wangeditor>，报错：The tag <wangeditor> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

import React, { Component } from 'react';
import E from 'wangeditor';

class WEditer  extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      editorContent: '',
    };
  }

  componentDidMount() {
    const elem = document.getElementById('edit');
    const editor = new E(elem);
    // 使用 onchange 函数监听内容的变化，并实时更新到 state 中
    editor.customConfig.onchange = (html) => {
      this.setState({
        editorContent: html,
      });
    };
    editor.create();
  }

  render() {
    return (
      <div style={{ background: '#fff' }}>
        {/* 将生成编辑器 */}
        <div ref="editorElem" style={{ textAlign: 'left' }} classID="edit" />
      </div>
    );
  }

}

export default WEditer ;

**Comment by Liaozhenting** [comment]
React设定,组件首字母要大写.小写会被认为是原本的dom.
tag <wangeditor> 要改成 <Wangeditor>
