### ISSUE TITLE
真希望你的编辑区高度，我可以自己设置

### ISSUE THREAD

**Issue by CommonN** [wangeditor-team/wangEditor#2034]
![image](https://user-images.githubusercontent.com/38940157/62607405-a3d93280-b930-11e9-8250-3059ae52e23d.png)

**Comment by lalaxyv** [comment]
把这个值改成 100%, 引用时， 设DIV高度就行。好像

**Comment by imziyang** [comment]
[https://www.kancloud.cn/wangfupeng/wangeditor3/335771](url)
将菜单和编辑区域分离就可以自己设置 class 了

**Comment by jieruian** [comment]
很简单的，你把标签取出来修改就可以了，我使用的vue，修改如下
editor.$textContainerElem['0'].style.height = '400px'

**Comment by a835100635** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
