### ISSUE TITLE
首次粘贴富文本编辑器内的文本失败

### ISSUE THREAD

**Issue by shenmaxg** [wangeditor-team/wangEditor#2035]
以官网首页 wangeditor.com的富文本为例
1.使用 ctrl +a全选富文本内的文字。
2. ctrl ＋c复制。
3.光标点击文字尾部，全选状态消失。
4.ctrl＋v黏贴
以上操作完成后，会发现文本并没有黏贴，只是在末尾增加了一个空格，再次ctrl＋ v 后成功。
浏览器环境 chrom 76
休息，以上操作中间不能有额外的点击。

**Comment by cs7233688** [comment]
查看源码，发现在取消全选的点击中，selection依然能打出之前选中的内容，也就是说那次点击并没有真的让文档取消全选，至于为什么，完全不懂。希望作者能帮忙看一看。

**Comment by cs7233688** [comment]
别沉呀，有人遇到过这个问题吗？

**Comment by BoyJun** [comment]
asdasda

**Comment by BoyJun** [comment]
adasdasdasd

**Comment by xueleilei** [comment]
> 别沉呀，有人遇到过这个问题吗？

也遇到这个问题了。

**Comment by zhouzhuang95** [comment]
有解决的吗
