### ISSUE TITLE
上传七牛时，不能调整图片大小，也不出现调整tab框；

### ISSUE THREAD

**Issue by shanchunyan** [wangeditor-team/wangEditor#2037]
上传七牛时，不能调整图片大小，也不出现调整图片tab框；
![image](https://user-images.githubusercontent.com/42674172/62756897-f7bc5680-baab-11e9-94da-9fd62a6cfbff.png)
![image](https://user-images.githubusercontent.com/42674172/62756922-14588e80-baac-11e9-93a2-cc1c103f152e.png)

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
