### ISSUE TITLE
内容区输入超出后滚动条的样式怎么修改？

### ISSUE THREAD

**Issue by warmer911** [wangeditor-team/wangEditor#2043]
![Uploading image.png…]()

**Comment by warmer911** [comment]
![image](https://user-images.githubusercontent.com/28683760/63313038-bc384c80-c335-11e9-8889-7c8e67f4ded7.png)

**Comment by junhoo** [comment]
<style>
.w-e-text {
  width: 200px;
  height: 100px;
  overflow: auto;
}
/*当前滚动盒模型的样式*/
.w-e-text::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}
/*正常情况下滑块的样式*/
.w-e-text::-webkit-scrollbar-thumb {
  background-color: rgba(0, 0, 0, .05);
  border-radius: 10px;
  -webkit-box-shadow: inset 1px 1px 0 rgba(0, 0, 0, .1);
}
/*鼠标悬浮在该类指向的控件上时滑块的样式*/
.w-e-text:hover::-webkit-scrollbar-thumb {
  background-color: rgba(0, 0, 0, .2);
  border-radius: 10px;
  -webkit-box-shadow: inset 1px 1px 0 rgba(0, 0, 0, .1);
}
/*鼠标悬浮在滑块上时滑块的样式*/
.w-e-text::-webkit-scrollbar-thumb:hover {
  background-color: rgba(0, 0, 0, .4);
  -webkit-box-shadow: inset 1px 1px 0 rgba(0, 0, 0, .1);
}
/*正常时候的主干部分*/
.w-e-text::-webkit-scrollbar-track {
  border-radius: 10px;
  -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0);
  background-color: white;
}
/*鼠标悬浮在滚动条上的主干部分*/
.w-e-text::-webkit-scrollbar-track:hover {
  -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .4);
  background-color: rgba(0, 0, 0, .01);
}
</style>
