### ISSUE TITLE
word 文档粘贴后会生成全局 h1 样式，影响页面其它样式

### ISSUE THREAD

**Issue by kennyzuo** [wangeditor-team/wangEditor#2049]
问题描述：
复制粘贴 word 文档的内容到富文本中，保存数据，随后在展示数据的时候发现，富文本的内容会生成全局的 H1 样式，对页面其它内容造成影响。

请问一下，这是粘贴的内容问题，还是富文本本身添加的啊？

**Comment by kennyzuo** [comment]
补充： 粘贴的文档，内部自动生成了好多 <style></style>节点

**Comment by pkptzx** [comment]
有很多无用的标签...搞不成...别的编辑器还有个自动过滤word粘贴时产生的无用标签,但这个...啥都没有提供....

导致项目产生了乱七八糟的展示
`<a id="tt" segoe="" ui',="" 'lucida="" grande',="" helvetica,="" arial,="" 'microsoft="" yahei',="" freesans,="" arimo,="" 'droid="" sans',="" 'wenquanyi="" micro="" hei',="" 'hiragino="" sans="" gb',="" gb="" w3',="" fontawesome,="" sans-serif;="" font-size:="" 16.799999237060547px;="" font-style:="" normal;="" font-variant-caps:="" font-weight:="" 500;="" letter-spacing:="" orphans:="" auto;="" text-align:="" start;="" text-indent:="" 0px;="" text-transform:="" none;="" white-space:="" widows:="" word-spacing:="" -webkit-text-size-adjust:="" -webkit-text-stroke-width:="" 0px;"=""></a><spansegoe ui',="" 'lucida="" grande',="" helvetica,="" arial,="" 'microsoft="" yahei',="" freesans,="" arimo,="" 'droid="" sans',="" 'wenquanyi="" micro="" hei',="" 'hiragino="" sans="" gb',="" gb="" w3',="" fontawesome,="" sans-serif;="" font-size:="" 16.799999237060547px;="" font-style:="" normal;="" font-variant-caps:="" font-weight:="" 500;="" letter-spacing:="" orphans:="" auto;="" text-align:="" start;="" text-indent:="" 0px;="" text-transform:="" none;="" white-space:="" widows:="" word-spacing:="" -webkit-text-size-adjust:="" -webkit-text-stroke-width:="" background-color:="" rgb(255,="" 255,="" 255);="" display:="" inline="" !important;="" float:="" none;"="">,`

**Comment by flashmecn** [comment]
https://github.com/wangfupeng1988/wangEditor/issues/1981
我的解决方案是加载dompurify.js过滤乱七八糟的标签，在.customConfig.pasteTextHandle函数编写自己要过滤的标签
