### ISSUE TITLE
vue onchange事件不触发

### ISSUE THREAD

**Issue by JuliannaGu** [wangeditor-team/wangEditor#2050]
editor.customConfig.onchange = (html) => {
          console.log('dsfdsfd', html)
      }
onchange事件里什么都打印不出来，没有触发

**Comment by Hench10** [comment]
注册完 onchange 之后再 editor.create();

**Comment by light212** [comment]
你把全部代码贴出来，看看

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
