### ISSUE TITLE
还是希望 wangEditor能够绑定到textarea

### ISSUE THREAD

**Issue by logofun** [wangeditor-team/wangEditor#2051]
原因在于
 wangEditor绑定在div上，对于前后台传值，还需借助一个隐藏的textarea.
真的希望 wangEditor能够绑定到textarea
这样前后台传值时方便多了，不需要监听onchange 且需转存一遍文本内容

**Comment by itshizhan** [comment]
为什么要借助隐藏的textarea？使用方法有误？

**Comment by logofun** [comment]
form表单提交时，不能提交div的值，可以直接提交textarea的内容
看下手册，有这个处理的内容

**Comment by itshizhan** [comment]
form 提交只是一种选择，推荐 ajax 提交。绑定div 有更多的好处的。
如果你使用vue、react 或angular 的话，都不是问题
