### ISSUE TITLE
编辑图片宽度的建议和自行处理的暂定方法

### ISSUE THREAD

**Issue by logofun** [wangeditor-team/wangEditor#2056]
在插入图片并完成编辑区回显时，一般会显示原图大小样式。
这时当选择这个回显的图片的时，再点击菜单栏的[上传图片]按钮，会显示编辑图片框
如图
![image](https://user-images.githubusercontent.com/22115036/64395401-a622cf80-d049-11e9-8732-46813fb580f5.png)
编辑宽度有30% 50%和100%三个选项
一般情况下是够用了，但还是想钻个角尖——可否进一步自定义宽度比例呢？
比如设可input 由编辑者输入宽度的比例，比如23%，然后再在样式中体现。
作为建议给开发者。

**Comment by logofun** [comment]
由于我配置图片回显大小时，需要增设一个10%的宽度，因此，我对wangEditor.js中tabsConfig项做了修改，形成下图效果
![image](https://user-images.githubusercontent.com/22115036/64395787-f2bada80-d04a-11e9-9016-a7134cb94b24.png)
算是一个暂定的自行处理方法吧

处理方法如下：
js文件中约2669行
```
_createEditPanel: function _createEditPanel() {
//增加id 10%
var width10 = getRandom('width-10');
```

然后再在下方的
```
// tab 配置
        var tabsConfig = [{
```
中增设一个html元素段
内容为
`<button id="' + width10 + '" class="left">10%</button>\n`
我放在<button id="' + width30 + '" class="left">30%</button>\n之前了

再处理显示代码
即在events: [中增加
```
events: [{
                selector: '#' + width10,
                type: 'click',
                fn: function fn() {
                    var $img = editor._selectedImg;
                    if ($img) {
                        $img.css('max-width', '10%');
                    }
                    // 返回 true，表示该事件执行完之后，panel 要关闭。否则 panel 不会关闭
                    return true;
                }
            },
```
重新引入该js即可

**Comment by logofun** [comment]
进一步改进
直接输入百分比
如下图
![image](https://user-images.githubusercontent.com/22115036/64398203-7aa4e280-d053-11e9-91ee-7f8fe00ca8e3.png)

方法和上述一样
```
_createEditPanel: function _createEditPanel() {
//增加id 百分比输入框 和确定按钮
var widthPercent =getRandom('width-percent');
var percentBtn = getRandom('percent-btn');

```
增加样式

// tab 配置
        var tabsConfig = [{
中增加
`<input id ="' + widthPercent + '"  type="text" style="width:50%" placeholder="请输入百分比"/><button id="' + percentBtn + '" class="gray">\u786E\u5B9A</button>\n`

然后在事件中增加按钮[确定]事件
```
events: [{
                selector: '#' + percentBtn,
                type: 'click',
                fn: function fn() {
                    var $img = editor._selectedImg;
                    if ($img) {
						var $widthPercent = $('#' + widthPercent);
						var percentval = $widthPercent.val().trim();
						if(percentval){
                        $img.css('max-width', percentval);
						}
                    }
                    // 返回 true，表示该事件执行完之后，panel 要关闭。否则 panel 不会关闭
                    return true;
                }
            },
```

重新引入 有效
需要增补的内容是 还需再加一个输入值的判断，输入值只能是‘’37%‘’这种形式。

这个判断我就没有再加了
请高手门帮忙补一下吧

**Comment by logofun** [comment]
再加把劲，嘿嘿
if(percentval){   处 前后加入正则表达式判断输入的是否为%百分比

```
var patt1 = /^\d+%$/;
if(percentval && patt1.test(percentval)){
```

**Comment by SWKende** [comment]
非常棒啊，输入调整大小这个帮大忙了

**Comment by logofun** [comment]
@SWKende
呵呵 谢谢表扬

**Comment by MMstarry** [comment]
@logofun 大佬，怎么重新引入该JS

**Comment by logofun** [comment]
@MMstarry 按所说的直接对 wangEditor.js 进行内容修改，保存后
还是有手册所说的引入即可，我没有更改原文件名啊
`<script src="wangEditor.js></script>"`
如果是wangEditor.min.js
建议对修改后的wangEditor.js进行压缩替换即可

**Comment by MMstarry** [comment]
谢谢大佬，解决了 @logofun

**Comment by StoneCode5** [comment]
很好的解决了问题

**Comment by iaminvictus1993** [comment]
mark,图片自定义大小

**Comment by logofun** [comment]
woo!!!!
楼上厉害 @iaminvictus1993

**Comment by zl939144892** [comment]
@wangfupeng1988 能否 merge 一下这个功能

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
