### ISSUE TITLE
复制输入框的文本，第一次粘贴会失效

### ISSUE THREAD

**Issue by xueleilei** [wangeditor-team/wangEditor#2057]
输入框内随便输入几个文字，然后全选输入框的内容ctrl+c复制，然后光标定位到文本最后面，ctrl+v第一次会是空的，再次ctrl+v才会粘贴成功。

**Comment by zhouzhuang95** [comment]
请问这个问题解决了吗？

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
