### ISSUE TITLE
改变格式之后，马上执行插入HTML操作，会把刚才更改的文本删除

### ISSUE THREAD

**Issue by AiKoSoSuBeTe** [wangeditor-team/wangEditor#2064]
比如一行文本，abcdefg，对bcdef执行加粗（或者其他操作），变成a**bcdef**g。之后点击bcdef的中间，让**选取区域收缩成1点**，这时如果马上执行`editor.cmd.do('insertHTML', html)`，会把bcdef删掉。
在`editor.cmd.do('insertHTML', html)`之前在代码里saveRange就能正常运行了

**Comment by LunaZxg** [comment]
加粗或者加背景色等这些样式如何获取呢

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
