### ISSUE TITLE
在vue中使用element select组件，下拉框覆盖到编辑器上时无法获取焦点

### ISSUE THREAD

**Issue by 612-A-34** [wangeditor-team/wangEditor#2065]
![image](https://user-images.githubusercontent.com/52451080/65122398-71d4e900-da23-11e9-994c-1481bc5b3e8f.png)
无法选择下拉框的内容

**Comment by RUANLI** [comment]
同求 。。。。

[图片]
![GCP71XTCQOQ8PCI(O1$L%{T](https://user-images.githubusercontent.com/43004937/65479753-42a9f600-dec1-11e9-84af-4b20f16b2793.png)

**Comment by BlackCodingCat** [comment]
设置一下.w-e-medu的层级就可以了
.w-e-toolbar .w-e-menu{z-index: 0;}

**Comment by RUANLI** [comment]
感谢！




------------------ 原始邮件 ------------------
发件人: "沈佳棋"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 上午9:51
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>;
抄送: "及他"<1455352355@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wangfupeng1988/wangEditor] 在vue中使用element select组件，下拉框覆盖到编辑器上时无法获取焦点 (#2065)




设置一下.w-e-medu的层级就可以了
 .w-e-toolbar .w-e-menu{z-index: 0;}

**Comment by Ele-Cat** [comment]
> 设置一下.w-e-medu的层级就可以了
> .w-e-toolbar .w-e-menu{z-index: 0;}

有效果，感谢
