### ISSUE TITLE
关于视频上传

### ISSUE THREAD

**Issue by luoying122** [wangeditor-team/wangEditor#2066]
作者您好，我这边近期nuxt项目中需要用到上传视频功能，目前是页面中抓取点击视频icon效果触发element上传。但是原生态的那个上传链接弹窗还是会出现，虽然用DOM元素样式设置，效果不是特别好。

想要实现的效果是，把npm装进去的js+css直接复制到本地目录下，然后修改video方法增加一个上传视频的入口。然后出现的问题是：

let E =  require('项目localPath/wangEditor.js'), 
这个一直无法成功引入.虽然官网上有webpack中的使用方法，还是不太行。

**Comment by luoying122** [comment]
作者能否指导下``

**Comment by yangfandashuaige** [comment]
// 客户端渲染的时候加载模块
if (process.client) {
  E = require('wangeditor')
}
