### ISSUE TITLE
如何让我渲染的默认内容变成不可编辑的

### ISSUE THREAD

**Issue by Rayyangyang** [wangeditor-team/wangEditor#2070]

**Comment by justholdon** [comment]
我的后端返回的html 渲染以后 默认是不可以编辑的   里面的元素是td，我正在想怎么把它弄成默认可编辑的

**Comment by Rayyangyang** [comment]
> 我的后端返回的html 渲染以后 默认是不可以编辑的 里面的元素是td，我正在想怎么把它弄成默认可编辑的

你请求的数据 渲染到前端就不可以编辑？ 怎么做到的哦，我请求到的数据 只能自己在前端设置 不可编辑

**Comment by CarylWu** [comment]
> 我的后端返回的html 渲染以后 默认是不可以编辑的 里面的元素是td，我正在想怎么把它弄成默认可编辑的

请问你的问题解决了吗，我这里是后端获取了元素设置进去无法换行
