### ISSUE TITLE
中文输入法, 在输入法联想的结果中用鼠标点击某个文字, 内容出现在编辑器中, 但是没有触发onchange方法

### ISSUE THREAD

**Issue by fenglian219** [wangeditor-team/wangEditor#2072]

**Comment by he-bill** [comment]
在wangEditor.js的4452行加入代码_this.change && _this.change();就可以了，希望能帮助到你

**Comment by 405396731** [comment]
> 在wangEditor.js的4452行加入代码_this.change && _this.change（）;就可以了，希望能帮助到你

这个可以解决在本地的问题 那上线后该怎么去解决这里的资源文件问题呢
