### ISSUE TITLE
有关格式刷

### ISSUE THREAD

**Issue by LunaZxg** [wangeditor-team/wangEditor#2080]
富文本编辑器的用途会越来越多，期望尽快加上格式刷的功能

**Comment by LunaZxg** [comment]
现在项目用的版本是2.x版本的，看到手册上有扩展菜单和插件功能
有个想法是：
1 选中一部分内容（要获取这部分内容的样式，并保存起来）
2 点击格式刷
3 重新选择一部分内容（将保留的样式赋予这部分新选区）
4 再次点击格式刷（清空保存的样式）



现在有个问题是：
在执行第一步的时候，我获取不到选中选区的样式
像这种类似斜体<i>的标签可以通过getSelfOrParentByName方法获取到并组合标签内容给到新选区（第三步），但是类似于color等这些样式怎么获取呢

**Comment by a835100635** [comment]
已记录该问题，感谢反馈
