### ISSUE TITLE
vue中使用，销毁应该怎么写

### ISSUE THREAD

**Issue by leolibao** [wangeditor-team/wangEditor#2081]
尝试了几种方法，都没有效果，而且放在dialog中时，第一次点击的时候不会出现，然后继续点击的时候每次点击都会重复出现

**Comment by LayneYangBlack** [comment]
我用this.$refs.xxx.html=""  你可以试试

**Comment by Nuh123** [comment]
加载的问题设一个定时器，50ms就足够，重复的问题，全局设置一个变量，判断是否已经有富文本框。再结合下面的方法，应该就合适了。（我是来找下面的方法的）
