### ISSUE TITLE
光标乱跳问题

### ISSUE THREAD

**Issue by wuhao775373334** [wangeditor-team/wangEditor#2084]
作者你好，我现在遇到一个问题，找了很久也没发现一个解决的类似的问题，我的问题是：
在我输入文字时或者按空格亦或是敲退格键时， 我的光标总是会往我当前文本位置的前面跳，有的时候跳多少字符位还不一样。 有时候就直接跳到我刚开始输入文本的位置。

**Comment by cuteProgram** [comment]
我也遇到相同的问题，不知道什么原因
