### ISSUE TITLE
编辑器里，表格中ctrl+v粘贴无效，右键粘贴可以

### ISSUE THREAD

**Issue by baggiomygod** [wangeditor-team/wangEditor#2085]
编辑器里，表格中ctrl+v粘贴无效，右键粘贴可以
求大神，如何解决这个问题？

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by zhouzhuang95** [comment]
有大神解决了这个问题吗？

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
