### ISSUE TITLE
wangeditor3在服务器上传图片参数无法传输

### ISSUE THREAD

**Issue by Appetence** [wangeditor-team/wangEditor#2088]
服务器上传图片后台接收时参数为空

**Comment by Appetence** [comment]
var E = window.wangEditor
    var editor = new E('#kcjj')
    var $text1 = $('#text1')
    
 	editor.customConfig.debug = true;
        //配置属性名称，绑定请求的图片数据
        //controller会用到，可以随便设置，但是一定要与controller一致
         editor.customConfig.uploadImgServer = '<%=path %>/upload' 
            //自定义name,接收的时候图片文件的那么用这个
        	    editor.customConfig.uploadFileName = 'upimg';
		       	 editor.customConfig.uploadImgMaxSize = 3 * 1024 * 1024;
		        editor.customConfig.uploadImgMaxLength = 5;
		        editor.customConfig.uploadImgTimeout = 50000;//超时
		       	 editor.customConfig.uploadImgHooks = {
                before: function before(xhr, editor, files) {
                	console.log(xhr);
                	console.log(editor);
                	console.log(files);
                	
                    // 图片上传之前触发

                    // 如果返回的结果是 {prevent: true, msg: 'xxxx'} 则表示用户放弃上传
                    // return {
                    //     prevent: true,
                    //     msg: '放弃上传'
                    // }
                },
                success: function success(xhr, editor, result) {
                	uploadurl = result.data
                    // 图片上传并返回结果，图片插入成功之后触发
                    console.log("插入图片成功　success result = " + result.errno + "  path = " + result.data );
                },
                fail: function fail(xhr, editor, result) {
                    console.log(" fail result = " + result.errno + "  path = " + result.data );
                    // 图片上传并返回结果，但图片插入错误时触发
                },
                error: function error(xhr, editor) {
                	console.log(xhr)
                    // 图片上传出错时触发
                    console.log("error result = " + result.errno + "  path = " + result.data );
                },
                timeout: function timeout(xhr, editor) {
                    // 图片上传超时时触发
                    console.log("timeout result = " + result.errno + "  path = " + result.data );
                },
        		
               // 如果服务器端返回的不是 {errno:0, data: [...]} 这种格式，可使用该配置　
                //--------------添加这段程序－－－－－－－－－－－－－－－－－－
                customInsert: function (insertImg, result, editor) {
                    // 图片上传并返回结果，自定义插入图片的事件（而不是编辑器自动插入图片！！！）
                    // insertImg 是插入图片的函数，editor 是编辑器对象，result 是服务器端返回的结果
                    // 举例：假如上传图片成功后，服务器端返回的是 {url:'....'} 这种格式，即可这样插入图片：
                    //－－－－－－－－－－－修改这里－－－－－－－－－－－－－－－－－－
                    //获取返回的图片地址
                    var url = result.data;
                    insertImg(url);
                    console.log("插入图片 url = " + url );
                    // result 必须是一个 JSON 格式字符串！！！否则报错
                }
            }

         editor.customConfig.linkImgCallback = function (url) {
             console.log(url) // url 即插入图片的地址
         }
    editor.customConfig.onchange = function (html) {
        // 监控变化，同步更新到 textarea
        $text1.val(html)
        $("#content").val(html);
    }
    editor.create()
    // 初始化 textarea 的值
    $text1.text(editor.txt.html())
				function changepic(obj) {
        //console.log(obj.files[0]);//这里可以获取上传文件的name
        var newsrc=getObjectURL(obj.files[0]);
        document.getElementById('show').src=newsrc;
    }
    	 
    	//建立一個可存取到該file的url
    	    function getObjectURL(file) {
    	        var url = null ;
    	        // 下面函数执行的效果是一样的，只是需要针对不同的浏览器执行不同的 js 函数而已
    	        if (window.createObjectURL!=undefined) { // basic
    	            url = window.createObjectURL(file) ;
    	        } else if (window.URL!=undefined) { // mozilla(firefox)
    	            url = window.URL.createObjectURL(file) ;
    	        } else if (window.webkitURL!=undefined) { // webkit or chrome
    	            url = window.webkitURL.createObjectURL(file) ;
    	        }
    	        return url ;
    	    }

**Comment by StephenChyi** [comment]
给一个参考，已肉测
前端配置
let params={name:value};
this.editor.customConfig.uploadImgParams =params;
后端接口 C#
 [HttpPost]
 public async Task<IActionResult> AddFileInfo([FromBody] Object params )
{ 
//此处可以读取到params 
 }
