### ISSUE TITLE
在 vue 上拓展双向绑定时会出现光标乱闪动和删除前一步操作的问题

### ISSUE THREAD

**Issue by hellomrbigshot** [wangeditor-team/wangEditor#2091]
提供一个jsfiddle在线例子
[戳我](https://jsfiddle.net/Yeachan/efgLpsbh/26/)

在输入框快速输入 123123123... 时常会出现某个输入闪动一下后被删除了。源码如下
html
```
<div id="app">
  <new-editor v-model="html"></new-editor>
</div>
```
js
```
Vue.component('new-editor', {
	props: ['value'],
	data: function () {
  	return {
    	ref: Math.floor(Math.random()*1000),
    	editor: null
    }
  },
	template: '<div :ref="ref"></div>',
  watch: {
  	value: function (newVal, oldVal) {
      if (this.editor) {
        this.editor.txt.html(newVal)
      }
    }
  },
  mounted: function () {
  	var that = this
  	var E = window.wangEditor
    this.editor = new E(this.$refs[this.ref])
    this.editor.customConfig.onchange = function (html) {
      that.$emit('input', html)
    }
    this.editor.create()
    this.editor.txt.html(this.value)
  }
}
)

new Vue({
  el: "#app",
  data: {
    html: '<p>123</p>'
 	},
  watch: {
  	html: function (newVal) {
    	console.log(newVal)
    }
  }
})
```

把 onchange 时间换成 onblur 倒是没有这个问题，但是 onblur 事件优先级貌似低于表单提交优先级，用 onblur 貌似会有副作用（必选先失焦才能获取到数据，操作完编辑器直接点击按钮提交表单无法获取数据）

**Comment by xueyj123** [comment]
@hellomrbigshot  你好，请问这个问题解决了吗

**Comment by songda1013** [comment]
估计是延迟问题，可以使用editor.customConfig.onchangeTimeout = 1000 // 单位 ms

**Comment by songda1013** [comment]
> @hellomrbigshot 你好，请问这个问题解决了吗？我也出现这个问题了

如果还是不好用的话可以去掉双向绑定，最后发送请求的时候父组件调用子组件的方法，这个方法 return 一个富文本的内容

**Comment by hellomrbigshot** [comment]
> 估计是延迟问题，可以使用editor.customConfig.onchangeTimeout = 1000 // 单位 ms

哈，不行，不用双向绑定了。

**Comment by Jasonbyy** [comment]
> 估计是延迟问题，可以使用editor.customConfig.onchangeTimeout = 1000 // 单位 ms

我也遇到一样的问题了，最后也是用的这种方法解决的，目前还是用的双向绑定

**Comment by JoeWrights** [comment]
我想问题出现的原因在于`editor.txt.html` 这个方法上，value值改变后就重新设置了html，导致光标被覆盖

**Comment by sakuraay** [comment]
不用v-model挺好用的,谢谢 @songda1013  ,解决了我的问题

**Comment by JoeWrights** [comment]
> 不用v-model挺好用的,谢谢 @songda1013 ,解决了我的问题

我这边改用quill-editor了，主要是可扩展性更强

**Comment by sakuraay** [comment]
> > 不用v-model挺好用的,谢谢 @songda1013 ,解决了我的问题
> 
> 我这边改用quill-editor了，主要是可扩展性更强

我们新项目也用了quill,但是觉得没原来的好看
