### ISSUE TITLE
希望增加编程语言关键词高亮显示插件，在

### ISSUE THREAD

**Issue by wcx1978** [wangeditor-team/wangEditor#2103]
希望增加编程语言关键词高亮显示插件，如CSDN 等源代码网站那样。  有行号，能 跟据定义显示 或 C++ 或 python 或 php 或 javascript 等等 编程语言的 关键词，符号。注释， 用不同色标出。 
      做成插件。  想必我们本身在做网站的人，本身就有很多源代码要收集，随手备用。或用于与人交流。 做教程。

**Comment by yuluowuying** [comment]
作者都给出解决方案了，就差把代码给你们写出来了。

**Comment by a835100635** [comment]
V4 即将发布，已解决该问题，感谢反馈
