### ISSUE TITLE
希望可以自己配置字号

### ISSUE THREAD

**Issue by liuen12** [wangeditor-team/wangEditor#2114]

**Comment by wenyanxiang0415** [comment]
3版本好像没这个功能  我也在找解决办法

**Comment by wangpeng1994** [comment]
刚看到一篇文章：
https://www.freebytes.net/it/front/wangeditor-lineheight.html -wangEditor增加行高和具体字号功能 -千里 • 明月

**Comment by xiaokyo** [comment]
V4 即将发布，已可以配置字号，感谢反馈
