### ISSUE TITLE
如何显示本机绝对路径图片

### ISSUE THREAD

**Issue by Rohmeng** [wangeditor-team/wangEditor#2117]
如: `<img src="file:///C:/User/1.jpg" />`   在不转换成Base64显示在编辑器内

**Comment by HumanSean** [comment]
之前百度过，想要通过浏览器来显示本地的图片是不可能的，出于安全起见，本地的资源都会被一个Fakepath的路径取代掉，而且没办法hack。所以只能转成相对路径。

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
