### ISSUE TITLE
在后台管理使用富文本编辑纯文本，微信小程序页面显示代码

### ISSUE THREAD

**Issue by patchwork-dummy** [wangeditor-team/wangEditor#2120]
后台管理输入
![5ba3dcdbab2933ebdc4b08bb2a91403](https://user-images.githubusercontent.com/16274751/69778623-f7bd9f00-11df-11ea-9a7e-e6ecc4d39086.png)

 前端小程序页面出现代码
![1c006dfb43e784cfe57a5f2c2f8e746](https://user-images.githubusercontent.com/16274751/69778595-da88d080-11df-11ea-88d2-74e44403590e.png)

**Comment by xiaokyo** [comment]
是用的text嘛？如果存得是html估计不好兼容
