### ISSUE TITLE
如果获取当前焦点的位置？

### ISSUE THREAD

**Issue by yangfan-coder** [wangeditor-team/wangEditor#2121]
需求：
       上传的视频和图片 是自定义开发的 手动插入到富文本里， 有个数限制
       但是因为有粘贴复制的功能 ，图片视频可以有多个！希望获取当前的位置，在超过规定的个数后
可以拦截提示，并且超过个数的节点

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
