### ISSUE TITLE
表格的删除行或删除列功能，删除之后，不能增加行或增加列

### ISSUE THREAD

**Issue by junjieit** [wangeditor-team/wangEditor#2122]
#### Version
3.1.1

#### Reproduction link
http://www.wangeditor.com/

#### Steps to reproduce

1.  选中表格某行，当前选区为选中 `td`;
2. 点击菜单栏-表格-删除行，删除后选区为 `tbody`;
3. 点击菜单栏-表格-增加行，无反应；

#### What is expected?
查看增加行的源码，有判断选区不为 `tr` 或 `td` 则 `return`。
但是“菜单栏-表格”仍然有对行、列的操作。
当选区不为 `tr` 或 `td` 时期望如下选择：
1. 隐藏“菜单栏-表格”对行、列的操作，或置灰；
2. 选中上一行或下一行；
3. 暴露接口，给使用者选择；

#### What is actually happening?
当删除行或列之后，选区为 `tbody`。点击行列增删无反应

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈
