### ISSUE TITLE
wangEditor3版本，初始化富文本编辑器的时候，怎么让页面不解析pre里面的html代码啊

### ISSUE THREAD

**Issue by 52lb** [wangeditor-team/wangEditor#2130]
[https://upload-images.jianshu.io/upload_images/12858218-11d9328f3bc5eb9c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240](https://upload-images.jianshu.io/upload_images/12858218-11d9328f3bc5eb9c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by xiaokyo** [comment]
不是很理解你说的意思

**Comment by xiaokyo** [comment]
尝试使用editor.txt.html('<pre>你的代码</pre>')
