### ISSUE TITLE
wangEditor 引入ele弹窗组件中报错

### ISSUE THREAD

**Issue by kaifeng680** [wangeditor-team/wangEditor#2131]
引入vue中，在element 弹窗组件中无法使用报错
未知的自定义元素：-您正确注册了组件吗？对于递归组件，请确保提供“name”选项
vue.esm.js?a026:591 [Vue warn]: Unknown custom element: <editor-bar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

其他页面无误

**Comment by xiaokyo** [comment]
这个问题应该和编辑器无关
