### ISSUE TITLE
如何清除代码

### ISSUE THREAD

**Issue by weiyinfu** [wangeditor-team/wangEditor#2135]
在编辑器中，先粘贴一段代码之后，在代码前面想要添加几句话，无法退出代码区域
![image](https://user-images.githubusercontent.com/16095925/71542647-d4833c80-29a3-11ea-8cbb-57b735a2ee99.png)

**Comment by HumanSean** [comment]
好问题，貌似只能先`Ctrl Z`，在前面输入点内容留个光标的方式来实现

**Comment by xiaokyo** [comment]
先编辑添加的话，在进行添加代码块即可
