### ISSUE TITLE
现在如何获取所有图片

### ISSUE THREAD

**Issue by vivices** [wangeditor-team/wangEditor#2139]
以前2的方法editor.$txt.find('img')
3的没找到呢

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈

**Comment by bxjg1987** [comment]
@vivices 官方文档没有看到这样的api，是我找错了地方吗，我想详细看看这个函数的说明。望赐教~

**Comment by wangfupeng1988** [comment]
@bxjg1987 v4 目前没有这个功能，可以获取 html 然后通过正则表达式，取出所有的图片，也不麻烦。
