### ISSUE TITLE
文字上下标

### ISSUE THREAD

**Issue by rongrongt** [wangeditor-team/wangEditor#2140]
可以在菜单栏中能加一个文字上下标的菜单功能吗，例如
![image](https://user-images.githubusercontent.com/21823510/72132423-d4c70300-33b9-11ea-9181-2f04edbccfcc.png)

**Comment by kevinzqz** [comment]
王兄你好，请问我们这款编辑器是否有支持上下标的计划呢，盼回复，谢谢！

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
