### ISSUE TITLE
第一行文字回车键无法换行

### ISSUE THREAD

**Issue by hanxiaosss** [wangeditor-team/wangEditor#2141]
只有一行文字时，光标定在第一行回车换行，光标跳到第二行后立马回到第一行，无法换行。版本wangeditor3.1.1。

**Comment by baggiomygod** [comment]
解决了吗，我也遇到这个问题

**Comment by hanxiaosss** [comment]
第一行文字或者只有一行文字的有时候没有被p标签包裹，导致换不了行，手动在内容外加一层p标签------------------ 原始邮件 ------------------
发件人: "wengfan"<notifications@github.com>
发送时间: 2020年2月12日(星期三) 下午4:43
收件人: "wangfupeng1988/wangEditor"<wangEditor@noreply.github.com>;
抄送: "hanxiao"<1107416303@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wangfupeng1988/wangEditor] 第一行文字回车键无法换行 (#2141)



解决了吗，我也遇到这个问题
 
&mdash;
