### ISSUE TITLE
无法触发onchange事件

### ISSUE THREAD

**Issue by lin0123** [wangeditor-team/wangEditor#2142]
当你### 快速用鼠标选中内容并且删除的时候（注意，不点击，就快速划过选中），内容删除了，但是onchange事件并没有触发，导致无法取到值。有时候操作不是很快也无法触发，求解这个该如何解决，非常谢谢！

**Comment by fred913** [comment]
用onkeyup事件试试？

**Comment by xuangel5052** [comment]
一样的问题，求解答！
场景：
1.富文本框内容已初始化；
2.直接鼠标选中删除内容（注意，不点击，就快速划过选中），如果选中部分删除，会触发onChange，但如果直接全选删除，就不会触发onChange，导致删除操作失效。

**Comment by xuangel5052** [comment]
见 issues #1749
