### ISSUE TITLE
富文本初始化错误

### ISSUE THREAD

**Issue by obelixs** [wangeditor-team/wangEditor#2143]
官方文档看过了，别人提的issues也看过了，也百度了，没能解决问题。
1.这是js初始化。editor.txt.html(...)
![image](https://user-images.githubusercontent.com/35298725/72656810-9c867c80-39d8-11ea-8ba9-6391df8cd38a.png)
2.这是html初始化.
![image](https://user-images.githubusercontent.com/35298725/72656830-d061a200-39d8-11ea-8f39-cab6db6ac149.png)
文本没能显示在编辑器内部。
----------------------------------
文本提交时用xss.js进行了过滤。

**Comment by obelixs** [comment]
问题已解决，我用TP6开发的，文本输出时加上|raw即可恢复正常。

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈
