### ISSUE TITLE
wangEditor写的移动端的app  android端触点问题

### ISSUE THREAD

**Issue by zghyf** [wangeditor-team/wangEditor#2145]
我使用wangEditor写的移动端的app，在Android端想要选中的点击2下是因为什么啊，而且不能连选就是在选中加粗的情况下在选择斜体啥的都不行
ios端就没有这种问题

**Comment by zghyf** [comment]
请问我是哪里设置错了吗，文档上也没有相关问题解决

**Comment by xiaokyo** [comment]
暂时不完全兼容移动端哦，后期考虑将兼容性完善到移动端
