### ISSUE TITLE
v3.1.1 上传多张图片会只上传一张

### ISSUE THREAD

**Issue by bbdlg** [wangeditor-team/wangEditor#2147]
首先感谢辛苦付出~

框架：laravel-admin + 阿里云oss
通过上传图片按钮上传多张图片，会只显示一张。
经查，是因为 uploadFileName 没有配置导致。
wangEditor.js  4170行左右：
`
 var formdata = new FormData();

     arrForEach(resultFiles, function (file) {

      //var name = uploadFileName || file.name;

      var name = file.name || uploadFileName;

       formdata.append(name, file);

 });
`

**Comment by iwisen** [comment]
同样遇到此问题，多谢大佬

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
