### ISSUE TITLE
自定义菜单createMenu方法不存在

### ISSUE THREAD

**Issue by jqican** [wangeditor-team/wangEditor#2148]
最新版的代码里wangEditor.js中并没有createMenu方法，无法自定义菜单

**Comment by HumanSean** [comment]
路过，我前几天刚开始用，文档里面写的是编辑器创建之前，可使用editor.customConfig.menus定义显示哪些菜单和菜单的顺序。[文档链接](https://www.kancloud.cn/wangfupeng/wangeditor3/332599)

**Comment by kingOneone942** [comment]
同问，显示没有这个方法

**Comment by xiaokyo** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335784
可以参照全屏功能扩展菜单

或者是你说的配置菜单
`editor.customConfig.menus = [
        'head',
        'bold',
        'italic',
        'underline'
    ]`
