### ISSUE TITLE
从word中复制内容有data-xxx会出现样式的代码

### ISSUE THREAD

**Issue by jeenkzou** [wangeditor-team/wangEditor#2151]
我复制的下面的代码：
| neutron-openvswitch-agent |
| neutron-metadata-agent      |
| neutron-openvswitch-agent |
| neutron-l3-agent                  |
+---------------------------+ 
但是wangeditor的编辑器却显示下面的内容：
| neutron-openvswitch-agent |
| neutron-metayes';font-family:宋体;mso-ascii-font-family:'Times New Roman'; mso-hansi-font-family:'Times New Roman';line-height:150%;font-size:12.0000pt; mso-font-kerning:1.0000pt;" >
| neutron-openvswitch-agent |
| neutron-l3-agent          |
+---------------------------+

**Comment by xiaokyo** [comment]
可以按照下面的操作来自定义手动过滤
```
<div id="div1">
    <p>欢迎使用 wangEditor 富文本编辑器</p>
</div>

<script type="text/javascript" src="/wangEditor.min.js"></script>
<script type="text/javascript">
    var E = window.wangEditor
    var editor = new E('#div1')
    // 关闭粘贴样式的过滤
    editor.customConfig.pasteFilterStyle = false
    // 忽略粘贴内容中的图片
    editor.customConfig.pasteIgnoreImg = true
    // 自定义处理粘贴的文本内容
    editor.customConfig.pasteTextHandle = function (content) {
        // content 即粘贴过来的内容（html 或 纯文本），可进行自定义处理然后返回
        return content + '<p>在粘贴内容后面追加一行</p>'
    }
    editor.create()
</script>
```
