### ISSUE TITLE
wangeditor2一个页面引用多个编辑器，上传图片时都显示在最后一个编辑器中

### ISSUE THREAD

**Issue by yxzq** [wangeditor-team/wangEditor#2152]
1、问题一：我用的时wangeditor2版本，然后一个页面中有多个元素（textarea）绑定富文本，图片上传功能使用了文档上的自定义上传事件那个方法，现在每一个元素点击图片上传按钮上传的图片都是显示在最后一个编辑器里，通过复制word中的图片是没有问题的
2、问题二：我的页面里有个控制富文本元素显示的切换radio，每个radio显示不同的富文本字段，我页面初始化的时候写了一个函数，通过判断radio值显示不同的富文本，然后在radio切换事件里又引用了这个函数，第一个radio切换到第二个radio然后再切换到第一个radio时第一个radio控制的富文本编辑器就显示了两遍富文本框，每切换一次就多渲染一个文本框
求大神指教，问题很急，还麻烦大神看到及时回复

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
