### ISSUE TITLE
Editor在Vue中使用时有内存泄漏问题

### ISSUE THREAD

**Issue by zhouyanggodking** [wangeditor-team/wangEditor#2153]
API中只有 create 方法，没有destroy 方法。 经测试，有内存泄漏问题

**Comment by fanlw0816** [comment]
+1

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈

**Comment by juliastegner** [comment]
> V4 即将发布，已解决该问题，感谢反馈

安装4.0测试了下 依然泄漏

**Comment by elvisyang2016** [comment]
> > V4 即将发布，已解决该问题，感谢反馈
> 
> 安装4.0测试了下 依然泄漏

这个有更新吗？Vue SPA集成碰到内存泄露，wangeditor版本4.7.8
