### ISSUE TITLE
如何删除editor,多次创建会出现嵌套的现象

### ISSUE THREAD

**Issue by tianchaofeng** [wangeditor-team/wangEditor#2158]
![bug](https://user-images.githubusercontent.com/31308216/75612470-a3b7b300-5b5e-11ea-8175-57861cf40eaa.png)

如果提供一个删除的功能   和 editor.create()  对应   就能解决这个问题

**Comment by xiaokyo** [comment]
按道理 不需要create多次，如果需要删除功能，在即将发布的V4版本中有destro()可以销毁编辑器
