### ISSUE TITLE
上传图片如何设置put方法？

### ISSUE THREAD

**Issue by zaozao1040** [wangeditor-team/wangEditor#2163]
上传图片我从结果看，wangEditor使用的是post，但是项目后端要求是put，如何修改成put方法呢？

**Comment by richex-cn** [comment]
Look: <https://www.kancloud.cn/wangfupeng/wangeditor3/335782>

```
editor.customConfig.customUploadImg = function (files, insert) {
    // files 是 input 中选中的文件列表
    // insert 是获取图片 url 后，插入到编辑器的方法

    // 上传代码返回结果之后，将图片插入到编辑器中
    insert(imgUrl)
}
```

**Comment by Seiphro** [comment]
直接在依赖的源代码里面找，很快就能找到，直接在这个层面改掉就好了。

**Comment by xiaokyo** [comment]
> Look: https://www.kancloud.cn/wangfupeng/wangeditor3/335782
> 
> ```
> editor.customConfig.customUploadImg = function (files, insert) {
>     // files 是 input 中选中的文件列表
>     // insert 是获取图片 url 后，插入到编辑器的方法
> 
>     // 上传代码返回结果之后，将图片插入到编辑器中
>     insert(imgUrl)
> }
> ```

可以采用自定义的方式来自定义上传规则，然后插入到编辑器即可
