### ISSUE TITLE
大神求解 v3.0 +typeScript中使用wangEditor时候 onchange失效   内容框中输入值 onchange并不回调,失去焦点时候会回调，自己手动在编辑框中点几次onchange会回调，请问有没有外部主动掉onblue事件的方法啊大神求解

### ISSUE THREAD

**Issue by 405396731** [wangeditor-team/wangEditor#2164]

**Comment by 405396731** [comment]
在线等急
import { ControllerBase, Prop, Emit, Inject, Watch,Model } from "prism-web";
const E = require("../../../node_modules/wangeditor");
export class wangEDController extends ControllerBase {
    constructor() {
        super();
    }
    @Inject("http") http: any;

    //私有样式引入
    temp = {
        style: require("../style/wangED.less")
    };
    private editor: any = null;
    private info_: any = null;
    private isChange: Boolean = false;
    @Model('change', { type: String }) readonly value!: String // 显示的值（hrml片段）
    @Prop() refName: String; // 标识多窗口的ref名  必传
    @Prop({
        type: Array,
        required: false,
        default: () => [
            "head", // 标题
            "bold", // 粗体
            "fontSize", // 字号
            "fontName", // 字体
            "italic", // 斜体
            "underline", // 下划线
            "strikeThrough", // 删除线
            "foreColor", // 文字颜色
            "backColor", // 背景颜色
            "link", // 插入链接
            "list", // 列表
            "justify", // 对齐方式
            "quote", // 引用
            "emoticon", // 表情
            "image", // 插入图片
            "table", // 表格
            // 'video', // 插入视频
            "code", // 插入代码
            "undo", // 撤销
            "redo", // 重复
            "fullscreen" // 全屏
        ] // 默认属性的默认值
    })
    private menus!: Array<String> | null; // menus不必传
    @Watch("value")
    getValue(val: any) {
            if(!this.isChange){
                if(val !== this.editor.txt.html()){
                    this.editor.txt.html(this.value);
                }   
            }
            this.isChange = false;
    }
    // @Watch("info_")
    // getinfo_(val) {
    //     this.$emit("input", val);
    // }
    //value为编辑框输入的内容，这里我监听了一下值，当父组件调用得时候，如果给value赋值了，子组件将会显示父组件赋给的值
    created() { }
    mounted() {
        this.seteditor();      
    }
    seteditor() {
        // http://192.168.2.125:8080/admin/storage/create
        this.editor = new E(
            this.$refs["toolbar" + this.refName],
            this.$refs["editor" + this.refName]
        );
        this.editor.customConfig.onchange = (html: any) => {
            this.info_ = html; // 绑定当前逐渐地值
            let text = this.editor.txt.text(); // 编辑的文本
            this.isChange = true;
            console.log(this.info_, text)
            this.$emit("change", this.info_, text); // 将内容同步到父组件中
        };
        this.editor.customConfig.onblur = html => {
            this.info_ = html; // 绑定当前逐渐地值
            let text = this.editor.txt.text(); // 编辑的文本
            this.isChange = true;
            console.log(this.info_, text)
            this.$emit("change", this.info_, text); // 将内容同步到父组件中
        };
        this.editor.customConfig.uploadImgShowBase64 = false; // base 64 存储图片 false只能传递网络图片不能本地  true以base形式传递本地图片
        // this.editor.customConfig.uploadImgServer = 'http://otp.cdinfotech.top/file/upload_images'// 配置服务器端地址
        // this.editor.customConfig.uploadImgHeaders = {}// 自定义 header
        // this.editor.customConfig.uploadFileName = 'file' // 后端接受上传文件的参数名
        this.editor.customConfig.uploadImgMaxSize = 2 * 1024 * 1024; // 将图片大小限制为 2M
        this.editor.customConfig.uploadImgMaxLength = 6; // 限制一次最多上传 3 张图片
        // this.editor.customConfig.uploadImgTimeout = 3 * 60 * 1000 // 设置超时时间

        // 配置菜单
        this.editor.customConfig.menus = this.menus;

        // this.editor.customConfig.uploadImgHooks = {
        //     fail: (xhr, editor, result) => {
        //         // 插入图片失败回调
        //     },
        //     success: (xhr, editor, result) => {
        //         // 图片上传成功回调
        //     },
        //     timeout: (xhr, editor) => {
        //         // 网络超时的回调
        //     },
        //     error: (xhr, editor) => {
        //         // 图片上传错误的回调
        //     },
        //     customInsert: (insertImg, result, editor) => {
        //         // 图片上传成功，插入图片的回调
        //         //result为上传图片成功的时候返回的数据，这里我打印了一下发现后台返回的是data：[{url:"路径的形式"},...]
        //         // console.log(result.data[0].url)
        //         //insertImg()为插入图片的函数
        //         //循环插入图片
        //         // for (let i = 0; i < 1; i++) {
        //         // console.log(result)
        //         let url = "http://otp.cdinfotech.top" + result.url
        //         insertImg(url)
        //         // }
        //     }
        // 
        // 创建富文本编辑器
        this.editor.create();
        this.editor.txt.html(this.value); // 让后续的编辑进入onchange事件
    }
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////
这是父组件中的写法
      <wang-Editor v-model="planContent.content" refName="editContent"
                                            @change="editorChange">
                                        </wang-Editor>

**Comment by 405396731** [comment]
在wangEditor.js的4452行加入代码_this.change && _this.change（）;就可以了  但是有个问题是 我是npm下载的  上线后应该也会有类似问题吧 我该怎么解决

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈
