### ISSUE TITLE
超链接点击后获取的$linkelem不正确

### ISSUE THREAD

**Issue by renwangyu** [wangeditor-team/wangEditor#2165]
如果在编辑框外点击后直接点击超链接，会导致selection选中的区域不正确，继而导致元素选到的元素不正确，显示的超链接编辑也不正确。建议判断必须是在编辑框内的元素，且没有href的元素返回link值为""，不要直接返回null
![111111](https://user-images.githubusercontent.com/10877763/77294055-8372b280-6d1e-11ea-9442-6d013784a48b.jpg)

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈
