### ISSUE TITLE
与antd design 的结合有很大的问题, 会遮住antd 的组件

### ISSUE THREAD

**Issue by Anxdada** [wangeditor-team/wangEditor#2167]
编辑框处会对antd的组件都会有覆盖的效果, 即如果有antd组件位于编辑框内, 都会显示编辑框的内容, 并且无法聚焦到antd组件上, 点击会直接到编辑框内.

**Comment by binyu1005** [comment]
我也遇到了和你一样的问题  
this.editor.customConfig.zIndex = 0; 貌似可以解决这个问题。

**Comment by Anxdada** [comment]
@binyu1005 
谢谢, 确实有效.

**Comment by image72** [comment]
element-ui dialog中结合使用后 head, list, justify, foreColor, backColor, fontSize都无法使用了

也不会弹出下拉功能列表，我觉得这不是zIndex能调整出来的问题

**Comment by xiaokyo** [comment]
我觉得编辑器里不应该会有其他第三方的组件吧，这种设计应该不是很常见的吧
