### ISSUE TITLE
建议增加一个自定义菜单的功能

### ISSUE THREAD

**Issue by qr122333** [wangeditor-team/wangEditor#2170]
不需要很复杂，我想法是加一个对象，展示一个新增菜单的图片，点击的时候能触发回调
{
name,
imgs
}

**Comment by xiaokyo** [comment]
https://www.kancloud.cn/wangfupeng/wangeditor3/335784
暂时可以参考全屏菜单功能的源码设计新的自定义菜单

即将发布的V4版本中有扩展菜单的详细文档及操作
