### ISSUE TITLE
wangEditor3.1.1 与 artDialog.source.js 4.1.6 冲突，回车无效

### ISSUE THREAD

**Issue by xiuqiang1995** [wangeditor-team/wangEditor#2171]
版本：
wangEditor 3.1.1
artDialog.source.js 4.1.6
现象：
页面同时引入artDialog.source.js与wangEditor.js时，富文本编辑器内回车无效。
引入artDialog.js与wangEditor.js时，回车正常。
附件是我所用的artDialog 4.1.6 版本
[artDialog.zip](https://github.com/wangfupeng1988/wangEditor/files/4401510/artDialog.zip)

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
