### ISSUE TITLE
IE11报错："由于出现错误 800a025e 而导致此项操作无法完成" 

### ISSUE THREAD

**Issue by fnroid** [wangeditor-team/wangEditor#2185]
IE11报错："由于出现错误 800a025e 而导致此项操作无法完成" 看代码是定位到3873行 selection.removeAllRanges();  
IE11版本：11.706.17134.0

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈

**Comment by smileBeauty** [comment]
这个问题 我也出现了 用的4.7.15 ie11 错误堆栈显示 出问题的代码也是selection.removeAllRanges(); 请问大佬 最后怎么解决的
