### ISSUE TITLE
可不可以固定某些字符不能删除掉？

### ISSUE THREAD

**Issue by keaidefeizao** [wangeditor-team/wangEditor#2186]
做了一个发送邮件的文本模板，然后我需要在那些html文本里添加id，我需要更具元素id自行添加内容。可是如果客户随意修富文本里面的东西的可以删除掉那些带有id的元素。这个如何解决？（不知道我的描述有没有让您听懂？）

**Comment by xiaokyo** [comment]
其实你完全可以 将id的元素分离出来，也就是要赋值的动态变量分离到其他地方输入，
然后编辑器设置 关键词{{name}} 来做替换即可，不需要针对编辑器进行调整，也可以达到你的模板效果
