### ISSUE TITLE
无法复制粘贴word中的多张图片到编辑器中，单独一张是可以的

### ISSUE THREAD

**Issue by happydele** [wangeditor-team/wangEditor#2191]
![image](https://user-images.githubusercontent.com/49010750/81276882-322c4180-9086-11ea-9ef7-b24f27cf8d70.png)
有什么解决方案吗？我想直接复制word中的多张截图

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
