### ISSUE TITLE
自定义设置的customAlert， 在插入链接校验失败后，并未生效

### ISSUE THREAD

**Issue by Ricardozhang** [wangeditor-team/wangEditor#2192]
看源码发现 插入链接时调用 _insertLink 时，在校验失败后，直接使用的alert, 没有调用 _alert，所以customAlert并不会生效

![image](https://user-images.githubusercontent.com/14835976/81362999-c47b2680-9114-11ea-8db2-408f44cd9536.png)

**Comment by xiaokyo** [comment]
这个只针对图片上传哦
已记录该问题，在 V4 版本中可以考虑到所有功能，感谢反馈
