### ISSUE TITLE
插入图片后，<img>标签没有闭合导致支付宝小程序无法显示图片

### ISSUE THREAD

**Issue by spmdhh** [wangeditor-team/wangEditor#2197]
大佬富文本插入图片后,<img>标签没有闭合导致支付宝小程序无法显示富文本类容这个问题该如何解决
@wangfupeng1988 

![1589462898](https://user-images.githubusercontent.com/51350350/81940402-23b3cc00-962a-11ea-991a-0b478a80c8ff.png)

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
