### ISSUE TITLE
编辑区一段文字加粗，在删除加粗文字后，再次输入文字，如何使再次输入的文字不带格式？

### ISSUE THREAD

**Issue by lyj6879668** [wangeditor-team/wangEditor#2201]
使用加粗功能，文字会被span标签包住，在删除span标签里面的内容后，再次输入文字，新输入的文字会被b标签包住，如果使新输入的文字不带样式（在不再次点击加粗按钮的情况下），这种情况是否是contenteditable自带的问题？

**Comment by yethyeth** [comment]
类似的问题，用insertHtml插入带格式的文字<span class="xxxx"></span>， 然后手动接着输入内容，把格式带上了。

**Comment by xiaokyo** [comment]
将后面接着输入的一些文字选中取消加粗即可
