### ISSUE TITLE
word复制问题

### ISSUE THREAD

**Issue by zhangcd7049** [wangeditor-team/wangEditor#2202]
[word文本.zip](https://github.com/wangfupeng1988/wangEditor/files/4660758/word.zip)
word文档复制黏贴后，保存成功，但是点编辑进行回显修改的时候，使用editor.txt.html()方法会报语法错误，但是一些简单的html都可以回显。
所以问下，word文档的操作是要规避一些格式或者重写什么方法么？谢谢~
![1590040383(1)](https://user-images.githubusercontent.com/65651120/82528029-6d407180-9b6a-11ea-9af4-502070a15adb.jpg)
![1590040434(1)](https://user-images.githubusercontent.com/65651120/82528072-89dca980-9b6a-11ea-83bf-f65d6c013813.jpg)

**Comment by WangAnQinga** [comment]
过滤全部的样式

**Comment by zhangcd7049** [comment]
> 过滤全部的样式

我就是想保留样式，有什么别的办法么~

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈

**Comment by 623130477** [comment]
该问题解决了吗？

**Comment by wangfupeng1988** [comment]
@623130477 可以去提交新的 issue ，会有人值班受理
