### ISSUE TITLE
上传到七牛云提示我不能multipart

### ISSUE THREAD

**Issue by AbnerXia** [wangeditor-team/wangEditor#2204]
我用下面链接里面的方法想上传图片到七牛云，
[关于在vue项目中使用wangEditor](https://www.cnblogs.com/huge1122/p/11346115.html)
但是七牛云的服务器提示我"error":"file is not specified in multipart"。，然后我尝试着将customConfig.uploadImgMaxLength的值设为1，但是还是不行，
不知道这是不是七牛云的问题。

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
