### ISSUE TITLE
【紧急Bug】在iOS网页中写一行文字再上传图片，图片会插入在文字前面

### ISSUE THREAD

**Issue by piaoluoya** [wangeditor-team/wangEditor#2207]
在Android中正常，开始我以为是我代码写的有问题，不断删除无关代码，copy官网demo有问题。
而官网首页中demo也是同样的问题，非常非常紧急，客户在不断吐槽了。

再现方式，iOS微信中  打开官网，在富文本中第二行输入几个字，点图片上传，上传显示的图片会跑到文字前面去。

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
