### ISSUE TITLE
web端的代码编辑器

### ISSUE THREAD

**Issue by yelloxing** [wangeditor-team/wangEditor#2210]
推荐一个可以在浏览器端运行的代码编辑器：https://yelloxing.github.io/Web-Studio-Code/Web-Studio-Code.html

![snipping](https://user-images.githubusercontent.com/23074691/83958922-121cb780-a8aa-11ea-97cc-ba525f88e9cc.png)

**Comment by yelloxing** [comment]
支持Chrome、Safari、Edge、Firefox、Opera和IE(9+)等常见浏览器！

**Comment by xiaokyo** [comment]
感谢分享，但和本编辑器没有联系
