### ISSUE TITLE
编辑器第一次初始化完成后的第一次的onblur无法监听到失去焦点

### ISSUE THREAD

**Issue by wangxiaoqier** [wangeditor-team/wangEditor#2211]
编辑器第一次初始化完成后会默认获取焦点，这时直接输入完成后，点击空白处，使其失去焦点，这时，实例化editor时候的onblur函数无法捕捉到失去焦点的事件。此时需要鼠标手动再去点击编辑器，获取焦点，然后再点击空白失去焦点，这时就会触发失去焦点的监听函数了

**Comment by Outang-b** [comment]
首次获取焦点并不是通过blur，可以尝试一个小技巧，先禁止可编辑然后打开。。

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
