### ISSUE TITLE
npm install 的时候报found 1 high severity vulnerability

### ISSUE THREAD

**Issue by luyk** [wangeditor-team/wangEditor#2213]
"overview": "All versions of `wangeditor` are vulnerable to Cross-Site Scripting. The package fails to properly encode output, allowing arbitrary Jav
aScript to be inserted in links and executed by browsers.",
      "recommendation": "No fix is currently available. Consider using an alternative module until a fix is made available.",

**Comment by xiaokyo** [comment]
请尝试使用阿里云且下载最新版本哦
