### ISSUE TITLE
怎么给菜单上加一个自定义的功能

### ISSUE THREAD

**Issue by 2017lw** [wangeditor-team/wangEditor#2215]
手册中有查看源码的说明，但是我想将查看源码的功能加到菜单上，手册上自定义菜单只是选择默认有的功能，请问怎么添加自定义的标签到菜单上

**Comment by zhaoqinghuan** [comment]
现在的版本不支持这个功能，你可以通过改源码实现，谨慎操作！
如果想好了要这么做参考下面的连接。
[https://www.cnblogs.com/wangmaoling/p/13275059.html](url)

**Comment by zhangporco** [comment]
不支持的，你可以将自定义插件写在源码menus目录下

**Comment by xiaokyo** [comment]
参考全屏功能菜单可新建一个功能菜单：https://www.kancloud.cn/wangfupeng/wangeditor3/335784
