### ISSUE TITLE
图片居中问题

### ISSUE THREAD

**Issue by WeiMouhui** [wangeditor-team/wangEditor#2221]
您好，图片怎么才能居中，我改过源码，但是加上居中后文字也居中了？大佬有什么好的解决办法吗？

**Comment by xiaokyo** [comment]
你是想要同一行中的文字和图片，只居中图片的话，应该是不行的

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
