### ISSUE TITLE
customUploadImg 的insert无效

### ISSUE THREAD

**Issue by crisbb** [wangeditor-team/wangEditor#2222]
if (_this.customUploadImg) {
        this.editor.customConfig.customUploadImg = function (files, insert) {
          // files 是 input 中选中的文件列表
          // insert 是获取图片 url 后，插入到编辑器的方法
          // 上传返回结果之后，将图片插入到编辑器中
          if (_this.compress) {
            let data = { file: files[0], ..._this.compressOptions }
            compressUtil.pictureCompress(data).then(resp => {
              _this.uploadFunction(resp).then(data => {
                console.log(data.data.info)
                console.log(insert)
                let jsonObj = {
                  url: data.data.info
                }
                insert(jsonObj.url)
              })
            })
          }
        }

**Comment by xiaokyo** [comment]
```
editor.customConfig.customUploadImg = function (files, insert) {
    // files 是 input 中选中的文件列表
    // insert 是获取图片 url 后，插入到编辑器的方法

    // 上传代码返回结果之后，将图片插入到编辑器中
    insert(imgUrl)
}
```
我试了是没有问题的，你得先确保上传并成功返回了url才可以insert插入编辑器
我看你是没有做空判断的
