### ISSUE TITLE
请问支持自定义换行吗？

### ISSUE THREAD

**Issue by Gardeniaxch** [wangeditor-team/wangEditor#2223]
请问支持自定义换行吗？比如ctrl+回车键换行

**Comment by btconfig** [comment]
> 请问支持自定义换行吗？比如ctrl+回车键换行

看了wangediter的源码，应该是利用原生的enter事件来换行的，wangediter应该没有做处理
原生支持的换行操作，wangediter应该都支持，比如enter、shift+enter，都可以换行
如果还不满足要求，你可以尝试换下操作逻辑，比如enter是换行，ctrl+enter对应到之前enter的逻辑

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
