### ISSUE TITLE
2.1.3版本，有序列表与无序列表切换后，对齐方式失效

### ISSUE THREAD

**Issue by MengFanXue** [wangeditor-team/wangEditor#2225]
创建一个有序（或者无序）列表，进行左对齐，居中对齐，右对齐操作，列表正常
将某一列表项切换成无序（或者有序），在进行左对齐，居中对齐，右对齐操作时，某一操作会失效，点击没反应

**Comment by xiaokyo** [comment]
确认了下，没有你说的问题，如果还有问题可以详细说明下使用的浏览器及场景或相关的信息
