### ISSUE TITLE
使用 div 而不是 p 标签

### ISSUE THREAD

**Issue by ultravires** [wangeditor-team/wangEditor#2226]
不知道有没有初始化标签的接口。我建议保留 div 标签作为基本换行标签，原因：div 标签可以嵌套任意标签，而 p 标签不能嵌套 div 等块级标签。不易扩展。实际上，原生的 contenteditable 就是使用的 div

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
