### ISSUE TITLE
截图，如何复制到qq，在从qq复制到编辑器，图片显示失败

### ISSUE THREAD

**Issue by whatarey** [wangeditor-team/wangEditor#2227]
我使用截图工具直接截图，如何粘贴到编辑器，图片能正常显示，但是，我从qq复制过来的图片无法显示在编辑器中
![image](https://user-images.githubusercontent.com/35121432/87277469-ef1e9c80-c514-11ea-84aa-de8a8734d9f8.png)

这个网站也不支持这样：
http://www.wangeditor.com/
![image](https://user-images.githubusercontent.com/35121432/87277520-078eb700-c515-11ea-934a-3ceac4516901.png)

但是这个图片存在本地
![image](https://user-images.githubusercontent.com/35121432/87277583-29883980-c515-11ea-9f4f-e10eeef11072.png)

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
