### ISSUE TITLE
富文本编辑器的撤回功能会把其他输入框的内容撤回，有办法撤回只作用于编辑器的内容吗？

### ISSUE THREAD

**Issue by xp-Su** [wangeditor-team/wangEditor#2228]
在使用富文本的过程中，要是中途去填了其他输入框，然后再在编辑器编辑，使用撤回时，会将中途填写在其他输入框的内容一同撤回了，这是bug呢还是说就是这样的？有没有什么解决办法？

**Comment by zhangporco** [comment]
wangEditor 是基于 document.execCommand 指令的一款编辑器，撤回使用的是 undo 指令，相当于全局有效。这应该属于设计上的缺陷，相当于编辑器的操作栈交给了浏览器来维护，如何前进后退也是浏览器来解释。
解决这个问题最好的方法应该是编辑器自己来维护操作栈，这样才能做到细粒度的控制

**Comment by xp-Su** [comment]
> wangEditor 是基于 document.execCommand 指令的一款编辑器，撤回使用的是 undo 指令，相当于全局有效。这应该属于设计上的缺陷，相当于编辑器的操作栈交给了浏览器来维护，如何前进后退也是浏览器来解释。
> 解决这个问题最好的方法应该是编辑器自己来维护操作栈，这样才能做到细粒度的控制

谢谢解答

**Comment by xiaokyo** [comment]
> wangEditor 是基于 document.execCommand 指令的一款编辑器，撤回使用的是 undo 指令，相当于全局有效。这应该属于设计上的缺陷，相当于编辑器的操作栈交给了浏览器来维护，如何前进后退也是浏览器来解释。
> 解决这个问题最好的方法应该是编辑器自己来维护操作栈，这样才能做到细粒度的控制

是这样的
