### ISSUE TITLE
对空白内容没有验证的问题

### ISSUE THREAD

**Issue by lijiadashaoye** [wangeditor-team/wangEditor#2233]
如果在编辑器内，只输入空格和回车，编辑器会返回一堆无用的标签，但表单里认为当前项是有值的，比如：
 `<p>&nbsp; &nbsp;</p><p>&nbsp;&nbsp;</p><p>&nbsp;</p><p><br></p>`；
所以我觉得有必要对富文本编辑器的输出值添加校验；
我写了一个目前觉得可以用的
`checkVal(str) {
      let num = 0,
        reg = /<p>(&nbsp;|&nbsp;\s+)+<\/p>|<p>(<br>)+<\/p>/g;
      while (num < str.length && str != "") {
        num++;
        let k = str.match(reg);
        if (k) {
          str = str.replace(k[0], "");
        }
      }
      return str == "";
    },`

**Comment by lijiadashaoye** [comment]
`<p>&nbsp; &nbsp;&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;&nbsp;</p><p><br></p>`

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈

**Comment by lijiadashaoye** [comment]
加油！挺好用的，我已封装好，用在项目里了
 
 
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 10月6日 18:48，xiaokyo <notifications@github.com> 写道： 
   
  已记录该问题，会安排在 V4 版本中解决，感谢反馈
