### ISSUE TITLE
从word等文档里边拷贝出来的内容，复制到编辑器中会生成解析不了的标签怎么办？

### ISSUE THREAD

**Issue by xzw1030** [wangeditor-team/wangEditor#2234]
![image](https://user-images.githubusercontent.com/34021416/88909397-a04f6180-d28d-11ea-9ebf-8afad7441388.png)

最多的就是这种的："<p><spanyes';font-family:宋体;......“

**Comment by imic07** [comment]
同样遇到了   

[测试.zip](https://github.com/wangfupeng1988/wangEditor/files/5021939/default.zip)

**Comment by xiaokyo** [comment]
参考：https://www.kancloud.cn/wangfupeng/wangeditor3/448202
自定义处理粘贴的文本内容
