### ISSUE TITLE
输入窗口.w-e-text-container大小怎么调？可设置吗？

### ISSUE THREAD

**Issue by DingDangDog** [wangeditor-team/wangEditor#2236]
.w-e-text-container输入框的高度宽度可以自定义吗，在使用手册没找到相关说明，看了一下好像是行内样式写死了，优先级最高，只能改源码吗？

**Comment by BaiFangZi** [comment]
![image](https://user-images.githubusercontent.com/45963987/90753822-aaec9c00-e30b-11ea-9788-ea5ef0f91d3c.png)

**Comment by BaiFangZi** [comment]
更改源码里的这句话，删除height属性
 $textContainerElem.css('border', '1px solid #ccc').css('border-top', 'none').css('height', '300px');

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈
