### ISSUE TITLE
插入图片后，能否拖拽改变其位置

### ISSUE THREAD

**Issue by 89466598946659** [wangeditor-team/wangEditor#2239]
大佬，插入图片后，能否拖拽图片插入其他位置，比如：ABC[图片]D，改成：A[图片]BCD
强需求，或者提示下怎么去处理，我去手动处理

**Comment by ssshooter** [comment]
直接用 html 的 draggable 属性和相关事件

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈

**Comment by qp91abc1234** [comment]
@xiaokyo hello，v4版本实现了这个功能么，是要怎么开启呢
