### ISSUE TITLE
插入图片后如何附加一个class属性已适配其自适应大小

### ISSUE THREAD

**Issue by wmgm183** [wangeditor-team/wangEditor#2240]
插入图片后可以 追加一个class属性吗

目前插入只是`<img src="图片地址" style="max-width:100%;">`

想实现`<img src="图片地址" class=“img-responsive” style="max-width:100%;">`

**Comment by liuzhenggang** [comment]
同求啊

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈
在新版本中可以等比拖拽图片大小
