### ISSUE TITLE
富文本编辑器在特定情况下会影响富文本编辑器以外的元素样式

### ISSUE THREAD

**Issue by fuxichen** [wangeditor-team/wangEditor#2243]
## 复现视频
![2x3x6-wgdth (1)](https://user-images.githubusercontent.com/17411462/91388281-90fe0c80-e869-11ea-8125-c917fe9d4181.gif)

> gif比较大在 gayhub 中可能加载很慢，可以[点击下载GIF](https://s17.aconvert.com/convert/p3r68-cdx67/2x3x6-wgdth.gif)
## 复现网站
> [wangEditor](http://www.wangeditor.com/index.html)
## 问题复现步骤

1. 在编辑框末尾插入一个表格
2. 在表格中输入文本(为了看相关效果)
3. 鼠标选中表格及至少一行表格外部文本
4. 将选中内容居右显示
5. 可以看到编辑器里面表格的文本居右显示的同时编辑框外面的文本(如底部的交流方式)也居右显示了

@wangfupeng1988

**Comment by xiaokyo** [comment]
按照您的步骤确认了下，没有此类问题发生
