### ISSUE TITLE
使用emoji表情并将html内容转为String存入数据库会报错，提示不支持的字符

### ISSUE THREAD

**Issue by iduand** [wangeditor-team/wangEditor#2244]
错误：Cause: java.sql.SQLException: Incorrect string value: '\xF0\x9F\xA4\x90<i...' for column 'detail' at row 1
\xF0\x9F\xA4\x90：经对比即是emoji表情转移过来的字符串

不知大佬有何解决方案吗？

**Comment by zhangshuling** [comment]
用的mysql？  要把存这个字段的字符集 改成 utf8mb4 , 别只用utf8

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
