### ISSUE TITLE
使用 MutationObserver 作为 change 事件的驱动器（优化）

### ISSUE THREAD

**Issue by zhangporco** [wangeditor-team/wangEditor#2247]
目前 change 事件的触发不太好
1.编辑区点击、keyup事件
2.工具栏点击事件
3.触发浏览器指令

我觉得采用 MutationObserver 作为change 驱动器是更好的做法

**Comment by zhangporco** [comment]
使用 MutationObserver 可以使代码更简单、纯粹

**Comment by zhangporco** [comment]
对于因脚本或其他原因导致的内容变化，不会触发keyup事件，导致内容变化但是不触发change，最近遇到了这个问题，我用 MutationObserver 重写了这一部分

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中优化，感谢反馈
