### ISSUE TITLE
不同的失去焦点方式导致复制新的内容进来会替换原有选中的内容

### ISSUE THREAD

**Issue by lingxiaoyi** [wangeditor-team/wangEditor#2248]
![GIF 2020-9-3 16-19-24](https://user-images.githubusercontent.com/18524956/92090293-d7bbab80-ee01-11ea-891a-968a71b16c69.gif)
![GIF 2020-9-3 16-20-09](https://user-images.githubusercontent.com/18524956/92090301-da1e0580-ee01-11ea-92cb-dca042537d6c.gif)
1.先选中内容,然后去网页外部复制文字进来,再进来网页,粘贴内容之后,内容被覆盖.
2.先选中内容,然后点一下编辑器外任意地方,然后复制文字,粘贴内容之后,内容不会被覆盖.

这个bug怎么解决????

**Comment by lingxiaoyi** [comment]
这个选区缓存怎么去掉的呢.我这里的负责人要求必须去掉这个选区缓存,所以特此开个问题的,谢谢

**Comment by zhangporco** [comment]
目前我们团队是通过修改源码解决的
在 src/js/selection/index.js 下添加 clean 方法
`
    // 清空选区
    clean: function () {
        const selection = window.getSelection()
        selection.removeAllRanges()
        this._currentRange = null
    },
`
然后在 src/js/command/index.js 的 do 函数末尾添加以下代码，即可在每次操作之后清除缓存
`editor.selection.clean()`

不过这样做是有副作用的，用户体验不好，无法连续操作，目前我也在寻找更好的做法
希望可以帮助到你

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
