### ISSUE TITLE
工具栏样式问题

### ISSUE THREAD

**Issue by Rorschaaaach** [wangeditor-team/wangEditor#2249]
`<link rel="stylesheet" href="../layuiadmin/layui/css/layui.css" media="all">`
只要插入了layui的样式，wangEditor的颜色样式就会被覆盖，完全不显示颜色了，这有啥好办法嘛？
![image](https://user-images.githubusercontent.com/37372729/92373620-2aae9f00-f131-11ea-9d25-93c7e0f9a631.png)

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
