### ISSUE TITLE
在用editor.txt.append插入一段带class的html进去之后 回车生成的每个div都会有同样的类名 请作者麻烦看下是什么问题呢？

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#2250]
![image](https://user-images.githubusercontent.com/43296632/92425427-cedc2880-f1b9-11ea-81e1-34a2b8f69c8a.png)
![image](https://user-images.githubusercontent.com/43296632/92425433-d1d71900-f1b9-11ea-93f9-bb27cbcae018.png)

**Comment by OnePsycho** [comment]
![image](https://user-images.githubusercontent.com/43296632/92425457-e87d7000-f1b9-11ea-9eb4-2e79d723cd10.png)

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
