### ISSUE TITLE
上传图片直传阿里云的异常处理

### ISSUE THREAD

**Issue by smalleast** [wangeditor-team/wangEditor#2254]
form data参数：需要把file作为最后一个参数，不然就会提示：
The bucket POST must contain the specified 'key'. If it is specified, please check the order of the fields
![image](https://user-images.githubusercontent.com/15937679/93578532-0758df00-f9d0-11ea-8a97-7c1675a4441c.png)

![image](https://user-images.githubusercontent.com/15937679/93578376-d2e52300-f9cf-11ea-882a-d2c9c9fb109d.png)

正确的参数应该是：

![image](https://user-images.githubusercontent.com/15937679/93578429-e85a4d00-f9cf-11ea-9158-cf6432c9c6ed.png)

**Comment by xiaokyo** [comment]
按照英文的意思应该是少了什么字段才会报这个错误

**Comment by xiaokyo** [comment]
与编辑器无关，将此issue关闭了

**Comment by joseITzh** [comment]
Where is the answer to this problem??? @xiaokyo
