### ISSUE TITLE
工具栏和内容分离， 内容可滚动时。 会导致滚动条拉到下面后图片上传框被隐掉

### ISSUE THREAD

**Issue by skypyb** [wangeditor-team/wangEditor#2255]
点击上传图片按钮的弹框会 **固定在内容的顶上**。
而内容一往下滑动， 则图片上传栏会被隐藏掉。

如图, 这是一个没有被完全隐掉的图片上传框。
![image.png](https://i.loli.net/2020/09/19/YUwOz8Wk2ASr4Jb.png)

为什么这个框不是以固钉的形式出现？
如何解决？

**Comment by skypyb** [comment]
值得一提的 **链接** 菜单点击后则会将滚动条拉到最上面去，然后显示出弹窗。
也多少有点不合理， 但还是比图片菜单的逻辑好。
如何能够让他们像是 **背景**、**颜色** 几个菜单一般显示？

**Comment by xiaokyo** [comment]
V4 即将发布，已解决该问题，感谢反馈
