### ISSUE TITLE
如何自定义paste事件？

### ISSUE THREAD

**Issue by NO-MAP** [wangeditor-team/wangEditor#2256]
## 功能需求
我需要在Editor上 执行paste 事件时，去对数据做判断操作，然后再用insertHTML 去插入自定义的dom节点

## 疑问
我可以监听到 paste事件，但是并不能阻止 editor的粘贴操作，是否有相应的api 禁用editor的粘贴？
或者有什么其他办法可以实现我这个需求么？

希望尽快回复。thanks~

**Comment by NO-MAP** [comment]
## 已解决。

在源码中找到了这个方法 -->  pasteTextHandle
可以实现目前的需求。

**Comment by angry-bread** [comment]
我没找到这个方法诶，楼主是在哪个文件找到的

**Comment by wangfupeng1988** [comment]
@angry-bread v5 的在这里 https://www.wangeditor.com/v5/editor-config.html#custompaste
