### ISSUE TITLE
请问向编辑器设置内容时同时遇到代码中含有“\n”和代码回车换行时，报错怎么处理(macOS系统)

### ISSUE THREAD

**Issue by ChocoliBao** [wangeditor-team/wangEditor#2259]
#include<stdio.h>
int main()
{
    printf("Hello, World !\n");
    return 0;
}

在代码区域回显报错不知道该怎么解决了。谢谢您了。

**Comment by xiaokyo** [comment]
这代码是c语言吧

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
