### ISSUE TITLE
请问如何解绑onchange函数呢？

### ISSUE THREAD

**Issue by smallnine9** [wangeditor-team/wangEditor#2261]
我阅读了官方文档，上面指明了使用editor.customConfig.onchange =  function 的方式来添加onchange函数，那请问是否可以绑定多个onchange函数呢？如果可以，又是否可以解绑某个绑定的onchange函数呢

**Comment by xiaokyo** [comment]
已记录该问题，会安排在 V4 版本中解决，感谢反馈
