### ISSUE TITLE
Vue3.0 support

### ISSUE THREAD

**Issue by jahnli** [wangeditor-team/wangEditor#2263]
Could you tell me the author， Do you plan to support Vue3.0 and when do you expect to implement it

**Comment by wangfupeng1988** [comment]
@shulandmimi  支持一下这个问题吧。
可以创建一个新的 repo https://github.com/wangeditor-team/wangEdior-with-vue3

**Comment by UltramanWeiLai** [comment]
Vue2 & Vue3 的使用示例可以参考：https://github.com/wangeditor-team/wangEditor-with-vue
