### ISSUE TITLE
回车时光标会自动跳到第一行第一个字的位置

### ISSUE THREAD

**Issue by cshenger** [wangeditor-team/wangEditor#2265]
我在编辑完之后点击回车，光标在下一行，但是在下一行编辑完之后光标就会自动跳回第一行第一个字的位置，希望帮忙看一下
这个问题在设置了this.editor.config.focus = false的时候会触发

**Comment by cshenger** [comment]
这个问题在设置了this.editor.config.focus = false的时候会触发

**Comment by cshenger** [comment]
目前我的解决办法是不要在富文本一开始就设置**this.editor.config.focus = false**，而是利用目前提供的onfocus事件和onblur事件，获取焦点时为true，失去焦点时为false。不过还是希望官方有空能看一下不这么设置就配置一次的情况下怎么解决。
```javascript
this.editor.config.onfocus = newHtml => {
    this.editor.config.focus = true;
}

this.editor.config.onblur = newHtml => {
    this.editor.config.focus = false;
};
```

**Comment by UltramanWeiLai** [comment]
能具体描述一下问题发生的步骤吗？

**Comment by clinfc** [comment]
> 目前我的解决方法是不要在富文本一开始就设置**this.editor.config.focus = false**，而是利用目前提供的onfocus事件和onblur事件，获取焦点时为真，失去焦点时为false。希望官方有空能看一下不这么设置就配置一次的情况下怎么解决。
> 
> ```js
> 这个。编辑。配置。onfocus  =  newHtml  =>  {
>     此。编辑。配置。焦点 = 真; 
> }
> 
> 这个。编辑。配置。onblur  =  newHtml  =>  { 
>     this 。编辑。配置。焦点 = 错误; 
> } ;
> ```

`editor.config.focus` 是在 `editor.create` 之前调用的，为的是用户不希望渲染成功后自动聚焦的情况，你这么用的意义何在？

**Comment by clinfc** [comment]
> 目前我的解决办法是不要在富文本一开始就设置**this.editor.config.focus = false**，而是利用目前提供的onfocus事件和onblur事件，获取焦点时为true，失去焦点时为false。不过还是希望官方有空能看一下不这么设置就配置一次的情况下怎么解决。
> 
> ```js
> this.editor.config.onfocus = newHtml => {
>     this.editor.config.focus = true;
> }
> 
> this.editor.config.onblur = newHtml => {
>     this.editor.config.focus = false;
> };
> ```

`editor.config.focus` 是在 `editor.create` 之前调用的，为的是用户不希望渲染成功后自动聚焦的情况，你这么用的意义何在？

**Comment by cshenger** [comment]
您好，不用了，我在其他的issue上找到了解答，是因为配合vue的watch使用时每次会刷新光标。
