### ISSUE TITLE
多个富文本框的时候，无论粘贴图片在哪一个富文本框，图片总会贴在最后一个文本框里。怎么解决啊

### ISSUE THREAD

**Issue by luoxiaofeng1029** [wangeditor-team/wangEditor#2266]
![QQ图片20201009174354](https://user-images.githubusercontent.com/50006313/95568619-0b1fd480-0a57-11eb-898f-2c1652c4d0de.png)

引入的js是这个
https://unpkg.com/wangeditor@4.0.0/dist/wangEditor.min.js 

一个文本框上传图片和直接粘贴都没问题。多个就不行了（上传依然没问题，直接粘贴不行）

 const E = window.wangEditor

        const editor1 = new E('#adverseCause')
        // 配置菜单栏，删减菜单，调整顺序
        editor1.config.menus = [
            'image',
        ]
        // 配置 onchange 回调函数
        editor1.config.onchange = function (newHtml) {
            $('#adverseCause_new').val(newHtml)
        }
        editor1.config.placeholder = '请输入'
        editor1.config.height = 100
        editor1.config.zIndex = 500
        editor1.config.uploadImgMaxLength = 1
        editor1.config.uploadImgMaxSize = 10 * 1024 * 1024 // 10M
        editor1.config.uploadImgShowBase64 = true
        editor1.config.showFullScreen = false
        editor1.create()

        const editor2 = new E('#effectiveMeasure')
        // 配置菜单栏，删减菜单，调整顺序
        editor2.config.menus = [
            'image',
        ]
        // 配置 onchange 回调函数
        editor2.config.onchange = function (newHtml) {
            $('#effectiveMeasure_new').val(newHtml)
        }
        editor2.config.placeholder = '请输入'
        editor2.config.height = 100
        editor2.config.zIndex = 500
        editor2.config.uploadImgMaxLength = 1
        editor2.config.uploadImgMaxSize = 10 * 1024 * 1024 // 10M
        editor2.config.uploadImgShowBase64 = true
        editor2.config.showFullScreen = false
        editor2.create()

        const editor3 = new E('#beforeImprove')
        // 配置菜单栏，删减菜单，调整顺序
        editor3.config.menus = [
            'image',
        ]
        // 配置 onchange 回调函数
        editor3.config.onchange = function (newHtml) {
            $('#beforeImprove_new').val(newHtml)
        }
        editor3.config.placeholder = '请输入'
        editor3.config.height = 100
        editor3.config.zIndex = 500
        editor3.config.uploadImgMaxLength = 1
        editor3.config.uploadImgMaxSize = 10 * 1024 * 1024 // 10M
        editor3.config.uploadImgShowBase64 = true
        editor3.config.showFullScreen = false
        editor3.create()

        const editor4 = new E('#afterImprove')
        // 配置菜单栏，删减菜单，调整顺序
        editor4.config.menus = [
            'image',
        ]
        // 配置 onchange 回调函数
        editor4.config.onchange = function (newHtml) {
            $('#afterImprove_new').val(newHtml)
        }
        editor4.config.placeholder = '请输入'
        editor4.config.height = 100
        editor4.config.zIndex = 500
        editor4.config.uploadImgMaxLength = 1
        editor4.config.uploadImgMaxSize = 10 * 1024 * 1024 // 10M
        editor4.config.uploadImgShowBase64 = true
        editor4.config.showFullScreen = false
        editor4.create()

**Comment by shulandmimi** [comment]
内部实例保存导致的问题，已修复
