### ISSUE TITLE
mac 下，safari、qq浏览器，都无法编辑内容，光标消失

### ISSUE THREAD

**Issue by ShaoboLiu1992** [wangeditor-team/wangEditor#2267]
![{X@8B0}P{4EGJ8O`AESJO B](https://user-images.githubusercontent.com/31101534/95642545-b4a8a980-0adb-11eb-9d68-176bb51e0858.jpg)

**Comment by ShaoboLiu1992** [comment]
![Uploading {X@8B0}P{4EGJ8O`AESJO[B.jpg…]()

**Comment by wangfupeng1988** [comment]
我这里复现不了。
请问你那边 mac os 是什么版本？以及浏览器是什么版本？

**Comment by ShaoboLiu1992** [comment]
很奇怪，我们什么都没做，现在可以了，不知道是什么问题，当时是好几台电脑，还有一台win的火狐不可以，现在又全部好了

**Comment by ShaoboLiu1992** [comment]
> 我这里复现不了。
> 请问你那边 mac os 是什么版本？以及浏览器是什么版本？
很奇怪，我们什么都没做，现在可以了，不知道是什么问题，当时是好几台电脑，还有一台win的火狐不可以，现在又全部好了

**Comment by UltramanWeiLai** [comment]
好的既然没有问题的话，这个 issues 我们就关闭了
