### ISSUE TITLE
编辑器内内容为空获取html元素默认会有一个换行标签

### ISSUE THREAD

**Issue by sawada27** [wangeditor-team/wangEditor#2270]
![image](https://user-images.githubusercontent.com/37053515/95644470-6ac6c000-0ae9-11eb-9f17-07b9457c4791.png)
此问题导致渲染填写的结果时会出现错位，由于多一个p加换行标签，换行标签会被渲染成一个空的p标签

**Comment by wangfupeng1988** [comment]
http://106.55.153.217:8881/master/examples/index.html 在这个测试环境下，清空编辑器，执行 `editor.txt.html()` 未复现你的问题。

请描述能复现的问题详细步骤。

**Comment by sawada27** [comment]
![image](https://user-images.githubusercontent.com/37053515/95807936-f33d9e80-0d3d-11eb-841b-4c6885f41308.png)
element 与vue条件下
1.打开element dialog控件
2.editor对应id的div在dialog是动态生成，因此用vue.nexttick()加载初始化编辑器方法
3.编辑器中无值，div中仅有样式，加载完成后的编辑器调用editor.txt.htm()方法默认为'<p><br></p>'
![image](https://user-images.githubusercontent.com/37053515/95808215-9098d280-0d3e-11eb-8337-eb03c5be818a.png)

**Comment by sawada27** [comment]
``
默认为<p><br></p>
输入几个空格后变为<p>   <p>如图

**Comment by clinfc** [comment]
富文本编辑器内容为空的时候，其实内部是有 <p><br></p> 这样的标签的，这是不可避免的机制，如果没有这对标签，会造成很多意外的情况。建议你在获取内容后自动判断下就可以了
