### ISSUE TITLE
创建表格没有反应怎么解决？

### ISSUE THREAD

**Issue by kkkkkkxser** [wangeditor-team/wangEditor#2272]
创建表格没有反应怎么解决？

**Comment by wangfupeng1988** [comment]
我复现不了，怎么解决？

**Comment by kkkkkkxser** [comment]
> 我复现不了，怎么解决？

我也不知道咋复现呀，我用到的就下面这些代码
![dcc4a1b02d5cf59576ff8b50af68a7f](https://user-images.githubusercontent.com/57437076/95710635-a7ceb600-0c93-11eb-9aa8-57156616f0e8.png)

**Comment by kkkkkkxser** [comment]
> 我复现不了，怎么解决？

const editor = new wangEditor(`#editor`);
    editor.config.onchange = (html) => {
      this.editorContent = html;
    };
    editor.config.uploadImgServer = "/upload-img";
    editor.config.menus = [
      // 菜单配置
      "head", // 标题
      "bold", // 粗体
      "fontSize", // 字号
      "fontName", // 字体
      "italic", // 斜体
      "underline", // 下划线
      "strikeThrough", // 删除线
      "foreColor", // 文字颜色
      "backColor", // 背景颜色
      "link", // 插入链接
      "list", // 列表
      "justify", // 对齐方式
      "quote", // 引用
      "emoticon", // 表情
      "image", // 插入图片
      "table", // 表格
      "code", // 插入代码
      "undo", // 撤销
      "redo", // 重复
    ];
    editor.create();
    this.editor = editor;

**Comment by wangfupeng1988** [comment]
上述代码，我这里复现不了问题。

**Comment by UltramanWeiLai** [comment]
因为你长时间没有回复，所以我们就暂时关闭该issues
