### ISSUE TITLE
为什么v4去掉了图片百分比设置，强烈建议加回来

### ISSUE THREAD

**Issue by yuntian001** [wangeditor-team/wangEditor#2273]
评估了好多编辑器，全部都是默认写死宽高像素的图片插入， 因为v3版本是百分比设置宽度才用的wangeditor，为什么在v4版本去掉了？？这样在富文本手机或电脑浏览时缩放查看 图片真心 百分比比较方便，不知道为什么市面上的图片全是写死像素

**Comment by wangfupeng1988** [comment]
可以在 tooltip 中加上 30% 50% 100%

**Comment by UltramanWeiLai** [comment]
该功能将会在下个版本中发布，敬请期待
