### ISSUE TITLE
功能菜单图标支持自定义

### ISSUE THREAD

**Issue by programmer-fly** [wangeditor-team/wangEditor#2278]
## 功能描述

![image](https://user-images.githubusercontent.com/26021587/95671660-1d6f4f00-0bcc-11eb-9fbe-44a42f5ad925.png)
菜单中的图标和我们现有系统风格不一致，系统能换一套icon如这样
![image](https://user-images.githubusercontent.com/26021587/95671723-c5851800-0bcc-11eb-948c-fca0b88721c4.png)

希望可以支持自定义图标，最好可以支持使用iconfont

## 提炼几个功能点

- 可以在配置中自定义图标
- 图标可以支持iconfont和svg

## 参考

这个是一个react的富文本编辑器，可以自定义图标
https://braft.margox.cn/

**Comment by wangfupeng1988** [comment]
暂不打算支持该功能。建议自己去覆盖菜单的 css 样式。
