### ISSUE TITLE
react 编辑的时候 多次按回车键或空格键聚焦点会跳到文章末尾

### ISSUE THREAD

**Issue by Arron-Maker** [wangeditor-team/wangEditor#2280]
## bug 描述

*react 编辑的时候 多次按回车键或空格键聚焦点会跳到文章末尾*

## 你预期的样子是？

*正常操作就可以*

## 浏览器及版本号

*Google Chrome 版本 86.0.4240.75（正式版本） (x86_64)*

## wangEditor 版本

*"wangeditor": "^3.1.1"*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请升级 v4 版本吧。
v3 升级 v4 成本不高，很平滑，有问题可以随时在 qq 群提问。
