### ISSUE TITLE
上传图片,怎么设置图片的宽高,一传图片无论任何尺寸,都是100%编辑器宽度

### ISSUE THREAD

**Issue by Husky-Yellow** [wangeditor-team/wangEditor#2281]
在编辑器中选择一个图片,都是宽度为100%,填充,
怎么才能让其按照用户想要的宽度进行展示

**Comment by wangfupeng1988** [comment]
暂不支持该功能。图片可以通过拖拽调整大小。后面也会支持百分比调整 https://github.com/wangeditor-team/wangEditor/issues/2273

PS：下次提交 issue 请务必按照模板，否则问题将不予理会。
