### ISSUE TITLE
如果字符串没有html标签，wangEditor初始化时就不会显示在编辑器里，这是什么问题？代码和渲染结果如下。

### ISSUE THREAD

**Issue by newbee-mall** [wangeditor-team/wangEditor#2283]
## bug 描述

同样都是在 #div1 里面，初始化时也是初始化 div1 成为编辑器，但是两个字符串，一个带有html的 p 标签，一个没有带该标签，渲染后就只有带标签的出现在编辑器内，未带标签的没有初始化进去。

![image](https://user-images.githubusercontent.com/54432435/95745588-f138f880-0cc7-11eb-8871-c60bbb4e1d7d.png)

## 你预期的样子是？

在 div1 内的两个字符串都出现在编辑器内。

## 浏览器及版本号

chrome 版本 84.0.4147.105（正式版本） （64 位）

## wangEditor 版本

最新版本

## 官网能否复现该 bug ？

不清楚这是不是bug，只是提一下这个问题。

## 最小成本的复现步骤

代码如下：

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="div1">
    初始化的内容
    <p>初始化的内容</p>
</div>
</body>
<script type="text/javascript" src="https://unpkg.com/wangeditor/dist/wangEditor.min.js"></script>
<script type="text/javascript">
    const E = window.wangEditor
    const editor = new E('#div1')
    editor.create()
</script>
</html>
```

**Comment by wangfupeng1988** [comment]
暂不支持该功能。
我们规定，所有的文本内容，都必须用 `<p></p>`里包裹。否则会出现其他额外的问题。
