### ISSUE TITLE
分隔线bug

### ISSUE THREAD

**Issue by lisheng741** [wangeditor-team/wangEditor#2289]
## bug 描述

如果编辑器第一行开始就添加多条分割线，某些情况下，第一条分隔线会出现无法通过“退格键”删除的bug（可以通过撤销删除）。
下面列举一种个人测试可以正常复现的操作，还有其他操作也可以复现，但是比较玄……
可复现的操作：分割线 -> 分割线 -> 分割线 -> 撤销（余下2条分隔线） -> “退格键”删掉第二条分隔线 -> 最后一条分隔线无法删除

## 你预期的样子是？

正常删除分隔线

## 浏览器及版本号

Google Chrome | 85.0.4183.121 (正式版本) （64 位） (cohort: Stable)

## wangEditor 版本

V4.0.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  添加3条分隔线（“分隔线”按钮按3次）
- 步骤二  “撤销”按钮一次（余下2条分隔线）
- 步骤三  “退格键”一次

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/96395364-0bf2fc00-11f7-11eb-99e1-2624011aa1f8.png)
该问题，在这个 PR 中已解决了。
至少是，你这个最小成本复现是无法再重现的
