### ISSUE TITLE
工具栏按钮 鼠标悬浮显示提示文字

### ISSUE THREAD

**Issue by lisheng741** [wangeditor-team/wangEditor#2290]
## 功能描述

鼠标悬浮在toolbar 上的 button 没有提示性的文字，新客户使用一开始分不清 button 作用。
希望鼠标悬浮在button上时能增加提示性文字。

## 提炼几个功能点

- 鼠标悬浮在button上时能增加提示性文字

## 原型图

![image](https://user-images.githubusercontent.com/53617305/95805797-d488d900-0d38-11eb-9b2a-3060fd02b932.png)

## 可参考的案例

无

**Comment by UltramanWeiLai** [comment]
该问题需要开发新功能，已安排执行

**Comment by wangfupeng1988** [comment]
提示文字，注意考虑多语言支持

**Comment by rsl140** [comment]
@wangfupeng1988 @UltramanWeiLai  https://www.yuque.com/docs/share/af821a76-8f89-45b9-9d69-1439b1e8263a?# 《需求文档 - 菜单按钮鼠标悬浮显示提示文字（饶思羚）》
