### ISSUE TITLE
禁止编辑模式下，tooltip 仍然可以作用

### ISSUE THREAD

**Issue by clinfc** [wangeditor-team/wangEditor#2293]
## bug 描述

contenteditable="false" 时，图片 resize 和 tooltip 仍能工作

## 你预期的样子是？

contenteditable="false" 时，图片 resize 和 tooltip 不再工作

## 浏览器及版本号

所有

## wangEditor 版本

V4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

设置 contenteditable="false"

**Comment by wangfupeng1988** [comment]
这个问题，我们新开发一个禁用 API 吧，不用简单粗暴的 `contenteditable="false"` 了。

我们作为新功能开发，这会花费一点时间。

**Comment by wangfupeng1988** [comment]
升级 v4.1.0 版本，定义了新的 API，代码参考 https://github.com/wangeditor-team/wangEditor/blob/master/examples/disable.html 

文档后面会补充上
