### ISSUE TITLE
建议增加编辑过程中删除图片时，增加已上传图片的删除事件供处理（一般为同步从服务端删除图片）

### ISSUE THREAD

**Issue by zhanhuichina** [wangeditor-team/wangEditor#2294]
## 功能描述

在编辑时，经常需要来回更换图片，以查看效果，但这样会上传很多不必要的图片到服务器；希望控件能支持检测删除图片或其它媒体文件事件，给个回调方法以便于处理。

## 功能点

- 功能1  删除图片或媒体文件时的回调方法，参数为图片的url地址

## 原型图

没有

## 可参考的案例

没有参考案例，类似本控件的onchange 回调函数，用法示例：

// 配置 ondeletefile 回调函数
editor.config.ondeletefile = function (fileurl) {
    console.log('被删除的图片文件', fileurl)
}

**Comment by UltramanWeiLai** [comment]
该功能并不在编辑器范围内，而且删除图片的行为有很多例如：撤销、退格、选取后退格、选取后输入新内容，很难进行捕捉，所以暂时不打算制作该功能
你可以和后端配合，编辑时上传的是临时文件夹，编辑器内容保存后，在把文件移动到正式文件夹下
