### ISSUE TITLE
建议增加将富文本内容转换为html代码并展示的功能，类似ueditor

### ISSUE THREAD

**Issue by sunzeJAVA** [wangeditor-team/wangEditor#2295]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by UltramanWeiLai** [comment]
请按 issue 模板格式提交，并且写清楚你的问题和意见
