### ISSUE TITLE
建议移除拖拽非图片文件进编辑框时的提示

### ISSUE THREAD

**Issue by Jasery** [wangeditor-team/wangEditor#2296]
## bug 描述

当拖拽其他类型的文件进入编辑框，比如word文档，会提示`图片验证未通过`

![image](https://user-images.githubusercontent.com/20091279/95848137-3ae51a00-0d80-11eb-9294-47a37ee85415.png)

## 你预期的样子是？

建议不是本插件处理的文件类型忽略即可，因为有开放了相关hook可以自己处理某些类型的文件。现在的问题是我自己的插件处理好了，但是却无法屏蔽其他插件的错误提示。

## 浏览器及版本号

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

## wangEditor 版本

4.0.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
  本地创建一个非图片类型的文件，如word文档
- 步骤二
  把此文件拖入编辑框

**Comment by clinfc** [comment]
关于此问题，你可以把这个自定义配置设置为空函数即可，[配置链接](http://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/10-%E8%87%AA%E5%AE%9A%E4%B9%89alert.html)

**Comment by Jasery** [comment]
> 关于此问题，你可以把这个自定义配置设置为空函数即可，[配置链接](http://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/10-%E8%87%AA%E5%AE%9A%E4%B9%89alert.html)

这里并不是想屏蔽所有提示， 而是对于拖拽文件这类操作，插件自己处理不了的文件没必要强行提示，因为有可能有其他插件可以处理

**Comment by wangfupeng1988** [comment]
@Jasery  任何输入都要对应输出，你拖拽一个 word 文档进去，总得给掉提示才行。
如你说的：处理不了的就不给提示 —— 这个功能，目前并未打算统一支持。你可以去实现自定义上传，自己定义上传规则 http://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/11-%E8%87%AA%E5%B7%B1%E5%AE%9E%E7%8E%B0%E4%B8%8A%E4%BC%A0%E5%8A%9F%E8%83%BD.html
