### ISSUE TITLE
多行文本选中后无法修改对齐方式

### ISSUE THREAD

**Issue by nulipinbo** [wangeditor-team/wangEditor#2298]
## bug 描述

*多行文本选中后，无法设置对其方式，目前只能单行设置对其方式*

## 你预期的样子是？

*多行文本 多张图片 只要是批量选中后 都可以统一设置对其方式 简化操作 提升用户体验*

## 浏览器及版本号

*版本 85.0.4183.121（正式版本） （64 位）*

## wangEditor 版本

*3.6.4?*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 输入多行文本并选中  修改对齐方式

**Comment by wangfupeng1988** [comment]
已修复，请升级 v4.1.0 版本。
如有问题，请再去提交新 issue 。
