### ISSUE TITLE
查看源码

### ISSUE THREAD

**Issue by ChartWay** [wangeditor-team/wangEditor#2299]
## 功能描述

点击查看源码，可以直接修改源码

## 提炼几个功能点

- 点击“源码”按钮，编辑器切换至源码编辑模式（禁用其他按钮）
- 源码格式化
- 修改源码
- 点击“源码”按钮，返回可见即可得模式

## 原型图

无

## 可参考的案例

https://summernote.org/

**Comment by UltramanWeiLai** [comment]
该问题需要开发新功能，已安排执行

**Comment by wangfupeng1988** [comment]
这个功能我们现在无法确定未来是否肯定要做。
因为你看看周边在线 office 的编辑器，全都没有了这个功能了。
即，如果面向未来考虑，这个功能会慢慢的消失，就像 IE 浏览器一样。

上述，外加查看编辑源码，是一个非常大非常重量级的功能，开发成本非常高。

所以，综合来说，这个功能我们先 pending 一下。

**Comment by ChartWay** [comment]
> 这个功能我们现在无法确定未来是否肯定要做。
> 因为你看看周边在线 office 的编辑器，全都没有了这个功能了。
> 即，如果面向未来考虑，这个功能会慢慢的消失，就像 IE 浏览器一样。
> 
> 上述，外加查看编辑源码，是一个非常大非常重量级的功能，开发成本非常高。
> 
> 所以，综合来说，这个功能我们先 pending 一下。

对重量级功能持不同看法，这个功能理论上是很简单的。

**Comment by 6LWa6ZKx** [comment]
> > 这个功能我们现在无法确定未来是否肯定要做。
> > 因为你看看周边在线 office 的编辑器，全都没有了这个功能了。
> > 即，如果面向未来考虑，这个功能会慢慢的消失，就像 IE 浏览器一样。
> > 上述，外加查看编辑源码，是一个非常大非常重量级的功能，开发成本非常高。
> > 所以，综合来说，这个功能我们先 pending 一下。
> 
> 对重量级功能持不同看法，这个功能理论上是很简单的。

查看源码这个功能感觉很有用，昨天想通过iframe查看我们自己做的报表页面发现无法插入，后面通过kindeditor在源码里面插入了<iframe>标签暂时性实现了。

**Comment by yuan2022** [comment]
+1，希望加上一个查看源码的功能，有时候鼠标点怎么也实现不了样式，必须改下源码样式才行。。。

**Comment by qqii3184** [comment]
对增加此功能表示支持，比如目前表格不能变更大小的问题，通过修改源码实现起来更加简单一些。

**Comment by ChartWay** [comment]
@UltramanWeiLai 看来需求量还是挺大的，请求加入受理

**Comment by 6LWa6ZKx** [comment]
可以参考下 CKEditor4，CKEditor5是收费的，但是功能更强大。
https://ckeditor.com/ckeditor-4/demo/#document

**Comment by wangfupeng1988** [comment]
经详细考虑，暂不开发这个功能。
编辑器功能还是要保持简洁，暂时不考虑加入过于复杂的编辑功能。
对此表示歉意，大家久等了。

如有需要，可以参考[这个](http://www.wangeditor.com/doc/pages/13-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/03-%E6%9F%A5%E7%9C%8B%E6%BA%90%E7%A0%81%E5%92%8C%E4%BF%AE%E6%94%B9%E6%BA%90%E7%A0%81.html)自行开发。
遇到困难，可新建 issue 或者到 qq 群提问。
