### ISSUE TITLE
一个页面同时存在2个编辑器实例报错

### ISSUE THREAD

**Issue by Ary-tan** [wangeditor-team/wangEditor#2300]
## bug 描述

*一个页面同时存在2个编辑器实例，在第一个编辑器里面添加表格，点击表格的tooltip按钮事件报错*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
还请补充好信息
