### ISSUE TITLE
在angular7项目中引入V4版本编辑器报错

### ISSUE THREAD

**Issue by scottMan1001** [wangeditor-team/wangEditor#2301]
## bug 描述

参照官网文档正确安装，并且引入。
![image](https://user-images.githubusercontent.com/38151889/95972338-e8216600-0e44-11eb-8b10-bbe3eb01b6a0.png)

![image](https://user-images.githubusercontent.com/38151889/95972344-e9eb2980-0e44-11eb-994f-6ea0c8a27a38.png)
![image](https://user-images.githubusercontent.com/38151889/95972384-f2436480-0e44-11eb-81bf-1d0904906286.png)

## 你预期的样子是？
应该正确new E 不会报错

## 浏览器及版本号

![image](https://user-images.githubusercontent.com/38151889/95972527-23239980-0e45-11eb-9034-8a77b263da54.png)

## wangEditor 版本

*请输入内容……*
![image](https://user-images.githubusercontent.com/38151889/95972541-26b72080-0e45-11eb-95f4-7b6f8e3fdcd2.png)

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
使用angularCli创建任意版本的angular7 或者最新的10版本项目
- 步骤二
参考官网引入wangEditot
- 步骤三
构建相应的wangEdtior页面

**Comment by wangfupeng1988** [comment]
angular7 不会用啊，没用过，不知道怎么下载安装。
能否直接给一个 git repo ，能复现 bug 即可，越简单越好，并且写明运行和复现步骤。
这样，我们能更快复现问题。

**Comment by scottMan1001** [comment]
> angular7 不会用啊，没用过，不知道怎么下载安装。
> 能否直接给一个 git repo ，能复现 bug 即可，越简单越好，并且写明运行和复现步骤。
> 这样，我们能更快复现问题。

 1.npm install -g @angular/cli   全局安装
2. ng new demo
 剩下的就是按照官网引入wangEditor   引入 成功后，  cd demo ,npm run start

**Comment by irootechMT** [comment]
确实是  3.1.1的版本就可以。还有就是  this.editor.config.height =200
      this.editor.config.focus = false; 设置了会报错

**Comment by scottMan1001** [comment]
> angular7 不会用啊，没用过，不知道怎么下载安装。
> 能否直接给一个 git repo ，能复现 bug 即可，越简单越好，并且写明运行和复现步骤。
> 这样，我们能更快复现问题。



> 确实是 3.1.1的版本就可以。还有就是 this.editor.config.height =200
> this.editor.config.focus = false; 设置了会报错

你们也遇到这汇总情况了嘛。。 angular引入问题。。

**Comment by jeromehan** [comment]
> > angular7 不会用啊，没用过，不知道怎么下载安装。
> > 能否直接给一个 git repo ，能复现 bug 即可，越简单越好，并且写明运行和复现步骤。
> > 这样，我们能更快复现问题。
> 
> > 确实是 3.1.1的版本就可以。还有就是 this.editor.config.height =200
> > this.editor.config.focus = false; 设置了会报错
> 
> 你们也遇到这汇总情况了嘛。。 angular引入问题。。

经过测试是wangEditor window.Promise = Promise 和 ng zone.js冲突了，升级zone.js@0.11.3之后在wangEditor中加入判断，如果不存在Promise进行赋值。就能解决了

**Comment by scottMan1001** [comment]
> 中最好加上判断是否存在再赋值
不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？

**Comment by scottMan1001** [comment]
> > > angular7 不会用啊，没用过，不知道怎么下载安装。
> > > 能否直接给一个 git repo ，能复现 bug 即可，越简单越好，并且写明运行和复现步骤。
> > > 这样，我们能更快复现问题。
> > 
> > 
> > > 确实是 3.1.1的版本就可以。还有就是 this.editor.config.height =200
> > > this.editor.config.focus = false; 设置了会报错
> > 
> > 
> > 你们也遇到这汇总情况了嘛。。 angular引入问题。。
> 
> 经过测试是wangEditor window.Promise = Promise 和 ng zone.js冲突了，升级zone.js@0.11.3之后在wangEditor中加入判断，如果不存在Promise进行赋值。就能解决了.所以源码中最好加上判断是否存在再赋值引用

如果你们用的是我提供的地址，并引入，那么  
![image](https://user-images.githubusercontent.com/38151889/99367312-c3f9ee80-28f4-11eb-9913-affbf9797e19.png)请问gui贵方也遇到这个问题了嘛

**Comment by jeromehan** [comment]
> > 中最好加上判断是否存在再赋值
> > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> 
> 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)

源码版本修改

**Comment by jeromehan** [comment]
> > 中最好加上判断是否存在再赋值
> > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> 
> 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
那个是源码引用路径有问题呢，源码版本的问题，可以自己手动改一下，不是啥大问题

**Comment by scottMan1001** [comment]
> > > 中最好加上判断是否存在再赋值
> > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > 
> > 
> > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> 
> 源码版本修改

![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
你是想让我修改这部分还是？  我升级ZONE.JS之后，

**Comment by jeromehan** [comment]
> > > > 中最好加上判断是否存在再赋值
> > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > 
> > > 
> > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > 
> > 
> > 源码版本修改
> 
> ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> 你是想让我修改这部分还是？ 我升级ZONE.JS之后，

你可以clone一下源码然后修改打包成dist 直接在打包文件改，没发改，太乱了

**Comment by jeromehan** [comment]
> > > > 中最好加上判断是否存在再赋值
> > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > 
> > > 
> > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > 
> > 
> > 源码版本修改
> 
> ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> 你是想让我修改这部分还是？ 我升级ZONE.JS之后，

![image](https://user-images.githubusercontent.com/19773879/99371302-b3984280-28f9-11eb-9bef-8ccc7a0a79e3.png)
源码修改此处

**Comment by scottMan1001** [comment]
> > > > > 中最好加上判断是否存在再赋值
> > > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > > 
> > > > 
> > > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > > 
> > > 
> > > 源码版本修改
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> > 你是想让我修改这部分还是？ 我升级ZONE.JS之后，
> 
> ![image](https://user-images.githubusercontent.com/19773879/99371302-b3984280-28f9-11eb-9bef-8ccc7a0a79e3.png)
> 源码修改此处

嗯嗯， 请问是否会发布新版本 。如果发布，准备安装你们新版本的包体

**Comment by jeromehan** [comment]
> > > > > > 中最好加上判断是否存在再赋值
> > > > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > > > 
> > > > > 
> > > > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > > > 
> > > > 
> > > > 源码版本修改
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> > > 你是想让我修改这部分还是？ 我升级ZONE.JS之后，
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19773879/99371302-b3984280-28f9-11eb-9bef-8ccc7a0a79e3.png)
> > 源码修改此处
> 
> 嗯嗯， 请问是否会发布新版本 。如果发布，准备安装你们新版本的包体

我也不是成员，看他们合这个pr不合了。你可以先这样解决。

**Comment by scottMan1001** [comment]
> > > > > > > 中最好加上判断是否存在再赋值
> > > > > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > > > > 
> > > > > > 
> > > > > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > > > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > > > > 
> > > > > 
> > > > > 源码版本修改
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> > > > 你是想让我修改这部分还是？ 我升级ZONE.JS之后，
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/19773879/99371302-b3984280-28f9-11eb-9bef-8ccc7a0a79e3.png)
> > > 源码修改此处
> > 
> > 
> > 嗯嗯， 请问是否会发布新版本 。如果发布，准备安装你们新版本的包体
> 
> 我也不是成员，看他们合这个pr不合了。你可以先这样解决。

3Q

**Comment by scottMan1001** [comment]
> > > > > > > 中最好加上判断是否存在再赋值
> > > > > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > > > > 
> > > > > > 
> > > > > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > > > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > > > > 
> > > > > 
> > > > > 源码版本修改
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> > > > 你是想让我修改这部分还是？ 我升级ZONE.JS之后，
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/19773879/99371302-b3984280-28f9-11eb-9bef-8ccc7a0a79e3.png)
> > > 源码修改此处
> > 
> > 
> > 嗯嗯， 请问是否会发布新版本 。如果发布，准备安装你们新版本的包体
> 
> 我也不是成员，看他们合这个pr不合了。你可以先这样解决。

![image](https://user-images.githubusercontent.com/38151889/99372661-746af100-28fb-11eb-9e17-8745d242743e.png)


这个问题呢

**Comment by jeromehan** [comment]
> > > > > > > > 中最好加上判断是否存在再赋值
> > > > > > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > > > > > 
> > > > > > > 
> > > > > > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > > > > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > > > > > 
> > > > > > 
> > > > > > 源码版本修改
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> > > > > 你是想让我修改这部分还是？ 我升级ZONE.JS之后，
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/19773879/99371302-b3984280-28f9-11eb-9bef-8ccc7a0a79e3.png)
> > > > 源码修改此处
> > > 
> > > 
> > > 嗯嗯， 请问是否会发布新版本 。如果发布，准备安装你们新版本的包体
> > 
> > 
> > 我也不是成员，看他们合这个pr不合了。你可以先这样解决。
> 
> ![image](https://user-images.githubusercontent.com/38151889/99372661-746af100-28fb-11eb-9e17-8745d242743e.png)
> 
> 这个问题呢

就是修改polyfill源码啊，重新打个包，看截图。就能解决

**Comment by scottMan1001** [comment]
> > > > > > > > > 中最好加上判断是否存在再赋值
> > > > > > > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > > > > > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 源码版本修改
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> > > > > > 你是想让我修改这部分还是？ 我升级ZONE.JS之后，
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/19773879/99371302-b3984280-28f9-11eb-9bef-8ccc7a0a79e3.png)
> > > > > 源码修改此处
> > > > 
> > > > 
> > > > 嗯嗯， 请问是否会发布新版本 。如果发布，准备安装你们新版本的包体
> > > 
> > > 
> > > 我也不是成员，看他们合这个pr不合了。你可以先这样解决。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/38151889/99372661-746af100-28fb-11eb-9e17-8745d242743e.png)
> > 这个问题呢
> 
> 就是修改polyfill源码啊，重新打个包，看截图。就能解决

polyfill源码已经修改，你的意思是药针对wangEditor进行打包吧。 ，请教一下，这个命令是

**Comment by jeromehan** [comment]
> > > > > > > > > > 中最好加上判断是否存在再赋值
> > > > > > > > > > 不太明白你的意思，你是想让我本机升级zone版本，同时在 wangEdirot 源码重 加入判断   还是？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 其次如果你用的是我提供的[https://github.com/scottMan1001/wangeditorForNgTest.git，编译时候是否遇到了](https://github.com/scottMan1001/wangeditorForNgTest.git%EF%BC%8C%E7%BC%96%E8%AF%91%E6%97%B6%E5%80%99%E6%98%AF%E5%90%A6%E9%81%87%E5%88%B0%E4%BA%86)
> > > > > > > > > ![image](https://user-images.githubusercontent.com/38151889/99367677-3bc81900-28f5-11eb-8c09-2625263ba468.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 源码版本修改
> > > > > > > 
> > > > > > > 
> > > > > > > ![image](https://user-images.githubusercontent.com/38151889/99370179-50f27700-28f8-11eb-86ba-e49f6040ac5d.png)
> > > > > > > 你是想让我修改这部分还是？ 我升级ZONE.JS之后，
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/19773879/99371302-b3984280-28f9-11eb-9bef-8ccc7a0a79e3.png)
> > > > > > 源码修改此处
> > > > > 
> > > > > 
> > > > > 嗯嗯， 请问是否会发布新版本 。如果发布，准备安装你们新版本的包体
> > > > 
> > > > 
> > > > 我也不是成员，看他们合这个pr不合了。你可以先这样解决。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/38151889/99372661-746af100-28fb-11eb-9e17-8745d242743e.png)
> > > 这个问题呢
> > 
> > 
> > 就是修改polyfill源码啊，重新打个包，看截图。就能解决
> 
> polyfill源码已经修改，你的意思是药针对wangEditor进行打包吧。 ，请教一下，这个命令是

npm run dev 修改源码之后去dist中找到wangEditor.js 就是打包文件
