### ISSUE TITLE
多编辑器情况下表格的 tooltip 除了删除表格以外的其他功能异常

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2302]
## bug 描述

多编辑器情况下表格的 tooltip 除了删除表格以外的其他功能异常

## 你预期的样子是？

tooltip 功能正常

## 浏览器及版本号

360极速浏览器

## wangEditor 版本

4.0.1

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：单页面创建一个以上的编辑器
- 步骤二：创建表格
- 步骤三：点击非删除表格的 tooltip 按钮

**Comment by xiangyang819** [comment]
我也遇到了这个问题

**Comment by wangfupeng1988** [comment]
已发布 `v4.2.0` 修复
如有问题，可继续提交新 issue 。
