### ISSUE TITLE
编辑器设置有序列表，再设置H1-H6会出现列表数字都是1

### ISSUE THREAD

**Issue by Nicer-n** [wangeditor-team/wangEditor#2303]
## bug 描述

*编辑器设置有序列表，再设置H2会出现列表数字都是1，设置h1会导致排序错乱*

## 你预期的样子是？

*设置有序列表，再H1-H6，排序依旧正常*

## 浏览器及版本号

*Google*

## wangEditor 版本

*3.1.1以及4.0.1*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：先写几行文字
- 步骤二：设置有序列表
- 步骤三：全选，设置文字为H1-H6的字体

**Comment by UltramanWeiLai** [comment]
序列和标题是无法共存的
当你在设置序列的标题后换行输入内容的时候你发现这行不通
如果你的标题需要 序号 的话，还请手动填写
