### ISSUE TITLE
多富文本框情况下,挨个输入文字,有概率有的框输入的文字不能识别到已经被输入

### ISSUE THREAD

**Issue by luoxiaofeng1029** [wangeditor-team/wangEditor#2305]
## bug 描述

多富文本框情况下,挨个输入文字,有概率有的框输入的文字不能识别到已经被输入,相对应的输入监听事件也无法触发.这个概率是随着我输入的速度越快而增加的.正常如果我点击第一个框,输入1,过一秒再点击第二个框输入1,大概率没问题.但是如果我点击第一个框,非常快的输入1后立马就点击第二个框输入1,那么大概率不会被识别到我已经输入1了.其它框同理
以下是正常速度输入：
![正常速度没问题](https://user-images.githubusercontent.com/50006313/96085583-97b51180-0ef3-11eb-972d-54deaf927551.gif)

以下是快速shuru输入出现的问题：
![快速有问题](https://user-images.githubusercontent.com/50006313/96085603-9edc1f80-0ef3-11eb-89e6-dc06e9249138.gif)

## 你预期的样子是？

正常的是,我不论点击哪个框输入内容,都应该立马可以识别到我输入了.并且如果有监听事件,应该也可以触发

## 浏览器及版本号

*请输入内容……*
![image](https://user-images.githubusercontent.com/50006313/96076545-291a8880-0ee0-11eb-8b03-2a43d3be9a4b.png)

## wangEditor 版本

4.0.3的那个js

## 官网能否复现该 bug ？

这个不太理解此项内容.但是实验应该很好实验,就是多几个框,多几个监听事件测一下就知道了

## 最小成本的复现步骤

,就是多几个框,多几个监听事件测一下就知道了.鼠标点击框,立马输入文字,立马点击下一个框,再立马输入,重复操作

**Comment by clinfc** [comment]
只要速度够快就会出现这个问题，无论哪个浏览器

**Comment by luoxiaofeng1029** [comment]
> 只要速度够快就会出现这个问题，无论哪个浏览器

问题是怎么解决，速度不是很快，也还是会出现。

**Comment by clinfc** [comment]
等这个 PR 合并了就解决了
![image](https://user-images.githubusercontent.com/39868400/96244042-213e0f80-0fd8-11eb-86dc-2fdfc5578762.png)

**Comment by clinfc** [comment]
![image](https://user-images.githubusercontent.com/39868400/96244148-4468bf00-0fd8-11eb-812b-d145f6c6ec87.png)
这个 PR 中已解决了这个问题

**Comment by luoxiaofeng1029** [comment]
> ![image](https://user-images.githubusercontent.com/39868400/96244148-4468bf00-0fd8-11eb-812b-d145f6c6ec87.png)
> 这个 PR 中已解决了这个问题

好的，就等合并更新了

**Comment by TheSixer** [comment]
求更新啊 大佬

**Comment by luoxiaofeng1029** [comment]
> 求更新啊 大佬

等作者合并呢，不知道什么时候合并

**Comment by clinfc** [comment]
> 求更新啊 大佬

一个需求的开发都有正规的流程，得按流程走，最快也是下周一了

**Comment by UltramanWeiLai** [comment]
已经更新了4.0.5 版本

**Comment by luoxiaofeng1029** [comment]
的确已修复，棒棒哒

**Comment by qiuyue11** [comment]
@UltramanWeiLai 您好，在v5 版本里又发现了这个问题
