### ISSUE TITLE
React中自定义扩展Panel 菜单，无法获取部分方法

### ISSUE THREAD

**Issue by 1308774130** [wangeditor-team/wangEditor#2306]
## bug 描述

*自定义扩展Panel 菜单，根据源码定义了createPanelConf()方法，但是PanelConf, PanelTabConf 这两个方法没有暴露出来，如果想用统一模板的话无法使用*

## 你预期的样子是？

*可以把PanelConf, PanelTabConf 暴露出来，使在项目中可以使用*

## 浏览器及版本号

*谷歌浏览器 3.0.1.6*

## wangEditor 版本

*V4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
PanelConf, PanelTabConf 可以冲 panel 中解构出来
![image](https://user-images.githubusercontent.com/23336585/96464740-c405c080-125a-11eb-994b-c50fc75b7a2f.png)
![image](https://user-images.githubusercontent.com/23336585/96464784-d1bb4600-125a-11eb-8157-64ec5c37e8d0.png)

**Comment by UltramanWeiLai** [comment]
该问题移步到 #2310

**Comment by wangfupeng1988** [comment]
升级 v4.0.6 ，重新阅读文档 http://www.wangeditor.com/doc/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html
