### ISSUE TITLE
希望兼容v3的多语言功能，省略安装i18next

### ISSUE THREAD

**Issue by zhaoxiangyan** [wangeditor-team/wangEditor#2307]
## 功能描述

*v3版本多语言i18next不是必须的，希望能够兼容，省略不必要的i18next安装*

## 提炼几个功能点

- 处理自定义config.lang、config.languages实现定制修改本地多语言

## wangEditor/src/editor/init-fns/i18next-init.ts源码修改(可参考)

![1602751335(1)](https://user-images.githubusercontent.com/26407895/96100252-c25c9580-0f06-11eb-83b3-64111e1320ff.jpg)

## 修改兼容之后代码实现
![1602751801(1)](https://user-images.githubusercontent.com/26407895/96104027-ec17bb80-0f0a-11eb-82ca-ac095b0428fd.jpg)

**Comment by UltramanWeiLai** [comment]
怎么说，就简单的文字替换来说的话，这种行为是可用行的，但是 i18next 不仅仅只有这个功能。
这里我话你不想安装 i18next 和 去修改源码的话 你可以自己实现一个 { t: function } 来做挂载就可以了 
const i18next = { t: () => { xxxx } }
editor.config.i18next = i18next 即可
