### ISSUE TITLE
使用 TypeScript 扩展自定义菜单，引入基类时报错

### ISSUE THREAD

**Issue by clinfc** [wangeditor-team/wangEditor#2310]
## bug 描述

使用 TypeScript 环境，按照官方的文档进行自定义菜单扩展，引入时报错
![image](https://user-images.githubusercontent.com/39868400/96151293-d7085000-0f3d-11eb-86e8-99a755484f27.png)
并且一些数据结构并未对外进行暴露
![image](https://user-images.githubusercontent.com/39868400/96154565-898de200-0f41-11eb-8e19-875acf2d096e.png)
![image](https://user-images.githubusercontent.com/39868400/96154829-d07bd780-0f41-11eb-82c1-f57e025251be.png)

## 你预期的样子是？

能正常引入并扩展目录

## wangEditor 版本

v4.0.3

## 官网能否复现该 bug ？

能

**Comment by UltramanWeiLai** [comment]
#2310 PanelConf, PanelTabConf 的数据结构也没有暴露出来

**Comment by wangfupeng1988** [comment]
已修复。
升级 v4.0.6 版本，然后重新参照文档 http://www.wangeditor.com/doc/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html
