### ISSUE TITLE
Edor.config.pasteFilterStyle，Udor.config.pasteIgnoreImg配置无效

### ISSUE THREAD

**Issue by ffffffbbbb** [wangeditor-team/wangEditor#2311]
## bug 描述

editor.config.pasteFilterStyle = false;配置无效
editor.config.pasteIgnoreImg = false;配置无效

## 你预期的样子是？

正常配置的话，粘贴图文信息，图片应该自动转base64编码，文字添加行内样式；
实际上使用，全部清除了行内样式，图片也无法显示了。

## 浏览器及版本号

QQ浏览器 10.5.2；
chrome  86.0.4240.75；

## wangEditor 版本

wangeditor 4.0.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接使用官网dome配置editor.config.pasteFilterStyle = false; 可以复现

**Comment by wangfupeng1988** [comment]
图片应该自动转base64编码 —— 这个预期实现不了。
如果能粘贴图片，也是粘贴网络图片，不会是 base64 格式的。

**Comment by wangfupeng1988** [comment]
我测试了一遍，这俩配置是有效的。测试代码如下

```js
        const E = window.wangEditor
        const editor = new E('#div1')
        editor.config.height = 800

        // 过滤样式，默认 true
        editor.config.pasteFilterStyle = false

        // 忽略图片，默认 false
        editor.config.pasteIgnoreImg = true

        editor.config.pasteTextHandle = function (content) {
            return content
        }

        editor.create()
```

**Comment by wangfupeng1988** [comment]
如果你那边确实有问题，你可以继续补充，再详细一点。
如：详细的代码？复制的具体是什么内容？

回复之后，reopen 即可。

**Comment by 1529084525** [comment]
![image](https://user-images.githubusercontent.com/49889130/101436015-56b40900-3948-11eb-8e41-a8a308bd3337.png)
![image](https://user-images.githubusercontent.com/49889130/101436035-603d7100-3948-11eb-870a-64794d998291.png)
![image](https://user-images.githubusercontent.com/49889130/101436054-64698e80-3948-11eb-8f9f-bf922408cda6.png)
没有效果！！
