### ISSUE TITLE
从word复制单张图片可以粘贴，文字和图片一起复制时图片粘贴失败，设置上传图片方式是base64格式

### ISSUE THREAD

**Issue by guoyf** [wangeditor-team/wangEditor#2313]
## bug 描述

*从word复制单张图片可以粘贴显示成功，文字和图片一起 或者多张图片时图片粘贴失败，设置上传图片方式是base64格式。用开发者工具可以看到显示成功的图片地址是base64格式的，而显示失败的是本地文件地址*

## 你预期的样子是？

*word文字和图片复制粘贴时图片正常显示。*

## 浏览器及版本号

*Chrome 80.0.3987.132*

## wangEditor 版本

*4.0.3*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一： 从word复制带有文字和图片的内容；
- 步骤二：粘贴到编辑器；
- 步骤三：发现图片显示错误。

**Comment by achunCoding** [comment]
@guoyf 请问解决了吗，目前我也遇到这个问题了

**Comment by wangfupeng1988** [comment]
暂不支持 word 的图片粘贴。目前没有找到合适的技术方案来解决这个问题。

如果你们有好的技术方案，欢迎推荐给我们。

**Comment by shenanheng** [comment]
我也遇到了,哎 @achunCoding 你找到好的富文本没有插件

**Comment by ihwf** [comment]
> 暂不支持 word 的图片粘贴。目前没有找到合适的技术方案来解决这个问题。
> 
> 如果你们有好的技术方案，欢迎推荐给我们。

可以参考CKeditor, 可以完美从word文档复制粘贴任何内容, 而且还能保留word文档的格式
