### ISSUE TITLE
在批量上传文件的时候，文件名是否有设置不自动添加number数字？

### ISSUE THREAD

**Issue by aveyuan** [wangeditor-team/wangEditor#2314]
## 功能描述

![image](https://user-images.githubusercontent.com/10907648/96266938-d6cd8a80-0ff9-11eb-82ce-57427f6ca877.png)
在批量上传文件的时候，文件名是否有设置不自动添加number数字？我设置的file,批量上传的时候会出现file1,file2

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by UltramanWeiLai** [comment]
这个应该是常规的。
这也不是 编辑器相关的 你可以查询 文件上传 或者和后端交流一下
如果你不想处理不确定的文件序号的话，你也可以一个接口只上传一张图片
