### ISSUE TITLE
编辑器设置内容，使用html初始化纯文本内容，则会渲染失败

### ISSUE THREAD

**Issue by mtfCloud** [wangeditor-team/wangEditor#2315]
比如想要设置的内容为：abc
有两种方法，一种是html初始化，一种是js设置，其中js设置没问题，但是若是用初始化：
`<div id="demo">abc</div>`
则abc渲染不到编辑器中，而是显示在外部

**Comment by UltramanWeiLai** [comment]
html 初始化内容必须要用 标签包裹，无法直接对纯文本进行渲染
