### ISSUE TITLE
复制粘贴表格时，表格背景无效，

### ISSUE THREAD

**Issue by Allie1995** [wangeditor-team/wangEditor#2316]
## bug 描述

复制表格时，使用V3版本， editor.customConfig.pasteFilterStyle = false;关闭过滤后，IE是有背景色的，其他浏览器有的有，有的没有；当我使用v4版本时editor.config.pasteFilterStyle = false完全无效，表格背景颜色没了

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

3.1.1

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

    <script type="text/javascript">
        var E = window.wangEditor;
        var editor = new E('#editor');
        editor.customConfig.pasteFilterStyle = false;
        editor.create();
    </script>

**Comment by UltramanWeiLai** [comment]
所以，你想表达什么？？？

**Comment by wangfupeng1988** [comment]
提问者长时间未回复，暂时关闭。
