### ISSUE TITLE
开始使用的文档里希望补充一个在线web页面的使用方式

### ISSUE THREAD

**Issue by fengssy** [wangeditor-team/wangEditor#2319]
## 功能描述

http://www.wangeditor.com/doc/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/01-%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8.html
如果我的项目里,没有走npm,并且不想用官方cdn的js引用,那么我就要自己去找min文件,以及去尝试是否还有其他依赖,并一一下载,放到自己的项目中才可以

另外提个bug: github下载的v4.0.4版本
里面的例子,引用的路径是"../dist/wangEditor.js",然而并不存在这个文件

## 提炼几个功能点
建议:
要么下载的多打包一个release版本
要么之前的包里放一个最终直接可以使用的目录

**Comment by UltramanWeiLai** [comment]
你下载了源码得编译才能有文件呀！
你想自己找min文件，直接把cdn地址在网页打开，复制一下然后新建一个js文件不就可以了？npm的软件包内也可以找到
