### ISSUE TITLE
粘贴的段落文本变成一行了

### ISSUE THREAD

**Issue by zhangzygit** [wangeditor-team/wangEditor#2321]
## bug 描述
在记事本中复制一段对话，然后在编辑器中粘贴，变成了一行内容了
显示的内容是：W: Hello. Sunnyside Inn. May I help you?M: Yes, I'd like to reserve a room for two on the 21st of March.W: OK. Let me check our books for a moment. The 21st of May, right?M: No. March, not May.

## 你预期的样子是？

W: Hello. Sunnyside Inn. May I help you?
M: Yes, I'd like to reserve a room for two on the 21st of March.
W: OK. Let me check our books for a moment. The 21st of May, right?
M: No. March, not May.

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一：
复制以下内容：
W: Hello. Sunnyside Inn. May I help you?
M: Yes, I'd like to reserve a room for two on the 21st of March.
W: OK. Let me check our books for a moment. The 21st of May, right?
M: No. March, not May.
- 步骤二
http://www.wangeditor.com/index.html
在编辑框中粘贴
- 步骤三
显示结果为：
W: Hello. Sunnyside Inn. May I help you?M: Yes, I'd like to reserve a room for two on the 21st of March.W: OK. Let me check our books for a moment. The 21st of May, right?M: No. March, not May.

**Comment by zhangzygit** [comment]
![Snipaste_2020-10-21_12-11-52](https://user-images.githubusercontent.com/32352808/96672364-adfd1a80-1396-11eb-942d-9e8b4908cc32.png)

**Comment by UltramanWeiLai** [comment]
该问题再 #2330 中受理，处理进程可以移步到 #2330  中查看
