### ISSUE TITLE
字体颜色和背景颜色区分配置项

### ISSUE THREAD

**Issue by wenfawang** [wangeditor-team/wangEditor#2322]
## bug 描述
字体颜色和背景颜色没有区分配置项，现在是统一通过colors设置的，期望添加不同的配置 项

## 你预期的样子是？
editor.config.colors 为字体颜色配置项
editor.config.backColors 为背景颜色配置项

## 浏览器及版本号
All

## wangEditor 版本
3 or 4版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

可以在/menus/back-color/index.ts 文件里面兼容一下背景色配置，如果配置了背景色选项则取自定义配置项 否则取colors配置项

**Comment by UltramanWeiLai** [comment]
你这个属于 建议新功能。
目前的话，我们可能会考虑优化出 取色器和色板 功能。
如果你坚持这个意见的话，可以重新 按照功能模板重新提交一下。
