### ISSUE TITLE
缩进功能支持其他元素

### ISSUE THREAD

**Issue by awamwang** [wangeditor-team/wangEditor#2323]
## 功能描述

v4新的缩进功能支持其他元素

## 提炼几个功能点

- 支持table
- 支持H1~H6
- 支持blockquote
- 支持pre

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

[tinyMCE](https://www.tiny.cloud/docs/demo/full-featured/)

**Comment by awamwang** [comment]
去调试了一下：
1. 非table的选区，感觉并不会出现$selectionElem是个list的情况，是否应该跟上面的走相同逻辑即可
```ts
            if ($selectionElem && $selectionElem.length > 0) {
                $selectionElem.forEach((item: any) => {
                    operateElement($(item), value, editor)
                })
            }
```
2. table选区，可能由于table的实现，导致单独选中table时，选区$selectionElem始终等于$textElem，无法准确找到施加缩进的元素

对选区这里并不是很了解，提供观察结果供参考

**Comment by UltramanWeiLai** [comment]
表格和标题之类的话我们可能暂时不会去优先考虑这个问题
插入代码的话，可能会进行优化

**Comment by wangfupeng1988** [comment]
暂时先关闭。
