### ISSUE TITLE
设置内容

### ISSUE THREAD

**Issue by Xiaobaiaixiaobai** [wangeditor-team/wangEditor#2326]
## bug 描述
![捕获](https://user-images.githubusercontent.com/35687605/96596088-ecef8980-131e-11eb-94fb-9d22a3353fea.PNG)
![捕获1](https://user-images.githubusercontent.com/35687605/96596104-f37e0100-131e-11eb-8dba-7d784a89fb09.PNG)
我用asp.net  后台获取内容后通过model 在div中显示。  然后内容进入不了编辑器。在外边。

## 你预期的样子是？
想让内容正常的显示到编辑器中

## 浏览器及版本号
谷歌浏览器版本 86.0.4240.75（正式版本） （64 位）

## wangEditor 版本
最新版 
通过 https://unpkg.com/wangeditor/dist/wangEditor.min.js  引用的

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 步骤一 用asp.net 后台程序将数据绑定到model中。
- 步骤二 然后在前台将model放置到div中。

麻烦看到回复下，感谢

**Comment by Xiaobaiaixiaobai** [comment]
问下，我这个问题不是问题吗？

**Comment by wangfupeng1988** [comment]
依赖于 asp.net 环境，我们不知道怎么去使用。

能否用纯 js 或者 nodejs 来复现这个问题？

**Comment by Xiaobaiaixiaobai** [comment]
你好    我先把内容绑定到TextArea中，然后将TextArea的值再复制给wangEditor。然后实现了。 （暂时解决了）      
还有， 如果方便的话，我可以部署一个简单的asp.net页面，然后提供下页面的地址，复现下我的问题。你看这个方面你排查不？
![image](https://user-images.githubusercontent.com/35687605/97111906-5fe07200-171c-11eb-8b79-a1cc4b500dc5.png)
![image](https://user-images.githubusercontent.com/35687605/97111916-6e2e8e00-171c-11eb-9fda-2c9be24938f0.png)

**Comment by wangfupeng1988** [comment]
@Xiaobaiaixiaobai 你可以提供一个页面出来，但要我们排查，页面的 js 源码得清晰可读，否则也看不懂。

**Comment by UltramanWeiLai** [comment]
这个问题我大概知道是为什么，应该是你的模板 
![image](https://user-images.githubusercontent.com/23336585/97768954-dab4ed00-1b61-11eb-969b-e542023c3ef1.png) 拿到的字符串的标签是进行过转移的，< > 尖括号被转移成了 &qt; 之类的东西。
由于你长时间没有回复，该问题暂且关闭。
