### ISSUE TITLE
自定义菜单 exclude，可以选择不需要的菜单

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2327]
## 功能描述

当只是不需要少数菜单的时候，希望可以直接设置不需要的菜单
而不是非得找出所有需要的菜单

## 提炼几个功能点

- exclude 设置不需要的菜单

## 原型图

无

## 可参考的案例

例如：我目前需求不需要用的插入代码可以通过 editor.config.exclude = ['code'] 来剔除 code 菜单

**Comment by clinfc** [comment]
建议将包含和排除进行统一对应，我们可以将这两个方法挂在 editor.menu 上，例如：
```js
const menus = ['head',  'bold',  'fontSize',  'fontName']

// 包含（需要显示的菜单）
editor.menu.include(menus)

// 排除（不需要的菜单）
editor.menu.exclude(menus)
```

**Comment by lnimpossible** [comment]
已提交pr https://github.com/wangeditor-team/wangEditor/pull/2593。 @echoLC @xiaokyo
