### ISSUE TITLE
序列

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2329]
## bug 描述

谷歌浏览器 多选行 设置 序列 的话 ul 标签被包裹在 p 标签中
序列无法进行取消

## 你预期的样子是？

ul 标签属于顶级段落，不能被包含在任何标签中
序列可以取消

## 浏览器及版本号

谷歌浏览器

## wangEditor 版本

wangEditor v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 用谷歌浏览器打开官网demo
- 输入三行文字并且选中
- 设置无序或者有序列表
- 打开控制台查看 dom 节点

**Comment by wangfupeng1988** [comment]
再补充一点：

在最后一个 item 回车，再回车，后面的行会被 `<div>` 包裹，这个问题很严重。
