### ISSUE TITLE
粘贴 txt 文件的内容没有换行

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2330]
## bug 描述

粘贴 txt 文件的内容没有换行

## 你预期的样子是？

内容正常换行

## 浏览器及版本号

所有浏览器

## wangEditor 版本

wangEditor v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 用浏览器打开官网demo
- 打开一个txt文件并且复制内容
- 在编辑器中粘贴

**Comment by hahaaha** [comment]
这个issue（https://github.com/wangeditor-team/wangEditor/issues/2297）解决后，本issue也能解决
