### ISSUE TITLE
edge浏览器 使用引用 quote 按钮不起作用

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2332]
## bug 描述

edge浏览器 使用引用 quote 按钮不起作用

## 你预期的样子是？

正常显示引用效果

## 浏览器及版本号

Edge浏览器

## wangEditor 版本

wangEditor v4

## 官网能否复现该 bug ？

能
## 最小成本的复现步骤

- 用 edge 浏览器打开官网 demo
- 输入一行文字，并选中
- 点击 引用 按钮

**Comment by hahaaha** [comment]
这个问题在新版本下已修复
https://github.com/wangeditor-team/wangEditor/issues/2333
具体参考这个issue

**Comment by UltramanWeiLai** [comment]
该问题已在 v4.2.2 中解决，请更新版本。
如有问题可以重新提交 issuse
