### ISSUE TITLE
一个页面使用多个编辑器，拖拽图片至第一个编辑器，但是图片都会出现在最后一个编辑器

### ISSUE THREAD

**Issue by gaoshanliushui1** [wangeditor-team/wangEditor#2341]
## bug 描述

*一个页面使用多个编辑器，拖拽图片至第一个编辑器，但是图片都会出现在最后一个编辑器*

## 你预期的样子是？

*拖拽图片至哪个编辑器，则图片就会显示在哪个编辑器里*

## 浏览器及版本号

*IE11，safari，chrom*

## wangEditor 版本

*4.0.4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一代码中写出两个编辑器
- 步骤二在页面上脱宅图片至第一个编辑器
- 步骤三在最后一个编辑器里边会出现这个图片

**Comment by q378532364** [comment]
此问题已在解决中，会在后期版本更新后修复

**Comment by UltramanWeiLai** [comment]
已发布 v4.2.0 修复
如有问题，可继续提交新 issue 。
