### ISSUE TITLE
上传base64图片，回显卡顿

### ISSUE THREAD

**Issue by goldprog** [wangeditor-team/wangEditor#2342]
## bug 描述

*上传base64图片，回显卡顿，设置editor.config.uploadImgShowBase64 = true，好半天才能回显出来*

## 你预期的样子是？

*像官网一样立马回显出来*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
烦请描述的清楚一点，不然我们很难理解你遇到的问题。
根据你现有的描述，我理解到的是，你使用 base64 做显示，但是显示很慢。
回显速度和图片大小挂钩把，如果有上传逻辑，还和你服务接口速度挂钩，编辑器只是一个工具而已。

**Comment by wangfupeng1988** [comment]
提交问题，请按照模板详细写明，否则不予受理。

这个先关闭了，再重新按模板提交一个新问题吧。
