### ISSUE TITLE
段落中的文本内容可否增加<span>子标签

### ISSUE THREAD

**Issue by zhangzygit** [wangeditor-team/wangEditor#2343]
## bug 描述
![Snipaste_2020-10-22_11-10-11](https://user-images.githubusercontent.com/32352808/96819840-304d1380-1457-11eb-95ce-1f1f1a047fd3.png)

段落中的文本没有用标签修饰，在通过`getSelectionContainerElem`选取时，判断了 `return $(elem.nodeType === 1 ? elem : elem.parentNode)` ，所以每次获得到的是其父节点，而得不到选择的文本节点。

## 你预期的样子是？

通过`getSelectionContainerElem`可以获得到选择的文本节点，比如获取到的是： `<span>happy</span>`

## 浏览器及版本号

chrome 86.0.4240.80

## wangEditor 版本

4.0.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 输入一段文本
- 浏览器检查Elements

**Comment by UltramanWeiLai** [comment]
通过父元素，获取文本节点不也很轻松吗？
JS 是提供了相关的 API 的
如果要添加 span 标签，你有没有考虑过，你的 happy 后面要添加新的内容怎么处理？
是新加一个 span 标签还是 在原有 span 标签里面添加？
如果在原有 span 标签里面添加的话，如何去做判断和操作？
这么做代价太大，而且也不符合逻辑。
