### ISSUE TITLE
placeholder不能正确隐藏

### ISSUE THREAD

**Issue by zunlongzhou** [wangeditor-team/wangEditor#2345]
## bug 描述

当在editor中输入文字后placeholder不会消失而是和文字一起重叠显示，只有当backspace删除一个字符时placeholder才会隐藏
![image](https://user-images.githubusercontent.com/42513377/96950640-54732800-151d-11eb-98b5-667f3799ad43.png)

## 你预期的样子是？

当用户往editor中输入文字，placeholder立即隐藏

## 浏览器及版本号

Google Chrome 85.0.4183.102

## wangEditor 版本

4.0.5 ，2020.10.21更新版

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/42513377/96950655-5dfc9000-151d-11eb-848f-6484da2e96b9.png)

- 步骤一 ctrl a全选文字，然后将文字全部删除
- 步骤二    editor从空开始输入字符，期间不要删除
- 步骤三     此时可以发现，placeholder的文字会一直存在，和正文重叠显示

**Comment by UltramanWeiLai** [comment]
我这边没有复现，选择了文字后 placeholder 还在的情况
中文输入法，只要说选中了文字 placeholder 也会消失 至于输入期间为什么没有消失，因为输入期间是不计入内容的

**Comment by zunlongzhou** [comment]
> 我这边没有复现，选择了文字后 placeholder 还在的情况
> 中文输入法，只要说选中了文字 placeholder 也会消失 至于输入期间为什么没有消失，因为输入期间是不计入内容的
> ![image](https://user-images.githubusercontent.com/23336585/96952473-8090a800-1521-11eb-953c-251cce3b6489.png)

1. 您仔细看我的截图，是在输入完毕后placeholder依旧继续存在

2. 我多次测试发现当我从空开始输入字符时，如果我一直只输入中文字符placeholder会一直存在，只有当我输入其他字符、英文字母，回退等操作时placeholder才会消失；这显然不是我们想要的效果；

3. 这是我一分钟前【2020.10.23 11:21】在官网尝试的，文字已经输入完毕没有输入法的文字选择框
![image](https://user-images.githubusercontent.com/42513377/96952670-057bc180-1522-11eb-9ded-c9eacd9c8df9.png)

**Comment by TheSixer** [comment]
> 我这边没有复现，选择了文字后 placeholder 还在的情况
> 中文输入法，只要说选中了文字 placeholder 也会消失 至于输入期间为什么没有消失，因为输入期间是不计入内容的
> ![image](https://user-images.githubusercontent.com/23336585/96952473-8090a800-1521-11eb-953c-251cce3b6489.png)

是windows自带的输入法会出现这种情况，我提了一个新的bug

**Comment by lei3536** [comment]
我也有这个问题，版本4.0.5

输入的文体只是简单盖上去了而已

![image](https://user-images.githubusercontent.com/29876945/97132873-23942c80-1783-11eb-81a8-305b500569fd.png)

**Comment by yedonensis** [comment]
![图片](https://user-images.githubusercontent.com/38917059/97410623-46b50c80-193a-11eb-9be0-94a4b467e9d7.png)
我的也出现了这种情况， 搜狗输入法的时候，placeholder 不能正常隐藏

**Comment by UltramanWeiLai** [comment]
这个问题已经修改完毕了，新版本发布应该就可以解决了详情可以去看 #2353

**Comment by 18508409531** [comment]
![image](https://user-images.githubusercontent.com/35060559/192525658-9469b116-7452-489d-b86a-5192d4fa2f2d.png)
我也遇见了，我发现搜狗输入法下输入中文存在这个问题。而且不会触发onChange事件。win10自带输入法输入中文可以，
我是用的是v5 谷歌64版本
