### ISSUE TITLE
placeholder可以支持自定义

### ISSUE THREAD

**Issue by yedonensis** [wangeditor-team/wangEditor#2346]
## 功能描述

*希望placeholder 能支持自定义（自己赋值）， 而不是只能默认*

## 原型图
![图片](https://user-images.githubusercontent.com/38917059/96953634-20e7cc00-1524-11eb-8b77-bdc4f112f61b.png)

**Comment by yedonensis** [comment]
![Uploading 图片.png…]()

**Comment by UltramanWeiLai** [comment]
老哥，你肯定是没看文档，该功能是已经有的。
http://www.wangeditor.com/doc/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/07-placeholder.html
