### ISSUE TITLE
火狐复制不了单行纯文本

### ISSUE THREAD

**Issue by gittlyt** [wangeditor-team/wangEditor#2347]
## bug 描述
复制不了单行纯文本
![图片](https://user-images.githubusercontent.com/49850288/96953555-ee3dd380-1523-11eb-9f83-aa964a1d19af.png)
单行只能复制带样式的内容，无样式的文字掉了
![图片](https://user-images.githubusercontent.com/49850288/96953678-4bd22000-1524-11eb-9a69-c98e0e5a7bd5.png)
## 你预期的样子是？
在火狐中可以复制粘贴任何内容

## 浏览器及版本号

火狐浏览器

## wangEditor 版本

wangEditor v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
用火狐浏览器打开官网 demo
- 步骤二
ctrl + c 复制任意demo中无样式的单行纯文本，在demo编辑器中 ctrl + v

**Comment by wangfupeng1988** [comment]
我这里用 mac os 火狐没有复现。

追问一下，你说的“任意demo中无样式的单行纯文本”是什么意思？就是编辑区域内，随便一个无样式的文字吗？

**Comment by gittlyt** [comment]
是的，选择普通文本后复制，编辑器里粘贴不了（多行可以粘贴，单行粘贴不了）
用的火狐是在windows环境下的
![图片](https://user-images.githubusercontent.com/49850288/97248276-6239ed80-183c-11eb-8fa1-e4da30a8d35e.png)

**Comment by UltramanWeiLai** [comment]
@gittlyt 这边的话移步到 #2399 中合并处理
