### ISSUE TITLE
黏体图片403错误

### ISSUE THREAD

**Issue by liaoyanhui** [wangeditor-team/wangEditor#2348]
## 复制网络图片黏贴403

*我在使用编辑器的时候黏贴图片*

## 你预期的样子是？

*预期编辑器内显示图片*

## 浏览器及版本号

*chrome*

## wangEditor 版本

*3.1.1*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 复制网络图片黏贴进入浏览器

**Comment by UltramanWeiLai** [comment]
老哥，你可以先去了解一下服务端 403 状态码是什么意思吧！
你的图片资源使用请求被拒绝了。
