### ISSUE TITLE
点击插入图片和视频的弹出框显示错位

### ISSUE THREAD

**Issue by guanguanguo** [wangeditor-team/wangEditor#2351]
## bug 描述

![GIF](https://user-images.githubusercontent.com/48321465/96974288-987d2180-154b-11eb-944c-2e00248465c9.gif)
点击插入图片和视频的弹出框显示有问题，插入链接的菜单也有这个问题存在

## 你预期的样子是？

![QQ截图20201023162110](https://user-images.githubusercontent.com/48321465/96974431-ce220a80-154b-11eb-9420-0ba4d35ae667.jpg)

## 浏览器及版本号

Chrome 版本 86.0.4240.75

## wangEditor 版本

4.0.5

**Comment by UltramanWeiLai** [comment]
弹框我们都居中做显示的。
至于为什么居中显示，也是考虑到编辑器的宽度和按钮的位置一些因素，才这样设计的。

**Comment by guanguanguo** [comment]
我是说弹出框的tab标签，当我点击”网络图片“时，tab标签就不见了
![QQ截图20201027114823](https://user-images.githubusercontent.com/48321465/97254964-83a1d600-184a-11eb-99ff-de597411ee8c.jpg)
**

> 正常情况应该是这样的

**
![image](https://user-images.githubusercontent.com/48321465/97255012-9e744a80-184a-11eb-80f5-df2ea18a969a.png)
