### ISSUE TITLE
上传本地图片覆盖问题

### ISSUE THREAD

**Issue by DelMemory** [wangeditor-team/wangEditor#2352]
## bug 描述

添加图片后，使用浮窗改变图片大小，点击图片右侧，再次上传会导致图片被替换

## 你预期的样子是？

正常新增图片

## 浏览器及版本号

Google Chrome 版本 86.0.4240.111（正式版本） (x86_64)

## wangEditor 版本

4.0.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
     上传图片
- 步骤二
     光标移入图片上，点击30%
- 步骤三
     点击图片右侧空白处（需无其他内容），上传图片，原图被新增图片替换

**Comment by UltramanWeiLai** [comment]
不是很明白，为什么点击图片右侧空白处会重新上传图片？
原图如果只是修改 src 属性应该不会有这个问题，如果你是把 img 标签给更新，那么图片肯定是会还原的，因为属性都没了
官网我也试过了，并没有说上传图片后设置百分比点击空白处会重置图片或者重新上传。

**Comment by wangfupeng1988** [comment]
按照你的步骤，我没有复现这个问题。

**Comment by DelMemory** [comment]
复现视频已经发到qq群 聊天记录搜索 改变大小导致图片替换问题 #2352 可以找到

**Comment by DelMemory** [comment]
@UltramanWeiLai

**Comment by UltramanWeiLai** [comment]
已经复现了
1、上传本地图片
2、双击右侧空白后，单击空白
3、再次上传本地图片
4、之前上传的图片被覆盖掉了
初步断定是 range 的问题

**Comment by wangfupeng1988** [comment]
已发布 `v4.2.0` 修复
如有问题，可继续提交新 issue 。
