### ISSUE TITLE
windows下使用系统自带的输入法不触发onchange事件，且placeholder不消失

### ISSUE THREAD

**Issue by TheSixer** [wangeditor-team/wangEditor#2353]
## bug 描述

windows下使用系统自带的输入法输入**中文**文本不触发onchange事件，且placeholder不消失

## 你预期的样子是？

输入内容正常触发onchange，且placeholder消失

## 浏览器及版本号

win10 Chrome版本 86.0.4240.75（正式版本）

## wangEditor 版本

4.0.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 切换至windows系统自带输入法
- 输入任意内容
- 控制台输出onchange回调内容

**Comment by LoveChenJinwen** [comment]
我也出现这个问题，望尽快解决，或者其他方法处理双向绑定；

**Comment by LoveChenJinwen** [comment]
`   this.editor.$textElem.on("compositionend", () => {
      // 输入法结束输入
      this.editor.config.onchange(this.editor.txt.html());
      this.editor.compositionend = true;
    });`
输入法结束调用onchange，我暂时是这样解决的

**Comment by wangfupeng1988** [comment]
请升级 v4.0.8 再试试。
如有问题，可再重新提交 issue 。
