### ISSUE TITLE
缩进功能和行高功能失效

### ISSUE THREAD

**Issue by w840980261** [wangeditor-team/wangEditor#2355]
## bug 描述

在官网demo和自己的项目中选中几行带非纯文本的数据，进行缩进和行高操作，均无变化

## 你预期的样子是？

选中序列会根据进行缩进和行高操作进行改变

## 浏览器及版本号

chrome 86.0.4240.75

## wangEditor 版本

4.0.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

在官网demo中选中几行带非纯文本的数据，进行缩进和行高操作，均无变化

**Comment by UltramanWeiLai** [comment]
非纯文本的数据是什么？

**Comment by wangfupeng1988** [comment]
一周未回复，暂时关闭。

**Comment by GZ-ted** [comment]
我也遇到这个问题，看源码只针对P标签，能开放不限制吗？

**Comment by juwin49** [comment]
为什么关了这个问题，我也遇到，缩进和行高直接不显示了
![image](https://user-images.githubusercontent.com/17706385/105458758-1cb68080-5cc4-11eb-890b-db3bdd08a441.png)
![image](https://user-images.githubusercontent.com/17706385/105458821-31931400-5cc4-11eb-862b-f43843b49555.png)
