### ISSUE TITLE
追加内容添加图片无法实现修改宽高

### ISSUE THREAD

**Issue by wineforyou** [wangeditor-team/wangEditor#2359]
## bug 描述
当配置了自定义菜单（按钮类型的：const { BtnMenu }=wangEditor.menuConstructors;），并且在menu菜单（editor.config.menus ）中取消配置了图片的按钮后
通过：editor.txt.append('<img  src="xxx" />') 追加的内容无法使用编辑器自带的图片修改宽高功能。

## 你预期的样子是？
通过：editor.txt.append('<img  src="xxx" />') 追加的内容无法使用编辑器自带的图片修改宽高功能。
 

## 浏览器及版本号
chrome 75 ,框架：VUE 

## wangEditor 版本

  "wangeditor": "^4.0.5"

## 官网能否复现该 bug ？

 不能

## 最小成本的复现步骤

 

- 步骤一
自定义menu，继承基础的BtnMenu
- 步骤二
editor.config.menus 中取消   'image',
- 步骤三
步骤1的自定义菜单点击后使用editor.txt.append('<img  src="xxx" />') 追加图片标签。

**Comment by wineforyou** [comment]
editor.txt.append('这里是一个图片标签') 
图片被github当成标签展示了。。。

**Comment by wineforyou** [comment]
官方请忽略 = =  原来应该用：PanelMenu 而不是BtnMenu

**Comment by wineforyou** [comment]
错了。还是不行。之前行是应为我把第二步取消了。现在自定义后还是不行。

**Comment by UltramanWeiLai** [comment]
图片修改宽高功能是再 img 菜单上进行挂载的，你可以参考源码里面 src/menus/img/bind-event/*.js 里面的代码去自定义实现 tooltip 功能

**Comment by jsysonG** [comment]
wangEditor.js   4718行 

新增  

editor.UploadImg = this;


//引用
editor.UploadImg.insertImg('IMG_URL');
