### ISSUE TITLE
邮件展示的时候，部分标签样式不生效

### ISSUE THREAD

**Issue by fujiabin00** [wangeditor-team/wangEditor#2361]
## 功能描述

用富文本编辑邮件内容时候，在邮件中table等部分标签样式不生效！！！

## 提炼几个功能点

- 点击邮件模式编辑，让内容在邮件中展示样式不丢失。

**Comment by UltramanWeiLai** [comment]
这个是你业务相关的内容，关于表格样式问题，你可以写一些 table 相关的 css 样式表

**Comment by andyhuai** [comment]
通过DOM获取的innerHtml也是不带样式的，默认样式是外联的，没法获取到
