### ISSUE TITLE
上传图片增加更新自定义 header机制

### ISSUE THREAD

**Issue by ChartWay** [wangeditor-team/wangEditor#2363]
## 功能描述

通常会把token放再自定义 header中，但是自定义 header是在编辑器实例化就生成了，如果页面停留太久，这个时候token可能过期，此时点击上传图片就需要刷新token。

## 提炼几个功能点

- 点击上传图片，加入更新自定义 header，这个时候可以根据需要来重新设置token

**Comment by UltramanWeiLai** [comment]
上传图片是可以自定义 header 的，具体查看文档 07 上传图片 里面的 自定义 header

**Comment by ChartWay** [comment]
> 上传图片是可以自定义 header 的，具体查看文档 07 上传图片 里面的 自定义 header

@UltramanWeiLai  我的意思是页面停留太久，这个header里面的token已经过期了，需要线刷新token后再上传图片，要不然就会上传失败。问题是如何在上传图片前刷新token。。

**Comment by ly023** [comment]
遇到了同样的问题，请问最后如何解决的？
