### ISSUE TITLE
插入标签

### ISSUE THREAD

**Issue by cn-zx** [wangeditor-team/wangEditor#2366]
## 我想在内容里面写入 html标签 能让前端正确解析这个标签， 我该如何做？或者说这个功能现在还不支持？

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
没看懂你啥意思。
请按照模板规则，详细描述功能和预期。
