### ISSUE TITLE
addRange(): The given range isn't in document.

### ISSUE THREAD

**Issue by zdd5176312** [wangeditor-team/wangEditor#2369]
根据左侧树显示对应的内容，当选择第一级的时候清空内容，选中第二级的时候显示对应的信息
直接点击切换二级，内容显示正确；
先点击第一级，再点击第二级创建的div内内容为空
`
if (obj.date_level === '5') {
                            this.queryFormData();
                            this.editor.$textElem.attr('contenteditable', true);
                            this.setState({
                                disabled: false,
                                mode: 'update'
                            })
                        } else {
                            this.formRef.current.resetFields();
                            this.editor.txt.clear();
                            this.editor.$textElem.attr('contenteditable', false);
                            this.setState({
                                disabled: true
                            })
                        }
`

**Comment by wangfupeng1988** [comment]
请按照 issue 模板，重新提交问题。
不符合模板规则的 issue ，不予受理，请理解。
