### ISSUE TITLE
新增自定义Panel wangEditor.min.js:报错 Uncaught TypeError: n.setPanel is not a function     at t.create (wangEditor.min.js:1)  

### ISSUE THREAD

**Issue by WAWZ** [wangeditor-team/wangEditor#2373]
## bug 描述
按照官网教程，直接参考视频菜单的源码，将ts改为js代码，createPanel方法报错，并且点击空白处或者其他menu不会关闭此panel,报错如下：
Uncaught TypeError: n.setPanel is not a function
    at t.create (wangEditor.min.js:1)
    at AlertMenu.createPanel (editor.js:64)
    at AlertMenu.clickHandler (editor.js:57)
    at HTMLDivElement.eval (wangEditor.min.js:1)

## 你预期的样子是？
修改bug，createPanel方法解决报错，并且点击空白处或者其他menu可以关闭此panel

## 浏览器及版本号
86.0.4240.111（正式版本） (x86_64)

## wangEditor 版本
4.0.6

## 官网能否复现该 bug ？
能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一: 参考视频菜单的源码，将ts转为js
- 步骤二: 按照官网教程，配置菜单
- 步骤三

**Comment by wangfupeng1988** [comment]
把你的核心代码贴这里吧。
只要能复现问题，代码越简单越好，让我们以最小成本复现问题。

**Comment by WAWZ** [comment]
两个js
editor.js

import React, { Component } from 'react';
// import { getRandom } from './utils/util';

import E from 'wangeditor';
const { $, BtnMenu, DropListMenu, PanelMenu, DropList, Panel, Tooltip } = E;
import { Editor, DropListConf, DropListItem, PanelTabConf, TooltipConfItemType } from 'wangeditor';
import createPanelConf from './create-panel-conf';


// 第一，菜单 class ，Button 菜单继承 BtnMenu class
class AlertMenu extends BtnMenu {
    constructor(editor = Editor) {
        const $elem = E.$(
            `<div class="w-e-menu" id="video-add"><i class="w-e-icon-play"></i></div>`
        );
        super($elem, editor);
    }

    // 菜单点击事件
    clickHandler(e) {
        this.createPanel(' ');
    }

    createPanel(iframe) {
        const conf = createPanelConf(this.editor, iframe);
        const panel = new Panel(this, conf);
        panel.create();
    }

    tryChangeActive() {}

    command(value) {
        // 设置标题
        this.editor.cmd.do('formatBlock12', value)
    }
    // 菜单是否被激活（如果不需要，这个函数可以空着）
    // 1. 激活是什么？光标放在一段加粗、下划线的文本时，菜单栏里的 B 和 U 被激活，如下图
    // 2. 什么时候执行这个函数？每次编辑器区域的选区变化（如鼠标操作、键盘操作等），都会触发各个菜单的 tryChangeActive 函数，重新计算菜单的激活状态
    tryChangeActive() {
        const reg = /^h/i
        const cmdValue = this.editor.cmd.queryCommandValue('formatBlock12')
        if (reg.test(cmdValue)) {
            // 选区处于标题内，激活菜单
            this.active()
        } else {
            // 否则，取消激活
            this.unActive()
        }
    }
}


export default class Editors extends Component {
    constructor(props) {
        super(props);
        this.editorElemMenu = React.createRef();
        this.editorElemBody = React.createRef();
        this.state = {
            editorContent: ''
        };
    }


    componentDidMount() {
        const editor = new E("#div1");
        // 使用 onchange 函数监听内容的变化，并实时更新到 state 中
        editor.config.onchange = html => {
            console.log(editor.txt.html())
            this.setState({
                editorContent: editor.txt.html()
            })
        }
        editor.config.menus = [
            // 'head',  // 标题
            'bold',  // 粗体
            // 'fontSize',  // 字号
            // 'fontName',  // 字体
            // 'italic',  // 斜体
            // 'underline',  // 下划线
            // 'strikeThrough',  // 删除线
            'foreColor',  // 文字颜色
            // 'backColor',  // 背景颜色
            // 'link',  // 插入链接
            'list',  // 列表
            // 'justify',  // 对齐方式
            // 'quote',  // 引用
            // 'emoticon',  // 表情
            'image',  // 插入图片
            // 'table',  // 表格
            // 'video',  // 插入视频
            // 'code',  // 插入代码
            // 'undo',  // 撤销
            // 'redo'  // 重复
        ];
        editor.config.uploadImgShowBase64 = true;
        editor.config.uploadImgServer = ''; // 图片服务器
        editor.config.uploadImgMaxSize = 1 * 1024 * 1024;
        editor.config.uploadImgMaxLength = 1;
        editor.config.showLinkImg = false;
        // 自定义文件名
        editor.config.uploadFileName = 'filename';
        // 将 timeout 时间改为 3s
        editor.config.uploadImgTimeout = 3000;

        //视频
        editor.config.uploadVideoServer = '';

        editor.config.uploadImgHooks = {
            before: function (xhr, editor, files) {
                // 图片上传之前触发
                // xhr 是 XMLHttpRequst 对象，editor 是编辑器对象，files 是选择的图片文件

                // 如果返回的结果是 {prevent: true, msg: 'xxxx'} 则表示用户放弃上传
                // return {
                //     prevent: true,
                //     msg: '放弃上传'
                // }
                alert("前奏");
            },
            success: function (xhr, editor, result) {
                // 图片上传并返回结果，图片插入成功之后触发
                // xhr 是 XMLHttpRequst 对象，editor 是编辑器对象，result 是服务器端返回的结果
                // var url = result.data.url;
                // alert(JSON.stringify(url));
                // editor.txt.append(url);
                alert("成功");
            },
            fail: function (xhr, editor, result) {
                // 图片上传并返回结果，但图片插入错误时触发
                // xhr 是 XMLHttpRequst 对象，editor 是编辑器对象，result 是服务器端返回的结果
                alert("失败");
            },
            error: function (xhr, editor) {
                // 图片上传出错时触发
                // xhr 是 XMLHttpRequst 对象，editor 是编辑器对象
                alert("错误");
            },
            // 如果服务器端返回的不是 {errno:0, data: [...]} 这种格式，可使用该配置
            // （但是，服务器端返回的必须是一个 JSON 格式字符串！！！否则会报错）
            customInsert: function (insertImg, result, editor) {
                // 图片上传并返回结果，自定义插入图片的事件（而不是编辑器自动插入图片！！！）
                // insertImg 是插入图片的函数，editor 是编辑器对象，result 是服务器端返回的结果
                // 举例：假如上传图片成功后，服务器端返回的是 {url:'....'} 这种格式，即可这样插入图片：
                var url = result.data[0].fileUrl;
                insertImg(url);
                // result 必须是一个 JSON 格式字符串！！！否则报错
            }
        }

        // 注册菜单
        const menuKey = 'alertMenuKey' // 菜单 key ，各个菜单不能重复
        editor.menus.extend('alertMenuKey', AlertMenu);
        
        // 将菜单加入到 editor.config.menus 中
        // 也可以通过配置 menus 调整菜单的顺序，参考【配置菜单】部分的文档
        editor.config.menus = editor.config.menus.concat(menuKey);

        editor.create()
    };





    render() {
        return (
            <div className="shop">
                <div id="div1">
                    <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
                </div>
            </div>
        );
    }

}

create-create-panel-conf.js

/**
 * @description video 菜单 panel tab 配置
 * @author tonghan
 */

// import editor from '../../editor/index';
import { PanelConf, $ } from 'wangeditor';
import UploadVideo  from './upload-video';



export default function Panels (editor, video) {
    // panel 中需要用到的id
    const upTriggerId = 'input-iframe-1'
    const upFileId = 'btn-ok-1'

    const uploadVideo = new UploadVideo(editor);


    /**
     * 插入链接
     * @param iframe html标签
     */
    function insertVideo(video) {
        editor.cmd.do('insertHTML', video + '<p><br></p>')
    }

    const conf = {
        width: 300,
        height: 0,
        // panel 中可包含多个 tab
        tabs: [
            {
            // 标题
            title: editor.i18next.t('menus.panelMenus.video.插入视频'),
            // 模板
            tpl: `<div class="w-e-up-img-container">
                    <div id="${upTriggerId}" class="w-e-up-btn">
                        <i class="w-e-icon-upload2"></i>
                    </div>
                    <div style="display:none;">
                        <input id="${upFileId}" type="file"  accept="audio/mp4, video/mp4"/>
                    </div>
                </div>`,
            // 事件绑定
            events: [
                // 触发选择图片
                {
                    selector: '#' + upTriggerId,
                    type: 'click',
                    fn: () => {
                        const $file = $('#' + upFileId)
                        const fileElem = $file.elems[0]
                        if (fileElem) {
                            fileElem.click()
                        } else {
                            // 返回 true 可关闭 panel
                            return true
                        }
                    },
                },
                // 选择图片完毕
                {
                    selector: '#' + upFileId,
                    type: 'change',
                    fn: () => {
                        const $file = $('#' + upFileId)
                        const fileElem = $file.elems[0]
                        if (!fileElem) {
                            // 返回 true 可关闭 panel
                            return true
                        }

                        // 获取选中的 file 对象列表
                        const fileList = fileElem.files
                        if (fileList.length) {
                            console.log(fileList, 'filelist==>');
                            // 拿到文件了  自己进行上传
                            // uploadVideo.uploadVideo(fileList);
                            // console.log('UploadVideo.uploadVideo===>');
                        }

                        // 返回 true 可关闭 panel
                        return true
                    },
                },
            ],
            }
        ], // tabs end
    }

    return conf
}

**Comment by wangfupeng1988** [comment]
代码过于复杂了。

建议你从最简单的开始，例如不要有 React，不要有图片上传的代码，把能砍的全砍掉。

只要能复现 bug ，代码越简单越好，一行都不要多余。

**Comment by wangfupeng1988** [comment]
长时间未回复，关闭 issue
