### ISSUE TITLE
addRange(): The given range isn't in document.

### ISSUE THREAD

**Issue by zdd5176312** [wangeditor-team/wangEditor#2374]
## bug 描述

*react切换树节点，展示对应的信息时，出现addRange(): The given range isn't in document.警告，表示实例化的对象已被移除*

## 你预期的样子是？

*切换树节点第一级时清空内容，将元素禁用；切换第二级时显示对应的信息*

## 浏览器及版本号

*谷歌浏览器 85.0.4183.102*

## wangEditor 版本

*^4.0.4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
- 步骤一 下载react、antd，选择antd中的树组件
- 步骤二 切换树节点，当level为1时，清空元素内容，且禁用元素
- 步骤三 切换树节点，当level为2时，展示对应的内容，并取消禁用元素
`
if (obj.date_level === '1') {
                            this.editor.txt.html('XXX')
                            this.editor.$textElem.attr('contenteditable', true);
                        } else {
                            this.formRef.current.resetFields();
                            this.editor.txt.clear();
                            this.editor.$textElem.attr('contenteditable', false);
                        }
`

**Comment by wangfupeng1988** [comment]
复现步骤过于复杂了。有没有更简单一点的？不用 antd ，不用树组件？
还是说，必须是这个步骤才能复现？

**Comment by zdd5176312** [comment]
> 是否没有更简单一点的？没有antd，不用树组件？
> 还是说，必须是这个步骤才能复现？

我写个demo给您发过去，您看行不行

**Comment by wangfupeng1988** [comment]
@zdd5176312 可以，写个简单的 demo ，上传到 github 吧，链接发过来。
只要能复现问题即可，越简单越好，让我们以最下成本复现问题。

**Comment by wangfupeng1988** [comment]
6 天未回复，暂时关闭

**Comment by zdd5176312** [comment]
那个问题解决了，不是插件的问题，那个bug是因为清空了form表单导致的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 中午12:50
收件人:&nbsp;"wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送:&nbsp;"START"<1876953027@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] addRange(): The given range isn't in document. (#2374)





 
@zdd5176312 可以，写个简单的 demo ，上传到 github 吧，链接发过来。
 只要能复现问题即可，越简单越好，让我们以最下成本复现问题。
