### ISSUE TITLE
editor.$textElem.attr('contenteditable', false)配置禁用编辑器后，redo和undo按钮仍可用

### ISSUE THREAD

**Issue by sunliyun** [wangeditor-team/wangEditor#2376]
## bug 描述

editor.$textElem.attr('contenteditable', false)配置禁用编辑器后，redo和undo按钮仍可用

## 你预期的样子是？

editor.$textElem.attr('contenteditable', false)配置禁用编辑器后，菜单栏中的所有按钮都禁用

## 浏览器及版本号

目前wangEditor支持的浏览器就可以

## wangEditor 版本

v4.0.8

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

editor.$textElem.attr('contenteditable', false)

**Comment by UltramanWeiLai** [comment]
当前已经开发了禁用相关的API
请等待更新

**Comment by wangfupeng1988** [comment]
升级 v4.1.0 ，文档参考 http://www.wangeditor.com/doc/pages/08-%E5%B8%B8%E7%94%A8API/04-%E7%A6%81%E7%94%A8%E7%BC%96%E8%BE%91%E5%99%A8.html
