### ISSUE TITLE
首行blockquote无法删除

### ISSUE THREAD

**Issue by yuluowuying** [wangeditor-team/wangEditor#2378]
## bug 描述

当编辑器首行是引用快blockquote的时候，不管如何操作，都无法删除，只有在首行以外的地方使用引用块，才可以删除。

## 你预期的样子是？

预期是可以删除。
不过我看了其他浏览器，似乎这是一个业界难题，只要首行是blockquote，都无法删除。

## 浏览器及版本号

Chrome 86.0.4240.111版本

## wangEditor 版本

任何版本。

## 官网能否复现该 bug ？

能。

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
在官网的demo页中的编辑器，首行弄一个blockquote。
- 步骤二
在下面写点儿东西。
- 步骤三
再回去删除blockquote，会发现无法删除。

**Comment by wangfupeng1988** [comment]
是不能删除。你可以点击菜单栏中的“引用”菜单，取消引用块。

这就像是，首行如果是一个 h1 ，那你也只能删除内容，而不能删除 h1 这个样式。
