### ISSUE TITLE
在富文本中插入button后用户可以修改按钮文字

### ISSUE THREAD

**Issue by 1308774130** [wangeditor-team/wangEditor#2379]
## bug 描述

*当我使用editor.cmd.do('innerHtml','<button>这应该是一个按钮</button>)对内容进行按钮插入以后，用户还可以通过移动光标至按钮文字上来进行按钮文字修改*

## 你预期的样子是？

*按钮正常显示，且用户不可修改按钮文字*

## 浏览器及版本号

*谷歌浏览器 3.0.1.6*

## wangEditor 版本

*V4.0.8*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 使用js控制执行editor.cmd.do('innerHtml','<button>这应该是一个按钮</button>)
- 按钮添加进来以后把光标移到按钮的文字上任意位置，然后输入文字

**Comment by wangfupeng1988** [comment]
编辑器现在还不支持编辑 form 表单，所以 button 默认也是可编辑的，你的需求暂时无法满足。

**Comment by cmm-va** [comment]
解决了吗 楼主  同样的问题
