### ISSUE TITLE
复制粘贴图片到编辑器不支持ie11和chrom，在safari是没有问题的

### ISSUE THREAD

**Issue by gaoshanliushui1** [wangeditor-team/wangEditor#2382]
## bug 描述

*复制粘贴本地图片到编辑器只有在safari可以，在ie11和chrom不支持*

## 你预期的样子是？

*chrom和IE11支持复制粘贴图片*

## 浏览器及版本号

*ie11，chrom*

## wangEditor 版本

*4.1.0*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 复制图片
- 让光标在编辑框闪烁
- 粘贴图片

**Comment by wangfupeng1988** [comment]
你说的是，直接在电脑桌面上，鼠标右击，复制一个图片文件，对吧？

**Comment by gaoshanliushui1** [comment]
是的

**Comment by wangfupeng1988** [comment]
@chenxiaoleizi 第一，先去调研一下各个浏览器粘贴图片文件的能力，在语雀写一篇调研文档。第二，根据调研结果再来看如何处理这个 issue 。

**Comment by chenxiaoleizi** [comment]
浏览器对本地图片粘贴存在限制，暂无好的办法解决这个问题。

**Comment by chenxiaoleizi** [comment]
浏览器也是为了考虑用户的使用安全，如果可以随便使用用户剪切板的内容，用户的隐私便可能会被泄漏。
