### ISSUE TITLE
编辑器里面输入文字和上传图片之后，点击发布按钮，怎么去掉p标签

### ISSUE THREAD

**Issue by cocozhang2017** [wangeditor-team/wangEditor#2386]
<p>555<br></p><p><img src="http://127.0.0.1:9001/SmartPsMas/Luck_draw\100005\01\logo.png"><br></p>
编辑器里面输入文字和上传图片之后，点击发布按钮，怎么去掉p标签和br标签，只需要里面的555,和http://127.0.0.1:9001/SmartPsMas/Luck_draw\100005\01\logo.png

**Comment by UltramanWeiLai** [comment]
。。。用正则匹配掉所有的你不需要的 html 标签
