### ISSUE TITLE
编辑器内使用ctrlC复制内容，光标选择在复制内容之后，粘贴无效

### ISSUE THREAD

**Issue by Seashell113** [wangeditor-team/wangEditor#2387]
## bug 描述

*在编辑器内ctrlC复制一段文本，然后鼠标点击让光标选择到原位置之后ctrlV粘贴，第一次粘贴在视觉效果上是失效的，但触发了粘贴事件，猜测是触发了选中文本的替换行为，即选中文本复制后点击鼠标并没有取消文本的选中状态*

## 你预期的样子是？

*粘贴后在光标位置后正常插入粘贴文本*

## 浏览器及版本号

*所有浏览器*

## wangEditor 版本

*v4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 在编辑器内ctrlC复制一段文本
- 鼠标点击让光标选择到复制内容后方
- ctrlV粘贴

**Comment by UltramanWeiLai** [comment]
该问题已在 v4.2.2 中解决，请更新版本。
如有问题可以重新提交 issuse
