### ISSUE TITLE
创建blockquote然后在其区域enter有时会创建blockquote有时会创建P，效果不一致

### ISSUE THREAD

**Issue by achuanVVVVV** [wangeditor-team/wangEditor#2389]
## bug 描述

创建blockquote然后在其区域enter有时会创建blockquote有时会创建P，效果不一致

## 你预期的样子是？

统一就好了，按照其他编辑器对比的话创建p更符合预期

## 浏览器及版本号

谷歌 80+

## wangEditor 版本

master 最新pull

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
除了以下情况其他情况enter创建为标签(指非代码块，tab)

- 步骤一  在一个空行选中引用区块 创建`blockquote`
- 步骤二 按下键盘上键移动光标，然后按下下键，移动光标
- 步骤三  按下enter 这个时候会创建`blockquote`

**Comment by UltramanWeiLai** [comment]
请移步到 #2417 中跟进该问题
