### ISSUE TITLE
insertHTML错误以及换行

### ISSUE THREAD

**Issue by lvtanxi** [wangeditor-team/wangEditor#2390]
## bug 描述

*在编辑器中输入一串文字，在字符串中间插入<button>测试</button>，button元素变成了span元素，还有一个就是插入第一个元素会导致编辑器会自动添加<br/>标签导致换行

## 你预期的样子是？

在指定位置插入button等相关元素，且不会被替换成其他元素变迁，也不换行。

## 浏览器及版本号

chrome 85.0.4183.83

## wangEditor 版本

我是直接用https://unpkg.com/wangeditor/dist/wangEditor.min.js，这个应该是最新的

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
情况一：
第一步在编辑器中输入一串字符串"我只是用来测试"
第二步调用editor.cmd.do('insertHTML', '<button>测试</button>‘)在字符中间插入，会变成span
情况二：
第一步在编辑器中输入一串字符串"我只是用来测试"
第二步调用editor.cmd.do('insertHTML', ' <button>测试</button> ’)在字符中间插入，编辑器自动换行了

**Comment by wangfupeng1988** [comment]
用 http://106.55.153.217:8881/master/examples/index.html 做测试，这个页面可以直接在控制台获取 `editor`

按照你的步骤，没有复现问题。

**Comment by lvtanxi** [comment]
@wangfupeng1988 
![Uploading 截图录屏_选择区域_20201031130535.gif…]()

![Uploading d.png…]()

**Comment by wangfupeng1988** [comment]
@lvtanxi 用文字吧，github 图片有时候加载不出来。

**Comment by lvtanxi** [comment]
@wangfupeng1988 
这是我的操作和代码
http://note.youdao.com/s/Aqihnt6s
http://note.youdao.com/s/ZiUoOF9H

**Comment by lvtanxi** [comment]
@wangfupeng1988 
这个是添加按钮自动换行的问题，代码跟上面一下，只不过我插入的时候是这样写的：
 editor.cmd.do('insertHTML', '<button contenteditable="false">测试</button>');

http://note.youdao.com/s/EVKbs0X1

**Comment by lvtanxi** [comment]
@wangfupeng1988 编辑器自动把button给解析了
重现步骤为：
情况一：
第一步在编辑器中输入一串字符串"我只是用来测试"
`第二步调用editor.cmd.do('insertHTML', '<button>测试</button>‘)在字符中间插入，会变成span`
情况二：
第一步在编辑器中输入一串字符串"我只是用来测试"
`第二步调用editor.cmd.do('insertHTML', ' <button  contenteditable='false'>测试</button> ’)在字符中间插入，编辑器自动换行了`

**Comment by wangfupeng1988** [comment]
wangEditor 目前只支持图文编辑，不支持编辑表单，以及表单项（如 button input textarea）
所以，你插入 `button` ，我们暂时无法做技术支持。

**Comment by lichenabson** [comment]
@lvtanxi 

``` this.editor.cmd.do('insertElem', { elems: [dom] })```
可以使用这种方式 插入 dom 替代 ```insertHtML```
```insertHtML``` 会有很多其他的问题
```insertElem ``` 虽然没有在文档上说明, 但是是可以使用的

**Comment by cmm-va** [comment]
> @lvtanxi
> 
> ` this.editor.cmd.do('insertElem', { elems: [dom] })`
> 可以使用这种方式 插入 dom 替代 `insertHtML`
> `insertHtML` 会有很多其他的问题
> `insertElem ` 虽然没有在文档上说明, 但是是可以使用的

> @lvtanxi
> 
> ` this.editor.cmd.do('insertElem', { elems: [dom] })`
> 可以使用这种方式 插入 dom 替代 `insertHtML`
> `insertHtML` 会有很多其他的问题
> `insertElem ` 虽然没有在文档上说明, 但是是可以使用的

insertElem的具体写法是？  我写都一直报错
