### ISSUE TITLE
页面有多个editor时，disable只对第一个起作用，并且disable时看不到txt.html()设置的内容

### ISSUE THREAD

**Issue by songlai** [wangeditor-team/wangEditor#2392]
## bug 描述

*当页面有多个editor时，disable只对第一个起作用，并且disable时看不到txt.html()设置的内容，editor中空白*

## 你预期的样子是？

*页面有多个时 this.$refs.editor.disable() 生效*
*disable时可正常浏览，但不能修改*

## 浏览器及版本号

*Google Chrome 版本 86.0.4240.80（正式版本） (x86_64)*

## wangEditor 版本

*4.1.0*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 创建多个editor
- 通过txt.html()赋值
- disable

**Comment by wangfupeng1988** [comment]
http://106.55.153.217:8881/master/examples/multi-editor.html ，我用这个做测试，这个页面可以在控制台使用 `editor1` `editor2`

```js
editor1.txt.html('<p>aaaa</p>') // 成功
editor2.txt.html('<p>bbbb</p>') // 成功
editor1.disable() // 成功
editor2.disable() // 失败
```

即，多个编辑器，第一个 `disable()` 之后，第二个就无法 `disable()` 了。这是一个 bug

你所说的其他问题，我没有复现，你可以继续追加复现的步骤。

**Comment by songlai** [comment]
editor1.disable() // 成功
editor2.disable() // 失败
editor1.txt.html('<p>aaaa</p>') // 失败
editor2.txt.html('<p>bbbb</p>') // 成功

**Comment by wangfupeng1988** [comment]
问题已修复，请升级到 v4.3.0 。

如有其他问题，可再重新提交新 issue 。
