### ISSUE TITLE
建议图片尺寸修改 加上一个自适应性tooltip选项

### ISSUE THREAD

**Issue by yuntian001** [wangeditor-team/wangEditor#2395]
## 功能描述

*建议图片尺寸修改 加上一个自适应性选项 点击后去掉之前拖拽或点击百分比 tooltip生成宽高style， 还原为最初上传完的样式状态 或者是width height 设为auto*

## 提炼几个功能点
- 图片 tooltip 加上一个自适应性选项点击后
去掉之前拖拽和点击百分比 tooltip生成宽高style 还原为最初上传完的样式状态 
或者
width height 设为auto*

## 原型图

*无*

## 可参考的案例

无

**Comment by wangfupeng1988** [comment]
可以加

**Comment by UltramanWeiLai** [comment]
> 可以加

这个应该是说 恢复默认 或者 清理格式 是不是会比较好
