### ISSUE TITLE
增加单独禁用编辑区域的功能

### ISSUE THREAD

**Issue by justinluhui** [wangeditor-team/wangEditor#2397]
## 功能描述

目前v4.1.0版本，禁止富文本的时候，是工具栏和内容区域一起禁止的
能否增加API，只禁止富文本编辑区域？

## 提炼几个功能点

- 工具栏和富文本编辑取，可以独立禁用
- 支持同时禁用工具栏和编辑区域

## 原型图
无

## 可参考的案例
v3版本的wangEditor支持this.editor.$textElem.attr("contenteditable", true/false) 的方式禁用或启用编辑区内容，V4好像不行

**Comment by justinluhui** [comment]
let mant = document.getElementsByClassName("w-e-menue-mantle");
mant && mant.length > 0 && mant[0].remove();
最好可以通过API实现  现在这么搞的

**Comment by wangfupeng1988** [comment]
> v3版本的wangEditor支持this.editor.$textElem.attr("contenteditable", true/false) 的方式禁用或启用编辑区内容，V4好像不行

v4 可以使用 `editor.$textElem.attr('contenteditable', false)`
