### ISSUE TITLE
表格功能比较单一

### ISSUE THREAD

**Issue by jzyzxx** [wangeditor-team/wangEditor#2400]
## 功能描述

*目前插入表格功能非常基础,希望能够增加以下功能*

## 提炼几个功能点

- 功能1 单元格行与列合并
- 功能2 单元格推拽改变宽度
- 功能3 单元格拖拽排序

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
http://doc.huangsw.com/vue-easytable/app.html#/table

**Comment by wangfupeng1988** [comment]
这些后面会作为新功能来安排开发。
需要一些时间，因为这些功能都非常复杂。
