### ISSUE TITLE
粘贴图片会触发多个函数

### ISSUE THREAD

**Issue by TaoWang747694342** [wangeditor-team/wangEditor#2401]
## bug 描述

*请输入内容……*正常：复制网络图片/word图片粘贴到富文本触发粘贴函数
                          问题：复制微信聊天记录图片粘贴到富文本会触发粘贴函数和customUploadImg函数

## 你预期的样子是？

*请输入内容……*粘贴只执行粘贴函数，点击上传图片才会执行customUploadImg函数

## 浏览器及版本号

*请输入内容……*chrome 版本 85.0.4183.102（正式版本)

## wangEditor 版本

*请输入内容……*v3

## 官网能否复现该 bug ？

能/不能  不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  创建富文本
- 步骤二   添加上传图片方法
- 步骤三    添加粘贴上传方法

**Comment by wangfupeng1988** [comment]
粘贴图片，就得上传图片。否则图片存哪里呀？

**Comment by UltramanWeiLai** [comment]
由于长时间无人回复，该问题暂且关闭。
如还有疑问可以重新提交 issues
