### ISSUE TITLE
标签引用功能问题

### ISSUE THREAD

**Issue by cb3570594** [wangeditor-team/wangEditor#2402]
## bug 描述

问题1：光标定位在表情后，点击上方引用按钮，只会在末尾增加无效的span标签，没有取消的功能
问题2：光标定位在某个ul,li下，点击上方引用按钮，只会无限增加blockquote标签，没有取消的功能*

## 你预期的样子是？

点击引用按钮，可以正常添加和删除blockquote标签

## 浏览器及版本号

*chrome v86.0.4240.111*

## wangEditor 版本

*官方demo*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

如图
![微信截图_20201103100318](https://user-images.githubusercontent.com/33076027/97938358-34185880-1dbc-11eb-9e2f-ba7c3e476607.png)

**Comment by UltramanWeiLai** [comment]
问题1：在官网 demo 上复现了，但是在 master上没有复现
问题2：复现了 但是我记得 引用好像是不能对 序列进行 引用的

**Comment by xian1688** [comment]
最新版的4.2.1，wangEditor.js或wangEditor.min.js文件为什么不在文件夹里面的，这该调用谁呢？网上文档和实际文件根本不一样

**Comment by UltramanWeiLai** [comment]
> 最新版的4.2.1，wangEditor.js或wangEditor.min.js文件为什么不在文件夹里面的，这该调用谁呢？网上文档和实际文件根本不一样

没明白你的意思，如果你是说源码里面的没有 wangEditor.js 的话，是因为需要编译，如果想单纯获取文件，可以复制 CND 的代码，或者参考群里的视频，我们有大佬已经录制了如何获取 wangEditor.min.js 文件的视频

**Comment by UltramanWeiLai** [comment]
请移步到 #2417 中跟进该问题
