### ISSUE TITLE
使用关闭粘贴样式的过滤时，无效。浏览器是谷歌、360、Edge

### ISSUE THREAD

**Issue by Allie1995** [wangeditor-team/wangEditor#2405]
根据文档引入使用的，然后我需求是从word粘贴文本，原本在word上的样式需要保留。所以我就是用了关闭粘贴样式过滤功能，结果试了好几个浏览器，结果没用。
代码如下：
    <script src="https://unpkg.com/wangeditor/dist/wangEditor.min.js"></script>
    <script type="text/javascript">
        const E = window.wangEditor
        const editor = new E('#editor');
        editor.config.pasteFilterStyle = false;
        editor.create()
    </script>
请问是怎么回事，急

**Comment by wangfupeng1988** [comment]
请按照 issue 模板，重新提交 issue 。
