### ISSUE TITLE
直接复制网页上有缩进的段落文字到编辑器中后，缩进部分丢失

### ISSUE THREAD

**Issue by unifocustar** [wangeditor-team/wangEditor#2409]
## bug 描述

直接复制网页上有缩进的段落文字到编辑器中后，缩进部分丢失

## 你预期的样子是？

直接复制网页上有缩进的段落文字到编辑器中后，保持缩进部分

## 浏览器及版本号

Cent Browser
版本 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)

## wangEditor 版本

官网demo（https://unpkg.com/wangeditor/dist/wangEditor.min.js）

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
访问：https://notebook.pconline.com.cn/1382/13820624.html#ad=8384，复制内容到编辑器窗口

- 步骤二
原网页段落前缩进消失

**Comment by wangfupeng1988** [comment]
复制粘贴时，这种样式的细节，暂时支持不了。
