### ISSUE TITLE
当富文本内容为空时，插入iframe视频后会执行onload中的代码

### ISSUE THREAD

**Issue by saint3347** [wangeditor-team/wangEditor#2412]
## bug 描述

*当富文本内容为空时，插入iframe视频后会执行onload中的代码*
![image](https://user-images.githubusercontent.com/7347133/98102476-a1b4a980-1ece-11eb-9077-d2f41b769ca9.png)

![image](https://user-images.githubusercontent.com/7347133/98102411-8fd30680-1ece-11eb-9213-8513522b4eef.png)

## 你预期的样子是？

*当富文本内容为空时，插入iframe视频后也不会执行onload中的代码*

## 浏览器及版本号

*chrome 最新版本*

## wangEditor 版本

*最新版本*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 富文本内容全部删除，删除干净
- 步骤二 点击插入视频
- 步骤三 输入<iframe onload="alert(1)"></iframe>，确定

**Comment by wangfupeng1988** [comment]
无论编辑器内容是否为空，iframe onload 都会执行，这个是符合预期的呀。
为啥要写 onload ，但却不让它执行呢？

**Comment by saint3347** [comment]
@wangfupeng1988 在官网上测试，有内容时插入视频的iframe的onload会被过滤掉了。

写 onload的人可能是要恶意攻击网站的人，录入的是评论，当其他用户打开评论列表页面时，就会alert一些奇怪的东西，或者写成<iframe onload="document.body.innerHTML = ''"></iframe>，页面都没了。。

**Comment by wangfupeng1988** [comment]
你可以获取 html ，然后正则匹配，把 onload 给过滤掉。

**Comment by UltramanWeiLai** [comment]
由于长时间没有回复，暂且关闭该问题
如后续有其他问题，可以重新提交 issuse 并附上该地址
