### ISSUE TITLE
选中内容改变样式，会出现选中内容有一部分没有改变样式

### ISSUE THREAD

**Issue by z1314x2007** [wangeditor-team/wangEditor#2415]
## bug 描述

*比如把一段文字变为粗体。操作过程：从右往左选中内容，鼠标在编辑框外松开左键，然后点击加粗菜单。会出现最左边的内容不会加粗。*

## 你预期的样子是？

*选择部分正常改变样式*

## 浏览器及版本号

*chrome 版本 85.0.4183.102（正式版本） （64 位）*

## wangEditor 版本

*V4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 从右往左选中第一行文字，鼠标一定要在编辑框外侧松开
- 步骤二 点击加粗菜单按钮
- 步骤三 BUG出现

**Comment by UltramanWeiLai** [comment]
按照你这个我并没有复现
你可以尝试着更新一下 编辑器的版本为最新的 v4.2.2

**Comment by UltramanWeiLai** [comment]
由于长时间没有回复，暂且关闭该问题
如后续有其他问题，可以重新提交 issuse 并附上该地址
