### ISSUE TITLE
撤销功能的撤销栈能否开放重置功能?

### ISSUE THREAD

**Issue by ahua8** [wangeditor-team/wangEditor#2416]
## 功能描述

在使用过程中, 同一书本下编辑多篇文章,可能是同一个editor实例(或者新实例),通过html()导入所选文章,这时点击编辑,会高亮撤销功能.  
   新实例的情况下,撤销会到空白,也就是html(content)之前的情况.
   单实例的情况下,撤销到内容跟所选章节严重不一致.会撤到之前修改过的文章,这对于保存来说,太多不可控.

希望大神,能否开放清空撤销栈的API, 通过调用实例方法的形式, 保障文档编辑过程中的内容的可控范围.

**Comment by wangfupeng1988** [comment]
请按照 issue 模板，重新提交 issue 。
