### ISSUE TITLE
引用菜单 BUG

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2417]
## bug 描述

BUG1：当引用标签在一个空行创建的时候会生成一个 空格标签 所以在通过鼠标进行光标移动到引用标签进行空行回车的时候无法跳出引用标签
BUG2：光标定位在表情后，点击上方引用按钮，只会在末尾增加无效的span标签，没有取消的功能
BUG3：光标定位在某个ul,li下，点击上方引用按钮，只会无限增加blockquote标签，没有取消的功能*

## 你预期的样子是？

点击引用按钮，可以正常添加和删除blockquote标签
回车换行能正常跳出引用

## 浏览器及版本号

chrome v86.0.4240.111

## wangEditor 版本

wangEditor V4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

BUG1 #2389 
- 步骤一 在一个空行选中引用区块 创建blockquote
- 步骤二 按下键盘上键移动光标，然后按下下键，移动光标
- 步骤三 按下enter 这个时候会创建blockquote

BUG2 & BUG3 #2402 
![image](https://user-images.githubusercontent.com/23336585/98194188-bc803000-1f59-11eb-8608-a82f8a3ae439.png)

**Comment by wangfupeng1988** [comment]
下载 v4.4.0
