### ISSUE TITLE
多图上传问题

### ISSUE THREAD

**Issue by pzs616358428** [wangeditor-team/wangEditor#2419]
## 问题描述

*多图上传时，请求参数名为file1,file2...，导致使用springmvc时无法使用数组接收，已使用自定义上传解决此问题*

## wangEditor 版本

*4.2.2*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 个人建议：目前FormData已支持设置多个重复的key，建议源码第4197行（name = name + (index + 1);）去掉
- 个人建议：或者增加一个参数来设置是否重名模式

**Comment by pzs616358428** [comment]
不好意思作者，写的时候没注意最后是复现步骤，被看成了修复步骤，实在是抱歉，复现的话用springmvc的上传功能接收一下多图片上传就可以

**Comment by UltramanWeiLai** [comment]
我个人觉得，这个 + 1 还是需要的。
如上述你说的，你不需要的话可以通过 自定义上传 来解决这个问题。

**Comment by pzs616358428** [comment]
好的
