### ISSUE TITLE
可不可以开放撤销栈的控制功能?

### ISSUE THREAD

**Issue by ahua8** [wangeditor-team/wangEditor#2421]
## 功能描述
在初始化编辑器后,通过html(),导入一篇文档,点击编辑区域,撤销会激活,点击撤销会导致内容被清空了.
在单实例,多编辑文档的情况下,会因为撤销,章节与撤销退档的内容严重偏移,

希望可能通过调用实例方法,可以清空撤销栈.保障文档编辑的安全性

## 提炼几个功能点

- 开放撤销栈的控制方法,比如清空撤销栈

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
撤销栈暂时无法开放。

建议你不要通过 `editor.txt.html()` 去赋值内容，可以通过该文档的第一种方式 http://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/01-%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AE%B9.html
