### ISSUE TITLE
复制word文档格式保留bug

### ISSUE THREAD

**Issue by oushifa** [wangeditor-team/wangEditor#2422]
## bug 描述
复制word文档格式没有保留，style=undefine

问题解决：
src/lib/simplehtmlparser.js

parseAttributes: function (sTagName, s) {
        var oThis = this
        var attrs = []
        console.log(s)
        s.replace(this.attrRe, function (a0, a1, a2, a3, a4, a5, a6) {
            attrs.push(oThis.parseAttribute(sTagName, a0, a1, a2, a3, a4, a5, a6))
        })
        return attrs
    },

变更为 
parseAttributes: function (sTagName, s) {
        var oThis = this
        var attrs = []
        console.log(s)
        s.replace(this.attrRe, function (a0, a1, a2, a3, a4, a5, a6, a7) {
            attrs.push(oThis.parseAttribute(sTagName, a0, a1, a2, a3, a4, a5, a6, a7))
        })
        return attrs
    },

**Comment by UltramanWeiLai** [comment]
复制粘贴的话，默认是过滤掉样式的。
如果不想过滤样式，请查看文档，文档里面有相关内容。
还有请按照模板提交 issues 否则是不受理的。
