### ISSUE TITLE
使用命令，手动插入html，但是编辑器会修改插入的html

### ISSUE THREAD

**Issue by JaylanChen** [wangeditor-team/wangEditor#2423]
## bug 描述

使用命令，手动插入html，但是编辑器会修改插入的html
`editor.cmd.do('insertHTML', '<span style="color:#4E90CD;" data-key="testKey">[测试名称]</span>');`

有时插入的内容不变，有时，内容变成：
`<span data-key="testKey" style="color: rgb(78, 144, 205);">[测试名称]</span>`
更有甚者变成：
`<span style="color: rgb(78, 144, 205);">[测试名称]</span>`

## 你预期的样子是？
保持插入的html不变
`<span style="color:#4E90CD;" data-key="testKey">[测试名称]</span>`

## 浏览器及版本号
chrome  86

## wangEditor 版本
4.2.2

## 最小成本的复现步骤
```
editor.cmd.do('insertHTML', '<span style="color:#4E90CD;" data-key="testKey">[测试名称]</span>');
editor.cmd.do('insertHTML', '<span style="color:#4E90CD;" data-key="testKey">[测试名称]</span>');
editor.cmd.do('insertHTML', '<span style="color:#4E90CD;" data-key="testKey">[测试名称]</span>');
```

**Comment by wangfupeng1988** [comment]
insertHTML 是浏览器 document.execCommand 的 API ，它的逻辑编辑变化，我们控制不了。

建议你换一种方式，用 editor.txt.append 插入 html 。

**Comment by JaylanChen** [comment]
我不是要追加内容，我试要在光标锁在，插入指定内容占位，到时候动态替换掉。

**Comment by cmm-va** [comment]
这个问题解决了吗 ，楼主，我同样得问题

**Comment by JaylanChen** [comment]
都关闭这个issue了，解决不了。我换了个编辑器。我用的 TinyMCE， ckeditor 也可以看看
