### ISSUE TITLE
点击“图片”菜单按钮时，直接弹出文件选择框

### ISSUE THREAD

**Issue by weijunfu** [wangeditor-team/wangEditor#2425]
## 功能描述

当隐藏插入图片链接时，点击“图片”菜单按钮，直接弹出文件选择框，而不是弹出Panel，还需要再次点击上传图片的按钮

## 提炼几个功能点

- 功能1：当隐藏插入图片链接时，点击“图片”菜单按钮，直接弹出文件选择框
- 功能2：提供点击‘按钮’，直接弹出选择文件框（文件上传可由用户定义）

**Comment by weijunfu** [comment]
> ## 功能描述
> 当隐藏插入图片链接时，点击“图片”菜单按钮，直接弹出文件选择框，而不是弹出Panel，还需要再次点击上传图片的按钮
> 
> ## 提炼几个功能点
> * 功能1：当隐藏插入图片链接时，点击“图片”菜单按钮，直接弹出文件选择框
> * 功能2：提供点击‘按钮’，直接弹出选择文件框（文件上传可由用户定义）
> 
> ## 原型图
> ## 可参考的案例

## 可参考的案例， 图片直接选择上传
https://www.layui.com/demo/layedit.html

**Comment by wangfupeng1988** [comment]
当隐藏插入图片链接时，点击“图片”菜单按钮，直接弹出文件选择框 —— 这个可以采纳

隐藏插入图片链接，这个配置目前也有 http://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/13-%E9%9A%90%E8%97%8F%E6%8F%92%E5%85%A5%E7%BD%91%E7%BB%9C%E5%9B%BE%E7%89%87%E7%9A%84%E5%8A%9F%E8%83%BD.html

**Comment by UltramanWeiLai** [comment]
该问题转移到 #2585 去跟踪
