### ISSUE TITLE
disable()的问题

### ISSUE THREAD

**Issue by ahua8** [wangeditor-team/wangEditor#2427]
## 问题描述
你好,我遇到的问题是,我的文档每次ajax回来的内容后,会销毁与创建单独的实例.但是在ajax回来的内容disable的需求时,会disable Editor;
但是在切换多个文档时,本来disable()的editor依旧可以编辑. 

## wangEditor 版本

*V4*

## 是否查阅了文档 ？
是
（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤
大概代码逻辑如下:
>
$(function(root){}(
     var editor = null;
    //创建编辑器
    function create(){
       editor && editor.destroy();
       editor = null;
       editor = new E();
       editor.create();
    }
     //文档标题列表,每次点击LI,异步获取内容. 单独创建editor
    $('ul').on('click','li',function(d){
          $.post(url,data,function(row){
               create(); //销毁再创建编辑器
               if(row.disable) editor.disable();  //确认此处有执行,但编辑器不是disable状态.
          });
   });
)(this))

**Comment by wangfupeng1988** [comment]
逻辑过于复杂了吧，为啥要每次 ajax 都销毁重新创建？
建议你去改一个比较简单的实现方式，不要频繁创建销毁。

**Comment by wangfupeng1988** [comment]
@a835100635 关注一下这个问题

**Comment by ahua8** [comment]
那就出现像上次提的撤销栈问题了. 一个单实便,我不断的修改, 撤销到云里雾里与我当前编辑的ID都是不对称了.
[#2421](https://github.com/wangeditor-team/wangEditor/issues/2421)

**Comment by a835100635** [comment]
第二次使用disable()前需要先调用enable()

**Comment by a835100635** [comment]
就你目前这种写法情况来说的话先调用enable()

**Comment by UltramanWeiLai** [comment]
该问题已经解决，请留意更新
如还有这种情况出现，可以重新反馈
