### ISSUE TITLE
增加音视频上传播放功能

### ISSUE THREAD

**Issue by GitthubOne** [wangeditor-team/wangEditor#2429]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
音频视频上传功能，正在规划研发中
