### ISSUE TITLE
希望添加图片的时候支持设置图片的alt属性

### ISSUE THREAD

**Issue by pmb2020** [wangeditor-team/wangEditor#2430]
## 功能描述

*添加图片的时候，增加添加图片alt属性*

## 提炼几个功能点

- 标签栏的上传图片点击时，图片链接输入框位置希望增加图片alt属性的输入框
- 内容框点击图片时，可以修改图片的alt属性

一直都很在意这个问题，也一直在关注wangEditor，但每次更新一直都没有解决这个问题，因为图片的alt属性很影响网站seo的，，，

**Comment by wangfupeng1988** [comment]
alt 属性，需连同上传图片，一起考虑。

**Comment by BarryBravo** [comment]
请问现在可以加了吗？

**Comment by wangfupeng1988** [comment]
@BarryBravo 已受理，排队开发中

**Comment by GZ-ted** [comment]
希望支持设置图片的超链接，这个功能很常用，点击图片做跳转 @wangfupeng1988

**Comment by UltramanWeiLai** [comment]
该问题转移到 #2585 去跟踪
