### ISSUE TITLE
未填写超链接内容也可以插入

### ISSUE THREAD

**Issue by x13666567452** [wangeditor-team/wangEditor#2431]
## bug 描述
插入超链接 文案填写链接未填写插入之后点击会打开新的一个页面
## 你预期的样子是？
不应该可以打开新的页面或者是都必须填写才能插入
## wangEditor 版本
3.1.1
## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
点击超链接
- 步骤二
输入文案
- 步骤三
点击插入

**Comment by x13666567452** [comment]
文档中是可以通过下方的方式去实现的，但是建议组件不要直接alert （有点丑），应该给调用者自行处理 


editor.config.linkCheck = (text, link) => {
      if (!text) {
        return '请输入链接文案';
      }
      if (!link) {
        return '请输入链接';
      }
      return true;
    };

**Comment by wangfupeng1988** [comment]
请升级 v4 版本。
v3 升级 v4 很平滑的，成本很低。只需要把 `customConfig` 改成 `config` 即可。
