### ISSUE TITLE
如何让富文本适应黑色主题

### ISSUE THREAD

**Issue by YSGStudyHards** [wangeditor-team/wangEditor#2433]
## 问题描述
当我把后台的主题切换成黑色主题时，如何设置富文本适应黑色主题，因为加入不设置适用黑色主题的时候富文本中的内容就是白色的导致无法查看富文本中的内容。
如下图所示：
![image](https://user-images.githubusercontent.com/35737263/98649898-20985f00-2373-11eb-966c-4a2e64724757.png)

## wangEditor 版本
v4.3.0

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
目前不支持主题切换。

建议自己去修改编辑器的各个 css class 的样式，覆盖编辑器已有样式即可。
