### ISSUE TITLE
react 封装 编辑器后 使用的时候无法使用回退按键

### ISSUE THREAD

**Issue by leiS521** [wangeditor-team/wangEditor#2434]
## bug 描述

*react 使用的时候无法使用回退按键*

## 你预期的样子是？

*react 封装后可以使用*

## 浏览器及版本号

*谷歌*

## wangEditor 版本

*^4.3.0*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

步骤一 在react 项目里复制下面代码

import React, {Component} from 'react';
import PropTypes from 'prop-types';
import E from 'wangeditor'
import xiuMiCIon from "./img/xiuMiIcon.png";
let editor = null;
const { $, BtnMenu, DropListMenu, PanelMenu, DropList, Panel, Tooltip } = E

export default class WangEditor extends Component {
    static defaultProps = {};
    static propTypes = {};

    constructor(props) {
        super(props);
        this.state = {
            content:''
        }
    }

    componentWillMount() {
    }

    componentDidMount() {
        editor = new E(this._div);
       // editor = new E("#editor");
        editor.config.menus = [
            'head',
            'bold',
            'fontSize',
            'fontName',
            'italic',
            'underline',
            'strikeThrough',
            'indent',
            'lineHeight',
            'foreColor',
            'backColor',
            'link',
            'list',
            'justify',
            'quote',
           /* 'emoticon',*/
           /* 'image',
            'video',*/
            'table',
            /*'code',*/
            'splitLine',
            'undo',
            'redo',
        ];
        const menuKey = 'xiuMI'; // 菜单 key ，各个菜单不能重复
        editor.menus.extend('xiuMI', XiuMI);
        editor.goXIu=()=>{
            this.props.goXiuMi&&this.props.goXiuMi()
        };
        editor.config.menus = editor.config.menus.concat(menuKey);
        editor.config.onchange = (newHtml) => {
            console.log(newHtml)
            this.props.callBackeditorContent&&this.props.callBackeditorContent(editor.txt.html())
            this.setState({content:newHtml})
        }
        /**
         *
         * 一定要创建 */

        editor.create()
    }
    componentWillUnmount() {
        editor.destroy()
    }

    componentWillReceiveProps(nextProps, nextContext) {
        let content = nextProps.content;
        if (nextProps.isUpDate) {
            editor.txt.clear()
            editor.txt.append(content)
        }

    }

    render() {

        return (
            <div style={{height:575}}>
                <div id="editor" ref={(ref) => this._div = ref}></div>
              {/*  <button onClick={()=>this.getHtml1()}>获取html1</button>
                <button onClick={()=>this.getText()}>获取text</button>*/}
            </div>
        )
    }

    // 获取html方法2
    getHtml1() {
        alert(editor.txt.html())
    }

// 获取text
    getText() {
        alert(editor.txt.append('<div class="projection" ng-show="status.isCopyMode" tn-atom-context="{ type: \'paper\', inEditor: true, animationEnabled: false }" stop-propagation="mousedown mouseup mouseover keydown keyup contextmenu click dblclick" style=""> <div class="tn-projection-print tn-scene-paper ng-binding" ng-mouseenter="onProjectionMouseEnter($event)" ng-click="onProjectionClick($event)" ng-copy="onProjectionCopy($event)" ng-bind-html="transcodeHTML | unsafe">&nbsp;<section style="box-sizing: border-box; font-style: normal; font-weight: 400; text-align: justify; font-size: 16px;"><section style="box-sizing: border-box;" powered-by="xiumi.us"><p style="white-space: normal; margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"></p></section><section style="text-align: left; justify-content: flex-start; opacity: 0.99; margin: 10px 0% -20px; position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block; width: auto; vertical-align: top; min-width: 10%; max-width: 100%; height: auto; box-sizing: border-box;"><section style="text-align: center; justify-content: center; position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block; width: 100%; vertical-align: top; border-style: solid; border-width: 2px; border-radius: 8px; border-color: rgb(169, 56, 59); padding: 3px; height: auto; overflow: hidden; background-color: rgb(255, 255, 255); box-sizing: border-box;"><section style="display: inline-block; width: 100%; vertical-align: top; background-color: rgb(169, 56, 59); padding: 5px 15px; border-width: 0px; border-radius: 6px; border-style: none; border-color: rgb(62, 62, 62); overflow: hidden; box-sizing: border-box;" powered-by="xiumi.us"><section style="text-align: justify; color: rgb(255, 255, 255); letter-spacing: 2px; box-sizing: border-box;" powered-by="xiumi.us"><p style="white-space: normal; margin: 0px; padding: 0px; box-sizing: border-box;"><b style="box-sizing: border-box;">关注消防，生命至上</b></p></section></section></section></section></section></section><section style="margin: 0px 0% 10px; position: static; box-sizing: border-box;" powered-by="xiumi.us"><section style="display: inline-block; width: 100%; vertical-align: top; border-style: solid; border-width: 2px; border-radius: 8px; border-color: rgb(169, 56, 59); overflow: hidden; padding: 30px 10px 10px; box-sizing: border-box;"><section style="color: rgb(62, 62, 62); box-sizing: border-box;" powered-by="xiumi.us"><p style="white-space: normal; margin: 0px; padding: 0px; box-sizing: border-box;"><br style="box-sizing: border-box;"></p></section></section></section></section>&nbsp;</div> </div>'))
    }

}
class XiuMI extends BtnMenu {

    constructor(editor) {
        console.log(editor)
        const $elem = E.$(
            `<div style="line-height: 40px"><img style="width:25px;height:25px;" src="images/xiuMiIcon.png" alt=""/></div>)`
        )
        super($elem, editor)
    }
    // 菜单点击事件
    clickHandler() {
        // 做任何你想做的事情
        // 可参考【常用 API】文档，来操作编辑器
        editor.goXIu();
        //alert('hello world')
    }
    // 菜单是否被激活（如果不需要，这个函数可以空着）
    // 1. 激活是什么？光标放在一段加粗、下划线的文本时，菜单栏里的 B 和 U 被激活，如下图
    // 2. 什么时候执行这个函数？每次编辑器区域的选区变化（如鼠标操作、键盘操作等），都会触发各个菜单的 tryChangeActive 函数，重新计算菜单的激活状态
    tryChangeActive() {
        // 激活菜单
        // 1. 菜单 DOM 节点会增加一个 .w-e-active 的 css class
        // 2. this.this.isActive === true
        this.active()

        // // 取消激活菜单
        // // 1. 菜单 DOM 节点会删掉 .w-e-active
        // // 2. this.this.isActive === false
        // this.unActive()
    }
}

步骤2 引入后组件后使用 <WangEditor
                                            content={‘’}
                                           
                                            callBackeditorContent={(data) => {
                                               
                                            }}
                                            goXiuMi={()=>{} />

**Comment by wangfupeng1988** [comment]
你描述的复现步骤过于复杂了。

https://github.com/wangeditor-team/wangEditor-with-react
你看下，能从这个 demo 中复现你的问题吗？

**Comment by leiS521** [comment]
你好，我在这个demo复现下，然后打包发给你，谢谢你的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "王福朋"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 上午9:38
收件人: "wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;; 
抄送: "雷神"<731833645@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wangeditor-team/wangEditor] react 封装 编辑器后 使用的时候无法使用回退按键 (#2434)





 
你描述的复现步骤过于复杂了。
 
https://github.com/wangeditor-team/wangEditor-with-react
 你看下，能从这个 demo 中复现你的问题吗？

**Comment by leiS521** [comment]
我复现了一下。是因为别的代码，把回车事件屏蔽掉了。我封装的时候再次强行开启就好了，建议在组件里面把回退事件强行开启。就不会出现回退失效了。

**Comment by wangfupeng1988** [comment]
好的
