### ISSUE TITLE
自定义上传视频

### ISSUE THREAD

**Issue by liu-zong-qing** [wangeditor-team/wangEditor#2436]
## 功能描述

*像自定义上传图片一样*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
该功能已受理，并排队开发中。

如果自己实在着急，那只能自定义扩展菜单 http://www.wangeditor.com/doc/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/

**Comment by zhishaofei3** [comment]
求开发video
