### ISSUE TITLE
多语言  使用 i18next

### ISSUE THREAD

**Issue by gitxinyi** [wangeditor-team/wangEditor#2437]
## 问题描述
按文档操作，无法实现多语言
## wangEditor 版本
wangEditor4
## 是否查阅了文档 ？
是

后面自己解决了，主要原因还是自己对npm的使用缺少经验。

**Comment by gitxinyi** [comment]
经过反复的试验，终于解决了问题。
输入命令 ` npm i -S i18next `
一直报错
`npm WARN saveError ENOENT: no such file or directory, open 'D:\web\test\package.json'`

后来查找原因是 需要在执行命令的地方npm要初始化一下
`npm init -y`

然后再执行命令  
 ` npm i -S i18next `

再将i18next 引入到项目中需要用的到页面（/static/node_modules/i18next/，这个路径写改成自己的）
`
<script type="text/javascript" src="/static/node_modules/i18next/i18next.js?t=123"></script>`

**Comment by xiaokyo** [comment]
那我将issue关闭了
