### ISSUE TITLE
复制文字后多出一个p标签包裹

### ISSUE THREAD

**Issue by Ele-Lee** [wangeditor-team/wangEditor#2439]
## bug 描述
在文本最后复制文本，会追加<p>标签包裹，导致写多几个字就换行。
复现条件：文本最后一个字是被b标签(其他标签也复现)包住
*请输入内容……*
![image](https://user-images.githubusercontent.com/29876945/98814301-71d24c80-2460-11eb-849d-b13cd715c2d4.png)
![image](https://user-images.githubusercontent.com/29876945/98814302-71d24c80-2460-11eb-9d45-c4c604bf4d0a.png)
然后文字后面复制一段字进去
![image](https://user-images.githubusercontent.com/29876945/98814514-beb62300-2460-11eb-93f6-42b85481242d.png)
![image](https://user-images.githubusercontent.com/29876945/98814492-b65de800-2460-11eb-8af9-92cde84e3793.png)

## 你预期的样子是？
讲道理不是应该在原先p标签里面追加内容吗

## wangEditor 版本
4.3.0
谷歌浏览器 86版本
MAC电脑

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
 区域里面重新输入一些文字
- 步骤二
对最后的字加粗
- 步骤三
然后去别的地方复制文本,直接粘贴

**Comment by wangfupeng1988** [comment]
这里加载不了 issue 的图片，你可以把相关的代码，以及编辑器获取的 html ，返回到这里。

**Comment by Ele-Lee** [comment]
@wangfupeng1988 
步骤二之后的html结构：
```js
<div contenteditable="true" style="width:100%; height:100%; min-height:160px;" class="w-e-text" id="text-elem5946439049699932"><p>普通文字<b>加粗</b></p></div>
```
步骤三(点一下编辑框，commend+v复制)之后
```js
<div contenteditable="true" style="width:100%; height:100%; min-height:160px;" class="w-e-text" id="text-elem5946439049699932"> <p>普通文字<b>加粗</b></p><p>复制的长长长长长长长长长长长长长长长长长长长长长长长长长长文本</p></div>
```

**Comment by wangfupeng1988** [comment]
你说：官网不能复现 bug  ？
那我要在什么环境下复现？

**Comment by UltramanWeiLai** [comment]
我觉得，你得考虑一下，你复制过来的内容，是否它就是一个单独的段落(<p>)。
这个问题我也没有复现

**Comment by Ele-Lee** [comment]
抱歉之前没说清，以为无关系。
我有多个编辑器，假设有两个A和B，我从A复制了一些文字到B编辑器。B的最后一个字如果被内联标签包裹着，就会出现这种情况，比如 
```js
<p>我是B编辑器<font>最后一个字</font></p>
```
如果没有这个font标签就没事
。有什么办法能看到我复制的载体吗

**Comment by Ele-Lee** [comment]
![image](https://user-images.githubusercontent.com/29876945/99143046-75024e00-2695-11eb-89aa-208e56fede2b.png)
```js
<div contenteditable="true" style="width:100%; height:100%; min-height:160px;" class="w-e-text" id="text-elem4025199953324501">
<p><span style="color: rgba(5, 12, 50, 0.85)">这里开</span></p>
<p>-ab&amp;ved=0ahUKEwijuc27pIHtAhWMA4gKHSBSDKkQ4dUDCA0&amp;uact=5</p>
</div>
```

事实上，我试过从浏览器复制链接到B编辑器，也是一样。所以一开始觉得无关系。具体怎么样的复现条件，我排查下来有点麻烦，很多变量值得怀疑。

**Comment by UltramanWeiLai** [comment]
怎么说，还真是巧了，我复现的时候刚好用的是多编辑器示例。。
![image](https://user-images.githubusercontent.com/23336585/99150593-a9dfc680-26d0-11eb-95ef-a19802a38b5c.png)
说真的八成就是你复制的本身就是一个段落，至于如何去看，我记得有一个 自定义处理粘贴的回调 你可以去文档里面找找

**Comment by Ele-Lee** [comment]
@UltramanWeiLai 这也不能综合解释两点：1. 最后一个字是被标签font标签(其他标签也是一样)才会复现；2. 为什么我复制浏览器链接上的字符也可以复现，浏览器输入框是纯文本性质的

**Comment by UltramanWeiLai** [comment]
第一个问题，你要看到 我的富文本编辑器2 是被斜体和加粗包裹的肯定是有  b 或者 font 的
![image](https://user-images.githubusercontent.com/23336585/99151512-b1a26980-26d6-11eb-8b87-f611fe6bc964.png)

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/99151534-ed3d3380-26d6-11eb-9c9b-cd58fb460206.png)

**Comment by Ele-Lee** [comment]
我渲染一个编辑器也是这种问题。
![image](https://user-images.githubusercontent.com/29876945/99152214-558e1400-26db-11eb-94c7-f50592ba014e.png)

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/99152307-01376400-26dc-11eb-87ee-f7fbea3855ce.png)

**Comment by Ele-Lee** [comment]
我是来提BUG的。
![image](https://user-images.githubusercontent.com/29876945/99152479-0a750080-26dd-11eb-9079-2a0c97539692.png)
给我的文件名字字符加了包裹标签。
我之前也试过 在 自定义里面 返回`pasteStr.replace(/\<\/?p\>/g, '')`，但是已经忘了为什么不这样做，引发另外问题

**Comment by UltramanWeiLai** [comment]
粘贴的内容是浏览器自身的效果。
所以说我一直在说，可能是粘贴的内容本身就是一个段落。
这种你只能自定义粘贴过滤的逻辑，我们总不可能说，去修改浏览器的行为吧。

**Comment by Ele-Lee** [comment]
@UltramanWeiLai 你是实习生吗？你真的是这个项目开发者吗？能换个带脑子的人来说话吗？怎么才能做到说出，加复制内容包裹了p标签是，我复制个文件名系统给我带上p标签，我还用玩？你看自己项目代码没有

**Comment by Ele-Lee** [comment]
问题根本还有一个，为什么粘贴的内容不会被塞进原本的P标签里面

**Comment by UltramanWeiLai** [comment]
真是把我给气笑了，林子大了什么鸟都有。
1. 你说的任何一种情况我都没有 **复现**
2. 而且我说的是什么 **粘贴的内容是系统或者浏览器自身的效果**
3. 我只是说 **可能** 可能是什么意思？？？难不成我还得给你一一排查干净给你解决掉？我只是说了一种可能性。
我忽然明白为什么官网无法复现这个问题，而且我们也不能复现，鬼知道是不是你做些什么不带脑子的事情。
还有放尊重点，我们没有义务给你解决问题。

你说的 bug 我们无法复现，请排查好你问题，或者给我们一个可以复现的方案。

**Comment by Ele-Lee** [comment]
@UltramanWeiLai 我对针对你个人的鲁莽言语表示抱歉，真的冲动了。

https://github.com/wangeditor-team/wangEditor/blob/master/src/text/paste/paste-event.ts#L48
我也希望你真清楚这部分源码再回复问题，不要头铁。
另外，我已经讲了几次，链接输入框和复制，铁定的纯文本，还纠结我复制的就是段落文本，真的是对牛弹琴。
我也不想追踪下去源码哪里做了去P标签的融合操作，这问题不影响我业务。

**Comment by wangfupeng1988** [comment]
> @UltramanWeiLai 你是实习生吗？你真的是这个项目开发者吗？能换个带脑子的人来说话吗？怎么才能做到说出，我复制个文件名是一个段落，系统给我带上p标签，我还用玩？你看过这个项目代码没有

@Ele-Lee 作为该软件作者，我表态一下，再有这种无聊的话语，我们将立刻终止该 issue 的回复并 close 。
我们是业余时间做的开源软件，免费开源的，独立的第三方。我们并不是乙方。

**Comment by Ele-Lee** [comment]
@wangfupeng1988 是我的不成熟和错误，今天白天把生活情绪带了进来，打扰了，可关。

**Comment by UltramanWeiLai** [comment]
@Ele-Lee 
知道我为什么会说 系统或浏览器行为 吗？
document.execCommand 命令每个浏览器实现可能都不一样。
而且确确实实，我没有复现出来，我甚至是跟着命令走的，这里插入的的确是 <p>text</p> 但是 insertHTML 命令确确实实是在当前段落(p)里面进行追加的。另外我觉得你也需要考虑一下，为什么官网无法复现这个问题(代码逻辑都是一样，不存在说 官网 demo 能再段落内复制，而你本地不行吧？)。
这里我再说明一下，我只能根据你说的情况去做同样的操作，但毕竟我没有复现，无法究根结底的去追踪，我只能根据情况去分析，给你提供意见和思路，你说我头铁没有搞清楚这部分源码，你自己又去做过相关的了解和测试？
![image](https://user-images.githubusercontent.com/23336585/99186114-fa1a5f80-2788-11eb-9d32-15c2edd4ff80.png)

**Comment by Ele-Lee** [comment]
w-e-text类下面的标签css文件 设了 "display: inline-block"。p的display样式造成。

https://stackoverflow.com/questions/60804360/insert-span-in-contenteditable-with-document-execcommandinserthtml

**Comment by wangfupeng1988** [comment]
我也了解 execCommand 是非标准的。不过目前除了 execCommand ，暂时没有低成本、稳定的替代方案。
