### ISSUE TITLE
无法粘贴来自企业微信的聊天内容

### ISSUE THREAD

**Issue by LiuYuLu** [wangeditor-team/wangEditor#2441]
## bug 描述
- 使用windows 10系统
- 企业微信版本：3.0.31.2988
- 在企业微信中，复制一行聊天内容后，无法在编辑器中ctrl+v粘贴，右击选择“粘贴为纯文本”可以粘贴。
复制多行聊天记录后，第一条聊天记录丢失，剩下的可以粘贴在编辑器中。

## 你预期的样子是？

预期能正常粘贴文本，多行粘贴不丢失数据

## 浏览器及版本号

谷歌浏览器 86.0.622.63  (64 位)

## wangEditor 版本

4.2.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 1. 在企业微信中，复制一行聊天内容
- 2. 在编辑器中ctrl+v粘贴

**Comment by LiuYuLu** [comment]
额外补充，操作在V3版本中是正常的

**Comment by wangfupeng1988** [comment]
我们没有企业微信，没法去执行你的复现步骤。

你看下普通微信，是否能复现？

**Comment by LiuYuLu** [comment]
> 我们没有企业微信，没法去执行你的复现步骤。
> 
> 你看下普通微信，是否能复现？

普通微信复制是正常的，没有出现这个问题。如果开发团队没有企业微信，我该怎么提供信息才能解决这个问题呢？

**Comment by jackyTo168** [comment]
同样有这样的问题，贴一下源码断点图，内容有 xxx 注释的标签就被清空掉了

**Comment by jackyTo168** [comment]
> 我们没有企业微信，没法去执行你的复现步骤。
> 
> 你看下普通微信，是否能复现？

我在官网测试 贴一下源码断点图，内容有 \<\!--StartFragment--\>\xxx\<\!--EndFragment--\>\ 注释的标签就被清空掉了 ，如下图：

<img width="960" alt="图一" src="https://user-images.githubusercontent.com/11623216/100403021-abc66400-3098-11eb-8f87-e92c98b69212.png">
<img width="960" alt="图三" src="https://user-images.githubusercontent.com/11623216/100403223-4626a780-3099-11eb-8c0f-05e6fe4dda4c.png">

**Comment by jackyTo168** [comment]
> 我们没有企业微信，没法去执行你的复现步骤。
> 
> 你看下普通微信，是否能复现？

@wangfupeng1988

**Comment by 86driver** [comment]
![image](https://user-images.githubusercontent.com/38236070/110322691-7bef0b00-804e-11eb-87e0-74b2e765898d.png)
  我尝试在index.html里面 这样去复现场景， 但是去粘贴的时候能正常粘贴出来 - -

**Comment by 86driver** [comment]
我又查了一下之前的提交记录，  这个地方是不是被非团队成员提交的pr修复了啊

他这里的代码跟我们现在master上面的代码已经不一样了。

具体可以看一下  这个pr  https://github.com/wangeditor-team/wangEditor/pull/2535

对应的issue是这个： https://github.com/wangeditor-team/wangEditor/issues/2530

**Comment by 86driver** [comment]
@LiuYuLu   你访问现在的官网试一下看看还会不会存在这个问题

**Comment by UltramanWeiLai** [comment]
该 bug 已经修复
该 issue 暂且关闭
如有问题，可以重新提交 issue

**Comment by SmileAjh** [comment]
还是有这个问题呃，企业微信复制第一条会丢失。@UltramanWeiLai @wangfupeng1988 wangfupeng1988
