### ISSUE TITLE
鼠标在输入区右下角拖动可灵活改变输入区大小

### ISSUE THREAD

**Issue by changxinjie** [wangeditor-team/wangEditor#2442]
## 功能描述

鼠标在输入区右下角拖动可灵活改变输入区大小

## 提炼几个功能点

- 鼠标在输入区右下角拖动可灵活改变输入区大小

## 可参考的案例

github.com issue 编辑器

**Comment by wangfupeng1988** [comment]
可以通过这个，自己实现。
http://www.wangeditor.com/doc/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/03-%E8%8F%9C%E5%8D%95%E5%92%8C%E7%BC%96%E8%BE%91%E5%8C%BA%E5%9F%9F%E5%88%86%E7%A6%BB.html
