### ISSUE TITLE
建议可以添加自定义组件，或者有什么好的方案解决

### ISSUE THREAD

**Issue by jeromehan** [wangeditor-team/wangEditor#2446]
## 功能描述

*添加内容区自定义组件

## 提炼几个功能点

- 插入自定义视频组件
- 插入自定义音频组件

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
https://www.yuque.com

**Comment by UltramanWeiLai** [comment]
请看文档，文档里面明确的提供了如何去自定义菜单
