### ISSUE TITLE
在动态构建多个富文本编辑器之后，onfocus和onblur事件只对最后一个创建的编辑器有效果。

### ISSUE THREAD

**Issue by Aquarius-IT** [wangeditor-team/wangEditor#2447]
## 问题描述

*在动态构建多个富文本编辑器之后，onfocus和onblur事件只对最后一个创建的编辑器有效果。之前创建的就没有事件效果了*
但是，如果不是动态创建的，页面初始化的时候create的多个编辑器就没有问题

## wangEditor 版本

*V4*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
添加div。里面的id是动态赋值的。我这里为了精简，直接写成了editor5Toolbar和editor5Text
$("#timulist").append("<div><div id="editor5Toolbar"> </div><div id="editor5Text"> </div></div>")
		
- 步骤二
循环执行以下语句创建编辑器
editorVarArray[index - 1] = new E('#editor' + index + 'Toolbar', '#editor' + index + 'Text');
		editorVarArray[index - 1].config.onfocus = function (newHtml) {
			$("#editor" + index + " div[id^='toolbar-elem']").show();
			$("#editor" + index + "Text").height("100px");
		}
		editorVarArray[index - 1].config.onblur = function (newHtml) {
			$("#editor" + index + " div[id^='toolbar-elem']").hide();
			$("#editor" + index + "Text").height("");
		}
		// editorVarArray[index - 1].config.height = 100;
		editorVarArray[index - 1].create();

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/99142265-53519880-268e-11eb-9ba9-ceabe9faac18.png)
我没有发现这种问题，多个编辑器的事件都是独立的

**Comment by UltramanWeiLai** [comment]
由于长期无人回复，暂且关闭该问题。
