### ISSUE TITLE
placeholder 无法显示

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/wangEditor#2449]
## bug 描述
editor.config.zIndex 设置为 'auto' 时, placeholder 无法显示 ( z-index 文档上未注明 不能设置 为 'auto' )

## 你预期的样子是？
placeholder 正常显示

## 浏览器及版本号
chrome 86

## wangEditor 版本
4.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 
editor.config.zIndex = 'auto'
editor.create()
- 步骤二
查看 placeholder

**Comment by UltramanWeiLai** [comment]
这个是 css 的特性
当其z-index值不是 auto 的时候，会创建层叠上下文。

**Comment by wangfupeng1988** [comment]
zIndex 不能设置为 auto ，按照文档来吧。
