### ISSUE TITLE
设置不自动focus，首次加载富文本，点击上传图片图标没反应

### ISSUE THREAD

**Issue by justinluhui** [wangeditor-team/wangEditor#2450]
## bug 描述
vue:
设置不自动focus:
editor.config.focus = false; 

富文本首次加载的时候，直接点工具栏上的上传图片图标，一点反应都没有，工具栏选择图片的的那个下拉没弹出来~

必须手动focus一下富文本编辑器，再点工具栏的上传图片图标，图片选择的下拉才能弹出来。

只要focus过一次，后面就不会有弹不出来的情况出现

如果editor.config.focus设置为true或者使用默认就不会有这个问题

## 你预期的样子是？

不管我有没有focus过富文本编辑器，工具栏上，点击上传图片图标，上传图片的下拉都能正常出现

## 浏览器及版本号

chrome 版本 86.0.4240.183（正式版本） (x86_64)

## wangEditor 版本

V4.1.0

## 官网能否复现该 bug ？

要先设置autofucus为false，没法操作

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 设置editor.config.focus = false; 
- 步骤二 刷新页面，不用focus富文本编辑器，点击上传图片按钮，一点反应都没有，选择图片的下拉没出现 （备注：图片上传使用的是自定义的方法editor.configcustomUploadImg）

**Comment by UltramanWeiLai** [comment]
当设置不默认聚焦的时候，编辑区域是没有选区的。
没有选区我们所有的按钮操作都是会直接 return 的。
因为没有选区，那么就等于没有可操作内容。
你考虑一个问题，如果这时候点上传图片的话，图片要插入在那里？当然你会说直接插入编辑区域就可以了，那么这种情况是没有默认内容的，如果后呢？我们又该如何去做？

**Comment by UltramanWeiLai** [comment]
由于长期无人回复，暂且关闭该问题。

**Comment by justinluhui** [comment]
> 当设置不默认聚焦的时候，编辑区域是没有选区的。
> 没有选区我们所有的按钮操作都是会直接 return 的。
> 因为没有选区，那么就等于没有可操作内容。
> 你考虑一个问题，如果这时候点上传图片的话，图片要插入在那里？当然你会说直接插入编辑区域就可以了，那么这种情况是没有默认内容的，如果有呢，我们又该如何去做？

这个我觉得是BUG噢  有内容的时候 默认focus到哪里呢？   这个自动focus和人工点一下效果是一样的 默认应该追加到结尾

**Comment by justinluhui** [comment]
> 由于长期无人回复，暂且关闭该问题。



> 当设置不默认聚焦的时候，编辑区域是没有选区的。
> 没有选区我们所有的按钮操作都是会直接 return 的。
> 因为没有选区，那么就等于没有可操作内容。
> 你考虑一个问题，如果这时候点上传图片的话，图片要插入在那里？当然你会说直接插入编辑区域就可以了，那么这种情况是没有默认内容的，如果有呢，我们又该如何去做？

其实追加到什么位置，跟默认focus是一样的就对了，  默认focus的时候我焦点移开，这时候上传会追加到末尾
