### ISSUE TITLE
是否可以自定义实现待办清单的功能

### ISSUE THREAD

**Issue by ManyMeanings** [wangeditor-team/wangEditor#2453]
## 问题描述

*是否可以自定义实现待办清单的功能*

## wangEditor 版本

*4.3.0*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 添加新菜单按钮
- 实现待办清单（checklist）

**Comment by wangfupeng1988** [comment]
该功能以受理，并已安排开发了。不过新功能开发，花费时间稍微长一点。请耐心等待。
