### ISSUE TITLE
插入网络视频的时候没有相关回调

### ISSUE THREAD

**Issue by tudou0099** [wangeditor-team/wangEditor#2456]
## 问题描述

*插入网络视频的时候可以输入xss攻击，但是查找文档没有找到相关插入网络视频相关的回调*

## wangEditor 版本

*^4.3.0*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 插入<img src='1' onerror='javascript:alert(1);' />
- 步骤二 onerror 如期执行

**Comment by tudou0099** [comment]
步骤一：插入`<img src='1' onerror='javascript:alert(1);' />`

**Comment by UltramanWeiLai** [comment]
该功能已经添加，更新版本后即可使用，使用方法见文档，如有问题可以重新提交一个 issue
