### ISSUE TITLE
通过editor.config.onchange回调函数获取编辑器里的内容时，会将最后面的空行删除

### ISSUE THREAD

**Issue by xzf123456** [wangeditor-team/wangEditor#2462]
## bug 描述

*通过editor.config.onchange回调函数获取编辑器里的内容时，会将最后面的空行删除，普通文章还可以接受，如果文章末尾是插入的代码段，通过editor.config.onchange获取内容并保存后，最后一行空行丢失，再次修改时无法在文章末尾添加新内容*

## 你预期的样子是？

*通过editor.config.onchange回调函数获取编辑器里的内容时，不会将末尾的空行删除*

## 浏览器及版本号

*谷歌浏览器 85.0.4183.121*

## wangEditor 版本

*V4*

## 官网能否复现该 bug ？

没有获取内容的地方，不知道

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一   在编辑器输入内容并敲回车（末尾空行数大于等于1行）
- 步骤二   使用editor.config.onchange获取编辑器的内容，并输出获取的内容
- 步骤三   仔细对比末尾空行数少一个

**Comment by UltramanWeiLai** [comment]
可以考虑用 追加 editor.txt.append('<p>追加的内容</p>') 插入一个空行

**Comment by xzf123456** [comment]
> 可以考虑用 追加 editor.txt.append('...') 插入一个空行

我强行给他追加的话，那岂不是如果文章本身末尾没有空行也会多一个空行？

**Comment by UltramanWeiLai** [comment]
> > 可以考虑用 追加 editor.txt.append('...') 插入一个空行
> 
> 我强行给他追加的话，那岂不是如果文章本身末尾没有空行也会多一个空行？

看你自己呀，比如 查询一下 最末尾结尾的标签是啥，如果属于需要空行的加，不需要的不加不就可以了？

**Comment by xzf123456** [comment]
> > > 可以考虑用 追加 editor.txt.append('...') 插入一个空行
> > 
> > 
> > 我强行给他追加的话，那岂不是如果文章本身末尾没有空行也会多一个空行？
> 
> 看你自己呀，比如 查询一下 最末尾结尾的标签是啥，如果属于需要空行的加，不需要的不加不就可以了？

所以这不是一个bug吗？

**Comment by UltramanWeiLai** [comment]
这倒不是，只不过你说的问题我这里没有复现，我只是告诉你一个解决方法而已
![image](https://user-images.githubusercontent.com/23336585/99473198-0ec34700-2985-11eb-925f-340718740c50.png)

**Comment by xzf123456** [comment]
> 这倒不是，只不过你说的问题我这里没有复现，我只是告诉你一个解决方法而已
> ![image](https://user-images.githubusercontent.com/23336585/99473198-0ec34700-2985-11eb-925f-340718740c50.png)

行，我知道了，我也就是给你们提一下
