### ISSUE TITLE
image.d.ts里面别名报错了，劳烦尽快修复下，万分感谢

### ISSUE THREAD

**Issue by RedScarf007** [wangeditor-team/wangEditor#2463]
![image](https://user-images.githubusercontent.com/28618983/99473239-26023480-2985-11eb-814b-7bf18e8e5d3b.png)
![image](https://user-images.githubusercontent.com/28618983/99473249-2d294280-2985-11eb-89cb-abad8a22f363.png)

环境是react(^16.10.2)和typescript(^3.6.4)

**Comment by wangfupeng1988** [comment]
我在 https://github.com/wangeditor-team/wangEditor-with-ts 没有复现你的问题，请详细描述复现的步骤。

请按照 issue 模板，再重新提交一个 issue 。
这个 issue 不予受理，关闭。
