### ISSUE TITLE
火狐浏览器经过多次删除内容，重新添加内容 文章内容没有被p标签包裹

### ISSUE THREAD

**Issue by jeromehan** [wangeditor-team/wangEditor#2469]
## bug 描述

火狐浏览器文章内容没有被p标签包裹 而是<br>标签之前输入内容

## 你预期的样子是？

被p标签包裹

## 浏览器及版本号

火狐浏览器 81.0.2 (64 位)

## wangEditor 版本

最新版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
1.没有输入正文时直接ctrl+A删除 
2.然后重新添加

如图

![image](https://user-images.githubusercontent.com/19773879/99494739-8193e880-29ac-11eb-9341-83a915108492.png)
![image](https://user-images.githubusercontent.com/19773879/99494760-88baf680-29ac-11eb-81a5-444887814e73.png)
继续编辑没有被标签包裹的变成这样了
![image](https://user-images.githubusercontent.com/19773879/99496899-0e8c7100-29b0-11eb-8879-85f223df8198.png)

**Comment by wangfupeng1988** [comment]
同时还发现，火狐浏览器中，全选删除，会有一个 js 报错
![image](https://user-images.githubusercontent.com/9583120/99607069-00892f80-2a46-11eb-9232-5102a8453167.png)

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/pull/2473
https://github.com/wangeditor-team/wangEditor/pull/2474
这俩 pr 已合并到 dev ，待发布
