### ISSUE TITLE
输入内容，提示不会消失

### ISSUE THREAD

**Issue by comxza** [wangeditor-team/wangEditor#2470]
![image](https://user-images.githubusercontent.com/21981010/99504517-9aa39600-29ba-11eb-8f40-40f19aebc1dd.png)

<div id="content"></div>
`<script type="text/javascript" src="//unpkg.com/wangeditor/dist/wangEditor.js"></script>
` const E = window.wangEditor
    const editor = new E('#content')
    editor.create()

**Comment by wangfupeng1988** [comment]
请按照 issue 模板，重新提交一个。
