### ISSUE TITLE
splitLine和code操作会报错

### ISSUE THREAD

**Issue by howezhong** [wangeditor-team/wangEditor#2472]
## bug 描述

1. 点击分割线splitLine会报错 Cannot read property 'getNodeName' of undefined，不过分割线能插入成功，之后点击此线也会报错
![image](https://user-images.githubusercontent.com/28563223/99512919-0428a200-29c5-11eb-8824-35f077e196b9.png)
2.输入的内容进行全选然后点击code会报 Cannot read property 'getNodeName' of undefined
![image](https://user-images.githubusercontent.com/28563223/99513337-7e592680-29c5-11eb-98c6-2b49591181a1.png)

## 浏览器及版本号

正在更新 Google Chrome
版本 85.0.4183.102（正式版本）（64 位）
## wangEditor 版本

4.4.1

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

问题一：
- 步骤一
直接点击 splitLine
- 步骤二
再点击生成的线条，或者鼠标随机移动要触碰到此线
问题二：
- 步骤一
输入多行内容
- 步骤二
全选，然后点击code

**Comment by wangfupeng1988** [comment]
抱歉，我们现在打算排查这个问题，但是用最新版本 v4.5.3 未覆盖该 bug 。

麻烦你再试一试，看能否在官网复现？
如果能复现的话，可以再提交一个新 issue 。
这个先暂时关闭了。
