### ISSUE TITLE
使用编辑器输入文字提示词不消失

### ISSUE THREAD

**Issue by comxza** [wangeditor-team/wangEditor#2476]
## 问题描述
在360急速浏览器或者谷歌浏览器中使用编辑器，在编辑器里面输入内容文字提示词不消失

*请输入遇到的问题...*
我这边是用的是laiyui+element两者结合，

vue版本是2.6.9
element-ui版本是2.14.0
![image](https://user-images.githubusercontent.com/21981010/99614107-cb83d980-2a53-11eb-93c7-e2fcbab8ef30.png)

## wangEditor 版本
V3-V4
*请输入内容……*
任何字符都不会吧提示词处理掉

## 是否查阅了文档 ？
是
（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤
`<script src="/admin/js/vue@2.6.9/vue.min.js"></script>`
`<script src="/admin/js/element-ui@2.14.0/index.js"></script>`
`<script type="text/javascript" src="//unpkg.com/wangeditor@4.1.0/dist/wangEditor.min.js"></script>`
我试过在
html中直接使用
`<script type="text/javascript">
    const E = window.wangEditor
    const editor = new E('#div1')
    // 或者 const editor = new E( document.getElementById('div1') )
    editor.create()
</script>`
也试过在Vue中使用
`created() {
                let editor = new wangEditor(`#content`)
                // 配置 onchange 回调函数，将数据同步到 vue 中
                editor.config.placeholder = '自定义 placeholder 提示文字'
                editor.config.onchange = (newHtml) => {
                    this.editorData = newHtml
                }
                // 创建编辑器
                editor.create()
                this.editor = editor
            },`
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by comxza** [comment]
以下代码让问题复现
`<!DOCTYPE html>
<html>
<head>
	<title>html+vue</title>
</head>
<body>
<div id="app">
		<div id="content"></div>
</div>
</body>
<script src="https://cdn.bootcdn.net/ajax/libs/vue/2.6.9/vue.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/element-ui/2.14.0/index.js"></script>
<script type="text/javascript" src="http://unpkg.com/wangeditor@4.1.0/dist/wangEditor.min.js"></script>
<script type="text/javascript">
    const E = window.wangEditor
    const editor = new E('#content')
    // 或者 const editor = new E( document.getElementById('div1') )
    editor.create()

     var app = new Vue({
            el:'#app',
            data:{}
        })
</script>

</html>`

**Comment by clinfc** [comment]
请使用最新版本，如果最新版本还有该问题，欢迎提交 issues
