### ISSUE TITLE
版本升级为V4.4.2后，上传图片配置uploadFileName，请求时uploadFileName异常导致上传图片失败

### ISSUE THREAD

**Issue by liangzq1** [wangeditor-team/wangEditor#2479]
## bug 描述

版本升级为V4.4.2后，上传图片配置uploadFileName，请求时uploadFileName异常导致上传图片失败

## 你预期的样子是？

上传图片

## 浏览器及版本号

Google Chrome 86.0.4240.193

## wangEditor 版本

V4.4.2

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 步骤一
` this.editor.config.pasteIgnoreImg = true;
    // 配置服务器端地址 upload:上传图片地址
    this.editor.config.uploadImgServer =
      "/test/activities/feiyiban-attach-file/uploadImgToWeb";
    this.editor.config.uploadImgHeaders = {
      emsToken: store.state.user.token, // 设置请求头
    };
    this.editor.config.uploadFileName = "multipartFile"; // formdata中的name属性`
- 步骤二
请求接口时FormData参数名变成 multipartFile5890718707403853
![微信图片_20201119144106](https://user-images.githubusercontent.com/45655539/99630696-50331f80-2a75-11eb-81b7-6f4bbfafb648.png)

- 步骤三

**Comment by gaosheng1991** [comment]
回退老版本解决，这个问题我也遇到了

**Comment by liangzq1** [comment]
> 回退老版本解决，这个问题我也遇到了

具体是哪个版本的问题不知道了，我回退到4.2.0版本可以了，不想回退到V3版本的，V3的版本要手动过滤粘贴过来的标签和样式

**Comment by gaosheng1991** [comment]
https://unpkg.com/browse/wangeditor@4.0.6/dist/wangEditor.min.js 我用的4.06

**Comment by UltramanWeiLai** [comment]
这是修改了某个 bug 照成的问题，这里我们会商讨一下具体会如何处理。

**Comment by wangfupeng1988** [comment]
这个问题是我的锅，抱歉大家。
今天一定紧急高优处理！

**Comment by zhuangbb** [comment]
> 这个问题是我的锅，抱歉大家。
> 今天一定紧急高优处理！

可以先降低到某一个版本用着先吗

**Comment by zhuangbb** [comment]
> https://unpkg.com/browse/wangeditor@4.0.6/dist/wangEditor.min.js 我用的4.06

4.0.6？

**Comment by liangzq1** [comment]
> > https://unpkg.com/browse/wangeditor@4.0.6/dist/wangEditor.min.js 我用的4.06
> 
> 4.0.6？

我降到4.2.0，可以正常上传图片

**Comment by gaosheng1991** [comment]
> > https://unpkg.com/browse/wangeditor@4.0.6/dist/wangEditor.min.js 我用的4.06
> 
> 4.0.6？
@zhuangbb 
我用的是 4.4.2 有这个问题 这个是我发出来的 4.0.6 可以解决问题的版本 少发了几个字 让你误解了

**Comment by wangfupeng1988** [comment]
已修改，请升级到 v4.5.0
再次表示抱歉，是我之前大意了
