### ISSUE TITLE
表格数据无法回写到富文本编辑器中

### ISSUE THREAD

**Issue by LLstar** [wangeditor-team/wangEditor#2480]
## bug 描述

保存后的富文本内容中包含表格，但是表格的数据无法回显到富文本中

## 你预期的样子是？

现在保存的表格内容

## wangEditor 版本

"wangeditor": "^4.3.0"

**Comment by hahaaha** [comment]
可以描述的更清楚点么。。。回显的富文本是指什么。。。还有那个保存后的格式能贴出来么

**Comment by hahaaha** [comment]
请按 issue 模板格式提交
