### ISSUE TITLE
表格数据不显示

### ISSUE THREAD

**Issue by LLstar** [wangeditor-team/wangEditor#2482]
## bug 描述

在富文本编辑器中插入表格数据，利用editor.txt.setJSON()设置内容只显示一条横线

![](https://i.loli.net/2020/11/19/hSUYcaqytPJgC8R.png)

## 你预期的样子是？

表格内容正常回显在富文本编辑器中

## wangEditor 版本

^4.3.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：利用editor.txt.getJSON()获取得到的表格内容
- 步骤二：将步骤一中获取到的表格内容利用editor.txt.setJSON()的方式回写到富文本编辑器中，就会出现上述问题

**Comment by UltramanWeiLai** [comment]
已复现已受理

**Comment by wangfupeng1988** [comment]
已修复，升级最新版本
