### ISSUE TITLE
升级v4.4.2后报错TypeError: this.config.compatibleMode is not a function"

### ISSUE THREAD

**Issue by sunliyun** [wangeditor-team/wangEditor#2483]
## bug 描述

升级v4.4.2后报错TypeError: this.config.compatibleMode is not a function"

## 你预期的样子是？

如何解决这个问题

## 浏览器及版本号

目前流行的浏览器即可

## wangEditor 版本

v4.4.2

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请描述复现步骤。否则 issue 将关闭。

**Comment by clinfc** [comment]
这个应该跟版本没关系，你是否进行了正常的配置，未正常配置造成这个问题不奇怪。

务必要认真的查阅文档
![image](https://user-images.githubusercontent.com/39868400/99748825-3696e400-2b18-11eb-9d5e-d6e3b7d47ec3.png)

**Comment by sunliyun** [comment]
我只是将版本从v3升级到v4，然后将editor.customConfig 改为 editor.config，重启项目就报上面的错误了

**Comment by clinfc** [comment]
我只想说，截图把代码贴出来就那么的难吗？

**Comment by sunliyun** [comment]
![image](https://user-images.githubusercontent.com/22999724/99749187-f421d700-2b18-11eb-911e-36a78d52d647.png)

**Comment by clinfc** [comment]
你自己的写法问题吧，你写成 `this.editor.config = {}` 的形式不就是把内置的配置全部干掉了吗？你要集中一次写不如写成 
```js
Object.assign(this.editor.config, {
    pasteTextHandle: function (content) {},
    lang: ...
})
```

**Comment by sunliyun** [comment]
好的 我试一下

**Comment by clinfc** [comment]
解决了回复下，我好关闭 issues

**Comment by sunliyun** [comment]
好了
