### ISSUE TITLE
未编辑任何内容, 直接点击 undo 出现报错, 

### ISSUE THREAD

**Issue by kkyyqq** [wangeditor-team/wangEditor#2486]
## bug 描述

  react项目中封装使用编辑器, 配置的菜单包括 "quote, undo, redo", 编辑器未输入任何内容的情况下, 直接点击 "撤销" 按钮, 出现报错: TypeError: Cannot read property 'getNodeName' of undefined
Quote.tryChangeActive
src/menus/quote/index.ts:78

![image](https://user-images.githubusercontent.com/49714942/99755315-70221c00-2b25-11eb-9a92-430c7e923c70.png)

  去掉 "quote"菜单 后, 编辑器未输入任何内容的情况下, 直接点击 "撤销" 按钮, 不会出现报错.

## 你预期的样子是？

  预期在上述情况下, 点击撤销, 不应该出现报错;

## 浏览器及版本号

谷歌: 版本 83.0.4103.61（正式版本）;
火狐;

## wangEditor 版本

^4.4.1

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一   react项目中封装使用编辑器, 配置的菜单包括 "quote, undo, redo";
- 步骤二  编辑器未输入任何内容的情况下, 直接点击 "撤销" 按钮, 出现报错;
- 步骤三

**Comment by hahaaha** [comment]
更新到最新版本可以解决这个问题
