### ISSUE TITLE
编辑器回显内容消失

### ISSUE THREAD

**Issue by zhuangbb** [wangeditor-team/wangEditor#2487]
## bug 描述
添加图片 文字  保存接口
重新进去编辑页面   内容回显 
在当前页面刷新浏览器   回显内容失败   后台有数据返回

## 你预期的样子是？

在当前页面刷新浏览器   回显内容

## 浏览器及版本号

谷歌  版本 86.0.4240.198（正式版本） (x86_64)

## wangEditor 版本

2.0.6

## 官网能否复现该 bug ？
不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
editor.config.uploadImgServer = this.uploadUrl;
    editor.config.uploadFileName = this.uploadFileNames;
    editor.config.uploadImgParams = this.params;
配置编辑器
- 步骤二
打开浏览器  添加图片  文字  信息保存  
- 步骤三
重新进入详情编辑   当前页刷新浏览器  内容消失

**Comment by blackhu0804** [comment]
建议使用最新版本，老版本暂不维护
