### ISSUE TITLE
【安全漏洞】插入链接功能存在存储型XSS

### ISSUE THREAD

**Issue by 5Laos** [wangeditor-team/wangEditor#2488]
## bug 描述

插入链接功能过滤不全，可以直接插入JS代码，可以用来进行Cookie盗取，键盘记录等操作

## 你预期的样子是？

过滤以及实体化特殊字符，对输入的链接格式进行校验。

## 浏览器及版本号

能执行JS的浏览器都可以触发。

## wangEditor 版本

v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
插入链接，在URL处输入：javascript:alert(document.cookie)
![image](https://user-images.githubusercontent.com/49939122/99771114-8c34b600-2b43-11eb-81ca-3f55ae7c133b.png)

- 步骤二
点击触发脚本
![image](https://user-images.githubusercontent.com/49939122/99771248-c2723580-2b43-11eb-8eed-8178e12b2502.png)

- 步骤三
当前站点的Cookie被获取
![image](https://user-images.githubusercontent.com/49939122/99771318-e2095e00-2b43-11eb-9934-08d983a7b9ff.png)

**Comment by yu530feng** [comment]
这个看文档中的常见问题

**Comment by clinfc** [comment]
链接的校验提供了对应的过滤 api，详情查看 [插入链接的校验](http://www.wangeditor.com/doc/pages/05-%E5%86%85%E5%AE%B9%E6%A0%A1%E9%AA%8C/01-%E6%8F%92%E5%85%A5%E9%93%BE%E6%8E%A5%E7%9A%84%E6%A0%A1%E9%AA%8C.html)
