### ISSUE TITLE
自定义一个图片上传组件上传图片,只有自带的图片上传菜单显示的时候才能调整图片大小

### ISSUE THREAD

**Issue by gonghaojin** [wangeditor-team/wangEditor#2492]
![图片](https://user-images.githubusercontent.com/17883128/99786919-08d28f00-2b5a-11eb-999c-de715dc05224.png)

**Comment by clinfc** [comment]
这并不是一个 bug，从图中我们可以看到图片相关的操作都绑定在图片菜单下面，既然不需要这个 菜单，其相关的操作肯定不会被初始化
![image](https://user-images.githubusercontent.com/39868400/99805755-efd8d680-2b77-11eb-9f4e-c7fa4afa3e36.png)
