### ISSUE TITLE
wangEditor2  的 formatText 这个属性  在 3 4 里面怎么用啊

### ISSUE THREAD

**Issue by chenyu-zyq** [wangeditor-team/wangEditor#2496]
> 

> ## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
不出意外应该是 editor.txt.text 文档里面该有的都有，还请过一下文档，视频也有。
