### ISSUE TITLE
是否可以仅引入文本编辑功能，减少打包体积

### ISSUE THREAD

**Issue by Alcantara6** [wangeditor-team/wangEditor#2497]
## 功能描述

我们的项目只用到文本编辑，但如果整体import的话，打包体积对于我们项目来说太大了。是否可以按需引入，只导入文本编辑的模块？

## 提炼几个功能点

- 按需引入，只导入文本编辑模块

## 原型图

无

## 可参考的案例

无

**Comment by wangfupeng1988** [comment]
从 v4.4.0 开始，因为一个 bug 而体积突然变大。
我们找到了原因并修复 https://github.com/wangeditor-team/wangEditor/commit/9c22960ee980c95fdfaa93866b08e4368db1c1ae

将会发布新版本 v4.5.2 解决这一问题。
