### ISSUE TITLE
关于添加样式使用font标签

### ISSUE THREAD

**Issue by qianchenrumeng** [wangeditor-team/wangEditor#2501]
## bug 描述

*编辑器升级到4以后，给文字添加样式变成了font，font是已经废弃的标签，在rn中的富文本渲染器上font标签渲染不出来*

## 你预期的样子是？

*希望能将font改回以前的span，样式用style里面用css来实现*

## 浏览器及版本号

*在rn的移动端上渲染*

## wangEditor 版本

*4.3.0*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
在有的富文本渲染器里面渲染不出来font标签，font是已经废弃的
- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
可以先使用 `editor.config.styleWithCSS = true`
