### ISSUE TITLE
4.5版本只有插入网络图片，没有本地图片插入选项

### ISSUE THREAD

**Issue by prayjourney** [wangeditor-team/wangEditor#2504]
## bug 描述
4.5版本只有插入网络图片，没有本地图片插入选项

## 你预期的样子是？
本地图片插入，网络图片插入

## 浏览器及版本号
chrome

## wangEditor 版本
4.5

## 官网能否复现该 bug ？
能/不能

## 最小成本的复现步骤
demo之中引入v4.5

**Comment by prayjourney** [comment]
最好默认开启啊 ！

**Comment by wangfupeng1988** [comment]
上传图片需要服务端接口的，默认开启的话，服务端接口写什么？
到时候，有上传本地图片的功能，但因为没服务端导致上传不成功，这不也是问题吗。
