### ISSUE TITLE
一个页面2个编辑器全屏BUG

### ISSUE THREAD

**Issue by whpcrs** [wangeditor-team/wangEditor#2507]
## bug 描述

一个页面有两个编辑器时，点击第一个编辑器的全屏，第二个编辑器出现在页面的最上层

![image](https://user-images.githubusercontent.com/6307811/100037611-71ad5600-2e3d-11eb-8ab5-89caf5f6bf14.png)
第二个编辑器出现在全屏的编辑器上层
![image](https://user-images.githubusercontent.com/6307811/100037652-8be73400-2e3d-11eb-9c8c-d9ded50d7be0.png)

## 你预期的样子是？
当一个编辑器全屏时，其他编辑器应该不可见

## 浏览器及版本号

谷歌浏览器

## wangEditor 版本

当前版本

## 官网能否复现该 bug ？

不能 官网只有一个编辑器

## 最小成本的复现步骤

代码上面描述中有，很简单
也有jsfiddle链接
[点我](https://jsfiddle.net/whpcrs/y327tnwq/7/)
点击第一个编辑器的全屏，可以看到

**Comment by maojie0047** [comment]
同样遇到了，希望可以尽快修复

**Comment by liucclear** [comment]
+1, 临时解决方案，监听editor的fullscreen事件来临时改变z-index属性

vue3示例
```javascript
// 编辑器z-index
const editorZIndex = ref(10)

watch(() => editorRef.value, (editor) => {
  if (!editor) return
  editor.on('fullScreen', () => {
    editorZIndex.value = 1000
  })
  editor.on('unFullScreen', () => {
    editorZIndex.value = 10
  })
}, { immediate: true })
```
