### ISSUE TITLE
tooltip 在编辑器失去焦点等行为后不会消失

### ISSUE THREAD

**Issue by careteenL** [wangeditor-team/wangEditor#2511]
## 功能描述

*期望内容区失去焦点时隐藏查看链接*

## 提炼几个功能点

- 点击是链接的部分时，会出现“查看链接”。如果此编辑器是在“弹窗or抽屉”里，直接关闭“弹窗or抽屉”，“查看链接”并不会消失。

## 原型图

无

## 可参考的案例

无

**Comment by UltramanWeiLai** [comment]
## bug描述

tooltip 在编辑器失去焦点，销毁等行为后，都不会消失

## 期望行为

- 再编辑器销毁、失去焦点等行为后，tooltip 也会跟着消失和销毁。
- 例如 弹框 抽屉 等行为下

## 浏览器版本

所有

## 编辑器版本

4.5.3

## 复现步骤
在 弹框中生成编辑器，插入超链接，单机超链接，然后点击弹框外部，弹框关闭后 tooltip 依旧存在

**Comment by UltramanWeiLai** [comment]
需要注意一下 执行销毁 api 的时候 tooltip 是否会被清除

**Comment by 86driver** [comment]
> ## 功能描述
> _期望内容区失去焦点时隐藏查看链接_
> 
> ## 提炼几个功能点
> * 点击是链接的部分时，会出现“查看链接”。如果此编辑器是在“弹窗or抽屉”里，直接关闭“弹窗or抽屉”，“查看链接”并不会消失。
> 
> ## 原型图
> 无
> 
> ## 可参考的案例
> 无

如果此编辑器是在“弹窗or抽屉”里，直接关闭“弹窗or抽屉”，“查看链接”并不会消失 这一条我根据你说的复现步骤试了一下，tooltip并没有不消失， 方便贴一个codepen复现一下你说的场景吗

**Comment by careteenL** [comment]
> @careteenL
> 如果此编辑器是在“弹窗or抽屉”里，直接关闭“弹窗or抽屉”，“查看链接”并不会消失
> 
> 这一条我根据你说的复现步骤试了一下，tooltip并没有不消失， 方便贴一个codepen复现一下你说的场景吗

@86driver  在[官网](http://www.wangeditor.com/)上先点击超链接`Github Star 1w+`显示`tooltip`，然后编辑器失去焦点（点击浏览器地址栏），此时`tooltip`还存在

![image](https://user-images.githubusercontent.com/23131426/103253185-0f56f080-49bb-11eb-9776-35852e198c4a.png)
