### ISSUE TITLE
富文本格式代码块粘贴

### ISSUE THREAD

**Issue by L1yp** [wangeditor-team/wangEditor#2512]
## 功能描述

富文本格式代码块粘贴，例如JB家族的代码复制后是有多种格式的，HTML/RTF/纯文本，不知道这个editor实现这个可选方案复杂吗?

## 提炼几个功能点

- 粘贴代码块时，配置可选格式?
- HTML/RTF/ClearText?

## 原型图
![image](https://user-images.githubusercontent.com/22633943/100054779-b648e980-2e5d-11eb-8881-d8711158bd4a.png)

## 可参考的案例

https://simditor.tower.im/

**Comment by wangfupeng1988** [comment]
代码块功能目前还比较弱，会择机重构。不过需要花费一些时间。
所以，这个问题暂时关闭，重构完会群里发通知。
