### ISSUE TITLE
富文本编辑器不能编辑数据（无法选中数据和粘贴复制）

### ISSUE THREAD

**Issue by longletian** [wangeditor-team/wangEditor#2517]
## 问题描述

*请输入遇到的问题...*
富文本编辑器不能编辑数据（无法选中数据和粘贴复制）
![image](https://user-images.githubusercontent.com/28197668/100195925-03e35600-2f33-11eb-8640-0a6758915fbf.png)

## wangEditor 版本
4.5.0
*请输入内容……*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
请详细写一下如何复现，不然我们这边也不知道如何 定位你说的问题

**Comment by longletian** [comment]
我也想，不知道为什么在我们公司的项目就不行 而我重新创建一个项目引入却可以的
