### ISSUE TITLE
建议添加本地视频(短视频)上传插入

### ISSUE THREAD

**Issue by 1119879311** [wangeditor-team/wangEditor#2519]
## 内容里面建议添加本地视频(短视频)上传插入

*内容里面建议添加本地视频(短视频)上传插入，
图片尺寸建议可以手动输入改动，而不是像官网的dome 只有选择 30%，50%，100% 参数
*

## 提炼几个功能点

- 1 .内容里面建议添加本地视频(短视频)上传插入
- 2. 图片尺寸建议可以手动输入改动，而不是

**Comment by UltramanWeiLai** [comment]
视频功能目前已经在进行中了。
图片手动输入宽高的话，目前拖拽虽然基本上能达到效果，所以我们内部需要讨论一下。
当然 小哥 有兴趣也可以自己修改源码 提交 PullRequests 我是欢迎 外部提交 PR 的

**Comment by UltramanWeiLai** [comment]
图片手动输入宽高的话，我们目前可能还支持不了，交互复杂度较高，我们目前以稳定现有版本的功能为主。

**Comment by KDWangBoss** [comment]
视频是不是不能够修改尺寸大小的

**Comment by wangfupeng1988** [comment]
@KDWangBoss 有没有可参考的案例，说几个具体的功能。

**Comment by wangfupeng1988** [comment]
@KDWangBoss 增加一个修改尺寸的弹框吧，可以自由输入高度、宽度。
