### ISSUE TITLE
删除图片回调 便于删除磁盘文件

### ISSUE THREAD

**Issue by easyTom** [wangeditor-team/wangEditor#2524]
## 功能描述
删除图片回调 便于删除磁盘文件

**Comment by UltramanWeiLai** [comment]
这个功能目前的话我们可能不考虑添加，实现过程非常负责，还要考虑其他的一些情况。
这里的话，可以和后端配合，文章编写时候的上传到一个临时目录，保存后，把文章中用到的图片移到正式目录里面，然后定期清除临时文件夹即可。
