### ISSUE TITLE
全屏时，点击图片，表格，展示出来的小面版不跟随

### ISSUE THREAD

**Issue by LuoRiWuSheng** [wangeditor-team/wangEditor#2526]
## bug 描述
全屏时，点击图片，表格，展示出来的小面版不跟随

## 你预期的样子是？

点击展开的小卡片是在我们的工具菜单的下方

## 浏览器及版本号
chrome 最新版本  87.0.4280.67（正式版本） (x86_64)

![image](https://user-images.githubusercontent.com/23192097/100300107-3ee79700-2fd0-11eb-8a5f-b0ddf86a57a2.png)

## wangEditor 版本
2020-11-26 官网 v4版本展示的

## 官网能否复现该 bug ？

能， 截图就是官网的截图

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
因为某些原因，面板目前全都是居中的，不是跟随按钮位置展示的
