### ISSUE TITLE
希望在插入图片的时候，图片的边线能拖拽 实现单个横向或者纵向拉伸

### ISSUE THREAD

**Issue by LuoRiWuSheng** [wangeditor-team/wangEditor#2527]
## 功能描述
希望在插入图片的时候，图片的边线能拖拽 实现单个横向或者纵向拉伸

## 提炼几个功能点
1、图片在水平方向可以横向拉伸
2、图片在纵向方面能纵向拉伸

![image](https://user-images.githubusercontent.com/23192097/100300520-275cde00-2fd1-11eb-9578-a7ccd14f6a0e.png)

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

无

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
无

**Comment by LuoRiWuSheng** [comment]
只是建议，哈哈哈   可能这样的要求好像也不合理，  拉伸会导致图片变形，失真

**Comment by UltramanWeiLai** [comment]
> 只是建议，哈哈哈 可能这样的要求好像也不合理， 拉伸会导致图片变形，失真

是的，不太合适，而且实现起来也比较复杂，真实用到的情况其实也不多，拖拽基本能覆盖应用场景了。
所以我就关了，非常欢迎提建议。

**Comment by LuoRiWuSheng** [comment]
> > 只是建议，哈哈哈 可能这样的要求好像也不合理， 拉伸会导致图片变形，失真
> 
> 是的，不太合适，而且实现起来也比较复杂，真实用到的情况其实也不多，拖拽基本能覆盖应用场景了。
> 所以我就关了，非常欢迎提建议。
嗯嗯  好的  我说咋少了一个 issue 哈哈哈

**Comment by fq1798** [comment]
2.x版本有这个功能,所以我现在还在用2.哈哈
