### ISSUE TITLE
希望菜单栏增加 清除，格式刷 格式的功能

### ISSUE THREAD

**Issue by LuoRiWuSheng** [wangeditor-team/wangEditor#2528]
## 功能描述
希望菜单栏增加 清除格式 ，格式刷  的功能

![image](https://user-images.githubusercontent.com/23192097/100301137-79523380-2fd2-11eb-89aa-a51d95162632.png)

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

语雀
![image](https://user-images.githubusercontent.com/23192097/100301197-a1419700-2fd2-11eb-9dc6-4290e45b81d1.png)

**Comment by UltramanWeiLai** [comment]
其实这个也在我们计划之中。这里我也收录一下吧。

**Comment by CrazyWood007** [comment]
清除文本功能比较急，现在设置了字体颜色或背景色以后，不能恢复成常规文本，导致后续输入的文字都有问题

**Comment by diction** [comment]
功能虽小，但是的确挺重要。

**Comment by liuqh0609** [comment]
这个我们在当前版本尝试完善该功能，但是在测试的时候会发现当前架构下的编辑器做该功能会造成一些问题，所以这个功能我们会放到v5版本去做，可以期待一下~

**Comment by bikesheddign** [comment]
有人做吗

**Comment by bikesheddign** [comment]
没的话我之前在其他产品实现过 可以尝试着贡献

**Comment by skique** [comment]
请问下，这个功能支持了吗？或者可以通过自定义菜单的方式实现吗？

**Comment by hxingever** [comment]
> 没的话我之前在其他产品实现过 可以尝试着贡献

大佬，有没有 自定义个自动排版功能（一件格式刷功能）分享下，谢谢v5版本的，510965496@qq.com

**Comment by cycleccc** [comment]
@bikesheddign 你好，现在还有兴趣参与这个项目吗，我们现在在维护[wangeditor-next](https://github.com/cycleccc/wangEditor-next)，欢迎来提 PR，一起继续维护这个项目。
