### ISSUE TITLE
希望字体颜色和背景能增加调色板功能

### ISSUE THREAD

**Issue by LuoRiWuSheng** [wangeditor-team/wangEditor#2529]
## 功能描述
希望字体颜色和背景能增加调色板功能

## 提炼几个功能点
1、提供基础的调试版，还可以有 那个 圆盘自己选择颜色
2、可以用户输入 rgb 和 hex 调整颜色
3、可以调整透明度

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

语雀
![image](https://user-images.githubusercontent.com/23192097/100302061-78ba9c80-2fd4-11eb-9a13-fd558b5a356a.png)
![image](https://user-images.githubusercontent.com/23192097/100302116-9851c500-2fd4-11eb-9988-9c1dd7c7adc3.png)

**Comment by UltramanWeiLai** [comment]
该功能也在计划中，目前处于调研状态。
我也顺道收录一下。

**Comment by JimuTroye** [comment]
这个真的很有必要啊，希望快点出这个功能

**Comment by clinfc** [comment]
@rsl140 @lkw199711 测试拜托两位了

**Comment by biology-w** [comment]
确实很有必要，这种
![image](https://user-images.githubusercontent.com/25600705/106841077-5633b680-66dc-11eb-9396-ec31e9142a8b.png)
比当前版本清晰很多。最好能自定义的。

**Comment by Lxshmily** [comment]
亟需这个功能！

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。

**Comment by pengwenfan012836** [comment]
亟需这个功能！！！！

**Comment by Fussyzhy** [comment]
> 亟需这个功能！！！！

这个功能到现在都没加，不过我通过自定义扩展实现了

**Comment by xx10n31y** [comment]
> > 亟需这个功能！！！！
> 
> 这个功能到现在都没加，不过我通过自定义扩展实现了

怎么实现的? 能分享下吗

**Comment by Fussyzhy** [comment]
> > > 亟需这个功能！！！！
> > 
> > 
> > 这个功能到现在都没加，不过我通过自定义扩展实现了
> 
> 怎么实现的? 能分享下吗

https://blog.csdn.net/u011798443/article/details/148299649可以看一下这个帖子

**Comment by xx10n31y** [comment]
> > > > 亟需这个功能！！！！
> > > 
> > > 
> > > 这个功能到现在都没加，不过我通过自定义扩展实现了
> > 
> > 
> > 怎么实现的? 能分享下吗
> 
> [https://blog.csdn.net/u011798443/article/details/148299649可以看一下这个帖子](https://blog.csdn.net/u011798443/article/details/148299649%E5%8F%AF%E4%BB%A5%E7%9C%8B%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA%E5%B8%96%E5%AD%90)

谢谢, 不过我是管理后台直接引入js/css进行使用的, 这个方式好像不太适合我
