### ISSUE TITLE
无法复制QQ对话框的文字

### ISSUE THREAD

**Issue by nickLuo1988** [wangeditor-team/wangEditor#2530]
## bug 描述
无法复制QQ对话框的文字，快捷键和右键复制粘贴都不行

## 你预期的样子是？
可以复制QQ对话框的文字到编辑器

## 浏览器及版本号

Google Chrome 已是最新版本
版本 87.0.4280.66（正式版本） （64 位）

## wangEditor 版本

"wangeditor": "^4.5.1",

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 复制QQ对话框的文字
- 步骤二 粘贴到官网编辑器里
- 步骤三 无法粘贴出来，空白

**Comment by hahaaha** [comment]
无法复现这个问题。。。你试试其他浏览器会不会有这个问题。。。看是不是因为插件导致问题

**Comment by nickLuo1988** [comment]
换浏览器也一样，发给几个同事在官网上也不能复制粘贴

**Comment by wangfupeng1988** [comment]
pr 已合并，待发布新版本
