### ISSUE TITLE
希望menu上增加hover显示汉字，很多小白用户都不知道菜单是干什么用的

### ISSUE THREAD

**Issue by yu530feng** [wangeditor-team/wangEditor#2531]
## 功能描述

希望menu上增加hover显示汉字，很多小白用户都不知道菜单是干什么用的

**Comment by hahaaha** [comment]
这个功能已经在计划中了，有需要的话可以关注下这个issue的解决进度https://github.com/wangeditor-team/wangEditor/issues/2290
