### ISSUE TITLE
vs 2019使用wangEditor4.5.1生成报错

### ISSUE THREAD

**Issue by newoul** [wangeditor-team/wangEditor#2533]
vs 2019使用wangEditor4.5.1生成报错,运行都运行不了

**Comment by xiaokyo** [comment]
请用bug的issue模板详细描述下你的场景及复现步骤

**Comment by newoul** [comment]
wangEditor4.5.1是只要引用wangEditor.min文件就可以是吗？我全部引用，那些ts文件就报错
