### ISSUE TITLE
Typescript 定义文件报错

### ISSUE THREAD

**Issue by lesonky** [wangeditor-team/wangEditor#2534]
## bug 描述

ERROR in /Users/shaojiasong/codes/harbor-pub/harbor-admin-ui/node_modules/wangeditor/dist/utils/dom-core.d.ts
14:64 Type parameter 'T' has a circular default.
    12 | };
    13 | export declare type DomElementSelector = string | DomElement | HTMLElement | Element | Document | HTMLCollection | Node | NodeList | HTMLElement[] | EventTarget | null | undefined;
  > 14 | export declare class DomElement<T extends DomElementSelector = DomElementSelector> {
       |                                                                ^
    15 |     selector: T;
    16 |     length: number;
    17 |     elems: HTMLElement[];
Version: typescript 3.6.2
Time: 14410ms

## wangEditor 版本

*4.5.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
打包编译的时候报错

> 应该是`DomElement` 循环引用了,把 `DomElementSelector` 里面的  `DomElement` 去掉应该就可以了

**Comment by wangfupeng1988** [comment]
你试一下，用这个 ts demo ，如何复现 bug ？
https://github.com/wangeditor-team/wangEditor-with-ts

**Comment by lesonky** [comment]
> 你试一下，用这个 ts demo ，如何复现 bug ？
> https://github.com/wangeditor-team/wangEditor-with-ts

用 ts demo 没有报错,我是在 vue 中初始化的时候报错的
我在 node_modules 中临时改了一下

`export declare type DomElementSelector = string | HTMLElement | Element | Document | HTMLCollection | Node | NodeList | HTMLElement[] | EventTarget | null | undefined;`

去掉了 DomElement 再重新编译,报错就消失了

**Comment by lesonky** [comment]
![image](https://user-images.githubusercontent.com/9718231/100713482-528b6700-33ef-11eb-92a3-e194a42b852d.png)
应该是这里的泛型定义循环了

**Comment by lesonky** [comment]
问题找到了
是 TS 版本问题,我用的 3.6.2 升级到 ^4.0.0 就可以了
这个issue 可以关闭了,3Q
