### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by 7niao** [wangeditor-team/wangEditor#2537]
## 问题描述
`editor.txt.html(nVal)` 设置内容后，概率性报错`Uncaught TypeError: Cannot read property 'contains' of undefined`  

## wangEditor 版本

"wangeditor": "^4.5.0"

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
vue3.0中使用：
后端返回富文本内容，
- 步骤二
将接收到的富文本内容设置到wangEditor对象；
`editor.txt.html(nVal)` 设置内容；
- 步骤三
重写请求页面时，有较高概率报错`Uncaught TypeError: Cannot read property 'contains' of undefined`；
报错后富文本编辑器完全不可用。

**Comment by wangfupeng1988** [comment]
你试一下，能用这个 repo 复现 bug 吗？https://github.com/wangeditor-team/wangEditor-with-vue3

**Comment by UltramanWeiLai** [comment]
由于长时间没有回复，暂时关闭该问题
