### ISSUE TITLE
获取html增加参数返回闭合标签

### ISSUE THREAD

**Issue by whpcrs** [wangeditor-team/wangEditor#2538]
## 功能描述

现在使用 editor.txt.html() 获取的html中的标签有些是非闭合的，比如`<br><img>`
希望editor提供方法获取闭合标签的html，将现在的`<br>,<img>`等非闭合标签改为`<br/>,<img/>`等闭合标签
现在获取的html
`<p><img src="logo.png" style="max-width:100%;"><br></p>`
希望获取的html
`<p><img src="logo.png" style="max-width:100%;"/><br/></p>`

**Comment by UltramanWeiLai** [comment]
请按照模板来描述问题，否则是不受理的
另外你说的着些属于浏览器行为，获取到的 img 是没有 '/' 去闭合的(你可以在控制台去通过原生的方式去试一下)，目前只能自己通过 正则表达式 去添加
