### ISSUE TITLE
设置pasteFilterStyle=false，关闭对样式的过滤，从word复制粘贴到编辑器，颜色并未保留

### ISSUE THREAD

**Issue by Ron233** [wangeditor-team/wangEditor#2542]
## bug 描述

*设置editor.config.pasteFilterStyle = false，关闭样式过滤，在word中复制了文字为粗体红色，但只保留了粗体，并未保留颜色*

## 你预期的样子是？

*复制至富文本编辑器，应该是文字粗体且红色*

## 浏览器及版本号

*Chrome87.0.4280.66*

## wangEditor 版本

*4.5.1*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 从word复制红色粗体文字到官网demo

**Comment by wangfupeng1988** [comment]
官网没有设置过 `editor.config.pasteFilterStyle = false` ，官网的 `editor.config.pasteFilterStyle` 是默认值 `true`

**Comment by Ron233** [comment]
> 官网没有设置过`editor.config.pasteFilterStyle = false`，官网的`editor.config.pasteFilterStyle`是替代值`true`

如果官网设置为false,那又是另一个bug了，因为我复制到官网，子题粗体是保留的，且我设置为false，也是没有保留样式，将颜色过滤掉了
![image](https://user-images.githubusercontent.com/32412608/100563144-abc49f00-32f8-11eb-8aad-435b140d7d74.png)

**Comment by Ron233** [comment]
> 官网没有设置过`editor.config.pasteFilterStyle = false`，官网的`editor.config.pasteFilterStyle`是替代值`true`
如果官网设置为true过滤，那就是设置editor.config.pasteFilterStyle根本无效，因为我复制到官网，字体粗体是保留的颜色被过滤，且我自己的代码里设置为false关闭过滤，也保留了粗体，但颜色被过滤掉了
就是那可能有两个问题，editor.config.pasteFilterStyle = false`无效，且样式解析存在问题
这是官网的复制粘贴
![image](https://user-images.githubusercontent.com/32412608/100563479-6f457300-32f9-11eb-9551-78fd69dd678d.png)
![image](https://user-images.githubusercontent.com/32412608/100563508-7c626200-32f9-11eb-96c9-f7ca36af7ded.png)
这是我本地代码
就只有两句，其他代码均已注释
![image](https://user-images.githubusercontent.com/32412608/100563706-03173f00-32fa-11eb-9ccf-0771b8a2ad59.png)
![image](https://user-images.githubusercontent.com/32412608/100563777-3659ce00-32fa-11eb-9191-d9908e3c42f7.png)

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/100573661-4c27bd00-3313-11eb-9e63-99d8fdc9c1f6.png)
我这边颜色和加粗都带上去了。

**Comment by Ron233** [comment]
> ![图片](https://user-images.githubusercontent.com/23336585/100573661-4c27bd00-3313-11eb-9e63-99d8fdc9c1f6.png)
> 我这边颜色和加粗都带上去了。
@UltramanWeiLai 
@wangfupeng1988 
貌似不行
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script src="https://unpkg.com/wangeditor/dist/wangEditor.min.js"></script>
</head>
<body>
  <div id="div1">
    <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
</div>
<script type="text/javascript">
  const E = window.wangEditor
  const editor = new E('#div1')
  editor.config.pasteFilterStyle = false
  // 或者 const editor = new E( document.getElementById('div1') )
  editor
  editor.create()
</script>
</body>
 </html>
```

**Comment by Ron233** [comment]
> ![图片](https://user-images.githubusercontent.com/23336585/100573661-4c27bd00-3313-11eb-9e63-99d8fdc9c1f6.png)
> 我这边颜色和加粗都带上去了。

@UltramanWeiLai 
好像不行，且按照 @wangfupeng1988 所说官网的demo也有问题，要么过滤了样式不会加粗黑色，要么没过滤加粗红色，但官网效果是加粗黑色  我的word是2019版本的
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script src="https://unpkg.com/wangeditor/dist/wangEditor.min.js"></script>
</head>
<body>
  <div id="div1">
    <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
</div>
<script type="text/javascript">
  const E = window.wangEditor
  const editor = new E('#div1')
  editor.config.pasteFilterStyle = false
  // 或者 const editor = new E( document.getElementById('div1') )
  editor
  editor.create()
</script>
</body>
</html>
```

**Comment by Ron233** [comment]
我在wps下试了一下效果是这样的 @UltramanWeiLai  @wangfupeng1988 
![image](https://user-images.githubusercontent.com/32412608/100596192-d9303d80-3336-11eb-8fe1-7bb827e81e8d.png)

**Comment by UltramanWeiLai** [comment]
> 我在wps下试了一下效果是这样的 @UltramanWeiLai @wangfupeng1988
> ![image](https://user-images.githubusercontent.com/32412608/100596192-d9303d80-3336-11eb-8fe1-7bb827e81e8d.png)

样式不一定是 style 标签自带的样式是不会被过滤的 wps 是会吧 style 带进来这个我已经收录了

**Comment by Ron233** [comment]
> > 我在wps下试了一下效果是这样的 @UltramanWeiLai @wangfupeng1988
> > ![image](https://user-images.githubusercontent.com/32412608/100596192-d9303d80-3336-11eb-8fe1-7bb827e81e8d.png)
> 
> 样式不一定是 style，像加粗 斜体 等都是 html 标签的行为不属于 style 的， wps 是会把 base style 带进来这个我已经收录了

office 2019下的颜色不会被识别

**Comment by Ron233** [comment]
> > > 我在wps下试了一下效果是这样的 @UltramanWeiLai @wangfupeng1988
> > > ![image](https://user-images.githubusercontent.com/32412608/100596192-d9303d80-3336-11eb-8fe1-7bb827e81e8d.png)
> > 
> > 
> > 样式不一定是 style，像加粗 斜体 等都是 html 标签的行为不属于 style 的， wps 是会把 base style 带进来这个我已经收录了
> 
> office 2019下的颜色不会被识别

而且对应用户而已，并不会管你style 和html标签是不是一类，要么就是 加粗斜体 和颜色一样都过滤，要么就都不过滤，如果你们不处理这个问题，当使用你们提供的自定义过滤函数时可不可以不执行你们的内部代码，我现在的问题就是我加粗的有颜色的问题，粘贴到文本框，颜色没了，无论editor.config.pasteFilterStyle = true还是false

**Comment by UltramanWeiLai** [comment]
> > > > 我在wps下试了一下效果是这样的 @UltramanWeiLai @wangfupeng1988
> > > > ![image](https://user-images.githubusercontent.com/32412608/100596192-d9303d80-3336-11eb-8fe1-7bb827e81e8d.png)
> > > 
> > > 
> > > 样式不一定是 style，像加粗 斜体 等都是 html 标签的行为不属于 style 的， wps 是会把 base style 带进来这个我已经收录了
> > 
> > 
> > office 2019下的颜色不会被识别
> 
> 而且对应用户而已，并不会管你style 和html标签是不是一类，要么就是 加粗斜体 和颜色一样都过滤，要么就都不过滤，如果你们不处理这个问题，当使用你们提供的自定义过滤函数时可不可以不执行你们的内部代码，我现在的问题就是我加粗的有颜色的文字，粘贴到编辑器，颜色没了，无论editor.config.pasteFilterStyle = true还是false

我们粘贴有回调可以自定义去实现逻辑，但实际上 过滤样式 和 过滤标签属于不同的内容，标签不是样式，这一点要了解，虽然看起来很像设置了样式。

**Comment by Ron233** [comment]
> > > > > 我在wps下试了一下效果是这样的 @UltramanWeiLai @wangfupeng1988
> > > > > ![image](https://user-images.githubusercontent.com/32412608/100596192-d9303d80-3336-11eb-8fe1-7bb827e81e8d.png)
> > > > 
> > > > 
> > > > 样式不一定是 style，像加粗 斜体 等都是 html 标签的行为不属于 style 的， wps 是会把 base style 带进来这个我已经收录了
> > > 
> > > 
> > > office 2019下的颜色不会被识别
> > 
> > 
> > 而且对应用户而已，并不会管你style 和html标签是不是一类，要么就是 加粗斜体 和颜色一样都过滤，要么就都不过滤，如果你们不处理这个问题，当使用你们提供的自定义过滤函数时可不可以不执行你们的内部代码，我现在的问题就是我加粗的有颜色的文字，粘贴到编辑器，颜色没了，无论editor.config.pasteFilterStyle = true还是false
> 
> 我们粘贴有回调可以自定义去实现逻辑，但实际上 过滤样式 和 过滤标签属于不同的内容，标签不是样式，这一点要了解，虽然看起来很像设置了样式。

算了，反正我也不用这个编辑器，你们说不算就不算吧

**Comment by Ron233** [comment]
既然是想过滤样式自然是想过滤粗体颜色什么乱七八糟的过滤掉，只过滤一个style,那直接只提供一个自定义过滤函数算了，你们自行将word粗体解析成b标签，过滤的时候又无视掉...

**Comment by 1529084525** [comment]
楼主是否已解决？我这边也有这种问题，关闭过滤后word粘贴进来没有样式。

**Comment by 1529084525** [comment]
![image](https://user-images.githubusercontent.com/49889130/101436015-56b40900-3948-11eb-8e41-a8a308bd3337.png)
![image](https://user-images.githubusercontent.com/49889130/101436035-603d7100-3948-11eb-870a-64794d998291.png)
![image](https://user-images.githubusercontent.com/49889130/101436054-64698e80-3948-11eb-8f9f-bf922408cda6.png)
没有效果！！

**Comment by UltramanWeiLai** [comment]
> 既然是想过滤样式自然是想过滤粗体颜色什么乱七八糟的过滤掉，只过滤一个style,那直接只提供一个自定义过滤函数算了，你们自行将word粗体解析成b标签，过滤的时候又无视掉...

自行把 word 体解析成b标签？标签 和 style 是复制过来就是这样的，不是我们特定解析了什么。自定义过滤的回调我们也有，你也可以自己对粘贴过来的内容进行处理。

**Comment by UltramanWeiLai** [comment]
该问题长时间没有人回复，暂且关闭
