### ISSUE TITLE
选择一段文本后粘贴，内容追加了而不是覆盖掉选择的部分

### ISSUE THREAD

**Issue by zhangzygit** [wangeditor-team/wangEditor#2544]
## bug 描述

选择一段文本后粘贴，结果是选择的文本+粘贴的文本

## 你预期的样子是？

覆盖掉选择的文本，显示粘贴的文本

## 浏览器及版本号

Chrome 87.0.4280.67

## wangEditor 版本

4.5.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 输入一段话，然后选择
- 复制其他文本，粘贴
![Nov-27-2020 18-43-43](https://user-images.githubusercontent.com/32352808/100440989-b0af0600-30e0-11eb-8e7e-845d3981392c.gif)

**Comment by UltramanWeiLai** [comment]
按照你的步骤我在官网上没有复现，能详细说一下复现步骤吗？

**Comment by zhangzygit** [comment]
**按commond/Ctrl+A 全选已存在的文本，然后commond/Ctrl+V粘贴就会出现这种情况，如果用鼠标右键粘贴就不会出现**
如果用鼠标拖拽全选或者按方向键移动光标全选，或者选择一部分文本进行粘贴就不会出现

**Comment by UltramanWeiLai** [comment]
> * 把官网上的内容都删掉
> * 随便输入一些文字，然后复制一段其他的文本
> * **按commond/Ctrl+A 全选已存在的文本，然后commond/Ctrl+V粘贴就会出现这种情况，如果用鼠标右键粘贴就不会出现，如果用鼠标拖拽全选或者按方向键移动光标全选，或者选择一部分文本进行粘贴就不会出现**

windows； 是的我使用快捷键 ctrl + a 然后复制的，没有复现。

**Comment by UltramanWeiLai** [comment]
由于长时间没有回复，暂时关闭该问题
