### ISSUE TITLE
回调函数 onchang事件 onchangeTimeout设置无效

### ISSUE THREAD

**Issue by langcs** [wangeditor-team/wangEditor#2548]
## bug 描述

回调函数 onchang事件 onchangeTimeout设置无效

## 你预期的样子是？

onchangeTimeout正常

## 浏览器及版本号

Google Chrome 86.0.4240.75

## wangEditor 版本

http://unpkg.com/wangeditor/dist/wangEditor.min.js

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/22113740/100580132-6320dc00-3320-11eb-9065-6c9a98ff8267.png)
![image](https://user-images.githubusercontent.com/22113740/100580106-52706600-3320-11eb-8336-b1c0278c7554.png)

**Comment by langcs** [comment]
**补充说明**：对比3.0版本 change事件触发频繁

**Comment by wangfupeng1988** [comment]
你不能在 onchange 里设置内容，这样可能引发其他未可知的问题。
onchange 仅仅是一个回调而已。

**Comment by clinfc** [comment]
老哥，仔细阅读文档有助于你更进一步的理解
![image](https://user-images.githubusercontent.com/39868400/100820559-6f747880-3489-11eb-941c-10ca03b9130b.png)

**Comment by langcs** [comment]
> 老哥，仔细阅读文档有助于你更进一步的理解
> http://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/07-%E9%85%8D%E7%BD%AE%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95.html
> ![image](https://user-images.githubusercontent.com/39868400/100820559-6f747880-3489-11eb-941c-10ca03b9130b.png)

你看看上面的补充说明 后续是按照设置兼容模式来的 但是同样的代码3.0版本和4.0版本效果是有差异的

**Comment by clinfc** [comment]
> > 老哥，仔细阅读文档有助于你更进一步的理解
> > http://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/07-%E9%85%8D%E7%BD%AE%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95.html
> > ![image](https://user-images.githubusercontent.com/39868400/100820559-6f747880-3489-11eb-941c-10ca03b9130b.png)
> 
> 你看看上面的补充说明 后续是按照设置兼容模式来的 但是同样的代码3.0版本和4.0版本效果是有差异的

老哥，v4 并不是在 v3 的基础上开发的......

**Comment by langcs** [comment]
> > > 老哥，仔细阅读文档有助于你更进一步的理解
> > > [http://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7 ％90％86 / 07-％E9％85％8D％E7％BD％AE％E5％8E％86％E5％8F％B2％E8％AE％B0％E5％BD％95.html](http://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/07-%E9%85%8D%E7%BD%AE%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95.html)
> > > ![图片](https://user-images.githubusercontent.com/39868400/100820559-6f747880-3489-11eb-941c-10ca03b9130b.png)
> > 
> > 
> > 你看看上面的补充说明后续是按照设置兼容模式来的但是同样的代码3.0版本和4.0版本效果是有差异的
> 
> 老哥，v4并非在v3的基础上开发的...

![image](https://user-images.githubusercontent.com/22113740/100821832-21ad3f80-348c-11eb-8c4e-86bc9d90b069.png)
好吧 文档上说平滑升级  customConfig -> config
