### ISSUE TITLE
切换 加粗/斜体/下划线等 功能无效

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/wangEditor#2552]
## bug 描述

输入一行文字,  选中菜单栏上的加粗/斜体/下划线等功能, 继续输入文字(此时加粗/斜体/下划线 等功能工作正常), 继续切换选中菜单栏上的 加粗/斜体/下划线等功能, 此时无法选中, 只能输入普通, 不带样式的文字

## 你预期的样子是？

切换 加粗/斜体/下划线等 功能后, 输入文字能正常展示样式

## 浏览器及版本号

chrome
v86

## wangEditor 版本
v4.5.2

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
选中菜单栏上的加粗/斜体/下划线  中一项功能, 输入文字
- 步骤二
切换选中菜单栏上的加粗/斜体/下划线  中一项功能, 此时无法选中其他菜单栏中的选项
- 步骤三
输入的文字是不带样式的普通文字

**Comment by lichenabson** [comment]
官网可以直接复现该 bug

**Comment by wangfupeng1988** [comment]
你说的复现步骤中，其中`此时无法选中其他菜单栏中的选项`具体指什么？

**Comment by lichenabson** [comment]
@wangfupeng1988 如果当前选中了**加粗** 正常输入文字, 然后去点击菜单栏上的下划线按钮, 就会点击不了(点击没有任何反应)

**Comment by lichenabson** [comment]
@wangfupeng1988 
![屏幕录制2020-12-02-上午11 11 54 (1)](https://user-images.githubusercontent.com/20200267/100826528-89b45380-3495-11eb-90e6-63fed40b9191.gif)

**Comment by wangfupeng1988** [comment]
你好，我是 wangEditor 维护的负责人。感谢反馈该 bug 。

但经我们调研，这个问题暂时不好解决。
因为我们是用 document.execCommand 实现的富文本编辑器，这个 API 这样操作会有问题。
所以抱歉，这个 issue 只能暂时放弃了。

不过我们也正在努力调研 document.execCommand 的替代方案，计划 2021 年高优处理这件事情。
再次感谢你的反馈。

**Comment by Heart-lin** [comment]
官网demo 依旧出现该bug   还没有修复吗

**Comment by cfmj** [comment]
同bug
