### ISSUE TITLE
设置字间距得菜单在哪啊

### ISSUE THREAD

**Issue by yuchunshui0613** [wangeditor-team/wangEditor#2554]
## 问题描述
设置字间距得菜单在哪啊
*请输入遇到的问题...*
设置字间距得菜单在哪啊
## wangEditor 版本
设置字间距得菜单在哪啊
*请输入内容……*
设置字间距得菜单在哪啊
## 是否查阅了文档 ？
设置字间距得菜单在哪啊
（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是/否*
是
## 最小成本的复现步骤
设置字间距得菜单在哪啊
（请告诉我们，如何**最快的**复现该问题？）
设置字间距得菜单在哪啊
- 步骤一
设置字间距得菜单在哪啊
- 步骤二
设置字间距得菜单在哪啊
- 步骤三
设置字间距得菜单在哪啊

**Comment by wangfupeng1988** [comment]
该功能没有。需要新开发。

**Comment by wangfupeng1988** [comment]
不过，该功能的需求量很少，所有优先级不高。至少近期，不会投入开发。
如果你急需，建议你去扩展自定义菜单。
http://www.wangeditor.com/doc/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html
