### ISSUE TITLE
视频添加本地上传功能

### ISSUE THREAD

**Issue by JimuTroye** [wangeditor-team/wangEditor#2555]
## 问题描述

*视频里要像图片那样，添加本地上传功能，网上找了很多文章都是在源码修改，有没有配置的方法 不修改源码*

## wangEditor 版本

*^4.5.2*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 图片加上editor.config.customUploadImg即可实现本地上传图片功能
-

**Comment by wangfupeng1988** [comment]
该功能正在开发中。
