### ISSUE TITLE
设置不自动focus，首次加载富文本，点击上传图片图标没反应

### ISSUE THREAD

**Issue by justinluhui** [wangeditor-team/wangEditor#2557]
## bug 描述
vue:
设置不自动focus:
editor.config.focus = false; 

富文本首次加载的时候，直接点工具栏上的上传图片图标，一点反应都没有，工具栏选择图片的的那个下拉没弹出来~

必须手动focus一下富文本编辑器，再点工具栏的上传图片图标，图片选择的下拉才能弹出来。

只要focus过一次，后面就不会有弹不出来的情况出现 (如果focus过一次，焦点再移出编辑器的话，这时候如果上传图片，会追加到原有内容的末尾，  所以未曾focus的编辑器，如果此时直接点上传的话，应该默认也是能追加到结尾才合理，而不是点了一点反应都没有)

如果editor.config.focus设置为true或者使用默认就不会有这个问题

## 你预期的样子是？

不管我有没有focus过富文本编辑器，工具栏上，点击上传图片图标，上传图片的下拉都能正常出现

## 浏览器及版本号

chrome 版本 86.0.4240.183（正式版本） (x86_64)

## wangEditor 版本

V4.1.0

## 官网能否复现该 bug ？

要先设置autofucus为false，没法操作

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 设置editor.config.focus = false; 
- 步骤二 刷新页面，不用focus富文本编辑器，点击上传图片按钮，一点反应都没有，选择图片的下拉没出现 （备注：图片上传使用的是自定义的方法editor.configcustomUploadImg）

**Comment by wangfupeng1988** [comment]
了解你的意思了，我觉得你提出的有道理。
即便是不自动 focus ，也可以通过菜单插入内容。
