### ISSUE TITLE
当点击添加<button>按钮时，form表单自动提交

### ISSUE THREAD

**Issue by 35598253** [wangeditor-team/wangEditor#2558]
## bug 描述

插入图片或者链接时，<form>表单自动提交

## 你预期的样子是？

不自动提交，目前 <button > 添加  type="button" 临时解决

## 浏览器及版本号

edge 87.0.664.41 

## wangEditor 版本

4.5.2

## 官网能否复现该 bug ？

官网没有form表单，不能去定

**Comment by xiaokyo** [comment]
浏览器button的默认行为。你这样解决了其实就是正解

**Comment by wangfupeng1988** [comment]
@UltramanWeiLai 去确认一下这个事情吧，如果真的默认触发 form 提交，就改一改。

**Comment by UltramanWeiLai** [comment]
该问题已修改，这周四更新的时候应该就能解决，如还有问题可重新提交 issue
