### ISSUE TITLE
无法正常粘贴内容到编辑器

### ISSUE THREAD

**Issue by doctorchao** [wangeditor-team/wangEditor#2560]
## 问题描述

点击编辑器聚焦后 长按无法粘贴内容到编辑器，需要对编辑器进行内容修改 比如输入空格再进行删除 之后就能粘贴了

## wangEditor 版本

v4.5.0  v4.5.2

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
新建编辑器
- 步骤二
复制一段内容
- 步骤三
粘贴到编辑器

**Comment by UltramanWeiLai** [comment]
我这边没有复现这个问题，能详细的写一下复现步骤吗？

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/100840680-364ffe80-34b1-11eb-8c8d-4912afc8cd90.png)
复制的该 issue 的标题

**Comment by UltramanWeiLai** [comment]
由于长时间没有回复，暂时关闭该问题

**Comment by doctorchao** [comment]
不好意思，在忙别的没有上线 。我重新试了下，是在editor.config.focus = false把自动聚焦关了后 就无法正常粘贴
