### ISSUE TITLE
⌘+A快捷键全选文本，然后用快捷键操作粘贴，粘贴的内容会在选择的文本后面追加展示而不是全部覆盖掉

### ISSUE THREAD

**Issue by zhangzygit** [wangeditor-team/wangEditor#2561]
## bug 描述

*⌘+A快捷键全选文本，然后用快捷键操作粘贴，粘贴的内容会在选择的文本后面追加展示而不是全部覆盖掉*
*而且有时候间隔近1秒钟才能在编辑器中显示粘贴的内容*
![Dec-02-2020 11-12-40](https://user-images.githubusercontent.com/32352808/100823946-2bd13d00-3490-11eb-91a8-5c948a913cc4.gif)

## 你预期的样子是？

*编辑器中全选的文本全部被替换掉，只展示粘贴的部分*

## 浏览器及版本号

*MacOS 11.0.1*
*Chrome 87.0.4280.67*

## wangEditor 版本

*4.5.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 把官网的编辑器内容全部删掉，随便输入一段文字
- 在其他地方复制一段文字
- Mac上用⌘+A快捷键全选文本，选中后⌘+V粘贴，粘贴的文本追加了而不是覆盖掉原始文本
- Window上的Ctrl+A全选快捷键没有尝试，不知道是否也存在这个问题

**Comment by wangfupeng1988** [comment]
我用 mac chrome  87.0.4280.67 没有复现你的问题。
粘贴正常。

**Comment by UltramanWeiLai** [comment]
Window 上的话我这边也没有复现。chrome 84.0.4147.105

**Comment by UltramanWeiLai** [comment]
犹豫长时间没有回复，所以暂时关闭该问题。
