### ISSUE TITLE
在windows下 对文字设置斜体, 光标位置错误

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/wangEditor#2562]
## bug 描述

在windows下, chrome 浏览器, 对文字设置斜体, 光标位置错误 (macos 下不会这么明显
![701E6EAF-CE5C-4111-97C5-812C70DF4DE5](https://user-images.githubusercontent.com/20200267/100826269-e82d0200-3494-11eb-8705-dc8baf0fc591.png)
![E549E58F-6C82-4d2e-AE9B-1EC0724CB365](https://user-images.githubusercontent.com/20200267/100826274-eb27f280-3494-11eb-9c3e-80c284f37ffc.png)

)

## 你预期的样子是？

光标位置正确

## 浏览器及版本号

windows
chrome v86

## wangEditor 版本
 v4.5.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 对文字设置斜体, 
- 观察光标位置

**Comment by UltramanWeiLai** [comment]
这个属于浏览器本身的行为，这是正常的。
而且这个想改也没法改
![image](https://user-images.githubusercontent.com/23336585/100841535-621fb400-34b2-11eb-9215-c68aecccbee1.png)
倾斜后字体间还会重叠呢
