### ISSUE TITLE
配合使用ant-pro-form，插入视频或者url时不操作其他直接点击插入触发form表单

### ISSUE THREAD

**Issue by jlxmaster** [wangeditor-team/wangEditor#2564]
## bug 描述

配合使用ant-pro-form，插入视频或者url时不操作其他直接点击插入触发form表单

## 你预期的样子是？

配合使用ant-pro-form，插入视频或者url时不操作其他直接点击插入不触发form表单

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
该问题已经受理请移步 #2558
