### ISSUE TITLE
火狐浏览器中无法粘贴复制

### ISSUE THREAD

**Issue by jlxmaster** [wangeditor-team/wangEditor#2565]
## bug 描述

火狐浏览器中无法粘贴复制

## 你预期的样子是？

火狐浏览器中可以粘贴复制

## 浏览器及版本号

最新

## wangEditor 版本

v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

配合使用ant-pro-form

**Comment by UltramanWeiLai** [comment]
该问题我们已经受理了详情可以去 #2399 了解
