### ISSUE TITLE
富文本编辑框嵌入antd的table组件中的bug

### ISSUE THREAD

**Issue by maojie0047** [wangeditor-team/wangEditor#2566]
## bug 描述

当一个富文本编辑框嵌入到antd的table组件中，点击编辑区域就会显示：编辑行列的工具栏。

## 你预期的样子是？

点击编辑区域不显示 编辑行列的工具栏

## 浏览器及版本号

谷歌版本 87.0.4280.66（正式版本） （64 位）

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

1.创建一个表格
2.表格的行列内容，是一个富文本编辑器
3.点击富文本编辑器的 编辑区域，
4.出现工具栏

**Comment by UltramanWeiLai** [comment]
该问题已经受理请移步 #2558

**Comment by zhaoxiangyan** [comment]
刚想咨询下，table嵌套table，里面的table生成的tooltip在body下面，当我display:none编辑器，body下面的tooltip仍会保留在页面上

**Comment by UltramanWeiLai** [comment]
该问题已修改，这周四更新的时候应该就能解决，如还有问题可重新提交 issue
