### ISSUE TITLE
自定义菜单后，而且uploadImgShowBase64=true和没有使用uploadImgServer，不能粘贴图片

### ISSUE THREAD

**Issue by wyl985** [wangeditor-team/wangEditor#2570]
### bug 描述
vue：wangEdit配置如下所示
```
      this.editor = new E(this.$refs.toolbar, this.$refs.editor)
      this.editor.config.uploadImgShowBase64 = true // base 64 存储图片
      this.editor.config.showLinkImg = false
      this.editor.config.focus = this.wangEditIsFocus //自动 focus
      //自定义表情
      this.editor.config.emotions = [
        {
          title: '默认',
          type: 'image',
          content: emotionJSON
        }
      ]
      // 配置菜单
      this.editor.config.menus = [
        'emoticon', // 表情
        'image', // 插入图片
      ]
      // 创建富文本编辑器
      this.editor.create()
```

然后截图、或者复制图片都不能粘贴到wangEdit！然后把自定义菜单注释掉，使用默认菜单，就可以粘贴了~

### 你预期的样子是？
不管有没有自定义菜单，粘贴图片都是正常的

### 浏览器及版本号
浏览器：360浏览器
版本号：12.2

### wangEditor 版本
release: v4.5.2

### 官网能否复现该 bug ？
要自定义菜单，没法操作

### 最小成本的复现步骤
1.自定义菜单
2.this.editor.config.uploadImgShowBase64 = true // base 64 存储图片
3.复制粘贴图片到wangEdit

**Comment by clinfc** [comment]
图片相关的功能都是绑定在系统的图片菜单中的，既然你未使用系统的图片菜单，那么相关的功能就未被初始化，也就造成了你不适用系统图片菜单就没有相关功能的“BUG”。这是我的猜测，因为你的描述并不详细。

**Comment by wyl985** [comment]
谢谢！解决了！
的确是我自定义的菜单中没有包含“系统的图片菜单”，所以导致该功能未被初始化。

**Comment by ViolenceAesthetics** [comment]
> 谢谢！解决了！
> 的确是我自定义的菜单中没有包含“系统的图片菜单”，因此导致该功能初始化。

能给下具体的方法么？我也在寻找复制粘贴不成功的问题，想尝试一下

**Comment by clinfc** [comment]
> > 谢谢！解决了！
> > 的确是我自定义的菜单中没有包含“系统的图片菜单”，因此导致该功能初始化。
> 
> 能给下具体的方法么？我也在寻找复制粘贴不成功的问题，想尝试一下

这个你得自己去翻源码了

**Comment by wyl985** [comment]
> > 谢谢！解决了！
> > 的确是我自定义的菜单中没有包含“系统的图片菜单”，因此导致该功能初始化。
> 
> 能给下具体的方法么？我也在寻找复制粘贴不成功的问题，想尝试一下

我的做法是，自定义菜单中添加“系统的图片菜单”，然后用css把它隐藏了就好，然后富文本框就会初始化复制粘贴图片的功能。

**Comment by LeungYu** [comment]
我觉得其实图片输入相关功能的设计不是很合理，毕竟只需要粘贴图片，不使用系统自带菜单的脱图片功能的人大有人在，一个是基础能力，另外一个是功能，应该把这两部分分离开来

**Comment by wyl985** [comment]
> 我觉得其实图片输入相关功能的设计不是很合理，毕竟只需要粘贴图片，不使用系统自带菜单的脱图片功能的人大有人在，一个是基础能力，另外一个是功能，应该把这两部分分离开来

是的，同意你说的话
