### ISSUE TITLE
点击图片，切换到网络图片，不填，直接插入，会有链接跳转。 超链接的插入也是一样

### ISSUE THREAD

**Issue by yu530feng** [wangeditor-team/wangEditor#2574]
## bug 描述

点击图片，切换到网络图片，不填，直接插入，会有链接跳转。
虽是小bug, 但影响体验

## 你预期的样子是？

不跳转，作相应提示

## 浏览器及版本号

chrome 86

## wangEditor 版本

v4.5.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一、点击图片，切换到网络图片，不填，直接插入，
- 步骤二
- 步骤三

**Comment by hahaaha** [comment]
根据你提供的信息没有复现出这个问题。。。麻烦步骤在详细描述下。。。另外这个“切换到网络图片”具体要怎么操作

**Comment by LuoRiWuSheng** [comment]
> 提
请看看我的那个 ，应该很这个描述的类似 [2580](https://github.com/wangeditor-team/wangEditor/issues/2580)

还有 这个差不多是 因为链接跳转导致，其实应该和表单的提交没有关系  [2576](https://github.com/wangeditor-team/wangEditor/issues/2576)

**Comment by LuoRiWuSheng** [comment]
> 根据你提供的信息没有复现出这个问题。。。麻烦步骤在详细描述下。。。另外这个“切换到网络图片”具体要怎么操作


请看看我的那个 ，应该很这个描述的类似, 我提的issue [2580](https://github.com/wangeditor-team/wangEditor/issues/2580)

还有 这个差不多是 因为链接跳转导致，其实应该和表单的提交没有关系[2576](https://github.com/wangeditor-team/wangEditor/issues/2576)

**Comment by UltramanWeiLai** [comment]
请确认是否在 from 表单内，再没有 from 表单内的话那么这个问题 可以异步到 #2558 里面去跟踪
如果不是，目前的话我们没有复现，是否可以提供详细的步骤或者Demo

**Comment by LuoRiWuSheng** [comment]
> 请确认是否在 from 表单内，再没有 from 表单内的话那么这个问题 可以移步到 #2558 里面去跟踪
> 如果不是，目前的话我们没有复现，是否可以提供详细的步骤或者Demo

我这边可以提供demo 看怎么给你

**Comment by UltramanWeiLai** [comment]
> > 请确认是否在 from 表单内，再没有 from 表单内的话那么这个问题 可以移步到 #2558 里面去跟踪
> > 如果不是，目前的话我们没有复现，是否可以提供详细的步骤或者Demo
> 
> 我这边可以提供demo 看怎么给你

github 或者 交流群里面上传 demo 文件都可以

**Comment by wpjCode** [comment]
这个问题我修改你的源码解决了，你这个插入写的是button，你需要些type类型，否则，他会在某些浏览器点击跳转 网络图片插入按钮如下：<button id="btn-link6534696021852706" class="right" type="button">插入</button> 增加’type="button"‘

**Comment by UltramanWeiLai** [comment]
> 这个问题我修改你的源码解决了，你这个插入写的是button，你需要些type类型，否则，他会在某些浏览器点击跳转 网络图片插入按钮如下：插入 增加’type="button"‘

该问题以及修复过了，在 PR 阶段，周四更新的时候应该就能修复
这边的话还是请 移步到 #2558 里面去跟踪问题
