### ISSUE TITLE
设置字体颜色或背景色后怎么清除设置

### ISSUE THREAD

**Issue by csshenzhi** [wangeditor-team/wangEditor#2575]
## 问题描述

设置了字体颜色或背景色后无法直接清除掉字体颜色或背景色，编辑器生成“：</span style="color: rgb(0, 0, 0);"/>的沙发舒服</span/>”希望能清除只显示文本：“的沙发舒服”

## wangEditor 版本

"wangeditor": "^4.5.2"

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：设置字体颜色或背景色类似生成：“</span style="color: rgb(0, 0, 0);"/>的沙发舒服</span/>”
- 步骤二：保存提交内容
- 步骤三：想去掉之前设置的字体颜色或背景色，希望只留下：“的沙发舒服”

**Comment by hahaaha** [comment]
我们已经在着手解决这个问题了，具体进度可以关注这个issue https://github.com/wangeditor-team/wangEditor/issues/2528
