### ISSUE TITLE
点击插入链接，form表单会自动提交

### ISSUE THREAD

**Issue by FateOfKing** [wangeditor-team/wangEditor#2576]
## bug 描述

*插入图片或者链接时，表单自动提交*

## 你预期的样子是？

*插入图片或者链接时，不触发表单提交*

## 浏览器及版本号

*chrome Version 87.0.4280.88 (Official Build) (x86_64)*

## wangEditor 版本

*4.5.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by clinfc** [comment]
具体场景模糊，请贴出你的代码

**Comment by UltramanWeiLai** [comment]
该问题以及在 PR 阶段了 具体可以异步到 #2558  去看
