### ISSUE TITLE
希望能增加源码编辑模式

### ISSUE THREAD

**Issue by hen1183392934** [wangeditor-team/wangEditor#2577]
## 功能描述
希望能增加html源码编辑模式
*请输入内容……*
源码编辑点击后可以编辑html源码
## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图
![image](https://user-images.githubusercontent.com/24801619/101150267-fb89ca00-365a-11eb-9a9c-a3cd0a0567aa.png)

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例
https://uutool.cn/ueditor/
*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by hahaaha** [comment]
这个问题可以参考下这个issue https://github.com/wangeditor-team/wangEditor/issues/2299
