### ISSUE TITLE
插入视频的时候，点击插入，页面刷新了

### ISSUE THREAD

**Issue by LuoRiWuSheng** [wangeditor-team/wangEditor#2580]
## bug 描述
页面初始化完成以后，点击插入视频， 直接点击插入按钮， 不在input框中填入任何内容， 页面刷新了

而且特别奇怪的是， 页面只要被那个bug自动刷新以后，再点击 插入 按钮，就是正常的；

## 你预期的样子是？
即使我什么视频的链接也不放，点击插入，也不要有整个页面的刷新动作

## 浏览器及版本号
mac下 最新版本
 87.0.4280.88（正式版本） (x86_64)

## wangEditor 版本
 "wangeditor": "^4.5.2",
vue 版本 "vue": "2.6.10",

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

- 步骤一
1. 要有2个路由的页面， 我是 vue 单页应用
- 步骤二
2. 富文本编辑器在 详情页（detail.vue）路由， 我们通过 列表(list.vue)页面，跳入详情页
- 步骤三
3. 详情页有富文本， 点击富文本的 视频的 插入 按钮， 此时页面刷新
重复
4.回到 列表页面（list.vue）， 重新进入详情页(detail.vue) ， 再重复 步骤3 可以复现

**Comment by wangfupeng1988** [comment]
必须用 vue 以及路由，才能复现吗？这复现步骤有点复杂呀。

能否再简化一下复现步骤，以最小的成本，复现问题。

**Comment by LuoRiWuSheng** [comment]
> 必须用 vue 以及路由，才能复现吗？这复现步骤有点复杂呀。
> 
> 能否再简化一下复现步骤，以最小的成本，复现问题。

我这边重新搭建一套单纯的环境 解决了  我认为，那个 插入的按钮  有问题

如果button 的type 没有明确指定， 在这个button 嵌入到 form 表单的时候，会触发form表单的默认行为； 而恰好我们将这个富文本是放在 form 表单中的； 看您这边能不能将 button的 type 显式 声明为type="button" 

![image](https://user-images.githubusercontent.com/23192097/101282303-5f54f400-380f-11eb-8612-c139f3e98e19.png)


如果在 element-ui 的 form中使用 ，在不修改wangeditor源码 的前提下  ，需要给 el-form 指定一个  <el-form @submit.native.prevent>    @submit.native.prevent 阻止表单的默认行为

![image](https://user-images.githubusercontent.com/23192097/101282338-95927380-380f-11eb-9e41-aa4f1dba3cd5.png)

**Comment by UltramanWeiLai** [comment]
如果是编辑器在form表中点击插入出现这个问题的话，可以移步到 #2558 该问题已在 PR 阶段了

**Comment by LuoRiWuSheng** [comment]
我这边放一个gif 动图 演示一下触发的场景
![wangeditor-error](https://user-images.githubusercontent.com/23192097/101282483-6a5c5400-3810-11eb-9921-b99862a88654.gif)

**Comment by LuoRiWuSheng** [comment]
> 如果是编辑器在form表中点击插入出现这个问题的话，可以移步到 #2558 该问题已在 PR 阶段了

哈哈哈 我是发现有2个类似的  我把别人的那个 下面回复了一下 链接跳转到我自己这个 issue 上了， 吃个饭的时间，想到可能是 form这个情况 单独写了一个 demo 跑

**Comment by UltramanWeiLai** [comment]
回头我试一下 spa 点插入，如果可以最好是能提供 demo 给我

**Comment by LuoRiWuSheng** [comment]
> 回头我试一下 spa 点插入，如果可以最好是能提供 demo 给我

901247714 我在这个群   要不你加我 qq  1197802519
