### ISSUE TITLE
最后一行文字看不见

### ISSUE THREAD

**Issue by btea** [wangeditor-team/wangEditor#2584]
## bug 描述

*编辑器最后一行是文字，在设置全屏之后，如果出现滚动条，滚动到底部，最后一行文字看不见。*

## 你预期的样子是？

*设置全屏之后，最后一行文字可见。*

## 浏览器及版本号

*Chrome86.0.4240.198     Firefox 83.0*

## wangEditor 版本

*^4.5.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

1、在编辑器最后一行添加文字，然后设置全屏。
2、如果出现滚动条，滚动到底部。
3、如果没有出现滚动条，添加文字至出现滚动条，然后设置全屏，再滚动至底部。

## 补充
fix [#2569](https://github.com/wangeditor-team/wangEditor/pull/2569)

**Comment by wangfupeng1988** [comment]
[pr](https://github.com/wangeditor-team/wangEditor/pull/2569)  已合并，待发布。
