### ISSUE TITLE
自定义配置菜单时报错

### ISSUE THREAD

**Issue by MR-YUZL** [wangeditor-team/wangEditor#2586]
## bug 描述

自定义配置菜单后，菜单项无法被选择，且会抛出‘wangEditor.js?6fad:10198 Uncaught TypeError: Cannot read property 'length' of undefined’的错误

## 浏览器及版本号

*谷歌*

## wangEditor 版本

4.5.2

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

    const editor = new wangEditor(`#richText`);

    editor.config.menus = [
      "fontName",
      "fontSize",
      "bold",
      "italic",
      "underline",
      "foreColor",
      "list",
      "link",
    ];
    editor.create();

**Comment by echoLC** [comment]
我这边试了下没法重现，你能本地写个简单demo实现有没有问题吗，看下是不是你的其它页面功能的影响导致的

**Comment by clinfc** [comment]
你这里应该放的是你自定义菜单的代码

**Comment by MR-YUZL** [comment]
> 我这边试了下没法重现，你能本地写个简单demo实现有没有问题吗，看下是不是你的其它页面功能的影响导致的

恩恩我再试试，我发现有的页面可以用，有的页面不行，感觉是被什么影响了

**Comment by MR-YUZL** [comment]
> 你这里应该放的是你自定义菜单的代码

就这些代码，我只是把原本的菜单栏给减少了数量

**Comment by MR-YUZL** [comment]
> 我这边试了下没法重现，你能本地写个简单demo实现有没有问题吗，看下是不是你的其它页面功能的影响导致的

我在你们的vue的官方demo上试了一下，自定义配置完菜单后，你切换字体或者字体大小都必须点两次才有效果，是不是因为这个原因？

**Comment by echoLC** [comment]
这个问题，我们之前有issue提过类似的，到时候解决的时候应该会一起解决。

**Comment by echoLC** [comment]
我就先关掉这个issue，其关联的issue为https://github.com/wangeditor-team/wangEditor/issues/2552
