### ISSUE TITLE
把自动聚焦关了后，无法正常粘贴内容到编辑器

### ISSUE THREAD

**Issue by doctorchao** [wangeditor-team/wangEditor#2589]
## bug 描述

点击编辑器聚焦后 长按无法粘贴内容到编辑器，需要对编辑器进行内容修改 比如输入空格再进行删除 之后就能粘贴了

## 你预期的样子是？

*请输入内容……*

## wangEditor 版本

v4

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

新建编辑器
配置自动聚焦为关闭状态
editor.config.focus = false
然后编辑器就无法正常粘贴内容了

**Comment by echoLC** [comment]
你好，请详细描述Bug的复现步骤，否则我们这边无法定位到问题，就不能及时跟进解决。

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭。
