### ISSUE TITLE
v4 中能否支持输入数学公式

### ISSUE THREAD

**Issue by 1456118242** [wangeditor-team/wangEditor#2591]

**Comment by hahaaha** [comment]
这个我们已经在调研了。。。如果你更好的建议或者方案。。。可以按模板提issue。。。后续我们会跟进的

**Comment by wangfupeng1988** [comment]
v5 已经支持公式 https://github.com/wangeditor-team/wangEditor-plugin-formula

v5 发布在即，v4 不会再开发 公式 了
