### ISSUE TITLE
一个更多菜单

### ISSUE THREAD

**Issue by Jayj1997** [wangeditor-team/wangEditor#2592]
## 问题描述

添加了一个更多菜单来容纳超出了一个宽度的功能（可以通过config关闭），让功能栏宽度不足时不再改变长度。我询问了群主他建议我提交一个issue，我应该改完后发pull request还是你们来做呢，你们觉得这有用吗？

现在还差

- 一个listener来append和remove $elem
-  把耦合的代码分出来，目前的情况是我直接写到init里了
- 一个dots horizontal icon
- 可选哪些被收进更多菜单内是有必要的功能吗？
- 修复亿个小bug

## wangEditor 版本
4

## 最小成本的复现步骤

https://sm.ms/image/dnh2AZfs3x8QO6W

## 我还想

- 让droplist出现且右边宽度不足时给绝对布局减left
- image加alt seo
- 传本地图片视频这种开接口向本地缓存是可行的吗？

which one is needed?

**Comment by echoLC** [comment]
我们这边的人力有限，如果我们来做可能会视功能的适用性排期来做，如果你自己有时间实现的话，可以做好后提交PR，我们会处理

**Comment by Jayj1997** [comment]
> 我们这边的人力有限，如果我们来做可能会视功能的适用性排期来做，如果你自己有时间实现的话，可以做好后提交PR，我们会处理

okay, happy to help
