### ISSUE TITLE
图片的外部自定义点击事件如何实现？

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#2594]
粘贴图片后 点击不想要修改尺寸功能 只想在外部拿到点击事件 和点击的DOM元素 如何实现呢

**Comment by echoLC** [comment]
我们暂时没办法支持，所以你可能要换种方式来解决这个问题。

**Comment by UltramanWeiLai** [comment]
下次还请按照模板提交 issue 否则是不受理的，关于自定义事件的话，editor 下面有 event hooks 但是并不建议修改容易出问题。
