### ISSUE TITLE
弹窗位置如何修改

### ISSUE THREAD

**Issue by surewinT** [wangeditor-team/wangEditor#2596]
![download](https://user-images.githubusercontent.com/53040563/101464549-c0004000-3979-11eb-887a-690ab6adf42e.png)
上传图片的弹窗位置能否修改，类似于element-ui的tooltip组件，弹窗出现的位置应该跟随菜单栏对应的图标

**Comment by UltramanWeiLai** [comment]
请按照模板来提交 issue 否则是不受理的。
弹框位置目前因为某些因素统一是居中显示的，占时没有开发修改的突进
