### ISSUE TITLE
insertElem指令有误？

### ISSUE THREAD

**Issue by 19971117hjs** [wangeditor-team/wangEditor#2597]
## bug 描述

*insertElem指令有误？*

## 你预期的样子是？

*正常插入嵌套dom节点*

## 浏览器及版本号

*版本 87.0.4280.88（正式版本） （32 位）*

## wangEditor 版本

*4.5.2*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤
Command.prototype.insertElem = function ($elem) {
    var editor = this.editor;
    var range = editor.selection.getRange();
    if (range == null) return;
    if (range.insertNode) {
      range.deleteContents();
      //   这个$elem.elems[0]是不是有误
      //   注释range.insertNode($elem.elems[0]);
      range.insertNode($elem);
    }
  };

**Comment by echoLC** [comment]
这个$elemn是我们自己抽象的一个对象，不是真实的dom，所以这里的设置没有错

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭。
