### ISSUE TITLE
最新版的 WPS for Mac,复制的内容会出现css 样式？

### ISSUE THREAD

**Issue by Aiden-Xi** [wangeditor-team/wangEditor#2600]
## bug 描述

*在官网里面黏贴 WPS for Mac 拷贝的内容会出现多余的 css 样式*

## 你预期的样子是？

*正常情况，css, html 等不应该显示出来*

## 浏览器及版本号

*版本 87.0.4280.88（正式版本） (x86_64)*

## wangEditor 版本

*V4.5.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
 下载最新版本的 [WPS for Mac](https://mac.wps.cn/), 随便编辑一部分文字，然后拷贝文字
- 步骤二
黏贴到官网，可以明显看到不必要的内容

**Comment by Aiden-Xi** [comment]
[WPS 官网](https://mac.wps.cn/)

**Comment by Aiden-Xi** [comment]
![image](https://user-images.githubusercontent.com/12513415/101758623-83684c00-3b13-11eb-9370-62efbb9843c4.png)

**Comment by UltramanWeiLai** [comment]
该问题已经收录且再处理中可以移步到 #2546 中跟进
