### ISSUE TITLE
初始化编辑器后，传入内容，还能进行撤销操作

### ISSUE THREAD

**Issue by kkosin** [wangeditor-team/wangEditor#2601]
## 功能描述

初始化编辑器后，代码传入内容后，发现还能进行撤销操作，撤销后内容变空，还有，我业务也有切换内容的情况，虽然能销毁重新创建编辑框，但感觉这样操作意义不大，看了下代码，外部无法清空历史记录，希望能添加这个接口

## 提炼几个功能点

- 功能1
清空历史记录接口

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by UltramanWeiLai** [comment]
通过代码的形式修改值，造成了 onchange 事件，所以能 撤销。
清除历史记录这个功能我们目前的可能暂时不考虑支持。

**Comment by lemos1235** [comment]
希望可以解决这个 bug
