### ISSUE TITLE
通过截图方式可以将照片粘贴到编辑框里

### ISSUE THREAD

**Issue by lvsonghan** [wangeditor-team/wangEditor#2602]
## 问题描述

*在关闭图片菜单后，通过微信截图等方式依然可以将照片粘贴到编辑框里，进而形成了可以上传图片的情况*

## wangEditor 版本

*4.5.2*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 通过微信进行截图
- 点击完成（绿色对号）按钮
- ctrl+v复制到编辑框里

**Comment by UltramanWeiLai** [comment]
虽然你没有配置 图片按钮，但是你配置了 图片上传的机制吧？
你可以把上传的相关配置 注释掉 然后把图片格式转换成 base64 应该就没问题了。

**Comment by UltramanWeiLai** [comment]
该问题长时间没有人回复，暂且关闭
