### ISSUE TITLE
editor.config.focus设置false，无法正常粘贴内容

### ISSUE THREAD

**Issue by ruipeng-wang** [wangeditor-team/wangEditor#2606]
## bug 描述

*editor.config.focus设置false，聚焦后ctrl+v粘贴内容两次以上才能成功*

## 你预期的样子是？

*ctrl+v一次实现粘贴*

## 浏览器及版本号

* Chrome87.0.4280.88,Safari也是*

## wangEditor 版本

*4.5.0*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

代码如下：
`
<script src="https://unpkg.com/wangeditor/dist/wangEditor.min.js"></script>
    <div class="editor" style="height: 800px;width: 600px;"></div>
    <script>
        var createEditor = function() {
            var E = window.wangEditor
            var editor = new E(".editor");
            editor.config.menus = [
                "head",
                "bold",
                "fontSize",
                "italic",
                "list",
                "justify",
                "image",
            ]
            
            editor.config.showFullScreen = false;
            // focus为true,没有问题
            editor.config.focus = false;
            editor.config.showLinkImg = false;
            editor.config.pasteFilterStyle = false;
            editor.config.pasteIgnoreImg = true;
            editor.config.onchange = (v) => {
                console.log(v)
            }
            editor.create();
        }
        createEditor();
    </script>

`

**Comment by UltramanWeiLai** [comment]
该问题已经解决，这周四发布新版本后应该就没问题了。
