### ISSUE TITLE
字体

### ISSUE THREAD

**Issue by shy19940217** [wangeditor-team/wangEditor#2615]
## 问题描述
支持的字体都有哪些，自定义配置的系统字体都可以生效吗？ 苹果的字体支持吗

## wangEditor 版本

v4.5.3

## 是否查阅了文档 ？

是

editor.config.fontNames = [
    '黑体',
    '仿宋',
    '楷体',
    '标楷体',
    '华文仿宋',
    '华文楷体',
    '宋体',
    '微软雅黑',
    'Arial',
    'Tahoma',
    'Verdana',
    'Times New Roman',
    'Courier New',
]
除了这些字体，其他的系统字体也支持吗

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by echoLC** [comment]
想要支持更多的字体，可以自定义配置

**Comment by shy19940217** [comment]
> 想要支持更多的字体，可以自定义配置

SF Pro Rounded   这个字体可以吧   我直接写在后面  发现前台没生效

**Comment by echoLC** [comment]
你确定浏览器有这个字体，没有的话是需要加载字体文件的

**Comment by shy19940217** [comment]
> 你确定浏览器有这个字体，没有的话是需要加载字体文件的

已经可以了  富文本的字体在ios客户端显示，这个字体比较新，ios需要替换这个字体，已经生效了

**Comment by UltramanWeiLai** [comment]
> > 你确定浏览器有这个字体，没有的话是需要加载字体文件的
> 
> 已经可以了 富文本的字体在ios客户端显示，这个字体比较新，ios需要替换这个字体，已经生效了

那我就关闭这个问题了，自定义字体依赖于客户端是否有这个字体文件，如果没有需要服务端进行加载的。
