### ISSUE TITLE
官网能添加每个版本的更新日志吗

### ISSUE THREAD

**Issue by fubd** [wangeditor-team/wangEditor#2616]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by echoLC** [comment]
我们目录下已经有changelog，可以看到每个版本的日志
