### ISSUE TITLE
编辑器table嵌套table问题

### ISSUE THREAD

**Issue by zhaoxiangyan** [wangeditor-team/wangEditor#2619]
## bug 描述

table嵌套table，里面的table生成的tooltip在body下面，当我display:none编辑器，body下面的tooltip仍会保留在页面

## 你预期的样子是？

当把编辑器dom清除或display:none，内部的tooltop能够跟随父级编辑器dom一起清除

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

4.5.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 直接添加嵌套表格
- 步骤二 激活内部表格tooltip
- 步骤三 通过检查元素，修改编辑器display:none,
![微信图片_20201211114257](https://user-images.githubusercontent.com/26407895/101868629-ba446d80-3bb8-11eb-8c39-165398219ffc.png)

**Comment by echoLC** [comment]
我们先跟进下这个问题

**Comment by UltramanWeiLai** [comment]
这个问题可以移步到 #2511 中去跟踪，需要说明的是，走销毁 api 会清除 tooltip，但是直接对 dom 操作的话，可能不会。
