### ISSUE TITLE
一个页面有多个富文本时拖拽图片无法正常使用

### ISSUE THREAD

**Issue by Cyearn** [wangeditor-team/wangEditor#2620]
## bug 描述

当我在一个页面内使用了两个富文本时，我想要将一张照片从本地拖拽到第一个富文本中，但是他却出现在了第二个富文本中

## 你预期的样子是？

拖到哪个富文本图片就进入哪个富文本中

## 浏览器及版本号

Chrome浏览器 版本 87.0.4280.88（正式版本） （64 位）

## wangEditor 版本

"wangeditor": "^4.1.0",

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
创建一个具有两个编辑器的wangeditor
```
<>
    <div id='editor1' className='text' style={{ width: '50%' }}></div>
    <div id='editor2' className='text' style={{ width: '50%'}}></div>
</>
```
- 步骤二
调用该组件
- 步骤三
从本地拖拽图片到第一个富文本

**Comment by blackhu0804** [comment]
上述情况未复现，如果问题依然存在，请再提供一下复现的详细路径。

**Comment by GeorgeDL001** [comment]
我也遇到了同样的问题，页面中引用多个wangeditor后，将一个图片拖拽到第一个wangeditor之后，图片会自动出现在最后一个wangeditor中，无论如何拖拽，图片只能出现在最后一个wangeditor中。
