### ISSUE TITLE
如果先对文字进行有序列表，然后再进行标题操作，会导致文字的上边距无限增大这个问题

### ISSUE THREAD

**Issue by yw8820** [wangeditor-team/wangEditor#2621]
## bug 描述

*如果先对文字进行有序列表，然后再进行标题操作，会导致文字的上边距无限增大，字体也会无限增大这个问题*

## 你预期的样子是？

*互不影响*

## 浏览器及版本号

*谷歌*

## wangEditor 版本

*4.5.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
如果先对文字进行有序列表，然后再进行标题操作，会导致文字的上边距无限增大，字体也会无限增大这个问题*

**Comment by UltramanWeiLai** [comment]
这里的话，我们不推荐对序列使用标题，因为这样会让 ul 或者 ol 标签 被 h[x] 标签包裹，而不是你心里想的对 li 标签内的内容进行 h[x] 的包裹，并且导致回车跳不出 h[x] 的范围。关于这个我会新建个 issue 对 标题按钮 做限制，不让它对不应该设置的 段落 起作用
