### ISSUE TITLE
全选后点击code，内容被嵌入到code标签中了

### ISSUE THREAD

**Issue by rsl140** [wangeditor-team/wangEditor#2623]
## bug 描述

当全选编辑器中的内容后点击code，内容被嵌入到code标签中了

## 你预期的样子是？

点击code后弹出插入代码的窗口

## 浏览器及版本号

版本 87.0.4280.88

## wangEditor 版本

v4.5.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
在编辑器内输入文字后全选
- 步骤二
点击code

**Comment by wangfupeng1988** [comment]
我觉得这个不用修改。这属于非常见、非正规操作
本来应该是，选中一个单词，点击 code 菜单，生成行内 code 。
![image](https://user-images.githubusercontent.com/9583120/103268678-db95be00-49ee-11eb-8126-e28c970b08be.png)
