### ISSUE TITLE
新版本无法【直接复制图片-粘贴-走自定义上传逻辑】,  老版本可以

### ISSUE THREAD

**Issue by sorakylin** [wangeditor-team/wangEditor#2625]
## bug 描述

老版本(4.0.3) 一直可以使用的，新版本无法使用了。 **复制粘贴图片,  走自定义的 customUploadImg() 逻辑**
已在本地切换不同的版本进行复现，  可100%复现

## 你预期的样子是？

新版本应该恢复此功能

## 浏览器及版本号

Google Chrome 87.0.4280.88

## wangEditor 版本

老版本 4.0.3,  新版本4.5.3

## 官网能否复现该 bug ？

不能,  因为官网是复制粘贴图片原链接的

## 最小成本的复现步骤

- 设置 editor.config.pasteIgnoreImg = true
- 自定义 editor.config.customUploadImg() 方法
- 随便在网络上找个右键可以复制的图片，  右键复制
- 在编辑器中粘贴 (使用 ctrl+v  或 右键粘贴均可)

**老版本可以成功走 customUploadImg 逻辑,  新版本则无事发生**

**Comment by UltramanWeiLai** [comment]
请问 uploadImgServer 有配置吗？没有可以试试配置了后再看

**Comment by skypyb** [comment]
> 请问 uploadImgServer 有配置吗？没有可以试试配置了后再看

没有配置 uploadImgServer ， 因为需要的是 **走自定义的逻辑** , 即 customUploadImg() 方法。 而新版本是无法实现这个功能的。  
奇妙的是老版本却有这个功能， 不知为何新版本给删了?

**Comment by wangfupeng1988** [comment]
新版本没有故意删除，这个需要排查一下。

**Comment by wangfupeng1988** [comment]
@clinfc 看下这个问题能否复现？

**Comment by clinfc** [comment]
> @clinfc 看下这个问题能否复现？

能复现，直接复制图片粘贴进来，不仅自定义上传图片有问题，存为 base64 和 上传到服务器都存在该问题

**Comment by yuntian001** [comment]
QQ 或者微信 截屏的图片 可以直接粘贴，但是右键复制的图片不支持粘贴

**Comment by misterpancn** [comment]
同样的问题，原来3.1.1可以，现在4.6.4。ctrl+v粘贴图片无事发生。
等一个更新🙄

**Comment by mutouzdl** [comment]
我粘贴图片也是没反应，是需要配置吗？
版本：4.6.6
