### ISSUE TITLE
自定义上传图片设置参数问题

### ISSUE THREAD

**Issue by gaoshiyong1272** [wangeditor-team/wangEditor#2627]
## bug 描述

*
因为我们使用的是七牛云存储上传，
希望使用自定义文件图片名称，希望每张图片都是唯一的，因为七牛存储，a.jpg 改完b.jpg，返回的hash是一样的，所以需要使用自定义key值，这个key只能在点击图片的时候生产，目前咱们自定义上传图片的参数是预定义固定死的，是否可在进行动态添加*

## 你预期的样子是？

*希望点击选择图片的时候对上传图片参数进行二次修改（editor.config.uploadImgParams）*

## 浏览器及版本号

*87.0.4280.88*

## wangEditor 版本

*4.0.3*

## 官网能否复现该 bug ？

能

**Comment by UltramanWeiLai** [comment]
虽然不是很明白你的意思，但是我们这边有提供 自定义上传 的方法，完全自主，不需要进行任何配置，理论上是能满足你的需求的。
![image](https://user-images.githubusercontent.com/23336585/102007661-fec13c00-3d65-11eb-99f9-cf2dc8b461bc.png)

**Comment by UltramanWeiLai** [comment]
该问题长时间没人答复，暂且关闭
