### ISSUE TITLE
Vue2.x 最简单的使用报错

### ISSUE THREAD

**Issue by changxinjie** [wangeditor-team/wangEditor#2630]
## bug 描述
版本 4.5.3,  
![image](https://user-images.githubusercontent.com/9565184/102036223-3a5b1500-3dfd-11eb-92d8-bda7701dd621.png)

报错信息

![image](https://user-images.githubusercontent.com/9565184/102035921-9b361d80-3dfc-11eb-8f38-ddc27f4de130.png)

取消47行注释, 又报这个错.

![image](https://user-images.githubusercontent.com/9565184/102035983-bc970980-3dfc-11eb-8513-b7285f14d026.png)

**Comment by UltramanWeiLai** [comment]
老哥，你这种 editor.config = {  xxx } 的配置，直接就把配置项清空了。 vue的demo官网上有demo可供下载和学习
