### ISSUE TITLE
在Ant Design of React 的<Form>组件中使用wangeditor，直接点击“插入”，会响应Form表单的提交的方法

### ISSUE THREAD

**Issue by wangmy-web** [wangeditor-team/wangEditor#2634]
### bug 描述
在**Ant Design of React** 的Form组件中使用wangeditor，直接点击链接、网络图片、视频“插入”，会响应Form表单的提交的方法(onFinish/onFinishFailed)

### 你预期的样子是？
点击插入不应该响应Form表单的提交的方法

### 浏览器及版本号
版本 87.0.4280.88（正式版本） （64 位）

### wangEditor 版本
V4.5.2

### 官网能否复现该 bug ？
要在Ant Design of React 的Form组件中，作为<Form.Item>的一项使用才会出现

### 最小成本的复现步骤
**插入连接：**
  1.文字和链接地址都不填，直接点击“插入”会出现；
  2.只填文字，不填链接地址，然后点击插入；
**插入网络图片：**
  1.不输入图片地址直接点击“插入”
  2.输入地址然后点击“插入”
**插入视频**
  1.什么都不输入直接点击“插入”

以上每种操作都会出现这个问题...

**Comment by UltramanWeiLai** [comment]
请更新到 4.5.3 版本即可解决
