### ISSUE TITLE
编辑器默认字体颜色

### ISSUE THREAD

**Issue by gitxinyi** [wangeditor-team/wangEditor#2635]
## 问题描述
怎么设置编辑器默认字体颜色
 
## wangEditor 版本
 V4

**Comment by UltramanWeiLai** [comment]
你外部写 style 就可以了。
或者 初始化编辑器的时候把 `<p><font face="黑体" color="#f9963b"><br></font></p>` 这段作为默认值初始化看看。
要默认颜色和字体，写 style 即可
