### ISSUE TITLE
react使用富文本编辑器，切换为英语失败

### ISSUE THREAD

**Issue by letterSmall** [wangeditor-team/wangEditor#2636]
## 问题描述

react使用富文本编辑器，安装 i18next后，使用英语版本失败

## wangEditor 版本

"wangeditor": "^4.0.0"

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

下载react结合案例（https://github.com/wangeditor-team/wangEditor-with-react）
安装：npm i -S i18next
使用：editor.config.lang = 'en'
           editor.i18next = window.i18next
           editor.create()

**Comment by letterSmall** [comment]
为出现报错，界面还是中文显示

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/102190639-3f01f500-3ef3-11eb-893f-02abd3550551.png)
