### ISSUE TITLE
输入内容后，撤销报错

### ISSUE THREAD

**Issue by RememberHearts** [wangeditor-team/wangEditor#2638]
## bug 描述

*输入一些内容后，不断撤销输入，会报错*

## 你预期的样子是？

*请输入内容后，撤销不报错*

## 浏览器及版本号

*Chrome 88.0.4292.2*

## wangEditor 版本

*wangeditor@4.5.3*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：输入一些内容
- 步骤二：不断撤销
- 步骤三：报错

## 报错内容

`IndexSizeError: Failed to execute 'setStart' on 'Range': The offset x is larger than the node's length (y).`
`xxx/wangEditor/src/editor/history/data/range/index.ts:114`

**Comment by echoLC** [comment]
官网不能重现，我们很难定位到问题，麻烦在仔细描述重现的步骤

**Comment by RememberHearts** [comment]
现在没有出现了。只有昨天出现了
