### ISSUE TITLE
申请添加对于如何进行内容编辑的使用帮助说明文档。

### ISSUE THREAD

**Issue by qqii3184** [wangeditor-team/wangEditor#2640]
## bug 描述

缺少使用文档说明，许多使用上的问题没有一个合适的文档。
GitHub也好，官网也好，所有的doc都只针对程序员如何在网页上加载编辑器做出说明
但是对使用此编辑器的网页内容编辑人员来说，许多操作说明并不明确。
比如如果想要实现一个复杂的图文混排该如何进行编辑？如何更方便的调整表格的大小和宽度？
这种针对电脑盲的使用说明文档及其缺乏。

## 你预期的样子是？

增加针对非程序开发人员的使用教程文档

## 浏览器及版本号

chrome87+

## wangEditor 版本

4.5.0

## 官网能否复现该 bug ？

能,因为根本没有此方面的文档。

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
看DOC就知道了，没有操作说明，只有如何在程序里加载编辑器
没有如何使用此编辑器编辑内容的说明。

**Comment by echoLC** [comment]
我们根据用户反馈考虑，如果如果这个需求有比较多的用户需要，我们会考虑加。

**Comment by qqii3184** [comment]
我想说的是，99%会在github反馈问题的都是程序员，只有极个别的网站编辑会使用github，而几乎所有的程序员在把editor加入项目之后并不会真正的使用他们，只会根据网站的功能需求增加或减少功能，也不会针对editor的使用对网站编辑进行培训或者有耐心的说明，大部分人都是你自己研究一下就会了的意思，所以。。。根据github反馈来确定是否有很多用户有这个需求并不准确，因为程序员没必要使用编辑器，而作为使用者的网站编辑不会反馈。。。。

**Comment by qqii3184** [comment]
> 我们根据用户反馈考虑，如果如果这个需求有比较多的用户需要，我们会考虑加。

其实很多网站内容编辑人员并不知道自己用的在线编辑器到底叫什么名字，以及遇到问题该如何反馈问题，他们大部分的操作是向开发人员询问，这个该怎么操作，而开发人员通常的回答是：你自己研究一下。。。或者之类的话，因为开发人员不是使用者，他们也不会完全掌握编辑器的具体用法。同样的，开发人员在反馈问题时并不会反馈操作问题而大部分时候反馈的都是代码bug，如果不牵扯到代码级别的处理，仅仅使用上的疑惑是不会提交issue的。因而到底有多少编辑在使用上遇到困难在自己想办法处理或者干脆放弃编辑，采用其它的处理方式不得而知。仅靠issue来考虑是否增加文档，我个人感觉不太准确。

**Comment by UltramanWeiLai** [comment]
我个人持有这样一个态度，我们提供的是一个工具，主要面向的也是程序员。
而且使用者(程序员)也会根据业务需求对编辑器进行二次开发。
至于 *图文混排* 我觉得这是属于个人能力个人技能上的东西，市面上那么多关于 word 使用的教程一大堆，富文本编辑器都是往 word 看齐的，而且功能相对来说也没有 word 那么复杂，一般人都知道如何去使用，至于如何使用的好就是个人软技能了。
哪怕需要 使用文档 这也应该属于公司或者网站提供方才需要出具的内容。

**Comment by UltramanWeiLai** [comment]
编辑器拥有的功能和能力，整个按钮一个试一遍就基本都了解，不外乎 标题 加粗 序列 斜体 下划线 颜色 大小 字体 背景色 等等。
哪怕我们出了 使用说明 也只可能是介绍每个按钮的功能，能做啥事情，想要玩出花来，还得看个人理解和能力

**Comment by wangfupeng1988** [comment]
第一，wangEditor 目前功能比较简单，也是轻量级的项目，所以我们预期它应该是傻瓜式的，0 学习成本的。当然是对于了解电脑的人，电脑盲也不在我们考虑范围之内。所以，我们会继续努力做好用户体验，而不是搞一个文档来教大家怎么用，我们还达不到这种复杂程度。
第二，你说的这种方式，我们想不出该怎么实现。假如，现在就有一个你预期的文档，那我们也只能是放在官网上。那如你所说，使用者连我们的编辑器是啥都不知道，他也不可能知道我们的官网，也找不到这份文档。反过来，他如果能找到我们的官网，那至少可以假如我们的 qq 群，群里肯定会有人乐意帮助他的。

所以，从各个方面综合考虑，暂不能接收你的这个建议。
但是无论如何也要感谢你对产品的关注和支持，thx ！
