### ISSUE TITLE
插入的表格不能手动调整

### ISSUE THREAD

**Issue by qqii3184** [wangeditor-team/wangEditor#2641]
## bug 描述

表格插入编辑器后，不能手动调整行列宽高

## 你预期的样子是？

可以像word那样调整行列宽高

## 浏览器及版本号

chrome87

## wangEditor 版本

4.5.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

点击插入表格
然后就可以看见，表格无法拖动，无法调整大小，不能调整边框样式

**Comment by UltramanWeiLai** [comment]
目前我们暂时可能不会考虑去支持这个功能，复杂度非常高，我们目前以优先稳定编辑器现有功能为主。
