### ISSUE TITLE
上传多个图片的时候自定义的filename 后面会加上1、2、3，应该改成增加'[]'

### ISSUE THREAD

**Issue by scalaview** [wangeditor-team/wangEditor#2642]
https://github.com/wangeditor-team/wangEditor/blob/7a7df9e59c1f4f1eaccdd86667b6b649dfce22d3/src/menus/img/upload-img.ts#L165

**BUG描述**：
比如自定义了一个filename = 'files'
上传多个文件的时候，form-data的name 应该要使用 files[]，而不是files1, files2......
正确的应该是这样子：
------WebKitFormBoundaryhvACva6nj1QRZbgY
Content-Disposition: form-data; name="**files[]**"; filename="QQ20201208-152614.png"
Content-Type: image/png

------WebKitFormBoundaryhvACva6nj1QRZbgY
Content-Disposition: form-data; name="**files[]**"; filename="QQ20201208-152602.png"
Content-Type: image/png

------WebKitFormBoundaryhvACva6nj1QRZbgY--

而现在是files后面加了 1， 2， 3
------WebKitFormBoundaryhvACva6nj1QRZbgY
Content-Disposition: form-data; name="**files1**"; filename="QQ20201208-152614.png"
Content-Type: image/png

------WebKitFormBoundaryhvACva6nj1QRZbgY
Content-Disposition: form-data; name="**files2**"; filename="QQ20201208-152602.png"
Content-Type: image/png

------WebKitFormBoundaryhvACva6nj1QRZbgY--

这样导致使用服务端Interceptor限制上传文件的参数名字时没法匹配。

参考链接：
https://stackoverflow.com/questions/12989442/uploading-multiple-files-using-formdata
http规范：
https://tools.ietf.org/html/rfc1867

**Comment by UltramanWeiLai** [comment]
请按照模板提交 issue 否则是不受理的。
另外关于 字段名 的个设置，如果和你业务逻辑有冲突，完全可以使用 自定义上传 的配置项进行处理。
