### ISSUE TITLE
placeholder属性中包含英文句点. 会无法渲染placeholder

### ISSUE THREAD

**Issue by ywandy** [wangeditor-team/wangEditor#2643]
## bug 描述
placeholder属性中包含英文句点. 会无法渲染placeholder
![image](https://user-images.githubusercontent.com/5309008/102333663-b2296b00-3fc8-11eb-8e31-d01514716594.png)

![image](https://user-images.githubusercontent.com/5309008/102333718-c1101d80-3fc8-11eb-82cb-6aefac4b987e.png)

如果不带英文句点 . 
![image](https://user-images.githubusercontent.com/5309008/102333754-d08f6680-3fc8-11eb-8934-daf4587e8947.png)
![image](https://user-images.githubusercontent.com/5309008/102333773-d5541a80-3fc8-11eb-99f3-257ea6d3ef4f.png)

经过查看源码，是因为i18next.t()里面的英文句点. 是关键字，所以导致失效
![image](https://user-images.githubusercontent.com/5309008/102333859-eef56200-3fc8-11eb-8171-7434a06f0416.png)

## 你预期的样子是？

placeholder包含英文句号. 后能正常显示

## 浏览器及版本号
chrome 版本 87.0.4280.88（正式版本） (x86_64)

## wangEditor 版本

4.3.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 在placeholder中包含英文句号 . 将会导致placeholder无法显示

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/102511868-43c9d300-40c4-11eb-9eaa-469785ebc7c4.png)
你不要在 key 上带 .  呀
![Uploading image.png…]()

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复，暂且关闭

**Comment by ywandy** [comment]
> 你不要在 key 上带 . 呀

哪个key?

**Comment by UltramanWeiLai** [comment]
> > 你不要在 key 上带 . 呀
> 
> 哪个key?

如上图所示
key 指的是 对象的 键
```
{
    key: 'value....' // 可以用
    'key...': 'value....'// 不能用
    不过话说，模板里面是没有 key 是带 .  的把
}
```
