### ISSUE TITLE
上传图片的时候能否直接点击选择图片

### ISSUE THREAD

**Issue by yedonensis** [wangeditor-team/wangEditor#2645]
## 功能描述

*目前的功能是，点击上传图片的时候会出现一个弹窗出来，然后提供网络图片以及本地图片上传，能否直接点击图片icon 就出现文件选择器*

## 提炼几个功能点

- 提供选择是否出现弹窗
- 点击图片icon 直接出现选择器

## 原型图

*ui 改动就是可以有不出现弹框的选择*
![图片](https://user-images.githubusercontent.com/38917059/102436129-db8ed900-4052-11eb-9118-174ed98319f0.png)

## 可参考的案例

*类似input 框上传一样点击之后直接出现文件选择器*

**Comment by yuwenlong** [comment]
那不就没法加网络图片了？

**Comment by UltramanWeiLai** [comment]
目前有在做类是的功能，当设置了只有上传图片的时候，可以直接唤起文件选择器，可以移步到 #2585 当中跟进
