### ISSUE TITLE
使用这个页面是空白的，加载不出来

### ISSUE THREAD

**Issue by Flyooofly** [wangeditor-team/wangEditor#2648]
你好，我使用这个，但是页面一片空白，并不报错，但是就是加载不出来，我确定自己的路由没写错，组件也export了，但其实他好像是有东西的，麻烦帮忙看下，谢谢
![image](https://user-images.githubusercontent.com/31236750/102512500-129dd280-40c5-11eb-8bc6-b8e2f32fd648.png)

**Comment by UltramanWeiLai** [comment]
请按照模板来提交 issue 否则是不受理的。
你这个，我看不到图片，vue react 都是有 demo 有问题可以去参考一下，没报错没加载，函数没有运行也可能是原因，先试着调试看断点能进 创建 哪里吧。
