### ISSUE TITLE
插入视频链接的时候，在ie11 下， input框会下沉

### ISSUE THREAD

**Issue by LuoRiWuSheng** [wangeditor-team/wangEditor#2650]
## bug 描述
富文本插入视频链接，打开那个插入面板， input框在ie11 下，会出现下沉， 当失焦的时候，会正常

## 你预期的样子是？
无论是否是 focus 聚焦， input框的内容，不应该出现上下抖动

## 浏览器及版本号
ie11

## wangEditor 版本
 "wangeditor": "^4.5.2",

## 最小成本的复现步骤
在ie11 的环境下打开官网，尝试复现即可

## 解决办法
请增加 input的 line-height 属性， 且 line-height 的值和 height 保持一致  ，即可解决， 这个bug只在 ie上出现，是兼容性bug

`.w-e-panel-tab-content input {`
    `       height: 20px;`
    `       line-height: 20px;`
`}`

**Comment by UltramanWeiLai** [comment]
emmm 我这边 ie11 的时候没有发现下沉的情况。

**Comment by LuoRiWuSheng** [comment]
> emmm 我这边 ie11 的时候没有发现下沉的情况。

我看给你做一个 gif 图，看看效果

**Comment by wangfupeng1988** [comment]
@clinfc 试一试能否复现？

**Comment by clinfc** [comment]
> @clinfc 试一试能否复现？

未能复现

**Comment by UltramanWeiLai** [comment]
> > emmm 我这边 ie11 的时候没有发现下沉的情况。
> 
> 我看给你做一个 gif 图，看看效果

我们这边多人测试皆无法复现，且由于你长时间没有回复，所以暂且关闭该问题，如还有疑问可以重新提交一个 issue 也可以在群里进行交流。
