### ISSUE TITLE
使用退格键删除编辑器内容后，编辑器获取到的html()仍有数据

### ISSUE THREAD

**Issue by qqii3184** [wangeditor-team/wangEditor#2653]
## bug 描述

若编辑器使用JS加载内容，则手动使用退格键删除所有内容后
使用editor.txt.html()获取编辑器内的数据，仍可获取到一个空格。

## 你预期的样子是？

数据应为空，而不是有个空格。

## 浏览器及版本号

chrome87+

## wangEditor 版本

4.5.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- editor.create();
- editor.txt.html(文本内容);
- 步骤二
- 手动删除编辑器的全部内容
- 步骤三
- 使用console.log(editor.txt.html().length)输出文本长度可以看到文本长度为1
- 使用console.log(editor.txt.html()+"文本结束")输出内容，可以看到文本结束前有一个空格

**Comment by echoLC** [comment]
我试了下，没有重现

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
