### ISSUE TITLE
当编辑器菜单很少时候，panel类型菜单显示位置不正确，如图片上传、插入表格等

### ISSUE THREAD

**Issue by iskyshop** [wangeditor-team/wangEditor#2654]
## bug 描述

当编辑器菜单很少时候，panel类型菜单显示位置不正确，如图片上传、插入表格等，如下：

## 你预期的样子是？
panel菜单都在对应按钮下方

## 浏览器及版本号

chrome 版本 87.0.4280.66（正式版本） （64 位）

## wangEditor 版本

最新demo里面的版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 删除菜单，只保留2-3个，要保留图片上传、插入表格等panel类型菜单

**Comment by echoLC** [comment]
已重现，受理

**Comment by iskyshop** [comment]
var left = (rect.width - width) / 2 + rect.left - menuRect.left; 改为 var left = (rect.width - width) / 2 就可以了

**Comment by iskyshop** [comment]
修改为 left=0；即可，margin-left是相对父级的

**Comment by wangfupeng1988** [comment]
我们所有的 panel 设置，都是菜单栏居中的，不是定位到按钮下面。

![image](https://user-images.githubusercontent.com/9583120/102606743-3105db80-4162-11eb-9221-e057234cda32.png)


如果你菜单很少，那建议你把菜单栏宽度缩小，就看起来正常了。
