### ISSUE TITLE
自定义扩展菜单后 点击富文本输入区域就报错

### ISSUE THREAD

**Issue by wannghao** [wangeditor-team/wangEditor#2655]
![image](https://user-images.githubusercontent.com/38241197/102690028-9da1d880-423d-11eb-8e4d-31f36d9dedd7.png)
![image](https://user-images.githubusercontent.com/38241197/102690034-a692aa00-423d-11eb-9686-4cd13233f0e8.png)
这个是自定义模块的代码
![image](https://user-images.githubusercontent.com/38241197/102690049-c1651e80-423d-11eb-8eb1-5efcfb21e376.png)

**Comment by wannghao** [comment]
图片好像异常了 我贴代码进来把
`Uncaught TypeError: Cannot read property 'bind' of undefined
    at module.exports (wangEditor.js?6fad:38650)
    at eval (wangEditor.js?6fad:64689)
    at Array.forEach (<anonymous>)
    at Menus.changeActive (wangEditor.js?6fad:64684)
    at HTMLDivElement.saveRange (wangEditor.js?6fad:54064)`

这个是我自定义菜单的代码
`class SaveMenu extends BtnMenu {
            constructor(editor: PdCAny) {
                const $elem = E.$(
                    `
            <div class="w-e-menu">
               <svg class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg"
                     width="20" height="20">
                 <path d="M725.333333 128H213.333333a85.333333 85.333333 0 0 0-85.333333 85.333333v597.333334a85.333333 85.333333 0 0 0 85.333333 85.333333h597.333334c46.933333 0 85.333333-38.4 85.333333-85.333333V298.666667l-170.666667-170.666667z m-213.333333 682.666667c-70.826667 0-128-57.173333-128-128s57.173333-128 128-128 128 57.173333 128 128-57.173333 128-128 128z m128-426.666667H213.333333V213.333333h426.666667v170.666667z"
                 ></path>
               </svg>
            </div>
            `
                );
                super($elem, editor);
            }

            // 菜单点击事件
            clickHandler() {
                _that.eventBus.$emit('saveEditor');
            }
        }`

**Comment by jerexyz** [comment]
![image](https://user-images.githubusercontent.com/5208531/102716299-f80e6800-4315-11eb-97be-a43ac4910559.png)
这里为什么会多了一个`selector`?参照一下文档的例子，如果还有问题请尽量提供一个完整可复现的repo

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
关于自定义菜单的使用，使用文档有，群公告里面也有视频教程，都可以去看。

**Comment by biology-w** [comment]
我也是报错了
![image](https://user-images.githubusercontent.com/25600705/103765329-fa7ffa00-5057-11eb-93e2-fd9544c0897d.png)
Cannot read property 'bind' of undefined
![image](https://user-images.githubusercontent.com/25600705/103765288-e936ed80-5057-11eb-9d49-409e3318b2b2.png)

**Comment by iysf** [comment]
我debug了半天，终于找到你们所言的错误和问题了。

其实最终还是在自定义菜单栏的时候，没有将tryChangeActive方法加到class中。

假如tryChangeActive在class的属性上，那这个问题就不会出现。
