### ISSUE TITLE
将editor封装成了组件，如何在引用组件的页面使用多个editor

### ISSUE THREAD

**Issue by Oujiax** [wangeditor-team/wangEditor#2656]
## 问题描述
用vue写的项目，把富文本框封装成了自定义组件，在引用的页面无法使用多个富文本框
*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*
## 是否查阅了文档 ？
是
（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 邮箱1120545164@qq.com
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请按照问题模板，填写复现问题的步骤，或者给出复现问题的源码。否则 issue 不予受理。
我先关闭该 issue ，你再按照规定重新提交一个吧。
