### ISSUE TITLE
自定义panel

### ISSUE THREAD

**Issue by coco123118** [wangeditor-team/wangEditor#2657]
## 问题描述
我想实现一个自定义的panel菜单，需要怎么做？官方文档是提示参考video，但是没有看懂，第一次使用有点懵，急求
*请输入遇到的问题...*

## wangEditor 版本
最新版本
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
![`](https://user-images.githubusercontent.com/9583120/102706830-38e38e00-42d0-11eb-8248-a19d422f332c.png)

**Comment by wangfupeng1988** [comment]
我在 qq 群回复你了。
