### ISSUE TITLE
代码高亮没作用

### ISSUE THREAD

**Issue by Python-Jay** [wangeditor-team/wangEditor#2661]
## 问题描述
*<link href="http://cdn.bootcss.com/highlight.js/8.0/styles/monokai-sublime.min.css" rel="stylesheet">
这个CDN无法访问了*
## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

**Comment by Python-Jay** [comment]
> ## 问题描述
> _ 这个CDN无法访问了_
> <link href="http://cdn.bootcss.com/highlight.js/8.0/styles/monokai-sublime.min.css" rel="stylesheet">
> 
> ## 是否查阅了文档 ？
> （文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）
> 
> _是_

**Comment by Python-Jay** [comment]
<link href="http://cdn.bootcss.com/highlight.js/8.0/styles/monokai-sublime.min.css" rel="stylesheet">

**Comment by Python-Jay** [comment]
http://cdn.bootcss.com/highlight.js/8.0/styles/monokai-sublime.min.css

**Comment by hahaaha** [comment]
麻烦按照模板填下问题。。。我们需要更多的信息
