### ISSUE TITLE
toolbar上的menu按钮，不使用button，而用div的原因是什么

### ISSUE THREAD

**Issue by fubd** [wangeditor-team/wangEditor#2662]
## 问题描述

toolbar上的menu按钮，不使用button，而用div的原因是什么？

用div，已经选择的文字会闪一下再恢复被选状态。用button的话不会有这个情况。

## wangEditor 版本

latest

**Comment by hahaaha** [comment]
麻烦重新提个issue 按照模板写一下复现步骤
