### ISSUE TITLE
用iexplore浏览器访问,粘贴图片的时候会变成Base64的方式存入并展现

### ISSUE THREAD

**Issue by luoxiaofeng1029** [wangeditor-team/wangEditor#2663]
## bug 描述

配置设置的是上传图片而非base64.基本所有粘贴都没问题,比如微信截图,粘贴.是先自动上传图片再返回URL的.但是今天有用户用d电脑自带的iexplore访问项目,然后粘贴,贴的图片没上传,就直接以base64的形式展现在了文本框(用户看到的还是图片粘贴上去的样子).导致存入数据库数据过大.

## 你预期的样子是？

在我配置正确的情况下,我预期的是只要粘贴进去的是图片,就应该自动上传图片

## 浏览器及版本号
![image](https://user-images.githubusercontent.com/50006313/102977775-6fbedb80-453e-11eb-9dce-68db5b029ed6.png)

## wangEditor 版本

4.0.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

用自带的IE浏览器截图看图片的属性就知道了

**Comment by wangfupeng1988** [comment]
所有与粘贴相关的行为，都不支持 IE11 。
包括你提到的粘贴图片，
也包括粘贴过滤的各种配置 http://www.wangeditor.com/doc/pages/06-%E7%B2%98%E8%B4%B4%E8%BF%87%E6%BB%A4/
