### ISSUE TITLE
建议在插入视频的时候，给 src增加一个时间戳的query参数

### ISSUE THREAD

**Issue by LuoRiWuSheng** [wangeditor-team/wangEditor#2664]
## 功能描述
希望我们插入的视频功能， 能将 iframe 的 src 或者 video 的source 提供一个 uuid 或者 时间戳

因为我们这边在ie11 中测试， 视频的插入，如果第一次插入以后，直接刷新页面，再插入，会出现视频格式不对的情况

ie的默认设置，请一定按照这样设置去复现，因为这是站在用户的角度去使用产品，用户是不会去清空缓存等操作的

用户的默认设置如下：

ie--》设置 --》 internet 设置 

![295c22d0-6b25-44ca-9e72-c482fd924ce4](https://user-images.githubusercontent.com/23192097/102780943-c955c780-43d1-11eb-909a-8eb4edc12543.png)

![bfd3a735-455a-4aeb-905b-a9a0b6957002](https://user-images.githubusercontent.com/23192097/102780948-cb1f8b00-43d1-11eb-924c-9f30db521355.png)

![85d8da2a-b4c2-430e-8bbe-146a9fa710b6](https://user-images.githubusercontent.com/23192097/102780950-d07cd580-43d1-11eb-98a6-f5a9e58e6030.png)

![efc971cf-d13d-43a5-8d20-0a6ae8c0c4c6](https://user-images.githubusercontent.com/23192097/102780955-d2df2f80-43d1-11eb-8ac4-9665753397b8.png)

如上，是用户ie11 的默认设置

且 http的状态  我看到的是   304  本地缓存

![image](https://user-images.githubusercontent.com/23192097/102781962-7d0b8700-43d3-11eb-9656-a3e867da8872.png)

如果能提供对外的前置接口， 比如可以让开发者 自己去拼接这个时间戳也行， 或者富文本内部帮我们做了

另外，我们的 http接口，也是在 ie11中发现，会存在一个问题， 即  http://xxx/api/getList   如果不加时间戳， 当 getList的内容出现更新， ie11 中第二次拿到的还是脏数据， chrome 是正常的， 所以，我们这边是在接口中 加入一个 ?_t=时间戳  解决整个项目在 ie11 下的痛点问题

## 原型图

无

## 可参考的案例

无

**Comment by LuoRiWuSheng** [comment]
测试数据

<iframe src="//player.bilibili.com/player.html?aid=202990002&bvid=BV1Ha411F7QD&cid=259603994&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>

<video poster="" controls="controls" width="100%" height="100%"><source src="https://blz-videos.nosdn.127.net/1/OverWatch/AnimatedShots/Overwatch_AnimatedShot_Bastion_TheLastBastion.mp4" /></video>


其实如果对外暴露一个前置接口，可能会让富文本内部的处理比较麻烦，因为开发者各式各样的方式对src二次处理，会导致不可控的因素

**Comment by LuoRiWuSheng** [comment]
我的 ie版本  11，
wangEditor 4.5.2
window 10

**Comment by blackhu0804** [comment]
有插入视频前的校验函数，可以自定义规则
