### ISSUE TITLE
ie下 插入的视频和chrome 存在差异，且ie只能通过右键控制播放

### ISSUE THREAD

**Issue by LuoRiWuSheng** [wangeditor-team/wangEditor#2665]
## bug 描述
ie下 插入的视频和chrome 存在差异，且ie只能通过右键控制播放

![image](https://user-images.githubusercontent.com/23192097/102783069-5a7a6d80-43d5-11eb-8836-1f0b2b8b19e2.png)

ie 11 中 视频的播放，只能通过右键，无法点击播放按钮，或者全屏按钮，也无法拖动视频快进

## 你预期的样子是？
期待外观和操作方式一致

## 浏览器及版本号

windwo 10

ie11 版本

## wangEditor 版本

wangEditor 4.5.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
window 10 电脑

ie 11 ，去官网复现

**Comment by blackhu0804** [comment]
这个属于浏览器表现的差异问题。
