### ISSUE TITLE
渲染数据时 会多出 首行 空格

### ISSUE THREAD

**Issue by GenuineYangShuai** [wangeditor-team/wangEditor#2666]
## 问题

使用官方网站 的 `editor.txt.append() ` 追加新的数据   渲染会进行 首行 默认换行 

## 你预期的样子是？

*不进行首行空格*

## wangEditor 版本

*官方网站 版本**

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤
不太确定如何实现的

**Comment by hahaaha** [comment]
编辑器内容为空时，会自动增加一个<p><br></p>。。。append后会插入空行之后

**Comment by hahaaha** [comment]
编辑器内容为空时，会自动增加一个`<p><br></p>`。。。append后会插入空行之后

**Comment by wangfupeng1988** [comment]
这个细节，是应该优化一下
