### ISSUE TITLE
插入的code无法回车无法跳出代码块

### ISSUE THREAD

**Issue by klwfwdk** [wangeditor-team/wangEditor#2670]
## bug 描述

在code中连续回车会新增<code><br></code>

以前以为是功能如此，仔细阅读源码后发现是enter-to-create.ts文件中已经实现的逻辑，但是现在已经失效了。

## 你预期的样子是？

code块中连续回车能够正常跳出代码块

## 浏览器及版本号

chrome，Safari

## wangEditor 版本

release版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

官网的灰色代码块连续回车无法跳出

**Comment by 86driver** [comment]
无内容情况下直接插入代码块， 代码块无法删除

在代码块中间回车 会出现这种情况
![image](https://user-images.githubusercontent.com/38236070/104125415-7e582000-5391-11eb-8fc1-af0062fdfd43.png)
 需要看一下这是不是正常情况

随便输入内容， 选中其生成代码块， 删除代码块内容后再次输入内容始终有背景色
