### ISSUE TITLE
设置HTML的时候，内嵌的style标签的样式影响编辑器外面的样式

### ISSUE THREAD

**Issue by gaograce** [wangeditor-team/wangEditor#2671]
## bug 描述

*我在HTML里面加了个style，做测试的时候，加上了样式div，然后影响到了整个页面*

## 你预期的样子是？

*只影响编辑器内部的样式*

## 浏览器及版本号

*chrome 版本 87.0.4280.88*

## wangEditor 版本

*4.5.4*

## 官网能否复现该 bug ？

能(我在HTML里面加个div，在js里面设置一下HTML，新加的div的文字也是红色的)

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- let html="<style>div {color: red;}</style>"
- 步骤二
- editor.txt.html(html)
- 步骤三
- 然后整个界面所有的文字都红了，，，，

**Comment by blackhu0804** [comment]
你直接设置了页面所有的div，建议设置指定div样式

**Comment by gaograce** [comment]
可能我没有说清楚，我知道样式设置的问题，我想表达的是，编辑器是给用户使用的，我们控制不了用户的行为，希望style的影响范围可以控制在编辑器内部，而不是我随便设置一下，外面样式乱七八糟，影响用户体验啊



---原始邮件---
发件人: "Black"<notifications@github.com&gt;
发送时间: 2020年12月23日(周三) 上午10:28
收件人: "wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送: "Grace"<1101726687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wangeditor-team/wangEditor] 设置HTML的时候，内嵌的style标签的样式影响编辑器外面的样式 (#2671)




 
你直接设置了页面所有的div，建议设置指定div样式

**Comment by UltramanWeiLai** [comment]
> 可能我没有说清楚，我知道样式设置的问题，我想表达的是，编辑器是给用户使用的，我们控制不了用户的行为，希望style的影响范围可以控制在编辑器内部，而不是我随便设置一下，外面样式乱七八糟，影响用户体验啊
> […](#)
> ---原始邮件--- 发件人: "Black"<notifications@github.com&gt; 发送时间: 2020年12月23日(周三) 上午10:28 收件人: "wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;; 抄送: "Grace"<1101726687@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [wangeditor-team/wangEditor] 设置HTML的时候，内嵌的style标签的样式影响编辑器外面的样式 (#2671) 你直接设置了页面所有的div，建议设置指定div样式 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我寻思一个问题，你觉得一个工具类的东西能改变宿主环境的行为吗？
而且这也不是一个 bug 你设置 style 标签并且设置 div 的文字颜色为 red 当然是当前页面所有 div 内的文字都受到这行标签的影响。这就是浏览器的规则。
如果你想要设置默认颜色，你可以给 外围容器 添加 class 并且给出 用于切换的菜单逻辑，保存的时候，把这个值也带到服务器去保存即可
