### ISSUE TITLE
设置默认内容，onchange事件触发返回的内容和默认内容不一致

### ISSUE THREAD

**Issue by ding991** [wangeditor-team/wangEditor#2672]
## bug 描述

使用this.editor.txt.html(value)设置默认内容，onchange事件触发返回的内容和默认内容不一致

## 你预期的样子是？

使用this.editor.txt.html(value)设置默认内容，onchange事件触发返回的内容和默认内容一致

## 浏览器及版本号

谷歌浏览器，版本 87.0.4280.88（正式版本） (x86_64)

## wangEditor 版本

4.4.0

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by blackhu0804** [comment]
请按 issue 模板格式提交
