### ISSUE TITLE
设置默认内容，onchange事件触发返回的内容和默认内容不一致

### ISSUE THREAD

**Issue by ding991** [wangeditor-team/wangEditor#2673]
## bug 描述

设置默认内容，onchange事件触发返回的内容和默认内容不一致

## 你预期的样子是？

设置默认内容，onchange事件触发返回的内容和默认内容一致

## 浏览器及版本号

谷歌浏览器版本 87.0.4280.88（正式版本） (x86_64)

## wangEditor 版本

4.4.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 新建一个编辑器
- 步骤二 监听编辑器的onchange事件
- 步骤三 使用this.editor.txt.html()设置一个初始内容，如果初始内容过多，且初始内容后面有多个换行，则onchange事件返回的值可能和初始内容不一致。

**Comment by wangfupeng1988** [comment]
请举一个详细的 demo 吧。
“如果初始内容过多”—— 你到底初始化了什么内容？可以直接把代码贴出来。

**Comment by ding991** [comment]
this.editor = new E(this.$refs.toolbar, this.$refs.editor)
            this.editor.customConfig = this.editor.customConfig
                ? this.editor.customConfig
                : this.editor.config
            this.editor.customConfig.onchange = html => {
                console.log('html', html) // 绑定当前逐渐地值
            }
            // 创建富文本编辑器
            this.editor.create()
            const value = "<p><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica 
              Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe 
              UI Symbol&quot;;">测试换行符号</span></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>"
            // 设置初始值后，上面onchange事件触发，输出的值与value不一致
            this.editor.txt.html(value)

**Comment by ding991** [comment]
输出的值比初始值少几个换行的标签

**Comment by wangfupeng1988** [comment]
@ding991 据我们测试，只是少了最后一个 `<p><br></p>` ，就一个，不是几个。
![image](https://user-images.githubusercontent.com/9583120/105163425-dc81c180-5b4e-11eb-9ce8-1faf2fdfdfa7.png)

**Comment by wangfupeng1988** [comment]
@lichenabson 提供你一个解决思路。

### 背景

当初要删掉最后一个 `<p><br></p>` 是有一个背景的。就是我们编辑器为了方便用户追加内容，在很多情况下，会自动往编辑器默认追加一个 `<p><br></p>` ，这样末尾有一个空行，方便用户编辑。

但这个空行，对用户造成了困扰。用户觉得这个空行没用，不需要，所以在 `editor.txt.html()` 时给删掉了最后一个空行。

当然，这也就造成了当前的这个问题。

### 解决方案

我们编辑器自动在末尾追加的空行，给一个特殊的标记，例如 `<p data-we-empty-p><br></p>`。这样，我们就能和用户自己添加的 `<p><br></p>` 区分开。

然后，在 `txt.html()` 方法里过滤的时候，只过滤最后的 `<p data-we-empty-p><br></p>` 即可。

这样就解决了问题了。
