### ISSUE TITLE
设置html的时候包含特殊字符，再获取的时候被删除了

### ISSUE THREAD

**Issue by gaograce** [wangeditor-team/wangEditor#2674]
## bug 描述

*设置html的时候包含特殊字符&#8203;，再获取html的时候被删除了*

## 你预期的样子是？

*保持原样*

## 浏览器及版本号

*chrome 版本 87.0.4280.88*

## wangEditor 版本

*4.5.4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
- `editor.txt.html('<p style="margin: 0px 0px 0px 20px; padding: 0px; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; line-height: 1.6; text-align: left; background-color: rgb(255, 255, 255);"><span style="font-size: 13.3333px; font-style: normal; font-weight: 400; font-family: Verdana, &quot;Signika Negative&quot;, Geneva, sans-serif; color: rgb(68, 68, 68);">&#8203;</span></p>');`
- 步骤二
- 然后输出editor.txt.html()
- 步骤三
- 特殊字符&#8203;消失了，我之前的HTML里面这个是用来换行的，特殊字符消失具体表现在空行没了

**Comment by wangfupeng1988** [comment]
为啥要单独设置一个特殊字符呢？这是啥使用场景

**Comment by gaograce** [comment]
从其他地方拷贝的数据，使用特殊字符做为换行



---原始邮件---
发件人: "王福朋"<notifications@github.com&gt;
发送时间: 2020年12月23日(周三) 晚上7:01
收件人: "wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送: "Grace"<1101726687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wangeditor-team/wangEditor] 设置html的时候包含特殊字符，再获取的时候被删除了 (#2674)




 
为啥要单独设置一个特殊字符呢？这是啥使用场景

**Comment by wangfupeng1988** [comment]
使用特殊字符做为换行？搞不懂啥意思

**Comment by wangfupeng1988** [comment]
如果不是常用的场景，我们将延后处理该问题。
毕竟，还有其他高优 issue 需要解决。

**Comment by gaograce** [comment]
其实，不支持特殊字符并不是最大的问题，关键是我第一次设置HTML的时候特殊字符没有删除，显示正常，然后我获取HTML保存之后，特殊字符被删除了，换行没有了，表现在看到的界面和最终保存的界面不一致，如果不支持特殊字符的话，我希望最开始设置的时候就删除它，让表现一致



---原始邮件---
发件人: "王福朋"<notifications@github.com&gt;
发送时间: 2020年12月25日(周五) 上午9:49
收件人: "wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送: "Grace"<1101726687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wangeditor-team/wangEditor] 设置html的时候包含特殊字符，再获取的时候被删除了 (#2674)




 
如果不是常用的场景，我们将延后处理该问题。
 毕竟，还有其他高优 issue 需要解决。

**Comment by gaograce** [comment]
比如，我调研了一下ckeditor，它在我设置的时候直接把特殊字符替换成了&nbsp;

**Comment by clinfc** [comment]
editor.txt.html() 是经过处理了才返回的，不可避免的会过滤掉一些东西，如果你希望获得原始内容的话， 可以考虑用 editor.$textElem.html()，不过这会有许多没必要的内容需要你自己去处理

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭，如还有疑问可以重新进行提交
