### ISSUE TITLE
copy问题

### ISSUE THREAD

**Issue by gaograce** [wangeditor-team/wangEditor#2675]
## bug 描述

*从一个editor里面进行复制到另一个editor里面粘贴，文字的颜色背景色等样式都消失了*

## 你预期的样子是？

*两个editor保持一致*

## 浏览器及版本号

*chrome 版本 87.0.4280.88*

## wangEditor 版本

*4.5.4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 在一个editor里面插入文字，设置颜色背景色，然后全选复制，到另一个空白editor里面粘贴
- 步骤二
- 颜色消失了

从其他人的编辑器里面copy的结果不强求，但是，自己的编辑器互相之间copy都变形了，就不太能接受了

**Comment by rsl140** [comment]
可通过设置 editor.config.pasteFilterStyle = false 来关闭样式过滤。
