### ISSUE TITLE
一段文字用br换行时，无法设置行高，会报错。

### ISSUE THREAD

**Issue by tinkbell** [wangeditor-team/wangEditor#2676]
## bug 描述

当一段文字不是用p标签分段，而是用br来换行时，无法设置行高，会报错。

## 你预期的样子是？

能正常设置行高

## 浏览器及版本号

chrome  87.0.4280.88

## wangEditor 版本

v4.5.3

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

把一段文字直接用br换行，不要用其他标签包裹。

**Comment by rsl140** [comment]
你好，请详细描述下复现步骤

**Comment by tinkbell** [comment]
![image](https://user-images.githubusercontent.com/9738691/102977321-cd065d00-453d-11eb-9acc-73792f0bad8e.png)
然后我设置段落行高，就报以下错误了。
![image](https://user-images.githubusercontent.com/9738691/102977388-e1e2f080-453d-11eb-9cc7-905985c178c6.png)

**Comment by rsl140** [comment]
尝试用editor.txt.html('测试文本测试文本测试文本<br>测试文本测试文本测试文本<br>') 没有复现该问题

**Comment by tinkbell** [comment]
你设置对齐方式，然后再设置行高试试。
![image](https://user-images.githubusercontent.com/9738691/102981654-42752c00-4544-11eb-8b55-f20a9fb920fc.png)

**Comment by gaograce** [comment]
我之前设置行高也出过问题，因为不知道怎么出的问题，后来复现不了，就没有提

**Comment by rsl140** [comment]
没有复现

**Comment by tinkbell** [comment]
你全选文本试试设置行高，还会出现其他bug，最后的一段文字还会被多复制一份，你们的bug太多了。自己都不做完全测试，就用理想的数据做测试，肯定测试不出来。

**Comment by UltramanWeiLai** [comment]
麻烦你端正一下你的态度，你不是我们甲方，你也不清楚我们开发流程，还请为你自己的发言负责。
我很负责任的告诉你，我们有完善的 单元测试、e2e、以及人工测试流程。
我是真的很无语，你自己使用方法有问题就来说是我们的 bug 。
我们编辑区域内容很明确的一行就是一个段落 也就是一个 html 标签，你非要强行用使用 br 作为一行进行回显，那么还请你对编辑器进行合乎你自己要求和规范的二次开发，这属于你们自己的业务逻辑

**Comment by wangfupeng1988** [comment]
不建议用 `<br>` 换行，一个段落用一个 `<p>` 即可。

其实我们研发时，正在极力的规避 `<br>` 带来的很多问题，避之不及。所以你就不要再引入 `<br>` 来凑这个热闹了。

**Comment by wangfupeng1988** [comment]
> 你全选文本试试设置行高，还会出现其他bug，最后的一段文字还会被多复制一份，你们的bug太多了。自己都不做完全测试，就用理想的数据做测试，肯定测试不出来。

这个世界上有两种软件：1. 遍地 bug 的；2. 没人用的；
