### ISSUE TITLE
新版本

### ISSUE THREAD

**Issue by qianchenrumeng** [wangeditor-team/wangEditor#2677]
## 问题描述

请问一下什么时候发布新版本呢，之前提交的关于font标签有的解析不了的情况，你们已经接受了，想请问一下要多久才能修改这个呢，因为现在用v3不能销毁实例，提示destroy 不是一个function，用v4的话font标签解析不出来，在页面上显示为空白

## wangEditor 版本
v3

## 是否查阅了文档 ？
是，关于v3的销毁有bug还是在issues里面找到的答案
（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by hahaaha** [comment]
v4 可以尝试使用这个 配置项 editor.config.styleWithCSS = true

**Comment by qianchenrumeng** [comment]
> v4可以尝试使用这个配置项editor.config.styleWithCSS = true

主要是这个获取的内容在别的地方解析不出来

**Comment by qianchenrumeng** [comment]
> v4 可以尝试使用这个 配置项 editor.config.styleWithCSS = true

这个font标签有点太老了，富文本解析的时候解析不出来

**Comment by UltramanWeiLai** [comment]
> > v4 可以尝试使用这个 配置项 editor.config.styleWithCSS = true
> 
> 这个font标签有点太老了，富文本解析的时候解析不出来

你有试过 editor.config.styleWithCSS = true 这个配置项吗？这个配置项可以把 常规设置 改成 style 形式的

**Comment by UltramanWeiLai** [comment]
![Uploading image.png…]()

**Comment by qianchenrumeng** [comment]
> ![image](https://user-images.githubusercontent.com/23336585/102999997-19b15e80-4565-11eb-9a96-4b7f5b8180c1.png)
> 如图所示，就是使用了 editor.config.styleWithCSS = true 这个配置项后的效果

图片看不到哦，不过我试了下这个配置，貌似可以诶，谢谢啦

**Comment by UltramanWeiLai** [comment]
> > ![image](https://user-images.githubusercontent.com/23336585/102999997-19b15e80-4565-11eb-9a96-4b7f5b8180c1.png)
> > 如图所示，就是使用了 editor.config.styleWithCSS = true 这个配置项后的效果
> 
> 图片看不到哦，不过我试了下这个配置，貌似可以诶，谢谢啦

那我就关闭这个问题了
