### ISSUE TITLE
插入表格后获取HTML渲染的表格是没有边框的

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#2679]
## 问题描述

插入的表格 边框为0 显示出来的边框样式是添加在 tr td上的 而且是 w-e-text下 导致获取的html内容在渲染出来的时候表格没有边框
![image](https://user-images.githubusercontent.com/43296632/103048894-0df88300-45cb-11eb-9395-47f1ec5297bd.png)

## wangEditor 版本

4

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

插入表格 然后获取HTML 渲染富文本

- 步骤一
- 步骤二
- 步骤三

**Comment by lichenabson** [comment]
可以参考文档, 导入 基础样式
http://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/03-%E8%8E%B7%E5%8F%96html.html
![image](https://user-images.githubusercontent.com/20200267/103075434-8c264b00-4606-11eb-843a-02e997975821.png)

**Comment by wangfupeng1988** [comment]
赞楼上。

**Comment by OnePsycho** [comment]
> 可以参考文档, 导入 基础样式
> http://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/03-%E8%8E%B7%E5%8F%96html.html
> ![image](https://user-images.githubusercontent.com/20200267/103075434-8c264b00-4606-11eb-843a-02e997975821.png)

那这个意思是  我只要有任何渲染表格的地方我都的加自定义样式来渲染边框吗？

**Comment by lichenabson** [comment]
@OnePsycho 是的
