### ISSUE TITLE
图片拖拽修改尺寸后是否有回调函数拿到修改后的图片尺寸方便进行图片压缩？

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#2680]
## 功能描述

图片拖拽修改尺寸后是否有回调函数拿到修改后的图片尺寸方便进行图片压缩？

## 提炼几个功能点

拖拽回调以及图片压缩

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by lichenabson** [comment]
如要要压缩的话, 不是上传图片的时候就压缩了吗?
还有, 图片压缩 跟你 获取图片大小有什么关系

**Comment by wangfupeng1988** [comment]
只通过拖拽就压缩图片，这个实现不了。

你可以在服务端对图片进行压缩，压缩到合适的尺寸，返回给前端。
前端再进行拖拽调整的时候，就不要再频繁压缩了。这样做太麻烦了，容易出错。

**Comment by OnePsycho** [comment]
> 如要要压缩的话, 不是上传图片的时候就压缩了吗?
> 还有, 图片压缩 跟你 获取图片大小有什么关系

现在采用的是base64的方式上传图片  我知道压缩可以和图片尺寸没关系  但是我现在的需求就是想 拿到拖拽后的尺寸 然后根据最新的尺寸来给到压缩后的图片大小 明白意思了吗？
