### ISSUE TITLE
自定义v-model的问题

### ISSUE THREAD

**Issue by kailong321200875** [wangeditor-team/wangEditor#2681]
## bug 描述

二次封装wangEditor编辑器，实现v-model双向绑定，会发现一直监听modelValue的变化重新设置内容，导致光标会一直回到第一个位置上，没办法停留在最后一个的位置。

## 你预期的样子是？

希望自定义v-model的时候，光标可以一直停留在最后一个位置上

## 浏览器及版本号

谷歌 86.0.4240.111（正式版本） （64 位）

## wangEditor 版本

4.5.4

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

`<template>
  <div ref="editorRef" />
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, onBeforeUnmount, unref, watch, computed } from 'vue'
import { editorProps } from './props'
import E from 'wangeditor'
export default defineComponent({
  name: 'Editor',
  props: editorProps,
  emits: ['change', 'update:modelValue'],
  setup(props, { emit }) {
    const editorRef = ref<HTMLElement | null>(null)
    const editor = ref<E | null>(null)

    onMounted(() => {
      createdEditor()
    })

    onBeforeUnmount(() => {
      if (editor.value) {
        editor.value.destroy()
        editor.value = null
      }
    })

    watch(
      () => props.modelValue,
      (value: string) => {
        if (editor.value) {
          editor.value.txt.html(value)
        }
      },
      {
        immediate: true
      }
    )

    function createdEditor(): void {
      editor.value = new E(unref(editorRef) as any)
      initConfig(editor.value)
      editor.value.create()
    }

    function initConfig(editor: any): void {

      // 配置 onchange 回调函数
      editor.config.onchange = (html: string) => {
        const text = editor.txt.text()
        emitFun(editor, html, 'change')
        emit('update:modelValue', props.valueType === 'html' ? html : text)
      }
    }

    function emitFun(editor: any, html: string, type: 'change' | 'focus' | 'blur'): void {
      const text = editor.txt.text()
      emit(type, props.valueType === 'html' ? html : text)
    }

    return {
      editorRef
    }
  }
})
</script>

<style>
</style>
`

**Comment by UltramanWeiLai** [comment]
目前我们不支持双向数据绑定，如果你一定要这么做，那么再编辑区域回显数据的时候，使用  moveCursor 去设置光标的位置，但是这是一个很复杂的方法，如果纯粹移动到末尾就很简单
