### ISSUE TITLE
editor.txt.append和editor.txt.html使用后光标跳转到内容最前面

### ISSUE THREAD

**Issue by hahaaha** [wangeditor-team/wangEditor#2683]
## bug 描述

editor.txt.append和editor.txt.html使用后光标跳转到内容最前面

## 你预期的样子是？

设置后光标在最后面

## 浏览器及版本号

chrome 87.0.4280.88

## wangEditor 版本
4.5.4

## 官网能否复现该 bug ？
不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 editor.create()后使用editor.txt.append 或者 editor.txt.html

**Comment by yu530feng** [comment]
也发现有这个问题，异步数据回来editor.txt.html后，光标定位到最前面

**Comment by hahaaha** [comment]
@yu530feng 在修复中了

**Comment by nikolausliu** [comment]
啥时候能修复啊

**Comment by hahaaha** [comment]
@nikolausliu 已修复。。。下周四会发一个新版本
