### ISSUE TITLE
默认功能建议增加段落首行缩进

### ISSUE THREAD

**Issue by ZhangErling** [wangeditor-team/wangEditor#2685]
## 功能描述

![image](https://user-images.githubusercontent.com/45256786/103077343-934f5800-460a-11eb-8928-a6d417d587f3.png)

目前只能整个段落填充式缩进，无法使用段落的首行缩进，在文本编辑还是挺常用的一个功能

### 建议默认功能增加首行缩进

使用环境
HTML
js  https://unpkg.com/wangeditor/dist/wangEditor.min.js

**Comment by wangfupeng1988** [comment]
经过内部讨论，这个功能暂不加，得先去搞其他高优的问题。

可以通过自定义 css 样式来实现。
