### ISSUE TITLE
图片前面回车自动图片消失

### ISSUE THREAD

**Issue by liangdiyuan** [wangeditor-team/wangEditor#2693]
## bug 描述

*光标在图片前面回车图片自动消失*

## 你预期的样子是？

*正常换行*

## 浏览器及版本号

*Google Chrome 已是最新版本，版本 87.0.4280.88（正式版本） （64 位）*

## wangEditor 版本

*4.5.4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 上传图片
- 步骤二
- 光标移到图片前
- 步骤三
- 回车

**Comment by wangfupeng1988** [comment]
我这里没有复现，是 mac OS

**Comment by liangdiyuan** [comment]
你可以去官网看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 上午9:59
收件人:&nbsp;"wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送:&nbsp;"梁帝源"<1104152218@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 图片前面回车自动图片消失 (#2693)





 
我这里没有复现，是 mac OS

**Comment by liangdiyuan** [comment]
4.6.0版本的，不是4.5.4


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 上午9:59
收件人:&nbsp;"wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送:&nbsp;"梁帝源"<1104152218@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 图片前面回车自动图片消失 (#2693)





 
我这里没有复现，是 mac OS

**Comment by liangdiyuan** [comment]
刚才测了一遍，图片前面是H1标签才会触发bug


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 上午9:59
收件人:&nbsp;"wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送:&nbsp;"梁帝源"<1104152218@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 图片前面回车自动图片消失 (#2693)





 
我这里没有复现，是 mac OS

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/103165068-2c21e580-484e-11eb-94a8-d9a91ae1c227.png)
我这里没有复现，是 windows

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭，如还有疑问可以重新进行提交
