### ISSUE TITLE
建议增加格式刷和删除格式功能

### ISSUE THREAD

**Issue by yunweibang** [wangeditor-team/wangEditor#2694]
## 功能描述

*建议增加格式刷和删除格式功能*

## 提炼几个功能点

- 建议增加格式刷和删除格式功能

## 可参考的案例

*和word里一样就可以*

**Comment by hahaaha** [comment]
已经在队列中了。。。详细进度可以查看这个issue https://github.com/wangeditor-team/wangEditor/issues/2528
