### ISSUE TITLE
项目里有办法对没有指明长宽的dom监听长宽的改变吗？

### ISSUE THREAD

**Issue by Jayj1997** [wangeditor-team/wangEditor#2695]
## 问题描述

之前在做一个如果编辑器的长度不够(或者你觉得toolbar的icon太多)，就把多出来的icon收到一个icon里 #2592。 然后遇到一个问题，如果这个编辑器的长宽改变了，需要改变收进去的图标，所以就需要一个类似于window.onresize的监听，然而对dom 的Onresize只在最新的chrome内支持，如果要做的话就需要polyfill，或者直接ponyfill（编辑器声明的自己的长宽是100%，实际的px就不太好确定。项目里的mutation监听不到改变）。我本身不太会ts，之前尝试移进来一个polyfill遇到一些问题。
想问一下：

- 之前项目对这种情况有什么轮子能拿来用吗，我自己找了一下好像没有。
- 如果没有你们有什么好方法吗。
- 如果只能用onresize，我可以引入一个ponyfill的包来用吗。
- 如果也不行，那这个问题是一个需要解决的问题吗？=。=

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

我把现在写的先推到我的repo里，你可以拉下来试试看看。收进去的图标跟刷子的图标一样。

**Comment by clinfc** [comment]
1、可以用 ResizeObserver，但是这个 API 存在兼容性问题，在 IE 和 Firefox 上不支持。
2、使用 setInterval/requestAnimationFrame + getBoundingClientRect 进行轮循，实时判断 toolbar 的宽高，这种实现我也不知好坏

**Comment by clinfc** [comment]
关于项目里的 MutationObserver 它只能监听 DOM 节点的增减、attribute 标签的变化 和 文字的变化，详细的一可以参考 [MDN ](https://developer.mozilla.org/zh-CN/docs/Web/API/MutationObserver)或者[这篇文章](https://juejin.cn/post/6866725132027559944)

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭，如还有疑问可以重新进行提交
