### ISSUE TITLE
wangEditor用户文档部分代码错误

### ISSUE THREAD

**Issue by xingorg1** [wangeditor-team/wangEditor#2698]
## 问题描述
如题，文档错误

## wangEditor 版本
- "wangeditor": "^4.5.4"

-  "highlight.js": "^9.18.1",

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

- 步骤一

[文档地址](http://www.wangeditor.com/doc/pages/03-%E9%85%8D%E7%BD%AE%E8%8F%9C%E5%8D%95/07-%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE.html)

- 步骤二
   配置菜单 -> 代码高亮 -> css引入

下面的代码有问题：

`import 'highlight.js/styles/monokai_sublime.css'`
`<link href="http://cdn.bootcss.com/highlight.js/8.0/styles/monokai-sublime.min.css" rel="stylesheet">`
## 改进建议：
monokai-sublime文件的名字，正确代码应该是中横线：
`import 'highlight.js/styles/monokai-sublime.css'`

**Comment by xiaokyo** [comment]
感谢建议，我们会进行调整

**Comment by wangfupeng1988** [comment]
文档已修改 CDN 地址 https://github.com/wangeditor-team/wangeditor-usage-doc/pull/14
