### ISSUE TITLE
video无法选中，导致无法手动删除

### ISSUE THREAD

**Issue by houlei719504735** [wangeditor-team/wangEditor#2699]
## bug 描述

*video无法选中，导致无法手动删除*

## 你预期的样子是？

*选中video标签按删除键可以删除改元素*

## 浏览器及版本号

*Google Chrome 84.0.4147.125*

## wangEditor 版本

*4.3.0*

## 官网能否复现该 bug ？

能

**Comment by UltramanWeiLai** [comment]
可以再下一行使用退格进行删除，该问题我们会在 上传视频 的时候一同解决。

**Comment by a835100635** [comment]
问题已解决，下个版本更新。
