### ISSUE TITLE
建议增加格式化代码功能

### ISSUE THREAD

**Issue by ChartWay** [wangeditor-team/wangEditor#2705]
## 功能描述

格式化html代码，将文本的样式（颜色、大小、字体等）清除，图片、视频居中，将p之外的标签都改为p标签，如h1-h6、div等，将span 标签清除。
总之，所有排版就是只有段落，自己重新取排版，这样从其他地方（如word）复制过来的内容就能够排版出更适合的格式，避免多余代码干扰。

**Comment by UltramanWeiLai** [comment]
该任务已在待办事项中，后续会增加的。
