### ISSUE TITLE
无法输入数值、英文、及删除。

### ISSUE THREAD

**Issue by yunlongduan** [wangeditor-team/wangEditor#2706]
## bug 描述

使用谷歌浏览器无法输入数值、英文、及删除。

## 你预期的样子是？

可以正常输入数值、英文、及删除。

## 浏览器及版本号

87.0.4280.88（正式版本）（x86_64）

## wangEditor 版本

4.4.1

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
- 打开官网
- 步骤二
- 输入英文或数字或按下删除键

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/103188181-664cbf00-4902-11eb-9caa-c16c22a7d451.png)
我这边没有复现。
而且这种明显的不行，而且很严重的问题，怎么可能会留到现在。。。

**Comment by yunlongduan** [comment]
我也是在测试阶段发现的，起初我也以为是自身调用有误，但是打开官网当前问题复现，而且出现概率是百分之百。因此才锁定是组件本身问题。

**Comment by UltramanWeiLai** [comment]
这就很奇特了，能提供可以复现的场景吗？

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭，如还有疑问，可以直接重新开一个 issue
