### ISSUE TITLE
关于表格组件几点优化小建议

### ISSUE THREAD

**Issue by skyworld** [wangeditor-team/wangEditor#2708]
1、表格插入增加如下模式。参考teambition的编辑器，个人觉得这种更直观，体验更好。
![image](https://user-images.githubusercontent.com/4318550/103199782-94dc9100-4926-11eb-84fb-416311861344.png)

2、表格宽度希望固定，并且可以通过拖拉改变列宽，目前wangEditor表格宽度是靠内容撑起来的，编辑的时候宽度不可预期。
![image](https://user-images.githubusercontent.com/4318550/103200042-5398b100-4927-11eb-9901-2c064dbbb290.png)

感谢作者提供这么好用的编辑器！以上意见欢迎探讨，如有不对的地方望海涵

**Comment by UltramanWeiLai** [comment]
请按照模板进行提交 issue 否则是不受理的。
表格拖拽宽高这个功能目前的话，我们可能暂时不考虑去新增，因为比较复杂，目前对编辑器现有功能的稳定较为优先。
