### ISSUE TITLE
点击菜单上的表格控件，填好行数跟列数之后，点击确定无反应

### ISSUE THREAD

**Issue by CasualMing** [wangeditor-team/wangEditor#2710]
## bug 描述

点击菜单上的表格控件，填好行数跟列数之后，点击确定无反应

## 你预期的样子是？

![image](https://user-images.githubusercontent.com/40878104/103203968-3072ff00-4931-11eb-9750-e421203a44dd.png)

## 浏览器及版本号

谷歌浏览器   87.0.4280.88

## wangEditor 版本

v4.5.3

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤
这是我做的富文本菜单配置
![image](https://user-images.githubusercontent.com/40878104/103204273-ec342e80-4931-11eb-8c41-2ae53b792498.png)
![image](https://user-images.githubusercontent.com/40878104/103204282-f3f3d300-4931-11eb-8fc5-ceb27fe1bae3.png)

- 步骤一  设置的初始化菜单
- 步骤二 点击表格。设置行列数，点击确定，无效
- 步骤三

**Comment by UltramanWeiLai** [comment]
官网无法复现的话，问题可能出在你的场景上面。
你可以试着 把编译器作为一个纯场景 实例化一下，或者下载官网提供的 demo 看看是否还有这个问题，如果没有，你可以分步骤移入你现有的场景中，看看具体问题在哪里。

**Comment by CasualMing** [comment]
追查了一下这个问题，我发现是因为我页面中使用了ul跟li，但是这个应该跟富文本没什么关系啊
![image](https://user-images.githubusercontent.com/40878104/103724146-a43a9900-500e-11eb-967d-288a1c424021.png)
![image](https://user-images.githubusercontent.com/40878104/103724158-aac91080-500e-11eb-973d-681f69f07aa7.png)；
你这查找不是应该是要从初始化富文本时传递给实例化内的选择器嘛？
例如  const editor = new Editor(".addAnn_content_matter");
那么这里插入表格，查找 $ul $ol 是应该从addAnn_content_matter下面找啊，不应该在页面全局找
