### ISSUE TITLE
从word文档中复制内容粘贴到富文本中，会额外粘贴不需要的内容

### ISSUE THREAD

**Issue by dengchao-ryan** [wangeditor-team/wangEditor#2713]
## bug 描述

word中有一段文字内容，不设置任何样式，将其复制到系统粘贴版后，将其粘贴到富文本编辑器中，会额外粘贴不需要的内容
word中要复制的内容：
 word中的内容xxx
粘贴到富文本编辑器中后的内容：
@page { margin: 2cm } p { margin-bottom: 0.25cm; line-height: 120% } a:link { so-language: zxx }

word中的内容xxx

## 你预期的样子是？

只需要粘贴  “word中的内容xxx” 即可，不需要任何样式。

## 浏览器及版本号

Google Chrome (86.0.4240.111（正式版本） （64 位）)

## wangEditor 版本

4.6.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 建一个wangeditor编辑器
- 步骤二
- 然后在word文档中任意输入内容，将其复制，粘贴到富文本编辑器中

**Comment by UltramanWeiLai** [comment]
该问题已经收录并且在受理中，可以在 #2546 中去查看详情
