### ISSUE TITLE
图片选择base64方式上传 是否有回调函数 可以让我拿到进入编辑器的图片

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#2714]
## 问题描述

图片选择base64方式上传 是否有回调函数 可以让我拿到进入编辑器的图片

## wangEditor 版本

4

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by a835100635** [comment]
图片选择base64方式上传没有回调函数，要取得选中的图片可以选择自定义上传customUploadImg ，第一个参数就是 input 中选中的文件列表

**Comment by UltramanWeiLai** [comment]
我其实很好奇，你都转base64了还要获取图片干啥？

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
