### ISSUE TITLE
无法对选中的文本设置对齐方式

### ISSUE THREAD

**Issue by treezhu** [wangeditor-team/wangEditor#2716]
## bug 描述

*复制一段纯文本，选中某段文字，设置对齐方式会将所有复制过来的文本设置同样的对齐方式*

## 你预期的样子是？

*只对选中的文本设置对齐方式*

## 浏览器及版本号

*chrome*

## wangEditor 版本

*最新版本*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
复制一段纯文本内容粘贴
- 步骤二
选中某个段落设置对齐方式

**Comment by UltramanWeiLai** [comment]
对齐方式就只是针对段落进行设置的，不是针对选中文字进行设置的。
目前我还没了解到过有那个富文本编辑器支持对文字进行对齐方式设置的。

**Comment by treezhu** [comment]
@UltramanWeiLai 选择的是一段的整个文本，不是单独的几个文字，可以看下效果差别
![image](https://user-images.githubusercontent.com/18158355/103271928-82318d00-49f6-11eb-8313-0765ceddc7ee.png)
![image](https://user-images.githubusercontent.com/18158355/103271965-99707a80-49f6-11eb-820c-9eb51a77e7ff.png)

**Comment by UltramanWeiLai** [comment]
> @UltramanWeiLai 选择的是一段的整个文本，不是单独的几个文字，可以看下效果差别
> ![image](https://user-images.githubusercontent.com/18158355/103271928-82318d00-49f6-11eb-8313-0765ceddc7ee.png)
> ![image](https://user-images.githubusercontent.com/18158355/103271965-99707a80-49f6-11eb-820c-9eb51a77e7ff.png)
> 希望每有一个换行都算一个段落，而不是把所有的文本当做一个段落

那你可以在每一行的末尾按一下回车即可，你要理解，在你目前的宽度里面看着可能是多行，那么你回显的时候宽度不一样呢？那该怎么处理？一个段落是一个段落一行是一行这不一样的。
我打个比方我设置的时候一行是 10 个字，我回显的时候一行是 5 个字 怎么处理？
如果你要单行处理，你就得手动回车把它变成一个段落

**Comment by treezhu** [comment]
> > @UltramanWeiLai 选择的是一段的整个文本，不是单独的几个文字，可以看下效果差别
> > ![image](https://user-images.githubusercontent.com/18158355/103271928-82318d00-49f6-11eb-8313-0765ceddc7ee.png)
> > ![image](https://user-images.githubusercontent.com/18158355/103271965-99707a80-49f6-11eb-820c-9eb51a77e7ff.png)
> > 希望每有一个换行都算一个段落，而不是把所有的文本当做一个段落
> 
> 那你可以在每一行的末尾按一下回车即可，你要理解，在你目前的宽度里面看着可能是多行，那么你回显的时候宽度不一样呢？那该怎么处理？一个段落是一个段落一行是一行这不一样的。
> 我打个比方我设置的时候一行是 10 个字，我回显的时候一行是 5 个字 怎么处理？
> 如果你要单行处理，你就得手动回车把它变成一个段落

不是你的那个意思，我选中的文本就是一个段落后面有个<br>换行的，不是显示的一行，是因为粘贴过来的时候把所有粘贴的内容当做一个段落了，git的图片好像显示不了。但我知道解决办法了，加一个粘贴内容的过滤器，将粘贴内容中的回车换行替换为<p>
