### ISSUE TITLE
如果选择器相同 多次调用new 方法，依然会创建多个实例

### ISSUE THREAD

**Issue by srq18211** [wangeditor-team/wangEditor#2718]
## 问题描述

*请输入遇到的问题...*
![image](https://user-images.githubusercontent.com/37665471/103271296-cd4aa080-49f4-11eb-8ffa-e26807fe0319.png)

## wangEditor 版本

4.5.4

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
多次调用相同选择器 new 方法即可

**Comment by lichenabson** [comment]
#2697

**Comment by UltramanWeiLai** [comment]
该问题已经收录，可以移步到 #2697 中去跟进
