### ISSUE TITLE
插入视频需要手动输入 标签容器 ，希望是默认值，或dropmenu方式可选容器

### ISSUE THREAD

**Issue by srq18211** [wangeditor-team/wangEditor#2719]
## 问题描述

*请输入遇到的问题...*
![image](https://user-images.githubusercontent.com/37665471/103271525-709bb580-49f5-11eb-81bc-5b881be1b77b.png)

## wangEditor 版本

4.5.4

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
你可以使用自定义菜单能功能，然后参考 插入视频 的源码去写一个符合你业务要求的菜单。
我们这边是考虑自由度方面，因为不同的标签属性设置也是不同的。
