### ISSUE TITLE
insertHtml执行后影响后续输入内容样式

### ISSUE THREAD

**Issue by vic-gakki** [wangeditor-team/wangEditor#2721]
## bug 描述

insertHtml命令执行后影响后续输入内容样式

## 你预期的样子是？
插入结束后，标签分离不影响后续文本样式

## 浏览器及版本号

Chrome 87.0.4280.88

## wangEditor 版本

4.5.3

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 执行insertHtml命令插入一段带样式的标签
- 插入内容后，手动输入文本

**Comment by echoLC** [comment]
严格来说，这不是一个bug，属于正常的表现行为，大多数文档工具也是这样的表现，只不过我们现在还没有格式刷这样的功能，我们先受理解决一下吧。

**Comment by wangfupeng1988** [comment]
经我们讨论，这个问题比较棘手（特别是涉及到多浏览器兼容性问题），而且你所说的应用场景并不多，所以暂不解决。
你如果急需，可以使用 [选取范围API](https://doc.wangeditor.com/pages/08-%E5%B8%B8%E7%94%A8API/02-%E9%80%89%E5%8C%BA%E8%8C%83%E5%9B%B4API.html) 去单独处理。
