### ISSUE TITLE
关于字号

### ISSUE THREAD

**Issue by qianchenrumeng** [wangeditor-team/wangEditor#2722]
## 问题描述

我看了文档，在使用编辑器的时候，如果编辑了字号，font-size都会变成类似xxx-large这种，如果在回显的地方需要显示样式需要在回显的地方也加上特殊的css，但是因为回显的地方是在移动端，用RN写的，这个特殊样式好像写不出来，就造成了在编辑器中设置的字号大小在回显的时候是没有样式的，不知道这个有没有办法解决呢，有没有类似的配置可以让字号在设置的时候直接就是32px这种的呢

## wangEditor 版本

v4.6.0

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
虽然我没有写过移动端也没有用过 RN 不过，css 的属性选择器 和 框架无关吧，只要是浏览器都是一样的把？
也可以使用 editor.config.styleWithCSS = true 这个配置，这个配置会把设置从标签行为转换成 行内样式
