### ISSUE TITLE
H标题列无法对多行选中文本设置字体大小

### ISSUE THREAD

**Issue by wangxiahong23** [wangeditor-team/wangEditor#2730]
## bug 描述

*多行文本选中，点击H标题列H2，不生效，且选中状态丢失*

## 你预期的样子是？

*多行选中可以设置H标题大小*

## 浏览器及版本号

*Google Chrome 版本 87.0.4280.88（正式版本）*

## wangEditor 版本

*3.1.1*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：鼠标选中多行文本
- 步骤二：选中H标题列H2
- 步骤三：查看选中文本变化

**Comment by UltramanWeiLai** [comment]
目前3版本的已经不维护了，可以升级到4版本，平滑升级。
目前 标题设置 是只限单行，多行设置的功能我会收录到 todo list 当中
