### ISSUE TITLE
多次点击文本使得单行文本选中，点击H标题列H2，文本字体不生效

### ISSUE THREAD

**Issue by wangxiahong23** [wangeditor-team/wangEditor#2731]
## bug 描述

*多次点击文本使得单行文本选中，点击H标题列H2，文本字体不生效*

## 你预期的样子是？

*标题字体对文本生效，可以设置成功*

## 浏览器及版本号

*Google Chrome 版本 87.0.4280.88（正式版本） （64 位）*

## wangEditor 版本

*3.1.1*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：连续多次点击某一列，使得文本成选中状态
- 步骤二：点击H标题列H2，查看文本字体呈现

**Comment by UltramanWeiLai** [comment]
目前3版本的已经不维护了，可以升级到4版本，平滑升级。
如果不行，建议你可以通过控制台看看 编辑区域的标签是否为 h2 如果是就一个是有样式重置的公共样式把 h2 的样式重置了导致的

**Comment by wangxiahong23** [comment]
目前官网的V4版本的demo也是测试不通过的，不是样式影响，选中p标签或者span标签或者文本里自由的H标签等元素都无法设置成功

**Comment by UltramanWeiLai** [comment]
> 目前官网的V4版本的demo也是测试不通过的，不是样式影响，选中p标签或者span标签或者文本里自由的H标签等元素都无法设置成功
哪能提供详细的复现步骤或者demo吗？有个视频或者 git 动图示意更好
因为按照你说的我去做复现，也是没法复现的，双击 一个段落 然后设置 标题，我这边都是可以成功设置的。
![image](https://user-images.githubusercontent.com/23336585/103509313-cf51ab00-4e9d-11eb-93fd-174f8e37e171.png)

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
