### ISSUE TITLE
图片上传不了

### ISSUE THREAD

**Issue by guoshuai2511** [wangeditor-team/wangEditor#2732]
如图
![image](https://user-images.githubusercontent.com/41183255/103400718-234c4f00-4b81-11eb-9319-59058086e94b.png)

**Comment by UltramanWeiLai** [comment]
开局一张图，内容全靠猜。
请按照模板提交 issue 否则我们是不受理的。
另外这种情况，我觉得应该是你隐藏了 网络图片 又没有配置 上传图片 的服务地址导致的。
群公告里面，文档，视频教学全都有，总有一个适合你。
