### ISSUE TITLE
直接复制word文件中的内容到富文本编辑器中

### ISSUE THREAD

**Issue by 1499513021** [wangeditor-team/wangEditor#2733]
## bug 描述

   直接复制word文件中的内容到富文本编辑器中,最后富文本返回的html中会出现<o:p></o:p>这样的标签

## 你预期的样子是？

正常情况下渲染的样子  应该是渲染成<p>标签包裹文本

## 浏览器及版本号

chrome 80

## wangEditor 版本

  4

## 官网能否复现该 bug ？
能
## 最小成本的复现步骤

- 步骤一
- 复制word的内容至富文本编辑器
- 步骤二
- 获取富文本生成的html内容
- 步骤三
- 可以看到里面带有<o:p>标签

**Comment by UltramanWeiLai** [comment]
需要留意一下这个 #2734
