### ISSUE TITLE
复制word内容到富文本编辑器

### ISSUE THREAD

**Issue by 1499513021** [wangeditor-team/wangEditor#2734]
## bug 描述

复制word内容到富文本编辑器，如果word中有换行符，那么富文本渲染的html会在文本信息中最后一个换行符的位置生成一长串‘/n/n/n/n/n/n/n/n/n/’的字样，   注意    这个东西会在最后一个换行符的地方生成  如果没有换行符就不会生成这个字符串

## 你预期的样子是？

word中包含换行，直接复制到富文本应该渲染成<br>换行符  不应该出现一串莫名的字符串

## 浏览器及版本号

chrome 80

## wangEditor 版本

4

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 步骤一
- 复制包含换行操作的word至富文本编辑器
- 步骤二
- 获取富文本生成的html
- 步骤三
- 可以在得到的html中查看最后一个换行符的位置有一串‘/n/n/n/n/n/n’的字符串

**Comment by UltramanWeiLai** [comment]
这个问题我没有复现。windows
如果可以，能提供详细分复现流程，能有demo是最好的

**Comment by 1499513021** [comment]
直接复制word中包含换行的文本到富文本编辑器中，获取生成的html，console 或者alert看不出来，通过vuedevtools调试工具或者直接查看保存至数据库中的文本信息可以看到最后一个换行处有/n字样。应该是js自己把复制过来的内容包含的换行转换成了/n，但是应该在每一个换行处生成/n，而不是只在最后一个换行处生成/n。生成/n的个数时文本换行数+1，希望你们能查看一下这个是什么原因

  当然，富文本生成的html渲染出来没有问题，只是直接通过复制word的内容至富文本会生成/n字样，而手动输入时换行正常，不会产生奇怪的字符

**Comment by UltramanWeiLai** [comment]
> 直接复制word中包含换行的文本到富文本编辑器中，获取生成的html，console 或者alert看不出来，通过vuedevtools调试工具或者直接查看保存至数据库中的文本信息可以看到最后一个换行处有/n字样。应该是js自己把复制过来的内容包含的换行转换成了/n，但是应该在每一个换行处生成/n，而不是只在最后一个换行处生成/n。生成/n的个数是文本换行数+1，希望你们能查看一下这个是什么原因
> 
> 当然，富文本生成的html渲染出来没有问题，只是直接通过复制word的内容至富文本会生成/n字样，而手动输入时换行正常，不会产生奇怪的字符

为什么 获取 html 和 console 打印看不出来？
按理说都是字符串，展现的内容应该都是一样的，为什么会保存到数据和通过vuedevtools调试的时候才会有 /n ? 
是否经过了什么的转义但是你不知道？
编辑器里面换行也是不少 /n 换行符去做的，编辑器的换行都是一个又一个p标签(块级元素)，哪怕因为浏览器的原因会有 <br/> 标签也不应该会有换行符才对。

**Comment by 1499513021** [comment]
首先：我没有转义操作，通过editor.txt.html()获取到html后在vuedevtools中查看就有/n换行符
其次：当直接复制word中的文本会出现这种情况，而手动输入则不会，如果是我有转义操作应该两者都有或者两者都没有

**Comment by wangfupeng1988** [comment]
第一，我猜测你说的是 `\n` ，不是 `/n` 吧？
第二，你需要脱离 vue 等框架的环境，使用纯 html 和 js 来复现这个问题。即，用最简单、成本最低的方式来复现问题，最好让我们能傻瓜式的复现问题。
否则，我们复现不了，也不好解决。

**Comment by UltramanWeiLai** [comment]
> 首先：我没有转义操作，通过editor.txt.html()获取到html后在vuedevtools中查看就有/n换行符
> 其次：当直接复制word中的文本会出现这种情况，而手动输入则不会，如果是我有转义操作应该两者都有或者两者都没有

那我如何去复现？
获取生成的html 是正常的。
但是 走 vuedevtools 和 后台逻辑 就多 /n 了
我只能理解 vuedevtools  和 后台逻辑 对字符串做了处理。。
或者你能提供一个可复现的环境和场景，让我们复现，不然无法复现的话，也无从解决

注：你可能没有转义，但是插件和后台框架都会继承一些 xss 之类的逻辑会对字符串做转义

**Comment by 1499513021** [comment]
![_14UH0$J~WO8SO`V}F%FB`G](https://user-images.githubusercontent.com/49010259/103520617-632d7200-4eb2-11eb-9022-e82611394b08.png)
截了个图 你看看

**Comment by 1499513021** [comment]
直接打印可以看到所有的换行全部跑到最后一个换行的地方了，或者用json.stringify转一下获取到的html，就能看到/n出现

**Comment by UltramanWeiLai** [comment]
> 直接打印可以看到所有的换行全部跑到最后一个换行的地方了，或者用json.stringify转一下获取到的html，就能看到/n出现

所有换行跑到最后一个换行的地方是啥意思？
俗话说得好，一图胜千言，一例胜千图

**Comment by 1499513021** [comment]
这上面好像不能提交图片呀

**Comment by UltramanWeiLai** [comment]
> 这上面好像不能提交图片呀

c + v 即可上传图片 截图也是 直接粘贴到 编辑区域

**Comment by 1499513021** [comment]
![_14UH0$J~WO8SO`V}F%FB`G](https://user-images.githubusercontent.com/49010259/103718945-e5c54700-5002-11eb-9d2c-8be61dfbd863.png)

**Comment by 1499513021** [comment]
![_14UH0$J~WO8SO`V}F%FB`G](https://user-images.githubusercontent.com/49010259/103718995-042b4280-5003-11eb-8d7a-2dbc93d37b51.png)

**Comment by UltramanWeiLai** [comment]
大概了解到了，我们会去进行排查的
这边你可以先通过正则去过滤 /n

**Comment by 1499513021** [comment]
好的
