### ISSUE TITLE
【BUG】设置标题无法多行设置

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2736]
## bug 描述

选中多行文本后设置标题，无反应，且选区去丢失

## 你预期的样子是？

正常设置为标题

## 浏览器及版本号

所有

## wangEditor 版本

所有

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 - 输入多行文本
- 步骤二 - 选择多行文本
- 步骤三 - 设置为标题

**Comment by liuqh0609** [comment]
交叉测试： @q378532364

**Comment by yuhuan101** [comment]
在谷歌浏览器（87.0.4280.141（正式版本） （64 位））有时候会出现设置标题不生效问题，官网也会偶现
