### ISSUE TITLE
菜单栏的tooltip在angular项目中显示异常

### ISSUE THREAD

**Issue by Ranxiu** [wangeditor-team/wangEditor#2741]
## bug 描述

*
editor.config.zIndex = 10
菜单的样式 class="w-e-menu"  z-index大于tooltip的z-index class="w-e-menu-tooltip w-e-menu-tooltip-up" 导致部分显示异常
菜单hover事件对w-e-menu样式进行了重写 导致z-index=12大于w-e-menu-tooltip的z-index=11
*
![image](https://user-images.githubusercontent.com/34741198/103513207-1abb8780-4ea5-11eb-81ae-22b057836094.png)
![image](https://user-images.githubusercontent.com/34741198/103513243-2dce5780-4ea5-11eb-904f-8595bb707590.png)

## 你预期的样子是？

*请输入内容……*
![image](https://user-images.githubusercontent.com/34741198/103513290-4474ae80-4ea5-11eb-923e-dde4e028e624.png)

## 浏览器及版本号

*Google Chrome  版本 87.0.4280.88（正式版本） (x86_64)*

## wangEditor 版本

*^4.6.1*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

ngAfterViewInit() {
    const editor = new E('#content');
    editor.config.uploadImgShowBase64 = true
    editor.config.placeholder = ''
    editor.config.height = 500
    editor.config.zIndex = 10
    editor.create()
  }

**Comment by 86driver** [comment]
@Ranxiu  这个bug是只针对angular吗， 我用官网例子根据你复现步骤没发现有bug，  方便的话可以贴个codepen在线例子

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
