### ISSUE TITLE
复制粘贴word文档会带有word文档的样式

### ISSUE THREAD

**Issue by Bmongo** [wangeditor-team/wangEditor#2743]
## bug 描述

在v4中，从word文档复制过来的文字会带有word文档中的样式，
开头会有@font-face{...}这些样式，在v3中是正常的。

## 你预期的样子是？

复制过来没有word中的样式

## wangEditor 版本

4.6.0

## 官网能否复现该 bug ？

能

**Comment by 86driver** [comment]
> ## bug 描述
> 在v4中，从word文档复制过来的文字会带有word文档中的样式，
> 开头会有@font-face{...}这些样式，在v3中是正常的。
> 
> ## 你预期的样子是？
> 复制过来没有word中的样式
> 
> ## wangEditor 版本
> 4.6.0
> 
> ## 官网能否复现该 bug ？
> 能

@Bmongo  我在官网复制带颜色的word文档正常， 贴一下你的复现步骤

**Comment by 86driver** [comment]
@Bmongo 请按 issue 模板格式提交

**Comment by Bmongo** [comment]
@86driver 我是在wps中输入一段话，然后随便改了改样式，加粗了一下，ctrl+a全选、在富文本框中ctrl+v粘贴就出现这种情况

**Comment by hyl1374961656** [comment]
一样的问题
