### ISSUE TITLE
点击图片编辑时拖拽框位置出现偏差

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#2744]
## bug 描述

点击图片编辑时拖拽框位置出现偏差
![3$JMKNJX E9}%F}@%T~WNW](https://user-images.githubusercontent.com/43296632/103597288-e1355b80-4f3a-11eb-96e8-bda4a3af6ec2.png)

## 你预期的样子是？

拖拽框的宽高位置应该是要和图片吻合的

## 浏览器及版本号

google最新

## wangEditor 版本

4

## 官网能否复现该 bug ？

能
## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/43296632/103597264-ccf15e80-4f3a-11eb-90b7-101f1c4d43a4.png)

- 步骤一
- 步骤二
- 步骤三

**Comment by 86driver** [comment]
@OnePsycho 我在官网没复现出你说的问题， 你是进行了什么操作之后才发现这个问题的？

**Comment by OnePsycho** [comment]
> @OnePsycho 我在官网没复现出你说的问题， 你是进行了什么操作之后才发现这个问题的？

是在dialog里面 的富文本 然后插入的是一张 1200*480的图片  编辑器宽高可能只有 600*400

**Comment by UltramanWeiLai** [comment]
我重新尝试去复现这个问题，但是不管图片是否超过编辑区域的大小编辑框都是正常的。
我详细看了一下你的图片，可能你觉得应该是拖蓝部分都应该包裹在框里面，框只针对图片本体，是针对整个段落的。
