### ISSUE TITLE
作者们，您们好，请问一下这个插件样式引入跟功能代码引入，将来会分开嘛？，是否会给外界引入的入口

### ISSUE THREAD

**Issue by CasualMing** [wangeditor-team/wangEditor#2746]
## 问题描述
我们有个需求新建广告，使用富文本新增完，需要到详情页展示全部的信息。我在新增的时候使用了new Editor等一系列操作及配置，但是详情页面，其实只是需要一个样式（之所以没自己写，一是为了要和新增的时候展示样式一致，重写比较麻烦，二是个人认为样式跟功能代码在一个持续迭代的插件中，不应该耦合在一起）。

当然，这只是我个人的一个看法。
暂时我这边使用的是，new Editor 完之后。将顶部菜单设置为空数组。设置为不可编辑。但是个人认为这并不是最优的解决办法

## wangEditor 版本

版本是4.5.3

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 新增完富文本
- 步骤二 详情页查看（详情页只负责查看）
- 步骤三

**Comment by 86driver** [comment]
@CasualMing  编辑器只负责编辑时样式， 不负责详情页样式， 一是因为详情页样式都是自定义的，需要编辑器默认样式可以到源码拷贝一份
