### ISSUE TITLE
toolbar菜单tooltip展示位置不准

### ISSUE THREAD

**Issue by CrazyWood007** [wangeditor-team/wangEditor#2747]
## bug 描述

toolbar菜单tooltip展示位置不准（当编辑器宽度较小导致菜单换行时），展示位置在第一行对应位置的上方，而不是对应图标上方

## 你预期的样子是？

tooltip展示在对应菜单上方

## 浏览器及版本号

chrome

## wangEditor 版本

4.6.1

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 打开官网
- 步骤二 resize到菜单换行
- 步骤三 hover菜单

**Comment by CrazyWood007** [comment]
同时希望能将这个功能做成可以选择/配置的，比如我就不想开启这个tooltip

**Comment by UltramanWeiLai** [comment]
菜单折行 展示位置在第一行对应位置的上方 是我们处理就是这样，主要是防止挡住其他的菜单按钮。
关于 是否开启 提示功能，这个我会收录的
