### ISSUE TITLE
ul被p包裹，双回车生成div标签，包裹于ul父级p中

### ISSUE THREAD

**Issue by CrazyWood007** [wangeditor-team/wangEditor#2748]
## bug 描述

如题，导致无法真正的退出list

## 你预期的样子是？

可以正常退出list

## 浏览器及版本号

chrome

## wangEditor 版本

4.6.1

## 官网能否复现该 bug ？

不能（这是我最奇怪的地方，怎么做到的）

## 最小成本的复现步骤

- 打开官网提供的codepen地址，选择 禁用编辑器api
- 随便输入些内容，选择无序列表
- 两下回车
- 检查元素，ul被p包裹，回车生成的元素为div

**Comment by CrazyWood007** [comment]
原来官网也能复现，只是在原有的结构中添加不会，如果是自己重新加个ul，效果和我遇到的相同

**Comment by UltramanWeiLai** [comment]
该问题可以移步到 #2329 中去跟进
