### ISSUE TITLE
4.6版本和react16.8，放在antd的抽屉里，head bold和倾斜方法都不生效

### ISSUE THREAD

**Issue by 18094707994** [wangeditor-team/wangEditor#2749]
## bug 描述

*请输入内容……*4.6版本和react16.8，放在antd的抽屉里，head bold和倾斜方法都不生效

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号
chrome 87.0.4280.88
*请输入内容……*

## wangEditor 版本
4.6.1
*请输入内容……*

## 官网能否复现该 bug ？

能/不能
不能
## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
就安装最新版本的编辑器，放入antd的抽屉，就这几个方法不生效也不报错，其它方法正常
- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
可以检查一下 dom ，是否相应的位置已经转换成了 h b i标签，如果是，则可能是 样式被重置了

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
