### ISSUE TITLE
建议pasteTextHandle支持Promise类型异步操作

### ISSUE THREAD

**Issue by gehaollt** [wangeditor-team/wangEditor#2750]
## 功能描述
pasteTextHandle 这个函数只能支持同步操作，如果需要调整的内容需要异步处理，就有些麻烦，比如调用接口只能用同步

**Comment by UltramanWeiLai** [comment]
还请按照模板进行提交 issue 否则是不受理的
处理粘贴的文本内容 为何会需要异步？需要使用请求？
有个问题，那么在这个异步阶段，我再输入新的内容后，异步回调触发并且返回内容，你觉得应该如何处理？
个人觉得这部分逻辑完全可以不涉及到异步层面，如果支持异步很可能造成显示混乱和冲突。

**Comment by gehaollt** [comment]
好的，看到你的描述，感觉确实不合适，我这边其实是做一个类似微信编辑器的东西，可以替换复制内容里面的图片链接

**Comment by UltramanWeiLai** [comment]
> 好的，看到你的描述，感觉确实不合适，我这边其实是做一个类似微信编辑器的东西，可以替换复制内容里面的图片链接

可以考虑在 onchange 里面去做相关的处理，不过复制图片这类行为不是会直接走 上传图片的？

**Comment by gehaollt** [comment]
是这样的，例如我从外网随便复制一篇web文章，这篇文章里面包含一些图片可能做了防盗链配置，我会在复制的时候把资源地址转换一下。

**Comment by UltramanWeiLai** [comment]
> 是这样的，例如我从外网随便复制一篇web文章，这篇文章里面包含一些图片可能做了防盗链配置，我会在复制的时候把资源地址转换一下。

可以考虑在 onchange 里面去做相关的处理，也可以考虑在保存的时候做相关处理

**Comment by gehaollt** [comment]
嗯呢，多谢

**Comment by codedart2018** [comment]
这个确实是需要异步去处理。同步要疯

**Comment by songyizhe** [comment]
> 嗯呢，多谢

做出来了吗，请问如何实现获取上传并替换img的链接的

**Comment by codedart2018** [comment]
> > 嗯呢，多谢
> 
> 做出来了吗，请问如何实现获取上传并替换img的链接的

我已经弄成异步处理了！这里面替换还是同步替换的，异步处理、
