### ISSUE TITLE
【功能优化】菜单 toolbar 优化

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2753]
## 功能描述

菜单的提示 toolbar 可以进行是否显示配置

## 提炼几个功能点

- 可以进行是否显示配置

## 原型图

无

## 可参考的案例

无

**Comment by sunliyun** [comment]
toolbar如何配置多语言啊？

**Comment by rsl140** [comment]
> toolbar如何配置多语言啊？

https://doc.wangeditor.com/pages/12-%E5%A4%9A%E8%AF%AD%E8%A8%80/

**Comment by rsl140** [comment]
@clinfc 交叉测试
