### ISSUE TITLE
富文本编辑器在创建时报错

### ISSUE THREAD

**Issue by Zswordcgf** [wangeditor-team/wangEditor#2754]
## bug 描述

*正常使用wangeditor，首先将其组件化封装。当跳转到该页面路由附带query参数时，会报 “editor.i18next.init is not a function”的错误，编辑器无法正常加载，而项目中并没有使用语言翻译类的功能*

## 你预期的样子是？

*正常加载组件*

## 浏览器及版本号

*chrome 76.0.3809.132*

## wangEditor 版本

*4.5.4*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 新建一个editor组件
- 在跳转到该组件所在页面时路由中带上query参数

**Comment by 86driver** [comment]
@Zswordcgf  应该是你使用的方式有问题吧？编辑器跟页面query参数没有联系的啊， 你要使用i18next 首先要安装i18next，

**Comment by 86driver** [comment]
附上文档地址
https://doc.wangeditor.com/pages/12-%E5%A4%9A%E8%AF%AD%E8%A8%80/

**Comment by Zswordcgf** [comment]
主要就是并没有想去使用i18next，但是他会报i18next创建的错误，然后在项目中装了i18next依赖并使用后就不会报错了

**Comment by yangweiran101** [comment]
> 主要就是并没有想去使用i18next，但是他会报i18next创建的错误，然后在项目中装了i18next依赖并使用后就不我也遇到这样的报错，后来发现是因为提取成组件，组件未销毁所以导致再次渲染的时候报错。建议在富文本编辑器组件上加上条件，便于组件销毁。
