### ISSUE TITLE
与jQuery Validation 一起使用时，wangEditor获取焦点或值变化时jQuery  Validation 报错

### ISSUE THREAD

**Issue by YueYunyun** [wangeditor-team/wangEditor#2755]
## bug 描述
使用 jQuery  Validation 验证会报错
### 报错信息：
        jquery.js:4094 Uncaught TypeError: Cannot read property 'jQuery321066704805316737552' of undefined
            at Data.get (jquery.js:4094)
            at Data.access (jquery.js:4112)
            at Function.data (jquery.js:4252)
            at HTMLDivElement.delegate (jquery.validate.js:402)
            at HTMLFormElement.dispatch (jquery.js:5206)
            at HTMLFormElement.elemData.handle (jquery.js:5014)
            at Object.trigger (jquery.js:8201)
            at Object.simulate (jquery.js:8260)
            at HTMLDocument.handler (jquery.js:8319)
![image](https://user-images.githubusercontent.com/27658806/103752357-97d13300-5044-11eb-8acc-07ac6891ab43.png)

### 报错追踪：
	var validator = $.data( this.form, "validator" ),
        this.form 的值为 undefined  
        wangEditor元素上没有form引起了jQuery  Validation 报错
![image](https://user-images.githubusercontent.com/27658806/103752444-b59e9800-5044-11eb-9772-d1ec829decbf.png)

## 你预期的样子是？
jQuery  Validation 不应该报错

## 浏览器及版本号

chrome,edge

## wangEditor 版本

4.6.1

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

https://codepen.io/YueKing/pen/gOwzVpP

**Comment by 86driver** [comment]
@YueYunyun  这个跟编辑器没什么关系， 可以把编辑器从 <form></form>标签拿出来

**Comment by YueYunyun** [comment]
@86driver 
不放在form标签里确实没有问题，
但是 所有 input组需要封装在form里统一验证提交，由于封装的原因，无法剥离出form标签。

**Comment by YueYunyun** [comment]
@86driver 
我认为这是编辑器的BUG,其他文本框，如input,textarea 在form里验证没有此类问题，但是wangEditor却不行。

**Comment by YueYunyun** [comment]
![image](https://user-images.githubusercontent.com/27658806/103768726-fd7de900-505d-11eb-9251-352343208a14.png)
给元素增加一个form属性就可以修复这个BUG

**Comment by YueYunyun** [comment]
@arliang @limichange @Lanfei  希望源码中能修复这个bug
