### ISSUE TITLE
img无法关闭拖拽功能

### ISSUE THREAD

**Issue by xixilalaha** [wangeditor-team/wangEditor#2757]
## 问题描述

给图片设置了contenteditable =false属性,也给图片设置了点击event.preventDefault事件，但是仍然无法阻止富文本框内图片可拖拽功能

## wangEditor 版本

v4.6.0

## 是否查阅了文档 ？

（文档链接 [http://www.wangeditor.com/doc](http://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

直接给添加的图片添加contenteditable =false属性仍然无效

**Comment by 86driver** [comment]
@xixilalaha  缩放操作的是蒙层， 然后根据蒙层去设置图片的大小 跟你说的contenteditable 没什么关系

**Comment by xixilalaha** [comment]
那无法关闭对这个图片点击的监听么，用了那个api里的imgclick也是无法禁止他选中


发送自我的盖乐世

**Comment by yixinagqingyuan** [comment]
大佬，我也有这个问题，请问你解决了吗

**Comment by xixilalaha** [comment]
@yixinagqingyuan 点击图片会出现一个蒙版，你把那个class隐藏掉就不会操作了，或者对图片添加一个禁止选中的样式就解决了
