### ISSUE TITLE
插入表格，然后将光标移动到表格末尾，按下删除键，控制台报错

### ISSUE THREAD

**Issue by echoLC** [wangeditor-team/wangEditor#2760]
## bug 描述

插入表格，然后在将光标移动到表格末尾，按下删除键，控制台报错，并且导致表格没法被删除，多按几次才能删除。

## 你预期的样子是？

应该不报错，并且能正常删除表格。

## 浏览器及版本号

chrome最新版本。

## wangEditor 版本

v4.6.1

## 官网能否复现该 bug ？

能，控制台不会报错，但是表格删除不了

## 最小成本的复现步骤

- 在编辑器中插入表格
- 将光标移动到表格末尾
- 按下键盘删除键

**Comment by 86driver** [comment]
这个bug 链接到 https://github.com/wangeditor-team/wangEditor/issues/2801 来处理
