### ISSUE TITLE
新增自定义菜单后粘贴方法会执行两次、粘贴worde文档会有css样式

### ISSUE THREAD

**Issue by WE1ZHANTA0** [wangeditor-team/wangEditor#2761]
## bug 描述

*1.新增自定义菜单后复制粘贴，editor.config.pasteTextHandle粘贴方法执行了两次，把自定义菜单代码去掉后正常
2.粘贴word文档到富文本里会有css样式代码*

## 浏览器及版本号

*谷歌*

## wangEditor 版本

*4.6.0*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 新增自定义菜单
- 步骤二 复制粘贴

**Comment by clinfc** [comment]
大哥，你是我哥，至少你的扩展功能代码得有个路径可以看吧

**Comment by UltramanWeiLai** [comment]
该问题长时间没有人回复，暂且关闭

**Comment by penggang-home** [comment]
const html = event.clipboardData.getData('text/html') // 获取粘贴的 html
const text = event.clipboardData.getData('text/plain') // 获取粘贴的纯文本
html && editor.insertText(text)
这样可以解决问题
