### ISSUE TITLE
从wps复制过来的段落文字，分段用的是br不是p

### ISSUE THREAD

**Issue by mlshan** [wangeditor-team/wangEditor#2764]
## 功能描述
在wps复制的文字段落，现在是br标签分段，应用p标签分割段落，这样可好做样式调整和排版
![image](https://user-images.githubusercontent.com/37204782/103991555-cd555800-51cd-11eb-8904-04ad9f1c5896.png)

**Comment by mlshan** [comment]
![image](https://user-images.githubusercontent.com/37204782/103991873-4785dc80-51ce-11eb-8c7a-b43f1431efc6.png)

**Comment by 86driver** [comment]
@mlshan 请按 issue 模板格式提交
