### ISSUE TITLE
表格内容填充时，修改为居中，新增一行时，内容填充的格式又变为居左对齐

### ISSUE THREAD

**Issue by guiguzigang** [wangeditor-team/wangEditor#2768]
表格内容填充时，修改为居中，新增一行时，内容填充的格式又变为居左对齐；
现在修改表格的列或行是直接替换了表格，但是没有把表格（table）的样式带上

**Comment by UltramanWeiLai** [comment]
请按照模板提交 issue 否则我们是不受理的
