### ISSUE TITLE
BtnMenu基类在typescript使用时报错

### ISSUE THREAD

**Issue by csfankun** [wangeditor-team/wangEditor#2771]
## 问题描述
extends' clause of exported class 'MathMenu' has or is using private name 'BtnMenu'

*请输入遇到的问题...*
typescript类型报错
## wangEditor 版本
4.6.1
*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）
https://doc.wangeditor.com/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html
*是/否*
是
## 最小成本的复现步骤
默认的react官方typescript脚手架，复制class AlertMenu extends BtnMenu {
这一系列的代码运行即可复现
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
这个报错说的是，导出的 MathMenu 使用私有的 BtnMenu
请确认是否导出了 BtnMenu 这个类。
或者提供 demo

**Comment by csfankun** [comment]
> 这个报错说的是，导出的 MathMenu 使用私有的 BtnMenu
> 请确认是否导出了 BtnMenu 这个类，或者哪里覆盖了。
> 或者提供 demo
> 关于自定义菜单的话，群公告里面有视频可以看

有导出  const { BtnMenu } = E

**Comment by UltramanWeiLai** [comment]
> > 这个报错说的是，导出的 MathMenu 使用私有的 BtnMenu
> > 请确认是否导出了 BtnMenu 这个类，或者哪里覆盖了。
> > 或者提供 demo
> > 关于自定义菜单的话，群公告里面有视频可以看
> 
> 有导出 const { BtnMenu } = E

你提供的信息很难让我去判断是什么原因，是否能提供 demo 之类的东西。
或者你看看 https://www.bilibili.com/video/BV1eK411N7W8?p=18 这个视频，是否能跟着写出来？

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
