### ISSUE TITLE
代码块的一些问题

### ISSUE THREAD

**Issue by xiaokyo** [wangeditor-team/wangEditor#2774]
## bug 描述

1. 代码块后有p空白元素时无法删除
2. 选中点击菜单代码块，在将代码块内容全部删除会出现样式属性及Font标签等

## 你预期的样子是？

1.代码块右边后面可以跟个光标然后删除的时候可以删除代码块
2.代码块不要出现无关标签

## 浏览器及版本号

chrome 版本 87.0.4280.88（正式版本） （64 位）

## wangEditor 版本

4.6.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

1. 代码块后有p空白元素时无法删除
2. 选中点击菜单代码块，在将代码块内容全部删除会出现样式属性及Font标签等

**Comment by wangfupeng1988** [comment]
非核心用途，而且比较难解决（ execCommand 的坑），暂缓吧。
