### ISSUE TITLE
动态生成的div 创建editor之后 编辑器出来了 但是菜单无效 请问有方法解决吗

### ISSUE THREAD

**Issue by Zyermy** [wangeditor-team/wangEditor#2776]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
请按照模板提交 issue 否则是不受理的。
你这说的和没说一样，请说明复现步骤，越简单越好，最好能提供 demo
