### ISSUE TITLE
我在vue中使用了watch，监听后端返回数据，然后写入页面，发现只要内容变化，光标就会定位在最前面

### ISSUE THREAD

**Issue by CasualMing** [wangeditor-team/wangEditor#2778]
## bug 描述
我在vue中使用wangEditor 封装了一个富文本组，这个组件负责新增编辑以及详情展示时使用。因为不确定详情的时候富文本接口是否能及时返回数据，遂在自己封装的组件内使用了watch 监听接口响应的数据。
本来预想是很完美的，但是在新增的时候，因为监听了chang事件，chang事件向上传递了最新的富文本字符串。也就会导致内容一有变化，就会使用 `editor.txt.html` 向富文本内写入一次数据。
然后就会出现每次输入数据的时候，富文本的光标就会在最前面。
![image](https://user-images.githubusercontent.com/40878104/104152453-945df300-541a-11eb-95c3-6e2657155fc0.png)
![image](https://user-images.githubusercontent.com/40878104/104152479-a8095980-541a-11eb-9820-16f555cf2b11.png)
![image](https://user-images.githubusercontent.com/40878104/104152703-47c6e780-541b-11eb-942c-d7aa05806be3.png)

![GIF](https://user-images.githubusercontent.com/40878104/104152540-d4bd7100-541a-11eb-80c4-da3680e7f8b4.gif)

## 你预期的样子是？

正常输入。光标符合预期

## 浏览器及版本号
谷歌 87

## wangEditor 版本
v4.6.1

## 官网能否复现该 bug ？
不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 使用vue构建项目，创建一个富文本组件
- 步骤二 监听外部传入的富文本字符串 以及 change 事件
- 步骤三 页面输入富文本

**Comment by clinfc** [comment]
```
export default {
    props: {
        // v-model 双向绑定：接受父组件的值
        value: {
            type: String,
            default: ''
        }
    },
    watch: {
        // 监听父组件传值，将值赋值给编辑器
        value(n) {
            if (this.editor && n !== this.temp) {
                this.editor.$textElem.html(n)
            }
        }
    },
    data() {
        return {
            temp: '',   // 缓存当前的编辑器中的值，用于与父组件传入值进行对比
            editor: null
        }
    },
}
```
你应该是缺少一个对比，值一变你就赋值给编辑器了，这样会造成一个循环，然后出现了你所说的情况。
很好解决，组件中用一个变量进行缓存当前编辑器的值，父组件传入的值如果发生了变化，与组件中缓存的值进行对比，如果不相等才赋值给编辑器

**Comment by CasualMing** [comment]
> ```
> export default {
>     props: {
>         // v-model 双向绑定：接受父组件的值
>         value: {
>             type: String,
>             default: ''
>         }
>     },
>     watch: {
>         // 监听父组件传值，将值赋值给编辑器
>         value(n) {
>             if (this.editor && n !== this.temp) {
>                 this.editor.$textElem.html(n)
>             }
>         }
>     },
>     data() {
>         return {
>             temp: '',   // 缓存当前的编辑器中的值，用于与父组件传入值进行对比
>             editor: null
>         }
>     },
>     mounted() {
>         this.editor = new wangEditor(this.$refs.wang)
> 
>         this.editor.txt.eventHooks.changeEvents.push(() => {
>             this.temp = this.editor.$textElem.html()
>             this.$emit('input', this.temp)
>         })
> 
>         this.editor.create()
>         
>         if (this.value.length) {
>             this.editor.txt.html(this.value)
>         }
>     },
> }
> ```
> 
> 你应该是缺少一个对比，值一变你就赋值给编辑器了，这样会造成一个循环，然后出现了你所说的情况。
> 很好解决，组件中用一个变量进行缓存当前编辑器的值，父组件传入的值如果发生了变化，与组件中缓存的值进行对比，如果不相等才赋值给编辑器

谢谢，这个问题解决
