### ISSUE TITLE
编辑器菜单的提示信息（ToolTip）能不能通过自定义的方式来实现

### ISSUE THREAD

**Issue by Rain256** [wangeditor-team/wangEditor#2779]
![image](https://user-images.githubusercontent.com/63837756/104153787-33d0b500-541e-11eb-99c4-75e7833747a9.png)
![image](https://user-images.githubusercontent.com/63837756/104153808-477c1b80-541e-11eb-9baa-8d5eed75662b.png)
目前的这两个按钮的提示信息应该相反了吧！

**Comment by rsl140** [comment]
https://github.com/wangeditor-team/wangEditor/issues/2780#issue-783188257
