### ISSUE TITLE
复制网页的Input框中的值之后，在编辑器中不换行连续粘贴的情况下，会多出带样式的span标签

### ISSUE THREAD

**Issue by liuqh0609** [wangeditor-team/wangEditor#2786]
## bug 描述

复制网页的Input框中的值之后，在编辑器中不换行连续粘贴的情况下，会多出带样式的span标签

```html
<p>
  这是一段文字是是是哈哈哈哈哈哈
  <span style="font-size: 1em;">这是一段文字是是是哈哈哈哈哈哈</span>
  <span style="font-size: 1em;">这是一段文字是是是哈哈哈哈哈哈</span>
</p>
```

## 你预期的样子是？
```html
<p>
 这是一段文字是是是哈哈哈哈哈哈 这是一段文字是是是哈哈哈哈哈哈 这是一段文字是是是哈哈哈哈哈哈
</P>
```

## 浏览器及版本号

版本 87.0.4280.141（正式版本） （64 位）

## wangEditor 版本

v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
  - 在一个网页的input框中输入值，并且复制
- 步骤二
  - 在wangEditor中的同一行里连续粘贴  
- 步骤三
  -  查看页面中对应的html结构

**Comment by echoLC** [comment]
我发现在 chrome和safari上，行为就是，你往一个p标签里面连续多次粘贴同样内容的p标签包裹的内容，然后第一次正常文本，第二次就会出现 span包裹，然后还会加上 font-size 这样的style，但是在firefox，就能正常把p标签粘贴，所以大家要讨论下这样的行为怎么统一处理比较合适。
