### ISSUE TITLE
打出中文用鼠标选中文字不能监听到内容

### ISSUE THREAD

**Issue by jinwen98** [wangeditor-team/wangEditor#2787]
## bug 描述

*打出中文用键盘中的数字选择可以监听到内容  用鼠标选中文字就不能监听到内容*

## 你预期的样子是？

*鼠标选中文字应该也可以双向绑定内容*

## 浏览器及版本号

*chrome 86.0.4240.198*

## wangEditor 版本

*^3.1.1*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 打出中文
- 鼠标选中文字
- 内容没有绑定赋值

**Comment by hahaaha** [comment]
可以试试升级到v4版本

**Comment by UltramanWeiLai** [comment]
目前 v3 版本已经不维护了，请升级到 v4 版本，如还有其他问题可以进群交流或者提交一个新的 issue
