### ISSUE TITLE
a标签修改字体颜色后，敲回车字体颜色消失

### ISSUE THREAD

**Issue by SkyEternity** [wangeditor-team/wangEditor#2788]
## bug 描述

a标签修改字体颜色后，敲回车字体颜色消失

## 你预期的样子是？

a标签可以设置颜色

## 浏览器及版本号

chrome

## wangEditor 版本

*4.5.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接在官网demo里面测试  https://www.wangeditor.com/

**Comment by liuqh0609** [comment]
交叉测试： @q378532364
