### ISSUE TITLE
未开始粘贴过滤相关配置，却无法将图片粘贴至富文本框中

### ISSUE THREAD

**Issue by 1263080327** [wangeditor-team/wangEditor#2789]
## bug 描述

未开始粘贴过滤相关配置，却无法将图片粘贴至富文本框中

## 你预期的样子是？

可以将图片粘贴至富文本框中

## 浏览器及版本号

Google Chrome 版本 87.0.4280.141（正式版本） （64 位）

## wangEditor 版本

4.5.2

## 官网能否复现该 bug ？

官网不能，但在官网提供的在线体验 demo ：https://codepen.io/collection/DNmPQV的每一个富文本编辑器实例都能复现此BUG

## 最小成本的复现步骤

- 步骤一 通过如下配置实例化富文本编辑框
const content = new WangeEditor();
content.create();
- 步骤二 通过微信客户端，进行截图
- 步骤三 在富文本编辑框编辑框中进行粘贴操作

**Comment by UltramanWeiLai** [comment]
默认是没有设置 图片上传 和 base64 的。
如果你需要复制粘贴图片，需要设置 上传图片 的相关配置，或者设置 base64 保存图片，二选其一
editor.config.uploadImgShowBase64 = true
