### ISSUE TITLE
4.6.2版修复wps粘贴样式bug后出现新问题

### ISSUE THREAD

**Issue by easyJone** [wangeditor-team/wangEditor#2791]
## bug 描述

*4.6.2版本修复4.6.1版本的[bug](https://github.com/wangeditor-team/wangEditor/issues/2546)后，出现了新问题：富文本默认过滤掉粘贴样式，但editor.config.pasteFilterStyle = false设置不生效了*

## 你预期的样子是？

*editor.config.pasteFilterStyle = false应可以保留从wps全选复制粘贴过来的样式*

## 浏览器及版本号

*谷歌版本 87.0.4280.88（正式版本） (x86_64)*

## wangEditor 版本

*4.6.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：打开官方demo粘贴过滤案例
- 步骤二：设置editor.config.pasteFilterStyle = false
- 步骤三：粘贴wps中带样式的文案，发现步骤二设置没起作用
[官方demo](https://codepen.io/xiaokyo-the-bold/pen/vYXGyrL)

**Comment by UltramanWeiLai** [comment]
该问题可以移步到 #2806 去跟踪
