### ISSUE TITLE
增加一个“清除选中文本格式”功能

### ISSUE THREAD

**Issue by xiaqii** [wangeditor-team/wangEditor#2794]
## 清除选中文本格式

*这个还是比较常用了，，*

## 提炼几个功能点

- 选中区块
- 清除所有格式

## 原型图

清除选中文本格式

## 可参考的案例

清除选中文本格式

**Comment by echoLC** [comment]
这个我们有考虑，只不过还没那么快，因为功能还比较复杂。

**Comment by UltramanWeiLai** [comment]
该问题已经在我们的代办当中了，因为负责程度的原因，目前还没有进入队列中，可以移步到 #2528 中跟进信息
