### ISSUE TITLE
拷贝文本粘贴进h1标签后将其修改为正文不生效

### ISSUE THREAD

**Issue by maplelfs** [wangeditor-team/wangEditor#2795]
## bug 描述

点击H选择h1标签，输入title，删除title，然后拷贝几行文本粘贴进h1标签内，左键选中这三行文本时左上H是高亮的，想要将其修改成正文，不生效，h1标签一直存在

## 你预期的样子是？

选中这三行文本，可以将其修改成正文

## 浏览器及版本号

版本 87.0.4280.141（正式版本） （64 位）

## wangEditor 版本

4.6.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
![image](https://user-images.githubusercontent.com/32224786/104585549-2118e300-569f-11eb-898f-f121d64f3a55.png)

- 步骤二
![image](https://user-images.githubusercontent.com/32224786/104585601-3a219400-569f-11eb-972f-8d2786084082.png)

**Comment by UltramanWeiLai** [comment]
标题标签目前不支持多行设置，你可以单行单行的设置为 正文
