### ISSUE TITLE
封装wangeditor成组件，使用v-model时，最新4.6.3版本光标位置还是有问题

### ISSUE THREAD

**Issue by yu530feng** [wangeditor-team/wangEditor#2799]
## bug 描述

封装wangeditor成组件，使用v-model双向绑定时，光标定位有问题。在第一行输入会自动定位到最后，如下图

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

4.6.3

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

mounted() {
  descEditor.config.onchange = (html) => {
   this.content= html
  }
},
watch: {
  content(v) {
    this.descEditor.txt.html(v)
  },
},

![wangeditor](https://user-images.githubusercontent.com/8703634/104671594-113de500-5719-11eb-9e08-673bc3bf00ec.gif)
- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
因为我们项目是基于 TypeScript 的，所以是不支持双向数据绑定的，其实你稍微思考一番就能明白为什么光标会跑到最后。
你设置双向数据绑定基于 editor.txt.html() 去设置的，这个设置会替换掉编辑区域内的内容，那么原先选区区域也就是光标的位置就会失效，而且一般来说富文本编辑器也用不到双向数据绑定，如果只是想子传父，可以通过抛出 onchange 事件完成

**Comment by yu530feng** [comment]
> 因为我们项目是基于 TypeScript 的，所以是不支持双向数据绑定的，其实你稍微思考一番就能明白为什么光标会跑到最后。
> 你设置双向数据绑定基于 editor.txt.html() 去设置的，这个设置会替换掉编辑区域内的内容，那么原先选区区域也就是光标的位置就会失效，而且一般来说富文本编辑器也用不到双向数据绑定，如果只是想子传父，可以通过抛出 onchange 事件完成

你上面说的只是富文本编辑器只是针对最基本的应用场景，一个页面编辑器的情况，那么写一个onchange事件函数可以接受，但比如：一个页面3-5个编辑器的场景、编辑器中内容是根据条件切换异步获取后变化的场景，肯定是封装成双向绑定是最理想的，而不是每个页面都去重复写一遍onchange事件。

**Comment by clinfc** [comment]
这个问题是你自己封装的不当造成的。你可以看下这篇文章[https://juejin.cn/post/6915967073432633357](https://juejin.cn/post/6915967073432633357)

**Comment by clinfc** [comment]
根据你的代码可以解读为：编辑器内容变化 ，发布 change => 赋值给 content => vue 监听到 content 变化 => 把新值赋值给编辑器
你认为上面的逻辑合理吗？

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
