### ISSUE TITLE
react添加待办事项后清空文本框报错

### ISSUE THREAD

**Issue by Peanutlyl** [wangeditor-team/wangEditor#2800]
## bug 描述

输入任意文字，点击添加待办事项，再全部删除，报错TypeError: Cannot read property 'attr' of undefined

## 你预期的样子是？

回复初始状态，无任何报错。

## 浏览器及版本号

Google Chrome版本 87.0.4280.141（正式版本） （64 位）

## wangEditor 版本

^4.0.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
- 文本框中输入1
- 步骤二
- 点击待办事项
- 步骤三
- 按两下删除键

**Comment by UltramanWeiLai** [comment]
function isTodo($topSelectElem: DomElement) {
    return $topSelectElem.attr('class') === 'w-e-todo'
}
$topSelectElem 需要做一个非空验证
