### ISSUE TITLE
firefox插入表格光标无法跳出table

### ISSUE THREAD

**Issue by 86driver** [wangeditor-team/wangEditor#2801]
## bug 描述

firefox插入表格按delete到表格内部之后光标跳出表格

## 你预期的样子是？

能够跳出表格

## 浏览器及版本号

火狐最新版

## wangEditor 版本

最新版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一：在firefox插入表格
- 步骤二：按delete，进入表格后，无法跳出表格

**Comment by 86driver** [comment]
需要注意一下 https://github.com/wangeditor-team/wangEditor/issues/2760
的问题。

**Comment by 86driver** [comment]
参考ck editort 在table 最后delete的方案

**Comment by echoLC** [comment]
在 chrome 下插入表格，把光标移到光标的末尾，然后按删除键报错，如下图：

![image](https://user-images.githubusercontent.com/15011780/105858612-78676d80-6026-11eb-91f9-167898f596ea.png)

**Comment by 86driver** [comment]
> 在 chrome 下插入表格，点击表格末尾空白的地方，光标闪烁一下后，控制台报错，如下图：
> 
> ![image](https://user-images.githubusercontent.com/15011780/105858612-78676d80-6026-11eb-91f9-167898f596ea.png)

已跟刘庆华沟通， 他统一处理这个问题 @liuqh0609
