### ISSUE TITLE
对齐方式中的两端对齐不能正确生效

### ISSUE THREAD

**Issue by A-passing-of-MOHS** [wangeditor-team/wangEditor#2802]
## bug 描述

对齐方式中的两端对齐不能正确生效 标签中已经存在了“textalign justify” 可文本只是左对齐
![GIF 2021-1-15 17-06-34](https://user-images.githubusercontent.com/48318560/104705486-ecfff980-5754-11eb-8f67-57e2d5823cc0.gif)

## 浏览器及版本号

谷歌浏览器 87.0.4280.141

## wangEditor 版本

v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by echoLC** [comment]
![image](https://user-images.githubusercontent.com/15011780/104902775-19687f80-59ba-11eb-8532-09674cad2754.png)
请仔细理解两端对齐的定义，再来提问题。
