### ISSUE TITLE
【feat】秀米和编辑器的适配和接入

### ISSUE THREAD

**Issue by mygithublxx** [wangeditor-team/wangEditor#2803]
## 问题描述

*秀米复制过来的文章视频会被过滤掉
使用百度编辑器和wangeditor粘贴的内容，明显很多地方不一样*

## wangEditor 版本

*^4.5.4*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- [从秀米粘贴一篇带有视频的文章](https://xiumi.us/#/studio/papers)
- 找到编辑器上，发现视频没了

**Comment by mygithublxx** [comment]
后来我自己测试，图片应该没有问题，就是视频会丢失，希望官方早日解决，不想换其他的编辑器用，就喜欢这款超好用的编辑器

**Comment by qianfengg** [comment]
您好，关于秀米适配和接入，我们做了调研，秀米要求内核是 ueditor ，而我们不是，所以解决成本比较高，但是我们会持续关注这个问题，会继续尝试解决，给您带来使用的不便尽请谅解。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。

**Comment by zhang1024899756** [comment]
v5版本接入秀米和135也会出现内容样式丢失的情况，要是能出一款插件就好了，有在考虑吗
