### ISSUE TITLE
给文本设置a标签属性后原来的样式消失了

### ISSUE THREAD

**Issue by Linindoo** [wangeditor-team/wangEditor#2807]
## bug 描述

先给一段文字设置 样式，比如字体，然后设置链接属性，设置完成后原来的字体样式没有了

## 你预期的样子是？

希望原来的样式能保留

## 浏览器及版本号

Google Chrome 版本 87.0.4280.141（正式版本） （64 位）

## wangEditor 版本

官网demo

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

按照描述操作就行

**Comment by echoLC** [comment]
你可以先将文字设置链接，然后再改它的颜色。这个属于可以优化的点，我们会视情况考虑。

**Comment by hahaaha** [comment]
交叉测试： @liuqh0609
