### ISSUE TITLE
设置FontWeight功能

### ISSUE THREAD

**Issue by JustForLucky** [wangeditor-team/wangEditor#2810]
## 功能描述

*目前的加粗功能是，点击“B”，增加b标签。希望新增设置FontWeight功能，可以自定义描述和值。交互类似字体和字号设置。*

## 提炼几个功能点

- 自定义FontWeight选项
- 根据选项设置对应的FontWeight

## 原型图

![image](https://user-images.githubusercontent.com/12389643/104896712-76603780-59b2-11eb-86a7-666240de4544.png)

## 可参考的案例

*无*

**Comment by echoLC** [comment]
可以考虑使用自定义菜单扩展此功能。

**Comment by JustForLucky** [comment]
> 可以考虑使用自定义菜单扩展此功能。
现在是使用自定义菜单扩展的～只是未来希望可以有原生支持～☺️

**Comment by UltramanWeiLai** [comment]
该功能，我们讨论了下后，觉得需求度不是很大，而且自定义菜单实现也不难，暂且可能不考虑去增加这个功能
