### ISSUE TITLE
使用“代码”功能，在提交的时候会把P标签移除掉。

### ISSUE THREAD

**Issue by GlaryJoker** [wangeditor-team/wangEditor#2812]
## bug 描述

*使用“代码”功能，在提交的时候会把P标签移除掉。*

## 你预期的样子是？

*<p>不要移除*

## 浏览器及版本号

*Chrome Version 87.0.4280.66*

## wangEditor 版本

*4.6.2*

## 官网能否复现该 bug ？

官网没有submit

## 最小成本的复现步骤

submit一下就行了。

**Comment by echoLC** [comment]
请详细描述问题的重现步骤，我们方便重现问题。

**Comment by GlaryJoker** [comment]
就是向服务器端提交的时候<pre>标签内的<p>标签被注释掉了。例如<pre><p></p></pre>内容，<p>标签被注释掉了。

**Comment by GlaryJoker** [comment]
就是向服务器端提交的时候<pre>标签内的<p>标签被注释掉了。例如
`
<pre><p></p></pre>
`
内容，<p>标签被移除掉了

**Comment by GlaryJoker** [comment]
`<pre><p></p></pre>`

**Comment by GlaryJoker** [comment]
代码块功能：`<pre><p></p></pre>`向服务器提交的时候`<p></p>`被移除了。

**Comment by UltramanWeiLai** [comment]
> 代码块功能：`<pre><p></p></pre>`向服务器提交的时候`<p></p>`被移除了。
 **最小成本的复现步骤**
你说的太笼统了
我在获取 html 标签的时候 p 标签依旧还在。
![image](https://user-images.githubusercontent.com/23336585/105186243-799f2300-5b6c-11eb-8ea2-fee14f5a13de.png)

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
