### ISSUE TITLE
osx系统Chrome浏览器下command+a全选后command+v黏贴 内容错误

### ISSUE THREAD

**Issue by komaedaXnagito** [wangeditor-team/wangEditor#2814]
## bug 描述

*osx系统Chrome浏览器下command+a全选后command+v黏贴 内容错误
全选的内容没有被替换成黏贴的内容，而是全选的内容还在，黏贴的内容会出现在光标的位置*

## 你预期的样子是？

*全选内容被替换成黏贴的内容*

## 浏览器及版本号

*Chrome 87.0.4280.141*

## wangEditor 版本

*4.6.3*

## 官网能否复现该 bug ？

能
## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 https://www.wangeditor.com/ 打开官网的首页
- 步骤二 commond+a全选demo编辑器的内容
- 步骤三 commond+c 复制 然后 commond+v 黏贴 整体内容变多，全选的内容没有被替换
使用鼠标右键，然后选择全选或者直接使用鼠标左键框选全部部分则不会出现这个问题

**Comment by rsl140** [comment]
交叉测试人员: @lkw199711  @daqianduanshuo
