### ISSUE TITLE
粘贴内容过长编辑器无法粘贴进去，页面卡死

### ISSUE THREAD

**Issue by cherishing** [wangeditor-team/wangEditor#2815]
## bug 描述

[*复制一下链接的内容，*](http://baoxian.pingan.com/uploadfile/clause/file/pingananzhenwuyoubaoxiantiaokuan.pdf?WT.mc_id=T00-BD-SSC-PP--XZ20190724-029477&WT.srch=1),粘贴到富文本编辑器，无反应，页面卡死，但粘贴到控制台内容显示。

## 你预期的样子是？

*正常显示粘贴内容*

## 浏览器及版本号

* 版本 87.0.4280.141（正式版本） (x86_64)*

## wangEditor 版本

*4.6.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  复制上面链接内容，粘贴到官网demo,页面卡死，且内容未被复制进去
- 步骤二
- 步骤三

**Comment by blackhu0804** [comment]
使用全选复制到官网并未复现

**Comment by cherishing** [comment]
> 使用全选复制到官网并未复现

复制少不部分内容能复制进去，但是你全选，复制到富文本页面就卡死，同时你粘贴到浏览器控制台可以看到内容可以正常显示。

**Comment by cherishing** [comment]
> 使用全选复制到官网并未复现
复制字数内容达到3万，页面卡死

**Comment by xiaokyo** [comment]
问题所在：复制pdf中带有<50mmHg的东西会导致SimpleHtmlParser的循环不会停止
