### ISSUE TITLE
官网表情菜单 panel ，表情图片太少了，建议弄的丰富一些，不要让用户再自己配置

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#2816]
## bug 描述

表情菜单 panel ，表情图片太少了

![image](https://user-images.githubusercontent.com/9583120/105007244-b1c23b00-5a72-11eb-8d7b-f2dc34916f52.png)

## 你预期的样子是？

1. 建议弄的丰富一些，最好撑满 panel，不要让用户再自己配置
2. 认真规划一下表情 panel ，参考一下微信等聊天工具，看看大家日常需要的表情有哪些？合理规划一下，现在这个太随意了，弄了 4 个 tab 。

## 浏览器及版本号

chrome 87

## wangEditor 版本

4.6.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

官网，插入表情，即可看到，上面有截图。

**Comment by wangfupeng1988** [comment]
1. 考虑用户的真实使用场景
2. 尽量减少用户的配置，傻瓜式一些

**Comment by liuqh0609** [comment]
交叉测试： @YmCoke
