### ISSUE TITLE
img标签未关闭

### ISSUE THREAD

**Issue by elitetyc** [wangeditor-team/wangEditor#2817]
上传图片后，生成的标签是
`<img src="url">`
这样的标签导致itext转pdf会出错
期望的内容是
`<img src="url" />`

**Comment by wangfupeng1988** [comment]
我们自己在 `editor.txt.html()`处理一下吧。

**Comment by UltramanWeiLai** [comment]
单闭合的标签可能都需要关注一下 img  br 什么的

**Comment by rsl140** [comment]
交叉测试 @lkw199711
