### ISSUE TITLE
todo 样式有问题

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#2818]
## bug 描述

编辑器内插入 todo 列表，样式有问题。如下图

![image](https://user-images.githubusercontent.com/9583120/105114933-df56c500-5b02-11eb-86f1-b17f02616d2e.png)

## 你预期的样子是？

样式正常即可。

## 浏览器及版本号

chrome 87

## wangEditor 版本

4.6.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 输入三行文字
- 选中这三行文字
- 设置 todo

**Comment by hahaaha** [comment]
交叉测试 @liuqh0609
