### ISSUE TITLE
上传图片建议添加选择图片媒体库回调功能

### ISSUE THREAD

**Issue by easydowork** [wangeditor-team/wangEditor#2819]
## 功能描述

*点击上传图片按钮,选择网络图片,在插入的旁边添加一个按钮,此按钮可以从自定义的图片媒体库选择图片地址插入到上方的输入框*

## 提炼几个功能点

- 添加选择图片按钮
- 可选择服务器提供图片列表或回调方式弹窗

**Comment by wangfupeng1988** [comment]
可以先做 https://github.com/wangeditor-team/wangEditor/issues/2832 ，再做这个。

**Comment by rsl140** [comment]
交叉测试：@Gavin-yh
