### ISSUE TITLE
bug: 有时候在控制台会出现 TypeError 报错

### ISSUE THREAD

**Issue by echoLC** [wangeditor-team/wangEditor#2820]
## bug 描述

在 react 中因为 TypeError 导致编译出错，导致无法使用编辑功能，具体信息如下图

![image](https://user-images.githubusercontent.com/15011780/105133358-949b7400-5b27-11eb-9189-5c835f51dbff.png)

## 你预期的样子是？

不出现报错

## 浏览器及版本号

chrome最新版本

## wangEditor 版本

v4.6.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

不能100%重现，某些情况下可能会出现这个问题。

- 步骤一
- 步骤二
- 步骤三

**Comment by echoLC** [comment]
这是我们公司有个团队在试用我们编辑器的时候，偶尔某些情况出现的错误，这也是 JS 中比较经典的 TypeError，图中这个判断的方式是有隐藏的问题。如果大家在现有的PR或者修复当中，用了这个判断，可以调整下，审核PR的同学也注意下，后续在修复 issue 的时候看到这个问题，也随手记得改一下，可以加个可选链的操作符解决。

**Comment by echoLC** [comment]
目前已知的触发条件包含： 编辑区域失焦的情况下切换文字颜色。

**Comment by echoLC** [comment]
插入分割线 继续输入就可以复现类似上次说的bug。如下图：

![image](https://user-images.githubusercontent.com/15011780/105472293-b8e98300-5cd6-11eb-888f-2c8fa6e23393.png)

**Comment by lichenabson** [comment]
![image](https://user-images.githubusercontent.com/20200267/105671573-e5dba700-5f1d-11eb-947e-ecdf1ef132cd.png)
我也发现一个

**Comment by blackhu0804** [comment]
全选之后删除 火狐稳定复现
![image](https://user-images.githubusercontent.com/18188260/105868780-7e168080-6031-11eb-8545-802cfd7d0466.png)

**Comment by 86driver** [comment]
插入table之后全选还是会出现

**Comment by liuqh0609** [comment]
交叉测试 @86driver

**Comment by anxuanzi** [comment]
我也遇到了同样的问题，不知道到底怎么触发的，貌似很随机（我的使用环境：vue3+parcejs2）
![image](https://user-images.githubusercontent.com/24320758/106710639-1c16c780-65ab-11eb-96bd-53851f6224a9.png)
