### ISSUE TITLE
插入网络图片，自定义校验通过之后还存在隐藏校验。

### ISSUE THREAD

**Issue by AlpsChan** [wangeditor-team/wangEditor#2823]
## 问题描述
插入的网络图片，是已经存放在服务端的图片，图片地址上面有签名参数。
*请输入遇到的问题...*
源码存在隐藏的正则校验，这个正则校验无法重构，导致网络图片一直插入不了。
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：插入网络图片
- 步骤二：输入http://core-platform.oss-cn-hangzhou.aliyuncs.com/2021/1/20/d30a085d-00c9-4be0-b18e-2b5e7b95572d..jpeg?Expires=4764737222&OSSAccessKeyId=LTAISn0yix1hGNLs&Signature=3gDLGraaZ%2BXmfS0UoSzunBr6%2BI4%3D
- 步骤三：提示‘您插入的网络图片无法识别’

**Comment by UltramanWeiLai** [comment]
升级一下版本应该即可解决该问题

**Comment by blackhu0804** [comment]
新版本已经优化这个问题，去掉了正则校验，如果需要校验，可以自行添加校验函数进行检查
