### ISSUE TITLE
上传视频，tooltip 上的“删除”点击没反应

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#2824]
## bug 描述

如题，删除视频没反应。

![image](https://user-images.githubusercontent.com/9583120/105275146-96be0b00-5bd9-11eb-8b7e-be5503a00d67.png)

## 你预期的样子是？

可通过 tooltip 删除视频

## 浏览器及版本号

chrome 87

## wangEditor 版本

4.6.3

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 访问测试页 http://106.55.153.217:8881/master/examples/upload-video.html
- 清空编辑区域内容
- 输入一行文字（重要）
- 回车，新起一个空行，上传视频
- 删除视频，就复现了

**Comment by webpig** [comment]
我也遇到这个问题，富文本内容不好删除

**Comment by webpig** [comment]
多个视频，删除一个会全部删除。。。
