### ISSUE TITLE
删除视频后，再输入文字，第一行文字不在 <p> 包裹之内（已和李大佬微信沟通）

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#2825]
## bug 描述

如题。把编辑器内容清空，只上传一个视频。然后删除视频，DOM结构是这样的（此时注意看光标位置，也不对）

![image](https://user-images.githubusercontent.com/9583120/105275922-4182f900-5bdb-11eb-853a-c8ce6f6c90a6.png)

然后输入文字，第一行就不会被 `<p>` 包裹

![image](https://user-images.githubusercontent.com/9583120/105275941-4fd11500-5bdb-11eb-992c-2027325d7754.png)

## 你预期的样子是？

文字都要被 `<p>` 包裹

## 浏览器及版本号

chrome 87

## wangEditor 版本

4.6.3

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 访问 http://106.55.153.217:8881/master/examples/upload-video.html
- 清空全部内容，上传一个视频
- 删除视频，观察 DOM 结构
- 继续输入文字，观察 DOM 结构

**Comment by Gavin-yh** [comment]
问题以前已经和童哥确认，没有复现，关联issue可能修复了，后续有问题可以再反馈
