### ISSUE TITLE
如果视频在最后一行，无法在视频后面继续输入文字

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#2826]
## bug 描述

如题。如果编辑器里，最后一个是视频，那么想继续在视频下面输入文字，就不行了。

PS：代码块、table ，也都有类似问题。可以和张温剑、颜彪沟通一下。

## 你预期的样子是？

可以继续在下面输入文字

## 浏览器及版本号

chrome 87

## wangEditor 版本

4.6.3

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 访问 http://106.55.153.217:8881/master/examples/upload-video.html
- 清空内容
- 输入一行文字
- 回车，上传视频
- 此时，再想在视频下面输入文字，就做不到了。

**Comment by wangfupeng1988** [comment]
参考目前的表格。如果表格是最后一行，后面永远有一个空行。（记得是颜彪开发的该功能）

**Comment by 86driver** [comment]
看了一下  又是firefox浏览器的问题- -

**Comment by sunliyun** [comment]
请问这个问题是解决了吗？发布版本了吗？

**Comment by wangfupeng1988** [comment]
@sunliyun 建议用 v5 吧 https://www.wangeditor.com/v5/ ，v5 没有这个问题。
v5 现在已经稳定了，下月会正式发布
