### ISSUE TITLE
上传本地视频文件回调时报insertVideoFn is not defined

### ISSUE THREAD

**Issue by Tony2021** [wangeditor-team/wangEditor#2827]
根据文档说明指导开发上传本地视频功能，回调时报insertVideoFn is not defined

**Comment by wangfupeng1988** [comment]
请按照 issue 模板重新提交。
不符合模板的不予受理。

**Comment by Tony2021** [comment]
这个功能比较急，今晚要完成，能否先直接回复正确的方法是什么，我再按模板提交issue


在2021年1月21日 13:32，王福朋<notifications@github.com> 写道：

Closed #2827.

**Comment by wangfupeng1988** [comment]
你就说了一句话，我都不知道哪里、怎么复现问题，我也不知道该如何解决。
光这个 insertVideoFn 函数，就在三个地方出现过，我也不知道你说的是哪里。

![image](https://user-images.githubusercontent.com/9583120/105284639-d858b100-5bed-11eb-9181-0645d4ca0afa.png)

至少，你得告诉我们如何复现问题。我们才能去解决。
