### ISSUE TITLE
允许设置图片默认在富文本框中展示的大小的百分比

### ISSUE THREAD

**Issue by zwb3707811** [wangeditor-team/wangEditor#2829]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
![image](https://user-images.githubusercontent.com/46095922/105343620-d1956280-5c1c-11eb-9806-b90c43f0447f.png)

**Comment by UltramanWeiLai** [comment]
请按照模板提交相应的信息，否则是不受理的。
另外你这需求写个 img { width: 50% } 不就可以了？？？

**Comment by zhuxiwen** [comment]
``> ## 功能描述
> _请输入内容……_
> 
> ## 提炼几个功能点
> * 功能1
> * 功能2
> * 功能3
> 
> ## 原型图
> _涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观_
> 
> ## 可参考的案例
> _是否已有可参考的案例（如其他编辑器），有的话请给出链接_
> ![image](https://user-images.githubusercontent.com/46095922/105343620-d1956280-5c1c-11eb-9806-b90c43f0447f.png)

customUploadImg时，使用自定义的insertImg 具体看【https://github.com/wangeditor-team/wangEditor/blob/f4d254d19bbd6671a7b5dddae60269865675dfe4/src/menus/img/upload-img.ts】
