### ISSUE TITLE
IE11中，选中文字无法设置颜色（偶发性）

### ISSUE THREAD

**Issue by liuqh0609** [wangeditor-team/wangEditor#2834]
## bug 描述

iE11中，设置文字颜色时，选区丢失，颜色无法设置

## 你预期的样子是？

正常设置颜色

## 浏览器及版本号

IE11

## wangEditor 版本

4.6。4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

1. 在官网可以直接选中第一行
2. 设置字体颜色为绿色

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/105622012-75af2180-5e48-11eb-838f-670b0a04b21a.png)
我没有在官网上复现

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
