### ISSUE TITLE
本地上传视频后，视频无法排版（居中、居右）

### ISSUE THREAD

**Issue by DengMingHao** [wangeditor-team/wangEditor#2840]
## bug 描述
本地视频上传后，想对视频进行排版（居左、居中、居右）操作，无法操作。

## 你预期的样子是？
视频应该能像图片一样进行排版。

## 浏览器及版本号
360极速浏览器
版本号: V13.0.2206.0

Edge

## wangEditor 版本
V4.6.4

## 官网能否复现该 bug ？
官网没有提供本地上传视频功能。

## 最小成本的复现步骤
http://106.55.153.217:8881/master/examples/upload-video.html
测试网址，自行尝试【本地上传视频】功能。

**Comment by 18720551903** [comment]
同样的困扰
