### ISSUE TITLE
在一个空白的编辑器中，直接进行【本地上传视频】，会导致光标无法在视频之后输入内容。

### ISSUE THREAD

**Issue by DengMingHao** [wangeditor-team/wangEditor#2841]
## bug 描述
在一个空白的编辑器中，直接进行【本地上传视频】，会导致光标无法在视频之后输入内容。

## 你预期的样子是？
正常应该能在视频后面进行内容输入。

## 浏览器及版本号
360极速浏览器
版本号: V13.0.2206.0

Edge

## wangEditor 版本
V4.6.4

## 官网能否复现该 bug ？
官网没有提供本地上传视频功能。

## 最小成本的复现步骤
http://106.55.153.217:8881/master/examples/upload-video.html
清空编辑器内容后，直接【上传本地视频】。

**Comment by UltramanWeiLai** [comment]
该问题已经收录，可以移步到 #2826 跟进
