### ISSUE TITLE
有序列表前面的序号，字体大小不会根据序号后面的字体变化，一直都是一个很小的数字

### ISSUE THREAD

**Issue by justinluhui** [wangeditor-team/wangEditor#2842]
## bug 描述

如题，有序列表前面的序号，字体大小不会根据序号后面的字体变化，一直都是一个很小的数字
<ol>
<li><font size="6">第一行</font></li><li><font size="6">第二行内容能</font></li><li><font size="6">第三行内容啦啦啦</font></li></ol>

## 你预期的样子是？

修改有序列表的字体大小，前面的序号大小也会跟着变化

## 浏览器及版本号

最新版chrome

## wangEditor 版本

4.6.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
css style 行为，我也查看了一些常规的在线文档都是这样的，可以去了解一下  list-style 。
有需要的话，就手写序列吧 
```
1. 1111
2. 2222
```
