### ISSUE TITLE
上传至阿里云OSS返回的结果insertImgFn放URL，会报错（格式png的图片） 

### ISSUE THREAD

**Issue by cheng9572** [wangeditor-team/wangEditor#2843]
![image](https://user-images.githubusercontent.com/45056779/105706337-5ef1f300-5f4c-11eb-9988-c21b4716fc26.png)

上传jpg到里没问题，但是png就报错了

**Comment by UltramanWeiLai** [comment]
报错信息已经很明显说明了问题所在。建议查查 403 代表什么意思吧
还有请按照模板进行提交，否则是不受理的
