### ISSUE TITLE
使用插入链接功能，panel 靠右偏移，不在链接按钮下方

### ISSUE THREAD

**Issue by blackhu0804** [wangeditor-team/wangEditor#2844]
## bug 描述

![image](https://user-images.githubusercontent.com/18188260/105722531-b8641d00-5f60-11eb-9da7-64ac46432fe0.png)
图片，表情，视频，链接 panel 出现在同一个位置，没有出现在对应按钮下方

## 你预期的样子是？

panel 显示在对应按钮下方

## 浏览器及版本号

chrome 87.0.4280.88

## wangEditor 版本

v4.6.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接引入初始化编辑器即可

**Comment by clinfc** [comment]
说实话，这个不属于 bug，本来就是这样设计的，drop list 跟随 菜单显示，panel 居中显示。当然这个居中可能会有10像素左右的偏差

**Comment by ShiDacheng** [comment]
链接这个panel 经常会莫名其妙消失

**Comment by zshno1** [comment]
这个引起的原因是菜单栏其他都选项都是hover触发的。点击完链接不小心hover到其他菜单选项时，那么输入链接的弹框就会消失。建议其他选项都改成click事件触发

**Comment by wangfupeng1988** [comment]
> 这个引起的原因是菜单栏其他都选项都是hover触发的。点击完链接不小心hover到其他菜单选项时，那么输入链接的弹框就会消失。建议其他选项都改成click事件触发

@zshno1 这个体验问题，我新提了一个 issue https://github.com/wangeditor-team/wangEditor/issues/2999 ，会单独解决的。

**Comment by qianfengg** [comment]
@q378532364 交叉测试
