### ISSUE TITLE
给文本框设置文本之后，再执行上传图片操作，会报错

### ISSUE THREAD

**Issue by ymforever555** [wangeditor-team/wangEditor#2846]
## bug 描述

使用editor.txt.html()设置文本之后，直接上传图片会报wangEditor.js?6fad:20102 Uncaught TypeError: Cannot read property 'parentNode' of undefined错误，先修改文本再上传之后，则不会报错。

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
该问题已经收录，可以移步到 #2820 中去跟踪
