### ISSUE TITLE
doc文件复制有问题

### ISSUE THREAD

**Issue by WaitingAloneU** [wangeditor-team/wangEditor#2847]
## bug 描述

从doc文件中复制出来的内容,前面会多了很多样式的内容

## 你预期的样子是？

不要有这种样式的内容

## 浏览器及版本号

chrome, 87.0.4280.141

## wangEditor 版本

v4

## 官网能否复现该 bug ？

不能, 但是, 从doc复制到官网的插件里面, 样式都没有了.

## 最小成本的复现步骤
直接从doc文件里面复制内容到编辑器内容

测试环境的截图
![image](https://user-images.githubusercontent.com/15140300/105831209-67f0cc00-6001-11eb-91dd-2f98e9e684c2.png)
![image](https://user-images.githubusercontent.com/15140300/105831302-8060e680-6001-11eb-83a2-5a8ed40e09aa.png)

**Comment by UltramanWeiLai** [comment]
升级一下版本吧 4.6.4 目前的版本

**Comment by WaitingAloneU** [comment]
我升级到4.6.4还是不行，但是降到3.1.1就可以了，不知道为什么。

**Comment by zgalive** [comment]
看一下设置 pasteFilterStyle, 需要设置为true

**Comment by hahaaha** [comment]
@WaitingAloneU 使用你在https://github.com/wangeditor-team/wangEditor/issues/2848  这个issue下提供的word在最新版本下尝试下来是正常的
<img width="1633" alt="截屏2021-01-27 上午11 20 36" src="https://user-images.githubusercontent.com/25847662/105937961-91f1cf00-6091-11eb-975a-02942f007ee3.png">

**Comment by WaitingAloneU** [comment]
知道了, 那我们改一下版本, 用4.6.4改一下配置再试试.

**Comment by WaitingAloneU** [comment]
看一下设置 pasteFilterStyle, 需要设置为true, 这个设置是粘贴的时候过滤样式吗? 不能过滤样式啊, 我就是需要word里面的样式, 才用的富文本编辑器. 过滤掉样式可行?

**Comment by WaitingAloneU** [comment]
@zgalive 麻烦再给看一下

**Comment by zgalive** [comment]
@WaitingAloneU 这个之前就是有bug，你可以搜一下issues 里面关键字word，我也在寻找一种完美的解决方案，但还没找到，只能先放弃保留样式，只黏贴纯文本了，比把style的内容黏贴出来好一点

**Comment by UltramanWeiLai** [comment]
我试了一下，不管 pasteFilterStyle 是 true 还是 false 粘贴都不会出现乱七八糟的 style 内容，但是确实显示是不带样式的。
显示不带样式我会重新提交一个 issue 作为跟踪 #2885
