### ISSUE TITLE
word文件内容无法复制进入编辑框内

### ISSUE THREAD

**Issue by WaitingAloneU** [wangeditor-team/wangEditor#2848]
## bug 描述

*请输入内容……*

## 你预期的样子是？

word文档的内容不能复制到编辑器中

## 浏览器及版本号

chrome 88.0.4324.104

## wangEditor 版本

3.1.1

## 官网能否复现该 bug ？

不能,

## 最小成本的复现步骤

把下面的word文件内容复制到编辑框内
[问题.docx](https://github.com/wangeditor-team/wangEditor/files/5877397/default.docx)

我之前提了个issue, 说升级到4.6.4能解决前面很多样式代码的问题, 但是不行, 我升级到4.6.4还是有那个问题, 我试了试, 只有3.1.1没有那个问题, 所以就降级到3.1.1了. 但是3.1.1又出现这个问题.

**Comment by hahaaha** [comment]
v3版本不在维护了。。。到这个issue下继续讨论吧https://github.com/wangeditor-team/wangEditor/issues/2847 。。。这个问题我先关闭了
