### ISSUE TITLE
4.6.4 版本 在文字空行处黏贴内容，内容会被复制到文本最下面

### ISSUE THREAD

**Issue by Aiden-Xi** [wangeditor-team/wangEditor#2852]
## bug 描述

在文字空行处黏贴内容，内容会被复制到文本最下面

## 你预期的样子是？

根据光标的位子，确定复制黏贴的内容

## 浏览器及版本号

谷歌浏览器：x86_64
## wangEditor 版本

4.6.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
在官网的内容里面随便空出几行
- 步骤二
 随意复制一段文本内容，在第一步空行中进行黏贴。
- 步骤三
内容没有准确的在光标停留的地方呈现，而是黏贴到文本框最下面去了。

**Comment by chenthreetrees** [comment]
```
// 如果是段落，为了兼容 firefox 和 chrome差异，自定义插入
                if (isParagraphHtml(html)) {
                    const $textEl = editor.$textElem
                    $textEl.append($(html))
                    // 如果选区是空段落，移除空段落
                    if (isEmptyParagraph($topElem)) {
                        $topElem.remove()
                    }
                    // 移动光标到编辑器最后的位置
                    const lastEl = $textEl.last()
                    if (!lastEl?.length) return
                    editor.selection.moveCursor(lastEl.elems[0])
                } else {
                    editor.cmd.do('insertHTML', `${formatHtml(pasteHtml)}`) // html
                }
```
这里源代码直接将 段落 直接 append 导致的，这个自定义插入是不是需要优化？

**Comment by zwb3707811** [comment]
我也出现了这个问题

**Comment by rsl140** [comment]
尝试用复现步骤执行，未复现该问题。可否将详细步骤再描述下？

**Comment by smallbad** [comment]
1在官网现有内容的基础上，在随便一行回车
2.随便在网上找一篇文章，选中两段以上的文字，一定要有换行的
3.粘贴到换行区域，则粘贴内容自动跑到底下了，控制台报错

**Comment by jeenkzou** [comment]
现在官网还是有这个问题呀？很容易复现，只能复制到最后一行

**Comment by duxuyang** [comment]
这个问题解决了吗，现在最新版还有这个问题

**Comment by q378532364** [comment]
过年我们休息了2周，修复后会发布，进入测试阶段了

**Comment by DLCnow** [comment]
大佬们好，请问预计什么时候发布，我现在bug卡在这里了，或者有什么办法可以临时用起来吗

**Comment by q378532364** [comment]
改源码这里是pr  https://github.com/wangeditor-team/wangEditor/issues/2852  你可以看下fileschange然后在看 https://github.com/wangeditor-team/wangEditor/tree/fix-paste-in-bottom 这边是提交的分支，

**Comment by DLCnow** [comment]
收到，感谢大佬

**Comment by duxuyang** [comment]
这个问题什么时候能解决发布版本，给个具体时间

**Comment by duxuyang** [comment]
这个问题导致现在的用户体验很差劲，能不能尽快测试发布版本

**Comment by duxuyang** [comment]
什么时候能发布
