### ISSUE TITLE
doc文件中的内容粘贴不全

### ISSUE THREAD

**Issue by MyGirs** [wangeditor-team/wangEditor#2853]
## bug 描述

 全选doc文档中的文字复制到编辑器中，文档中可能有隐藏的文字，粘贴到编辑器中，只显示隐藏文字之前的内容

## 你预期的样子是？

可不可以全部粘贴到编辑器中

## 浏览器及版本号

谷歌

## wangEditor 版本

3.1.1以及4.6.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by hahaaha** [comment]
可以提供下可以复现的文件么：）

**Comment by UltramanWeiLai** [comment]
啥是文档中可能有隐藏的文字？
能否提供文档文件或者demo？

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
