### ISSUE TITLE
粘贴过滤保留样式不生效

### ISSUE THREAD

**Issue by zhaoguangyue** [wangeditor-team/wangEditor#2856]
## bug 描述
粘贴过滤editor.config.pasteFilterStyle = false  设置为false不生效 粘贴完是一堆 style=“undefined”
*请输入内容……*
![image](https://user-images.githubusercontent.com/25996201/105960866-c3ca5c00-60b8-11eb-9463-5d07c6cdf35b.png)

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号
chrome最新版
*请输入内容……*

## wangEditor 版本
4.6.4
*请输入内容……*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
官网粘贴
（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
这边 wps 去复制粘贴的确无论是否过滤都是没有样式的，但是没有你这种 style=“undefined” 情况，请告诉我们，如何快速的浮现该问题

**Comment by zhaoguangyue** [comment]
在vue中，从npm包import的方式会有此问题

import Editor from 'wangeditor'

const editor = new Editor('#editor')
editor.config.pasteFilterStyle = false; 
。。。。

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/108447536-0851ad80-729b-11eb-9fe8-955d3ccf297c.png)
vue 下使用 npm 安装 import 引入
正常显示style

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
