### ISSUE TITLE
新增格式刷功能

### ISSUE THREAD

**Issue by jeenkzou** [wangeditor-team/wangEditor#2858]
## 文本格式刷

*在其他地方获取的文本，或者是复制进来的文本，难免会有格式不匹配的问题，需要格式刷来保证格式的统一性！*

## 可参考的案例

*tinymce格式刷功能：https://www.tiny.cloud/docs/enterprise/formatpainter/#tryourformatpainterplugindemo*

**Comment by hahaaha** [comment]
这个已在队列中 详细进度请关注这个issue https://github.com/wangeditor-team/wangEditor/issues/2528
