### ISSUE TITLE
扩展自定义菜单的顺序

### ISSUE THREAD

**Issue by yclgkd** [wangeditor-team/wangEditor#2859]
## 问题描述

*请输入遇到的问题...*

注册的自定义扩展菜单能否在菜单栏中指定显示的顺序？我尝试了在editor.config.menus中配置菜单的顺序，但没能起作用。

## wangEditor 版本

*请输入内容……*

4.6.4

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

![image](https://user-images.githubusercontent.com/31514100/105979614-d8b1ea00-60ce-11eb-806d-5c86d04817a0.png)

[复现的地址](https://codepen.io/yclgkd/pen/bGwXZzy)

**Comment by YmCoke** [comment]
请使用editor.menu.extend方法注册自定义菜单，可以实现扩展自定义菜单的顺序。[文档链接](https://doc.wangeditor.com/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html)

**Comment by YmCoke** [comment]
请使用editor.menu.extend方法注册自定义菜单，可以实现扩展自定义菜单的顺序。[文档链接](https://doc.wangeditor.com/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html)

**Comment by yclgkd** [comment]
> 请使用editor.menu.extend方法注册自定义菜单，可以实现扩展自定义菜单的顺序。[文档链接](https://doc.wangeditor.com/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html)

是让自定义菜单出现在菜单栏中的指定位置，不是在菜单栏末尾添加自定义菜单

**Comment by YmCoke** [comment]
> > 请使用editor.menu.extend方法注册自定义菜单，可以实现扩展自定义菜单的顺序。[文档链接](https://doc.wangeditor.com/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html)
> 
> 是让自定义菜单出现在菜单栏中的指定位置，不是在菜单栏末尾添加自定义菜单

是editor.menus.extend接口, 上面打错了。详细使用你可以看这个[demo](https://codepen.io/ymcoke/pen/poNKwxO)

**Comment by yclgkd** [comment]
> > > 请使用editor.menu.extend方法注册自定义菜单，可以实现扩展自定义菜单的顺序。[文档链接](https://doc.wangeditor.com/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html)
> > 
> > 
> > 是让自定义菜单出现在菜单栏中的指定位置，不是在菜单栏末尾添加自定义菜单
> 
> 是editor.menus.extend接口, 上面打错了。详细使用你可以看这个[demo](https://codepen.io/ymcoke/pen/poNKwxO)

问题已解决，thanks
