### ISSUE TITLE
项目中也使用了i18next，插件再用i18next, 会将项目中的多语言覆盖掉，导致项目的多语言没有翻译

### ISSUE THREAD

**Issue by lihaixing** [wangeditor-team/wangEditor#2860]
## 问题描述

* 项目中也使用了i18next，插件再用i18next, 会将项目中的多语言覆盖掉，导致项目的多语言没有翻译，这种怎么处理呢*

## wangEditor 版本

*4.6.4*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

**Comment by UltramanWeiLai** [comment]
你可以简单的去实现一个 i18next 的 t 方法，用来代替 i18next，目前编辑器中没有使用到计算之类的写法，只需要分隔字符串去拿值就可以了，或者你想一下是否能 new(整) 一个新的 i18next 对象出来。
编辑器内部初始化 i18next 就会把外部的配置整没

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
