### ISSUE TITLE
只给某一行或某段文字中的部分文字设置标题，会导致整行或整个段落样式受影响

### ISSUE THREAD

**Issue by Alangjun** [wangeditor-team/wangEditor#2861]
## bug 描述
**只给某一行或某段文字中的部分文字设置标题，会导致整行或整个段落样式受影响*请输入内容……***

## 你预期的样子是？
设置标题功能只对选中的那部分内容设置

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
标题是针对段落的而不是针对选中的文本的
如果想达到选中文字放大且加粗的实现方式 可以使用加粗+设置字号的方式
