### ISSUE TITLE
 强烈建议加上 <pre class="language-xxxx"><code></code></pre> 

### ISSUE THREAD

**Issue by jiechi** [wangeditor-team/wangEditor#2864]
## 提炼几个功能点

- 强烈建议加上 <pre class="language-xxxx"><code></code></pre>  主流的都是这样了  可以更好的支持highlightjs 和Prismjs 
- 图片上传 二次弹框可以去掉
- 功能3

## 原型图
![image](https://user-images.githubusercontent.com/33302789/106106937-3dc61800-6181-11eb-8b10-15d2d9c942ee.png)

**Comment by wangfupeng1988** [comment]
@lkw199711 看下吧

**Comment by lkw199711** [comment]
1.将为code标签添加类名，为标签内的语言类型。去除pre标签的type行内属性
2.弹框已经可以除去，设置‘editor.config.showLinkImg = false’，即可

**Comment by jiechi** [comment]
> 1.将为代码标签添加类名，为标签内部的语言类型。移除prelabel的类型行内部属性
> 2.弹框已经可以除去，设置'editor.config.showLinkImg = false'，即可

大写的优秀，大赞
