### ISSUE TITLE
怎么去掉富文本编辑器自动包裹一层的p标签

### ISSUE THREAD

**Issue by Mrchenyiyang123** [wangeditor-team/wangEditor#2866]
## 问题描述
在富文本编辑器编辑完内容后，输出的字符串都有一层p标签包裹，包括开始的一层无用的p标签
*请输入遇到的问题...*

## wangEditor 版本
"wangeditor": "^4.6.4"
*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一  编辑富文本编辑器，上传图片
- 步骤二  查看输出内容，每个外层都有p标签包裹

**Comment by hahaaha** [comment]
设计的时候就是每一个都在p标签内的。。。无用的输出后可以自己过滤下
