### ISSUE TITLE
连续复制 input 内容会换行

### ISSUE THREAD

**Issue by mzcc666GtHb** [wangeditor-team/wangEditor#2867]
## bug 描述

在vue2 生成的实例里面，连续复制粘贴 input 内容会换行

## 你预期的样子是？

不应该换行，而是应该在光标后面，我看是是因为 input 内容复制出来的内容被p标签包裹了，所以换行了，
按理说，复制input 的内容， 粘贴的后，应该是出现在 光标后面

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

4.6.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 在页面上写一个input 框 填充上内容
- 步骤二 复制 input 内容
- 步骤三  连续粘贴，连续粘贴，发现是一直换行的

**Comment by UltramanWeiLai** [comment]
input 复制的内容只会在文本末尾进行粘贴
直接在百度官网的输入框中写入文字并且复制即可复现

**Comment by UltramanWeiLai** [comment]
该问题应该和 #2852 是同一个问题，可以移步到 #2852 去跟踪
