### ISSUE TITLE
怎么去掉非文字下包裹的p标签

### ISSUE THREAD

**Issue by Mrchenyiyang123** [wangeditor-team/wangEditor#2868]
## 问题描述
上传图片，外层有个p标签包裹

*请输入遇到的问题...*
上传图片，外层有个p标签包裹

## wangEditor 版本
"wangeditor": "^4.6.4"

*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一  上传图片，查看返回的富文本html，会发现有p标签包裹img

**Comment by hahaaha** [comment]
编辑器的设计就是这样每一行的内容都会包裹在p元素中

**Comment by UltramanWeiLai** [comment]
一个 p 标签即代表一个段落，如果你不需要这个 p 标签可以自行使用正则表达式去做相应的处理，不过需要注意的是，回显到编辑器内的时候可能会有问题，所以并不建议这样去做。
