### ISSUE TITLE
使用edit.txt.html 设置内容为table的时候，无法添加行和添加列

### ISSUE THREAD

**Issue by spriteXY** [wangeditor-team/wangEditor#2872]
## bug 描述

使用edit.txt.html 设置内容为table的时候，无法添加行和添加列，而且删除行的时候会删除整个table，使用工具栏插入的表格可以正常使用

## 你预期的样子是？

当设置内容为table的时候，可以正常添加行和列，或者删除行

## 浏览器及版本号

Chrome 88.0.4324.104

## wangEditor 版本

4.6.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

链接：https://codepen.io/demon_place/pen/MWbWYdm

- 步骤一
- 
![image](https://user-images.githubusercontent.com/44464037/106224134-b5e21b80-621d-11eb-8536-fbf83375a0c5.png)
- 步骤二
- 点击右侧的添加行，或者删除行，即可复现

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/pull/2896
感谢 btea  提供的 pr ，已合并
