### ISSUE TITLE
无法上传jfif格式的图片,我是否设置的有问题

### ISSUE THREAD

**Issue by Creative6** [wangeditor-team/wangEditor#2873]
## 功能描述

*上传jfif格式的图片*

## 提炼几个功能点

- 上传jfif格式的图片

## 我的设置

![image](https://user-images.githubusercontent.com/20942162/106228507-779d2a00-6226-11eb-9675-6ab2fac6e3e4.png)

**Comment by hahaaha** [comment]
本地上传图片需要增加下对于ifif格式的适配。。。顺便看看要不要把这个配置项放开出去。。。内部不另作限制

**Comment by UltramanWeiLai** [comment]
该问题移步到 #2963 中跟进
