### ISSUE TITLE
建议字体颜色和字体背景色添加调色板

### ISSUE THREAD

**Issue by yclgkd** [wangeditor-team/wangEditor#2874]
## 功能描述

如题，配置里加颜色可供用户选择的毕竟有限，如果有调色板可能体验会好很多

## 提炼几个功能点

- 配置里的颜色显示在pannel上
- 在配置颜色的末尾加上自定义颜色的按钮，点击后弹出调色板。调色板上两个按钮保存和取消。

## 原型图

![chrome_41EbYzLNxf](https://user-images.githubusercontent.com/31514100/106239280-2f92ee80-61b7-11eb-92a1-ce7105a25c13.png)

![chrome_DZ21yxqO1i](https://user-images.githubusercontent.com/31514100/106239319-3f123780-61b7-11eb-9a68-b45f6544fa60.png)

## 可参考的案例

[tinyMCE](https://www.tiny.cloud/docs/demo/full-featured/)

**Comment by hahaaha** [comment]
https://github.com/wangeditor-team/wangEditor/issues/2529 这个已经在队列中了。。。具体进度可以关注前面那个issue
