### ISSUE TITLE
Chrome插入图片时会多一个<br>换行

### ISSUE THREAD

**Issue by MIPyao** [wangeditor-team/wangEditor#2875]
## bug 描述

Chrome浏览器插入图片后，会是这种格式`<p><img><br></p>`。不希望有一个额外的换行，这会导致下一行给图片添加标题的时候，间距过大
Firefox下是正常的`<p><img></p>`

## 浏览器及版本号

Chrome 88.0.4324.104
Firefox 84.0.2

## wangEditor 版本

以前的版本和官网首页上的都有这个问题

## 官网能否复现该 bug ？

能

**Comment by UltramanWeiLai** [comment]
我测试了一下，有没有这个 br 间距实际上都是一样的，或许你可以关注一下 p 标签的默认样式
这个行为是不同浏览器对 execCommand 的实现差异造成的。

**Comment by UltramanWeiLai** [comment]
该问题长期没有回复，暂且关闭
