### ISSUE TITLE
添加多段文字和图片，修改最后一张图片居中，下面的文字也会跟着居中

### ISSUE THREAD

**Issue by zzzli** [wangeditor-team/wangEditor#2876]
编辑器插入多段文字和图片。在修改最后一张图片居中的时候，下面的文字也会跟着居中。

**Comment by UltramanWeiLai** [comment]
请按照模板进行提交 issue 否则是不受理的，你 new issue 的时候会有一个选择模板的操作，另外这个我没有复现，你确定你拖拽选区的时候没有意外把文字的选区带入(段落头部空白处，是不会显示拖蓝的，但是该段落加入到了选区中)
![image](https://user-images.githubusercontent.com/23336585/106373331-74837480-63b3-11eb-8733-269557d1a5a9.png)
