### ISSUE TITLE
内容溢出

### ISSUE THREAD

**Issue by sulongjiu** [wangeditor-team/wangEditor#2877]
## 内容溢出

*内容溢出*

## wangEditor 版本

*修改的时候内容出现在富文本我们*

## 是 

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

**Comment by UltramanWeiLai** [comment]
？？？ 我完全不知道你想表达什么？？？
能否详细一点，最好能附上 demo 和详细的复现步骤

**Comment by UltramanWeiLai** [comment]
该问题长期无人回复，暂且关闭
