### ISSUE TITLE
代办事项checkbox未与文字对齐

### ISSUE THREAD

**Issue by hyfree** [wangeditor-team/wangEditor#2879]
## bug 描述

代办事项checkbox未与文字对齐

[![yktxv6.png](https://s3.ax1x.com/2021/01/30/yktxv6.png)](https://imgchr.com/i/yktxv6)

## 你预期的样子是？

checkbox与文字对齐

## wangEditor 版本

https://www.wangeditor.com/

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

编辑区域清空，输入文字，插入代办事项
checkbox未与文字对齐

**Comment by hahaaha** [comment]
https://github.com/wangeditor-team/wangEditor/issues/2818 这个问题已经在修复中了。。。进度请关注前面的issue
