### ISSUE TITLE
统一在表格里按上下键移动光标移动在不同浏览器的表现行为

### ISSUE THREAD

**Issue by echoLC** [wangeditor-team/wangEditor#2882]
## bug 描述

目前，在chrome中，在表格中按上下键移动光标的位置，发现也是按左右键的效果，但是在 firefox中是正常的。

## 你预期的样子是？

应该使得firefox和chrome中表现一致

## 浏览器及版本号

最新版本

## wangEditor 版本

v4.6.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 插入表格，将光标聚焦到表格内部
- 按上下键移动光标

**Comment by UltramanWeiLai** [comment]
这玩意我关了哈
