### ISSUE TITLE
【BUG】WPS 复制粘贴无论是否过滤样式都没有样式显示

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2885]
## bug 描述

WPS 复制粘贴无论是否过滤样式都没有样式显示

## 你预期的样子是？

当不过滤样式的时候正常显示样式

## 浏览器及版本号

全部

## wangEditor 版本

4.6.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：打开 wps 输入内容并且设置样式 例如 加粗斜体颜色等
- 步骤二：复制内容到编辑器中

**Comment by xiaokyo** [comment]
clipboardData.getData('text/html')
无法获取wps带样式的内容
