### ISSUE TITLE
当传入富文本的值不含任何标签时，对该字符进行任何操作(如点击)会报`undefined`错误

### ISSUE THREAD

**Issue by Exrick** [wangeditor-team/wangEditor#2886]
## bug 描述

当传入富文本的值不含任何标签时，对该字符进行任何操作(如点击)会报`undefined`错误，如`editor.txt.html('<p>前面有一个包含标签的字符</p>后面这个不含标签的值会报错')`

![QQ20210131-212727@2x.png](https://i.loli.net/2021/01/31/ejtpQMNLWzmsGbl.png)

## 你预期的样子是？

对变量进行判断处理，不提示错误

## 浏览器及版本号

Chrome最新

## wangEditor 版本

4.6.5

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 设置一个不含任何标签的字符 `editor.txt.html('<p>前面有一个包含标签的字符</p>test')`
- 点击刚设置的值test（将光标移至该处）即可在控制台看到错误

**Comment by UltramanWeiLai** [comment]
。。。老哥不要花里胡哨的弄呀！
编辑器内一个 p 标签即为一个段落
所相应的内容应该都存在于段落中，你在编辑区域内直接创建 文本 是不符合规则的，当然会报错。

**Comment by Exrick** [comment]
但是当扩展编辑html功能时，用户可能并不知道必须添加标签

**Comment by Exrick** [comment]
所以每次用户编辑后要为其在最外层包裹div处理...

![QQ20210201-105205@2x.png](https://i.loli.net/2021/02/01/nAYD2cvClFNEHkg.png)

建议文档中 设置内容 和 常见问题中 需提醒一下！

**Comment by UltramanWeiLai** [comment]
ok 我们会在文档中添加相关的提示内容，感谢你的意见。
至于在编辑后在最外层包裹 div 目前来说是行不通的。
编辑器目前依赖于 execCommand 命令，后续我们会考虑自研的 execCommand 命令该问题就能解决
那么这个 issue 我就关闭了
