### ISSUE TITLE
复制，然后全选粘贴后会有重复的文字出来

### ISSUE THREAD

**Issue by li741938507** [wangeditor-team/wangEditor#2888]
## bug 描述

复制，然后全选粘贴后会有重复的文字出来

## 你预期的样子是？

无重复文字

## 浏览器及版本号

chrome 83.0.4103.97

## wangEditor 版本

4.5.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
随便复制一段文字(ctr+c)
- 步骤二
鼠标全选编辑器中的内容，全选时鼠标点击后不松开，尽量移到编辑器外面后松开鼠标左键，然后粘贴(ctr+v)
- 步骤三
多尝试几次，会有重复内容的出现

**Comment by liuqh0609** [comment]
这个我操作了一下，觉得应该是因为你鼠标移出编辑区后再松开导致的选中区域没有完整被选中的缘故导致的

**Comment by liuqh0609** [comment]
你说的这个有重复的文字出来，是不是指在全选后粘贴导致的有一部分文字没有被删除掉，而是紧跟着这部分文字在后面粘贴上的现象？
如果是的话应该是你在鼠标移出编辑区域外后导致选中区域没有正确获取到的原因，这里还是建议全选时在编辑器内进行操作

**Comment by li741938507** [comment]
你们有复现出来吗，我觉得这个问题挺严重的

**Comment by wangfupeng1988** [comment]
@li741938507  这个 bug 我记得前几天解决了，你试试最新版 demo 的还能复现吗？http://106.55.153.217:8881/publish-npm-test/

**Comment by li741938507** [comment]
依然有

**Comment by krisQT** [comment]
4.6.6还是有此问题

**Comment by blackhu0804** [comment]
> 4.6.6还是有此问题

请提供一下复现路径吧。

**Comment by UltramanWeiLai** [comment]
该问题已经解决，暂且关闭，如更新后还有疑问可，重新提交 issue

**Comment by zxqAzxq-hash** [comment]
@blackhu0804 1.再列表页面点击编辑-粘贴了一段文本再editor中，点击提交/取消（无异常）
2.回到列表页面，再次点击编辑-粘贴在editor中-会出现**两边**粘贴的内容
重复上面步骤，每次都会 **+1 遍**
再第一次提交以后，先刷新再次编辑，就不会出现这个问题
