### ISSUE TITLE
初始化时div子元素不再编辑器里面

### ISSUE THREAD

**Issue by zhoutengjiao** [wangeditor-team/wangEditor#2889]
## 问题描述

首先，有些页面可以正常初始化，但是最近改其他也面时，发现直接将内容写到要创建编辑器的 <div> 标签中，内容不再编辑器里面，而在上边，一直找不到原因，只能修改为通过editor.txt.html()设置

## wangEditor 版本

4.6.4

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
按文档来
html 初始化内容

**Comment by zhoutengjiao** [comment]
补充一下，子元素是一段文本

**Comment by liuqh0609** [comment]
你是直接使用的文本吗？没有标签包裹？

**Comment by zhoutengjiao** [comment]
类似这种   <div id="div1">abc</div>

**Comment by zhoutengjiao** [comment]
`<div id="div1">abc</div>`

**Comment by liuqh0609** [comment]
你这样做是不符合规则的，在目前的编辑器中初始化需要p标签包裹的，可以参考这个[issue](https://github.com/wangeditor-team/wangEditor/issues/2886)

**Comment by zhoutengjiao** [comment]
好的

**Comment by liuqh0609** [comment]
如果没什么问题的话这个issue我们就先关闭了~

**Comment by beiifeng** [comment]
- 版本："^4.6.5"

在开发时，同样出现该问题
![image](https://user-images.githubusercontent.com/18087934/106585246-15c02580-6582-11eb-9b0f-de198c14c53e.png)
![image](https://user-images.githubusercontent.com/18087934/106585366-3be5c580-6582-11eb-96d7-01eff8bb374c.png)


但是在codesandbox 却无法复现，同样的代码却没出现。
![image](https://user-images.githubusercontent.com/18087934/106586487-7a2fb480-6583-11eb-9c7d-06dbf5469bc1.png)
https://codesandbox.io/s/jiben-antd4112-forked-3z5g0?file=/TechDisclosure.js

**Comment by beiifeng** [comment]
补充一下调试信息，
![image](https://user-images.githubusercontent.com/18087934/106588850-3e4a1e80-6586-11eb-9675-a422fc68a815.png)

但是在浏览器中全局搜索一下，没有直接的id，但是应该有别的东西
![image](https://user-images.githubusercontent.com/18087934/106589249-c8928280-6586-11eb-9639-aceffeeab8c7.png)

于是乎，把id改掉，然后就好了
![image](https://user-images.githubusercontent.com/18087934/106589486-098a9700-6587-11eb-8725-4efdcbdddf05.png)

**Comment by UltramanWeiLai** [comment]
那没问题我就关闭了
