### ISSUE TITLE
输入内容后,按住删除不放开会崩溃

### ISSUE THREAD

**Issue by lsai2270** [wangeditor-team/wangEditor#2890]
输入内容后,缓慢点击删除后,没问题,但是要是一直按住删除键,会出错

**Comment by liuqh0609** [comment]
能具体描述一下错误吗？或者贴一个截图，而且如果是提交bug的话，麻烦按照模板进行填写对应的描述哈

**Comment by wangfupeng1988** [comment]
chrome 浏览器访问 http://106.55.153.217:8881/master/examples/index.html
- 清空内容
- 输入 5 行文字
- 按住删除键不松手，连续删除

控制台报错如下：

![image](https://user-images.githubusercontent.com/9583120/106561275-56f50d00-6563-11eb-9edc-921b1ba5b2e8.png)

**Comment by liuqh0609** [comment]
该issue已经解决，周四发布新版之后更新一下版本就可以了。

**Comment by liuqh0609** [comment]
这个错误可以参考[issue#2820](https://github.com/wangeditor-team/wangEditor/issues/2820)

**Comment by lsai2270** [comment]
谢谢
