### ISSUE TITLE
选中富文本中的内容点击右键无法复制

### ISSUE THREAD

**Issue by jeenkzou** [wangeditor-team/wangEditor#2891]
## 问题描述

*选中富文本中的内容后，鼠标右键无法复制选中的内容，只能使用CTRL+C通过浏览器的复制*

## wangEditor 版本

*4.6.5*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 选中一段文本
- 鼠标右键
- 复制选项无法点击

**Comment by UltramanWeiLai** [comment]
可以移步到 #2903 中去跟进这个问题
