### ISSUE TITLE
字体展示问题

### ISSUE THREAD

**Issue by zhaoguangyue** [wangeditor-team/wangEditor#2892]
## 问题描述

*请输入遇到的问题...*
我们遇到了mac上字体不展示的问题
## wangEditor 版本

*请输入内容……*
我们遇到了mac上字体不展示的问题，其根本原因在于mac下字体英文名称不一致的问题，如
`<font face="宋体">helloworld<font>`
mac下不能识别，需要改为 
`<font face="STSongti-SC-Regular">helloworld<font>`
另外因我们需要在centos上使用puppeteer进行预览截图，中文的字体名称也不能识别

目前此处源码为
this.itemList.push({
    $elem: $(`<p style="font-family:'${fontValue}'">${fontValue}</p>`),
    value: fontValue,
})

目前官方的配置字体如下
editor.config.fontNames = [
    '黑体',
    '仿宋',
    ...
]
建议扩展，增加支持
editor.config.fontNames = [
{ key: '黑体',  value: "SimHei" },
{ key: '宋体',  value: 'SimSun STSongti-SC-Regular'},
...
]
`
list.forEach(font => {
    this.itemList.push({
        $elem: $(<p style="font-family:'${tpyeof font === 'string' ? font : font.value}'">${tpyeof font === 'string' ? font : font.key} </p>),
        value: tpyeof font === 'string' ? font : font.value,
    })
})
`
## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by zhaoguangyue** [comment]
或者简单些
editor.config.fontNames = [
{
key: '黑体',
value: "SimHei"
},
{
key: '宋体',
value: 'SimSun STSongti-SC-Regular'},
...
]


list.forEach(font => {
            this.itemList.push({
                $elem: $(`<p style="font-family:'${tpyeof font === 'string' ? font : font.value}'">${tpyeof font === 'string' ? font : font.key}</p>`),
                value: tpyeof font === 'string' ? font : font.value,
            })
        })

**Comment by UltramanWeiLai** [comment]
应该是不同操作系统和电脑内置的字体文件的区别吧？
可以自行配置 fontNames 即可解决呀！
editor.config.fontNames = [
'SimHei',
'SimSun STSongti-SC-Regular',
...
]

**Comment by zhaoguangyue** [comment]
但是我希望展示为中文，这个无法解决的

**Comment by zhaoguangyue** [comment]
> 应该是不同操作系统和电脑内置的字体文件的区别吧？
> 可以自行配置 fontNames 即可解决呀！
> editor.config.fontNames = [
> 'SimHei',
> 'SimSun STSongti-SC-Regular',
> ...
> ]

但是我希望展示为中文，这个无法解决的
