### ISSUE TITLE
输入框为空时，设置字号要点两下才生效，设置字体，设置文字颜色，设置背景色也有类似的问题

### ISSUE THREAD

**Issue by leirong** [wangeditor-team/wangEditor#2901]
## bug 描述

*以设置字号为例，输入框为空，依次从上而下把字号全部点一遍，再点击获取html，如图
![image](https://user-images.githubusercontent.com/32090489/106720797-d9063400-663e-11eb-8916-b04bac24c9be.png)
点击fontsize 1，3，5，7时没有生效
*

## 你预期的样子是？

*点击一下立即生效*

## 浏览器及版本号

*chrome 版本 88.0.4324.96（正式版本） (x86_64)*

## wangEditor 版本

*4.6.5*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一输入框为空，切换字号，要点击两下才生效
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
注：字体切换每间隔一次会插入一次空白字符但是并没有生成 font 标签
