### ISSUE TITLE
希望富文本支持 自动获取焦点失去焦点配置

### ISSUE THREAD

**Issue by chailiangyang** [wangeditor-team/wangEditor#2902]

**Comment by UltramanWeiLai** [comment]
请按照模板进行提交问题，否则是不受理的
编辑器默认是自动获取焦点的，可以通过 editor.config.focus 去设置是否自动获取焦点
如果你说的是使用中手动去获取焦点 https://developer.mozilla.org/zh-cn/docs/Web/API/HTMLElement/focus 可以看一下这个
