### ISSUE TITLE
【BUG】右键会取消选区

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2903]
## bug 描述

在编辑区域内拖蓝一段文字后右键，拖蓝状态会被取消掉

## 你预期的样子是？

正常的不会取消

## 浏览器及版本号

所有

## wangEditor 版本

4.6.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 输入文字
- 步骤二 拖蓝文字
- 步骤三 鼠标右键

**Comment by chuifengji** [comment]
https://github.com/wangeditor-team/wangEditor/pull/2908#issue-567519428

**Comment by wangfupeng1988** [comment]
我用 mac OS chrome 浏览器，没有复现你的问题
![image](https://user-images.githubusercontent.com/9583120/107212289-b068aa80-6a41-11eb-95ce-444c0d04904a.png)

**Comment by wangfupeng1988** [comment]
哦，我在 firefox 下复现了。
