### ISSUE TITLE
希望可以选中图片文本江选中内容增加链接跳转

### ISSUE THREAD

**Issue by xjy2016** [wangeditor-team/wangEditor#2911]
## 功能描述

*希望可以选中图片文本江选中内容增加链接跳转*

- 原有的添加链接只能针对文本进行添加，无法针对图片进行链接的添加。
- 默认图片控件只有插入网络图片，改为禁用网络图片后本地图片通过点击菜单栏图标进行上传，没看见两种图片默认均存在的情况。

**Comment by UltramanWeiLai** [comment]
图片配置转跳链接的功能应该是已经存在了具体可以查看该 PR [PR](https://github.com/wangeditor-team/wangEditor/pull/2659)
当只有上传图片选项的时候直接唤起面板也已经存在了，具体可以查看该 PR [PR](https://github.com/wangeditor-team/wangEditor/issues/2585)
