### ISSUE TITLE
粘帖相关问题

### ISSUE THREAD

**Issue by skl-hyf** [wangeditor-team/wangEditor#2914]
## bug 描述

纯文本内容粘帖到编辑器中时，会跑到最下方，而不是光标位置，此时控制台有报错。但有些内容就正常，比如完整网址，或者有格式的文本。

![image](https://user-images.githubusercontent.com/76997845/106986724-e9392300-67a6-11eb-8c58-096f66b31a86.png)
4.6.2版本实测正常

## 你预期的样子是？
正常粘帖文字

## 浏览器及版本号

Chromium 86.0.4240.198

## wangEditor 版本

4.6.6

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 打开官网，光标定位在“初见”后面，从txt复制一段纯文本，如  “备注1：产品类型=产品，样品，其他” ，ctrl+v粘帖
- 步骤二 控制台就能看到报错了，文字被粘帖到了最后面
- 步骤三

**Comment by UltramanWeiLai** [comment]
该问题已经收录，可以移步到 #2852 中跟进该问题
