### ISSUE TITLE
编辑器的全局配置

### ISSUE THREAD

**Issue by clinfc** [wangeditor-team/wangEditor#2915]
## 功能描述

*在创建实例前，可以对编辑器进行公共配置*

## 提炼几个功能点

- 官方配置项的全局配置
- 用户扩展菜单注册自定义配置

## 原型图

*无*

## 可参考的案例

*[axios.defaults](http://www.axios-js.com/zh-cn/docs/#%E5%85%A8%E5%B1%80%E7%9A%84-axios-%E9%BB%98%E8%AE%A4%E5%80%BC)*

**Comment by wangfupeng1988** [comment]
我感觉，目前我们还不需要这种功能，就不要过早设计了。
