### ISSUE TITLE
在输入东西后，一直按删除键会报错

### ISSUE THREAD

**Issue by 18853823692** [wangeditor-team/wangEditor#2916]
## bug 描述

我任意输入文字后，一直按着删除键不动，控制台会不断报错：Uncaught TypeError: Cannot read property 'nodeName' of undefined

## 你预期的样子是？

不想报错

## 浏览器及版本号

Chrome 版本 88.0.4324.96（正式版本） （64 位）

## wangEditor 版本

4.6.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一随意输入文字
- 步骤二打开console控制台
- 步骤三一直按着删除键不放

**Comment by liuqh0609** [comment]
该问题已经修复，请将版本升级至4.6.6版本，[版本公告](https://github.com/wangeditor-team/wangEditor/blob/master/CHANGELOG.md)
