### ISSUE TITLE
【功能优化】添加菜单提示开关

### ISSUE THREAD

**Issue by fuermojie** [wangeditor-team/wangEditor#2917]
## 问题描述

*打开富文本编辑器后, 鼠标悬浮到全屏按钮, 显示全屏, 点击全屏后, 鼠标悬浮全屏按钮, 希望显示成 '取消全屏' 类似的文字。*

## wangEditor 版本

*vue中安装  4.6.4*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一:  点击全屏
- 步骤二:  鼠标悬浮全屏按钮
- 步骤三:  目前显示全屏 ( 希望显示取消全屏之类的内容 )

**Comment by UltramanWeiLai** [comment]
@rsl140 添加是否展示提示的开关配置 and 全屏后全屏按钮的提示信息应该为取消全屏或者关闭全屏等
