### ISSUE TITLE
请问有序列表带无序列表的多级列表功能实现了吗？

### ISSUE THREAD

**Issue by charidad** [wangeditor-team/wangEditor#2921]
## 功能描述

有序列表带无序列表的多级列表，在20年12月份在群里提及过

## 提炼几个功能点
1. 3333
2. 213123
    · 123123213
    · 123123213
3. 123213

类似这种效果

## 原型图

无

## 可参考的案例

word ueditor都有此类功能

**Comment by wangfupeng1988** [comment]
这个功能尚未支持，但是会继续做的。
其实就是“多级列表”。
