### ISSUE TITLE
点击编辑框弹出ckeditor 悬浮toolbar,还有红色的插入段落

### ISSUE THREAD

**Issue by Wydumn** [wangeditor-team/wangEditor#2922]
## 问题描述
点击编辑框弹出ckeditor 悬浮toolbar,还有红色的插入段落

自己在本地试没有问题，在测试环境碰到的
## wangEditor 版本
version 3.1.1
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

本地无法复现
![image](https://user-images.githubusercontent.com/29623732/107469328-84b20580-6ba4-11eb-9b1c-1e4f0c71fe70.png)

**Comment by wangfupeng1988** [comment]
1. 请升级版本到 v4 最新版本，v3 不再支持
2. 没搞懂你的问题是啥，为啥会有 ckeditor ? 请再详细问题、以及复现问题的详细步骤，否则我们复现不了也没法解决。
