### ISSUE TITLE
快速展开功能

### ISSUE THREAD

**Issue by ChaoLei-Ling** [wangeditor-team/wangEditor#2923]
## 功能描述

当富文本过多时，除了当前的全屏功能，有时我们也需要在不全屏的基础上（需要同时参考页面上的其他信息），查看更多的信息，希望在右下角提供一个展开的功能，自动将当前富文本的高度设置到文本实际内容的最大高度

## 提炼几个功能点

- 展开，自动将当前富文本的高度设置到文本实际内容的最大高度
- 收缩，自动将当前富文本的高度设置到初始值

## 原型图

![image](https://user-images.githubusercontent.com/18180687/107478694-debac700-6bb4-11eb-8b56-dc8d6cce38fb.png)

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
这个可以自己实现。通过[设置高度](https://doc.wangeditor.com/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/02-%E8%AE%BE%E7%BD%AE%E9%AB%98%E5%BA%A6.html)或者[菜单和编辑区域分离](https://doc.wangeditor.com/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/03-%E8%8F%9C%E5%8D%95%E5%92%8C%E7%BC%96%E8%BE%91%E5%8C%BA%E5%9F%9F%E5%88%86%E7%A6%BB.html)，都可以自定义编辑区域的尺寸。
