### ISSUE TITLE
【优化 & 重构】图片添加超链接和 alt

### ISSUE THREAD

**Issue by aloehh** [wangeditor-team/wangEditor#2929]
## 问题描述
1.  网络图片添加超链接后， 回显时点击无效
2. 上传的图片不支持超链接

## wangEditor 版本

latest

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 编辑器中添加网络图片并设置超链接
- 步骤二 回显时， 链接并未添加成功， 因此点击无效
- 步骤三

**Comment by UltramanWeiLai** [comment]
## 问题描述
1、图片超链接如何设置，如何回显，如何查看
2、图片如何设置 alt
网络图片 和 上传图片都需要该功能

## wangEditor 版本

latest

## 是否查阅了文档 ？

*是*

**Comment by terry-ly** [comment]
有考虑给上传的图片设置超链接吗？目前只支持给网络图片设置超链接

**Comment by UltramanWeiLai** [comment]
> 有考虑给上传的图片设置超链接吗？目前只支持给网络图片设置超链接

上传图片有，但是只能通过后端去处理

**Comment by terry-ly** [comment]
> > 有考虑给上传的图片设置超链接吗？目前只支持给网络图片设置超链接
> 
> 上传图片有，但是只能通过后端去处理

你好，我是做后端的，后端处理的思路是怎样的？现在能想到的就是编辑源码，这对于不懂代码的使用者来说有点困难。

**Comment by UltramanWeiLai** [comment]
![Uploading image.png…]()

**Comment by terry-ly** [comment]
> ![image](https://user-images.githubusercontent.com/23336585/111601067-f9fca000-880c-11eb-9dfa-b146ab267803.png)
> 
> https://doc.wangeditor.com/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/01-%E9%85%8D%E7%BD%AE%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8E%A5%E5%8F%A3.html

这也正是我想说的一个问题，我一开始有尝试返回如图格式的json数据，但是editor好像并不能识别image object，显示插入节点错误，最后我在data中直接输出图片地址，可以正常显示，请问是否需要额外的配置项？或是bug引起
`{"errno":0,"data":["https://example.com/xZx444E4CwrrUVobGZ90tpk1UWFxoWeSuQR42mdu.jpeg"]}`

**Comment by tonysong77** [comment]
> 有考虑给上传的图片设置超链接吗？目前只支持给网络图片设置超链接

网络图片设置超链接，前端点击无效，这个问题有修复吗？

**Comment by z1948296027** [comment]
> > 有考虑给上传的图片设置超链接吗？目前只支持给网络图片设置超链接
> 
> 网络图片设置超链接，前端点击无效，这个问题有修复吗？

可以在配置了超链接的情况下在图片外层包装一个a标签吧

**Comment by z1948296027** [comment]
咱这个功能能支持下吗，急用

**Comment by wangfupeng1988** [comment]
@z1948296027  v4不再升级功能，v5 支持这个功能。
https://www.wangeditor.com/v5/

**Comment by guo273559624** [comment]
v5版本图片设置超链接之后，也是不能点击跳转的，实现方式跟实际场景还是有差别的，目前wangEditor是给img标签增加的data-href属性，并不是在外面包一层a标签。
<a href=""> <img src=""></a>

**Comment by wangfupeng1988** [comment]
> v5版本图片设置超链接之后，也是不能点击跳转的，实现方式跟实际场景还是有差别的，目前wangEditor是给img标签增加的data-href属性，并不是在外面包一层a标签。

加一个 click 事件即可搞定。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
