### ISSUE TITLE
本地图片上传，对图片的后缀进行过滤，不生效

### ISSUE THREAD

**Issue by zxqAzxq-hash** [wangeditor-team/wangEditor#2930]
## 问题描述

*图片上传后缀验证editor.config.uploadImgAccept = ['jpg', 'png']不生效 *

## wangEditor 版本

*^4.6.4*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- editor.config.uploadImgAccept = ['jpg', 'png']
- 再源码上发现
- 
            if (/\.(jpg|jpeg|png|bmp|gif|webp)$/i.test(name) === false) {
                // 后缀名不合法，不是图片
                errInfos.push(`【${name}】${t('不是图片')}`)
                return
            }

- 这段话，他这里直接手写使用了这几个后缀的验证，我editor.config.uploadImgAccept = ['jpg', 'png'] 对上传gif依然不过滤

**Comment by UltramanWeiLai** [comment]
目前已经关闭了该设置，图片验证可以自行进行设置

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复，暂且关闭
