### ISSUE TITLE
全选粘贴会追加内容而不是覆盖

### ISSUE THREAD

**Issue by DLCnow** [wangeditor-team/wangEditor#2932]
## bug 描述

全选粘贴会追加内容而不是覆盖

## 你预期的样子是？

全选粘贴会覆盖内容而不是追加

## 浏览器及版本号

Microsoft Edge 87.0.664.55
Google Chrome 88.0.4324.96

## wangEditor 版本

4.6.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 保证输入框干净，随便输入点什么
- 步骤二 command + a 全选
- 步骤三 从vscode 或者 word 里面随便复制回到编辑器 粘贴

**Comment by wangfupeng1988** [comment]
这个问题之前存在过，已经解决了。你可以再试试 http://106.55.153.217:8881/master/examples/index.html

**Comment by UltramanWeiLai** [comment]
该问题已收录，可以在 #2888 中跟进
