### ISSUE TITLE
【BUG】XSS

### ISSUE THREAD

**Issue by imust6226** [wangeditor-team/wangEditor#2933]
## bug 描述
*插入网络图片，引入恶意代码片段，导致xss*

## 你预期的样子是？

*优化插入网络图片，不合法的图片插入失败*

## 浏览器及版本号

*搜狗浏览器 11.0.1*

## wangEditor 版本

*ALL*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 选择插入图片->网络图片
- 步骤二 图片地址插入img标签，并时候图片后缀结束，如`http://xsstest/<img src="1" onmouseover="alert("xss")>.jpg`
- 步骤三 鼠标滑过图片，触发xss，如下图

![image](https://user-images.githubusercontent.com/42436911/108480790-4b0d8880-728f-11eb-9b1d-71ca1130a44a.png)

**Comment by imust6226** [comment]
[](url)

**Comment by ivybao0628** [comment]
这个富文本是有很多xss的，你要申请cve吗？不过之前作者文档里建议自己处理xss问题。

**Comment by imust6226** [comment]
这样子嗦...不好意思，没有看到之前作者的文档。

**Comment by wangfupeng1988** [comment]
xss 攻击自己处理啊吧，参考[文档](https://doc.wangeditor.com/pages/13-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/02-xss%E6%94%BB%E5%87%BB.html) 。
