### ISSUE TITLE
使用v-if判断展示时设置初始内容失效

### ISSUE THREAD

**Issue by HBreaker** [wangeditor-team/wangEditor#2940]
## 问题描述

使用v-if判断展示时设置初始内容失效

## wangEditor 版本

4.6.6

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
？？？
如何复现？
具体是啥？
你就一句话，很难让我知道你到底想表达啥出来。

**Comment by HBreaker** [comment]
![image](https://user-images.githubusercontent.com/59952212/108931187-2f84f200-7682-11eb-9188-208e80cc9c13.png)
这里有多个v-if判断页面初始的时候展示哪个区域，initData是初始化传入的内容，此时editor的初始化内容是失败
![image](https://user-images.githubusercontent.com/59952212/108931695-04e76900-7683-11eb-99f2-cd165844275e.png)
![image](https://user-images.githubusercontent.com/59952212/108931736-1fb9dd80-7683-11eb-865f-de67ee8fe6dd.png)
![image](https://user-images.githubusercontent.com/59952212/108931756-29434580-7683-11eb-94d5-609c27d3f1c2.png)

**Comment by UltramanWeiLai** [comment]
... 试着用一下 vue 的高阶组件吧
你这个 if show 是真的多
是否使用 if 和编辑器设置初始化内容无关。
你 intro 是如何操作的？
建议使用 api 去初始化内容。

**Comment by wangfupeng1988** [comment]
5 天未回复，暂时关闭。有问题可以新提交一个 issue 。
