### ISSUE TITLE
在vue2中使用wangedit出现以下问题

### ISSUE THREAD

**Issue by comxza** [wangeditor-team/wangEditor#2942]
## 问题描述
在vue2中使用wangedit出现以下问题

*请输入遇到的问题...*
我使用的是element UI的框架，在使用他们的https://element.eleme.cn/#/zh-CN/component/dialog这个组件的时候，我在这个里面里面引入编辑器并且初始化了，如下图
![image](https://user-images.githubusercontent.com/21981010/108811749-c8ffc580-75e8-11eb-8b95-8f96b68e7330.png)
![image](https://user-images.githubusercontent.com/21981010/108811759-d026d380-75e8-11eb-8c4f-caaec6ccff2e.png)
![image](https://user-images.githubusercontent.com/21981010/108811774-d87f0e80-75e8-11eb-8bc3-16397f0e2654.png)
，通过以上步骤的设置
![image](https://user-images.githubusercontent.com/21981010/108811810-e765c100-75e8-11eb-85d4-aa4ffd6421a4.png)
编辑器并没有渲染出来，并且有如下图这两个警告，
![image](https://user-images.githubusercontent.com/21981010/108811847-fb112780-75e8-11eb-86a0-48b4ed33644c.png)

## wangEditor 版本
4.6.6
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*
已经看了，但是如果我不在这个dialog里面正常渲染
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 下载vue-element-admin框架，安装编辑器
- 步骤二
- 随便一个页面，创建一个dialog的弹出框
- 步骤三
- 错误可以复现

**Comment by UltramanWeiLai** [comment]
element ui 中的 dialog 组件中是可以使用 wangEditor 的
个人感觉编辑没有创建成功是因为 dialog 还有没创建节点出来
可以在 mounted 中打个断点然后使用 document.getElementById('demo1') 查看节点是否存在

**Comment by lbszz** [comment]
我也遇到了 同样的问题

**Comment by comxza** [comment]
> 我也遇到了同样的问题

其实这个有个解决办法，就是在弹出dialog的时候顺便初始化编辑器，既可以解决这个问题
![image](https://user-images.githubusercontent.com/21981010/109266909-aae1d180-7843-11eb-8ac5-20da8496c67c.png)
就是在nextTick里面执行一遍

**Comment by lbszz** [comment]
> > 我也遇到了同样的问题
> 
> 其实这个有个解决办法，就是在弹出dialog的时候顺便初始化编辑器，既可以解决这个问题
> ![image](https://user-images.githubusercontent.com/21981010/109266909-aae1d180-7843-11eb-8ac5-20da8496c67c.png)
> 就是在nextTick里面执行一遍

确实可以 解决问题！
