### ISSUE TITLE
黏贴会将内容黏贴到编辑器底部

### ISSUE THREAD

**Issue by zijjj** [wangeditor-team/wangEditor#2943]
## bug 描述
黏贴会将内容黏贴到编辑器底部

## 你预期的样子是？
黏贴到正确的位置

## 浏览器及版本号
谷歌 v88

## wangEditor 版本
4.6.4及以上版本
4.6.3及以下没问题

## 官网能否复现该 bug ？
能

## 最小成本的复现步骤
 直接在官网首页的编辑器里黏贴一段文章内容就可以复现

**Comment by UltramanWeiLai** [comment]
该问题已经在处理中，可以到 #2888 中去跟进

**Comment by UltramanWeiLai** [comment]
该问题已经在处理中，可以到 #2888 中去跟进
