### ISSUE TITLE
复制黏贴文字到全选内容的富文本，文字追加在已有内容后面，而不是覆盖

### ISSUE THREAD

**Issue by krisQT** [wangeditor-team/wangEditor#2944]
## bug 描述

从input（element-ui）上复制文字， 全选已经存在内容的富文本输入框，黏贴文字，文字是追加在后面，而不是覆盖

## 你预期的样子是？

全选已有内容，再黏贴一段文字，会覆盖已有内容，而不是追加到已有内容的后面

## 浏览器及版本号

google浏览器 版本 65.0.3325.181（正式版本） （32 位）

## wangEditor 版本

4.6.6

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一： 在element-ui的input组件上输入一段文字，并 ctrl + c 复制该文字（ https://element.eleme.cn/#/zh-CN/component/input ）
- 步骤二：在 wangEditor 中输入一段文字，并 ctrl + a 全选
- 步骤三：ctrl + v 黏贴

**Comment by UltramanWeiLai** [comment]
该问题已经在处理中，可以到 #2888 中去跟进

**Comment by UltramanWeiLai** [comment]
该问题已经在处理中，可以到 #2888 中去跟进

**Comment by UltramanWeiLai** [comment]
该问题已经在处理中，可以到 #2888 中去跟进
