### ISSUE TITLE
希望editor.txt.html获取的内容保留样式，应该怎么做？

### ISSUE THREAD

**Issue by mutouzdl** [wangeditor-team/wangEditor#2947]
## 问题描述
我看了这个文档：[https://doc.wangeditor.com/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/03-%E8%8E%B7%E5%8F%96html.html](https://doc.wangeditor.com/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/03-%E8%8E%B7%E5%8F%96html.html)
已经知道了，editor.txt.html获取的是纯html，不含样式。

我的疑问是，有没有办法获取到包含样式的html。
我们希望把html内容作为邮件发送出去，如果不含样式的话，表格之类的内容就无法正常展示了。

## wangEditor 版本
4.6.6

## 是否查阅了文档 ？

（文档链接 [https://doc.wangeditor.com/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/03-%E8%8E%B7%E5%8F%96html.html](https://doc.wangeditor.com/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/03-%E8%8E%B7%E5%8F%96html.html)）

*是*

## 最小成本的复现步骤

- 步骤一 从word复制带表格的内容
- 步骤二 粘贴到编辑器
- 步骤三 使用editor.txt.html获取html内容

**Comment by UltramanWeiLai** [comment]
文档看全一点：https://doc.wangeditor.com/pages/06-%E7%B2%98%E8%B4%B4%E8%BF%87%E6%BB%A4/01-%E5%85%B3%E9%97%AD%E5%AF%B9%E7%B2%98%E8%B4%B4%E5%86%85%E5%AE%B9%E6%A0%B7%E5%BC%8F%E7%9A%84%E8%BF%87%E6%BB%A4.html?h=pasteFilterStyle
