### ISSUE TITLE
字体大小设置

### ISSUE THREAD

**Issue by lihaixing** [wangeditor-team/wangEditor#2949]
## bug 描述

*首次输入字体，从右往左选择整行文字，设置字体大小，不生效*
但是双击选择整行字体，却能够生效

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

IE 11

## wangEditor 版本

4.6.6

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
- 将编辑器内容清空，输入一行文字
- 从右往左选择整行文字，设置字体大小
- 字体大小没生效

**Comment by wangfupeng1988** [comment]
@YmCoke 帮忙看下，这个问题能否复现？

**Comment by YmCoke** [comment]
首次输入字体，从右往左选择整行文字，如果超出editor区域抬起鼠标，点击功能区域无法为选中文字设置样式；反之如果在editor区域内抬起鼠标，则可以通过菜单为选区设置样式。
由于ie11默认左侧有一列菜单栏，因此很容易出现从右往左选中整行字体时鼠标划出editor区域。
