### ISSUE TITLE
切换国际化语言创建编辑器，国际化显示有问题

### ISSUE THREAD

**Issue by gyn10590** [wangeditor-team/wangEditor#2950]
## bug 描述

*创建一个中文显示的编辑器，此时我想切换为英文显示，单独设置lang为en无效，此时我将创建的编辑器销毁，创建配置lang为en的编辑器，此时显示异常，中文+英文一起显示。只有刷新页面后，第一次创建的中文或者英文配置的编辑器才显示正常。*

## 你预期的样子是？

*创建完lang为中文的编辑器，如果能修改lang的配置为英文那么就能切换是为最好
如果不行，此时销毁编辑器，创建lang为英文能显示正常也行。
*

## 浏览器及版本号

*
浏览器：Google Chrome
版本 88.0.4324.182（正式版本） （64 位）
*

## wangEditor 版本

*4.6.6   vue2 vue3都有此情况*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
-  mounted() {
    this.editor = new E(this.$refs.wang);
    this.editor.config.lang = "zh-CN";
    this.editor.i18next = i18n;
    this.editor.create();
    console.log("第一次创建中文editor", this.editor);
  },
- 步骤二
- clickNo() {
      this.editor.destroy();
      this.editor = null;
      this.$nextTick(() => {
        this.editor = new E(this.$refs.wang);
        this.editor.config.lang = "en";
        this.editor.i18next = i18n;
        this.editor.create();
        console.log("销毁中文editor，创建英文editor", this.editor);
      });
    },
- 步骤三
![截图](https://user-images.githubusercontent.com/35243438/108980044-3c2b3980-76c6-11eb-817a-692c76085ee4.PNG)

**Comment by sunliyun** [comment]
遇到相同问题了，盼官方回复

**Comment by wangfupeng1988** [comment]
@UltramanWeiLai 你来看下吧。

**Comment by clinfc** [comment]
当前编辑器并不是像 vue 一样的双向绑定机制，无法通过数据刷新视图，只能在创建时通过数据定制视图

**Comment by UltramanWeiLai** [comment]
国际化插件使用不当导致的。
i18next 使用的时候 是直接 init 的，重复 init 会出现问题。
所以在设置 i18next 的时候 要使用创建一个新实例的方法 i18next.createInstance()
![image](https://user-images.githubusercontent.com/23336585/109423354-0796e500-7a1a-11eb-99be-32f7491ab0fa.png)

**Comment by UltramanWeiLai** [comment]
> 遇到相同问题了，盼官方回复

已回复

**Comment by gyn10590** [comment]
good good
