### ISSUE TITLE
建议新增清除内容格式功能

### ISSUE THREAD

**Issue by fengcms** [wangeditor-team/wangEditor#2953]
## 功能描述

在用户使用编辑器时，如果过多的操作各种控制按钮，很容易产生大量的 style 之类的东西。而编辑在审核这些内容的时候，希望一键清除掉，只使用基本的 html 标签即可。因为在渲染时，会使用配套的 CSS 来进行内容的展示，而不过于依赖富文本编辑器生成的样式。
当然，某些时候又是需要这些内容的，因此不能在后端统一处理。因此希望能有这个功能。

## 提炼几个功能点

- 一键清除 style
- 一键清除 font
- 一键清除 color

**Comment by wangfupeng1988** [comment]
我们有考虑增加一个“清楚格式”的按钮，但我觉得这不是你想要的功能。

我理解，你是想要编辑器定义几个 API ，供使用者执行，可以：
- 清除 style
- 清除 font
- 清除 color

对吧？

如果是这样的话，我们暂时没有打算支持。因为我觉得，获取内容 html ，然后通过正则表达式过滤，即可得到你想要的结果。

**Comment by fengcms** [comment]
应该是我描述得有问题，我想要的，和你们想做的是一个东西，只是我描述了三个清除场景。实际上，都应该是直接清除掉，不需要分别执行的。

----

就是说，我希望新增一个“清除格式”按钮，点击一下，就把 style\font\color 等内容，全部清除掉。😄

**Comment by wangfupeng1988** [comment]
那我们暂时没法支持，这个可以先自己用正则表达式过滤。
