### ISSUE TITLE
tooltip覆盖

### ISSUE THREAD

**Issue by mobei95** [wangeditor-team/wangEditor#2956]
## 功能描述

现有的tooltip为编辑器原有的tooltip，开发人员还可以配置自己的tooltip，但是自定义的tooltip和原有的tooltip会重叠，所以，可不可以增加一个配置，隐藏原有的tooltip，或者直接对原有的tooltip进行自定义配置

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
你没有说明具体的使用场景。我猜测，例如不想要默认的链接的 tooltip ，想要自己定义一个，是吗？
![image](https://user-images.githubusercontent.com/9583120/109416392-ea055380-79f8-11eb-86d6-0c9dbf73c82d.png)

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
