### ISSUE TITLE
4.6.7版本遇到了自定义问题

### ISSUE THREAD

**Issue by liu-sir666** [wangeditor-team/wangEditor#2958]
## 问题描述

config不能使用，只能用customConfig

## wangEditor 版本

4.6.7

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

我是vue 2.x里用的

**Comment by wangfupeng1988** [comment]
v4 开始就将 customConfig 切换到 config 了，我猜测你是搞错版本了。

**Comment by liu-sir666** [comment]
我的vue项目，package.json里确实是4.6.7版本，而且我之前是3.xx版本我把它卸载了然后又按照v4文档的npm那个下载的，但是就是报config&nbsp; undefined




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月28日(星期天) 晚上7:11
收件人:&nbsp;"wangeditor-team/wangEditor"<wangEditor@noreply.github.com&gt;;
抄送:&nbsp;"@@@"<914294067@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 4.6.7版本遇到了自定义问题 (#2958)





 
v4 开始就将 customConfig 切换到 config 了，我猜测你是搞错版本了。

**Comment by UltramanWeiLai** [comment]
建议检查 package.json 然后删除 node_models 重新 npm install

**Comment by liu-sir666** [comment]
大佬，现在已经好，用其他人电脑删除之后又下载的，然后我又重新拉取的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;UltramanWeiLai&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月4日(星期四) 晚上10:00
收件人:&nbsp;&quot;wangeditor-team/wangEditor&quot;<wangEditor@noreply.github.com&gt;;
抄送:&nbsp;&quot;Smile&quot;<914294067@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 4.6.7版本遇到了自定义问题 (#2958)
