### ISSUE TITLE
撤回的时候，当数据为空报错

### ISSUE THREAD

**Issue by manChenyufan** [wangeditor-team/wangEditor#2962]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本
4.6.6

*请输入内容……*

## 是否查阅了文档 ？

是

*是/否*

## 最小成本的复现步骤

撤回的时候，当数据为空的时候，提示错误，错误如下
Uncaught TypeError: Cannot read property 'parentNode' of undefined
Uncaught TypeError: Cannot read property 'nodeName' of undefined
如果本身有数据的情况下（编辑模式下）通过给编辑器传递数据，这样的数据应该是撤回不了的，还是可以撤回，

**Comment by manChenyufan** [comment]
![微信图片_20210301093631](https://user-images.githubusercontent.com/51591329/109441919-ab5faf80-7a71-11eb-9996-04219bbe5fca.png)

**Comment by UltramanWeiLai** [comment]
如果本身有数据的情况下（编辑模式下）通过给编辑器传递数据是指？
你试着更新一下 wangEditor 后再试一下？
或者先试一下官网是否能复现这个问题？

**Comment by manChenyufan** [comment]
默认的情况下是有数据的，就好比如添加产品和编辑产品，编辑器里会有传递过来数据，通过props

**Comment by manChenyufan** [comment]
问题找到了，this.editor.txt.html（）这个模块，如果把数据清空它就报错

**Comment by manChenyufan** [comment]
如果取消这个就不会报错

**Comment by UltramanWeiLai** [comment]
虽然不是很明白，但是问题解决就好
