### ISSUE TITLE
【功能优化】上传图片的格式验证配置

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#2963]
## 功能优化描述
上传图片的格式验证配置，当配置设置为空数组，则不去对图片后缀进行验证

## 你预期的样子是？

可以设置上传图片不进行验证配置

## 浏览器及版本号

所有

## wangEditor 版本

lastest

**Comment by YmCoke** [comment]
交叉测试： @liuqh0609
