### ISSUE TITLE
vue3中使用editor.disable()没有作用

### ISSUE THREAD

**Issue by xiaowcji55** [wangeditor-team/wangEditor#2965]
## 问题描述

vue3中使用editor.disable()没有作用

## wangEditor 版本

V4.6.6

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 创建editor实例
- 步骤二 禁用editor
- 步骤三

**Comment by wangfupeng1988** [comment]
我们不知道你的 vue3 是什么环境，所以也复现不了你的问题。

你可以下载编辑器的 vue3 demo https://github.com/wangeditor-team/wangEditor-with-vue3 ，然后修改一下，复现这个问题。
告诉我们怎么在这个 vue3 demo 中复现问题，这样我们就可以复现并修改。

**Comment by xiaowcji55** [comment]
好的，谢谢，我在demo上试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 王福朋 <notifications@github.com&gt;
发送时间: 2021年3月2日 09:22
收件人: wangeditor-team/wangEditor <wangEditor@noreply.github.com&gt;
抄送: xiaowcji55 <202939546@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[wangeditor-team/wangEditor] vue3中使用editor.disable()没有作用 (#2965)





 
我们不知道你的 vue3 是什么环境，所以也复现不了你的问题。
 
你可以下载编辑器的 vue3 demo https://github.com/wangeditor-team/wangEditor-with-vue3 ，然后修改一下，复现这个问题。
 告诉我们怎么在这个 vue3 demo 中复现问题，这样我们就可以复现并修改。

**Comment by xiaowcji55** [comment]
> 我们不知道你的vue3是什么环境，所以也复现不了你的问题。
> 
> 你可以下载编辑器的vue3演示https://github.com/wangeditor-team/wangEditor-with-vue3，然后修改一下，复现这个问题。
> 告诉我们怎么在这个vue3演示中复现问题，这样我们就可以复现并修改。``const enable = () => {
           instance.enable();
        };

        const disable = () => {
            instance.disable();
        };

我在你提供的官方vue3 demo中使用disable() 前端直接报runtime-core.esm-bundler.js?5c40:217 Uncaught TypeError: instance.disable is not a function 错误

**Comment by rsl140** [comment]
> > 我们不知道你的vue3是什么环境，所以也复现不了你的问题。
> > 你可以下载编辑器的vue3演示[https://github.com/wangeditor-team/wangEditor-with-vue3，然后修改一下，复现这个问题。](https://github.com/wangeditor-team/wangEditor-with-vue3%EF%BC%8C%E7%84%B6%E5%90%8E%E4%BF%AE%E6%94%B9%E4%B8%80%E4%B8%8B%EF%BC%8C%E5%A4%8D%E7%8E%B0%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%E3%80%82)
> > 告诉我们怎么在这个vue3演示中复现问题，这样我们就可以复现并修改。``const enable = () => {
> > instance.enable();
> > };
> 
> ```
>     const disable = () => {
>         instance.disable();
>     };
> ```
> 
> 我在你提供的官方vue3 demo中使用disable() 前端直接报runtime-core.esm-bundler.js?5c40:217 Uncaught TypeError: instance.disable is not a function 错误

你好，根据你的描述我在wangEditor-with-vue3项目中测试，并未复现该问题。

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
