### ISSUE TITLE
粘贴文本会重复

### ISSUE THREAD

**Issue by zxqAzxq-hash** [wangeditor-team/wangEditor#2966]
## bug 描述

*粘贴文本会重复，比如粘贴“你好”，第一次没事，提交了再进行修改第二次就成了“你好你好”，以此类推，第四次会重复四边，但是如果再主页面刷新一遍再点进去修改文本就没问题*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*谷歌 89.0.4385.0（正式版本） （32 位）*

## wangEditor 版本

*4.6.7*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 粘贴了一段文本再editor中，点击提交/取消
- 回到列表页面，再次点击编辑-粘贴在editor中-会出现两边粘贴的内容
- 重复上面步骤，每次都会+1便
- 提交以后先刷新再次编辑，就不会出现这个问题

**Comment by zxqAzxq-hash** [comment]
@wangfupeng1988 你好，我可以先给您截个图说明一下莫？

**Comment by zxqAzxq-hash** [comment]
@wangfupeng1988 #踏着富文本不能贴截图。，，，，我在描述一下：
首先这是一个vue写的，一个类似淘宝商家管理的功能
1.商家后台登陆后，有一个商品详情页：每个商品都有一个详情的修改按钮，点击修改（可以想象成淘宝商品预览页面，淘宝商品下面那个图文的介绍我们再这里使用的是您的富文本）
2.粘贴一段内容，不会出现问题
3.我们再这个页面有一个提交功能，就是商家上传他们的商品介绍
4.商家再次点击某一个商品的详情按钮-修改-再从其他地方复制一段内容，再次粘贴-会重复两份，比如“你好你好”
5.再次提交，然后再次打开某一个商品的详情按钮-修改-复制-那就会“你好你好你好”，

**Comment by zxqAzxq-hash** [comment]
我刚才想起来一个问题就是我这个富文本只是单纯的 ### editor.create() 创建了，每次提交后就跳转会商品详情页了，我并没有关闭这个editor啊。会不会是这个问题？

**Comment by zxqAzxq-hash** [comment]
就是点击详情页进行了修改时候editor.create()创建了一个富文本，然后提交内容后跳转到了详情页，再次点击详情页有创建一个，上一次的没有关闭掉？**而且我上面提到的重复问题可以通过刷新页面来解决。**

**Comment by UltramanWeiLai** [comment]
可以试一下再销毁生命周期里面 销毁编辑器

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
