### ISSUE TITLE
文字颜色和背景颜色选择框的一点建议

### ISSUE THREAD

**Issue by oxywen** [wangeditor-team/wangEditor#2967]
## 功能描述

您好，非常感激您分享了这个强大的项目。在使用wangEditor的过程中，我想提供一个建议。
在当前版本的wangEditor中，关于文字颜色和背景颜色的选择框是这样子的，但可能由于线条粗细的原因，颜色指示的可能不够明显，特别是白色、灰色这种浅色可能就更加不明显。
![image](https://user-images.githubusercontent.com/48750627/109520638-6bd3aa80-7ae7-11eb-9bca-500816ac8d60.png)
同时如果需要更多的颜色种类也需要进行手动的配置，这一点可能有点麻烦。

## 提炼几个功能点

- 增强选择框中颜色按钮的样式辨识度
- 内置更多的基础颜色
- 提供色值的输入框便于自定义颜色

## 原型图

原型图可见下图参考案例，当然在这个基础上，可以在近期使用和全部颜色之间，加上一个栏目 【推荐使用】，这里存放可在代码中配置的初始色值。

## 可参考的案例
参考案例，来自今日头条。
![image](https://user-images.githubusercontent.com/48750627/109521116-ea304c80-7ae7-11eb-93c1-619c9812f652.png)
http://mp.toutiao.com/profile_v4/graphic/publish

**Comment by wangfupeng1988** [comment]
这个问题 @clinfc  正在开发中。参考这个 issue https://github.com/wangeditor-team/wangEditor/issues/2529
