### ISSUE TITLE
请问是如何实现execCommand('fontSize')这个方法的？

### ISSUE THREAD

**Issue by theChengundertheQun** [wangeditor-team/wangEditor#2969]
我现在有个需求 需要自己实现一个富文本编辑器 然后文本方面有三个功能 加粗、斜体、跟标题字体
具体需求是 框选中一段文本 点击加粗 这个时候这段文本加粗 再点击斜体 这段文本加粗+倾斜 再点击标题icon 这段文本加粗+倾斜+字体放大
再点击加粗 这段文本取消加粗 只剩倾斜 + 字体放大
我的代码是:
```
const handleBold = () => {
    restoreSelection(); // 光标返回之前的位置
    
    console.log(state.range);

    document.execCommand('bold', false, null);
  };

  const handleFontSize = () => {
    restoreSelection();

    document.execCommand('fontSize', false, 4);
  }

  const handleItalic = () => {
    restoreSelection();

    document.execCommand('italic', false, null);
  }
```

但我发现fontSize并不是一个类似开关的属性 设置第二次并不会取消 只能document.execCommand('removeFormat', false, null); 
但我如何去判断何时设置何时取消呢？然后如何保留其他的样式呢？

**Comment by UltramanWeiLai** [comment]
还请按照模板提交 issue 否则是不受理的
可以看看我们编辑器的的 fontSize 的实现
