### ISSUE TITLE
如何导出word

### ISSUE THREAD

**Issue by nanachiOwQ** [wangeditor-team/wangEditor#2974]
## 问题描述

只能结合其他插件实现吗

## wangEditor 版本

4.6.7

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

**Comment by UltramanWeiLai** [comment]
是的，目前编辑器只是处理富文本的，导出 word 一般是在线文档才会提供的功能
