### ISSUE TITLE
图片bug

### ISSUE THREAD

**Issue by zhaoguangyue** [wangeditor-team/wangEditor#2975]
## bug 描述
不使用网络图片，现在上传图片是点击就直接调起图片上传弹框吗
上传后框对不齐
![image](https://user-images.githubusercontent.com/25996201/109750233-04b51380-7c17-11eb-82b9-c3f0aa1ea5a3.png)

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
不设置网络图片目前是可以设置是否需要出现面板的。
这不是框不准确，是选区会获取行高，图片本身大小是没问题的，你可以通过控制台查看图片大小
