### ISSUE TITLE
> 让无序和有序缩进的功能

### ISSUE THREAD

**Issue by Myqilixiang** [wangeditor-team/wangEditor#2976]
> 让无序和有序缩进的功能

你是只多级的列表吗？

_Originally posted by @wangfupeng1988 in https://github.com/wangeditor-team/wangEditor/issues/766#issuecomment-320186790_

是的 现在无序列表不可多级显示

**Comment by UltramanWeiLai** [comment]
请按照模板进行提交问题，否则是不受理的
该功能开发起来非常复杂周期会比较长，目前我们主要是优先编辑器稳定合优化方面，所以目前可能不会考虑开发该功能
