### ISSUE TITLE
表格缺少单元格合并功能

### ISSUE THREAD

**Issue by yangdaming0218** [wangeditor-team/wangEditor#2977]
在编辑器中插入表格后，鼠标选中想要合并的单元格区域，没有合并功能，在官网中也没有看到单元格合并的相关描述，这个功能只要涉及需要插入表格的样式，感觉是一个不可或缺的功能，希望能够开发一下。
![image](https://user-images.githubusercontent.com/39049385/109787714-7c9c3180-7c49-11eb-9e42-8eccfa13296e.png)

**Comment by UltramanWeiLai** [comment]
该功能开发起来非常复杂周期会比较长，目前我们主要是优先编辑器稳定合优化方面，所以目前可能不会考虑开发该功能
