### ISSUE TITLE
光标显示问题

### ISSUE THREAD

**Issue by yangdaming0218** [wangeditor-team/wangEditor#2978]
## 问题描述
问题1、在编辑器中，我编辑一段内容，发现其中有一段内容错了，此时我将光标点到需要修改的位置，我完成一次输入后，光标又自动返回到了内容最后，对于修改的体验不好。
问题2、在编辑器中，多次按enter键换行，光标有时会出现上下跳动等情况。
*请输入遇到的问题...*

## wangEditor 版本
4.6.9
*请输入内容……*

## 是否查阅了文档 ？
（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤
问题1、随便打一段文字，修改中间的内容
问题2、上传一张图片，在图片后面多次按enter键
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
官网是否有能复现该问题？
内部是否使用了 onchange 去同步编辑区域的内容？

**Comment by yangdaming0218** [comment]
官网没有这个问题，因为在项目中需要监听父组件传递的参数数据，将数据在编辑器中回显导致

> 官网是否有能复现该问题？
> 内部是否使用了onchange去同步编辑区域的内容？

官网没有这个问题，问题原因是因为我需要监听父组件传递的参数，将数据在编辑器中进行回显导致

**Comment by 17biubiu** [comment]
这个问题看着是chrome86升级之后，compositionstart监听事件对中文做了特殊处理，
![image](https://user-images.githubusercontent.com/13295895/110111382-32eb4c80-7deb-11eb-8435-034d04542746.png)

**Comment by wangfupeng1988** [comment]
不要在编辑器中回显，编辑区域也不支持这样的回显。直接用 onchange 获取内容即可。

**Comment by sunbingqing** [comment]
请问第一个问题解决了吗？我也遇到了，怎么处理
