### ISSUE TITLE
vue 封装 wangEditor 组件 多次加载出现英文词条问题

### ISSUE THREAD

**Issue by chailiangyang** [wangeditor-team/wangEditor#2980]
1、组件封装 添加销毁钩子函数 销毁组件
2、同时在容器上添加了v-if 强制更新组件
3、首次加载正常第二次及以后 会出现 英文问题
4、版本号 4.6.6
   求大佬给出解决问题的方法

 beforeDestroy() {
    this.instance.destroy();
    this.showEditor = false;
    this.instance = null;
  },

**Comment by UltramanWeiLai** [comment]
请按照模板进行提交 issue 否则是不受理的
另外请经量详细的提供复现步骤给我们，不然很难复现。
