### ISSUE TITLE
插入代码添加事件

### ISSUE THREAD

**Issue by xixixida** [wangeditor-team/wangEditor#2982]
###在插入代码能不能增加钩子或者使用highlight的时候吧语言类型传出来

我想在代码菜单里添加一个 Katex 的公式选项，我现在无法通过事件或者 highlight 拿到这个选项类型 *

## 提炼几个功能点

- 可以在用户点击插入提供钩子可以拿到代码和代码类型
- 在使用highlight的时候能拿到代码和代码类型

**Comment by wangfupeng1988** [comment]
暂时不支持。
公式菜单后面会单独开发。
