### ISSUE TITLE
菜单提示信息可否新增下标显示

### ISSUE THREAD

**Issue by swling** [wangeditor-team/wangEditor#2986]
## 功能描述
悬停到菜单上，提示信息目前是在菜单上方显示，存在两个问题：
- 当编辑器全屏的时候，提示信息就被完全遮住了
- 当选择将菜单栏和文本区域分开时，如目前流行的，编辑页面向下滚动时，将菜单栏悬浮固定在页面顶部，也会存在类似的问题，不得不额外预留一个高度，影响整体美观度。

## 提炼几个功能点
- 菜单提示信息可选上标或下标显示，或其他优化 UI 的方式，以解决全屏编辑，或将菜单栏固定在页面顶部需额外处理布局的问题。

## 原型图
暂无

## 可参考的案例
今日头条、百家号内容编辑器。

**Comment by wangfupeng1988** [comment]
感谢这个提议，我们已经受理了。
目前还不能立马做，需要等待一下，等待 https://github.com/wangeditor-team/wangEditor/issues/2999 完成之后。

**Comment by YmCoke** [comment]
交叉测试： @liuqh0609
