### ISSUE TITLE
复制黏贴有时候会出现在文本最下方情况

### ISSUE THREAD

**Issue by babaiwan** [wangeditor-team/wangEditor#2987]
![image](https://user-images.githubusercontent.com/50008615/110075652-17b61800-7dbe-11eb-8dce-45cd149ee542.png)

如图，复制黏贴时，并不总是在编辑器当前行的P标签中添加内容，而是会新增一个p标签 append在最下方

**Comment by wangfupeng1988** [comment]
请按照 issue 模板重新提交。
注意，试一下最新版的编辑器（官网上即可）
