### ISSUE TITLE
代码块高亮，css引入问题

### ISSUE THREAD

**Issue by MengfeiCao** [wangeditor-team/wangEditor#2988]
## bug 描述

*根据官网指导，代码块高亮必须引入highlight的css，npm方式为：import 'highlight.js/styles/monokai_sublime.css'，但引入之后报错：Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve 'highlight.js/styles/monokai_sublime.css'，经过将近一天的筛查，发现最后一级文件名错误，应该是monokai-sublime.css*

## 你预期的样子是？

*import 'highlight.js/styles/monokai-sublime.css'*

## 浏览器及版本号

*Chrome 88.0.4324.190*

## wangEditor 版本

*V4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- npm安装：npm install highlight.js -S
- 步骤二
- css文件引入：import 'highlight.js/styles/monokai_sublime.css'

**Comment by wangfupeng1988** [comment]
@lkw199711 看下这个问题吧，能否复现？

**Comment by lkw199711** [comment]
问题存在，感谢指正
npm引入名词分割为‘-’； cdn引入为‘_’；
将对用户文档进行修改。
