### ISSUE TITLE
输入中文时placeholder不消失

### ISSUE THREAD

**Issue by jaxlix** [wangeditor-team/wangEditor#2989]
## bug 描述

1.无内容时会显示placeholder
2.获取焦点后，开始拼写中文，但是不选中中文，此时输入框会显示键入的英文字符，但是placeholder不消失，出现重叠
![1614934538(1)](https://user-images.githubusercontent.com/27676731/110094871-468cb800-7dd7-11eb-9604-fe13dbcfd25d.png)

## 你预期的样子是？

在拼写中文但未填充到输入框时，不要填充英文字符

## 浏览器及版本号

chrome：v88

## wangEditor 版本

v4.5.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一：清空输入框，出现placeholder
- 步骤二：输入法切换为中文，点击输入框获取焦点
- 步骤三：拼写中文，但不要选中中文输入

**Comment by wangfupeng1988** [comment]
修改时：
单独针对拼音事件，来处理 placeholder
不要动 onchange 的逻辑。
