### ISSUE TITLE
先设置有序列表或者无序列表后再设置行高无效

### ISSUE THREAD

**Issue by Amoxi1** [wangeditor-team/wangEditor#2990]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请按照 issue 模板，重新提交。
