### ISSUE TITLE
复制图片的时候遇到防盗链问题

### ISSUE THREAD

**Issue by jiaotadie** [wangeditor-team/wangEditor#2991]
## 问题描述
复制图片的时候遇到防盗链问题
*请输入遇到的问题...*
复制图片的时候遇到防盗链问题，请问能否解决比如复制过来直接转换成base64
## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
防盗链，前端是没有办法的。否则防盗链也就没有意义了。
你可以右击图片，拷贝图片，然后粘贴到编辑器中。官网就支持这个功能。
