### ISSUE TITLE
光标前图片前面回车图片会被删除

### ISSUE THREAD

**Issue by xiaokyo** [wangeditor-team/wangEditor#2995]
## bug 描述

光标前图片前面回车图片会被删除

## 你预期的样子是？

回车后图片依然还在并且换行

## 浏览器及版本号

chrome

## wangEditor 版本

4.6.8

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 复制这个图片链接： https://www.baidu.com/img/PCpad_012830ebaa7e4379ce9a9ed1b71f7507.png
- 然后新窗口打开官网 ctrl+shift+[点击这里](https://www.wangeditor.com/?_blank)
- 插入网络图片，确保图片位置当前行后面没有其他东西
- 然后在图片前面回车，图片会消失

**Comment by UltramanWeiLai** [comment]
# 2996
