### ISSUE TITLE
当代码块是最后一行时，无法在下面再输入内容了

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#2998]
## bug 描述

当代码块是最后一行时，无法在下面再输入内容了

## 你预期的样子是？

可以继续输入内容

## 浏览器及版本号

chrome 88

## wangEditor 版本

v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 插入一段代码块
- 将代码块下面的所有内容全部删除，空行也不留，全部删除
- 无法在下面再输入内容了

**Comment by wangfupeng1988** [comment]
参考目前的表格。如果表格是最后一行，后面永远有一个空行。（记得是颜彪开发的该功能）

**Comment by liuqh0609** [comment]
交叉测试：@qianfengg
