### ISSUE TITLE
dropList 菜单，建议改成 click ，而不是 hover

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#2999]
## 功能描述

dropList 菜单，建议改成 click ，而不是 hover 。
例如“序列”菜单，现在是 hover 就现实 dropList ，建议改成 click 才展示 dropList 。

![image](https://user-images.githubusercontent.com/9583120/110199387-160a5400-7e93-11eb-9871-7fd04a4efff7.png)

这样修改的主要原因：
当前，鼠标点击“链接”菜单，然后稍微又移，移动到“序列”菜单上，链接的 panel 就会消失。用户体验非常差，一不小心就这样。
所以，如果如上所说，dropList 由 hover 改成 click ，就不会有这个问题了。

![image](https://user-images.githubusercontent.com/9583120/110199461-68e40b80-7e93-11eb-8ad9-9fac19d708d3.png)

## 提炼几个功能点

- dropList 由 hover 改成 click

## 原型图

无

## 可参考的案例

无

**Comment by wangfupeng1988** [comment]
> 当前，鼠标点击“链接”菜单，然后稍微又移，移动到“序列”菜单上，链接的 panel 就会消失。用户体验非常差，一不小心就这样。
注意，做这个改动，是为了解决这个问题

**Comment by YmCoke** [comment]
交叉测试： @UltramanWeiLai
