### ISSUE TITLE
【Bug】菜单和编辑区域分离设置默认内容

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#3000]
## bug 描述

菜单和编辑区域分离的情况下，设置默认内容会导致默认内容不会被收录到生成编辑器的编辑区域内

## 你预期的样子是？

正常显示默认内容

## 浏览器及版本号

所有

## wangEditor 版本

所有

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 设置 菜单栏和编辑区域分离
- 步骤二 在给配置给编辑区域的 标签 里面添加 默认内容
- 步骤三 创建编辑器查看页面

**Comment by qianfengg** [comment]
交叉测试：@liuqh0609
