### ISSUE TITLE
视频显示很小

### ISSUE THREAD

**Issue by yangfeng1003** [wangeditor-team/wangEditor#3001]
视频在iframe上传后，无法设置大小，富文本编辑的效果：
![image](https://p0.meituan.net/travelcube/34ad1bb32773dce7f6bb89c0e15b4570153286.jpg@750w_80q)

页面展示效果如下：
![图片](https://p0.meituan.net/travelcube/f36416f074fc03df0c657c1e50f4505a653692.jpg@750w_80q)

希望可以像图片一样，达到最大占满屏幕宽度，且高度自适应

**Comment by rsl140** [comment]
你好，请按 issue 模板格式提交。
