### ISSUE TITLE
光标定位异常

### ISSUE THREAD

**Issue by janyyy** [wangeditor-team/wangEditor#3005]
## bug 描述

*多段落编辑，光标每改一下光标都会定位到最后一行*

## 你预期的样子是？

*光标在当前位置不动，比如说我删除第一段某个文字。不能跳到第二段最后一行*

## 浏览器及版本号

*89.0.774.45*

## wangEditor 版本

*4.6.8*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
新建三段文字
- 步骤二
新增/删除第一段文字某个字符
- 步骤三
光标跳到最后一行
![GIF 2021-3-7 14-59-42](https://user-images.githubusercontent.com/27274865/110232393-541d7b80-7f58-11eb-82d8-a1037e9f5a77.gif)

**Comment by wangfupeng1988** [comment]
官网不能复现，那什么环境下才能复现呢？
即，如何让我们复现这个问题？否则也没法改

**Comment by janyyy** [comment]
> ## bug 描述
> _多段落编辑，光标每改一下光标都会定位到最后一行_
> 
> ## 你预期的样子是？
> _光标在当前位置不动，比如说我删除第一段某个文字。不能跳到第二段最后一行_
> 
> ## 浏览器及版本号
> _89.0.774.45_
> 
> ## wangEditor 版本
> _4.6.8_
> 
> ## 官网能否复现该 bug ？
> 不能
> 
> ## 最小成本的复现步骤
> （请告诉我们，如何最快的复现该 bug）
> 
> * 步骤一
>   新建三段文字
> * 步骤二
>   新增 / 删除第一段文字某个字符
> * 步骤三
>   光标跳到最后一行
>   ![GIF 2021-3-7 14-59-42](https://user-images.githubusercontent.com/27274865/110232393-541d7b80-7f58-11eb-82d8-a1037e9f5a77.gif)
