### ISSUE TITLE
视频无法调整显示大小

### ISSUE THREAD

**Issue by yangfeng1003** [wangeditor-team/wangEditor#3007]
## bug 描述

插入视频文件无法设置显示大小

## 你预期的样子是？

可以占满容器宽度显示，并且视频宽高比不变

## 浏览器及版本号

谷歌

## wangEditor 版本

*4.6.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
  插入视频 

  ```html
  <iframe src="https://flowplus.meituan.net/v1/mss_a002ed9fc97544cebd70304686903863/cube/1614844148934.mp4" ></iframe>
  ```

  ![](https://p0.meituan.net/travelcube/34ad1bb32773dce7f6bb89c0e15b4570153286.jpg@750w_80q)

- 步骤二
  查看展示效果 ：图中视频展示过小。例如图中的图片那样，按照100%展示，否则在手机上看不清楚

  ```html
  <div dangerouslySetInnerHTML={{ __html: content }}></div>
  ```

  ![](https://p0.meituan.net/travelcube/f36416f074fc03df0c657c1e50f4505a653692.jpg@750w_80q)

**Comment by janyyy** [comment]
指定width height可以暂时处理

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
