### ISSUE TITLE
引入代码块，保存后，再加载，换行丢失

### ISSUE THREAD

**Issue by tywo45** [wangeditor-team/wangEditor#3009]
## bug 描述

引入代码块，保存后，再加载，换行和部分空格丢失

`@RequestPath(value ="/fix")public HttpResponsefix()throws Exception {byte[] bs = Json.toJson(Resp.fail("Your IP is on the blacklist")).getBytes();returnnew HttpResponse(null, bs);
	}`

## 你预期的样子是？

@RequestPath(value ="/fix")
public HttpResponsefix() throws Exception { 
    byte[] bs = Json.toJson(Resp.fail("Your IP is on the blacklist")).getBytes();
    return new HttpResponse(null, bs);
	}

## 浏览器及版本号

chrome 89.0.4389.72（正式版本） （64 位）

## wangEditor 版本

wangeditor@4.6.8

## 官网能否复现该 bug ？

不知道，因为涉及到回显

## 最小成本的复现步骤
- 插入代码块
- 保存html
- 在编辑框中回显html

**Comment by tywo45** [comment]
https://www.tiocloud.com/2/case/index.html
到这里来提交案例，然后再编辑案例，就能重现了

**Comment by rsl140** [comment]
建议暂时先不使用高亮，代码块这部分会重构

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
