### ISSUE TITLE
不支持字符串类型的节点作为编辑器的默认值

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/wangEditor#3010]
## bug 描述

问题一: 不支持字符串类型的节点作为编辑器的默认值
```
<div id="app">1123</div>
```
```
<div id="app">1123 <p>456</p></div>
```
都会有问题

## 你预期的样子是？

可以支持

## 浏览器及版本号

chrom

## wangEditor 版本

4.6.8

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 第一步 
设置默认html 为 
```
<div id="app">1123 <p>456</p></div>
```
第二步
```
a = new E('#app')
a.create()
```
![image](https://user-images.githubusercontent.com/20200267/110266873-b1b5d480-7ff9-11eb-90d5-2577ad52c244.png)

**Comment by rsl140** [comment]
你好，文字内容需要包含在P标签内，这是必要条件。
