### ISSUE TITLE
在做数据回显的时候，编辑内容会自动跳到文章最后一行

### ISSUE THREAD

**Issue by cmlly** [wangeditor-team/wangEditor#3011]
## bug 描述

在做数据回显的时候，编辑内容会自动跳到文章最后一行

## 你预期的样子是？

编辑内容应该正常按顺序来

## 浏览器及版本号

谷歌 88.0.4324.190

## wangEditor 版本

4.6.8

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
可否提空详细的复现步骤以便我们定位问题。

**Comment by UltramanWeiLai** [comment]
编辑器不支持双向绑定

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
