### ISSUE TITLE
火狐浏览器下，插入代码块后，无法再次进行编辑

### ISSUE THREAD

**Issue by liuqh0609** [wangeditor-team/wangEditor#3016]
## bug 描述
在火狐浏览器下，新插入代码块之后，无法向代码块中输入新内容

## 你预期的样子是？

正常编辑修改代码块内容

## 浏览器及版本号

Mac电脑
Firefox： 86.0（64位）

## wangEditor 版本

4.6.8

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一： 找个区域插入代码块
- 步骤二： 插入完成后，点击代码块输入内容，无反应

**Comment by rsl140** [comment]
代码块中的内容应该是不可编辑的
