### ISSUE TITLE
输入文本不能使用Backspace删除，全选设置字号，只有部分被修改

### ISSUE THREAD

**Issue by harshwinter** [wangeditor-team/wangEditor#3019]
## bug 描述

1、easyui框架下，输入文本不能使用Backspace删除，Delete可以，deleteUpEvents能执行，尝试修改z-index，未解决
2、全选设置字号字体等，只有部分被修改（偶发）

## 你预期的样子是？

可以使用Backspace删除文本

## 浏览器及版本号

谷歌浏览器 83.0.4103.61及360极速最新

## wangEditor 版本

V4 

## 官网能否复现该 bug ？

问题一不能复现。问题2官网提供的在线demo网址可复现，但是偶发 

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一输入文本
- 步骤二拖动鼠标全选文本
- 步骤三设置字号或字体、斜体等
![123](https://user-images.githubusercontent.com/65010769/110566194-a0e89880-818a-11eb-8126-80ee448b57ff.gif)

**Comment by UltramanWeiLai** [comment]
你可以现在一个只有编辑器的场景下去测试一下是否能浮现这些问题。
或者是否能提供可以复现问题的环境给我们进行复现。
越简单越好

**Comment by harshwinter** [comment]
> 你可以现在一个只有编辑器的场景下去测试一下是否能浮现这些问题。
> 或者是否能提供可以复现问题的环境给我们进行复现。
> 越简单越好
第二个问题 上传了一个gif 是在线体验 demo网站上 复现的
https://codepen.io/xiaokyo-the-bold/pen/ZEpWByR
![123](https://user-images.githubusercontent.com/65010769/110579604-1b70e280-81a2-11eb-991d-8454fc5649fe.gif)

**Comment by UltramanWeiLai** [comment]
问题二已复现并且重新提交了个 issue 进行跟进 #3024

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
