### ISSUE TITLE
粘贴从Word文档复制过来的内容会在顶部出现样式代码

### ISSUE THREAD

**Issue by Jasery** [wangeditor-team/wangEditor#3020]
## bug 描述

关闭粘贴样式过滤后，粘贴从Word文档复制过来的内容会在顶部出现部分样式代码
![image](https://user-images.githubusercontent.com/20091279/110567676-dd1cf880-818c-11eb-992f-bff67b1b16ab.png)
用的是WPS，版本：v11.1.0

## 你预期的样子是？

正确显示复制的文本，无额外的内容

## 浏览器及版本号

Chrome 88.0.4324.190

## wangEditor 版本

4.6.8

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 设置`editor.config.pasteFilterStyle = false`
- 复制Word文档里面的文本
- 粘贴到编辑器里面

**Comment by aoxiangsky** [comment]
我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。  原因未知。

**Comment by ToCooking** [comment]
那你们解决一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 中午11:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 粘贴从Word文档复制过来的内容会在顶部出现样式代码 (#3020)





 
我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。  原因未知。

**Comment by Jasery** [comment]
> 我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。 原因未知。

能不能问一下你旁边同事的系统和用的word版本？

**Comment by aoxiangsky** [comment]
> > 我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。 原因未知。
> 
> 能不能问一下你旁边同事的系统和用的word版本？

这个问题已经修复了，最新的官方版本v4.6.9已无该问题。 昨天我用的版本是v4.5.4

**Comment by UltramanWeiLai** [comment]
> > 我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。 原因未知。
> 
> 能不能问一下你旁边同事的系统和用的word版本？

wps 带着的样式是以 style 标签的形式进入剪切板的，该问题之前已经处理过所以可以先更新一下版本后再看看效果，额外说一句，因为 wps 的样式是 style 标签，所以即使是开放了粘贴样式不过滤后依旧是拿不到任何样式的，这点还请悉知。

**Comment by Jasery** [comment]
> > > 我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。 原因未知。
> > 
> > 
> > 能不能问一下你旁边同事的系统和用的word版本？
> 
> 这个问题已经修复了，最新的官方版本v4.6.9已无该问题。 昨天我用的版本是v4.5.4

升级最新版本测试了，用office没有问题，用WPS还是有问题

**Comment by Jasery** [comment]
> > > 我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。 原因未知。
> > 
> > 
> > 能不能问一下你旁边同事的系统和用的word版本？
> 
> wps 带着的样式是以 style 标签的形式进入剪切板的，该问题之前已经处理过所以可以先更新一下版本后再看看效果，额外说一句，因为 wps 的样式是 style 标签，所以即使是开放了粘贴样式不过滤后依旧是拿不到任何样式的，这点还请悉知。

升级最新版本在WPS下还是一样，WPS复制出来的也有一部分样式是保留在标签里面，开放粘贴样式不过滤还是可以保留部分样式的

**Comment by UltramanWeiLai** [comment]
> 升级最新版本在WPS下还是一样，WPS复制出

官网 demo 能否复现这个问题？

**Comment by UltramanWeiLai** [comment]
该问题移步到 #3061 中跟进吧
应该是修改了其他 bug 导致 wps 设置了 editor.config.pasteFilterStyle = false 的时候不会过滤掉 style 相对应的 wps 的内容有样式了

**Comment by 18720551903** [comment]
> 我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。 原因未知

**Comment by 18720551903** [comment]
> > > 我这也出现了，但是我旁边同事的电脑上没出现，同样的代码。 原因未知。
> > 
> > 
> > 能不能问一下你旁边同事的系统和用的word版本？
> 
> wps 带着的样式是以 style 标签的形式进入剪切板的，该问题之前已经处理过所以可以先更新一下版本后再看看效果，额外说一句，因为 wps 的样式是 style 标签，所以即使是开放了粘贴样式不过滤后依旧是拿不到任何样式的，这点还请悉知。
可以过滤
