### ISSUE TITLE
【Bug】选取范围获取异常

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#3024]
## bug 描述

当拖拽选区的时候，如果鼠标移除到编辑区域外进行拖拽操作，选区则不会更新

## 你预期的样子是？

正常更新选区区域的数据 range

## 浏览器及版本号

所有

## wangEditor 版本

所有

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 输入一段长文字
- 步骤二 在文字的的最右侧按住鼠标拖蓝第一个和几个注意不要全部拖蓝了文字，然后鼠标移出编辑器后继续拖蓝
- 步骤三 设置 加粗、斜体、颜色、等功能

**Comment by YmCoke** [comment]
交叉测试： @UltramanWeiLai
