### ISSUE TITLE
不能使单个元素居中

### ISSUE THREAD

**Issue by xiwang123** [wangeditor-team/wangEditor#3025]
## 问题描述

*请输入遇到的问题...*
输入文字之后，如果我只想把图片居中会导致文字也居中

## wangEditor 版本

*请输入内容……*
4.6.8
## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 输入文字
- 步骤二
- 输入图片
- 步骤三
- 使用居中

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/110742063-ab7d5d80-8270-11eb-854a-382623135447.png)
你好，没有没有复现该问题。

**Comment by xiwang123** [comment]
这是我的问题，我当时可能是图片和文字在一个p标签内导致的问题，现在已经解决了，感谢

**Comment by rsl140** [comment]
> 这是我的问题，我当时可能是图片和文字在一个p标签内导致的问题，现在已经解决了，感谢

好的 那我关闭了
