### ISSUE TITLE
如何单独拿到table元素或者配置table的菜单

### ISSUE THREAD

**Issue by pro-xiaoy** [wangeditor-team/wangEditor#3026]
## 问题描述

需要对独立的table拉出来操作

但是使用**this.editor.selection.getSelectionContainerElem().elems[0]**是选不中table的，看到table的菜单是可以删除table应该是对dom层进行了操作，在官网也没找到删除表格的回调

## wangEditor 版本
v4.6.8

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
在富文本里面是光标是选不中,想拿到独立的tabledom节点

**Comment by wangfupeng1988** [comment]
使用 `editor.selection.getSelectionContainerElem().elems[0]` 获取选中的 elem ，然后顺着 DOM 树向上查找，就可以找到 table elem 。
