### ISSUE TITLE
从秀米，135等复制来的内容如果带svg svg内容丢失

### ISSUE THREAD

**Issue by zyh819heng** [wangeditor-team/wangEditor#3028]
## bug 描述

从秀米，135等复制来的内容如果带svg svg内容丢失.已经关闭内容样式过滤。图片和文字能是能正常显示排版正确的

## 你预期的样子是？

内容和秀米，135一致

## 浏览器及版本号

Google Chrome 88.0.4324.104（正式版本） （64 位）

## wangEditor 版本

4.0.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

从秀米编辑器直接编辑器复制内容到wangEditor

- 步骤一

![image](https://user-images.githubusercontent.com/22977205/110879209-8263d800-8317-11eb-8d16-096a936aec42.png)

- 步骤二
![image](https://user-images.githubusercontent.com/22977205/110879559-28174700-8318-11eb-9c7e-8304f8ffa22b.png)

- 步骤三
上面的图片是F12后秀米对应svg的内容 下面是wangEditor内容，wangEditor过滤了部分内容导致svg无法显示了
![image](https://user-images.githubusercontent.com/22977205/110879259-9c051f80-8317-11eb-88ab-570279777e66.png)
![image](https://user-images.githubusercontent.com/22977205/110879279-a9220e80-8317-11eb-9b42-f0ad4cdb7f6c.png)

**Comment by zyh819heng** [comment]
后来试了关闭js 过滤也无法正常显示svg  editor.config.jsFilter = false;

**Comment by rsl140** [comment]
你好，能提供一个可复现的模板。

**Comment by zyh819heng** [comment]
![image](https://user-images.githubusercontent.com/22977205/110902579-16966500-8341-11eb-957f-000af436a27c.png)
s随便选2个svg都是不行的

**Comment by zyh819heng** [comment]
> 你好，能提供一个可复现的模板。

![image](https://user-images.githubusercontent.com/22977205/110902680-39c11480-8341-11eb-9129-fdc7980a3202.png)
进秀米布局随便选2个svg反正都是不行的

**Comment by zyh819heng** [comment]
> > 你好，能提供一个可复现的模板。
> 
> ![image](https://user-images.githubusercontent.com/22977205/110902680-39c11480-8341-11eb-9129-fdc7980a3202.png)
> 进秀米布局随便选2个svg反正都是不行的

![image](https://user-images.githubusercontent.com/22977205/110905123-f5377800-8344-11eb-9f8c-4b837eb219b8.png)

**Comment by rsl140** [comment]
该问题已经收录，可以移步到 #2803 中去跟进
