### ISSUE TITLE
mac端遨游浏览器无法上传图片

### ISSUE THREAD

**Issue by zengzengli** [wangeditor-team/wangEditor#3030]
## bug 描述

mac端遨游浏览器无法上传图片

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

版本 5.1.60 (180821)

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接在官网实例打开

**Comment by rsl140** [comment]
傲游浏览器官网没有找到mac版下载地址

**Comment by zengzengli** [comment]
> 傲游浏览器官网没有找到mac版下载地址

需要 app Store下载

**Comment by rsl140** [comment]
你好 ，已尝试过修复，但最终发现浏览器自身有一个运行环境的报错提示。也尝试过处理该问题，但是效果都无法满足需求。
还是建议更换其他浏览器
