### ISSUE TITLE
复制粘贴不会触发pasteTextHandle，纯文本会复制粘贴成链接标签

### ISSUE THREAD

**Issue by YeaseonZhang** [wangeditor-team/wangEditor#3032]
## bug 描述

复制富文本内部内容，不会触发pasteTextHandle，特定场景。
比如我手动输入一个url（纯文本），然后复制粘贴变成了一个 <a>标签的链接。同时没有触发pasteTextHandle

## 你预期的样子是？

复制纯文本链接例如：http://www.baidu.com（www.baidu.com不会出现这个问题），仍然得到的是纯文本

## 浏览器及版本号

Chrome  89.0.4389.82

## wangEditor 版本

4.6.7

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
输入：http://www.baidu.com
- 步骤二
复制 粘贴

**Comment by UltramanWeiLai** [comment]
一：复制粘贴检测为链接的情况下自动转换成超链接的行为是优化用户体验的，大部分编辑器或者提供类是功能的产品都会有这方面的考虑例如你提交的 issue 里面的连接。
二：复制富文本内部内容，不会触发pasteTextHandle，特定场景。这个特定场景是什么场景？如何复现？是否能提供复现场景或详细的复现步骤，场景越简单越好。

**Comment by YeaseonZhang** [comment]
> 一：复制粘贴检测为链接的情况下自动转换成超链接的行为是优化用户体验的，大部分编辑器或者提供类是功能的产品都会有这方面的考虑例如你提交的 issue 里面的连接。你不需要连接可以自行选中取消链接，或者自定义处理复制粘贴。
> 二：复制富文本内部内容，不会触发pasteTextHandle，特定场景。这个特定场景是什么场景？如何复现？是否能提供复现场景或详细的复现步骤，场景越简单越好。

**Comment by YeaseonZhang** [comment]
@UltramanWeiLai。第一点，使用了自定义处理复制粘贴，但是不会触发pasteTextHandle。场景上面提到了，复现步骤在富文本编辑器输入http://www.baidu.com，然后复制粘贴，不会触发pasteTextHandle

**Comment by YeaseonZhang** [comment]
发现只要是链接不管是从哪里复制，粘贴到富文本中都不会触发pasteTextHandle

**Comment by YeaseonZhang** [comment]
@UltramanWeiLai

**Comment by UltramanWeiLai** [comment]
已安排成员复现该问题。

**Comment by Gavin-yh** [comment]
@rsl140 交叉测试已完成
