### ISSUE TITLE
谷歌浏览器下，新增表格后，表格下面的标签无法删除

### ISSUE THREAD

**Issue by liuqh0609** [wangeditor-team/wangEditor#3033]
## bug 描述

谷歌浏览器下，新增表格后，表格下面的标签无法删除
![image](https://user-images.githubusercontent.com/43341115/111030471-6a867400-843d-11eb-9ebe-30486b960556.png)

（选中的标签无法删除，导致中间会空出一行）
## 你预期的样子是？

正常删除内容

谷歌：88.0.4324.192

*请输入内容……*

4.6.9

*请输入内容……*

能

## 最小成本的复现步骤

- 步骤一：增加表格
- 步骤二：在表格下面输入三行文字
- 步骤三：删除表格下面的第一行文字

**Comment by UltramanWeiLai** [comment]
我记得好像是为了处理表格后无法插入新的内容做的限制，不过再表格后的内容非最后一列的情况下应该允许删除。
