### ISSUE TITLE
鼠标选中所有内容，长按删除键 ，直到删除了所有内容，然后让编辑器失去焦点，这时候 onblur不触发

### ISSUE THREAD

**Issue by a835100635** [wangeditor-team/wangEditor#3034]
## bug 描述

鼠标选中所有内容，长按删除键 ，直到删除了所有内容，然后让编辑器失去焦点，这时候 onblur不触发

## 你预期的样子是？

 onblur触发

## 浏览器及版本号

谷歌浏览器

## wangEditor 版本

4.6.8

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

鼠标选中所有内容，长按删除键 ，直到删除了所有内容，然后让编辑器失去焦点，这时候 onblur不触发

**Comment by qianfengg** [comment]
交叉测试 @liuqh0609
