### ISSUE TITLE
初始化设置了editor.config.focus = false,  然后随便点个地方 onblur 回调还会触发  ，onfocus 也会触发

### ISSUE THREAD

**Issue by a835100635** [wangeditor-team/wangEditor#3035]
## bug 描述

初始化设置了config.focus = false,  然后随便点个地方 onblur 回调还会触发  ，onfocus 也会触发

## 你预期的样子是？

 onblur 不触发  ，onfocus 不会触发

## 浏览器及版本号

谷歌浏览器

## wangEditor 版本

4.6.8

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

初始化设置了editor.config.focus = false,  然后随便点个地方 onblur 回调还会触发  ，onfocus 也会触发

**Comment by UltramanWeiLai** [comment]
这玩意我记得我好像改过。。

**Comment by hb-bobo** [comment]
我的是create后立马调txt.html()， 会执行focus

**Comment by liuqh0609** [comment]
交叉测试： @YmCoke

**Comment by jyjey** [comment]
我还是遇到这个问题4.7.15版本
