### ISSUE TITLE
以插入视频的方式插入视频, 选中视频, 无法显示tooltip

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/wangEditor#3037]
## bug 描述

以插入视频的方式插入视频, 选中视频, 无法显示tooltip

## 你预期的样子是？

能显示tooltip

## 浏览器及版本号

chrom86 
## wangEditor 版本

v4.6.9
## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 插入视频
![image](https://user-images.githubusercontent.com/20200267/111071074-77739800-850f-11eb-8634-78398d01164c.png)

- 步骤二
- 选中视频
- 步骤三
没有 tooltip 显示

**Comment by UltramanWeiLai** [comment]
我的意见是，插入视频的时候如果插入的是 video 那么也需要支持 tooltip。
但是其他乱七八糟的标签的时候不用

**Comment by a835100635** [comment]
video支持 tooltip。
