### ISSUE TITLE
想探讨一下，哪部分不兼容移动端

### ISSUE THREAD

**Issue by Teacher-Li** [wangeditor-team/wangEditor#3038]
## 问题描述

移动端和pc端都想使用wangEditor，希望可以了解下在移动端方面，会出现哪些严重的bug

## wangEditor 版本

4.6.9

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

无

**Comment by echoLC** [comment]
这个我们也没有严格去测试，只能你自己去整入到移动端项目去试一下。

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
