### ISSUE TITLE
复制粘贴a标签的rel属性被过滤了

### ISSUE THREAD

**Issue by gaoxiangyu1122** [wangeditor-team/wangEditor#3039]
## bug 描述

复制粘贴a标签的rel属性被过滤了

## 你预期的样子是？

复制的a标签是有rel属性的，粘贴过来的html没有了
<a href="https://www.baidu.com" target="_blank" rel="nofllow">测试</a>

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
能提供复现场景或详细的复现步骤？

**Comment by UltramanWeiLai** [comment]
该问题长时间没回复暂且关闭
