### ISSUE TITLE
设置showLinkImg为false后，无法两次上传同一张图片

### ISSUE THREAD

**Issue by gyjlovelh** [wangeditor-team/wangEditor#3041]
## bug 描述

做如下设置之后 
```
editor.config.showLinkImg = false;
editor.config.uploadImgShowBase64 = true;
```
1. 连续上传一张图片两次，第二次无反应。
2. 上传A图片，删除，再次上传A图片，无反应。
## 你预期的样子是？

第二次可以上传

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

4.6.9

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
```
editor.config.showLinkImg = false;
editor.config.uploadImgShowBase64 = true;
```
- 步骤二 
   上传一张图片
- 步骤三
    再次上传该图片（一定要是同一张图片）

**Comment by mybells** [comment]
customUploadImg上传完后加`let toolbarId = `#${this.editor.toolbarElemId} input[id^=up-file-id]`;
                let el = document.querySelector(toolbarId);
                if(el) {
                    el.value = null;
                }`

**Comment by Gavin-yh** [comment]
@rsl140  交叉测试完
