### ISSUE TITLE
插入的视频不希望自动播放

### ISSUE THREAD

**Issue by yangfeng1003** [wangeditor-team/wangEditor#3043]
## 问题描述

*插入的视频无法设置是否自动播放*

## wangEditor 版本

*任意版本*

## 是否查阅了文档 ？

*是，文档未涉及*

## 最小成本的复现步骤

在富文本中插入视频，视频就直接开始播放了。保存后查看页面，视频同样是自动播放的，在C端打开的话耗费用户流量。
检查元素发现video自带了autoplay属性，如下图
![image](https://user-images.githubusercontent.com/44138013/111283922-917db980-867a-11eb-8599-6d23f57a8243.png)

**Comment by rsl140** [comment]
iframe 插入的视频 video的属性 是取决于视频网站自己的配置哦。

**Comment by aoxiangsky** [comment]
> iframe 插入的视频 video的属性 是取决于视频网站自己的配置哦。

我这是上传到七牛云，然后把返回链接用<frame/>插入，也是自动播放。不知道到取决于视频网站自己配置这句话是什么意思。临时解决方案是直接用video标签插入

**Comment by rsl140** [comment]
取决于 iframe里的src中配置的网站，这个网站对video的设置 比如你截图中的
![image](https://user-images.githubusercontent.com/7655291/111409524-12d45b00-8712-11eb-8467-5037ef7b056f.png)
