### ISSUE TITLE
文字颜色和背景颜色中的白色不容易辨别

### ISSUE THREAD

**Issue by rsl140** [wangeditor-team/wangEditor#3048]
## 功能描述

文字颜色和背景颜色中的白色不容易辨别，建议将白色提前而不是放在最后一个。
例如：
![image](https://user-images.githubusercontent.com/7655291/111431704-1201f000-8737-11eb-9e57-7e7e8a823729.png)
当前需要鼠标移动到最后才能看见

可以将白色提前便于发现有一个白色。

## 提炼几个功能点

将文字颜色和背景颜色中的白色位置提前。
![image](https://user-images.githubusercontent.com/7655291/111431817-35c53600-8737-11eb-824b-26ac6af4a797.png)

**Comment by Gavin-yh** [comment]
[fix: 文字颜色和背景颜色中的白色不容易辨别, 调整位置](https://github.com/wangeditor-team/wangEditor/pull/3067/commits/6f0390b44994bf4f026180ab10655317c45e6d57)
