### ISSUE TITLE
功能区增加占位符

### ISSUE THREAD

**Issue by CrazyWood007** [wangeditor-team/wangEditor#3049]
## 功能描述

希望头部功能区能增加占位符，便于功能列表的排版，分组

*请输入内容……*

现有逻辑是功能区按menu顺序展示按钮，希望在menu中能增加一种关键字，例如placeholder，用于渲染一个空的按钮，从而让功能区分组，尤其是当面板宽度不足时，功能区渲染为多行，可以美化排版

最好能有两个值，一个占位半个格子，一个占位一个格子

## 提炼几个功能点

- 功能1 menu中增加占位关键字，用于在功能区渲染空格子，无交互

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by UltramanWeiLai** [comment]
感谢你的意见，我先收录一下，不过该功能的有优先度会比较低，可能近期不会去处理。

**Comment by wangfupeng1988** [comment]
我理解，你要的应该是菜单分组的功能，对吧？

**Comment by CrazyWood007** [comment]
对，主要原因就是这个，因为我使用的场景是盒子比较窄，菜单要换行，这个时候如果redo和undo分在了两行就会不太优雅 林俊辰 ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月13日 20:26，王福朋 写道： 我理解，你要的应该是菜单分组的功能，对吧？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
