### ISSUE TITLE
修改工具栏的字号，换行后选择其他字号设置，输入文字发现第2、4、6个配置的字号无法生效

### ISSUE THREAD

**Issue by yangfeng1003** [wangeditor-team/wangEditor#3050]
### 问题描述
设置了7个新的字号，新起一行输入的情况下，发现有3个字号未生效，4个字号可以正常设置

## wangEditor 版本
4.6.5

## 是否查阅了文档 ？
是

## 步骤一
默认的字号较小，因此将7个字号改为更大的数字。
editor.config.fontSizes = {
      'x-small': { name: '28px', value: '1' },
      small: { name: '30px', value: '2' },
      normal: { name: '32px', value: '3' },
      large: { name: '34px', value: '4' },
      'x-large': { name: '36px', value: '5' },
      'xx-large': { name: '38px', value: '6' },
      'xxx-large': { name: '40px', value: '7' },
    };
font[size='1'] {
 font-size: 28px;
}
font[size='2'] {
 font-size: 30px;
}
font[size='3'] {
 font-size: 32px;
}
font[size='4'] {
 font-size: 34px;
}
font[size='5'] {
 font-size: 36px;
}
font[size='6'] {
 font-size: 38px;
}
font[size='7'] {
 font-size: 40px;
}
## 步骤二
空白的编辑框，选择字号28px，然后输入内容，正常。
## 步骤三
按下换行符，光标移到第二行，此时选择30px字号设置，输入内容，发现子特别小，是编辑器默认的大小，不是30px
## 步骤四
再次换行，选择32px，输入发现正常
在换行选择34，又变成默认字体。
后续依次换行和增大字体，一个字号生效，一个不生效，循环往复...
![image](https://user-images.githubusercontent.com/44138013/111463550-a92c6f00-875a-11eb-9c8c-bb5e29787793.png)

**Comment by UltramanWeiLai** [comment]
可以尝试更新一下版本，该问题已经在上周发布的版本中解决了应该 #2901 可以在该 issue 中查看相关内容和修改

**Comment by yangfeng1003** [comment]
> 可以尝试更新一下版本，该问题已经在上周发布的版本中解决了应该 #2901 可以在该 issue 中查看相关内容和修改

更新的代码发布了吗，   我更新了npm包到版本4.6.9，发现还有问题

**Comment by yangfeng1003** [comment]
> > 可以尝试更新一下版本，该问题已经在上周发布的版本中解决了应该 #2901 可以在该 issue 中查看相关内容和修改
> 
> 更新的代码发布了吗， 我更新了npm包到版本4.6.9，发现还有问题

而且我看官网现在还是有问题的啊  这个能修复一下吗，特别紧急...   https://www.wangeditor.com/ 直接可以在官网复现   谢谢！！！

**Comment by blackhu0804** [comment]
> > > 可以尝试更新一下版本，该问题已经在上周发布的版本中解决了应该 #2901 可以在该 issue 中查看相关内容和修改
> > 
> > 
> > 更新的代码发布了吗， 我更新了npm包到版本4.6.9，发现还有问题
> 
> 而且我看官网现在还是有问题的啊 这个能修复一下吗，特别紧急... https://www.wangeditor.com/ 直接可以在官网复现 谢谢！！！

尽量在下个版本修复

**Comment by yangfeng1003** [comment]
请问下个版本大概什么时间上线呢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月21日(星期天) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 修改工具栏的字号，换行后选择其他字号设置，输入文字发现第2、4、6个配置的字号无法生效 (#3050)

**Comment by blackhu0804** [comment]
> 请问下个版本大概什么时间上线呢------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年3月21日(星期天) 下午4:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wangeditor-team/wangEditor] 修改工具栏的字号，换行后选择其他字号设置，输入文字发现第2、4、6个配置的字号无法生效 (#3050)

大概在下周四周五，这周工作太忙暂时没时间处理
