### ISSUE TITLE
通过insertHTML插入公式svg图片后 图片左右都没办法聚焦 而且没有插入到文本同一行

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3051]
## 问题描述

通过insertHTML插入公式svg图片后 图片左右都没办法聚焦 而且没有插入到文本同一行，我插入的就是span元素通过insertHTML应该是插入在同一行，图片插入就是一样的道理没有问题,但是插入svg图片后就换行 而且左右都无法聚焦 无法删除插入的图片
## wangEditor 版本
![9d18b59b72f6566b7655987a832bae6](https://user-images.githubusercontent.com/43296632/111603976-d25b0700-880f-11eb-8c74-9c36df221edd.png)

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
插入svg图片 可以复现

**Comment by OnePsycho** [comment]
只能在文字后面聚焦 继续编辑 但是公式那一行 都是没办法操作的 删除也不行

**Comment by rsl140** [comment]
你好，能否提供复现场景或详细的复现步骤，场景越简单越好。

**Comment by OnePsycho** [comment]
就是直接通过这样 插入一段HTML 内容就是一段 <svg>xxxxxxx</svg> 那个公式就一张SVG图片  就会出现我所说的情况
![47816d7e962603865a520c08a6316b7](https://user-images.githubusercontent.com/43296632/111720342-a041b780-8898-11eb-84a9-8ad3a61ba33a.png)

**Comment by UltramanWeiLai** [comment]
应该是浏览器的默认行为吧
公式的话我们目前已经在研发中了。
也有在做 卡片机制 的处理。

**Comment by OnePsycho** [comment]
> 应该是浏览器的默认行为吧( svg )
> 公式的话我们目前已经在研发中了。
> 也有在做 卡片机制 的处理。

那针对目前这种情况，该如何来解决呢 有建议嘛？谢谢大佬

**Comment by UltramanWeiLai** [comment]
> > 应该是浏览器的默认行为吧( svg )
> > 公式的话我们目前已经在研发中了。
> > 也有在做 卡片机制 的处理。
> 
> 那针对目前这种情况，该如何来解决呢 有建议嘛？谢谢大佬

尝试用 canvas 转换为图片？或者在 svg 外围包裹一下 p 标签看看能不能在左右获取光标？

**Comment by OnePsycho** [comment]
> > > 应该是浏览器的默认行为吧( svg )
> > > 公式的话我们目前已经在研发中了。
> > > 也有在做 卡片机制 的处理。
> > 
> > 
> > 那针对目前这种情况，该如何来解决呢 有建议嘛？谢谢大佬
> 
> 尝试用 canvas 转换为图片？或者在 svg 外围包裹一下 p 标签看看能不能在左右获取光标？

外面包了p标签试过了 包span也试过了 都不能获取光标  而且也办法插入到同一行

**Comment by OnePsycho** [comment]
已自行解决。期待官方早日更新。
