### ISSUE TITLE
编辑器初始化自动聚焦后，首次输入中文，第一个字母被截断

### ISSUE THREAD

**Issue by yuanci222** [wangeditor-team/wangEditor#3052]
## bug 描述

初始化编辑器后自动聚焦，此时直接输入中文，第一个字母会被截断
![image](https://user-images.githubusercontent.com/40686137/111609179-0258d900-8815-11eb-859c-98c735affdad.png)

## 你预期的样子是？

正常输入

## 浏览器及版本号

chrome 89.0.4389.90

## wangEditor 版本

4.6.9

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 运行你们提供的 demo
- 刷新页面，直接开始输入中文

**Comment by WangJolin** [comment]
经测试，其他浏览器（Safari、QQ浏览器、Firefox、IE）都不存在此问题，初步判断是 chrome 浏览器的问题。
