### ISSUE TITLE
新版本不支持text-decoration: underline和“多空格”生成下划线

### ISSUE THREAD

**Issue by sycreece** [wangeditor-team/wangEditor#3053]
## bug 描述

v4.6.6+版本（包含v4.6.6）不支持`"text-decoration: underline ;"`和`多空格` 生成下划线；

## 你预期的样子是？

最新版本`支持"text-decoration: underline ;"`和`多空格`生成下划线；保持向下兼容；

## 浏览器及版本号

Chrome 版本 90.0.4430.30（正式版本）beta (x86_64)

## wangEditor 版本

v4.6.9

## 官网能否复现该 bug ？

不能，感觉官网用的不是最新的版本？

## 最小成本的复现步骤

```html
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">下划线bug</span><span style="font-size: 12pt; text-decoration: underline ;">　　　　　　　　</span></p>
```

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/111723142-0d0b8080-889e-11eb-84c7-20ba69bb9b76.png)
没啥毛病呀空格的下划线出来了呀

**Comment by sycreece** [comment]
直接在官网插入代码的形式没有问题，在本地用npm装的最新包，通过 editor.txt.html() 设置后，会复现这个问题。

**Comment by UltramanWeiLai** [comment]
> 直接在官网插入代码的形式没有问题，在本地用npm装的最新包，通过 editor.txt.html() 设置后，会复现这个问题；目前暂时用editor.$textElem.html() 替代，是正常的。

editor.txt.html() 默认情况下我记得是会清除 style 的，你可以设置过滤样式的配置为不过滤再试试看

**Comment by sycreece** [comment]
> > 直接在官网插入代码的形式没有问题，在本地用npm装的最新包，通过 editor.txt.html() 设置后，会复现这个问题；目前暂时用editor.$textElem.html() 替代，是正常的。
> 
> editor.txt.html() 默认情况下我记得是会清除 style 的，你可以设置过滤样式的配置为不过滤再试试看

好的，4.6.6版本以下用editor.txt.html() ，默认不会清除的，后面升级的版本是特意修改的？还是漏掉了什么？

**Comment by sycreece** [comment]
> > 直接在官网插入代码的形式没有问题，在本地用npm装的最新包，通过 editor.txt.html() 设置后，会复现这个问题；目前暂时用editor.$textElem.html() 替代，是正常的。
> 
> editor.txt.html() 默认情况下我记得是会清除 style 的，你可以设置过滤样式的配置为不过滤再试试看

editor.txt.html() 设置的内容，默认没有过滤掉style哦，样式都还是

**Comment by UltramanWeiLai** [comment]
editor.txt.html() 好像会清理掉 空格 如需输入 空格可以使用  editor.txt.html()  代替

**Comment by sycreece** [comment]
> editor.txt.html() 好像会清理掉 空格 如需输入 空格可以使用   代替

额~，可能我没描述清楚，现在的情况是4.6.6以下的版本，“text-decoration: underline ;”和多空格生成下划线是没问题的，4.6.6以上的版本既不支持“text-decoration: underline ;”，也不支持多空格生成下划线。我的猜想是，这是官方特意这么改的，还是bug呢？

**Comment by UltramanWeiLai** [comment]
> > editor.txt.html() 好像会清理掉 空格 如需输入 空格可以使用   代替
> 
> 额~，可能我没描述清楚，现在的情况是4.6.6以下的版本，“text-decoration: underline ;”和多空格生成下划线是没问题的，4.6.6以上的版本既不支持“text-decoration: underline ;”，也不支持多空格生成下划线。我的猜想是，这是官方特意这么改的，还是bug呢？如果是特意这么改的，我就明白了，如果是bug，下个版本会不会修复呢？

我觉你可能需要详细的描述一下你的场景，已经如何操作的，然后得到了什么效果，但是又不符合你的预期？

我实际上去尝试去复现你说的问题(就我理解的)的时候 text-decoration: underline 实际是可以生效的。
多空格生成下划线也是可以的
如果你在尝试使用 editor.txt.html(‘<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">下划线bug</span><span style="font-size: 12pt; text-decoration: underline ;">　　　　　　　　</span></p>’) 去生成带下划线的空格，但是没有出现的话，我可以告诉你，是因为  
![image](https://user-images.githubusercontent.com/23336585/112011572-593b1700-8b63-11eb-973f-4f734554c5f1.png) 空格被清除掉了替换成 &nbsp; 即可

**Comment by sycreece** [comment]
> > > editor.txt.html() 好像会清理掉 空格 如需输入 空格可以使用   代替
> > 
> > 
> > 额~，可能我没描述清楚，现在的情况是4.6.6以下的版本，“text-decoration: underline ;”和多空格生成下划线是没问题的，4.6.6以上的版本既不支持“text-decoration: underline ;”，也不支持多空格生成下划线。我的猜想是，这是官方特意这么改的，还是bug呢？如果是特意这么改的，我就明白了，如果是bug，下个版本会不会修复呢？
> 
> 我觉你可能需要详细的描述一下你的场景，已经如何操作的，然后得到了什么效果，但是又不符合你的预期？
> 
> 我实际上去尝试去复现你说的问题(就我理解的)的时候 text-decoration: underline 实际是可以生效的。
> 多空格生成下划线也是可以的
> 如果你在尝试使用 `editor.txt.html(‘<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">下划线bug</span><span style="font-size: 12pt; text-decoration: underline ;">　　　　　　　　</span></p>’)` 去生成带下划线的空格，但是没有出现的话，我可以告诉你，是因为
> ![image](https://user-images.githubusercontent.com/23336585/112011572-593b1700-8b63-11eb-973f-4f734554c5f1.png) 空格被清除掉了替换成 `&nbsp;` 即可，如果不是我所想的这样，还请详细和明确的表达出你所想表达的内容

好的，我描述一下我的具体使用方法：

使用场景和问题复现步骤：
1、`把word文档转换成一份html代码`（这步是自己用软件转换的）；
2、在页面中引入编辑器（用的是v4.6.9版本），把转换后的html代码用`editor.txt.html()`的方式插入到编辑器中（上面的代码是从`转换的html`中截取的一部分，包括其中的`style`和`多空格`）；
3、在浏览器中预览结果，没有下划线（没有特殊设置过滤的效果）；
4、v4.6.6以前的版本（比如v4.6.5）能够正确显示下划线，不需要把`多空格`替换成`&nbsp;`；以下是实现代码和效果对比（v4.6.5 & v4.6.9）：

**代码如下：**
![代码](https://fr-static.jiazhengye.cn/wangEditor.08a6cbe02a129d58.png)

**v4.6.5版本，预览效果：**
![v4.6.5](https://fr-static.jiazhengye.cn/4.6.5.cc3156945d3f481e.png)

**v4.6.9版本，预览效果：**
![v4.6.9](https://fr-static.jiazhengye.cn/4.6.9.967dcf99709be0b9.png)

**我的问题：**
为什么新旧版本对`editor.txt.html()`的表现不一致，是bug？还是升级之后设计如此？

**预期效果：**
1、`editor.txt.html()`方法在新版本中和旧版本（v4.6.6以下）表现一致，支持`多空格`和`text-decoration: underline`生成下划线；
2、qq群中得到的回复是，暂时用`editor.$textElem.html()`，该方案在v4.6.6+版本中能够解决下划线的问题；

**Comment by UltramanWeiLai** [comment]
> > > > editor.txt.html() 好像会清理掉 空格 如需输入 空格可以使用   代替
> > > 
> > > 
> > > 额~，可能我没描述清楚，现在的情况是4.6.6以下的版本，“text-decoration: underline ;”和多空格生成下划线是没问题的，4.6.6以上的版本既不支持“text-decoration: underline ;”，也不支持多空格生成下划线。我的猜想是，这是官方特意这么改的，还是bug呢？如果是特意这么改的，我就明白了，如果是bug，下个版本会不会修复呢？
> > 
> > 
> > 我觉你可能需要详细的描述一下你的场景，已经如何操作的，然后得到了什么效果，但是又不符合你的预期？
> > 我实际上去尝试去复现你说的问题(就我理解的)的时候 text-decoration: underline 实际是可以生效的。
> > 多空格生成下划线也是可以的
> > 如果你在尝试使用 `editor.txt.html(‘<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">下划线bug</span><span style="font-size: 12pt; text-decoration: underline ;">　　　　　　　　</span></p>’)` 去生成带下划线的空格，但是没有出现的话，我可以告诉你，是因为
> > ![image](https://user-images.githubusercontent.com/23336585/112011572-593b1700-8b63-11eb-973f-4f734554c5f1.png) 空格被清除掉了替换成 `&nbsp;` 即可，如果不是我所想的这样，还请详细和明确的表达出你所想表达的内容
> 
> 好的，我描述一下我的具体使用方法：
> 
> 使用场景和问题复现步骤：
> 1、`把word文档转换成一份html代码`（这步是自己用软件转换的）；
> 2、在页面中引入编辑器（用的是v4.6.9版本），把转换后的html代码用`editor.txt.html()`的方式插入到编辑器中（上面的代码是从`转换的html`中截取的一部分，包括其中的`style`和`多空格`）；
> 3、在浏览器中预览结果，没有下划线（没有特殊设置过滤的效果）；
> 4、v4.6.6以前的版本（比如v4.6.5）能够正确显示下划线，不需要把`多空格`替换成`&nbsp;`；以下是实现代码和效果对比（v4.6.5 & v4.6.9）：
> 
> **代码如下：**
> ![代码](https://camo.githubusercontent.com/bae3dd1163b79ad9d6479f7d06767a4bd02520f6ccd4d4301fcf95248896557d/68747470733a2f2f66722d7374617469632e6a69617a68656e6779652e636e2f77616e67456469746f722e303861366362653032613132396435382e706e67)
> 
> **v4.6.5版本，预览效果：**
> ![v4.6.5](https://camo.githubusercontent.com/174d39c516463c0b1e4d2e359785862e7a9165dcae6bd9fba95fcd7e7fc57c70/68747470733a2f2f66722d7374617469632e6a69617a68656e6779652e636e2f342e362e352e636333313536393435643366343831652e706e67)
> 
> **v4.6.9版本，预览效果：**
> ![v4.6.9](https://camo.githubusercontent.com/6544549659be6f45a7709e3061dbbaea2434f9762e5eed737c3d2570e73402cc/68747470733a2f2f66722d7374617469632e6a69617a68656e6779652e636e2f342e362e392e393637646366393937303962653062392e706e67)
> 
> **我的问题：**
> 为什么新旧版本对`editor.txt.html()`的表现不一致，是bug？还是升级之后设计如此？
> 
> **预期效果：**
> 1、`editor.txt.html()`方法在新版本中和旧版本（v4.6.6以下）表现一致，支持`多空格`和`text-decoration: underline`生成下划线；
> 2、qq群中得到的回复是，暂时用`editor.$textElem.html()`，该方案在v4.6.6+版本中能够解决下划线的问题；

所以实际上的问题就是 v4.6.6+ 版本后对空格进行了过滤，而 v4.6.6 以前没有。
应该是因为修复某个 bug 才增加的这个过滤限制。
有空的话我回去看看提交记录，看看是为什么会过滤空格。
不过目前有曲线救国倒也还好。
那这个问题就这样终结？

**Comment by sycreece** [comment]
> > > > > editor.txt.html() 好像会清理掉 空格 如需输入 空格可以使用   代替
> > > > 
> > > > 
> > > > 额~，可能我没描述清楚，现在的情况是4.6.6以下的版本，“text-decoration: underline ;”和多空格生成下划线是没问题的，4.6.6以上的版本既不支持“text-decoration: underline ;”，也不支持多空格生成下划线。我的猜想是，这是官方特意这么改的，还是bug呢？如果是特意这么改的，我就明白了，如果是bug，下个版本会不会修复呢？
> > > 
> > > 
> > > 我觉你可能需要详细的描述一下你的场景，已经如何操作的，然后得到了什么效果，但是又不符合你的预期？
> > > 我实际上去尝试去复现你说的问题(就我理解的)的时候 text-decoration: underline 实际是可以生效的。
> > > 多空格生成下划线也是可以的
> > > 如果你在尝试使用 `editor.txt.html(‘<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">下划线bug</span><span style="font-size: 12pt; text-decoration: underline ;">　　　　　　　　</span></p>’)` 去生成带下划线的空格，但是没有出现的话，我可以告诉你，是因为
> > > ![image](https://user-images.githubusercontent.com/23336585/112011572-593b1700-8b63-11eb-973f-4f734554c5f1.png) 空格被清除掉了替换成 `&nbsp;` 即可，如果不是我所想的这样，还请详细和明确的表达出你所想表达的内容
> > 
> > 
> > 好的，我描述一下我的具体使用方法：
> > 使用场景和问题复现步骤：
> > 1、`把word文档转换成一份html代码`（这步是自己用软件转换的）；
> > 2、在页面中引入编辑器（用的是v4.6.9版本），把转换后的html代码用`editor.txt.html()`的方式插入到编辑器中（上面的代码是从`转换的html`中截取的一部分，包括其中的`style`和`多空格`）；
> > 3、在浏览器中预览结果，没有下划线（没有特殊设置过滤的效果）；
> > 4、v4.6.6以前的版本（比如v4.6.5）能够正确显示下划线，不需要把`多空格`替换成`&nbsp;`；以下是实现代码和效果对比（v4.6.5 & v4.6.9）：
> > **代码如下：**
> > ![代码](https://camo.githubusercontent.com/bae3dd1163b79ad9d6479f7d06767a4bd02520f6ccd4d4301fcf95248896557d/68747470733a2f2f66722d7374617469632e6a69617a68656e6779652e636e2f77616e67456469746f722e303861366362653032613132396435382e706e67)
> > **v4.6.5版本，预览效果：**
> > ![v4.6.5](https://camo.githubusercontent.com/174d39c516463c0b1e4d2e359785862e7a9165dcae6bd9fba95fcd7e7fc57c70/68747470733a2f2f66722d7374617469632e6a69617a68656e6779652e636e2f342e362e352e636333313536393435643366343831652e706e67)
> > **v4.6.9版本，预览效果：**
> > ![v4.6.9](https://camo.githubusercontent.com/6544549659be6f45a7709e3061dbbaea2434f9762e5eed737c3d2570e73402cc/68747470733a2f2f66722d7374617469632e6a69617a68656e6779652e636e2f342e362e392e393637646366393937303962653062392e706e67)
> > **我的问题：**
> > 为什么新旧版本对`editor.txt.html()`的表现不一致，是bug？还是升级之后设计如此？
> > **预期效果：**
> > 1、`editor.txt.html()`方法在新版本中和旧版本（v4.6.6以下）表现一致，支持`多空格`和`text-decoration: underline`生成下划线；
> > 2、qq群中得到的回复是，暂时用`editor.$textElem.html()`，该方案在v4.6.6+版本中能够解决下划线的问题；
> 
> 所以实际上的问题就是 v4.6.6+ 版本后对空格进行了过滤，而 v4.6.6 以前没有。
> 应该是因为修复某个 bug 才增加的这个过滤限制。
> 有空的话我回去看看提交记录，看看是为什么会过滤空格。
> 不过目前有曲线救国倒也还好。
> 那这个问题就这样终结？

嗯嗯，好的，后续如果有结果，我们再沟通，谢谢~
