### ISSUE TITLE
word 同时复制图片和文字，图片丢失

### ISSUE THREAD

**Issue by aoxiangsky** [wangeditor-team/wangEditor#3057]
## bug 描述

word 同时复制图片和文字，图片丢失,文字样式部分丢失

## 你预期的样子是？

quill.js 官网文字能完好复制过去，但是图片复制只有一个空占位。 希望wangeditor文字能完好复制过去，然后再能补上图片不能复制的缺陷

## 浏览器及版本号

所有

## wangEditor 版本

最新

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一   复制有图片和文字的word
- 步骤二  粘贴
- 步骤三  只有文字没有图片

**Comment by UltramanWeiLai** [comment]
编辑器的话默认是过滤 style 样式的
图片的话目前好像只能单独进行粘贴
注意：如果是 wps 的话，不管过滤不过滤都不会有样式，因为 wps 的样式是通过 style 标签携带的，但是携带 style 标签会导致样式文本出现在编辑区域内，所以目前的处理方式是屏蔽掉了 style 标签的复制

**Comment by rsl140** [comment]
该问题长时间没回复暂且关闭

**Comment by Joyjiangsq** [comment]
遇到了同样的问题，复制word中的单张图片可以，复制word中文字+图片，图片就不显示了
