### ISSUE TITLE
添加菜单时，提示改按钮的功能简述有前缀menus.title

### ISSUE THREAD

**Issue by aoxiangsky** [wangeditor-team/wangEditor#3059]
## bug 描述

添加菜单时，使用 data-title="功能" 提示改按钮的功能简述自动添加前缀menus.title，变成menus.title.功能

## 你预期的样子是？

功能简述只有  data-title="功能"  中的  功能  二字

看源码为

` $tooltipEl.text(editor.i18next.t('menus.title.' + title))`

感觉可能根据自带的languages，然后过滤调了

自行对editor.config.languages.en 进行修改，会提示en不属于类型editor.config.languages

## 浏览器及版本号

所有

## wangEditor 版本

最新
## 官网能否复现该 bug ？

非操作，无法点击复现

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一   添加自定义按钮菜单
- 步骤二  定义 data-title
- 步骤三  功能提示会出现前缀menus.title

**Comment by aoxiangsky** [comment]
languages: typeof langConfig    =>   languages: typeof langConfig.languages  ,  这样子OK？

**Comment by rsl140** [comment]
你开启了多语言，然后多语言里面没有配置你这个新增的对应翻译。可以参考下文档，[多语言配置](https://doc.wangeditor.com/pages/12-%E5%A4%9A%E8%AF%AD%E8%A8%80/)。
假设新增的英文对应名称：
editor.config.languages['en'].wangEditor.menus.title['功能'] = '功能'

**Comment by UltramanWeiLai** [comment]
你需要在原有的 i18next 模板里面添加上对应的信息，否则获取不到自然就会带上 title.xxx.xxx 了

**Comment by aoxiangsky** [comment]
> 你开启了多语言，然后多语言里面没有配置你这个新增的对应翻译。可以参考下文档，[多语言配置](https://doc.wangeditor.com/pages/12-%E5%A4%9A%E8%AF%AD%E8%A8%80/)。
> 假设新增的英文对应名称：
> editor.config.languages['en'].wangEditor.menus.title['功能'] = '功能'

typescript下，类型静态校验会出错，  languages: typeof langConfig    =>   languages: typeof langConfig.languages  ,  这样子OK？

**Comment by rsl140** [comment]
> > 你开启了多语言，然后多语言里面没有配置你这个新增的对应翻译。可以参考下文档，[多语言配置](https://doc.wangeditor.com/pages/12-%E5%A4%9A%E8%AF%AD%E8%A8%80/)。
> > 假设新增的英文对应名称：
> > editor.config.languages['en'].wangEditor.menus.title['功能'] = '功能'
> 
> typescript下，类型静态校验会出错， languages: typeof langConfig => languages: typeof langConfig.languages , 这样子OK？

没听懂你的问题是啥？ 如果还是menus.title的问题 你只需在原有的 i18next 模板里面添加对应名字即可翻译。

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭。
