### ISSUE TITLE
word中复制粘贴的文字和插入位置的文字格式、字体大小不一致

### ISSUE THREAD

**Issue by sycreece** [wangeditor-team/wangEditor#3060]
## bug 描述

*word转成的html代码显示在编辑器中，代码中带有style（e.g. `font-size`），从其他地方复制粘贴文字插入到编辑器中，被插入的文字会被设置一个字号，和已有的文字大小不一致*

## 你预期的样子是？

*复制粘贴的文字和将要插入位置的文字大小保持一致*

## 浏览器及版本号

*Chrome 版本 90.0.4430.30（正式版本）beta (x86_64)*

## wangEditor 版本

*v4.6.9*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

1、安装最新版本；
2、用editor.txt.html()设置以下html代码：
```html
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt;">1、复制粘贴问题</span><span style="font-size: 12pt; text-decoration: underline ;">　　　　　　　　</span><span style="font-size: 12pt;">判断1：①演示文字；②演示文字，演示文字</span><span style="font-size: 12pt; text-decoration: underline ;">　　　</span></p>
```
3、在浏览器编辑器中粘贴已复制的文字，即能复现；

**Comment by UltramanWeiLai** [comment]
你也说了标签上带有 style 样式自然是按照标签上 style 来的呀
编辑器默认 复制粘贴 来的内容是过滤 style 的，请检查是否开启了不过滤的设置。

**Comment by sycreece** [comment]
> 你也说了标签上带有 style 样式自然是按照标签上 style 来的呀
> 编辑器默认 复制粘贴 来的内容是过滤 style 的，请检查是否开启了不过滤的设置。

粘贴过来的文字是不带样式的哈，已有的文字是带有style的；不过滤是没开的。

**Comment by UltramanWeiLai** [comment]
那我就不是很明白你表达的意思了
意思是，你在编辑器中输入了一段文本，并给文本设置了字号 32，然后复制了一段 word 里面的内容，然后再编辑器中粘贴进去，然后粘贴的内容的字号和前面输入的文本的字号不一样？但是我又看到你说用 editor.txt.html

**Comment by sycreece** [comment]
> 那我就不是很明白你表达的意思了
> 意思是，你在编辑器中输入了一段文本，并给文本设置了字号 32，然后复制了一段 word 里面的内容，然后再编辑器中粘贴进去，然后粘贴的内容的字号和前面输入的文本的字号不一样？但是我又看到你说用 editor.txt.html ...
> 还请尽量详细的说明一下你想表达的意思，以及复现的步骤吧。

好的，我描述下使用场景概述：

1、把word文档转换成html代码；
2、用`editor.txt.html()`把转换的html代码插入到编辑器中（v4.6.9版本）；
3、从应用（qq/微信/word/vs code/wangEditor或其他应用）复制一段文字，在浏览器中的编辑器（wangEditor）中粘贴，粘贴的字体样式和插入位置的字体样式不同，表现为大小不一；

**结果**
粘贴的文字和插入地方的文字样式表现不一致

**代码截图**
![代码](https://fr-static.jiazhengye.cn/fontsizecode.553612e41d620437.png)

**浏览器预览截图**
![代码](https://fr-static.jiazhengye.cn/fontsize.ced4ac72429b2e8c.png)

**预期**
在浏览器编辑器中，粘贴的文字和插入地方的文字样式保持一致

**Comment by UltramanWeiLai** [comment]
？？？
我大概知道你说的是什么意思了。
但是粘贴进去的内容是独立的和你在哪里粘贴的没关系，特别是如果不过滤样式的时候，你想想这种情况何谈粘贴内容匹配周围的样式是吧。。。
如果你要处理这种情况，可以自定义粘贴的回调里面写处理方法

**Comment by sycreece** [comment]
> ？？？
> 我大概知道你说的是什么意思了。
> 但是粘贴进去的内容是独立的，和你在哪里粘贴的没关系，特别是如果不过滤样式的时候，你想想这种情况何谈粘贴内容匹配周围的样式是吧。。。
> 如果你要处理这种情况，可以自定义粘贴的回调里面写处理方法

额，好吧，从word转换的html，过滤样式怎么设置呢，我看编辑器配置里没有特殊设置的地方，`editor.txt.html()`默认没有把样式全部过滤掉。

**Comment by UltramanWeiLai** [comment]
> > ？？？
> > 我大概知道你说的是什么意思了。
> > 但是粘贴进去的内容是独立的，和你在哪里粘贴的没关系，特别是如果不过滤样式的时候，你想想这种情况何谈粘贴内容匹配周围的样式是吧。。。
> > 如果你要处理这种情况，可以自定义粘贴的回调里面写处理方法
> 
> 额，好吧，从word转换的html，过滤样式怎么设置呢，我看编辑器配置里没有特殊设置的地方，`editor.txt.html()`默认没有把样式全部过滤掉。

你自己转的话，可能需要自己通过正则去过滤样式。
不过样式过不过滤和你想要的效果没什么实质性的关联吧？
我感觉你这个需求有点不合理，而且估计实现上会有点难度。
清除掉 word 的样式，让其是默认样式，说起来也算是一种曲线救国的方法。

**Comment by sycreece** [comment]
> > > ？？？
> > > 我大概知道你说的是什么意思了。
> > > 但是粘贴进去的内容是独立的，和你在哪里粘贴的没关系，特别是如果不过滤样式的时候，你想想这种情况何谈粘贴内容匹配周围的样式是吧。。。
> > > 如果你要处理这种情况，可以自定义粘贴的回调里面写处理方法
> > 
> > 
> > 额，好吧，从word转换的html，过滤样式怎么设置呢，我看编辑器配置里没有特殊设置的地方，`editor.txt.html()`默认没有把样式全部过滤掉。
> 
> 你自己转的话，可能需要自己通过正则去过滤样式。
> 不过样式过不过滤和你想要的效果没什么实质性的关联吧？
> 我感觉你这个需求有点不合理，而且估计实现上会有点难度。
> 清除掉 word 的样式，让其是默认样式，说起来也算是一种曲线救国的方法。

额，实际的业务场景中，可以设置字体大小、字体和编辑器提供的其他菜单栏功能，如果把word样式清除，比如标题、加粗功能，word转换的html用的标签不是语义化的h1,strong之类，这个就没法针对标题、加粗等功能统一设置样式了吧。
另外，我试了下粘贴的回调处理函数，尝试给粘贴的内容添加新的html标签和class名称，发现最后生成的dom里会过滤掉后添加的html标签和class名称，这是编辑器在底层又做了处理吧，这个能解决吗？

**Comment by sycreece** [comment]
> > > > ？？？
> > > > 我大概知道你说的是什么意思了。
> > > > 但是粘贴进去的内容是独立的，和你在哪里粘贴的没关系，特别是如果不过滤样式的时候，你想想这种情况何谈粘贴内容匹配周围的样式是吧。。。
> > > > 如果你要处理这种情况，可以自定义粘贴的回调里面写处理方法
> > > 
> > > 
> > > 额，好吧，从word转换的html，过滤样式怎么设置呢，我看编辑器配置里没有特殊设置的地方，`editor.txt.html()`默认没有把样式全部过滤掉。
> > 
> > 
> > 你自己转的话，可能需要自己通过正则去过滤样式。
> > 不过样式过不过滤和你想要的效果没什么实质性的关联吧？
> > 我感觉你这个需求有点不合理，而且估计实现上会有点难度。
> > 清除掉 word 的样式，让其是默认样式，说起来也算是一种曲线救国的方法。
> 
> 额，实际的业务场景中，可以设置字体大小、字体和编辑器提供的其他菜单栏功能，如果把word样式清除，比如标题、加粗功能，word转换的html用的标签不是语义化的h1,strong之类，这个就没法针对标题、加粗等功能统一设置样式了吧。
> 另外，我试了下粘贴的回调处理函数，尝试给粘贴的内容添加新的html标签和class名称，发现最后生成的dom里会过滤掉后添加的html标签和class名称，这是编辑器在底层又做了处理吧，这个能解决吗？

**Comment by UltramanWeiLai** [comment]
> > > > ？？？
> > > > 我大概知道你说的是什么意思了。
> > > > 但是粘贴进去的内容是独立的，和你在哪里粘贴的没关系，特别是如果不过滤样式的时候，你想想这种情况何谈粘贴内容匹配周围的样式是吧。。。
> > > > 如果你要处理这种情况，可以自定义粘贴的回调里面写处理方法
> > > 
> > > 
> > > 额，好吧，从word转换的html，过滤样式怎么设置呢，我看编辑器配置里没有特殊设置的地方，`editor.txt.html()`默认没有把样式全部过滤掉。
> > 
> > 
> > 你自己转的话，可能需要自己通过正则去过滤样式。
> > 不过样式过不过滤和你想要的效果没什么实质性的关联吧？
> > 我感觉你这个需求有点不合理，而且估计实现上会有点难度。
> > 清除掉 word 的样式，让其是默认样式，说起来也算是一种曲线救国的方法。
> 
> 额，实际的业务场景中，可以设置字体大小、字体和编辑器提供的其他菜单栏功能，如果把word样式清除，比如标题、加粗功能，word转换的html用的标签不是语义化的h1,strong之类，这个就没法针对标题、加粗等功能统一设置样式了吧。
> 
> 另外，我试了下粘贴的回调处理函数，尝试给粘贴的内容添加新的html标签和class名称，发现最后生成的dom里会过滤掉后添加的html标签和class名称，这是编辑器在底层又做了处理吧，我的想法是，如果能够在粘贴的时候对内容添加标签，我这边就能对内容做二次加工处理了。
> 
> 关闭了编辑器过滤（editor.config.pasteFilterStyle = false;），发现粘贴文字大概率是可以匹配周边文字大小的，用的是v4.6.10，但是偶尔还会出现不匹配的情况，这个有点儿懵。

1. 可以使用 editor.$textElem.html() 来规避 editor.txt.html() 的样式处理。
2. 可能是看粘贴的是纯文本还是带标签的文本吧，纯文本应该就能匹配周围的样式，因为是进入标签内的好像。
