### ISSUE TITLE
从wps中粘贴上之后css没有被过滤掉

### ISSUE THREAD

**Issue by 1365436742** [wangeditor-team/wangEditor#3061]
## bug 描述

*从wps中粘贴上之后css没有被过滤掉，我设置了editor.config.pasteFilterStyle = false;想要保留原有的样式*

##现在的样子
*
![image](https://user-images.githubusercontent.com/51362520/111761542-f9323f80-88da-11eb-9007-18ab811ad870.png)
*

## 你预期的样子是？

*
![image](https://user-images.githubusercontent.com/51362520/111761687-21ba3980-88db-11eb-91bb-be9bd1555875.png)
*

## wangEditor 版本

*4.6.10*

## 个人目前解决办法加了正则

editor.config.pasteTextHandle = function (pasteStr) {
      // 对粘贴的文本进行处理，然后返回处理后的结果
      var newStr = pasteStr.replace(
        /@font-face{[^>]*div.Section0{page:Section0;}/g,
        ""
      );
      return newStr;
};

**Comment by UltramanWeiLai** [comment]
请问官网是否能复现该问题？

**Comment by xiaokyo** [comment]
此问题在 [#2885](https://github.com/wangeditor-team/wangEditor/issues/2885)
已经一并解决了，现在是待发布状态，大概是每周四会进行发布，具体时间按照正常发布时间为准

**Comment by 1365436742** [comment]
好的辛苦



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月24日(星期三) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 从wps中粘贴上之后css没有被过滤掉 (#3061)





 
此问题在 #2885
 已经一并解决了，现在是待发布状态，大概是每周四会进行发布，具体时间按照正常发布时间为准
