### ISSUE TITLE
建议增加校验用户html的机制

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/wangEditor#3064]
## bug 描述

建议增加校验用户html的机制

## 你预期的样子是？

详情见 语雀 技术文档 
https://www.yuque.com/wangeditor/mf8eum/vcn8s3

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by lemos1235** [comment]
页面无法访问呀

**Comment by wangfupeng1988** [comment]
> 页面无法访问呀

楼主是研发团队的人，文档是我们团队内部文档，所以其他人无法访问。
其实文档也不是啥新功能，都是一些细碎的优化，比较细节。

**Comment by lichenabson** [comment]
经过开发实现, 无法覆盖到 所有的用户输入场景, 且依赖于这种校验机制也不可靠, 所以关闭此issue
