### ISSUE TITLE
关于插入dom，写入的文字都在新增的dom内

### ISSUE THREAD

**Issue by pro-xiaoy** [wangeditor-team/wangEditor#3070]
## 问题描述
关于插入dom写入的文字都在新增的dom内

## wangEditor 版本

^4.6.8

## 是否查阅了文档 ？
*是*

## 最小成本的复现步骤
js操作文本
```js
    const inserHtml = '<span style=\"color: red\">' + dataInsert + '</span>'
    editor.cmd['do']('insertHTML', inserHtml)
```
富文本内写入的文字都变成红色
## 解决
可以贴出关于原生的导入链接(插入a链接)之后做了哪些操作

**Comment by rsl140** [comment]
不太明白什么叫写入的文字都在新增的dom内

**Comment by pro-xiaoy** [comment]
> 不太明白什么叫写入的文字都在新增的dom内



> 不太明白什么叫写入的文字都在新增的dom内

你好，我直接贴代码演示吧:
```js
 const inserHtml = '<span style=\"color: red\">' + dataInsert + '</span>'
    editor.cmd['do']('insertHTML', inserHtml)
```
你解下来输入的文字全部都是红色，看控制台，文本都写在span标签里面。

看了下，插入链接本质是innerHTML一个A标签，但是在他后面写的文字和A标签是独立的

**Comment by wangfupeng1988** [comment]
@pro-xiaoy 你说的这种情况是正常的，就例如，你选中了一整行，设置了红色，然后再继续在这一行输入，也还是红色的，这符合预期。

PS：你的说“A标签”我一直搞懂是啥意思。

**Comment by pro-xiaoy** [comment]
@wangfupeng1988 先解释下A标签，菜单上不是有个插入链接，插入的文本是高亮，你接着**链接文本**写的话字体又回到默认状态，你会发现链接的文本是通过a标签包住的，仿佛整个这个链接文本对于富文本来说，是独立。

我说的插入问题想了下，强行改了下源码，模拟插入链接的方法，增加attr属性来判断。

**Comment by rong12345** [comment]
> @ wangfupeng1988先解释下一个标签，菜单上不是有个插入链接，插入的文本是高亮，你接着**链接文本**写的话字体又回到交替状态，你会发现链接的文本是通过a标签包住的，仿佛整个这个链接文本对于富文本来说，是独立。
> 
> 我说的插入问题想了下，强行改了下源码，模拟插入链接的方法，增加了attr属性来判断。
同样的问题 如何解决的啊  我也是插入了一个带有颜色的标签内容 之后输入文字都是带颜色的

**Comment by rsl140** [comment]
可以尝试editor.cmd['do']('insertHTML', '<p style=\"color: red\">' + dataInsert + '</p>')
新起一行时会恢复默认色。

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复暂且关闭
