### ISSUE TITLE
1、建议增加颜色选择 ，颜色值太少

### ISSUE THREAD

**Issue by Denglee** [wangeditor-team/wangEditor#3071]
## 功能描述
1、建议增加颜色选择 ，颜色值太少
2、当前编辑选了颜色和字体，怎么取消选中的颜色和背景色。换行也会把颜色带过来
*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by rsl140** [comment]
1.关于颜色可以自己定义[配置颜色](https://doc.wangeditor.com/pages/03-%E9%85%8D%E7%BD%AE%E8%8F%9C%E5%8D%95/02-%E9%85%8D%E7%BD%AE%E9%A2%9C%E8%89%B2.html)
2. 取消颜色的话 可以将文字颜色设为黑色

**Comment by rsl140** [comment]
该问题长时间没回复暂且关闭
