### ISSUE TITLE
如何提取富文本编辑器的css样式（作为邮件内容的时候，邮件内容和编辑的时候不一致）

### ISSUE THREAD

**Issue by jocklei** [wangeditor-team/wangEditor#3073]
## 问题描述

*wangEdit团队，非常感谢你们的贡献，现在我们有一需求，就是给订阅我们的客户发送推送文章，在我们的后台系统使用的是wangEdit作为推送文章的编辑器，编辑完成后邮件发送到客户邮箱后，客户打开发现和编辑时的样式不一致，排查发现，没有加载wangEdit富文本编辑器的样式，发送邮件服务不能添加wangEdit js包，给拦截了。研究发现，不能加载js脚本包，可以添加css包，只要在发送的邮件中添加css包，应该就能解决问题，现在想问一下有没有接口提取wangEdit编辑器的css呢？？*

## wangEditor 版本

*最新版*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

**Comment by UltramanWeiLai** [comment]
emmmm 实际上 wangEditor 本身并没有对编辑区域的内容做样式限定，表格 和 code 除外，但是也只需要简单的定制样式即可。
1. 可以先看看你们项目自身的全局样式是否对标签样式做了 reset
2. 你可以现在页面中进行回显内容，看样式是否有区别
3. 或者可以尝试自定义样式，类是与定制皮肤一样？

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
