### ISSUE TITLE
使用editor.cmd["do"]('insertHTML',xxx) 插入不到同一行  只有部分元素插入到了 其余都是新的一行 

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3074]
## 问题描述

使用editor.cmd["do"]('insertHTML',xxx) 插入不到同一行  只有部分元素插入到了 其余都是新的一行 详情可以看截图

## wangEditor 版本
4.0

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

看截图，就是想要插入后是在同一行

![de6662b8d37ba6b8d7751ce96516ac3](https://user-images.githubusercontent.com/43296632/111977826-29c5e380-8b3e-11eb-9616-18f7a8ddbeed.png)

![image](https://user-images.githubusercontent.com/43296632/111977900-4530ee80-8b3e-11eb-905a-20e99627a3a2.png)

**Comment by OnePsycho** [comment]
可以看到第一个 class为space的 span标签进入了第一行  后面的就都没进去 导致到了下一行  display都设置为 行内元素的

**Comment by UltramanWeiLai** [comment]
insertHTML 是浏览器的行为，我们目前也没有太好的办法。
或者你要不要尝试使用获取选区通过节点进行 dom 操作来插入？

**Comment by OnePsycho** [comment]
我比较奇怪的是 其他的元素 比如图片 公式svg这些 用相同的方法是可以插入到同一行的  但是我截图上插入的这段富文本却不行

**Comment by OnePsycho** [comment]
> insertHTML 是浏览器的行为，我们目前也没有太好的办法。
> 或者你要不要尝试使用获取选区通过节点进行 dom 操作来插入？

您说的这个获取选取通过节点进行dom操作 具体指的是什么意思呢

**Comment by OnePsycho** [comment]
明白了 已通过 这种方式解决、
![b02e411df4243cce1abd3a0bed7bcea](https://user-images.githubusercontent.com/43296632/112080483-0ee68400-8bbd-11eb-8b4b-0f38316d28fa.png)

**Comment by UltramanWeiLai** [comment]
> 明白了 已通过 这种方式解决、
> ![b02e411df4243cce1abd3a0bed7bcea](https://user-images.githubusercontent.com/43296632/112080483-0ee68400-8bbd-11eb-8b4b-0f38316d28fa.png)

ok 那么该问题我就关闭了，内部还有获取当前所有被选段落的 api 就在 selection 里面，如果有拖蓝情况需要处理的话，也可以考虑使用它
