### ISSUE TITLE
在vue中富文本初始化时，设置了`editor.config.focus = false`  `editor.config.onfocus`事件依旧会被触发一次

### ISSUE THREAD

**Issue by yunshu1996** [wangeditor-team/wangEditor#3075]
## bug 描述

在vue中富文本初始化时，设置了`editor.config.focus = false`

`editor.config.onfocus`事件依旧会被触发一次

## 你预期的样子是？
设置`editor.config.focus = false`之后不会触发`editor.config.onfocus`

## 浏览器及版本号

chrome 89.0.4389.90

## wangEditor 版本

4.6.9

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

初始化编辑器的时候设置`editor.config.focus = false`
然后注册onfocus事件
```
editor.config.onfocus = (newHtml) => {
      console.log('focus')
    };
```
bug为偶发性，有时候会触发onfocus事件，有时候不会触发事件
----------------------补充一下后续---------------------
问题的具体场景是通过v-for在一个页面循环出多个富文本编辑器时，会依次触发onfocus事件
此时最后一个富文本编辑器是onfocus状态，但它的编辑区域内并没有光标，
且此时点击另一个富文本编辑器的编辑区域，被点击的富文本编辑器并不会获得焦点，焦点依旧停留在之前的富文本编辑器上
再继续点击第二次，焦点才会转移到被点击的富文本编辑器上
目前的解决方案是在初始化完成之后，用js触发一次body的click事件来强制使所有富文本编辑器失去焦点
`document.querySelector("body").click();`

**Comment by UltramanWeiLai** [comment]
你是如何去循环生成富文本编辑器的？
我配置的失焦后，怎么刷都没有 onfocus 触发
