### ISSUE TITLE
内容回显时，光标问题

### ISSUE THREAD

**Issue by bifhxzf** [wangeditor-team/wangEditor#3077]
## 问题描述

*如果代码块是最后内容，回显时光标在代码块里。此时回车无法正常新起一行(新起一非代码块行)。需要连续摁两次向下键才可以新起一非代码块行*

## wangEditor 版本

*4.6.10*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 存储代码块
- 回显代码块
- 光标默认在代码最后一行，此时新启动一代码块行

**Comment by UltramanWeiLai** [comment]
感觉没啥问题
光标在代码块内，按回车自然是针对代码块内的操作。
光标在代码块外，回车自然是新起一行。
如果你想光标默认在代码块最后，在回显的时候在字符串后面加个 `<p>&nbsp;</p>` 就可以了

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
