### ISSUE TITLE
使用backspace删除键无法删除内容，需要选中delete键才能删除

### ISSUE THREAD

**Issue by oneMeterSunshine-y** [wangeditor-team/wangEditor#3078]
## 问题描述

使用backspace删除键无法删除内容，需要选中delete键才能删除

## wangEditor 版本

v4 版本，用的cdn引入 https://cdn.jsdelivr.net/npm/wangeditor@latest/dist/wangEditor.min.js

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

jq写的代码，谷歌最新浏览器 89.0.4389.90。就cdn引入，按照文档create初始化富文本，然后输入文本就无法删除，未做其他操作

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
并未复现该问题，可否提供具体的复现步骤以及场景。

**Comment by oneMeterSunshine-y** [comment]
![微信图片_20210324095835](https://user-images.githubusercontent.com/49930653/112242877-91d41100-8c87-11eb-8604-af13f9f07fb5.png)

按文档引入。
场景应该是用的 shtml 内嵌网页, ES5的规范

**Comment by UltramanWeiLai** [comment]
> ![微信图片_20210324095835](https://user-images.githubusercontent.com/49930653/112242877-91d41100-8c87-11eb-8604-af13f9f07fb5.png)
> 
> 按文档引入。
> 场景应该是用的 shtml 内嵌网页, ES5的规范

建议先简单的整个 html 文件，在里面创建一个编辑器，是否还会出现该问题。

**Comment by btea** [comment]
在编辑器中创建一个table，然后使用backspace键无法删除内容。（官网可复现）
（版本 89.0.4389.90（正式版本） （64 位））

**Comment by UltramanWeiLai** [comment]
> 在编辑器中创建一个table，然后使用backspace键无法删除内容。（官网可复现）
> （版本 89.0.4389.90（正式版本） （64 位））

表格后面有个 p 标签是无法删除的，主要是为了末尾内容是表格的时候，你无法往后面添加内容，你把光标插入表格那一个段落的后面再用 backspace 就可以删除表格，而且也不影响其他文本的删除，表格本身也有 tooltip 里面的删除按钮

**Comment by btea** [comment]
> > 在编辑器中创建一个table，然后使用backspace键无法删除内容。（官网可复现）
> > （版本 89.0.4389.90（正式版本） （64 位））
> 
> 表格后面有个 p 标签是无法删除的，主要是为了末尾内容是表格的时候，你无法往后面添加内容，你把光标插入表格那一个段落的后面再用 backspace 就可以删除表格，而且也不影响其他文本的删除，表格本身也有 tooltip 里面的删除按钮

好的，了解了。

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
