### ISSUE TITLE
复制粘贴图片造成页面卡死

### ISSUE THREAD

**Issue by ycx0317** [wangeditor-team/wangEditor#3080]
## bug 描述

将图片设置成支持base64，在编辑器中复制图片，在同一个或不同编辑器中粘贴，造成页面卡死

## 你预期的样子是？

可以正常复制粘贴编辑器中已有的图片

## 浏览器及版本号

chrome 89

## wangEditor 版本

4.6.10

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 打开官网上传图片的demo
- 在coding中将图片设置成支持base64
- 在编辑器中粘贴或上传图片
- 复制上一步中的图片
- 在编辑器中执行粘贴操作，页面卡死

**Comment by rsl140** [comment]
该问题已经收录，可以移步到 #3029 中去跟进
