### ISSUE TITLE
npm 安装时提示高危漏洞并且无法修复

### ISSUE THREAD

**Issue by xiaomaolver** [wangeditor-team/wangEditor#3082]
## 问题描述
安装时提示报错复现有截图，实际node_models 里面已经有包，但是还是提示高危漏洞并且无法修复，重新删除整个node_models 再安装也不行，其他引入的包都可以用，唯独wangEditor不行

## wangEditor 版本
最新版安装

## 是否查阅了文档 ？
是，文档没有相关解答

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/47557223/112254759-13ce3500-8c9c-11eb-9b94-de66f13c3d3b.png)

**Comment by wangfupeng1988** [comment]
感谢你的反馈。

目前确实有 npm audit 的提示，详情参考 https://www.npmjs.com/advisories/876
它提示的是 Cross-Site Scripting ，即跨站的脚本攻击，就是有可能存在 XSS 的风险。
关于这一点，我们文档中也写了，如何防止 xss 攻击，参考[这里](https://doc.wangeditor.com/pages/13-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/02-xss%E6%94%BB%E5%87%BB.html)

只要你自己做好了 xss 攻击的预防，便可放心使用 wangEditor 。

**Comment by xiaomaolver** [comment]
@wangfupeng1988 好的，感谢老板
