### ISSUE TITLE
在ie11浏览器中，上传图片没能成功，后续导致浏览器崩溃，使得浏览器重新刷新页面。

### ISSUE THREAD

**Issue by moStartIn2019** [wangeditor-team/wangEditor#3083]
## bug 描述

在ie11浏览器中，上传图片没能成功，后续导致浏览器崩溃，使得浏览器重新刷新页面。
ps：谷歌浏览器 89.0.4389.90 (正式版本)没有出现该问题。

出现问题的gif图如下所示：
![bug](https://user-images.githubusercontent.com/50790154/112262641-f5bb0180-8ca8-11eb-886e-b5c4f9373a87.gif)

## 你预期的样子是？

图片能正常上传，不会导致浏览器崩溃

## 浏览器及版本号

浏览器：ie11
版本号如下图所示：
![1616560829(1)](https://user-images.githubusercontent.com/50790154/112261562-197d4800-8ca7-11eb-82df-930ab6ff4317.jpg)

## wangEditor 版本

 4.6.9

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 打开windows系统自带的ie11浏览器，输入官网：https://www.wangeditor.com/
- 步骤二 选择图片上传按钮并点击，选中任一一张照片上传

**Comment by rsl140** [comment]
未复现该问题。

**Comment by moStartIn2019** [comment]
请问确定是在ie11上操作上传图片而非edge？

**Comment by moStartIn2019** [comment]
> 未复现该问题。
请问确定是在ie11上操作上传图片而非edge？

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/112412850-260ea880-8d5a-11eb-9b13-e48171f5492d.png)

**Comment by moStartIn2019** [comment]
> 未复现该问题。
好吧，我目前回退到原来没升级之前的4.6.2就没出现这个问题，还是谢谢你！
