### ISSUE TITLE
表格是否可以增加合并单元格功能

### ISSUE THREAD

**Issue by 498755303** [wangeditor-team/wangEditor#3086]
## 功能描述

希望表格可以增加一个合并单元格功能,目前表头和表格中无法合并单元格

## 提炼几个功能点

- 表头合并单元格
- 表格合并单元格

## 可参考的案例

参见ueEditor，目前可以直接粘贴进去 ,但是不支持按钮方式合并单元格

**Comment by baikefun** [comment]
这个功能确实很需要

**Comment by xiexihai** [comment]
请问这个功能开发好了么？最近也需要这个功能

**Comment by wangfupeng1988** [comment]
我早就记录下这个问题了。

不过，这个功能非常麻烦，暂时做不了。
以后会在 v5 中开发，得待 v5 发布后再安排，不是近期。

**Comment by yuanjinxiugithub** [comment]
这个功能啥时候可以上呀？ @wangfupeng1988

**Comment by wangfupeng1988** [comment]
@yuanjinxiugithub 不确定，这个功能还是挺麻烦的

**Comment by cycleccc** [comment]
已在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 实现
https://github.com/cycleccc/wangEditor-next/issues/24
