### ISSUE TITLE
image 图片不支持打开本地文件夹选择图片吗？

### ISSUE THREAD

**Issue by Agaoquan** [wangeditor-team/wangEditor#3089]
## 问题描述

*请输入遇到的问题...*
目前选择图片上传地址感觉太繁琐，希望能直接打开本地文件夹，选择图片上传。
## wangEditor 版本

*请输入内容……*
![image](https://user-images.githubusercontent.com/19632534/112415961-c0bdb600-8d5f-11eb-958a-1b178a4a2246.png)

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by moStartIn2019** [comment]
this.editor.config.showLinkImg = false 就行了，不过会引发一个bug，上传后无法重复上传同一张图片，这个有问题记录的

**Comment by rsl140** [comment]
[隐藏插入网络图片的功能](https://doc.wangeditor.com/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/13-%E9%9A%90%E8%97%8F%E6%8F%92%E5%85%A5%E7%BD%91%E7%BB%9C%E5%9B%BE%E7%89%87%E7%9A%84%E5%8A%9F%E8%83%BD.html)
