### ISSUE TITLE
4.6.11更新后显示不正常

### ISSUE THREAD

**Issue by baekilda** [wangeditor-team/wangEditor#3092]
## bug 描述

如题，更新至4.6.11后显示不正常，官网可见

## 你预期的样子是？

编辑器正常显示

## 浏览器及版本号

试过的浏览器：

macOS:
Chrome  89.0.4389.82(arm64) 不正常
Safari 14.1 (16611.1.21.1.12) 不正常
Edge 89.0.774.57 不正常

Windows:
Edge 89.0.774.45 不正常

iOS 14:
Safari 不正常
crios: 不正常

## wangEditor 版本

4.6.11

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

打开官网即可见

<img width="1308" alt="截屏2021-03-26 上午4 41 19" src="https://user-images.githubusercontent.com/67785358/112533664-87cc2280-8ded-11eb-9195-48946a2af30c.png">

**Comment by rsl140** [comment]
目前已修复，感谢反馈~
