### ISSUE TITLE
增加去除格式功能按钮

### ISSUE THREAD

**Issue by diction** [wangeditor-team/wangEditor#3093]
## 功能描述

用于去除选中文本的样式。

**Comment by rsl140** [comment]
如果说的是格式刷功能的话可以移步到#2528跟进，该功能已被收录

**Comment by diction** [comment]
不是格式刷，是将选中的文本现有的格式，如：加粗，颜色，引用等格式都删除，成为最基本的文本。

**Comment by diction** [comment]
对，是#2528中的第一个功能要求。
