### ISSUE TITLE
b标签前的空格被删除了（我看有好多关于空格的bug和PR）

### ISSUE THREAD

**Issue by uniquejava** [wangeditor-team/wangEditor#3094]
## bug 描述
 `Hello, my name is cyper`.  双击选中单词`is`, 点击`B图标`加粗`is`。 保存到后台。

观察db中的文字内容为 `<p>Hello, my name <b>is</b> cyper`

![image](https://user-images.githubusercontent.com/1049271/112595118-eec8f600-8e44-11eb-95c0-bb2b6522dfa9.png)

然后进入编辑页面，使用函数 `editor.txt.html(....)`初始化编辑器， 发现name前的空格没有了。name 和 is挨在了一起

![image](https://user-images.githubusercontent.com/1049271/112595156-fa1c2180-8e44-11eb-8aa4-ca9303acf157.png)

## 你预期的样子是？

name和is之间有一个空格

## 浏览器及版本号

chrome最新版

## wangEditor 版本

  "wangeditor": "^4.6.12"

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

 `Hello, my name is cyper`.  双击选中单词`is`, 点击`B图标`加粗`is`。 保存到后台。

观察db中的文字内容为 `<p>Hello, my name <b>is</b> cyper`

然后进入编辑页面，使用函数 `editor.txt.html(....)`初始化编辑器， 发现name前的空格没有了。name 和 is挨在了一起

**Comment by rsl140** [comment]
可以暂时先用editor.$textElem.html代替。
