### ISSUE TITLE
鼠标选中一段文字，光标点击中间，插入图片，选中的文字消失了，而不是插入到光标处

### ISSUE THREAD

**Issue by mybells** [wangeditor-team/wangEditor#3096]
## bug 描述

鼠标选中一段文字，光标点击中间，插入图片，选中的文字消失了，而不是插入到光标处

## 你预期的样子是？

上传的图片插入到光标处

## 浏览器及版本号

Chrome 版本 89.0.4389.90（正式版本） (x86_64)

## wangEditor 版本

4.6.12

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 鼠标选中一段文字
- 鼠标点击选中的文字中间
- 上传图片
- 之前选中的文字替换成了图片，而不是图片插入到光标处

**Comment by mybells** [comment]
getSelection时机不对，加个settimeout

**Comment by liuqh0609** [comment]
交叉测试： @qianfengg
