### ISSUE TITLE
document.execCommand 已经废弃了

### ISSUE THREAD

**Issue by SmartWuJun** [wangeditor-team/wangEditor#3098]
## document.execCommand API 已经废弃了 是否有替代方案

如果浏览器不支持document.execCommand 功能了怎么办

**Comment by UltramanWeiLai** [comment]
首先，请按照模板进行 issue 的提交，否则是不受理的。
其次，document.execCommand API 不在规范中，且被标记为废弃了，这我们肯定是知道的。
最后，我们也一直在有自研 execCommand API 方面去进行调研的小伙伴
