### ISSUE TITLE
建议菜单没有配置“image”的时候，点击编辑器里面的图片可以显示tooltip，改变图片的宽度

### ISSUE THREAD

**Issue by ChuangShiOS** [wangeditor-team/wangEditor#3100]
## 功能描述

当我们自定义实现图片插入的时候，点击编辑器里面的图片没有显示tooltip，现在只有菜单配置了“image”才会出现tooltip，才能设置图片的百分比宽度和拖拽修改宽度

**Comment by rsl140** [comment]
你好，有详细的复现步骤么

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
