### ISSUE TITLE
初始时将isFouce设置为false，回车会报错；

### ISSUE THREAD

**Issue by baozi-wei** [wangeditor-team/wangEditor#3102]
![image](https://user-images.githubusercontent.com/40175584/112784898-54a3c080-9085-11eb-9dd3-28b3c0823dd1.png)

**Comment by baozi-wei** [comment]
需求：
别处有一些模板变量，点击这个模板变量时，如果文本框未获取光标时，在富文本框开始的地方一行一行的插入；获取到光标后在光标处插入文本 
目前的做法是: 
![image](https://user-images.githubusercontent.com/40175584/112785177-f5927b80-9085-11eb-98ab-7252e8523378.png)
问题：
回车的时候光标和插入地不一致

**Comment by rsl140** [comment]
1. 请按 issue 模板格式提交,否则我们是不会受理的。
2. 复现步骤或环境尽量简单，便于我们复现问题。
