### ISSUE TITLE
当文本框已经有些值，然后插入图片，选中图片，然后插入链接页面完全卡死也不报错

### ISSUE THREAD

**Issue by baozi-wei** [wangeditor-team/wangEditor#3103]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
复现步骤？ 我们如何能复现该问题？

**Comment by longFeiLi** [comment]
bug 描述
当给编辑器里面的图片添加链接的时候，会造成页面卡死现象。

你预期的样子是？
能正常添加链接，用户可以通过编辑器内容，点击图片进行跳转

浏览器及版本号
版本 89.0.4389.90（正式版本） (arm64)
win系统 谷歌浏览器一样

wangEditor 版本
最新版本

官网能否复现该 bug ？
能

![image](https://user-images.githubusercontent.com/10267141/112924371-9181bd00-9142-11eb-9706-cb7fe649b2fe.png)


点击插入之后就会卡死...

**Comment by baozi-wei** [comment]
在插入链接的事件里，拦截一下含img的情况
![image](https://user-images.githubusercontent.com/40175584/112951506-00284000-916e-11eb-9d2c-102ac2c0c496.png)

**Comment by baozi-wei** [comment]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `wangeditor@4.6.12` for the project I'm working on.



Here is the diff that solved my problem:

```diff
diff --git a/node_modules/wangeditor/src/menus/link/create-panel-conf.ts b/node_modules/wangeditor/src/menus/link/create-panel-conf.ts
index caf2191..ecfc3b9 100644
--- a/node_modules/wangeditor/src/menus/link/create-panel-conf.ts
+++ b/node_modules/wangeditor/src/menus/link/create-panel-conf.ts
@@ -139,8 +139,14 @@ export default function (editor: Editor, text: string, link: string): PanelConf
                             let text = $text.val().trim()
 
                             let html: string = ''
-                            if (selection && !selection?.isCollapsed)
+                            if (selection && !selection?.isCollapsed) {
+                              const imgReg = /<img.*?(?:>|\/>)/gi;
+                              if (imgReg.test(selection.anchorNode?.outerHTML)) {
+                                html = selection.anchorNode?.innerHTML
+                              }else{
                                 html = insertHtml(selection, topNode)?.trim()
+                              }
+                            }
 
                             // 去除html的tag标签
                             let htmlText = html?.replace(/<.*?>/g, '')
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by rsl140** [comment]
该问题已复现 可以到 #3113 跟进
