### ISSUE TITLE
编辑文字标题问题

### ISSUE THREAD

**Issue by puzhixin** [wangeditor-team/wangEditor#3107]
## bug 描述

*先写一行设置为标题1，回车将这行放在第二行，光标再回到第一行不动，按Del键，第二行的标题一自动跳到第一行，但是字体大小变成了2em，你们的例子里都有这个问题，期待能修复下*

## 你预期的样子是？

*期待的样子就是和官网文档例子一样*

## 浏览器及版本号

*谷歌浏览器，目前最新版*

## wangEditor 版本

*wangEditor4 也是安装的最新版，前段时间安装的*

## 官网能否复现该 bug ？

官网：不能
官网的案例展示里面有这个问题

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 先在第一行输入一行字，设置为标题1
- 将这行文字回车放到第二行
- 光标再回到第一行，然后按下Del键删除第一行，当第二行文字自动回到第一行的时候，标题一的字体从原来的1em变成了2em,
- 这时候这行的标题12345以及正文，字体都变大了

**Comment by rsl140** [comment]
@clinfc 交叉测试
