### ISSUE TITLE
表格大小

### ISSUE THREAD

**Issue by puzhixin** [wangeditor-team/wangEditor#3109]
## 功能描述

*介意表格可以自定义大小缩放，*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by rsl140** [comment]
目前暂时还没法直接做，不过 wangEditor 正在规划卡片机制，待卡片机制搞定之后，表格会做一次重构，到时会支持所有常见功能。（完成时间还无法确定，可能会比较久）
