### ISSUE TITLE
从QQ中复制文本粘贴为空（win10可复现）

### ISSUE THREAD

**Issue by mlshan** [wangeditor-team/wangEditor#3111]
## bug 描述
从qq中复制文本然后粘贴到编辑器中，显示为空，只有相应的<br>标签

## 你预期的样子是？

显示复制的文本，并按预期的段落展示

## 浏览器及版本号

谷歌浏览器，版本 87.0.4280.141（正式版本） （64 位）

## wangEditor 版本

"wangeditor": "^4.6.12"

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
从qq复制文本并粘贴

**Comment by rsl140** [comment]
按步骤，并未复现该问题。

**Comment by mlshan** [comment]
从qq的聊天框中复制文本，然后粘贴编辑器内，显示就为空




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 从QQ中复制文本粘贴为空 (#3111)





 
按步骤，并未复现该问题。

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/112964831-40da8600-917b-11eb-8c1c-3d0260ea694a.png)

**Comment by mlshan** [comment]
已经发送的文本



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 从QQ中复制文本粘贴为空 (#3111)

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/112966643-01149e00-917d-11eb-9a33-15399fd75da0.png)

**Comment by mlshan** [comment]
你这个是苹果机，可否用Windows测试一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 从QQ中复制文本粘贴为空 (#3111)

**Comment by mlshan** [comment]
在大群里，其他用户也测试了 ，确实不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 从QQ中复制文本粘贴为空 (#3111)
