### ISSUE TITLE
为图片添加链接，页面会卡死

### ISSUE THREAD

**Issue by rsl140** [wangeditor-team/wangEditor#3113]
## bug 描述

为图片添加链接，页面会卡死

## 你预期的样子是？

页面不会卡死

## 浏览器及版本号

谷歌最新版

## wangEditor 版本

v4.6.12

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 点击选中编辑器内的一张图片
- 步骤二 点击链接按钮输入地址
- 步骤三 点击插入

**Comment by baozi-wei** [comment]
![image](https://user-images.githubusercontent.com/40175584/112964424-e6d9c080-917a-11eb-9a11-64214f28bb1f.png)

**Comment by UltramanWeiLai** [comment]
备注：该问题仅 Mac 可以复现

**Comment by baozi-wei** [comment]
> 备注：该问题仅 Mac 可以复现

不是的，win也有
