### ISSUE TITLE
css var 在插入图片时导致样式被继承

### ISSUE THREAD

**Issue by shi-lai-mu** [wangeditor-team/wangEditor#3114]
## bug 描述

*当使用cmd.do插入图片时，图片的style会不正确的继承父级，这会导致在存入数据库时增加大量的样式数据和后期渲染时不可控的样式。并且在cmd.do第一次插入时图片的style是正确的是预期的，但在之后插入的图片会产生继承例如 背景颜色、文字颜色、字体大小等*

## 你预期的样子是？

*和第一次cmd.do插入图片时一样，我的场景中有网站主题色，主要是用css的var来改变编辑器颜色，然后就发现了这个bug*

## 浏览器及版本号

*Chrome/89.0.4389.90*

## wangEditor 版本

*4.6.12*

## 官网能否复现该 bug ？

能（官网给的codepen中复现）

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
  

![T %MV_JE%5MQQCY_WBQZ@ C](https://user-images.githubusercontent.com/45140991/113027802-127d9a80-91bd-11eb-9982-91feb6225568.png)
- 左边对应cmd.do，插入图片及设定了一个预期的样式
- 给div1或者.w-e-text-container设置样式，经测试样式需要用css变量var才会被触发继承，而字体大小只要是父级设定了都会被继承到图片中，图片用到fontsize这似乎不是很正常

![image](https://user-images.githubusercontent.com/45140991/113027751-0560ab80-91bd-11eb-87f0-2dc8a3f9d637.png)

- 点击触发cmd.do，插入图片后右键检查图片会发现除了第一个插入的，后面的都继承了样式

**Comment by wangfupeng1988** [comment]
你插入图片的时候，这个 style 变量，值是什么？
![image](https://user-images.githubusercontent.com/9583120/113236850-48fc0800-92d8-11eb-9b5d-6cbcf941f7e6.png)

另外，我理解你提的是两个问题。
第一，使用了 css var ，第二次插入图片，会产生很多非预期的 style ，如 background-color 和 color
第二，插入图片时，会继承上级节点的 font-size: 1em 。

是这样吗？

**Comment by shi-lai-mu** [comment]
> 我理解你提的是两个问题。
> 第一，使用了css var，第二次插入图片，会产生很多非预期的风格，如background-color和color
> 第二，插入图片时，会继承上一级例程的font-size：1em。
> 
> 是这样吗？

是的，但第二个问题font-size继承的非上一级，而是父级即包括body和html，且这里是我实际操作时遇到的img+几个风格问题，其他标签和样式是否也存在该问题可能需要测试一下。

**Comment by shi-lai-mu** [comment]
他的值在上方定义了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] css var 在插入图片时导致样式被继承 (#3114)





 
你插入图片的时候，这个 style 变量，值是什么？
 
 
另外，我理解你提的是两个问题。
 第一，使用了 css var ，第二次插入图片，会产生很多非预期的 style ，如 background-color 和 color
 第二，插入图片时，会继承上级节点的 font-size: 1em 。
 
是这样吗？

**Comment by wangfupeng1988** [comment]
好的，我们先受理排查一下吧。
