### ISSUE TITLE
video无法像图片一样，光标定位在视频后面

### ISSUE THREAD

**Issue by XunyChen** [wangeditor-team/wangEditor#3115]
## 问题描述

*如题，这其实是一个用户的编辑习惯，删除内容的时候习惯把光标删到某个图片，或者视频的后面，而当前编辑器当光标在视频下一行的时候，再按退格键删除，则视频直接删除了*

## wangEditor 版本

*4.5.4*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：自定义视频上传菜单，上传视频
- 步骤二：在视频的下一行执行退格键删除，把当前行内容删完
- 步骤三：再继续按一下退格键，视频就删掉了，用户习惯应该是光标回到视频后

**Comment by wangfupeng1988** [comment]
图片是 inline 元素，视频是 block 元素，所以视频无法像图片一样。
