### ISSUE TITLE
菜单栏配置和粘贴图片上传冲突

### ISSUE THREAD

**Issue by misterpancn** [wangeditor-team/wangEditor#3117]
## bug 描述

当设置`editor.config.menus = []`，也就是menus为空时，编辑器实例化正常，但是自定义图片上传`customUploadImg`不能触发

## 你预期的样子是？

我需要去掉编辑器自带的菜单栏，之前老版本是这么设置的没有问题

## 浏览器及版本号

Chrome

## wangEditor 版本

4.6.12

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤
使用qq截图，直接ctrl+v粘贴到编辑器
```
const editor = new E("#div1");
editor.config.menus = []     // 去掉这个可以正常触发
editor.config.customUploadImg = (files, insert) => {
  alert('success')
}
```

**Comment by wangfupeng1988** [comment]
建议你先使用 `editor.$toolbarElem.hide()` 临时隐藏菜单栏。
这个问题我们先排查一下。

**Comment by YmCoke** [comment]
目前customImage只有在menus中存在img菜单时才会生效，请暂时使用`editor.$toolbarElem.hide()`来代替`editor.config.menus = []`。对于这个问题，我们将在后面的插件化版本中进行处理。
