### ISSUE TITLE
复制网络图片，粘贴到编辑器，会显示两张

### ISSUE THREAD

**Issue by yx570** [wangeditor-team/wangEditor#3119]
## bug 描述
复制网络图片，粘贴到编辑器，会显示两张
*请输入内容……*
![image](https://user-images.githubusercontent.com/13014581/113271628-5089d400-930d-11eb-86e1-000bbdbfbcf9.png)
![image](https://user-images.githubusercontent.com/13014581/113271911-9fd00480-930d-11eb-8159-77d1aa5512f4.png)

## 你预期的样子是？
希望复制网络图片能像截图粘贴那样，只显示处理后的图片
*请输入内容……*

## 浏览器及版本号
版本 88.0.4324.150（正式版本） （64 位）
*请输入内容……*
https://www.wangeditor.com/  官网即可复现
## wangEditor 版本
4.3.0
*请输入内容……*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  网上找张图片，右键复制图片
- 步骤二  打开官网，在编辑器中粘贴即可复现
- 步骤三

**Comment by baixiao1522** [comment]
等

**Comment by yx570** [comment]
> 可以通过配置 editor.config.pasteIgnoreImg = true 来忽略粘贴的图片。如果复制的内容有图片又有文字，则只粘贴文字，不粘贴图片。

如果就是需要粘贴图片呢

**Comment by biology-w** [comment]
bug 描述
------------------------------------------------------------------------------------
环境：
windows10专业版 64位
chrome 91.0.4472.101
wangEditor 4.3.0

直接复制word或微信内单个图片,粘贴到编辑器，会显示两张。
![image](https://user-images.githubusercontent.com/25600705/121663085-9e267800-cad8-11eb-896f-90b47312ea7e.png)
![image](https://user-images.githubusercontent.com/25600705/121663215-c3b38180-cad8-11eb-831b-d2375b6242cb.png)
![image](https://user-images.githubusercontent.com/25600705/121663279-d8901500-cad8-11eb-97b7-dca4d51423ae.png)

**Comment by Gavin-yh** [comment]
> ## bug 描述
> 环境： windows10专业版 64位 chrome 91.0.4472.101 wangEditor 4.3.0
> 
> 直接复制word或微信内单个图片,粘贴到编辑器，会显示两张。 ![image](https://user-images.githubusercontent.com/25600705/121663085-9e267800-cad8-11eb-896f-90b47312ea7e.png) ![image](https://user-images.githubusercontent.com/25600705/121663215-c3b38180-cad8-11eb-831b-d2375b6242cb.png) ![image](https://user-images.githubusercontent.com/25600705/121663279-d8901500-cad8-11eb-97b7-dca4d51423ae.png)



> ## 错误描述
> 环境： windows10 专业版64位chrome 91.0.4472.101 wangEditor 4.3.0
> 
> 直接复制文字或微信内的个别图片，粘贴到编辑器，会显示两张。 ![图片](https://user-images.githubusercontent.com/25600705/121663085-9e267800-cad8-11eb-896f-90b47312ea7e.png) ![图片](https://user-images.githubusercontent.com/25600705/121663215-c3b38180-cad8-11eb-831b-d2375b6242cb.png) ![图片](https://user-images.githubusercontent.com/25600705/121663279-d8901500-cad8-11eb-97b7-dca4d51423ae.png)

**Comment by Gavin-yh** [comment]
> ## 错误描述
> 环境： windows10 专业版64位chrome 91.0.4472.101 wangEditor 4.3.0
> 
> 直接复制文字或微信内的个别图片，粘贴到编辑器，会显示两张。 ![图片](https://user-images.githubusercontent.com/25600705/121663085-9e267800-cad8-11eb-896f-90b47312ea7e.png) ![图片](https://user-images.githubusercontent.com/25600705/121663215-c3b38180-cad8-11eb-831b-d2375b6242cb.png) ![图片](https://user-images.githubusercontent.com/25600705/121663279-d8901500-cad8-11eb-97b7-dca4d51423ae.png)

**Comment by Gavin-yh** [comment]
> ## bug 描述
> 环境： windows10专业版 64位 chrome 91.0.4472.101 wangEditor 4.3.0
> 
> 直接复制word或微信内单个图片,粘贴到编辑器，会显示两张。 ![image](https://user-images.githubusercontent.com/25600705/121663085-9e267800-cad8-11eb-896f-90b47312ea7e.png) ![image](https://user-images.githubusercontent.com/25600705/121663215-c3b38180-cad8-11eb-831b-d2375b6242cb.png) ![image](https://user-images.githubusercontent.com/25600705/121663279-d8901500-cad8-11eb-97b7-dca4d51423ae.png)

这种情况当时是怎么复现的呢

**Comment by lsdstone** [comment]
1.自定义了上传图片的逻辑；
2.当复网络图片粘贴到编辑器时
满足上述两个条件会导致编辑器出现两张图片
满足以上两个条件可以在config配置的pasteTextHandle中单独处理纯图片粘贴的逻辑

设置config的pasteTextHandle函数如下

      // 配置粘贴文本的内容处理
      config.pasteTextHandle = function (pasteStr) {
        const isHasOnlyImgEleReg = /^<img [^>]*src=['"]([^'"]+)[^>]*>$/g
        // 如果是纯图片。这个粘贴逻辑会被编辑器的插入图逻辑覆盖，所以这里需要返回空字符，不需要粘贴了，否则会变成两张图片
        if (isHasOnlyImgEleReg.test(pasteStr.trim())) {
          return ''
        }
        return pasteStr
      }
