### ISSUE TITLE
word粘贴时，图片与文字customUploadImg方法无法调用

### ISSUE THREAD

**Issue by zouk688** [wangeditor-team/wangEditor#3121]
## bug 描述
从word粘贴文字与图片到富文本框中时customUploadImg无法调用
*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
只粘贴图片是走的customUploadImg，既有图片又有文字的是走pasteTextHandle。这是符合预期的

**Comment by zouk688** [comment]
pasteTextHandle 这个怎么处理图表上传功能

**Comment by UltramanWeiLai** [comment]
正则取 img 标签呗

**Comment by rsl140** [comment]
该问题长时间未回复，暂时关闭
