### ISSUE TITLE
删除内容为空时，不会立即显示placeholder

### ISSUE THREAD

**Issue by ycx0317** [wangeditor-team/wangEditor#3122]
## bug 描述

在输入区域使用中文输入法，出现中文后不选择内容，而是点击delete，关闭输入法面板，再次点击delete，之前的内容被删除，此时看到输入区域已经为空，不会立即显示placeholder，需要再点击一次delete，才会显示placeholder

## 你预期的样子是？

删除内容后能立即显示placeholder

## 浏览器及版本号

chrome89

## wangEditor 版本

4.6.13

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 打开官网demo
-  切换中文输入法，点击键盘，出现中文选择内容
![image](https://user-images.githubusercontent.com/8268811/113388515-f1859700-93c0-11eb-9ca1-818a77567e11.png)

- 点delete，输入法选择面板被关闭
![image](https://user-images.githubusercontent.com/8268811/113388340-a1a6d000-93c0-11eb-918a-12b1dc7c0bd8.png)

- 再次点击delete，输入区已无内容
![image](https://user-images.githubusercontent.com/8268811/113388339-a1a6d000-93c0-11eb-8a9d-3947a6903c49.png)

- 不显示placplaceholder，需要再次点击delete后，才会显示placeholder

**Comment by rsl140** [comment]
未复现该问题

**Comment by wanlinqiang** [comment]
![image](https://user-images.githubusercontent.com/10278813/113653268-197a4080-96c8-11eb-80d0-9e2e2668dbda.png)

**Comment by wanlinqiang** [comment]
https://user-images.githubusercontent.com/10278813/113653363-475f8500-96c8-11eb-86ae-db3fe145d5d1.mov

**Comment by UltramanWeiLai** [comment]
请问是用的什么输入法？

**Comment by wanlinqiang** [comment]
> 请问是用的什么输入法？

Sogou

**Comment by YmCoke** [comment]
未复现该问题，该问题应该已被解决。
