### ISSUE TITLE
使用 this.editor.cmd.do("insertHTML","")值错误

### ISSUE THREAD

**Issue by liwei60** [wangeditor-team/wangEditor#3123]
## bug 描述
使用 this.editor.cmd.do("insertHTML",<span>111</span>) 
在谷歌浏览器上p标签丢失  只有111插入进去了
在火狐上是正确的
## 你预期的样子是？

<p><span>111</span></p>

## 浏览器及版本号

谷歌浏览器

## wangEditor 版本
4.6.6

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤
- 步骤一
- 新建一个菜单栏选项
- 步骤二
- 选中编辑器中数据的第一个字，执行 this.editor.cmd.do("insertHTML",<span>111</span>) 命令
- 步骤三
发现插入标签错乱

**Comment by rsl140** [comment]
1. 步骤一中所说的新建一个菜单栏选项是自定义一个扩展菜单么？
2. 标签错乱是指什么样的错乱？

**Comment by UltramanWeiLai** [comment]
准确来说，谷歌浏览器的行为才更符合预期。
你插入的的是 '111' 而不是 '<p>111</p>'
insertHTML 的实现是用的 execCommand 各个浏览器对它的实现稍有不同。
所以还请尽量写完整吧。

**Comment by liwei60** [comment]
> 1. 步骤一中所说的新建一个菜单栏选项是自定义一个扩展菜单么？
> 2. 标签错乱是指什么样的错乱？

1.是扩展菜单
2.标签错乱的意思是比如我插入了一个"<span data-type='${targetType}'  data-content='${channel}' >1111</span"  返回的是"<span font-size="24px">1111</span>"

**Comment by liwei60** [comment]
> ```
> 准确来说，谷歌浏览器的行为才更符合预期。
> 你插入的的是 '111' 而不是 '<p>111</p>'
> insertHTML 的实现是用的 execCommand 各个浏览器对它的实现稍有不同。
> 所以还请尽量写完整吧。
> ```

我插入的就是'<span data-type='${targetType}' data-content='${channel}'>${text}</span>'  返回的却是'<span font-size='24px'>${text}</span>'  这种

**Comment by rsl140** [comment]
并未复现

`editor.cmd.do("insertHTML","<span data-type='aaa' data-content='bbb' >1111</span>")`

![image](https://user-images.githubusercontent.com/7655291/113715348-fd07f380-971b-11eb-9013-c699395013ad.png)

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
