### ISSUE TITLE
insertHTML、insertImage 插入位置非当前光标位置

### ISSUE THREAD

**Issue by Kenny1zhao** [wangeditor-team/wangEditor#3125]
## bug 描述

*insertHTML、insertImage 插入位置非当前光标位置*

## 你预期的样子是？

*insertHTML、insertImage 应该是在光标位置插入*

## 浏览器及版本号

*chrome 最新*

## wangEditor 版本

*v3、v4都有*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 输入一小段文字
- 在这段文字后面插入一张图片
- 全选设置 文字 效果（加粗、斜体、或其他随意一个）
- 此时光标在图片后面，插入一张图片
- 图片出现在最前面（文字前面），非光标位置处

**Comment by UltramanWeiLai** [comment]
经过调试过后发现，可能是 execCommand 的问题，我会另外再去跟踪一次。

**Comment by Charlolo** [comment]
请问问题解决了吗？ T_T

**Comment by blackhu0804** [comment]
> 请问问题解决了吗？ T_T

在解决中了
