### ISSUE TITLE
上传图片或网络图片时增加img标签属性设置

### ISSUE THREAD

**Issue by xiangzongliang** [wangeditor-team/wangEditor#3128]
## 功能描述

建议针对上传的图片可以添加图片属性，源码中默认的插入方式为：
```javascript
/**
* src/menus/img/upload-img.ts 
*/
// 先插入图片，无论是否能成功
editor.cmd.do('insertHTML', `<img src="${src}" style="max-width:100%;"/>`)
```
建议修改结果如：
`<img src="xxx" loading="lazy" crossorigin="anonymous" ...>`

## 提炼几个功能点

1、自定义添加属性。
2、可在图片上传提示中动态增加多栏自定义属性

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
