### ISSUE TITLE
copy一段带URL的文字，粘贴后URL的链接被修改了。

### ISSUE THREAD

**Issue by ju7-mo** [wangeditor-team/wangEditor#3129]
## bug 描述

copy一段带URL的文字，粘贴到编辑器后a标签里面的href属性设置错误。

## 你预期的样子是？

正确设置a标签的href属性。

## 浏览器及版本号

谷歌 89.0.4389.114（Official Build） （x86_64）

## wangEditor 版本

V4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- copy如下内容。

```
https://www.baidu.com/

测试
```

- 将内容粘贴到wangEditor编辑器
- 查看URL的a标签的href属性，显示如下。
`<a href="https://www.baidu.com/<br/><br/>测试" target="_blank">https://www.baidu.com/<br><br>测试</a>`

**Comment by rsl140** [comment]
未复现该问题
![image](https://user-images.githubusercontent.com/7655291/113716809-8b30a980-971d-11eb-874f-277fcbab3d8d.png)

**Comment by ju7-mo** [comment]
单独一个URL没有问题，问题复现的话，需要copy一个段落。

<pre><code>https://www.baidu.com/

测试
</code></pre>


<img width="1127" alt="test" src="https://user-images.githubusercontent.com/54229268/113793428-d88f3400-977a-11eb-9c7e-c55caaa61813.png">

**Comment by ju7-mo** [comment]
在官网验证的时候，改bug依然存在。
