### ISSUE TITLE
建议增加右键粘贴菜单

### ISSUE THREAD

**Issue by zuoliang0** [wangeditor-team/wangEditor#3130]
## 功能描述

*建议增加右键菜单粘贴 ，去除格式粘贴*

## 提炼几个功能点

- 右键菜单
- 粘贴
- 仅文字（不含格式文本）

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
![image](https://user-images.githubusercontent.com/8434253/113689167-9a532f80-96fc-11eb-94b9-bf9c344ce174.png)

**Comment by zuoliang0** [comment]
参考的wps的右键菜单

**Comment by wangfupeng1988** [comment]
感谢提出，很好的建议。
不过当前没法直接加，我们正在规划新版本的重构，到时会统一考虑右键菜单，包括表格的右键菜单。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
