### ISSUE TITLE
输入文字后，不选中文字多次切换字号，输入框光标乱跳，字号并未改变

### ISSUE THREAD

**Issue by ZhaoCongDream** [wangeditor-team/wangEditor#3131]
## 1.初始输入任意文字后  
![image](https://user-images.githubusercontent.com/30501861/113712713-0c397200-9719-11eb-8cf2-37d9f5436de6.png)
## 2.然后不选中文字切换字号，光标会跳到行首  
![image](https://user-images.githubusercontent.com/30501861/113712811-2bd09a80-9719-11eb-99af-dbc2c7895857.png)
## 3.再次切换字号，行高改变，字号未改变  
![image](https://user-images.githubusercontent.com/30501861/113712889-46a30f00-9719-11eb-90ad-028812579d19.png)

示例代码 官方例子即可查看 https://codepen.io/xiaokyo-the-bold/pen/yLaOVrR

**Comment by rsl140** [comment]
请按 issue 模板格式提交
