### ISSUE TITLE
按照文档z-index配置，不仅无效且导致更多问题

### ISSUE THREAD

**Issue by wusongbai139** [wangeditor-team/wangEditor#3132]
## 问题描述

*按照文档配置了z-index，但是正文区域却变得无法点击无法输入文字*

## wangEditor 版本：v4

##正文：
*浏览器是chrome，按照文档配置了z-index后：*
*1，工具导航栏（toolbar-container）部分无效，正文（text-container）部分有效。*
*2，页面加载完成后，可以直接在正文区域输入内容，但是一旦鼠标点击了其他地方的input后，再点击正文（text-container）部分时，却点击不上。*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*就是依据文档配置的*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：

`

<div style="display: none">
    <label for="text1"></label>
    <textarea name="body" id="text1" style="width:100%; height:200px;"></textarea>
</div>
<div>
      <div id="toolbar-container" class="toolbar"></div>
      <p></p>
      <div id="text-container" class="text" name="text-container"></div>
  </div>`
- 步骤二：
`
// js代码
const E = window.wangEditor
        const editor = new E('#toolbar-container', '#text-container') 
        const $text1 = document.getElementById('text1')

        editor.config.onchange = function (html) {
            // 同步更新到 textarea
            $text1.value = html
        }
        // 配置菜单栏
        editor.config.excludeMenus = [
            'indent',
            'fontName',
            'head',
            'lineHeight',
            'todo',
            'undo',
            'redo',
        ]
        //配置字号大小
        editor.config.fontSizes = {
            //'x-small': {name: '10px', value: '1'},
            'small': {name: '13px', value: '2'},
            'normal': {name: '16px', value: '3'},
            'large': {name: '18px', value: '4'},
            'x-large': {name: '24px', value: '5'},
            //'xx-large': {name: '32px', value: '6'},
            //'xxx-large': {name: '48px', value: '7'},
        }
        // 代码高亮 挂载highlight插件
        editor.highlight = hljs
       
       // 问题源头：
        editor.config.zIndex = -1

        editor.create()
        $text1.value = editor.txt.html()`

**Comment by wusongbai139** [comment]
代码放的有点乱，不过都是咱们文档里的代码，没有别的修改的地方

**Comment by rsl140** [comment]
zIndex 需要设置为>0以上的值
