### ISSUE TITLE
输入文字后，不选中文字，多次切换字号，发现输入框光标乱跳，同时行高改变，字号未改变 。

### ISSUE THREAD

**Issue by ZhaoCongDream** [wangeditor-team/wangEditor#3133]
## 问题描述
输入文字后，不选中文字，多次切换字号，发现输入框光标乱跳，同时行高改变，字号未改变 。  
查阅了源码，发现可能是因为在未选中数据时切换行号会插入一个空白元素，请问我该如何规避这个现象？
## 浏览器及版本号
 Mac Chrome 浏览器 89.0.4389.90
## wangEditor 版本

V4.6.9

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 初始输入任意文字后  
![image](https://user-images.githubusercontent.com/30501861/113712713-0c397200-9719-11eb-8cf2-37d9f5436de6.png)
- 步骤二 然后不选中文字切换字号，光标会跳到行首  
![image](https://user-images.githubusercontent.com/30501861/113712811-2bd09a80-9719-11eb-99af-dbc2c7895857.png)
- 步骤三 再次切换字号，行高改变，字号未改变  
![image](https://user-images.githubusercontent.com/30501861/113712889-46a30f00-9719-11eb-90ad-028812579d19.png)

**Comment by rsl140** [comment]
未复现该问题
![QQ20210408-091053-HD](https://user-images.githubusercontent.com/7655291/113953759-15c2f700-984b-11eb-908e-fe443750b68b.gif)

**Comment by UltramanWeiLai** [comment]
window 也未复现

**Comment by ZHAOzn** [comment]
可能是css被覆盖了？

**Comment by rsl140** [comment]
> 可能是css被覆盖了？

可以尝试在最简单的环境下使用是否会出现。

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭。
