### ISSUE TITLE
工具栏（toolbar-container）和正文部分（text-container）的z-index 是否可以分开设置

### ISSUE THREAD

**Issue by wusongbai139** [wangeditor-team/wangEditor#3135]
## 问题描述

*在web开发中想要将工具栏（toolbar-container）在滚动到一定位置后固定住，但是随着工具栏的固定，工具栏底下的正文部分（text-container）却将工具栏覆盖住了*

>
<img width="805" alt="截屏2021-04-07 上午11 41 07" src="https://user-images.githubusercontent.com/69897981/113807384-9b389f80-9796-11eb-96fd-e1174d88325d.png">

## wangEditor 版本

*v4*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：html代码
`<div>`
     `<div id="toolbar-container" class="toolbar"></div>`
     `<div id="text-container" class="text" name="text-container"></div>`
  `</div>`
- 步骤二：js设置
`editor.config.zIndex = 10`
- 步骤三：css设置
`#toolbar-container {
    position: -webkit-sticky;
    position: sticky;
    top: 70px;
}`
`#text-container{z-index: 1;}`
`#text-container > div{z-index: 1;}`

**Comment by UltramanWeiLai** [comment]
你这不是手动对编辑区域进行了 z-index 的设置吗？

**Comment by wusongbai139** [comment]
> 你这不是手动对编辑区域进行了z-index的设置吗？

抱歉我在正文里没写明白，我手动设置了编辑区域的z-index，但是没有效果。当工具导航条粘到顶部时候，编辑区域既然会覆盖到上面。
<img width="961" alt="截屏2021-04-08 上午10 53 09" src="https://user-images.githubusercontent.com/69897981/113961501-c08de200-9858-11eb-9c83-741320009543.png">

**Comment by WangJolin** [comment]
编辑器 z-index 默认为 10000（[参考](https://doc.wangeditor.com/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/06-zIndex.html)），出现以上情况是因为工具栏的父元素的层级不够高，给toolbar-container设置比编辑区高的z-index值即可。
