### ISSUE TITLE
企业微信复制多行文本第一行内容丢失

### ISSUE THREAD

**Issue by SmileAjh** [wangeditor-team/wangEditor#3136]
bug 描述
使用windows 10系统
企业微信版本：3.1.6.3605
在企业微信中，复制一行聊天内容后，无法在编辑器中ctrl+v粘贴，右击选择“粘贴为纯文本”可以粘贴。
复制多行聊天记录后，第一条聊天记录丢失，剩下的可以粘贴在编辑器中。
你预期的样子是？
预期能正常粘贴文本，多行粘贴不丢失数据

浏览器及版本号
谷歌浏览器 89.0.4389.90(32 位)

wangEditor 版本
4.6.13

官网能否复现该 bug ？
能

最小成本的复现步骤
（请告诉我们，如何最快的复现该 bug）

在企业微信中，复制多行聊天内容
在编辑器中ctrl+v粘贴

**Comment by SmileAjh** [comment]
https://github.com/wangeditor-team/wangEditor/issues/2441 相关issue，问题仍在

**Comment by SmileAjh** [comment]
![image](https://user-images.githubusercontent.com/18346430/113823349-23c43980-97b1-11eb-9312-a409b35f8fe0.png)
![image](https://user-images.githubusercontent.com/18346430/113823447-3cccea80-97b1-11eb-92bb-263e1a06450e.png)

**Comment by UltramanWeiLai** [comment]
因为我们这边没有企业微信，很难精确的去复现和修复该问题。
是否能提供企业维修账号，或者相应的字符串，供我们复现和测试该问题？

**Comment by SmileAjh** [comment]
> 因为我们这边没有企业微信，很难精确的去复现和修复该问题。
> 是否能提供企业微信账号，或者相应的字符串，供我们复现和测试该问题？

"<html>
<body>
test(测试)&nbsp;4-7&nbsp;10:17:51<br>你好<BR><BR>助手&nbsp;4-7&nbsp;10:23:43<br>请更新到最新版本再试试？我们没复现到这个问题哦<BR><BR>test(测试)&nbsp;4-7&nbsp;10:24:40<br>https://www.wangeditor.com/<BR><BR>test(测试)&nbsp;4-7&nbsp;10:24:55<br>这个是编辑器的测试地址<BR><BR>test(测试)&nbsp;4-7&nbsp;10:27:25<br>复制企业微信中多条聊天记录进入上面的编辑器&nbsp;&nbsp;第一行内容就会丢失<BR><BR>助手&nbsp;4-7&nbsp;10:34:00<br>问题出现了么。<BR><BR>test(测试)&nbsp;4-7&nbsp;10:34:25<br>好的
</body>
</html>"
出现问题的字符串

**Comment by SmileAjh** [comment]
`` @UltramanWeiLai 请教您个问题，tag.ts的IGNORE_TAGS中忽略body的目的是什么，出于怎样的考虑，为了解决什么问题？我测试是移除body就可以解决这个问题.

**Comment by wangfupeng1988** [comment]
> 出现问题的字符串
> 文件：[test.txt](https://github.com/wangeditor-team/wangEditor/files/6275585/test.txt)

@SmileAjh  这个问题和 https://github.com/wangeditor-team/wangEditor/issues/3111 一样，会安排一起来解决的。

**Comment by fzhyzamt** [comment]
同遇到这个问题，如果只复制一行内容的话，就完全粘贴不进去了

**Comment by chenxiaoleizi** [comment]
已找到问题，正在研究解决方案
