### ISSUE TITLE
表格优化

### ISSUE THREAD

**Issue by szxzxh** [wangeditor-team/wangEditor#3138]
## 功能描述

*表格优化*

## 新增几个功能点

- 功能1：是否可以支持表格的列宽高、行宽高 自定义拉伸，类似 office那种？
- 功能2：是否可以支持 对整个表格进行拉伸缩，类似图片的大小控制。
- 功能3：是否可以支持 对列数据 设置对齐方式呢？

## 原型图

**

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by UltramanWeiLai** [comment]
我们正在规划新版本的重构，到时会对表格功能进行重构，尽量丰富其功能。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
