### ISSUE TITLE
自定义上传图片，相同图片依次上传，第二次无响应

### ISSUE THREAD

**Issue by bayi-lzp** [wangeditor-team/wangEditor#3139]
## bug 描述
采用自定义上传功能，上传一张图片为测试.png，能上传成功，再次重复上传相同的图片，测试.png。结果无响应

## 你预期的样子是？
可以连续上传相同的图片文件

## 浏览器及版本号

浏览器版本：mac chrome 89.0.4389.114

## wangEditor 版本

v4.6.13
## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 
 采用自定义上传
- 步骤二
上传一张图片为测试.png，上传成功
- 步骤三
再次重复2步骤，上传步骤2相同的图片，测试.png。结果无响应

**Comment by UltramanWeiLai** [comment]
官网中并没有复现没有该问题。
可以关注一下请求的情况。

**Comment by Gavin-yh** [comment]
该问题已经修复，下个版本更新

**Comment by rsl140** [comment]
该问题已经修复，下个版本会更新
可以移步到#3041 issue中 跟进进度。
