### ISSUE TITLE
建议在配置菜单时候，没有“image”图片菜单，也能点击编辑器里面的图片设置宽度

### ISSUE THREAD

**Issue by ChuangShiOS** [wangeditor-team/wangEditor#3140]
## 功能描述

这个是我在线上重现的例子：https://codesandbox.io/s/wandering-sky-imvff?file=/src/index.js
有两个编辑器，上面的编辑器没有配置“image”图片菜单，下面的编辑器有配置“image”图片菜单
我希望的效果是没有配置“image”图片菜单的时候，也能点击编辑器里面的图片进行设置宽度

**Comment by UltramanWeiLai** [comment]
图片的 tooltip 是依赖于图片菜单的，如果你自定义了其他的图片插入方法，需要 tooltip 的话，需要实现相应的逻辑，可以参照源码里面 `/src/menus/img` 中的代码

**Comment by ChuangShiOS** [comment]
图片的 tooltip 放在全局的来配置会不会挺好的？  因为很多人因为开发水平的原因会做不出很好的tooltip效果，希望你们也能考虑一下，谢谢了。

**Comment by UltramanWeiLai** [comment]
> 图片的 tooltip 放在全局的来配置会不会挺好的？ 因为很多人因为开发水平的原因会做不出很好的tooltip效果，希望你们也能考虑一下，谢谢了。

这个我们会去讨论一下的，不过这个也得看情况，有的人可能需要，有的人可能不需要是不？而且我们有提供 tooltip 的基类，参考源码复写一个 tooltip 还是相对简单的。

**Comment by UltramanWeiLai** [comment]
那么如果没有其他问题，该 issue 我就关闭了？

**Comment by ChuangShiOS** [comment]
好的好的  谢谢啦 这个一个很好用的富文本编辑器 祝开源越来越好
