### ISSUE TITLE
编辑框如何去加入自定义高度按钮功能，如图所示

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3147]
## 功能描述

编辑框如何去加入自定义编辑区域高度按钮功能，如图所示，可以上下拉动

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

![image](https://user-images.githubusercontent.com/43296632/114158403-37a9a000-9957-11eb-991d-638ab12f9f5a.png)

## 可参考的案例

![image](https://user-images.githubusercontent.com/43296632/114158403-37a9a000-9957-11eb-991d-638ab12f9f5a.png)

**Comment by clinfc** [comment]
https://juejin.cn/post/6910870154737877000

**Comment by UltramanWeiLai** [comment]
可以根据上述文章的内容进行实现。
目前编辑器现有功能的稳定性和实用性为主，暂时不会去支持该功能。

**Comment by OnePsycho** [comment]
> 可以根据上述文章的内容进行实现。
> 目前编辑器现有功能的稳定性和实用性为主，暂时不会去支持该功能。

感谢大佬！
