### ISSUE TITLE
自定义上传图片，连续两次上传相同的图片，第二次不会触发上传方法

### ISSUE THREAD

**Issue by justinluhui** [wangeditor-team/wangEditor#3148]
## bug 描述
如题：连续两次上传相同的图片，第一次上传成功，第二次不会触发editor.config.customUploadImg这个方法：
editor.config.customUploadImg = function (resultFiles, insertImgFn) {
    // resultFiles 是 input 中选中的文件列表
    // insertImgFn 是获取图片 url 后，插入到编辑器的方法

    // 上传图片，返回结果，将图片插入到编辑器中
    insertImgFn(imgUrl)
}

## 你预期的样子是？

连续两次上传相同的图片，两次都能正常触发图片上传方法

## 浏览器及版本号

chrome 89.0.4389.90

## wangEditor 版本

4.6.14

## 官网能否复现该 bug ？

-- 官网没有自定义图片上传功能，不好复现

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：代码中设置图片上传自定义方法；
- 步骤二：上传一张图片，能上传成功
- 步骤三：在上传步骤二那张图片，没有任何响应。  未进入自定义上传图片的方法中~

**Comment by rsl140** [comment]
该问题已经修复，下个版本会更新
可以移步到#3041 issue中 跟进进度。
