### ISSUE TITLE
怎样动态修改placeholder

### ISSUE THREAD

**Issue by ZHAOzn** [wangeditor-team/wangEditor#3149]
## 问题描述
i18n国际化，placeholder不会随着传入的值变化

editor.config.placeholder = "新的值" ，组件并不会变化
我现在是通过先destory，再create来解决这个问题，是否有更好的解决方式呢

## wangEditor 版本
^4.6.12

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by clinfc** [comment]
editor.$textContainerElem.find('.placeholder').text('重新设置的 placeholder')

**Comment by ZHAOzn** [comment]
> editor.$textContainerElem.find('.placeholder').text('重新设置的 placeholder')

谢谢

**Comment by Gasang-Pon** [comment]
> editor.$textContainerElem.find('.placeholder').text('重新设置的 placeholder')

你好，v5版本没有$textContainerElem这个，请问要怎么动态修改

**Comment by Gasang-Pon** [comment]
document.querySelector('.w-e-text-placeholder').innerText可以修改
