### ISSUE TITLE
菜单栏与编辑区分离时没有边框且设置高度无效

### ISSUE THREAD

**Issue by clinfc** [wangeditor-team/wangEditor#3152]
## bug 描述

菜单栏与编辑区分离时没有边框且设置 editor.config.height 无效

## 你预期的样子是？

菜单栏与编辑区分离时有边框且设置高度有效

## 浏览器及版本号

all

## wangEditor 版本

v4.6.14

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

菜单和编辑区域分离的方式进行初始化

**Comment by UltramanWeiLai** [comment]
好像是没有，样式得自己定义。
