### ISSUE TITLE
小程序字体样式bug

### ISSUE THREAD

**Issue by HuangJinxing2019** [wangeditor-team/wangEditor#3154]
## bug 描述

小程序无法显示在服务本编辑的字体颜色和大小

## 你预期的样子是？

小程序可正常显示字体样式大小，使用<p>或<span>标签内嵌style样式

## 浏览器及版本号

小程序

## wangEditor 版本

4.6.10

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

使用小程序<rich-text nodes="{{htmlSnip}}"></rich-text>组件显示富文本内容

**Comment by UltramanWeiLai** [comment]
可以通过 editor.config.styleWithCSS = true 把标签转换成 style 样式

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
