### ISSUE TITLE
支持显示当前输入字数

### ISSUE THREAD

**Issue by pengwangpengwang** [wangeditor-team/wangEditor#3155]
## 功能描述
增加配置可支持显示当前输入字符数量
## 原型图
![image](https://user-images.githubusercontent.com/29265420/114527326-705cb880-9c7a-11eb-8801-4294bc7dde14.png)

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例 
百度Ueditor

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
https://github.com/fex-team/ueditor

**Comment by wangfupeng1988** [comment]
你可以获取编辑器的内容  https://doc.wangeditor.com/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/ 然后自己获取 text 的长度，自己显示。
