### ISSUE TITLE
table线框抖动

### ISSUE THREAD

**Issue by CrazyWood007** [wangeditor-team/wangEditor#3157]
## bug 描述

在table中输入内容，table发生抖动，线不对齐
可能不是wangeditor的问题，但是想要寻求一个解决办法

## 你预期的样子是？

线框对齐，正常展示，table不抖动

## 浏览器及版本号

chrome 88+

## wangEditor 版本

4.6.9

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 插入表格，比如5*5
- 步骤二 在格子内输入内容（不要按顺序一个一个格子输入，内容包含换行）

![image](https://user-images.githubusercontent.com/44600593/114536884-1eb92b80-9c84-11eb-886b-0424b3d5dfb7.png)

**Comment by wangfupeng1988** [comment]
这应该是 chrome 渲染的问题，table 解构没有变，我们暂时没有解决办法。
