### ISSUE TITLE
大纲目录介意可以收缩（做成树形呀）

### ISSUE THREAD

**Issue by puzhixin** [wangeditor-team/wangEditor#3158]
## 功能描述

*大纲目录介意可以收缩（做成树形呀）*

## 提炼几个功能点

- 大纲目录介意可以收缩（做成树形呀）
## 原型图

*点击以及标题可以收缩子级*

## 可参考的案例

**

**Comment by UltramanWeiLai** [comment]
这个你可以自行实现，我们这边只提供了 header 的描点

**Comment by wangfupeng1988** [comment]
可参考这个 demo https://codepen.io/xiaokyo-the-bold/pen/zYKvgPj
