### ISSUE TITLE
IE11下需要先选中内容再点居中才能生效

### ISSUE THREAD

**Issue by lujdong** [wangeditor-team/wangEditor#3161]
## bug 描述

*请输入内容……*
IE11下需要居中内容时需要先选中需要居中的内容然后选择居中才能成功
## 你预期的样子是？
应当是选择居中功能后，无需选择需要居中的内容即可居中成功
*请输入内容……*
使用编辑器居中功能后，在编辑器中显示正常，但是获取到的数据 p 标签缺少 align="center" 样式
## 浏览器及版本号
IE11
*请输入内容……*

## wangEditor 版本
3.1.1
*请输入内容……*

## 官网能否复现该 bug ？
否
能/不能

## 最小成本的复现步骤
使用IE浏览器11版本，选择编辑器的居中功能，输入内容，此时编辑器中的内容是居中状态，但是获取到的html字符串数据中该内容缺少 align="center" 样式，以至于发送给后台的数据有误。
（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
![1618395229547](https://user-images.githubusercontent.com/7655291/114695178-e847e300-9d4d-11eb-9889-f72a1d20f214.gif)

![image](https://user-images.githubusercontent.com/7655291/114695123-d5351300-9d4d-11eb-80eb-113a875a7b31.png)
未复现该问题

**Comment by UltramanWeiLai** [comment]
v3 版本目前已经不进行维护了，建议升级到 v4 版本进行使用。
