### ISSUE TITLE
关于 onblur 事件

### ISSUE THREAD

**Issue by NextVsco** [wangeditor-team/wangEditor#3162]
## bug 描述

当光标焦点在 wangeditor 内时，点击按钮。
wangeditor 的 onblur 事件执行在 按钮的 onclick 之后

## 你预期的样子是？

wangeditor 的 onblur 事件执行在 按钮的 onclick 之前；
参考input 的onblur 事件

## 浏览器及版本号

google 版本 89.0.4389.114（正式版本） （64 位）

## wangEditor 版本

^4.5.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

<el-input v-model="" @blur="demo(1)"></el-input>
<wangeditor @onblur="demo(2)"/>
<el-button @click="demo(3)">提交</el-button>
1、先将光标移动到 wangeditor 内；
2、然后直接点击“提交”按钮。

**Comment by rsl140** [comment]
不太明白是什么问题，可否提供示例？

**Comment by UltramanWeiLai** [comment]
该问题长时间没有人回复，暂且关闭。
注：点击按钮的时候，用定时器做个延迟就能解决该问题，这个**应该**是浏览器的事件循环机制的入队时间造成的。
