### ISSUE TITLE
支持Markdown语法编辑

### ISSUE THREAD

**Issue by Fullsize** [wangeditor-team/wangEditor#3164]
## 功能描述

支持Markdown语法编辑

## 提炼几个功能点

- 支持Markdown语法编辑
- 支持Markdown样式

## 可参考的案例
**

**Comment by rsl140** [comment]
你好，该功能已收录 可以移步到 #2284 进行跟踪
不过，该功能会在插件化后再增加此功能。

**Comment by wangfupeng1988** [comment]
markdown 插件已经开发完了 https://github.com/wangeditor-team/wangEditor-plugin-md

不过只能用于 [v5](https://www.wangeditor.com/v5/) 。v5 近期会正式发布，v4 不再做功能升级了。
