### ISSUE TITLE
 文档代码块行内编辑和换行会自动增加多个HTML废弃标签<xmp> 或  多个 <code>标签

### ISSUE THREAD

**Issue by jiechi** [wangeditor-team/wangEditor#3165]
## bug 描述

*文档代码块内编辑和换行会自动增加多个HTML废弃标签**<xmp.>**，提交文本过滤xmp后，回填内容编辑和换行又会自动增加多个<code.>   标签， 空白换行码块内存在<br.>标签 *

## 你预期的样子是？

*1、建议去除xmp <br/> 2、提交文本过滤xmp后，建议去除回填内容编辑和换行又会自动增加多个<code.>标签 同时去除代空白换行码块内的<br.>标签*

## 浏览器及版本号

*chrome*

## wangEditor 版本

*v4.6.13*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一  自动增加xml 1 
- 
![image](https://user-images.githubusercontent.com/33302789/114692072-da449300-9d4a-11eb-982c-e6a5d804089e.png)

- 步骤二 自动增加xml 2 f12查看
- 
![image](https://user-images.githubusercontent.com/33302789/114692181-f7796180-9d4a-11eb-8ea4-b1508beb7e07.png)

- 步骤三 自动增加code 1
-
![image](https://user-images.githubusercontent.com/33302789/114692346-21328880-9d4b-11eb-9cf7-13167f581b31.png)

- 步骤四 自动增加code 2  f12查看
- 
![image](https://user-images.githubusercontent.com/33302789/114692428-30b1d180-9d4b-11eb-8ac1-26b1cfc1c4d9.png)

**Comment by rsl140** [comment]
嗯，稍微解释下。写代码段的话，是在弹出框内写
![image](https://user-images.githubusercontent.com/7655291/115098508-ffabe980-9f62-11eb-9376-0c41a0e3f8b4.png)
显示出来的code中不要去修改内容。因为其实应该是只读的。但是因为一些技术原因，现在不太好做。
在后期的插件化，会对代码块这个功能做改动。所以，如若要修改内容尽量还是在弹出框内就修改完成。

**Comment by UltramanWeiLai** [comment]
而且，回车换行新增的标签是浏览器本身的处理，并不是我们特意设置的。
在某些空段落中会出现 <br/> 也是因为浏览器需要该标签，否则会出现一些不可预期的问题。
如果你需要祛除着些标签，可以考虑使用 正则 或者其他方式进行过滤和解析处理
