### ISSUE TITLE
在标题中回车，生成的标签 id attribute 值一样

### ISSUE THREAD

**Issue by clinfc** [wangeditor-team/wangEditor#3168]
## bug 描述

在标题中回车，生成的标签 id attribute 值一样

## 你预期的样子是？

在标题中回车，生成的标签 id attribute 值不一样

## 浏览器及版本号

all

## wangEditor 版本

最新

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

1、设置某段文字为标题
2、在标题中间回车
3、在控制台查看刚刚操作位置的代码

![image](https://user-images.githubusercontent.com/39868400/114811231-4e7d4600-9de0-11eb-83f7-98d992990a65.png)

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
