### ISSUE TITLE
B粗体和H标题无法缩进，如tinymce可以

### ISSUE THREAD

**Issue by TheAkali-li** [wangeditor-team/wangEditor#3170]
## bug 描述

B粗体和H标题无法缩进，如tinymce可以

## 你预期的样子是？

希望可以实现B粗体和H标题首行缩紧，可能还有其他的样式无法实现

## 浏览器及版本号

chrom

## wangEditor 版本

4.6.14

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/46320446/114836090-de34eb80-9e04-11eb-8c61-d913c5df217a.png)

**Comment by rsl140** [comment]
步骤1
输入一段文字并加粗
步骤2
为这段文字选择缩进

**Comment by TheAkali-li** [comment]
> 步骤1
> 输入一段文字并加粗
> 步骤2
> 为这段文字选择缩进

目前发现，应该是只要为他加入标题，就无法缩进，希望能解决下，感谢

**Comment by UltramanWeiLai** [comment]
这个不是 bug ，目前我们的缩进只支持普通的段落，也就是 p 标签。

**Comment by wangfupeng1988** [comment]
建议对 head 开放“缩进”功能。
