### ISSUE TITLE
获得的html内容无法通过v-html展示富文本样式

### ISSUE THREAD

**Issue by TheAkali-li** [wangeditor-team/wangEditor#3171]
## 问题描述

获得的html内容无法通过v-html展示富文本样式，比如标题会显示不出来，或许还有其他样式

## wangEditor 版本

4.6.14

## 是否查阅了文档 ？

*是*

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/46320446/114836574-65825f00-9e05-11eb-8c22-1c5571b34716.png)
![image](https://user-images.githubusercontent.com/46320446/114836584-67e4b900-9e05-11eb-97b0-c4acb4ad36d6.png)

**Comment by rsl140** [comment]
需要确认是否对H1标签样式做了样式重置。

**Comment by TheAkali-li** [comment]
> 需要确认是否对H1标签样式做了样式重置。

不好意思，全局默认样式，这边关闭问题，感谢
