### ISSUE TITLE
自己实现上传图片

### ISSUE THREAD

**Issue by chen870370470** [wangeditor-team/wangEditor#3173]
## 问题描述

*Vue中添加了自己实现上传图片，但是页面内的上传图片没有变化只有网络图片*

## wangEditor 版本

*4.6.14*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：添加自己实现上传图片代码
- 步骤二：
![image](https://user-images.githubusercontent.com/59992255/114847304-2574a980-9e10-11eb-984c-f61a84dbcfba.png)

- 步骤三：项目中刷新、重启后依然还是只有网络图片上传
- 
![image](https://user-images.githubusercontent.com/59992255/114847420-476e2c00-9e10-11eb-89b0-690b9f1a71f7.png)

**Comment by rsl140** [comment]
请将customUploadImg 放在editor.create()的上方

**Comment by chen870370470** [comment]
> 请将customUploadImg 放在editor.create()的上方

亲测可用~谢谢美女啦

**Comment by wxg3a702** [comment]
测试无效  upload 异步接口调用成功，无法执行后续插入操作
![image](https://user-images.githubusercontent.com/15683774/115665774-5310a400-a376-11eb-9e91-84c7973660ad.png)
