### ISSUE TITLE
低版本浏览器粘贴图片报错

### ISSUE THREAD

**Issue by chao-hua** [wangeditor-team/wangEditor#3177]
## bug 描述
1.在低版本chromiun内核的QQ浏览器中
2.通过剪切版复制图片进富文本编辑器时
3.出现错误
*请输入内容……*
![image](https://user-images.githubusercontent.com/20752717/114963820-25bc8580-9ea0-11eb-8c78-a3dc7b462e8f.png)
![image](https://user-images.githubusercontent.com/20752717/114963903-4c7abc00-9ea0-11eb-96f3-ebd43754698c.png)

希望可以支持一下，感谢~

## 你预期的样子是？

粘贴图片正常

## 浏览器及版本号

QQ浏览器 9.7
## wangEditor 版本

4.6.15

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

由于低版本file.name是undefined，可以变相解决一下。
我们尝试了一下，是可以的。
![image](https://user-images.githubusercontent.com/20752717/114965159-a086a000-9ea2-11eb-8927-2288414ea77c.png)

**Comment by rsl140** [comment]
下载不到9.7版本的QQ浏览器 
![image](https://user-images.githubusercontent.com/7655291/115099253-5adfdb00-9f67-11eb-8c70-e0a798dcf50d.png)
在该版本下未复现该问题

**Comment by chao-hua** [comment]
> 下载不到9.7版本的QQ浏览器
> ![image](https://user-images.githubusercontent.com/7655291/115099253-5adfdb00-9f67-11eb-8c70-e0a798dcf50d.png)
> 在该版本下未复现该问题

链接: https://pan.baidu.com/s/1KnskPThPaeJxJQaDojTFuw  密码: woc5
我将9.7上传至百度云盘，麻烦你试试。

**Comment by rsl140** [comment]
@lkw199711  交叉测试
