### ISSUE TITLE
表格前面有内容时，重新编辑内容会导致表格缺失一格。

### ISSUE THREAD

**Issue by graceful-qi** [wangeditor-team/wangEditor#3178]
## bug 描述
表格前面有内容时，双击内容进行修改会导致致表格缺失一格。
![image](https://user-images.githubusercontent.com/42545339/114967755-9b781f80-9ea7-11eb-8a6c-2bde7e2cc49b.png)

## 你预期的样子是？
只修改双击选中的那行内容，表格无变化

## 浏览器及版本号
谷歌 
版本 89.0.4389.114（正式版本） (x86_64)

## wangEditor 版本
^4.0.0
## 官网能否复现该 bug ？
能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 随便输入文字（最好大于两行，触发概率更高），添加表格
- 双击文字选中
- 随便输入内容，表格会缺失一角

**Comment by rsl140** [comment]
你好未复现该问题

**Comment by UltramanWeiLai** [comment]
建议先把版本升级到最新的再看看。

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复，暂且关闭
