### ISSUE TITLE
标题设置影响整段文字

### ISSUE THREAD

**Issue by hj901204** [wangeditor-team/wangEditor#3179]
## bug 描述

*在编辑器里面将整段文字里的某一行选中文字，然后设置标题为H1（H1～H5都行）后，整段文字也会变成标题了也就是H1的大小和样式*

## 你预期的样子是？

*选中的文字成为标题，没选中的地方还是保存原来的格式样式*

## 浏览器及版本号

*谷歌浏览器 版本：89.0.4389.128（正式版本）（x86_64）*

## wangEditor 版本

*wangeditor": "^4.6.14"*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一: 在富文本里面输入几行文字
- 步骤二：选中某一行的几个字，然后设置成标题
- 步骤三

**Comment by rsl140** [comment]
标题是整体的 这是符合预期的。如果想使选中的文字变大可以使用字体大小来设置

**Comment by hj901204** [comment]
那如果我需要通过选择某一行的几个文字进行设置成标题，你们的代码我该怎么改呢？我想进行二次开发

**Comment by hj901204** [comment]
那如果我需要通过选择某一行的几个文字进行设置成标题，你们的代码我该怎么改呢？我想进行二次开发

**Comment by UltramanWeiLai** [comment]
> 那如果我需要通过选择某一行的几个文字进行设置成标题，你们的代码我该怎么改呢？我想进行二次开发

我寻思，啥是标题？
如果你需要几个字设置成类是与标题的那种效果，完全可以使用 加粗和字号 的组合形式，如果想定制化菜单功能，可以看看文档里面的 自定义菜单 部分，群里面也有视频 公告上
