### ISSUE TITLE
上传图片的接口返回格式是否可以自定义

### ISSUE THREAD

**Issue by radish999** [wangeditor-team/wangEditor#3180]
配置服务端接口目前约定好的
`{
    "errno": 0,
    "data": []
}
`
像errno字段是否能支持修改呢 因为不同团队会有不同的返回格式例如{code: 200，message: "success","data":{}} 这种格式

**Comment by szxzxh** [comment]
看文档。。

**Comment by rsl140** [comment]
1. 请按格式提交issue，否则是不会受理的
2. 该问题可以去看[文档](https://doc.wangeditor.com/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/09-%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0.html)
3. customInsert
