### ISSUE TITLE
插入选择框和文字重叠，插入表格高度变小

### ISSUE THREAD

**Issue by GeekDonn** [wangeditor-team/wangEditor#3182]
## bug 描述

*低版本谷歌内核浏览器选择框靠前插入表格高度变小*

## 你预期的样子是？

*和官网展示相同*

## 浏览器及版本号

*cefsharp49（chromium49）*

## wangEditor 版本

*4.6.12*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 使用谷歌内核chromium49的浏览器，或者使用c#嵌入cefsharp49
- 在编辑器中添加多选框，添加表格
- 步骤三
![G7D0T0Q2$055~QNIS`GH9E](https://user-images.githubusercontent.com/23131977/114998460-8dd88f00-9ed3-11eb-881e-0f34e06c84c9.png)

**Comment by rsl140** [comment]
可否提供一个简单的复现环境，方便我们定位问题？

**Comment by wangfupeng1988** [comment]
普通的 chrome 浏览器（目前我看最新的是 v89），能复现这个问题吗？

**Comment by GeekDonn** [comment]
> 可否提供一个简单的复现环境，方便我们定位问题？



> 普通的 chrome 浏览器（目前我看最新的是 v89），能复现这个问题吗？



> 普通的 chrome 浏览器（目前我看最新的是 v89），能复现这个问题吗？

bu

> 普通的 chrome 浏览器（目前我看最新的是 v89），能复现这个问题吗？

高版本的复现不出来，69版本的选择框也会有问题，版本越低的问题越多

**Comment by UltramanWeiLai** [comment]
兼容性问题。
而且应该还是 标签 兼容性。
我们会根据具体情况，酌情进行修改，或给出相应的解决方案。

**Comment by blackhu0804** [comment]
请提供一个对应版本的浏览器安装包吧。
