### ISSUE TITLE
多文件上传为何要设定uploadFileName不能重复呢？

### ISSUE THREAD

**Issue by PIRANHACHAN** [wangeditor-team/wangEditor#3183]
## 问题描述
![微信图片_20210416215826](https://user-images.githubusercontent.com/24191934/115035187-e40ef780-9efe-11eb-9585-8ca062d14524.png)
![微信图片_20210416220117](https://user-images.githubusercontent.com/24191934/115035570-4962e880-9eff-11eb-8534-cf54bbf7f657.png)
后端为Node，在使用Multer处理多文件上传时遇到Unexpected Error错误，研究许久不明白为何报错，直到去翻了源码，才知道，多文件上传时，每个文件的name都不一样。
想问下，这样设计是出于什么考虑呢？

## wangEditor 版本
4.6.15

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
保证文件的唯一性。类似对象的KEY也不能重复呀~

**Comment by PIRANHACHAN** [comment]
> 保证文件的唯一性。类似对象的KEY也不能重复呀~

但Multer本身支持相同name的文件上传，这个name不是唯一标识吧？
![微信图片_20210419111658](https://user-images.githubusercontent.com/24191934/115176988-c6a97b80-a100-11eb-8417-6d9aaabb4ef1.png)

**Comment by rsl140** [comment]
1. filename是设置的formData的key，不是文件的filename
2. 你可以尝试搜索下如何用Multer接收formData
3. 或者可以使用 [自定义上传功能](https://doc.wangeditor.com/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/11-%E8%87%AA%E5%B7%B1%E5%AE%9E%E7%8E%B0%E4%B8%8A%E4%BC%A0%E5%8A%9F%E8%83%BD.html)

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复，暂且关闭
