### ISSUE TITLE
列表，在某些情况下，无法删除。

### ISSUE THREAD

**Issue by moketao** [wangeditor-team/wangEditor#3185]
## bug 重现步骤

clone 整个项目

按如下次序运行命令

`npm i`

`npm run start`

打开浏览器（Chrome 最新版或较新版）访问：

` http://127.0.0.1:8881/examples/index.html`

按 `F12` 打开调试面板，在浏览器 console 面板中输入命令：

`editor.txt.html('<p>d．&nbsp; 超时签收提醒，包括：首次文档的签收超时提醒，批量分发文档的签收超时提醒。</p><p><br/></p><ol><li><o:p></o:p></li></ol>')`

得到一个列表，

此列表，无法选中，我们期望可以删除，但**无法通过 del 按键删除**。

如果通过 backspace 按钮删除，是可以删除，代价是必须先把列表前面的全部内容删除，这似乎代价太大。

按以上步骤，可重现。

**Comment by UltramanWeiLai** [comment]
场景应该是复制粘贴 word 的时候吧？
我记得这个应该是会过滤掉 o:p 这个无意义的标签的。

**Comment by UltramanWeiLai** [comment]
还有哦，请麻烦按照模板进行 issue 的提交，否则是不受理的。
你需要提供足够详细的信息，我们才好去跟踪和复现。
