### ISSUE TITLE
关于图标提示不自动消失的bug

### ISSUE THREAD

**Issue by ahking** [wangeditor-team/wangEditor#3190]
提个bug，当点击插入图片图标时，关闭弹出的层，图标上方的提示不消失

**Comment by UltramanWeiLai** [comment]
请按照模板进行 issue 来提交，否则不受理。
另外，个人感觉这也不算 bug 吧？

**Comment by ahking** [comment]
不算bug么？已经关闭插入图片的层了，相应的提示当然应该消失
