### ISSUE TITLE
编辑器只读状态时，scroll-to-head功能失效

### ISSUE THREAD

**Issue by misumi111** [wangeditor-team/wangEditor#3191]
## bug 描述

编辑器只读状态时，scroll-to-head功能失效

## 你预期的样子是？

编辑器只读状态时，scroll-to-head功能有效

## 浏览器及版本号

chrome 89

## wangEditor 版本

4.6.13

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

设置编辑器只读，并使用scroll-to-head功能。

**Comment by misumi111** [comment]
初步判断应该是禁用编辑器后只显示生成的预览副本。
但是原编辑器dom状态被设为display none导致offsetParent为null，从而锚点滚动失效。

**Comment by UltramanWeiLai** [comment]
如果可以的话，请提供尽量详细的信息。
你目前说的这些，很难让我们理解是啥场景，要如何去操作和复现。

**Comment by misumi111** [comment]
> 如果可以的话，请提供尽量详细的信息。
> 你目前说的这些，很难让我们理解是啥场景，要如何去操作和复现。


https://codepen.io/xiaokyo-the-bold/pen/zYKvgPj

这是一个锚点示例
在这个示例最后加上
editor.disable();
禁止编辑器编辑，右侧锚点的点击滚动就会一并无效。

我理解禁止编辑器修改，不应该一起禁止锚点功能。

**Comment by cmingliang** [comment]
我也遇到了这个问题，调用editor.disable禁用编辑后，editor.scrollToHead失效

**Comment by misumi111** [comment]
@cmingliang 请问下这个问题有进度吗？还是需要我再提供什么？

**Comment by misumi111** [comment]
@UltramanWeiLai 请问下这个问题有进度吗？还需要我提供什么信息？

**Comment by UltramanWeiLai** [comment]
> @UltramanWeiLai 请问下这个问题有进度吗？还需要我提供什么信息？

目前等待安排成员进行处理。

**Comment by 86driver** [comment]
> @UltramanWeiLai 请问下这个问题有进度吗？还需要我提供什么信息？

正在处理～
