### ISSUE TITLE
自定义一个button，点击任意按钮控制台报错

### ISSUE THREAD

**Issue by Charon-1020** [wangeditor-team/wangEditor#3192]
## 问题描述

*点击菜单内的任意按钮，或点击编辑区域时，控制台会报一个typeerror的错误
![image](https://user-images.githubusercontent.com/76542931/115190482-aab2d380-a11a-11eb-8052-3a720ae5c00e.png)

*

## wangEditor 版本

*4.6.15*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 创建富文本实例
- 如下配置：
- editor.config.uploadImgServer = "/upload-img";
      editor.config.showLinkImg = false;
      editor.config.uploadVideoServer = "/api/upload-video";
      editor.config.showLinkVideo = false;
      const { BtnMenu } = E;
      class AlertMenu extends BtnMenu {
        constructor(editor) {
          const $elem = E.$(
            `<div class="w-e-menu">
              <button>源码</button>
            </div>`
          );
          super($elem, editor);
        }
        clickHandler() {
          // const editorHtml = editor.txt.html();
          // console.log(editorHtml);
          // editor.txt.text(`<p>${editorHtml}</p>`);
          console.log("11111111111111111111");
        }
      }
      const menuKey = "yuanmamenu";
      editor.menus.extend(menuKey, AlertMenu);
      editor.config.menus = editor.config.menus.concat(menuKey);
- 点击任意按钮或编辑区域就会报错

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复，暂且关闭
