### ISSUE TITLE
使用无序列表显示的不是点而是个空位符

### ISSUE THREAD

**Issue by hj901204** [wangeditor-team/wangEditor#3194]
## bug 描述

*在编辑器里面点击无序列表后，不显示点而是显示的是个空占位符*

## 你预期的样子是？

*能够正常显示点*

## 浏览器及版本号

*谷歌浏览器 版本：89.0.4389.128（正式版本）（x86_64）*

## wangEditor 版本

*wangeditor": "^4.6.14"*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 在编辑器里面点击无序列表后，不显示点而是显示的是个空占位符

**Comment by UltramanWeiLai** [comment]
注意是项目当中全局或者局部(class)下做了 reset.css 之类的样式重置，是否对 li 标签的 list-style 样式做了重置。
