### ISSUE TITLE
显示的图片统一大小

### ISSUE THREAD

**Issue by Charon-1020** [wangeditor-team/wangEditor#3195]
## 功能描述

*上传图片，统一图片的尺寸大小*

## 提炼几个功能点

- 上传时可以输入图片的宽高
- 上传后可以拖动图片修改大小
- 配置项中添加默认的图片宽度，高度自适应

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
可以考虑自定义图片媒体库（图床）功能，自定义图片的上传、剪切（阿里云 oss 都支持这些功能）
https://doc.wangeditor.com/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/16-%E4%BB%8E%E5%AA%92%E4%BD%93%E5%BA%93%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87.html

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复，暂且关闭
