### ISSUE TITLE
自定义字号希望可以设置多个，例如UEditor

### ISSUE THREAD

**Issue by a952454** [wangeditor-team/wangEditor#3196]
## 功能描述

自定义字号希望可以设置多个，例如UEditor

## 可参考的案例

http://fex.baidu.com/ueditor/
![image](https://user-images.githubusercontent.com/34675560/115209588-5286cc00-a130-11eb-8667-8adfb87e6869.png)

**Comment by UltramanWeiLai** [comment]
我们使用的 execCommand 只支持七个字号的设置。
我们正在筹备 execCommand 的自研，到时候就能自定义个数的字号了

**Comment by a952454** [comment]
> 我们使用的 execCommand 只支持七个字号的设置。
> 我们正在筹备 execCommand 的自研，到时候就能自定义个数的字号了

OK，感谢您的团队对于开源的贡献

**Comment by UltramanWeiLai** [comment]
> > 我们使用的 execCommand 只支持七个字号的设置。
> > 我们正在筹备 execCommand 的自研，到时候就能自定义个数的字号了
> 
> OK，感谢您的团队对于开源的贡献
