### ISSUE TITLE
富文本内复制的图片无法再次粘贴

### ISSUE THREAD

**Issue by qiang47199** [wangeditor-team/wangEditor#3197]
## bug 描述

*富文本内复制的图片无法再次粘贴，pasteIgnoreImg = false && pasteTextHandle 有log触发*

## 你预期的样子是？

*粘贴后展示图片*

## 浏览器及版本号

*Chrome v89.0.4389.90*

## wangEditor 版本

*v4.6.15*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

你们提供的示例https://codepen.io/xiaokyo-the-bold/pen/ZEpWByR?editors=1111随便上传图片复制粘贴就可以稳定复现

**Comment by rsl140** [comment]
我理解的复现步骤是：
1. 显示的设置pasteIgnoreImg = false
2. 上传一张图片
3. 复制粘贴这张图片

**Comment by clinfc** [comment]
@rsl140 交叉测试
