### ISSUE TITLE
通过新添加的菜单栏中的一个新的按钮用来显示后台返回的图片，第一张永远是烂图，然后再上传就是正常显示，但是报图片404

### ISSUE THREAD

**Issue by lilyliying** [wangeditor-team/wangEditor#3199]
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<script src="../../static/js/vue.js"></script>
		<link rel="stylesheet" href="../../static/css/page/videoOfVisualization/font.css">
		<script type="text/javascript" src="../../static/js/baidu_hlsPlayer/player/cyberplayer.js"></script>
		<script src="../../static/js/jquery-1.10.2.min.js" type="text/javascript"></script>
		<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/wangeditor@4.6.15/dist/wangEditor.min.js" type="text/javascript"></script>
	</head>
	<body>
		<div class="wrap">
			<div id="editor"> </div>
		</div>
	</body>
	<script>
		new Vue({
			el: '.wrap',
			index:0,
			data: {
				editor: '',
				cameraList: [],
				select: '',
				html:'',
				htmlData: '',
				selectInfo: {}, 
				restaurantInfo: {},
				isSubmit: true,
				dialogVisible: false
			}, 
			mounted() { 
				this.createEditor()
			},
			methods: {
				createEditor() {
					let _this = this
					var E = window.wangEditor
					_this.editor = new E('#editor')   
					// 自定义菜单配置
					const {BtnMenu} = E
					class illustrateMenu extends BtnMenu {
					    constructor(editor) {
					        const $elem = E.$(
					            `<div class="w-e-menu">
					                <i class="iconfont icon-paizhao"></i>
					            </div>`
					        )
					        super($elem, editor)
					    }
					    // 菜单点击事件
					    clickHandler() {   _this.getCapturePicture()  }
					    tryChangeActive() {  }
					}
					_this.editor.menus.extend('illustrateMenu', illustrateMenu)
					_this.editor.config.menus = [   'bold',    'head',   'link',   'italic',   'underline',   'image',  'illustrateMenu' ] 
					_this.editor.create()

				},
				getCapturePicture() {
					let args = { deviceId: 'XXX', channelId: 'XX' }  
					axios.get('XXXX', {
						params: args
					}).then(data => { 
						if (data.data.code === 'SUCCESS') {  
							//  this.editor.txt.html('<img src="'+data.data.result+'"/>');
							//  console.log(this.editor.txt.html) 
							// console.log(data.data)
							let url = data.data.result  
							 var json = this.editor.txt.getJSON() // 获取 JSON 格式的内容
							 console.log(json)
							 let item = { tag: 'p', attrs: [], children: [{ tag: 'img', attrs: [{ name: 'src', value: url }], children: [] }]} 
							//console.log(item)
							 json.push(item) 
							 this.editor.txt.setJSON(json)  
							// console.log(json)
						}
					}).catch(error => {
						console.log(error)
					}) 
				}
			}
		})
	</script>
</html>

**Comment by rsl140** [comment]
请按issue模版提交，否则是不会受理的
