### ISSUE TITLE
vue中使用wangeditor以及elementui，无法通过rules进行表单校验，blur,change等事件无法在rules中触发

### ISSUE THREAD

**Issue by guoyucloud** [wangeditor-team/wangEditor#3201]
## bug 描述

*vue中使用wangeditor以及elementui，无法通过rules进行表单校验，blur,change等事件无法在rules中触发*

## 你预期的样子是？

*正常触发rules*

## 浏览器及版本号

*chrome任意版本*

## wangEditor 版本

*v4.6.15*

## 官网能否复现该 bug ？

不能，因为官网没有elementui

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 弄一个elementui
- 步骤二
- 做一个表单校验使用rules进行校验
- 步骤三
- 无法通过rules进行校验，因为blur，change等无法触发。

**Comment by rsl140** [comment]
可以参考[回调函数](https://doc.wangeditor.com/pages/04-%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0/)
执行onchange和onblur实现校验

**Comment by guoyucloud** [comment]
@rsl140 这个我已经做了，只是发现不支持rules，因此咨询一下这个问题。那我就继续按照当前推荐方式去使用了。
麻烦帮忙看一下我提出的另一个问题吧 #3200  #3206 ，我看确认为bug了，我提交了一个修改可以解决这个问题，自测过没问题。不过不知道解决这个问题的方式是否成熟，希望可以抽出宝贵的时间帮忙看一下能否完美解决该问题。
