### ISSUE TITLE
关于多语言问题，key能否换成英文

### ISSUE THREAD

**Issue by heaven-hub** [wangeditor-team/wangEditor#3202]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by heaven-hub** [comment]
总体不错，就是多语言的key是中文的

**Comment by rsl140** [comment]
目前暂时不考虑更换，后期插件化后会有相应调整。感谢您的反馈~
