### ISSUE TITLE
无法正确黏贴

### ISSUE THREAD

**Issue by HJK409** [wangeditor-team/wangEditor#3203]
## bug 描述

*4.6.12及以后的的版本选择富文本中一行内容中的部分文档进行复制粘贴，无法复制，4.6.6以前的没有问题，但是4.6.6的版本在选择word文档，输入框中的内容时无法复制到光标指定的位置

## 你预期的样子是？

*可以正确复制到光标指定的位置*

## 浏览器及版本号

*google*

## wangEditor 版本

*4.6.6 ，4.6.12*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 选择一行中的部分内容ctrl+c
- 指定位置ctrl+v
-

**Comment by rsl140** [comment]
不太明白是什么意思，是指复制word中的内容到编辑器
 还是复制编辑器里本身的内容到编辑器内光标所在的位置

**Comment by HJK409** [comment]
在比较新的版本上（4.6.12之后的版本吧）无法复制编辑器本身的内容，比如官网上的编辑器，复制“轻量级”三个字后无法粘贴。
在4.6.6的版本上复制word中的内容会有些问题

**Comment by rsl140** [comment]
1. 未复现 2. 请升级到最新版
![QQ20210421-113931-HD](https://user-images.githubusercontent.com/7655291/115493451-62b8bb80-a296-11eb-9943-7b3fc26826ee.gif)

**Comment by HJK409** [comment]
好的谢谢，火狐浏览器不行

**Comment by rsl140** [comment]
> 好的谢谢，火狐浏览器不行

火狐也尝试了 也是没有复现
