### ISSUE TITLE
工具栏加固定的功能

### ISSUE THREAD

**Issue by hj901204** [wangeditor-team/wangEditor#3209]
## 功能描述

*希望能给工具栏加个固定的功能，方便富文本内容过长过高的情况下能够不用滚动到上面操作工具栏*

## 提炼几个功能点

- 工具栏加固定功能
- 也可以解除工具栏固定

## 原型图

*无，上面的描述应该很仔细了不需要原型图，就加固定*

## 可参考的案例

*无*

**Comment by rsl140** [comment]
[参考文档](https://doc.wangeditor.com/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/03-%E8%8F%9C%E5%8D%95%E5%92%8C%E7%BC%96%E8%BE%91%E5%8C%BA%E5%9F%9F%E5%88%86%E7%A6%BB.html)

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复，暂且关闭
