### ISSUE TITLE
一段文字截取前几个字回车，这几个字设置成标题

### ISSUE THREAD

**Issue by hj901204** [wangeditor-team/wangEditor#3210]
## bug 描述

*一段文字截取前几个字回车，然后将这几个字设置成标题，下面的文字也变成标题了*

## 你预期的样子是？

*截取的前几个字设置成标题后不影响下面一段文字，因为前面几个字回车后是单独的p标签*

## 浏览器及版本号

*谷歌浏览器 版本：89.0.4389.128（正式版本）（x86_64）*

## wangEditor 版本

*wangeditor": "^4.6.14"*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 将光标放在一段文字中间回车
- 然后将回车后的前面一段文字后双击选中后设置成标题
- 后面一段也变成标题了
![image](https://user-images.githubusercontent.com/35586822/115519762-15e7db80-a2bc-11eb-80a5-f351958c705a.png)

![image](https://user-images.githubusercontent.com/35586822/115520200-7bd46300-a2bc-11eb-9bf5-f3db547a6eab.png)

**Comment by rsl140** [comment]
您好 没有复现该问题

**Comment by hj901204** [comment]
不能拿鼠标按着选中，是在旁边双击选中

**Comment by rsl140** [comment]
![QQ20210423-092327-HD](https://user-images.githubusercontent.com/7655291/115804580-da612480-a415-11eb-851a-0331abe6e2ab.gif)

**Comment by rsl140** [comment]
该问题长时间未回复，暂且关闭
