### ISSUE TITLE
使用图片上传功能图片无法正常回显

### ISSUE THREAD

**Issue by SurgeBillows** [wangeditor-team/wangEditor#3216]
## bug 描述

*使用图片上传功能图片无法正常回显*

## 你预期的样子是？

*封装为一个组件，在不同页面引入正常使用*

## 浏览器及版本号

*Google chrome 90.0.4430.85*

## wangEditor 版本

*4.6.15*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 封装一个富文本组件
- 步骤二
- 在后台管理首页引入使用，并在其他菜单页面表单使用
- 步骤三
- 启动项目加载首页，去其他页面的表单内使用图片上传功能

**Comment by rsl140** [comment]
建议尝试在一个简单的环境下实现该功能，看是否能够复现。（避免因其他功能而产生的影响。）

**Comment by UltramanWeiLai** [comment]
该 issue 长时间无人回复，暂且关闭
