### ISSUE TITLE
文本框粘贴3万字，页面崩溃

### ISSUE THREAD

**Issue by dajieda123** [wangeditor-team/wangEditor#3217]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本
4.6.2
*请输入内容……*
直接粘贴2万到3万字左右的文本到编辑器后，出现页面奔溃
## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by baozi-wei** [comment]
我也遇到了

**Comment by 15601342019** [comment]
我也是，这个能处理吗，不然老板要换富文本了

**Comment by rsl140** [comment]
没有复现该问题，可否执行以下步骤方便我们定位问题：
1. 尝试更新到最新版本是否还有该问题
2. 如果有可否提供更详细的内容比如：是粘贴的来自wps或者offic中的文本，或者用的什么样的浏览器以及文本内容中是否包含特殊内容等

**Comment by 15601342019** [comment]
> 没有复现该问题，可否执行以下步骤方便我们定位问题：
> 
> 1. 尝试更新到最新版本是否还有该问题
> 2. 如果有可否提供更详细的内容比如：是粘贴的来自wps或者offic中的文本，或者用的什么样的浏览器以及文本内容中是否包含特殊内容等

官网可以复制黏贴成功，项目中使用4.5.0版本复制黏贴失败，版本从4.5.0更新到4.6.16，结果报错，截图如下：
![image](https://user-images.githubusercontent.com/33148177/115982496-366ea900-a5ce-11eb-9c36-fc6e192f5504.png)

**Comment by rsl140** [comment]
> 官网可以复制黏贴成功，项目中使用4.5.0版本复制黏贴失败，版本从4.5.0更新到4.6.16，结果报错，截图如下：
> ![image](https://user-images.githubusercontent.com/33148177/115982496-366ea900-a5ce-11eb-9c36-fc6e192f5504.png)

可能是挂载的ID节点有误导致的。因为没有详细内容用于定位问题。
建议新起一个纯净的项目只引入wangEditor后查看是否还会有该问题

**Comment by 15601342019** [comment]
> > 官网可以复制黏贴成功，项目中使用4.5.0版本复制黏贴失败，版本从4.5.0更新到4.6.16，结果报错，截图如下：
> > ![image](https://user-images.githubusercontent.com/33148177/115982496-366ea900-a5ce-11eb-9c36-fc6e192f5504.png)
> 
> 可能是挂载的ID节点有误导致的。因为没有详细内容用于定位问题。
> 建议新起一个纯净的项目只引入wangEditor后查看是否还会有该问题

是的，需要在完成dom节点渲染后再创建editor对象，这个问题已解决。现在更新到最新4.6.16版本富文本，一万多字可以黏贴成功了，但是很慢，12000字大概需要1分30秒，官网就很快，这个从哪里能排查一下问题吗

**Comment by rsl140** [comment]
> > > 官网可以复制黏贴成功，项目中使用4.5.0版本复制黏贴失败，版本从4.5.0更新到4.6.16，结果报错，截图如下：
> > > ![image](https://user-images.githubusercontent.com/33148177/115982496-366ea900-a5ce-11eb-9c36-fc6e192f5504.png)
> > 
> > 
> > 可能是挂载的ID节点有误导致的。因为没有详细内容用于定位问题。
> > 建议新起一个纯净的项目只引入wangEditor后查看是否还会有该问题
> 
> 是的，需要在完成dom节点渲染后再创建editor对象，这个问题已解决。现在更新到最新4.6.16版本富文本，一万多字可以黏贴成功了，但是很慢，12000字大概需要1分30秒，官网就很快，这个从哪里能排查一下问题吗

可以尝试一下在performance录一下看看是哪部分耗时比较长

**Comment by 15601342019** [comment]
尝试使用performance录一下。12000字的富文本内容，全选删除操作用时约50秒，耗时主要体现在Rendering部分，performance记录如下图，
![image](https://user-images.githubusercontent.com/33148177/116230891-be99ad80-a78a-11eb-834f-9f689b2fa143.png)

主线程中发现的问题，performance记录截图如下：
![image](https://user-images.githubusercontent.com/33148177/116232848-3b2d8b80-a78d-11eb-9705-e95d90a2edcf.png)
![image](https://user-images.githubusercontent.com/33148177/116232874-42549980-a78d-11eb-9445-892aaafc3431.png)
调用栈信息performance记录截图如下：
![image](https://user-images.githubusercontent.com/33148177/116233069-7203a180-a78d-11eb-9e3d-fe8352602751.png)
耗时主要集中在Layout和 Recalclate Style，但是看不到具体哪里的问题

**Comment by wangfupeng1988** [comment]
@15601342019 我看你说官网没问题。
那还需要你提供一个详细的复现步骤，先让我们复现问题，然后再看如何解决。

**Comment by rsl140** [comment]
长时间未回复，暂时关闭
