### ISSUE TITLE
网页右键复制图片粘贴后出现富文本内会出现两个一样的图片

### ISSUE THREAD

**Issue by zhoucat** [wangeditor-team/wangEditor#3218]
## bug 描述

*复制图片粘贴后出现富文本内会出现两个一样的图片，插入了两个img标签*

![image](https://user-images.githubusercontent.com/21006928/115843142-19f93200-a451-11eb-8b93-cae017ce489a.png)

## 你预期的样子是？

*粘贴后只出现一个图片*

## 浏览器及版本号

*chrome最新*

## wangEditor 版本

*V4.6.4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

-  选择一个网页上的图片，右键复制图片
- 粘贴到富文本框
- 出现两个一样的图片

**Comment by lkw199711** [comment]
粘贴反应正常 bug无法复现
