### ISSUE TITLE
增加点击图片给图片添加跳转链接功能，类似微信公众号

### ISSUE THREAD

**Issue by cookie-zhang** [wangeditor-team/wangEditor#3223]
## 功能描述
近期公司有一个需求，就是在秀米等编辑器中编辑好的文章，复制到富文本编辑器，第一：格式不能乱，第二：图片要上传到我们自己的服务器，第三：点击图片可以给图片添加跳转链接。（解决方式：第一第三修改了源码）

## 提炼几个功能点
点击图片，给图片添加跳转链接

## 原型图
![image](https://user-images.githubusercontent.com/33242308/115981220-e3442880-a5c4-11eb-8a71-78455f613a8d.png)

 ## 已实现代码
`
// 修改原型
DomElement.prototype = {
    constructor: DomElement,
// ......
    // 增加图片跳转链接 zjf
    appendGoLink: function append(goLink) {
        return this.forEach(function (elem) {
            var ele = document.createElement('a')
            elem.parentNode.replaceChild(ele, elem)
            ele.appendChild(elem)
            ele.href = goLink
            ele.setAttribute('target', '_blank')
            ele.setAttribute('style', 'float:left')
        })
    },
_createEditPanel: function _createEditPanel() {
        var editor = this.editor;

        // id
        var width30 = getRandom('width-30');
        var width50 = getRandom('width-50');
        var width100 = getRandom('width-100');
        var delBtn = getRandom('del-btn');
        // zjf
        var goLink = getRandom('goLink')
        var goLinkBtnId = getRandom('goLinkBtnId')

        // tab 配置
        var tabsConfig = [{
            title: '编辑图片',
            // tpl: '<div>\n                    <div class="w-e-button-container" style="border-bottom:1px solid #f1f1f1;padding-bottom:5px;margin-bottom:5px;">\n                        <span style="float:left;font-size:14px;margin:4px 5px 0 5px;color:#333;">\u6700\u5927\u5BBD\u5EA6\uFF1A</span>\n                        <button id="' + width30 + '" class="left">30%</button>\n                        <button id="' + width50 + '" class="left">50%</button>\n                        <button id="' + width100 + '" class="left">100%</button>\n                    </div>\n                    <div class="w-e-button-container">\n                        <button id="' + delBtn + '" class="gray left">\u5220\u9664\u56FE\u7247</button>\n                    </dv>\n                </div>',
            tpl: '<div>\n                    <div class="w-e-button-container" style="border-bottom:1px solid #f1f1f1;padding-bottom:5px;margin-bottom:5px;">\n                        <span style="float:left;font-size:14px;margin:4px 5px 0 5px;color:#333;">\u6700\u5927\u5BBD\u5EA6\uFF1A</span>\n                        <button id="' + width30 + '" class="left">30%</button>\n                        <button id="' + width50 + '" class="left">50%</button>\n                        <button id="' + width100 + '" class="left">100%</button>\n                    </div>\n        <div>\n                    <input id="' + goLink + '" type="text" class="block" placeholder="\u8d85\u94fe\u63a5\u5730\u5740"/></td>\n                    <div class="w-e-button-container">\n                        <button id="' + goLinkBtnId + '" class="right">\u63D2\u5165</button>\n                    </div>\n                </div>\n            <div class="w-e-button-container">\n                        <button id="' + delBtn + '" class="gray left">\u5220\u9664\u56FE\u7247</button>\n                    </dv>\n                </div>',
         }]   
// ....
    },
// ....
`
## 可参考的案例
微信公众号

**Comment by rsl140** [comment]
图片可以支持超链接地址的功能

**Comment by rsl140** [comment]
您好，该功能暂时做不了，在具体的设计实现方面比较复杂。
不过该功能后面会考虑加上的，只是暂时来不急做。
其次，建议您升级到V4版本
