### ISSUE TITLE
請問自定義toolbar為什麼不顯示提示詞？

### ISSUE THREAD

**Issue by heaven-hub** [wangeditor-team/wangEditor#3224]
## 請問自定義toolbar為什麼不顯示提示詞？

自定義功能bar之後，提示詞不能顯示

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？
 是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
editor.config.lang = 'en'
editor.i18next = window.i18next
editor.config.languages['en'] = {
    wangEditor: {
      请输入正文: 'please enter the text!',
    }
}

**Comment by heaven-hub** [comment]
這個問題解決了，謝謝，還有就是toolbar的提示不出現，用原始的只有第二行有提示，自定義的提示不出現

**Comment by rsl140** [comment]
> 這個問題解決了，謝謝，還有就是toolbar的提示不出現，用原始的只有第二行有提示，自定義的提示不出現

什么意思？你自定义的多语言么？

**Comment by UltramanWeiLai** [comment]
问题，描述的有点太抽象了，详细具体一点我们才好理解和复现。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
