### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by long1316371134** [wangeditor-team/wangEditor#3227]
## 问题描述

使用官网默认案例启动后报错：Uncaught (in promise) Error: 无效的节点选择器：div1

## wangEditor 版本

"wangeditor": "^4.6.3"

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- idea终端切换到web目录下npm命令安装
- 步骤二
- 页面导入依赖
       import E from "wangeditor"
        const editor = new E("#div1")
         editor.create()
 - 步骤三
运行页面报错：Uncaught (in promise) Error: 无效的节点选择器：div1

**Comment by lvxm0** [comment]
请问怎么解决的？ 我也是这个版本，然后报错了无效的节点选择器

**Comment by lvxm0** [comment]
之前还是ok的，然后今天重装了一下依赖，结果报错了

**Comment by long1316371134** [comment]
我用的vue3，需要把
const editor = new E('#div1')
editor.create()
这个加到onmounted中


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月26日(星期一) 下午5:42
***@***.***&gt;;
抄送:&nbsp;"@***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 启动报错 (#3227)





 
之前还是ok的，然后今天重装了一下依赖，结果报错了

**Comment by caiNiao0820** [comment]
React hook里面启动报错该怎么解决呢
![image](https://user-images.githubusercontent.com/51197178/117482726-5ec7b180-af97-11eb-8f4a-38fb658b7839.png)
