### ISSUE TITLE
全选删除表格里最后一行最后一栏的文本内容时，表格外的文本内容会走进表格里

### ISSUE THREAD

**Issue by immrl** [wangeditor-team/wangEditor#3228]
## bug 描述

全选删除表格里最后一行最后一栏的文本内容时，表格外的文本内容会走进表格里面

## 你预期的样子是？

全选删除表格里最后一行最后一栏的文本内容时，只会删除这个cell的内容而不应该影响表格以外的内容

## 浏览器及版本号

Chrome

## wangEditor 版本

v4.6.15

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 双击全选表格里最后一行最后一栏的文本内容
<img width="1198" alt="螢幕截圖 2021-04-26 13 40 37" src="https://user-images.githubusercontent.com/2060488/116034603-24f0d400-a696-11eb-8e6d-162f382b2199.png">

- 按退格键(backspace)删除文本内容
<img width="1170" alt="螢幕截圖 2021-04-26 13 40 44" src="https://user-images.githubusercontent.com/2060488/116034554-0db1e680-a696-11eb-9e8c-219210f0e213.png">

**Comment by rsl140** [comment]
没有复现该问题

**Comment by immrl** [comment]
Macbook + Chrome下用touchpad双击全选可以复现哦

**Comment by immrl** [comment]
Macbook + Chrome下用touchpad双击最后一行最后一列那个cell会自动全选cell里的文本内容，这样就可以复现

**Comment by immrl** [comment]
我试了两次，第一次是正常的，然后在重试一次就会复现 （期间没有刷新页面）

**Comment by rsl140** [comment]
第二次执行该操作的时候会出现该问题。
第一次操作后导致td标签中多了一个br标签
![image](https://user-images.githubusercontent.com/7655291/116043589-71daa780-a6a2-11eb-89d8-e9b03ea5d188.png)
