### ISSUE TITLE
如何将黏贴过来的文本样式自动匹配旁边文本的样式

### ISSUE THREAD

**Issue by hello-Div180** [wangeditor-team/wangEditor#3229]
我用的版本是4.6.3

**Comment by hello-Div180** [comment]
![image](https://user-images.githubusercontent.com/65322434/116082464-027aad00-a6ce-11eb-91a2-387129ec783c.png)
划线的是我已经用谷歌翻译过滤掉样式，并黏贴进来的，它旁边的字体这字体是不一样

**Comment by UltramanWeiLai** [comment]
请按照模板提交 issue 否则是不受理的。
谷歌翻译的输入框里面的文字也是有相应的样式的。
正常情况下复制粘贴进来的纯文本是会自动匹配当前段落的样式的。
比如：
![image](https://user-images.githubusercontent.com/23336585/116112059-ca816300-a6e9-11eb-93b8-23576e7fdc82.png)
另外建议先升级到最新的版本
