### ISSUE TITLE
黏贴过来的纯文本，不能自动匹配旁边文字的样式

### ISSUE THREAD

**Issue by hello-Div180** [wangeditor-team/wangEditor#3230]
## 问题描述
黏贴过来的纯文本，不能自动匹配旁边文字的样式
*请输入遇到的问题...*
![image](https://user-images.githubusercontent.com/65322434/116173613-7a34f000-a73f-11eb-9f86-903f7a5ca43d.png)
![image](https://user-images.githubusercontent.com/65322434/116173634-828d2b00-a73f-11eb-83cc-4042e6f21824.png)
可以看出划红线的字体跟旁边的字体不一样，旁边的文字我是在设置了字体大小
## wangEditor 版本
4.6.16
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤
能
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 纯手打一段文字，并设置一个h1标题
- 
![image](https://user-images.githubusercontent.com/65322434/116174097-56be7500-a740-11eb-93a5-793d8acea9ed.png)

- 步骤二
- 在文字后黏贴纯文本
- 步骤三
- 就可以看出黏贴的那段话不在<font>...</font>中
- 
![image](https://user-images.githubusercontent.com/65322434/116174097-56be7500-a740-11eb-93a5-793d8acea9ed.png)

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/116193407-e58fb980-a761-11eb-9f1f-e8ab7ac630ef.png)
未复现该问题
![image](https://user-images.githubusercontent.com/7655291/116193458-fd673d80-a761-11eb-8c24-21d493a51f3b.png)

**Comment by hello-Div180** [comment]
@rsl140 先写一段字号为32px的文字，然后在后面黏贴纯文本。纯文本就不匹配32px的字号

**Comment by rsl140** [comment]
> @rsl140 先写一段字号为32px的文字，然后在后面黏贴纯文本。纯文本就不匹配32px的字号

是在设置了字号大小后然后在粘贴是么。这个是符合预期的。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
