### ISSUE TITLE
点击图片放大功能

### ISSUE THREAD

**Issue by hj901204** [wangeditor-team/wangEditor#3235]
## 功能描述

*点击上传后的图片实现放大预览功能*

## 提炼几个功能点

- 点击富文本里面的图片实现放大预览功能

## 原型图

*无*

## 可参考的案例

*无*

**Comment by wangfupeng1988** [comment]
预览或者查看文章时，才会有这个功能。
编辑器里不会有这个功能。

**Comment by dengshicheng1996** [comment]
> 只读模式下，会有放大图片的需求存在

**Comment by dengshicheng1996** [comment]
> 

能否提供一个简易demo，我是在react 里面使用
