### ISSUE TITLE
获取选区所在节点在ie11和火狐下与预期不符。

### ISSUE THREAD

**Issue by HAM2506** [wangeditor-team/wangEditor#3236]
由于wangeditor的菜单样式与ui不符，于是自定义了菜单栏，内容包括：字体颜色、字体大小、粗体、斜体、下划线。

想获取光标所在的dom各个字体属性实现和菜单做联动，比如点击选择光标位置或者键盘左右选择时，获取光标所在左边的文字的颜色、大小等，实现菜单的颜色、大小等与光标左边的文字做联动。

用editor.cmd.queryCommandValue和queryCommandState在谷歌浏览器基本实现需求，但是发现在火狐和ie11获取文字属性时，经常会错乱，并不像谷歌表现的会获取到光标左侧文字属性，经常是光标右边的文字属性或者光标上一次所在的文字属性。

于是改变策略使用editor.selection.getSelectionContainerElem().elems[0]去做，问题还是和editor.cmd.queryCommandValue类似。

请问一下大佬如何解决？或者有其他方案吗。

**Comment by wangfupeng1988** [comment]
请按照 issue 模板，重新提交问题。

不符合模板格式的，不予受理，请体谅。
