### ISSUE TITLE
获取所在dom节点在不同浏览器表现不一致。

### ISSUE THREAD

**Issue by HAM2506** [wangeditor-team/wangEditor#3237]
## 问题描述

用editor.cmd.queryCommandValue和queryCommandState在火狐和ie11获取文字属性时，并不像谷歌表现的会获取到光标左侧文字属性，经常是光标右边的文字属性或者光标上一次所在的文字属性。

使用editor.selection.getSelectionContainerElem().elems[0]和editor.cmd.queryCommandValue一样。

## wangEditor 版本

4.6.16

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

在实例上添加编辑区点击事件，点击事件中打印editor.cmd.queryCommandValue或者editor.selection.getSelectionContainerElem().elems[0]，点击编辑区光标改变时，在火狐和ie11中打印出的内容与谷歌不一致。

**Comment by rsl140** [comment]
描述的有点抽象，不是太明白是什么意思。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
