### ISSUE TITLE
ie11 下 设置行高无效，在多行文本情况下，设置非1行高再设置行高为1，第一行消失

### ISSUE THREAD

**Issue by guoyucloud** [wangeditor-team/wangEditor#3238]
## bug 描述

*ie11 下 设置行高无效，在多行文本情况下，设置非1行高再设置行高为1，第一行消失*

## 你预期的样子是？

*正常显示*

## 浏览器及版本号

*ie11*

## wangEditor 版本

*v4.6.16*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
- 输入几行内容
- 步骤二
- 选中文字设置行高
- 步骤三
- 设置行高为3，无效，设置行高为1，有可能出现第一行文字消失。

**Comment by guoyucloud** [comment]
您好，请教一下一般时候更新版本，我们遇到了已经解决了的bug，希望早点更新到 v4.6.17
@wangfupeng1988

**Comment by rsl140** [comment]
> 您好，请教一下一般时候更新版本，我们遇到了已经解决了的bug，希望早点更新到 v4.6.17
> @wangfupeng1988

一般周四会更新

**Comment by guoyucloud** [comment]
> 您好，请教一下一般时候更新版本，我们遇到了已经解决了的错误，希望早点更新到v4.6.17
> @ wangfupeng1988



> > 您好，请教一下一般时候更新版本，我们遇到了已经解决了的bug，希望早点更新到 v4.6.17
> > @wangfupeng1988
> 
> 一般周四会更新

好的，谢谢。

**Comment by guoyucloud** [comment]
> > 您好，请教一下一般时候更新版本，我们遇到了已经解决了的bug，希望早点更新到 v4.6.17
> > @wangfupeng1988
> 
> 一般周四会更新

您好，请问本周更新吗，今天周五了还没有看到版本的变化。

**Comment by shi-lai-mu** [comment]
> > > 您好，请教一下一般时候更新版本，我们遇到了已经解决了的错误，希望早点更新到v4.6.17 
> > > @ wangfupeng1988
> > 
> > 
> > 一般周四会更新
> 
> 您好，请问本周更新吗，今天星期五了还没有看到版本的变化。

因五一原因本周没有发布计划，要等到下周四更新的
