### ISSUE TITLE
缩进文本，为什么用的是padding-left；而不是text-indent？

### ISSUE THREAD

**Issue by kakaC1879** [wangeditor-team/wangEditor#3240]
## 问题描述

我在进行一段文本进行缩进时（中文排版常见的 首行缩进），居然是整段文本缩进，有点不理解，为何这样设计？

**Comment by UltramanWeiLai** [comment]
字面上的区别，缩进是缩进，首行缩进是首行缩进。
如果需要首行缩进的效果，可以使用 自定义菜单 的能力根据 缩进写一个即可。
哔哩哔哩 搜索 wangEditor 有相关教学视频可以看，群公告里面也有链接。

**Comment by UltramanWeiLai** [comment]
该 issue 长时间没有人回复，暂且关闭

**Comment by Zachary-zm** [comment]
必须得吐槽一下

**Comment by UltramanWeiLai** [comment]
> 必须得吐槽一下

吐槽啥？
实际上在大部分编辑器里面 **缩进** 都是整个段落的缩进，哪怕是 word 里面，word 里面的需要首字母缩进也是在段落里面的特殊缩进里面选择首行缩进才行是吧
只是在有意识想要 **首行缩进** 的时候，才会想到觉得为什么不是 **首行缩进**，实际上自定义一个首行缩进的菜单功能即可，也不难
而且 缩进是缩进，首行缩进是首行缩进，表达出的意思都是不一样的

**Comment by Zachary-zm** [comment]
> > 必须得吐槽一下
> 
> 吐槽啥？
> 实际上在大部分编辑器里面 **缩进** 都是整个段落的缩进，哪怕是 word 里面，word 里面的需要首字母缩进也是在段落里面的特殊缩进里面选择首行缩进才行是吧
> 只是在有意识想要 **首行缩进** 的时候，才会想到觉得为什么不是 **首行缩进**，实际上自定义一个首行缩进的菜单功能即可，也不难
> 而且 缩进是缩进，首行缩进是首行缩进，表达出的意思都是不一样的

所以要吐槽，确实不难，所以你们加起来应该也不难。 之前也有人提了，也加入了todolist，这么久了也没有回应。大部分编辑器是没有，但是我们为什么不能做第一个有这样设置的编辑器呢？只是吐槽，自己已经加了自定义了。

**Comment by UltramanWeiLai** [comment]
> > > 必须得吐槽一下
> > 
> > 
> > 吐槽啥？
> > 实际上在大部分编辑器里面 **缩进** 都是整个段落的缩进，哪怕是 word 里面，word 里面的需要首字母缩进也是在段落里面的特殊缩进里面选择首行缩进才行是吧
> > 只是在有意识想要 **首行缩进** 的时候，才会想到觉得为什么不是 **首行缩进**，实际上自定义一个首行缩进的菜单功能即可，也不难
> > 而且 缩进是缩进，首行缩进是首行缩进，表达出的意思都是不一样的
> 
> 所以要吐槽，确实不难，所以你们加起来应该也不难。 之前也有人提了，也加入了todolist，这么久了也没有回应。大部分编辑器是没有，但是我们为什么不能做第一个有这样设置的编辑器呢？只是吐槽，自己已经加了自定义了。

因为优先级不高，这个功能的应用场景比较少，而且实现起来也不困难。
所以会优先其他更重要的东西。
