### ISSUE TITLE
如何取消代码(code)

### ISSUE THREAD

**Issue by philwu** [wangeditor-team/wangEditor#3243]
## 问题描述

一块代码不能恢复成非代码

## wangEditor 版本

4.6.17 (另建议在dist生成的.js文件中加上包含版本的comment，以便了解自己用的是哪个版本)

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

- 步骤一： 输入任意两行字
- 步骤二： 选中其中一行字，按代码按钮，这行字变成了代码。
- 步骤三： 再次选中这行字，按代码按钮，没有反应。我期望的是，选中的这行代码变成非代码。

**Comment by philwu** [comment]
引用按钮(quote)，就没有这个问题

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
