### ISSUE TITLE
不设置表头的表格某行没数据无高度

### ISSUE THREAD

**Issue by 1059997476** [wangeditor-team/wangEditor#3245]
## bug 描述
不设置表头的表格如果某一整行没有数据，则这一行的高度显示时会被置为空

## 你预期的样子是？
在前端显示的时候每个tr标签会有个空格(&nbsp;)但传给后端时没有空格，使用导致回显的时候tr标签里面没东西

## 浏览器及版本号

chrome

## wangEditor 版本

4.6.16

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 随便加入一个表，然后某一整行没有数据
- 步骤二把整个table下的html内容传给后端
- 步骤三 发现tr里面的&nbsp;没带过去，但在设置表格时，tr里面有个&nbsp

**Comment by rsl140** [comment]
不是太明白，看了下表格结构里面并没有&nbsp
![image](https://user-images.githubusercontent.com/7655291/116784951-94692800-aac9-11eb-92d0-bc9698e1aaf9.png)

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
