### ISSUE TITLE
在编辑区域偶尔换行无效，也不报错

### ISSUE THREAD

**Issue by EmptyG2018** [wangeditor-team/wangEditor#3248]
## bug 描述

在编辑区域偶尔换行无效，也不报错

## 你预期的样子是？

在编辑区域能够正常换行

## 浏览器及版本号

版本 90.0.4430.93（正式版本） （64 位）

## wangEditor 版本

^4.6.17

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一：暂无任何规律
- 步骤二：暂无任何规律
- 步骤三：暂无任何规律

**Comment by rsl140** [comment]
需要一个具体的复现步骤，才能知道如何解决该问题

**Comment by joywins-y** [comment]
在ProTableDrawerForm中使用wangeditor，在编辑区域中按回车键时，会直接自动保存，请问有什么办法可以设置回车键只起到换行的作用？

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
