### ISSUE TITLE
有設置showLinkImgAlt，但不起作用

### ISSUE THREAD

**Issue by JasonFes** [wangeditor-team/wangEditor#3249]
## 问题描述
![image](https://user-images.githubusercontent.com/16607607/117026262-38eba400-ad2e-11eb-853a-ee4263ee1cb1.png)
e
有設置showLinkImgAlt，但不起作用

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by JasonFes** [comment]
![Uploading image.png…]()

**Comment by JasonFes** [comment]
![image](https://user-images.githubusercontent.com/16607607/117026987-d2b35100-ad2e-11eb-8fae-2b4536d0b002.png)

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/117238973-75b7b800-ae60-11eb-8519-74754e41391e.png)
未复现该问题

**Comment by rsl140** [comment]
长时间未回复，暂且关闭。
