### ISSUE TITLE
全选文字以后，设置居中样式， 无法生效

### ISSUE THREAD

**Issue by lvxm0** [wangeditor-team/wangEditor#3250]
## bug 描述

全选文字(全选所有文字/ 选部分文字)以后，设置居中样式， 无法生效

## 你预期的样子是？

选择某一段落，期望设置该段落的对齐情况

## 浏览器及版本号

google chrome

## wangEditor 版本

官网复现

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 全选文字
- 选择居中方式
- 发现失效

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/117424974-eb9d4b80-af54-11eb-8a1c-964708bb220c.png)
未复现该问题

**Comment by rsl140** [comment]
长时间未回复，暂且关闭。
