### ISSUE TITLE
highlight样式的一些小问题

### ISSUE THREAD

**Issue by yuyiRai** [wangeditor-team/wangEditor#3251]
## 问题描述

引入了atom-one-dark主题时发现插入的代码块展示不符合样式，检查样式后发现问题

使用hljs插件时，code标签应该带有‘hljs’的class名
并且不应该指定代码块的背景色（由‘hljs’样式自行指定）

查阅源码后还发现highlightAuto方法未传入用户指定的代码类型，会导致部分解析异常
如，此处的ts语法的装饰器无法被解析为hljs-meta
```typescript
@Component({})
export class Test {

}
```
传入即可修复

## wangEditor 版本

4.6.17

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

插入代码块即可

**Comment by rsl140** [comment]
抱歉，描述的有点抽象 不是太明白，是否可以提供一个可以复现的场景，便于我们复现问题

**Comment by yuyiRai** [comment]
> 抱歉，描述的有点抽象 不是太明白，是否可以提供一个可以复现的场景，便于我们复现问题

https://codepen.io/yuyirai/pen/xxqbqaZ

改动点都集中在
https://github.com/wangeditor-team/wangEditor/blob/master/src/menus/code/create-panel-conf.ts#L135

**Comment by rsl140** [comment]
大概理解了一下，插入代码的背景之类的应该是黑色风格，然而我们编辑导致他并没有应用引入的高亮代码块样式风格？
是这样么？

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
