### ISSUE TITLE
有没有blur方法,让我能够主动去移除foucs,而不是只能在回调函数里拿到

### ISSUE THREAD

**Issue by lsai2270** [wangeditor-team/wangEditor#3253]
![image](https://user-images.githubusercontent.com/32258110/117396387-70c03a80-af2c-11eb-8989-a713f4288eea.png)
这里我输入框的focus实际上在富文本框中,我粘贴内容到输入框中就会粘贴到富文本中
![image](https://user-images.githubusercontent.com/32258110/117396556-c4cb1f00-af2c-11eb-9ad3-2ca711927347.png)
有没有api方法来主动移除editor的Focus

**Comment by rsl140** [comment]
请按issue模板提交内容，否则是不受理的
