### ISSUE TITLE
表格点击设置/取消表头，会删除第一行的内容。

### ISSUE THREAD

**Issue by yak-9** [wangeditor-team/wangEditor#3254]
## bug 描述

表格点击设置/取消表头，会删除第一行的内容。

## 你预期的样子是？

设置/取消表头成功，内容不丢失。

## 浏览器及版本号

Chrome/90.0.4430.93

## wangEditor 版本

4.6.17

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

1.添加表格，第一行的单元格中输入任意内容；

2.点击设置/取消表头按钮。

**Comment by yak-9** [comment]
4.6.12版本是正常的

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/117426756-db866b80-af56-11eb-9874-8cee904ca7fa.png)
取消表头后预期的效果：
![image](https://user-images.githubusercontent.com/7655291/117426786-e2ad7980-af56-11eb-9823-887fe5aa2580.png)

**Comment by qianfengg** [comment]
@liuqh0609  交叉测试
