### ISSUE TITLE
富文本中有一个input输入框,粘贴内容到输入框中,会粘贴到富文本框中,推测是鼠标移到输入框中,editor没有失去焦点

### ISSUE THREAD

**Issue by lsai2270** [wangeditor-team/wangEditor#3255]
## 问题描述

*富文本中有一个input输入框,粘贴内容到输入框中,会粘贴到富文本框中,猜想应该是鼠标到输入框的focus,富文本框没有失去焦点*

## wangEditor 版本

*4.6.17*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一: 在富文本的内容中加入一个input输入框
- 步骤二: 复制粘贴一个内容到输入框中
- 步骤三: 内容会被粘贴到富文本中

**Comment by rsl140** [comment]
您好， 我们不支持在编辑器中加入 input 输入框。

**Comment by lsai2270** [comment]
> 您好， 我们不支持在编辑器中加入 input 输入框。

那有没有blur方法我来主动移除焦点,而不是只能拿到失去焦点的回调

**Comment by rsl140** [comment]
[文档](https://doc.wangeditor.com/pages/04-%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0/02-onfocus%E5%92%8Conblur.html)

**Comment by lsai2270** [comment]
> [文档](https://doc.wangeditor.com/pages/04-%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0/02-onfocus%E5%92%8Conblur.html)
这个文档我看过了,
![image](https://user-images.githubusercontent.com/32258110/117432640-2d31f480-af5d-11eb-90b8-dd878ee3b37f.png)

你们的原型中有foucs事件,但是没有blur事件

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/117433412-07591f80-af5e-11eb-9854-aca3fe1e009c.png)
onblur不就是么？

**Comment by lsai2270** [comment]
我的意思是我触发input的 onfous事件后,我怎么主动移除富文本的焦点


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 晚上6:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 富文本中有一个input输入框,粘贴内容到输入框中,会粘贴到富文本框中,推测是鼠标移到输入框中,editor没有失去焦点 (#3255)





 

 onblur不就是么？

**Comment by rsl140** [comment]
editor.$textElem.blur()

**Comment by lsai2270** [comment]
> editor.$textElem.blur()

![image](https://user-images.githubusercontent.com/32258110/117522224-a6285f00-afe4-11eb-9716-4457be925c92.png)
editor.$textElem中没有blur()方法的??

**Comment by lsai2270** [comment]
> > > editor.$textElem.blur()
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/32258110/117522224-a6285f00-afe4-11eb-9716-4457be925c92.png)
> > editor.$textElem中没有blur()方法的??
> 
> 查了下 确实没有，所以，目前暂时没有解决方案。可能需要您先自己解决下了。

这个应该是你们没有继承,希望你们下个版本可以把这个方法暴露出来,谢谢啦
