### ISSUE TITLE
当文本内容被删除后, 图片被清空了

### ISSUE THREAD

**Issue by BeeWjh** [wangeditor-team/wangEditor#3256]
## bug 描述

1. 当文本内容被删除后, 图片被清空了
2. 当富文本中只有图片时 点击删除键 则全部删除

## 你预期的样子是？

图片单个删除

## 浏览器及版本号

谷歌

## wangEditor 版本

4.6.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一: 全部文案删除
- 步骤二: 图片不见了
- 步骤三

**Comment by li-jingxuan** [comment]
@rsl140 我目前是在这个位置进行了临时处理，希望能够提供一下更加完善的解决方案，谢谢![](https://files.catbox.moe/pg4o1r.png)
