### ISSUE TITLE
可以添加一个表格合并单元格的功能吗？

### ISSUE THREAD

**Issue by WenBoWeb** [wangeditor-team/wangEditor#3262]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by rsl140** [comment]
该功能已受理 可以到 #3086 跟进
