### ISSUE TITLE
外部 css 样式影响到编辑器内部初始化样式

### ISSUE THREAD

**Issue by SenLiangpi** [wangeditor-team/wangEditor#3265]
## 问题描述

外部 css 样式影响到编辑器内部初始化样式

## wangEditor 版本

4.6.17

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

https://codepen.io/pipi40401210/pen/abJOKmd

**Comment by 86driver** [comment]
这个是正常的。
 如果用户需要自定义编辑器样式，比如行高这些， 都是要样式覆盖的。

**Comment by SenLiangpi** [comment]
@86driver 
初始化样式的自定义应该在 API 中体现出来。
这是否又会影响最后的保存？由于受到外部 css 的影响，编辑中看到的样式是否与保存后展示的样式一致？
