### ISSUE TITLE
回退iframe所在当前行时，iframe使用src渲染，希望支持srcdoc

### ISSUE THREAD

**Issue by sunchuxin** [wangeditor-team/wangEditor#3267]
## bug 描述

*iframe使用srcdoc添加html，添加到编辑器中后，删除iframe当前行，iframe回退到上一行时，iframe读取src属性，使iframe报404*

## 你预期的样子是？

*希望iframe支持srcdoc属性*

## 浏览器及版本号

*Google Chrome 90.0.4430.93（正式版本） （64 位）*

## wangEditor 版本

*V4*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- iframe使用srcdoc添加html
- 删除iframe所在当前行，让iframe自动回退到上一行

**Comment by 86driver** [comment]
方便贴一个codepen 描述一下你遇到的问题吗

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
