### ISSUE TITLE
光标跳到文本最前

### ISSUE THREAD

**Issue by donzel-lin** [wangeditor-team/wangEditor#3268]
## bug 描述

先输入一段文字，然后不选中这段文字，修改字体大小，第一次可以正常显示，当继续 重复操作时，光标会从文本最后跳到最前面
看下图（官网的编辑器）：
![8osmp-7peae](https://user-images.githubusercontent.com/73420229/117771907-324ab880-b269-11eb-939a-f4943f502507.gif)

## 你预期的样子是？

保持光标不动

## 浏览器及版本号
谷歌
版本 90.0.4430.93（正式版本） （64 位）
## wangEditor 版本
4.6.10
## 官网能否复现该 bug ？
能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 输入文字
- 不选中文字，切换字体大小
- 重复第二步，继续切换字体大小，查看光标位置

**Comment by 86driver** [comment]
![image](https://user-images.githubusercontent.com/38236070/117809601-f0ce0380-b290-11eb-9017-033d0aa6485b.png)
和[issue3272](https://github.com/wangeditor-team/wangEditor/issues/3272)
报同样的错

**Comment by donzel-lin** [comment]
修改字体颜色也有相同的问题
