### ISSUE TITLE
外部 css 样式影响到编辑器内部初始化样式

### ISSUE THREAD

**Issue by SenLiangpi** [wangeditor-team/wangEditor#3269]
原 https://github.com/wangeditor-team/wangEditor/issues/3265
后续提问
初始化样式的自定义应该在 API 中体现出来。
这是否又会影响最后的保存？由于受到外部 css 的影响，编辑中看到的样式是否与保存后展示的样式一致？
这影响这我的决定和后续的工作。

**Comment by 86driver** [comment]
样式是不应该放到api里面的， 你所说的编辑和保存， 正常操作都是你自己要维护自己的样式表，使得它在编辑和回显的样式一致， 编辑器不会帮你做这些东西的。

编辑器做的就是所见即所得，样式上要规范， 自己要维护样式表的

**Comment by SenLiangpi** [comment]
@86driver  @rsl140 
操作栏中那些样式选项，我在初始化时配置选中某一项，如 字号初始化默认选中18px 。但我在API中并没有看到这种配置。而我所说的 “初始化样式的自定义应该在 API 中体现出来” 也是这个疑问。
很多项目，都会有全局的公共样式配置，如全局的 字体大小 颜色，我个人感觉编辑器中的样式应该保持独立且不应受到外部样式的影响。但现在的它受到了影响，我应该如何解决这个问题？

**Comment by rsl140** [comment]
关于样式影响 该问题已经收录 可以移步到 #3095 进行跟进
