### ISSUE TITLE
没有查看源码的菜单和字体设置问题f.o.n.e标签已废弃问题

### ISSUE THREAD

**Issue by juhelie** [wangeditor-team/wangEditor#3273]
1、能否增加一个源码的菜单？和版本二那种。
2、font标签已经废弃，设置字体大小颜色加粗等能否用style="font-size:16px;color:#c9c9c9"这种呢？

**Comment by juhelie** [comment]
> 1、能否增加一个源码的菜单？和版本二那种.
> 2、字体标签已经废弃，设置字体大小颜色加粗等能否用 s.t.y.l.e=“f.o.n.e：16 px；c.o.l.o.r：.#c9c9c9”这种呢？

**Comment by rsl140** [comment]
首先，请按issue模板提交问题，否则是不受理的。
其次 关于查看源码参考[这里](https://doc.wangeditor.com/pages/13-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/03-%E6%9F%A5%E7%9C%8B%E6%BA%90%E7%A0%81%E5%92%8C%E4%BF%AE%E6%94%B9%E6%BA%90%E7%A0%81.html)
关于font 目前是基于execommand开发的，之后的L1改版后应该会考虑用别的方案
