### ISSUE TITLE
标题 添加 超链接无效

### ISSUE THREAD

**Issue by donzel-lin** [wangeditor-team/wangEditor#3276]
## bug 描述

选中带有标题的文字，使用 链接，输入 网址，插入后没有效果
（如果是普通股文本添加了超链接之后，再使用标题样式，是有效果的）

## 你预期的样子是？

标题无法使用 链接的功能（即选中了带有标题样式的文本，无法点击 链接的按钮）
或者 标题可以正常使用 链接

## 浏览器及版本号
谷歌
版本 90.0.4430.212（正式版本） （64 位）

## wangEditor 版本

4.6.10

## 官网能否复现该 bug ？
![xc6s1-qm1mp](https://user-images.githubusercontent.com/73420229/117930748-f549f900-b330-11eb-9cfc-03aba3328053.gif)

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 输入文本
- 选择标题
- 选中该文字，点击 链接 按钮，填入网址，查看效果

**Comment by 86driver** [comment]
感觉这个问题比较严重， 我选中标题 添加链接 会莫名其妙导致网页崩溃，  连F12都按不出来

**Comment by SheldonWatson** [comment]
我也遇到这样的问题

**Comment by sunliyun** [comment]
遇到同样的问题
