### ISSUE TITLE
光标置于输入框最前的时候多次点击删除后书写混乱

### ISSUE THREAD

**Issue by haust-lyb** [wangeditor-team/wangEditor#3277]
## bug 描述

*当我多次使用删除后，再快速的键入一些中文，就会出现抽风的现象，貌似还在受删除操操作的影响*

## 浏览器及版本号
*我是用的是MacBookPro M1芯片版本*
*chorme 90.0.4430.93（正式版本） (arm64)*

## wangEditor 版本

*官网的第一个案例：https://www.wangeditor.com/*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 输入一些内容，快速连续点击删除键
- 紧接着上一个步骤不要停快速输入中文
- 看到抽风现象

视频：
当我删除到定格的时候依然多次点击了删除，然后快速的输入中文你好，发现很难干净的打出你好，手速一块就抽风了
https://user-images.githubusercontent.com/23397828/117932947-9c2f9480-b333-11eb-9f21-eb87adbd128d.mov

**Comment by 86driver** [comment]
我在官网试了一下 没发现你所说的抽风问题 - -

**Comment by haust-lyb** [comment]
这个我后来看了一下，在Windows下很好，在我这台Mac上就不行，同事和我同款Mac也有这个问题，挺奇怪的
![image](https://user-images.githubusercontent.com/23397828/118072368-3a773500-b3dc-11eb-914a-3f58fb194fe0.png)

**Comment by rsl140** [comment]
你和你同事的都是M1芯片么？

**Comment by liuqh0609** [comment]
结合你录制的视频加上我日常的一些使用体验感觉这个应该不是编辑器的问题。
M1的mac是会有这个打字出现混乱的问题的，无论是在微信还是一些其他可以输入字符的地方，当你快速输入的时候会出现莫名其妙的字符。
