### ISSUE TITLE
onchangeTimeout 属性无效

### ISSUE THREAD

**Issue by 1165468011** [wangeditor-team/wangEditor#3278]
## bug 描述

*使用onchangeTimeout属性修改change事件反应时间无效*

## 你预期的样子是？

*如官网所述，在用户停止操作一定时间后触发change时间，优化性能*

## 浏览器及版本号

*Google Chrome  90.0.4430.212（正式版本） （64 位）*

## wangEditor 版本

*4.6.17*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

https://codepen.io/xiaokyo-the-bold/pen/ZEpWByR
官方demo即可复现

- 步骤一
- 在 instance.config 添加 onchangeTimeout 属性
- 步骤二
- 添加onchange事件的回调，console.log()

**Comment by clinfc** [comment]
![image](https://user-images.githubusercontent.com/39868400/118066915-20385980-b3d2-11eb-8656-d3fe4508228f.png)

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回暂且关闭

**Comment by Kijin-Seija** [comment]
您好，关于这个问题我有一些个人意见。
我在查询文档的时候，首先看到的是这里
![image](https://user-images.githubusercontent.com/27846243/129130239-1c52f5d3-ada7-4639-bb17-eaed1dcd5fec.png)
这里给onchangeTimeout的定义是：
> 如果需要修改 onchange 触发的延迟时间（ onchange 会在用户无任何操作的 xxx 毫秒之后被触发），可通过 onchangeTimeout 配置。

而在配置历史记录里，onchangeTimeout的定义又发生了变化：

> // 当我们使用兼容模式的时候，可以自定义记录的频率，默认 200 ms
editor.config.onchangeTimeout = 500 // 修改为 500 ms

这两个定义是完全不一样的。

开始我以为这个事件自带了debounce，然后去自己设定需要的timeout，发现不生效。结果发现应该是下面这个定义，所以是否文档这里需要调整一下，或者是onchangeTimeout这个变量名是否应该修改下以匹配它真正的意义？
