### ISSUE TITLE
富文本框点击图片，ctr+c， ctr+v，图片粘贴不上去

### ISSUE THREAD

**Issue by baozi-wei** [wangeditor-team/wangEditor#3279]
## bug 描述

富文本框点击图片，ctr+c， ctr+v，图片粘贴不上去；注意，不是右键复制图片，是ctrl c + ctrl v操作才能复现

## 你预期的样子是？

图片正常粘贴

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本
4.6.16

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
该问题已经收录，可以移步到 #3197 进行跟进
