### ISSUE TITLE
设置标题的时候，有情况会报错，然后页面卡死

### ISSUE THREAD

**Issue by baozi-wei** [wangeditor-team/wangEditor#3280]
## bug 描述
设置标题的时候，代码报错，页面就卡死了。但是我没有找到必现场景，根据当时具报错找到了原代码:
createRangeByElems方法，接收到的dom是undefined。目前我自己的处理时简单加个判断，页面不卡死就行了。
![image](https://user-images.githubusercontent.com/40175584/117963340-d52b3180-b352-11eb-8338-bd88bc5a061b.png)

## 你预期的样子是？

正常设置标题

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本
4.6.17

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by 86driver** [comment]
感觉应该是没有做参数判断

**Comment by rsl140** [comment]
可以提供一个大体的方向么 ，在什么情况下 有几率复现该问题

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭
