### ISSUE TITLE
输入中文 第一个被截断成字母

### ISSUE THREAD

**Issue by ZhaoCongDream** [wangeditor-team/wangEditor#3281]
## bug 描述

输入中文 第一个被截断成字母
![Kapture 2021-05-12 at 20 40 36](https://user-images.githubusercontent.com/30501861/117977835-cef18100-b363-11eb-82a1-39a5b63b6c7c.gif)
![image](https://user-images.githubusercontent.com/30501861/117978199-34457200-b364-11eb-9523-08204fa14997.png)

在群里查看聊天记录后
![image](https://user-images.githubusercontent.com/30501861/117978352-5a6b1200-b364-11eb-873e-abe2389266b9.png)

## 你预期的样子是？

第一个不应该被截断

## 浏览器及版本号

chrome 90.0.4430.93

## wangEditor 版本

     4.6.14

## 官网能否复现该 bug ？

 不能

## 最小成本的复现步骤

暂时不知如何帮助你们复现，只能提供相关信息
使用的 react 15.6
![image](https://user-images.githubusercontent.com/30501861/117978785-d1080f80-b364-11eb-8014-343d23a21360.png)

**Comment by rsl140** [comment]
可以参考#3052 该问题已经排查过，是谷歌浏览器的问题。不太容易处理.

**Comment by ZhaoCongDream** [comment]
目前有什么可以规避这个问题的方案么

**Comment by rsl140** [comment]
抱歉，目前暂时没有好的方案可以避免
