### ISSUE TITLE
在保留样式的条件下复制内容到编辑器中windows电脑和mac电脑表现不一致

### ISSUE THREAD

**Issue by rubbish11** [wangeditor-team/wangEditor#3282]
## bug 描述

1.对编辑器设置样式不过滤editor.config.pasteFilterStyle = false来保留样式,
2.然后从135编辑器中复制有排版样式的内容到编辑器中
3.windows电脑中能复制内容，并且样式保持不变
4.今天试了4台mac 复制的时候会没有反应，或者复制成功了但是只保留文本没有样式和图片
chrome 版本都是最新，控制台没有任何报错，在官网中的列子也试过了 ，排除其他插件的影响

## 你预期的样子是？
windows 电脑 和 mac电脑的行为保持一致

## 浏览器及版本号

谷歌浏览器，同为最新版本

## wangEditor 版本

4.6.17

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

1.对编辑器设置样式不过滤editor.config.pasteFilterStyle = false来保留样式,
2.然后从135编辑器中复制有排版样式的内容到编辑器中
3.windows电脑中能复制内容，并且样式保持不变
4.今天试了4台mac 复制的时候会没有反应，或者复制成功了但是只保留文本没有样式和图片

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
