### ISSUE TITLE
请问在编辑器内容超出固定高度出现滚动条的情况下 怎么去获取到 内容的真实高度？

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3283]
## 问题描述

请问在编辑器内容超出固定高度出现滚动条的情况下 怎么去获取到 内容的真实高度？

## wangEditor 版本

4.0

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

固定高度 输入多行文本 出现滚动条 我需要获取到全部内容的总高度 如图所示 看到的是最后一截的内容 但是上面还有内容

![image](https://user-images.githubusercontent.com/43296632/118091866-eda45600-b3fd-11eb-94ed-c0a635ae5e08.png)

**Comment by UltramanWeiLai** [comment]
dom. scrollHeight

**Comment by UltramanWeiLai** [comment]
该问题长时间无人回复，暂且关闭
