### ISSUE TITLE
code行内代码按回车换行后再插入代码块样式显示错误

### ISSUE THREAD

**Issue by zh-lx** [wangeditor-team/wangEditor#3285]
## bug 描述

将输入光标置于编辑器最后一行，随便输入一段内容，鼠标选中该内容并点击工具栏中的code按钮将其设置为行内代码，然后按回车键另起一行。再次点击工具栏的code按钮插入一段代码，插入的代码块样式显示错误，并且插入的代码内容没有被添加到代码块中。

具体的错误复现步骤及错误效果如下图所示：
![错误图片](https://i.postimg.cc/RVbkcPQ4/editor.gif)

## 你预期的样子是？

行内代码换行后，再次插入代码段能够正确显示。

## 浏览器及版本号

Chrome 90.0.4430.93

## wangEditor 版本

4.6.17

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一：在编辑器最后一行，随意输入一段文本，鼠标选中该段文本，点击工具栏的code，将其设置为行内代码
- 步骤二：按下回车，另起一行
- 步骤三：点击工具栏的code按钮，随意输入一段代码，插入后样式显示错误
（具体复现步骤及效果可参照我bug描述中的动图，该bug解决方式我也已找到，稍后会提PR）

**Comment by zh-lx** [comment]
修复请见PR #3286

**Comment by zlx1134558955** [comment]
@clinfc 这个修复方案在第三方PR中有，可以验证下是否可行，不必重复修复

**Comment by wangfupeng1988** [comment]
@shi-lai-mu 你来帮忙测试一下这个 pr 吧 https://github.com/wangeditor-team/wangEditor/pull/3286
没问题的话就合并

**Comment by shi-lai-mu** [comment]
> @ shi-lai-mu你来帮忙测试一下这个pr吧[＃3286](https://github.com/wangeditor-team/wangEditor/pull/3286)
> 没问题的话就合并

好的

**Comment by shi-lai-mu** [comment]
> @clinfc 这个修复方案在第三方PR中有，可以验证下是否可行，不必重复找原因浪费时间 #3286

您好，您的PR有以下缺陷：
1. 您创建的PR应当需按照[规范](https://github.com/wangeditor-team/wangEditor/blob/master/docs/dev.md#%E5%88%9B%E5%BB%BA-prpull-request)合并到dev中
2. 经测试在插入code后，点击下一行时无法删除上一行的code

**Comment by shi-lai-mu** [comment]
> @clinfc 这个修复方案在第三方PR中有，可以验证下是否可行，不必重复找原因浪费时间 #3286
经测试在插入code后，点击下一行时无法删除上一行的code
