### ISSUE TITLE
base64保存图片，复制图片再粘贴，网页卡死

### ISSUE THREAD

**Issue by zjw93615** [wangeditor-team/wangEditor#3287]
## bug 描述

使用base64保存图片，ctrl c复制原本编辑器里面的图片，ctrl v再粘贴回去编辑器，网页卡死

## 你预期的样子是？

ctrl c复制原本编辑器里面的图片，ctrl v可以正常粘贴回去

## 浏览器及版本号

本机 
Version 90.0.4430.212 (Official Build) (x86_64)
其他机器上的Chrome也会有一样的问题

## wangEditor 版本

wangEditor v4.6.2

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 编辑器设置保存图片为base64
- 微信截图或其他截图工具截图，然后粘贴进去编辑器
- 编辑器中选中图片，ctrl c复制
- ctrl v粘贴，页面卡死

**Comment by UltramanWeiLai** [comment]
v4.6.2 ？
可以先尝试升级一下编辑器版本

**Comment by rsl140** [comment]
关于多行粘贴可以移步到 #3299 跟踪
图片粘贴问题可以移步到 #3197 跟踪
