### ISSUE TITLE
自定义字号大小为24、26、28。非选中文字，点击加粗变为默认的14px

### ISSUE THREAD

**Issue by wagagaa** [wangeditor-team/wangEditor#3288]
## bug 描述

自定义字号大小为24、26、28。非选中文字，点击加粗变为默认的14px

## 你预期的样子是？

不选文字点击加粗两次。再输入时候维持默认字号，或者是上次字号。而不是14px的字号

## 浏览器及版本号

Google Chrome 90.0.4430.212

## wangEditor 版本

4.7.0

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 不选文字点击加粗两次
- 再输入文字
- 字号变为默认的14px（内联样式的14px）

![image](https://user-images.githubusercontent.com/27282311/118238566-3fff7880-b4cb-11eb-9abd-fd9cc5d10def.png)
输入123，点击'B'两次

**Comment by rsl140** [comment]
复现步骤：
步骤1：输入文字内容，
步骤2：点击两次加粗功能，
步骤3：再次输入内容

标签变为如下格式
![image](https://user-images.githubusercontent.com/7655291/118430221-31e96c00-b706-11eb-9d43-5c3bd2932403.png)

**Comment by wangfupeng1988** [comment]
这种问题是 `execCommand` API 的一些异常 bug ，目前没法低成本解决。
我们正在火力研发新版本，到时将弃用 `execCommand` API ，这种问题就会彻底解决。

所以，暂不解决这个问题，请等待新版本。
