### ISSUE TITLE
官网打不开

### ISSUE THREAD

**Issue by guoyushane** [wangeditor-team/wangEditor#3289]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by zenghj** [comment]
同打不开官网

**Comment by 86driver** [comment]
正在修复

**Comment by wangfupeng1988** [comment]
已经修复了

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/
