### ISSUE TITLE
通过editor.txt.html()或者editor.txt.text()获取的值，开头总是有一个空格

### ISSUE THREAD

**Issue by Csymaet** [wangeditor-team/wangEditor#3290]
## bug 描述

log相关代码如下:
```js
    editor.config.onchange = function(newhtml){
        console.log("html:"+editor.txt.html()+"###");
        console.log("text:"+editor.txt.text()+"###");
    }
```
看下图
![GIF 2021-5-14 16-00-10](https://user-images.githubusercontent.com/11030217/118242087-83f47c80-b4cf-11eb-9162-5fb23afd6caf.gif)

## 你预期的样子是？

当编辑器内的内容被清空时，通过editor.txt.text()应该得到的是一个空串，而不是空格。

## 浏览器及版本号

Microsoft Edge
版本 90.0.818.62 (官方内部版本) (64 位)

## wangEditor 版本

4.7.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
在`editor.create()`之前加入如下代码：
```js
    editor.config.onchange = function(newhtml){
        console.log("html:"+editor.txt.html()+"###");
        console.log("text:"+editor.txt.text()+"###");
    }
```
- 步骤二
随意在编辑器内输入一些内容，观察输出的log

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/118426655-34e05e80-b6fe-11eb-9296-29cc2d0671a4.png)
在有内容的时候，前面是不会多一个空格的
在没有内容的时候，编辑器里面会默认有一个 p 标签，且 p 标签内有个 br 标签，空白内容的 空格 就是该 br 标签
br 是浏览器 api 需要的
而且空白的时候返回会有个空格有什么影响吗？

**Comment by Csymaet** [comment]
不是的，当有内容的时候，前面也会多一个空格，你仔细看我发的动图  可以看得出来。

影响倒不大，就是想判断当前编辑器的内容是否为空，现在编辑器里的内容若为一个空格，那我就判定它为空，问题不大。

**Comment by UltramanWeiLai** [comment]
有内容的话，我这边并没有多余的空格出来，如上图所示，可以考虑一下 es6 string 有一组专门去除空格的 api https://developer.mozilla.org/zh-CN/search?q=trim

**Comment by Csymaet** [comment]
好的 谢谢了！
