### ISSUE TITLE
文档打不开了

### ISSUE THREAD

**Issue by gmars** [wangeditor-team/wangEditor#3291]
## bug 描述

文档打不开了
## 你预期的样子是？

[](https://oss.okvipcar.com/cic_pud/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20210514175955.png)

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/doc/
