### ISSUE TITLE
插入上传图片后，删除键不起作用

### ISSUE THREAD

**Issue by way-jm** [wangeditor-team/wangEditor#3293]
## bug 描述

插入图片后，删除键删除不了图片

## 你预期的样子是？

插入图片后，删除键可以删除图片

## wangEditor 版本

4.7.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 点到一处
- 点击图片上传
- 按删除键

**Comment by way-jm** [comment]
commit

**Comment by rsl140** [comment]
1. 输入一段内容
2. 上传一张图片
3. 点击backspace按钮

**Comment by Gavin-yh** [comment]
可以跟进这个issue: https://github.com/wangeditor-team/wangEditor/issues/3272，相同的问题
