### ISSUE TITLE
代码模块建议增加一个复制的功能

### ISSUE THREAD

**Issue by yxa521** [wangeditor-team/wangEditor#3296]
![image](https://user-images.githubusercontent.com/52530867/118420627-e75df480-b6f1-11eb-9a4e-fc0583d12ed0.png)
有时一个代码模块很长，加一个copy的功能就很容易copy了

**Comment by UltramanWeiLai** [comment]
请按照模板进行 issue 提交，否则是不受理的
例如： #3298
