### ISSUE TITLE
vue2+wangEditor4.7.0版本插入图片错误，在wangEditor示例（examples文件夹下）的upload-image页面能成功

### ISSUE THREAD

**Issue by iflovezj** [wangeditor-team/wangEditor#3297]
## bug 描述
vue2项目下，使用wangEditor4.7.0版本的插入图片，提示插入图片错误，但是在wangEditor4.7.0例子中能正常上传成功

## 最小成本的复现步骤

使用vue脚手架，生成最简单的项目

<template>
  <div id="app">
	<div ref="editor"></div>
  </div>
</template>

<script>
import Editor from "wangeditor"

export default {
  name: 'App',
  components: {},
	data() {
		return {
			editor: null
		}
	},
	mounted(){
		this.editor = new Editor(this.$refs.editor);
		this.editor.create();
	}
}
</script>

图片路径  https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fcdn.duitang.com%2Fuploads%2Fitem%2F201202%2F18%2F20120218194349_ZHW5V.thumb.700_0.jpg&refer=http%3A%2F%2Fcdn.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1623808438&t=2fe62b3389997774f8be8b242588f344

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/118425619-22652580-b6fc-11eb-8a3a-349c1699de45.png)
![image](https://user-images.githubusercontent.com/23336585/118425635-2c872400-b6fc-11eb-86e1-856f53890fff.png)
没有复现

**Comment by UltramanWeiLai** [comment]
而且你这个配置是，网络图片 吧，连服务器地址都没有配置，哪来的上传图片

**Comment by UltramanWeiLai** [comment]
建议看看文档或者视频，了解一下上传图片的使用

**Comment by iflovezj** [comment]
可能是我描述错了，应该是 ： 插入网络图片的时候，选择上述的图片地址，点击插入后，提示插入图片错误，在案例中能成功插入图片

**Comment by iflovezj** [comment]
> 建议看看文档或者视频，了解一下上传图片的使用
