### ISSUE TITLE
【Feature】代码块功能按钮

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#3298]
## 功能描述

光标在代码块内的时候，可以给代码块提供一些功能按钮，例如：复制

## 提炼几个功能点

- 功能1 功能栏
- 功能2 功能按钮

## 原型图

![image](https://user-images.githubusercontent.com/23336585/118425996-f9916000-b6fc-11eb-838e-e354fab1a888.png)

## 可参考的案例

* 掘金
* 简书
* ...

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
