### ISSUE TITLE
无法正常粘贴内容

### ISSUE THREAD

**Issue by lichenabson** [wangeditor-team/wangEditor#3299]
## bug 描述

无法正常粘贴内容, 只能粘贴复制文本的最后一行

## 你预期的样子是？

正常粘贴

## 浏览器及版本号

chrome86

## wangEditor 版本

官网最新版

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 粘贴多行文本
- 复制

https://user-images.githubusercontent.com/20200267/118429626-ae7b4b00-b704-11eb-84c9-9a1cdfa6ee14.mov

**Comment by rsl140** [comment]
mac电脑可以复现

**Comment by Vibing** [comment]
我也遇到一样的问题，复制一篇文章到编辑器，无法复制全文，只能粘贴一点点

比如我复制以下内容：
![](https://tva1.sinaimg.cn/large/008i3skNly1gqmkpfo5tmj30jn093jsz.jpg)

然后粘贴：
![](https://tva1.sinaimg.cn/large/008i3skNly1gqmkq4r3doj30rk09aabf.jpg)

并且样式不正确

**Comment by Lupeiwen0** [comment]
这个问题也遇到了，确实挺影响使用的，希望可以尽快修复哈！！！

**Comment by Dream-wu** [comment]
我也遇到了，希望尽快解决，这个Bug太影响使用了

**Comment by joriewong** [comment]
same issue

**Comment by joriewong** [comment]
> same issue

回滚到4.6.4版本，没有问题
