### ISSUE TITLE
图片-网络图片，点击插入，提示插图片错误。

### ISSUE THREAD

**Issue by iflovezj** [wangeditor-team/wangEditor#3300]
## bug 描述

vue2.x版本项目  图片-网络图片，点击插入，提示插图片错误。
官方案例\examples文件夹下的upload-image.html页面能正常插入图片
无其他配置
图片地址： https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fcdn.duitang.com%2Fuploads%2Fitem%2F201202%2F18%2F20120218194349_ZHW5V.thumb.700_0.jpg&refer=http%3A%2F%2Fcdn.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1623808438&t=2fe62b3389997774f8be8b242588f344

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

4.7.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

<template>
  <div id="app">
	<div ref="editor"></div>
  </div>
</template>

<script>
import Editor from "wangeditor"

export default {
  name: 'App',
  components: { },
  data() {
	return {
		editor: null
	}
  },
  mounted(){
	this.editor = new Editor(this.$refs.editor);
	this.editor.create();	
  }
}
</script>

**Comment by rsl140** [comment]
1. 查看vue项目中的编辑器版本是否为最新版，并检查是否对文件进行了限制图片大小和类型的配置

**Comment by UltramanWeiLai** [comment]
该问题长时间没有人回复，暂且关闭
