### ISSUE TITLE
编辑器组件会影响页面上其他组件的拖拽上传功能

### ISSUE THREAD

**Issue by wang997722** [wangeditor-team/wangEditor#3301]
## bug 描述

编辑器会把页面的拖动事件禁止掉, 导致 页面内使用<input type='file' />时, 不能拖拽上传文件

## 你预期的样子是？

不影响其他组件的正常使用

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

1. 页面引入编辑器
2. 页面引入<input type='file' />
3. input拖拽功能将会失效

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
是否可以提供一个简单的复现场景，便于我们复现该问题

**Comment by rsl140** [comment]
该问题长时间未回复，暂且关闭
