### ISSUE TITLE
编辑器选中本行居中下一行也会跟着居中

### ISSUE THREAD

**Issue by RichOvernigh** [wangeditor-team/wangEditor#3302]
## bug 描述

使用官网的demo编辑器 删除默认内容，随便输入几个文字然后使用回车换行 然后选中第一行数据点击居中发现第二行文字同样跟着居中 

## 你预期的样子是？

只居中选中的那一行
## 浏览器及版本号

chrome 版本 90.0.4430.93（正式版本） (x86_64)
## wangEditor 版本

官网版本
## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
使用官网的demo编辑器 删除默认内容，随便输入几个文字然后使用回车换行在随便输入几个文字 然后选中第一行数据点击居中发现第二行文字同样跟着居中 
（请告诉我们，如何最快的复现该 bug）

**Comment by RichOvernigh** [comment]
https://user-images.githubusercontent.com/73455910/118604939-5289f280-b7e8-11eb-9cac-56cad075df70.mp4

**Comment by RichOvernigh** [comment]
![WechatIMG16686](https://user-images.githubusercontent.com/73455910/118605020-6897b300-b7e8-11eb-8e3e-a3802814fca3.jpeg)

**Comment by hahaaha** [comment]
按你所说的步骤并没有复现出来

**Comment by RichOvernigh** [comment]
你好，我用的是Mac 系统 系统版本号为 macOS Big Sur 11.0.1 
使用同事的window 电脑在官网上面同样的操作同样未复现 ，使用Mac,进行同样的操作就会出现上面视频的那种问题，这种兼容性问题需要怎么解决呢？
@hahaaha

**Comment by rsl140** [comment]
同样使用mac系统 并未复现给问题

**Comment by hahaaha** [comment]
在macos big sur 11.2.3中也没有复现出来

**Comment by UltramanWeiLai** [comment]
该问题长期没有回复，暂且关闭
