### ISSUE TITLE
富文本失焦之后 的内容编辑问题

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3303]
## 问题描述

富文本失焦之后是不是就没有办法操作editor.txt.append之类的 现在我的场景是我添加了两个按钮在富文本上面 点击的时候 会出发富文本的失焦事件 但是我希望可以不触发 因为触发之后会有一些业务处理（我点击编辑是要选择往富文本添加自定义的内容） 有没有什么办法是可以让我点击按钮的时候 不失焦

## wangEditor 版本

4.0

## 是否查阅了文档 ？

是

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/43296632/118625889-fd0c1080-b7fc-11eb-8077-3cb327107326.png)

**Comment by rsl140** [comment]
这个是没有办法的

**Comment by way-jm** [comment]
> 这个是没有办法的

是不是可以这样做，因为wangEditor上，判断点击如果是在菜单栏上，是不触发onFocus事件的，所以可以把这两个按钮做成自定义菜单即可。

**Comment by rsl140** [comment]
> 是不是可以这样做，因为wangEditor上，判断点击如果是在菜单栏上，是不触发onFocus事件的，所以可以把这两个按钮做成自定义菜单即可。

可以尝试下

**Comment by UltramanWeiLai** [comment]
把两个外置按钮换成，自定义菜单功能按钮应该是可行的
