### ISSUE TITLE
360安全浏览器兼容模式下，字体、H、行高、引用、表格失效。另谷歌浏览器下，设置字体也失效。

### ISSUE THREAD

**Issue by changlinger** [wangeditor-team/wangEditor#3305]
## bug 描述
360安全浏览器兼容模式下，字体设置无效、H设置无效、行高设置无效、引用设置无效、表格有时可以添加上，有时添加不上，或添加上表格后无法删除或添加行或列。另谷歌浏览器下，设置字体也失效。
## 你预期的样子是？
360安全浏览器兼容模式下，字体、H、行高、引用、表格可以正常设置。且谷歌浏览器下，设置字体也失效。
## 浏览器及版本号
360安全浏览器版本12.1.1276.0，谷歌浏览器版本 90.0.4430.212
## wangEditor 版本
版本3

## 官网能否复现该 bug ？

不能
![image](https://user-images.githubusercontent.com/37582160/118766606-3c933500-b8af-11eb-9c86-df4394b06217.png)
官网不支持360兼容模式？

## 最小成本的复现步骤

- 步骤一
- 使用360安全浏览器兼容模式打开我的网页
- 步骤二在我的网页中打开有wangeditor的页面
- 步骤三设置字体、H设置、行高、引用、表格等，无效。

**Comment by rsl140** [comment]
只复现出了表格插入，其他功能可以正常使用

**Comment by UltramanWeiLai** [comment]
版本 3 目前已经不维护了，建议升级到 版本 4
另外 360兼容模式可以选择使用的 ie内核版本，目前只兼容到 ie 11
