### ISSUE TITLE
v4.7.0版本，虽然删除内容能显示placeholder了，但是获取的内容中多一个空格。

### ISSUE THREAD

**Issue by guoyucloud** [wangeditor-team/wangEditor#3306]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*输入内容并删除后获取内容应该为空字符串*

## 浏览器及版本号

*chrome*

## wangEditor 版本

*v4.7.0*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 打开这个网址
- https://codepen.io/xiaokyo-the-bold/pen/KKgzaKG
- 步骤二
- 删除所有内容，点击获取文本或者内容按钮
- 步骤三
- 删除内置代码中的内容，然后在初始化内容为空的时候点击获取文本或者内容的按钮
- 步骤四
- 复现该问题
- alert中你用鼠标选中会发现多一个空格在输入内容并删除内容的时候。

**Comment by guoyucloud** [comment]
@shi-lai-mu 您好帮忙看一下该问题吧，这个问题很严重。直接导致富文本判断是否为空做校验失败了。

**Comment by guoyucloud** [comment]
@shi-lai-mu 您好，请问下次发布是在什么时候呀。

**Comment by shi-lai-mu** [comment]
> @shi-lai-mu 您好，请问下次发布是在什么时候呀。

您好，如果不出意外是每周四更新的

**Comment by guoyucloud** [comment]
> > @shi-lai-mu 您好，请问下次发布是在什么时候呀。
> 
> 您好，如果不出意外是每周四更新的

上周为啥没更新呀，每周是否发布有什么渠道可以得知吗

**Comment by shi-lai-mu** [comment]
> > > @shi-lai-mu 您好，请问下次发布是在什么时候呀。
> > 
> > 
> > 您好，如果不出意外是每周四更新的
> 
> 上周为啥没更新呀，每周是否发布有什么渠道可以得知吗

1. 上周因编译流程问题导致更新延迟
2. 您可以 通过[releases ](https://github.com/wangeditor-team/wangEditor/releases) 或 **待发布态的PR被关闭时** 得知版本的更新状态
