### ISSUE TITLE
在模态框中第一次添加link时报错

### ISSUE THREAD

**Issue by ply920716** [wangeditor-team/wangEditor#3307]
## bug 描述

我把wangeditor放在一个modal里面（用的是ant-design-vue中的a-modal），第一次打开模态框，直接输入链接后，报wangEditor.js?6fad:14706 Uncaught (in promise) TypeError: Cannot read property 'getNode' of undefined 错误，关掉模态框，再次打开后，就正常了，报错如下：
![image](https://user-images.githubusercontent.com/16110741/118773534-84b65580-b8b7-11eb-874e-219320397006.png)
![image](https://user-images.githubusercontent.com/16110741/118773564-8bdd6380-b8b7-11eb-9b0e-f7f6ac55a4b7.png)

## 你预期的样子是？

怎么解决这个问题

## 浏览器及版本号

Chrome Version 90.0.4430.93 (Official Build) (64-bit)

## wangEditor 版本

4.6.17

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
能否提供一个简单的环境，以便我们复现该问题

**Comment by ply920716** [comment]
> 能否提供一个简单的环境，以便我们复现该问题

就是在一个ant-design-vue框架项目中，把wangeditor放在<a-modal>标签中，第一次打开模态框就会报这个错误

**Comment by rsl140** [comment]
未复现该问题

**Comment by rsl140** [comment]
该问题长时间未回复，暂且关闭
