### ISSUE TITLE
目前是否提供了查找和替换功能

### ISSUE THREAD

**Issue by lvxm0** [wangeditor-team/wangEditor#3308]
## 功能描述

根据输入字符，提供查找和替换功能

## 提炼几个功能点

- 查找字符，高亮
- 查找字符，点击'<' ，'>'可以跳转到 上一个/下一个相应字符的位置
- 替换单个字符
- 替换全部字符

## 原型图

<img width="527" alt="截屏2021-05-19 18 54 19" src="https://user-images.githubusercontent.com/31623469/118801464-9f96c300-b8d3-11eb-8f39-ccfbf7ff2d8b.png">

## 可参考的案例

vscode的查找替换功能

**Comment by rsl140** [comment]
当前版本暂不支持，计划在下一个版本中支持
