### ISSUE TITLE
表格回显没有边框

### ISSUE THREAD

**Issue by 878302797** [wangeditor-team/wangEditor#3312]
## bug 描述

表格回显没有边框

## 你预期的样子是？

表格回显有边框

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
查看下是否重置了表格样式，或自定义表格样式即可

**Comment by UltramanWeiLai** [comment]
请看文档，文档里面注明了，table 和 code 两个功能需要自定义添加部分样式，样式在文档里面也写出来了，你也可以自定义想要的样式
