### ISSUE TITLE
文本框清空，粘贴图片换行后输入文字，再删除完文字后，图片跟着被删除

### ISSUE THREAD

**Issue by qq1041663097** [wangeditor-team/wangEditor#3313]
## bug 描述

文本框清空，粘贴一张截图，换行后输入文字：“测试”，然后再backspace删除这两个字，此时上方的图片被删除。

## 你预期的样子是？

预期删除文字后任在第二行，图片不被删除

## 浏览器及版本号

![image](https://user-images.githubusercontent.com/47656506/119070453-9bc18880-ba1a-11eb-9ecc-8740877324e7.png)
360极速浏览器（急速模式）
版本：13.0.2216.0
内核版本：86.0.4240.198

## wangEditor 版本

4.7.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
清空文本框
- 步骤二
粘贴图片
- 步骤三
换行
- 步骤四
输入文字：“测试”
- 步骤五
backspace删除“测试”这两个文字

**Comment by rsl140** [comment]
4.7.1中已修复该问题  可以更新到4.7.1 是否还会复现该问题。

**Comment by qq1041663097** [comment]
4.7.1已解决
