### ISSUE TITLE
zIndex设置不生效

### ISSUE THREAD

**Issue by wangning1314** [wangeditor-team/wangEditor#3315]
## bug 描述

editor.config.zIndex 设置不生效

## 你预期的样子是？

通过 editor.config.zIndex 设置层级

## 浏览器及版本号

Google Chrome 90.0.4430.212（正式版本）

## wangEditor 版本

"wangeditor": "^4.6.16"

## 官网能否复现该 bug ？

无法复现

## 最小成本的复现步骤

```
<script>
    // 引入 wangEditor
    import wangEditor from 'wangeditor'
    const editor = new wangEditor(`#demo1`)
    editor.config.uploadFileName = "file";
    editor.config.zIndex = 0;
    editor.config.uploadImgParams = {
        from: "wang-editor"
    };
    editor.create()
    // 创建编辑器
    this.editor = editor
</script>

// 这样F12检查还是看到 class="w-e-toolbar"的元素z-index=10000
```

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/119355252-9fcdfe80-bcd7-11eb-9365-e830c4d1c35f.png)
未复现该问题

**Comment by wangning1314** [comment]
是配置参数放错文件了，引用错了，现在没问题了，感谢~
