### ISSUE TITLE
没有文本选中事件，希望增加此事件钩子

### ISSUE THREAD

**Issue by 404area** [wangeditor-team/wangEditor#3316]
## 功能描述
选中文本内容时触发文本选中钩子 即onselect事件
## 提炼几个功能点

- 功能1
  没有此事件的钩子函数 ，修改源码 自定义select 无效。。希望增加这个事件钩子
[建议.txt](https://github.com/wangeditor-team/wangEditor/files/6531743/default.txt)

## 原型图

无
## 可参考的案例
无
*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
无

**Comment by wangfupeng1988** [comment]
感谢提出，我们受理这个功能。

使用 `window.document.addEventListener('selectionchange', fn)` 监听，判断 DOM 是否在编辑器之内，然后触发回调函数即可。
需要增加用户配置，写文档。
