### ISSUE TITLE
将编辑器切换英文语言的时候总是没有效果

### ISSUE THREAD

**Issue by 734423631** [wangeditor-team/wangEditor#3318]
// 选择语言
editor.config.lang = 'en'
// 引入 i18next 插件
editor.i18next = window.i18next
向上面这样引入了，经测试行不通。
然后自定义语言也是行不通。

**Comment by rsl140** [comment]
首先 请按issue模板提交问题。
其次[参考国际化在线示例](https://codepen.io/xiaokyo-the-bold/pen/vYXGypN)
