### ISSUE TITLE
加入链接时，键盘输入enter键，可以直接保存链接吗

### ISSUE THREAD

**Issue by ply920716** [wangeditor-team/wangEditor#3321]
## 功能描述

*请输入内容……*

![image](https://user-images.githubusercontent.com/16110741/119594874-2c2f0d00-be0f-11eb-89aa-6fa59fc3b611.png)

如上如所示，在输入链接时，键盘敲入enter键，可以实现和点击“插入"一样的效果吗

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by rsl140** [comment]
需统一处理这种问题，所有带 input 的 panel ，都要增加这个功能。
