### ISSUE TITLE
editor.config.excludeMenus 无法排除显示“全屏”菜单。

### ISSUE THREAD

**Issue by koibi2** [wangeditor-team/wangEditor#3322]
## bug 描述

editor.config.excludeMenus 排除菜单配置项。其它的菜单都隐藏了（撤销、重做等）。
但全屏无法隐藏。
设置了 fullscreen、cancel fullscreen 都不行。

![image](https://user-images.githubusercontent.com/34370367/119619167-47f9d980-be36-11eb-9bcb-63fecc9b9a2f.png)
![image](https://user-images.githubusercontent.com/34370367/119619212-5516c880-be36-11eb-88ef-4a84cb769fb2.png)

## 你预期的样子是？

![image](https://user-images.githubusercontent.com/34370367/119619167-47f9d980-be36-11eb-9bcb-63fecc9b9a2f.png)

## 浏览器及版本号

chrome

## wangEditor 版本

最新版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

![image](https://user-images.githubusercontent.com/34370367/119619167-47f9d980-be36-11eb-9bcb-63fecc9b9a2f.png)

**Comment by rsl140** [comment]
使用`editor.config.showFullScreen = false;`关闭

**Comment by dai-shifu** [comment]
```
  // 工具栏配置
  const toolbarConfig: Partial<IToolbarConfig> = {
    excludeKeys:['fullScreen']
  }; // TS 语法
```
