### ISSUE TITLE
a标签包裹img时，选中img左上角出现的功能标签显示叠加，点击取消链接时，图片消失

### ISSUE THREAD

**Issue by mlshan** [wangeditor-team/wangEditor#3323]
## bug 描述

1. a标签包裹img时，选中img左上角出现的功能标签显示叠加
2. 点击取消链接时，图片消失
![image](https://user-images.githubusercontent.com/37204782/119621908-3ebe3c00-be39-11eb-924d-82308460d461.png)

## 你预期的样子是？
显示正常，同时点击取消链接功能正常
*请输入内容……*

## 浏览器及版本号

现用谷歌测试

## wangEditor 版本

4.7.1

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

1.复制张图片粘贴
2.打开调试工具，编辑增加a标签
![image](https://user-images.githubusercontent.com/37204782/119622524-d0c64480-be39-11eb-9706-923af9ecebab.png)

**Comment by rsl140** [comment]
1： editor.cmd.do( 'insertHTML', `<a><img src="https://user-images.githubusercontent.com/37204782/119621908-3ebe3c00-be39-11eb-924d-82308460d461.png" style="max-width:100%;"/></a>` )
2：点击图片，点击取消链接
