### ISSUE TITLE
在 React 中，使用菜单与编辑区分离的方案时，onfocus、onblur 等这些方法第一次不会执行

### ISSUE THREAD

**Issue by hugewilliam** [wangeditor-team/wangEditor#3326]
## bug 描述
采用菜单与编辑器分离，传入 config 中的 `onblur` 、 `onfocus` 和 `onChange` 第一次的事件不会触发。

## 你预期的样子是？
事件正常触发

## 浏览器及版本号
chrome 最新版

## wangEditor 版本
4.6.16

## 官网能否复现该 bug ？

能/不能
不能
## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
未复现该问题

**Comment by rsl140** [comment]
长时间未回复暂且关闭

**Comment by TheMenLikeWind** [comment]
是不是用了多个编辑器啊，加上editor.config.focus = false试试
