### ISSUE TITLE
编辑器交互页面优化

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#3328]
## 功能描述

1、交互、操作、页面美观程度有待优化；
2、需增加上传附件功能；
3、需增加地图功能；
4、需增加特殊字符及描点；
5、增加日历、日期、时间等等
请参考百度编辑器。

需 支持 移动端。

## 可参考的案例

http://www.miniui.com/demo/thirdparty/htmleditor/ueditor/ueditor.html

**Comment by wangfupeng1988** [comment]
感谢反馈。这些将在后续版本中逐步增加。
