### ISSUE TITLE
建议增加一个 色板功能

### ISSUE THREAD

**Issue by yiijun** [wangeditor-team/wangEditor#3329]
## 功能描述

编辑器可以选择字体的颜色

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by rsl140** [comment]
可以移步到 #2529 进行跟踪
