### ISSUE TITLE
插入本地视频光标消失不见了

### ISSUE THREAD

**Issue by myAllDream** [wangeditor-team/wangEditor#3330]
vue2.0 pc版本，插入本地视频后，如果视频video标签前后没有内容，那么光标就会消失了，无法再在视频前后写入内容 ，回显也是一样，如果只有视频内容，比如这样，光标就会消失，无法再写入新内容
`<p style="text-align:center;"><video src="http://naolihai-open.oss-cn-hangzhou.aliyuncs.com/2021-05-27-1622080050899planContent.mp4" controls="controls" style="max-width:100%"></video></p>`

**Comment by rsl140** [comment]
请按issue模板提交内容，否则是不予受理的

**Comment by wuhuama** [comment]
<p> <video style="max-width: 100%;" controls id="video"> <source src="${url}" type="video/mp4">您的浏览器不支持 video 标签 </video> <p><br></p> </p>
video 标签后加一空白行
