### ISSUE TITLE
复制一行文本，粘贴，只能粘贴一部分

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#3337]
## bug 描述

http://106.55.153.217:8881/master/examples/index.html

复制第一行，然后粘贴。只能粘贴一部分文字

![image](https://user-images.githubusercontent.com/9583120/120135437-d689a480-c202-11eb-953a-c02dda0824ee.png)

## 你预期的样子是？

粘贴全部的文本内容

## 浏览器及版本号

chrome 90

## wangEditor 版本

v4.7.1

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- http://106.55.153.217:8881/master/examples/index.html
- 复制第一行，然后粘贴。只能粘贴一部分文字

**Comment by xuliuzhu1834** [comment]
MAC上可以复现，windows上正常

**Comment by mouday** [comment]
我也出现了  版本号 "wangeditor": "^4.6.6"
