### ISSUE TITLE
绑定自定义ToolTip后，默认Tooltip与自定义ToolTip重叠

### ISSUE THREAD

**Issue by xi-mao-fang** [wangeditor-team/wangEditor#3338]
## wangEditor 4.7.1
- editor.txt.eventHooks.linkClickEvents 添加自定义ToolTip后添加链接 
- 点击链接，Tooltip有两个，且自定义Tooltip被覆盖
- 是否有设置可以不显示默认的ToolTip，只显示自定义的？找了文档没有找到解决方案

目前自己找到一个办法是，在create之后，移除掉原有的showImgTooltip方法，然后再添加自定义的ToolTip，后期是否可以拓展配置选项呢?

**Comment by rsl140** [comment]
我稍微理解下， 你的意思是不是只要有a标签包裹的内容里面显示自己的自定义tooltips a标签自带的也会显示？

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复暂且关闭

**Comment by xi-mao-fang** [comment]
是的
