### ISSUE TITLE
当前光标插入 标签代码字段时

### ISSUE THREAD

**Issue by charliecola** [wangeditor-team/wangEditor#3342]
## bug 描述

在调用光标处插入方法editor.cmd.do('insertHTML', '<标签 contenteditable="true">' + text + '</标签>')时 重复出现 两条数据  一条带标签 一条不带标签
## 你预期的样子是？

在光标处插入 一条附带标签的内容
## 浏览器及版本号

Google Chrome
版本 90.0.4430.72（正式版本）
及
https://codepen.io/  demo演示版本
## wangEditor 版本

3.* 及 4.*
## 官网能否复现该 bug ？

能/不能
能
## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
使用  
- 步骤一 调用 **editor.cmd.do('insertHTML', '<标签 contenteditable="true">' + text + '</标签>')**
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
不明白你在说什么

**Comment by charliecola** [comment]
> 不明白你在说什么

我改了一下 你再帮忙看一下

**Comment by rsl140** [comment]
建议你录个屏之类的
![image](https://user-images.githubusercontent.com/7655291/120645998-a7499080-c4ab-11eb-84fe-bfb17ff73dae.png)

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
