### ISSUE TITLE
vue中通过v-if控制外部弹窗隐藏时，鼠标点击编辑区域按住不动移到弹窗外触发隐藏时，会报错

### ISSUE THREAD

**Issue by keepCreate** [wangeditor-team/wangEditor#3344]
## bug 描述

vue中通过v-if控制外部弹窗隐藏时，鼠标点击编辑区域按住不动移到弹窗外触发隐藏时，会报错
在beforeDestroy中已进行销毁处理

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

4.7.1

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 一个带mask遮罩的弹窗内部有编辑器，鼠标先点击编辑区域内按住不动移到遮罩上触发v-if隐藏

**Comment by keepCreate** [comment]
具体点说，当需要通过v-if来控制嵌套了编辑器的组件显隐时，onclick事件触发时同时也触发了编辑器自己绑定在document上的事件，而当事件执行的过程中进行dom元素获取时，编辑器已经被v-if销毁，因此会触发报错。
需要该场景的原因是每次重新打开弹窗都需要重置整个编辑器，而不通过v-if编辑器内部的历史记录等操作无法重置为初始状态

**Comment by keepCreate** [comment]
这个问题应该是内部事件在获取元素时未进行相关存在判断导致，还是需要加一层逻辑避免这种情况发生，另外可否考虑增加清空重置全部操作的功能，这样可以避免该问题

**Comment by keepCreate** [comment]
应该是鼠标的这种操作触发了编辑器绑定的相关事件，可以具体测下看看。
目前的解决方案是通过监听外部弹窗的显隐变化，增加timeout延时后再对该编辑器组件进行v-if重置处理

**Comment by keepCreate** [comment]
https://user-images.githubusercontent.com/17747538/120628627-7a8b7e00-c497-11eb-9292-f65f1bdf9a9d.mov

**Comment by rsl140** [comment]
建议最好是能上个简单的复现环境源码，便于我们复现该问题

**Comment by keepCreate** [comment]
复现环境如下：https://codepen.io/keepcreate/pen/BaWrwgo @rsl140

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/120910875-24942180-c6b5-11eb-96fa-d622e0cf4620.png)
改成这样 你再试试

**Comment by keepCreate** [comment]
这样改没什么意义呀，这个问题不是出在每次打开没有重新创建实例，而是每次通过我描述的方式关闭弹窗时，通过v-if销毁编辑器会报这个错，重新创建实例不会出这个问题的

**Comment by keepCreate** [comment]
这样改并不能达到我想要在每次关闭弹窗时同时销毁编辑器并打开时重新创建新的，问题就是基于我的这个需求引发的，这个问题应该是出在编辑器绑定在document的一些事件内部获取dom时出的问题，需要进行存在判断

**Comment by UltramanWeiLai** [comment]
你在弹框的销毁事件的回调函数里面，手动执行销毁逻辑不就可以了？
你这种属于非常规的销毁，有报错不是很正常吗？
鼠标在编辑区域内按下，会有捕捉 选取区域 的行为事件进行绑定，你移出编辑区域后弹起鼠标按键，触发回调，这个时候 dom 已经销毁了，自然会报错。

**Comment by keepCreate** [comment]
手动执行销毁逻辑还是会遇到dom不存在的情况，其实更多的需求还是想每次能够重置初始化编辑器，这样也可以避免这种问题的发生

**Comment by UltramanWeiLai** [comment]
手动执行怎么可能会遇到 dom 不存在的情况，怕是用错了事件吧？？
![image](https://user-images.githubusercontent.com/23336585/121453794-50284c00-c9d4-11eb-9964-74d23fdf243b.png)
