### ISSUE TITLE
样式应所见即所得

### ISSUE THREAD

**Issue by Cheng007** [wangeditor-team/wangEditor#3347]
## bug 描述

富文本编辑时表现出来的样式是框架内部定义的硬编码的样式，最终获取的html不包含编辑时的样式，会迷惑用户，若用户需要自定义样式，目前在编辑阶段没有较好的方式实时显示用户自定义样式，如`p`标签需要样式`font-size: 15px;`

![image](https://user-images.githubusercontent.com/13946264/120670052-9bb59400-c4c2-11eb-8034-6cb15481c250.png)

## 你预期的样子是？

富文本编辑器，应该所见即所得，即：编辑器最终导出的样子应该就是编辑完成时看到的样子

在用户需要自定义样式时，编辑器应该能展现出自定义的样式

（是否可以添加一个关于样式的命名空间配置，在用户设置之后，编辑器文本编辑区展现出来的样子就是用户需要自定义的样式，或是增加单独导出默认样式文本功能，再或者就是导出内联样式html）

## 浏览器及版本号

Chrome 91.0.4472.77（正式版本） (x86_64)

## wangEditor 版本

4.72

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 打开任意一个官方demo地址，如：https://codepen.io/xiaokyo-the-bold/pen/abmNBxe
- 在编辑区输入文字或其它内容
- 查看编辑区某一标签的样式

**Comment by keepCreate** [comment]
目前我的实现方案是把源码中的内部样式拿过来，然后通过创建body内部style的innerHTML插入进去，同时将生成的html用一层带有时间戳的随机码id包起来，内部样式同样加一层这个id，保证了不会对其他地方造成样式污染

**Comment by rsl140** [comment]
可以将编辑器内的样式复制出来使用，至于样式隔离问题已经收录 可以移步到 #3095 进行跟踪
