### ISSUE TITLE
插入本地视频光标不能移动到视频后面

### ISSUE THREAD

**Issue by wuhuama** [wangeditor-team/wangEditor#3348]
## bug 描述

*往编辑器中插入html片段-video标签,光标不能无法放在视频后面，导致不能在视频之后添加内容*
`editor.cmd.do(
    "insertHTML",
    `<p>123456
       <video style="max-width: 100%; display: block;" controls id="video">
         <source src="https://www.runoob.com/try/demo_source/mov_bbb.mp4" type="video/mp4">您的浏览器不支持 video 标签
       </video>
    </p>`
  );`

## 你预期的样子是？

*光标自动放在插入的视频之后，或者能手动移至视频之后*

## 浏览器及版本号

*Google Chrome 91.0.4472.77（正式版本） (arm64)*

## wangEditor 版本

*4.7.1*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- https://codepen.io/wuhuama/pen/bGqvYgg?editors=1010

**Comment by wuhuama** [comment]
`this.editor.cmd.do(
          'insertHTML',
          `<p>
            <video style="max-width: 100%;" controls id="video">
              <source src="${url}" type="video/mp4">您的浏览器不支持 video 标签
            </video>
            <p data-we-empty-p=""><br></p>
          </p>`
      )`
插入空行即可

**Comment by samsonCao** [comment]
使用了 wuhuama的方法，插入视频后在后面加了标签 <p data-we-empty-p=""><br></p>。但是鼠标选中视频后发现无法删除视频。
