### ISSUE TITLE
希望能对插入视频功能进行优化，直接填写链接而不是用iframe代码方式，另外希望替换为h5 video风格可进行相关定制

### ISSUE THREAD

**Issue by keepCreate** [wangeditor-team/wangEditor#3349]
## 功能描述

希望能对插入视频功能进行优化，直接填写链接而不是用iframe代码方式，另外希望替换为h5 video风格可进行相关定制

## 提炼几个功能点

- 直接填写链接而不是用iframe代码方式
- 替换为h5 video风格
- 增加插入前回调操作可返回相关配置参数，如是否可暂停等

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

https://quilljs.com/

**Comment by rsl140** [comment]
可以插入如：<video src="video.mp4"></video>这种标签的

**Comment by rsl140** [comment]
长时间未回复，暂且关闭

**Comment by 1261960504** [comment]
这个在视频这里的提示有问题，因为必须插入video标签才能使用，但用户不是程序员，使用iframe插入后是不行的
![image](https://user-images.githubusercontent.com/25954437/122151594-6af63700-ce92-11eb-8b14-51fad15680aa.png)
