### ISSUE TITLE
vue中一个页面用了两个编辑器，无论哪个编辑器上传图片都只会显示在第二个编辑器

### ISSUE THREAD

**Issue by Movielove** [wangeditor-team/wangEditor#3354]
## bug 描述

vue中一个页面用了两个编辑器，无论哪个编辑器上传图片都只会显示在第二个编辑器

## 你预期的样子是？

哪个编辑器上传图片就显示在哪个编辑器里面

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

^2.1.23

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
      <el-row>
        <el-form-item label="pc端详情" prop="productWebDetails">
          <Editor :content="detailForm.detail1" @getEditorData="getEditorData1" :refType="'pcRef'" />
        </el-form-item>
      </el-row>
      <el-row>
        <el-form-item label="移动端详情" prop="productMobbileDetails">
          <Editor :content="detailForm.detail2" @getEditorData="getEditorData2" :refType="'mobileRef'" />
        </el-form-item>
      </el-row>
- 步骤二
- 
 /* 获取PC端详情*/
    getEditorData1(html) {
      if (!html) {
        this.$message.error('请输入PC端详情')
        return
      }
      this.detailForm = Object.assign({}, { ...this.detailForm, productWebDetails: html })
      this.$refs['detailForm'].clearValidate('productWebDetails')
    },

- 步骤三
- <template>

  <div :id="refType" :ref="refType" style="height: 300px" />
</template>
<script>
  import WangEditor from 'wangeditor'
  import { uploadImageUrl } from '@/api/common'
  import vue from 'vue'
  export default {
    props: {
      content: {
        type: String
      },
      contenteditable: {
        type: Boolean,
        default() {
          return true
        }
      },
      refType: {
        type: String,
        default() {
          return 'editorEle'
        }
      }
    },
    data() {
      return {
        editor: null,
        editorContent: ''
      }
    },
    computed: {
      uploadImageUrl() {
        return uploadImageUrl()
      }
    },
    watch: {
      content(val) {
        this.editor.$txt.html(val)
      }
    },
    mounted() {
      this.editor = null
      // this.editor = new WangEditor('editorEle')
      console.log(this.refType)
      this.editor = new WangEditor(this.$refs[this.refType])
      // this.editor = new WangEditor(this.refType)
      this.editor.config.menus = [
        'head', // 标题
        // 'source',
        '|', // '|' 是菜单组的分割线
        'bold', // 粗体
        'fontsize', // 字号
        'fontfamily', // 字体
        'italic', // 斜体
        'underline', // 下划线
        'strikethrough', // 删除线
        'forecolor', // 文字颜色
        'bgcolor', // 背景颜色
        'alignleft',
        'aligncenter',
        'alignright',
        '|',
        'list', // 列表
        'justify', // 对齐方式
        'quote', // 引用
        'emoticon', // 表情
        'table', // 表格
        '|',
        'link', // 插入链接
        'img', // 插入图片
        '|'
      ]
      this.editor.config.uploadImgUrl = this.uploadImageUrl
      this.editor.config.uploadImgFileName = 'file'
      this.editor.config.uploadHeaders = { 'token': vue.ls.get('USER_TOKEN') }
      // 自定义load事件
      this.editor.config.uploadImgFns.onload = (resultText, xhr) => {
        console.log(this.$refs)
        console.log(this.refType)
        const result = JSON.parse(resultText)
        const originalName = this.editor.uploadImgOriginalName ? this.editor.uploadImgOriginalName : ''
        if (result.code === '200') {
          this.editor.command(null, 'insertHtml', '<img src="' + `${result.data}` + '" alt="' + originalName + '" style="max-width:100%;"/>')
        } else {
          this.$message.error(result.msg ? result.msg : '上传图片失败')
        }
      }
      this.editor.onchange = () => {
        console.log(this.$refs)
        this.$emit('getEditorData', this.editor.$txt.html())
      }
      this.editor.create()
      this.editor.$txt.html(this.content)

      if (this.contenteditable) {
        this.editor.enable()
      } else {
        this.editor.disable()
      }
    }
  }
</script>

**Comment by rsl140** [comment]
... 朋友 你这样子完全没法看啊

**Comment by UltramanWeiLai** [comment]
^2.1.23 ？
v4 以下版本目前已经不维护了，建议使用最新的版本
