### ISSUE TITLE
todo list bug

### ISSUE THREAD

**Issue by tiyunchen** [wangeditor-team/wangEditor#3359]
## bug 描述

*在点击checkbox 按钮的时候编辑器会失去焦点，在编辑的时候使用搜狗输入法在打一个中文字的时候会第一个识别成字母*

## 你预期的样子是？

*点击checkbox 按钮的时候编辑器会自动聚焦，输入文字是正确的*

## 浏览器及版本号

*Chrome91(arm 64 apple m1) *

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接在官网上打点击checklist 然后输入文字

**Comment by tiyunchen** [comment]
https://user-images.githubusercontent.com/24793416/121009436-bfc8ec00-c7c6-11eb-9c88-5994ea815d57.mov

**Comment by TGuoW** [comment]
可以复现

**Comment by rsl140** [comment]
该问题，目前只有谷歌会有这个问题，兼容性问题暂时没有很好的办法去解决

**Comment by tiyunchen** [comment]
https://user-images.githubusercontent.com/24793416/122537010-b6a60d80-d057-11eb-9484-2d593fef4315.mov

**Comment by tiyunchen** [comment]
不知道这个问题能不能修复， 出现的频率很高

**Comment by KaelZhang0303** [comment]
> 该问题，目前只有谷歌会有这个问题，是兼容性问题，目前暂时没有很好的办法去解决

谷歌不就是最主流的浏览器吗？
