### ISSUE TITLE
插入图片时，建议在 img 标签添加 data- 属性

### ISSUE THREAD

**Issue by LeoCharles** [wangeditor-team/wangEditor#3360]
## 功能描述

*某些场景下需要在 img 标签存储额外的信息，需要用到data- 属性，目前只有固定的三个属性，可以在 insertImg() 方法中增加一个参数*

**Comment by wangfupeng1988** [comment]
这个需求目前并不大众，暂不受理。
可以去自己 fork 之后修改源码，有问题可以去 qq 群聊。
