### ISSUE TITLE
中文输入情况下，输入法会失去焦点，导致无法文字输入

### ISSUE THREAD

**Issue by Zhoushunshun541** [wangeditor-team/wangEditor#3361]
mac系统，谷歌浏览器，搜狗输入法，正常第一次页面进入以后，可以正常输入 但是删除内容以后，再次编辑就会出现无法输入文字的情况，
代码如下：
` const E = window.wangEditor
          const editor = new E('#editor')
          // 设置编辑区域高度为 500px
          editor.config.height = 613
          // 配置菜单
          editor.config.menus = [
            'head',
            'bold',
            'fontSize',
            'fontName',
            'italic',
            'underline',
            'strikeThrough',
            'indent',
            'lineHeight',
            'foreColor',
            'backColor',
            'link',
            'list',
            'justify',
            'quote',
            'emoticon',
            'image',
            'table',
            'splitLine',
            'undo',
            'redo',
          ]
          // // 配置 onchange 回调函数
          editor.config.onchange = function (newHtml) {
            $('.preview_content').html(newHtml)
          }
          editor.config.onchangeTimeout = 500 // 修改为 500ms
          editor.create()`

**Comment by lucky-kang** [comment]
> '

有截图或录屏吗？

**Comment by rsl140** [comment]
请按issue模板提交问题，否则是不会受理的

**Comment by Zhoushunshun541** [comment]
有的，[这是配置截图](http://file.e.0913edu.cn/file/2021/06/09/091746987-laB9ukvy.png)[这是视频](http://file.e.0913edu.cn/file/2021/06/09/091838302-ekDigBua.mp4)
