### ISSUE TITLE
如何获取菜单栏所有的已选定配置。

### ISSUE THREAD

**Issue by ZhaoWei9527** [wangeditor-team/wangEditor#3362]
## 问题描述

*如何能获取到页面选定好的配置呢，用户选择了字体为24px，那么我从哪个api可以拿到这个值，或者通过什么途径可以拿到这个值，想保存这些用户选定的配置，做缓存，用户下次进入时，沿用之前的配置*

## wangEditor 版本

*4.7.2*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是，查阅了文档，发现有  ‘编辑区域的事件钩子’  这些api，其中有menuClickEvents这个event，但是发现并没有上下文对象下发，并不能知道用户点选的菜单详情以及菜单selected值，不知道是不是使用方式不正确。*

## 最小成本的复现步骤

*这个问题并不是bug，可能是我自己的问题，不清楚如何用api获取用户点选的所有菜单selected值，如：用户选择了  
字体大小->24px   不知道从哪个api可以拿到24px这个值。*

**Comment by rsl140** [comment]
不太明白，其实用户选择了之后，样式已经应用在了显示的文案中了。

**Comment by ZhaoWei9527** [comment]
对，但是不太明白如何获取到已经选定的配置，比如字体大小列表有很多，用户选定的那个，确实已经在显示的文案里，我想知道的是，用户选定时候，有没有触发的事件，可以让我知道他选择了哪一种字体。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 上午9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 如何获取菜单栏所有的已选定配置。 (#3362)





 
不太明白，其实用户选择了之后，样式已经应用在了显示的文案中了。

**Comment by rsl140** [comment]
目前没有。可以尝试使用事件监听的方式自行实现，不过应该会比较复杂。

**Comment by ZhaoWei9527** [comment]
可以大体提供一个思路吗，因为我想保证源码本身是可以信赖的，如果是为了业务去修改源码，有点本末倒置了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 上午9:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 如何获取菜单栏所有的已选定配置。 (#3362)





 
目前没有。可以尝试使用事件监听的方式自行实现，不过应该会比较复杂。

**Comment by rsl140** [comment]
addEventListener 监听菜单栏的点击事件

**Comment by ZhaoWei9527** [comment]
这样子，行，好的，那我明白了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 上午9:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 如何获取菜单栏所有的已选定配置。 (#3362)





 
addEventListener 监听菜单栏的点击事件

**Comment by rsl140** [comment]
那我关闭issue了哈~
