### ISSUE TITLE
最新版Chrome下截图粘贴bug

### ISSUE THREAD

**Issue by tianzhihen121** [wangeditor-team/wangEditor#3363]
## bug 描述

*来自微信输入框截图+chrome最新版91.0.4472.77，在wangEditor中会显示重复截图的bug*

## 你预期的样子是？

*截图只有一张*

## 浏览器及版本号

*chrome 91.0.4472.77*

## wangEditor 版本

*官网版本*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 复制excel单元格中的两行单元格
- 步骤二 粘贴到微信PC客户端，会自动变成图片，然后复制到剪切板
- 步骤三 chrome浏览器91.0.4472.77版本（最新版），打开wangEditor官网，复制粘贴复现
- 备注：只有chrome的最新版有这个问题，90版本的chrome似乎是好的，火狐也没问题

**Comment by rsl140** [comment]
mac端 步骤2就执行不了了
win端 步骤三 粘贴是没有反应的

**Comment by biology-w** [comment]
bug 描述
------------------------------------------------------------------------------------
环境：
windows10专业版 64位
chrome 91.0.4472.101
wangEditor 4.3.0

直接复制word或微信内单个图片,粘贴到编辑器，会显示两张。
![image](https://user-images.githubusercontent.com/25600705/121663085-9e267800-cad8-11eb-896f-90b47312ea7e.png)
![image](https://user-images.githubusercontent.com/25600705/121663215-c3b38180-cad8-11eb-831b-d2375b6242cb.png)
![image](https://user-images.githubusercontent.com/25600705/121663279-d8901500-cad8-11eb-97b7-dca4d51423ae.png)

**Comment by rsl140** [comment]
> ## 个别用户粘贴图片后，编辑器上会插入两张图片。
> （不是所有用户，是在个别用户会有这个问题）
> 环境：
> windows10专业版 64位
> chrome 91.0.4472.101
> wangEditor 4.3.0
> 
> 直接复制word或微信内单个图片,粘贴到编辑器，会显示两张。
> ![image](https://user-images.githubusercontent.com/25600705/121663085-9e267800-cad8-11eb-896f-90b47312ea7e.png)
> ![image](https://user-images.githubusercontent.com/25600705/121663215-c3b38180-cad8-11eb-831b-d2375b6242cb.png)
> ![image](https://user-images.githubusercontent.com/25600705/121663279-d8901500-cad8-11eb-97b7-dca4d51423ae.png)

你先升级版本到最新，然后再试试。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭

**Comment by biology-w** [comment]
升级到最新版本了，还是同样问题。官网也能复现。
![image](https://user-images.githubusercontent.com/25600705/124232759-a9534d80-db44-11eb-834a-204eaf9c2315.png)

**Comment by biology-w** [comment]
能加微信或者qq 直接联系嘛。issue交流有些慢呢

**Comment by Durant35** [comment]
是不是Chrome的一些安全策略？

**Comment by biology-w** [comment]
不是的。都是chrome版本，只在个别用户电脑上出现该问题（如上 https://github.com/wangeditor-team/wangEditor/issues/3363#issuecomment-862008786）
