### ISSUE TITLE
清空后Ctrl A全选能选中删除<br>错误

### ISSUE THREAD

**Issue by Keen-Cat** [wangeditor-team/wangEditor#3364]
## bug 描述

清空编辑器全部内容后，再Ctrl A发现能选中一个”小空格“，调试发现是选中了`<p><br></p>`中的`<br>`。删除后再在工具栏进行标题或文字操作会报错`Uncaught TypeError`错误

## 你预期的样子是？

清空后Ctrl A全选不应再选中

## 浏览器及版本号

Chrome 91.0.4472.77，火狐 83.0

## wangEditor 版本

4.7.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  清空或删除全部内容
- 步骤二  Ctrl A全选，按 backspace删除
- 步骤三  点击 H进行标题操作，报错

**Comment by TGuoW** [comment]
可以复现
![Uploading image.png…]()

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
