### ISSUE TITLE
自定义代码块的 Class

### ISSUE THREAD

**Issue by swling** [wangeditor-team/wangEditor#3365]
## 功能描述
目前代码块的包裹节点类似
` <code class="CSS">xxxx</code>`
希望能自定义这个 Class 如 
`<code class="language-css">xxxx</code>`
如此可以适配更多的代码高亮项目

## 提炼几个功能点
- 自定义代码块的 class
- 可传递代码的语言参数

## 原型图
无

## 可参考的案例
无

**Comment by swling** [comment]
另外注意到代码块还包含一个 <xmp></xmp>标签。但从 MDN 看到，这个标签已经被废弃了。建议移除。
[](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/xmp)

**Comment by swling** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/xmp

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
