### ISSUE TITLE
希望能提供纯 API 的库

### ISSUE THREAD

**Issue by musicode** [wangeditor-team/wangEditor#3366]
## 功能描述

提供一套操作 Range 的 API（不需要任何 UI），方便自定义编辑器，尤其是移动端用于 webview 的编辑器

移动端不需要 pc 这么多功能，编辑器最最核心的就是操作 Range、Selection 的接口，如果能从 wangEditor 提取出一个单独的库，那样移动端就可以自行定制

希望 wangeditor-team 能解决前端这个痛点

## 提炼几个功能点

- 添加 和 取消 加粗、斜体、下划线、删除线 等样式
- 支持添加图片，只需要插入 `img` 标签，不需要上传图片功能
- 粘贴从其他网页复制过来的富文本时，能定制保留哪些标签

**Comment by UltramanWeiLai** [comment]
1、我们目前的定义是开箱即用的，也暂时没有考虑兼容移动端，因为兼容移动端实际上很复杂 - 我们目前在规划 v5 版本，理论上是可以提供一个仅有 core 的能力
2、添加 和 取消 加粗、斜体、下划线、删除线 等样式 - 不是很明白，目前这些按钮默认使用的是标签，可以通过 config 的配置转换成使用 style
3、 支持添加图片，只需要插入 img 标签，不需要上传图片功能 - 默认的网络图片就是如此
4、粘贴从其他网页复制过来的富文本时，能定制保留哪些标签 - 这个 v5 中可以通过自定义插件的形式自行实现

**Comment by musicode** [comment]
我做过一版 webview 的简易编辑器，没碰到太多问题，因此不了解『兼容移动端很复杂』具体指什么？如果是说兼容安卓低版本很麻烦，比如 4.x，那可以选择不支持，兼容到最近 5 年左右的版本就可以。

我说的这些功能，可以参考知乎 app 的编辑器，移动端不需要太多功能，什么表格、列表，根本用不上，只需要一些常用的加粗、斜体、插图就行。

如果你们有计划做这块，可以试着用 react native 搭建一个测试页，布局大概是一个 webview 组件 + 底部的操作按钮区，webview 只有一个编辑器，其他的 UI 都在外面的 App 里，因此需要编辑器提供纯 API 操作。

关于上传图片或视频之类的功能，我想要的流程是：点击上传图片按钮，弹出选图片的界面，选定一张图片，调用编辑器接口插入一个 loading 图片，我自己上传图片成功后，调用编辑器接口替换该 loading 图片，上传结束。

**Comment by UltramanWeiLai** [comment]
怎么说，对于你来讲可能不需要，但是对其他人来说可能并不是这样的，我们需要考虑的东西相对来说会比较多，以及会有短期和长期的目标的。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
