### ISSUE TITLE
feature: 希望链接添加上传本地文档功能

### ISSUE THREAD

**Issue by Tyx-muyu** [wangeditor-team/wangEditor#3369]
## 功能描述

1.现有的 '链接' 功能仅支持输入文档url，希望添加类似于上传图片一样的上传本地文件功能

## 提炼几个功能点

- 功能1：链接功能可上传本地文件，如word文档之类

## 原型图
类似于上传本地图片功能
![截屏2021-06-10 上午10 50 30](https://user-images.githubusercontent.com/48275063/121457105-b5cb0700-c9d9-11eb-932b-720b7aaee6ea.png)

## 可参考的案例

其他编辑器demo：https://froala.com/wysiwyg-editor/
![截屏2021-06-10 上午11 02 53](https://user-images.githubusercontent.com/48275063/121458154-74d3f200-c9db-11eb-9f23-8e3b15bc5065.png)

**Comment by rsl140** [comment]
当前版本暂时不会做，v5版本中会考虑加入该功能

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。V5 有上传附件功能 https://www.wangeditor.com/v5/plugins.html
