### ISSUE TITLE
部分弹出框组件在27寸显示器下展示位置不正确

### ISSUE THREAD

**Issue by alvis-u** [wangeditor-team/wangEditor#3370]
## bug 描述

27寸显示器，上传图片、插入视频、插入表格、插入代码，弹出框位置有问题，有偏移

## 你预期的样子是？

能像表情组件一样，弹出框位置能正确

## 浏览器及版本号

Microsoft Edge  v91.0

> 

## wangEditor 版本

官网版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
 找个27寸显示器
- 步骤二
打开edge浏览器，打开官网编辑器，点击编辑器全屏
- 步骤三
打开上传图片、插入视频、插入表格、插入代码，都能看到位置偏移

**Comment by rsl140** [comment]
抱歉，没有该硬件条件去做到这个测试

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
