### ISSUE TITLE
苹果电脑粘贴丢失内容

### ISSUE THREAD

**Issue by CYscared** [wangeditor-team/wangEditor#3373]
## bug 描述

*苹果电脑赋值文章，粘贴进富文本，前面的内容全部丢失，只有最后一行，查看customUploadImg和pasteTextHandle方法，数据确实丢失*

## 你预期的样子是？

*苹果电脑粘贴文章，内容不丢失*

## 浏览器及版本号

*苹果电脑，谷歌，safari都有这个问题*

## wangEditor 版本

*4.7.1*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 腾讯新闻找一篇文章，粘贴到官网首页富文本，换行的内容都会丢失，只有最后一行会进入富文本（苹果）
- 步骤二
- 步骤三
-

**Comment by rsl140** [comment]
该问题已修复，可更新到4.7.3再尝试下是否还会复现

**Comment by CYscared** [comment]
测试已正常，多谢
