### ISSUE TITLE
## Promise then 函数中使用 editor.txt.html(); 无结果！

### ISSUE THREAD

**Issue by yyqyangyongqiang** [wangeditor-team/wangEditor#3374]
## Promise then 函数中使用 editor.txt.html(); 无结果！

在 axios 返回的 then 函数中 使用 editor.txt.html('后台返回信息');  设置失败!

## 你预期的样子是？

设置内容显示到 wangeditor 编辑器中。

## 浏览器及版本号

chrom 版本 90.0.4430.85（正式版本） （64 位）

## wangEditor 版本

https://cdn.jsdelivr.net/npm/wangeditor@latest/dist/wangEditor.min.js

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 下载 axios 

- 步骤二
- 引入 axios
- 创建
const E = window.wangEditor
    const editor1 = new E('#div1')
    // 或者 const editor = new E( document.getElementById('div1') )
    editor1.create()

- 步骤三
-在 axios 外部 editor.txt.html('咿呀咿呀');   能够正常使用 . 在 axios.then 内部不能使用
控制台 警告：wangeditor.js:16 addRange(): The given range isn't in document.；

代码如下：
axios.post('http://127.0.0.1:8888/index.php/article/searchOne', data)
                    .then(function (response) {                        
                       editor1.txt.html('此处设置失败');
                    })
                    .catch(function (error) {
                        console.log(error);
                    });

**Comment by rsl140** [comment]
未复现该问题，建议自查下代码

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
