### ISSUE TITLE
内容为空，使用引用功能，引用效果会占满编辑器

### ISSUE THREAD

**Issue by ly01112020** [wangeditor-team/wangEditor#3376]
## bug 描述

编辑器内容为空，直接使用引用功能，引用效果会占满编辑器

## 你预期的样子是？

正常的引用效果

## 浏览器及版本号

chrome,edge      v:91

## wangEditor 版本

https://www.wangeditor.com/

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
1.官网编辑器 ctl+a 删除内容,
2.删除后还保留一个空的引用效果（这是不是也是一个bug），删除这个引用，保证内容为空
3.点击引用菜单，引用效果占满整个编辑器

**Comment by rsl140** [comment]
未复现该问题

![image](https://user-images.githubusercontent.com/7655291/121622377-79aea980-caa0-11eb-8894-224d3ba7c1b1.png)

**Comment by ly01112020** [comment]
1.ctl+a  
2.delete
3. 退格键两次，
4. 点击引用
连续操作，可复现，

**Comment by Gavin-yh** [comment]
1. 删除没有删除干净，还保留了引用
2. 全屏引用的问题
![image](https://user-images.githubusercontent.com/40813001/124842801-fca12200-dfc2-11eb-9e44-3f1b1d6e9d76.png)
已经在排查和修复

**Comment by Gavin-yh** [comment]
[fix](https://github.com/wangeditor-team/wangEditor/pull/3466)
