### ISSUE TITLE
当最后一行内容为引用，补充的空行又被删除则无法在下面添加内容

### ISSUE THREAD

**Issue by ly01112020** [wangeditor-team/wangEditor#3377]
## bug 描述

当最后一行内容为引用，补充的空行又被删除则无法在下面添加内容

## 你预期的样子是？

编辑器被激活后检测结尾是否有可编辑空行，如果没有则添加一行

## 浏览器及版本号

随意

## wangEditor 版本

最新

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一  在官网示例中最后一行添加一个引用
- 步骤二  最后一行 退格 删掉 
- 步骤三 会导致无法在下面添加内容

**Comment by rsl140** [comment]
未复现该问题

**Comment by ly01112020** [comment]
连续回车可以自动跳出，没问题了，
