### ISSUE TITLE
使用E.registerMenu注册一个自定义菜单后，改菜单直接在菜单栏中显示，不能通过 menus 配置管理，

### ISSUE THREAD

**Issue by ly01112020** [wangeditor-team/wangEditor#3378]
## bug 描述

如题

## 你预期的样子是？

注册归注册，还是能通过menus管理显示还是不显示

## 浏览器及版本号

最新 chrome edge

## wangEditor 版本

4.7.1

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤
编辑器是单独封装成组件使用，默认会注册一些自定义菜单，后面根据场景使用，
- 步骤一   E.registerMenu(Annotation.menuKey, Annotation);   
- 步骤二   const e = new E(`#${id}`);
- 步骤三   e.config ={menus:['fontName', 'fontSize', 'bold', 'italic']}
- 步骤四   e.create();

**Comment by rsl140** [comment]
[参考example里的自定义菜单](https://github.com/wangeditor-team/wangEditor/blob/master/examples/customMenu.html) 如果不想显示自定义的菜单出来，可以使用editor.config.excludeMenus

**Comment by Lupeiwen0** [comment]
遇到了同样的问题，自定义注册菜单，
menus配置-无法控制->该菜单在菜单栏中显示的顺序

**Comment by ly01112020** [comment]
我想注册后，使用memus配置去管理显不显示和显示位置

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/121978099-0e274d80-cdba-11eb-9cb4-b38077451fe4.png)
可以控制啊

**Comment by ly01112020** [comment]
使用实例模式可以解决我现在的问题，当初看文档建议使用全局注册模式然后就没考虑实例模式。
讲道理全局注册后也应该使用menus 管理，一般开发过程中默认都会做几组菜单配置然后直接以常量使用。

**Comment by ly01112020** [comment]
使用实例模式可以解决我现在的问题，当初看文档建议使用全局注册模式然后就没考虑实例模式。
讲道理全局注册后也应该使用menus 管理，一般开发过程中默认都会做几组菜单配置然后直接以常量使用。

**Comment by WangEbo** [comment]
> 

请问下，实例模式 怎么用，文档里没找着

**Comment by ly01112020** [comment]
> > 
> 
> 请问下，实例模式 怎么用，文档里没找着

![image](https://user-images.githubusercontent.com/4043937/180178937-64194747-8c91-4001-b4e1-edb0521344b6.png)
