### ISSUE TITLE
wangeditor（3.11版本）版本导致样式显示有问题

### ISSUE THREAD

**Issue by jerry933900** [wangeditor-team/wangEditor#3379]
求助一下大佬们，本人使用谷歌浏览器和IE11浏览器，用doc或者docx文档复制内容，会出现一下问题。
1.使用谷歌浏览器复制doc或者docx格式的文字，然后粘贴到富文本显示不正常，正文首行缩进没有，发送给后台然后数据显示回来查看，文档是有首行缩进的，发给后台和返回返回的报文都有格式的标签。然后手机小程序查看也是没有首行缩进的显示格式。比如偏右格式或者日期申请人等都是从左边开始的。
2.ie浏览器复制到富文本编辑器是有首行缩进的显示，然后发给后台查看数据显示也是有正常显示格式的，手机小程序查看也是正常的，就对谷歌有问题。
   前端vue做数据查看显示是v-html解析的。然后后台返回的格式都是未过滤标签的，XSS标签格式攻击除外。

**Comment by rsl140** [comment]
1. 请按issue模板提问，否则不予受理
2. v3版本已不再维护，建议升级至V4版本使用
