### ISSUE TITLE
文本中插入多张图片只能显示最后一张 其余地方可插入多张

### ISSUE THREAD

**Issue by xihuixiang** [wangeditor-team/wangEditor#3381]
## bug 描述 

在文本中插入多张图片只能显示最后一张 其余地方可以

## 你预期的样子是？
正常插入显示

## 浏览器及版本号
谷歌 最新版

## wangEditor 版本

4.7.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 在文字中插入
- 上传图片-多张
- 结果： 只能插入显示最后一张

**Comment by UxieVerity** [comment]
图片貌似一次只能上传一张的样子吧，我试了一下，加入你上传的图片是同一张的话那么就会覆盖掉上一张照片

**Comment by xihuixiang** [comment]
> 图片好像一次只能上传一张照片吧，我试了一下，加入你上传的照片是同一张照片就很可能被曝光的上一张照片

可以多张上传的， 空白地方插入多张就正常

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
