### ISSUE TITLE
给没有`p`标签包裹的文字设置标题, 会导致页面卡死

### ISSUE THREAD

**Issue by linchengzzz** [wangeditor-team/wangEditor#3382]
## bug 描述

给没有<p>标签包裹的文字设置标题, 会导致页面卡死

## 你预期的样子是？

可以添加标题

## 浏览器及版本号

Edge 最新版

## wangEditor 版本

4.7.3

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

![image](https://user-images.githubusercontent.com/24381509/121679555-0a11dc00-caeb-11eb-94bb-2f129df39f2f.png)

给 "如果对本政策..." 这一行添加 `h2` 标签 JS 报错
![image](https://user-images.githubusercontent.com/24381509/121679701-388fb700-caeb-11eb-8a66-e583e18d6cf4.png)

**Comment by UltramanWeiLai** [comment]
为什么会有没有标签的文字？
目前编辑区域的内容，必须是在 段落(p、h*、ul、pre、...) 标签内的

**Comment by linchengzzz** [comment]
> 为什么会有没有标签的文字？
> 目前编辑区域的内容，必须是在 段落(p、h*、ul、pre、...) 标签内的

富文本编辑器里面的内容是直接从 word 里面 Ctrl+C Ctrl+V 过来的, 复制过来的时候没包裹标签

**Comment by rsl140** [comment]
可否提供下素材

**Comment by linchengzzz** [comment]
> 可否提供下素材

根本原因是当时复制粘贴的时候最外层的 p 标签丢失导致的, 刚才重新尝试了复制粘贴下, 暂时没法复现这个问题了,
