### ISSUE TITLE
新增上传音频的功能

### ISSUE THREAD

**Issue by StupidManYI** [wangeditor-team/wangEditor#3383]
## 上传音频

*上传音频*

## 提炼几个功能点

- 支持mp3上传
- 音频按钮

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*
![新建项目 (1)](https://user-images.githubusercontent.com/50037510/121764748-be0d7880-cb78-11eb-9a78-b3feaa7a727b.png)

## 可参考的案例
百度的ueditor
![image](https://user-images.githubusercontent.com/50037510/121764521-2bb8a500-cb77-11eb-8f32-566e9cfa517a.png)

<img width="1083" alt="QQ20210612-122157@2x" src="https://user-images.githubusercontent.com/50037510/121764758-d8dfed00-cb78-11eb-934d-8feea368d7c1.png">

**Comment by UltramanWeiLai** [comment]
目前建议可以参考上传视频加上自定义菜单的功能自行实现一个。
该功能已经在列表中了。
