### ISSUE TITLE
“Cannot read property 'parentNode' of undefined”

### ISSUE THREAD

**Issue by kohott** [wangeditor-team/wangEditor#3384]
## bug 描述
Vue环境
页面渲染后，**editor默认没有内容的情况下，同时editor在没有获得焦点时**，直接点击插入图片会报出
“Cannot read property 'parentNode' of undefined”
![image](https://user-images.githubusercontent.com/3894888/121794196-f83e4f00-cc38-11eb-8e07-6be97a1e8b35.png)

## 浏览器及版本号

Chrome

## wangEditor 版本

v4.7.3

## 官网能否复现该 bug ？

不能，因为默认有内容，该bug条件是默认没有内容

**Comment by rsl140** [comment]
复现步骤也没有，如何复现？

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
