### ISSUE TITLE
粘贴内容后，格式错误。在3.1.1的版本中是没有问题的

### ISSUE THREAD

**Issue by xuliuzhu1834** [wangeditor-team/wangEditor#3386]
## bug 描述

*复制一段带样式的内容（`pasteFilterStyle=false`），在wangeditor@3.1.1中是没有问题的。但是在4.x的任何版本中都有问题*

## 你预期的样子是？

*在版本3.1.1中的样子是*
![image](https://user-images.githubusercontent.com/8508762/122021861-a93f1800-cdf8-11eb-91e3-7ec0c072b7c4.png)

## 浏览器及版本号

*chrome 版本 91.0.4472.101（正式版本） (arm64)*

## wangEditor 版本
*粘贴正常版本： 3.1.1*
*粘贴后显示错误版本：4.x*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一

*复制的内容链接:  https://codesandbox.io/s/static-html-skxk5?resolutionWidth=1920&resolutionHeight=1080* 
![wecom-temp-3ea9b559ab78a4c549a951d25467c179](https://user-images.githubusercontent.com/8508762/122021318-25852b80-cdf8-11eb-9cd7-1bb826436d1a.png)

- 步骤二

将结果粘贴入版本为4.x的富文本，显示的结果为
![image](https://user-images.githubusercontent.com/8508762/122022551-47cb7900-cdf9-11eb-982a-610687fcbf0b.png)

**Comment by rsl140** [comment]
关于粘贴这部分，再考虑统一修正，可以移步到 #3260 进行后续跟踪
