### ISSUE TITLE
输入字体过快第一个字母直接成拼音

### ISSUE THREAD

**Issue by limuen** [wangeditor-team/wangEditor#3387]
## bug 描述

输入字体过快第一个字母直接成拼音例如：queren（确认）q野人

## 你预期的样子是？

queren（确认）而不是q野人

## 浏览器及版本号

 91.0.4472.101

## wangEditor 版本

4.7.2

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 直接快速打字在编辑器里面即可看到
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
该问题是谷歌浏览器兼容性问题，暂时还没有好的解决方案
