### ISSUE TITLE
插入视频的提示错误

### ISSUE THREAD

**Issue by 1261960504** [wangeditor-team/wangEditor#3388]
## bug 描述

在使用网络视频上传上，提示使用iframe标签，但实际上使用iframe无法实现插入视频但功能，只能使用video标签插入才行
如下图
![image](https://user-images.githubusercontent.com/25954437/122152539-0b992680-ce94-11eb-9313-1bc9c695ef5d.png)
使用iframe上传视频无法看到视频的，如下图
![image](https://user-images.githubusercontent.com/25954437/122152567-15bb2500-ce94-11eb-97f0-12ba965fe7d2.png)

## 你预期的样子是？

提示改为：请输入<video  src="/busiAttachments/view/218" controls="controls" style="width: 700px;">您的浏览器不支持 video 标签。</video>

## 浏览器及版本号

chrome 70.0.3538.67

## wangEditor 版本

wangeditor@4.7.3

## 官网能否复现该 bug ？

能

- 步骤一
- https://www.wangeditor.com/
- 选择插入视频，插入任意网络视频<iframe  src="" controls="controls" style="width: 700px;">您的浏览器不支持 video 标签。</iframe>

**Comment by 1261960504** [comment]
希望提示改成<video  src="" controls="controls" style="width: 700px;">您的浏览器不支持 video 标签。</video>

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/122305185-0b9f3200-cf39-11eb-868d-4f93c038bacd.png)
支持iframe和video

**Comment by 1261960504** [comment]
在我的chrome版本70.0.3538.67上，使用iframe插入时候，无法插入视频。那是不是使用video的兼容性会比iframe更好一些。且提示的时候提示的是不支持video标签

**Comment by 1261960504** [comment]
谢谢，是我没有在视频链接后面添加?rel=0&amp;autoplay=1，如果加了就OK
