### ISSUE TITLE
编辑器中有序列表 和 无序列表 内容，选中 改变字体大小 不生效

### ISSUE THREAD

**Issue by xianglove** [wangeditor-team/wangEditor#3391]
## bug 描述
1、选中有序列表 或者 无序列表的字体，
2、改变字体大小
3、更改未生效

## 你预期的样子是？

更改字体大小应该生效

## wangEditor 版本

官网版本 

## 官网能否复现该 bug ？

可以

## 最小成本的复现步骤

1、选中有序列表 或者 无序列表的字体，
2、改变字体大小
3、更改未生效

![image](https://user-images.githubusercontent.com/14902197/122197772-1de28700-cecb-11eb-9b53-46db7bf980c7.png)

**Comment by rsl140** [comment]
未复现该问题

**Comment by xianglove** [comment]
我是使用 H来 改变字体大小的，不是 自定义的字体大小来改变的。

使用 H 来改变也没复现吗？

**Comment by xianglove** [comment]
> 未复现该问题

我是使用 H来 改变字体大小的，不是 自定义的字体大小来改变的。

使用 H 来改变也没复现吗？

**Comment by rsl140** [comment]
H是标题， 你要改变字体大小 请使用字体大小来改变
标题和列表 目前是不支持同时使用的
![image](https://user-images.githubusercontent.com/7655291/122320852-8118fb80-cf55-11eb-8453-2ebe3cfeeb23.png)

**Comment by xianglove** [comment]
哦吼，原来是这样。 感谢 ♥️
