### ISSUE TITLE
前端输出时如何统一样式？

### ISSUE THREAD

**Issue by phpgiter** [wangeditor-team/wangEditor#3393]
## 问题描述
![image](https://user-images.githubusercontent.com/26064554/122347851-0fed3e80-cf7d-11eb-9813-508b2304260c.png)
如图，在管理页面编辑的内容，在前端展示时样式没了，请问这种情况如何保证样式基本统一？或者是输出时也要引入编辑器的css？
![image](https://user-images.githubusercontent.com/26064554/122347953-31e6c100-cf7d-11eb-8ba2-e6fca01d044f.png)

## wangEditor 版本
4.7.3
## 是否查阅了文档 ？
是

## 最小成本的复现步骤
无

**Comment by FreeRide-Joe** [comment]
请问解决了吗？
