### ISSUE TITLE
表格的单元格高度和为表格内容添加链接

### ISSUE THREAD

**Issue by fightinghom** [wangeditor-team/wangEditor#3395]
## bug 描述
1、插入表格时单元格高度显示不正确
2、为单元格内容添加链接，链接中会额外生成一个table标签

## 你预期的样子是？
1、插入表格时单元格高度需要为有内容时的高度
2、为单元格内容添加链接时，链接中不会生成额外的table标签

## 浏览器及版本号
chrome  91.0.4472.106

## wangEditor 版本
4.7.4

## 官网能否复现该 bug ？
能

## 最小成本的复现步骤

- 步骤一 插入表格
- 步骤二 向一个单元格输入内容
- 步骤三 为内容添加链接，会发现下方被撑开
- 步骤四 使用开发者工具查看链接处，发现有一个额外的table标签

**Comment by rsl140** [comment]
插入表格后，表格高度有问题
![image](https://user-images.githubusercontent.com/7655291/122543682-9ded2600-d05e-11eb-86b7-18de55df4a6d.png)

**Comment by wangfupeng1988** [comment]
插入链接，确实有一个多余的 `<table></table>`

![image](https://user-images.githubusercontent.com/9583120/127763519-5afe44a4-de84-4dea-83b5-ea7f4896ffb5.png)

**Comment by Guitarur** [comment]
其实很好解决,   自己在style 加个 height就可以了

**Comment by fightinghom** [comment]
> 其实很好解决, 自己在style 加个 height就可以了

源码里在生成单元格的时候添加一个<br>就行了，可能作者忘加上了
