### ISSUE TITLE
有设置光标位置的方法吗

### ISSUE THREAD

**Issue by Lin-Jiaxiang** [wangeditor-team/wangEditor#3399]
## 功能描述

设置光标位置

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by rsl140** [comment]
editor.selection.moveCursor()
![image](https://user-images.githubusercontent.com/7655291/122847009-9cab4a00-d339-11eb-9a0f-8ed90b4bc6a1.png)

**Comment by Lin-Jiaxiang** [comment]
感谢大佬，可以了
