### ISSUE TITLE
editor.selection.moveCursor()

### ISSUE THREAD

**Issue by ResponseState200** [wangeditor-team/wangEditor#3403]
editor.selection.moveCursor()
![image](https://user-images.githubusercontent.com/7655291/122847009-9cab4a00-d339-11eb-9a0f-8ed90b4bc6a1.png)

_Originally posted by @rsl140 in https://github.com/wangeditor-team/wangEditor/issues/3399#issuecomment-865447061_

想要移动光标到富文本框内容文本的某个字符后面如何传值? 
      this.editor.selection.moveCursor(this.editor.$textElem.elems[0],2)
      this.editor.selection.moveCursor(this.editor.$textElem.elems[0].firstChild,2)
上述两种方式都试过了,不可行,会报错Error in v-on handler: "IndexSizeError: Failed to execute 'setStart' on 'Range': There is no child at offset 2."

**Comment by rsl140** [comment]
首先你需要去了解下什么是Range，如果要具体定位的话就比较复杂了。
不太建议去自己操作。

**Comment by ResponseState200** [comment]
好的,谢谢~
