### ISSUE TITLE
服务端响应上传图片格式格式问题

### ISSUE THREAD

**Issue by puzzle9** [wangeditor-team/wangEditor#3404]
## bug 描述

如果采用文档写法 会报出 `call` 错误

## 浏览器及版本号

`chrome 版本 92.0.4515.59（正式版本）beta （64 位）`

## wangEditor 版本

`v4.7.4`

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

当后台按照

![i
mage](https://user-images.githubusercontent.com/13518196/122881087-54a61a80-d36d-11eb-931e-a94f8ba325f2.png)
```
{"errno":0,"data":{"url":"\/backend\/web\/images\/upload\/forum\/2021-06-22\/ff922426a65281714ba8aa70152007ef.jpg","alt":"lake_forest_bridge_nature_garden_reflection_3888x2189","href":null}}
```

返回时候 会报
![image](https://user-images.githubusercontent.com/13518196/122881167-6982ae00-d36d-11eb-85cc-f1e7d4b93de0.png)

如果返回

```
{"errno":0,"data":["\/backend\/web\/images\/upload\/forum\/2021-06-22\/e691a92d9b9264dd342f0962dd48811e.jpg"]}
```

则正常

**Comment by rsl140** [comment]
文档中不是说了么:
` data 是一个数组，返回图片Object，Object中包含需要包含url、alt和href三个属性`

**Comment by puzzle9** [comment]
> 文档中不是说了么:
> ` data 是一个数组，返回图片Object，Object中包含需要包含url、alt和href三个属性`

抱歉 是我大意了
