### ISSUE TITLE
windows微信客户端中复制的图片，粘贴会出现重复的情况

### ISSUE THREAD

**Issue by singoMa** [wangeditor-team/wangEditor#3407]
## bug 描述

*windows微信客户端中`复制`的图片，粘贴会出现重复的情况。现只在windows系统下微信pc客户端复制的图片会出现，mac系统没有复现*

## 你预期的样子是？

*从微信端复制的图片能正常粘贴，不会重复*

## 浏览器及版本号

*chrome 90*

## wangEditor 版本

*最新v3版本*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 准备windows操作系统pc一台，登录微信pc客户端
- 复制任意会话中图片：图片上点击右键——复制
- 在官网富文本框中粘贴，即可复现

**Comment by rsl140** [comment]
v3版本已经暂停维护了，请升级到V4版本使用

**Comment by imGenji** [comment]
> v3版本已经暂停维护了，请升级到V4版本使用

您好 V4版本我这里也不行

**Comment by rsl140** [comment]
> > v3版本已经暂停维护了，请升级到V4版本使用
> 
> 您好 V4版本我这里也不行

未复现该问题，尝试更新到最新版试试呢？

**Comment by imGenji** [comment]
> > > v3版本已经暂停维护了，请升级到V4版本使用
> > 
> > 
> > 您好 V4版本我这里也不行
> 
> 未复现该问题，尝试更新到最新版试试呢？

已经是最新版本了 我这边是使用win10 出现的 
调试了下 发现复制微信图片的时候会有两个file文件 两个图片是一样的 
![image](https://user-images.githubusercontent.com/20432616/123731131-26bf5980-d8ca-11eb-83bf-bae43e747c26.png)

用了几个别的富文本编辑器 支持一次复制多张图片的也有这个问题。。

**Comment by qq1041663097** [comment]
本人谷歌内核91版本，使用v4.7.4版本也会出现这个情况。

**Comment by OnePsycho** [comment]
请问最终结论是什么？

**Comment by biology-w** [comment]
请问结果是什么？

**Comment by wangfupeng1988** [comment]
@OnePsycho @biology-w issue 排队解决中。如果有进展，会更新 issue 状态的。

**Comment by noe132** [comment]
这很可能是 chrome 91 的bug。我这另外一个代码库也用到了图片粘贴上传的逻辑，微信复制的图片会在 ClipboardEvent 里出现 2 个 File，升级到最新的 electron 后这个问题就消失了。建议升级浏览器版本试试

**Comment by Lingouzi** [comment]
chrome：98.0.4758.109
mac：12.2.1
wangeditor：4.7.12，
vue：3.2.31，
也出现此问题，我是复制的网络文章图片，右键图片复制，然后在编辑器粘贴，使用的是customUploadImg方式自动上传图片，出现 2 张。查看富文本发现是，上传的结构插入一次，然后粘贴的源地址再显示一次。
<img width="880" alt="WX20220302-135203@2x" src="https://user-images.githubusercontent.com/12908403/156303431-17417fc9-1f3e-4c75-89b5-50e5e7f11f29.png">

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
