### ISSUE TITLE
编辑器首次输入中文与输入法不兼容

### ISSUE THREAD

**Issue by xkHua** [wangeditor-team/wangEditor#3408]
## bug 描述

*在首次打开编辑器的时候，输入内容前几个字母不会出现在输入法中，比如输入：nihao，出来的内容是ni好*

## 你预期的样子是？

*能正常使用，前几个字母正常显示在输入法中，打出来的字体正确*

## 浏览器及版本号

*chrome 91.0.4472.114*

## wangEditor 版本

*4.0.6*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 刷新页面
- 步骤二
- 输入nihao拼音
- 步骤三
![image](https://user-images.githubusercontent.com/86354439/123087046-b1313480-d456-11eb-9063-ecc322248f31.png)

**Comment by rsl140** [comment]
这个是谷歌浏览器的兼容性问题，暂时还没有好的方法能够解决
