### ISSUE TITLE
如何给编辑器默认使用的元素标签添加样式？  例如给p标签添加行高

### ISSUE THREAD

**Issue by flyzhaowu** [wangeditor-team/wangEditor#3411]
## 问题描述

*如何给编辑器默认使用的元素标签添加样式？例如给p标签添加行高*

**Comment by rsl140** [comment]
自己用外部样式覆盖富文本中的样式呗.

**Comment by UltramanWeiLai** [comment]
请使用模板来提交 issue 否则是不受理的。

另外 编辑区域 的样式，基本上是基于默认的，如果想定制皮肤，只需要在现实页面添加相应的 css 即可，注意回显的页面也是
