### ISSUE TITLE
自定义粘贴过滤，内容需异步处理

### ISSUE THREAD

**Issue by luckymiaow** [wangeditor-team/wangEditor#3412]
## 问题描述

*请输入遇到的问题...*
自定义粘贴过滤，需要转存网络图片到服务器，需要到了异步处理
## wangEditor 版本 
4.7.3
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

editor.config.pasteTextHandle = pasteStr => {
      setTimeout(() => {
        pasteStr = '异步数据';
      }, 1000);
      return pasteStr;
 };

**Comment by UltramanWeiLai** [comment]
完全没明白你想表达的意思，请尽量详细的说明

**Comment by wangfupeng1988** [comment]
你是想，从其他网页复制过来的 html ，里面有图片的话，就转存到自己的服务器，对吧？

你试试这样子行吧？

```js
editor.config.pasteTextHandle = function (pasteStr) {
    setTimeout(() => {
        editor.cmd.do('insertHTML', '<p>...你异步处理之后的 html 内容...</p>')
    })
    return ''
}
```

**Comment by luckymiaow** [comment]
> 你是想，从其他网页复制过来的 html ，里面有图片的话，就转存到自己的服务器，对吧？
> 
> 你试试这样子行吧？
> 
> ```js
> editor.config.pasteTextHandle = function (pasteStr) {
>     setTimeout(() => {
>         editor.cmd.do('insertHTML', '<p>...你异步处理之后的 html 内容...</p>')
>     })
>     return ''
> }
> ```

是的，谢谢。

**Comment by codedart2018** [comment]
> > 你是想，从其他网页复制过来的 html ，里面有图片的话，就转存到自己的服务器，对吧？
> > 你试试这样子行吧？
> > ```js
> > editor.config.pasteTextHandle = function (pasteStr) {
> >     setTimeout(() => {
> >         editor.cmd.do('insertHTML', '<p>...你异步处理之后的 html 内容...</p>')
> >     })
> >     return ''
> > }
> > ```
> 
> 是的，谢谢。

这个不算是异步啊，这个项多算是睡眠处理
