### ISSUE TITLE
插入链接报错

### ISSUE THREAD

**Issue by miss131** [wangeditor-team/wangEditor#3414]
## bug 描述

你选中文字和图片再点插入链接，页面直接卡死了，看浏览器console有报错

## 你预期的样子是？

应该把选中的元素直接被a标签包裹返回

## 浏览器及版本号

chrome  91

## wangEditor 版本

最新的V4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
- 步骤一
- 富文本框中插入图片和文字，选中图片和文字，点击插入链接按钮，正常输入链接地址，点击插入

**Comment by xiaokyo** [comment]
mac中无法复现
