### ISSUE TITLE
选择表格后，没有高度，样式丑陋

### ISSUE THREAD

**Issue by BENSHAKA** [wangeditor-team/wangEditor#3415]
## bug 描述

当插入表格时，没有高度，导致填写内容时，光标错位，交互和样式都不抬友好

## 你预期的样子是？

具有默认高度，光标位置正常

## 浏览器及版本号

chrome 91.0.4472.106

## wangEditor 版本

4.6.15

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接选择插入表格即可

## 修复建议

由于给tr设置了min-height，是无效的；建议直接设置height，内容撑开后，会自动增加高度

**Comment by rsl140** [comment]
该问题已收录，请移步到 #3395 进行跟踪
