### ISSUE TITLE
选中文本后点击工具栏的 droplist 类型的 item 选区蓝色背景暂时丢失，但不影响功能

### ISSUE THREAD

**Issue by ForzaMichael** [wangeditor-team/wangEditor#3416]
## bug 描述

选中文本后点击工具栏的 droplist 类型的 item 选区蓝色背景暂时丢失，但不影响功能

## 你预期的样子是？

选中文本后点击工具栏的 item 仍显示选中区域

## 浏览器及版本号

*chrome 91*

## wangEditor 版本

*4.6.14*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

选中后点击调整字号或颜色的 tool 会暂时丢失选中显示

**Comment by ForzaMichael** [comment]
我把每个 toolItem 加了个 preventDefault：
`
document.getElementsByClassName("w-e-menu").forEach(menu => {
      menu.addEventListener("mousedown", evt => {
        evt.preventDefault();
      });
    });
`
暂时没发现有其他问题

**Comment by wangfupeng1988** [comment]
这个本来就是符合预期的。
丢失的选区，就在执行命令时再 restore 回来。
所以不用修改。

**Comment by ForzaMichael** [comment]
这竟然是符合预期的。。。。
