### ISSUE TITLE
插入视频时直接填写视频地址，不会自动生成video标签吗？

### ISSUE THREAD

**Issue by mryun11** [wangeditor-team/wangEditor#3417]
![495205AB676916CD0E1D0F6E85D73C8B](https://user-images.githubusercontent.com/12914415/123517585-60c70a80-d6d4-11eb-9c0d-60cdefdc386b.jpg)
![3B34A7FAEF0DDF7255A8DD7509FF1E76](https://user-images.githubusercontent.com/12914415/123517586-61f83780-d6d4-11eb-8a34-a11fec5344f7.jpg)

插入视频时直接填写视频地址，不会自动生成video标签吗？

**Comment by rsl140** [comment]
首先，请按照模板提交内容，否则不予受理
其次，需要自己包裹 类似于
![image](https://user-images.githubusercontent.com/7655291/123566131-8433a780-d7f1-11eb-9c15-5c7fb76e026e.png)

**Comment by mryun11** [comment]
所以需要编辑人员自行写<video>标签？是否有点不够人性化？
