### ISSUE TITLE
三击选中一行文本设置对齐方式后，选中行的下一行也会被设置成对应的对齐方式

### ISSUE THREAD

**Issue by warnerhu** [wangeditor-team/wangEditor#3418]
## bug 描述

不是鼠标拖动选中一行文本，而是三击选中一行文本并设置对齐方式后，会导致当前选中行的下一行未被选中的文本，也会被设置成和选中行同样的对齐方式。

如果两行文本之间通过回车换了行，就不会有这个问题。

## 你预期的样子是？

三击选中一行文本并设置对齐方式后，不会影响下一行未被选中的文本的对齐方式。

## 浏览器及版本号

Google Chrome 91.0.4472.124

## wangEditor 版本

v4.7.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
输入两行普通文本
（补充下，这里的两行是指通过一次回车换行形成的两个段落）
- 步骤二
三击选中第一行文本
- 步骤三
将选中行文本设置任意一个对齐方式

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/123577563-a84db380-d806-11eb-821d-8c20e357d4ae.png)

我理解的是，你在个段落输入的内容很多导致自动换行的情况下设置第一行的内容的对齐方式，发现第二行也改变了。

因为内容过多而自动换行的文本，本质上还属于同一段落，对齐方式是以段落为单位的，所以这个行为是正常的。

设想：如果按照你设想的来说，那么当 容器 的宽度变化了，一行可以容纳的文本数量变多，这又该如何呈现？

**Comment by warnerhu** [comment]
> ![image](https://user-images.githubusercontent.com/23336585/123577563-a84db380-d806-11eb-821d-8c20e357d4ae.png)
> 
> 我理解的是，你在个段落输入的内容很多导致自动换行的情况下设置第一行的内容的对齐方式，发现第二行也改变了。
> 
> 因为内容过多而自动换行的文本，本质上还属于同一段落，对齐方式是以段落为单位的，所以这个行为是正常的。
> 
> 设想：如果按照你设想的来说，那么当 容器 的宽度变化了，一行可以容纳的文本数量变多，这又该如何呈现？

我理解你的意思  但这个bug不是你理解的那样  我所说的两行是指已经通过回车换行的两个段落   而不是一行文本过长自动换行的两行

至于我描述的

> 如果两行文本之间通过回车换了行

是指已经回车换行的两个段落之间再次回车换行

另外这个bug可以直接在官网复现

**Comment by rsl140** [comment]
可以到 #3432 跟进
