### ISSUE TITLE
增加当前字号显示功能

### ISSUE THREAD

**Issue by ForzaMichael** [wangeditor-team/wangEditor#3421]
## 功能描述

增加当前字号显示功能

## 提炼几个功能点

显示当前选区或光标处字号

## 可参考的案例

https://ckeditor.com/ckeditor-5/demo/

**Comment by rsl140** [comment]
看不懂。能描述具体点么

**Comment by ForzaMichael** [comment]
![image](https://user-images.githubusercontent.com/44543789/123749536-20d87100-d8e8-11eb-84b5-5db347da1dcc.png)
显示当前字体的大小

**Comment by wangfupeng1988** [comment]
该功能将在 v5 版本实现，当前版本不做了。
![image](https://user-images.githubusercontent.com/9583120/127763655-7ed2a9f1-79c7-4ee8-8492-25739d3a800f.png)
