### ISSUE TITLE
偶发性图标丢失

### ISSUE THREAD

**Issue by xd055852859** [wangeditor-team/wangEditor#3428]
## bug 描述
图标样式错乱
## 你预期的样子是？
图标正常

## 浏览器及版本号

Google Chrome 已是最新版本
版本 91.0.4472.114（正式版本） (x86_64)

## wangEditor 版本

"wangeditor": "^4.6.10"

## 官网能否复现该 bug ？

暂时不能，偶尔发生

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/5848528/123719974-77788780-d8b5-11eb-8676-91b58a67a08f.png)
（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
调式模式下看看是不是请求数据失败了

**Comment by rsl140** [comment]
长时间未回复暂且关闭
