### ISSUE TITLE
中文状态下输入@会出现两个@@

### ISSUE THREAD

**Issue by qq1041663097** [wangeditor-team/wangEditor#3429]
## bug 描述

中文状态下输入@会出现两个@@

## 你预期的样子是？

中文状态下输入@只需要显示一个@

## 浏览器及版本号

Google Chrome 版本 89.0.4389.114

## wangEditor 版本

4.7.4

## 官网能否复现该 bug ？

不能，因为我不能执行清空操作

## 最小成本的复现步骤

- 步骤一
- 谷歌浏览器打开demo页
- 步骤二
- 使用 editor.txt.clear() 清空富文本内容
- 步骤三
- 搜狗输入法中文状态下按下shift+2，也就是@，会出现两个@
- 注：4.5.4版本是不会出现这个情况的

**Comment by rsl140** [comment]
未复现该问题

**Comment by qq1041663097** [comment]
> 未复现该问题

代码如下：
```
<div id="div1">
    <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
</div>
<script src="https://cdn.jsdelivr.net/npm/wangeditor@4.7.4/dist/wangEditor.min.js"></script>
<script type="text/javascript">
    const E = window.wangEditor
    const editor = new E('#div1')
    editor.create();
    editor.txt.clear();
</script>
```
保存为html文件，用谷歌浏览器打开，搜狗输入法中文状态下输入@

**Comment by rsl140** [comment]
抱歉，未复现该问题。

你是使用的win系统还是mac系统？

**Comment by qq1041663097** [comment]
> 抱歉，未复现该问题。
> 
> 你是使用的win系统还是mac系统？

我用的是win10系统家庭中文版64位 版本19042.867
我去群里面问了下群友，部分会出现这问题
![image](https://user-images.githubusercontent.com/47656506/124211430-a4c86e00-db1f-11eb-845c-c859a320b2a8.png)

**Comment by rsl140** [comment]
由于是偶发性的问题，这边暂时复现不了，就不太好定位的问题所在，先待定吧

**Comment by zhawf** [comment]
附议，偶发性，仅出现在初始化后首次按下某个键，一次初始化至多出现一次

**Comment by Gulang10783** [comment]
亲测使用4.4.0的版本是不会出现这个问题的，推荐先使用这个

**Comment by zouyuanfeng** [comment]
同遇到这问题了，用最新的4.7.8的版本也会出现。win10系统的
