### ISSUE TITLE
在序列状态下，对序列内某行增加超链接会改变序列格式，且插入的超链接无效

### ISSUE THREAD

**Issue by Damugua20** [wangeditor-team/wangEditor#3430]
## bug 描述

在序列状态下，对序列内某行增加超链接会改变序列格式，且插入的超链接无效。

## 你预期的样子是？

不改变序列且超链接有效

## 浏览器及版本号

chrome最新91.04472.114

## wangEditor 版本

4.73

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

选择官网的某个序列的某2个字，添加超链接。

![无标题](https://user-images.githubusercontent.com/86652843/123761110-158b4280-d8f4-11eb-977b-43cec6167f44.png)

**Comment by liuqh0609** [comment]
交叉测试人： @Gavin-yh
