### ISSUE TITLE
在nuxt使用,表情为什么不是带颜色的而是黑白,我不知道哪里使用错误了

### ISSUE THREAD

**Issue by QiZZ121** [wangeditor-team/wangEditor#3431]
## 问题描述

在nuxt使用,表情为什么不是带颜色的而是黑白,我不知道哪里使用错误了

## wangEditor 版本

V4.7.4

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
在nuxt中使用时发现与demo表情颜色不一样，我查看了文档不确定是哪里用错了，不在项目中直接使用却是正常的下面是我的使用截图
![avatar](https://pic4.zhimg.com/80/v2-1bf069f8037befea1ac52e5192f35dd5_720w.png)

**Comment by liuqh0609** [comment]
nuxt是在服务端完成渲染的，可能服务端系统中是没有这个表情库的所以会造成这种情况。我们目前的表情选择的都是win/mac系统支持的表情

**Comment by QiZZ121** [comment]
和nuxt没有关系，查了下这个emoji字符的支持，似乎是由于window7不支持这种彩色字符，才显示了灰色表情，在window8以上好像是正常显示的

**Comment by QiZZ121** [comment]
不过window7更新这个也说是可以支持的，我没有进行更新过：
https://support.microsoft.com/en-us/topic/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-server-2008-r2-is-available-0743a473-3afe-e8b2-7c20-54aa430463d6

**Comment by QiZZ121** [comment]
不过window7更新这个也说是可以支持的，我没有进行更新过：
https://support.microsoft.com/en-us/topic/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-server-2008-r2-is-available-0743a473-3afe-e8b2-7c20-54aa430463d6
