### ISSUE TITLE
三击全选中某行，然后换标题格式，会把下面那行的标题格式也改变

### ISSUE THREAD

**Issue by Damugua20** [wangeditor-team/wangEditor#3432]
## bug 描述

三击选中某行，然后换标题格式，会把下面那行的标题格式也改变

## 你预期的样子是？

只改变当前行

## 浏览器及版本号

chrome最新91.04472.114

## wangEditor 版本

4.73

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

三击选中官网“在线体验 demo”这行，然后改变标题，会把下面那行也改变成对应标题。
（好像是三击完判断把下面那段的开头也选中了。直接框选那行之后改标题格式，不会有问题。
![无标题1](https://user-images.githubusercontent.com/86652843/123889982-11f5cb00-d989-11eb-99ff-6da8716a3269.png)
![无标题2](https://user-images.githubusercontent.com/86652843/123889991-13bf8e80-d989-11eb-992e-65c4e801b689.png)
）

**Comment by a835100635** [comment]
v4 暂时没有好的解决方案，v5 已经解决了这个问题

**Comment by warnerhu** [comment]
> v4 暂时没有好的解决方案，v5 已经解决了这个问题

请问 v5 有明确发布时间吗
