### ISSUE TITLE
待办事项和中文输入法的冲突

### ISSUE THREAD

**Issue by yipanhuasheng** [wangeditor-team/wangEditor#3433]
## bug 描述

*在新的一行，点击待办事项，然后中文搜狗输入法，输入中文，第一个汉字会拼不出来，只呈现该汉字的首字母*

## 你预期的样子是？

*正常出现输入的文字*

## 浏览器及版本号

*chrome版本 91.0.4472.114（正式版本） (x86_64)*

## wangEditor 版本

*官网版本*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：点击待办事项
- 步骤二：输入汉字
- 步骤三：出现文字不全的问题

## 补充一下：
1.目前删除空待办事项后边文字会直接删除掉多选框，这个交互感觉不太友好啊，感觉像bug。
2.在清空文字，多选框被自动删除时，文本框在聚焦状态，但是再点击待办事项就失焦了，不会重新创建待办。在正常的删除多选框情况下，不会出现这种问题。

**Comment by yipanhuasheng** [comment]
![image](https://user-images.githubusercontent.com/18358639/124057765-b0059600-da5a-11eb-80ac-88aa3bded2b3.png)
首字母没有被拼入输入法

**Comment by Nicholaslanic** [comment]
我也遇到了这个情况，首次输入过程中，输入第一个字母时，输入法会被关闭，第一个字母可能会消失；
如果前面输入空格就没问题了，好奇怪

**Comment by Nicholaslanic** [comment]
我也遇到了这个情况，首次输入过程中，输入第一个字母时，输入法会被关闭，第一个字母可能会消失；
如果前面输入空格就没问题了，好奇怪

**Comment by rsl140** [comment]
请移步到 #3423 进行跟踪该问题
