### ISSUE TITLE
选中字段，插入超链接后，字段的字体大小被设置会原来的样子

### ISSUE THREAD

**Issue by Damugua20** [wangeditor-team/wangEditor#3434]
## bug 描述

选中字段，插入超链接后，字段的字体大小被设置会原来的样子

## 你预期的样子是？

不改变字体大小

## 浏览器及版本号

chrome最新

## wangEditor 版本

4.7.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

选中“体验”，修改字体大小。之后插入超链接，“体验”变回原来的大小
![无标题](https://user-images.githubusercontent.com/86652843/124096875-9598e000-da8d-11eb-88b5-7207b0fc8b61.png)
![无标题1](https://user-images.githubusercontent.com/86652843/124096880-96ca0d00-da8d-11eb-8757-55d0fd0cb836.png)

**Comment by yixiaoyan1** [comment]
请问这个问题解决了吗？我也遇到这个问题了

**Comment by Gavin-yh** [comment]
> 请问这个问题解决了吗？我也遇到这个问题了

在处理了

**Comment by Gavin-yh** [comment]
> 请问这个问题解决了吗？我也遇到这个问题了

可以用下这个地址，看还有没有这个问题。http://106.12.198.214:8881/master/examples/index.html
