### ISSUE TITLE
点击上传图片按钮，然后点击图片上传后，按钮的tooltip未能隐藏

### ISSUE THREAD

**Issue by mlshan** [wangeditor-team/wangEditor#3435]
## bug 描述

点击上传图片按钮，然后点击图片上传后，按钮的tooltip未能隐藏，如图
1.
![image](https://user-images.githubusercontent.com/37204782/124101606-1ce85280-da92-11eb-9d5b-b0f651f5ef8d.png)
2.
![image](https://user-images.githubusercontent.com/37204782/124101636-27a2e780-da92-11eb-8376-754cf9adffd4.png)

## 你预期的样子是？

![image](https://user-images.githubusercontent.com/37204782/124101726-3a1d2100-da92-11eb-8cb8-fa213c3ca690.png)
图片按钮tooltip隐藏

## 浏览器及版本号

谷歌

## wangEditor 版本

4.7.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 点击上传图片按钮
- 步骤二
- 点击上传图标
- 步骤三
- 
![image](https://user-images.githubusercontent.com/37204782/124102366-e232ea00-da92-11eb-80b7-84a65d931bfa.png)

**Comment by rsl140** [comment]
未复现该问题，鼠标移出菜单栏就会隐藏了

**Comment by mlshan** [comment]
你好，这是步骤![image](https://user-images.githubusercontent.com/37204782/124213519-4d2c0180-db23-11eb-83a2-70a2e02cd497.png)

**Comment by rsl140** [comment]
当点击上传按钮后会弹出文件选择，所以其实不影响的。
本质上是根据菜单栏的鼠标移入移出设计的显隐。
