### ISSUE TITLE
无法正常插入网络图片

### ISSUE THREAD

**Issue by Karroyling** [wangeditor-team/wangEditor#3437]
## bug 描述

无法插入网络图片

## 你预期的样子是？

正常插入网络图片

## 浏览器及版本号

Google Chrome 91.0.4472.114
## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 点击插入网络图片
- 步骤二
- https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimage.tianjimedia.com%2FuploadImages%2F2020%2F100%2F17%2F8X95OQW1U332.jpg&refer=http%3A%2F%2Fimage.tianjimedia.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1627789614&t=f02737c5ff27afe13a942d2a3a2ceb57
- 步骤三
- 提示报错：插入图片错误

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/124228576-f8967f80-db3e-11eb-819b-190da298ae3b.png)

![image](https://user-images.githubusercontent.com/7655291/124228598-fd5b3380-db3e-11eb-9452-90e4386e4c92.png)

**Comment by rsl140** [comment]
长时间未回复暂且关闭
