### ISSUE TITLE
如何单独引入样式文件？

### ISSUE THREAD

**Issue by Yangjia23** [wangeditor-team/wangEditor#3438]
## 问题描述

目前在开发一款chrome 插件，在网页上划词后会弹出表单，表单中有使用到 wangEditor 进行输入，但目前 wangEditor 样式无法正常显示

<img width="327" alt="截屏2021-07-02 下午1 55 02" src="https://user-images.githubusercontent.com/20862209/124227650-9db05880-db3d-11eb-93a3-43579f25eff7.png">

*请输入遇到的问题...*
wangEditor 样式无法正常显示，具体原因是因为

我们为了插件和每个网页的样式不会互相影响，划词之后的弹窗的 DOM 和 CSS 都插入到  shadow DOM 中，但 wangEditor 的样式默认是通过 style-loader 插入到页面的 <head> 中，所有不生效

<img width="505" alt="截屏2021-07-02 下午1 50 23" src="https://user-images.githubusercontent.com/20862209/124227718-b456af80-db3d-11eb-8e5c-0171126f791c.png">
<img width="313" alt="截屏2021-07-02 下午1 55 57" src="https://user-images.githubusercontent.com/20862209/124227749-bcaeea80-db3d-11eb-8b64-4c831046a449.png">

## 我的期望

wangEditor 的样式能打包成单独的文件，可以单独引入

## wangEditor 版本

```"wangeditor": "^4.7.4"```

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
v4 暂时不支持。
v5 会拆分 js 和 css
