### ISSUE TITLE
复制粘贴图片，出现重复图片。官网也能重现该问题。

### ISSUE THREAD

**Issue by biology-w** [wangeditor-team/wangEditor#3439]
## bug 描述
重复图片
https://github.com/wangeditor-team/wangEditor/issues/3363#issuecomment-862008786

复制一张图片，粘贴后出现两张同样图片。
## 你预期的样子是？
只有一张

## 浏览器及版本号
chrome 91 
![image](https://user-images.githubusercontent.com/25600705/124233281-42826400-db45-11eb-92b9-07edb6336612.png)

## wangEditor 版本
4.7.4

## 官网能否复现该 bug ？
能
![image](https://user-images.githubusercontent.com/25600705/124233442-6ba2f480-db45-11eb-9d0b-8ca0b1020c30.png)

## 最小成本的复现步骤
（请告诉我们，如何最快的复现该 bug）
- 步骤一
- 在微信或者文件夹内鼠标右击复制一张图片
- 步骤二
- 然后点击wangEditor编辑框
- 步骤三
- 鼠标右击粘贴，出现重复图片。

**Comment by rsl140** [comment]
该问题已收录，请移步至#3407 进行跟踪
