### ISSUE TITLE
增加缩进和减少缩进，添加的属性为padding-left:2em，实际需求为段落首行缩进text-indent:2em

### ISSUE THREAD

**Issue by mlshan** [wangeditor-team/wangEditor#3440]
## 问题描述

增加缩进和减少缩进，为段落添加的属性为padding-left:2em，整个段落右移，实际需求为段落首行缩进text-indent:2em

## wangEditor 版本

4.7.4

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

在段落前放置光标，点击缩进按钮

**Comment by wangfupeng1988** [comment]
你说的“首行缩进”和“段落缩进”不一样。
首行缩进，你可以自己用 css 实现。
