### ISSUE TITLE
Error: 无效的节点选择器：#editor

### ISSUE THREAD

**Issue by dongfenglong** [wangeditor-team/wangEditor#3443]
## 问题描述

*vue从v3.0.*升级到3.1.*版本后，提示错误无效的节点选择器：#editor*

## wangEditor 版本

*4.7.5*

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*文档链接404了*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
 vue升级到3.1.4，目前3.1.*其他版本有bug，项目无法正常运行
- 步骤二
 添加我提供的组件代码，即可复现。

================================================

> <template>
    <div id="editor" ref="editor"></div>
</template>

<script lang="ts">
import { defineComponent, onMounted, onBeforeUnmount, ref } from 'vue'
import E from 'wangeditor'
import 'highlight.js/styles/monokai-sublime.css'

export default defineComponent({
  name: 'WangEditor',
  emits: ['change'],
  props: {
    content: String
  },
  setup (props, { emit }) {
    const editor = ref()
    const edit = new E('#editor')
    //
    // let instance = reactive<any>({})
    onMounted(() => {
      edit.config.height = 500
      Object.assign(edit.config, {
        onchange (html: string) {
          if (props.content !== html) {
            console.log('内容：', html)
            emit('change', html)
          }
        }
      })

      edit.config.zIndex = 1
      // 插入代码语言配置
      edit.config.languageType = [
        'Go',
        'Bash',
        'CSS',
        'JavaScript',
        'JSON',
        'TypeScript',
        'Plain text',
        'Html',
        'SQL',
        'Markdown'
      ]
      // 设置languageTab
      edit.config.languageTab = '  '
      edit.create()
      edit.txt.html(props.content)
    })

    onBeforeUnmount(() => {
      edit.destroy()
    })

    return {
      editor
    }
  }
})
</script>

<style scoped>

</style>

**Comment by shi-lai-mu** [comment]
> ## 问题描述
> *vue从v3.0.*升级到3.1._版本后，提示错误无效的节点选择器：#editor_
> 
> ## wangEditor 版本
> _4.7.5_
> 
> ## 是否查阅了文档 ？
> （文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）
> 
> _文档链接404了_
> 
> ## 最小成本的复现步骤
> （请告诉我们，如何**最快的**复现该问题？）
> 
> * 步骤一
>   vue升级到3.1.4，目前3.1.*其他版本有bug，项目无法正常运行
> * 步骤二
>   添加我提供的组件代码，即可复现。
> 
> ================================================
> 
> > ```
> > <div id="editor" ref="editor"></div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > <script lang="ts">
> > import { defineComponent, onMounted, onBeforeUnmount, ref } from 'vue'
> > import E from 'wangeditor'
> > import 'highlight.js/styles/monokai-sublime.css'
> > 
> > export default defineComponent({
> >   name: 'WangEditor',
> >   emits: ['change'],
> >   props: {
> >     content: String
> >   },
> >   setup (props, { emit }) {
> >     const editor = ref()
> >     const edit = new E('#editor')
> >     //
> >     // let instance = reactive({})
> >     onMounted(() => {
> >       edit.config.height = 500
> >       Object.assign(edit.config, {
> >         onchange (html: string) {
> >           if (props.content !== html) {
> >             console.log('内容：', html)
> >             emit('change', html)
> >           }
> >         }
> >       })
> > 
> >       edit.config.zIndex = 1
> >       // 插入代码语言配置
> >       edit.config.languageType = [
> >         'Go',
> >         'Bash',
> >         'CSS',
> >         'JavaScript',
> >         'JSON',
> >         'TypeScript',
> >         'Plain text',
> >         'Html',
> >         'SQL',
> >         'Markdown'
> >       ]
> >       // 设置languageTab
> >       edit.config.languageTab = '  '
> >       edit.create()
> >       edit.txt.html(props.content)
> >     })
> > 
> >     onBeforeUnmount(() => {
> >       edit.destroy()
> >     })
> > 
> >     return {
> >       editor
> >     }
> >   }
> > })
> > </script>
> > <style scoped>
> > 
> > </style>

可以试着把 `new E('#editor')` 放到 `onMounted` 内

**Comment by shi-lai-mu** [comment]
可以试着把 `new E('#editor')` 放到 `onMounted` 内

**Comment by dongfenglong** [comment]
可以了，谢谢。

**Comment by HuRuilin** [comment]
> 可以试着把 `new E('#editor')` 放到 `onMounted` 内

我在vue2 项目中也遇到了同样的问题，调用的方法是写在mounted 中的，但仍然报同样的错。尝试将调用放在settimeout 回调中， 请问可能是什么原因呢？
```
  mounted() {
        const editor = new E('#editor');
        editor.create();
    }
```

**Comment by shi-lai-mu** [comment]
> > 可以试着把 `new E('#editor')` 放到 `onMounted` 内
> 
> 我在vue2 项目中也遇到了同样的问题，调用的方法是写在mounted 中的，但仍然报同样的错。尝试将调用放在settimeout 回调中， 请问可能是什么原因呢？
> 
> ```
>   mounted() {
>         const editor = new E('#editor');
>         editor.create();
>     }
> ```

主要原因是需要创建编辑器的节点未被渲染，除了生命周期外也有可能是：选择的节点在组件内但组件未被渲染、节点外层有v-if，可以用原生的dom选择方法去确认目标是否能在创建阶段获取

**Comment by HuRuilin** [comment]
> > > 可以试着把 `new E('#editor')` 放到 `onMounted` 内
> > 
> > 
> > 我在vue2 项目中也遇到了同样的问题，调用的方法是写在mounted 中的，但仍然报同样的错。尝试将调用放在settimeout 回调中， 请问可能是什么原因呢？
> > ```
> >   mounted() {
> >         const editor = new E('#editor');
> >         editor.create();
> >     }
> > ```
> 
> 主要原因是需要创建编辑器的节点未被渲染，除了生命周期外也有可能是：选择的节点在组件内但组件未被渲染、节点外层有v-if，可以用原生的dom选择方法去确认目标是否能在创建阶段被获取到

谢谢，问题已解决。原因确实如你所言，我用于创建编辑器的节点在el-dialog 的插槽中，el-dialog 可能出于性能优化的原因，插槽里的内容做了懒加载，导致该节点在初始化的时候，未被获取到，所以编辑器创建失败。

**Comment by NeoZephyr** [comment]
怎么解决的啊，我也遇到这个问题了，而且我的那个 div 在 ant 的 modal 表单里面，就算是在 onMounted 里面去 create 还是会有问题，因为modal 没有打开，然后没有渲染，就找不到

**Comment by dongfenglong** [comment]
> 怎么解决的啊，我也遇到这个问题了，而且我的那个 div 在 ant 的 modal 表单里面，就算是在 onMounted 里面去 create 还是会有问题，因为modal 没有打开，然后没有渲
![{4KY49_39C`@N6WS%JT_F3A](https://user-images.githubusercontent.com/6386364/141707478-e5492753-6711-4583-9a52-807a673ed638.png)
染，就找不到
