### ISSUE TITLE
Angular8+antd+ts框架中，npm安装wangEditor后，运行项目，报错

### ISSUE THREAD

**Issue by yourhug** [wangeditor-team/wangEditor#3444]
## bug 描述

Angular8中，npm安装wangEditor后，运行项目，报错，内容为如下：

    ERROR in node_modules/wangeditor/dist/editor/history/index.d.ts(18,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/wangeditor/dist/menus/menu-constructors/DropList.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/wangeditor/dist/menus/menu-constructors/Menu.d.ts(35,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/wangeditor/dist/menus/menu-constructors/Tooltip.d.ts(39,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/wangeditor/dist/utils/dom-core.d.ts(14,64): error TS2716: Type parameter 'T' has a circular default.
    node_modules/wangeditor/dist/utils/dom-core.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/wangeditor/dist/utils/observer/mutation.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.

## 你预期的样子是？

安装完成后，正常启动项目

## 浏览器及版本号

Microsoft Edge
版本 91.0.864.64 (官方内部版本) (64 位)

## wangEditor 版本

v4.7.5

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 步骤一：安装 angular+antd+ts框架
- 步骤二：安装 wangEditor依赖
- 步骤三：启动项目yarn start 或 npm start

**Comment by shi-lai-mu** [comment]
这是因为typescript版本过旧导致的问题大致为`3.5.x`版本，可以试着下面两个方案
1. 如果可以请升级Angular
2. 可以试着升级devDependencies typescript版本`>= 3.7.0-beta`
> 如果出现Angular TypeScript版本警告，请在tsconfig.json中的angularCompilerOptions添加disableTypeScriptVersionCheck为true，跳出版本检测

**Comment by shi-lai-mu** [comment]
这是因为typescript版本过旧导致的问题大致为`3.5.x`版本，可以试着下面两个方案
1. 如果可以请升级Angular
2. 可以试着升级devDependencies typescript版本`>= 3.7.0-beta`
> 如果出现Angular TypeScript版本警告，请在tsconfig.json中的angularCompilerOptions添加disableTypeScriptVersionCheck为true，跳出版本检测

**Comment by yourhug** [comment]
> 这是因为typescript版本过旧导致的问题大致为`3.5.x`版本，可以试着下面两个方案
> 
> 1. 如果可以请升级Angular
> 2. 可以试着升级devDependencies typescript版本`>= 3.7.0-beta`
> 
> > 如果出现Angular TypeScript版本警告，请在tsconfig.json中的angularCompilerOptions添加disableTypeScriptVersionCheck为true，跳出版本检测

好的，通过第二个方案解决了改问题，感谢

**Comment by yourhug** [comment]
@shi-lai-mu 
好的，通过第二方案，解决了报错问题，感谢
