### ISSUE TITLE
上传图片配置图片服务端接口，隐藏网络图片功能，不弹出Panel

### ISSUE THREAD

**Issue by TimeBooksGit** [wangeditor-team/wangEditor#3445]
## bug 描述

Vue项目（2.6.12），配置图片服务端接口，隐藏网络图片功能，不弹出Panel

## 你预期的样子是？

panel弹出，上传图片Tab展示，网路图片Tab隐藏
如上传视频的形式

## 浏览器及版本号

Google Chrome 版本 91.0.4472.124

## wangEditor 版本

4.7.4

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

上传图片功能：
操作步骤：
1. npm安装wangEditor
2. new 一个实例
3. 配置上传图片服务端接口
4. 隐藏插入网路图片功能
5. 点击工具条上传图片按钮

表现形式：
panel不弹出

**Comment by rsl140** [comment]
你好 发一下具体的配置代码呢

**Comment by TimeBooksGit** [comment]
> 你好 发一下具体的配置代码呢

#package.json
"dependencies": {
      ......
      "vue": "2.6.12",
      "wangeditor": "^4.7.5"
 }

# vue文件
<template>
    <div id="WEditor"></div>
</template>

<script>
import WEditor from 'wangeditor';

export default {
    mounted() {
        const editor = new WEditor(`#WEditor`);

        editor.config.uploadImgServer = '/upload-img'
        editor.config.showLinkImg = false

        // 创建编辑器
        editor.create()
    }
};
</script>

**Comment by UltramanWeiLai** [comment]
这个我记得是当隐藏了网络图片的 tab 的时候，默认不再弹出 panel 直接触发图片选择框

**Comment by TimeBooksGit** [comment]
> 这个我记得是当隐藏了网络图片的 tab 的时候，默认不再弹出 panel 直接触发图片选择框

如果是这样的话，和视频的表现形式就不太一样了，感觉不是太友好

**Comment by rsl140** [comment]
其实，当你隐藏了网络图片的 tab 的时候，默认就是上传本地图片了，这时候再弹出panel 话 其实并没有需要用户选择或者填写的情况了，是为了简化用户的多余操作

**Comment by TimeBooksGit** [comment]
> 其实，当你隐藏了网络图片的 tab 的时候，默认就是上传本地图片了，这时候再弹出panel 话 其实并没有需要用户选择或者填写的情况了，是为了简化用户的多余操作

只是为了实现和视频的表现形式一样，因为图片和视频都属于媒体类，表现形式略有差异，体验上不太好

**Comment by UltramanWeiLai** [comment]
> > 其实，当你隐藏了网络图片的 tab 的时候，默认就是上传本地图片了，这时候再弹出panel 话 其实并没有需要用户选择或者填写的情况了，是为了简化用户的多余操作
> 
> 只是为了实现和视频的表现形式一样，因为图片和视频都属于媒体类，表现形式略有差异，体验上不太好

这个我记得是有个属性可以配置的，可以查询文档看看
设置 editor.config.showLinkImg = false 即可隐藏插入网络图片的功能，即只保留上传本地图片。
而且这个好像还是主动配置才会隐藏
