### ISSUE TITLE
支持点击菜单栏按钮时弹出弹窗，关闭弹窗时可携带回调

### ISSUE THREAD

**Issue by AWhiteMouse** [wangeditor-team/wangEditor#3447]
目前的应用场景是，点击菜单栏按钮，弹出公式编辑器弹窗，编写完成之后，可关闭弹窗，回传公式表达式（字符串形式）

**Comment by UltramanWeiLai** [comment]
请按照模板进行提交，否则是不受理的。

就你描述的这个意思，我觉得是以有的，比如 图片上传、视频上传 等功能按钮的模式都符合你所说的。
