### ISSUE TITLE
字号设置问题

### ISSUE THREAD

**Issue by dandanXO** [wangeditor-team/wangEditor#3448]
## 问题描述

想问 #292 已经有做出优化了吗?
目前使用还是有这个问题
没有输入之前，设置字体大小不起作用，必须通过选中文字才能设置字号，而且没有显示当前选择的字号大小，有点不太方便
## wangEditor 版本
v3
v4

## 是否查阅了文档 ？

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

是

## 最小成本的复现步骤
2個問題
1. 不输入选择字号或自体再输入不会生效
or
1. 输入到一半换字号往后的字号也不使用新的字号而是前面文档的字号

**Comment by wangfupeng1988** [comment]
首先感谢反馈，这两条都是非常好的优化建议。
不过在 v4 版本中不太好加。

我们正在研发 v5 版本，到时将全面解决你提到的类似问题。
v5 目前基本功能已经研发完成了，接下来将我们内部测试，然后就是阻止用户试用，最后发布。
敬请期待吧～

![image](https://user-images.githubusercontent.com/9583120/124708727-3de6f280-df2d-11eb-8a00-7495a40c1a01.png)
