### ISSUE TITLE
无内容的情况下粘贴一段文本，粘贴后光标位于行首而不是粘贴内容的行尾

### ISSUE THREAD

**Issue by CristoMonte** [wangeditor-team/wangEditor#3449]
## bug 描述

无内容的情况下粘贴一段文本，粘贴后光标位于行首而不是粘贴内容的行尾

## 你预期的样子是？

无内容的情况下粘贴一段文本，粘贴后光标位于行尾

## 浏览器及版本号

chrome 91.0.4472.114

## wangEditor 版本

4.7.4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 删除所有内容，让编辑器回到初始化状态，出现placeholder；
- 粘贴文本，光标位于粘贴文本的首部；

**Comment by rsl140** [comment]
未复现该问题，
粘贴的文体是粘贴的什么样的？

**Comment by CristoMonte** [comment]
目前只发现从IDE vscode中随便粘贴一段文字或者一个字符都会出现这个问题，其他途径的确没有这种情况出现。
