### ISSUE TITLE
内容清空后设置标题导致报错

### ISSUE THREAD

**Issue by shi-lai-mu** [wangeditor-team/wangEditor#3450]
## bug 描述
复制一段内容进去后删除全部文本内容，设置标题出现报错后所有菜单功能全部报错，内容区域无法编辑
![image](https://user-images.githubusercontent.com/45140991/124690315-935ed780-df0c-11eb-89b7-12fcbd597923.png)

## 你预期的样子是？

点击标题后，菜单功能正常、内容正常编辑

## 浏览器及版本号

Chrome/91.0.4472.124

## wangEditor 版本

v4.7.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
- 全选删除编辑器内容  or  粘贴任意内容全选删除
- 点击设置标题

**Comment by wangfupeng1988** [comment]
该问题重复了，之前已被提问、受理。
