### ISSUE TITLE
增加复制图片文件后粘贴的功能

### ISSUE THREAD

**Issue by yangdan8** [wangeditor-team/wangEditor#3452]
## 功能描述

如题

## 可参考的案例

可参考ueditor就支持这种方式

**Comment by rsl140** [comment]
你是说本地找个图片 然后复制粘贴？

**Comment by rsl140** [comment]
长时间未回复，暂且关闭

**Comment by yangdan8** [comment]
> 长时间未回复，暂且关闭
是的，选中资源管理器中文件，然后复制文件，然后到wangEditor粘贴
