### ISSUE TITLE
菜单增加点击触发或鼠标经过触发配置

### ISSUE THREAD

**Issue by HelloCPL** [wangeditor-team/wangEditor#3453]
## 功能描述
一、菜单如果是下拉选择（如标题、字号选择）的菜单，需要点击触发下拉选择框，这样跟直接点击触发的功能菜单（如下划线）雷同，造成用户使用不便与疑惑，建议下拉菜单新增鼠标经过触发配置
二、菜单新增自定义图标配置，编辑器本身的图标不能配置，使用与场景不搭配不美观（如字体颜色图标等），建议默认菜单也可增加图标自定义或内容自定义

**Comment by rsl140** [comment]
v5版本中已改进为鼠标经过触发，敬请期待
自定义图标的话，有待考量。
