### ISSUE TITLE
 Known security vulnerability in 4.7.5 

### ISSUE THREAD

**Issue by uniquejava** [wangeditor-team/wangEditor#3455]
漏洞扫描工具在我们的前端项目中找到的security vulnerability。 咋办？ 应该是2年前就有了， 没人关注吗？

![image](https://user-images.githubusercontent.com/1049271/124857820-8959d900-dfdf-11eb-8e23-f0f4258fc552.png)

应该如何向 产品部门 或者 安全部门 说明？

**Comment by uniquejava** [comment]
或者有没有什么 workaround 或者 option 可以屏蔽相关的功能， 让项目可以通过扫描

**Comment by wangfupeng1988** [comment]
感谢再次反馈，我安排一下，高优去修复一些比较明显的 xss 
- 插入链接
- 插入网络图片
- 插入视频

但我目前还不知道修复完之后，能否完全通过 npm 的安全检查。我还没有来得及去调研它详细的检查规则。
总之，先修复明显的吧，完事儿再观察。

PS：近期我一直在努力的开发 V5 ，工作量和难度都很大，所以 V4 的 issue 没有及时处理。在此表示抱歉。

**Comment by leohai** [comment]
如插入连接时输入 `1"/> <script>alert("xss");</script>`，html结构改变了，注入了script标签

![5b790b1e8a9a7b61fe4009ac54aacaa](https://user-images.githubusercontent.com/34530234/129676493-81479b3c-3793-42ef-9163-270473edf126.png)

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
