### ISSUE TITLE
无法插入代码，以代码形式转成预览模式

### ISSUE THREAD

**Issue by fantacy-Xu** [wangeditor-team/wangEditor#3456]
## bug 描述
无法把Facebook ，youtube 生成的第三方引用代码插入在富文本中显示出来

## 你预期的样子是？
可以把 Facebook ，youtube 生成的第三方引用代码插入在富文本中显示出来；
例如：可以嵌入这段YouTube的代码 
<iframe width="560" height="315" src="https://www.youtube.com/embed/faoCe_gLuy0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## 浏览器及版本号
谷歌浏览器  版本 91.0.4472.124（正式版本）
## wangEditor 版本
lasted
## 官网能否复现该 bug ？
能
## 最小成本的复现步骤
没有入口将代码放入富文本中显示出效果

- 步骤一
- 步骤二
- 步骤三

**Comment by shi-lai-mu** [comment]
这边尝试似乎可以进行预览
![image](https://user-images.githubusercontent.com/45140991/124866017-4d7a4000-dfee-11eb-8547-b08c211137cb.png)

**Comment by rsl140** [comment]
需要科学上网才能显示出来
