### ISSUE TITLE
可以加个清除格式的菜单吗

### ISSUE THREAD

**Issue by Phoenix-s** [wangeditor-team/wangEditor#3457]
## 功能描述

就输入内容和加了格式后，加个一键清除格式的菜单按钮

## 可参考的案例

![微信图片_20210711155912](https://user-images.githubusercontent.com/52309291/125187192-f4fea900-e260-11eb-9b75-cef857d98bdd.png)

**Comment by rsl140** [comment]
请移步至#2528 跟进
