### ISSUE TITLE
复制文字+图片到富文本中会提示报错,Not allowed to load local resource

### ISSUE THREAD

**Issue by ChenWilling** [wangeditor-team/wangEditor#3460]
## bug 描述

*复制文字+图片到富文本中会提示报错,Not allowed to load local resource*

## 你预期的样子是？

*文字和图片会显示出来*

## 浏览器及版本号

*chrome 91.0.4472.124*

## wangEditor 版本

*最新版 V4.7.5*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一:从word中一起复制文字和图片
- 步骤二:粘贴到富文本中
- 步骤三

**Comment by rsl140** [comment]
只支持单独粘贴图片，图文粘贴 本地图片会受浏览器安全限制，粘贴不进来的

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
