### ISSUE TITLE
QQ截屏图片粘贴这个功能在谷歌浏览器中有BUG，会出错

### ISSUE THREAD

**Issue by zxjhyb** [wangeditor-team/wangEditor#3461]
## bug 描述
QQ截屏图片粘贴在编辑器上传到指定服务器功能在谷歌浏览器中有BUG出错。

## 你预期的样子是？
正常上传到指定服务器，正常显示

## 浏览器及版本号
谷歌浏览器 隐私模式 版本 91.0.4472.124（正式版本） （64 位）

## wangEditor 版本
V3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
QQ截屏到聊天窗口，发送不发送都可以，然后复制该图片直接到编辑器中进行粘贴，会没有反应，然后F12查看console中输出JS错误：Uncaught TypeError: Cannot read property 'name' of null
    at Array.<anonymous> (wangEditor.min.js:16)
    at Object.t.arrForEach (wangEditor.min.js:16)
    at r.uploadImg (wangEditor.min.js:16)
    at i (wangEditor.min.js:16)
    at wangEditor.min.js:16
    at wangEditor.min.js:16
    at Array.forEach (<anonymous>)
    at HTMLDivElement.<anonymous> (wangEditor.min.js:16)
(anonymous) @ wangEditor.min.js:16
t.arrForEach @ wangEditor.min.js:16
r.uploadImg @ wangEditor.min.js:16
i @ wangEditor.min.js:16
(anonymous) @ wangEditor.min.js:16
(anonymous) @ wangEditor.min.js:16
(anonymous) @ wangEditor.min.js:16
（请告诉我们，如何最快的复现该 bug）

**Comment by rsl140** [comment]
未复现该问题

**Comment by gyjpz** [comment]
我也出现了这个问题

**Comment by zxjhyb** [comment]
在官网操作也是有同样的错误，不能发视频，能发视频了我发个视频给你。刚刚又去https://www.wangeditor.com/官网试了，从QQ聊天窗口复制一张图片往编辑器里粘贴，没反应，查console有上边提交的报错。

**Comment by rsl140** [comment]
win10系统上复现
