### ISSUE TITLE
复制图片后去编辑器粘贴会出现两张

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3462]
## bug 描述

复制图片后去编辑器粘贴会出现两张，但是截图后粘贴正常。

## 你预期的样子是？

只出现一张图片

## 浏览器及版本号

chorme 最新版

## wangEditor 版本

4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

复制微信聊天的图片 然后ctrl+v进行粘贴

**Comment by rsl140** [comment]
该问题已收录，请移步至#3407 进行跟进

**Comment by OnePsycho** [comment]
但还是没有得到解决方案呢

**Comment by OnePsycho** [comment]
> 该问题已收录，请移步至#3407 进行跟进

是否有解决方案？
