### ISSUE TITLE
文字加粗/斜体/下划线出现​&#8203;字符

### ISSUE THREAD

**Issue by yyf821** [wangeditor-team/wangEditor#3463]
## bug 描述

点击加粗，会把光标后的文字加粗，此时再点击加粗/斜体/下划线，会多出一个如下标签，
`<span style="font-size: 14px;">​&#8203;</span>`
点击多次会新增多个标签
## 你预期的样子是？

文字能够显示正确的样式

## 浏览器及版本号

chrome 版本 72.0.3626.121（正式版本） （32 位）

## wangEditor 版本

v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 新建空白行
- 点击加粗/斜体/下划线，输入一些文字
- 再点击加粗/斜体/下划线，再输入一些文字

**Comment by rsl140** [comment]
未复现该问题

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
