### ISSUE TITLE
清空编辑器，输入中文时，删除完所有拼音再次输入，会出现第一个拼音被吞的情况

### ISSUE THREAD

**Issue by hzf-666** [wangeditor-team/wangEditor#3467]
## bug 描述

*输入中文时，只输入拼音然后删除完，再次输入拼音，第一个拼音会不见*

## 你预期的样子是？

*再次输入拼音不会被吞掉第一个*

## 浏览器及版本号

*谷歌浏览器、QQ浏览器，其他浏览器估计也会，都是最近的版本*

## wangEditor 版本

*^4.5.2*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 在官网清空编辑器，打开中文输入法
- 连按三次q键，然后再按三次删除键
- 重新按下q键，中文输入法没有出现q

**Comment by rsl140** [comment]
#3423 已收录
