### ISSUE TITLE
能否优化代码块的显示效果？

### ISSUE THREAD

**Issue by dongfenglong** [wangeditor-team/wangEditor#3468]
## 功能描述

*能否优化代码块的显示效果？*

## 提炼几个功能点

- 能否开发原型图中这种mac风格的代码块？

## 原型图
![1626340746(1)](https://user-images.githubusercontent.com/6386364/125764474-32842a5d-d729-44b7-9497-e9ae0a0d9cd1.jpg)

## 可参考的案例

*参考链接：https://editor.mdnice.com/*

**Comment by wangfupeng1988** [comment]
看你给的案例，是在预览显示的时候，才有的这种效果。不是编辑的时候

![image](https://user-images.githubusercontent.com/9583120/125888630-a4a8d898-ada5-4ce1-a260-0b5acdd075b1.png)

所以，需要你自己获取编辑器 html ，自己添加样式去实现。

![image](https://user-images.githubusercontent.com/9583120/125888607-206f817f-39ce-4193-b979-8250a03e22fb.png)
