### ISSUE TITLE
出大BUG了，官网demo中复制单张图片，粘贴时无效

### ISSUE THREAD

**Issue by Y2zz** [wangeditor-team/wangEditor#3470]
## bug 描述

复制单张图片，粘贴时无效

## 你预期的样子是？

正常复制粘贴图片

## 浏览器及版本号

chrome  91.0.4472.164

## wangEditor 版本

官方demo

## 官网能否复现该 bug ？

能

**Comment by rsl140** [comment]
从哪里复制的图片，我这边正常

**Comment by rsl140** [comment]
初始化的图片不能粘贴，4.6.15之前正常。

1. 复制粘贴官网的二维码图片

**Comment by soislom** [comment]
应该是没有设置上传接口吧

**Comment by Y2zz** [comment]
> 应该是没有设置上传接口吧

不不不，包含正文时粘贴是有效的，粘贴后你再复制那张图片再粘贴实际上是没效果的

**Comment by rsl140** [comment]
处理的时候 可以参考下 #3592
