### ISSUE TITLE
选中不同div的内容居中时，只有第一个div中的文字居中了

### ISSUE THREAD

**Issue by FaFaer** [wangeditor-team/wangEditor#3472]
## bug 描述

*选中不同div的内容居中时，只有第一个div中的文字居中了*

## 你预期的样子是？

*选中的所有内容居中*

## 浏览器及版本号

*chrome 91.0.4472.124*

## wangEditor 版本

  *v4*

## 官网能否复现该 bug ？

不能，但是官网的居中也有问题，同时选中”为何选择 wangEditor“和”简洁、轻量级、文档齐全“ 时  下面几行也会跟着居中

## 最小成本的复现步骤
同时选中”为何选择 wangEditor“和”简洁、轻量级、文档齐全“ ，工具栏上选择居中。

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
选中不同div的内容居中时，只有第一个div中的文字居中了，能详细描述一下如何复现？

**Comment by FaFaer** [comment]
<p class="content">$!S2H.html(${report.x11})</p>
	<div class="p4">
		<h4>系统边界</h4>
	</div>

这段代码放在编辑器里面 两行都选中，居中的时候，只有p标签里的居中了。

**Comment by FaFaer** [comment]
“<p class="content">$!S2H.html(${report.x11})</p>
	<div class="p4">
		<h4>系统边界</h4>
	</div>“

**Comment by rsl140** [comment]
是这样么？
![image](https://user-images.githubusercontent.com/7655291/126272110-99bf55bf-d8d1-471f-9e22-86296a2df405.png)

**Comment by FaFaer** [comment]
是的，官网上是这样的，但是在我自己本地 同样的操作可能会只有”为何选择wangEditor“ 这一行居中。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月20日(星期二) 下午2:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 选中不同div的内容居中时，只有第一个div中的文字居中了 (#3472)





 
是这样么？

**Comment by wangfupeng1988** [comment]
解决时和 https://github.com/wangeditor-team/wangEditor/issues/3474 一起看

**Comment by wangfupeng1988** [comment]
经调研，当前 v4 版本这个问题不好解决，因为 v4 使用的是 `document.execCommand` 我们不好控制。
v5 已经研发完成，正在内测中，已经没有了这个 bug
![image](https://user-images.githubusercontent.com/9583120/129501264-d8dba4b6-3447-4b52-b568-ae113e54ba74.png)
