### ISSUE TITLE
支持暗色版

### ISSUE THREAD

**Issue by janryWang** [wangeditor-team/wangEditor#3473]
## 功能描述

*请输入内容……*

考虑支持暗色版吧

## 提炼几个功能点

基于css变量的暗色版

## 原型图

暂无

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

暂无

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。V5 支持修改主题。
