### ISSUE TITLE
【bug】序列进行对齐方式异常

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#3474]
## bug 描述

给任意序列添加对齐方式，整个序列都会被添加对齐方式

## 你预期的样子是？

只有被选中的单列被添加对齐方式

## 浏览器及版本号

所有

## wangEditor 版本

v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 打开官网
- 步骤二 选中 **简洁、轻量级、文档齐全** 
- 步骤三 添加对齐方式 居中或者右对齐

**Comment by wangfupeng1988** [comment]
解决时和 https://github.com/wangeditor-team/wangEditor/issues/3472 一起看

**Comment by wangfupeng1988** [comment]
参考 https://github.com/wangeditor-team/wangEditor/issues/3472 的回复，关闭 issue
