### ISSUE TITLE
图片下添加描述

### ISSUE THREAD

**Issue by yanzhou-share** [wangeditor-team/wangEditor#3475]
## 功能描述

*添加图片描述*

## 提炼几个功能点

- 添加描述
- 删除

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*ckeditor*

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本，V5 支持图片描述。
