### ISSUE TITLE
使用修改文字颜色的功能时，用wangeditor修改文字颜色生成的富文本在微信小程序里rich-text组件中颜色不生效

### ISSUE THREAD

**Issue by beilika** [wangeditor-team/wangEditor#3477]
## 问题描述

*使用修改文字颜色的功能时，用wangeditor修改文字颜色生成的富文本在微信小程序里rich-text组件中颜色不生效*

## wangEditor 版本

*最新版*

## 是否查阅了文档 ？

*是，经查看是因为wangeditor修改文字颜色用的是font标签，微信小程序rich-text组件不解析font标签的color属性，有什么办法可以解决这个吗*

**Comment by rsl140** [comment]
受限于execCommand方法，目前V4版本暂时没有办法。

**Comment by wusp1994** [comment]
使用editor.config.styleWithCSS = true设置
https://github.com/wangeditor-team/wangEditor/issues/2568
