### ISSUE TITLE
错误：初始化编辑器时候未传入任何参数，请查阅文档

### ISSUE THREAD

**Issue by 923204485** [wangeditor-team/wangEditor#3480]
## 问题描述
初始化时报错提示"错误：初始化编辑器时候未传入任何参数，请查阅文档"

## wangEditor 版本
4.7.5

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/52374664/126461908-7a81a1d0-218e-4c81-98e0-8c6baeaa1239.png)

## 报错提示
![image](https://user-images.githubusercontent.com/52374664/126461985-c3c615d5-c72f-4088-b0c7-686d5ed9d3b4.png)

**Comment by leohai** [comment]
请给出完整代码，包含引入部分，最好给个demo方便排查

**Comment by leohai** [comment]
请给出完整代码，包含引入部分，最好给个demo方便排查

**Comment by rsl140** [comment]
请确保你的'add_wangeditor' 此节点存在

**Comment by HJianfeng** [comment]
![Uploading image.png…]()
出现同样问题

**Comment by HJianfeng** [comment]
![image](https://user-images.githubusercontent.com/17350820/126743910-4548a36c-10a2-4e88-8fb5-14bc98adb33d.png)
出现同样问题

**Comment by leohai** [comment]
初始化编辑器放在mounted生命中期中

**Comment by HJianfeng** [comment]
已解决
