### ISSUE TITLE
编辑区域的事件钩子不能执行

### ISSUE THREAD

**Issue by AC-greener** [wangeditor-team/wangEditor#3481]
## bug 描述

编辑区域的事件钩子（editor.txt.eventHooks）不能执行

## 你预期的样子是？

编辑区域的事件钩子能正确执行

## 浏览器及版本号

chrome  91.0.4472.114

## wangEditor 版本

4.7.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一，打开链接 [https://codepen.io/ac-greener/pen/bGWrJbr?editors=111](https://codepen.io/ac-greener/pen/bGWrJbr?editors=1111)
- 步骤二，点击插入视频按钮
- 步骤三，期待打印出123

**Comment by leohai** [comment]
看了下例子，videoClickEvents  的意思时点击video 标签的元素会触发。

- 想再插入的时候触发钩子函数，可以通过onChange 的html 来判断
- 想在插入之前进行某些操作，暂时没提供接口

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
