### ISSUE TITLE
插入contenteditable="false"的dom异常

### ISSUE THREAD

**Issue by qza6268963** [wangeditor-team/wangEditor#3487]
## bug 描述

往编辑器里插入一个不可编辑的dom `<span contenteditable="false">这个dome是无法编辑</span>`
会自动换行而且文字重复了
![01](https://user-images.githubusercontent.com/40649127/126617195-61d87b40-66ba-49f7-a235-61f860de2058.jpg)
![02](https://user-images.githubusercontent.com/40649127/126617235-ac5a73f9-ad33-40bd-98d3-930051028e0a.jpg)
![03](https://user-images.githubusercontent.com/40649127/126617248-7ed36ff0-fcb5-4a75-a064-3dda99ee402f.jpg)

## 你预期的样子是？
只插入我手动插
入的dom，而不插入多余内容

## 浏览器及版本号

浏览器：Chrome 
版本： 91.0.4472.164

## wangEditor 版本

4.7.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
  创建一个dom并且写好插入逻辑
  `<p id="insert">插入一个禁止的dom</p>     
const insert = document.getElementById('insert')
      insert.addEventListener("click", function(){
          editor.cmd.do('insertHTML', '<span contenteditable="false">这个dome是无法编辑的</span>')
      }); `
- 步骤二
 往一句话中间插入（这一句话是在一行之中的）

**Comment by leohai** [comment]
改成 `<span contenteditable="false">这个dome是无法编辑</span>&nbsp;`  加入个空格符

**Comment by qza6268963** [comment]
这样做确实是没有出现重复的内容了，可是因为插入的是`span`标签，我的目的是想让他们在同一行的，但是他却换行了，这与预期不符，有什么办法能解决吗？ @rsl140

**Comment by rsl140** [comment]
暂时没有办法，本身是不推荐这样做的。
