### ISSUE TITLE
同一行插入多个链接后，tooltips没有指向被链接后的文本

### ISSUE THREAD

**Issue by winsydeny** [wangeditor-team/wangEditor#3489]
## 问题描述

同一行插入多个链接后，tooltips没有指向被链接后的文本

## wangEditor 版本

v4.7.5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

在同一行插入多个链接后点击链接出现tooltips即可复现

**Comment by liuqh0609** [comment]
该问题确实存在，但是目前来说并不会影响使用，我们决定在v5版本去修复这个问题，可以期待一下v5版本。如果没有什么问题的话这个issue就暂时关闭了~
