### ISSUE TITLE
V4版本，苹果系统复制内容导致内容丢失

### ISSUE THREAD

**Issue by huanglei-0** [wangeditor-team/wangEditor#3490]
## bug 描述

*V4版本，苹果系统复制内容导致内容丢失*

## 你预期的样子是？

*V3版本，没有这个问题*

**Comment by rsl140** [comment]
复现步骤，复现环境呢？

**Comment by huanglei-0** [comment]
用vue2X使用的V4版本，就正常的复制一些新闻或者文章导致内容缺失，谷歌浏览器，win10 系统没有这个问题，苹果系统会出现这个问题，现在已经改为V3版本了，暂时没有其他问题，希望V4能改进这个问题。

> 复现步骤，复现环境呢？

**Comment by lvlingjie** [comment]
同样的问题，我还以是我mac出bug了

**Comment by rsl140** [comment]
未复现该问题，可以具体说说复现步骤么，比如哪个网页的文章，以及用的什么浏览器等。越详细越好。
需提供必要的复现环境，便于我们复现问题才能查找问题所在。

**Comment by FrankLord** [comment]
macOS Catalina 10.15.7 (19H512)； chrome内核版本 91.0.864.37 (官方内部版本) (x86_64)；safari版本14.0.3 (15610.4.3.1.6, 15610)；从[http://www.xinhuanet.com/2021-07/28/c_1127705466.htm](url) 此网站一次性复制两段以上文字后，粘贴到编辑器只显示部分内容

**Comment by rsl140** [comment]
> macOS Catalina 10.15.7 (19H512)； chrome内核版本 91.0.864.37 (官方内部版本) (x86_64)；safari版本14.0.3 (15610.4.3.1.6, 15610)；从[http://www.xinhuanet.com/2021-07/28/c_1127705466.htm](url) 此网站一次性复制两段以上文字后，粘贴到编辑器只显示部分内容

未复现该问题，我记得之前有过类似的问题 已经修复了。尝试更新到最新版编辑器试试

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
