### ISSUE TITLE
动态增减多个editor时出现文本显示问题

### ISSUE THREAD

**Issue by zhou-tao** [wangeditor-team/wangEditor#3493]
## bug 描述

*动态生成多个富文本编辑器时对其中某个进行增减操作时，编辑器内的文本显示未更新。*

![image](https://user-images.githubusercontent.com/36221207/127271574-60cf81d5-aa1d-4ccb-81a8-1666b90e442b.png)
![image](https://user-images.githubusercontent.com/36221207/127271634-20002236-dc76-4f7a-8fd8-3fad410de4eb.png)
![image](https://user-images.githubusercontent.com/36221207/127271997-4bdcd16c-e1ca-4cbd-8caf-f68d85966d0b.png)
![image](https://user-images.githubusercontent.com/36221207/127271954-fe968e24-7069-40e9-8135-4bd6563c892b.png)

## 你预期的样子是？

*编辑器内文本正常显示*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
可否提供复现环境。越简单越好。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
