### ISSUE TITLE
回车换行失败

### ISSUE THREAD

**Issue by uncleMrWang** [wangeditor-team/wangEditor#3495]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
请按issue模板并提交详细内容，否则不予受理。
