### ISSUE TITLE
清除全部数据后点击引用工具生成的blockquote层级不正确

### ISSUE THREAD

**Issue by yangdan8** [wangeditor-team/wangEditor#3496]
## bug 描述

清除全部数据后点击引用工具生成的blockquote层级不正确

## 你预期的样子是？

blockquote标签应该是contenteditable的div的子元素

## 浏览器及版本号

chrome92

## wangEditor 版本

4.7.5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
- 步骤一
- 打开官网demo页面https://www.wangeditor.com/
- 步骤二
- 清除全部内容
- 步骤四
- 点击引用工具
- 步骤五
- 检测源码发现contenteditable的div会去到blockquote
- 页面上仍然在显示placeholder
-
![editor-error](https://user-images.githubusercontent.com/16515026/127589890-50760222-e7a9-4e84-827d-31c818ef389f.png)
![image](https://user-images.githubusercontent.com/16515026/127589933-aec04269-a2ca-4104-b377-ffef9b8cc605.png)

**Comment by rsl140** [comment]
#3376 应该是和该问题一样 最新版本已修复 可尝试更新到最新版

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
