### ISSUE TITLE
移动光标方法moveCursor() 在 restoreSelection() 方法之前未调用 saveRange()

### ISSUE THREAD

**Issue by simo-an** [wangeditor-team/wangEditor#3498]
## 问题描述

移动光标方法为什么在 restoreSelection() 方法之前未 saveRange()，导致该方法不起作用

## wangEditor 版本

v4.7.6

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

我这边复用了您的核心代码去做一个用于发送消息的编辑器，在使用 moveCursor() 方法的时候，发现restoreSelection未进行保存Range。

```typescript
    public moveCursor(node: Node, position?: number): void {
        const range = this.getRange()
        //对文本节点特殊处理
        let len: number =
            node.nodeType === 3 ? (node.nodeValue?.length as number) : node.childNodes.length
        if ((UA.isFirefox || UA.isIE()) && len !== 0) {
            // firefox下在节点为文本节点和节点最后一个元素为文本节点的情况下
            if (node.nodeType === 3 || node.childNodes[len - 1].nodeName === 'BR') {
                len = len - 1
            }
        }
        let pos: number = position ?? len
        if (!range) {
            return
        }
        if (node) { // <--------- HERE
            range.setStart(node, pos)
            range.setEnd(node, pos) 
            this.restoreSelection()
        }
    }
```

是否应该为
```typescript
    if (node) {
      range.setStart(node, pos);
      range.setEnd(node, pos);
      this.saveRange(range); // 保存Range 
      this.restoreSelection();
    }
```

**Comment by simo-an** [comment]
ADDITION: 
还有一个问题，这边在当前页面（非文本编辑器）拖拽图片进入文本编辑器时候，会有比较高的概率出现 `_currentRange` 变成了被拖拽图片的Range，但是整个过程中并没有 调用 `saveRange()` 等会直接改变 `_currentRange` 的方法。

同时，我将`getRange`返回的结果使用 `cloneRange` 返回，依旧会有这个问题
```
  public getRange(): Range | null | undefined {
    return this._currentRange.cloneRange()
  }

```
**不知您在开发当前编辑器的过程中有没有出现这个问题？**

我这边暂时的处理方式是，在执行`insertHTML`方法前会监测当前Range并重置
```typescript
  public isCurrentRangeInEditor(): boolean {
    if (!this._currentRange) return false;
    const selection = window.getSelection() as Selection
    if (selection.rangeCount === 0) {
      return false;
    }
    const range = selection.getRangeAt(0)

    // 获取选区范围的 DOM 元素
    const $containerElem = this.getSelectionContainerElem(range)

    return this.editor.$textElem.isContain($containerElem);
  }
```

```typescript
    if (!editor.selection.isCurrentRangeInEditor()) {
      this.editor.initSelection();
    }

```

这样会导致每次拖拽的图片只能添加到最后了。。。。

**Comment by wangfupeng1988** [comment]
> ADDITION:
> 还有一个问题，这边在当前页面（非文本编辑器）拖拽图片进入文本编辑器时候，会有比较高的概率出现 `_currentRange` 变成了被拖拽图片的Range，但是整个过程中并没有 调用 `saveRange()` 等会直接改变 `_currentRange` 的方法。
> 
> 同时，我将`getRange`返回的结果使用 `cloneRange` 返回，依旧会有这个问题
> 
> ```
>   public getRange(): Range | null | undefined {
>     return this._currentRange.cloneRange()
>   }
> ```
> 
> **不知您在开发当前编辑器的过程中有没有出现这个问题？**
> 
> 我这边暂时的处理方式是，在执行`insertHTML`方法前会监测当前Range并重置
> 
> ```ts
>   public isCurrentRangeInEditor(): boolean {
>     if (!this._currentRange) return false;
>     const selection = window.getSelection() as Selection
>     if (selection.rangeCount === 0) {
>       return false;
>     }
>     const range = selection.getRangeAt(0)
> 
>     // 获取选区范围的 DOM 元素
>     const $containerElem = this.getSelectionContainerElem(range)
> 
>     return this.editor.$textElem.isContain($containerElem);
>   }
> ```
> 
> ```ts
>     if (!editor.selection.isCurrentRangeInEditor()) {
>       this.editor.initSelection();
>     }
> ```
> 
> 这样会导致每次拖拽的图片只能添加到最后了。。。。

@simo-an 这个问题，建议重新提交一个 issue ，否则不好管理。麻烦了哈～
