### ISSUE TITLE
选中内容后修改字号或对齐方式等时，选中状态消失

### ISSUE THREAD

**Issue by zhouxiangd** [wangeditor-team/wangEditor#3501]
## bug 描述

*选中内容后修改字号或对齐方式等时，选中状态消失*

## 你预期的样子是？

*选中内容后修改字号或对齐方式等时，选中状态不消失*

## 浏览器及版本号

*火狐浏览器V89.0.2（64位）*

## wangEditor 版本

* v4.7.6*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 编写几个文字
- 选择上方改变字体大小按钮
- 这时选中状态消失

**Comment by rsl140** [comment]
这个是因为编辑区失焦导致的，选中区域还是在的，不影响的。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭

**Comment by qinghuihu** [comment]
肯定要保持选中状态吧

**Comment by wind4gis** [comment]
@rsl140 可以处理这个问题吗，确实挺影响使用体验的
