### ISSUE TITLE
zindex属性过高，然后把我现在所用的框架的组件都盖住了

### ISSUE THREAD

**Issue by wh123660** [wangeditor-team/wangEditor#3504]
## bug 描述

*zindex属性过高，然后把我现在所用的框架的组件都盖住了*

## 你预期的样子是？

*zindex属性，可以设置低点，或者看下能不能有办法把zindex去掉*

## 浏览器及版本号

*联想浏览器7.0.0.*
Google Chrome 已是最新版本
版本 92.0.4515.131（正式版本） （64 位）

## wangEditor 版本
package.json:
"wangeditor": "^4.7.6"

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

使用的是vue-element-admin的框架，然后只需要里面加个页面，然后在页面里面声明一个editor，然后就可以出来bug了，下面是图片
![image](https://user-images.githubusercontent.com/20349017/128136819-130f82ce-09d6-4f8e-9780-ea2aa2f4dd4c.png)

**Comment by Gulang10783** [comment]
把class调到z-index:100 !important就阔以拉
