### ISSUE TITLE
建议增加多级序号功能

### ISSUE THREAD

**Issue by mis98zb** [wangeditor-team/wangEditor#3510]
## 建议增加多级序号功能

*支持多级序号*
例如：
1. 啊啊啊啊
   1.1. 哦哦哦哦
    1.2. 哈哈哈哈
2. 嘻嘻嘻嘻

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
