### ISSUE TITLE
空文本时使用工具栏中设置标题，报错导致编辑器无法继续使用

### ISSUE THREAD

**Issue by ganxiaozhe** [wangeditor-team/wangEditor#3512]
## bug 描述

删除所有内容后，输入框显示【请输入正文】，若在此时使用工具栏中的【设置标题】，则会报错，并且编辑器无法继续使用：
```
wangEditor.min.js:16 Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at s.createRangeByElems (wangEditor.min.js:16)
    at f.setMultilineHead (wangEditor.min.js:16)
    at f.command (wangEditor.min.js:16)
    at clickHandler (wangEditor.min.js:16)
    at HTMLLIElement.<anonymous> (wangEditor.min.js:16)
s.createRangeByElems @ wangEditor.min.js:16
f.setMultilineHead @ wangEditor.min.js:16
f.command @ wangEditor.min.js:16
clickHandler @ wangEditor.min.js:16
(anonymous) @ wangEditor.min.js:16
```
![image](https://user-images.githubusercontent.com/37825446/128387412-9bb9f8ab-dcda-43f3-aed2-34a0581027dc.png)

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

## wangEditor 版本

4.0最新版

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 删除所有内容，直至出现【请输入正文】
- 点击工具栏【设置标题】，如点击H1
- 报错啦

**Comment by rsl140** [comment]
该问题已收录，请移步到#3406 进行跟踪
