### ISSUE TITLE
视频校验区分大小写

### ISSUE THREAD

**Issue by pinguo-liuqiang** [wangeditor-team/wangEditor#3514]
## bug 描述
当 editor.config.uploadVideoAccept = ['mp4'] 时
上传文件格式为大写的 .MP4 校验不通过!
建议先进行大小写转换再去比较,
类似问题['mp4', 'Mp4', 'mP4']
一个一个写太复杂了.

## wangEditor 版本
4.7.5

**Comment by rsl140** [comment]
这个本身就是视频类型限制接口，本身是要满足不同的需求 如果强制转为小写判定的话，不利于需要该功能的用户。

**Comment by pinguo-liuqiang** [comment]
收到，谢谢答复

**Comment by pinguo-liuqiang** [comment]
一个想法：是否可以加一个配置项，去判断类型是否严格匹配呢？这样的话既可以区分大小写，也可以不区分。
