### ISSUE TITLE
复制粘贴一张图片，在编辑器里会出现2张相同的图，确定不是ctrl+v 了2次

### ISSUE THREAD

**Issue by zhngxz1219** [wangeditor-team/wangEditor#3515]
## bug 描述

  从微信中(或网页上图片)复制一张图片后，在编辑器里粘贴 会出现2张相同的图片，确定不是因为误操作 粘贴2次导致。
  

## 你预期的样子是？

粘贴时只有一张图片 

## 浏览器及版本号
 
  谷歌 版本 91.0.4472.77（正式版本） （64 位）

## wangEditor 版本

 4.6.8

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
在微信输入框中 粘贴 一张图片，可不发送
- 步骤二
-复制图片，
- 步骤三
- 在编辑器里 粘贴图片

**Comment by rsl140** [comment]
该问题已收录，可到#3407 进行跟踪
