### ISSUE TITLE
使用行高功能后，把原来存在样式里的color属性去掉了

### ISSUE THREAD

**Issue by carolineCQ** [wangeditor-team/wangEditor#3520]
## bug 描述

*原本p标签里存在color属性，但是使用行高功能之后，把color弄没了，但是其他的样式属性还存在*

## 你预期的样子是？

*使用行高功能，原来存在的样式属性保持不变，仅多添加一个line-height属性*

## 浏览器及版本号

*Google Chrome 版本 91.0.4472.77（正式版本） （64 位）*

## wangEditor 版本

*v4*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

1.步骤一
首先在富文本的编辑区输入文本时，给生成的p标签设置好默认的color属性和其他属性
<img width="793" alt="1628472121(1)" src="https://user-images.githubusercontent.com/88637058/128652094-2a9ad3ec-bfde-4451-b443-bac0f094350c.png">

2.步骤二
步骤一图片看的时候是没有问题，color是存在的，一旦使用了行高功能，设置为2，会发现color属性没了，第一个p标签的padding属性也没了。
<img width="232" alt="1628472335(1)" src="https://user-images.githubusercontent.com/88637058/128652233-4cd8b390-e5b0-445f-9aef-af9bb23c4dd6.png">
<img width="682" alt="1628472398(1)" src="https://user-images.githubusercontent.com/88637058/128652275-d21f0778-6e22-48fd-a619-713ae0552a29.png">

**Comment by carolineCQ** [comment]
<img width="495" alt="c3e58e7eed03ad48f36f29101507c9d" src="https://user-images.githubusercontent.com/88637058/128664938-74f2e976-690d-45ec-b4f4-66bbabc59d7d.png">
设置多行行高，有时候还会报这个错误

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本，V5 没有这个 bug 。
