### ISSUE TITLE
插入表格，鼠标焦点样式显示有误

### ISSUE THREAD

**Issue by G-WangZH** [wangeditor-team/wangEditor#3521]
## bug 描述

*在富文本中插入表格，表格中的焦点显示有问题*

## 你预期的样子是？

*在富文本插入表格的时候，每行高度可以至少20px，且鼠标焦点定位可以正常显示*

## 浏览器及版本号

*chome， 版本 92.0.4515.131*

## wangEditor 版本

*^4.6.9*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
在富文本插入table表格
- 步骤二
鼠标显示错位
![image](https://user-images.githubusercontent.com/24827526/128669652-dd5e5a18-3528-4fec-8ad8-19b050ee94dd.png)

**Comment by wangfupeng1988** [comment]
这是单元格高度问题，已经受理了。
