### ISSUE TITLE
清空编辑器中的所有内容之后, 通过拼音输入中文, 第一个拼音会被瞬间删除

### ISSUE THREAD

**Issue by free-pan** [wangeditor-team/wangEditor#3523]
## bug 描述

*清空编辑器中的所有内容之后, 通过拼音输入中文, 第一个拼音会被瞬间删除*

## 你预期的样子是？

*能够正常输入, 而不是被清除*

## 浏览器及版本号

*chrome: 92.0.4515.131*

## wangEditor 版本

*4.7.6*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一: 进入官网: https://www.wangeditor.com/
- 步骤二: 删除编辑器中的所有内容
- 步骤三: 切换为拼音来输入中文, 按下f, 则f会被迅速删除
- 步骤四: 如果上面步骤未重现该问题, 请重复第二步, 第三步

**Comment by wangfupeng1988** [comment]
和这个 https://github.com/wangeditor-team/wangEditor/issues/3525 一起看

**Comment by Brolly0204** [comment]
解决了？一开始首字母输入不上去  删除后也是会出现首字母丢失问题
