### ISSUE TITLE
word文档中复制图片加文字粘贴到编辑器，图片会显示不出来

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3524]
## bug 描述

word文档中复制图片加文字粘贴到编辑器，图片会显示不出来

## 你预期的样子是？

正常显示

## 浏览器及版本号

Google最新

## wangEditor 版本

4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/43296632/128706405-6dc45692-a4f9-45d0-918a-7e3cb1989fb5.png)
![image](https://user-images.githubusercontent.com/43296632/128706456-6975ca8e-9e60-477c-97c4-8650f36740b1.png)

（请告诉我们，如何最快的复现该 bug）

**Comment by wangfupeng1988** [comment]
暂不支持复制 word 图片的功能。
