### ISSUE TITLE
清空编辑器内容，先按数下删除键，然后在中文输入的情况下，会出现首字母丢失的情况

### ISSUE THREAD

**Issue by Qsnh** [wangeditor-team/wangEditor#3525]
## bug 描述

编辑器内容为空的情况下，先按数下删除键，然后在中文输入的情况下，会出现首字母丢失的情况，比如说我，我输入山的拼音shan，但是s丢失了，只有han

## 浏览器及版本号

谷歌浏览器，版本 92.0.4515.131（正式版本） (x86_64)

## wangEditor 版本

最新版本，官网的演示站编辑器存在这个问题

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

中文输入状态下，先清空编辑器内容，然后按数下删除键，然后输入就出现bug了

**Comment by 1269140053** [comment]
你可以这样设置来规避这个bug
![1628573546(1)](https://user-images.githubusercontent.com/60088915/128813386-9701dce3-e936-4e85-8c8b-739e2265097f.png)

**Comment by Qsnh** [comment]
> 你可以这样设置来规避这个bug
> ![1628573546(1)](https://user-images.githubusercontent.com/60088915/128813386-9701dce3-e936-4e85-8c8b-739e2265097f.png)

我试试

**Comment by 1269140053** [comment]
行了吗？

**Comment by Qsnh** [comment]
> 行了吗？

不行，这样会导致编辑器失去焦点

**Comment by Qsnh** [comment]
看了下文档，没找到主动设置焦点的方法

**Comment by wangfupeng1988** [comment]
一起看这个 https://github.com/wangeditor-team/wangEditor/issues/3523 ，类似的 bug

**Comment by Brolly0204** [comment]
解决了嘛  怎么解决呀

**Comment by forrany** [comment]
> 一起看这个 #3523 ，类似的 bug

是的，一模一样，这个问题非常影响使用，请问可以修复吗

**Comment by czlin** [comment]
可以暂时先把版本降到4.5.4,等官方修复了再升回来

**Comment by 1135004584** [comment]
我服了，作者是不是故意启动的时候输出一段代码把这个bug给遮盖过去了，这个bug太致命了，没有修复相当于这个编辑器没有意义
