### ISSUE TITLE
可以设置初始化字体、字号、颜色等功能

### ISSUE THREAD

**Issue by CONAN0** [wangeditor-team/wangEditor#3527]
## 功能描述

富文本在初始化的时候可以设置初始的字体、字号、颜色等

## 提炼几个功能点

在项目开发中，需要给富文本一个初始化

## 原型图

在项目开发中，需要给富文本一个初始化字号、字体等，但是目前没有这个功能，就导致没法设置

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
暂不支持该功能
