### ISSUE TITLE
粘贴进来的文章，再次添加超链接，会导致a标签添加失败&&莫名会换行

### ISSUE THREAD

**Issue by NewMarket12138** [wangeditor-team/wangEditor#3528]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请描述复现的步骤，以及在官网 demo 是否可以复现？

**Comment by Gavin-yh** [comment]
> 请描述复现的步骤，以及在官网 demo 是否可以复现？

换行应该是截断导致的

**Comment by rsl140** [comment]
该问题长时间未回复，暂且关闭
