### ISSUE TITLE
建议新增上传音频功能

### ISSUE THREAD

**Issue by guilter** [wangeditor-team/wangEditor#3530]
## 功能描述

与上传视频功能类似，希望新增一个上传音频文件的功能。

## 提炼几个功能点

- 支持上传音频文件
- 能正常播放音频

## 原型图

无

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

ckeditor编辑器的相关插件有类似功能
https://blog.csdn.net/xzz1173724284/article/details/80906916
https://ckeditor.com/

**Comment by wangfupeng1988** [comment]
该那本不会支持了
后考虑在后续 v5 版本逐步支持。

v5 尚在内部测试中，发布时间待定。

**Comment by wasd345** [comment]
音频功能本人已添加，有需要的可以问我要代码
![image](https://github.com/wangeditor-team/wangEditor/assets/5779660/7b4c0eb5-26e6-4e8c-a5be-62c4d61816cc)
![image](https://github.com/wangeditor-team/wangEditor/assets/5779660/1f3ab44d-8e43-4abd-a645-094ab45d60aa)
