### ISSUE TITLE
编辑器中获取文件(图片或视频)时能否支持使用blob方式

### ISSUE THREAD

**Issue by guilter** [wangeditor-team/wangEditor#3531]
## 功能描述

编辑器中获取图片或视频增加支持blob方式，且支持自定义请求头，这样的好处有：
1.可以增加认证信息，如请求头中增加access_token
2.文件不易被爬

## 提炼几个功能点

- 编辑器中获取图片或视频增加支持blob方式回显
- 使用blob方式回显文件时支持增加自定义请求头

## 原型图

无

## 可参考的案例

可以参考使用blob下载文件的相关实现

**Comment by wangfupeng1988** [comment]
没理解你的意思。

**Comment by guilter** [comment]
类似这里面的实现
https://blog.csdn.net/weixin_44524243/article/details/116233462
https://www.cnblogs.com/deng-jie/p/11549821.html

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
