### ISSUE TITLE
bug : 新打开的editor直接使用大标题会崩溃

### ISSUE THREAD

**Issue by liuyike98** [wangeditor-team/wangEditor#3539]
## bug 描述

新打开的editor,在不输入任何文本的情况下点击H1大标题,直接报错,而且报错后不可继续再编辑

## 浏览器及版本号

苹果 edge 最新版本

## wangEditor 版本

最新版cdn引入

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 新建空白editor
- 步骤二 点击h1
- 步骤三 复现

**Comment by shi-lai-mu** [comment]
该问题已收录，请移步到 #3406 进行跟踪
