### ISSUE TITLE
编辑的内容包含不可编辑的区域时，enter换行和backspace删除的结果不符合预期。

### ISSUE THREAD

**Issue by potato-sauce** [wangeditor-team/wangEditor#3543]
## bug 描述
想在编辑器内插入自定义的行内卡片，操作上发现问题。

通过editor.txt.html来插入一段「不可编辑的区域」的span文本
![image](https://user-images.githubusercontent.com/32588809/129559865-589398de-33ba-45e2-9bb5-31facbb32e9c.png)

```html
<p>editable<span><span contenteditable="false">uneditable</span></span></p>
```

### enter换行
在uneditable前面按enter换行会变成:
```html
<p>editable<p>
<p>
    <br>
    <span>
      <span contenteditable="false">uneditable</span>
    <span>
</p>
```
![image](https://user-images.githubusercontent.com/32588809/129559584-ff821a7a-5c31-43be-b759-480dbfdbc1d1.png)
uneditable前面出现的br是不符合预期的。

### backspace删除
同时在uneditable按backspace能删除<br>，回退一行，继续删除的时候光标会回退到"editable"，"uneditable"在第二行不变，不会自动回退到第一行
![image](https://user-images.githubusercontent.com/32588809/129559921-45fb664e-d0b4-420d-b7db-b9be19159910.png)

## 你预期的样子是？

回车换行和删除跟正常的文本行为一致。
如果"uneditable"不是位于行首，表现是正常的。换行不会有多余的br，删除文本前面的br也能回到第一行。
但是删除“uneditable“前面的文本仍会存在没有回退到第一行的问题。

![image](https://user-images.githubusercontent.com/32588809/129560342-6b095a7e-3b80-47ad-b8bf-914a0df944d9.png)

如微信公众号采用的ueditor，语雀和腾讯文档似乎都避开了行内自定义卡片的，采用插入块的方式，不知道是不是contenteditable="true"包含contenteditable="false"的子节点会存在难以解决的其他坑？

## 浏览器及版本号

chrome92

## wangEditor 版本

4.7.6

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

https://codesandbox.io/s/dreamy-dream-m9d5y?file=/src/App.vue

```js
editor.txt.html(
      '<p>content<span style="color: blue; border: 1px solid"><span contenteditable="false">uneditable</span></span>content</p>'
    )
```

**Comment by rsl140** [comment]
该行为应该是浏览器的一个默认行为导致的，本身我们是没有对该行为做处理的

**Comment by simo-an** [comment]
希望能支持在编辑器中插入不可编辑的元素的，并调整一些浏览器异常行为😁

**Comment by rsl140** [comment]
> 希望能支持在编辑器中插入不可编辑的元素的，并调整一些浏览器异常行为😁

感谢您的反馈，目前v4受限于技术原因，浏览器的一些异常行为不太容易处理，可以期待下V5版本。
关于不可编辑元素需要一些技术调研，因为也不是很好处理
