### ISSUE TITLE
希望　editor.config.pasteTextHandle　可以异步处理图片。目前同步图片太蛋疼了！

### ISSUE THREAD

**Issue by codedart2018** [wangeditor-team/wangEditor#3544]
## 功能描述

如果处理里面的同步，不await的话。是来不及拿回服务端的内容来的。但是用了await后src 就成了object promise了。这就有点脑壳痛了。按理说都阻塞了，src应该是我服务端返回的结果集，但现实不是。我也看了下issue也有人都在反应这个问题。

目前我这样子处理感脚脑仁疼。
我把内容里的img全部提练出来处理成一个loading.正常返回去渲染，然后再把提取出来的图片push到一个数组里面去。最后循环数组一个一个的去上传，完成后再把内容拿过来进行正则查找再匹配再替换。好疯啊！希望可以在里面进行异步处理图片。

**Comment by rsl140** [comment]
抱歉，不是很明白在说什么，我记得 #3412 里面有提到过如何提交到服务器，可以参考该方案实现。
其次 请按issue模版提问，否则是不予受理的。

**Comment by codedart2018** [comment]
> 抱歉，不是很明白在说什么，我记得 #3412 里面有提到过如何提交到服务器，可以参考该方案实现。
> 其次 请按issue模版提问，否则是不予受理的。

什么叫异步你那叫定时。

**Comment by z1948296027** [comment]
哈哈，又遇到同样的问题了

**Comment by codedart2018** [comment]
> 哈哈，又遇到同样的问题了

我很粗爆的处理的。先把所有图片替换成一张加载图片。然后把要换的图片推到一个数组当中去。然后调一个任务去处理，处理完成后，再把加载图片替换成后台处理好的图片地址。

**Comment by z1948296027** [comment]
> > 哈哈，又遇到同样的问题了
> 
> 我很粗爆的处理的。先把所有图片替换成一张加载图片。然后把要换的图片推到一个数组当中去。然后调一个任务去处理，处理完成后，再把加载图片替换成后台处理好的图片地址。

我这边倒不用自己处理图片，只是先把外链的图片捞出来，然后传给后端，后端把图片转成内部可访问的，再一一匹配回去，可是中间还是有个异步

**Comment by beforeBurning** [comment]
> > 哈哈，又遇到同样的问题了
> 
> 我很粗爆的处理的。先把所有图片替换成一张加载图片。然后把要换的图片推到一个数组当中去。然后调一个任务去处理，处理完成后，再把加载图片替换成后台处理好的图片地址。

请问一下  最后是用什么方法替换的? 我没有在官方找到相关的方法
