### ISSUE TITLE
点击图片出现图片工具栏，此时无法滚动富文本框

### ISSUE THREAD

**Issue by yangdan8** [wangeditor-team/wangEditor#3546]
## bug 描述

点击图片出现图片工具栏，此时无法滚动富文本框

## 你预期的样子是？

正常滚动

## 浏览器及版本号

Chrome92

## wangEditor 版本

4.7.6

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 打开官网https://www.wangeditor.com/
- 拖动滚动条到底部
- 点击支付宝图片
- 点击菜单上的100%
- 再次点击支付宝图片
- 滚动富文本框，发现无法滚动

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
