### ISSUE TITLE
请支持 IE 下的粘贴事件监听

### ISSUE THREAD

**Issue by rieval** [wangeditor-team/wangEditor#3547]
## 功能描述

![image](https://user-images.githubusercontent.com/22883406/129657738-f0a2ab72-4918-4ac8-b704-ae3d9b351557.png)

目前的粘贴事件说是不支持 IE，我自身做的项目是要求功能在 IE 下能完全实现。

希望这个功能能支持 IE，如果实现不了，也请说明为什么实现不了

自己造轮子的话，是不是只要模仿这个就可以了？

https://developer.mozilla.org/zh-CN/docs/Web/API/Element/paste_event

## 提炼几个功能点

- IE 下可以监听编辑器的内容粘贴事件

## 原型图

/

## 可参考的案例

/

**Comment by wangfupeng1988** [comment]
第一，从大的方向来说，不会再对 IE 做太多支持了，V5 版本（已经在内测）已放弃 IE 。V4 处于维护状态，也不会再增加对 IE 的额外支持。
第二，至于具体的原因，我一时记不起了，当时做过详细的调研，IE 对于粘贴的支持不足以满足 wangEditor 的粘贴需求。否则，不会平白无故的单独剔除 IE 浏览器。
