### ISSUE TITLE
滚动部分内容后在首行换行滚动条异常

### ISSUE THREAD

**Issue by yangdan8** [wangeditor-team/wangEditor#3548]
## bug 描述

滚动部分内容后，当前的首行按回车键，不会把当前内容往后面换行

## 你预期的样子是？

向后换行

## 浏览器及版本号

Chrome92

## wangEditor 版本

4.7.6

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 打开官网https://www.wangeditor.com/
- 滚动内容到“初见”，使“初见”成为首个可见行
- 定位光标到“初”字之前
- 输入多个回车
- 发现好像回车换行丢失，实际内容在之前，向上滚动滚动条可见

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
