### ISSUE TITLE
动态配置菜单问题

### ISSUE THREAD

**Issue by JoeYnnn** [wangeditor-team/wangEditor#3549]
## 问题描述

现在有需求是通过外部select组件去选择菜单内容，然后配置到编辑器内，现在的做法就是通过props改变之后销毁再创建编辑器达到效果。有其他更好的方式吗？

## wangEditor 版本

^4.7.5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
试试 editor.txt.html()
[参考](https://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/01-%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AE%B9.html)

**Comment by JoeYnnn** [comment]
> 头脑编辑器.txt.html()
> [参考](https://www.wangeditor.com/doc/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/01-%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AE%B9.html)

不是内容的动态改变，是menu的动态配置，通过props传进来的一个menus数组，编辑器只能先销毁再new一个增加config，最后create才能实现这块。想通过直接动态改变menu，不需要重新create编辑器达到相应的效果

**Comment by rsl140** [comment]
目前暂时没有该功能。

**Comment by wangfupeng1988** [comment]
暂不支持该功能。
