### ISSUE TITLE
VUE项目中，菜单栏失效

### ISSUE THREAD

**Issue by LongYinSang** [wangeditor-team/wangEditor#3550]
## 问题描述

VUE项目中，插入wangEditro，加粗、斜体、更改字号等文字相关的菜单项会失效，上传图片、撤销、恢复、对齐等功能完好。

## wangEditor 版本

wangEditor 4.7.6

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

不清楚如何复现，但是在我npm安装wangEditor之后，会报出@vant/touch-emulator和XSS的缺失错误，重新安装后这两个依赖后不再报错

**Comment by rsl140** [comment]
抱歉，为复现该问题

**Comment by hotfave** [comment]
尝试重复使用加粗或者斜体功能，如：正常输入123，斜体输入456，取消斜体正常输入789，再点击斜体输入000，是否最后次点击斜体输入000时斜体功能失效，能复现的话 这个问题是共性问题了。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
