### ISSUE TITLE
将已有内容全部删除，点击标题，文本编辑光标消失控制台报错，无法继续编辑。

### ISSUE THREAD

**Issue by xueyy** [wangeditor-team/wangEditor#3552]
## bug 描述
将已有内容全部删除，点击标题，文本编辑光标消失控制台报错，无法继续编辑。

## 你预期的样子是？

可以继续编辑

## 浏览器及版本号
chrome 92.0.4515.131

## wangEditor 版本

4.7.6

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
- 随便输入些内容，再删了
- 步骤二
- 编辑器选择H-标题一
-光标消失，无法操作，控制台报错

**Comment by shi-lai-mu** [comment]
该问题已收录，请移步到 #3406 进行跟踪
