### ISSUE TITLE
请问可以配置全局参数能让自定义参数里拿到定义的全局参数吗？比较实用和需要的点。

### ISSUE THREAD

**Issue by codedart2018** [wangeditor-team/wangEditor#3553]
## 问题描述

直接上图，这个图是我自定义配置菜单弹出来的
![示例](http://oss.jibei.ycoto.cn/store_content/2021/custome.png)

因为这个弹窗是我封装好的。在很多地方都有调用它，需要传不同的参数到后端去。以便于上传的时候后端更好的分类管理存入不同的分类下，以及上传限制上传大小，上传数量，限制选择数量等等等。所以迫切的需要全局配置参数能让我在自定义菜单中获取到。翻看了文档也没有找到如何定义，或者说自定义菜单可以额外的传参数进去。以便于自定义菜单中拿到参数更好的传入到别的地方去。以上就是我的疑问，谢谢大家，如果有解决的希望参议。
## wangEditor 版本

version: 4.7.6

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

**Comment by codedart2018** [comment]
> ## 问题描述
> 直接上图，这个图是我自定义配置菜单弹出来的
> ![示例](https://camo.githubusercontent.com/6cc932c0d90e33b8e8389129d784c448a5d11e7ebcde923d4bdb18e96ac0e87e/687474703a2f2f6f73732e6a696265692e79636f746f2e636e2f73746f72655f636f6e74656e742f323032312f637573746f6d652e706e67)
> 
> 因为这个弹窗是我封装好的。在很多地方都有调用它，需要传不同的参数到后端去。以便于上传的时候后端更好的分类管理存入不同的分类下，以及上传限制上传大小，上传数量，限制选择数量等等等。所以迫切的需要全局配置参数能让我在自定义菜单中获取到。翻看了文档也没有找到如何定义，或者说自定义菜单可以额外的传参数进去。以便于自定义菜单中拿到参数更好的传入到别的地方去。以上就是我的疑问，谢谢大家，如果有解决的希望参议。
> 
> ## wangEditor 版本
> version: 4.7.6
> 
> ## 是否查阅了文档 ？
> （文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）
> 
> _是_

```
import E from 'wangeditor';
import { ConfigType } from 'wangeditor/dist/config';
import { QueryParamsType } from '@/components/AlbumModal/data';

export declare type NewConfigType = {
  albumQueryParams?: QueryParamsType;
} & ConfigType;

// 新类继承 自行补充一些方法和参数
export declare class NE extends E {
  config: NewConfigType;
}

```

我自己这样解决吧。但还是希望自定义菜单能带参数进去。这样就不用向上面动刀子了

**Comment by rsl140** [comment]
既然已解决了，那这边就关闭issue了
