### ISSUE TITLE
editor.config.historyMaxSize设置为0时快捷键依然生效

### ISSUE THREAD

**Issue by yangdan8** [wangeditor-team/wangEditor#3559]
重现步骤
- 设置editor.config.historyMaxSize=0
- 在输入框输入任意内容
- Ctrl+Z能删除输入的内容

**Comment by clinfc** [comment]
![image](https://user-images.githubusercontent.com/39868400/132665303-a13c4874-c0c7-473c-bdf3-e7ee4c6c4dc5.png)
