### ISSUE TITLE
table里面选择一行进行居中，导致其他行都进行了居中

### ISSUE THREAD

**Issue by phoebemoon16** [wangeditor-team/wangEditor#3560]
## bug 描述

table里面选择一行对齐方式选择居中，导致其他行都居中

## 你预期的样子是？

只是选中的行进行居中

## 浏览器及版本号

谷歌游览器 版本 87.0.4280.88（正式版本） （64 位）

## wangEditor 版本

*请输入内容……*
^4.6.7

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 粘贴一个表格，或者插入一个表格。在每一行添加一些数据。
- 步骤二
- 选中一行数据选择对齐方式，导致所有的行的对齐方式都进行了改变。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
