### ISSUE TITLE
拷贝链接后有图片时，图片未粘贴出来

### ISSUE THREAD

**Issue by simo-an** [wangeditor-team/wangEditor#3563]
## bug 描述

拷贝链接后有图片时，图片未粘贴出来

## 你预期的样子是？

拷贝链接后有图片时，图片粘贴到文本编辑器中

## 浏览器及版本号

Chrome 92

## wangEditor 版本

官网版版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
拷贝一个链接且链接后面有一张图片
![image](https://user-images.githubusercontent.com/38021707/129872776-74a2f192-db18-4032-adef-6b4dcbc4d4f7.png)

- 步骤二
在WangEditor上粘贴

- 步骤三
只有链接被拷贝到编辑器中了

如果只拷贝部分链接，则显示正常

![1629278509463](https://user-images.githubusercontent.com/38021707/129873739-86925468-b8f1-4e03-a0c6-44dd7a348b17.png)

## 解决建议

在 `paste-text-html.ts ` 中代码

```typescript
        // 如果用户开启闭粘贴样式注释则将复制进来为url的直接转为链接 否则不转换
        //  在群中有用户提到关闭样式粘贴复制的文字进来后链接直接转为文字了，不符合预期，这里优化下
        if (urlRegex.test(pasteText) && pasteFilterStyle) {
            //当复制的内容为链接时，也应该判断用户是否定义了处理粘贴的事件
            if (pasteTextHandle && isFunction(pasteTextHandle)) {
                // 用户自定义过滤处理粘贴内容
                pasteText = '' + (pasteTextHandle(pasteText) || '') // html
            }

            const insertUrl = urlRegex.exec(pasteText)![0]
            const otherText = pasteText.replace(urlRegex, '')

            return editor.cmd.do(
                'insertHTML',
                `<a href="${insertUrl}" target="_blank">${insertUrl}</a>${otherText}`
            ) // html
        }
```
直接忽略掉了拷贝的数据中含有非文本信息

可以在此检查一下拷贝的信息中是否有非文本信息

**Comment by rsl140** [comment]
由于我们需要处理链接，比如将粘贴进来的文本类链接转换为带有A标签性质的链接，所以这里做了特殊处理，故，链接处理是高于文本带图片的处理。为了保证链接的正确性，只会处理为文本，且优先级是大于文本+图片的方式的。
所以这是一个预期的显示结果
