### ISSUE TITLE
能新加一个word 的审阅插入批注功能吗

### ISSUE THREAD

**Issue by lszyzs** [wangeditor-team/wangEditor#3566]
## 功能描述

用来记录对选中文字添加类似笔记效果的功能

## 提炼几个功能点

- 能支持对任意文字选中 图片和表格能拿支持是最好的
- 
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例
![image](https://user-images.githubusercontent.com/58094462/129993508-13da3beb-077c-4f32-9b66-cf6bf0c152c4.png)

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
石墨文档也有类似的功能 [链接](https://shimo.im/dashboard/used)

**Comment by wangfupeng1988** [comment]
这个近期不会增加。
等到 v5 发布并稳定后，会逐步升级这些外围功能，到时会做成一个一个插件。
