### ISSUE TITLE
vue中接入v4.7.6编辑器，使用黑体、斜体等功能出现异常

### ISSUE THREAD

**Issue by hotfave** [wangeditor-team/wangEditor#3567]
## bug 描述

反复切换斜体功能导致后续点击斜体功能没反应

## 你预期的样子是？

多次切换斜体功能时，能正常输入斜体文字

## 浏览器及版本号

chrome 、版本 92.0.4515.131（正式版本） （64 位）
## wangEditor 版本

v4.7.6

## 官网能否复现该 bug ？

不能（官网是以cdn方式引入，所以没有此问题，vue中npm引入才有该问题）

## 最小成本的复现步骤
vue中使用4.7.6版本编辑器时，使用如斜体功能时进行以下操作
- 步骤一：输入123，点击斜体，输入456
- 步骤二：点击取消斜体，输入789
- 步骤三：点击斜体，输入000
步骤三中再使用斜体功能输入000时，无法再触发斜体功能

**Comment by rsl140** [comment]
未复现该问题 
![image](https://user-images.githubusercontent.com/7655291/130073769-95c5fa08-377a-41c3-920c-1173123c522e.png)

**Comment by hotfave** [comment]
> 未复现该问题
> ![形象](https://user-images.githubusercontent.com/7655291/130073769-95c5fa08-377a-41c3-920c-1173123c522e.png)

请问是在官网尝试复现的吗？还是跑的vue项目去尝试复现？

**Comment by hotfave** [comment]
> 未复现该问题
> ![image](https://user-images.githubusercontent.com/7655291/130073769-95c5fa08-377a-41c3-920c-1173123c522e.png)

官网demo的话是没法复现出来的，得在vue项目里运行

**Comment by hotfave** [comment]
![image](https://user-images.githubusercontent.com/29624295/130176509-cfff74ab-193b-418d-9812-e169422a9614.png)
写入的时候发现插入的文本嵌在了span里面，正常应该是没有的

**Comment by rsl140** [comment]
vue 项目里也未复现该问题

**Comment by hotfave** [comment]
> vue 项目里也未复现该问题

方便问下vue的版本吗 3.0？

**Comment by hotfave** [comment]
> vue 项目里也未复现该问题

**Comment by hotfave** [comment]
> ![image](https://user-images.githubusercontent.com/29624295/130176509-cfff74ab-193b-418d-9812-e169422a9614.png)
> 写入的时候发现插入的文本嵌在了span里面，正常应该是没有的


重新明确复现步骤：在vue项目中，body设置了fontsize之后， 会出现这种情况 @rsl140

**Comment by rsl140** [comment]
我看到你这里有个font-size:12px的定义，如果去掉这个的话 是正常的
![image](https://user-images.githubusercontent.com/7655291/131241039-997ab9d7-de68-450a-9465-29b97d78eddc.png)

这块的话 是浏览器的一个默认行为导致的。不太好处理..
