### ISSUE TITLE
插入表格功能异常：每行高度只有2mm，官网必现

### ISSUE THREAD

**Issue by BarneyRoos** [wangeditor-team/wangEditor#3568]
## bug 描述

*插入表格时，每一行都只有2mm高，官网Demo上也是这样。*
![image](https://user-images.githubusercontent.com/12667145/130026595-8dd2ece9-a560-478b-a858-653ab7ad58af.png)

## 你预期的样子是？

*插入的表格每行高度至少能容纳一行字，最好可以手动调整宽高*

## 浏览器及版本号

*chrome  版本 92.0.4515.131（正式版本） (x86_64)*

## wangEditor 版本

*V4 最新版*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 插入一个5行5列的表格

**Comment by BarneyRoos** [comment]
官网必现

**Comment by Sanchez3** [comment]
是的。且无法设置表格的border和collapse，导致预览富文本内容时表格没有样式

**Comment by rsl140** [comment]
该问题已收录，请移步到 #3395 进行跟踪
