### ISSUE TITLE
快捷键截图自动填充输入内容

### ISSUE THREAD

**Issue by lishaoshi** [wangeditor-team/wangEditor#3570]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by rsl140** [comment]
？？ 不明白你要表达什么问题。
