### ISSUE TITLE
上传视频后，视频找不到选区，没光标，不能换行

### ISSUE THREAD

**Issue by chen9091** [wangeditor-team/wangEditor#3571]
## bug 描述

*上传视频后，视频找不到选区，前后没光标，不能换行，选区元素貌似一直停在视频标签*

## 你预期的样子是？

*上传视频后希望可以如图片一样增加选区，视频元素前后光标复现*

## 浏览器及版本号

*谷歌91.0.4472.164*

## wangEditor 版本

*wangEditor4 最新版*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
上传视频就能看到，

**Comment by rsl140** [comment]
未复现该问题

**Comment by chen9091** [comment]
上传本地视频，看看能选到选区吗？还有文本居中对齐，text-align:center，会赋值给编辑器外层包裹的li元素，https://www.wangeditor.com/你们官网demo也是，把包裹的div 换成li 复现

**Comment by UltramanWeiLai** [comment]
> 上传本地视频，看看能选到选区吗？还有文本居中对齐，text-align:center，会赋值给编辑器外层包裹的li元素，https://www.wangeditor.com
> 你们官网demo也是，把包裹的div 换成li 复现

video 标签确实是无法获取光标的，所以我们做了处理，在插入视频后，会默认在下面添加一行空行
li 标签的那个复现了，我会另外单独添加一个 issue 单独处理

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
