### ISSUE TITLE
本地图片上传customInsert 方法的问题

### ISSUE THREAD

**Issue by Agaoquan** [wangeditor-team/wangEditor#3572]
## 问题描述

*请输入遇到的问题...*
![image](https://user-images.githubusercontent.com/19632534/130201783-6072b41b-2959-4efb-8d10-88b3b6d7aca2.png)
![image](https://user-images.githubusercontent.com/19632534/130201871-5884f090-e3ed-44ea-8c51-6f129c7b3a83.png)
想不明白为啥？insertImgFn 直接插入图片地址是可以的。变量就不行。。。。有哪位大神知道吗？
## wangEditor 版本
最新
*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
你先检查下你的图片地址是否存在 ，不是都报404了么

**Comment by Agaoquan** [comment]
> 你先检查下你的图片地址是否存在 ，不是都报404了么

地址没问题。报404是插件报的。有一种解决办法。设置个两秒的定时器可正常显示图片
![image](https://user-images.githubusercontent.com/19632534/130384781-d42343b1-ca24-430d-91c9-7b0c6d6cf65f.png)

**Comment by UltramanWeiLai** [comment]
> > 你先检查下你的图片地址是否存在 ，不是都报404了么
> 
> 地址没问题。报404是插件报的。有一种解决办法。设置个两秒的定时器可正常显示图片
> ![image](https://user-images.githubusercontent.com/19632534/130384781-d42343b1-ca24-430d-91c9-7b0c6d6cf65f.png)

那大概率是在加载图片的时候，后台服务那边还没有将图片处理好，所以添加了定时器后正常获取。
而且报错信息确确实实反应了该问题存在性，注：报错信息是浏览器给的并不是插件给出来的，通过控制台的网络里面也可以查看到图片的具体请求信息

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
