### ISSUE TITLE
回车触发antd proform自动提交

### ISSUE THREAD

**Issue by z1948296027** [wangeditor-team/wangEditor#3575]
## bug 描述

*在proform标单项中使用wangEditor，然后在回车的时候自动触发了onFinish*

## 你预期的样子是？

*不要自动提交*

## 浏览器及版本号

*google浏览器*

## wangEditor 版本

*4.7.6*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。

**Comment by z1948296027** [comment]
> 尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。

antd的proform自己添加了一个input输入框，然后hidden掉了，回车的时候不会触发。

**Comment by z1948296027** [comment]
抱歉，和wangEditor没有关系，是表单的问题

**Comment by codedart2018** [comment]
> > 尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。
> 
> antd的proform自己添加了一个input输入框，然后hidden掉了，回车的时候不会触发。

你是怎么加的呢，我阻止冒泡失败了！

**Comment by codedart2018** [comment]
> > 尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。
> 
> antd的proform自己添加了一个input输入框，然后hidden掉了，回车的时候不会触发。

我阻止冒泡，冒泡是成功了，但是编辑器却不回车了！

**Comment by z1948296027** [comment]
> > > 尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。
> > 
> > 
> > antd的proform自己添加了一个input输入框，然后hidden掉了，回车的时候不会触发。
> 
> 我阻止冒泡，冒泡是成功了，但是编辑器却不回车了！

不用试了，查了挺多资料，原生form表单里面回车就是会触发提交，和wangEditor没有关系，所以form表单提交不要使用onFinish,提交事件绑定在按钮上就好了

**Comment by codedart2018** [comment]
> > > > 尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。
> > > 
> > > 
> > > antd的proform自己添加了一个input输入框，然后hidden掉了，回车的时候不会触发。
> > 
> > 
> > 我阻止冒泡，冒泡是成功了，但是编辑器却不回车了！
> 
> 不用试了，查了挺多资料，原生form表单里面回车就是会触发提交，和wangEditor没有关系，所以form表单提交不要使用onFinish,提交事件绑定在按钮上就好了

ant 官方在from上多加了一个参数，明天就发包可以阻止回车，但还是希望wangEditor内部回车事件阻止冒泡。

**Comment by z1948296027** [comment]
> > > > > 尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。
> > > > 
> > > > 
> > > > antd的proform自己添加了一个input输入框，然后hidden掉了，回车的时候不会触发。
> > > 
> > > 
> > > 我阻止冒泡，冒泡是成功了，但是编辑器却不回车了！
> > 
> > 
> > 不用试了，查了挺多资料，原生form表单里面回车就是会触发提交，和wangEditor没有关系，所以form表单提交不要使用onFinish,提交事件绑定在按钮上就好了
> 
> ant 官方在from上多加了一个参数，明天就发包可以阻止回车，但还是希望wangEditor内部回车事件阻止冒泡。

有参考链接吗

**Comment by codedart2018** [comment]
> > > > > > 尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。
> > > > > 
> > > > > 
> > > > > antd的proform自己添加了一个input输入框，然后hidden掉了，回车的时候不会触发。
> > > > 
> > > > 
> > > > 我阻止冒泡，冒泡是成功了，但是编辑器却不回车了！
> > > 
> > > 
> > > 不用试了，查了挺多资料，原生form表单里面回车就是会触发提交，和wangEditor没有关系，所以form表单提交不要使用onFinish,提交事件绑定在按钮上就好了
> > 
> > 
> > ant 官方在from上多加了一个参数，明天就发包可以阻止回车，但还是希望wangEditor内部回车事件阻止冒泡。
> 
> 有参考链接吗

https://github.com/ant-design/ant-design-pro/issues/9073#issuecomment-916135398

**Comment by z1948296027** [comment]
> > > > > > > 尝试了下 ，只要是在表单里的输入框中按下回车 都会触发提交事件。
> > > > > > 
> > > > > > 
> > > > > > antd的proform自己添加了一个input输入框，然后hidden掉了，回车的时候不会触发。
> > > > > 
> > > > > 
> > > > > 我阻止冒泡，冒泡是成功了，但是编辑器却不回车了！
> > > > 
> > > > 
> > > > 不用试了，查了挺多资料，原生form表单里面回车就是会触发提交，和wangEditor没有关系，所以form表单提交不要使用onFinish,提交事件绑定在按钮上就好了
> > > 
> > > 
> > > ant 官方在from上多加了一个参数，明天就发包可以阻止回车，但还是希望wangEditor内部回车事件阻止冒泡。
> > 
> > 
> > 有参考链接吗
> 
> [ant-design/ant-design-pro#9073 (comment)](https://github.com/ant-design/ant-design-pro/issues/9073#issuecomment-916135398)

👍
