### ISSUE TITLE
设置编辑器里默认字号为七个字号里的最小字号

### ISSUE THREAD

**Issue by xjsdlla** [wangeditor-team/wangEditor#3577]
## 问题描述

目前设置的七个字号为12px,14px,16px,18px,20px.24px,36px
同时想要将12px设置为默认字号，像上述这么配置的话默认字号为16px

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
目前不支持修改默认字号～
