### ISSUE TITLE
配置字体好像没效果 ， 按照 文档去配置

### ISSUE THREAD

**Issue by La577138337** [wangeditor-team/wangEditor#3578]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by UltramanWeiLai** [comment]
请按照模板来填写 issue 否则是不受理的。
另外，我这边是可以配置字体效果。
请检查你在设置字体的之前，是否已经加载了相应的字体到页面中，并且检查对应命名是否准确
