### ISSUE TITLE
【bug】当编辑器被 li 标签包裹的时候，对齐方式异常

### ISSUE THREAD

**Issue by UltramanWeiLai** [wangeditor-team/wangEditor#3579]
## bug 描述

当编辑器被 li 标签包裹的时候，对齐方式会添加到外围的 li 标签上面，获取 parent 没有边界

## 你预期的样子是？

获取 parent 不要超出编辑器的边界

## 浏览器及版本号

全部

## wangEditor 版本

4.7.7

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 在实例代码的编辑器容器外添加 ul li 的标签嵌套
- 步骤二 运行代码并且在浏览器中打开编辑器
- 步骤三 输入文字并且设置对齐方式

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
