### ISSUE TITLE
企业微信工作台使用，mac 系统无法拖拽图片

### ISSUE THREAD

**Issue by qimuling55** [wangeditor-team/wangEditor#3581]
## bug 描述

*在企业微信工作台使用，mac 系统无法拖拽图片，且复制图片会变为文字，不能完整复制图片*

## 你预期的样子是？

*在企业微信工作台使用，mac 系统也可以拖拽及复制图片*

## 浏览器及版本号

*mac 企业微信内置浏览器*

## wangEditor 版本

*4.7.6*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

直接在企业微信工作台 mac 系统使用图片拖拽即可复现

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/132658706-37d2c4bb-bec0-47ae-a57f-70a9048275b8.png)

先确认下打开的浏览器是什么吧。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
