### ISSUE TITLE
先改变字号大小再设置标题，字号大小不能被覆盖

### ISSUE THREAD

**Issue by susantong** [wangeditor-team/wangEditor#3583]
## bug 描述

先给文字设置字号为48px，再給文字设置H1标题，H1的样式不能覆盖字号的样式

## 你预期的样子是？

后设置的样式覆盖先设置的样式。

## 浏览器及版本号

浏览器chrome
版本： 92.0.4515.107

## wangEditor 版本

v4.7.6

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

-选择编辑器中任意文字，设置字号为10px
-选中该文字，设置为H1标题

**Comment by UltramanWeiLai** [comment]
该问题长时间没有回复，暂且关闭
