### ISSUE TITLE
插入表格问题

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#3588]
## bug 描述

插入表格后，单元格没有高度

## 你预期的样子是？

插入表格后，希望单元格有一定的高度

## 浏览器及版本号

谷歌浏览器、 92.0.4515.159（64位）

## wangEditor 版本

最新版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
点击 表格，插入默认5行5列的表格。

**Comment by rsl140** [comment]
该问题已收录，请移步至 #3395 进行跟踪

**Comment by zxueliang** [comment]
> 该问题已收录，请移步至 #3395 进行跟踪

这个问题什么时候能给解决呢，着急使用

**Comment by rsl140** [comment]
可以自己给表格增加样式 价格height就可以了

**Comment by zxueliang** [comment]
> 可以自己给表格增加样式 加个height就可以了

怎么加呢？你们不能给解决这个问题吗？

**Comment by rsl140** [comment]
修复进度请移步到 #3395 进行查看 如果想临时解决 就自己给表格加style样式 可以临时解决
