### ISSUE TITLE
输入内容后，手动添加序号后不能对齐

### ISSUE THREAD

**Issue by carolineCQ** [wangeditor-team/wangEditor#3591]
## bug 描述

*在编辑器是里输入内容，手动添加序号后不能调整对齐*

## 你预期的样子是？

*输入内容，可以手动对齐*

## 浏览器及版本号

*Microsoft Edge 版本 92.0.902.84 *

## wangEditor 版本

*最新版*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
- 输入三行内容，手动添加序号对齐，最好添加一个背景色方便看到效果
<img width="709" alt="1630306715(1)" src="https://user-images.githubusercontent.com/88637058/131298564-22ba88f2-7ed4-4e80-8d9e-0cd0a4919d89.png">

**Comment by rsl140** [comment]
手动添加序号其实只是文本内容 至于对齐的话 也是需要自己手动调整，
建议可以尝试使用表格来达到效果

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
