### ISSUE TITLE
严重bug，图片在某些情况下无法复制（bug太大，你们忍一下）

### ISSUE THREAD

**Issue by i886** [wangeditor-team/wangEditor#3592]
## bug 描述

在你们处理这个issues时，https://github.com/wangeditor-team/wangEditor/issues/3119
造成了已存在编辑器里的图片，复制或剪切时无法插入编辑框

具体造成上面issuse多次调用插入图片的bug代码没找到

问题代码： 
                // 如果用户从百度等网站点击复制得到的图片是一串img标签且待src的http地址
                 // 见 https://github.com/wangeditor-team/wangEditor/issues/3119
                    // 如果是走用户定义的图片上传逻辑
                    const isHasOnlyImgEleReg = /^<img [^>]*src=['"]([^'"]+)[^>]*>$/g
                    if (!isHasOnlyImgEleReg.test(html)) {
                        editor.cmd.do('insertHTML', html)
                    }

## 你预期的样子是？

可正确复制图片

## 浏览器及版本号

谷歌最新版本

## wangEditor 版本

最新版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一    打开wangEditor官网首页
- 步骤二    在首页的编辑器里，翻到最下面
- 步骤三    复制微信收款码，粘贴
- 步骤四    发现无法粘贴

**Comment by i886** [comment]
贴出来一个可以暂时解决的方法，手动do，但是会还原之前的bughttps://github.com/wangeditor-team/wangEditor/issues/3119，复制网络图片会粘上去两张

editor.config.pasteTextHandle = (v) => editor.cmd.do('insertHTML', v);

**Comment by rsl140** [comment]
和#3470 问题重复，最新进度请移步至#3470
