### ISSUE TITLE
可以手动拖拽进行图片缩放么

### ISSUE THREAD

**Issue by hao-allen** [wangeditor-team/wangEditor#3593]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
目前暂时没有
