### ISSUE TITLE
拼音打字，首个字母会消失

### ISSUE THREAD

**Issue by return2-1** [wangeditor-team/wangEditor#3594]
## bug 描述

首行，第一个字拼音首个字母会消失

## 你预期的样子是？

首个字能正常输入

## 浏览器及版本号

Google  版本 92.0.4515.159

## wangEditor 版本

4.6.3

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一:vue 项目 直接安装4.6.3版本wangEditor
- 步骤二： 默认配置 ，直接使用
- 步骤三： 百度或者搜狗输入法 输入

**Comment by return2-1** [comment]
补充：输入一些文字后，删除所有文字，再次输入，会出现这个bug

**Comment by rsl140** [comment]
该问题已收录，可以到#3371 进行跟踪
