### ISSUE TITLE
官网上的编辑器，报错卡死

### ISSUE THREAD

**Issue by poolye** [wangeditor-team/wangEditor#3595]
## bug 描述

*打开官网编辑器，Ctrl+A选中所有内容，delete删除。然后点击H标题，选H2。然后Chrome控制台报错，编辑器卡死。*

## wangEditor 版本

*4.7.6*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
- 步骤一：打开官网编辑器，Ctrl+A选中所有内容，delete删除
- 步骤二：点击H标题，选H2
- 步骤三：报错卡死

![image](https://user-images.githubusercontent.com/17544309/131789736-80bfce4e-0c47-4e54-aa1a-83b513057a77.png)

**Comment by shi-lai-mu** [comment]
该问题已收录，请移步到 #3406 进行跟踪
