### ISSUE TITLE
图片选中区域大于图片本身的区域

### ISSUE THREAD

**Issue by Thlq** [wangeditor-team/wangEditor#3596]
## 问题描述

图片选中区域大于图片本身的区域

## wangEditor 版本

图片选中区域大于图片本身的区域(如图)，我看官网上的没有这种异常，请问下大概是我这边什么问题造成的呢？
![image](https://user-images.githubusercontent.com/21211777/131827139-1f5c00ea-897b-49df-874b-20f660af0d72.png)

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
首先我们得复现该问题 才能知道是什么原因导致的。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
