### ISSUE TITLE
输入第一个汉字，首字母会自动输入为英文

### ISSUE THREAD

**Issue by qinghuihu** [wangeditor-team/wangEditor#3597]
![image](https://user-images.githubusercontent.com/48936045/131842875-59d13c2d-0a73-4b88-bf02-afe3d4bd28fb.png)

**Comment by qinghuihu** [comment]
重现步骤：先输入汉字，然后再全部删除，此刻再输入就出现这个bug了

**Comment by ChenLiuPng** [comment]
群里也有2个人问。我暂时使用
`var emptyTags = ['<p><br></p>', '<br>', '<p data-we-empty-p=""></p>', const_1.EMPTY_P];
// 改成
var emptyTags = ['<p><br></p>', '<br>', '<p data-we-empty-p=""></p>', ''];`

**Comment by ChenLiuPng** [comment]
或者不修改源码
`editor.config.onchange = function(){
    if(editor.txt.html()===''){
        editor.txt.html(' &nbsp')
    }
}`

**Comment by rsl140** [comment]
请按issue模板提交内容 否则不予受理，
其次该问题已收录。
