### ISSUE TITLE
工具栏编辑区域分离自动加换行bug

### ISSUE THREAD

**Issue by hesanp** [wangeditor-team/wangEditor#3598]
代码地址：https://codepen.io/hesanp/pen/ZEyOMRY

该代码只是把官方的稍微修改了一点。

在 `<div id="text-container" class="text"></div>` 中放入了 `<p>1111</p><p>222</p><p>333</p><p>444</p><p>555</p><p>666</p>`

**然后内容区域总是在顶部自动加了1个换行。**

我想要的是 不要在内容区域顶部自动加换行。

**Comment by rsl140** [comment]
请按issue模板提交内容，否则不予受理
