### ISSUE TITLE
序列和标题功能冲突两个样式不能同时存在

### ISSUE THREAD

**Issue by qq986063761** [wangeditor-team/wangEditor#3599]
## 序列和标题功能冲突
- 先选一个标题如选：h1，然后对这个 h1 内容选区后再选择序列（无序列表和有序列表都行），然后之前的 h1 标签就没了，序列的 li 标签内只留了之前 h1 内部的内容没有包含这个 h1 标签

## 你预期的样子是？
- 应该是把根元素 h1 标签也放在序列标签 li 内部

## 浏览器及版本号
- 谷歌浏览器，版本 93.0.4577.63（正式版本） (x86_64)

## wangEditor 版本
- 4.7.7

## 官网能否复现该 bug ？
- 能

## 最小成本的复现步骤
<img width="1264" alt="WX20210904-140604@2x" src="https://user-images.githubusercontent.com/18366007/132084650-2435f83b-35f9-4100-9ce9-f7a453454b34.png">

- 先选一个标题如选：h1
- 然后对这个 h1 内容选区后再选择序列（无序列表和有序列表都行）
- 查看之前的 h1 标签就没了，序列的 li 标签内只留了之前 h1 内部的内容，并没有包含这个 h1 根标签

## 我从源码中找到的原因的相关文件代码位置
- src/menus/list/utils.ts 的 createElementFragment 函数定义内部因为用了 $list.innerHTML = $node.html()，但是这种情况下这个 html() 方法返回的内容并没有包含 h1 标签自己

**Comment by rsl140** [comment]
你好，该功能不支持同时使用，只能二选一

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
