### ISSUE TITLE
移动端插入代码功能的编辑框显示异常

### ISSUE THREAD

**Issue by SteveCGC** [wangeditor-team/wangEditor#3600]
## bug 描述

*
如图所示，移动端富文本，点击插入代码时
![image](https://user-images.githubusercontent.com/16144832/132094931-a4faf309-7247-4322-8fd4-c2a4c3bdc7f0.png)
*

## 你预期的样子是？

*编辑框正常在中间显示*

## 浏览器及版本号

*chrome 92.0.4515.159*

## wangEditor 版本

*4.7.7*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
chrome调成移动端调试模式
- 步骤二
集成wangeditor
- 步骤三
点击插入代码

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/132190063-966690f6-77ef-4596-853d-44b86b5ca449.png)

**Comment by SteveCGC** [comment]
能处理下移动端吗

**Comment by rsl140** [comment]
目前V4没有计划兼容移动端
