### ISSUE TITLE
自定义配置panel菜单中tabs中的events未生效

### ISSUE THREAD

**Issue by qcz121** [wangeditor-team/wangEditor#3601]
## 问题描述
自定义panel菜单时，conf中配置的events未生效

## wangEditor 版本
4.4.7

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

 步骤一
声明一个类AlertMenu继承PanelMenu
![image](https://user-images.githubusercontent.com/42165863/132113259-3d064920-0785-4155-8441-02e967f9e4b8.png)
步骤二
设置pancelConf中的tabs
![image](https://user-images.githubusercontent.com/42165863/132113274-c105df85-4d45-4d5a-b466-3a86f0aba5fb.png)
步骤三
点击插入并不会触发console.log(123)
![image](https://user-images.githubusercontent.com/42165863/132113302-23bf49ad-74d0-48a5-b48f-3aa38d5abbed.png)

**Comment by rsl140** [comment]
你这 也看不出来呀，可以尝试提供下复现场景，如codepen之类的

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
