### ISSUE TITLE
文字靠右对齐

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#3602]
## bug 描述

设置文字靠右对齐后，提交给后台后，文字又靠左对齐了。

## 你预期的样子是？

文字靠右对齐后，提交到后台还是靠右对齐

## 浏览器及版本号

谷歌浏览器（ 93.0.4577.63）

## wangEditor 版本

4.7.2

## 官网能否复现该 bug ？

官网上可以设置靠右，但是没有提交

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
建议你对比下提交前的代码和从后台获取的代码是否一致，本质上只是有个style="text-align:right;"样式增加

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
