### ISSUE TITLE
编辑器h1-h5换行后是div标签，div标签和h1-5标签设置行高都无效

### ISSUE THREAD

**Issue by Taonanqiang** [wangeditor-team/wangEditor#3603]
## bug 描述

*编辑器从Word粘贴过来的h1-h5换行后是div标签，div标签和h1-5标签设置行高都无效*

## 你预期的样子是？

*h1-h5标签可以设置行高，换行后可以是同类型标签，也可是默认p标签*

## 浏览器及版本号

*Chrome92.0.4515.131*

## wangEditor 版本

*4.7.6*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 在Word编辑一段内容，设置为标题格式
- 粘贴到编辑器上，然后进行换行，另起的一行是div格式，编辑另一段内容，
- 对两个段落进行行高设置无效
- 忽略Word格式问题，H1-5标签行高依旧无法设置

**Comment by rsl140** [comment]
h1-5标签内容，设置行高无效

**Comment by Taonanqiang** [comment]
> h1-5标签内容，设置行高无效

这么简单粗暴的吗，那Word标题格式粘贴过来的格式问题能看看吗

**Comment by rsl140** [comment]
关于粘贴方面 有一个issue在跟进了，但是粘贴这块坑比较多，进度比较缓慢

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
