### ISSUE TITLE
添加表格时，能否默认不添加表头？

### ISSUE THREAD

**Issue by rieval** [wangeditor-team/wangEditor#3604]
## 问题描述

使用表格按钮添加表格时，好像默认会使用表头功能，但我目前的业务并不需要表头功能，每次都要手动关闭表头挺麻烦的，有没有什么办法默认不添加表头？

## wangEditor 版本

v4.7.7

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

/

**Comment by rsl140** [comment]
目前暂不支持该功能
