### ISSUE TITLE
[国际化切换不生效]

### ISSUE THREAD

**Issue by jiemodetang** [wangeditor-team/wangEditor#3605]
## 问题描述

editor.customConfig.lang初始化配置后，全局改变语言，多语言不生效

## wangEditor 版本

3

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 配置改变语言，new之后多实例初始化editor.customConfig.lang无法改变，不想销毁dom实例

**Comment by jiemodetang** [comment]
有没有update的方法，调用源码replaceLang改变语言

**Comment by rsl140** [comment]
抱歉，目前暂时不支持该功能
