### ISSUE TITLE
标准模式下设置onchangeTimeout无效

### ISSUE THREAD

**Issue by littlewhiteuser** [wangeditor-team/wangEditor#3606]
## 问题描述

![image](https://user-images.githubusercontent.com/32633362/132438688-be92fdf4-d587-4222-a77a-236f0ceec02b.png)
标准模式下设置onchangeTimeout无效，看源码是被重置了，这一步的目的是什么呢？

## wangEditor 版本

4.7.7

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by clinfc** [comment]
之所以会重置为固定值，是因为我们内部的 js 代码可能会在 DOM 变化后对内容进行二次修正，如果用户可以自定位为 0，那么上诉的特殊情况会生成两个历史记录（即两步）。你值更改了一次，却需要撤销两次，这明显不合理，并且如果你只撤销了一次，意味着 DOM 结构并不是理想结构，这会造成一些意外的 bug。

并且内部触发 change 并不是同步的，而是异步触发。在国内使用折叠输入（拼音输入）的是绝大多数人。在底层中，拼音输入的这个阶段一直在触发 change，然而常规认知是拼音输入完成才是一步历史记录，这里重置为 30 也有考虑到拼音输入结束后，能完整的将变化保存为一步历史记录。

**Comment by clinfc** [comment]
兼容模式下，每一步历史记录都是对整个文档的完整保存，所以不太需要考虑一些特殊情况，而正常模式下是对 DOM 树中标签变化的记录而生成历史记录，也可以成为 DOM 树的差异变化的记录，其核心原理是不一样的
