### ISSUE TITLE
table表格

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#3608]
## 问题描述

从word复制的表格及表格里面的内容，怎么调整单元格的宽度及高度，怎么调整单元格里的内容对齐方式

## wangEditor 版本

4.7.7

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
目前的话 你可以考虑通过设置tr td的style样式来进行调整

**Comment by zxueliang** [comment]
这不太现实，有的宽有的窄，这个功能什么时候上线

**Comment by rsl140** [comment]
由于功能较为复杂，目前优先级不高，短期内暂时没有该计划

**Comment by wangfupeng1988** [comment]
这个功能近期不会去做。
计划是这样的：1. 待 v5 发布、稳定之后；2. 升级表格组件功能，加上调整宽高；
