### ISSUE TITLE
IE11 下点击插入表格按钮，无法生成表格

### ISSUE THREAD

**Issue by rieval** [wangeditor-team/wangEditor#3609]
## bug 描述

跟之前同样的问题：https://github.com/wangeditor-team/wangEditor/issues/3533

无法插入表格，看着像是 Promise 的问题，编译的时候没有降级引入 polyfill 吗？
能请尽快答复一下吗？如果没时间修复，说一下解决的大概思路也可以的，我这边项目赶着要上线。

## 你预期的样子是？

能插入表格

## 浏览器及版本号

IE 11

## wangEditor 版本

v4.7.7

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

/

**Comment by wangfupeng1988** [comment]
紧急处理的话，你那边自己先做一下 Promise polyfill 兼容吧，这是最快的方式。
