### ISSUE TITLE
customInsertVideo函数不生效

### ISSUE THREAD

**Issue by lazzzzzz** [wangeditor-team/wangEditor#3610]
## bug 描述

我在editor.create()之前设置了editor.config.customInsertVideo函数，但是此函数内部的代码没有在插入视频时执行。

## 你预期的样子是？

在点击 视频 >输入url>提交 之后，正确的执行customInsertVideo里的代码

## 浏览器及版本号

chrome 92.0.4515.159 

## wangEditor 版本

4.7.7

## 官网能否复现该 bug ？

不能（并不让我设置,但是官网上指向codepen的demo体验中可以）

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- new一个editor
- 设置editor.config.customInsertVideo
- editor.create()
- 插入一个视频

**Comment by rsl140** [comment]
该功能是指在本地上传视频的情况下才触发该函数

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
