### ISSUE TITLE
源码打包大小问题

### ISSUE THREAD

**Issue by qinghuihu** [wangeditor-team/wangEditor#3612]
## 问题描述

大佬们，因为自己修改了源码，然后打包，但是发现打包的比npm上面的大了将近一倍。请问怎么打包，大小才能跟npm上面的包一样。

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

![image](https://user-images.githubusercontent.com/48936045/132703834-cca9dd36-8e25-44da-99d2-595717678511.png)
![image](https://user-images.githubusercontent.com/48936045/132703931-e0ef3ca8-07b7-4fd8-bdb7-b221dadabd6d.png)

**Comment by wangfupeng1988** [comment]
就 npm run build ，发布 npm 也是这样打包的
https://github.com/wangeditor-team/wangEditor/blob/master/.github/workflows/npm-publish.yml

**Comment by qinghuihu** [comment]
> 就 npm run build ，发布 npm 也是这样打包的
> https://github.com/wangeditor-team/wangEditor/blob/master/.github/workflows/npm-publish.yml

ok，谢谢福朋哥的回复。但我就只加了给图片添加链接的代码（文本改为range），代码量改动也不大。我再看看打包流程。会不会是我添加了icon的字体包的原因？
