### ISSUE TITLE
自定义上传图片，在紧挨着的字之间插入多张图片，会少插入一个

### ISSUE THREAD

**Issue by NorthWind17** [wangeditor-team/wangEditor#3613]
## 问题描述

自定义上传图片，在紧挨着的字之间插入多张图片，会少插入一个

## wangEditor 版本

"wangeditor": "^4.7.6"

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

editor.config.customUploadImg = function (files, insertImgFn) {
                    // files 是 input 中选中的文件列表
                    // insert 是获取图片 url 后，插入到编辑器的方法

                    // 上传代码返回结果之后，将图片插入到编辑器中
                    files.forEach((item) => {
                        _this.upload(item, insertImgFn, editor)
                    })
                }

upload(file, insertImgFn, editor) {
            const that = this
            let httpurl = ''
            httpurl += that.url.add
            let method = 'post'
            let newVal = new FormData()
            newVal.append('file', file)
            newVal.append('biz', 'temp')
            httpAction(httpurl, newVal, method)
                .then((res) => {
                    if (res.success) {
                        insertImgFn(res.message)  //res.message是上传接口返回的图片url
                    } else {
                        that.$message.warning(res.message)
                    }
                })
                .finally(() => {})
        }

**Comment by rsl140** [comment]
你这,不是很明白你在表达什么

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
