### ISSUE TITLE
复制粘贴时可以过滤样式，那用js添加内容时怎样配置过滤样式。

### ISSUE THREAD

**Issue by qinsansang** [wangeditor-team/wangEditor#3615]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本 4.7.8

js添加内容时怎样配置过滤样式。

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三
复制粘贴时可以过滤样式，那用js添加内容时怎样配置也过滤样式。

**Comment by rsl140** [comment]
这个需要你自己进行处理后在插入到编辑器中，可以参考源码[paste-text-html](https://github.com/wangeditor-team/wangEditor/blob/master/src/text/event-hooks/paste-text-html.ts)
