### ISSUE TITLE
编辑器的边框样式怎么去除

### ISSUE THREAD

**Issue by a327958099** [wangeditor-team/wangEditor#3616]
编辑器的顶层div会自定添加style样式边框属性，请问这个样式是否可以同个配置去除，我不想要这个样式，和我的主题不搭配
![image](https://user-images.githubusercontent.com/26393031/132987017-98b86e70-b1c3-4390-a852-f3674d1cf1a5.png)

**Comment by UltramanWeiLai** [comment]
请按照模板提交 issue 否则是不受理的。
边框目前是无法配置的
可以直接使用 css 的 !important 强行覆盖掉
