### ISSUE TITLE
是否可以支持选择已经上传成功（素材库）的图片和视频？

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [wangeditor-team/wangEditor#3617]
对于图片和视频的插入是否可以支持选择已经上传成功的图片？
点击图片或者视频的图标，出现一个自定义弹窗，用户可以选择已经上传成功的图片或者视频！
例如：微信公众号的编辑页面！

**Comment by rsl140** [comment]
请按issue模板提交内容 
[从媒体库上传图片](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/16-%E4%BB%8E%E5%AA%92%E4%BD%93%E5%BA%93%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87.html)
