### ISSUE TITLE
英文文档标题的单词错误

### ISSUE THREAD

**Issue by BruceLuo33** [wangeditor-team/wangEditor#3618]
## 英文文档的单词错误

现在的文档上面，是这样的：

A lightweight rich text editor, friendly API and use extremely conventient.

## 你预期的样子是？

conventient --> convenient

另外，这句话感觉有语病。

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

与版本无关

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

改单词

**Comment by wangfupeng1988** [comment]
感谢反馈～
