### ISSUE TITLE
在使用图片上传时，上传接口需要将图片名字作为参数传递给后端来使用，

### ISSUE THREAD

**Issue by jcbound** [wangeditor-team/wangEditor#3620]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本
4.7.8
*请输入内容……*
你们好，我在使用图片上传时，上传接口需要将图片名字作为参数传递给后端来使用，我使用editor.config.uploadImgHooks上传钩子在
before方法里获取到xhr数据，但是里面并没有有关图片的信息，那么目前能够获取到吗
## 是否查阅了文档 ？
查阅了，
（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤
需要调用个上传接口来验证
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
[自定义 header](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/06-%E8%87%AA%E5%AE%9A%E4%B9%89header.html)
[自定义上传参数](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/04-%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0%E5%8F%82%E6%95%B0.html)

**Comment by jcbound** [comment]
谢谢回复，上面的那两个我用了，我的意思是我期望的传参是这样的`{uploadFile:(binary),attachName: Z.jpg}` 实际上我的传参是`{uploadFile:(binary),attachName: null}`  这个图片的信息，我在上传时xhr对象中是没有的，所以没法给attachName赋值图片名字，类似于element ui 中的上传组件一样，它会在上传前从file参数中拿到这个文件的信息，我就可以手动给他文件赋值，咱们这个能拿到这个文件信息吗，文档中的方法我都试了下，只有成功才会返回图片的相关信息，

**Comment by wangfupeng1988** [comment]
可以使用 fileName 参数 https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/05-%E8%87%AA%E5%AE%9A%E4%B9%89filename.html

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
