### ISSUE TITLE
图片上传返回格式

### ISSUE THREAD

**Issue by fabin5** [wangeditor-team/wangEditor#3621]
## 功能描述

*各家公司服务端上传接口返回的字段和结构可能不同，所以无法按照wangEditor的要求，数据格式跟要求的一致*

## 提炼几个功能点

- server 接口返回格式做成可配置的。

**Comment by rsl140** [comment]
可以[自己实现上传功能](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/11-%E8%87%AA%E5%B7%B1%E5%AE%9E%E7%8E%B0%E4%B8%8A%E4%BC%A0%E5%8A%9F%E8%83%BD.html)的
