### ISSUE TITLE
上传图片失败时的alter弹窗可以在editor.config.uploadImgHooks.fail中覆盖掉吗？

### ISSUE THREAD

**Issue by yangfancn** [wangeditor-team/wangEditor#3622]
## 问题描述
![image](https://user-images.githubusercontent.com/42950770/133595852-9c63bbe6-c444-47f7-a66f-2792fd2d375f.png)
我想在 fail 中自定义消息提示，但是alter弹窗我无法取消

## wangEditor 版本

*CDN 4.7.8*

**Comment by rsl140** [comment]
[自定义alert](https://www.wangeditor.com/doc/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/09-%E8%87%AA%E5%AE%9A%E4%B9%89%20alert.html)
