### ISSUE TITLE
选中多行文字，最后一行设过颜色，再调整行高会导致部分文字变为两遍

### ISSUE THREAD

**Issue by HomyZhu** [wangeditor-team/wangEditor#3624]
## bug 描述

*在使用中发现一个特别的问题，随便输入多行文字，最后行中随便几个字设置颜色，选中这两行调整行高的时候，有颜色的文字加上到行尾的内容，即会被复制为两遍。但设置颜色的不在最后一行，或是再多选一个空行(也即有颜色的不是最后一行了)，就不会出现此 bug 了。*

## 你预期的样子是？

*调整行高不会使任何文字变为两遍*

## 浏览器及版本号

*QQ浏览器最新版和谷歌浏览器最新版，均可复现*

## wangEditor 版本

*V4最新版*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：第一行输入123，第二行输入123
- 步骤二：将第二行中的 2 设置为红色
- 步骤三：选中这两行(不能多选第三行)，调整行高为 2，即可看到第二行变成了 12323

**Comment by Gavin-yh** [comment]
> range的问题，，我的已经解决了
