### ISSUE TITLE
内容问题

### ISSUE THREAD

**Issue by Baishao-xue** [wangeditor-team/wangEditor#3626]
## bug 描述

删除内容之后，输入第一个字母有问题，第一个字母会被忽略

## 你预期的样子是？

输入之后应该是可以正常输入的

## 浏览器及版本号

谷歌稳定版

## wangEditor 版本

最新版

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

第一步输入内容

第二步删除内容

第三步输入内就会看到 比如输入拼音 women  字母w就会被忽略

**Comment by rsl140** [comment]
请移步到 #3423 进行跟着
另: 该问题正在定位，目前已知只有谷歌会复现该问题。
