### ISSUE TITLE
editor.txt.html()转义问题

### ISSUE THREAD

**Issue by 994681903** [wangeditor-team/wangEditor#3628]
## bug 描述
插入代码时插入'\<String\>',然后获取html()格式,不符合预期(不会对\<和\>转义)。

![image](https://user-images.githubusercontent.com/58013994/133987355-646da196-f3e6-43ea-a721-884350d4996d.png)

## 你预期的样子是？
对于 \<String\> 应该是转义成功的。

## 浏览器及版本号

内核版本: Chromium 75.0.3770.100  +  IE (Trident 7~11)

## wangEditor 版本

V4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

代码插入'\<String\>'然后获取其html()格式。

**Comment by rsl140** [comment]
不太明白你的意思，麻烦完成描述一下复现步骤。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
