### ISSUE TITLE
图片拖拽和剪切

### ISSUE THREAD

**Issue by MsNan** [wangeditor-team/wangEditor#3631]
## 功能描述

*MAC操作系统，在官网操作图片拖拽没有此功能，能否实现，编辑器内的图片选中剪切或者复制到其他位置功能能否实现*

## 提炼几个功能点

- 功能1 编辑器内上传的图片拖拽到其他位置
- 功能2 编辑器内上传的图片剪切复制到其他位置
- 功能3 视频同理能否实现

**Comment by wangfupeng1988** [comment]
该功能 v5 实现了。v5 在 10 月会开放用户测试版。
