### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by zidingz** [wangeditor-team/wangEditor#3634]
Hey there!

I belong to an open source security research community, and a member (@shellinjector) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by wangfupeng1988** [comment]
Security issue will be fixed in 5.0 version

**Comment by JamieSlome** [comment]
@wangfupeng1988 - if you believe the report to be valid; if you could please ensure you mark it accordingly, so that the researcher is rewarded for their efforts!

**Comment by ShellInjector** [comment]
Can you please just confirm the issue on huntr.dev , if you believe that the v4 is vulnerable and the bug is valid.
