### ISSUE TITLE
编辑器内复制并粘贴 todo list（待办事项），复选框会变成输入框

### ISSUE THREAD

**Issue by Shaun-Li** [wangeditor-team/wangEditor#3635]
## bug 描述

编辑器内复制并粘贴 todo list（待办事项），复选框会变成输入框

## 你预期的样子是？

复制粘贴后，还是 checkbox

## 浏览器及版本号

Chrome 94.0.4606.54（正式版本） (x86_64)

## wangEditor 版本

4.7.8

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

输入几个 todo list，复制，粘贴

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
