### ISSUE TITLE
扩展tooltip是遇到节点无法定位

### ISSUE THREAD

**Issue by hzylab** [wangeditor-team/wangEditor#3636]
3302 | var textElemRect = this.editor.$textElem.getBoundingClientRect(); // 获取基于 textContainerElem 的 位置信息
  3303 | 
> 3304 | var targetOffset = this.$targetElem.getOffsetData();
       | ^  3305 | var targetParentElem = dom_core_1["default"](targetOffset.parent); // 获取 编辑区域的滚动条信息
  3306 | 
  3307 | var scrollTop = this.editor.$textElem.elems[0].scrollTop; // 是否插入 textContainer 中

**Comment by rsl140** [comment]
请按issue模板提交问题，否则不予受理。
