### ISSUE TITLE
希望视频上传也有类似图片的uploadImgFromMedia方法

### ISSUE THREAD

**Issue by HackerWand** [wangeditor-team/wangEditor#3637]
## 功能描述

通过媒体库选取视频，把获取到的视频url插入

我现在直接通过自定义菜单的方式，吊起媒体库，然后通过API插入video标签会报错
this.$editor.cmd.do('insertHTML', `<video src="${data.url}" controls="controls" style="max-width:100%"></video>`)
Uncaught TypeError: Cannot read properties of undefined (reading 'bind')
    at module.exports (wangEditor.js?6fad:9139)
    at eval (wangEditor.js?6fad:13596)
    at Array.forEach (<anonymous>)
    at Menus.changeActive (wangEditor.js?6fad:13593)
    at saveRange (wangEditor.js?6fad:11749)
    at eval (wangEditor.js?6fad:11787)

**Comment by HackerWand** [comment]
暂时先用下面的方法解决了
```
  // 打开媒体库并插入
  editor.config.uploadVideoFromMedia = () => {
      this.media.show = true
      this.media.type = 'video'
      this.media.insert = (data) => this.$editor.cmd.do('insertHTML', '<video src="' + data.url + '" controls="controls" style="max-width:100%"></video><p data-we-empty-p=""><br></p>')
    }

    // 先创建
    editor.create()

    // 覆盖点击
    const videoMenu = editor.menus.menuList.find(v => v.key === 'video')
    videoMenu.clickHandler = function () {
      editor.config.uploadVideoFromMedia()
    }
```

**Comment by rsl140** [comment]
那这边先关闭issue了
