### ISSUE TITLE
内容输入错误

### ISSUE THREAD

**Issue by ju7-mo** [wangeditor-team/wangEditor#3640]
## bug 描述

键盘输入中文内容后，第一个字符会被转为英文字母。
https://gyazo.com/cbcf172cbe085b6e4544e9dfbf8cd718

## 你预期的样子是？

输入内容，正常显示。

## 浏览器及版本号

Chrome 93.0.4577.82

## wangEditor 版本

v4.7.8

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一：打开wangEditor官网首页。
- 步骤二：滑动到编辑最底部（注意不要点击编辑器）。
- 步骤三：输入 “你好”，此时编辑器里面会显示为 "n好"

**Comment by UltramanWeiLai** [comment]
#3423 
可以移步到该 issue 中
