### ISSUE TITLE
Vue3.0 + Vite中使用后 打包报错 Unsupported source map comment 

### ISSUE THREAD

**Issue by ZANJIAHAO1008** [wangeditor-team/wangEditor#3642]
## bug 描述

[vite] warnings while transforming wangeditor.01f2c293.js with esbuild:
Unsupported source map comment
24413|  /******/ ])["default"];
24414|  });
24415|  //# sourceMappingURL=wangEditor.js.map
   |                       ^
24416|  });

## 你预期的样子是？

无报错

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

 Google Chrome 版本 92.0.4484.7（正式版本） （32 位）

## 官网能否复现该 bug ？

不知道

## 最小成本的复现步骤

Vue3.0 + vite 使用wangeditor后打包可以复现

**Comment by rsl140** [comment]
该问题已收录，请移步至 #3076  进行跟踪。
