### ISSUE TITLE
给图片tooltip加个添加超链接功能

### ISSUE THREAD

**Issue by qinsansang** [wangeditor-team/wangEditor#3646]
## 功能描述

*请输入内容……*

## 提炼几个功能点

给图片tooltip加个添加超链接功能

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

                {
                    $elem: $('<span>添加超链</span>'),
                    onClick: (editor, $node) => {
                        const urlhtml = prompt('输入链接：')
                        if (!urlhtml) return
                        let imghtml = ''
                        let parhtml = ''
                        if ($node.parent().selector.nodeName == 'A')  {
                            let reg3 = /(<\/?a.*?>)/gi
                            parhtml = $node.parent().selector.outerHTML
                            imghtml = parhtml.replace(reg3,'')
                            editor.selection.createRangeByElem($node.parent())
                            editor.selection.restoreSelection()
                        } else { 
                            imghtml = $node.selector.outerHTML
                            editor.selection.createRangeByElem($node)
                            editor.selection.restoreSelection()
                        }
                        if (!imghtml) return
                        editor.cmd.do('insertHTML', `<a href="${urlhtml}" target="_blank">${imghtml}</a>`)
                        return true
                    },
                },
                {
                    $elem: $('<span>查看超链</span>'),
                    onClick: (editor, $node) => {
                        if ($node.parent().selector.nodeName == 'A')  {
                            alert($node.parent().selector.href)
                        }
                        return true
                    },
                },
                {
                    $elem: $('<span>取消超链</span>'),
                    onClick: (editor, $node) => {
                        if ($node.parent().selector.nodeName == 'A')  {
                            let imghtml = ''
                            let parhtml = ''
                            let reg3 = /(<\/?a.*?>)/gi
                            parhtml = $node.parent().selector.outerHTML
                            imghtml = parhtml.replace(reg3, '')
                            editor.selection.createRangeByElem($node.parent())
                            editor.selection.restoreSelection()
                            if (!imghtml) return
                            editor.cmd.do('insertHTML', `${imghtml}`)
                        }
                        return true
                    },
                },

**Comment by rsl140** [comment]
该功能再V5版本已实现

**Comment by HCLAC** [comment]
> 该功能再V5版本已实现，v4版本暂时只做维护工作

您好，v5什么时候发布啊
