### ISSUE TITLE
文末换行时，config.onchange回调接收到的br与实际的行数不一致

### ISSUE THREAD

**Issue by DearGaz** [wangeditor-team/wangEditor#3650]
## bug 描述

在文末回车换行时，config.onchange回调接收到的<br />数量比编辑器实际的换行行数少一行

## 你预期的样子是？

onchange回调接收到的数据与展示的一致

## 浏览器及版本号

Chrome 93.0.4577.82（正式版本） （64 位）

## wangEditor 版本

最新版

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

step1： 运行最简代码代码
step2：输入任意文字，换行，查看控制台

图示
![image](https://user-images.githubusercontent.com/41284640/136537240-644c674a-f6ef-488d-9760-c143e714f0e2.png)

![image](https://user-images.githubusercontent.com/41284640/136537655-c9ca0924-4a0c-400e-885b-7cd44f26e11c.png)

![image](https://user-images.githubusercontent.com/41284640/136537588-b5e052f8-597e-40a7-ba0b-58c78fcf4ed4.png)

**Comment by rsl140** [comment]
抱歉，没有看的太懂
你的意思是说，编辑器再disable的状态下 通过JS来更改内容么？

**Comment by DearGaz** [comment]
@rsl140  不是。 其实是React框架下的一些使用风格（受控模式），通过onchange实时获取编辑器的内容状态，然后通知到上层组件；或者从上层组件接收数据，编辑器组件重新设定自己的数据。

不过呢，后来通过onblur监听，实现了大多数的功能，虽然偶尔会碰到换行失败的情况，但是还可以接受~ 

根本的原因还是，实时编辑的内容与onchange回调的不一致。希望考虑考虑，印象中 v3版本是没有这个问题的

**Comment by DearGaz** [comment]
@rsl140  感谢感谢 先关了
