### ISSUE TITLE
V4的onCatalogChange事件 V5还有吗？ 看了一圈没找到

### ISSUE THREAD

**Issue by CodeWithiYouth** [wangeditor-team/wangEditor#3657]
## 问题描述
在V5版本没有找到V4里的onCatalogChange事件

## wangEditor 版本
V5

## 是否查阅了文档 ？
是

**Comment by Gavin-yh** [comment]
v5版本的可以在： https://github.com/wangeditor-team/wangEditor-v5这里提issue
