### ISSUE TITLE
编辑器行数超过47，编辑界面就不会随着光标下移

### ISSUE THREAD

**Issue by CodeWithiYouth** [wangeditor-team/wangEditor#3658]
## bug 描述

编辑器行数超过47，编辑界面就不会随着光标下移
demo页面就有这个问题

## 你预期的样子是？

无论多少行都随着光标下移

## 浏览器及版本号

Chrome，                                                       360极速浏览器
94.0.4606.71（正式版本） （64 位）

## wangEditor 版本

V5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接按住回车行数过多编辑区不随光标下移

**Comment by Gavin-yh** [comment]
v5版本的可以在： https://github.com/wangeditor-team/wangEditor-v5这里提issue

**Comment by rsl140** [comment]
> 拼音输入第一个字体的时候会消失

该问题可以移步 #3423  查看进度
