### ISSUE TITLE
在编辑器内手动输入的回车换行和从txt中复制进去的表现不一样

### ISSUE THREAD

**Issue by Firesuiry** [wangeditor-team/wangEditor#3659]
## bug 描述

在编辑器内手动输入的回车和从txt中复制进去的表现不一样
![image](https://user-images.githubusercontent.com/30189673/136949212-d95b801f-467d-4719-a202-2f5306afdeff.png)

## 你预期的样子是？

两个方法输入的应该是一致的

## 浏览器及版本号

Microsoft Edge
版本 94.0.992.38 (官方内部版本) (64 位)

## wangEditor 版本

官网版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
在编辑器中输入 1 回车 1 回车 1 回车 1 回车
- 步骤二
在txt中输入 1 回车 1 回车 1 回车 1 回车
- 步骤三
将txt中的内容复制到编辑器

**Comment by Gavin-yh** [comment]
txt复制过来的都是文本，没有标签，所以展示的都是文本。和编辑器输入的形式是两个概念

**Comment by cNelf** [comment]
> > > txt复制过来的都是文本，没有标签，所以展示的都是文本。和编辑器输入的形式是两个概念
> > 
> > 
> > 我看新的编辑器里面两种输入方式表现是一样的。 请问这个是在旧的编辑器里设计就是不一样的吗？
> 
> 新版和旧版的实现方式不一样。旧版是基于浏览器自带的api实现的



> > > txt复制过来的都是文本，没有标签，所以展示的都是文本。和编辑器输入的形式是两个概念
> > 
> > 
> > 我看新的编辑器里面两种输入方式表现是一样的。 请问这个是在旧的编辑器里设计就是不一样的吗？
> 
> 新版和旧版的实现方式不一样。旧版是基于浏览器自带的api实现的

那请问我想要回车默认使用<br>换行，而不是插入p标签，需要怎么配置呢？

**Comment by rsl140** [comment]
> 那请问我想要回车默认使用换行，而不是插入p标签，需要怎么配置呢？
暂时没有该功能，包裹P标签是有原因的，为了不免不必要的未知样式错误等
