### ISSUE TITLE
自定义图片上传时, 提交的form表单数据中没有图片内容

### ISSUE THREAD

**Issue by lingting** [wangeditor-team/wangEditor#3662]
## 问题描述

自定义图片上传时, 提交的form表单数据中没有图片内容, 只有文件名和类型.
![image](https://user-images.githubusercontent.com/59352063/137088829-b1592013-caa0-4291-b0ad-5d747620ab30.png)

## wangEditor 版本
4.7.8

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
https://codesandbox.io/s/wangeditor-mm1vr?file=/src/App.tsx

**Comment by Gavin-yh** [comment]
![image](https://user-images.githubusercontent.com/40813001/137230804-915d9bf3-0371-471d-a717-e1682c8e3627.png)

提交是有数据的，你换个正常服务器地址。

**Comment by lingting** [comment]
> ![image](https://user-images.githubusercontent.com/40813001/137230804-915d9bf3-0371-471d-a717-e1682c8e3627.png)
> 
> 提交是有数据的，你换个正常服务器地址。

控制台有数据, 你看 network , 没有发数据出去.

**Comment by lingting** [comment]
> ![image](https://user-images.githubusercontent.com/40813001/137230804-915d9bf3-0371-471d-a717-e1682c8e3627.png)
> 
> 提交是有数据的，你换个正常服务器地址。

你按f12看具体发出去的请求里面是什么东西. 有没有数据.

**Comment by Gavin-yh** [comment]
请求没有发送数据是业务方的问题，编辑器已经将对应的数据给到了业务方。

**Comment by lingting** [comment]
> 请求没有发送数据是业务方的问题，编辑器已经将对应的数据给到了业务方。
我就把数据放到 formData里面发出去, 里面都是空的. 我该怎么弄才能有数据?
