### ISSUE TITLE
能否知道是否点击菜单某个按钮的方法或者事件吗，请问有提供类似的api吗

### ISSUE THREAD

**Issue by jcbound** [wangeditor-team/wangEditor#3663]
## 问题描述
我页面导航栏是fixed固定的 z-index:10，编辑器的包裹元素z-index:9,这样就不会浮在导航上面，但是导致使用全屏功能时，菜单栏是在导航栏的下面，影响使用了，我想知道有没有个菜单点击方法，我点击菜单就知道点击的是那个菜单按钮，当我点击全屏时，手动把z-index给改大，大致就是这样，谢谢！

*请输入遇到的问题...*

## wangEditor 版本
4.7.8
*请输入内容……*

## 是否查阅了文档 ？
查阅了，没看到类似的方法，
（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
那这边先关闭了
