### ISSUE TITLE
vue结合 wangEditor，菜单栏如何改成英文的

### ISSUE THREAD

**Issue by linooooooo** [wangeditor-team/wangEditor#3665]
this.editor.config.lang = 'en'
这样改了之后没有反应，菜单栏提示还是中文

**Comment by rsl140** [comment]
请按issue模板提交内容！

确认是否引入了i18next插件。
请根据[文档](https://www.wangeditor.com/doc/pages/12-%E5%A4%9A%E8%AF%AD%E8%A8%80/)内容操作
