### ISSUE TITLE
wangEditor 作为受控组件使用时，value 改变光标移到末尾，求如何控制

### ISSUE THREAD

**Issue by nolan1230** [wangeditor-team/wangEditor#3666]
## bug 描述

在处理输入时文本替换时（检测输入的内容有 #tag# 这种形式，就替换将 #tag# 部分替换成<i>tag</i>）,在 onChange 里调用 外层组件传入的回调函数改变 value。但这时光标就自动被设置到了最后，导致不能正常在中间插入输入。

## 最小成本的复现步骤

https://codesandbox.io/s/prod-microservice-jhtph?file=/src/App.tsx

**Comment by wangfupeng1988** [comment]
你可以给 wangeditor-for-react 提交一个 issue ，这是一个第三方的库。

然后，你可以再试试 v5 新版本，会否有这个问题 https://www.wangeditor.com/v5/guide/for-frame.html#react

**Comment by xdoer** [comment]
最近也遇到了这样的问题，这是我的解决方案: [富文本编辑器转为受控组件的一种思路](https://aiyou.life/post/Fjnj0JDZ5/)，可以一起探讨下哈..
