### ISSUE TITLE
V5版本没有待办，checkedbox了吗

### ISSUE THREAD

**Issue by Zeng1998** [wangeditor-team/wangEditor#3674]
## 问题描述

V5版本工具栏没找到待办工具

## wangEditor 版本

v5 （https://www.wangeditor.com/v5/guide/installation.html）  

## 是否查阅了文档 ？

https://www.wangeditor.com/v5/guide/installation.html 这个文档地址不对吗

## 最小成本的复现步骤

https://www.wangeditor.com/demo/zh-CN/index.html  这个demo上也没有待办

**Comment by rsl140** [comment]
目前V5只是基本功能，这些较为复杂的功能后续会陆续加入进来的。
其次关于V5的issue 请提交到[这里](https://github.com/wangeditor-team/wangEditor-v5/issues)
