### ISSUE TITLE
在一串数字中间添加视频（视频上传方式是文档中的自定义上传功能）视频的靠右靠左居中功能失效

### ISSUE THREAD

**Issue by surviavalF** [wangeditor-team/wangEditor#3675]
## bug 描述

在一串数字中间添加视频（视频上传方式是文档中的自定义上传功能）视频的靠右靠左居中功能失效，根据console了txt.html()发现，直接在字符中插入<video>标签外无<p>标签包裹，所以无法实现位置更改功能。

## 你预期的样子是？

可以成功更换视频位置

## 浏览器及版本号

Google Chrome 94.0.4606.81

## wangEditor 版本

    "wangeditor": "^4.7.9"

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 在一串数字或字母中间添加视频

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
