### ISSUE TITLE
在标题行的最前面点击删除后，本来的h标签变成p包含span且span内有style样式

### ISSUE THREAD

**Issue by hou-zhe** [wangeditor-team/wangEditor#3676]
## bug 描述

在标题行的最前面点击删除后，本来的h标签变成p包含span且span内有style样式

## 你预期的样子是？

或者删除h标签，或者删除上行的标签

## 浏览器及版本号

Google Chrome  版本 94.0.4606.54（正式版本） （64 位）

## wangEditor 版本

"wangeditor": "^3.1.1"

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

光标直接对着h标签的最前面删除后，审查元素看下h标签没有了，剩下p标签带着span

**Comment by aluyi** [comment]
这个问题我也遇到了。
<h1 id="y4dkd"><br></h1>(光标在此处)<p data-we-empty-p="">内容</p>
点击删除后变为
<h1 id="y4dkd"><span style="font-size: 16px; color: rgba(0, 0, 0, 0.65);">内容</span><br></h1>
虽然初看没什么问题，但是放在h1中的行高就变了，而且字体颜色也不是黑色了。
我觉得如果这个时候点击删除，应该把前面一行的内容删掉，直接变成
<p data-we-empty-p="">内容</p> 就合理了。
目前只能靠用户手动把上一行的标题h1模式关掉，改成正文p模式，再删除。才会正常，所以用户反馈操作麻烦。

版本4.7.9

**Comment by aluyi** [comment]
这个问题我也遇到了。
< h1 id="y4dkd">< br >< /h1>(光标在此处)< p data-we-empty-p="">内容< /p>
点击删除后变为
< h1 id="y4dkd">< span style="font-size: 16px; color: rgba(0, 0, 0, 0.65);">内容</ span>< br >< /h1>
虽然初看没什么问题，但是放在h1中的行高就变了，而且字体颜色也不是黑色了。
我觉得如果这个时候点击删除，应该把前面一行的内容删掉，直接变成
< p data-we-empty-p="">内容< /p> 就合理了。
目前只能靠用户手动把上一行的标题h1模式关掉，改成正文p模式，再删除。才会正常，所以用户反馈操作麻烦。

版本4.7.9

**Comment by hou-zhe** [comment]
> 这个问题我也遇到了。 <H1 ID = “y4dkd”> <BR> </ H1>（光标在此处）<P数据我们空-P = “”>内容</ P> 点击删除后变为 < h1 id="y4dkd"><span style="font-size: 16px; color: rgba(0, 0, 0, 0.65);">内容</span><br></h1> 虽然初看没什么问题，但是放在H1中的行高就变了，而且字体颜色也不是黑色了。 我觉得如果这个时候点击删除，应该把前面一行的内容删掉，直接变成 <p个数据-我们空-p="">内容</p> 就合理了。现在 只能靠用户手动把标题上一行的标题h1模式关掉，改成正文p模式，再删除。才会正常，所以用户反馈操作麻烦。
> 
> 版本4.7.9
为什么要将上一行的h标签删除？
我想应该是把span内部样式洗掉，或者说完整删除span标签比较合适；
现在正在处理的就是监听删除时正则匹配所有带style的span标签，将其删除后重新赋值给txthtml，但现在有个问题是在赋值时使用html()，会造成光标返回最开始位置

**Comment by hou-zhe** [comment]
确实是只有谷歌webkit内核的存在这种问题，火狐就不会出现，但是火狐是在h标签的最后增加strong标签，webkit内核浏览器处理的话，在删除时dom操作removeAttribute删除style样式，或者removeChild删除span标签，新建dom使用block替换，或者直接值替换三种方式

**Comment by hou-zhe** [comment]
好的，最后一次记录一下，光标问题，替换问题
append可以对dom追加字符串且不会造成光标移动
在删除span这个dom节点前，将innertext值取出，append到p标签里，删除span dom
ok

**Comment by rsl140** [comment]
> 好的，最后一次记录一下，光标问题，替换问题 append可以对dom追加字符串且不会造成光标移动 在删除span这个dom节点前，将innertext值取出，append到p标签里，删除span dom ok

那这边关闭issue了
