### ISSUE TITLE
从PPT文件中复制内容到编辑器出现大量空白行

### ISSUE THREAD

**Issue by ju7-mo** [wangeditor-team/wangEditor#3678]
## bug 描述

从PPT文件中复制内容到编辑器出现大量多余空白行。

## 你预期的样子是？

格式和PPT中保持一致，不要出现多余空白行。

## 浏览器及版本号

94.0.4606.61（Official Build） （x86_64）

## wangEditor 版本

4.7.9

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一:  创建一个PPT文件并输入任意段落内容。
- https://gyazo.com/027192d1ee17499ea8650da3cec411f9
- 
- 步骤二:全选复制PPT中内容到编辑器，粘贴后F12查看网页元素（此时可以观察到多余P标签）。
- https://gyazo.com/944a97c3bf930783ba9989bdcc99b4fe
- 
- 步骤三：使用editor.txt.html() 方法获取编辑器中的内容（此时p标签中有多余空白行）。
- https://gyazo.com/55a4c63cea509aab3b6e174c17eaf83b

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
