### ISSUE TITLE
在react环境下，使用上传视频自定义插入视频后，对视频点击播放暂停，报错

### ISSUE THREAD

**Issue by wansuiasdn** [wangeditor-team/wangEditor#3679]
## bug 描述

在富文本区域播放暂停视频报错
![图片](https://user-images.githubusercontent.com/47979542/138684410-81de5ee7-0117-4b98-bc0a-baba7985fb47.png)
![图片](https://user-images.githubusercontent.com/47979542/138684461-c0a1fd29-e711-4338-b670-6bb7dee3ae50.png)

## 你预期的样子是？

点击后可以像图片一样拉伸大小？至少别异常。。

## 浏览器及版本号

firefox 最新的

## wangEditor 版本

wangeditor@4.7.4

## 官网能否复现该 bug ？

不能 ，官网没法上传视频到服务器

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 上传视频到服务器并自定义video标签插入到光标处
- 步骤二 在富文本框内播放暂停视频
- 步骤三 等待bug lol

**Comment by a835100635** [comment]
![2021-11-05 10-11-42 2021-11-05 10_13_35](https://user-images.githubusercontent.com/65208676/140447100-56a7f2a6-91ca-4340-b66a-1a1cd8d27cfd.gif)
![2021-11-05 10-08-07 2021-11-05 10_12_45](https://user-images.githubusercontent.com/65208676/140447134-767f2956-70a6-4d6f-a5ba-cfde21d142e4.gif)
![image](https://user-images.githubusercontent.com/65208676/140447159-996bde31-a9be-40be-8294-f89d0d77398b.png)
![image](https://user-images.githubusercontent.com/65208676/140447179-ac3bd915-c459-4c87-b074-e9a417ef3c68.png)
并没有复现

**Comment by a835100635** [comment]
检查一下插入标签时的代码是否按照规则来插入的

**Comment by wansuiasdn** [comment]
感谢，我这边确认一下

**Comment by wansuiasdn** [comment]
@a835100635 感谢，除火狐浏览器外，更换其他浏览器貌似没有该异常提示，

**Comment by rsl140** [comment]
那这边先关闭该问题了
