### ISSUE TITLE
建议增加删除图片/视频事件钩子

### ISSUE THREAD

**Issue by yuner523** [wangeditor-team/wangEditor#3682]
## 功能描述

 *建议增加删除图片/视频事件钩子，返回被删的图片/视频的url，方便删除服务器文件*

## 提炼几个功能点

-编辑区域删除文件（目前是图片和视频）后，返回被删除的文件urls数组

## 可参考的案例
[编辑区域的事件钩子](https://www.wangeditor.com/doc/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/06-%E7%BC%96%E8%BE%91%E5%8C%BA%E5%9F%9F%E7%9A%84%E4%BA%8B%E4%BB%B6%E9%92%A9%E5%AD%90.html?h=%E5%88%A0%E9%99%A4)
// function showLinkTooltip() { /* 显示 tooltip */ }
// 点击链接元素是，显示 tooltip
editor.txt.eventHooks.linkClickEvents.push(showLinkTooltip)

**Comment by wangfupeng1988** [comment]
这种钩子加了没用。删除图片之后还可以 undo ，undo 之后还可以 redo ，你无法实时的去删除服务器文件。

想要清理服务器冗余文件，只能在用户关闭编辑器时，全局的对比、删除。

**Comment by yuner523** [comment]
感谢大佬的回答。目前项目中就是这样做的，编辑过程中产生的文件都记录下来，关闭编辑时再做差集删除。但是感觉略显麻烦，每个项目使用富文本时都要重写或copy一遍删文件相关的代码；如果在退出编辑时提供一个获取需要删除的文件列表函数，就太完美了。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
