### ISSUE TITLE
有没有什么办法可以把图片上传之后的回显可以提供一个api，比如一个html字符串来让我们控制图片样式和结构

### ISSUE THREAD

**Issue by lijianhong123** [wangeditor-team/wangEditor#3684]
1. 现在想要回显之后加入一个x的icon点击删除，而且把图片和文字相分开，图片固定在下面，而文字在上面。感觉如果可以控制插入进去的元素的话可以方便一下，请教一哈 这种情况有什么好的解决方法吗

**Comment by rsl140** [comment]
请按issue模板提交内容，否则不予受理
