### ISSUE TITLE
插入代码选择语言后再次插入，语言默认还是第一栏

### ISSUE THREAD

**Issue by Kevincodog** [wangeditor-team/wangEditor#3685]
## 问题描述

插入代码选择语言后再次插入，语言默认还是第一栏，需要重新切换

## wangEditor 版本

v4

## 是否查阅了文档 ？

是，文档未提及

## 最小成本的复现步骤
1、插入代码，默认是SQL语言，选择JAVA语言
2、再次插入，默认还是SQL语言而不是刚刚选择的JAVA语言

**Comment by rsl140** [comment]
你好，目前没有记忆功能

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
