### ISSUE TITLE
想要dark mode

### ISSUE THREAD

**Issue by wszdhxh** [wangeditor-team/wangEditor#3688]
## 功能描述

后台要亮和暗两个版本的, 希望编辑器能支持

## 提炼几个功能点

黑暗模式

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
暂时不支持 dark mode
可以先自己去定义 css
