### ISSUE TITLE
插入js代码块，方法名称使用中文输入法拼音，回车输入时出现重复内容

### ISSUE THREAD

**Issue by SmartWuJun** [wangeditor-team/wangEditor#3689]
## 插入js代码块，先写方法体最后， 方法名称使用中文输入法拼音，回车输入时出现重复内容

function ceshiceshi(){
}

## 你预期的样子是？

function ceshi(){
}

## 浏览器及版本号

浏览器 chrome 95

## wangEditor 版本
5.0

https://www.wangeditor.com/demo/zh-CN/

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 官网
- 插入代码块 javascript
- 首先插入内容  function (){}
- 在输入法 切换到中文， 在() 前面 插入 ceshi 拼音 然后回车 ，出现两个 ceshiceshi

**Comment by wangfupeng1988** [comment]
你是哪个输入法。我用 mac 自带中文输入法没有复现。

**Comment by rsl140** [comment]
我也未复现该问题

**Comment by SmartWuJun** [comment]
我这100%复现 额

发自我的iPhone

**Comment by SmartWuJun** [comment]
﻿我这100%复现 额

发自我的iPhone

**Comment by rsl140** [comment]
你这个是V5的issue的嘛 建议到[v5](https://github.com/wangeditor-team/wangEditor-v5/issues)进行提问
