### ISSUE TITLE
Bug Report ( Security issue discussion )

### ISSUE THREAD

**Issue by ShellInjector** [wangeditor-team/wangEditor#3690]
Dear Support,

You told us that this vulnerability will be fixed on V5 . can you please validate the issue first ?

Link to the report --> https://huntr.dev/bounties/4a27716e-4490-415d-a301-616765e4265d/

**Comment by wangfupeng1988** [comment]
Link error 403

**Comment by ShellInjector** [comment]
No! maybe you just need to create an account on this platform first

**Comment by ShellInjector** [comment]
here is a same one --> https://github.com/wangeditor-team/wangeditor/issues/3634

**Comment by ShellInjector** [comment]
Any updates here!

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
