### ISSUE TITLE
Word复制文本格式问题

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#3691]
## 问题描述

Word里的文本有段落（每个段落前都空2个格，一个段落如果有多行的话，只有第一行空2个格），复制到编辑器里就没有段落了，全部都顶格了，如果全选然后缩进就全都缩进，体现不出来段落了。没有首行缩进功能

## wangEditor 版本

最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
  在Word里编辑几段有段落的文字，前边空2个格，一个段落如果有多行，只需要第一行有空格
- 步骤二
将Word里编辑好的文字全选，然后复制粘贴到编辑器里
- 步骤三
官网可以体现出来。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
