### ISSUE TITLE
editor.config.showLinkVideo = false 设置无效

### ISSUE THREAD

**Issue by LChao05** [wangeditor-team/wangEditor#3692]
## bug 描述

*editor.config.showLinkVideo = false 设置无效，还是无法隐藏*

## 你预期的样子是？

*editor.config.showLinkImg = false 和这个效果一样*

## 浏览器及版本号

 *chrome  95.0.4638.69*

## wangEditor 版本

*4.6.16*

## 官网能否复现该 bug ？

能
### 
## 最小成本的复现步骤

const E = window.wangEditor;
const editor = new E("#toolbar-container", "#text-container");
editor.config.showLinkImg = false;
editor.config.showLinkVideo = false;
editor.create();

**Comment by rsl140** [comment]
如果你是不想要上传图片和视频的功能的话 建议使用 editor.config.menus 这个只是去除网络连接的方式

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
