### ISSUE TITLE
建议增加文字、图片、视频的拖拽功能

### ISSUE THREAD

**Issue by LvCoding112** [wangeditor-team/wangEditor#3696]
## 功能描述

可以在编辑器内将文本、视频、图片拖拽至任意位置
## 提炼几个功能点

- 功能1：拖拽视频
- 功能2：拖拽图片
- 功能3：拖拽文本

## 原型图

和v5的拖拽功能一致

## 可参考的案例

wangeditor v5

**Comment by UltramanWeiLai** [comment]
为何不直接用 v5 ？

**Comment by LvCoding112** [comment]
目前已经到生产环境了，没有办法替换了

**Comment by zxueliang** [comment]
V5插入表格后，上边空出来一行。
在官网 首先插入一个表格，上边会空出来一行
官网可体现

**Comment by LvCoding112** [comment]
> V5插入表格后，上边空出来一行。 在官网 首先插入一个表格，上边会空出来一行 官网可体现
是不是回复岔了

**Comment by rsl140** [comment]
v4 这边的目前只做维护了 新功能暂时不会添加了

**Comment by LvCoding112** [comment]
了解了

**Comment by Mowmowj** [comment]
> 



> v4 这边的目前只做维护了 新功能暂时不会添加了

请问V5怎么用拖拽呢

**Comment by wangfupeng1988** [comment]
现在支持文字、图片拖拽，你可以试试官网 demo
