### ISSUE TITLE
Vue项目中多个地方引用相同组件，该组件使用了富文本编辑器，但只有第一次使用组件时富文本才显示，其他都不显示

### ISSUE THREAD

**Issue by fhx10012091** [wangeditor-team/wangEditor#3698]
## 问题描述

ue项目中多个地方引用相同组件，该组件使用了富文本编辑器，但只有第一次使用组件时富文本才显示，其他都不显示

## wangEditor 版本

4.7.9

## 是否查阅了文档 ？

是，项目中使用的是vue3，写法是option Api

## 最小成本的复现步骤

- vue3
- option Api 写法，非setup
- mounted中初始化
- 问题一，不支持ref，造成已初始化，不能每调用一次组件就初始化一个相同组件
- 问题二，该组件为公共组件，如果页面同时存在两个组件，会报错
- 问题三，当组件销毁时，我也使用destory api进行销毁，但是报错Cannot read properties of undefined (reading 'previousElementSibling')

**Comment by wansuiasdn** [comment]
。。。你是实例化了一个编辑器用了三遍，不是实例化了三个编辑器各用各的

**Comment by fhx10012091** [comment]
> 。。。你是实例化了一个编辑器用了三遍，不是实例化了三个编辑器各用各的

是的

**Comment by rsl140** [comment]
建议每次使用都实例化
