### ISSUE TITLE
删空编辑器内内容时，使用中文输入法，编辑器会吞字符（在官网示例中已复现）

### ISSUE THREAD

**Issue by chanjuanmoon** [wangeditor-team/wangEditor#3703]
## bug 描述

*删空编辑器内内容时，使用中文输入法，编辑器会吞字符*

## 你预期的样子是？

*正常输入字符*

## 浏览器及版本号

*浏览器chrome 95.0.4638.69 *

## wangEditor 版本

*版本：v4.7.9  *

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 删空编辑器内内容时，使用中文输入法(我使用的是搜狗)，编辑器会吞字符

**Comment by rsl140** [comment]
未复现该问题

**Comment by LvCoding112** [comment]
我这边也出现这个bug了，百分百复现，初始编辑器内容为空时，输入（使用搜狗输入法）汉字，打的拼音首字母会被吞掉，但是输入过内容的编辑器哪怕清空后也不出出现这个bug

**Comment by LvCoding112** [comment]
![image](https://user-images.githubusercontent.com/45002318/141076405-297b15b2-1dae-4732-9699-1a62898df892.png)

**Comment by LvCoding112** [comment]
@rsl140

**Comment by rsl140** [comment]
> @rsl140

先确认下 你的版本是4.7.9么 ？

**Comment by LvCoding112** [comment]
是的，版本4.7.9
![image](https://user-images.githubusercontent.com/45002318/141090639-cfcbd401-2675-4367-8204-aa5095841173.png)

**Comment by vologo** [comment]
我也遇到这个问题。用的搜狗输入法，win 和mac 平台均有该问题

**Comment by rsl140** [comment]
复线方式：一初始化编辑框，什么操作都不要做，切换到中文输入法，

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
