### ISSUE TITLE
wangEditor无法二次加载内容,以及无法使用.destroy()

### ISSUE THREAD

**Issue by simborgem** [wangeditor-team/wangEditor#3705]
## 问题描述
1. 我需要二次加载内容, 新内容在老内容后面, 老内容因为已经生成了editor, 控制台报错: 已生成组件无法再次生成,导致后续加载的新内容都无法展示出来;
2. 查阅文档后使用destroy, 控制台也直接报警告.destroy() is not Function.

*请输入遇到的问题...*
1. .destroy()无法使用
2. new E 无法覆盖原有组件

## wangEditor 版本
^4.7.9
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
没看懂，你是想要干什么？

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
