### ISSUE TITLE
在插入的图片直接enter换行输入文本，显示的文本错误

### ISSUE THREAD

**Issue by Josephineisis** [wangeditor-team/wangEditor#3706]
![image](https://user-images.githubusercontent.com/23067473/140898981-d498a2a2-6e4f-4554-b6bb-a307dde765af.png)
在编辑器中插入图片，图片对应行p标签font-size:0;图片换行后在上方插入图片，上方的行p标签font-size也为0，但输入文字因为有编辑器样式中写定的最高权重样式，编辑器内展示的字号是16px，实际应为0px

**Comment by rsl140** [comment]
不明白你想表述什么，font-size:0这个是浏览器的一个默认操作行为。
实际上 我认为让文字显示出来 是符合逻辑的

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
