### ISSUE TITLE
复制一段文本，在编辑器中连续多次黏贴文本时，部分文本无p标签包裹

### ISSUE THREAD

**Issue by nickel1991** [wangeditor-team/wangEditor#3707]
## bug 描述

*复制一段文本，在编辑器中连续多次黏贴文本时，部分文本无p标签包裹*

## 你预期的样子是？

*希望能有标签包裹*

## 浏览器及版本号

*chrome 95.0.4638.69*

## wangEditor 版本

*V4.7.8*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 随意复制一段文本
- 步骤二
- 在富文本中多次黏贴，每次黏贴结束后，不移动光标，继续黏贴
- 步骤三
- 页面显示部分文本无样式

**Comment by rsl140** [comment]
个人认为逻辑上是没有问题的，没有移动光标则表示在该内容后面继续添加文本内容。

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
