### ISSUE TITLE
选中段落设置行高，最后一行的内容会被重复添加

### ISSUE THREAD

**Issue by 2395968228** [wangeditor-team/wangEditor#3708]
## bug 描述

选中段落设置行高，最后一行的内容会被重复添加

## 你预期的样子是？

只设置行高，不要添加对于的字符

## 浏览器及版本号

Chrome 71.0.3578.98 和 Firefox。普遍存在

## wangEditor 版本

最新版本

## 官网能否复现该 bug ？

能，看截图操作

## 最小成本的复现步骤

看下方两个截图：
行高设置前-截图1
![image](https://user-images.githubusercontent.com/13842626/141255051-26d16e43-e4aa-41aa-8dfc-5ab1607e9cde.png)

行高设置后-截图2
![image](https://user-images.githubusercontent.com/13842626/141255222-b59776c4-b84b-486e-8446-ef098998ce3d.png)

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
