### ISSUE TITLE
字号太大时背景色遮不完字体

### ISSUE THREAD

**Issue by guxing1992** [wangeditor-team/wangEditor#3709]
![11](https://user-images.githubusercontent.com/18378939/141267212-84b093c3-eb45-4c88-b395-9625a2232e21.png)
如图画线部分选中的48px字体的背景色

**Comment by guxing1992** [comment]
![11](https://user-images.githubusercontent.com/18378939/141266990-5a56be5a-c4e8-4539-951c-d2e802454faa.png)
如图横线部分选择的48px字体加背景色

**Comment by rsl140** [comment]
未复现该问题，其次，请按issue模板提交问题，否则不予受理的

**Comment by guxing1992** [comment]
font-size设置48px，背景任意颜色
