### ISSUE TITLE
对 WangEditor 提出几个建议。

### ISSUE THREAD

**Issue by koibi2** [wangeditor-team/wangEditor#3710]
## 问题描述

公司使用 WangEditor 时，遇到几个问题，提出建议。

## wangEditor 版本

最新 4.7.9

## 是否查阅了文档 ？

*是*

## 建议内容

这是我们家产品给出的原型：
![image](https://user-images.githubusercontent.com/34370367/141283441-7ac2d253-a1ed-4376-81eb-dd91fa8cac0a.png)

wangEditor 不支持这几点：
1. 不支持格式刷（清除格式功能）。
WangEditor 正在开发，版本5可能会支持。
https://github.com/wangeditor-team/wangEditor/issues/2528#issuecomment-898812235

2. 不支持自定义图标。
WangEditor 不支持，且不打算支持。
https://github.com/wangeditor-team/wangEditor/issues/2278#issuecomment-707094466

3. 不支持菜单分隔符。
插入“自定义菜单” 无法实现，正在想办法。
https://github.com/wangeditor-team/wangEditor/issues/1740#issue-363378183
https://github.com/wangeditor-team/wangEditor/issues/902

希望（尽早）支持，在功能实现上超越 Quill 。

**Comment by wangfupeng1988** [comment]
第三条 V5 已经支持。
前两条 V5 都会慢慢支持起来，根据优先级持续开发。

V4 不会再做功能调整了。
