### ISSUE TITLE
疑似文档错误

### ISSUE THREAD

**Issue by ShangTX** [wangeditor-team/wangEditor#3713]
## 问题描述

视频上传的文档疑惑

## wangEditor 版本
4.7.6
关于限制大小配置项的描述为
editor.config.uploadVideoMaxSize = 1 * 1024 * 1024 * 1024 // 1024m
实际使用发现大小限制为10M的话，这样配置才生效
editor.config.uploadVideoMaxSize = 10 * 1024 // 1024m
我不清楚

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤
实际上传即可
![微信截图_20211112105741](https://user-images.githubusercontent.com/25798245/141401495-028e5e5c-0485-4f87-9ed2-125292bf7ed3.png)

**Comment by windExplorer** [comment]
你是不是文档看错地方了。[看这里](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/02-%E9%99%90%E5%88%B6%E5%9B%BE%E7%89%87%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)

**Comment by ShangTX** [comment]
> 你是不是文档看错地方了。[看这里](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/02-%E9%99%90%E5%88%B6%E5%9B%BE%E7%89%87%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)

我看的是上传视频那个部分的限制大小，[这个地方](
https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E8%A7%86%E9%A2%91/02-%E9%99%90%E5%88%B6%E8%A7%86%E9%A2%91%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)

**Comment by windExplorer** [comment]
> > 你是不是文档看错地方了。[看这里](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/02-%E9%99%90%E5%88%B6%E5%9B%BE%E7%89%87%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)
> 
> 我看的是上传视频那个部分的限制大小，[这个地方](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E8%A7%86%E9%A2%91/02-%E9%99%90%E5%88%B6%E8%A7%86%E9%A2%91%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)

好吧，是我眼拙，看漏了，抱歉

**Comment by rsl140** [comment]
> > > 你是不是文档看错地方了。[看这里](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/02-%E9%99%90%E5%88%B6%E5%9B%BE%E7%89%87%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)
> > 
> > 
> > 我看的是上传视频那个部分的限制大小，[这个地方](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E8%A7%86%E9%A2%91/02-%E9%99%90%E5%88%B6%E8%A7%86%E9%A2%91%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)
> 
> 好吧，是我眼拙，看漏了，抱歉

那这边关闭该issue了~

**Comment by windExplorer** [comment]
> > > > 你是不是文档看错地方了。[看这里](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/02-%E9%99%90%E5%88%B6%E5%9B%BE%E7%89%87%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)
> > > 
> > > 
> > > 我看的是上传视频那个部分的限制大小，[这个地方](https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E8%A7%86%E9%A2%91/02-%E9%99%90%E5%88%B6%E8%A7%86%E9%A2%91%E5%A4%A7%E5%B0%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html)
> > 
> > 
> > 好吧，是我眼拙，看漏了，抱歉
> 
> 那这边关闭该issue了~

你回复错人了。
