### ISSUE TITLE
颜色增加拾色器功能

### ISSUE THREAD

**Issue by areyoukillme** [wangeditor-team/wangEditor#3714]
## 功能描述

*字体颜色和背景色颜色数组不能满足要求*

## 提炼几个功能点

- 字体颜色和背景色可以使用拾色器选择颜色

## 原型图

*参考element-ui 拾色器下面可以设置自定义颜色*

## 可参考的案例

*quill*

**Comment by rsl140** [comment]
该问题已收录，请移步到 #2529 进行跟踪
