### ISSUE TITLE
> > > 可以试着把 `new E('#editor')` 放到 `onMounted` 内

### ISSUE THREAD

**Issue by NeoZephyr** [wangeditor-team/wangEditor#3715]
> > > 可以试着把 `new E('#editor')` 放到 `onMounted` 内
> > 
> > 
> > 我在vue2 项目中也遇到了同样的问题，调用的方法是写在mounted 中的，但仍然报同样的错。尝试将调用放在settimeout 回调中， 请问可能是什么原因呢？
> > ```
> >   mounted() {
> >         const editor = new E('#editor');
> >         editor.create();
> >     }
> > ```
> 
> 主要原因是需要创建编辑器的节点未被渲染，除了生命周期外也有可能是：选择的节点在组件内但组件未被渲染、节点外层有v-if，可以用原生的dom选择方法去确认目标是否能在创建阶段被获取到

谢谢，问题已解决。原因确实如你所言，我用于创建编辑器的节点在el-dialog 的插槽中，el-dialog 可能出于性能优化的原因，插槽里的内容做了懒加载，导致该节点在初始化的时候，未被获取到，所以编辑器创建失败。

_Originally posted by @HuRuilin in https://github.com/wangeditor-team/wangEditor/issues/3443#issuecomment-966940534_

**Comment by NeoZephyr** [comment]
怎么解决的啊，我也遇到这个问题了，而且我的那个 div 在 ant 的 modal 表单里面，就算是在 onMounted 里面去 create 还是会有问题，因为modal 没有打开，然后没有渲染，就找不到

**Comment by HuRuilin** [comment]
> 怎么解决的啊，我也遇到这个问题了，而且我的那个 div 在 ant 的 modal 表单里面，就算是在 onMounted 里面去 create 还是会有问题，因为modal 没有打开，然后没有渲染，就找不到
> 
> 就是我发现是因为 modal 根本没有显示，我去 new E("#editor") 就获取找不到那个节点，这个该怎么办呢?

你可以尝试自定义一个组件，在自定义组件的mounted钩子函数里边儿，去初始化编辑器。然后在在modal 里面，使用自定义的组件。这样做可以保证，创建富文本编辑器的时候，dom 是已经存在的。

**Comment by rsl140** [comment]
抱歉，请按issue模板提交内容，否则这边是不予受理的

**Comment by HuRuilin** [comment]
> > 怎么解决的啊，我也遇到这个问题了，而且我的那个 div 在 ant 的 modal 表单里面，就算是在 onMounted 里面去 create 还是会有问题，因为modal 没有打开，然后没有渲染，就找不到
> > 就是我发现是因为 modal 根本没有显示，我去 new E("#editor") 就获取找不到那个节点，这个该怎么办呢?
> 
> 你可以尝试自定义一个组件，在自定义组件的mounted钩子函数里边儿，去初始化编辑器。然后在在modal 里面，使用自定义的组件。这样做可以保证，创建富文本编辑器的时候，dom 是已经存在的。

element-ui 中  Dialog 的内容是懒渲染的，即在第一次被打开之前，传入的默认 slot 不会被渲染到 DOM 上。因此，如果需要执行 DOM 操作，或通过 ref 获取相应组件，请在 open 事件回调中进行。
