### ISSUE TITLE
从其他地方复制的富文本插入超链异常

### ISSUE THREAD

**Issue by trtrtr6** [wangeditor-team/wangEditor#3716]
## bug 描述

从其他地方复制过来的富文本，然后选中一部分文本插入超链，会出现卡死、不生效、部分文本丢失等着各种情况

## 你预期的样子是？

预期是超链插入功能正常，可以参考tinymce这个编辑器（他家的没啥问题）

## 浏览器及版本号

任何浏览器及版本

## wangEditor 版本

4.6.15

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
- 随便找一篇网络文章复制到wangEditor中
- 然后选中一段文本插入超链

**Comment by Gavin-yh** [comment]
![image](https://user-images.githubusercontent.com/40813001/141924418-447c7f22-2382-45a8-865e-f71505d09b4f.png)
官网能复现吗

**Comment by rsl140** [comment]
建议更新到最新版本后尝试，我记得好像修复过该问题

**Comment by trtrtr6** [comment]
@Gavin-yh 可以复现  最简单的场景，给p标签包裹一个div，然后再插入超链，就能复现
![image](https://user-images.githubusercontent.com/17608015/142127479-ed89d507-6a13-4273-a616-711e134084fd.png)
插入后的富文本结构异常
![image](https://user-images.githubusercontent.com/17608015/142127560-a8af20ba-6e91-41df-9313-f664c78dcec6.png)

**Comment by rsl140** [comment]
复制粘贴这部分的逻辑比较复杂，需要花大量的时间进行整理，改进，所以目前可能没办法快速修复该类问题。复制粘贴的相关问题会收录在 #3260 进行跟踪 ，之后的话 可以移步到 #3260 进行进度查看

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
