### ISSUE TITLE
自定义的元素无法嵌套显示

### ISSUE THREAD

**Issue by zjg2114** [wangeditor-team/wangEditor#3718]
## bug 描述
自定义的元素无法嵌套显示
![4FCE8EC3DC4251D4A7BB81ADE14D13CD](https://user-images.githubusercontent.com/44963328/142150764-211df56f-d167-4827-bc04-81631a17c3c3.jpg)
平铺的数据结构是可以正常运行的
![2E27EBC5FC478C26509EE4D292AC63E4](https://user-images.githubusercontent.com/44963328/142150845-9e3efd74-538f-4900-8caf-b124dbf08666.jpg)
在paragraph下嵌套variable 出错
![2D876C13524176A53504D8060B898034](https://user-images.githubusercontent.com/44963328/142150901-0c0405fd-ee5d-4479-93fd-ec7f2f451e2c.jpg)

## 你预期的样子是？
在paragraph下嵌套variable 正常显示

## 浏览器及版本号
chrome 94.0.4606.81
 Vue3

## wangEditor 版本

v5最新版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
elemToHtml.ts
 ```
import { Boot, IDomEditor, SlateElement } from "@wangeditor/editor";

function variableToHtml(elem: SlateElement, childrenHtml: string, editor: IDomEditor): string {
  return `<v>${childrenHtml}</v>`;
}
const conf = {
  type: "variable", 
  elemToHtml: variableToHtml
};
Boot.registerElemToHtml(conf);
```
------------------分割线---------------
renderElem.ts
```
import { h, VNode } from "snabbdom";
import { Boot, IDomEditor, SlateElement } from "@wangeditor/editor";

function fn(elem: SlateElement, children: VNode[] | null, editor: IDomEditor): VNode {
  const vnode = h("v", {}, children); // type: 'paragraph' 节点，即渲染为 <p> 标签
  return vnode;
}
const conf = {
  type: "variable", // 节点 type ，重要！！！
  renderElem: fn
};
Boot.registerRenderElem(conf);

- 步骤二
- const defaultContent = [
      {
        type: "paragraph",
        children: [
          { text: "一行文字" },
          {
            type: "variable",
            children: [{ text: "自定义" }]
          },
          { text: "二行文字" }
        ]
      }
    ];
- 步骤三
控制台报错
```
index.es.js:2269 Uncaught (in promise) Error: Cannot find a descendant at path [0,1] in node: {"children":[{"type":"paragraph","children":[{"text":"一行文字二行文字"}]},{"type":"variable","children":[{"text":"自定义文字"}]}],"operations":[{"type":"remove_node","path":[0,1],"node":{"type":"variable","children":[{"text":"自定义"}]}},{"type":"merge_node","path":[0,1],"position":4,"properties":{}}],"selection":null,"marks":null,"id":"wangEditor-4","isDestroyed":false,"isFullScreen":false,"history":{"undos":[[{"type":"remove_node","path":[0,1],"node":{"type":"variable","children":[{"text":"自定义"}]}},{"type":"merge_node","path":[0,1],"position":4,"properties":{}}]],"redos":[]}}
```

**Comment by wangfupeng1988** [comment]
inline 元素是需要手动定义的，参考 link 的 https://github.com/wangeditor-team/wangEditor-v5/blob/main/packages/basic-modules/src/modules/link/plugin.ts

![8619248F29C1781971F8134F81419F0F](https://user-images.githubusercontent.com/9583120/142169989-a310e9c1-0ade-4571-bdac-b0138f070299.jpg)
