### ISSUE TITLE
上传图片

### ISSUE THREAD

**Issue by xiaoZhang1011** [wangeditor-team/wangEditor#3720]
## bug 描述

*v5上传图片设置server不起作用*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
v5的相关问题请移步到[这里提交](https://github.com/wangeditor-team/wangEditor-v5/issues)
