### ISSUE TITLE
图片后面的文字被默认居中

### ISSUE THREAD

**Issue by iceshou** [wangeditor-team/wangEditor#3721]
## bug 描述

* 选则一张图片上传
* 将图片设置为居中
* 回车进入下一行
* 添加文字
* 文字会默认居中

## 你预期的样子是？

文字不居中

## 浏览器及版本号

* Google 95

## wangEditor 版本

最新版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

参照bug描述

**Comment by rsl140** [comment]
![image](https://user-images.githubusercontent.com/7655291/142757126-6ec56cc7-fb35-454c-941f-6022ef4978db.png)
未复现该问题

**Comment by iceshou** [comment]
1. 先添加图片
2. 将图片设为居中
3. 此时光标在图片后面，然后回车
4. 光标此时在下一行中间，默认居中了

ps: 如果你这里本地还是无法复现，可将邮箱提供，我发一段操作视频给你

![image](https://user-images.githubusercontent.com/5445667/142968769-ada07330-c3d7-450a-8cb6-215d30b33846.png)

**Comment by rsl140** [comment]
我这边的话 是回车后 光标会自动回到最左侧。 你的浏览器是谷歌95的版本是么？

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
