### ISSUE TITLE
从excel拷贝内容样式被过滤

### ISSUE THREAD

**Issue by SYZ0111** [wangeditor-team/wangEditor#3723]
我们会在excel填好内容，然后copy到编辑器。但是样式会被过滤掉，按照官方文档给的解决方案 已经设置了不要过滤样式，可是没有起作用。试了最新的 v5版本，v5中从excel中copy到编辑器的内容会被转为图片，不知道v5是否可以在保留样式的同时，内容依旧是表格呢？

**Comment by rsl140** [comment]
你好，请按issue模板提交问题，否则不予受理。如果是V5的问题 请移步到[这里](https://github.com/wangeditor-team/wangEditor-v5/issues)提交
