### ISSUE TITLE
在vue3中，隐藏部分Toolbar会失效

### ISSUE THREAD

**Issue by comxza** [wangeditor-team/wangEditor#3724]
## 问题描述
![image](https://user-images.githubusercontent.com/21981010/142802694-65d1cc2d-3e37-4178-a814-6fc594fc53df.png)
![image](https://user-images.githubusercontent.com/21981010/142802735-df1a7ae2-ff3a-44e5-b7b0-ff2b1d40cc7d.png)
*请输入遇到的问题...*
我想把insertImage 也就是网络图片按钮隐藏，仅保留上传图片，但是我如图设置  他并不生效
## wangEditor 版本
最新版 V5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
下载最新版本V5   在vue3中
- 步骤二
- 
![image](https://user-images.githubusercontent.com/21981010/142802982-95f1be2a-20cc-42d8-adc4-5185ab87d63c.png)
如此引入
- 步骤三
，即可发现

**Comment by wangfupeng1988** [comment]
移动到了这里 https://github.com/wangeditor-team/wangEditor-v5/issues/273
