### ISSUE TITLE
图片支持“块”和“内嵌”两种形式

### ISSUE THREAD

**Issue by FaeryQuest** [wangeditor-team/wangEditor#3725]
## 功能描述

*希望可以配置图片插入后的显示方式，块和内嵌，就是可以配置为图片上传完成后单独占一行，禁止内嵌*

## 提炼几个功能点

- 图片插入方式可配置

参考ckeditor5
https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageinsert-ImageInsertConfig.html#member-type

**Comment by wangfupeng1988** [comment]
感谢反馈。
不过需求会以后在 V5 中支持（不是现在，待V5 发布之后再做），V4 不再做改动了。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
