### ISSUE TITLE
工具栏编辑区域分离的情况下，编辑区域默认值会被默认加空行

### ISSUE THREAD

**Issue by xuliuzhu1834** [wangeditor-team/wangEditor#3726]
## bug 描述

*工具栏编辑区域分离的情况下，编辑区域默认值会被默认加空行(`<p><br ></p>`)*

## 你预期的样子是？

*编辑区域默认值会被默认值正确显示*

## 浏览器及版本号

*chrome 91*

## wangEditor 版本

*4.7.9*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

在线复现代码地址：
[https://codepen.io/30547352/pen/ExvJzxN](https://codepen.io/30547352/pen/ExvJzxN)

![企业微信截图_909626c6-eecf-45d5-a008-96f2404dcf1e](https://user-images.githubusercontent.com/8508762/142867480-a3d46db9-47b6-4ebe-8539-a4efd914247b.png)

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。

**Comment by guxing1992** [comment]
请问解决了吗，我也遇到这个问题，很棘手
