### ISSUE TITLE
npm无法下载@wangeditor/editor-for-vue@next和@wangeditor/editor

### ISSUE THREAD

**Issue by xuewangwang** [wangeditor-team/wangEditor#3728]
## bug 描述

包无法正常下载
![image](https://user-images.githubusercontent.com/69711985/142966803-5360127e-8eed-4565-aea9-072b4ecc73c1.png)

## 你预期的样子是？

正常下载

## 浏览器及版本号

chrome

## wangEditor 版本

最新版

**Comment by wangfupeng1988** [comment]
用 yarn 下载试试 https://www.wangeditor.com/v5/guide/installation.html

**Comment by wangfupeng1988** [comment]
用 yarn 下载试试 https://www.wangeditor.com/v5/guide/installation.html

**Comment by a835100635** [comment]
mac环境下：
清除npm缓存并设置npm默认源https://registry.npmjs.org/、执行npm i @wangeditor/editor --save、npm i @wangeditor/editor-for-vue@next --save，是可以成功的
![image](https://user-images.githubusercontent.com/65208676/142968320-b8b110e7-5a6b-4d80-983a-3b5a8c9710bd.png)

**Comment by a835100635** [comment]
![image](https://user-images.githubusercontent.com/65208676/142968872-858d7fb3-b15e-42a2-8af4-f6ab6d95bcc2.png)

**Comment by xuewangwang** [comment]
是npm版本的问题，7和8下载都是报错的，我回退到6就可以下载了
