### ISSUE TITLE
表格什么时候可以支持合并单元格呢

### ISSUE THREAD

**Issue by BENSHAKA** [wangeditor-team/wangEditor#3729]
## 插入表格支持合并单元格

*表格支持合并单元格*

- 表格支持合并单元格

*飞书*

**Comment by wangfupeng1988** [comment]
这个问题提的用户比较多，我早已记录下。
但是它非常麻烦，目前还没有精力做。
得使劲往后推迟一下了。业余开源项目，希望能理解。
