### ISSUE TITLE
支持表格的行列进行拉伸

### ISSUE THREAD

**Issue by 953921532** [wangeditor-team/wangEditor#3730]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
目前不支持。
这个问题早已记录下，但暂时没有精力开发。
业余开源项目，还请理解。
