### ISSUE TITLE
图片设置上传类型时的accept不正确

### ISSUE THREAD

**Issue by assd12138** [wangeditor-team/wangEditor#3731]
## bug 描述

上传图片时的accept设置错误
设置限制图片类型
```js
editor.config.uploadImgAccept = ['jpg']
```
accept属性变为`image/jpg`，这个不符合原生的限制规定，没法正确筛选，因为jpg类型是隶属于image/jpge下的，应当设置为拓展名格式.jpg，才可以正确筛选，我在stack over flow上搜到了[相关问题](https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg)

![image](https://user-images.githubusercontent.com/33787498/142998652-d5862a26-df55-4998-8a69-ce61ff8cb47b.png)

## 你预期的样子是？

设置editor.config.uploadImgAccept的时候，能正确的根据拓展名设置input的accept类型

## 浏览器及版本号

chrome  98.0.4724.0（正式版本）canary （64 位）
任意现代浏览器均可复现

## wangEditor 版本

v5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤
[示例链接](https://7mx0e.csb.app/)
可以点击右下角open in codesandbox查看源码

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
