### ISSUE TITLE
事件钩子toolbarClickEvents，只有点击全屏时触发，点击其它菜单选项不触发

### ISSUE THREAD

**Issue by BENSHAKA** [wangeditor-team/wangEditor#3732]
## bug 描述

editor.txt.eventHooks.toolbarClickEvents.push(this.test)
使用该方式自定义钩子函数，但是只有在点击全屏的菜单选项时才触发

## 你预期的样子是？

*想要点击每个菜单选项进行触发，并可以回传菜单选项类型值*

## 浏览器及版本号

*chrome 95.0.4638.69*

## wangEditor 版本

*4.7.4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 定义test函数，函数内编写console.log
- editor.txt.eventHooks.toolbarClickEvents.push(test)进行触发
- 点击每个菜单，观察控制台看是否输出调试语句

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
