### ISSUE TITLE
从word里复制内容粘贴到文本框里,会多出两个span标签,切span标签带很长的style属性

### ISSUE THREAD

**Issue by lsai2270** [wangeditor-team/wangEditor#3733]
## 问题描述

*从word里复制内容粘贴到文本框里,会多出两个span标签,切span标签带很长的style属性*

## wangEditor 版本

*4.7.9*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一  yarn create umi myapp 选择ant-design-pro 、JavaScript、simple 、
- 步骤二  yarn add wangeditor 
- 步骤三 在项目工程/pages/Welocme.jsx加入如下代码
- 
![image](https://user-images.githubusercontent.com/32258110/143204656-6e9a4c4b-3073-423a-9ec5-7306244a500c.png)

- 在word中复制一段内容 在文本框中先打一个空格 然后粘贴内容 会出现如下问题
- 
![image](https://user-images.githubusercontent.com/32258110/143206362-cf1bd9cf-6d3c-4efc-ae8b-2cd0a072a2e5.png)

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
