### ISSUE TITLE
上传图片之后undo redo按钮失效，图片以及视频的tooltip菜单失效

### ISSUE THREAD

**Issue by Westdoorr** [wangeditor-team/wangEditor#3734]
## 问题描述

上传图片之后undo redo按钮失效，图片以及视频的tooltip菜单失效

## wangEditor 版本

4.7.9

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

其他项目也添加了wangEditor ，添加图片后功能都正常。
但是现在问题是不太能定位到为什么现在这个项目添加了图片后会出现undo redo按钮失效 以及图片和视频的tooltip菜单失效
想询问下开发者导致undo redo失效的问题可能是什么

**Comment by wangfupeng1988** [comment]
http://106.12.198.214:8881/dev/examples/upload-image.html 
demo 未复现这个问题，你可以参考 demo 源代码。
