### ISSUE TITLE
字体加粗b标签前后会填充span包装的&ZeroWidthSpace;导致后续文字无法使用样式

### ISSUE THREAD

**Issue by tzfun** [wangeditor-team/wangEditor#3735]
## 字体加粗b标签前后会填充span包装的&ZeroWidthSpace;导致后续文字无法使用样式

![N(QO}8H{7{~KTS)`OQYEIV3](https://user-images.githubusercontent.com/34815354/143212581-f3ede268-fd6c-4c4d-8b7d-b734bf4eb587.png)

![}5ITSEW(U4`$Q7K)`( X`R9](https://user-images.githubusercontent.com/34815354/143212553-5f8bb4dd-e200-4b47-8aba-caf7017b590b.png)

## 浏览器及版本号

*Chrome 95.0.4638.69（正式版本） （64 位）*

## wangEditor 版本

*4.7.9*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一：输入任意文字
- 步骤二：开启B加粗，输入任意文字
- 步骤三：关闭B加粗，输入任意文字，发现无法使用新样式

**Comment by wangfupeng1988** [comment]
demo 未复现该问题 http://106.12.198.214:8881/master/examples/
![image](https://user-images.githubusercontent.com/9583120/143797689-2ef50657-b23f-46b4-9075-a42bbe9dd279.png)

**Comment by tzfun** [comment]
刚刚试了下 demo中确实正常，但是官网的editor以及我本地最新版本editor都能复现。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 字体加粗b标签前后会填充span包装的&amp;ZeroWidthSpace;导致后续文字无法使用样式 (Issue #3735)





 
demo 未复现该问题 http://106.12.198.214:8881/master/examples/
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfupeng1988** [comment]
你可以再下载最新版本试试，demo 中的代码前段时间重新发布了（当时忘记回复你了）

**Comment by gamemock** [comment]
> 你可以再下载最新版本试试，demo 中的代码前段时间重新发布了（当时忘记回复你了）

使用了最新的4.7.10版本，该问题仍然存在。
而且官网首页的示例中也仍然存在该问题。
demo中不仅该问题已修正，切点击加粗按钮也能得到视觉回馈。请问demo中的版本什么时候可以上线呢？

**Comment by wangfupeng1988** [comment]
@gamemock demo 就是 master 代码的，按理说已经发布了，我再检查一下吧。
