### ISSUE TITLE
在 Firefox 中，使用 ctrl + a 全选后，修改文字对齐方式，文字对齐方式改变但是不触发 onChange事件

### ISSUE THREAD

**Issue by afruitfish** [wangeditor-team/wangEditor#3736]
## bug 描述

在 Firefox 中，使用 ctrl + a 全选后，修改文字对齐方式，文字对齐方式改变但是不触发 onChange事件

## 你预期的样子是？

在 Firefox 中，使用 ctrl + a 全选后，修改文字对齐方式，文字对齐方式改变且触发 onChange事件

## 浏览器及版本号

Firefox 94.0.2 (64 位)

## wangEditor 版本

4.7.6

## 官网能否复现该 bug ？

能 [官网demo](https://codepen.io/xiaokyo-the-bold/pen/abmNByX?editors=1111)

## 最小成本的复现步骤

- 步骤一
     输入任意内容
- 步骤二
    ctrl+a全选 使用工具栏的文字对齐方式改变对齐方式

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
