### ISSUE TITLE
插入表格时，能否限制列数

### ISSUE THREAD

**Issue by nickel1991** [wangeditor-team/wangEditor#3739]
## 问题描述

*插入表格时，能否限制列数*

## wangEditor 版本
v4.7.8

*插入表格时，能否限制列数*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤
 
（请告诉我们，如何**最快的**复现该问题？）

- 官网示例中点击插入表格按钮
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这个暂时不会支持。
如果你用了 V5 ，你可以自定义插件解决。V4 不支持这种插件。
