### ISSUE TITLE
建议给一个错误码表，可以自定义报错信息

### ISSUE THREAD

**Issue by xdoer** [wangeditor-team/wangEditor#3740]
## 功能描述
下面这是网站文档的 `customAlert` 的介绍，可以看到，用户只能拿到操作的状态 `success | info | ...` 和报错信息，而不能自定义错误输出，建议 customAlert 支持传入一个对象，包含操作状态，错误码，错误信息等。用户拿到错误码，可自定义错误信息，如果不想自定义，也可以使用你这里默认的。
![image](https://user-images.githubusercontent.com/22864183/143407836-c89bf83f-91a8-4ec6-b8d8-1f0edad9400c.png)

## 提炼几个功能点

- 错误码
- 修改 customAlert 方法

## 原型图
无

## 可参考的案例
无

**Comment by wangfupeng1988** [comment]
既然是展示给用户的，那还是以简洁的文字为主。操作状态，错误码，错误信息等，这些你可以集合到报错提示文字里。

**Comment by xdoer** [comment]
我的场景是想自定义一下上传本地图片的报错。错误产生的原因是源码中捕获的，比如图片太大什么的，源码中把这个错误信息整成了一个字符串，没办法进行自定义。

比如[这里的代码](https://github.com/wangeditor-team/wangEditor/blob/e07f9f549a7f47a34afc01d104c5108f5822b1ff/src/menus/img/upload-img.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L147)

**Comment by wangfupeng1988** [comment]
还是没明白你的问题，你预期的效果是什么？

**Comment by xdoer** [comment]
我简单写个 demo 吧

```ts
// 定义错误码映射
enum ErrorCode {
  ImgSizeLimit = 10001   // 10001 表示图片超出限定
}

// 操作状态
enum OpStatus {
  success = 'success',
  fail = 'fail'
}

// ========================= 这是源码里的图片大小校验

if(file.size > ImgMaxSize) {
  customAlert({
    code: ErrorCode.ImgSizeLimit,
    status: OpStatus.fail,
    message: '图片超过大小'   // 源码定义的错误信息
  })
}

// ========================= 这是用户配置的自定义 alert

function customAlert({ code, message, status }) {
  if(status === 'fail') {
   // 这里我根据 code, 可以知道错误原因是图片超过限制了
    if(code === 10001) {
     // 这里执行图片超过限制的逻辑
     window.location.href="https://www.baidu.com"
    }
  }
}
```

目前编辑器实现不了这样的效果。对开发者来说，只知道操作成功还是失败，错误信息是直接抛给用户的，开发者也掌握不了具体报错原因是什么。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
