### ISSUE TITLE
已关闭对粘贴样式的过滤了，从excel拷贝的内容样式依旧会被过滤

### ISSUE THREAD

**Issue by SYZ0111** [wangeditor-team/wangEditor#3744]
## 问题描述
已关闭对粘贴样式的过滤了，从excel拷贝的内容样式依旧会被过滤

## wangEditor 版本
4.4.0

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
1. 设置该属性 editor.config.pasteFilterStyle = false，关闭对粘贴样式的过滤
2. 从excel拷贝带样式的文字，会发现样式依旧会被过滤

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
