### ISSUE TITLE
V5文档 React使用 的用例里面，useEffect传少了个参数

### ISSUE THREAD

**Issue by DrRua** [wangeditor-team/wangEditor#3745]
## 问题描述

`// 及时销毁 editor ，重要！！！
    useEffect(() => {
        return () => {
            if (editor == null) return
            editor.destroy()
            setEditor(null)
        }
    }, [])`
useEffect 第二个参数是不是少传了个 editor？

## wangEditor 版本

v5

## 是否查阅了文档 ？

是

**Comment by wangfupeng1988** [comment]
是的，参考这里 https://juejin.cn/post/7030584414652334093#heading-3
感谢反馈~
