### ISSUE TITLE
插入代码块如何显示行数？

### ISSUE THREAD

**Issue by Liusiyuan-git** [wangeditor-team/wangEditor#3746]
## 问题描述
插入代码块如何显示行数？

## wangEditor 版本
V4

## 是否查阅了文档 ？

是，翻遍了，只讲了代码怎么高亮

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 就插入代码
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
目前不支持该功能。v4 v5 都不支持。
后面会陆续在 V5 中增加。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。

**Comment by ZhongChunle** [comment]
目前还是没有可以显示代码块的行号问题

**Comment by wangfupeng1988** [comment]
> 目前还是没有可以显示代码块的行号问题

暂不支持，后续有时间再优化
