### ISSUE TITLE
BUG 代码模块显示有问题

### ISSUE THREAD

**Issue by Liusiyuan-git** [wangeditor-team/wangEditor#3747]
## bug 描述

getJson 得到json, 用 setJson 反显示，代码模块中隐藏字符串 “<br” 等不生效

## 你预期的样子是？
getJson之前什么样子，setJson之后也是什么样子

## 浏览器及版本号

谷歌浏览器96最新版

## wangEditor 版本

v4

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  getJson 的到 Json
- 步骤二 用 setJson 输入 上面的Json
- 步骤三  看显示效果

**Comment by 86driver** [comment]
@Liusiyuan-git  能不能给个具体的案例， 比如 getjson是什么， setjson少了什么

**Comment by Liusiyuan-git** [comment]
@86driver 很简单的，你就点击代码标签，随便输入一段代码，比如 hello world：
我提供个go语言的吧：
package main

import "fmt"

func main() {
    ch := make(chan float64)
    ch <- 1.0e10    // magic number
    x, ok := <- ch
    defer fmt.Println(`exitting now\`)
    go println(len("hello world!"))
    return
}

然后getJSON 得到一段JSON
然后再把这段JSON，用setJSON 塞回去，看看样式有没有乱就ok了
你会发现，代码全都变成了一条，既没有换行，改被浏览器解析的html字符串，比如：“<br>” 也没有解析

**Comment by 86driver** [comment]
@Liusiyuan-git  你的意思是setjson 得到的是json字符串，而不是反转之后的代码块。

你想要的是 输入代码块 -> getJson得到json串 -> setJson之后应该看起来还是代码块那样， 而不是一堆字符串是吗

**Comment by 86driver** [comment]
@Liusiyuan-git  我觉得你可能想要的不是getJson/setJson，因为getJson/setJson做了转译， setJson出来的就是字符串。  你想要的那种效果或许可以用editor.txt.html()这个api。  如果我理解的有误， 再@我一下。 :smiley:

**Comment by Liusiyuan-git** [comment]
@86driver 有考虑过editor.txt.html()这个api，但我记得文档里提到过，用了editor.txt.html()之后就不能再对原来的进行再编辑了？比如说一个作者发布了一篇谈论代码的博客，发表之后他觉得有些代码块中的代码需要再改一下，这时候就需要让已发表的博客回到再编辑状态，只有setJSON能让博客回到再编辑状态吧？Html的话就只是展示用的。

**Comment by Liusiyuan-git** [comment]
@86driver 你想要的是 输入代码块 -> getJson得到json串 -> setJson之后应该看起来还是代码块那样， 而不是一堆字符串是吗
是的！

**Comment by Liusiyuan-git** [comment]
@86driver 我看了下代码的关于setJSON的逻辑，好像就是根据JSON里面的各种 tag, attr, value等等字段，重新拼接成html吧，在解析到纯字符串部分的时候，直接elem = document.createTextNode(item);变成文本了，没有再做额外处理

**Comment by Liusiyuan-git** [comment]
@86driver 我这边暂时做了一个小处理，把代码改成了：
elem = document.createElement("text");
elem.innerHTML = item
显示是正常了，就是不知道会不会有隐藏的其他问题，请大佬赐教

**Comment by 86driver** [comment]
@Liusiyuan-git   我晚点看一下

**Comment by 86driver** [comment]
@Liusiyuan-git  关于你说的那个编辑状态， 你只要发布肯定会保存一份html字符串给后端， 编辑的时候不就是 把那部分内容拿过来放在 editor区域(editor.txt.html('接口拿过来的数据')),   之后继续编辑就可以了吧。

**Comment by 86driver** [comment]
@Liusiyuan-git  没什么问题 这个issue我就关掉了哦。后续又问题记得艾特我
