### ISSUE TITLE
能否增加列表层级展示功能 （bulleted list） 

### ISSUE THREAD

**Issue by luxiaodui** [wangeditor-team/wangEditor#3748]
## 功能描述

用户想使用bulleted list功能,但是用户想呈现层级展示,比如第一级，第二级，使用Tab键可以完成,目前CKEditor支持这个功能

## 提炼几个功能点

- 点中<li>数据按下Tab键,可以转换成二级数据

## 原型图

没办法上传图片啊

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*https://ckeditor.com/ckeditor-5/demo/*

**Comment by wangfupeng1988** [comment]
这个问题我早已记录下。
不过目前没有精力开发，业余开源项目，还请体谅。
后面会慢慢的做起来。
