### ISSUE TITLE
何不增加一个删除图片回调

### ISSUE THREAD

**Issue by kx500** [wangeditor-team/wangEditor#3749]
## 功能描述

因为图片上传到服务器后，我会保存URL到数据库，以防止过多的垃圾文件，如果编辑器中删除了图片，我想在数据库中也同时删除

## 可参考的案例

 Tooltip.prototype.appendMenus = function () {
    var _this = this;

    var conf = this.conf;
    var editor = this.editor;
    var $targetElem = this.$targetElem;
    var $container = this.$container;
    (0, _forEach["default"])(conf).call(conf, function (item, index) {
      //
      var $elem = item.$elem;
      var $wrapper = dom_core_1["default"]('<div></div>');
      $wrapper.addClass('w-e-tooltip-item-wrapper ');
      $wrapper.append($elem);
      $container.append($wrapper); // 

      $elem.on('click', function (e) {
        e.preventDefault();
        var res = item.onClick(editor, $targetElem);
        if (res) {
            _this.remove();
            editor.config.removeImg($targetElem.selector);  //新增
        }
      });
    });
  };

## 调用编辑器的页面加入：

editor.config.removeImg = function (img) {
        console.log('remove', img)
}

**Comment by wangfupeng1988** [comment]
增加图片删除回调。你监听回调，如果图片删除，你就从服务器端删除图片文件，防止垃圾文件。对吧？
但是，如果刚删除完，又撤销了呢？撤销又重做了呢。重做又撤销了呢？—— 即，你不知道图片是啥时候有，啥时候没有。

建议你参考一下这个方法，虽然是 v5 的文档，但解决思路是一致的。
https://www.wangeditor.com/v5/guide/menu-config.html#%E8%8E%B7%E5%8F%96%E5%B7%B2%E5%88%A0%E9%99%A4%E7%9A%84%E5%9B%BE%E7%89%87

**Comment by kx500** [comment]
非常感谢您的回复，先前我的确是没想到这一点，您给的参考链接对我很有帮助，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月29日(星期一) 晚上7:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 何不增加一个删除图片回调 (Issue #3749)





 
增加图片删除回调。你监听回调，如果图片删除，你就从服务器端删除图片文件，防止垃圾文件。对吧？
 但是，如果刚删除完，又撤销了呢？撤销又重做了呢。重做又撤销了呢？—— 即，你不知道图片是啥时候有，啥时候没有。
 
建议你参考一下这个方法，虽然是 v5 的文档，但解决思路是一致的。
 https://www.wangeditor.com/v5/guide/menu-config.html#%E8%8E%B7%E5%8F%96%E5%B7%B2%E5%88%A0%E9%99%A4%E7%9A%84%E5%9B%BE%E7%89%87
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kx500** [comment]
麻烦您帮我看下，使用 editor.getElemsByType 获取图片时报错：
function formsubmit(){
		var imageList2 = editor.getElemsByType('image');
		console.log('imageList2', imageList2)
		
		return false;
	}

错误：
Uncaught TypeError: editor.getElemsByType is not a function

**Comment by wangfupeng1988** [comment]
@kx500 我说过了，给你的参考链接是 v5 的，而你现在用的是 v4 的，所以 API 肯定不能用。只是一个解决思路，具体代码要你自己实现。
