### ISSUE TITLE
输入中文的时候首字母无法转换

### ISSUE THREAD

**Issue by sannyin** [wangeditor-team/wangEditor#3751]
## bug 描述

在v4官网，将全部内容删除之后，输入文字 “测试” 首字母无法转移，若单次未出现可以多尝试两次。附（复现视频）
https://user-images.githubusercontent.com/42018360/143815621-b503da7b-4998-41b0-8950-69064b7fb2e7.mov

## 你预期的样子是？

可以正常输入

## 浏览器及版本号

谷歌 版本 93.0.4577.63（正式版本） (x86_64)

## wangEditor 版本

4.3.0

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
打开网址 https://www.wangeditor.com/
- 步骤二
删除里面内容
- 步骤三
输入 “测试” 如果正常输入，请删除之后重新输入。输入文字速度快一点。

**Comment by vologo** [comment]
![image](https://user-images.githubusercontent.com/65098722/143838709-5ad22fde-83f2-4e23-a9eb-109628ce8070.png)

**Comment by wangfupeng1988** [comment]
重复了 https://github.com/wangeditor-team/wangEditor/issues/3742
