### ISSUE TITLE
是否能够手动调用撤销api，或者自定义插入网络视频的模板？

### ISSUE THREAD

**Issue by wq758511990** [wangeditor-team/wangEditor#3752]
## wangEditor 版本
4.7.9

## 内容
现在插入网络视频链接，如果直接插入视频链接是不会在两边包裹video标签
目前我的做法是用提供的插入视频链接回调函数，在插入视频链接后，先调用document.execCommand("undo")，执行撤销，而后使用编辑器提供的editor.cmd.do("insertHTML")，插入视频，但是document.execCommand方法似乎随时可能被移除，故而有此问。

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
点击视频 - 输入链接 - 点确定，出来的只是链接字符串，

**Comment by wangfupeng1988** [comment]
如果你用 V4 ，不用担心 document.execCommand 会被移除的问题。
因为 V4 本身就是基于 document.execCommand 的，如果 document.execCommand 不能用了，那 V4 整体都不能用了。

而且，现在很多富文本编辑器都是基于 document.execCommand 的，浏览器不可能近期禁止掉 document.execCommand ，所以请放心使用即可。

**Comment by wangfupeng1988** [comment]
至于你说的“手动调用撤销api，或者自定义插入网络视频的模板”，这个不支持。
