### ISSUE TITLE
menus失效

### ISSUE THREAD

**Issue by moonlight418** [wangeditor-team/wangEditor#3761]
## 问题描述

*在模态框中使用该editor，menus点击无效，无法弹出对应的功能*

## wangEditor 版本

*4.7.10*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 直接在模态框中使用
- 步骤二
- 步骤三

**Comment by rsl140** [comment]
模态框是指？

**Comment by wangfupeng1988** [comment]
需要给出明确的复现步骤，帮助我们尽快复现问题。

**Comment by moonlight418** [comment]
![image](https://user-images.githubusercontent.com/57989938/144397825-96e5ad90-90d7-4cca-a7aa-0ae16ddbee12.png)
在bootstrap的模态框中使用，点击表情以及其它菜单都没反应

**Comment by moonlight418** [comment]
> 模态框是指？

image
在bootstrap的模态框中使用，点击表情以及其它菜单都没反应

**Comment by moonlight418** [comment]
> 模态框是指？

![image](https://user-images.githubusercontent.com/57989938/144398644-45df18f2-e9fd-4ff7-bb22-8ce406c7fee2.png)
在bootstrap模态框中使用，点击表情没有反应，其它菜单也没反应。

**Comment by moonlight418** [comment]
> 模态框是指？
![image](https://user-images.githubusercontent.com/57989938/144399172-14c0d4e2-d3de-4cf0-9889-addf3b431093.png)

在bootstrap模态框中使用，点击表情没有反应，其它菜单也没反应。

**Comment by moonlight418** [comment]
> 模态框是指？

1

**Comment by moonlight418** [comment]
> 模态框是指？

![image](https://user-images.githubusercontent.com/57989938/144399365-3a01301a-2d80-4925-b676-160321f13036.png)
在bootstrap模态框中使用，点击表情没有反应，其它菜单也一样
