### ISSUE TITLE
复制黏贴内容到编辑器，无法将内容中的图片复制到编辑器中

### ISSUE THREAD

**Issue by cced3000** [wangeditor-team/wangEditor#3762]
## 问题描述

从一个站点页面中，复制带有多张图片的图文内容信息，黏贴到编辑器中，图片信息无法黏贴到编辑器，文本信息没问题，图片被过滤掉。

复制内容的对象：

![image](https://user-images.githubusercontent.com/300924/144373513-525d1393-6290-400b-977d-106c7c33dd87.png)

复制到编辑器后的效果如下，图片丢失：

![image](https://user-images.githubusercontent.com/300924/144373394-29d8679a-b7b2-4865-a828-b4fba8492864.png)

## wangEditor 版本

wangEditor V5版本

## 是否查阅了文档 ？

查看了文档，没有发现相关配置选项，复制黏贴内容到编辑器，也没有触发图片上传请求，应该是编辑器直接过滤了，如果只复制图片就正常可以复制到编辑器里。

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 例如，打开网易新闻页面：https://www.163.com/dy/article/GQ73F9RR05118O8G.html，复制新闻资讯的正文内容（全部的图文信息）
- 步骤二  复制内容到wangEditor 编辑器。
- 步骤三

**Comment by wangfupeng1988** [comment]
v5 目前只支持粘贴纯文本，可已通过 customPaste 自定义 https://www.wangeditor.com/v5/guide/editor-config.html#custompaste

支持图文粘贴，近期会开发，需要一点时间

**Comment by wangfupeng1988** [comment]
另外，v5 的 issue 可以来这里提交 https://github.com/wangeditor-team/we-2021/issues
