### ISSUE TITLE
上传的图片用退格键删除一次会删掉两张

### ISSUE THREAD

**Issue by junfengZhang2018** [wangeditor-team/wangEditor#3763]
## bug 描述

上传的图片用退格键删除一次会删掉两张

## 你预期的样子是？

应只删掉一张

## 浏览器及版本号

ChromeV96

## wangEditor 版本

4.7.9

## 官网能否复现该 bug ？

没试过

## 最小成本的复现步骤

- 步骤一
- 上传本地图片两张，我是一张张上传的
- 步骤二
- 用退格键删除第二张

**Comment by wangfupeng1988** [comment]
官网未复现。

**Comment by junfengZhang2018** [comment]
刚刚去官网试了，官网会偶现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 上传的图片用退格键删除一次会删掉两张 (Issue #3763)





 
官网未复现。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cc138** [comment]
图片1后紧挨着图片2或文字，删除图片二或文字，图片1也会被删除

**Comment by wangfupeng1988** [comment]
> 图片1后紧挨着图片2或文字，删除图片2或文字，图片1也会被删除 之前提了这个bug [#3687 ](https://github.com/wangeditor-team/wangEditor/issues/3687)

那在这个 issue 跟踪吧，可能是一个 bug 。这个 issue 先关闭了。
