### ISSUE TITLE
上传多张图片后,点击图片定位有问题;

### ISSUE THREAD

**Issue by WzSepia** [wangeditor-team/wangEditor#3764]
## bug 描述

上传多张图片后(一行文字,一行图片),点击图片文档会发生滚动,无法定位到操作图片;

## 你预期的样子是？

点击哪个图片就定位到哪个图片,无文档滚动,设置弹窗应出现在正确位置;

## 浏览器及版本号

谷歌浏览器

## wangEditor 版本

V5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

第一行  输入一段文字;
第二行 上传一张图片;
第三行  输入一段文字;
第四行 上传一张图片;
...
以此类推;
点击图片就会复现问题;
<img width="1190" alt="截屏2021-12-03 下午3 36 01" src="https://user-images.githubusercontent.com/34569364/144565718-9ab4edf4-5190-463e-8cb0-885fd1072e7f.png">

## demo通道
[https://www.wangeditor.com/demo/zh-CN/](url)

**Comment by wangfupeng1988** [comment]
最新版本已经修复了，你试试吧
https://github.com/wangeditor-team/wangEditor-v5/issues/282

**Comment by WzSepia** [comment]
已修复
