### ISSUE TITLE
上传分辨率大的图片,在编辑器正常展示,但是展示其保存的html内容时,会超出展示文档;

### ISSUE THREAD

**Issue by WzSepia** [wangeditor-team/wangEditor#3765]
## bug 描述

上传分辨率大的图片,在编辑器正常展示,但是展示其保存的html内容时,会超出展示文档;

## 你预期的样子是？

和在编辑器展示大小一致;

## 浏览器及版本号

任何浏览器都能复现

## wangEditor 版本

V5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接上传个大分辨率图片就能复现;

## 样式文件存在这段代码,

`.w-e-text-container [data-slate-editor] img {`
`     cursor: default;`
`     max-width: 100%;`
`     min-height: 20px;`
`     min-width: 20px`
`}`

## 期望完善编辑元素大小的逻辑处理

**Comment by wangfupeng1988** [comment]
展示的时候自己加一个样式即可。

```css
img {
    max-width: 100%;
}
```

PS：展示的时候需要自己定义很多样式，不仅仅是图片的。参考这里 https://www.wangeditor.com/v5/guide/display.html#%E5%A2%9E%E5%8A%A0%E6%A0%B7%E5%BC%8F

**Comment by WzSepia** [comment]
自己在外部处理了,期待这个能有内部处理;

**Comment by wangfupeng1988** [comment]
编辑器输出的内容尽量是纯净的 html ，才能让用户自由发挥定义各种样式。所以这块还是你们自己处理吧。

**Comment by WzSepia** [comment]
嗯,OK
