### ISSUE TITLE
mac系统，搜狗输入法，在官网编辑器中，首行输入中文文字时出现异常

### ISSUE THREAD

**Issue by wk666** [wangeditor-team/wangEditor#3766]
## bug 描述

*mac系统，搜狗输入法，在官网编辑器中，首行输入中文文字时出现异常*

## 你预期的样子是？

*在第一行输入中文，“我的”，预期出现中文“我的”,实际上会概率性出现某几个字母被自动删除，导致无法正常打出中文文字，猜测和删除键有关，比如，首行文本框内只有2个字，然后连续摁3次删除，立即输入“我的”，大概率无法正常打出“我的”这两个字*

## 浏览器及版本号

*chrome 版本 96.0.4664.55（正式版本） (x86_64)*

## wangEditor 版本

*V4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
预期里写了

**Comment by wangfupeng1988** [comment]
首行文本框内只有2个字，然后连续摁3次删除，立即输入“我的”，大概率无法正常打出“我的”这两个字 —— 这个是可以复现的。

**Comment by rsl140** [comment]
#3799 也是类似的问题，处理的时候可以一起排查下

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
