### ISSUE TITLE
希望代码块支持修改语言和显示语言类型

### ISSUE THREAD

**Issue by coolqingcheng** [wangeditor-team/wangEditor#3769]
目前输入代码后，只支持删除，一旦选择语言错误，只能删掉重新录入。

而且输入错误后，也不知道在哪儿看代码块的语言类型

**Comment by wangfupeng1988** [comment]
这个不在 v4 中改了（业余维护的开源项目，精力有限，还请体谅），v5 中已经支持改功能。
