### ISSUE TITLE
V5版本代码块连续换行，光标会跳出代码块

### ISSUE THREAD

**Issue by yaniswang** [wangeditor-team/wangEditor#3770]
## bug 描述

*v5版本代码块中，连续多个换行，光标会跳出代码块*

## 你预期的样子是？

*可以连续输入多个换行，光标始终在代码块内部*

## 浏览器及版本号

*chrome 96*

## wangEditor 版本

*@wangeditor/editor 0.12.8*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一： 打开：https://www.wangeditor.com/demo/zh-CN/
- 步骤二：输入内容：abc
- 步骤三：设置代码块
- 步骤四：连续按3次回车

这个时候，光标就会跳出代码块到外部。

![image](https://user-images.githubusercontent.com/970390/144805925-42093f3c-5ca2-4fe9-b1e8-4df4cc815022.png)

如果这个时候再次将光标点击回abc的后面

![image](https://user-images.githubusercontent.com/970390/144805978-b4b3a8da-5627-4b45-9a05-42792a75e50e.png)

然后再按一次回车，代码块会被拆分成两个。

![image](https://user-images.githubusercontent.com/970390/144806036-16a4c3c1-bd5f-4c82-9cc8-e74db670dae8.png)

**Comment by wangfupeng1988** [comment]
移动到 https://github.com/wangeditor-team/wangEditor-v5/issues/289 这里跟踪
