### ISSUE TITLE
初始化后输入法为中文的情况下，按住shift再加上键盘数字区域来输入“~!@#$%^&*()_+”这类特殊符号，会变成两个

### ISSUE THREAD

**Issue by shu-da-wang** [wangeditor-team/wangEditor#3771]
## bug 描述

*富文本初始化完成后，内容为空的时候，输入法切换到中文，输入“@”，富文本框里会出现两个@@符号*

## 你预期的样子是？

*只出现一个@符号*

## 浏览器及版本号

*chrome V96.0.4664.45*

## wangEditor 版本

*4.7.10*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 选择官网任意demo
- 步骤二
- 切换输入法为中文模式
- 步骤三
- 输入“~！@#￥%……&*（）”等符号

Tips:
之前自己在处理  contenteditable="true" 的元素时也遇到过同样的问题，场景一样，当时出现的原因是因为同步调用了目标元素的onBlur()事件，放到异步中之后，问题就没有了，可以参考一下是不是同样的原因

**Comment by wangfupeng1988** [comment]
我在官网 https://www.wangeditor.com/ 并没有复现（我这是中文输入，搜索输入法）
![image](https://user-images.githubusercontent.com/9583120/144944521-d553d8b2-0e22-46b4-857c-64d1b2bee2e0.png)

**Comment by yunshu1996** [comment]
![image](https://user-images.githubusercontent.com/25656472/144953799-77363c79-abec-4aa7-aca7-f928c6632549.png)
官网demo复现不出来是因为富文本初始化之后是有内容的，需要在初始化之后没有内容的情况下第一次输入才会复现。
可以试试这里面的demo
https://codepen.io/xiaokyo-the-bold/details/ZEpWByR

**Comment by wangfupeng1988** [comment]
奇怪了，我这试着也没啥问题呀。

Mac OS + Chrome96 + 搜狗输入法

![image](https://user-images.githubusercontent.com/9583120/144963606-25bf9a45-a89c-4eb5-8e68-87845f28377e.png)

**Comment by yunshu1996** [comment]
看起来应该是windows系统下才会出现这个问题，我刚刚试了一下mac os下也是没有问题的

**Comment by yunshu1996** [comment]
在windows下监听input事件可以发现，输入法为中文的情况下，输入"@"符号实际上会触发两次input事件，两次的data值都是“@”

**Comment by UltramanWeiLai** [comment]
![image](https://user-images.githubusercontent.com/23336585/144966486-3affe67e-c244-4628-aa77-4bfca83f088f.png)
win10 没有复现

**Comment by yunshu1996** [comment]
> 

win10下，系统自带的输入法确实没问题，但搜狗输入法会出现。。。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
