### ISSUE TITLE
配置languageType后 报错 TypeError: Cannot set properties of undefined (setting 'languageType')

### ISSUE THREAD

**Issue by echobool** [wangeditor-team/wangEditor#3777]
## bug 描述

editor = new E('#publish-editor')
                editor.highlight = hljs
                **//插入代码语言配置**
                editor.config.languageType = [
                    'Bash',
                    'C',
                    'C#',
                    'C++',
                    'CSS',
                    'Java',
                    'JavaScript',
                    'JSON',
                    'TypeScript',
                    'Plain text',
                    'Html',
                    'XML',
                    'SQL',
                    'Go',
                    'Kotlin',
                    'Lua',
                    'Markdown',
                    'PHP',
                    'Python',
                    'Shell Session',
                    'Ruby',
                ]
                editor.customConfig.menus = [
                    'head',  // 标题
                    'bold',  // 粗体
                    'fontSize',  // 字号
                    'fontName',  // 字体
                    'italic',  // 斜体
                    'underline',  // 下划线
                    'strikeThrough',  // 删除线
                    'foreColor',  // 文字颜色
                    'backColor',  // 背景颜色
                    'list',  // 列表
                    'justify',  // 对齐方式
                    'quote',  // 引用
                    'image',
                    'code',
                    'undo',  // 撤销
                    'redo'  // 重复
                ]
                editor.create()

控制台报错 Uncaught TypeError: Cannot set properties of undefined (setting 'languageType')

## 你预期的样子是？

能正常选择 编程语言类型

## 浏览器及版本号

chrome 90

## wangEditor 版本

wangeditor@^3.1.1

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

var E = require('wangeditor')
var hljs = require('highlight.js')
editor = new E('#publish-editor')
                editor.highlight = hljs
                //插入代码语言配置
                editor.config.languageType = [
                    'Bash',
                    'C',
                    'C#',
                    'C++',
                    'CSS',
                    'Java',
                    'JavaScript',
                    'JSON',
                    'TypeScript',
                    'Plain text',
                    'Html',
                    'XML',
                    'SQL',
                    'Go',
                    'Kotlin',
                    'Lua',
                    'Markdown',
                    'PHP',
                    'Python',
                    'Shell Session',
                    'Ruby',
                ]
                editor.customConfig.menus = [
                    'head',  // 标题
                    'bold',  // 粗体
                    'fontSize',  // 字号
                    'fontName',  // 字体
                    'italic',  // 斜体
                    'underline',  // 下划线
                    'strikeThrough',  // 删除线
                    'foreColor',  // 文字颜色
                    'backColor',  // 背景颜色
                    'list',  // 列表
                    'justify',  // 对齐方式
                    'quote',  // 引用
                    'image',
                    'code',
                    'undo',  // 撤销
                    'redo'  // 重复
                ]
                editor.create()
                // 赋值编辑器内容
                editor.txt.html('')

**Comment by wangfupeng1988** [comment]
v3 早就不维护了。
开源项目，精力有限，还请体谅。
