### ISSUE TITLE
在不同的JS页面调用editor函数

### ISSUE THREAD

**Issue by shiguangfeishi191** [wangeditor-team/wangEditor#3778]
因为要实现文章修改功能，要在不同页面调用editor.txt.html()添加内容

JS页面1中初始化editor
JS1页面：
const E = window.wangEditor;
const editor = new E('#id');

JS页面2中怎么调用
JS2页面:
editor.txt.html('添加内容')

**Comment by wangfupeng1988** [comment]
这个看起来不是 editor 的问题，而是一个 js 的问题。

如果不是 editor ，而是一个普通的 js 对象，你能夸两个页面调用吗？
