### ISSUE TITLE
【新功能建议】插入超链接后，若未输入http://，自动添加。

### ISSUE THREAD

**Issue by koibi2** [wangeditor-team/wangEditor#3779]
## 功能描述

希望粘贴链接后，若未输入http:// 或 https:// ，自动添加http://。
**现在 wangEditor 最新版。如果用户没加 http:// ，插入了链接 www.abc.com，会跳转到 https://www.example/www.abc.com。**

之前的 issues 提到过这个，但现在最新版没有生效。https://github.com/wangeditor-team/wangEditor/issues/636

## 可参考的案例

最好参考 quill ，允许让用户手动处理。
![image](https://user-images.githubusercontent.com/34370367/145511699-b3b5b269-4dda-4f8b-981a-d94595f50186.png)

**Comment by koibi2** [comment]
wangEditor 的 V5版本也有这个问题。勉强算一BUG？
希望优化支持。

**Comment by wangfupeng1988** [comment]
如果插入一个相对链接，或者锚点，再加 https 就不行了。

**Comment by koibi2** [comment]
已支持
https://www.wangeditor.com/v5/guide/menu-config.html#链接
