### ISSUE TITLE
能增加一个左侧输入代码，右侧预览的模式嘛？

### ISSUE THREAD

**Issue by shibaoqian** [wangeditor-team/wangEditor#3784]
## 功能描述

就类似下图这种

## 提炼几个功能点

- 主要就是能让用户能同时看到自己输入的和预览的

## 原型图

![1639364980(1)](https://user-images.githubusercontent.com/42538416/145746466-63413c61-5840-4e4d-8d74-d679f5942f74.jpg)

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

案例：https://imzbf.github.io/md-editor-v3/index

**Comment by wangfupeng1988** [comment]
这个需要你自己开发。左侧是编辑器，然后 onchange 实时获取编辑器内容，并渲染到右侧。
编辑器本身不会支持
