### ISSUE TITLE
加粗功能

### ISSUE THREAD

**Issue by A189861A** [wangeditor-team/wangEditor#3785]
加粗功能是用过用b标签包裹实现的，chrome浏览器默认禁止b标签加粗效果

**Comment by wangfupeng1988** [comment]
> chrome浏览器默认禁止b标签加粗效果

你是什么版本，我这边没有默认禁止呢。Mac OS, chrome 96

![image](https://user-images.githubusercontent.com/9583120/146109578-300efdd9-5c69-4556-9b31-0e58004f6c42.png)

**Comment by rsl140** [comment]
我觉得 你看看你自己的默认全局样式，是不是吧B标签给自定义了

**Comment by rsl140** [comment]
长时间未回复，暂且关闭
