### ISSUE TITLE
设置字体颜色的问题

### ISSUE THREAD

**Issue by abb-uu** [wangeditor-team/wangEditor#3787]
## 问题描述

设置字体颜色时添加的是font标签, 但是font标签已被废弃, 所以将html嵌入webview时标签与标签内容都不显示

## wangEditor 版本

4.7.10

## 是否查阅了文档 ？

是

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
v4.x 版本用的是 execCommand API 来操作富文本，它用的就是 font 标签。所以暂时没办法改。
目前只能你自己把 font 替换为 span 。直接拿到 html 字符串，自己替换即可

另外，你可以调研一下 [v5](https://www.wangeditor.com/v5/) 版本，v5 弃用了 execCommand ，不会再有这个问题。
