### ISSUE TITLE
V5是否可以增加代码高亮（集成highlight ）

### ISSUE THREAD

**Issue by Lrunlin** [wangeditor-team/wangEditor#3791]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
V5 默认已经支持代码高亮，用的是 prism.js

**Comment by goku1989** [comment]
能够提供一个，通过修改prism.js的样式，从而修改wangeditor样式的方式
