### ISSUE TITLE
 dangerouslyInsertHtml设置内容无效

### ISSUE THREAD

**Issue by master-genius** [wangeditor-team/wangEditor#3792]
## bug 描述

我需要从旧版的迁移到新版，需要直接使用 dangerouslyInsertHtml来直接设置html内容，但是发现设置无效。

## 你预期的样子是？

可以直接设置html文本内容，保持和原有程序兼容。

## 浏览器及版本号

Firefox 95+

## wangEditor 版本

wangEditor 5 公开测试版。

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

我只是从storage获取保存的html文本，此文本是通过onChange事件获取的，测试发现可以正常获取，缓存获取的内容也正常，但是之后再调用此接口设置无效。

**Comment by wangfupeng1988** [comment]
`可以直接设置html文本内容，保持和原有程序兼容。` —— 这个功能目前不能实现，否则 API 的名字的就不会有 `dangerously` 这个单词了。dangerouslyInsertHtml 目前主要用于粘贴 HTML ，不保证语义一致性。

V4 升级 V5 需要参考 https://github.com/wangeditor-team/wangEditor-v5/issues/233

PS：我有考虑过让 V5 完全支持 V4 的 html ，但目前尚无法轻松实现，明年会做一下。

**Comment by master-genius** [comment]
> 
谢谢，我这两天熬夜换到了v5版本，其实这个完全基于结构化数据的设计比直接用html要好，程序开发友好，之前的html文本我不得不针对不同场景做很多正则处理，甚至后来打算自己解析html到js对象。我很喜欢wangeditor不引入过多扩展，简单实用的设计，这也是我给其他人推荐的理由，国外的很多编辑器都动不动就引入很多扩展，使用上很难受。

**Comment by wangfupeng1988** [comment]
感谢支持。有什么建议可以继续提新 issue 。
如果没问题的话，这个 issue 就先关闭。

**Comment by csfankun** [comment]
我在使用这个api 粘贴字符串 <p><span style=\"font-size: 12px;\"><img src=\"https://minio.cvmart.net/cvmart-richtext-image/642a06ebfaef4292bc3157f8109439d0.jpg\"></span></p><p><br></p><h3><span style=\"font-size: 18px;\">大赛官网 </span><a href=\"https://www.cvmart.net/list/ZHCV2021?utm_source=topics\" target=\"_blank\" style=\"font-size: 18px; color: rgb(38, 125, 255);\">https://www.cvmart.net/list/ZHCV2021</a></h3><p><br></p><p><span style=\"font-size: 12px;\"> 【大赛介绍】</span></p><p><span style=\"font-size: 12px;\"> 珠港澳人工智能算法大赛是由珠海市香洲区科技创新促进中心主办，腾讯云启创新中心（珠海）、珠海极市科技有限公司承办的高级别算法竞赛。</span></p><p><br></p><p><span style=\"font-size: 12px;\"> 大赛旨在促进全球人工智能人才的技术交流，立足于珠海的城市创新发展，让广大开发者为大湾区的发展贡献技术力量。通过充分评估开发者的工程化能力和综合实力，推动人工智能领域的人才发展，为打造“智慧珠海”的城市形象，实现产业变革提供创新动力。</span></p><p><br></p><p><span style=\"font-size: 12px;\"> 【大赛选题】</span></p><p><span style=\"font-size: 12px;\"> 本次大赛设置两个赛道</span><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> *</span><span style=\"font-size: 12px;\"> ：</span></p><p><span style=\"font-size: 12px;\"> 赛道一：智慧工业·打手机识别</span></p><p><span style=\"font-size: 12px;\"> 赛道二：智慧安防·烟雾检测</span></p><p><br></p><p><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> *</span><span style=\"font-size: 12px;\"> 注：两个赛题分开评奖，可同时参与两个赛题。</span></p><p><br></p><p><span style=\"font-size: 12px;\"> 【奖项设置】</span></p><p><span style=\"font-size: 12px;\"> 两个赛题分开评奖，参赛者可同时参与两个赛题，各赛题奖项设置如下：</span></p><p><br></p><p><span style=\"font-size: 12px;\"> \uD83E\uDD47 一等奖：奖金￥20,000 + 获奖证书 + 10,000 极力值</span><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> *</span><span style=\"font-size: 12px;\"> （1支队伍）</span></p><p><span style=\"font-size: 12px;\"> \uD83E\uDD48 二等奖：奖金￥15,000 + 获奖证书 + 8,000 极力值（1支队伍）</span></p><p><span style=\"font-size: 12px;\"> \uD83E\uDD49 三等奖：奖金￥10,000 + 获奖证书 + 6,000 极力值（1支队伍）</span></p><p><span style=\"font-size: 12px;\"> \uD83C\uDFC5 优胜奖：奖金￥3,000 + 获奖证书 + 4,000 极力值（2支队伍）</span></p><p><span style=\"font-size: 12px;\"> \uD83D\uDC90 特别扶持奖：项目落地配套政策扶持 + 获奖证书 + 2,000 极力值（若干）</span></p><p><br></p><p><span style=\"font-size: 12px;\"> 另外，大赛期间各赛道还设置有✨ 「周新星」超越奖项，优胜者可获得￥200京东卡奖励。</span></p><p><br></p><p><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> *</span><span style=\"font-size: 12px;\"> 注：极力值可在极市平台内兑换算力或礼品，兑换规则详见极市平台说明。</span></p><p><br></p><p><span style=\"font-size: 12px;\"> 【赛程安排】</span></p><p><span style=\"font-size: 12px;\"> 10/27：大赛开启，线上报名</span></p><p><span style=\"font-size: 12px;\"> 11/04：线下启动仪式，赛前主题培训</span></p><p><span style=\"font-size: 12px;\"> 11/27：截止提交比赛作品</span></p><p><span style=\"font-size: 12px;\"> 12/10：公布获奖名单</span></p><p><span style=\"font-size: 12px;\"> 12/17：算法大赛线下颁奖典礼，暨人工智能开发者大会</span></p><p><br></p><p><span style=\"font-size: 12px;\"> 【参赛资格】</span></p><p><span style=\"font-size: 12px;\"> 1、本次大赛面向全社会开放，个人、高等院校、科研单位、企业等人员或单位均可报名参赛</span><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> *</span><span style=\"font-size: 12px;\"> 。</span></p><p><span style=\"font-size: 12px;\"> 2、每位选手只能加入一支队伍；每支参赛队伍不超过3人。</span></p><p><br></p><p><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> *</span><span style=\"font-size: 12px;\"> 注：大赛组织机构单位中涉及题目编写、数据接触的人员禁止参赛。主办方员工和赛事合办单位参赛，可参与排名，但不参与评奖及领取奖金。</span></p><p><br></p><p><span style=\"font-size: 12px;\"> 【报名方式】</span></p><p><span style=\"font-size: 12px;\"> 1、报名开始时间：北京时间 2021年10月27日；</span></p><p><span style=\"font-size: 12px;\"> 2、截止提交大赛成绩时间：北京时间 2021年11月27日 19:00；</span></p><p><span style=\"font-size: 12px;\"> 3、报名方式：访问 https://www.cvmart.net/list/ZHCV2021 登录并完成报名信息，即可报名参赛</span><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> *</span><span style=\"font-size: 12px;\"> 。</span></p><p><br></p><p><span style=\"font-size: 12px;\"> 【大赛交流】</span></p><p><span style=\"font-size: 12px;\"> 1、大赛微信交流群：添加赛事助手极小东（微信号：cvmart3），加入大赛微信交流群。</span></p><p><span style=\"font-size: 12px;\"><img src=\"https://minio.cvmart.net/cvmart-richtext-image/9ce9b692d2f346ceb29e5431d2ab4a3a.png\"></span></p><p><br></p><p><span style=\"font-size: 12px;\"> 2、大赛交流社区：https://bbs.cvmart.net/c/match</span></p><p><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> 3、</span><span style=\"color: rgb(230, 0, 0);\">大赛 FAQ： https://bbs.cvmart.net/articles/5694</span></p><p><br></p><p><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> 【线上比赛流程】</span></p><p><span style=\"font-size: 12px;\"> 1、报名及组队；</span></p><p><span style=\"font-size: 12px;\"> 2、在线编码调试；</span></p><p><span style=\"font-size: 12px;\"> 3、发起训练任务；</span></p><p><span style=\"font-size: 12px;\"> 4、编写测试SDK，发起自动测试，自动得出A/B榜成绩；</span></p><p><span style=\"font-size: 12px;\"> 5、比赛过程中实时刷新A榜成绩，比赛结束后展示B榜成绩，以B榜为最后评比依据。</span></p><p><br></p><p><span style=\"font-size: 12px; color: rgb(230, 0, 0);\"> 【评审规则】</span></p><p><span style=\"font-size: 12px;\"> 详见</span><span style=\"font-size: 12px; background-color: rgb(255, 255, 255);\"> 赛题说明部分。</span></p>   发现其中的两个图片没显示出来

**Comment by wangfupeng1988** [comment]
@csfankun `<img>` 在 `<span>` 内部，这无法识别。

**Comment by lyy199212** [comment]
> @csfankun `<img>` 在 `<span>` 内部，这种的不会解析。

`<img>` 在 `<span>` 内部在a标签内部都是不能解析的吧,那业务场景需要的话 有什么处理方案么 谢谢~

**Comment by cyberkingkong** [comment]
<div class="row"><div class="col-lg-6">a</div><div class="col-lg-6">b</div></row>
我也遇到此类问题
        editor.focus();
        editor.dangerouslyInsertHtml(layout, true)
只能插入  ab二个字符
html被过滤掉了
vue 3.2.7 
wangEditor  5.1.23

**Comment by cyberkingkong** [comment]
`<div class="row"><div class="col-lg-6">a</div><div class="col-lg-6">b</div></div>`
