### ISSUE TITLE
插入链接加粗之后菜单不能激活，并且无法无显

### ISSUE THREAD

**Issue by chaofan-rensheng** [wangeditor-team/wangEditor#3795]
## bug 描述
插入链接加粗之后菜单不能激活，没有被选中，并且无法回显。不加粗的时候正常
*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本
最新版本
*请输入内容……*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 插入链接
- 步骤二 选中链接文案 加粗
- 步骤三 光标放在链接文案中，菜单没激活切无法回显链接内容

**Comment by Gavin-yh** [comment]
是v4版本的吗?

**Comment by wangfupeng1988** [comment]
@chaofan-rensheng 请重新编辑问题，说明浏览器和版本，以及 wangEditor 版本。然后我再 reopen issue
