### ISSUE TITLE
粘贴到富文本中的文字丢失居中样式

### ISSUE THREAD

**Issue by fanxinxin6** [wangeditor-team/wangEditor#3797]
## bug 描述

在word中输入一段文案，居中显示，把这段文案粘贴到editor里面，就变成居左了，丢失了居中样式

## 你预期的样子是？

在word里面是居中的文案，粘贴到editor后依然是居中的

## 浏览器及版本号

chrome 96 mac系统

## wangEditor 版本

4.7.10

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
在word里面写一段文案，对齐方式是居中
- 步骤二
选中在word里面写的文案,粘贴到editor里面

**Comment by wangfupeng1988** [comment]
word 粘贴不能完全保证样式的细节。
否则，这个工作量就太大了，业余维护还请体谅。

**Comment by fanxinxin6** [comment]
不过发现好几款编辑器都支持粘贴居中这个哦。觉得wangeditor文档啊设计啊都很棒，考虑在用了，唯一觉得不足的就是word粘贴会不居中。维护的人员可以考虑一下哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 粘贴到富文本中的文字丢失居中样式 (Issue #3797)





 
word 粘贴不能完全保证样式的细节。
 否则，这个工作量就太大了，业余维护还请体谅。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfupeng1988** [comment]
如果你用的是 v4 ，我们将不再优化了。如果你用的 v5 版本，我们将继续优化。
业余精力优先，还请体谅。

**Comment by fanxinxin6** [comment]
打算用v5呢,发现v5的极简模式对齐方式是展开的，用户使用方便点，少一步操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 粘贴到富文本中的文字丢失居中样式 (Issue #3797)





 
如果你用的是 v4 ，我们将不再优化了。如果你用的 v5 版本，我们将继续优化。
 业余精力优先，还请体谅。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
