### ISSUE TITLE
输入法为中文时，如果是初始化没有任何内容的情况下，会出现先在输入框输入英文的情况

### ISSUE THREAD

**Issue by finger24** [wangeditor-team/wangEditor#3799]
## bug 描述

*在windows10 edge浏览器下环境，初始化时输入法为中文时，会出现先在输入框输入英文的情况。*
*如果像官网一样已经有内容，则不会有此BUG*
*删除错误的输入，重新输入的时候则不会再次发生该BUG*

## 你预期的样子是？

*中文输入*

## 浏览器及版本号

*版本 96.0.1054.62 (官方内部版本) (64 位)，输入法为windows10自带输入法*

## wangEditor 版本

*V4.7.5*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

*步骤一：打开示例网站https://codepen.io/xiaokyo-the-bold/pen/ZEpWByR，即示例程序*
*步骤二：切换到中文输入法进行输入*
*步骤三：中文输入wode，即“我的”，显示如下*
![image](https://user-images.githubusercontent.com/45475421/147067631-e5a13369-0508-4678-9120-701d0b9cd5bc.png)

**Comment by rsl140** [comment]
该问题已经收录 可以移步到 #3766 跟进
