### ISSUE TITLE
插入图片居中后换行，光标是跟随进行居中的，不是在最前边

### ISSUE THREAD

**Issue by zylgt** [wangeditor-team/wangEditor#3801]
## bug 描述

*插入图片居中后换行，光标是跟随进行居中的，不是在最左边*

## 你预期的样子是？

*插入图片剧中后换行，光标是在最前边*

## 浏览器及版本号

*谷歌浏览器*

## wangEditor 版本

*4.7.9*

## 官网能否复现该 bug ？

偶尔能

## 最小成本的复现步骤

插入图片居中后，换行
![WechatIMG136](https://user-images.githubusercontent.com/30862791/147339943-2926096e-40de-44db-bd56-0150a8920a7b.png)

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这个符合预期。
图片的居中，其实就是它所在的 `<p>` 设置了 `text-align: center` 。所以换行也就随着居中了。

**Comment by swanghao** [comment]
> 这个符合预期。 图片的居中，其实就是它所在的 `<p>` 设置了 `text-align: center` 。所以换行也就随着居中了。

如果是一直输不按回车这个是没问题得， 但是如果他按了回车键呢？不是新生成一共p标签 清除text-align:center所带来得影响吗？

**Comment by wangfupeng1988** [comment]
@swanghao 参考这里 https://github.com/wangeditor-team/wangEditor/issues/3835
