### ISSUE TITLE
关于菜单栏添加文本着重号功能

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3804]
## 功能描述

操作方式和加粗、斜体、下划线一样，效果是将选中的文本添加着重号显示，才做这个自定义插件的时候发现加粗、斜体、下划线你们源码都是采用的浏览器原生的execCommand执行的，所以想请教下大佬们，这个功能手动该用怎么样的思路去处理，我只能拿到用户选择的那几个纯文本还有所在的dom。要处理的几种情况如下。 希望大佬们可以提供点思路。万分感谢！

## 提炼几个功能点

- 功能1  给部分文本添加着重号
- 功能2  给部分文本取消着重号
- 功能3  同时存在着重号和粗体斜体等

## 原型图

*
![image](https://user-images.githubusercontent.com/43296632/147458520-1d24d6c5-7e84-4548-9f19-1243b81a53c6.png)

## 可参考的案例

![image](https://user-images.githubusercontent.com/43296632/147458525-12196756-609a-4110-a01c-202795f9af03.png)

**Comment by wangfupeng1988** [comment]
“重点号”这个我还真是第一次听说，之前也没见过。
该怎么处理，我也一时搞不懂。即便是抛开 execCommand ，光说用 css 和 dom 去操作，我目前也没有一个简洁明了的思路。
