### ISSUE TITLE
添加复制功能

### ISSUE THREAD

**Issue by 3239089** [wangeditor-team/wangEditor#3806]
## 功能描述

当插入图片后，文本框内有图片+文本。但是复制出来后得到的只有文本，没有图片。（在微信聊天窗口内Ctrl+V的）

## 提炼几个功能点

- 复制

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
https://bj.96weixin.com/

**Comment by wangfupeng1988** [comment]
哪个 wangEditor 版本，以及哪个浏览器？

我用 chrome 在官网 https://www.wangeditor.com/ 试着，是可以复制图片 + 文字的

**Comment by 3239089** [comment]
我也是在官网上试的https://www.wangeditor.com/，比如我先输入了文字，再插入图片。这时候复制到微信聊天框内，只有文字，没有图片。而我上面发出来的这个网址：https://bj.96weixin.com/。它就能达到这样的效果。文本和图片一起复制到微信了。

**Comment by wangfupeng1988** [comment]
你是想要从其他地方，复制粘贴图片对吧？这个有些确实不支持。

**Comment by 3239089** [comment]
不是，是想从wangEditor里把图片+文本一起复制到微信聊天输入框，但是只复制得了文本，复制不了图片。

**Comment by wangfupeng1988** [comment]
这个还不支持
