### ISSUE TITLE
自定义图片上传，可以添加一个拖拽上传功能吗，现在很需要要，谢谢

### ISSUE THREAD

**Issue by 8392** [wangeditor-team/wangEditor#3807]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
本身就支持，demo 在这里 http://106.12.198.214:8881/master/examples/upload-image.html
