### ISSUE TITLE
在其他网站复制内容进来，会带入行内样式，此时再去按回车换行，json没问题，但是生成的html会有问题

### ISSUE THREAD

**Issue by wang-cola** [wangeditor-team/wangEditor#3808]
## bug 描述

在其他网站复制内容进来，会带入行内样式，此时再去按回车换行，json没问题，但是生成的html会有问题，br会消失

## 你预期的样子是？

按照编辑器显示的样子，html里有正常的br换行

## 浏览器及版本号

chrome

## wangEditor 版本

https://www.wangeditor.com/demo/zh-CN/index.html 官网版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
   在官网即可复现
  我复制内容的网站：https://baijiahao.baidu.com/s?id=1649960506095758902&wfr=spider&for=pc
- 步骤一
   从网站里随意复制一段话
   此时查看getHtml，没有问题
- 步骤二
   然后在文本里按几个回车换行
  
![image](https://user-images.githubusercontent.com/21015798/147637510-cfcc119c-fd10-4e97-86d0-e9056a1ee8b3.png)
此时查看getHtml 会发现换行的几个p里<p><span></span></p>里是没有br的
- 步骤三
  此时删掉编辑器内容，自己去输入文字，然后回车换行，再getHtml，会发现 之前粘贴进来的格式还在，还是没有br
![image](https://user-images.githubusercontent.com/21015798/147637736-dddf37d8-a5d9-4d2e-91eb-d14dbafaa88a.png)

**Comment by wangfupeng1988** [comment]
这并不是复制粘贴的问题。自己在编辑器操作一番也会复现这个问题
- 打开官网 demo https://www.wangeditor.com/demo/zh-CN/index.html
- 输入一些文字，全选，设置 color 和 bgColor
- 然后按照你的步骤二（中间回车）和步骤三（全部删除，再回车）

这个问题的核心在于两点
1. 如果当前一行有 color ，那回车之后产生的新行，该不该继续有这个 color 属性？—— 答案是：应该有。所以你说的“步骤二”，是符合预期的，不是 bug
2. 如果全选删除，那之前设置的 color，应该继续保留？—— 这个我不确定，但看腾讯文档里，是依然保留的。这就是你的“步骤三”

所以，对此，不能做任何改动。

**Comment by wang-cola** [comment]
> 这并不是复制粘贴的问题。自己在编辑器操作一番也会复现这个问题
> 
> * 打开官网 demo https://www.wangeditor.com/demo/zh-CN/index.html
> * 输入一些文字，全选，设置 color 和 bgColor
> * 然后按照你的步骤二（中间回车）和步骤三（全部删除，再回车）
> 
> 这个问题的核心在于两点
> 
> 1. 如果当前一行有 color ，那回车之后产生的新行，该不该继续有这个 color 属性？—— 答案是：应该有。所以你说的“步骤二”，是符合预期的，不是 bug
> 2. 如果全选删除，那之前设置的 color，应该继续保留？—— 这个我不确定，但看腾讯文档里，是依然保留的。这就是你的“步骤三”
> 
> 所以，对此，不能做任何改动。

不不不 大佬，我提的这个问题  关键点说的不是那些color啥的，是各种回车之后，editor.getHtml()，获取的html字符串，里面那些换行的<br/>没了。。。你看我截图里拿红箭头指出来的地方，那些地方应该是有换行的br的，但是都木有了

**Comment by wangfupeng1988** [comment]
哦，你关注的是：空行没有了 `<br>` 。确实，这个是一个 bug ，我之前没理解到位。

**Comment by erpiiiii** [comment]
昨天为这事掰扯一整天,没搞好.只要输入的html 只要不去编辑,就不会有任何问题
而且输入的html的样子,和编辑器中的样子差距很大,比如字体,位置等等
....我还以为是我没认真看文档,原来这就是个bug

**Comment by wangfupeng1988** [comment]
@erpiiiii 还遇到了啥其他现象，可以继续在这里补充，我可以排查的更精确一些。

**Comment by erpiiiii** [comment]
我的这个项目有个功能是通过上传word,然后后台将接受的流通过fr.opensagres.poi.xwpf.converter转化为html字符串.再传回前端,前端接收后通过editor.txt.html(res.html)这个方法,直接把html字符串插入到编辑器的.
       其实我想实现的是所见即所得.因为后台转换后的html样式本身就需要微调.但就如上述所说.如果我把html字符串插入到编辑器,再输出到网页(输出是直接在div中使用 v-html)的话,样式会发生意想不到的变化.例如在编辑器中某个标题的字体看起来很小,但实际输出后却很大.仿佛是编辑器私自加入了某些样式,让我编辑器中看到的和实际输出的样式有较大区别.我的想法是能让在我插入的内容,在微调后没有被编辑器加入其它的样式.如果哪里没有说清楚,这是我的邮箱pepe0209@foxmail.com,请联系我

**Comment by wangfupeng1988** [comment]
空行没有 `<br>` 的问题已经解决，等待合并、发布
https://github.com/wangeditor-team/wangEditor-v5/pull/341

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。

**Comment by wang-cola** [comment]
我这个issue就是v5版本的吧？



| |
王博
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月12日 11:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wangeditor-team/wangEditor] 在其他网站复制内容进来，会带入行内样式，此时再去按回车换行，json没问题，但是生成的html会有问题 (Issue #3808) |

V5 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
