### ISSUE TITLE
关于内容粘贴时功能的建议

### ISSUE THREAD

**Issue by ztzzhi** [wangeditor-team/wangEditor#3809]
## 功能描述

*关于内容粘贴时功能的建议*

## 提炼几个功能点

- 功能1  粘贴内容的时候可否增加图片转换成base64的功能
- 功能2 粘贴内容的时候将内容中的图片全部上传自己的服务器然后再替换掉之前的img标签的路径

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
这个目前不支持。
后续会在 v5 中考虑逐步支持，但需要时间。
