### ISSUE TITLE
上传图片只显示网络图片没有上传图片

### ISSUE THREAD

**Issue by guanpenghui1993** [wangeditor-team/wangEditor#3810]
![image](https://user-images.githubusercontent.com/25782424/147739727-85bd9a82-5a3e-4dce-9416-d828e839a725.png)
如图

**Comment by wangfupeng1988** [comment]
看文档吧。

另外，下次提交 issue 要按照模板格式，否则不予受理。

**Comment by guanpenghui1993** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
