### ISSUE TITLE
拿到的数据无法回显

### ISSUE THREAD

**Issue by 1364357141** [wangeditor-team/wangEditor#3811]
## 问题描述

*请输入遇到的问题...*
拿到数据后无法显示
## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
![image](https://user-images.githubusercontent.com/71486956/147743414-ea77bcd3-3ce4-4868-ac4d-b2a2db8f544c.png)

- 步骤二
- 
![image](https://user-images.githubusercontent.com/71486956/147743438-4a394020-5200-41ea-aa32-0e3963459584.png)

- 步骤三

**Comment by wangfupeng1988** [comment]
这提示的很清楚了，`editor.txt.html()` 返回的是一个字符串，你不能当做函数来执行。

![image](https://user-images.githubusercontent.com/9583120/147753211-d5df73ee-d44d-44c2-96a2-ff9f039acb47.png)

**Comment by wangfupeng1988** [comment]
下次提交 issue 时请说明 wangEditor 版本
