### ISSUE TITLE
当光标所处行有内容时，插入视频，居中靠左靠右失灵

### ISSUE THREAD

**Issue by maizhiyuan** [wangeditor-team/wangEditor#3812]
## bug 描述

当光标所处行有内容时，插入视频，居中靠左靠右按钮失灵

## 你预期的样子是？

不应该出现这种问题

## 浏览器及版本号

chrome  96.0.4664.110

## wangEditor 版本

4.7.10

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 将光标置于官网（https://www.wangeditor.com/ ）demo中的微信收款码后面，与收款码处在同一行
- 步骤二 点击插入视频，输入<video src="xxxxx视频链接xxx" />
- 步骤三 将视频元素大小设为30%
- 步骤四 几个调整位置的按钮（居中靠左靠右）一直来回点

**Comment by wangfupeng1988** [comment]
需要点击视频所在的 `<p>` ，才能设置 justify 。点击视频设置将无效。
V4 目前只能这样。V5 就彻底改变了，把视频做成了 void 元素 https://www.wangeditor.com/demo/zh-CN/
