### ISSUE TITLE
上传图片问题

### ISSUE THREAD

**Issue by 2456719939** [wangeditor-team/wangEditor#3814]
## 问题描述

*能否在上传图片时调整图片大小比例*

## v4.7.11

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这个不支持
