### ISSUE TITLE
有图片 但是就是不展示出来

### ISSUE THREAD

**Issue by liuxingyuxia** [wangeditor-team/wangEditor#3816]
## 问题描述

*有图片 但是就是不展示出来.*

## 4.7.4

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三
![image](https://user-images.githubusercontent.com/18691687/147907690-720d8a76-e920-4274-a7d2-81802c77a5f0.png)

```
<template>
  <div  class="editor">
    <div  ref="editorElem" style="text-align:left"></div>
  </div>
</template>
<script>
import E from 'wangeditor'
export default {
  name: 'editorElem',
  data() {
    return {
      editor: null,
      editorContent: ''
    }
  },
  model: {
    prop: 'value',
    event: 'change'
  },
  props: [ 'value'],    // 接收父组件的方法
  watch: {
    value(myValue) {
      console.log(myValue,'myValue')
      this.editor.txt.html(myValue)
    }
  },
  mounted() {
    this.editor = new E(this.$refs.editorElem)

    this.editor.config.onchange = (html) => {
      this.editorContent = html
      this.$emit('change',html)
      this.$emit('input',html)
    }
    this.editor.config.debug = true;
    this.editor.config.showLinkImg = false
    this.editor.config.customUploadImg = async (files, insert) => {
      insert('http://imgtest.swgfarmer.com/hg1634199147.0829093036810854.jpg')
    }
    this.editor.create()     // 创建富文本实例
    if (!this.content) {
      this.editor.txt.html(this.value)
    }
  }
}
</script>

<style lang="css">
  .editor {
    width: 100%;
    margin: 0 auto;
    position: relative;
    z-index: 0;
  }

  .toolbar {
    border: 1px solid #ccc;
  }

  .text {
    border: 1px solid #ccc;
    max-height: 500px;
    min-height: 300px;
    overflow : auto;
  }
</style>
```

**Comment by liuxingyuxia** [comment]
![image](https://user-images.githubusercontent.com/18691687/147912166-d1ee8f64-ddab-4552-968f-bce260d435f8.png)
头疼  图片格式怎么这样了

this.editor.config.showLinkImg = false
    this.editor.config.customUploadImg = async (files, insert) => {
      insert('http://imgtest.swgfarmer.com/hg1634199147.0829093036810854.jpg')
    }

**Comment by wangfupeng1988** [comment]
看你截图，`img` 和 `src` 之间没有空格
![image](https://user-images.githubusercontent.com/9583120/147935096-35b03e54-1022-4d5a-8c36-05e7a44d896f.png)

**Comment by liuxingyuxia** [comment]
> insert('http://imgtest.swgfarmer.com/hg1634199147.0829093036810854.jpg')

![image](https://user-images.githubusercontent.com/18691687/148322774-933edb4f-3aba-4025-8e8a-92ba39932867.png)
上面的写法 是可以的 但是下面就不可以了
