### ISSUE TITLE
存储和显示中“再次编辑”   希望继续支持html

### ISSUE THREAD

**Issue by czphappy** [wangeditor-team/wangEditor#3817]
## 问题描述

新版本的存储和显示，将content和html分离，不能很好兼容上一个版本（仅使用html的模式），由于我开发的项目涉及大量的富文本修改操作，需要存储content（以前存储html字符串即可）。而且content的存储尤为麻烦，后台服务器端需要更改数据表的数据格式（字符串修改为Json数组），回报率不高。希望能继续支持html的修改。或者编写一个函数，支持html转content

## wangEditor 版本

wangEditor 5.1.8

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

不涉及

**Comment by rsl140** [comment]
[V5 无法用 html 格式编辑的说明](https://github.com/wangeditor-team/wangEditor-v5/issues/233)
