### ISSUE TITLE
编辑器图片单击编辑双击看大图

### ISSUE THREAD

**Issue by RainyNights** [wangeditor-team/wangEditor#3818]
## 问题描述

*编辑器图片单击编辑双击看大图，如何给图片添加双击事件，同时单击事件和双击事件不冲突？*

## wangEditor 版本 

*4.7.6*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这个目前不支持。

你可以自己监听双击事件，自己做处理。

**Comment by RainyNights** [comment]
就是不知道怎么给那个图片加双击事件了？

**Comment by wangfupeng1988** [comment]
就使用 JS 绑定 DOM 事件即可，可以把绑定到编辑区域的 `<div>` 上，使用事件代理
