### ISSUE TITLE
上传视频,接口返回地址没有问题, 返回到js中就出现 undefined

### ISSUE THREAD

**Issue by chunchunchundashui** [wangeditor-team/wangEditor#3819]
## bug 描述
这是前段出现的问题
*<p><video src="undefined" controls="controls" style="max-width:100%"></video></p>
wangEditor.min.js:16 wangEditor: wangEditor: 插入视频错误，视频链接 "undefined"，下载链接失败*

## 你预期的样子是？

*{errno: 0,…}
data: [{url: "/uploads/editor/20220105\bc9e69d1a8dcd37589093866237dd77a.mp4", href: "", alt: "04.mp4",…}]
0: {url: "/uploads/editor/20220105\bc9e69d1a8dcd37589093866237dd77a.mp4", href: "", alt: "04.mp4",…}
alt: "04.mp4"
href: ""
size: 988560
url: "/uploads/editor/20220105\\bc9e69d1a8dcd37589093866237dd77a.mp4"
errno: 0 这是我后端返回的数据, 跟图片上传返回的数据一样的, 上传图片没有问题, 上传视频就出现了*

## 浏览器及版本号

*Google Chrome 96.0.4664.110 (64位)*

## wangEditor 版本

*4.7.11*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 使用富文本上传一个视频, 就会出现这种问题
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
用这测试页 http://106.12.198.214:8881/dev/examples/upload-video.html ，上传本地的一个 mp4 ，是正常的。

所以，请详细说明错误的复现步骤

**Comment by chunchunchundashui** [comment]
您好,我这边上传成功后, 有返回地址, 前端报错 视频插入时出错了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 上传视频,接口返回地址没有问题, 返回到js中就出现 undefined (Issue #3819)





 
用这测试页 http://106.12.198.214:8881/dev/examples/upload-video.html ，上传本地的一个 mp4 ，是正常的。
 
所以，请详细说明错误的复现步骤
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfupeng1988** [comment]
你要说明错误的复现步骤，让我们能复现这个错误。

**Comment by chunchunchundashui** [comment]
不好意思, 我发现是我这边的问题, 跟你这边没关系

**Comment by nodepade** [comment]
我发现的问题：上传接口是异步的，导致图片还没完全上传到服务器，已经开始加载视频，所以出现报错
