### ISSUE TITLE
为什么toolbar点击之后无法弹出

### ISSUE THREAD

**Issue by Lqs66** [wangeditor-team/wangEditor#3820]
## 点击标题等按钮无法弹出
预期结果：![image](https://user-images.githubusercontent.com/62269820/148222393-a803b4c7-957f-4188-9928-f6998846010d.png)
实际结果：
![image](https://user-images.githubusercontent.com/62269820/148222480-75f29237-4b20-4018-a44e-5e117289c934.png)
使用的代码：
<script src="dist/wangEditor.min.js"></script>
<div id="div1">
    <h1>欢迎使用 <b>wangEditor</b> 富文本编辑器</h1>
</div>

<script type="text/javascript">
    const E = window.wangEditor
    const editor = new E('#div1')
    // 或者 const editor = new E( document.getElementById('div1') )
    editor.create()
</script>

*请输入遇到的问题...*

## v4.7.11

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
没懂的你问题。什么无法弹出？官网能复现吗？

**Comment by Lqs66** [comment]
> 没懂的你问题。什么无法弹出？官网能复现吗?
谢谢您的回复，我按照如下教程在我的html页面中实现编辑器
![image](https://user-images.githubusercontent.com/62269820/148224876-bc58f4bb-cc22-4f82-8c99-363409788f1e.png)
随后当我点击标题按钮并不会出现下图所示的内容（该图来自官网的展示页面）
![image](https://user-images.githubusercontent.com/62269820/148225099-2b35f78e-9821-48c0-a2a8-a7f4af2445ee.png)
当我在我的html页面中点击标题时，所有的内容都挤在一个方格中，如下图
![image](https://user-images.githubusercontent.com/62269820/148225287-92513ce9-348c-4912-b150-9385e9bd1df7.png)

**Comment by Lqs66** [comment]
> 没懂的你问题。什么无法弹出？官网能复现吗？

感谢您，我已经解决了
