### ISSUE TITLE
自定义tooltip出现多个tooltip栏

### ISSUE THREAD

**Issue by wangjiahao123456** [wangeditor-team/wangEditor#3823]
## 问题描述  
自定义图片点击tooltip，按照官网的实例将代码重写了一遍在自己代码里重新加载了一遍，出现了我想要的tooltip栏，可是原有的tooltip栏依然存在，请问有方法能关闭原有的tooltip么？

## wangEditor 版本  
"wangeditor": "^4.7.11",
## 是否查阅了文档 ？ 
是
## 最小成本的复现步骤
参见问题描述

**Comment by wangfupeng1988** [comment]
V4 版本目前不支持，只能自己用 js 或者 css 隐藏了。
V5 支持自定义悬浮栏
