### ISSUE TITLE
过滤文本

### ISSUE THREAD

**Issue by czphappy** [wangeditor-team/wangEditor#3824]
## 问题描述

![image](https://user-images.githubusercontent.com/31985427/148878184-c2119764-0e03-416d-8fc3-3368cd4ef575.png)
这里我们希望复制过来的时候，可以让用户选择是否保留原格式，像word一样。
![image](https://user-images.githubusercontent.com/31985427/148878266-52a8bf80-a6e9-4a12-b26e-9ef4d6175846.png)

我们希望能调用系统过滤的接口

## wangEditor 版本

*V4*

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

不涉及

**Comment by wangfupeng1988** [comment]
目前不支持这个功能。
