### ISSUE TITLE
全屏遮挡，除了覆盖css之外，有配置吗

### ISSUE THREAD

**Issue by iCloudys** [wangeditor-team/wangEditor#3825]
## bug 描述

点击全屏按钮，左侧菜单的z-index是10001，测试编译器显示不全
![image](https://user-images.githubusercontent.com/13017318/148887270-382e2941-18b1-4bc6-a3b0-dcd2cde51718.png)

## 你预期的样子是？

显示在最上方，现在的办法是覆盖css,有没有api能修改呢

## 浏览器及版本号

chrome

## wangEditor 版本

 "@wangeditor/editor": "^0.13.6",
   "@wangeditor/editor-for-vue": "^0.6.12-6",

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 
页面写个div,并且设置z-index为很高
点击全屏后，就会复现

**Comment by wangfupeng1988** [comment]
设置 z-index ，文档里有 https://www.wangeditor.com/v5/guide/getting-started.html#z-index

**Comment by zjg23** [comment]
![image](https://user-images.githubusercontent.com/12578973/187844919-f8334f45-d6a4-49af-8a09-ed5c7b1d67f8.png)

https://www.wangeditor.com/v5/getting-started.html#%E5%BC%95%E5%85%A5-css-%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
