### ISSUE TITLE
【vue2 + wangEditor4.7.11 + @wangeditor/editor0.13.6】 emotion中可以增加多组tab表情吗？

### ISSUE THREAD

**Issue by DoggyYao** [wangeditor-team/wangEditor#3828]
## 问题描述
wangEditor4.7.11 ， emotion中可以增加多组表情吗？

*请输入遇到的问题...*
我想在emotion中增加多组表情，比如["系统"， “自定义”.....]等等，就类似与微信发表情的那个面板一样。
我看官网中只写了通过
editorConfig.MENU_CONF['emotion'] = {
emotions: '😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉'.split(' ') // 数组
}
这个只是设置 了一组表情，如果我还想在增加另一组表情“自定义”，请问这么配置？
注：我看 wangEditor3中可以通过设置 editor.customConfig.emotions 来配置多个tab，editorWang 4.7.11 也是这么用的吗？

## wangEditor 版本
wangEditor4.7.11

*请输入内容……*

## 是否查阅了文档 ？
是。
已查阅文档 https://www.wangeditor.com/v5/guide/menu-config.html#%E8%A1%A8%E6%83%85

**Comment by wangfupeng1988** [comment]
V4 中本来就支持多 tab 表情 https://www.wangeditor.com/doc/pages/03-%E9%85%8D%E7%BD%AE%E8%8F%9C%E5%8D%95/06-%E9%85%8D%E7%BD%AE%E8%A1%A8%E6%83%85%E5%9B%BE%E6%A0%87.html

PS：你标题中 `@wangeditor/editor0.13.6` 还有描述中的 `editorConfig.MENU_CONF['emotion'] ` 都是 V5 的写法。猜测你对 wangEditor 版本理解比较混乱。V4 文档 https://www.wangeditor.com/ ，V5 文档  https://www.wangeditor.com/v5/
