### ISSUE TITLE
小写字母g、j无法添加下划线样式

### ISSUE THREAD

**Issue by SamyeChan** [wangeditor-team/wangEditor#3829]
## bug 描述

小写字母g、j无法添加下划线样式，望能修复
![image](https://user-images.githubusercontent.com/31913599/149072058-ed1424d0-7ea0-43ae-b5a6-95712a261f12.png)

## 你预期的样子是？

![image](https://user-images.githubusercontent.com/31913599/149072393-a1b61ecd-2c45-4ef1-9883-3cb13e93e7a6.png)

## 浏览器及版本号

Chrome v96

## wangEditor 版本

v4.7.10

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

直接输入j或g，查看效果

**Comment by wangfupeng1988** [comment]
这就是使用的浏览器默认渲染，就这样，改不了。
