### ISSUE TITLE
是否支持添加自定义字号大小

### ISSUE THREAD

**Issue by wanmaoor** [wangeditor-team/wangEditor#3830]
## 问题描述

看了v5版本关于字号的文档, 有一个疑问:
该版本是否支持添加自定义的字号大小, 比如要配置一个100px的字号
```ts
const editorConfig: Partial<IEditorConfig> = { MENU_CONF: {} }

editorConfig.MENU_CONF['fontSize'] = {
    fontSizeList: ['12px', '16px', '24px', '40px', '100px']
}
```
能否成功配置呢?

## wangEditor 版本

v5新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
可以支持。
