### ISSUE TITLE
使用txt.html回显数据，换行符丢失

### ISSUE THREAD

**Issue by GHwangxingren** [wangeditor-team/wangEditor#3832]
使用txt.html回显数据，会触发两次onchange，并且换行符丢失

**Comment by wangfupeng1988** [comment]
请按照 issue 模板格式，重新提交。
非模板格式的不予受理。

**Comment by liuxiaobina** [comment]
<template>
  <div>
    <div ref="editor" class="editor-wrapper"></div>
  </div>
</template>

<script>
import WEditor from "wangeditor";
const config = [
  "head",
  "bold",
  "fontSize",
  "fontName",
  "italic",
  "underline",
  "strikeThrough",
  "indent",
  "lineHeight",
  "foreColor",
  "backColor",
  "link",
  "list",
  "todo",
  "justify",
  "quote",
  "emoticon",
  "table",
  "code",
  "splitLine",
  "undo",
  "redo"
];
export default {
  name: "WangEditor",
  model: {
    event: "change",
    prop: "value"
  },
  props: {
    // eslint-disable-next-line
    value: {
      type: String
    }
  },
  data() {
    return {
      editor: null,
      editorContent: null
    };
  },
  watch: {
    value(val) {
      this.editorContent = val;
      this.editor.txt.html(val);
    }
  },
  mounted() {
    this.initEditor();
  },
  methods: {
    initEditor() {
      this.editor = new WEditor(this.$refs.editor);
      this.editor.config.menus = config;

      // this.editor.onchangeTimeout = 200
      this.editor.config.onchange = html => {
        this.editorContent = html;
        this.$emit("change", this.editorContent);
      };
      this.editor.create();
    }
  }
};
</script>

<style lang="scss" scoped></style>
这样封装的 换行不会显示有问题

**Comment by liuxiaobina** [comment]
`<template>
  <div>
    <div ref="editor" class="editor-wrapper"></div>
  </div>
</template>

<script>
import WEditor from "wangeditor";
const config = [
  "head",
  "bold",
  "fontSize",
  "fontName",
  "italic",
  "underline",
  "strikeThrough",
  "indent",
  "lineHeight",
  "foreColor",
  "backColor",
  "link",
  "list",
  "todo",
  "justify",
  "quote",
  "emoticon",
  "table",
  "code",
  "splitLine",
  "undo",
  "redo"
];
export default {
  name: "WangEditor",
  model: {
    event: "change",
    prop: "value"
  },
  props: {
    // eslint-disable-next-line
    value: {
      type: String
    }
  },
  data() {
    return {
      editor: null,
      editorContent: null
    };
  },
  watch: {
    value(val) {
      this.editorContent = val;
      this.editor.txt.html(val);
    }
  },
  mounted() {
    this.initEditor();
  },
  methods: {
    initEditor() {
      this.editor = new WEditor(this.$refs.editor);
      this.editor.config.menus = config;

      // this.editor.onchangeTimeout = 200
      this.editor.config.onchange = html => {
        this.editorContent = html;
        this.$emit("change", this.editorContent);
      };
      this.editor.create();
    }
  }
};
</script>

<style lang="scss" scoped></style>
`
