### ISSUE TITLE
粘贴文章前将编辑器格式设置为H1-H5中任一格式，粘贴后全选文章，无法将其修改为正文，且居中有问题。

### ISSUE THREAD

**Issue by wangjingruliu** [wangeditor-team/wangEditor#3833]
## bug 描述

编辑器中内容为空时，若将编辑器格式设置H1-H5中任一格式后粘贴文章，粘贴后全选文章，”H“按钮变为蓝色，无法将文章格式修改为正文；且选中某段文字居中，全篇文章均居中。

## 你预期的样子是？

1.全选文章后，能将格式修改为正文。
2.仅选中的内容居中。

## 浏览器及版本号

*Google Chrome：版本 96.0.4664.110（正式版本） (x86_64)*

## wangEditor 版本

*wangEditorV4*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：打开编辑器，将编辑器格式设置为H2格式；
- 步骤二：粘贴文章；
- 步骤三：全选文章，”H“按钮变为蓝色，点击”H“按钮，选中“正文”；
- 步骤四：选中首行，设置为“居中”格式。

**Comment by wangfupeng1988** [comment]
V4 粘贴的奇怪问题有挺多，不太好排查（因为 V4 是基于 html 操作的，而 html 格式过于灵活 ）

你可以试试 V5 的粘贴是否正常 https://www.wangeditor.com/demo/zh-CN/ ，以后会发布 V5 并替换掉 V4
