### ISSUE TITLE
回车换行没有生成p标签 生成了br标签 对图片进行居中对齐 后面得文字也跟着居中对齐

### ISSUE THREAD

**Issue by swanghao** [wangeditor-team/wangEditor#3835]
## 问题描述
回车换行没有生成p标签 生成了br标签 对图片进行居中对齐 后面得文字也跟着居中对齐

## wangEditor 版本
4.7.11

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）
是

## 最小成本的复现步骤
![微信图片_20220113164616](https://user-images.githubusercontent.com/13250516/149296669-6cabc559-009c-4020-8fb8-fa64e54e09df.png)

**Comment by wangfupeng1988** [comment]
你这是两个问题。
第一，回车换行没有生成p标签 生成了br标签 。这个已经在官网复现了，如下图。会作为 bug 修复。

![image](https://user-images.githubusercontent.com/9583120/149313388-b21b9622-44c5-4bbe-9bd8-3709f9069828.png)


第二，对图片进行居中对齐 后面得文字也跟着居中对齐 —— 如果图片和文字在同一个 `<p>` 那这就符合预期了。**居中，目前只能对 `<p>` 设置，不能单独对 `<img>` 设置**。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
