### ISSUE TITLE
editor.txt.html()获取到的值怎么写入行内样式。因为要在iframe预览 只能通过对editor.txt.html()的值进行修改

### ISSUE THREAD

**Issue by cyfdegit** [wangeditor-team/wangEditor#3837]
## 问题描述

*editor.txt.html()获取到的值是什么数据类型 因为table标签默认没有样式 replace正则替换不了table样式*

## wangEditor 版本

*4.7.11*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- editorRef?.current?.editor?.txt.html()获取到html结构
- replace对获取的html中全局table写入样式
- 无法实现，有别的方案可以实现吗

**Comment by wangfupeng1988** [comment]
对于 `<table>` 不支持行内样式。
需要你自行处理 html ，自己加样式，这也不麻烦。

**Comment by cyfdegit** [comment]
直接引css文件这个我文档上看过了 我是想要弄成行内的。不然iframe里面接受不到样式 但是这个html结构我用replace无法替换

**Comment by wangfupeng1988** [comment]
自行处理 html 就行，思路如下
- 把 html 转换为 DOM 节点
- 找到 table 节点，设置 CSS 样式
- 再产出新的 html
