### ISSUE TITLE
ts node 生成 html标签不包含具体内容

### ISSUE THREAD

**Issue by chuck-ma** [wangeditor-team/wangEditor#3838]
## bug 描述

node 使用 ts  获取 editor的 html值，只能拿到 标签字符串 : `<p><br></p>`

## 你预期的样子是？

得到html: `<p><span>class 组件 - 基本使用</span></p>`

## 浏览器及版本号

node
nvm use v14.17.1

## wangEditor 版本

"dependencies": {
    "@wangeditor/editor": "^0.13.6"
  }

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

```ts
import { createEditor } from '@wangeditor/editor';
const anyThing: any = {
  type: 'paragraph',
  children: [
    {
      text: 'class 组件 - 基本使用',
    },
  ],
};

const editor = createEditor({
  content: [
    anyThing,
  ], // 初始化内容
  mode: 'default',
});
const htmlStr = editor.getHtml();
console.log(htmlStr);
```

**Comment by wangfupeng1988** [comment]
这跟 ts 和 js 没关系。你随便用一个 js demo 看能复现吗

```js
const editor = createEditor({
      selector: '#editor-text-area',
      config: editorConfig,
      content: [
        {
          type: 'paragraph',
          children: [{ text: 'hello' }]
        }
      ],
    })
    console.log(editor.getHtml()) // '<p>hello</p>
```

**Comment by chuck-ma** [comment]
@wangfupeng1988 只用 nodejs没法复现，原因是缺少 document之类的global对象

**Comment by wangfupeng1988** [comment]
抱歉我一开始看错了，忽略了 nodejs 的环境。我试了一下，在 nodejs 环境下复现了。

这个问题很严重，我周末紧急看一下吧。

**Comment by chuck-ma** [comment]
经过一番debug 后，发现 问题主要出在 styleToHtml这个函数上了。
现在 github的主分支的styleToHtml函数 看起来是没问题的。

有问题的是当前 发布的 0.26版本的 函数，因为代码经过打包，不太好看， anyway， 这个函数大概是下面这样：
 styleToHtml: function (e, t) {
          if (!o.Text.isText(e)) return t;
          var n = e, r = n.bold, a = n.italic, u = n.underline, s = n.code, c = n.through, l = n.sub, f = n.sup, d = i.$(t), p = d.html() || "<br>";
          return (r && (p = "<strong>" + p + "</strong>"), s && (p = "<code>" + p + "</code>"), a && (p = "<em>" + p + "</em>"), u && (p = "<u>" + p + "</u>"), c && (p = "<s>" + p + "</s>"), l && (p = "<sub>" + p + "</sub>"), f && (p = "<sup>" + p + "</sup>"), d.html(p), oo(d));
        }

然后debug就有种难以下手的感觉了。

**Comment by wangfupeng1988** [comment]
@chuck-ma 你说的 styleToHtml 源码在这里 https://github.com/wangeditor-team/wangEditor-v5/blob/main/packages/basic-modules/src/modules/text-style/style-to-html.ts

我会根据你的提示继续看看

**Comment by chuck-ma** [comment]
`/**
 * @description textStyle to html
 * @author wangfupeng
 */

import { Text, Descendant } from 'slate'
import $, { getOuterHTML } from '../../utils/dom'
import { ColorText } from './custom-types'

/**
 * style to html
 * @param textNode slate text node
 * @param textHtml text html 格式如 `<span ...>xxx</span>`
 * @returns styled html
 */
export function styleToHtml(textNode: Descendant, textHtml: string): string {
  if (!Text.isText(textNode)) return textHtml

  const { color, bgColor } = textNode as ColorText
  if (!color && !bgColor) return textHtml

  // 设置样式
  const $text = $(textHtml)
  if (color) $text.css('color', color)
  if (bgColor) $text.css('background-color', bgColor)

  // 输出 html
  return getOuterHTML($text)
}
`
这段代码是没问题的，我在康康问题出在哪

**Comment by wangfupeng1988** [comment]
我找到原因了，是因为 nodejs 环境下无法初始化 DOM 结构。

![image](https://user-images.githubusercontent.com/9583120/149622422-a028c52b-a184-4482-b0bb-e2f8d1316bd4.png)

解决方案我正在搞

**Comment by wangfupeng1988** [comment]
我周末看了两天，发现目前没有更好的解决方案。因为各个地方的 toHtml 免不了要用到 DOM 操作，而 nodejs 对其支持并不好，或者说没有办法做到同样的代码，兼容浏览器和 nodejs 的 DOM 操作。
所以，目前看来没有办法通过 nodejs 转换 html 了，等会儿我就去改一改文档。

之前是我们测试不全面，以为 nodejs 转 html 正常的。在你这个 issue 提醒下，才发现这里的问题。对此表示非常的抱歉~

不过，好消息时：回显 html 已经在测试中了，计划在一周之后发布，参考 https://github.com/wangeditor-team/wangEditor-v5/issues/351 。到时你需需要存储 html 即可，不用存储 JSON content 。

**Comment by wangfupeng1988** [comment]
问题我先关闭，有疑问或建议可继续跟我讨论。

**Comment by chuck-ma** [comment]
@wangfupeng1988 能否支持 后端的ts 呢，或者用 node 的jsdom来做这个事。因为我们需要在后端动态修改 json数据，存储html，这事就没法做了

**Comment by chuck-ma** [comment]
我大概有个思路了，就执行前先看下环境是不是node，如果是的话全局注册一下 window这些对象，问题就搞定了，
example如下：
`import 'global-jsdom/register';

import {
  $,
  css,
  append,
  prepend,
  addClass,
  removeClass,
  hasClass,
  on,
  off,
  focus,
  attr,
  hide,
  show,
  parents,
  dataset,
  val,
  text,
  removeAttr,
  children,
  html,
  remove,
  find,
  width,
  height,
  Dom7Array,
} from 'dom7';

export { Dom7Array } from 'dom7';

$.fn.css = css;
$.fn.append = append;
$.fn.prepend = prepend;
$.fn.addClass = addClass;
$.fn.removeClass = removeClass;
$.fn.hasClass = hasClass;
$.fn.on = on;
$.fn.off = off;
$.fn.focus = focus;
$.fn.attr = attr;
$.fn.removeAttr = removeAttr;
$.fn.hide = hide;
$.fn.show = show;
$.fn.parents = parents;
$.fn.dataset = dataset;
$.fn.val = val;
$.fn.text = text;
$.fn.html = html;
$.fn.children = children;
$.fn.remove = remove;
$.fn.find = find;
$.fn.width = width;
$.fn.height = height;

function getOuterHTML($elem: Dom7Array) {
  const $div = $('<div></div>');
  $div.append($elem);
  return $div.html();
};

function styleToHtml(textHtml: string): string {
  const $text = $(textHtml);
  const innerHtml = $text.html() || '<br>';


  $text.html(innerHtml);

  // 返回最新 html
  return getOuterHTML($text);
}


const s : string = styleToHtml('<span>class 组件 - 基本使用</span>');
console.log(s);
`

**Comment by chuck-ma** [comment]
看上去上面的思路是可以跑通的

**Comment by chuck-ma** [comment]
我等会搞个 mr吧

**Comment by wangfupeng1988** [comment]
@chuck-ma 感谢你的反馈，我试着这样果然可以。不过你不用提交 mr ，在 nodejs 中设置即可

```js
require('global-jsdom/register')
const { createEditor } = require("@wangeditor/editor")

const editor = createEditor({
    content: [{"type":"paragraph","children":[{"text":"hello","color":"#eb903a","underline":true},{"text":" "},{"text":"world","bold":true},{"text":"~"}],"textAlign":"center"}],
})

console.log( editor.getHtml() )
```

**Comment by wangfupeng1988** [comment]
文档中我已经改过来了，参考这个来即可 https://www.wangeditor.com/v5/guide/display.html#content-%E8%BD%AC%E6%8D%A2%E4%B8%BA-html 

![image](https://user-images.githubusercontent.com/9583120/149659515-1b1e0ccb-c874-40bb-b7fb-2fa74e934c67.png)

再次感谢你对该问题的反馈，这个问题很重要~

**Comment by chuck-ma** [comment]
我有点担心这个jsdom的实现和browser的实现是否有差异，从而引发未知的bug

**Comment by chuck-ma** [comment]
我们现在在做 cms headless，你做的这个editor给了我们很多启发。 many thanks.

**Comment by wangfupeng1988** [comment]
> 我有点担心这个jsdom的实现和browser的实现是否有差异，从而引发未知的bug； wangeditor的单元测试是否会覆盖相关的场景呢

单元测试每个功能点都覆盖了，而且单元测试也是 jest + jsdom ，按目前情况评估不会有其他常规问题。至于那些非常怪异的异常情况，这谁都说不准。

反正你有问题就向我们提问，遇到这种重大 bug 我会第一时间处理。
下次来这提交问题 https://github.com/wangeditor-team/wangEditor-v5/issues
