### ISSUE TITLE
上传本地图片不支持超链接

### ISSUE THREAD

**Issue by zhangbengbeng** [wangeditor-team/wangEditor#3843]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
服务端返回 `href` 即可，参考 https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/01-%E9%85%8D%E7%BD%AE%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8E%A5%E5%8F%A3.html

**Comment by zhangbengbeng** [comment]
谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月15日(星期六) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 上传本地图片不支持超链接 (Issue #3843)





 
Closed #3843.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
