### ISSUE TITLE
V4如何支持shadow dom

### ISSUE THREAD

**Issue by tyy110171** [wangeditor-team/wangEditor#3846]
## 问题描述
我们目前是在shadow dom中使用，但是发现很多功能无法使用
*请输入遇到的问题...*
我们目前是在shadow dom中使用，但是发现很多功能无法使用，如何支持
## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
v4 将不再继续增加新特性了。
v5 现在支持 shadow dom http://106.12.198.214:8882/main/examples/shadow-dom.html （demo 还有点 css 问题，会继续处理）
