### ISSUE TITLE
建议在官网实例那加个按钮 可以显示content  跟html  这样方便用户对照看看对照查看是否是自己的问题

### ISSUE THREAD

**Issue by pupillxy** [wangeditor-team/wangEditor#3847]
比如我如果直接输入文字
![image](https://user-images.githubusercontent.com/41733945/149905613-fd8b3d91-24c1-402c-b89f-4b4f6bc83d09.png)
这个地方是没有空格的   但是当我设置字体大小后
![image](https://user-images.githubusercontent.com/41733945/149905798-161c4d4d-9e73-4ba8-ab99-621309c2812f.png)
就有了空格  不知道是不是content 的原因   
![image](https://user-images.githubusercontent.com/41733945/149905900-ae73ebee-8634-4602-ac57-d4edceebaaed.png)
这个地方是没有空格的 
这我也不知道算不算bug  
如果有那个按钮后   就可以看到 官方是否可以复现

**Comment by wangfupeng1988** [comment]
没太看懂你的问题。可以按照 issue 模板再修改一下。

**Comment by jl1178436585** [comment]
是实时预览功能吧
