### ISSUE TITLE
getHtml显示异常  

### ISSUE THREAD

**Issue by pupillxy** [wangeditor-team/wangEditor#3848]
## bug 描述

getHtml后 只显示图片  没有文字

![image](https://user-images.githubusercontent.com/41733945/149908794-dbcddc05-f232-457c-8248-1ac87b569dab.png)

![image](https://user-images.githubusercontent.com/41733945/149907246-a5cfdabb-574c-45b2-8be8-f76c168ac646.png)

然后想着直接用存content  跟html  方便一点
结果html  只要我设置字体  这个字前面 就有个空格

![image](https://user-images.githubusercontent.com/41733945/149908095-6314b8e5-3980-474e-9ec0-f46de9070ad8.png)
![image](https://user-images.githubusercontent.com/41733945/149908243-55d9cd58-2f29-4908-a441-043b71f88f00.png)
![image](https://user-images.githubusercontent.com/41733945/149908431-da20863b-cd30-4e42-b816-2ed9927e88a9.png)
![image](https://user-images.githubusercontent.com/41733945/149909063-d01d4090-292f-4292-b5ce-e6ba93c20293.png)

## 你预期的样子是？
转getHtml后字体显示出来 我就不用去存html了’

html不会因为设置了字体大小后  出现个空格

## wangEditor 版本

0.12.7

## 最小成本的复现步骤
跟上面图片一样  转之前是对的 转之后就不对了

**Comment by wangfupeng1988** [comment]
你第一个截图中的 JSON 数据是什么？贴到这里

**Comment by pupillxy** [comment]
> 你第一个截图中的 JSON 数据是什么？把文本贴到这里，不要截图

[{"type":"paragraph","children":[{"text":""},{"type":"image","src":"http://192.168.100.8:8022/upload/2022_01_12/2022_01_12_10_54_2331f8d2c510b948e440709f155a54d470.png","href":"http://192.168.100.8:8022/upload/2022_01_12/2022_01_12_10_54_2331f8d2c510b948e440709f155a54d470.png","alt":"","style":[],"children":[{"text":""}]},{"text":""}]},{"type":"paragraph","children":[{"text":""}]},{"type":"paragraph","children":[{"text":""}]},{"type":"paragraph","children":[{"text":""}]},{"type":"paragraph","children":[{"text":"我没有设置字体"}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]},{"type":"paragraph","children":[{"fontSize":"22px","text":"我设置了字体"}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]},{"type":"paragraph","children":[{"fontSize":"16px","text":""}]}]

**Comment by wangfupeng1988** [comment]
@pupillxy 我测试着是有内容的，随便搞一个最简单的 demo 即可，如下图

![image](https://user-images.githubusercontent.com/9583120/149921605-61ac63e1-f4b2-44ec-b643-d96374e09f83.png)

**Comment by pupillxy** [comment]
小程序的吗&nbsp; 我这 显示不对呀&nbsp; 代码也是一模一样&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月18日(星期二) 晚上6:39
收件人: ***@***.***&gt;; 
抄送: "(10E4W20) 活 动 中 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] getHtml显示异常   (Issue #3848)





 
@pupillxy 我测试着是有内容的，随便搞一个最简单的 demo 即可，如下图
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfupeng1988** [comment]
@pupillxy 不是小程序。编辑器只支持 PC 浏览器，不支持移动端。所以，`getHtml` 只能在 PC 浏览器中获取。

你可以下载 http://106.12.198.214:8882/main/examples/simple-mode.html 的源代码。把其中的 `content` 改成你的 JSON 数据，然后用 chrome 打开，就可以看到我截图的效果。

**Comment by pupillxy** [comment]
我在pc 有getHtml&nbsp; 然后获取的那个html&nbsp; 只要我设置字体大小 转出来就有个空格&nbsp; &nbsp;&nbsp; json 是没有的&nbsp; &nbsp;可以看看这个html 那个“我设置了字体”那行 前面是有空格<p&gt; ↵    <img src="http://192.168.100.8:8022/upload/2022_01_12/2022_01_12_10_54_2331f8d2c510b948e440709f155a54d470.png" alt="" data-href="http://192.168.100.8:8022/upload/2022_01_12/2022_01_12_10_54_2331f8d2c510b948e440709f155a54d470.png" style=""/&gt; ↵</p&gt; ↵<p&gt; ↵    <br/&gt; ↵</p&gt; ↵<p&gt; ↵    <br/&gt; ↵</p&gt; ↵<p&gt; ↵    <br/&gt; ↵</p&gt; ↵<p&gt;我没有设置字体</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 22px;"&gt;我设置了字体</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt; ↵<p&gt; ↵    <span style="font-size: 16px;"&gt;</span&gt; ↵</p&gt;


然后加上那个这个样式后&nbsp;
p, li, td, th, blockquote {
  white-space: pre-wrap; /* 显示空格 */
}

就这样了&nbsp;&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月19日(星期三) 上午9:49
收件人: ***@***.***&gt;; 
抄送: "(10E4W20) 活 动 中 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] getHtml显示异常   (Issue #3848)





 
@pupillxy 不是小程序。编辑器只支持 PC 浏览器，不支持移动端。所以，getHtml 只能在 PC 浏览器中获取。
 
你可以下载 http://106.12.198.214:8882/main/examples/simple-mode.html 的源代码。把其中的 content 改成你的 JSON 数据，然后用 chrome 打开，就可以看到我截图的效果。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
