### ISSUE TITLE
使用editor.config.placeholder放入html提示文字时，不能滚动

### ISSUE THREAD

**Issue by LiZisheng** [wangeditor-team/wangEditor#3849]
## 问题描述

使用editor.config.placeholder放入html提示文字，提示文字比较多超出当前框的高度，不能滚动

## wangEditor 版本

"wangeditor": "^4.7.11"

## 是否查阅了文档 ？

查阅文档https://www.wangeditor.com/doc/pages/01-%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8/07-placeholder.html?h=place

## 最小成本的复现步骤

- 工具栏和文本域分离
- 设置固定高度
- 设置html格式的提示文字，并使数量超出显示范围

**Comment by wangfupeng1988** [comment]
通过以下代码，并没有复现该问题

```html
<div>
    <div id="toolbar-container" class="toolbar"></div>
    <p>------ 我是分割线 ------</p>
    <div id="text-container" class="text"></div>
</div>

<script src="../dist/wangEditor.js"></script>
<script>
    const E = window.wangEditor
    const editor = new E('#toolbar-container', '#text-container')
    editor.config.placeholder = 'Type here...'
    editor.create()
</script>
```

![image](https://user-images.githubusercontent.com/9583120/150097574-a676d9a6-bc82-42c4-9028-e2ffd2d0e408.png)

**Comment by LiZisheng** [comment]
抱歉，没有描述清楚，不是内容没有滚动条而是placeholder不能滚动，限制了placeholer的展示量，示例如下：

**Comment by LiZisheng** [comment]
抱歉没有说清楚，不是内容不滚动，而是placehodler中的数量太多，editor内显示不下的时候不能滚动，代码及示例如下
`<style>
    .toolbar {
        border: 1px solid #ccc;
    }
    .text {
        border: 1px solid #ccc;
        height: 300px;
    }
</style>

<div>
    <div id="toolbar-container" class="toolbar"></div>
    <p>------ 我是分割线 ------</p>
    <div id="text-container" class="text"></div>
</div>

<script  src="https://cdn.jsdelivr.net/npm/wangeditor@latest/dist/wangEditor.min.js"></script>
<script>
    const E = window.wangEditor
    const editor = new E('#toolbar-container', '#text-container')
    editor.config.placeholder = 'Type here..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffffhere..\nyyyyyyyy\nfffffffff1111112222这里超出了显示范围'
    editor.create()
</script>`
![image](https://user-images.githubusercontent.com/44458337/150677039-a4fc0d5a-55cd-4dfe-ad3f-5c580f48e7b7.png)

在placehodler中放大量内容应该是一个比较小众的场景，我只是无意中碰到看有没有好的解决办法

**Comment by wangfupeng1988** [comment]
这种情况还不支持。placeholder 只支持一行。
