### ISSUE TITLE
v5版本不兼容Html编辑应该醒目提醒

### ISSUE THREAD

**Issue by aveyuan** [wangeditor-team/wangEditor#3850]
## 问题描述
看到v5就开始做了了。最后发现，必须要存储content才能编辑。这会导致以前只有html数据的版本不能够直接迁移。这种破坏性的变更，建议在主页里面醒目式的提醒。

**Comment by wangfupeng1988** [comment]
马上就能支持了，功能已经开发完了，再做最后的发布准备，就这 1-2 天了。
到时候会在 681464059 qq 群集体通知
