### ISSUE TITLE
表格复制问题

### ISSUE THREAD

**Issue by 6tJaCeF** [wangeditor-team/wangEditor#3851]
## 问题描述

表格复制过去样式没用

## wangEditor 版本

   "@wangeditor/editor": "^0.14.0",
    "@wangeditor/editor-for-react": "^0.6.20",

## 是否查阅了文档 ？
是

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 复制链接代码https://www.wangeditor.com/v5/guide/for-frame.html#%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8-2
- 步骤二  启动react
- 步骤三  从react粘贴

**Comment by wangfupeng1988** [comment]
目前还不支持表格样式。

后面会逐步支持，但需要一些时间。
