### ISSUE TITLE
缩进功能怎么修改？

### ISSUE THREAD

**Issue by zhxiaoyu123** [wangeditor-team/wangEditor#3854]
## 问题描述

缩进功能在v5的版本默认是padding-left: 32px，怎么修改为text-indent: 2em

## wangEditor 版本

"@wangeditor/editor": "^0.14.0",
"@wangeditor/editor-for-vue": "^0.6.13"

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 输入一段文字，选中后按缩进功能按钮
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
我这两天来搞一下吧。

**Comment by wangfupeng1988** [comment]
已修改，下载最新版试试
@wangeditor/editor: 0.14.0
