### ISSUE TITLE
表格處理問題

### ISSUE THREAD

**Issue by Richardleo** [wangeditor-team/wangEditor#3856]
## 问题描述

插入表格時，单元格的长度宽度可以实现用户自定义控制么

## wangEditor 版本

4.7.11

## 是否查阅了文档 ？

[（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）](https://www.wangeditor.com/doc/)

是

## 最小成本的复现步骤
插入表格

**Comment by wangfupeng1988** [comment]
目前不支持。

另外，[V5](https://www.wangeditor.com/v5/) 发布在即，V4 此后将不再升级任何功能。V5 目前也不支持你说的功能，但后面会陆续做出来，需要一些时间。
