### ISSUE TITLE
希望可通过设置 editor.config.pasteFilterStyle = false 来关闭样式过滤

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor#3860]
## 问题描述

*希望可通过设置 editor.config.pasteFilterStyle = false 来关闭样式过滤。v5版本看着像是没有支持*

## wangEditor 版本

*editor v5版本*
*wangeditor/editor-for-react最新版本*

## 是否查阅了文档 ？
![image](https://user-images.githubusercontent.com/13927744/151193215-2f491d1a-f9f2-4746-a61f-2a6773828616.png)

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤
在创建editor的时候，设置了editor.config.pasteFilterStyle = false
但是没有效果，点击查看没有pasteFilterStyle 的定义

**Comment by wangfupeng1988** [comment]
V5 可以使用 customPaste 来关闭粘贴样式 https://www.wangeditor.com/v5/guide/editor-config.html#custompaste

```js
const editorConfig = {}
editorConfig.customPaste = (editor, event) => {
    // event 是 ClipboardEvent 类型，可以拿到粘贴的数据
    // 可参考 https://developer.mozilla.org/zh-CN/docs/Web/API/ClipboardEvent

    const text = event.clipboardData.getData('text/plain') // 获取粘贴的纯文本
    if (text) {
        editor.insertText(text)
        return false
    }

    return true
}
```

**Comment by tangyouwo** [comment]
@wangfupeng1988 请问在customPaste 里自定义粘贴样式，是需要自己手动解析getData('text/html')得到的html原始字符串吗。
然后按自己想法，比如要给<span  style="font-size:20"> 这样的，改成h1标签。
是这样麽。那么，，请问手动解析的话，有例子麽。。。(´･ω･`)   不是特别知道如何手动解析html字符串。
要转成dom？还是直接正则 replace？

**Comment by wangfupeng1988** [comment]
@tangyouwo 你的思路没问题。

如果是简单的替换，用正则表达式没问题。如果比较复杂，建议转换为 DOM 然后操作。

**Comment by a15218378694** [comment]
> 

只拿纯文本的话, 不就丢失样式了吗 ? 该怎么保留样式呢
