### ISSUE TITLE
点击菜单栏显示panel之后tooltip-up不隐藏

### ISSUE THREAD

**Issue by claviering** [wangeditor-team/wangEditor#3861]
## bug 描述

点击菜单栏显示panel之后tooltip-up不隐藏，插入/关闭插入链接之后，链接的tooltip-up没有隐藏

## 你预期的样子是？

插入/关闭插入链接之后，链接的tooltip-up隐藏

## 浏览器及版本号

Chrome Version 97.0.4692.71 (Official Build) (arm64)

## wangEditor 版本

v4.7.11

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：点击菜单栏的链接
- 步骤二：输入文字，输入地址，点击插入

**Comment by wangfupeng1988** [comment]
你意思是，插入链接之后，菜单来的 tooltip 不隐藏，对吧？
如下图

![image](https://user-images.githubusercontent.com/9583120/151335877-f440cd8d-cc6b-44c9-89f1-204fb3712a03.png)

**Comment by claviering** [comment]
> wangeditor-team#3861

是的
