### ISSUE TITLE
建议内置一套默认主题，在展示编辑器table等标签时，可以直接显示边框，无需自己写样式

### ISSUE THREAD

**Issue by jl1178436585** [wangeditor-team/wangEditor#3866]
https://www.kancloud.cn/wangfupeng/wangeditor3/335775

![image](https://user-images.githubusercontent.com/9854795/151651272-5f5b75c1-0e93-41d8-84f2-c76f20e42be0.png)
上面文档中提到table等标签，需要自己写样式，像table,pre等标签，建议官方内置一套主题，就跟editor.md或者其他类型的富文本编辑器一样，使用者开箱即用，无需自己去写这样标签的样式

**Comment by wangfupeng1988** [comment]
主题不应该编辑器产出，应该展示的时候再设置。
