### ISSUE TITLE
Is there a way of getting it as a component for svelte framework ?

### ISSUE THREAD

**Issue by albu77** [wangeditor-team/wangEditor#3868]
Simply a question for experimenting it with Svelte.....

**Comment by wangfupeng1988** [comment]
Sorry, there is no svelte component yet.

**Comment by lizy-CZ** [comment]
有打算支持 svelte 吗？svelte 的数据趋势越来越好

**Comment by wangfupeng1988** [comment]
@lizy-CZ 当然想支持 svelte ，但目前还不会用 svelte 。
