### ISSUE TITLE
回显数据时首行有个空行

### ISSUE THREAD

**Issue by comxza** [wangeditor-team/wangEditor#3869]
## 问题描述
在回显数据时，在首行有个空行，如下图
![image](https://user-images.githubusercontent.com/21981010/152806869-eb7afc5b-1a62-4fc7-a686-8e7f36950584.png)
回显的数据格式如下图
![image](https://user-images.githubusercontent.com/21981010/152807158-a97d43b4-9da7-44da-b775-89a74768f0e4.png)
![image](https://user-images.githubusercontent.com/21981010/152807222-ef14d513-23f3-47c0-ab2a-d6b1f4d1b22f.png)

*请输入遇到的问题...*
问题是  按理说不应该存在空行呀？

## wangEditor 版本
0.14.3
*请输入内容……*

## 是否查阅了文档 ？
已查阅
（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- `[{\"type\":\"paragraph\",\"children\":[{\"text\":\"命令: 用于清空某表的数据 且让自增的id重新从0开始\",\"color\":\"rgb(51, 51, 51)\",\"bgColor\":\"rgb(255, 255, 255)\",\"fontSize\":\"14px\",\"fontFamily\":\"\\\"PingFang SC\\\", \\\"Microsoft YaHei\\\", \\\"Helvetica Neue\\\", Helvetica, Arial, sans-serif\"}]},{\"type\":\"pre\",\"children\":[{\"type\":\"code\",\"language\":\"sql\",\"children\":[{\"text\":\"truncate table 你的表名\"}]}]},{\"type\":\"paragraph\",\"children\":[{\"color\":\"rgb(51, 51, 51)\",\"bgColor\":\"rgb(255, 255, 255)\",\"fontSize\":\"14px\",\"fontFamily\":\"\\\"PingFang SC\\\", \\\"Microsoft YaHei\\\", \\\"Helvetica Neue\\\", Helvetica, Arial, sans-serif\",\"text\":\"注意：谨慎使用 truncate 命令，该命令执行后将清空数据表，且不可会滚。谨慎使用！！\"}]}]`
- 步骤二
- 直接使用此数据进行回显即可复现
- 步骤三

**Comment by wangfupeng1988** [comment]
使用你给的 JSON 内容初始化编辑器，没有出现首行空格。如下图

![image](https://user-images.githubusercontent.com/9583120/152939783-0b5e0628-7036-417d-9d4b-11a72c5d69c5.png)


代码如下

```js
const editor = E.createEditor({
      selector: '#editor-text-area',
      config: editorConfig,
      // content: window.content1,
      content: [{"type":"paragraph","children":[{"text":"命令: 用于清空某表的数据 且让自增的id重新从0开始","color":"rgb(51, 51, 51)","bgColor":"rgb(255, 255, 255)","fontSize":"14px","fontFamily":"PingFang SC, Microsoft YaHei, Helvetica Neue, Helvetica, Arial, sans-serif"}]},{"type":"pre","children":[{"type":"code","language":"sql","children":[{"text":"truncate table 你的表名"}]}]},{"type":"paragraph","children":[{"color":"rgb(51, 51, 51)","bgColor":"rgb(255, 255, 255)","fontSize":"14px","fontFamily":"PingFang SC, Microsoft YaHei, Helvetica Neue, Helvetica, Arial, sans-serif","text":"注意：谨慎使用 truncate 命令，该命令执行后将清空数据表，且不可会滚。谨慎使用！！"}]}],
      mode: 'simple'
    })
```

**Comment by comxza** [comment]
问题存在于，如果是初始化，没问题，但是在后端传递过来，通过此方法，传递就会出现
![image](https://user-images.githubusercontent.com/21981010/153157528-ee96e924-a3b3-44e3-b8f3-4ab2a62d2eae.png)

**Comment by wangfupeng1988** [comment]
@comxza `insertNode` 是插入节点。空白编辑器本身有一个默认的空行，再插入节点肯定保留这个空行。
如果想通过 API 覆盖内容，可参考 https://www.wangeditor.com/v5/guide/API.html#%E9%87%8D%E7%BD%AE%E5%86%85%E5%AE%B9

**Comment by wangfupeng1988** [comment]
如果你是异步获取内容，应该是异步创建编辑器。这样更好。
而不是先创建空白编辑器，再设置内容。
