### ISSUE TITLE
有序无序列表下，添加多个表格不生效

### ISSUE THREAD

**Issue by jianjun6668** [wangeditor-team/wangEditor#3873]
## 问题描述

新建一行无序列表，插入表格，第一次生效 后序再插入就不生效了

## wangEditor 版本

4.7.11

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

- 新建一行无序列表，插入表格
- 在这个表格下再次插入表格不生效

**Comment by wangfupeng1988** [comment]
`新建一行无序列表，插入表格` —— 无序列表中是无法插入表格的，请再详细描述这个操作步骤。

**Comment by jianjun6668** [comment]
https://user-images.githubusercontent.com/24822623/153321733-cd128bd5-dc61-4174-a05b-18f525358b68.mp4

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
