### ISSUE TITLE
M1芯片，Chrome最新版本，编辑器错误，从钉钉复制图片粘贴到编辑器中显示插入图片错误

### ISSUE THREAD

**Issue by lq920320** [wangeditor-team/wangEditor#3874]
## bug 描述

Chrome最新版本：Chrome 已是最新版本，版本 98.0.4758.80（正式版本） (arm64)；
错误：从钉钉复制图片粘贴到编辑器中显示插入图片错误

## 你预期的样子是？

预期正常插入

## 浏览器及版本号

*Chrome 已是最新版本，版本 98.0.4758.80（正式版本） (arm64)；*

## wangEditor 版本

*4.7.11*

## 官网能否复现该 bug ？

能，打开官网 `https://www.wangeditor.com/`，edge浏览器与火狐浏览器打开都是编辑器样式，但是最新的Chrome打开直接是页面，没有编辑器。
![image](https://user-images.githubusercontent.com/18696549/153326571-698db629-5c69-4de5-bbba-6cfb883a7833.png)
![image](https://user-images.githubusercontent.com/18696549/153326808-f7c40df8-ba6a-4dd0-afb0-3510d3168f6b.png)

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：打开官网即可

**Comment by wangfupeng1988** [comment]
问题在：这个 js 没加载成功，如下图

![image](https://user-images.githubusercontent.com/9583120/153332562-d875f7d4-bbf2-4c8f-ae76-d57dd01aa3af.png)

**Comment by lq920320** [comment]
> 

这个是官网，也会有这种问题吗

**Comment by wangfupeng1988** [comment]
你看下这个 js 的链接，引用的事 jsdeliver.net 网站的，国内某些用户是加载不到。

官网是部署到 github pages 的，这个在国内也不稳定，有人访问不到。
但国内没有免费的 pages 服务，所以没办法。

**Comment by lq920320** [comment]
@wangfupeng1988 

现在下载是可以了，官网也同样是编辑器模式了，但是在官网，直接通过复制图片，再粘贴，同样的会出错，别的同事windows电脑是可以的，所以不确定是编辑器的兼容问题还是钉钉复制的图片出现了问题，如果是钉钉出问题的话，那按理说，火狐或者edge都不会成功，但是奇怪的是，这两个浏览器都是可以成功的，所以还需要您给查下会不会有兼容的问题。

![image](https://user-images.githubusercontent.com/18696549/153333223-46dbad84-a42f-410e-92c4-3f3d9a8a1191.png)

![image](https://user-images.githubusercontent.com/18696549/153333094-b045c8cb-7aee-4897-9986-de0a2868a009.png)

**Comment by wangfupeng1988** [comment]
@lq920320 用这个 demo 试试呢？
http://106.12.198.214:8881/dev/examples/upload-image.html

**Comment by lq920320** [comment]
> @lq920320 用这个 demo 试试呢？ http://106.12.198.214:8881/dev/examples/upload-image.html

![image](https://user-images.githubusercontent.com/18696549/153343732-1729ccff-eaf1-4139-b1e3-f723e7fb9fe3.png)
不行，这个demo有点问题

**Comment by wangfupeng1988** [comment]
http://106.12.198.214:8881/dev/examples/upload-image.html
你试试这个 demo ，上传图片的图片，可以吗？

我怀疑你本地网络有限制，访问不了这个上传 server API

**Comment by lq920320** [comment]
@wangfupeng1988 
我换了4GG网络，现在是可以上传本地的普通文件了，但是从钉钉聊天记录里复制的商品就不行 😵‍💫 报超时

![image](https://user-images.githubusercontent.com/18696549/153361938-0f3f1a8e-8329-4f5d-aeba-249c021cb748.png)

然后我换了一张小一点的图片，上传之后还是不可以，报上传错误，上传之后的图片链接如下：
`http://106.12.198.214:3000/upload-files/image-gq9.png`

![image](https://user-images.githubusercontent.com/18696549/153362624-0fd43b4e-b9aa-4b3b-a323-85d67431e7da.png)

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
