### ISSUE TITLE
图片上传前回调before的问题

### ISSUE THREAD

**Issue by zhangzejun123** [wangeditor-team/wangEditor#3875]
## 问题描述

我想在图片上传前将图片压缩后再上传，before(xhr, editor, resData){ } 我在参数中如何获取图片的文件呢，处理后的图片我如何继续上传呢？ 不知道可以这样做不，，，

## wangEditor 版本

v4.7.11

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

**Comment by wangfupeng1988** [comment]
不支持。

可以使用 `customUploadImg` https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/11-%E8%87%AA%E5%B7%B1%E5%AE%9E%E7%8E%B0%E4%B8%8A%E4%BC%A0%E5%8A%9F%E8%83%BD.html
