### ISSUE TITLE
想要实现导出为word文件功能，怎么实现呢，有没有内置的方法呢

### ISSUE THREAD

**Issue by yjun666** [wangeditor-team/wangEditor#3876]
## 问题描述

想要实现一个富文本编辑器导出word文件下载的功能

## wangEditor 版本

版本4.7.8

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
目前没有内置的方法。

可以通过 editor 获取 html 内容，然后自己实现到处 word 。

**Comment by littleforce163** [comment]
`可以通过 editor 获取 html 内容，然后自己实现到处 word 。`
html中的图片会不会丢失

**Comment by wangfupeng1988** [comment]
> `可以通过 editor 获取 html 内容，然后自己实现到处 word 。` html中的图片会不会丢失

导出方式正确，肯定是不会丢失的。html 导出 word 已经和编辑器无关了。

**Comment by mk-697** [comment]
有导出word的好的推荐案例吗，现在导出word.docx文件会丢失表格边框
