### ISSUE TITLE
@wangeditor/editor-for-react是否需要配置editorId？ 我发现在一个页面多个editor一起使用的时候，用AntDesign的Form组件赋值，只有最后一个editor赋值成功，前面的editor赋值不成功

### ISSUE THREAD

**Issue by ChuangShiOS** [wangeditor-team/wangEditor#3878]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
可使用 https://codesandbox.io/ 提供一个复现该 bug 的 demo

**Comment by ChuangShiOS** [comment]
不好意思 是我这边代码写的有问题 一个页面多个editor是没有问题的 
我写的demo：https://codesandbox.io/s/new-bird-2tl16?file=/src/App.js
不过我发现了一个问题：一个页面多个editor初始化没有任何操作的时候，最后一个editor会赋值“<p><br></p>”，前面editor是赋值“”。（重现方式：1、页面打开会有一个console信息；2、点击页面最后的“取值”按钮会有打印console信息）

**Comment by cao-lianhui** [comment]
初始化多个editor的时候最后一个自动获取了焦点，使用 getHtml 获取的内容是为"<p><br></p>"，你可以试试在其他 editor 获取焦点，点击取值 getHtml 获取的内容都是 "<p><br></p>"， 判断内容是否为空可以用 getText 获取，

> 不好意思 是我这边代码写的有问题 一个页面多个editor是没有问题的 我写的demo：https://codesandbox.io/s/new-bird-2tl16?file=/src/App.js `不过我发现了一个问题：一个页面多个editor初始化没有任何操作的时候，最后一个editor会赋值“<p><br></p>”，前面editor没有赋值。（重现方式：1、页面打开会有一个console信息；2、点击页面最后的“取值”按钮会有打印console信息）`

**Comment by cao-lianhui** [comment]
> 不好意思 是我这边代码写的有问题 一个页面多个editor是没有问题的 我写的demo：https://codesandbox.io/s/new-bird-2tl16?file=/src/App.js `不过我发现了一个问题：一个页面多个editor初始化没有任何操作的时候，最后一个editor会赋值“<p><br></p>”，前面editor没有赋值。（重现方式：1、页面打开会有一个console信息；2、点击页面最后的“取值”按钮会有打印console信息）`

初始化多个editor的时候最后一个自动获取了焦点，使用 getHtml 获取的内容是为``` "<p><br></p>"```，你可以试试在其他` editor 获取焦点，点击取值 getHtml 获取的内容都是 ```"<p><br></p>"```， 判断内容是否为空可以用 getText 获取，

**Comment by ChuangShiOS** [comment]
好的 谢谢了
