### ISSUE TITLE
peer @wangeditor/editor@"^0.14.0" from @wangeditor/editor-for-vue@5.1.8-7

### ISSUE THREAD

**Issue by Lingouzi** [wangeditor-team/wangEditor#3881]
## 问题描述
vue3 安装编辑器的时候出现错误

## wangEditor 版本
执行
`npm i @wangeditor/editor -S` 安装版本 "@wangeditor/editor": "^0.15.2",

vue 版本："vue": "^3.2.22",

继续执行安装 `@wangeditor/editor-for-vue@next` 出现错误
```
➜ npm i @wangeditor/editor-for-vue@next -S
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sc_portal@0.1.0
npm ERR! Found: @wangeditor/editor@0.15.2
npm ERR! node_modules/@wangeditor/editor
npm ERR!   @wangeditor/editor@"^0.15.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @wangeditor/editor@"^0.14.0" from @wangeditor/editor-for-vue@5.1.8-7
npm ERR! node_modules/@wangeditor/editor-for-vue
npm ERR!   @wangeditor/editor-for-vue@"5.1.8-7" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/ly/.npm/eresolve-report.txt for a full report.

```

**Comment by wbflike** [comment]
我也是一样的，不过我的是vue2
安装npm install @wangeditor/editor --save 正常不报错。
但是安装 npm install @wangeditor/editor-for-vue --save 报错
PS E:\code\vue_wangeditor_demo> npm install @wangeditor/editor-for-vue --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue_wangeditor_demo@0.1.0
npm ERR! Found: @wangeditor/editor@0.15.2
npm ERR! node_modules/@wangeditor/editor
npm ERR!   @wangeditor/editor@"^0.15.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @wangeditor/editor@"^0.14.0" from @wangeditor/editor-for-vue@0.6.13
npm ERR! node_modules/@wangeditor/editor-for-vue
npm ERR!   @wangeditor/editor-for-vue@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\W.GouDan\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\W.GouDan\AppData\Local\npm-cache\_logs\2022-02-14T02_31_17_744Z-debug.log

**Comment by liuqh0609** [comment]
刚才升级了对应的依赖，现在可以尝试重新安装一下。

如果还不行的话麻烦提供一下npm版本

**Comment by wbflike** [comment]
可以了 安装成功
