### ISSUE TITLE
复制粘贴图片bug

### ISSUE THREAD

**Issue by luoyanling98** [wangeditor-team/wangEditor#3884]
## bug 描述

*本地接口上传，复制粘贴文件都显示的是默认名称image.png，导致图片粘贴不了*

## 你预期的样子是？

*文件复制粘贴不是同一张*

## 浏览器及版本号

* 谷歌  版本号：98.0.4758.82*

## wangEditor 版本

*^4.7.9*

## 官网能否复现该 bug ？
不能
能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请描述：如何复现该问题。

因为 demo 是可以粘贴上传图片的 http://106.12.198.214:8881/dev/examples/upload-image.html
