### ISSUE TITLE
使用defaultHtml时，<p></p>标签内包含<br>标签 则该行不显示

### ISSUE THREAD

**Issue by DFive5** [wangeditor-team/wangEditor#3885]
## 问题描述

*使用defaultHtml时，`<p></p>`标签内包含`<br>`标签 则该行不显示*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
采用defaultHtml方式，当defaultHtml为`<p>一行文字<br/></p>`时，该行不会显示

**Comment by liuxiaobina** [comment]
我也有这个问题

**Comment by wangfupeng1988** [comment]
会和 https://github.com/wangeditor-team/wangEditor-v5/issues/389 这个问题一起解决。关注它的进度即可。
