### ISSUE TITLE
基于该库封装的编辑器回车不能换行

### ISSUE THREAD

**Issue by liuxiaobina** [wangeditor-team/wangEditor#3888]
## bug 描述
基于该库封装的编辑器回车不能换行

## 你预期的样子是？

期望能够排查问题，或者给我们一个解决方案

## 浏览器及版本号
谷歌浏览器

## wangEditor 版本

4.x

## 官网能否复现该 bug ？

 不能

## 最小成本的复现步骤
```
<template>
  <div>
    <div ref="editor" class="editor-wrapper"></div>
  </div>
</template>

<script>
import WEditor from "wangeditor";
const config = [
  "head",
  "bold",
  "fontSize",
  "fontName",
  "italic",
  "underline",
  "strikeThrough",
  "indent",
  "lineHeight",
  "foreColor",
  "backColor",
  "link",
  "list",
  "todo",
  "justify",
  "quote",
  "emoticon",
  "table",
  "code",
  "splitLine",
  "undo",
  "redo"
];
export default {
  name: "WangEditor",
  model: {
    event: "change",
    prop: "value"
  },
  props: {
    // eslint-disable-next-line
    value: {
      type: String
    }
  },
  data() {
    return {
      editor: null,
      editorContent: null
    };
  },
  watch: {
    value(val) {
      this.editorContent = val;
      this.editor.txt.html(val);
    }
  },
  mounted() {
    this.initEditor();
  },
  methods: {
    initEditor() {
      this.editor = new WEditor(this.$refs.editor);
      this.editor.config.menus = config;

      // this.editor.onchangeTimeout = 200
      this.editor.config.onchange = html => {
        this.editorContent = html;
        this.$emit("change", this.editorContent);
      };
      this.editor.create();
    }
  }
};
</script>

<style lang="scss" scoped></style>
```

这样封装的 换行不会显示有问题
vue 里面使用上述组件 v-model 双向绑定 enter 回车无效

**Comment by liuxiaobina** [comment]
> 在 [codesandbox](https://codesandbox.io/) 中做一下这个 demo 吧。
> 
> （每天处理 issue 太多，实在没精力挨个都重新搭建环境，还请体谅~）

您好，我这边有发给您例子，您这边收到了吗

**Comment by wangfupeng1988** [comment]
@liuxiaobina 可以打开。但没发现有编辑器。

**Comment by liuxiaobina** [comment]
https://codesandbox.io/s/withered-sun-jtw6k?file=/src/App.vue  失误了，看下这个

**Comment by liuxiaobina** [comment]
> https://codesandbox.io/s/withered-sun-jtw6k?file=/src/App.vue 失误了，看下这个

**Comment by liuxiaobina** [comment]
@wangfupeng1988 https://codesandbox.io/s/withered-sun-jtw6k?file=/src/App.vue 失误了，看下这个

**Comment by wangfupeng1988** [comment]
@liuxiaobina bug 已复现

**Comment by ding2650** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/58728634/154189786-4e5efac4-e199-40d9-9045-a020a92fb6bc.png">

@liuxiaobina  有点小疑问：内部已经实现了双向绑定，这个watch操作的目的是啥？（watch操作去掉就正常了）

**Comment by liuxiaobina** [comment]
> 

watch 主要作用是  this.editor.txt.html(val) ，比如你初始化的时候html（val），主要双向绑定就是为了方便使用，如果我用ref 去操作是没有bug，但是却让使用更加麻烦了，我本意是让作者提供下这个问题的思路，如果能够解决当然更好

**Comment by ding2650** [comment]
解决方案：去掉``watch``操作，在``initEditor``中添加初始化代码。
<img width="475" alt="image" src="https://user-images.githubusercontent.com/58728634/154450706-ba756d79-2882-4e7a-b14f-0313aaec1215.png">
原因：
下面这个操作会触发onchange，然后触发watch，vue中watch的优化执行机制（具体是什么，为什么只有换行会有问题我也不晓得）导致了这个问题。
<img width="448" alt="image" src="https://user-images.githubusercontent.com/58728634/154451436-e4f87763-0626-4d18-9e83-a563ad4f71cf.png">

ps: 可以在onchange中打印一下，会发现常规字符更新会触发两次，换行会触发四次。
不知道有没有帮到你。

**Comment by liuxiaobina** [comment]
> `watch`操作

去掉watch 之后 ，异步获取的数据 如何绑定初始化  编辑器的数据？  编辑器子组件 mounted 的生命周期已经走过了，不会再走了

**Comment by ding2650** [comment]
@liuxiaobina  https://codesandbox.io/s/vigilant-haslett-gf99je?file=/src/App.vue ，应该符合你描述的场景，把loading展示优化下就好。

**Comment by liuxiaobina** [comment]
> @liuxiaobina https://codesandbox.io/s/vigilant-haslett-gf99je?file=/src/App.vue ，应该符合你描述的场景，把loading展示优化下就好。

重复渲染没什么意义了，你这样我还不如ref 操作

**Comment by liuxiaobina** [comment]
> @liuxiaobina bug  基于这个问题 能否给一个官方的回复结论

**Comment by liuxiaobina** [comment]
@wangfupeng1988  这个问题能否给一个官方的结论，是不能这样双向绑定使用，还是说 这个库 底层代码可以优化下？

**Comment by wangfupeng1988** [comment]
> @wangfupeng1988 这个问题能否给一个官方的结论，是不能这样双向绑定使用，还是说 这个库 底层代码可以优化下？

我业余时间都在忙于 v5 版本的事情，尚未顾及这个问题。另外，v5 发布在即，v4 不会有太大的改动了。
