### ISSUE TITLE
卡片式链接

### ISSUE THREAD

**Issue by ysfuns** [wangeditor-team/wangEditor#3889]
## 超链接可以改为卡片链接的形式

*卡片式链接的优点：

在移动互联网的时代，有许多人通过智能手机浏览文章，通过卡片式链接打开新页面对他们更友好；
旧式的链接显示方式不够明显，很容易导致人们忽视了这是一条链接，卡片式链接能够突出显示，不容易被他人忽略；
许多平台，例如 Bilibili，知乎，微信公众号等平台，均有将链接转换为卡片式链接的功能，*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
知乎和微信公众号上面的很多,类似知乎上面有商品的超链接,都是占用比较大的空间,还有小图片,特别的醒目

**Comment by wangfupeng1988** [comment]
该功能早就记录了，正在排队开发中，还需要一些时间。

**Comment by wangfupeng1988** [comment]
v5 已经支持链接卡片 https://github.com/wangeditor-team/wangEditor-plugin-link-card

v5 发布在即，v4 不再升级功能了。
