### ISSUE TITLE
insertText， 在外部button添加click事件追加文本可以，换别的标签，比如div，则追加文本失败

### ISSUE THREAD

**Issue by luzhe0359** [wangeditor-team/wangEditor#3890]
## bug 描述

v5版本，内容处理：insertText， 在外部button添加click事件追加文本可以成功，换别的标签，比如div、span，则追加文本失败。且再次调用editor.focus() ，光标会移至初始位置。

## 你预期的样子是？

在外部事件处理函数中，调用 insertText，可以成功追加文本。再次调用editor.focus()，光标会聚焦至末尾位置。

## 浏览器及版本号

chrome 版本 98.0.4758.82（正式版本） （64 位）

## wangEditor 版本

"@wangeditor/editor": "^0.15.3",
"@wangeditor/editor-for-vue": "^0.6.14-0",
"wangeditor": "^4.7.11",

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 在外部新建button并绑定click事件，在click事件中insertText，追加文本成功
- 步骤二 在外部新建div并绑定click事件，在click事件中insertText，追加文本失败，editor.focus() ，光标会移至初始位置。

**Comment by luzhe0359** [comment]
editor.dangerouslyInsertHtml() , 也会出现同样的问题。

**Comment by wangfupeng1988** [comment]
给一个具体的 demo 吧，我需要看看你步骤二中追加的内容具体是什么。

**Comment by luzhe0359** [comment]
随意输入内容，再点击button/div  追加内容，即可复现bug。

另外，我想请教一下，@功能这部分有没有更具体的说明、或者demo。 




感谢！！！







在 2022-02-15 11:27:59，"王福朋" ***@***.***> 写道：

给一个具体的 demo 吧，我需要看看你步骤二中追加的内容具体是什么。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfupeng1988** [comment]
@ 功能，就是使用插件，监听 `insertText` ，然后弹出选择框。然后点击选择框某个 item ，再使用 `insertNode` 插入元素即可。

这个插件我后面会做出一个 demo ，但现在忙于搞数学公式插件，得过两天再弄。

**Comment by wangfupeng1988** [comment]
> 随意输入内容，再点击button/div  追加内容，即可复现bug。

请详细说明追加了什么内容。
