### ISSUE TITLE
官网DEMO 使用发现了BUG

### ISSUE THREAD

**Issue by CasualMing** [wangeditor-team/wangEditor#3891]
## bug 描述

在使用官网demo体验的时候，发现将有背景或者有颜色的文字删除之后，再输入文字，文字的颜色还是之前设置的颜色。

## 你预期的样子是？

文字删除完毕之后，再输入，文字颜色应该按照默认的来

## 浏览器及版本号

谷歌浏览器：版本 97.0.4692.71（正式版本） （32 位）

## wangEditor 版本

官网页面，最新展示demo，不确定是哪个版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  进入官网 https://www.wangeditor.com/
- 步骤二  删除这一段文字，但是不删除这一行，只是将文字删除
![image](https://user-images.githubusercontent.com/40878104/153980546-388e0a5f-1606-40f2-a43d-fcd9fe1a218a.png)
类似这种
![image](https://user-images.githubusercontent.com/40878104/153980599-1cbbad7f-1df2-4b91-b725-eb573a7bdc45.png)

- 步骤三  再输入文字，新输入的文字依然有之前的背景色
-![image](https://user-images.githubusercontent.com/40878104/153980645-43563eb8-54d3-4e3b-bce8-349f2cbd2a13.png)

**Comment by wangfupeng1988** [comment]
这个符合预期。腾讯文档也是这样的。
