### ISSUE TITLE
从EXCEL复制带有合并单元格的表格时，会在表格右侧显示多余的单元格

### ISSUE THREAD

**Issue by hugangyi110** [wangeditor-team/wangEditor#3892]
## bug 描述

从EXCEL复制带有合并单元格的表格时，会在表格右侧显示多余的单元格

## 你预期的样子是？

复制时不要显示多余的单元格

## 浏览器及版本号

双核浏览器
版本 3.0.1.6

## wangEditor 版本

5

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
在这里跟踪 https://github.com/wangeditor-team/wangEditor-v5/issues/390
