### ISSUE TITLE
v5回调文件对象遇到一个问题

### ISSUE THREAD

**Issue by zhangzejun123** [wangeditor-team/wangEditor#3894]
## 问题描述

我在onbefore 回调时我看那个files的格式说明时{ke1:file1, key2:file2},但是我下断点时 看到的files只有一个文件对象，我在选择多个文件时如何获取到全部对象呢？
![image](https://user-images.githubusercontent.com/29722834/154398642-367e59c8-50cd-4d7b-8aca-60bcd1f91ee1.png)

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
已经复现，会尽快解决。

**Comment by wangfupeng1988** [comment]
> 已经复现，会尽快解决。

我看错了，这并不是 bug 。多个文件上传，是分开一个一个上传的，因此会触发多次 `onBeforeUpload` ，你再仔细 debug 看看。

**Comment by zhangzejun123** [comment]
> > 已经复现，会尽快解决。
> 
> 我看错了，这并不是 bug 。多个文件上传，是分开一个一个上传的，因此会触发多次 `onBeforeUpload` ，你再仔细 debug 看看。

好的，我发现了，建议修改一下文档，容易引起误解。。。还有就是我记得v4的时候上传多个图片只调用一次接口，刚刚换到v5发现他是按照你说的一样有几张就调用几次后台接口，感觉v4那种方式更合理一点点，但是v5能获取到文件对象也很好用，希望后期综合一下

**Comment by wangfupeng1988** [comment]
v4 那样会有一个问题：一次性上传，不太好保证多个图片的顺序。
v5 分开上传，就可按照顺序来。

文档我会去修改。

**Comment by zhangzejun123** [comment]
> 

嗯，好的。谢谢！
