### ISSUE TITLE
插入多张图片时图片报错显示502，但是图片链接是没问题的 提示插入插入图片错误

### ISSUE THREAD

**Issue by Wsqwangsiqi** [wangeditor-team/wangEditor#3896]
## 问题描述

*插入多张图片时图片报错显示502，但是图片链接是没问题的 提示插入插入图片错误*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

1.上传多张图片，若干图片会显示502
![image](https://user-images.githubusercontent.com/31403668/154425838-8cfb7766-971d-4e13-9c5c-8834410e721b.png)
![image](https://user-images.githubusercontent.com/31403668/154425935-d73cc472-138b-4868-ad56-0f46545231b6.png)
![image](https://user-images.githubusercontent.com/31403668/154426007-20707147-a17a-459c-b070-df67db9ffde7.png)
但是图片链接是没问题的

**Comment by wangfupeng1988** [comment]
v3 早就不维护了。考虑升级到 v5 吧 https://www.wangeditor.com/v5/
