### ISSUE TITLE
获取HTML内容时，发现没有内联样式

### ISSUE THREAD

**Issue by RiCTT** [wangeditor-team/wangEditor#3897]
## 问题描述

获取HTML内容时，发现没有内联样式，查阅过文档发现时不提供这个功能，需要自定义样式；这样子的话意味我要从源码里面拷贝一份，然后放在我自己的项目当中，这算是一个解决办法，保证了编辑跟显示的样式统一；但是！如果哪天编辑器更新了新的样式，而我的项目还是旧版的样式代码，就失去了样式统一；建议：是否可以提供一个官方处理过的维护的css文件，通过npm或者cdn的方式去使用呢？

## wangEditor 版本

4.7.11

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

无

**Comment by wangfupeng1988** [comment]
V4 不再改动了。

V5 已经把 js 和 css 单独分离了。
