### ISSUE TITLE
希望上传图片，可以设置图片宽高的功能

### ISSUE THREAD

**Issue by 15655117358** [wangeditor-team/wangEditor#3899]
## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
请按照 issue 模板，说明详细的需求。再重新提交一个 issue 。

还有，针对 v4 还是 v5 ？

需求不明确，我也不知道怎么设计。
