### ISSUE TITLE
wangEditorV4版本 length判断有问题

### ISSUE THREAD

**Issue by duzuimoye** [wangeditor-team/wangEditor#3902]
## wangEditorV4版本 length判断有问题

*因为富文本编辑器要限制长度、所以增加了validator校验*
代码如下
```
                      rules={[
                            { required: true, message: '请输入协议内容' },
                            {
                                validator: (rule, value, callback) => {
                                    console.log(value?.length, '长度')
                                    if (value?.length > 5000) {
                                        callback(new Error('协议内容字数不能超过5000字'))
                                    } else {
                                        callback()
                                    }
                                }
                            }
                        ]}
```
打印出来、发现length不对劲、输入一个字、长度竟然是8 我换行之后长度变化也很奇怪。
麻烦大佬解惑一下。
![image](https://user-images.githubusercontent.com/37163594/154782752-2c2e5feb-f867-4bf4-a531-5f38dee672a6.png)

**Comment by wangfupeng1988** [comment]
它检测的可能是 html 的长度。
这个插件我也不熟悉，能否让它检测 text 纯文本的长度？

**Comment by duzuimoye** [comment]
> 它检测的可能是 html 的长度。 这个插件我也不熟悉，能否让它检测 text 纯文本的长度？

我找到原因了、检测的还是把div p标签都算上了。但是呢、我总不能写个正则把它去掉吧、万一用户自己输入的内容是"<div>11111"这种呢？

**Comment by wangfupeng1988** [comment]
或者你可以考虑一下 v5 版本，v5 自带了 maxlength 检测 https://www.wangeditor.com/v5/guide/editor-config.html#maxlength-onmaxlength

**Comment by duzuimoye** [comment]
> 或者你可以考虑一下 v5 版本，v5 自带了 maxlength 检测 https://www.wangeditor.com/v5/guide/editor-config.html#maxlength-onmaxlength

V5 不是还在公测中吗？我怕有问题。

**Comment by wangfupeng1988** [comment]
@duzuimoye v5 已经公测好几个月了，目前已经稳定了。而且 v5 真遇到一些比较严重的问题，我会第一时间修复的。

你应该怕 v4 才对，因为 v5 发布之后，v4 就不再维护了。
