### ISSUE TITLE
更换工具栏按钮图标

### ISSUE THREAD

**Issue by fallling** [wangeditor-team/wangEditor#3904]
## 功能描述

*在项目中需要根据界面UI更换菜单图标*

**Comment by wangfupeng1988** [comment]
哪个版本？

**Comment by fallling** [comment]
"wangeditor": "^4.7.11"

**Comment by wangfupeng1988** [comment]
v4 的菜单图片是用 css 控制的，你直接重写对应的 css 即可。

**Comment by shijie-todd** [comment]
> v4 的菜单图片是用 css 控制的，你直接重写对应的 css 即可。

大佬请问下V5的如何换图标，用{key: '', svgIcon:}的方式会多一个下拉
