### ISSUE TITLE
目前引用功能 只能一次引用一行内容吗，换行会有间隙（体验上不是很好）。建议支持一下一次引用的时候可以引用多行

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor#3905]
## 功能描述
目前引用功能 只能一次引用一行内容吗，换行会有间隙。
建议支持一下一次引用的时候可以引用多行，在引用退出的时候，不要按下回车就退出，按下回车的时候判断当前行是否是空行 （参考了下qq文档、语雀、飞书等文档都用这个方式，可能用户习惯上也比较习惯这个）

## 原型图
![image](https://user-images.githubusercontent.com/13927744/154957669-146be934-38da-417a-ba62-50686b10cb58.png)

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
好建议！记录下了，后面会陆续做起来。

不过，这种功能优化只会在 v5 升级，v5 马上就正式发布了，所以 v4 不会在升级了。
个人精力有限，还请体谅~

**Comment by wangfupeng1988** [comment]
v5 最新版本已经支持该功能
https://www.npmjs.com/package/@wangeditor/editor
