### ISSUE TITLE
插入代码

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#3906]
## 问题描述
使用编辑器 插入代码的功能，我插入的代码类型为 Html，代码里如果带html标签的话，编辑器不给解析html标签

## wangEditor 版本
最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 点击 代码，类型选择 Html
- 步骤二
- 输入带 html标签 的内容，最后显示出来的时候标签不解析
- 步骤三
- 官网可以重现

**Comment by wangfupeng1988** [comment]
第一，你用的具体是哪个版本？v4 还是 v5
第二，你报错的 html 代码具体是什么？

**Comment by zxueliang** [comment]
一、使用的是v4最新版本
二、不报错，就是我使用咱们的编辑器 插入代码的功能，我插入的类型是html，代码里有html标签，显示的时候还是显示html标签，html标签不给解析

**Comment by wangfupeng1988** [comment]
html 代码具体是什么？

**Comment by zxueliang** [comment]
“<span>123456</span>”，显示的时候，还是这个，不解析<span>

**Comment by wangfupeng1988** [comment]
你截图这个没啥问题，符合预期。

我理解，你的意思应该是，插入代码，就应该当做 html 源代码解析了，对吧？
但该功能不是这样的，插入什么代码就直接显示纯文本，不会解析的。

你可以去参考其他富文本编辑器，插入代码都是仅仅展示，不会解析。
如果解析，那就是 XSS 攻击了，很危险。

**Comment by zxueliang** [comment]
在 点击 插入按钮的时候，有什么事件可以进行调用吗，我来自定义插入代码的内容

**Comment by zxueliang** [comment]
![22](https://user-images.githubusercontent.com/39672406/155053415-ae5550a0-d459-4964-9100-ea78cd065df4.png)
在 点击 这个插入按钮的时候，有什么事件可以进行调用吗，然后来修改输入代码的内容

**Comment by wangfupeng1988** [comment]
你想插入 html 代码，不是在这里搞。

你可以执行 API `editor.cmd.do('insertHTML', '<p>...</p>')` 来插入，参考 https://www.wangeditor.com/doc/pages/08-%E5%B8%B8%E7%94%A8API/03-%E5%86%85%E5%AE%B9%E6%93%8D%E4%BD%9CAPI.html
