### ISSUE TITLE
pnpm下peer依赖报错，麻烦升级一下包

### ISSUE THREAD

**Issue by robin901118** [wangeditor-team/wangEditor#3907]
## 问题描述

pnpm最新版会对peer进行检测,不正确则出现警告，作者这边几个插件出现问题，如下

警告提示：
 WARN  Issues with peer dependencies found
.
└─┬ @wangeditor/editor
  ├─┬ @wangeditor/basic-modules
  │ └── ✕ unmet peer @wangeditor/core@^0.7.1: found 0.14.9 in @wangeditor/editor
  ├─┬ @wangeditor/code-highlight
  │ └── ✕ unmet peer @wangeditor/core@^0.7.1: found 0.14.9 in @wangeditor/editor
  ├─┬ @wangeditor/list-module
  │ └── ✕ unmet peer @wangeditor/core@^0.7.1: found 0.14.9 in @wangeditor/editor
  ├─┬ @wangeditor/table-module
  │ └── ✕ unmet peer @wangeditor/core@^0.7.1: found 0.14.9 in @wangeditor/editor
  ├─┬ @wangeditor/upload-image-module
  │ ├── ✕ unmet peer @wangeditor/core@^0.7.1: found 0.14.9 in @wangeditor/editor
  │ └── ✕ unmet peer @wangeditor/basic-modules@^0.9.0: found 0.11.5 in @wangeditor/editor
  └─┬ @wangeditor/video-module
    └── ✕ unmet peer @wangeditor/core@^0.7.1: found 0.14.9 in @wangeditor/editor

## wangEditor 版本

0.15.8

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

pnpm add @wangeditor/editor

**Comment by wangfupeng1988** [comment]
好，我们看看
