### ISSUE TITLE
内容区域的粘贴事件和超链接输入框的粘贴事件冲突

### ISSUE THREAD

**Issue by OnePsycho** [wangeditor-team/wangEditor#3908]
## 问题描述

对富文本进行了粘贴事件的监听，但是内容区域的粘贴事件和超链接输入框的粘贴事件冲突，我希望在超链接的地方粘贴不会触发监听事件该如何处理呢，是否有API判断当前是在编辑正文还是工具栏？
![image](https://user-images.githubusercontent.com/43296632/155055895-1a64b972-2796-472d-a568-e23ed826060f.png)

## wangEditor 版本
4

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

自定义粘贴事件

**Comment by wangfupeng1988** [comment]
`内容区域的粘贴事件和超链接输入框的粘贴事件冲突` —— 这个具体什么意思？给一个例子说明吧。

**Comment by OnePsycho** [comment]
> `内容区域的粘贴事件和超链接输入框的粘贴事件冲突` —— 这个具体什么意思？给一个例子说明吧。

就是我对编辑器进行了粘贴事件监听（我只想对正文进行粘贴监听），如图所示，然后我在工具栏-超链接-粘贴网址 我不想触发监听的事件

![image](https://user-images.githubusercontent.com/43296632/155060709-408bc1f0-224c-45a0-8d00-48c510e5cede.png)

**Comment by wangfupeng1988** [comment]
那你判断一下 `e.target` 如果是 `<input>` 就忽略。

**Comment by OnePsycho** [comment]
感谢 已解决！
