### ISSUE TITLE
用户反馈从word粘贴过来的文本莫名换行或者莫名挤在一起

### ISSUE THREAD

**Issue by DwbpleaseCallMe** [wangeditor-team/wangEditor#3909]
## bug 描述

因为我们的文章要支持\n换行，所以我给富文本加了{white-space：break-spaces}；这个样式；然后很多用户反馈从word粘贴到富文本里文章会莫名的换行，有的用户反馈是文章都挤在一起了。我用的mac系统，测了一遍都正常，用win10的office测出了粘贴上来的文章会莫名的换行，至于文章都挤在一起就不知道是什么原因导致的了，用户回复我们的频率也比较低，想问下wang对于系统和word粘贴的兼容性

## 你预期的样子是？

完美还原word粘贴的样式

## 浏览器及版本号

谷歌
## wangEditor 版本

4.6
## 官网能否复现该 bug ？

能
## 最小成本的复现步骤
1.对editor加white-space：break-spaces这个css；
2.用win10的office 写一段英文。带标点
3.复制office文章 到editor粘贴

**Comment by DwbpleaseCallMe** [comment]
现在就是不了解各个word粘贴过来的标签都是什么  我在后台看 有的是br标签 有的是p标签 有的是\n标签  对于office 那个bug，我看到粘贴过来的样式里有很多 \r\n标签导致的换行，正常换行他都是走的p标签  于是我是在粘贴的时候把\r\n标签都给替换成了掉空格；
结果第二天 又多了很多文章挤在一起的问题，我看该用户的文章之前都是br换行的，我只改动了\r\n  应该不会影响他的，也没复现出来他是怎么操作的。现在一直在试图联系作者。只是联系的效率很慢，看看大家有么有遇到这个问题

**Comment by wangfupeng1988** [comment]
v4 现在对于 word 文档的粘贴没有做太多优化

v5 目前也没有优化太多，后面会慢慢做起来。word 文档格式非常多，全部兼容起来需要耗费大量的精力。

**Comment by DwbpleaseCallMe** [comment]
加油。
