### ISSUE TITLE
希望在插入/上传图片时可自定义图片node的一些属性

### ISSUE THREAD

**Issue by DOVE-PH** [wangeditor-team/wangEditor#3910]
## 功能描述

*使用入/上传图片时insertFn函数自动生成的格式如下：` <img src="xxxx" alt="" data-href="" style=""/>`。
但有时希望在传入的alt,href参数为null | undefined | '' 等情况时不要自动生成alt和href属性？
另外经常会要对图片的大小/样式等属性进行自定义，是否可以直接传入node的html代码，这样要传什么属性都可以自定义？*

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

**Comment by wangfupeng1988** [comment]
第一，配置上 customInsert https://www.wangeditor.com/v5/guide/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8F%92%E5%85%A5

第二，在其中不要执行 `insertFn` ，而是获取 editor 实例，执行 editor.insertNode 插入图片节点 https://www.wangeditor.com/v5/guide/API.html#insertnode

**Comment by DOVE-PH** [comment]
是的用的v5，上面的方法确实可以自定义样式了。
不过发现即使用insertNode API（insertFn也一样）不传alt,href,style生成的img标签仍然有alt和href属性
`editor.insertNode({ type: "paragraph", children: [{ type: "image", src: url, children: [{ text: "" }] }] });`

**Comment by wangfupeng1988** [comment]
哦，这样啊。做了好久了，我也有点忘了。

那我记录下，后续优化一下吧。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。

**Comment by physihan** [comment]
insertNode 只支持width和height 怎样可以支持margin等样式啊 @wangfupeng1988

**Comment by wangfupeng1988** [comment]
@physihan margin 等样式 —— 暂不支持
