### ISSUE TITLE
v5编辑器多空格问题

### ISSUE THREAD

**Issue by andylcl** [wangeditor-team/wangEditor#3912]
## 问题描述

*v5在生成editor时传递Html设置编辑器内容时，html内容含多个'&nbsp;'用来做缩进，但是显示出来的内容里没有显示那么多的空格，再次获取编辑器html时也没有*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一:随便写点东西，添加一些空格，调用getHtml()
- 步骤二:将生成的内容重新显示到编辑器中

**Comment by wangfupeng1988** [comment]
我试着，连续的空格确实有点问题，我查一下。

**Comment by wangfupeng1988** [comment]
v5 最新版本已经解决该问题
https://www.npmjs.com/package/@wangeditor/editor

**Comment by Ftrybe** [comment]
2个及以上空格自动变成tab吗？

**Comment by wangfupeng1988** [comment]
@Ftrybe 默认不支持，需要自己写插件，文档参考 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E6%8F%92%E4%BB%B6

```js
    newEditor.insertText = (t) => {
       // 监听当前输入的是空格，上一个文字也是空格，则输入 tab
    }
```
