### ISSUE TITLE
图片/视频上传有统一配置域名的参数吗

### ISSUE THREAD

**Issue by iCloudys** [wangeditor-team/wangEditor#3913]
图片/视频上传有统一配置域名的参数吗？比如上传文件后，后台返回的url为`/files/20220222/c6a75636043d45a5b7a805b1f5772628.png` ，怎么通过参数配置域名？如果直接把域名写死到url上，无法满足域名发生变动的情况

**Comment by wangfupeng1988** [comment]
不支持这个功能。

我能想到的解决方案：
- 你可以后台返回 `/files/aaa/bbb.png` 这种 url 形式，然后获取的 html 就是 `<img src="/files/aaa/bbb.png"/>`
- 然后再显示 HTML 之前，把其中的 `src` 临时加上一个域名
