### ISSUE TITLE
建议在官方json content解析成html的时候，对header类型的标签加上一个id，方便标题类型或者某区块的导航

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor#3914]
## 功能描述
版本v5
建议在json content解析成html的时候，对header类型的标签加上一个id。考虑到wangeditor 底层数据存储是json，感觉加id这个操作直接在json里加是不是比较合适。比如编辑的doc每新增一个header就id递增转成64位 ，删掉header不操作
参考了下语雀、飞书这些一般是给header 加上id，这样可以根据id导航到该header的位置
## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例
![image](https://user-images.githubusercontent.com/13927744/155140192-8e526bea-d712-4fbf-8f50-4ebb45508eba.png)

![image](https://user-images.githubusercontent.com/13927744/155139619-d130297e-21e8-4ae1-8e42-7e00f31a5791.png)

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
v5 本身就支持这个功能。

文档 https://www.wangeditor.com/v5/guide/API.html#scrolltoelem
demo http://106.12.198.214:8882/main/examples/headers.html
