### ISSUE TITLE
官方V5文档 使用 textarea 的.innerHTML方法建议更换为 .value

### ISSUE THREAD

**Issue by Yulinn233** [wangeditor-team/wangEditor#3916]
## 问题描述

如果是`.innerHTML`的方法在使用代码块，在提交表单的时候会过滤掉`<pre><code>此处的代码</pre></code>`
修改为`document.getElementById('bbp_reply_content').value`就不会过滤
## wangEditor 版本

V5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
使用 textarea 添加代码块并提交表单的时候

**Comment by wangfupeng1988** [comment]
好的，感谢反馈，我尽快处理。
