### ISSUE TITLE
V5版本 建议新增点击工具栏按钮后再次点击收起菜单功能 

### ISSUE THREAD

**Issue by Yulinn233** [wangeditor-team/wangEditor#3917]
## 功能描述

V5版本 建议新增点击工具栏按钮后再次点击收起菜单功能 

## 提炼几个功能点

- 点击菜单收起
- CSS的一点点优化

## 原型图
UI细节优化
![image](https://user-images.githubusercontent.com/8427876/155190757-6b2a0a7f-dc22-46d7-b752-47d79164b5e1.png)
上移菜单或者下移提示块 以便挡住这个黑色小三角
CSS

> .w-e-bar-item-group .w-e-bar-item-menus-container {
>     background-color: var(--w-e-toolbar-bg-color);
>     border: 1px solid var(--w-e-toolbar-border-color);
>     border-radius: 3px;
>     box-shadow: 0 2px 10px rgba(0, 0, 0, .12);
>     display: none;
>     left: 0;
>     margin-top: 36px;
>     position: absolute;
>     top: 0;
>     z-index: 1
> }
> .w-e-drop-panel {
>     margin-top: 36px;
>     min-width: 200px;
>     padding: 10px;
>     top: 0
> }
> .w-e-menu-tooltip-v5:after {
>     border: 5px solid transparent;
>     border-bottom: 5px solid var(--w-e-toolbar-active-color);
>     content: "";
>     opacity: 0;
>     position: absolute;
>     top: 31px;
>     transition: opacity .6s;
>     visibility: hidden;
>     z-index: 1;
> }
> .w-e-menu-tooltip-v5:before {
>     background-color: var(--w-e-toolbar-active-color);
>     border-radius: 5px;
>     color: var(--w-e-toolbar-bg-color);
>     content: attr(data-tooltip);
>     font-size: .75em;
>     opacity: 0;
>     padding: 5px 10px;
>     position: absolute;
>     text-align: center;
>     top: 41px;
>     transition: opacity .6s;
>     visibility: hidden;
>     white-space: pre;
>     z-index: 1
> }

## 可参考的案例

语雀编辑器

**Comment by wangfupeng1988** [comment]
我觉得“再次点击收起”这个功能，对用户使用影响不大，所有它优先级并不高。
我先记录下吧，后面抽空优化。
