### ISSUE TITLE
editor.config.onCatalogChange 已经移除，V5版本大纲目录如何获取

### ISSUE THREAD

**Issue by gopherchn** [wangeditor-team/wangEditor#3918]
## 问题描述
获取大纲目录之前版本可以根据onCatalogChange拿到数组
https://codepen.io/xiaokyo-the-bold/pen/zYKvgPj

## wangEditor 版本(v5版本）

查看V5的文档没有目录和onCatalogChange相关的说明

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

```javascript
     onCreated(editor) {
            setEditor(editor)
            // 此处会报错
            editor.config.onCatalogChange = function(arr) {
                console.log('arr: ', arr)
            }
            // 此处啥都没有
            editor.on('onCatalogChange', function(arr: any) {
                console.log('arr: ', arr)
            })
        }
```

**Comment by wangfupeng1988** [comment]
v5 参考这个 demo 的源码 http://106.12.198.214:8882/main/examples/headers.html

核心 API 是 `getElemsByTypePrefix ` 和 `scrollToElem ` ，v5 的文档中都有
