### ISSUE TITLE
图片设置超链接之后 点击不能跳转

### ISSUE THREAD

**Issue by guo273559624** [wangeditor-team/wangEditor#3919]
> ## 问题描述
> 1. 网络图片添加超链接后， 回显时点击无效
> 2. 上传的图片不支持超链接

> ## wangEditor 版本
> 4.7.10

v5，v4版本图片设置超链接之后，点击不能跳转，实现方式跟实际场景还是有差别的，目前wangEditor是给img标签增加的data-href属性，并不是在外面包一层a标签

**Comment by guo273559624** [comment]
看到之前有人提过这个问题，没有看到结果是什么。这个是本身就是这个设计的 还是 可优化呢？

**Comment by wangfupeng1988** [comment]
这个本来就没想做优化。加一个 click 事件即可解决。

**Comment by guo273559624** [comment]
感谢回答，你说的是针对当前页面的图片点击跳转吧。如果富文本的内容是回显到第三方的一个页面去展示呢，这种click事件怎么去写？

**Comment by wangfupeng1988** [comment]
> 感谢回答，你说的是针对当前页面的图片点击跳转吧。如果富文本的内容是回显到第三方的一个页面去展示呢，这种click事件怎么去写？

这个真倒是一个合理理由。我记录下，后续做优化。

**Comment by wangfupeng1988** [comment]
> 感谢回答，你说的是针对当前页面的图片点击跳转吧。如果富文本的内容是回显到第三方的一个页面去展示呢，这种click事件怎么去写？

@guo273559624 我大概想了一下。从编辑器输出 html `<a><img /></a>` 这种比较简单，但还要考虑将 html 回显到编辑器，这会和链接冲突，会导致内部复杂度大增。

所以，你可以在外部把 `<img data-href="xxx"/>` 这种替换为 `<a href="xxx"><img /></a>` ，使用正则表达式替换，或者转换为 DOM 替换，都可以。
但请注意，替换要生成新 html ，不要修改编辑器产出的 html 格式，否则再次回显到编辑器无法识别。

**Comment by guo273559624** [comment]
@wangfupeng1988 是的，我现在也是这么去做的，保存的时候用正则去替换的，两个方案，一种是加外层加a标签，一种是img标签内增加onclik事件

**Comment by DFive5** [comment]
> @wangfupeng1988 是的，我现在也是这么去做的，保存的时候用正则去替换的，两个方案，一种是加外层加a标签，一种是img标签内增加onclik事件

大佬 能分享下正则的处理吗

**Comment by guo273559624** [comment]
@DFive5  用了一个方法，拿数据的时候将超链接替换掉，提交数据的时候再把超链接加上
/**
     * @desc: 格式化富文本
     */
    formatDescription(content) {
      if (content) {
        return content.replace(/<a.*?>(<img.*?\/>)<\/a>/g, (result, res1) => {
          return res1
        })
      } else {
        if (editor) {
          let target = editor.txt.html()
          return target.replace(/<img[^>]*?data-href="(.*?)".*?\/>/g, (result, res1) => {
            // decode一下
            return `<a href="${decodeURIComponent(res1)}">${result}</a>`
          })
        }
      }
    },

**Comment by renaiqin** [comment]
> @DFive5 用了一个方法，拿数据的时候将超链接替换掉，提交数据的时候再把超链接加上 /** * @desc: 格式化富文本 _/ formatDescription(content) { if (content) { return content.replace(/<a._?>(<img._?/>)</a>/g, (result, res1) => { return res1 }) } else { if (editor) { let target = editor.txt.html() return target.replace(/<img[^>]_?data-href="(._?)"._?/>/g, (result, res1) => { // decode一下 return `<a href="${decodeURIComponent(res1)}">${result}</a>` }) } } },

这一段复制出来报错，能给一段正确的吗

**Comment by renaiqin** [comment]
我是研究透了，更好的做法是：
let domparser = new DOMParser() 
let doc = domparser.parseFromString(content, 'text/html') // 转为html片段 然后就可以对dom操作了， 想加啥加啥，
最后再doc.body.innerHTML 取出内容就好了，这是最简单的做法，比正则好用多了
