### ISSUE TITLE
添加对表格的操作

### ISSUE THREAD

**Issue by zz925625** [wangeditor-team/wangEditor#3924]
## 表格中对单元格  表格 属性的操作

* 可以参考 ckeditor编辑器的功能。*

## 提炼几个功能点

- 单元格宽高 对齐方式 背景颜色
- 表格的宽高，对齐方式，边框，颜色，等等
## 原型图
![image](https://user-images.githubusercontent.com/69182155/155698095-a01a20e6-b698-4c2b-8046-6ca780f670c3.png)
![image](https://user-images.githubusercontent.com/69182155/155698181-3af23ca3-3dce-4fbd-9ddb-830c7fa011c0.png)

## 可参考的案例
https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html    
编辑器中对表格进行操作

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html    
编辑器中对表格进行操作

**Comment by wangfupeng1988** [comment]
感谢反馈~

其实，这些功能我早就记录下了，只不过开发成本较高，而我个人业余精力有限，后面再慢慢做吧。

PS：改功能只会在 v5 上开发，v4 不会再升级功能了。
