### ISSUE TITLE
通过在Vue中使用wangEditor，浏览器后台报错 To enable the plugin, import and call enableES5() when initializing your application.

### ISSUE THREAD

**Issue by ZiuChen** [wangeditor-team/wangEditor#3925]
## 问题描述

我在编写游猴脚本时，通过[CDN](https://cdn.jsdelivr.net/npm/@wangeditor/editor@0.15.11/dist/index.min.js)引入了`0.15.11`版本的wangeditor，并在Vue中初始化。

进入页面后向输入框输入内容不显示，且重复报告相同错误。
错误info：`Uncaught Error: [Immer] The plugin for 'ES5' has not been loaded into Immer. To enable the plugin, import and call `enableES5()` when initializing your application.`

![image](https://user-images.githubusercontent.com/64892985/155710636-82ba7331-da44-45e0-acfc-ead988b57aeb.png)

## wangEditor 版本

`0.15.11`

## 是否查阅了文档 ？

是，未找到相关问题

在`Github`搜索到了这两个可能相关的Issue：

[fix: use immer will throw error in IE11](https://github.com/ice-lab/icestore/pull/120)
[NextJS and enabling plugins](https://github.com/ice-lab/icestore/pull/120)

## 最小成本的复现步骤

- 步骤一：我将正在开发的脚本debug版本上传到了[蓝奏云](https://wwa.lanzouq.com/iQghG00mee0b)（Github不允许上传.js文件），
- 步骤二：将脚本下载解压后，导入浏览器拓展[`Tampermonkey`](https://www.tampermonkey.net/)，并打开[`www.baidu.com`](https://www.baidu.com/)
- 步骤三：向输入框内输入内容，浏览器后台出现此报错

## 出现问题的源代码

```vue
<template>
  <div id="toolbar-container"></div>
  <div id="editor-container"></div>
</template>

<script>
import log from "../ts/Log";
const E = window.wangEditor;
if (E !== undefined) {
  log("wangEditor initialized");
}

export default {
  mounted() {
    this.initEditor();
  },
  methods: {
    initEditor() {
      const editorConfig = { MENU_CONF: {} };
      editorConfig.placeholder = "请输入内容";
      editorConfig.MENU_CONF["uploadImage"] = {
        fieldName: "index-fileName",
        base64LimitSize: 10 * 1024 * 1024, // 10M 以下插入 base64
      };
      editorConfig.onChange = (editor) => {
        const selectionText = editor.getSelectionText();
        const text = editor.getText();
        document.getElementById(
          "status"
        ).innerHTML = `当前文字数量：${text.length}，选中文字：${selectionText}`;
      };

      const editor = E.createEditor({
        selector: "#editor-container",
        content: [],
        // html: '',
        config: editorConfig,
      });
      const toolbar = E.createToolbar({
        editor,
        selector: "#toolbar-container",
      });
    },
  },
};
</script>

<style scoped></style>

```

**Comment by wangfupeng1988** [comment]
你是什么浏览器？

参考 v5 浏览器兼容性 https://www.wangeditor.com/v5/#%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by ZiuChen** [comment]
Edge浏览器，版本 98.0.1108.56 (官方内部版本) (64 位)

**Comment by wangfupeng1988** [comment]
先现成的 vue 组件，你可以直接拿来使用 https://www.wangeditor.com/v5/guide/for-frame.html#vue2

**Comment by ZiuChen** [comment]
谢谢，我尝试了直接使用`Vue`组件，方法确实可行，但用户脚本包体积有限制，不得不从cdn引入。
 
### 调试过程

其他网页在从cdn引入wangEditor后，从控制台`console.log(window.wangEditor)`都有正常object输出。

但是在我的应用中，`Vue` `created` 和 `mounted`时输出`console.log(window.wangEditor)`都能正常输出，但直接在控制台用`console.log(window.wangEditor)`却输出`undefined`。

好在刚刚找到了[解决方案](https://www.cnblogs.com/taoshihan/p/15808575.html)，能够正常使用了，感谢您的耐心回复！

### 实现代码：
``` vue
<template>
  <div id="welcomeEditor"></div>
</template>

<script>
export default {
  mounted() {
    this.initEditor();
  },
  methods: {
    initEditor() {
      if (this.editor != null) {
        return;
      }
      const E = window.wangEditor;
      this.editor = new E("#welcomeEditor");
      this.editor.config.height = 240;
      this.editor.config.menus = [
        "head",
        "bold",
        "fontSize",
        "fontName",
        "italic",
        "underline",
        "strikeThrough",
        "indent",
        "lineHeight",
        "foreColor",
        "backColor",
        "link",
        "justify",
        "emoticon",
        "table",
        "splitLine",
        "undo",
        "redo",
      ];
      this.editor.create();
    },
  },
};
</script>

<style scoped></style>

```
