### ISSUE TITLE
回显路径重复

### ISSUE THREAD

**Issue by 17875622328** [wangeditor-team/wangEditor#3926]
## bug 描述
tp5 上线后 wangEditor 上传多张图片回显路径重复

## 你预期的样子是？
图片不要重复，上传的是什么就是什么
## 浏览器及版本号
google   98.0.4758.102

## wangEditor 版本

v4

**Comment by 17875622328** [comment]
我原来用的也没有问题的，就这两天才出现的，回显路径重复是因为多张图片上传有个别的图片没有保存到目录中去，这个是因为什么呢？

**Comment by 17875622328** [comment]
我这个是在线上出问题的，本地测试是没有问题的
就好比如说：我一次上传8张图片，但是我去到保存的图片的目录去看，就只有7张图片，所以在回显的时候就有一张图片是重复的

**Comment by 17875622328** [comment]
![image](https://user-images.githubusercontent.com/88179153/155838761-9772a138-3521-42c9-97e2-96310ba01653.png)
这个是上传代码，这个有办法复现吗

**Comment by wangfupeng1988** [comment]
你本地都复现不了，我肯定也没办法帮你复现。

1. 线上环境上传 8 张图片，抓包（或看 chrome devTools Network）看 http 请求是否 8 张图片真的已经全部传给了服务端，先保证 req 没问题。
2. 服务端增加一些日志，看这 8 张图片是否都已经收到、处理、并保存为文件。

用这两步即可找到问题。第 2 步会比较麻烦，但没办法，你只有线上环境能复现。

**Comment by 17875622328** [comment]
![image](https://user-images.githubusercontent.com/88179153/155910991-ed12110d-6e54-4203-a018-3a93c05636f5.png)
![image](https://user-images.githubusercontent.com/88179153/155911036-215704b4-5dd8-493c-b35b-66a768dd868d.png)

**Comment by 17875622328** [comment]
我这个问题不知道是我的服务器问题，还是你的软件问题。我的项目都应经上线用了一个来月了最近才出现问题

**Comment by wangfupeng1988** [comment]
看你截图，是服务端端返回的文件名重复了。如下图

<img width="839" alt="image" src="https://user-images.githubusercontent.com/9583120/155919064-8f47b7b1-0eed-4da3-8046-111cd60e1dc8.png">

**Comment by 17875622328** [comment]
是的，被重复的图片在图片目录上是没有保存到的

**Comment by wangfupeng1988** [comment]
这看起来像是服务端的问题。

**Comment by 17875622328** [comment]
这应该和我写的程序没关系吧，不知道是不是我的宝塔配置的问题，都找不出来
