### ISSUE TITLE
添加字体间距 letter-spacing 属性 可下拉选择间距大小

### ISSUE THREAD

**Issue by mumumie** [wangeditor-team/wangEditor#3927]
## 功能描述
选择需要设置间距的字体 跟设置字体大小一样进行设置间距大小

## 提炼几个功能点

- 给文字设置间距大小

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
目前还不支持。后面会陆续做起来。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
