### ISSUE TITLE
在编辑数据量大的文本(如内嵌多张BASE64图片)时 会出现卡顿

### ISSUE THREAD

**Issue by fatwolf** [wangeditor-team/wangEditor#3928]
## bug 描述

在编辑数据量大的文本(如内嵌多张BASE64图片)时，当对内容进行变更，会出现卡顿，内存占用高 ，在5M文本内容的情况，任何操作均需1s左右

## 你预期的样子是？

编辑时不出现卡顿

## 浏览器及版本号

Chrome 98.0.4758.102

## wangEditor 版本

官网首页即可复现

## 官网能否复现该 bug 
能

## 最小成本的复现步骤

- 步骤一:打开官网
- 步骤二:编辑区域黏贴多张base64图片>10 总文本量>5M
- 步骤三:触发卡顿

**Comment by wangfupeng1988** [comment]
这么大的图片建议上传到服务器，别用 base64 了。
