### ISSUE TITLE
文档笔误

### ISSUE THREAD

**Issue by Vesper-0407** [wangeditor-team/wangEditor#3931]
学习这个功能的时候:
[https://www.wangeditor.com/doc/pages/08-%E5%B8%B8%E7%94%A8API/06-scroll-to-head.html#]

最下方应该是
在显示（现实）这些内容时，可以使用这些 id 来做锚点，实现 scroll to head 的功能

**Comment by wangfupeng1988** [comment]
感谢反馈~我抽空改过来
