### ISSUE TITLE
表格模块能否新增合并单元格的功能

### ISSUE THREAD

**Issue by mikezhang93** [wangeditor-team/wangEditor#3932]
## 表格合并单元格

*表格模块能否新增合并单元格的功能*

## 功能点

- 合并单元格

## 可参考的案例
[CKEditor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html)
![image](https://user-images.githubusercontent.com/32701876/156338686-550683de-c0d7-4c1c-be17-cc174d01f2c5.png)

**Comment by wangfupeng1988** [comment]
这个问题我早就记录下了，但目前还没来得及实现，这个功能非常复杂。后面有空了再弄吧，具体时间也不好给出。

PS：会在 v5 开发，v4 不会在升级新功能了

**Comment by mikezhang93** [comment]
谢谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月2日(星期三) 晚上7:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 表格模块能否新增合并单元格的功能 (Issue #3932)





 
Closed #3932.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
