### ISSUE TITLE
静态资源的图片没法显示，其他存储的文件是可以正常显示的

### ISSUE THREAD

**Issue by kuaiting** [wangeditor-team/wangEditor#3933]
## bug 描述
上传图片到服务器本地上传图片，上传成功后无法正常显示，但是再浏览器上输入 文件地址 是可以访问的（如：http://localhost:8080/upload/1499207144224985088.jpeg ）

![2022-03-03_10-27-18](https://user-images.githubusercontent.com/64479445/156484567-a3901903-1d39-40db-b532-ac6a71b365fb.png)

文件确定已上传
![2022-03-03_10-27-38](https://user-images.githubusercontent.com/64479445/156484637-abd3dca4-57c9-431c-b506-3c97fcb26392.png)

## 你预期的样子是？

我的预期是静态资源的文件夹下的文件可以访问 （如：http://localhost:8080/upload/1499207144224985088.jpeg） ，可以在编辑器上显示

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能

**Comment by wangfupeng1988** [comment]
你看下这几个图片的 src 具体是什么？（下图）

<img width="315" alt="image" src="https://user-images.githubusercontent.com/9583120/156499659-34cde6ab-bf75-4b03-89ca-255f0c12fa46.png">

**Comment by kuaiting** [comment]
<p&gt;<img src="http://localhost:8080/upload/1499249534520397824.png" style="max-width:100%;"&gt;<br&gt;</p&gt;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月3日(星期四) 中午1:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 静态资源的图片没法显示，其他存储的文件是可以正常显示的 (Issue #3933)





 
你看下这几个图片的 src 具体是什么？（下图）
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
