### ISSUE TITLE
通过js插入包含<topic>标签的代码时出现了问题

### ISSUE THREAD

**Issue by leezg1234** [wangeditor-team/wangEditor#3934]
## 问题描述
editor.cmd.do('insertHtml', '<topic id="12">#3分钟回顾北京冬奥#</topic>');
通过代码插入一个包含标签的html。保存后标签名被替换为span，而且id属性也没有了。
主要想实现的功能是通过按钮添加一个话题或者在编辑器里面插入一段@用户的代码，如'<at id="123">张三</at>'

**Comment by leezg1234** [comment]
var topic = '<topic id="12">#3分钟回顾北京冬奥#</topic>';
editorHtml = editor.txt.html();
newEditorHtml = editorHtml + topic + "";
$("#content").html(newEditorHtml);
editor.txt.html($("#content").val());
也尝试通过拼接html的方式去实现，但是这样插入话题以后。后面再换行输入新的内容，就默认是被<topic>标签包含了

**Comment by wangfupeng1988** [comment]
v4 不支持这种 topic 和 `@xxx` 功能。

v5 目前支持 `@xxx` 功能 https://github.com/wangeditor-team/wangEditor-plugin-mention

**Comment by leezg1234** [comment]
> v4 不支持这种 topic 和 `@xxx` 功能。
> 
> v5 目前支持 `@xxx` 功能 https://github.com/wangeditor-team/wangEditor-plugin-mention



> v4 不支持这种 topic 和 `@xxx` 功能。
> 
> v5 目前支持 `@xxx` 功能 https://github.com/wangeditor-team/wangEditor-plugin-mention

我用的是加载js的方式安装的编辑器。。如何通过js的方式实现呢

**Comment by wangfupeng1988** [comment]
CDN 方式目前还不行，后面会支持上。

**Comment by leezg1234** [comment]
> CDN 方式目前还不行，后面会支持上。

其实现在就想用一个简单的方式先满足功能。。比如一个输入框输入话题，一个按钮插入话题。然后把话题的html代码写入到编辑器里面，目前的问题是写入进去会遇到问题。。达不到预期，有没有临时的解决方案，只要能把@和#话题# 加入到编辑器里面就行。
