### ISSUE TITLE
编辑器内的图片快速替换

### ISSUE THREAD

**Issue by fhao07** [wangeditor-team/wangEditor#3935]
## 功能描述
编辑器内的图片快速替换，帮助用户省下删除，重新上传的操作
*请输入内容……*
编辑器内的图片快速替换，帮助用户省下删除，重新上传的操作
## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
该功能很少有用户提及，所以近期不会开发。
