### ISSUE TITLE
在内容的指定区域增加新的内容

### ISSUE THREAD

**Issue by Zy76278** [wangeditor-team/wangEditor#3938]
## 问题描述

比如 下面一串数字：
“123456789”，我选中56时点击自定义的菜单的功能时，在这串字符串变成
”1234“
”56“
”789“
这个形式

## wangEditor 版本
 版本：4.7.11

## 是否查阅了文档 ？

是

**Comment by wangfupeng1988** [comment]
`点击自定义的菜单的功能时` —— 你的功能做了哪些操作？如果仅仅是一个普通的 button ，点击会不会这样？
