### ISSUE TITLE
一个页面中同时有多个编辑器时输入内容后光标会自动跳转到最后一个编辑器内

### ISSUE THREAD

**Issue by jkfan** [wangeditor-team/wangEditor#3939]
## bug 描述

*在vue中，要做一个试题的添加页面，其中试题的题干和选项（4个）都是富文本编辑器，我是把wangEditor封装成了一个组件，现在的问题是在题干编辑器里输入一个字符后，光标跑到了最后一个选项的编辑器内*

## 你预期的样子是？

*预期光标不跑，还在当前输入的编辑器内*

## 浏览器及版本号

*谷歌浏览器，98.0.4758.102*

## wangEditor 版本

*4.7.11*

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/19430321/157161360-fc926563-c8f8-4281-a640-1b6cfdb7ef5c.png)

**Comment by wangfupeng1988** [comment]
不知道如何复现你的问题。

v4 有一个多编辑器的 demo http://106.12.198.214:8881/dev/examples/multi-editor.html ，你看如何用这个 demo 复现问题？
