### ISSUE TITLE
请教:如何实现拖拽文本到编辑区时，编辑器出现光标

### ISSUE THREAD

**Issue by lbf911531** [wangeditor-team/wangEditor#3940]
## 问题描述

在使用wangEditor v5的demo发现，选取一段文本拖拽到编辑区内，编辑区在鼠标进入时出现光标；而v4版本没有实现该功能；
因此想请教实现思路

## wangEditor 版本

v4

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
访问官网给出的 v5版本的demo (https://www.wangeditor.com/demo/zh-CN/)
![image](https://user-images.githubusercontent.com/41470095/157163205-256388e6-73b7-48c0-8932-e310db07f598.png)

**Comment by wangfupeng1988** [comment]
V5 发布在即，V4 不会再增加新功能了。

实现思路很简单：就是监听 drag 和 drop 相关的事件，然后在 drop 位置插入文本，但实际做起来可能会有很多细节需要考虑。

**Comment by lbf911531** [comment]
好的，谢谢
