### ISSUE TITLE
上传视频后只显示音频，只能播放音频

### ISSUE THREAD

**Issue by Sxxxx-x** [wangeditor-team/wangEditor#3941]
## bug 描述

*上传视频后编辑框没有视频，只有音频
![image](https://user-images.githubusercontent.com/72953013/157401370-1dab061b-e5da-46d6-ad61-0564df89f408.png)
*

## 你预期的样子是？

*上传视频显示视频.*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
该怎么复现这个问题？

**Comment by Sxxxx-x** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月9日(星期三) 下午4:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 上传视频后只显示音频，只能播放音频 (Issue #3941)





 
该怎么复现这个问题？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfupeng1988** [comment]
自定义上传视频，不会插入 `<audio>` 标签。看你截图，显示的是 `<audio>` 而不是 `<video>`

**Comment by Sxxxx-x** [comment]
> 

![image](https://user-images.githubusercontent.com/72953013/157568641-c24a890d-655d-46ff-9bb2-6ad023390ebd.png)
![image](https://user-images.githubusercontent.com/72953013/157568699-699931b1-5ad6-46cd-a8cd-7401f11302cf.png)

**Comment by wangfupeng1988** [comment]
我抽时间查一下

**Comment by Sxxxx-x** [comment]
可能是谷歌浏览器不适配？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 上午10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 上传视频后只显示音频，只能播放音频 (Issue #3941)





 
我抽时间查一下
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sxxxx-x** [comment]
> 我抽时间查一下

解决了，是视频编码不支持，只支持h264编码

**Comment by wangfupeng1988** [comment]
好的。
