### ISSUE TITLE
自定义菜单不按照添加顺序显示

### ISSUE THREAD

**Issue by taarony** [wangeditor-team/wangEditor#3943]
## bug 描述

全局注册的扩展菜单，不能按照配置的顺序显示，比内置的菜单显示靠后。
比如自定义菜单CustomMenu，
```
// 全局注册:
E.registerMenu('customMenu, CustomMenu);
// 配置菜单：
editor.config.menus = ['customMenu', 'fontSize'];
```
结果fontSize菜单显示在customMenu菜单前面

注：实例注册时，能正常按照配置顺序显示

## 你预期的样子是？
customMenu菜单显示在fontSize菜单前面

## 浏览器及版本号
Chrome  97.0.4692.71   64位

## wangEditor 版本
4.7.12

## 官网能否复现该 bug ？
能

## 最小成本的复现步骤
- 步骤一 
创建自定义菜单并全局注册
```
class CustomMenu extends BtnMenu {
    constructor(editor) {
        const $elem = E.$(
            `<div class="w-e-menu">
                <span>customMenu</span>
            </div>`
        )
        super($elem, editor)
    }
}
// 全局注册
E.registerMenu('customMenu', CustomMenu);
```
- 步骤二
配置编辑器菜单
editor.config.menus = ['customMenu', 'fontSize'];

结果：fontSize菜单显示在customMenu菜单之前

**Comment by wangfupeng1988** [comment]
建议更换 v5 吧。现在 v5 发布在即，没太有精力跟踪 v4 的问题了。

**Comment by taarony** [comment]
试了下v5，随便点了几下就发现了个bug… 点击添加视频，勾选关闭弹窗按钮，然后移动到菜单栏，全都是cursor: not-allow 不可点击状态。官网demo也会。

**Comment by taarony** [comment]
添加网络图片也是一样的情况

**Comment by taarony** [comment]
试了一下，所有点击后弹出modal的，点击关闭按钮之后，都会导致编辑器失去焦点并且菜单不可点击。

**Comment by wangfupeng1988** [comment]
@taarony 以上你所说的这俩，不算是 bug ，算是一个体验性问题。
弹出 modal 再关闭，编辑器一直处于失焦状态，所以菜单不可用。你再重新点击编辑器，让编辑器聚焦即可。多一步鼠标操作。
