### ISSUE TITLE
V5 文本选择的时候插入链接修改链接文本然后确定修改链接文本无效。

### ISSUE THREAD

**Issue by webgaochao** [wangeditor-team/wangEditor#3945]
## bug 描述

文本选择的时候插入链接修改链接文本然后确定修改链接文本无效。

## 你预期的样子是？

文本选择的时候插入链接修改链接文本然后确定修改链接文本替换掉选择的文本

## 浏览器及版本号

Google Chrome 版本 99.0.4844.51（正式版本） (x86_64)

## wangEditor 版本

v5版本

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

文本选择的时候插入链接修改链接文本然后确定修改链接文本无效。

![image](https://user-images.githubusercontent.com/22511584/157829149-0d211d40-ff7b-4d43-864d-28eaec361878.png)

**Comment by wangfupeng1988** [comment]
> 文本选择的时候插入链接修改链接文本然后确定修改链接文本无效。

这句话连个逗号都没有。需要一步一步详细说明复现步骤，傻瓜式的。

**Comment by webgaochao** [comment]
第一步：富文本输入文本33333

**Comment by webgaochao** [comment]
> > 文本选择的时候插入链接修改链接文本然后确定修改链接文本无效。
> 
> 这句话连个逗号都没有。需要一步一步详细说明复现步骤，傻瓜式的。

第一步：富文本输入文本33333
第二步：鼠标右键选择文本33333
第三步：选择文本后富文本弹出操作栏，选择插入链接选项。
第四步：选择插入链接选项，弹出链接编辑弹框。修改链接文本44444，填写链接地址。点击确定。
第五步：发现富文本内容依然是33333。修改无效。

**Comment by wangfupeng1988** [comment]
已复现

**Comment by shadowDDD** [comment]
现在项目上也是有这个bug，请问啥时候vue版本能更新修复这个bug呢

> 已复现

**Comment by wangfupeng1988** [comment]
代码已修改，等待下次发布 npm https://github.com/wangeditor-team/wangEditor-v5/commit/5fdf6ae33b1bebe9b7373e4b7ee8c568480a3c08

**Comment by wangfupeng1988** [comment]
已修复。请下载最新版本  https://www.npmjs.com/package/@wangeditor/editor
