### ISSUE TITLE
关于使用nuxt 集成 wangEditor 样式问题

### ISSUE THREAD

**Issue by zenlinuxs** [wangeditor-team/wangEditor#3946]
## 关于使用nuxt 集成 wangEditor 样式问题

* 基本环境：
{
  "name": "xxx",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@wangeditor/editor": "^0.15.11",
    "@wangeditor/editor-for-vue": "^0.6.14-1",
    "axios": "^0.26.1",
    "core-js": "^3.19.3",
    "element-ui": "^2.15.6",
    "nuxt": "^2.15.8",
    "vue": "^2.6.14",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^4.46.0"
  },
  "devDependencies": {
    "@vue/test-utils": "^1.3.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^27.4.4",
    "jest": "^27.4.4",
    "vue-jest": "^3.0.4"
  }
}

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
1.按文档步骤即成富文本编辑器是没问题的，提交的是默认的html参数而不是json数据，存在解析和转化问题，直接采用了默认的html。
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/41136685/158011731-d0864396-7970-4fb9-9ea7-f2df53af7b58.png">
- 步骤二

 1.但是在使用 vue的v-html解析提交的富文本内容时，有些样式不起作用。我尝试过去是不是element样式的覆盖问题，去掉引入后发现然不起作用。应该这样表述：有些样式是起作用有些不起比如table标签不起作用，h标签倒是起作用。对富文本来说输入的内容应该原样解析输出才对，wangEditorV5应该考虑element或其他样式覆盖的问题。到现在我然找不到问题所在。
- 步骤三
1.提交的富文本数据和获得的数据一致的，我依然怀疑是引入的样式问题。希望求的帮助。

**Comment by wangfupeng1988** [comment]
没看懂你的问题。

你意思是将 html 回显到编辑器时，样式不对？

**Comment by zenlinuxs** [comment]
> 没看懂你的问题。
> 
> 你的意思是 html 回显到编辑器时，样式不对？

显示到用户查看html样式不对。

**Comment by zenlinuxs** [comment]
为了更加清晰的表述我的问题：
富文本发布的内容效果：
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/41136685/158017187-b718c8ed-5e25-4f54-a052-c74ae9e0dde1.png">

解析用户查看的内容效果
<img width="887" alt="image" src="https://user-images.githubusercontent.com/41136685/158017232-5e507606-44d2-4269-8721-ecff70e031fa.png">

**Comment by wangfupeng1988** [comment]
看这里 https://www.wangeditor.com/v5/guide/content.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by zenlinuxs** [comment]
> 编辑器只输出纯 html ，样式需要自定义。文档里有写，看这里 https://www.wangeditor.com/v5/guide/content.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

1.这个是自定义输出的样式，问题是我连设置的样式都不行。
就在刚刚我将vue的<style scoped> scoped 删除了，然后神奇的被重写了样式，我记得scoped除开写自己属性的样式之外并且更全局样式共同作用样式才对，他们是个继承关系不应该是互斥关系呀？

**Comment by zenlinuxs** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/41136685/158017856-cfb80308-b006-4de6-b354-bc72a45a6183.png">

好了。算是治标的解决了吧。

**Comment by cainiaodjm** [comment]
你用的是nuxt3吗 我nuxt3上装不上 报错
