### ISSUE TITLE
关于maxLenth实现建议

### ISSUE THREAD

**Issue by Buzaisonghua** [wangeditor-team/wangEditor#3949]
这里给change后的数据称为html数据，首先可以基于正则拿到当前页面文本长度，在html中字符长度超长时，将html转换为vdom，后遍历vdom截取掉多余结构，即可实现限制最大长度，目前没发现这个逻辑有啥bug

**Comment by wangfupeng1988** [comment]
v5 已经支持 maxlength https://www.wangeditor.com/v5/guide/editor-config.html#maxlength-onmaxlength
