### ISSUE TITLE
如何在上传图片后给图片添加点击事件?

### ISSUE THREAD

**Issue by ljh257110** [wangeditor-team/wangEditor#3950]
## 问题描述

如何在上传图片后给图片添加点击事件

## wangEditor 版本

v5.1.8-10

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
使用editor.insertNode或editor.dangerouslyInsertHtml插入img元素，无法添加onclick，最终生成的元素和使用insertFn添加的一样，也就是有src、alt、data-href、style四个属性，不知如何加入onclick事件

**Comment by wangfupeng1988** [comment]
第一， `insertNode` 和 `dangerouslyInsertHtml` 是不能加入 click 等事件的

第二，你可以再编辑器的容器 DOM 上绑定 click 事件，然后判断 `event.target.nodeName === 'IMG'` 就触发时间（就是 DOM 事件代理/委托）
