### ISSUE TITLE
切换页面 destroy 报错：Can not get editor instance

### ISSUE THREAD

**Issue by stephentian** [wangeditor-team/wangEditor#3954]
## bug 描述

![image](https://user-images.githubusercontent.com/20151912/158557163-65fcddad-061f-4888-a903-d2838b0b62b5.png)
<img width="604" alt="image" src="https://user-images.githubusercontent.com/20151912/158557221-9bed7e86-991f-4a39-b9e7-eb5ca98d8975.png">

## wangEditor 版本

```
"@wangeditor/editor": "^0.15.11",
"@wangeditor/editor-for-vue": "^0.6.14-1",
```
debugger 发现 `editor` 存在，并有 `destroy` 方法，仍报错

**Comment by stephentian** [comment]
![image](https://user-images.githubusercontent.com/20151912/158558648-c74d79a9-6530-4134-a26b-6c5c9cd1aa09.png)

这样不报错，确定 `editor.destroy` 这个方法里报错

**Comment by wangfupeng1988** [comment]
https://github.com/wangfupeng1988/vue2-wangeditor-demo
用这个 demo 试试报错吗？

**Comment by stephentian** [comment]
> 

好的

**Comment by wangfupeng1988** [comment]
> https://github.com/wangfupeng1988/vue2-wangeditor-demo 用这个 demo 试试报错吗？

这个 demo 没有切换页面。抱歉刚才没看到“切换页面” 这几个字。

我招人来帮你看看。

**Comment by stephentian** [comment]
> > https://github.com/wangfupeng1988/vue2-wangeditor-demo 用这个 demo 试试报错吗？
> 
> 这个 demo 没有切换页面。抱歉刚才没看到“切换页面” 这几个字。
> 
> 我招人来帮你看看。

没事，我加下 vue-router 试下

**Comment by stephentian** [comment]
加了一行 `autoFocus` 就不出现问题了；

![image](https://user-images.githubusercontent.com/20151912/158728322-0766a743-3f9c-4de8-8f7c-5832336feb76.png)

但是点击编辑器( 即 `focus` 编辑器)，然后在跳转页面，页面会报错。

**Comment by stephentian** [comment]
> https://github.com/wangfupeng1988/vue2-wangeditor-demo 用这个 demo 试试报错吗？

demo 不报错，已添加 多页面测试，也没复现 bug;

怀疑是不是 editor `focus` 状态影响了 editor 的销毁

**Comment by wangfupeng1988** [comment]
@stephentian 我这个 demo 里没有对 autoFocus 做特殊设置，既然 demo 不报错，应该就不是编辑器本身的问题。

**Comment by stephentian** [comment]
> @stephentian 我这个 demo 里没有对 autoFocus 做特殊设置，既然 demo 不报错，应该就不是编辑器本身的问题。

好的，感谢；

我先不销毁试试。切换页面 Dom 应该自动销毁了，不需要在 `beforeDestroy` 调用。

**Comment by liuqh0609** [comment]
这个问题应该在最新版本的editor中解决了，我本地用最新版本没有复现。
你可以查看下这个仓库： [https://github.com/liuqh0609/wangEditor-vue2-demo](https://github.com/liuqh0609/wangEditor-vue2-demo)
