### ISSUE TITLE
复制粘贴其他富文本的代码块出错

### ISSUE THREAD

**Issue by augushong** [wangeditor-team/wangEditor#3955]
## bug 描述

一般情况下复制其他富文本的代码不会出错,但是复制这个网站的代码会出错,如果粘贴到其V4版本不会出错.
## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 打开这个页面:http://www.php-cpp.com/documentation/your-first-extension
- 复制折上面的一个代码块,
- 粘贴到V5编辑器:https://www.wangeditor.com/demo/zh-CN/
- 出错
-  粘贴到V4编辑器不出错

**Comment by wangfupeng1988** [comment]
我记得，你在 qq 群还提到：使用 `editor.dangerouslyInsertHtml(...)` 输入几个连续的 `<span>` 也会导致报错，对吧？

如有此问题，可以在这里回复一下复现步骤。

然后我一起修改这俩问题。

**Comment by augushong** [comment]
> 不是我,我没有,就这个.

其他的问题不知道,也没碰见过连续`<span></span>`报错的问题,具体我也不知道为什么会报错,粘贴其他富文本的`代码块`没出过问题,就是复制粘贴我给的链接里面的`代码块`是会出问题.

**Comment by wangfupeng1988** [comment]
好，那我先解决你的问题吧。

**Comment by wangfupeng1988** [comment]
解决了，下载最新版本试试

**Comment by augushong** [comment]
好的,我是用的是CDN的方式,可能还没有更新,过段时间再试试
