### ISSUE TITLE
重大bug 上传图片功能

### ISSUE THREAD

**Issue by xhhaha** [wangeditor-team/wangEditor#3958]
## 问题描述

*请输入遇到的问题...*
上传图片损失
## wangEditor 版本
v5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 原图 我上传这张图片
![原图](https://user-images.githubusercontent.com/40232076/158787426-422f89ce-61d4-4988-bdb1-b1fc86909872.png)

- 步骤二
- 第二次上传 
- 
![image](https://user-images.githubusercontent.com/40232076/158789109-66ca27b0-5107-4868-b231-42862b2aaef5.png)

总结 上传图片 对图片文件有损坏

**Comment by wangfupeng1988** [comment]
第一，你看下这个 data 里的数据是啥？如下图

<img width="662" alt="image" src="https://user-images.githubusercontent.com/9583120/158789818-2a57d3c4-9e86-421d-ae31-a68ea1633453.png">


第二，你再看看这图片的 src 是啥？如下图

<img width="553" alt="image" src="https://user-images.githubusercontent.com/9583120/158789878-65db97fb-7ab1-4d3b-8fd5-09bc69e5f6c3.png">

**Comment by xhhaha** [comment]
data key 里 返回的是文件路径  

这个图片保存的时候 损坏了
插件里的附件上传功能没问题，但是到了 上传图片 就发生这样的事情 这让我措不及防呀 

![image](https://user-images.githubusercontent.com/40232076/158916491-d0a1286e-bd12-4e71-95e6-072e81360916.png)

**Comment by xhhaha** [comment]
我反复测试之后  发现v5 之前的版本  图片上传没有问题，，，v5 的图片上传 不知道什么情况下 对数据帧进行了改变 导致我上传的图片内容部分丢失 或者完整丢失

**Comment by wangfupeng1988** [comment]
试试这个 v5 上传图片的 demo
http://106.12.198.214:8882/main/examples/upload-image.html

**Comment by xhhaha** [comment]
经过 反复 测试 发现 问题所在了  

 base64LimitSize: 5 * 1024, // 5kb 以下插入 base64

上述一行代码 如果加了 没问题 
如果不加 就会出现图片内容丢失问题

**Comment by wangfupeng1988** [comment]
> 试试这个 v5 上传图片的 demo http://106.12.198.214:8882/main/examples/upload-image.html

我用这个 demo 注释掉了 `base64LimitSize: 5 * 1024`，本地测试也没问题。如下图

<img width="1767" alt="image" src="https://user-images.githubusercontent.com/9583120/158988641-26115207-1a68-4664-b206-5dfe5ecabdfd.png">
