### ISSUE TITLE
上传图片后,会自动替换掉整个编辑框

### ISSUE THREAD

**Issue by kugarliyifan** [wangeditor-team/wangEditor#3959]
## bug 描述
处理自定义上传图片的功能的时候,,上传成功后,调用insertImgFn() 传入图片地址url,后,会直接把整个编辑框替换成图片,版本号是"wangeditor": "^4.7.12",  vue 2.x下

![`AQTHLWTN)BM6KEZXZ4X EO](https://user-images.githubusercontent.com/18448413/159146645-b51e198a-486b-44b7-8f41-a85c0a7ea889.png)

调用前:

![1CT~2C}$}U5F1MSLBU9GQS0](https://user-images.githubusercontent.com/18448413/159146658-e8d781f6-e80d-409b-ac19-970b36ac1e0c.png)

调用insertImgFn()后
![SRF}L@B3CK 1NT4HYKCUOUW](https://user-images.githubusercontent.com/18448413/159146648-de21a146-aeb6-4fab-9de5-38236a004211.png)

不管是uploadImgHooks或者customUploadImg都一样

控制台会输出:
![image](https://user-images.githubusercontent.com/18448413/159146686-3ea909c1-29ba-4c65-8fbb-f5ab98134089.png)
 
这个错误

代码是:
 ```
editor.config.uploadImgHooks = {
        // 上传图片之前

        // 图片上传并返回了结果，图片插入已成功
        success: function (xhr) {
          console.log('success', xhr)
        },
        // 图片上传并返回了结果，但图片插入时出错了
        fail: function (xhr, editor, resData) {
          console.log('fail', resData)
        },
        // 上传图片出错，一般为 http 请求的错误
        error: function (xhr, editor, resData) {
          console.log('error', xhr, resData)
        },
        // 图片上传并返回了结果，想要自己把图片插入到编辑器中
        // 例如服务器端返回的不是 { errno: 0, data: [...] } 这种格式，可使用 customInsert
        customInsert: function (insertImgFn, result) {
          // result 即服务端返回的接口
          //debugger
          console.log('customInsert', result)

          // insertImgFn 可把图片插入到编辑器，传入图片 src ，执行函数即可
          insertImgFn(result.returnData)
        },
      }
```

**Comment by wangfupeng1988** [comment]
你下载这个 demo 的源码试试 view-source:http://106.12.198.214:8881/dev/examples/upload-image.html
把 `customUploadImg` 相关的代码解注释。

**Comment by kugarliyifan** [comment]
我的锅,,,我在定义节点的时候用了<div id="demo1" v-html='content'></div>,,,onchange的时候,就被替换掉了

**Comment by kugarliyifan** [comment]
我的锅,,,我在定义节点的时候用了 v-html="content"

,,,onchange的时候,就被替换掉了
