### ISSUE TITLE
行高不生效问题

### ISSUE THREAD

**Issue by jokercakuyi** [wangeditor-team/wangEditor#3960]
## bug 描述

*从别的地方复制过来的文章，莫名会有个section 标签 且设置那一行的行高会不生效*

## 你预期的样子是？

*请输入内容……*

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

*请输入内容……*

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请按照 issue 模板填写其他信息，否则不予受理。
