### ISSUE TITLE
从word复制包含文本和图片的内容，粘贴到输入框只有文本，控制台报错

### ISSUE THREAD

**Issue by VantStark** [wangeditor-team/wangEditor#3961]
## bug 描述

从word复制包含文本和图片的内容，粘贴到输入框只有文本，控制台报错

## 你预期的样子是？

文本和图片都可以粘贴到输入框

## 浏览器及版本号

Microsoft Edge
版本 99.0.1150.46 (正式版本) (64 位)

## wangEditor 版本

4.7.12

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一，打开word，输入一些文字，插入一张图片
- 步骤二，在word中选择上一步的文字和图片，Ctrl+C复制
- 步骤三，浏览器打开官网。粘贴图片到富文本框（ctrl+v或者右键粘贴）
- 步骤四，打开F12开发人员工具，控制台报错
![image](https://user-images.githubusercontent.com/8328013/159440030-c11056cb-6037-4f63-b31c-74d9cc1186ac.png)

**Comment by wangfupeng1988** [comment]
v4 对 word 粘贴无法完全支持，不支持粘贴 word 的图片。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
