### ISSUE TITLE
希望可以像csdn那边可以有个插件，快速往前一行或者后一行插入一个空白

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor#3962]
## 功能描述
两个代码块或者表格连在一起的时候，无法在中间插入一行。希望可以像csdn那边可以有个插件，快速在前一行或者后一行插入一个空白行
*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图
![image](https://user-images.githubusercontent.com/13927744/159524735-dacd68be-9bf3-4418-bd0a-445b0f06c437.png)

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
忘了给你回复了，后来增加了这个功能。如下图

<img width="512" alt="image" src="https://user-images.githubusercontent.com/9583120/177480970-fe4a45b2-2015-4720-aa11-74f91b2bca6e.png">
