### ISSUE TITLE
扩展了按钮问题

### ISSUE THREAD

**Issue by yndjl** [wangeditor-team/wangEditor#3964]
## 问题描述

*使用vue扩展一个新的音视频选择按钮，点击之后，想要打开自定义的弹窗组件，选择网络图片之后，图片回显编辑框。请问是否有相关功能，或实现方式*

## wangEditor 版本

*4.7.12*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 无

**Comment by wangfupeng1988** [comment]
没懂。音视频，为啥要选择图片呢？

**Comment by yndjl** [comment]
自定义按钮
![image](https://user-images.githubusercontent.com/18571223/159826364-5c3e6205-ab08-499c-957c-7b4985a6a205.png)
点击之后触发弹窗
![image](https://user-images.githubusercontent.com/18571223/159826451-960711ba-ec4d-4ffc-b912-6a9d624e9fe7.png)
弹窗中有图片、音频、视频3中资源类型，目前就是想要实现：选择其中一种资源，再将资源回填到编辑框中。扩展按钮是不是没有提供这种实现方式的回调接口。

然而，目前遇到另一个问题。在自定义的menu的clickhandler事件中，直接添加audio，audio无法展示。直接添加video标签，video标签只能添加在编辑框内容的最后面

**Comment by wangfupeng1988** [comment]
> 选择其中一种资源，再将资源回填到编辑框中

可以使用 `editor.cmd.do('insertHTML', 'xxxx')` 来插入到编辑器中。

**Comment by yndjl** [comment]
对于音频资源，是否目前不支持h5中的audio标签。只可以通过iframe进行mp3资源地址加载。
![1648100228(1)](https://user-images.githubusercontent.com/18571223/159849602-85d6f28b-ed61-49ae-8c0b-04144523536f.jpg)

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
