### ISSUE TITLE
@wangeditor/plugin-formula插入公式时报错Uncaught (in promise) Error: Cannot resolve a DOM node from Slate node: {"text":""}

### ISSUE THREAD

**Issue by Black-Jacki** [wangeditor-team/wangEditor#3965]
## bug 描述

*编辑器使用数学公式插件@wangeditor/plugin-formula时，点确定后就报错Uncaught (in promise) Error: Cannot resolve a DOM node from Slate node: {"text":""}，然后每次点输入框都会报错，麻烦帮看下怎么解决这个问题？
![image](https://user-images.githubusercontent.com/63303518/159831603-5e6e3bea-0520-4917-8adc-2382acaff5cc.png)
*

## 你预期的样子是？

*点确定后插入公式，并且编辑器还能正常使用*

## 浏览器及版本号

*Google Chrome 版本 99.0.4844.82（正式版本） （64 位）*

## wangEditor 版本

*"@wangeditor/editor": "^0.15.15",
"@wangeditor/editor-for-react": "^0.6.23",
 "@wangeditor/plugin-formula": "^1.0.8",*

## 官网能否复现该 bug ？

官网没有该demo

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- React v17.0.2

```import React, {useState, useEffect} from 'react';
import '@wangeditor/editor/dist/css/style.css';
import {Editor, Toolbar} from '@wangeditor/editor-for-react';
import {Boot} from "@wangeditor/editor";
import formulaModule from '@wangeditor/plugin-formula';

const WangEditor = () => {

  const [editor, setEditor] = useState(null);

  const defaultContent = [
    {type: "formula", children: [{text: ""}], value: "c = \\pm\\sqrt{a^2 + b^2}"}
  ];
  // const defaultHtml = `<p>这是一行文字</p>`;

  const toolbarConfig = {
    insertKeys: {
      index: 0,
      keys: [
        'insertFormula', // “插入公式”菜单
        'editFormula' // “编辑公式”菜单
      ],
    },
  };
  const editorConfig = {
    placeholder: "请输入内容...",
    // 选中公式时的悬浮菜单
    hoverbarKeys: {
      formula: {
        menuKeys: ["insertFormula", 'editFormula'], // “编辑公式”菜单
      },
    },
    onCreated: editor => setEditor(editor),
    onChange: editor => {
      console.log("editor", editor);
      console.log("editor.children", editor.children);
    }
  };

  useEffect(() => {
    // 注册。要在创建编辑器之前注册，且只能注册一次，不可重复注册。
    Boot.registerModule(formulaModule)
  }, []);

  useEffect(() => {
    return () => {
      if (editor == null) return
      editor.destroy()
      setEditor(null);
    }
  }, [editor])

  return <div style={{border: "1px solid #ccc", zIndex: 100}}>
    <Toolbar
      editor={editor}
      defaultConfig={toolbarConfig}
      mode="default"
      style={{borderBottom: "1px solid #ccc"}}
    />
    <Editor
      defaultConfig={editorConfig}
      defaultContent={defaultContent}
      // defaultHtml={defaultHtml}
      mode="default"
      style={{height: "500px", overflowY: "hidden"}}
    />
  </div>;
};

export default WangEditor;
```

**Comment by wangfupeng1988** [comment]
去 codesandbox 搞一个 demo 吧，来复现这个 bug 。

**Comment by Black-Jacki** [comment]
https://codesandbox.io/s/friendly-darkness-jnw5zw?file=/src/App.js
我刚试了原生js的方式不会报错，但是react的方式会报错，你看下这个
另外有个问题，就是getHtml()之后，后续页面展示公式时，应该要怎么处理这个节点，我试了dangerouslySetInnerHTML解析不了这个公式节点，katex的渲染方式又只能字符串，暂时没想到怎么弄好

```
<p><span data-w-e-type="formula" data-w-e-is-void data-w-e-is-inline data-value="\displaystyle {1 + \frac{q^2}{(1-q)}+\frac{q^6}{(1-q)(1-q^2)}+\cdots }= \prod_{j =0}^{\infty}\frac{1}{(1-q^{5j+2})(1-q^{5j+3})}"></span></p>
```

**Comment by Black-Jacki** [comment]
难道要展示时 把有公式的地方分割出来，再用katex解析data-value吗？

**Comment by wangfupeng1988** [comment]
codesandbox 中，App.js 改为如下代码，刷新，就不报错了

```jsx
import React, { useState, useEffect } from "react";
import "@wangeditor/editor/dist/css/style.css";
import { Editor, Toolbar } from "@wangeditor/editor-for-react";
import { Boot } from "@wangeditor/editor";
import formulaModule from "@wangeditor/plugin-formula";

// 1. 组件外注册
Boot.registerModule(formulaModule);

const WangEditor = () => {
  const [editor, setEditor] = useState(null);

  const defaultContent = [
    {
      type: 'paragraph', // 2. 要有一个 paragraph
      children: [
        {
          type: "formula",
          children: [{ text: "" }],
          value: "c = \\pm\\sqrt{a^2 + b^2}"
        }
      ]
    }
  ];
  // const defaultHtml = `<p>这是一行文字</p>`;

  const toolbarConfig = {
    insertKeys: {
      index: 0,
      keys: [
        "insertFormula", // “插入公式”菜单
        "editFormula" // “编辑公式”菜单
      ]
    }
  };
  const editorConfig = {
    placeholder: "请输入内容...",
    // 选中公式时的悬浮菜单
    hoverbarKeys: {
      formula: {
        // 3.  这里删掉 "insertFormula"
        menuKeys: ["editFormula"] // “编辑公式”菜单
      }
    },
    onCreated: (editor) => setEditor(editor),
    onChange: (editor) => {
      console.log("editor", editor);
      console.log("editor.children", editor.children);
    }
  };

  // 4. 移动到组件外去注册 module
  // useEffect(() => {
  //   // 注册。要在创建编辑器之前注册，且只能注册一次，不可重复注册。
  //   Boot.registerModule(formulaModule);
  // }, []);

  useEffect(() => {
    return () => {
      if (editor == null) return;
      editor.destroy();
      setEditor(null);
    };
  }, [editor]);

  return (
    <div style={{ border: "1px solid #ccc", zIndex: 100 }}>
      <Toolbar
        editor={editor}
        defaultConfig={toolbarConfig}
        mode="default"
        style={{ borderBottom: "1px solid #ccc" }}
      />
      <Editor
        defaultConfig={editorConfig}
        defaultContent={defaultContent}
        // defaultHtml={defaultHtml}
        mode="default"
        style={{ height: "500px", overflowY: "hidden" }}
      />
    </div>
  );
};

export default WangEditor;
```

**Comment by wangfupeng1988** [comment]
> 难道要展示时 把有公式的地方分割出来，再用katex解析data-value吗？

Katex 渲染公式就需要两个参数：1. Latex 代码；2. 一个 elem 。现在这俩都有了，你怎么着也能把公式渲染出来。

**Comment by Black-Jacki** [comment]
谢啦，问题已都解决😃

**Comment by Black-Jacki** [comment]
https://codesandbox.io/s/friendly-darkness-jnw5zw?file=/src/App.js

刚看错了，katex还是会把其他非公式元素渲染出来，例如

![image](https://user-images.githubusercontent.com/63303518/159875868-535a07c1-7c05-4768-8da3-e09d71fd51b7.png)

这个问题应该怎么处理？

**Comment by Black-Jacki** [comment]
需求场景是：富文本编辑完后把数据存储到数据库，后面展示页面的时候我拿到的应该一段html文本，需要解析展示到页面上

**Comment by wangfupeng1988** [comment]
> katex.render(editor.getHtml(), viewRef.current);

你完全搞错了，katex 仅仅是渲染公式，不是渲染整个 html 代码。建议你先做一个单独的 katex demo ，试试它的渲染公式的能力。

**Comment by Black-Jacki** [comment]
我看katex的文档仅仅是解析字符串式的公式，也就是
``` javascript
katex.render("c = \\pm\\sqrt{a^2 + b^2}", element, {
    throwOnError: false
});
```
所以当我拿到
``` html
<span data-w-e-type="formula" data-w-e-is-void data-w-e-is-inline data-value="ds = \sqrt{dx^2 + dy^2}"></span>
```
我需要把data-value解析出来，再用katex渲染对吗？
我是想知道有没有快捷的办法能直接把html和里面的公式快速渲染出来。
类似于readOnly模式的编辑器，只需要赋值html就能解析整段html字符串

**Comment by wangfupeng1988** [comment]
我能想到的快捷方式，供你参考
第一，定义一个自定义 element  `<w-e-formula-card value="xxx"></w-e-formula-card>`，参考 https://github.com/wangeditor-team/wangEditor-plugin-formula/tree/main/src/register-custom-elem 
第二，在渲染 html 之前，把公式的标签 `<span data-w-e-type="formula" data-value="xxx"></span>` 转换为 `<w-e-formula-card value="xxx"></w-e-formula-card>` 形式。

**Comment by Black-Jacki** [comment]
谢谢，完美实现。大佬牛👍👍👍

**Comment by ysypnbh** [comment]
> 

请问怎么实现的，有没有demo

**Comment by doYbest** [comment]
> 谢谢，完美实现。大佬牛👍👍👍

请问是如何在编辑器使用latex公式后，再服务器取出内容后进行latex和markdown的渲染？

**Comment by 745740681** [comment]
使用的框架：Vue2.6.14
遇到的问题 ：Cannot resolve a DOM node from Slate node: {"text":"111"} 如下图
![image](https://user-images.githubusercontent.com/27795092/227756272-916652ad-74c7-46f7-83bc-a4166bf871fe.png)
这个问题是在创建自定义新元素的时候出现的
我复现的过程 （参照官网上的实例操作的）
1、在菜单中注册一个自定义的按钮 如下图
![image](https://user-images.githubusercontent.com/27795092/227756328-bfbc0d6f-be88-437e-bc05-6ca177d9e24e.png)
2、定义一个新元素并注册
![image](https://user-images.githubusercontent.com/27795092/227756395-10bd9bf5-14ac-4bd1-aabf-8793efd58c8d.png)
在菜单栏点击自定义按钮时就出现了问题

请教大神，帮我看一下这个问题改如何解决

**Comment by Yutianyudaodao** [comment]
hello，我也遇到了这个问题，官方文档说需要一个空的text，但是点击插入自定义dom时候，会报错
this.editor.on('insertGoodsClick', () => {
        console.log(333, '你点击了插入商品菜单')
        this.editor.insertNode({
          type: 'goodscard',
          imgSrc: 'https://ggg.jpg',
          title: 'ggg',
          price: '69',
          id: 31,
          children: [{ text: '' }]
        })
      })
