### ISSUE TITLE
文本设置H标题后，再设置line-height不生效

### ISSUE THREAD

**Issue by tinysparkle** [wangeditor-team/wangEditor#3966]
## bug 描述

文本设置H标题后，再设置line-height不生效

## 你预期的样子是？

文本设置H标题后，再设置line-height生效

## 浏览器及版本号

chrome 99.0.4844.51

## wangEditor 版本

4.7.12

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一
- 选中文本，点击H设置标题
- 步骤二
- 选中设计为标题的文本，点击设置行高

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
