### ISSUE TITLE
placeholder class被Bootstrap 5.0的 placeholder class影响

### ISSUE THREAD

**Issue by DavidTai780** [wangeditor-team/wangEditor#3967]
## 问题描述
*placeholder class被Bootstrap 5.0的 placeholder class影响，造成placeholder直接一大块灰色长方块在文本编辑器，如下方截图。*
![image](https://user-images.githubusercontent.com/26398101/159844535-a35c64c1-1023-44cb-b378-185d2cc2f669.png)

*文本编辑器应该如官网的如图二*
![image](https://user-images.githubusercontent.com/26398101/159844651-adb15232-10c8-4432-a5e4-b8e73fcb7768.png)

## wangEditor 版本
*CDN里的最新版
https://cdn.jsdelivr.net/npm/wangeditor@latest/dist/wangEditor.min.js*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 引入Bootstrap 5.0版本
- 引入与设置wangEditor(如文档中的默认设置即可)

**Comment by wangfupeng1988** [comment]
自己去覆写一下 `.w-e-text-container .placeholder` 的样式吧，目前只能这样做。

**Comment by DavidTai780** [comment]
> 自己去覆写一下 `.w-e-text-container .placeholder` 的样式吧，目前只能这样做。
谢谢，好的知道了
