### ISSUE TITLE
ERROR in /node_modules/wangeditor/dist/utils/dom-core.d.ts   Type parameter 'T' has a circular default.

### ISSUE THREAD

**Issue by 404100797** [wangeditor-team/wangEditor#3970]
ERROR in /node_modules/wangeditor/dist/utils/dom-core.d.ts
14:64 Type parameter 'T' has a circular default.
    12 | };
    13 | export declare type DomElementSelector = string | DomElement | Document | Node | NodeList | ChildNode | ChildNode[] | Element | HTMLElement | HTMLElement[] | HTMLCollection | EventTarget | null | undefined;
  > 14 | export declare class DomElement<T extends DomElementSelector = DomElementSelector> {
       |                                                                ^
    15 |     selector: T;
    16 |     length: number;
    17 |     elems: HTMLElement[];

yarn install 时出错 版本"wangeditor": "^4.7.12"

**Comment by wangfupeng1988** [comment]
请按照 issue 模板重新提交，写明详细的复现步骤。

**Comment by 404100797** [comment]
本地打了个patches，把DomElementSelector类型改为any就可以了！
