### ISSUE TITLE
图片的图片链接丢失

### ISSUE THREAD

**Issue by cjx19961030** [wangeditor-team/wangEditor#3971]
## bug 描述

后台返回通过富文本生成的html代码之后，我通过dangerouslyInsertHtml将html代码复制进去编译器内容，然后本来在图片里面插入的图片链接会丢失，图片地址和图片描述还在

## 你预期的样子是？

图片链接不丢失

## 浏览器及版本号

*请输入内容……*

## wangEditor 版本

"@wangeditor/editor-for-vue": "^5.1.8-10",

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

- 步骤一
- 上传图片
- 步骤二
- 编辑图片地址
- 步骤三
- 通过getHtml生成的内容后，用dangerouslyInsertHtml将富文本 复制到文本编辑器

**Comment by wangfupeng1988** [comment]
你执行 `dangerouslyInsertHtml` 传入的 html 具体是什么，回复到这里。

**Comment by cjx19961030** [comment]
> 你执行 `dangerouslyInsertHtml` 传入的 html 具体是什么，回复到这里。

<p><span></span><a href="https://www.baidu.com/" target="_blank"><span>春季促销活动</span></a><span>              </span></p><p><span>111</span></p><p><span><br></span><img src="https://oss-product.msldd.com/shop/oss/30017588df9820ee6e788424b672daec.png" alt="哈哈哈" data-href="http://192.168.3.70:1818/zh/product/productlist" style=""/><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p>

**Comment by cjx19961030** [comment]
> 你执行 `dangerouslyInsertHtml` 传入的 html 具体是什么，回复到这里。

包括图片的style也会丢失
`<p><span><br></span><img src="https://oss-product.msldd.com/shop/oss/bb80b8eecfdbed36dd05e4bfc9073427.jpg" alt="哈哈哈" data-href="www.baidu.com" style="width: 50%;"/><span><br></span></p><p><span><br></span></p><p><span><br></span></p><p><span><br></span></p>`
![image](https://user-images.githubusercontent.com/51942659/160036904-c798721c-3fcb-4401-bb26-c4a8c59fb493.png)

**Comment by cjx19961030** [comment]
> 你执行 `dangerouslyInsertHtml` 传入的 html 具体是什么，回复到这里。

其实一开始是用你文档vue3那个defaultHtml的，可是发现我直接复制你文档demo的代码也回显不了
![image](https://user-images.githubusercontent.com/51942659/160042535-6b0ee4ca-1a3b-46bc-a950-c95cf0b316f4.png)

**Comment by cjx19961030** [comment]
问题已经自行排查出来了，更新了一下@wangeditor/editor 和 @wangeditor/editor-for-vue@next，问题就解决了 @wangfupeng1988
