### ISSUE TITLE
回车在chrome中控制台报错：Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.

### ISSUE THREAD

**Issue by mybells** [wangeditor-team/wangEditor#3973]
## bug 描述

初始进入有wangEditor的页面时，内容栏为空且失焦时，不要点击页面其他地方，直接回车。在chrome中控制台报错：Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
但是不影响后续操作

发现是这块代码的问题，需要做兼容处理
![image](https://user-images.githubusercontent.com/23007275/160086915-0ae7e7c9-5967-4667-b4b9-ef31f9e85574.png)
在网页使用者点击一个加载完毕的新打开的页面之前，rangeCount的值是0。在使用者点击页面之后，rangeCount的值变为1，即使并没有可视的选区(selection)。
该参数指定需要被处理的子集编号（从零开始计数）。如果该数值被错误的赋予了大于或等于 [rangeCount](https://developer.mozilla.org/en-US/docs/Web/API/Selection/rangeCount) 结果的数字，将会产生错误。

## 你预期的样子是？

控制台没报错

## 浏览器及版本号

chrome 版本 99.0.4844.83（正式版本） (x86_64)

## wangEditor 版本

4.7.11

## 官网能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

1. 第一次进入有wangeditor的页面，且页面失焦
2. 直接点击键盘回车
3. 鼠标光标聚焦在wangeditor编辑栏中，浏览器控制台报错。Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
