### ISSUE TITLE
怎么把文字增加一个框框

### ISSUE THREAD

**Issue by baobeiqie** [wangeditor-team/wangEditor#3974]
## 问题描述

*怎么把文字增加一个框框，
![image](https://user-images.githubusercontent.com/29722067/160095873-421b9b15-2840-42a6-bc41-02147ff0b162.png)
*

## wangEditor 版本

*V5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
为啥要加一个框？以及什么情况下要加框？需要你详细描述一下背景和具体功能。

**Comment by baobeiqie** [comment]
主要在某些新闻里面，在已经去世的人的姓名的外面，对人名加框，这个叫做“示亡号”，是表示这个人已经死了的一种符号，传递所标示的人物在近期内已死亡的信息，并借以表示悼念

**Comment by wangfupeng1988** [comment]
这个功能你需要自行扩展，首先你需要参考这个文档 https://www.wangeditor.com/v5/guide/development.html#render
然后可以参考“附件”的源码 https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment/tree/main/src/module

你要显示的这个样子，和“附件”显示的样子有点相似。
