### ISSUE TITLE
V4.7.12在IE11 下点击本地图片上传时，提示：“Promise”未定义

### ISSUE THREAD

**Issue by long-ge-sz** [wangeditor-team/wangEditor#3975]
## bug 描述

在IE11 下点击本地图片上传时，控制台提示：wangEditor.js (216,5) “Promise”未定义
在chrome下没有该问题，V3版本也没有该问题

## 你预期的样子是？

IE11下能上传本地图片

## 浏览器及版本号

IE 11

## wangEditor 版本

4.7.12

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

<script type="text/javascript" src="https://unpkg.com/wangeditor/dist/wangEditor.js"></script>
    <script type="text/javascript">
        const E = window.wangEditor
        const editor = new E('#div1')
      
        editor.config.uploadImgServer = 'uploads.php';
        editor.config.uploadFileName = "file";
        editor.config.uploadImgHooks = {  
            error: function (xhr, editor) {
                alert("2：" + xhr + "请查看你的json格式是否正确，图片并没有上传");
            },
            fail: function (xhr, editor, result) {
                alert("1：" + xhr + "请查看你的json格式是否正确，图片上传了，但是并没有回显");
            },
            success:function(xhr, editor, result){
                //console.log(result)
            },
            customInsert: function (insertImg, result, editor) {
                insertImg(result.url);
            }
        };
        editor.create()
    </script>

**Comment by wangfupeng1988** [comment]
自己引入一个 Promise 的 polyfill 吧，百度搜一下“javascript promise polyfill”
