### ISSUE TITLE
请问如何在回显内容时保持文本样式图片等

### ISSUE THREAD

**Issue by Siegolaid** [wangeditor-team/wangEditor#3976]
## 问题描述

显示不知道如何回显内容，
后来发现要先 editor.focus() 再 editor.insertText() 才有效
然而回显后的内容是带标签的文本，而不是预期效果（加大后的字体）

## wangEditor 版本

v5.10.0

## 是否查阅了文档 ？

是，实在是琢磨不出来了

**Comment by wangfupeng1988** [comment]
你说一个具体的例子吧。
想回显什么内容，你是通过什么 API 进行的？（用 insertText 只能插入纯文本）

**Comment by Siegolaid** [comment]
我其实就想实现：存的时候是什么样式，回显就什么样式……没成功

我换成v4，用 editor.txt.html 解决了。

发自我的iPhone

**Comment by wangfupeng1988** [comment]
> 我其实就想实现：存的时候是什么样式，回显就什么样式……没成功

v5 肯定也支持的。

v5 预计下个月要正式发布了，到时 v4 就没精力维护了。

**Comment by Siegolaid** [comment]
好的，辛苦了作者了
