### ISSUE TITLE
setNodes 使用问题

### ISSUE THREAD

**Issue by qiang9420d** [wangeditor-team/wangEditor#3977]
## 问题描述

*请输入遇到的问题...*
setNodes 怎么修改通过editor.getElemsByType('image')获取的IMG标签的SRC？
 ## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
以这个 demo 为例 http://106.12.198.214:8882/main/examples/default-mode.html 

先点击“create editor”按钮创建编辑器，然后在浏览器控制台执行如下代码

```js
const images = editor.getElemsByType('image')
const domNode = document.getElementById(images[0].id)
const slateNode = wangEditor.DomEditor.toSlateNode(editor, domNode)
const path = wangEditor.DomEditor.findPath(null, slateNode)
wangEditor.SlateTransforms.setNodes(editor, { src: "https://www.baidu.com/img/flexible/logo/pc/result@2.png" }, { at: path })
```

PS：在 webpack 等模块化代码中，可以这样获取 SlateTransforms 和 DomEditor ，如下：

```js
import { SlateTransforms, DomEditor } from '@wangeditor/editor'
```

**Comment by qiang9420d** [comment]
wangEditor 是哪来的？
