### ISSUE TITLE
建议根部加上默认样式，防止从父节点继承样式时导致编辑器样式错乱。

### ISSUE THREAD

**Issue by zomixi** [wangeditor-team/wangEditor#3979]
## bug 描述

父节点有文本样式时，会导致编辑器样式错乱

## 你预期的样子是？

编辑器有自己的固定样式，而不是需要用户去做重置样式的工作。（我看官网例子父节点有样式text-align: left;）

## 浏览器及版本号

Google Chrome 99.0.4844.84（正式版本） （64 位）

## wangEditor 版本

4.7.12

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

给官网编辑器父节点加上文本样式
![image](https://user-images.githubusercontent.com/33776415/160526858-578e3e27-73e3-4a8c-829f-4727e28225ef.png)

**Comment by wangfupeng1988** [comment]
如被外部 css 影响了，自己写 css 覆盖即可。这不是啥大问题。
