### ISSUE TITLE
编辑器4v 新增格式刷

### ISSUE THREAD

**Issue by Monkeyqin** [wangeditor-team/wangEditor#3981]
在4.0版本上，新增一个格式刷功能，类似头条发布内容页面的样子。

![image](https://user-images.githubusercontent.com/28913197/160796668-2342d33b-1e34-400b-9b72-9294ec628706.png)*

**Comment by wangfupeng1988** [comment]
暂不支持。尚无该功能的开发计划。

**Comment by dengshicheng1996** [comment]
> 在4.0版本上，新增一个格式刷功能，类似头条发布内容页面的样子。
> 
> ![image](https://user-images.githubusercontent.com/28913197/160796668-2342d33b-1e34-400b-9b72-9294ec628706.png)*

你是已经实现了吗？ 能否提供一个简易demo
