### ISSUE TITLE
我自定义了一个菜单功能，但是不知道怎么设置中英文

### ISSUE THREAD

**Issue by Livsnqin** [wangeditor-team/wangEditor#3983]
## 问题描述
我自定义了一个菜单功能，但是不知道怎么设置中英文
*请输入遇到的问题...*
我自定义了一个菜单功能，中文显示正常，英文状态下tooltip显示前面会加上menus.title.
具体为我想要的是eliminate，却显示的是   menus.title.eliminate
## wangEditor 版本
4.6.13
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

```js
      const { $, BtnMenu, DropListMenu, PanelMenu, DropList, Panel, Tooltip } = E
      const that = this
      let text = that.commonVar.getZhEn('清除','eliminate')
      console.log(text)
      // 第一，菜单 class ，Button 菜单继承 BtnMenu class
class AlertMenu extends BtnMenu {
    constructor(editor) {
      // data-title属性表示当鼠标悬停在该按钮上时提示该按钮的功能简述
        const $elem = E.$(
            `<div class="w-e-menu" data-title="${text}">
             <img style="width:16px;height:16px" src=${that.imgs} />
            </div>`
        )
        super($elem, editor)
    }
```

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考这里 https://www.wangeditor.com/doc/pages/12-%E5%A4%9A%E8%AF%AD%E8%A8%80/

**Comment by Livsnqin** [comment]
文档我肯定都看了，不知道怎么用，文档里都是在依赖里定义好了的，我是加了一个，尝试着加一个，反而会把默认的那些也搞出这个情况

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
