### ISSUE TITLE
如何设置与表单一起提交？

### ISSUE THREAD

**Issue by epart123** [wangeditor-team/wangEditor#3986]
## 问题描述

内容编辑之后，表单提交，如果将编辑器的数据提交到后台？现在我的做法是，在提交之前，getHtml()，放到隐藏上input中，但这个方法不友好。

## wangEditor 版本

V5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by epart123** [comment]
这种方法还是不太友好，能不能做到像UE或者KindEditor那样，绑定到一个input上就能自动显示？  也能提交？

**Comment by wangfupeng1988** [comment]
暂不支持这种方式。
