### ISSUE TITLE
操作按钮 撤销和重做的英文翻译反了，麻烦尽快修复一下，谢谢

### ISSUE THREAD

**Issue by luoxiao-xy** [wangeditor-team/wangEditor#3988]
撤销和重做的英文反了，麻烦尽快修复一下
![image](https://user-images.githubusercontent.com/49856280/161235523-f55008ab-b921-4bf7-b91a-6628ba1ac3f3.png)

**Comment by luoxiao-xy** [comment]
redo应该对应恢复，undo应该对应撤销

**Comment by 15669028801** [comment]
个人认为这种简单的问题，可以自己提交一个合并请求。、

**Comment by wangfupeng1988** [comment]
@luoxiao-xy 已合并，今天发布一版。
