### ISSUE TITLE
自动排版

### ISSUE THREAD

**Issue by baobeiqie** [wangeditor-team/wangEditor#3990]
## 功能描述

能不能增加个自动排版功能。

## 提炼几个功能点

比如，一个报社有多个编辑，如果手动排版的话，每个人排出来的风格、格式可能不一样，导致发布出来的文章，有各种格式的。如果有类似ueditor的自动排版【图片中的标注字打错了，应该是自动排版，其实是一个意思】，那么老师把内容做好，点一键排版，样式基本就确定了，只需对部分文字进行微调，比如改个颜色、加粗什么的。当然，微调的这些不在一键排版范围内。

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

![image](https://user-images.githubusercontent.com/29722067/161361912-35f6ed78-b46c-403f-8868-eeb2d85f7b90.png)
![image](https://user-images.githubusercontent.com/29722067/161361940-304460df-45d5-4bb0-80fa-d578f21adff0.png)
![image](https://user-images.githubusercontent.com/29722067/161361968-31b317ee-1eb1-46fd-9479-a0df51ef1a0b.png)

**Comment by wangfupeng1988** [comment]
默认不支持。需要你自己开发自定义菜单来实现。
