### ISSUE TITLE
如何拖拽网页上的 img 元素到 editor 内？

### ISSUE THREAD

**Issue by LKL2017** [wangeditor-team/wangEditor#3991]
## 问题描述

拖拽网页上的图片（img 节点）到 editor 内，由于 dataTransfer.files 没有数据而被 bindDropImg 函数过滤掉了

## wangEditor 版本

v4.7.12

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是* https://www.wangeditor.com/doc/pages/07-%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87/

## 最小成本的复现步骤
- 在网页上拖拽 img 元素到 editor 内
- editor 内无响应

请问一下是否考虑加入类似的处理来接收 dataTransfer.items 里的内容？
另外是本地开发只能通过 append 到 editor 尾部来 hack 实现拖拽 img，请问是否有相关 API 可以直接 append 到光标处？

**Comment by wangfupeng1988** [comment]
这个功能 [V5](https://www.wangeditor.com/v5/)  支持

V5 发布在即，V4 不再有精力维护了。

**Comment by LKL2017** [comment]
@wangfupeng1988 好的 谢谢
