### ISSUE TITLE
在后台模板下引入编辑器，编辑器的图片无法居中的问题

### ISSUE THREAD

**Issue by bobolike123** [wangeditor-team/wangEditor#3992]
## 问题描述

*在NaiveUIAdmin后台引入编辑器，图片无法正常居中的问题*

## wangEditor 版本

*4.7.12*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 下载NaiveUI Admin 后台模板 git clone https://github.com/jekip/naive-ui-admin.git
- 步骤二 通过yarn 或者npm 安装v4版本的编辑器源码包
- 步骤三 在工程文件的任意的views下(src/views)选择一个页面，这里推荐src/views/dashboard/workplace/workplace.vue 下利用官方给的vue引入方法引入vue组件（因为dashboard好找）,刷新页面，随便插入一个网络图片，点击居中，会发现无法居中。
- 补充说明: 在简单的网页结构中(wangEditor直接挂载在vue的app示例下)，如下图，图片是可以正常排版的
- 
![Snipaste_2022-04-02_12-44-03](https://user-images.githubusercontent.com/29175881/161366756-7564f631-3943-486d-9ef9-a04b28915ca0.png)

但是套用了后台模板后，图片无法通过text-align:'center' 居中，但是可以通过改为flex布局居中。如下图
![Snipaste_2022-04-02_12-46-09](https://user-images.githubusercontent.com/29175881/161366805-c1536cae-0824-47c9-8487-4c2d974551ed.png)

![Snipaste_2022-04-02_12-47-22](https://user-images.githubusercontent.com/29175881/161366810-69bae2d2-e2fc-4bbd-9627-59d1a95bf4a9.png)

本人对CSS不是很精通，请问有什么方法能够解决图片居中的问题呢。

**Comment by wangfupeng1988** [comment]
加上这段 css 试试

```css
.w-e-text img {
    text-align: center !important;
}
```

**Comment by bobolike123** [comment]
还是不行，然后我把.vue文件script的scoped拿掉了也不行

**Comment by bobolike123** [comment]
找到原因了，后台用的tailwindCSS强制把img标签变成块状(display:block;)，但是编辑器里面的img标签，必须得应用内联样式才能实现居中等排版。
干扰的tailwind全局CSS样式如下.
![1111](https://user-images.githubusercontent.com/29175881/161377090-474f9dc0-1ba5-4381-a371-23d26efa7e71.png)
为此，需要在vue组件中将class = "w-e-text"下的img标签强制转换成inner-block !important; 样式并拿掉scoped限制符，如下图所示，即可解决问题。
![222](https://user-images.githubusercontent.com/29175881/161377096-e99970a6-12a8-44ab-a3e3-199ded84399b.png)

建议：开发的时候考虑到编辑器被外部CSS全局样式干扰的问题，毕竟脚手架开发是趋势，编辑器在某个CSS样式框架下或多或少会受其影响导致某些功能异常。希望wangEditor能越做越好

**Comment by wangfupeng1988** [comment]
好，感谢反馈~ 以后我加上这个

**Comment by XuLiwei-S** [comment]
的确是tailwindcss(v4)的原因,tailwind强制将图片设置为display:block
解决方法:在 @import "tailwindcss" 引入tailwindcss 的文件中添加以下代码
@layer base {
  p img,
  div img {
    display: inline-block;
    max-width: 100%;
    height: auto;
    vertical-align: middle;
  }
}
