### ISSUE TITLE
v5网页一起复制图片和汉字， 图片没有复制成功?

### ISSUE THREAD

**Issue by lwangjun** [wangeditor-team/wangEditor#3993]
## bug 描述
v5网页一起复制图片和汉字， 图片没有复制成功?
*请输入内容……*
 
![image](https://user-images.githubusercontent.com/37007795/161372823-8cedb705-97ad-46d4-b6b5-59d66ca84be6.png)
汉字和图片

## 你预期的样子是？
全部数据
 
 
![image](https://user-images.githubusercontent.com/37007795/161373085-189bf732-6612-4693-ae0e-b13e4fd6ff19.png)

## 浏览器及版本号

Google Chrome   99.0.4844.84

## wangEditor 版本

v5

## 官网能否复现该 bug ？

能 

## 最小成本的复现步骤
复制的内容
https://ysg.ckcest.cn/ysgNews/1217885.html
图片和标题
在 https://www.wangeditor.com/demo/zh-CN/  图片不显示

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
粘贴的内容，HTML 格式不可控，所以 wangEditor 目前无法全部解析。

如下图，你给出的示例，`<img>` 在 `<span>` 内部，目前解析不了。

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/9583120/161374342-3b96f9f4-b016-4d29-be71-6e5989999deb.png">

**Comment by lwangjun** [comment]
谢谢
