### ISSUE TITLE
关于设置html回显问题

### ISSUE THREAD

**Issue by comxza** [wangeditor-team/wangEditor#3994]
## 问题描述

*请输入遇到的问题...*
如何回显编辑器回显类容html
## wangEditor 版本

*请输入内容……*
0.15.18
## 是否查阅了文档 ？
已查阅
（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 第一种
- 
![image](https://user-images.githubusercontent.com/21981010/161391994-f0912ee3-c5a6-4b17-98be-7e16c86d13c0.png)
使用此方案  内容为后台返回，但是编辑器不显示。不知道是不是方式不对
- 第二种
![image](https://user-images.githubusercontent.com/21981010/161392046-4f547842-fd66-4169-a4a4-8f6cba611f40.png)
通过此方案虽然可以回显并且显示类容在编辑器，但是他会默认聚焦到最后，并不是开头，或者不聚焦显示在开头

**Comment by wangfupeng1988** [comment]
就用你的第一种方式即可。

参考这个 demo 的网页源码 http://106.12.198.214:8882/main/examples/parse-html.html

<img width="595" alt="image" src="https://user-images.githubusercontent.com/9583120/161407511-748a48e0-83cd-4cb0-965c-8a3b371615be.png">

**Comment by comxza** [comment]
> 就用你的第一种方式来做。
> 
> 参考这个demo的网页源码http://106.12.198.214:8882/main/examples/parse-html.html
> 
> <img alt="图片" width="595" src="https://user-images.githubusercontent.com/9583120/161407511-748a48e0-83cd-4cb0-965c-8a3b371615be.png">
  

我用第一种方案，编辑器出来了  但是内容没出来

**Comment by wangfupeng1988** [comment]
你参照我这个 demo ，写一个最简单的示例，看能出来吗？
