### ISSUE TITLE
文档没写如何从V4迁移到V5

### ISSUE THREAD

**Issue by JmyFilm** [wangeditor-team/wangEditor#3998]
## 问题描述

请问如何从V4迁移到V5

## wangEditor 版本

V4

## 是否查阅了文档 ？

看了

**Comment by wangfupeng1988** [comment]
遇到了什么具体的问题？

**Comment by JmyFilm** [comment]
就是没有找到迁移的教程文档，不知道有哪些破坏性改动🤣

**Comment by wangfupeng1988** [comment]
V5 改动确实挺大的，从底层重构了。你可以把文档目录先看一遍，花不了多长时间。有疑问在这里回复即可。

**Comment by zuoliang0** [comment]
请问作者能否在文档中提供一份如何用原生js的快速开始，我看现在文档很多地方是typescript写的，并且也用到了类似这种语法，我不是很清楚这种语法如果直接用来写简单的没有框架的html是否可以正常使用。感谢
`
// CDN 引入 css 和 js
// const { createEditor, createToolbar } = window.wangEditor
`

**Comment by wangfupeng1988** [comment]
@zuoliang0 要不你直接看 demo 的网页源码吧，这是 js 的： https://www.wangeditor.com/demo/

**Comment by wangfupeng1988** [comment]
@zuoliang0 感谢，你可以往这个 repo https://github.com/wangeditor-team/wangEditor-v5-doc  提交 pull request

**Comment by zuoliang0** [comment]
不是，我不是说改文档，我意思是国际化文件有内置在哪儿吗这块儿我可以提供繁中 、 英、日、韩翻译

**Comment by zuoliang0** [comment]
因为做多语言翻译需要有一份完整的前置语言，比如中文，然后让翻译人员翻译成其他语种，现在我在代码中看了一下
https://github.com/wangeditor-team/wangEditor/blob/master/packages/core/src/i18n/index.ts
里面没有明确哪些字符需要翻译，这块儿需要怎么弄呢？

**Comment by zuoliang0** [comment]
这样分散在不同地方真不是一个好办法，不方便做国际化了，能否提供一个文档完整的收集这些内容，我们以插件的形式提供呢？

**Comment by zuoliang0** [comment]
嗯，我意思如果你有时间，把这些收集一下，写到文档里面，就算不是我来做维护，其他同学想做如果有一个统一的地方查，是不是也会方便很多
