### ISSUE TITLE
选择区域文本进行“引用“格式化的时候，会对每行单独进行”引用“处理。这个可以改成对选中的文本格式化在一起吗

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor#3999]
## 问题描述

选择区域文本进行“引用“格式化的时候，会对每行单独进行”引用“处理。这个可以改成对选中的文本格式化在一起吗

## wangEditor 版本

wangEditor v5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/13927744/161913986-bd4b9168-81ee-4a4f-a408-8572d84161e6.png)

预期是这样
![image](https://user-images.githubusercontent.com/13927744/161913913-d9d293c6-4c08-4d0a-b0f8-9fc00c82c261.png)

**Comment by wangfupeng1988** [comment]
暂不支持这样操作。

不过，“引用”内部是支持换行的。
