### ISSUE TITLE
vue onfocus onblur 事件不生效

### ISSUE THREAD

**Issue by lxy030988** [wangeditor-team/wangEditor#4000]
## bug 描述

onblur 事件不能触发

## 你预期的样子是？

onblur 事件及时触发

## 浏览器及版本号

谷歌100

## wangEditor 版本

4.7.11

## 官网能否复现该 bug ？

能/不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

[查看示例](https://stackblitz.com/edit/vitejs-vite-lh9ndq?file=src/components/Editor.vue)

**Comment by wangfupeng1988** [comment]
复现了。

不过目前 V5 发布在即，个人没精力做 V4 。所以，建议你直接去使用 [V5](https://www.wangeditor.com/v5/) 版本

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。

**Comment by lizy-CZ** [comment]
V5 这个 issus 也是存在的
