### ISSUE TITLE
输入框中还有个输入框

### ISSUE THREAD

**Issue by laoa1717** [wangeditor-team/wangEditor#4001]
## 问题描述

*输入框中还有个输入框*

## wangEditor 版本

*^4.7.6*

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/31725500/162114522-e66b16f6-a646-417c-94cd-5aa3d9d46a28.png)

**Comment by wangfupeng1988** [comment]
请重新描述复现步骤，给出关键代码。

**Comment by laoa1717** [comment]
<template>
  <div class="editor-container">
    <div id="editor-box"></div>
    <div class="bottom">
      <el-button type="primary" @click="onSubmitClick">{{
        $t('msg.article.commit')
      }}</el-button>
    </div>
  </div>
</template>

<script setup>
import E from 'wangeditor'
import { onMounted, defineProps, defineEmits, watch } from 'vue'
import i18next from 'i18next'
import { useStore } from 'vuex'
import { commitArticle, editArticle } from './commit'
import { watchSwitchLang } from '@/utils/i18n'

const store = useStore()
const props = defineProps({
  title: {
    required: true,
    type: String
  },
  detail: {
    type: Object
  }
})

const emits = defineEmits(['onSuccess'])

// Editor实例
let editor
// 处理离开页面切换语言导致 dom 无法被获取
let el
onMounted(() => {
  el = document.querySelector('#editor-box')
  initEditor()
})

const initEditor = () => {
  editor = new E(el)
  editor.config.zIndex = 1
  // 菜单栏提示
  editor.config.showMenuTooltips = true
  editor.config.menuTooltipPosition = 'down'
  editor.create()
  // 国际化相关处理
  editor.config.lang = store.getters.language === 'zh' ? 'zh-CN' : 'en'
  editor.i18next = i18next

  editor.create()
}

watchSwitchLang(() => {
  if (!el) return
  const htmlStr = editor.txt.html()
  editor.destroy()
  initEditor()
  editor.txt.html(htmlStr)
})

const onSubmitClick = async () => {
  if (props.detail && props.detail._id) {
    // 编辑文章
    await editArticle({
      id: props.detail._id,
      title: props.title,
      content: editor.txt.html()
    })
  } else {
    // 创建文章
    await commitArticle({
      title: props.title,
      content: editor.txt.html()
    })
  }

  editor.txt.html('')
  emits('onSuccess')
}

// 编辑相关
watch(
  () => props.detail,
  (val) => {
    if (val && val.content) {
      editor.txt.html(val.content)
    }
  },
  {
    immediate: true
  }
)
</script>

**Comment by laoa1717** [comment]
### 第一步：用Vue3创建模板
```
<template>
<div id="editor-box"></div>
</template>
```
### 第二步：创建实例

```
<script setup>
import E from 'wangeditor'

// Editor实例
let editor
// 处理离开页面切换语言导致 dom 无法被获取
let el
onMounted(() => {
  el = document.querySelector('#editor-box')
  initEditor()
})
const initEditor = () => {
  editor = new E(el)
  editor.config.zIndex = 1
  // 菜单栏提示
  editor.config.showMenuTooltips = true
  editor.config.menuTooltipPosition = 'down'
  editor.create()
  // 国际化相关处理
  editor.config.lang = store.getters.language === 'zh' ? 'zh-CN' : 'en'
  editor.i18next = i18next

  editor.create()
}
</script>
```
**版本号 "wangeditor": "^4.7.6",**

**Comment by wangfupeng1988** [comment]
你监听一下，执行了几次 `editor.create()` ？

PS：如果初次使用，强烈推荐直接使用 [V5](https://www.wangeditor.com/v5/guide/for-frame.html#vue3) 版本。V5 计划下周就要正式发布了。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
