### ISSUE TITLE
无法设置固定不可删除的文本

### ISSUE THREAD

**Issue by maowazi** [wangeditor-team/wangEditor#4002]
## 功能描述

需求要做成插件里要有固定不可删除的文本及可以删除的文本，例如给用户一个模板有固定的标题或开头；

## 提炼几个功能点

- 功能1 可以设置不删除的文字；
- 功能2 可以设置多个不可删除的文本；
- 功能3 不可删除及可以删除的可以拼接一起显示并设置不通的颜色；

## 原型图

![image](https://user-images.githubusercontent.com/49268006/162149852-b83b598b-df05-4850-8b22-3ef7671a57c5.png)

- 加粗部分不可删除；

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
暂不支持这个功能。
