### ISSUE TITLE
一个页面中同时有多个编辑器时输入内容后光标消失

### ISSUE THREAD

**Issue by Ellen-DUAN** [wangeditor-team/wangEditor#4003]
## 问题描述

现在有两个编辑器，一个用来输入文字，另一个用来展示。现在的问题是在第一个编辑器中输入文字后，光标消失。

## wangEditor 版本

4.7.13

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

https://stackblitz.com/edit/editor-demo-1-cr6pfv?file=Editor.js

在第一个编辑器中输入任何内容都可复现问题。

**Comment by wangfupeng1988** [comment]
为啥展示也用编辑器呢？直接显示 HTML 即可。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
