### ISSUE TITLE
能否將插入視頻連結的placeholder寫死的部分刪除

### ISSUE THREAD

**Issue by heaven-hub** [wangeditor-team/wangEditor#4005]
## 能否將插入視頻連結的placeholder寫死的部分刪除

*能否將插入視頻連結的placeholder寫死的部分刪除*

## wangEditor 版本

*4.7.5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

- 步骤一
- 點擊插入視頻，input的placeholder有一部分是寫死的，：<iframe src=... ></iframe>
- 步骤二
- 希望將這個部分的字符串拿掉
- 步骤三

**Comment by wangfupeng1988** [comment]
暂不支持。
