### ISSUE TITLE
disable()不能用了

### ISSUE THREAD

**Issue by shibaoqian** [wangeditor-team/wangEditor#4006]
## bug 描述

*onCreated时，使用disable禁用编辑器不可用*

## 你预期的样子是？

*预期执行editor.disable()，可禁用编辑器*

## 浏览器及版本号

*chrome 100.0.4896.75*

## wangEditor 版本

*    "@wangeditor/core": "^0.14.0",
    "@wangeditor/editor": "^0.15.14",
    "@wangeditor/editor-for-vue": "^5.1.8-11",
    "@wangeditor/plugin-ctrl-enter": "^1.0.2",*

## 官网能否复现该 bug ？

能

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/42538416/162350891-48b81632-0b1b-4dc5-92d8-dc8576194a1a.png)

直接在demo就可以复现

**Comment by liuqh0609** [comment]
尝试升级一下editor的相关包到最新版本：
```json
    "@wangeditor/editor": "^0.15.18",
    "@wangeditor/editor-for-vue": "^5.1.9",
```

**Comment by shibaoqian** [comment]
> 尝试升级一下编辑器的相关包到最新版本：
> 
> ```json
>     “@wangeditor/editor”：“ ^0.15.18 ”，
>      “@wangeditor/editor-for-vue”：“ ^5.1.9 ”，
> ```

我切换到这个版本以后，就直接工具栏都没了
![image](https://user-images.githubusercontent.com/42538416/162357894-8936e01b-0008-4220-aff5-c4db82f042bf.png)

**Comment by liuqh0609** [comment]
参考文档修改ToolBar组件[https://www.wangeditor.com/v5/guide/for-frame.html#vue3](https://www.wangeditor.com/v5/guide/for-frame.html#vue3)。
注意新版是移除了`editorId`的，取而代之的是`editor`属性

**Comment by shibaoqian** [comment]
改了的呀
![image](https://user-images.githubusercontent.com/42538416/162360313-e37b427c-7e29-4ff7-866d-a4c54db19039.png)

**Comment by shibaoqian** [comment]
> 参考文档修改工具栏组件https://www.wangeditor.com/v5/guide/for-frame.html#vue3。注意属性 新版是移除`editorId`的，取而代之的是`editor`

改了的呀
![image](https://user-images.githubusercontent.com/42538416/162360764-9ea2dc04-e80d-40a8-83dc-32aea5e9cd3d.png)

**Comment by wangfupeng1988** [comment]
不要在 onCreated 中执行 disable() ，你可以选择
1. 定义一个按钮，点击按钮执行 disable() ，如这个 demo https://stackblitz.com/edit/vue3-wangeditor-demo?file=src%2Fcomponents%2FBasicEditor.vue
2. 编辑器配置设置“只读模式” https://www.wangeditor.com/v5/guide/editor-config.html#readonly

**Comment by shibaoqian** [comment]
> 不要在 onCreated 中执行 disable() ，你可以选择
> 
> 1. 定义一个按钮，点击按钮执行 disable() ，如这个 demo https://stackblitz.com/edit/vue3-wangeditor-demo?file=src%2Fcomponents%2FBasicEditor.vue
> 2. 编辑器配置设置“只读模式” https://www.wangeditor.com/v5/guide/editor-config.html#readonly

确实，解决了。
谢谢~
