### ISSUE TITLE
连续上传图片视频后图片视频中间无法聚焦光标空行，再次编辑的时候也无法在视频后面聚焦光标输入内容

### ISSUE THREAD

**Issue by 595789072** [wangeditor-team/wangEditor#4008]
## 问题描述

*连续上传图片视频后图片视频中间无法聚焦光标空行，再次编辑的时候也无法在视频后面聚焦光标输入内容*

## wangEditor 版本

*V4*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 上传图片
- 上传视频
- 在图片与视频中间换行输入文字

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/v5/) 发布在即，建议有条件升级 V5 吧。

V4 的这些问题，目前没精力排查，业余维护，还请体谅。

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
