### ISSUE TITLE
onblur事件有时不能正常触发

### ISSUE THREAD

**Issue by cadreman** [wangeditor-team/wangEditor#4011]
## bug 描述

*编辑器的onblur事件有时不能正常触发。*

## 你预期的样子是？

*当编辑器失去焦点时能稳定地触发onblur事件*

## 浏览器及版本号

Microsoft Edge
版本 100.0.1185.36 (正式版本) (64 位)

## wangEditor 版本

*V4*

## 官网能否复现该 bug ？

没有地方测试

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请详细说明复现步骤

**Comment by wangfupeng1988** [comment]
[V5](https://www.wangeditor.com/) 已正式发布，v4 的 issue 将暂停处理。
该项目也是业余维护的，精力不够，还请体谅~

推荐尽快升级到 V5 版本。
