### ISSUE TITLE
使用序列时没有内容的空行可否不要添加？

### ISSUE THREAD

**Issue by afan0228** [wangeditor-team/wangEditor#4012]
## 问题描述

使用序列时没有内容的空行可否不要添加？

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com/doc](https://www.wangeditor.com/doc/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 使用序列时没有内容的空行可否不要添加？
- 步骤二 使用序列时没有内容的空行不加li标签？
- 步骤三

**Comment by wangfupeng1988** [comment]
那你如何创建一个新的`<li>` 并输入内容呢？

**Comment by afan0228** [comment]
可否实现类似Word文档的操作方式呢？

**Comment by wangfupeng1988** [comment]
可直接说明你预期的样子。

**Comment by afan0228** [comment]
期望如下：
![图片](https://user-images.githubusercontent.com/8581365/162855160-2108a3a9-d543-427c-9e53-3eda48654532.png)

**Comment by wangfupeng1988** [comment]
这个实现不了。

如果中间分开了，那序号就得从 1 开始重新计算，而不是从 2 继续。如下图：
<img width="337" alt="image" src="https://user-images.githubusercontent.com/9583120/162867143-f9ecc871-a15e-4689-b755-ad6c23a65eeb.png">
