### ISSUE TITLE
移动端可用编辑

### ISSUE THREAD

**Issue by seanock** [wangeditor-team/wangEditor#4017]
## 功能描述

请问有没有计划预计什么时候支持移动端编辑呢？

## 提炼几个功能点

- 功能1
   可以在移动端编辑，如知乎移动端的编辑器和今日头条的移动端编辑器等等。

**Comment by seanock** [comment]
很喜欢这个编辑器，但是不敢用，怕公司说要支持移动端编辑就悲催了。

**Comment by wangfupeng1988** [comment]
暂不支持移动端编辑。
