### ISSUE TITLE
插入表格

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4021]
## bug 描述

在编辑器开始 插入表格后，上边会多出来一行

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本:google浏览器， 100.0.4896.75

## wangEditor 版本

V5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 在编辑器开始 插入表格后，上边会多出来一行

这个符合预期，否则表格上面无法继续输入文字。
