### ISSUE TITLE
建议新增获取行间距、行高，字体大小、字间距等方法

### ISSUE THREAD

**Issue by dojia** [wangeditor-team/wangEditor#4023]
## 功能描述

我这编辑器的场景是这样的：编辑器宽高固定，只能在编辑框内输入，当输入的内容(含文字、表格、图片)可能超出编辑框范围的时候需要进行拦截

## 提炼几个功能点

- 获取每个node的字体大小、字间距
- 获取block类型node的行高、行间距

## 原型图

无

## 可参考的案例

功能场景有点像word，word一页输入超出时会跳到下一页。我这是需要知道输入超出一页时拦截输入，给出用户提示

**Comment by wangfupeng1988** [comment]
这你只能查询 DOM 然后获取 DOM 节点的样式了。我没有其他好的办法。
