### ISSUE TITLE
editor容器设置min-height点不到焦点

### ISSUE THREAD

**Issue by kfuudotcn** [wangeditor-team/wangEditor#4026]
我的目的是想设置编辑器最大高度是多少，最小高度是多少。

最大高度我是用这种方法，最大高度可行。
.w-e-scroll{
    max-height: 600px;
    overflow-y: auto;
}

最小高度，不管是设置editor容易还是 .w-e-scroll，设置 min-height都会导致无法点击到编辑器焦点
如果设置height，那编辑器高度就固定了，不能根据内容自动增高

![image](https://user-images.githubusercontent.com/63281264/163134399-304af3dd-9a07-42d8-8407-597a048f75b2.png)

**Comment by wangfupeng1988** [comment]
参考这的 demo 的网页源代码 https://www.wangeditor.com/demo/like-qq-doc.html

看最后几行。

**Comment by kfuudotcn** [comment]
感觉大佬，已解决。但是我觉得这问题应该在editor自身上去解决^_^
