### ISSUE TITLE
v4版本走cdn引入js，TS类型如何引入

### ISSUE THREAD

**Issue by jyxu1016** [wangeditor-team/wangEditor#4027]
## 问题描述

*v4版本走cdn引入js，TS如何引入呢？例如：
import type Editor from 'wangeditor/src/editor/index';
import type { PanelConf, PanelTabConf } from 'wangeditor/src/menus/menu-constructors/Panel';*

## wangEditor 版本

*4.4.0*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
js 中不识别 ts 类型，把 ts 相关的语法都删掉，只保留 js 语法即可运行。
