### ISSUE TITLE
在safari浏览器中使用editor.dangerouslyInsertHtml无效

### ISSUE THREAD

**Issue by Hxtst** [wangeditor-team/wangEditor#4029]
## bug 描述

在safari浏览器中使用editor.dangerouslyInsertHtml无效

## 你预期的样子是？

可以插入html代码

## 系统和浏览器及版本号

mac自带safari浏览器

## wangEditor 版本

5.0.0

## demo 能否复现该 bug ？

不能

## 最小成本的复现步骤

在safari浏览器中使用dangerouslyInsertHtml（）方法

**Comment by wangfupeng1988** [comment]
safari 访问 https://www.wangeditor.com/demo/ ，然后在控制台执行 `editor.dangerouslyInsertHtml('<p>hello</p>')` ，即可成功。

PS：如果想插入纯文本，需用 `editor.insertText('xxx')` 方法

**Comment by Hxtst** [comment]
我使用你的demo确实没问题，麻烦看一下https://1mrzg7.csb.app这个，也是使用的demo，但是safari浏览器确实不行
具体代码：
![image](https://user-images.githubusercontent.com/64404409/163305083-fc25299d-5537-4ea3-b13c-2799151c9d5e.png)

**Comment by Hxtst** [comment]
> 我使用你的demo确实没问题， 麻烦看一下https://1mrzg7.csb.app 这个，也是使用的demo，但是safari浏览器确实不行 具体代码： ![image](https://user-images.githubusercontent.com/64404409/163305083-fc25299d-5537-4ea3-b13c-2799151c9d5e.png)



> safari 访问https://www.wangeditor.com/demo/，然后在问题执行`editor.dangerouslyInsertHtml('<p>hello</p>')`，顺利成功。
> 
> PS：如果想插入纯文本，需用`editor.insertText('xxx')`方法

**Comment by Hxtst** [comment]
使用的是官方提供的https://codesandbox.io/s/vue2-wangeditor-demo-1rwjms?file=/src/components/MyEditor.vue 这个

**Comment by wangfupeng1988** [comment]
在 dangerouslyInsertHtml 之前，加一行 `editor.restoreSelection();` 即可。如下图

<img width="615" alt="image" src="https://user-images.githubusercontent.com/9583120/163313843-0ceffef5-7757-4dd2-b73f-cb090806e492.png">
