### ISSUE TITLE
react组件使用时工具栏不展示

### ISSUE THREAD

**Issue by teddy1209** [wangeditor-team/wangEditor#4030]
## 问题描述

react组件使用时工具栏不展示

## wangEditor 版本

5.0.0

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/](https://www.wangeditor.com/v5/toolbar-config.html#getconfig)

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

![image](https://user-images.githubusercontent.com/43714011/163198809-89bb0048-b087-492a-a98b-1d8a4f36e7bc.png)
如图，工具栏没有dom结构

**Comment by wangfupeng1988** [comment]
参考这里 demo https://www.wangeditor.com/v5/for-frame.html#react

**Comment by teddy1209** [comment]
![image](https://user-images.githubusercontent.com/43714011/163301446-f0e71e09-b8d9-48bc-b60b-acf84189c98e.png)
您好，我是完全按照demo引入的，前面的dom结构中，红框圈出的div就是由Toolbar生成的，但是不知为何只生成了一个div，没有子结构

**Comment by wangfupeng1988** [comment]
你下载 demo 能运行成功吧？
