### ISSUE TITLE
按照demo引入工具栏，不能正确渲染

### ISSUE THREAD

**Issue by teddy1209** [wangeditor-team/wangEditor#4032]
问题描述
react组件使用时工具栏不展示

wangEditor 版本
5.0.0

是否文档了？
（文档链接 [www.wangeditor.com]( [https://www.wangeditor.com/](https://www.wangeditor.com/v5/toolbar-config.html#getconfig)](https://www.wangeditor.com/%5D(https://www.wangeditor.com/v5/toolbar-config.html#getconfig))[](https://user-images.githubusercontent.com/43714011/163198809-89bb0048-b087-492a-a98b-1d8a4f36e7bc.png)

是

最小报价的复现步骤
（请告诉我们，如何复现该问题？）
![image](https://user-images.githubusercontent.com/43714011/163301900-47b2537b-02b9-4529-a4f8-a691638e748c.png)
![image](https://user-images.githubusercontent.com/43714011/163301880-8ca97b78-214d-4005-b675-d419eaafc7f2.png)
![image](https://user-images.githubusercontent.com/43714011/163302095-4cb7541c-70e0-498c-9170-016e17a8b8e4.png)

您好，工具栏是按照demo正确引入的，红框中的div就是Toolbar渲染出来的，但是没有子结构

**Comment by wangfupeng1988** [comment]
下载 demo 看能否运行成功？ https://www.wangeditor.com/v5/for-frame.html#demo-2

如果 demo 可以，而你这不行，那你需要给我一个复现问题的环境。可以在 https://stackblitz.com/ 或 https://codesandbox.io/ 做一个项目来复现问题。

**Comment by teddy1209** [comment]
新建的空白react项目可以运行，在我的项目中不行，看起来是遇到了某些问题，项目比较大，且是微前端架构，复现环境不太好构建，如果您这边暂时没有遇到，我先通过原始的creator来创建组件吧

**Comment by wangfupeng1988** [comment]
我没遇到。

我复现不了你的问题，也就没法帮你解决。

**Comment by grays820** [comment]
@teddy1209 你在setEditor里面没有设置 editor。。。
