### ISSUE TITLE
有计划整合slate-yjs插件吗？

### ISSUE THREAD

**Issue by yumcc-com** [wangeditor-team/wangEditor#4033]
## 功能描述

*slate上有个插件[slate-yjs](https://docs.slate-yjs.dev/)，请问wangeditor近期会考虑整合吗？或者有简单的slate插件转wangeditor插件的教程么？*

## 提炼几个功能点

- 多人协作

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*[DEMO](https://slate-yjs.dev/remote-cursors-overlay)*

**Comment by wangfupeng1988** [comment]
暂时没有开发多人协同功能的计划。

PS：多人协同是一个非常复杂的工程，不是集成一个插件就可以解决的。而且，你看下 slate-yjs 它的周下载量 https://www.npmjs.com/package/@slate-yjs/core ，你真的敢用于生产环境吗？
