### ISSUE TITLE
从word中粘贴样式不正确

### ISSUE THREAD

**Issue by shellyaoo** [wangeditor-team/wangEditor#4034]
## bug 描述

*从word中复制文本到编辑器中，样式出现问题*

## 你预期的样子是？

*粘贴后的样式与word中的样式保持一致*

## 系统和浏览器及版本号

- 操作系统window11
- 浏览器和版本 Google Chrome，100.0.4896.88

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 ：window11 操作系统，word版本 office2010 
- 步骤二 ：一行正常字体混合加粗、下划线属性
- 步骤三：复制到编辑器中整行都有加粗、下划线属性

**Comment by wangfupeng1988** [comment]
在贴两个截图吧：word 截个图 ； 粘贴到编辑器截个图；

**Comment by shellyaoo** [comment]
![word](https://user-images.githubusercontent.com/30407654/163322955-c6c9bb83-05d7-4bf3-b2ce-a1eb3fcc8c4c.jpg)
![wangeditor v5](https://user-images.githubusercontent.com/30407654/163322959-ef1786d4-4381-49e5-89f5-6584adcb5093.jpg)

**Comment by shellyaoo** [comment]
并且还发现了其他样式问题~见下图，我把word也传上来了，

**Comment by shellyaoo** [comment]
加粗和下划线问题，是对样式的识别范围出错了吧？？看了下，复制过来的是b标签和u标签包裹的
![1649916815(1)](https://user-images.githubusercontent.com/30407654/163324863-9c980928-da90-4e2d-8a1b-9dc4c3afffe1.jpg)
![1649917367(1)](https://user-images.githubusercontent.com/30407654/163325996-9ccb753b-c2ce-4dd8-9cfa-cab8d0722dc8.jpg)

**Comment by foxFallingSkies** [comment]
确实有问题,主要是下划线有点恶心，他会将整行都加下划线

**Comment by dengshicheng1996** [comment]
> 确实有问题,主要是下划线有点恶心，他会将整行都加下划线

感觉是解析层出的问题，将一整行的文字都解析到了一个标签里，对于特殊的文字样式没有被新增的标签包裹

**Comment by wangfupeng1988** [comment]
连续加粗、连续下划线，已经解决了，可更新 `@wangeditor/editor` 最新版本

也可以到 demo 中重新测试 https://www.wangeditor.com/demo/
