### ISSUE TITLE
在中文输入法下，无法输入中文的句号(。)、书名号《》等中文特有的符号

### ISSUE THREAD

**Issue by ljh257110** [wangeditor-team/wangEditor#4035]
## bug 描述

*在mac系统谷歌浏览器下用中文输入法(搜狗输入法、百度输入法)下，无法输入中文的句号(。)、书名号《》等中文特有的符号，会被转换成英文符号*

## 你预期的样子是？

*中文输入法下，就显示中文的符号，英文输入法就显示英文的*

## 系统和浏览器及版本号

- mac
- 谷歌浏览器

## wangEditor 版本

*5.1.10*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 直接切换中文输入法即可

**Comment by wangfupeng1988** [comment]
我在这个 demo 没复现你的问题 https://www.wangeditor.com/demo/get-html.html  （Mac OS ， Chrome 99）

<img width="975" alt="image" src="https://user-images.githubusercontent.com/9583120/163314471-baa59fe2-9ece-4719-83da-d7c66b43ed80.png">

**Comment by ljh257110** [comment]
> 我在这个演示中没有复现你的问题https://www.wangeditor.com/demo/get-html.html （Mac OS ， Chrome 99）
> 
> <img alt="图片" width="975" src="https://user-images.githubusercontent.com/9583120/163314471-baa59fe2-9ece-4719-83da-d7c66b43ed80.png">
## maxos 11.6  谷歌浏览器版本 100.0.4896.88（正式版本） (x86_64)
## qq群里另一个小伙伴也遇到了，应该是有问题的
![7851649912305_ pic_hd](https://user-images.githubusercontent.com/30766973/163316561-aded65c8-e73e-4fb6-949a-3522ac9a75ef.jpg)

**Comment by ljh257110** [comment]
我又试了一下，用mac自带的那个简体拼音就正常，但我用搜狗输入法切换的中文就不正常，qq群里还有个用百度输入法的也不行

macos 11.6 谷歌浏览器版本 100.0.4896.88（正式版本） (x86_64)









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 中午12:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 在中文输入法下，无法输入中文的句号(。)、书名号《》等中文特有的符号 (Issue #4035)





 
我在这个 demo 没复现你的问题 https://www.wangeditor.com/demo/get-html.html  （Mac OS ， Chrome 99）

**Comment by wangfupeng1988** [comment]
该问题涉及到浏览器和输入法，编辑器不好解决这个问题。我只能先观察着。

**Comment by ljh257110** [comment]
可以了，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月22日(星期五) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 在中文输入法下，无法输入中文的句号(。)、书名号《》等中文特有的符号 (Issue #4035)





 
@ljh257110 前两天解决了一个类似的 bug ，你再试试官网 demo ，这问题可以了吗？
