### ISSUE TITLE
安装vue2版本安装失败

### ISSUE THREAD

**Issue by doudou-dream** [wangeditor-team/wangEditor#4037]
## 问题描述
npm install @wangeditor/editor 安装成功
npm install @wangeditor/editor-for-vue 安装失败

## wangEditor 版本
wangEditor 5.0
*请输入内容……*

## 是否查阅了文档 ？
*是*

查阅的 wangEditor 5.0 文档 vue2 安装方法

## 最小成本的复现步骤
npm install @wangeditor/editor 安装成功
npm install @wangeditor/editor-for-vue 安装失败
## 错误信息：
PS C:\Users\HP\maidou\2022-4\doknow-web-main> npm install @wangeditor/editor-for-vue
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: webpack@4.46.0
npm WARN node_modules/webpack
npm WARN   peerOptional webpack@"*" from @storybook/addon-essentials@6.2.8
npm WARN   node_modules/@storybook/addon-essentials
npm WARN     dev @storybook/addon-essentials@"^6.2.8" from the root project
npm WARN   10 more (@storybook/vue, @vue/cli-plugin-babel, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^5.0.0" from css-loader@6.7.1
npm WARN node_modules/css-loader
npm WARN   peer css-loader@"*" from @storybook/vue@6.2.8
npm WARN   node_modules/@storybook/vue
npm WARN   1 more (vue-loader)
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @wangeditor/core@1.0.0
npm WARN node_modules/@wangeditor/core
npm WARN   @wangeditor/core@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN     peer @wangeditor/editor@">=5.0.0" from @wangeditor/editor-for-vue@1.0.0
npm WARN     node_modules/@wangeditor/editor-for-vue
npm WARN   2 more (@wangeditor/basic-modules, @wangeditor/code-highlight)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @wangeditor/core@"0.x" from @wangeditor/list-module@1.0.0
npm WARN node_modules/@wangeditor/list-module
npm WARN   @wangeditor/list-module@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @wangeditor/core@1.0.0
npm WARN node_modules/@wangeditor/core
npm WARN   @wangeditor/core@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN     peer @wangeditor/editor@">=5.0.0" from @wangeditor/editor-for-vue@1.0.0
npm WARN     node_modules/@wangeditor/editor-for-vue
npm WARN   2 more (@wangeditor/basic-modules, @wangeditor/code-highlight)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @wangeditor/core@"0.x" from @wangeditor/table-module@1.0.0
npm WARN node_modules/@wangeditor/table-module
npm WARN   @wangeditor/table-module@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @wangeditor/basic-modules@1.0.0
npm WARN node_modules/@wangeditor/basic-modules
npm WARN   @wangeditor/basic-modules@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN     peer @wangeditor/editor@">=5.0.0" from @wangeditor/editor-for-vue@1.0.0
npm WARN     node_modules/@wangeditor/editor-for-vue
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @wangeditor/basic-modules@"0.x" from @wangeditor/upload-image-module@1.0.0
npm WARN node_modules/@wangeditor/upload-image-module
npm WARN   @wangeditor/upload-image-module@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @wangeditor/core@1.0.0
npm WARN node_modules/@wangeditor/core
npm WARN   @wangeditor/core@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN     peer @wangeditor/editor@">=5.0.0" from @wangeditor/editor-for-vue@1.0.0
npm WARN     node_modules/@wangeditor/editor-for-vue
npm WARN   2 more (@wangeditor/basic-modules, @wangeditor/code-highlight)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @wangeditor/core@"0.x" from @wangeditor/upload-image-module@1.0.0
npm WARN node_modules/@wangeditor/upload-image-module
npm WARN   @wangeditor/upload-image-module@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @wangeditor/core@1.0.0
npm WARN node_modules/@wangeditor/core
npm WARN   @wangeditor/core@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm WARN     peer @wangeditor/editor@">=5.0.0" from @wangeditor/editor-for-vue@1.0.0
npm WARN     node_modules/@wangeditor/editor-for-vue
npm WARN   2 more (@wangeditor/basic-modules, @wangeditor/code-highlight)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @wangeditor/core@"0.x" from @wangeditor/video-module@1.0.0
npm WARN node_modules/@wangeditor/video-module
npm WARN   @wangeditor/video-module@"^1.0.0" from @wangeditor/editor@5.0.0
npm WARN   node_modules/@wangeditor/editor
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: postcss@7.0.39
npm ERR! node_modules/postcss
npm ERR!   postcss@"^7.0.0" from postcss-loader@3.0.0
npm ERR!   node_modules/@vue/cli-service/node_modules/postcss-loader
npm ERR!     postcss-loader@"^3.0.0" from @vue/cli-service@4.5.12
npm ERR!     node_modules/@vue/cli-service
npm ERR!       peer @vue/cli-service@"^3.0.0 || ^4.0.0-0" from @vue/cli-plugin-babel@4.5.12
npm ERR!       node_modules/@vue/cli-plugin-babel
npm ERR!         dev @vue/cli-plugin-babel@"~4.5.0" from the root project
npm ERR!       2 more (@vue/cli-plugin-eslint, the root project)
npm ERR!   postcss@"^7.0.14" from @vue/component-compiler-utils@3.2.0
npm ERR!   node_modules/@vue/component-compiler-utils
npm ERR!     @vue/component-compiler-utils@"^3.1.2" from @vue/cli-service@4.5.12
npm ERR!     node_modules/@vue/cli-service
npm ERR!       peer @vue/cli-service@"^3.0.0 || ^4.0.0-0" from @vue/cli-plugin-babel@4.5.12
npm ERR!       node_modules/@vue/cli-plugin-babel
npm ERR!         dev @vue/cli-plugin-babel@"~4.5.0" from the root project
npm ERR!       2 more (@vue/cli-plugin-eslint, the root project)
npm ERR!     @vue/component-compiler-utils@"^3.1.0" from vue-loader@15.9.6
npm ERR!     node_modules/vue-loader
npm ERR!       peer vue-loader@"^15.7.0" from @storybook/vue@6.2.8
npm ERR!       node_modules/@storybook/vue
npm ERR!         peerOptional @storybook/vue@"6.2.8" from @storybook/addon-essentials@6.2.8
npm ERR!         node_modules/@storybook/addon-essentials
npm ERR!         1 more (the root project)
npm ERR!       2 more (@vue/cli-service, the root project)
npm ERR!   43 more (autoprefixer, css-declaration-sorter, cssnano, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"^8.0.0" from postcss-modules@4.0.0
npm ERR! node_modules/postcss-modules
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\HP\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Local\npm-cache\_logs\2022-04-14T06_45_00_783Z-debug.log

**Comment by echoLC** [comment]
有可能你是自己本地环境或者 Node 版本问题，我这边自己的项目按你的操作步骤没有重现问题。
