### ISSUE TITLE
[建议]菜单分组样式问题

### ISSUE THREAD

**Issue by lcuncle** [wangeditor-team/wangEditor#4038]
## 问题描述

菜单分组包含有下拉选项的菜单时，下拉选项会盖住此菜单下面的其它菜单
![QQ截图20220414200732](https://user-images.githubusercontent.com/42888101/163387476-f726834c-b9bd-4216-b326-654d0ecc5c61.png)

![wangEditor](https://user-images.githubusercontent.com/42888101/163386569-3061d929-fe3e-4f36-a015-537b3af44a05.png)

## wangEditor 版本

wangEditor V5

## 最小成本的复现步骤

添加一个菜单分组，分组中包含有下拉选项的菜单，即可复现

## 建议

菜单分组包含有下拉选项的菜单时，下拉选项侧边显示
![demoa](https://user-images.githubusercontent.com/42888101/163387241-3903b3e1-d861-4fa9-9562-e4ae2b75740a.jpg)

**Comment by wangfupeng1988** [comment]
目前不支持你说的方式。所以，先不要把 SelectListMenu 放在 group-menu 中。
