### ISSUE TITLE
5.0.0版本什么时候发布release？

### ISSUE THREAD

**Issue by 914aaa** [wangeditor-team/wangEditor#4039]
## 问题描述

5.0.0版本什么时候发布release？

## wangEditor 版本

5.0.0

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
尚未同步到 github release ，正在同步中...

你需要什么文件，我可以单独告诉你。

**Comment by 914aaa** [comment]
> 尚未同步到 github release ，正在同步中...
> 
> 你需要什么文件，我可以单独告诉你。

我需要Git上面的release tag同步到数据库，否则无法使用新版本

**Comment by wangfupeng1988** [comment]
可以临时用这个 https://github.com/wangeditor-team/wangEditor-v5/releases/tag/v5.0.0
