### ISSUE TITLE
自定义菜单点击时会自动隐藏的问题

### ISSUE THREAD

**Issue by lclong** [wangeditor-team/wangEditor#4040]
## 问题描述

自定义菜单实现了IDropPanelMenu接口，主要是实现为选中文字增加描边颜色。现在的效果是点击一次DropPanel时，弹出的面板会自动隐藏，不能实现为文本增加描边效果的功能

## wangEditor 版本

v5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

- 步骤一：自定义菜单实现了IDropPanelMenu接口，主要是实现为选中文字增加描边颜色。
- 步骤二：现在的效果是点击DropPanel时，弹出的面板会自动隐藏。需要的效果是点击面板不隐藏，点击编辑区域内容时再隐藏。
-
![image](https://user-images.githubusercontent.com/6212279/163510329-1940f9e2-f7dd-4747-bf94-d7fb27f13fc5.png)

**Comment by wangfupeng1988** [comment]
第一，看下当 dropPanel 被弹出时，执行 `editor.isFocused()` 是什么？（如果是 `false` 就对了）

第二，点击 dropPanel 的某个元素时，要执行 `event.preventDerfault()` 。可参考"颜色"菜单的配置 https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/color/menu/BaseMenu.ts

**Comment by lclong** [comment]
好的。我试一下，谢谢。
还请问一下，是否支持禁用ctrl+b、ctrl+i等快捷键，以及修改默认菜单的iconSvg图标？谢谢

**Comment by wangfupeng1988** [comment]
这些目前不支持

**Comment by lclong** [comment]
好的，谢谢。
