### ISSUE TITLE
Vue2 常见报错 Error in ./node_modules/@wangeditor/editor/dist/index.esm.js

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#4041]
报错如下图：

![1](https://user-images.githubusercontent.com/9583120/163511329-0072a807-09f4-4b13-8ad9-5cf415610f9a.jpeg)

解决方案如下图：

![2](https://user-images.githubusercontent.com/9583120/163511339-15ee407b-dcd3-4a2c-99b0-f110faa49822.jpeg)

**Comment by huandie2012** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/8893631/163566468-a89ce302-9643-44bd-a3bf-337b54124793.png">
按照上面的方式改了webpack的相关配置，但是还是报这个错误。

**Comment by wangfupeng1988** [comment]
给一个能复现问题的 demo 吧，提交到 github 或者放在 codesandbox.io 上，给给链接。

复现不了问题，就无从下手去解决。

**Comment by wangkang185720667** [comment]
我也出现了这个报错，我已经解决了，但是在我初始化的时候报错
![image](https://user-images.githubusercontent.com/58802384/163784961-2c8bca9f-0ceb-424b-90fd-2fd78a541e91.png)

报错：Uncaught ReferenceError: globalThis is not defined

此代码报错源码：function interpolate(phrase, options) {
报错路径为：editor/index.esm.js：12708

**Comment by wangfupeng1988** [comment]
@wangkang185720667 什么浏览器，什么版本，如何复现？（这些没有，我也不知道咋复现这个问题）

**Comment by wangkang185720667** [comment]
@wangfupeng1988 好的 谢了

**Comment by finham** [comment]
![微信图片_20220425185214](https://user-images.githubusercontent.com/52123941/165075335-1971855f-8db1-4f86-98a7-09a4f71ec307.jpg)
@wangfupeng1988 开发者你好，我参考了你上述的方法，但是还是报如下错误，我不知道这两个有否关联，试了好多方法都没能解决掉...

**Comment by duanduanyie** [comment]
增加了这段还是报错include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client'),resolve('node_modules/@wangeditor')]，

in ./node_modules/_@wangeditor_editor@5.0.1@@wangeditor/editor/dist/index.esm.js

Module parse failed: Unexpected token (12822:18)
You may need an appropriate loader to handle this file type.
| 
|   const prevLocale = this.locale;
|   this.locale = { ...prevLocale,
|     strings: { ...prevLocale.strings,
|       ...locale.strings

**Comment by prot3in** [comment]
> ![微信图片_20220425185214](https://user-images.githubusercontent.com/52123941/165075335-1971855f-8db1-4f86-98a7-09a4f71ec307.jpg) @wangfupeng1988 开发者你好，我参考了你上述的方法，但是还是报如下错误，我不知道这两个有否关联，试了好多方法都没能解决掉...
> 
> 当我注释掉import {Editor, Toolbar} from "@wangeditor/editor-for-vue"后，不再报该错误。

配置文件里加个下划线就好了 'node_modules/_@wangEditor'

**Comment by prot3in** [comment]
> 增加了这段还是报错include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client'),resolve('node_modules/@wangEditor')]，
> 
> in ./node_modules/_@wangeditor_editor@5.0.1@@wangeditor/editor/dist/index.esm.js
> 
> Module parse failed: Unexpected token (12822:18) You may need an appropriate loader to handle this file type. | | const prevLocale = this.locale; | this.locale = { ...prevLocale, | strings: { ...prevLocale.strings, | ...locale.strings

  这个在配置加个下划线就行了  @_wangEditor   @duanduanyie

**Comment by STAR5201** [comment]
按图改了后还是报错

**Comment by hehanli101** [comment]
> 我也出现了这个报错，我已经解决了，但是在我初始化的时候报错 ![image](https://user-images.githubusercontent.com/58802384/163784961-2c8bca9f-0ceb-424b-90fd-2fd78a541e91.png)
> 
> 报错：Uncaught ReferenceError: globalThis is not defined
> 
> 此代码报错源码：function interpolate(phrase, options) { 报错路径为：editor/index.esm.js：12708



> globalThis is not defined

globalThis is not defined 我叶出现了这个问题 不知道你解决了没

**Comment by wangfupeng1988** [comment]
可以再参考这个 https://github.com/wangeditor-team/wangEditor/issues/4211#issuecomment-1128310354

**Comment by fyxiaokeai** [comment]
添加了resolve('node_modules/@wangeditor')，还是报./node_modules/@wangeditor/editor/dist/index.esm.js
Module parse failed: Unexpected token (12822:18)
You may need an appropriate loader to handle this file type.
| 
|   const prevLocale = this.locale;
|   this.locale = { ...prevLocale,
|     strings: { ...prevLocale.strings,
|       ...locale.strings

**Comment by wangfupeng1988** [comment]
谁能给我一个能复现该问题的 demo ？ （最简单的 demo ，不要掺杂其他无关代码）

**Comment by Charlotte007** [comment]
问题主要与cnpm有关，找不到对应的模块，webpack.base.conf.js中babel-loader的配置中，添加 resolve('node_modules/@wangeditor'), resolve('node_modules/_@wangeditor') 就可以正常引用了

**Comment by Charlotte007** [comment]
问题主要与cnpm有关，找不到对应的模块，webpack.base.conf.js中babel-loader的配置中，添加 resolve('node_modules/@wangeditor'), resolve('node_modules/_@wangeditor') 就可以正常引用了

**Comment by bcmaidou** [comment]
能复现问题的demo     https://github.com/bcmaidou/wang-edit
node -v 14.15.0
最开始我以为是node版本问题。升级之后，官网的demo能正常跑起来，但是用在自己的工程里面就是不行

**Comment by bcmaidou** [comment]
> 谁能给我一个能复现该问题的 demo ？ （最简单的 demo ，不要掺杂其他无关代码）
能复现问题的demo https://github.com/bcmaidou/wang-edit
node -v 14.15.0
最开始我以为是node版本问题。升级之后，官网的demo能正常跑起来，但是用在自己的工程里面就是不行

**Comment by bcmaidou** [comment]
能复现问题的demo https://github.com/bcmaidou/wang-edit
node -v 14.15.0
最开始我以为是node版本问题，升级之后，官网的demo能运行起来，但是放到自己工程里面就是不行

**Comment by smithyj** [comment]
我来回复下， webpack 配置 include 应该使用正则规则，估计是 @ 符号导致的解析问题
```
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: { cacheDirectory: '.cache' },
      },
      {
        test: /\.js$/,
        include: [/node_modules\/@wangeditor/],
        loader: 'babel-loader',
        options: { cacheDirectory: '.cache' },
      },
```
@bcmaidou @duanduanyie @Charlotte007 @wangfupeng1988 @huandie2012

**Comment by GuoxiongZhang** [comment]
我按上面的方法修改了webpack的配置，在本地执行yarn build成功。但是，当我把代码配置放到测试环境，采用Jenkins构建的时候，仍然出现了该问题。难道因为Linux和Windows环境的区别吗？

**Comment by GuoxiongZhang** [comment]
具体报错信息：
/opt/npm/node_modules/@wangeditor/editor/dist/index.esm.js
Module parse failed: Unexpected token(18:966)
You may need an appropriate loader to handle this file type.
| * @param {object} options with values that will be used to replace placeholders
| *@returns {any[]} interpolated
| */function ry(e, t) {const n=/\$/g;let r=[e]}

版本信息：
@wangeditor/editor : ^5.1.23
@wangeditor/editor-for-react:  ^1.0.6

**Comment by DragonLet0727** [comment]
我说一下，是它@wangeditor里面有个index.esm.js文件里面引的时候的路径问题，改成@wangeditor/editor-for-vue即可

**Comment by KKM408** [comment]
能帮忙看一下什么原因吗？https://gitee.com/z_dj/vue-admin-template/tree/feature%2Fnew/
![image](https://user-images.githubusercontent.com/57133279/220693327-1b104150-883b-4d07-a9b5-c8eac223eae4.png)

**Comment by smithyj** [comment]
> 能帮忙看一下什么原因吗？https://gitee.com/z_dj/vue-admin-template/tree/feature%2Fnew/
> ![image](https://user-images.githubusercontent.com/57133279/220693327-1b104150-883b-4d07-a9b5-c8eac223eae4.png)

看我上面的回复 https://github.com/wangeditor-team/wangEditor/issues/4041#issuecomment-1289872683

**Comment by zhangpeibisha** [comment]
> 

请问在vue-cli 里面的 vue.config.js 里面怎么配置哦

**Comment by 1203086522** [comment]
作者大大的方法是可以解决这个问题的，有些小伙伴使用了还是在报错，原因就是引入的链接不对， 使用cnpm 、 npm、pnpm、yarn安装插件的时候，路径都是不一样的，所以要对应着改路径就可以了
![image](https://user-images.githubusercontent.com/51741106/232467397-2f3bcb1e-1fb8-4228-b6ae-7a574fc6c86a.png)

**Comment by hello-jiaojiao** [comment]
> 具体报错信息： /opt/npm/node_modules/@wangeditor/editor/dist/index.esm.js Module parse failed: Unexpected token(18:966) You may need an appropriate loader to handle this file type. | * @param {object} options with values that will be used to replace placeholders | *@returns {any[]} interpolated | */function ry(e, t) {const n=/$/g;let r=[e]}
> 
> 版本信息： @wangeditor/editor : ^5.1.23 @wangeditor/editor-for-react: ^1.0.6

我也是这个错，请问怎么解决啊

**Comment by 1203086522** [comment]
> > 具体报错信息： /opt/npm/node_modules/@wangeditor/editor/dist/index.esm.js 模块解析失败：意外令牌 （18：966） 您可能需要适当的加载程序来处理此文件类型。|*  {object} 选项，其中包含将用于替换占位符的值 |* {any[]} 插值 |*/function ry（e， t） {const n=/$/g;let r=[e]}
> > 版本信息： @wangeditor/编辑器 ： ^5.1.23 @wangeditor/editor-for-react： ^1.0.6
> 
> 我也是这个错，请问怎么解决啊

resolve( XXXX)  引入的地址不对，你的应该是resolve((这前面应该还有一段)/opt/npm/node_modules/@wangeditor)

**Comment by jerrycat123** [comment]
这个路径还是区分大小写的，我本地目录是`node_modules/@wangeditor`，填了`resolve('node_modules/@wangEditor')`死活不行，改成跟路径一致就好了

**Comment by mangy1** [comment]
![image](https://github.com/wangeditor-team/wangEditor/assets/67996468/ba874e61-34c3-451d-a24c-e42df84c96a8)
还是不行，路径是对的，我在升级babel版本6=>7时遇到了这个问题，原来这个配置是可以运行的，babel 6=>7，babel-loader 7=>8，升级后出现了这个问题。
![image](https://github.com/wangeditor-team/wangEditor/assets/67996468/07cf12d3-4f2d-410a-bdd0-511fc6f0e712)

**Comment by Amosyue** [comment]
> 

看看是不是babel7的配置文件导致的，使用babel.config.js；我这边就出现了这个情况，babel6升级到babel7出现了这个错误，改了之后就好了

**Comment by sitangruan** [comment]
尝试了上面所有办法都没有用，最后尝试了下面这个resolve配置（在webpack.base.conf.js的babel-loader部分），终于可以编译。如果你遇到一样的问题，也可以试试。

resolve('node_modules/@wangeditor/editor/dist')

**Comment by Nan-aa** [comment]
试过了上面所有解决方案 同样没有用 本地webpack3.6.2 node14.18.2 在webpack.base.conf.js的babel-loader部分配置resolve('node_modules/@wangeditor')依旧没办法通过编译

**Comment by Nan-aa** [comment]
试过了上面所有解决方案 同样没有用 本地webpack3.6.2 node14.18.2 在webpack.base.conf.js的babel-loader部分配置resolve('node_modules/@wangEditor') 依旧没办法通过编译  上面的所有方法均已尝试均报一样的错误 怀疑webpack编译问题
最终解决方法(慎用):  升级项目到webpack5版本 
花了一天时间项目配置文件统统改了一遍 最后通过编译通过功能正常使用

**Comment by Kuro-P** [comment]
### 项目配置：Vue 2、Webpack 3、Babel 7

Webpack3 对 ESM 支持有限，引入需要通过 Babel 转译才能识别， 因此要为 babel-loader 加上 preset-env。

我的项目中使用以下配置后可以正常编译了：
```
    {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
                resolve('src'), 
                resolve('node_modules/webpack-dev-server/client'), 
                resolve('node_modules/@wangeditor')
       ],
        options: {
                presets: ['@babel/preset-env']
        }
    },
```
但这种写法会覆盖项目已有的 .babelrc 配置，所以更好的写法是单独为 wangeditor 写一条 rules 进行处理：
```
      {
        test: /\.esm.js/,
        loader: 'babel-loader',
        include: /node_modules[\\/]@wangeditor[\\/]editor/,
        options: {
                presets: ['@babel/preset-env']
        }
      },
```

以上两种方法在我的机器（Mac OS）上均可以编译通过。
