### ISSUE TITLE
vue3中无法通过 DomEditor.getToolbar 获取到 toolbar 的实例

### ISSUE THREAD

**Issue by Rebornjiang** [wangeditor-team/wangEditor#4045]
## 问题描述

在 vue3 中 onMounted 钩子函数中 的nextTicket中 通过过 DomEditor.getToolbar 无法获取到 toolbar 的实例。
![image](https://user-images.githubusercontent.com/49037487/163530697-329f14a1-8237-472e-8619-32df1f6cc5a5.png)

![ad79cdd1-c8a8-4a90-ae20-db0d38d01d2c](https://user-images.githubusercontent.com/49037487/163530984-05281adc-5737-4ed5-b68a-5d206b46cacd.jpg)

## wangEditor 版本
"@wangeditor/editor": "^5.0.0",
  "@wangeditor/editor-for-vue": "^5.1.10",
  "vue": "^3.2.25",

## 是否查阅了文档 ？
查阅了，未找到 vue3 中获取 toolbar 实例的方法

## 最小成本的复现步骤
按照上面的图片中的代码即可实现

**Comment by wangfupeng1988** [comment]
通过 setTimeout 可以获取，或者点击某个按钮时也可以获取。

在 Vue3 在线 demo 中，增加如下代码

<img width="616" alt="image" src="https://user-images.githubusercontent.com/9583120/163533978-a98054d9-32a8-4888-9dec-bd504a8b2236.png">

**Comment by WangQingye** [comment]
vue2里面也获取不到，通过settimeout获取到了，略蛋疼。。

**Comment by wangfupeng1988** [comment]
也可以试试 $nextTick

**Comment by sinpor** [comment]
作者你好！

请问有没有计划支持ref获取toolbar实例或者抛出事件获取？

**Comment by wangfupeng1988** [comment]
> 作者你好！
> 
> 请问有没有计划支持ref获取toolbar实例或者抛出事件获取？

现在通过 API 获取就很方便，没必要提供其他方式了

**Comment by XueMH** [comment]
> 也可以试试 $nextTick

也不行，是null

**Comment by suifeng128** [comment]
import {DomEditor} from '@wangeditor/editor'
onMounted(() => {
  setTimeout(() => {
    console.log(DomEditor.getToolbar(editorRef.value).getConfig().toolbarKeys)
  })
})
使用这个，没问题
