### ISSUE TITLE
复制word图文，编辑器在不同客户端下返回 html 字符串结果不一致。

### ISSUE THREAD

**Issue by ddddderek** [wangeditor-team/wangEditor#4046]
## bug 描述
复制word图文，编辑器在不同客户端(两台操作系统都是win10的PC主机)下返回 html 字符串结果不一致。

## 你预期的样子是？
返回结果一致，应该包含地址为本地路径的图片节点字符串

## 系统和浏览器及版本号

- 操作系统 win10 64位
- 浏览器和版本 chrome 100.0.4896.88（正式版本） （64 位）

## wangEditor 版本
V5

## demo 能否复现该 bug ？
官网在线demo既能复现

## 在线 demo
 https://www.wangeditor.com/demo/index.html

（请告诉我们，如何最快的复现该 bug）

- 步骤一 进入官网demo，从word复制一段图文，即可复现

**Comment by wangfupeng1988** [comment]
需要补充一个示例：具体复制什么样子的图文，粘贴后是什么样子的效果，`editor.getHtml()` 返回什么

**Comment by ddddderek** [comment]
经本地对比之后发现，wps格式文章的粘贴复制编辑器会创建图片节点，word文档不会创建图片节点。请问这个有临时的解决方案么。

**Comment by ddddderek** [comment]
word editor.getHtml() 返回结果： <p>123123123123</p><p>&nbsp;</p><p><br></p>
wps editor.getHtml() 返回结果 返回结果：<p><span style="font-size: 10.5pt; font-family: 等线;">123123123123</span></p ><p><span style="font-size: 10.5pt; font-family: 等线;">&nbsp;</span></p ><p>< img src="file:///C:\Users\ADMINI~1\AppData\Local\Temp\ksohtml\wps1891.tmp.jpg" alt="" data-href="" style=""/><span style="font-size: 10.5pt; font-family: 等线;">&nbsp;</span></p >

**Comment by ddddderek** [comment]
word 返回结果：`<p>123123123123</p><p>&nbsp;</p><p><br></p>`
wps 返回结果：`<p><span style="font-size: 10.5pt; font-family: 等线;">123123123123</span></p ><p><span style="font-size: 10.5pt; font-family: 等线;">&nbsp;</span></p ><p>< img src="file:///C:\Users\ADMINI~1\AppData\Local\Temp\ksohtml\wps1891.tmp.jpg" alt="" data-href="" style=""/><span style="font-size: 10.5pt; font-family: 等线;">&nbsp;</span></p >`

插入图文如下，就是最简单的图文。
![image](https://user-images.githubusercontent.com/25541838/163537894-191607ce-df24-40bc-9969-2ff11d791584.png)

**Comment by wangfupeng1988** [comment]
咱不支持 word 图片粘贴。

你可以自定义粘贴行为 https://www.wangeditor.com/v5/editor-config.html#custompaste
