### ISSUE TITLE
使用ol / ul 嵌套，再次回显在editor中时，展示的内容不对

### ISSUE THREAD

**Issue by xiao-adan** [wangeditor-team/wangEditor#4047]
## bug 描述

在editor中使用ol / ul 嵌套时（如li中再次嵌入ul / ol），再次回显在editor中时，展示的内容不对

## 你预期的样子是？

不支持嵌套的ol / ul 或者 回显时展示的样式与输入时一致

## 系统和浏览器及版本号

- 操作系统 mac 11.6
- 浏览器和版本  Microsoft Edge  100.0.1185.39 (正式版本) (x86_64)

## wangEditor 版本

V5  "@wangeditor/editor": "^0.15.20" 

## demo 能否复现该 bug ？

官网在线demo就可以复现

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://www.wangeditor.com/demo/get-html.html
- https://www.wangeditor.com/demo/set-html.html

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

`<ul><li>amsd&nbsp;asndk&nbsp;asnd&nbsp;ansd&nbsp;</li><ul><li>amsd&nbsp;asndk&nbsp;asnd&nbsp;ansd&nbsp;</li><ul><li>amsd&nbsp;asndk&nbsp;asnd&nbsp;ansd&nbsp;</li></ul></ul></ul><p><br></p>`

方法一： 
- 直接将上方代码复制到(https://www.wangeditor.com/demo/set-html.html) setHtml输入框中，点击set Html

方法二
- 在官网“获取HTML”的editor中输入一行ol/ul，回车到第二行。
- 复制第一行的内容到第二行。
- 复制editor下方对应的getHtml内容。
- 点击左边栏“设置HTML”，将复制的getHtml内容粘贴到对应的输入框中。
- 点击set html 就可以看到结果

<img width="1330" alt="getHtml" src="https://user-images.githubusercontent.com/32729381/163540312-9a0ba703-a16a-4ab9-b5fe-2cbe81c818b2.png">
<img width="1439" alt="setHtml" src="https://user-images.githubusercontent.com/32729381/163540363-5b868cb5-7b58-4fe0-a40c-fd95cf8fe008.png">

**Comment by wangfupeng1988** [comment]
暂不支持嵌套 list
