### ISSUE TITLE
请问v5自定义菜单，如何给绑定事件呢

### ISSUE THREAD

**Issue by codedart2018** [wangeditor-team/wangEditor#4049]
## 问题描述

我自定义一个菜单过后，就是一个很简单的功能，跳转到第三方页面。我想通过点击后跳转，我看了一下文档自定义事件。但没有绑定使用上。哪儿有案例可看嘛。

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

**Comment by wangfupeng1988** [comment]
看这个 demo 的网页源代码 https://www.wangeditor.com/demo/extend-menu.html 

点击会触发其中的 `exec` 函数
