### ISSUE TITLE
vue 页面刷新报错

### ISSUE THREAD

**Issue by tech-zjf** [wangeditor-team/wangEditor#4050]
![image](https://user-images.githubusercontent.com/63299338/163579003-9e825c3c-e578-4869-a9f6-000391b5abd2.png)
![image](https://user-images.githubusercontent.com/63299338/163579122-ff183daa-407d-447d-8946-28bc11190e33.png)

**Comment by wangfupeng1988** [comment]
请按照 issue 模板重新提交一个，说明详细复现问题的步骤。

不按照模板的 issue ，不予理会
