### ISSUE TITLE
找不到 "./@wangeditor/editor-for-react" 

### ISSUE THREAD

**Issue by huyongtao-cmd** [wangeditor-team/wangEditor#4053]
## 问题描述
yarn add之后提示容器中不存在 "./@wangeditor/editor-for-react" 

*请输入遇到的问题...*
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/71239740/163662613-899cf33e-f370-4dff-9a01-f67a6578dd06.png">

## wangEditor 版本

v5

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
1. yarn add引入依赖包
2. 直接使用
<img width="899" alt="image" src="https://user-images.githubusercontent.com/71239740/163663037-fe6f2488-20f5-4a28-a3d8-61bdd474c08a.png">

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
下载文档中的 demo ，看是否可用？https://www.wangeditor.com/v5/for-frame.html#react

**Comment by uYoaiXiL** [comment]
> ## 问题描述
> yarn add 之后提示容器中不存在 "./@wangeditor/editor-for-react"
> 
> _请输入遇到的问题..._ <img alt="图片" width="1419" src="https://user-images.githubusercontent.com/71239740/163662613-899cf33e-f370-4dff-9a01-f67a6578dd06.png">
> 
> ## wangEditor 版本
> v5
> 
> _请输入内容……_
> 
> ## 是否文档了？
> （文档链接[www.wangeditor.com](https://www.wangeditor.com/)）
> 
> _是_
> 
> ## 最小报价的复现步骤
> 1. yarn add 投资依赖包
> 2. 直接使用
> 
> <img alt="图片" width="899" src="https://user-images.githubusercontent.com/71239740/163663037-fe6f2488-20f5-4a28-a3d8-61bdd474c08a.png">
> 
> （请告诉我们，如何**复**现该问题？）
> 
> * 步骤一
> * 步骤二
> * 步骤三

删除.umi文件，重新运行应该就好了
