### ISSUE TITLE
pre 代码高亮时报错

### ISSUE THREAD

**Issue by kfuudotcn** [wangeditor-team/wangEditor#4054]
页面中出现本编辑器添加的代码时，控制台报错
![image](https://user-images.githubusercontent.com/63281264/163664458-dd392677-0ff2-4ecd-a6f2-f182d9ac4b75.png)
同时代码也没有被高亮

![image](https://user-images.githubusercontent.com/63281264/163664496-188a9b1c-933a-4c61-8f59-5cdcf11039df.png)

**Comment by wangfupeng1988** [comment]
请按照 issue 模板提交，详细描述复现步骤。否则不予受理。
