### ISSUE TITLE
在“引用”里面换行可以设置成 p 标签吗？

### ISSUE THREAD

**Issue by iwubo** [wangeditor-team/wangEditor#4056]
v4版本在“引用”里面换行是p标签，升级到v5后，发现在“引用”里换行是br，这会影响之前用v4版本写的内容，如何像v4一样换行是p标签？

**Comment by wangfupeng1988** [comment]
具体是哪一步有问题？

你不用告诉我解决方案，你只描述你具体的问题即可。

**Comment by iwubo** [comment]
你好，请看附件截图。
希望br标签设置为p标签包裹每一行内容。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月16日(星期六) 晚上10:59
***@***.***&gt;;
抄送:&nbsp;"In the ***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 在“引用”里面换行可以设置成 p 标签吗？ (Issue #4056)





 
具体是哪一步有问题？
 
你不用告诉我解决方案，你只描述你具体的问题即可。

**Comment by wangfupeng1988** [comment]
没看到有截图 @iwubo

**Comment by iwubo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月16日(星期六) 晚上11:19
***@***.***&gt;;
抄送:&nbsp;"In the ***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 在“引用”里面换行可以设置成 p 标签吗？ (Issue #4056)





 
没看到有截图 @iwubo

**Comment by iwubo** [comment]
![22](https://user-images.githubusercontent.com/9998423/163680726-9f022661-8122-4b4c-985b-57ae13fbd1da.png)
@wangfupeng1988

**Comment by wangfupeng1988** [comment]
看到截图了。

但我还是不明白你的问题，为啥非得用 `<p>`，用 `<br>` 不行吗？
