### ISSUE TITLE
自定义上传图片时，希望图片的上传地址可动态配置

### ISSUE THREAD

**Issue by LucaLJX** [wangeditor-team/wangEditor#4057]
## 问题描述

使用场景：图片上传使用了aws相关的接口，每次上传都需要先动态获取上传地址，再进行上传；
因此无法在editor进行create()之前配置好config中的server，需要每次选择文件之后，动态获取上传地址并配置

## wangEditor 版本

*wangeditor@4.7.13*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
暂不支持该功能。

你可以使用自定义上传，文档里有。
