### ISSUE TITLE
富文本中需要加入select input 下拉框等表单元素

### ISSUE THREAD

**Issue by CONAN0** [wangeditor-team/wangEditor#4063]
## 问题描述

*富文本中需要加入select input 下拉框等表单元素，但是通过dangerouslyInsertHtml方法会过滤掉*

## wangEditor 版本

*wangEditor 5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 富文本中需要加入select input等表单元素，但是通过dangerouslyInsertHtml方法会过滤掉

**Comment by CONAN0** [comment]
能通过什么办法追加进去？目前用的是wangEditor 4，可以追加select input等元素，升级成wangEditor 5之后就不行了

**Comment by wangfupeng1988** [comment]
v5 目前不支持 input ，如有需要你可以自定义扩展元素 https://www.wangeditor.com/v5/development.html#%E6%A6%82%E8%BF%B0

**Comment by CONAN0** [comment]
> v5 目前不支持 input ，如有需要你可以自定义扩展元素 https://www.wangeditor.com/v5/development.html#%E6%A6%82%E8%BF%B0

有demo可以参考吗？只看到几个api介绍，不知道怎么连起来用？这边具体功能是一个html片段，里面有input元素，怎么显示呢？

**Comment by wangfupeng1988** [comment]
目前没有 input 相关的示例。

可参考的是几个插件 https://www.wangeditor.com/v5/plugins.html

**Comment by successColin** [comment]
你好 大佬   可以写个input元素相关案例吗
