### ISSUE TITLE
在设置vue2中，如果设置readOnly为true，会报错！

### ISSUE THREAD

**Issue by jiaopianjun** [wangeditor-team/wangEditor#4064]
## bug 描述

*在设置readOnly为true的时候，如果第一个是插入图片而不是文字。渲染报错。*

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/17241960/163798791-eeea71e7-fc29-4044-ae41-d00a26319703.png">

## 你预期的样子是？

*应该回显正常*

## 系统和浏览器及版本号

- 操作系统 mac
- 浏览器和版本 chrome 最新版本

## wangEditor 版本

*v5 vue2*

**Comment by liuqh0609** [comment]
我这边测试过您这边提到的问题**没办法复现**。
提供给您这边一个demo，可以对照查看一下自己的**content节点结构是否正确**：[https://github.com/liuqh0609/editor-vue2-demo/blob/main/src/components/BaseC.vue](https://github.com/liuqh0609/editor-vue2-demo/blob/main/src/components/BaseC.vue)
