### ISSUE TITLE
菜单栏可以填加主题色，来修改主题背景

### ISSUE THREAD

**Issue by yiwen9488** [wangeditor-team/wangEditor#4068]
## 功能描述
菜单栏增加主题颜色选择，选择颜色后，主题背景颜色更改
*请输入内容……*
菜单栏增加主题颜色选择，选择颜色后，主题背景颜色更改

## 提炼几个功能点

- 功能1 菜单栏增加主题颜色选择，选择颜色后，主题背景颜色更改

- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例
/* 暗色主题 */
html.dark {
    --w-e-textarea-bg-color: #333;
    --w-e-textarea-color: #fff;
    /* ...其他... */
}
*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
这个暂时不打算支持。

编辑器的主题应该是跟着系统主题来的，不应该在菜单栏随意设置。
