### ISSUE TITLE
暂时只有defaultValue ，需要采用value方便多个富文本切换，内容生效

### ISSUE THREAD

**Issue by monkey-gxp** [wangeditor-team/wangEditor#4070]
## bug 描述

目前的DefaultValue在加载时可以渲染默认数据，如果多个tab下切换使用，则不会重新渲染改组件
## 你预期的样子是？
通过 value值来确定组件的渲染

**Comment by wangfupeng1988** [comment]
我看不懂你说的是什么，哪里的 `DefaultValue` ？ 

请按照 issue 模板重新提交一个吧。
