### ISSUE TITLE
Vite2.8.0使用 wangEditorV5开发报错

### ISSUE THREAD

**Issue by HeidaLay** [wangeditor-team/wangEditor#4071]
## 问题描述

Vite2.8.0使用 wangEditorV5开发报错

![企业微信截图_16503346944449](https://user-images.githubusercontent.com/44107178/163907908-f98e47d9-f044-455d-a132-65737e7fda6b.png)

## wangEditor 版本

    "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-react": "^1.0.1",

## 是否查阅了文档 ？

是

*是/否*

## 最小成本的复现步骤

npm create vite@latest my-react-app -- --template react

npm i 

npm run dev

- 步骤一
- 步骤二
- 步骤三

**Comment by HeidaLay** [comment]
已解决

**Comment by wangfupeng1988** [comment]
@HeidaLay 可以把解决方法分享一下~

**Comment by dangjingtao** [comment]
看来作者也还不太清楚解决方法？
显式安装一下 @babel/runtime-corejs3这个插件
