### ISSUE TITLE
自定义表情，按照v4版本格式，表情显示不出来

### ISSUE THREAD

**Issue by Bobyoung0719** [wangeditor-team/wangEditor#4072]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
v5 的表情配置参考这里 https://www.wangeditor.com/v5/menu-config.html#%E8%A1%A8%E6%83%85 

其他格式不支持。

**Comment by Bobyoung0719** [comment]
实际场景上有需要自定义表情（表情格式为图片）

**Comment by wangfupeng1988** [comment]
可以自定义第三方功能来扩展 https://www.wangeditor.com/v5/development.html#%E6%A6%82%E8%BF%B0

**Comment by Bobyoung0719** [comment]
希望能将v4版本的自定义表情功能迁移到v5版本，感谢****
