### ISSUE TITLE
指令没生效

### ISSUE THREAD

**Issue by Monkeyqin** [wangeditor-team/wangEditor#4073]
## 问题描述

在html中引入https://cdn.jsdelivr.net/npm/@wangeditor/editor@latest/dist/index.min.js，创建了editor,但是动态插入html文本没生效

## wangEditor 版本
wangeditor V5

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

![image](https://user-images.githubusercontent.com/28913197/163917673-e57a7a3a-8ec5-4d31-82be-59f91e499171.png)
![image](https://user-images.githubusercontent.com/28913197/163917749-d89e23c7-e1e9-4c26-a799-0b330f5ef35a.png)

**Comment by wangfupeng1988** [comment]
可以试试这样

```js
editor.restoreSelection()
editor.dangerouslyInsertHtml('<p>hello</p>')
```

**Comment by Monkeyqin** [comment]
可以了，谢谢
