### ISSUE TITLE
vue中使用富文本编辑器，编辑富文本反显富文本会在首部增加一个<p><br></p> ，导致会出现一个换行，怎样解决

### ISSUE THREAD

**Issue by JadeZHY** [wangeditor-team/wangEditor#4074]
## 问题描述

vue中使用富文本编辑器，编辑富文本反显富文本会在首部增加一个<p><br></p> ，导致会出现一个换行，怎样解决

## wangEditor 版本

@wangeditor/editor 5.0.0  @wangeditor/editor-for-vue 1.0.0

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

table列表某一项富文本内容
点击编辑功能，
弹窗里面的富文本编辑器进行反显，
第一次编辑无问题，
点击下一个编辑就会在首部多一个`<p><br></p> `

**Comment by wangfupeng1988** [comment]
编辑时你传入的 html 内容是什么？（只要能复现问题即可，内容越简单越好）

**Comment by JadeZHY** [comment]
> 编辑时你传入的 html 内容是什么？（只要能复现问题即可，内容越简单越好）

我传入的内容不存在<p></br></p>,就是简单的<p>内容</p>。我知道问题在哪里了， 是我设置maxlength， 就会有这个问题，但是我这边需要限制最大输入值。改怎么解决呢

**Comment by JadeZHY** [comment]
> > 编辑时你传入的 html 内容是什么？（只要能复现问题即可，内容越简单越好）
> 
> 就是简单的p标签内容。我知道问题在哪里了， 是我设置maxlength， 就会有这个问题，但是我这边需要限制最大输入值。改怎么解决呢

问题图片：
![image](https://user-images.githubusercontent.com/20716651/163936256-3ec650ac-9c71-43d2-84f2-cbf0f00f1bff.png)

**Comment by wangfupeng1988** [comment]
可以试试这样

```js
import { SlateTransforms } from '@wangeditor/editor'

SlateTransforms.removeNodes(editor, { at: [0] }) // 删除第一行
```

**Comment by JadeZHY** [comment]
> 

![image](https://user-images.githubusercontent.com/20716651/163984375-b29ac7a8-13ab-4ce4-8239-bf2e08f5f406.png)
报错了
![image](https://user-images.githubusercontent.com/20716651/163984562-6f6d72a2-d0a2-4572-9bc8-a6151cc4c050.png)
