### ISSUE TITLE
dangerouslyInsertHtml插入自定义dom片段，没生效

### ISSUE THREAD

**Issue by Monkeyqin** [wangeditor-team/wangEditor#4075]
## 问题描述
dangerouslyInsertHtml插入自定义dom片段，没生效

## wangEditor 版本
wangeditor V5

## 是否查阅了文档 ？
 是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/28913197/163938150-f36fd910-d170-4dcc-bd69-f0f37ffe1852.png)
![image](https://user-images.githubusercontent.com/28913197/163938262-8d6290bb-8694-4b88-9881-ab816497a5b0.png)

**Comment by wangfupeng1988** [comment]
只能支持 wangEditor 产出的 HTML 格式，参考 https://www.wangeditor.com/v5/content.html#%E8%AE%BE%E7%BD%AE-html
