### ISSUE TITLE
react tsx wangEditor v5版本

### ISSUE THREAD

**Issue by xtt-lydia** [wangeditor-team/wangEditor#4077]
## 问题描述
在react tsx 中引入v5版本，工具栏配置时页面语法提示:类型“IDomEditor | null | undefined”的参数不能赋给类型“IDomEditor”的参数。
  不能将类型“undefined”分配给类型“IDomEditor”。ts
控制面板报错：mf-va_remoteEntry.js:867 Uncaught (in promise) Error: Module "./@wangeditor/editor" does not exist in container.
while loading "./@wangeditor/editor" from webpack/container/reference/mf

*请输入遇到的问题...*
工具栏配置时页面语法提示:类型“IDomEditor | null | undefined”的参数不能赋给类型“IDomEditor”的参数。
  不能将类型“undefined”分配给类型“IDomEditor”。ts
控制面板报错：mf-va_remoteEntry.js:867 Uncaught (in promise) Error: Module "./@wangeditor/editor" does not exist in container.
while loading "./@wangeditor/editor" from webpack/container/reference/mf

## wangEditor 版本
v5版本
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一  按照文档react的安装后，直接复制react的[示例源码](https://github.com/wangfupeng1988/react-wangeditor-demo)成功引用
- 步骤二  再到工具栏配置 复制
//- 如果你使用 Vue React ，可以通过如下代码获取 toolbar 实例
import { DomEditor } from '@wangeditor/editor'
const toolbar = DomEditor.getToolbar(editor)
- 步骤三

**Comment by wangfupeng1988** [comment]
可以在 codesandbox 中 fork 一下 React 在线 demo （看这里 https://www.wangeditor.com/v5/for-frame.html#react ）然后复现你的问题。
把 codesandbox 项目链接发过来。

**Comment by xtt-lydia** [comment]
我在在线源码里调试了一下是没有问题的，但我在自己项目里报错
