### ISSUE TITLE
使用wangeditor V4 自定义了清除格式按钮，需要不换行清除格式

### ISSUE THREAD

**Issue by Monkeyqin** [wangeditor-team/wangEditor#4079]
## 问题描述
使用wangeditor V4 自定义了清除格式按钮，现在清除后，没有换行了，请问如何清除格式后，保留换行

## wangEditor 版本
wangeditor V4

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
![image](https://user-images.githubusercontent.com/28913197/163961522-03e73917-3b3b-4fbe-905b-fe2b04fa394f.png)
![image](https://user-images.githubusercontent.com/28913197/163961627-0b21abee-e8ac-4882-badc-b83846ca61bc.png)
![image](https://user-images.githubusercontent.com/28913197/163961135-6ef93d70-82a7-4258-9349-9a410ca2e740.png)

**Comment by wangfupeng1988** [comment]
v5 已发布，v4 暂无经历维护。业余维护，还请体谅。
