### ISSUE TITLE
粘贴大量文本的时候会出现卡顿情况

### ISSUE THREAD

**Issue by clown-helang** [wangeditor-team/wangEditor#4081]
## 问题描述

当粘贴大量文本的时候会出现明显卡顿问题（页面无法进行其他操作）。官方示例中有一个[大文件10W字](https://www.wangeditor.com/demo/huge-doc.html)的示例可以复现该效果。

## wangEditor 版本
V5.0.0

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
使用[大文件10W字](https://www.wangeditor.com/demo/huge-doc.html)示例
- 步骤一 Ctrl + A 全选文字，全选过程中会出现滚动文本空白问题
- 步骤二 Ctrl + X 剪切文字，需要⌛️等待一段时间才能实现全部剪切
- 步骤三 Ctrl + V 粘贴文字，需要等待更长的时间

相同操作在[V4版本示例](https://codepen.io/xiaokyo-the-bold/pen/ZEpWByR)体验要明显好于V5版本

**Comment by wangfupeng1988** [comment]
v4 就是最基本的 HTML 操作，而 v5 是虚拟 DOM 转真实 DOM 的流程，所以大文字会卡顿，这个目前没有好办法。

PS：编辑器内有几万字，普通的输入、删除、设置格式是可以的。
