### ISSUE TITLE
How to create a custom IModalMenu?

### ISSUE THREAD

**Issue by tuononh** [wangeditor-team/wangEditor#4082]
## bug 描述

I cannot create a custom modal menu because `DOMElement` which is returned by `getModalContentElem()` is unavailable to import.

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
You can refer this demo https://github.com/wangeditor-team/wangEditor-plugin-formula/blob/main/src/module/menu/InsertFormula.ts

**Comment by tuononh** [comment]
@wangfupeng1988 I means how can I import these modules?
```
import $, { Dom7Array, DOMElement } from '../../utils/dom'
import { genRandomStr } from '../../utils/util'
```

**Comment by wangfupeng1988** [comment]
You can create your `dom.ts` file, like this file https://github.com/wangeditor-team/wangEditor-plugin-formula/tree/main/src/utils
