### ISSUE TITLE
v5设置默认html内容光标未在末尾

### ISSUE THREAD

**Issue by Exrick** [wangeditor-team/wangEditor#4083]
## bug 描述

设置默认html内容后鼠标光标未在末尾

## 你预期的样子是？

设置默认html内容后鼠标光标应在末尾

## 系统和浏览器及版本号

- MacOS 最新
- Chrome 最新

## wangEditor 版本

v5.0.0

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/set-html.html

## 在线 demo

https://www.wangeditor.com/demo/set-html.html

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
<img width="376" alt="image" src="https://user-images.githubusercontent.com/22902934/164280959-805080a6-92a1-424c-b86a-12896d608dd9.png">

- 点击设置按钮后 鼠标光标自动移至末尾

<img width="969" alt="image" src="https://user-images.githubusercontent.com/22902934/164280848-ca0ee8b1-8d83-42f9-aea6-1155c0c5c8ff.png">

**Comment by wangfupeng1988** [comment]
待设置完内容之后，执行这个代码

```js
import { SlateEditor } from '@wangeditor/editor'

const endPoint = SlateEditor.end(editor, [])
editor.select(endPoint)
```
