### ISSUE TITLE
V5版本如何才能和V4版本一样 可以多次点击 增加缩进

### ISSUE THREAD

**Issue by dongjialin** [wangeditor-team/wangEditor#4084]
## 问题描述

V5版本如何才能和V4版本一样 可以多次点击 增加缩进

## wangEditor 版本

V5

## 是否查阅了文档 ？

*是*

## 最小成本的复现步骤

输入内容 
点击 增加缩进

**Comment by wangfupeng1988** [comment]
默认不支持这个功能。需要你自己定义扩展菜单，可参考文档。
