### ISSUE TITLE
umi项目报错

### ISSUE THREAD

**Issue by wangjingithub** [wangeditor-team/wangEditor#4085]
devScripts.js:5035 ./node_modules/@wangeditor/editor-for-react/dist/index.esm.js
Module not found: Can't resolve '@babel/runtime-corejs3/core-js-stable/json/stringify' in 'D:\workDemo\umi-admin\node_modules\@wangeditor\editor-for-react\dist'

**Comment by wangfupeng1988** [comment]
看起来和 https://github.com/wangeditor-team/wangEditor/issues/4041 这个 issue 类似。

修改一下 webpack 配置，include 这个文件 `./node_modules/@wangeditor/editor-for-react/dist/index.esm.js`

**Comment by carmineprince** [comment]
`yarn add  @babel/runtime-corejs3`
