### ISSUE TITLE
V5版本有V4版本的获取 JSON格式内容的方法吗

### ISSUE THREAD

**Issue by linsem123** [wangeditor-team/wangEditor#4086]
## 问题描述

*V5版本有提供获取 JSON格式内容的方法吗，V4版本提供的方法是editor.txt.getJSON().*

## wangEditor 版本

*V5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
看文档 https://www.wangeditor.com/v5/content.html#%E8%8E%B7%E5%8F%96%E5%86%85%E5%AE%B9 ，有获取 JSON ，也有设置 JSON
