### ISSUE TITLE
Vue2 readOnly 不生效

### ISSUE THREAD

**Issue by yangxin6** [wangeditor-team/wangEditor#4087]
## bug 描述

Vue2 readOnly 不生效

## 你预期的样子是？

![image](https://user-images.githubusercontent.com/43163881/164403554-65402ffa-ad7d-4067-87f3-c5bde49b0ab1.png)

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 Google 100.0.4896.88

## wangEditor 版本

    "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-vue": "^1.0.0",

## 最小成本的复现步骤

不使用工具栏，只用 Editor作展示，禁用编辑
editorConfig: {
          readOnly: true,
        },

**Comment by yangxin6** [comment]
![image](https://user-images.githubusercontent.com/43163881/164449728-6e55d862-6989-4d4a-9afb-49ae6b3348cb.png)
我已经设置了 readOnly位 true 
但是editor.getConfig() 里面的值为什么还是false
但是打印的鸷鹊诗True

**Comment by liuqh0609** [comment]
我这边测试了一下没复现你这个问题，请参考该demo检查是否自己代码中存在问题：[https://github.com/liuqh0609/editor-vue2-demo](https://github.com/liuqh0609/editor-vue2-demo)

**Comment by liuqh0609** [comment]
查看在线链接也可以[https://codesandbox.io/s/focused-snow-ves4fn?file=/src/components/BaseC.vue](https://codesandbox.io/s/focused-snow-ves4fn?file=/src/components/BaseC.vue)

**Comment by Leyoz** [comment]
vue3 版本复现了 ， 通过 v-model  绑定 valueHtml ，redonly 不生效

**Comment by wangfupeng1988** [comment]
可以在 editor 初始化完成之后执行 `disable` https://www.wangeditor.com/v5/API.html#disable

**Comment by WJmascara** [comment]
> 我这边测试了一下没复现你这个问题，请参考该demo检查是否自己代码中存在问题：https://github.com/liuqh0609/editor-vue2-demo

你这个demo应该也有问题吧，跑了你的demo依旧有这个问题呢

**Comment by liuqh0609** [comment]
> 
没有问题啊，你看下在线的这个demo [https://codesandbox.io/s/wangeditor-vue2-demo-0v7gbp?file=/src/components/BaseC.vue](https://codesandbox.io/s/wangeditor-vue2-demo-0v7gbp?file=/src/components/BaseC.vue)

**Comment by liuqh0609** [comment]
> > 我这边测试了一下没复现你这个问题，请参考该demo检查是否自己代码中存在问题：https://github.com/liuqh0609/editor-vue2-demo
> 
> 你这个demo应该也有问题吧，跑了你的demo依旧有这个问题呢

没有问题啊，你看下在线的这个[demo](https://codesandbox.io/s/wangeditor-vue2-demo-0v7gbp?file=/src/components/BaseC.vue)

**Comment by wangfupeng1988** [comment]
@liuqh0609 你再试试用 v-model 咋样？

**Comment by liuqh0609** [comment]
> vue3 版本复现了 ， 通过 v-model 绑定 valueHtml ，redonly 不生效
 
升级到最新版本即可 `@wangeditor/editor-for-vue@5.1.11`

**Comment by liuqh0609** [comment]
`readOnly`问题在新版本中已经解决，大家可以升级到最新版本尝试一下:

- vue3组件：`@wangeditor/editor-for-vue@5.1.11`
- vue2组件：`@wangeditor/editor-for-vue@1.0.1`
