### ISSUE TITLE
maxLength属性添加后,异步加载内容,会自动添加一个换行<p><br></p>

### ISSUE THREAD

**Issue by CYCharles** [wangeditor-team/wangEditor#4089]
## bug 描述
import { Editor, Toolbar } from "@wangeditor/editor-for-vue";
editorConfig.maxLength

![image](https://user-images.githubusercontent.com/27986378/164577976-c0b6df6f-bdf7-453f-b0fe-20d802117a36.png)

## 你预期的样子是？

不希望初始化添加标签

## 系统和浏览器及版本号

谷歌必现

## wangEditor 版本

vue2
"@wangeditor/editor-for-vue": "^1.0.0",

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- https://codesandbox.io/s/vue2-wangeditor-demo-forked-44x7g0?file=/src/components/MyEditor.vue:1236-1245
- 步骤二
- editorConfig: {
        placeholder: "请输入内容...",
        // autoFocus: false,
        maxLength: 10000,   //!===========>添加maxLength属性就会出现自动添加一个换行在最前面
        // 所有的菜单配置，都要在 MENU_CONF 属性下
        MENU_CONF: {},
      },
- 步骤三

**Comment by wangfupeng1988** [comment]
和这个 issue 一个问题 https://github.com/wangeditor-team/wangEditor/issues/4078 ，已经记录下。

**Comment by twosugar** [comment]
遇到同样的问题
