### ISSUE TITLE
代码高亮渲染报错

### ISSUE THREAD

**Issue by kfuudotcn** [wangeditor-team/wangEditor#4090]
## bug 描述

代码高亮渲染报错
这是使用编辑器所生成的html代码提交到后端，刷新页面把这个代码展示在页面时，编辑器在处理高亮时js报错

&lt;p&gt;&lt;br&gt;&lt;/p&gt;&lt;pre&gt;&lt;code class=&quot;language-css&quot;&gt;body{color:#fff}&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;

![image](https://user-images.githubusercontent.com/63281264/164586799-a09fe212-45ca-4ea1-8d94-3fb46cfd62c9.png)

## 你预期的样子是？

代码正常高亮

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 chrome 最新版 版本 100.0.4896.127（正式版本） （64 位）

## wangEditor 版本

Minified by jsDelivr using Terser v5.10.0.

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤
直接复现

&lt;!doctype html&gt;
&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
    &lt;meta charset=&quot;UTF-8&quot;&gt;
    &lt;title&gt;Document&lt;/title&gt;
    &lt;link href=&quot;wangEditor/style.css&quot; rel=&quot;stylesheet&quot;&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;div class=&quot;content&quot;&gt;
    &lt;p&gt;&lt;br&gt;&lt;/p&gt;&lt;pre&gt;&lt;code class=&quot;language-css&quot;&gt;body{color:#fff}&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;
    &lt;/div&gt;
    &lt;script src=&quot;wangEditor/index.min.js&quot;&gt;&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;

![image](https://user-images.githubusercontent.com/63281264/164587661-3b02654c-eb8d-4c3c-9123-a300e7de0946.png)

**Comment by kfuudotcn** [comment]
![image](https://user-images.githubusercontent.com/63281264/164587493-d32f4983-d16e-4528-bbe2-2660623c3e3b.png)
用这个代码，就会报错，可以复现这个bug

**Comment by wangfupeng1988** [comment]
使用这个 demo https://www.wangeditor.com/demo/set-html.html

输入框中写上如下代码，然后点击“Set HTML”按钮

```css
<p><br></p><pre><code class="language-css">body{color:#fff}</code></pre><p><br></p>
```

**Comment by kfuudotcn** [comment]
> 使用这个 demo https://www.wangeditor.com/demo/set-html.html
> 
> 输入框中写上如下代码，然后点击“Set HTML”按钮
> 
> ```css
> <p><br></p><pre><code class="language-css">body{color:#fff}</code></pre><p><br></p>
> ```

哦不是，我不是要把代码写入到编辑器，是像
https://www.wangeditor.com/demo/code-highlight.html
是要代码高亮

**Comment by wangfupeng1988** [comment]
我把 code-highlight.html 中的代码，替换为你给的代码，也没有复现这个 bug 。如下图

<img width="550" alt="image" src="https://user-images.githubusercontent.com/9583120/164618155-0b8d2ca9-6927-4979-8531-dac11e91ff28.png">

**Comment by goku1989** [comment]
> 这个代码高亮得依赖 prism.js ...

能不能修改prism.js的主题呢
