### ISSUE TITLE
Vue2 使用@wangeditor/editor-for-vue 怎么修改菜单配置？

### ISSUE THREAD

**Issue by HGCVincent** [wangeditor-team/wangEditor#4091]
## 问题描述

Vue2 使用@wangeditor/editor-for-vue 怎么修改菜单配置？

## wangEditor 版本

V5

## 是否查阅了文档 ？

是

**Comment by wangfupeng1988** [comment]
看文档即可 https://www.wangeditor.com/v5/toolbar-config.html#getconfig 

遇到其他具体的问题再来回复。

**Comment by HGCVincent** [comment]
uploadImage里面的meta的变量会动态绑定吗？
`
meta: {
  srId: _this.srId,
  srType: _this.srType
}
`
srId的值变了，上传图片请求的srId没有改变。

**Comment by HGCVincent** [comment]
我使用自定义上传解决了，谢谢！
