### ISSUE TITLE
自定义拓展功能无法重新绘制toolbar问题

### ISSUE THREAD

**Issue by ZHT131** [wangeditor-team/wangEditor#4092]
## 问题描述
本问题是我在vue3中使用遇到的问题
![image](https://user-images.githubusercontent.com/22323594/164652491-ddf0ef5f-3f30-44d4-afe4-76f6933007ac.png)
如上图说的是 1.必须在创建编辑器之前注册 2.全局只能注册一次，不要重复注册
但是当我需要判断编辑器中是否已经注册了的时候，就需要调用editor.getAllMenuKeys() 查询编辑器注册的所有菜单 key；
然而getAllMenuKeys又是需要实例创建完成之后才能成功调用，那么这两者是否就冲突呢？
我既无法在实列创建前获取menukey,也无法在实列创建后重新绘制toolbar工具栏，我该如何解决呢？
## wangEditor 版本

wangEditor v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

在vue3中按照文档使用组件遇到的问题

**Comment by wangfupeng1988** [comment]
不冲突啊。你先在 JS 初始化时注册菜单。然后初始化 editor ，拿到 editor 实例，然后就可以 getAllMenuKeys 了

**Comment by ZHT131** [comment]
> 不冲突啊。你先在 JS 初始化时注册菜单。然后初始化 editor ，拿到 editor 实例，然后就可以 getAllMenuKeys 了

问题是首先要获取到getAllMenuKeys 才能判断是否已经注册了自定义菜单啊，重复注册菜单会报错，肯定就要先判断是否设置再决定是否再注册啊

**Comment by wangfupeng1988** [comment]
@ZHT131 不是的。你在初始化时就注册，并且保证代码只被执行一次即可。

就像这个 https://github.com/wangfupeng1988/vue2-wangeditor-demo/blob/master/src/components/MyEditorWithFormula.vue

**Comment by ZHT131** [comment]
我的就是和这个差不多，只是在setup中创建的，但是我觉得这两者结合vue-router的keepalive实现的刷新当前路由时，重载就会导致报错重复menu key

**Comment by ZHT131** [comment]
所以我才说有没有办法在创建实例前获取key或者再实例创建后动态改变toolbar
