### ISSUE TITLE
项目启动时报错

### ISSUE THREAD

**Issue by Duanxy835** [wangeditor-team/wangEditor#4093]
## bug 描述

![image](https://user-images.githubusercontent.com/33226907/164666194-1e26ff0d-5a6f-46c1-8e98-9f064771c2ea.png)

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

项目使用ruoyi+vue3

## wangEditor 版本

"@wangeditor/editor": "^5.0.0",
    "@wangeditor/editor-for-vue": "^5.1.10",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
版本升级了，getEditor 已经被删掉，重新看看文档吧
