### ISSUE TITLE
editor.insertNode   和   SlateTransforms.insertNodes  有什么区别？为啥有两个？

### ISSUE THREAD

**Issue by zhangjindong** [wangeditor-team/wangEditor#4094]
## 问题描述

问题一：editor.insertNode   和   SlateTransforms.insertNodes  有什么区别？为啥有两个？
问题二：自定义工具，能否插入一个自定义的HTML标签 例如：field  , user 之类的；如果能，麻烦Demo一下；
问题三：例如在H1文本中插入一个link。字体大小、颜色为啥不是H1？

## wangEditor 版本

V5

## 是否查阅了文档 ？

是

**Comment by wangfupeng1988** [comment]
第一，editor.insertNode 只能插入一个节点，而后者可以插入一个数组（多个节点）
第二，这个需要自定义元素 https://www.wangeditor.com/v5/development.html#%E6%A6%82%E8%BF%B0
第三，没看懂这个问题，可再举例描述

**Comment by zhangjindong** [comment]
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/5567162/164952120-8eb33398-7c37-4534-bf6c-8d0d59d536fe.png">

OK我明白了，InsterLink 样式是link自己的，EditLink 样式是H1的

**Comment by zhangjindong** [comment]
插入一个自定义的HTML标签 例如：field , user 之类，已解决；可以使用h ；

之前遇到的问题是：直接插入<field/> react 会提示到没有这个html标签，而且如果自己申明一个field标签，又会提示 Element 不能转为VNode；尝试多次未果。最终使用了h解决。
感谢大佬！
