### ISSUE TITLE
> 不冲突啊。你先在 JS 初始化时注册菜单。然后初始化 editor ，拿到 editor 实例，然后就可以 getAllMenuKeys 了

### ISSUE THREAD

**Issue by ZHT131** [wangeditor-team/wangEditor#4095]
> 不冲突啊。你先在 JS 初始化时注册菜单。然后初始化 editor ，拿到 editor 实例，然后就可以 getAllMenuKeys 了

问题是首先要获取到getAllMenuKeys 才能判断是否已经注册了自定义菜单啊，重复注册菜单会报错，肯定就要先判断是否设置再决定是否再注册啊

_Originally posted by @ZHT131 in https://github.com/wangeditor-team/wangEditor/issues/4092#issuecomment-1106240747_

**Comment by ZHT131** [comment]
如果是不先进行判断是否已经注册了，那么在vue中刷新某路由栈的时候就会碰到报错重复的menu key

**Comment by wangfupeng1988** [comment]
参考 https://github.com/wangeditor-team/wangEditor/issues/4092

**Comment by lazyboywu** [comment]
这种问题作者没有办法理解痛点，你只能自己想办法，实在没有办法就这样
```javascript
if (typeof window.registedXXX === 'undefined') {
  window.registedXXX = false;
}
if (!window.registedXXX) {
  Boot.registerModule(XXX);
  window.registedXXX = true;
}
```
通过全局变量搞一个自己识别
