### ISSUE TITLE
v4版本当字体设置为宋体时在文本中间敲入连续的两个空格时大小显示不一致

### ISSUE THREAD

**Issue by ZSLOGIN** [wangeditor-team/wangEditor#4096]
## bug 描述

*v4版本当字体设置为宋体时在文本中间敲入连续的两个空格时大小显示不一致*

## 系统和浏览器及版本号

- windows
- google  100.0.4896.127（正式版本）

## wangEditor 版本

*4.7.9*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codepen.io/xiaokyo-the-bold/pen/vYXGyrL

## 最小成本的复现步骤

- 步骤一  输入文字
- 步骤二  选中文字改为宋体
- 步骤三  将光标移至文字中间，连续敲入两个空格

**Comment by wangfupeng1988** [comment]
v5 发布了，v4 已无精力维护，自己业余开源，还请体谅~
