### ISSUE TITLE
用CDN方式引入wangEditor（纯html方式），怎么添加扩展的插件呢

### ISSUE THREAD

**Issue by ffrankfeng** [wangeditor-team/wangEditor#4097]
## 问题描述

用CDN方式引入wangEditor（纯html方式），怎么添加扩展的插件呢

## wangEditor 版本

latest

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
一样的，例如扩展菜单，可以看这个 demo 源代码 https://www.wangeditor.com/demo/extend-menu.html

**Comment by ffrankfeng** [comment]
那如果想要引入这些已有的插件呢，怎么import。
例如：
![image](https://user-images.githubusercontent.com/37799449/164873446-762da220-3662-4d72-8992-a358d2f7132d.png)

**Comment by wangfupeng1988** [comment]
第三方插件也支持 CDN 方式，去他们官网看看
