### ISSUE TITLE
onCreated事件下无法直接向编辑器插入内容

### ISSUE THREAD

**Issue by kfuudotcn** [wangeditor-team/wangEditor#4098]
编辑器版本：v5
onCreated(editor){
    editor.insertText('你好');   // 无效
     
    setTimeout(function() {
        editor.insertText('你好');  //有效
    }, 10);
},

**Comment by wangfupeng1988** [comment]
onCreated 时，编辑器的 DOM 还没准备好呢。如果你需要在 onCreated 时插入内容，可以考虑在初始化时直接设置 HTML 或者 JSON
