### ISSUE TITLE
如何能够创建多个富文本编辑器

### ISSUE THREAD

**Issue by avandou** [wangeditor-team/wangEditor#4099]
## 问题描述

*如何能够创建多个富文本编辑器*

## wangEditor 版本

*wangeditor5-for-vue3的最新版*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
直接创建多个编辑器组件 `<Editor ... />` 和 `<Toolbar.../>` 即可，跟多个 `<div>` 多个 `<p>` 没啥差别
