### ISSUE TITLE
react 版本无法输入中文字符，会自动转换成英文字符

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor#4100]
## bug 描述

react 版本无法输入中文字符，会自动转换成英文字符

## 你预期的样子是？

预期输入，但是编辑器得到的是,

## 系统和浏览器及版本号

- mac/linux
- Chrome

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能/不能
官方react 版本demo能复现
https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js

## 最小成本的复现步骤

打开链接，切换中文输入法（个人使用的是搜狗输入法），输入，、等中文标点符号。得到,\的结果

**Comment by wangfupeng1988** [comment]
你给出的 demo 链接，我没有复现，如下图

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/9583120/164892086-5949c4b5-04e6-4743-8b33-59cb74aa3bc5.png">

我是 Mac Chrome100 搜狗拼音

**Comment by tankpanv** [comment]
> 你给出的 demo 链接，我没有复现，如下图
> 
> <img alt="image" width="1373" src="https://user-images.githubusercontent.com/9583120/164892086-5949c4b5-04e6-4743-8b33-59cb74aa3bc5.png">
> 
> 我是 Mac Chrome100 搜狗拼音
不好意思，我的描述有问题。问题应该是，输入中文标点符号会自动转换成英文的标点符号。

**Comment by tankpanv** [comment]
> 

不好意思，我的描述有点问题。正确的问题是，编辑框里无法输入中文标点符号，输入之后会自动转换成英文标点符号，比如束输入“，”得到“,"

**Comment by wangfupeng1988** [comment]
@tankpanv 没问题的

<img width="209" alt="image" src="https://user-images.githubusercontent.com/9583120/165037049-cf747699-0fba-48cb-a605-6b41df309dc0.png">

**Comment by teddy1209** [comment]
请问解决了么？我也遇到这个问题

**Comment by tankpanv** [comment]
> 

其实我也没有，最近忙别的还没有处理这个，你如果有解决方案也通知我一下额

**Comment by teddy1209** [comment]
我发现只有搜狗输入法会出现这个问题，系统输入法可以输入中文，已经提给作者，作者在帮助排查了

**Comment by wangfupeng1988** [comment]
参考 https://github.com/wangeditor-team/wangEditor/issues/4180
