### ISSUE TITLE
Vue3组件中如果是使用v-model，并且是异步填充内容，那么readonly配置会失效

### ISSUE THREAD

**Issue by liuqh0609** [wangeditor-team/wangEditor#4103]
## bug 描述

Vue3中如果是使用v-model，并且是异步填充内容，那么readonly配置会失效
[详情参考](https://codesandbox.io/s/wangeditor-vue3-demo-0vyk8j?file=/src/components/VModel.vue)

## 你预期的样子是？

readonly生效

## 系统和浏览器及版本号

- 操作系统  `Mac`
- 浏览器和版本 `Microsoft Edge  版本 100.0.1185.44 (正式版本) (x86_64)`

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

- https://codesandbox.io/s/wangeditor-vue3-demo-0vyk8j?file=/src/components/VModel.vue

## 最小成本的复现步骤

查看提供的demo

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor-for-vue/pull/9/files

**Comment by liuqh0609** [comment]
该问题在新版本中已经解决，可以升级到最新版本:

vue3组件：@wangeditor/editor-for-vue@5.1.11
vue2组件：@wangeditor/editor-for-vue@1.0.1

**Comment by zhangjindong** [comment]
> 该问题在新版本中已经解决，可以升级到最新版本:
> 
> vue3组件：@wangeditor/editor-for-vue@5.1.11 vue2组件：@wangeditor/editor-for-vue@1.0.1

React 什么时候发一版。坐等

**Comment by liuqh0609** [comment]
> > 该问题在新版本中已经解决，可以升级到最新版本:
> > vue3组件：@wangeditor/editor-for-vue@5.1.11 vue2组件：@wangeditor/editor-for-vue@1.0.1
> 
> React 什么时候发一版。坐等

莫慌，很快就会发了，因为疫情大家现在都不太容易，理解一下子~🥷

**Comment by hahaaha** [comment]
@zhangjindong  react 版本已经发布了 更新到 [1.0.3] 即可
