### ISSUE TITLE
Vue3版本，完全复制demo代码，运行后无富文本编辑器出现

### ISSUE THREAD

**Issue by yunxiaoyang01** [wangeditor-team/wangEditor#4104]
## 问题描述

*Vue3版本，完全复制demo代码，运行后无富文本编辑器出现*

## wangEditor 版本

*V5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

使用gin-vue-admin项目。引入wangEditor，复制demo代码，运行后无富文本编辑器出现
控制台输出
runtime-core.esm-bundler.js:38 [Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 
  at <Anonymous defaultConfig= {placeholder: '请输入内容...'} mode=undefined modelValue="<p>模拟 Ajax 异步设置内容</p>"  ... > 
  at <BaseEditor modelValue=null onUpdate:modelValue=fn placeholder="请输入内容"  ... > 
  at <ElFormItem label="内容" prop="field103" > 
  at <ElForm ref="elForm" model= {field101: undefined, field103: null} rules= {field101: Array(1), field103: Array(1)}  ... > 
  at <AddWorkDynamic element-loading-text="正在加载中" class="admin-box" onVnodeUnmounted=fn<onVnodeUnmounted>  ... > 
  at <KeepAlive include= (6) ['System', 'FormGenerator', 'SuperAdmin', 'Api', 'AutoCode', 'Menus'] > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition mode="out-in" name="el-fade-in-linear" > 
  at <RouterView key=0 element-loading-text="正在加载中" class="admin-box" > 
  at <ElMain class="main-cont main-right" > 
  at <ElContainer class="openside" > 
  at <ElContainer class="layout-cont" > 
  at <Layout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
看这个 demo 吧 https://www.wangeditor.com/v5/for-frame.html#vue3 ，你的代码我也不清楚

**Comment by Tkoyist** [comment]
我遇到了相同的问题，在我将node_modules删除，并使用npm安装之后（之前使用的是cnpm），该问题得到了解决。
目前猜测是cnpm安装的依赖的问题。
