### ISSUE TITLE
sub & sup 标签支持

### ISSUE THREAD

**Issue by pureJim** [wangeditor-team/wangEditor#4105]
## 功能描述
能否加入 sub 下标 和 sup 上标的支持

## 可参考的案例

quill 上已有支持

**Comment by wangfupeng1988** [comment]
v5 已经有了 https://www.wangeditor.com/demo/index.html 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/9583120/164968693-41109cf8-8204-45d1-a794-dc13b616f4cd.png">
