### ISSUE TITLE
上传图片api

### ISSUE THREAD

**Issue by Duanxy835** [wangeditor-team/wangEditor#4107]
## 问题描述
上传图片api
![image](https://user-images.githubusercontent.com/33226907/164970154-e3c3609e-0026-4ab7-937a-3e0d7b7fcb88.png)

## wangEditor 版本

![image](https://user-images.githubusercontent.com/33226907/164970205-940d3a9f-660c-4fcd-ab4f-ce797120a211.png)

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤
点击后出现下面报错
![image](https://user-images.githubusercontent.com/33226907/164970183-b907ded4-3bb7-47b1-ae09-7e9e8dd4cafb.png)

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
猜测 `MENU_CONF` 没初始化赋值。
