### ISSUE TITLE
希望富文本中支持 markdown 解析转义，可通过配置开启。

### ISSUE THREAD

**Issue by zhuyuanmin** [wangeditor-team/wangEditor#4108]
## 功能描述

*希望富文本中支持 markdown 解析转义，可通过配置开启。*

## 提炼几个功能点

- 希望富文本中支持 markdown 解析转义，可通过配置开启。

## 原型图

*无*

## 可参考的案例

*不需要提供*

**Comment by wangfupeng1988** [comment]
参考 https://github.com/wangeditor-team/wangEditor-plugin-md
