### ISSUE TITLE
word 字段上下标复制解析错误

### ISSUE THREAD

**Issue by pureJim** [wangeditor-team/wangEditor#4109]
## bug 描述

当我从 **word** 中复制一段 n<sub>o</sub>vel c<sup>oro</sup>navirus 到富文本内部时，会出现所有文字都变为统一的上标或下标
> ### 特别注意
> 必须是从 word 上设置的上下标才会有

## 你预期的样子是？

n<sub>o</sub>vel c<sup>oro</sup>navirus

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

v5 demo

## demo 能否复现该 bug ？

能
- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

- 在 word 写一段文字
- 通过 word 的设置上下标功能随意选几个字体转换格式
- copy 到输入框中格式就会错误

**Comment by wangfupeng1988** [comment]
截两个图吧，贴这里。我做一个参考。

word 里截个图，粘贴之后再截个图。

**Comment by clinfc** [comment]
在 window 端使用 wps word 未复现该问题，不过发现一个新问题。从 wps word 中复制的文本的 font-size 单位为 pt，这导致字体大小的菜单栏无法正常渲染

![f75a7cd898f100b31a2176e1a8c8a99](https://user-images.githubusercontent.com/39868400/165030966-07bdd8d6-7b63-4d61-93e0-81978ebc7137.png)

**Comment by pureJim** [comment]
![image](https://user-images.githubusercontent.com/93514455/165032928-0c3cbade-5004-43db-be87-f8d4450fc3d7.png)

**Comment by pureJim** [comment]
![image](https://user-images.githubusercontent.com/93514455/165032981-4d8d1c31-ee43-4c77-86cb-70e1b714f74c.png)

> 我复制了` the incubation period`

![image](https://user-images.githubusercontent.com/93514455/165033082-2c04f6ce-b1c6-43a4-b294-5874c82efe41.png)
![image](https://user-images.githubusercontent.com/93514455/165033138-cf0309d3-df5a-4cd8-9c0b-70eedcba581b.png)

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/wangEditor/issues/4034 是类似的问题

**Comment by wangfupeng1988** [comment]
连续上标、下标，已经解决了，可更新 `@wangeditor/editor` 最新版本

也可以到 demo 中重新测试 https://www.wangeditor.com/demo/
