### ISSUE TITLE
粘贴保留文本样式问题

### ISSUE THREAD

**Issue by fAIUFHAI** [wangeditor-team/wangEditor#4110]
## 问题描述

*从vscode里面粘贴代码进富文本，代码的颜色和背景色不见了*

## wangEditor 版本

*"@wangeditor/core": "^1.0.0",
		"@wangeditor/editor": "^5.0.0",
		"@wangeditor/editor-for-vue": "^5.1.10",
		"@wangeditor/plugin-ctrl-enter": "^1.0.2",*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一  在vscode选中代码点击复制，再在富文本里面粘贴（ctrl+v）
- 步骤二  粘贴后，代码文本被粘贴进来了，但是文本的颜色背景色不见了
- 步骤三

**Comment by wangfupeng1988** [comment]
代码块的样式，只能受编辑器自带的样式定义，不支持 vscode 的各种样式
