### ISSUE TITLE
v5复制粘贴后文字样式消失，图片不展示

### ISSUE THREAD

**Issue by 541110727gdx** [wangeditor-team/wangEditor#4112]
## bug 描述

复制粘贴内容到富文本中，v4版本能展示文字和图片且有样式。v5版本不能展示图片只展示无样式的文字

## 你预期的样子是？

v5版本复制粘贴内容能如期展示

## 系统和浏览器及版本号

- win10 企业版
- chrome  99.0.4844.84（正式版本） （64 位）

## wangEditor 版本

"@wangeditor/editor": "^5.0.1",
"@wangeditor/editor-for-vue": "^5.1.10",

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

https://www.wangeditor.com/demo/index.html
https://codepen.io/xiaokyo-the-bold/pen/ZEpWByR

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

http://k.sina.com.cn/article_1700720163_655eee2302001555q.html  复制该网站文章内容 到v4官方demo中能展示图片 v5的demo图片不显示

**Comment by wangybg** [comment]
我也遇到了同样的问题，还有图片和'todo'插件一起拷贝时也会出现样式丢失，文字拷贝两份

**Comment by sunyongkun** [comment]
遇到同样问题

**Comment by wangfupeng1988** [comment]
可以自定义粘贴的逻辑 https://www.wangeditor.com/v5/menu-config.html#custompaste

**Comment by wangybg** [comment]
> 可以自定义粘贴的逻辑 https://www.wangeditor.com/v5/menu-config.html#custompaste
    if ($elem.attr('data-w-e-type')) {
      return parseCommonElemHtml($elem, editor)
    } else {
      return parseTextElemHtml($elem, editor)
    }
自定义粘贴逻辑选不中img标签，因为img都是被span 标签包裹，span 又有自己的parser，重写span 会引发更多的问题

**Comment by 541110727gdx** [comment]
> 可以自定义粘贴的逻辑 https://www.wangeditor.com/v5/menu-config.html#custompaste

自定义粘贴怎么实现复制样式显示和图片展示啊  为啥v4的没问题呢  不会要回滚到v4才能解决吧

**Comment by wangfupeng1988** [comment]
@541110727gdx 对 HTML 格式没做什么限制，所以支持各种灵活的 HTML 格式 —— 所以，也除了很多其他的问题。

v5 现在发布了 v4 不再有精力维护，可以自行选择。
