### ISSUE TITLE
如何使用自定义的渲染方法

### ISSUE THREAD

**Issue by yangchuanlong** [wangeditor-team/wangEditor#4114]
## 问题描述

有办法使用自定义的render方法吗？像slate-react中的renderElement那样？

![image](https://user-images.githubusercontent.com/7564819/165235523-1ef628e1-d1a8-4f36-af4c-1e71d390e867.png)

**Comment by wangfupeng1988** [comment]
看这里 https://www.wangeditor.com/v5/development.html#render
