### ISSUE TITLE
不太理解这里这么处理的原因，这样很多被span标签包裹的标签也不会被parse

### ISSUE THREAD

**Issue by wangybg** [wangeditor-team/wangEditor#4116]
https://github.com/wangeditor-team/wangEditor/blob/2281957020a30de9cda1c5e9d5e20c6668b7f592/packages/core/src/editor/plugins/with-content.ts#L267

**Comment by wangfupeng1988** [comment]
因为 `<span>` 被设计出来就是包裹文字的。

HTML 格式过于灵活了，编辑器如果像浏览器一样支持所有的格式，那成本太高了。

**Comment by wangybg** [comment]
> 因为 `<span>` 被设计出来就是包裹文字的。
> 
> HTML 格式过于灵活了，编辑器如果像浏览器一样支持所有的格式，那成本太高了。
可以留个接口吗？来控制哪些需要主动处理的TAG，因为现在用wangEditor的image插件保存的图片就是用span 包裹的，导致复制图标时复制不成功
