### ISSUE TITLE
最新版的上传视频与图片的后端接口返回什么样格式的数据啊

### ISSUE THREAD

**Issue by tgw1983** [wangeditor-team/wangEditor#4118]
## 问题描述
5.0版本的上传视频接口，实例上是http://106.12.198.214:3000/api/upload-video ，这个api最终要返回的格式是哪种？文档中也没写啊

我本地项目使用，总不能把视频都上传到这个服务器上吧，实例中带一个后台DEMO也好啊，第一次用，感觉好难

**Comment by wangfupeng1988** [comment]
文档参考 https://www.wangeditor.com/v5/menu-config.html#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%9C%B0%E5%9D%80

后台 demo 我只会写 nodejs 的 https://github.com/wangeditor-team/server ，其他技术栈不会写。

**Comment by tgw1983** [comment]
好的，谢谢，看到了，我直接从官网上没看到这个链接
