### ISSUE TITLE
上传视频的后台API接口要返回哪种格式的数据

### ISSUE THREAD

**Issue by tgw1983** [wangeditor-team/wangEditor#4119]
## 问题描述

上传视频的后台API接口要返回哪种格式的数据，实例中接口是http://106.12.198.214:3000/api/upload-video ，这个文件最终要返回什么，有demo吗？

## wangEditor 版本
5.0

## 是否查阅了文档 ？
查询了文档，文档中没有

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/issues/4118 参考这个
