### ISSUE TITLE
上传图片不能回显图片

### ISSUE THREAD

**Issue by hapiGitHub** [wangeditor-team/wangEditor#4121]
## 问题描述
上传图片不能回显图片
*请输入遇到的问题...*
上传图片不能回显图片，回显的图片通过浏览器地址栏可以正常访问就是不能回显数据，通过在请求前面加上完整地址也不行
## wangEditor 版本
5
*请输入内容……*
上传图片不能回显图片，回显的图片通过浏览器地址栏可以正常访问就是不能回显数据
## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
![-3e71a11b066e0f38](https://user-images.githubusercontent.com/63957382/165563593-1d454a6e-ddfe-4291-94c8-87a5c61e3dba.png)
![3e9a4e8b7d426366](https://user-images.githubusercontent.com/63957382/165563592-20947ebd-613d-48e8-ad2b-6f9f698c40b3.png)

- 步骤二
![mmexport1651072144721](https://user-images.githubusercontent.com/63957382/165563637-7fcfc749-7c18-4b40-9760-1206c80dbcc2.png)
![mmexport1651072148401](https://user-images.githubusercontent.com/63957382/165563691-09f7d98b-acb1-42aa-aaf1-538c8d8da99a.png)

- 步骤三
![70bc86f615f78a7f](https://user-images.githubusercontent.com/63957382/165563756-e3227113-6bd1-428f-a6ab-0b2f7ca27db9.png)
![mmexport1651075914885](https://user-images.githubusercontent.com/63957382/165563901-2ea6d0e9-b767-4ff8-902c-0225e6e8d1a5.png)

**Comment by wangfupeng1988** [comment]
通过你目前给出的信息，我也看不出你哪里的问题。

不过，上传图片本身的功能是没问题的，你可以参考这个 demo http://106.12.198.214:8882/master/examples/upload-image.html

**Comment by hapiGitHub** [comment]
> 通过你目前给出的信息，我也看不出你哪里的问题。
> 
> 不过，上传图片本身的功能是没问题的，你可以参考这个 demo http://106.12.198.214:8882/master/examples/upload-image.html

找到问题所在了就是回显的时候图片的请求头不对
正常和出错的
![mmexport1651117986083](https://user-images.githubusercontent.com/63957382/165673071-ccaae8b6-9893-417c-849a-09a1cd65f116.png)
![mmexport1651117990295](https://user-images.githubusercontent.com/63957382/165673106-8d6441ff-7980-4ccb-a517-8b538f9998b5.jpg)
但是为啥会出现这种情况

**Comment by wangfupeng1988** [comment]
如下图。你这里返回的是 404 ，这是问题所在，从这里查吧

<img width="434" alt="image" src="https://user-images.githubusercontent.com/9583120/165683255-0a00cbc9-9f60-4854-b740-4fc38ae40e2e.png">
