### ISSUE TITLE
重构了表格逻辑无法复制表格为新的表格结构节点

### ISSUE THREAD

**Issue by 1034148617** [wangeditor-team/wangEditor#4122]
## 问题描述

参照table-module的内容自定义了一个表格类型，可以在编辑器里正确的插入渲染表格，实现调整单元格、合并等功能，现在需要从word复制表格插入到编辑器中，但是插入进来的节点依旧为table-module中的类型而不是自定义重构后的类型，无法进行扩展功能的操作，是否是因为insertData方法未成功实现或者其他原因导致。另外昨天更新的文档，可能是没找到或者缺少一个总的目录，今天使用的时候跳转多个页面依旧无法找到想要的功能。

## wangEditor 版本

vue3/wangEditor5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 重构了table-module，并且在plugin文件中重写了normalizeNode、insertData等方法，

**Comment by wangfupeng1988** [comment]
这个我需要再确定一下。不过，我目前小区封闭，拿不到办公电脑，得过几天解封了以后。

然后，建议你先先重构 `paragraph` 试试，从简单的验证起，别一上来就搞那么复杂。

**Comment by zhangjindong** [comment]
我遇到同样的问题，我只是想做个“表格无边框”的按钮，发现需要重写tablemodule才能实现；
