### ISSUE TITLE
代码块使用问题

### ISSUE THREAD

**Issue by aaa2281002** [wangeditor-team/wangEditor#4123]
使用代码块后。如何在页面显示代码块的标签和样式效果。  我现在加上的是 <span style="color:red;">xxxx</span>这行代码是要求在页面显示为字体红色的xxxx。 但是现在我使用代码块后 显示的直接是这串内容<span style="color:red;">xxxx</span> 而不是实际效果

**Comment by wangfupeng1988** [comment]
目前不支持自定义颜色和主题

**Comment by aaa2281002** [comment]
你好。 可以借鉴以前的一些富文本编辑器的一些HTML源代码编写吗？ 如：http://kindeditor.net/demo.php   这个富文本编辑器的
![image](https://user-images.githubusercontent.com/8611439/165664365-085be08f-84bf-47cf-8c99-9ca53e806b2b.png)
HTML源代码操作等处理。  可以增加一些标签自定义样式？
