### ISSUE TITLE
wangEditorV5 vue版本支持IE浏览器吗，我的在谷歌浏览器可以正常访问，在IE浏览器就打不开

### ISSUE THREAD

**Issue by jcbound** [wangeditor-team/wangEditor#4124]
## 问题描述
wangEditorV5 vue版本我的在谷歌浏览器可以正常访问，在IE浏览器就打不开,
*请输入遇到的问题...*
IE浏览器表现特征为路由无法跳转，控制台报错[object Error]{description: "无法获取未定义或 nu...", message: "无法获取未定义或 nu...", name: "TypeError", number: -2146823281, stack: "TypeError: ..."}
## wangEditor 版本
 "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-vue": "^1.0.0",
*请输入内容……*

## 是否查阅了文档 ？
查阅了，
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤
安装上面的vue版本，然后在IE浏览器访问即可
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
V5 全部都不再支持 IE

**Comment by jcbound** [comment]
> V5 全部都不再支持 IE
