### ISSUE TITLE
link plugin 中  normalizeNode 有问题Cannot find a descendant at path [1,0] in node

### ISSUE THREAD

**Issue by zhangjindong** [wangeditor-team/wangEditor#4127]
## bug 描述

*index.js:24 Uncaught (in promise) Error: Cannot find a descendant at path [1,0] in node: {"children":[{"type":"paragraph","children":[{"type":"link","url":"qwqw","children":[{"text":" "}]}]},{"type":"paragraph","children":[]}],"operations":[{"type":"insert_node","path":[0,1],"node":{"type":"link","url":"qwqw","children":[]}},{"type":"move_node","path":[0,0],"newPath":[0,1,0]},{"type":"insert_node","path":[1,1],"node":{"type":"link","url":"qwqw","children":[]}},{"type":"move_node","path":[1,0],"newPath":[1,1,0]},{"type":"remove_node","path":[1,0],"node":{"type":"link","url":"qwqw","children":[{"text":""}]}}],"selection":{"anchor":{"path":[0,0,0],"offset":0},"focus":{"path":[0,0,0],"offset":1}},"marks":null,"id":"wangEditor-1","isDestroyed":false,"isFullScreen":false,"history":{"undos":[[{"type":"insert_text","path":[0,0],"offset":0,"text":" "}],[{"type":"split_node","path":[0,0],"position":1,"properties":{}},{"type":"split_node","path":[0],"position":1,"properties":{"type":"paragraph"}},{"type":"set_selection","properties":{"anchor":{"path":[1,0],"offset":0}},"newProperties":{"anchor":{"path":[0,0],"offset":0}}}],[{"type":"insert_node","path":[0,1],"node":{"type":"link","url":"21","children":[]}},{"type":"move_node","path":[0,0],"newPath":[0,1,0]},{"type":"insert_node","path":[1,1],"node":{"type":"link","url":"21","children":[]}},{"type":"move_node","path":[1,0],"newPath":[1,1,0]},{"type":"remove_node","path":[1,0],"node":{"type":"link","url":"21","children":[{"text":""}]}},{"type":"set_selection","properties":{"anchor":{"path":[0,0,0],"offset":0}},"newProperties":{"anchor":{"path":[0,0,0],"offset":1}}},{"type":"insert_node","path":[1,0],"node":{"text":""}},{"type":"insert_node","path":[0,0],"node":{"text":""}},{"type":"insert_node","path":[0,2],"node":{"text":""}},{"type":"set_selection","properties":{"anchor":{"path":[1,0],"offset":0}},"newProperties":{"anchor":{"path":[0,0],"offset":0}}}],[{"type":"remove_node","path":[0,1],"node":{"type":"link","url":"21","children":[{"text":" "}]}},{"type":"remove_node","path":[0,1],"node":{"text":""}},{"type":"remove_node","path":[0],"node":{"type":"paragraph","children":[{"text":""}]}}],[{"type":"insert_text","path":[0,0],"offset":0,"text":" "}],[{"type":"split_node","path":[0,0],"position":1,"properties":{}},{"type":"split_node","path":[0],"position":1,"properties":{"type":"paragraph"}},{"type":"set_selection","properties":{"anchor":{"path":[1,0],"offset":0}},"newProperties":{"anchor":{"path":[0,0],"offset":0}}}],[{"type":"insert_node","path":[0,1],"node":{"type":"link","url":"qwqw","children":[]}},{"type":"move_node","path":[0,0],"newPath":[0,1,0]},{"type":"insert_node","path":[1,1],"node":{"type":"link","url":"qwqw","children":[]}},{"type":"move_node","path":[1,0],"newPath":[1,1,0]},{"type":"remove_node","path":[1,0],"node":{"type":"link","url":"qwqw","children":[{"text":""}]}}]],"redos":[]}}*

## 你预期的样子是？

*不应该报错*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*V5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

- 步骤一 输入任意字符，并换行
- 步骤二 Ctrl + A 全选文本
- 步骤三 Link 按钮 确定。
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/5567162/165879655-e57cd68c-5a4c-4b9b-b83b-ef7acf7a38fd.png">

**Comment by TGuoW** [comment]
我尽快处理下

**Comment by wangfupeng1988** [comment]
已合并，待发布新版本

**Comment by wangfupeng1988** [comment]
已发布，升级 `@wangeditor/editor` 最新版即可。

**Comment by yl196356303** [comment]
为什么升级到最新的还是有这个问题，官网react demo就能复现

**Comment by z836454898** [comment]
我也是有这个问题
