### ISSUE TITLE
wangEditor5.0的自定义菜单的问题

### ISSUE THREAD

**Issue by djzblue** [wangeditor-team/wangEditor#4128]
试用老师新版本的wangEditor，由于使用了自定义菜单，用一个对话框加载editor,第一次运行没问题，可是后面再打开就会出错， Error: Duplicated key ‘left-itemMenu’ in menu items， at Function.Boot2.registerMenu， 我是在onMounted里去进行注册的，我知道菜单只能全局注册一次，同时需要在编辑器实例化之前注册，可是不知道怎么获取已注册的menuKeys，editor.getAllMenuKeys是必须编辑器实例才可以调用的，请问老师，这个问题如何解决，还有注册的自定义菜单数据是存在哪里的？ 为什么组件销毁后再次进入会还存在呢？

**Comment by wangfupeng1988** [comment]
不要在 onMounted 里注册，要全局注册一次

参考 https://github.com/wangfupeng1988/vue2-wangeditor-demo/blob/master/src/components/MyEditorWithFormula.vue 这里的 `Boot.registerModule(formulaModule)`

**Comment by djzblue** [comment]
谢谢双越老师的快速回复，这些没看邮箱，不好意思。




我是用script setup语法的，就是参照您的官网提供的vue3demo来实现的，就是把注册放在onMounted外面，但时不时就会出现我提的那个问题，我估计demo里的代码也是有问题，是否应该新开一个script标签，去执行Boot.registerMenu(menuConf)才行， 因为script setup语法里的代码不是全局的，


&nbsp;我现在的解决方法是，还是写在script setup的script里， 但是给menuConf.key生成一个随机数，则不再会出现这个问题，但始终觉得不是一个好方法。老师有什么好建议？&nbsp; 另外，如果希望给自定义菜单实现一个快捷键组合，有没有什么方法？ 谢谢老师！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月30日(星期六) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] wangEditor5.0的自定义菜单的问题 (Issue #4128)





 
不要在 onMounted 里注册，要全局注册一次
 
参考 https://github.com/wangfupeng1988/vue2-wangeditor-demo/blob/master/src/components/MyEditorWithFormula.vue 这里的 Boot.registerModule(formulaModule)

**Comment by wangfupeng1988** [comment]
可以定一个全局的变量 `flag` ，只要注册过一次就设置 `flag = true` ，然后根据 `flag` 来判断是否需要注册。

**Comment by noenif** [comment]
> 可以定一个全局的变量 `flag` ，只要注册过一次就设置 `flag = true` ，然后根据 `flag` 来判断是否需要注册。

准确说可以用vuex  ,他和vuex的生命周期一样

**Comment by 0415ypt00** [comment]
想问一下 自定义菜单之后 回调在哪里写啊
<img width="698" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/14194720/95cee854-d5d2-48c2-b20a-4fead9e0a038">

**Comment by ZongYan30** [comment]
> 谢谢双越老师的快速回复，这些没看邮箱，不好意思。 我是用script setup语法的，就是参照您的官网提供的vue3demo来实现的，就是把注册放在onMounted外面，但时不时就会出现我提的那个问题，我估计demo里的代码也是有问题，是否应该新开一个script标签，去执行Boot.registerMenu(menuConf)才行， 因为script setup语法里的代码不是全局的， &nbsp;我现在的解决方法是，还是写在script setup的script里， 但是给menuConf.key生成一个随机数，则不再会出现这个问题，但始终觉得不是一个好方法。老师有什么好建议？&nbsp; 另外，如果希望给自定义菜单实现一个快捷键组合，有没有什么方法？ 谢谢老师！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wangeditor-team/wangEditor" ***@***.***&gt;; 发送时间:&nbsp;2022年4月30日(星期六) 下午3:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wangeditor-team/wangEditor] wangEditor5.0的自定义菜单的问题 (Issue #4128) 不要在 onMounted 里注册，要全局注册一次 参考 https://github.com/wangfupeng1988/vue2-wangeditor-demo/blob/master/src/components/MyEditorWithFormula.vue 这里的 Boot.registerModule(formulaModule) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

本人亲测再开一个`<script/>`有用，是这样的。
vue3中<script setup>语法糖实际上是在setup声明中执行的，当你的Boot.registerMenu(menuConf)代码放在setup中，相当于每次刷新页面或者重新加载组件都会执行，那么这样每次都注册就会报这个错误。
解决办法:
1.在<script setup>下放置一个<script>标签,该标签中执行引入和注册Boot.registerMenu(menuConf)。
   原理:<script>标签不会像<script setup>一样，组件每次都执行的。
2.既然问题是重复注册了Menukey，那么我们不让他重复注册就好了。我们可以把引入和注册的代码放置在main.ts中去。

**Comment by withlunar** [comment]
```
const registMenuKeyName = ref('html-menu-key' + new Date().getTime())
const menuConf = {
  key: registMenuKeyName.value, // menu key ，唯一。注册之后，需通过 toolbarKeys 配置到工具栏
  factory() {
    return new htmlMenu()
  },
}
const toolbarConfig = ref({
  insertKeys: {
    index: 0,
    keys: [registMenuKeyName.value]
  }
})
```

我也遇到这个问题了 全局注册和全局状态标记对我这个来说不太行 我要调用editor以外的方法
其实加一个查看注册过的key就能解决qwq 没有这个查看也没办法 只能想其他的方法

暂时的解决办法是给key加时间戳
既然不能重复注册就不让重名好了: (
后续有时间再研究其他的解决办法

**Comment by kgradon98** [comment]
可以通过作者提供的自定义时间来做
editor.on('event-key', fn)
editor.emit('event-key')
