### ISSUE TITLE
在 focus 的时候，不显示光标，输入文字后才会显示光标

### ISSUE THREAD

**Issue by Sylor-huang** [wangeditor-team/wangEditor#4129]
## 问题描述

在安装 vue3 的文档安装后，页面可以正常加载，但是点击编辑框后（即 focus) 后不显示光标，输入文字后才会显示

## wangEditor 版本

```js
"@wangeditor/editor": "^5.0.1",
"@wangeditor/editor-for-vue": "^5.1.11",
```

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是，参考文档和代码：

https://stackblitz.com/edit/vue3-wangeditor-demo?file=package.json

## 最小成本的复现步骤

<img width="769" alt="image" src="https://user-images.githubusercontent.com/26167245/166112862-920d21f5-0a71-461f-8e4a-fddc5bdcedf6.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/26167245/166112885-ec939822-a39b-4e78-b482-0dda794db460.png">

## 想请问的是

- [ ] 这个可能的问题会是什么呢？和 css 有关的吗？

非常感谢~

**Comment by wangfupeng1988** [comment]
> 点击编辑框后（即 focus) 后不显示光标

这个你在官网 demo 中可以复现吗？

**Comment by Sylor-huang** [comment]
@wangfupeng1988 在官网的 demo 中没有复现。

我用 vue3 的 demo： `vue3-wangeditor-demo` 里的 代码在本地运行时，是正常的。

但是 demo 里的代码，完整复制到我本地的项目运行时，就会有这样的问题，应该是我项目的原因，我再检查下哈。

感谢你的回复~

**Comment by Sylor-huang** [comment]
- [x] 在添加了这个 css 也可以解决：

```css
span[data-slate-zero-width="n"] {
  padding: 0 1px !important;
}
```

**Comment by jaychou2012** [comment]
同问，我也遇到了这个问题。vue3

**Comment by cfmj** [comment]
> * [x]  在添加了这个 css 也可以解决：
> 
> ```css
> span[data-slate-zero-width="n"] {
>   padding: 0 1px !important;
> }
> ```

可以解决

**Comment by Ray911s** [comment]
直接添加CSS：
span[data-slate-zero-width="n"] {
  padding: 0 1px !important;
}

**Comment by jaychou2012** [comment]
E-MAIL 已收到。
