### ISSUE TITLE
vue 绑定html片段， 不能保存自定义attribute。

### ISSUE THREAD

**Issue by luoyanzecs** [wangeditor-team/wangEditor#4130]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*
vue 使用v-model绑定html代码片段， init之后，自定义的attribute消失， 有什么办法能保留这些自定义的attribute吗？
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
<img width="603" alt="截屏2022-05-02 上午3 24 33" src="https://user-images.githubusercontent.com/44136414/166161418-3329462a-d03c-4357-ba5f-f9d0e77eaa4d.png">

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by luoyanzecs** [comment]
v5版本

**Comment by wangfupeng1988** [comment]
不支持你说的自定义 attr
