### ISSUE TITLE
文档写有些乱

### ISSUE THREAD

**Issue by simon-zhangmuye** [wangeditor-team/wangEditor#4135]
plain js和react还有vue的文档dou没有区分开，
感觉是拼凑起来的。

**Comment by wangfupeng1988** [comment]
有啥改进建议？

**Comment by simon-zhangmuye** [comment]
建议plainjs和vue reactwendang分开。

**Comment by wangfupeng1988** [comment]
现在就是分开的，你觉得哪里混起来了？可以给出更加具体的建议。

**Comment by sorakylin** [comment]
> 有啥改进建议？

menu key 的定义不能从文档里全部查看。
想要知道一个按钮的key到底是什么， 还得去写代码`editor.getAllMenuKeys()`，然后还得看key猜对应。
不太好吧。

**Comment by wangfupeng1988** [comment]
@sorakylin 你说的有道理

**Comment by sorakylin** [comment]
> @sorakylin 你说的有道理，我想一下

我找了半天…… 也没找到那个左右居中对齐的select menu是啥key，只有分开的…… 😭 
希望能在文档里出个表格。

---

还有请问一下像是 headerSelect 这种menu， 是不是没办法定义里边的子菜单。
比如只需要 H1/H2/H3/正文 不要 H4/H5。 要做这种效果 是只能自己从零开始自定义菜单么

**Comment by wangfupeng1988** [comment]
@sorakylin 目前不支持 headerSelect 自定义列表。

**Comment by loringray** [comment]
> 


> @sorakylin 目前不支持 headerSelect 自定义列表。

那看来只能自己重新一个新的 headerSelect Menu，这样才能去掉 H4/H5 😭，或者自定义 header 选项
