### ISSUE TITLE
toolbarkeys 可用的值有哪些？

### ISSUE THREAD

**Issue by miserylee** [wangeditor-team/wangEditor#4138]
RT，文档中没有找到 toolbarkeys 可用的所有值，在配置工具栏时不知道可以填哪些

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/v5/toolbar-config.html#toolbarkeys 

如下图

<img width="508" alt="image" src="https://user-images.githubusercontent.com/9583120/166847214-666615f9-1afb-4491-a6ba-f506d127f35f.png">

**Comment by MeFelixWang** [comment]
List full keys in the doc may be more convenient for use. 

By the way, there is no "paragraph" in full keys.

For now, if I don't use "headerSelect", I have to click "header1,2,3,4,5" again to reset the text, this may cause a little bit confusion.

How about making an independent "paragraph" key?

Thanks!
