### ISSUE TITLE
To do css问题

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [wangeditor-team/wangEditor#4140]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/97073795/166847581-6eeaeedf-3223-408d-833c-7fe97a97aa1c.png">
感觉没对齐。

**Comment by wangfupeng1988** [comment]
可以先自己写 css 微调一下。

**Comment by ANUGLYPLUGIN** [comment]
> 可以先自己写 css 微调一下。

好的谢谢。
