### ISSUE TITLE
不过滤标签

### ISSUE THREAD

**Issue by ZLiangLiang** [wangeditor-team/wangEditor#4143]
## 功能描述

可以插入div，audio等标签，或者通过设置不过滤这些标签

## 提炼几个功能点

增加可插入其它标签的配置

## 原型图

无
## 可参考的案例

无

**Comment by wangfupeng1988** [comment]
你只是 dangerouslyInsertHtml 这个 API 吗？

**Comment by ZLiangLiang** [comment]
> 是指 dangerouslyInsertHtml 这个 API 吗？

是的，用这个插入div标签无效，还有别的方法吗？

**Comment by wangfupeng1988** [comment]
编辑器不识别 div 标签，你需要自己转换为其他标签。

编辑器只能识别 editor.getHtml() 生成的标签，如 p table 等。

**Comment by ZLiangLiang** [comment]
> 编辑器不识别 div 标签，你需要自己转换为其他标签。
> 
> 编辑器只能识别 editor.getHtml() 生成的标签，如 p table 等。

那我换成p标签之后，可以自定义类名和样式吗？

**Comment by wangfupeng1988** [comment]
不可以单独自定义 css 相关的。

如果你有需要，可以自定义扩展 elem ，文档里有 https://www.wangeditor.com/v5/development.html

**Comment by aylitat** [comment]
感觉自定义扩展这个方案很安全，但过于保守。是否可以2种方案并行呢？
一方面使用slate，一方面允许直接渲染html标签，哪怕这不安全。因为在某些情况下，用户输入是可控的，值得信任的。在这种情况下，如果可以支持全标签，会更灵活。

> 不可以单独自定义 css 相关的。
> 
> 如果你有需要，可以自定义扩展 elem ，文档里有 https://www.wangeditor.com/v5/development.html
