### ISSUE TITLE
如何加入地图定位？

### ISSUE THREAD

**Issue by tgw1983** [wangeditor-team/wangEditor#4144]
## 问题描述

想实现插入地图定位的功能，类似于百度编辑器那种，可以选一个地点坐标，然后插入到当前内容中，现在工具栏没有吧，没找到相关的资料，应该怎么实现呢？

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

**Comment by wangfupeng1988** [comment]
要实现插入地图功能，需要你自定义 https://www.wangeditor.com/v5/development.html

可以参考现有的插件 https://www.wangeditor.com/v5/plugins.html ，这些也都是自定义扩展的
