### ISSUE TITLE
自定义插入SVG元素时点击报错

### ISSUE THREAD

**Issue by hansonGong** [wangeditor-team/wangEditor#4147]
## 插入SVG元素时点击报错

自定义开发的公式插件，生成公式后插入编辑区，点击公式报错：TypeError: elem.className.split is not a function，debugger时可以看到SVG 的className是一个SVGAnimatedString对象而非字符串，希望能兼容处理一下，在上一步的判断一起return掉，在线demo可以复现👇

## 你预期的样子是？

*点击SVG元素时不会报错*

## wangEditor 版本

*v4*

## demo 能否复现该 bug ？

能

## 在线 demo
https://codesandbox.io/s/funny-leaf-u9gso4

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 点击菜单栏的公式
- 鼠标移到 f(x) 菜单，随便选择一个公式
- 点击插入后，再在wangeditor编辑区点击公式

**Comment by wangfupeng1988** [comment]
v5 发布之后，v4 已不再维护了（业余维护，没精力，请体谅）

推荐你使用 [v5](https://www.wangeditor.com/) ，也有[公式插件](https://www.wangeditor.com/v5/plugins.html)
