### ISSUE TITLE
能否提供反注册菜单的api

### ISSUE THREAD

**Issue by icefee** [wangeditor-team/wangEditor#4148]
如题
在使用过程中，很多时候注册菜单的时候，会传递一些回调函数进去，这种情况下如果根据是否注册过来避免重复注册，实践起来会不太方便。
增加反注册菜单的api可以很方便的处理类似问题，也能解决重复注册的问题

**Comment by wangfupeng1988** [comment]
注册菜单、插件等都是全局的行为，不是组件的行为。所以全局只能注册一次，也是合理的。

无论你用什么框架，都可实现全局注册一次。

**Comment by icefee** [comment]
好的 感谢！
