### ISSUE TITLE
使用富文本的图片上传遇到传递参数问题

### ISSUE THREAD

**Issue by jcbound** [wangeditor-team/wangEditor#4153]
## 问题描述
使用富文本的图片上传遇到传递参数你问题
*请输入遇到的问题...*
我在
 ```
 meta: {
              fileName: '',
              unId: getUploadUUID(),
              position: 'banner',
              author: 'smp',
              appName: 'minapp'
            },
```
中定义了要上传的参数，但是这个fileName是需要随着上传图片的名称进行同步的，然后我在  

```
onBeforeUpload (file) {
              const fileObj = Object.keys(file)
              // file 选中的文件，格式如 { key: file }
              file[fileObj[0]].meta.fileName = file[fileObj[0]].name
                return file
              // 可以 return
              // 1. return file 或者 new 一个 file ，接下来将上传
              // 2. return false ，不上传这个 file
            } 
```

函数中手动去同步他的名字，但是每次都是meta里面的fileName参数先提交上去，然后console.log(file)也确实修改了，
我想让fileName名字修改后，然后在走上传接口把我修改后的参数提交上去，而不是每次把我默认的参数提交上去,请问该如何操作呢
## wangEditor 版本
 "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-vue": "^1.0.0",
*请输入内容……*

## 是否查阅了文档 ？
查阅了文档
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是，
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
没懂你的问题。

你是不是想动态修改这里的 `fieldName` 属性？ https://www.wangeditor.com/v5/menu-config.html#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE

**Comment by jcbound** [comment]
感谢回复，是的，我默认的给的fileName是空值，我想在上传之前拿到file对象手动把图片的name赋值给fileName， 但是我在上述操作中，已经给赋值了name，也打印出来，fileName已经有值了， 但是上传时候还是传递的空值，

**Comment by jcbound** [comment]
```
 // form-data fieldName ，默认值 'wangeditor-uploaded-image'
    fieldName: 'upfile',

    // 单个文件的最大体积限制，默认为 2M
    maxFileSize: 1 * 1024 * 1024, // 1M

    // 最多可上传几个文件，默认为 100
    maxNumberOfFiles: 10,

    // 选择文件时的类型限制，默认为 ['image/*'] 。如不想限制，则设置为 []
    allowedFileTypes: ['image/*'],

    // 自定义上传参数，例如传递验证的 token 等。参数会被添加到 formData 中，一起上传到服务端。
    meta: {
             fileName: '', //修改的是这里的名字
             unId: xxx,
             position: 'xxx',
             author: 'xxx',
             appName: 'xxx'
    },
```


感谢回复，不是filedName，上传接口要求额外传递的图片name（fileName），我默认的给的fileName是空值，我想在上传之前拿到file对象手动把图片的name赋值给fileName， 但是我在上述操作中，已经给赋值了name，也打印出来，fileName已经有值了， 但是上传时候还是传递的空值，

**Comment by wangfupeng1988** [comment]
你直接使用 file.name 不行吗？干嘛要自己再弄个 fileName ，这样数据冗余，还有同步的风险。

**Comment by jcbound** [comment]
感谢回复，接口是通用的老上传接口， 是必须要这个fileName的，后来用自定义上传函数解决了，
