### ISSUE TITLE
如何在Readonly状态下触发image的事件

### ISSUE THREAD

**Issue by zhangjindong** [wangeditor-team/wangEditor#4154]
## 问题描述

*如何在Readonly状态下触发image的事件*

希望实现 在readOnly时，点击图片执行 一些代码。比如下载 或提示。

## wangEditor 版本

*V5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
自己写 JS 事件即可。
