### ISSUE TITLE
如何在nuxt3中引入wangEditor

### ISSUE THREAD

**Issue by chen-ccll** [wangeditor-team/wangEditor#4155]
## 问题描述

大佬求助，如何在nuxt3中引入wangEditor，按照nuxt3插件引入，没有生效，不知是否我的引用方式问题

## wangEditor 版本
  "@wangeditor/editor": "^5.0.1",
 "@wangeditor/editor-for-vue": "^1.0.1",

## 是否查阅了文档 ？
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/v5/for-frame.html#vue3) ）

## 最小成本的复现步骤
- 步骤一  
在nuxt项目plugins目录下创建 wang-editor.js文件
```javascript
import { defineNuxtPlugin } from "#app";
import { Editor, Toolbar } from "@wangeditor/editor-for-vue";
import "@wangeditor/editor/dist/css/style.css";
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(Editor);
  nuxtApp.vueApp.use(Toolbar);
});
```
- 步骤二
在nuxt.config.ts文件中引入wang-editor.js文件
```javascript
import { defineNuxtConfig } from "nuxt";
export default defineNuxtConfig({
 plugins: ["@/plugins/antd-ui", {src: "@/plugins/wang-editor",ssr:false}],
  css: [
    "ant-design-vue/dist/antd.css",
    "@/assets/css/main.css",
    "@wangeditor/editor/dist/css/style.css",
  ],
});
```
- 步骤三
在页面中使用wangeditor，没有生效
```javascript
<template>
  <div class="content">
          <div style="border: 1px solid #ccc">
            <Toolbar
              style="border-bottom: 1px solid #ccc"
              :editor="editorRef"
              :defaultConfig="toolbarConfig"
              :mode="mode"
            />
            <Editor
              style="height: 500px; overflow-y: hidden"
              v-model="valueHtml"
              :defaultConfig="editorConfig"
              :mode="mode"
              @onCreated="handleCreated"
            />
          </div>
    </div>
</template>
<script setup>
// import "@wangeditor/editor/dist/css/style.css"; 引入 css
// import { Editor, Toolbar } from "@wangeditor/editor-for-vue";这里引入也没有生效
definePageMeta({
  layout: "custom",
});
</script>
```

**Comment by rui-ys** [comment]
@chen-ccll  Have you solved this problem? How to handle

**Comment by never106** [comment]
@chen-ccll  Have you solved this problem? How to handle? Can you share your solution with me

**Comment by phcent** [comment]
``
import { defineNuxtPlugin } from "#app";
import { Editor, Toolbar } from "@wangeditor/editor-for-vue";
import "@wangeditor/editor/dist/css/style.css";
export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component('Editor',Editor).component('Toolbar',Toolbar);
});
``

**Comment by stj8888** [comment]
有完整教程吗

**Comment by kehuan3088613773** [comment]
@chen-ccll Have you solved this problem? How to handle? Can you share your solution with me

**Comment by Alotofwater** [comment]
我引入成功了。以下完整教程  https://note.youdao.com/s/IYiELtYJ

**Comment by gspgsp** [comment]
根本就不支持nuxt3，推荐使用 quill
