### ISSUE TITLE
粘贴样式丢失，建议保留粘贴样式，以及图片

### ISSUE THREAD

**Issue by mymxdcxy** [wangeditor-team/wangEditor#4156]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
感觉你这个应该按照 bug 的模板（issue 模板）来提交，而不是新功能的模板
