### ISSUE TITLE
上传图片或视频，弹出资源管理器，不选择文件点击取消，鼠标短时间失去焦点

### ISSUE THREAD

**Issue by lcuncle** [wangeditor-team/wangEditor#4158]
## 问题描述

上传图片或视频，弹出资源管理器，不选择文件点击取消，鼠标短时间失去焦点

## wangEditor 版本

v5.*

## 电脑环境

win11 latest
chrome latest

## 最小成本的复现步骤

打开官方demo，上传图片或视频，弹出资源管理器，不选择文件点击取消，鼠标短时间失去焦点

**Comment by wangfupeng1988** [comment]
看你描述，感觉这个跟操作系统和浏览器有关，前端 JS 无法控制。如果仅仅是短时间失焦的话，那就先用着吧。
