### ISSUE TITLE
HTML 格式解析错误

### ISSUE THREAD

**Issue by lcuncle** [wangeditor-team/wangEditor#4159]
## bug 描述

使用`dangerouslyInsertHtml()`出现 HTML 格式解析错误
举例：
        输入`<p><strong>a</strong></p><strong>a</strong>`
        结果`<p><strong>aaa<br>a</strong></p>`

## 你预期的样子是？

举例：
        输入`<p><strong>a</strong></p><strong>a</strong>`
        结果`<p><strong>a<br>a</strong></p>`

## 系统和浏览器及版本号

- Win11 latest
- Chrome latest

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

[设置 HTML](https://www.wangeditor.com/demo/set-html.html)
输入 `<p><strong>a</strong></p><strong>a</strong>` 即可复现

**Comment by wangfupeng1988** [comment]
不支持这种格式，wangEditor 进支持自己输出的HTML 格式，文档里写了 https://www.wangeditor.com/v5/content.html#%E8%AE%BE%E7%BD%AE-html

**Comment by lcuncle** [comment]
谢谢，理解了。另外建议把文档的例子去掉 https://www.wangeditor.com/v5/content.html#%E8%AE%BE%E7%BD%AE-html 

~~`例如，wangEditor 可以识别 <strong>hello</strong> 为加粗，但无法识别 <span style="font-weight: bold;">hello</span> 等其他加粗方式。`~~

虽然 wangEditor 可以识别 `<strong>hello</strong>` 为加粗，但因为不是从 `editor.getHtml()` 获取的 html 内容，所以解析会出现格式问题。只保留上面的注意就可以完全明白了，也没有歧义。

`【注意】这里的 html 内容必须是 wangEditor 生成的 HTML 格式，不可以自己随意写。HTML 格式非常灵活，wangEditor 无法兼容所有的 HTML 格式。`

**Comment by lcuncle** [comment]
输入`<p><strong>a</strong></p><strong>a</strong>`
结果`<p><strong>a</strong></p><p><strong>a</strong></p>`

输入`<h1>a</h1>a`
结果`<h1>a</h1><p>a</p>`

如果以这种解析规则的话，就不会出现解析结果内容重复或者丢失了
