### ISSUE TITLE
hoverbarKeys 自定义 match 函数如何使用，文档、源码中都不清晰，没具体案例

### ISSUE THREAD

**Issue by Yangjia23** [wangeditor-team/wangEditor#4162]
## 问题描述

需求： 需要在 Image 的 hoverbarKeys 中增加一个图片下载的按钮，想通过自定义 match 函数实现，但  match 函数如何使用，文档、源码中都不清晰，没具体案例

## wangEditor 版本

@wangeditor/editor: 0.15.20

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

自定义 image 的 hoverbarKeys

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
自定义 image 的 hoverbarKeys 可以直接使用 elem 形式，不用 match 函数
https://www.wangeditor.com/v5/editor-config.html#%E4%BD%BF%E7%94%A8-element-type

**Comment by qiyulaoshi** [comment]
我也不是很明白这个， 我想自定义一些hoverbarKeys以及对应的点击事件， 不知道该如何实现

**Comment by Yangjia23** [comment]
> 我也不是很明白这个， 我想自定义一些hoverbarKeys以及对应的点击事件， 不知道该如何实现

我解决了，先通过自定义菜单来创建一个 menu, 然后在 Image 的 hoverBarKey 数组增加自定义的 menu key 即可

自定义菜单的实现可参考文档：https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E8%8F%9C%E5%8D%95
