### ISSUE TITLE
启动完成后报__WEBPACK_IMPORTED_MODULE_36_babel_runtime_core_js_symbol___default(...) is not a function

### ISSUE THREAD

**Issue by STAR5201** [wangeditor-team/wangEditor#4163]
## 问题描述
通过https://github.com/wangeditor-team/wangEditor/issues/4041 解决启动问题后，控制台报以下错误
`_WEBPACK_IMPORTED_MODULE_36_babel_runtime_core_js_symbol___default(...) is not a function`
*请输入遇到的问题...*
启动报错页面无法加载
## wangEditor 版本

*请输入内容……*
npm依赖如下
` "@wangeditor/core": "1.0.0",
    "@wangeditor/editor": "5.0.0",
    "@wangeditor/editor-for-vue": "^0.6.15",
    "@wangeditor/plugin-formula": "^1.0.8",
    "@wangeditor/plugin-mention": "^0.0.5",`
完整错误
`**index.esm.js?7c96:104 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_36_babel_runtime_core_js_symbol___default(...) is not a function
    at Object.eval (index.esm.js?7c96:104:4151)
    at eval (index.esm.js:4666:30)
    at Object../node_modules/@wangeditor/editor/dist/index.esm.js (app.js:741:1)
    at __webpack_require__ (app.js:678:30)
    at fn (app.js:88:20)
    at eval (index.esm.js:10:77)
    at Object../node_modules/@wangeditor/editor-for-vue/dist/index.esm.js (app.js:733:1)
    at __webpack_require__ (app.js:678:30)
    at fn (app.js:88:20)
    at eval (selector.js?type=script&index=0&bustCache!./src/views/modules/blog/blog-add-or-update.vue:3:85)**`
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
webpack 什么版本？babel 什么版本？如何才能复现这个问题呢？

**Comment by STAR5201** [comment]
webpack4.0&nbsp;&nbsp;babel-loader": "7.1.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月9日(星期一) 中午1:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 启动完成后报__WEBPACK_IMPORTED_MODULE_36_babel_runtime_core_js_symbol___default(...) is not a function (Issue #4163)





 
webpack 什么版本？babel 什么版本？如何才能复现这个问题呢？

**Comment by STAR5201** [comment]
我这个项目地址https://gitee.com/yifeifan/blog-admin-ui



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月9日(星期一) 中午1:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 启动完成后报__WEBPACK_IMPORTED_MODULE_36_babel_runtime_core_js_symbol___default(...) is not a function (Issue #4163)





 
webpack 什么版本？babel 什么版本？如何才能复现这个问题呢？

**Comment by wangfupeng1988** [comment]
@STAR5201 webpack3 babel6 ，版本有点低了 https://gitee.com/yifeifan/blog-admin-ui/blob/master/package.json
