### ISSUE TITLE
editor.getHtml()后保存的表格在另外的页面无样式

### ISSUE THREAD

**Issue by cssssssss** [wangeditor-team/wangEditor#4164]
## bug 描述

1、editor.getHtml()后保存的表格在另外的页面无样式
2、word 中贴进来的表格样式在编辑器中会被清除

## 你预期的样子是？

1、 editor.getHtml()获取到的内容在任意页面表格样式都存在
2、word 中贴进来的表格样式在编辑器中保留

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

最新版本

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

1、编辑器中添加一个表格，getHtml()，贴到一个空h5页面中，表格没有样式（现有的表格样式完全依赖于wangeditor.css。
 2、任意带样式的word表格，贴到编辑器中，表格样式被清除

**Comment by wangfupeng1988** [comment]
getHtml 显示时需要自定义样式 https://www.wangeditor.com/v5/content.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

编辑器中表格样式是固定的，无法支持所有 word 表格的样式

**Comment by cssssssss** [comment]
> getHtml 显示时需要自定义样式 https://www.wangeditor.com/v5/content.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
> 
> 编辑器中表格样式是固定的，无法支持所有 word 表格的样式


从同一个word贴相同的内容到编辑器里，v3是可以展示的，v5不可以；
而v5中添加一个最基本的表格，getHtml()无法展示（你都看不出来他是一个表格，连边框都么有），可能是因为v5需要从class继承基础的样式，v3是直接写在style里；

仅从编辑器使用者角度来看，如果用了编辑器还需要使用者在新页面中额外自定义一些样式，那还用编辑器干嘛？

**Comment by wangfupeng1988** [comment]
@cssssssss 你可以继续想想怎么解决这些问题。反正开源软件，大家一起贡献代码。

你说的这些现象，肯定不是我故意不做刁难用户，是有其他难点而导致做不了。

**Comment by wxxcarl** [comment]
我也遇到这个问题，其它有样式的html代码迁移过来，表格样式完全丢失，所以只能放弃了。我看到它好像把所有标签全部重新整理了一遍，把很多属性去掉了，比如valign，style之类的，甚至标签都删除了，比如<p><strong>，这。。。。。。。

**Comment by wangfupeng1988** [comment]
@wxxcarl 编辑器是生成富文本内容的，并不是任意识别、编辑 HTML 内容的。
稳定的编辑器肯定会规定自己的 DSL ，否则编辑功能就是不稳定的（例如 v4）
