### ISSUE TITLE
V5 表格建议增加设置多行表头

### ISSUE THREAD

**Issue by YiQingWang** [wangeditor-team/wangEditor#4165]
## 功能描述

V5 表格建议增加设置多行表头；虽然不支持合并单元格的编辑，但是可以从其他工具复制合并后的表格，合并单元格这个功能 issue 关注了很久，可能比较麻烦耗费精力。但是单纯的设置多行表头是否可以增加呢？

## 提炼几个功能点

- ![image](https://user-images.githubusercontent.com/16113453/167382622-bffa1dae-3352-4aef-b4eb-58e895dd99b6.png)

## 原型图

期望：框选第二行、或光标停留在第二行，设置第二行有标题背景色样式
![image](https://user-images.githubusercontent.com/16113453/167382674-c4956fa1-e98f-43bc-9ec5-76d16d5ca279.png)

## 可参考的案例

不需要 ck 这样复杂的功能，期望设置多行表头背景色即可
https://ckeditor.com/ckeditor-5/demo/

**Comment by wangfupeng1988** [comment]
多行表头，目前没有其他人反馈，可见需求比较少。暂时不会考虑增加。

不过，表格单元格的样式（颜色、背景色等）这些会在后续的工作计划中

**Comment by YiQingWang** [comment]
> 多行表头，目前没有其他人反馈，可见需求比较少。暂时不会考虑增加。
> 
> 不过，表格单元格的样式（颜色、背景色等）这些会在后续的工作计划中

好的，不过辛苦问下，表格单元格的样式（颜色、背景色等）这些后续大概是什么计划呢？
比如近期，本年，次年，待定

**Comment by YiQingWang** [comment]
> 多行表头，目前没有其他人反馈，可见需求比较少。暂时不会考虑增加。
> 
> 不过，表格单元格的样式（颜色、背景色等）这些会在后续的工作计划中

其实可以自定义背景色就ok了，多设两行背景效果等同于多行表头

**Comment by wangfupeng1988** [comment]
@YiQingWang 近期做不了，计划在今年之内做起来。
