### ISSUE TITLE
随着字数或者行数增加，自适应增高编辑框

### ISSUE THREAD

**Issue by shadowDDD** [wangeditor-team/wangEditor#4167]
## 随着字数或者行数增加，自适应增高编辑框

*目前有一个比较广泛的聊天输入的功能就是输入框要随着字数增加或者说行数增加，自适应增加编辑器高度，增加到最大高度或某个最大行数后内部滚动*

## 提炼几个功能点

- 随行数占满编辑框后，编辑框自适应增高
- 根据自定义的最大行数限制自适应增高的极限

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
编辑器的 DOM 都是自定义的，这个功能你自己做就行了，可以实现的。

**Comment by shadowDDD** [comment]
> 编辑器的 DOM 都是自定义的，这个功能你自己做就行了，可以实现的。

好的
