### ISSUE TITLE
插件中有个@ mention 提及 ，自定义@这个前缀

### ISSUE THREAD

**Issue by shadowDDD** [wangeditor-team/wangEditor#4168]
## @ mention 提及 ，自定义@这个前缀

*目前有时候不止@功能，可能会有#某个话题这样的，能否增加一个自定义提及，可以自定义关键字比如@ #这样的*

## 提炼几个功能点

- 增加自定义提及快捷词

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
# 话题功能和 mention 功能不一样，不能混在一起。所以，mention 功能也没支持 `@` 自定义其他符号。

**Comment by shadowDDD** [comment]
> 



> `#` 话题功能和 mention 功能不一样，不能混在一起。所以，mention 功能也没支持 `@` 自定义其他符号。

确实，#功能不一样，但是有时候确实需要提及时自定义一些特殊字或者啥的，我看源码直接是判断是否是@这个字符，能否可选配置为自定义字符呢

**Comment by wangfupeng1988** [comment]
目前不支持。否则会带来其他问题的。

**Comment by shadowDDD** [comment]
> 目前不支持。否则会带来其他问题的。

好的，我已经通过自己外部手写组件完成了该功能，谢谢解答

**Comment by Homebrew1** [comment]
@wangfupeng1988 把源码里的@删掉，不会有其他问题，插入时用'@' + text来插入
