### ISSUE TITLE
在本地和公司的服务器上显示正常，在甲方哪里toolbar整个不显示

### ISSUE THREAD

**Issue by haj97905** [wangeditor-team/wangEditor#4169]
## 问题描述

我在本地运行项目 富文本编辑器显示正常 但是在2组服务器上富文本编辑器一组显示 ，一组不显示。

## wangEditor 版本

 "@wangeditor/editor": "^0.12.11",
    "@wangeditor/editor-for-vue": "^0.6.12-2",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

必出现

**Comment by wangfupeng1988** [comment]
你得告诉我如何复现这个问题，否则我也不知道咋解决。

**Comment by haj97905** [comment]
方便私聊看看吗 我在群里  因为是在我这边的服务器运行着样的并且是公司项目

**Comment by wangfupeng1988** [comment]
@haj97905 抱歉，不私聊
