### ISSUE TITLE
请问富文本编辑框失去焦点时不想禁用工具栏怎么办

### ISSUE THREAD

**Issue by LILI-FUN** [wangeditor-team/wangEditor#4172]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by LILI-FUN** [comment]
请问富文本编辑框失去焦点时不想禁用工具栏怎么办

**Comment by LILI-FUN** [comment]
v5

**Comment by wangfupeng1988** [comment]
目前不支持。
