### ISSUE TITLE
希望增加菜单栏图标大小自定义功能

### ISSUE THREAD

**Issue by zwfengineer** [wangeditor-team/wangEditor#4173]
## 问题描述

*菜单栏的图标实在是太大了我希望能自定义这些图标的大小*

## wangEditor 版本

*wangEditor 5.x*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
目前不支持自定义图标。

一旦自定义，你还需要调整图标的 css 样式，这样很麻烦。
