### ISSUE TITLE
span标签包裹的img不会显示

### ISSUE THREAD

**Issue by icefee** [wangeditor-team/wangEditor#4175]
## bug 描述
如题， html是由其他编辑器（CK editor）生成， 因为有些兼容问题，换成现在的编辑器，发现出现上述情况

## wangEditor 版本
最新 cdn

## demo 能否复现该 bug ？
能

## 在线 demo
https://stackblitz.com/edit/web-platform-qk1bdk?file=index.html

**Comment by icefee** [comment]
我现在的处理方式是用正则将span替换成p 可以临时解决问题

**Comment by wangfupeng1988** [comment]
span 包含 img 这本身就是一种不规范的写法，目前还不支持。
