### ISSUE TITLE
建议维护自己内部的样式，而不受如reset.css之类的影响

### ISSUE THREAD

**Issue by ashuicoder** [wangeditor-team/wangEditor#4178]
- 如引用了`tailwind.css`后，重写了很多标签的默认样式，比如h1的字体大小，ul、ol的list-style等，就会出现列表签名的圆圈消失
- 作为一个通用的组件库，希望做到的是通用的

**Comment by shinchanZ** [comment]
你好，请问这个最后怎么解决的，我在使用过程中样式也被ｔａｉｌｗｉｎｄｃｓｓ　覆盖了

**Comment by simon-muyezhang** [comment]
@shinchanZ @ashuicoder @wangfupeng1988 请问大佬是如何解决tailwindcss中的样式冲突问题的，我把@tailwind base;这行注释掉，富文本编辑器的样式是保留了，但是shadow, hover这些tailwind的样式出不来了

**Comment by AIchovy** [comment]
在next.js和tailwindcss的技术栈中使用会碰到样式错乱的问题，单独维护wangEditor.css样式文件引入解决。
[样式来源](https://unpkg.com/@wangeditor/editor@latest/dist/css/style.css)
```
import './wangEditor.css'
```
