### ISSUE TITLE
自定义个 ModalMenu 菜单，Modal 弹窗怎么设置为网页正中间

### ISSUE THREAD

**Issue by Yangjia23** [wangeditor-team/wangEditor#4179]
## 问题描述

我正在自定义创建个 ModalMenu，点击菜单后会弹出个 modal, 如何设置 modal 的位置在页面正中间？我看了源码中 getModalPositionNode 方法来设置弹窗位置，但不清楚如何使用，没看到demo示例

## wangEditor 版本

@wangeditor/editor 0.15.14

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

自定义创建个 ModalMenu

**Comment by wangfupeng1988** [comment]
参考这里 https://www.wangeditor.com/v5/toolbar-config.html#modalappendtobody

**Comment by Yangjia23** [comment]
> 参考这里 https://www.wangeditor.com/v5/toolbar-config.html#modalappendtobody

按照链接已经实现了，但设置 modalAppendToBody = true , 会导致插入链接🔗 的弹窗也会插入到  body 中，这个能特殊处理嘛

**Comment by wangfupeng1988** [comment]
@Yangjia23 不支持特殊处理
