### ISSUE TITLE
react版本中文标点符号会被转换为英文

### ISSUE THREAD

**Issue by teddy1209** [wangeditor-team/wangEditor#4180]
## bug 描述

使用搜狗输入法输入中文标点符号会转换为英文，系统输入法正常

## 你预期的样子是？

能够输入中文标点符号

## 系统和浏览器及版本号

- 操作系统 macOS Catalina
- 浏览器和版本 Chrome  101.0.4951.54

## wangEditor 版本

0.15.18

## demo 能否复现该 bug ？

能

https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/yarn.lock:109113-109117

## 在线 demo

https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/yarn.lock:109113-109117

## 最小成本的复现步骤

- 步骤一：使用搜狗输入法
- 步骤二：输入中文，
- 步骤三：富文本展示英文,

**Comment by wangfupeng1988** [comment]
复现了。我也是 Mac Chrome 和搜狗输入法。

很奇怪，用这个 demo http://106.12.198.214:8882/master/examples/default-mode.html 就可以正常输入，用 React 就不行呢。

我继续查查吧

**Comment by teddy1209** [comment]
非常感谢，另外还有一个问题：
![image](https://user-images.githubusercontent.com/43714011/167840639-70e7feaa-fbce-47db-a0f7-141c099e69ad.png)
![image](https://user-images.githubusercontent.com/43714011/167840703-a1bf7bf7-d5e4-42b8-ba5a-5994041e37e5.png)
如图，选中文字后输入，光标会出现在该行最前面，可否一起看下，react demo也可以复现

**Comment by wangfupeng1988** [comment]
@teddy1209 其他的 bug 再重新提交吧，别混在一起。

**Comment by wangfupeng1988** [comment]
@teddy1209 升级 `@wangeditor/editor` 和 `@wangeditor/editor-for-react` 最新版本即可解决，参考 demo 源码 https://github.com/wangfupeng1988/react-wangeditor-demo 

你试试

**Comment by teddy1209** [comment]
问题解决了，非常感谢😊
