### ISSUE TITLE
ould not resolve "@babel/runtime-corejs3/core-js-stable/json/stringify"

### ISSUE THREAD

**Issue by muyang1992** [wangeditor-team/wangEditor#4181]
##  vite +react 项目中使用 项目运行报错

Could not resolve "@babel/runtime-corejs3/core-js-stable/json/stringify"

    node_modules/@wangeditor/editor-for-react/dist/index.esm.js:1:13:
      1 │ import e from"@babel/runtime-corejs3/core-js-stable/json/stringify";import t,{useRef as r,useState ...
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime-corejs3/core-js-stable/json/stringify" as external to
  exclude it from the bundle, which will remove this error.

11:01:11 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@wangeditor/editor-for-react/dist/index.esm.js:1:13: ERROR: Could not resolve "@babel/runtime-corejs3/core-js-stable/json/stringify"

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
能否给一个 demo 示例？选择以下都可以

https://codesandbox.io/
https://codepen.io/
https://stackblitz.com/

**Comment by muyang1992** [comment]
现在已经解决了，重新安装@babel/runtime-corejs3 这个就可以了。

**Comment by joket1999** [comment]
> @babel/runtime-corejs3
我也遇到这个问题，wangEditor里应该加上这个依赖。或者文档里明示需要安装@babel/runtime-corejs3
