### ISSUE TITLE
关于目录大纲的问题

### ISSUE THREAD

**Issue by wangzhongl** [wangeditor-team/wangEditor#4182]
## 问题描述

*查阅文档时 没有发现预览模式 还有关于侧边目录大纲的写法*

## wangEditor 版本

*最新版本*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
第一，预览模式需要你自己去做，通过 `editor.getHtml()` 获取 HTML 然后预览即可

第二，目录大纲参考 https://www.wangeditor.com/demo/catalog.html

**Comment by wangzhongl** [comment]
感谢
