### ISSUE TITLE
选中后输入中文文字，输入内容会出现在该行开头

### ISSUE THREAD

**Issue by teddy1209** [wangeditor-team/wangEditor#4183]
## bug 描述

选中部分内容后输入中文文字，输入内容会出现在该行开头，回车后才出现在插入位置，但若中途输入错误，光标就会停留在句首

## 你预期的样子是？

输入内容出现在选中位置

## 系统和浏览器及版本号

macos
chrome 101.0.4951.54

## wangEditor 版本

"@wangeditor/editor": "^5.0.1",
"@wangeditor/editor-for-react": "^1.0.2",

## demo 能否复现该 bug ？

能

## 在线 demo

https://www.wangeditor.com/demo/

## 最小成本的复现步骤

- 步骤一 输入任意文字
- 步骤二 选中部分文字
- 步骤三 输入任意文中文
- 步骤四 输入内容出现在句首
- 
![image](https://user-images.githubusercontent.com/43714011/168015862-f05c7b5c-19b6-4565-8257-7866333e985d.png)
![image](https://user-images.githubusercontent.com/43714011/168015916-6afd7f37-6712-4e74-911a-d1f4cebda6a0.png)

**Comment by wangfupeng1988** [comment]
已知问题

**Comment by cyh401** [comment]
┗|｀O′|┛ 嗷~~这个问题什么时候嫩解决啊

**Comment by wangfupeng1988** [comment]
@cyh401 不确定，得需要时间排查，大家都业余做。

**Comment by wangfupeng1988** [comment]
代码已合并，待发布

**Comment by wangfupeng1988** [comment]
已发布，更新最新版本 https://www.npmjs.com/package/@wangeditor/editor

**Comment by zhm84** [comment]
> 已发布，更新最新版本 https://www.npmjs.com/package/@wangeditor/editor

请问最新版修改这个问题了吗？刚刚试了一下还是有问题，官网的demo也能复现。

**Comment by wangfupeng1988** [comment]
@zhm84 已修复了，我试着官网 demo 已经可以了。chrome 浏览器

**Comment by zhm84** [comment]
> @zhm84 已修复了，我试着官网 demo 已经可以了。chrome 浏览器

我也是chrome浏览器

可以试一下一下步骤：
1. 在编辑器内输入以下三行内容
![第一步](https://user-images.githubusercontent.com/57031862/180751345-5c07d40f-9a52-4e7e-ad7f-ad75732fcb97.png)
2. 在第一行的末尾随便新增一点内容
![第二步2](https://user-images.githubusercontent.com/57031862/180751781-28561c2f-4c35-4a0e-a03c-b36378e3e072.png)
3. 选中第三行的文字，输入内容
![第三步](https://user-images.githubusercontent.com/57031862/180751903-7c8d891f-766f-45ba-bb8f-ec79fef8e9d3.png)
4. 可以看到影响了第一行的内容
![第四步](https://user-images.githubusercontent.com/57031862/180752059-a65434d8-4a53-4946-abc6-ef534eba8bc7.png)

**Comment by wangfupeng1988** [comment]
@zhm84 你说的这是一个新的 bug ，之前没有发现过，和这个 bug 无关。

你可以再去提交一个新 issue ，我们作为 bug 跟踪
