### ISSUE TITLE
自定义菜单，TS 报错，引入也是乱糟糟，太不友好了

### ISSUE THREAD

**Issue by PieDi** [wangeditor-team/wangEditor#4184]
## 问题描述
是这样的，奔着富文本编辑器生成页面的需求，考虑存在pc和移动端所以打算加个预览的自定义菜单，但是使用起来太不友好了，第一文档中没有描述，第二参考demo源码，在 react 中的引入也是乱糟糟，
![image](https://user-images.githubusercontent.com/19202314/168016662-947f26ee-b202-426c-8f97-d1ccd8bb1d80.png)
如图所示，Dom7Array  和  $   如何在react 中引入呢
  
*请输入遇到的问题...*

## wangEditor 版本  5.0

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考这里这个源码 https://github.com/wangeditor-team/wangEditor-plugin-formula

你截图部分参考这里 https://github.com/wangeditor-team/wangEditor-plugin-formula/blob/main/src/module/menu/InsertFormula.ts

**Comment by PieDi** [comment]
老哥 这个Dom7Array  要按照你demo zhongde 复制出来一个么，这个我记得还有一个注册Ele  那个又是啥呢？感觉老哥后续有时间可以 把  demo 整理一下，我后来用 ISelectMenu  实现了 也添加到toolbar  上了，但是  getValue  里面的 match  一直是空，我感觉肯定是哪里key 的标识需要前后流程统一，但是有没有文档说 全靠猜

**Comment by wangfupeng1988** [comment]
感谢建议哈，我有空了录制一个视频教程。

注册 elem 我猜你可能说的是这个：https://www.wangeditor.com/v5/development.html#renderelem

**Comment by PieDi** [comment]
> 

是的，但是 老实讲，我看了文档  并不明白这个注册都是为了做啥，应该存在某种关联，我的自定义菜单也是看着仿照源码加上去的，目前是成功加到toolbar 上了，但是不能使用，应为getvalue 一直无法匹配，
