### ISSUE TITLE
滚动条

### ISSUE THREAD

**Issue by xiaoliulang0213** [wangeditor-team/wangEditor#4185]
## 功能描述

*可否在设置min-height属性后，输入的内容超过该高度时自动出现滚动条，而不是编辑器随着内容一起变高？
或者设置height属性，在没有内容时不出现滚动条，只有内容超过该高度时才出现滚动条*

**Comment by wangfupeng1988** [comment]
这个需要你自己做。编辑器的 DOM 都是自己定义的。
