### ISSUE TITLE
vue3官网引入直接报错..我是菜鸡大佬

### ISSUE THREAD

**Issue by xhcq** [wangeditor-team/wangEditor#4186]
## bug 描述

*请输入内容……*

## 你预期的样子是？
![error](https://user-images.githubusercontent.com/89125689/168043346-de5dce4d-3922-4ba6-bfba-fb73380dd560.png)

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本
5
*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
可以参考这里的 demo https://www.wangeditor.com/v5/for-frame.html#vue3
