### ISSUE TITLE
这个破逼玩意vue3根本用不了，操， ｢wdm｣: WARNING in ./node_modules/@wangeditor/editor-for-vue/dist/index.esm.js 185:22-40

### ISSUE THREAD

**Issue by yinwubikong** [wangeditor-team/wangEditor#4187]
## bug 描述
![image](https://user-images.githubusercontent.com/14801769/168049508-301dfc14-0c0e-4e89-8812-1fd1eb390d7c.png)

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
![image](https://user-images.githubusercontent.com/14801769/168049657-acd079ec-16e9-4d7f-a8e9-3112d890a712.png)

## wangEditor 版本

*请输入内容……*
复制粘贴的demo都tm跑步起来，你们这star都是他妈刷的吧

**Comment by wangfupeng1988** [comment]
对，几万行代码也都是刷的
