### ISSUE TITLE
为什么定义了 keyup事件不执行

### ISSUE THREAD

**Issue by charrysong** [wangeditor-team/wangEditor#4189]
editor.on("keyup",function(){
                            console.log("keyup事件执行了");
 })

**Comment by wangfupeng1988** [comment]
没有 keyup 事件，具体参考 https://www.wangeditor.com/v5/API.html#%E5%86%85%E7%BD%AE%E7%9A%84%E4%BA%8B%E4%BB%B6

如果你想要 keyup ，得自己注册 DOM 事件

**Comment by charrysong** [comment]
知道了
