### ISSUE TITLE
editor.focus能不能将光标定位到最后

### ISSUE THREAD

**Issue by lovemyFamilyFovever** [wangeditor-team/wangEditor#4190]
## 问题描述
当前业务需要定制一个功能，点击某一按钮，将内容自动输入到编辑框内,如下图

目前遇到的问题是：每次输入之前都需要【手动】将光标定位到编辑器的最后的位置，因为点击了其他按钮会使editor失焦，使用了editor.focus(),但是这个会将光标默认放在首位。

## wangEditor 版本

editor@5.0.1

## 是否查阅了文档 ？

[（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）](https://www.wangeditor.com/v5/API.html#focus)

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
点击按钮时，先执行 `editor.focus(true)` 就会定位到文档最后

文档没有 `true`，我去补充一下

**Comment by ilovesabin** [comment]
编辑回显值的时候光标定位到了首位，设置了editor.focus(true)也不会定位到最后一位
