### ISSUE TITLE
自定义菜单(ISelectMenu)，已经注册，但是getvalue 中 match 一直为空，但是toolbar 并不能显示我的所选项

### ISSUE THREAD

**Issue by PieDi** [wangeditor-team/wangEditor#4192]
## 问题描述
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/19202314/168194816-8a60fdd7-1cab-4904-9fe1-98fbbb6cdb40.png">
 如图我所需的菜单我已经添加上去了 
这是我注册的过程
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/19202314/168194912-f61093d8-fc84-41a7-be5f-2aadaa3203b0.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/19202314/168194933-ee3b349b-3d1c-4e28-a6ce-224f296189ab.png">

但是我去不能正确的使用  
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/19202314/168194988-6cbfb8e4-5f71-4d76-957c-8dfa0b72dbe9.png">
![image](https://user-images.githubusercontent.com/19202314/168195775-72d8c538-6f7d-4648-ad6b-c5b6f6f15838.png)

打印调试表明，match 永远是空，set  和 get 的过程 我理解是通过这两个方法可一个组件赋值，和  获取值（toolbar上显示 select 相关项 ），但是我这个mactch 为空，导致toolbar 上显示不出来我的选择项

## wangEditor 版本
5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
你这里打印的 `n` 都是什么？贴出来我看看

<img width="546" alt="image" src="https://user-images.githubusercontent.com/9583120/168206974-769bdc20-619c-461e-8016-bdcd1d6b3f4a.png">

**Comment by PieDi** [comment]
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/19202314/168224337-612e8673-2e48-4b4c-b7a7-e50d808dd0bf.png">
一直是 underfine ，导致我一直点某一项  但是没有在toolbar 上显示出来，

**Comment by PieDi** [comment]
还有老哥，建议看看 图片编辑的能否加上宽高设置，以及文字设置，目前我看图片是等比变化，然后和文字配合的布局也不友好，
<img width="746" alt="image" src="https://user-images.githubusercontent.com/19202314/168226371-86b3f18d-2e70-4d1c-b78e-ecc8388e9b13.png">
类似这个  第一个箭头是配合文字布局的设置按钮，第二个可以分别设置图片宽高

**Comment by wangfupeng1988** [comment]
> 一直是 underfine

不是 undefind ，你看看 `3333222` 那一行，有打印，并不是你定义的 `preview` elem

**Comment by wangfupeng1988** [comment]
> 还有老哥，建议看看 图片编辑的能否加上宽高设置，以及文字设置，目前我看图片是等比变化，然后和文字配合的布局也不友好，


去重新提交个 issue 吧，我没看懂你的意思

**Comment by PieDi** [comment]
> 

嗯嗯 这个是个优化建议

**Comment by PieDi** [comment]
> > 一直是 underfine
> 
> 不是 undefind ，你看看 `3333222` 那一行，有打印，并不是你定义的 `preview` elem

这个我是说我屁匹配的结果一直是underfine，我确实不知道 这个如何去和 elem 关联  文档中也没有 对照源码 没有猜出来是如何关联的，所以想 请教 老哥 如何让我自定义的menu  能和 elem 进行相应的匹配

**Comment by wangfupeng1988** [comment]
这个我也没法一两句说说清楚，你现在只能去参考下现有插件的源码。

我下周去做一个相关的视频。

**Comment by PieDi** [comment]
> 这个我也没法一两句说说清楚，你现在只能去参考下现有插件的源码。
> 
> 我下周去做一个相关的视频。

嗯嗯 感谢老哥，期待，确实需要把自定义菜单的注册、以及内部事件流转逻辑搞清楚。我也是参考源码 把自定义菜单添加上去的，但是，确实也没有猜出来这个是流转过程，导致匹配不上 无法使用赋值

**Comment by wangfupeng1988** [comment]
> 我下周去做一个相关的视频。

https://www.bilibili.com/video/BV1Y3411A7eb
