### ISSUE TITLE
不好使，这个sb作者还tm在这乱删回复，太恶心人了，打死不用这个b玩意，一堆bug还敢玩这提交

### ISSUE THREAD

**Issue by yinwubikong** [wangeditor-team/wangEditor#4193]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
那你可就为难我了，打死人犯法！你还是凑活着用吧。

**Comment by xxasd** [comment]
会不会是因为你太菜了😆
