### ISSUE TITLE
React v5 上传图片后台MultipartFile为空，但是参数后台可以接收到。

### ISSUE THREAD

**Issue by AnnaSuSu** [wangeditor-team/wangEditor#4195]
## 问题描述
React v5 上传图片后台MultipartFile为空，但是传递的参数后台可以接收到。

## wangEditor 版本

5.0.1

## 是否查阅了文档 ？

*是*

## 最小成本的复现步骤

- 步骤一
-     editor.getMenuConfig('uploadImage').fieldName = "img"
    editor.getMenuConfig('uploadImage').server = '/api/server/web/rest/news/uploadingEditorImg'
    editor.getMenuConfig('uploadImage').meta = {
      news_id: 1
    }
    this.setState({ editor: editor });
- 步骤二
- 	@RequestMapping("uploadingEditorImg")
	public void uploadingEditorImg(MultipartFile file, HttpServletRequest request) throws IOException {
		// 得到上传图片图片对应的新闻编号
		String id = request.getParameter("news_id");
		System.out.println(id);
		System.out.println(file);
	}
- 步骤三
- file为空，id可以接收到为1

**Comment by wangfupeng1988** [comment]
看你描述，你上传图片应该是成功了，对吧？

然后你在浏览器控制台看看 Network ，看看请求时的 FormData 是不是正确？
