### ISSUE TITLE
可以插入一个button吗，或者可以插入一个只读的文本吗

### ISSUE THREAD

**Issue by du-pu** [wangeditor-team/wangEditor#4196]
## 问题描述

希望插入只读的button，发现插入后该button的内容还是可以编辑的,期望插入一个不可编辑的内容，类似实现tag的功能

## wangEditor 版本

wangEditor 5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一  打开https://www.wangeditor.com/demo/set-html.html
- 步骤二  在sethtml上方的编辑框最后一行插入  一个button， <button type="button">点我!</button>
- 步骤三  点击下方的编辑器，发现button的内容还是可以编辑的

**Comment by wangfupeng1988** [comment]
这个需要你自定义，文档可参考 https://www.wangeditor.com/v5/development.html 

源码可参考[插件](https://www.wangeditor.com/v5/plugins.html)，有类似的功能

**Comment by du-pu** [comment]
谢谢回复，我研究一下

**Comment by PaulDuChina** [comment]
参照着艾特组件已经实现了这个功能，谢谢指导
