### ISSUE TITLE
上传图片怎么触发事件

### ISSUE THREAD

**Issue by BenjenPeng** [wangeditor-team/wangEditor#4197]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

v5.10

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

 editorConfig.MENU_CONF['uploadImage'] = {
      server: 'http://106.12.198.214:3000/api/upload-img', // 上传图片地址
      // server: 'http://106.12.198.214:3000/api/upload-img-10s', // 用于测试 timeout
      // server: 'http://106.12.198.214:3000/api/upload-img-failed', // 用于测试 failed
      // server: 'http://106.12.198.214:3000/api/xxx', // 用于测试 404

      timeout: 5 * 1000, // 5s

      fieldName: 'custom-fileName',
      meta: { token: 'xxx', a: 100 },
      metaWithUrl: true, // 参数拼接到 url 上
      headers: { Accept: 'text/x-json' },

      maxFileSize: 10 * 1024 * 1024, // 10M

      base64LimitSize: 5 * 1024, // 5kb 以下插入 base64

      onBeforeUpload(files) {
        console.log('onBeforeUpload', files)

        return files // 返回哪些文件可以上传
        // return false 会阻止上传
      },
      onProgress(progress) {
        console.log('onProgress', progress)
      },
      onSuccess(file, res) {
        console.log('onSuccess', file, res)
      },
      onFailed(file, res) {
        alert(res.message)
        console.log('onFailed', file, res)
      },
      onError(file, err, res) {
        alert(err.message)
        console.error('onError', file, err, res)
      },
}

**Comment by wangfupeng1988** [comment]
没懂，触发什么事件？
