### ISSUE TITLE
在uniapp中使用wangeditor样式错误问题

### ISSUE THREAD

**Issue by myfcag** [wangeditor-team/wangEditor#4198]
在uniapp中，使用wangeditor，toolbar的样式是完全错误的，所有button按钮都带了一个黑边框，而且宽度也都不对，这里不能上传图片，不知道该怎么发出来

**Comment by myfcag** [comment]
![image](https://user-images.githubusercontent.com/105475698/168212822-74354a19-36b8-4f07-b4d2-5f0906e8e7a8.png)
就是这样的，不知道该怎么解决，能帮我处理一下吗？

**Comment by wangfupeng1988** [comment]
uniapp 我也不了解，我去问问其他人，看有知道的吗

**Comment by yixinagqingyuan** [comment]
你是要编译到哪个平台？还是直接用uniapp正常写vue页面

**Comment by syxchina** [comment]
这个是因为uniapp 会把样式里面原生样式去掉， 比如：  .name button{color:red;}，这种样式就不会生效；
目前无解，wangeditor里面很多都用这种方式，目前无解

**Comment by syxchina** [comment]
可以实用V4版本，可以用
