### ISSUE TITLE
wangEditor如何设置内容的编码格式？

### ISSUE THREAD

**Issue by cxmmmmmmm** [wangeditor-team/wangEditor#4199]
## 问题描述

*在wangEditor编辑器中输入大量阿拉伯语，在保存的时候出现（unable to decode value）返回参数异常*

## wangEditor 版本

*4.7.10*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）是

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一  输入大量阿拉伯语
- 步骤二 点击保存
- 步骤三  get请求将内容传入服务器

**Comment by cxmmmmmmm** [comment]
希望尽快收到答复

**Comment by wangfupeng1988** [comment]
我对阿拉伯语不了解，没做过此类项目，暂时帮不上你。

**Comment by cxmmmmmmm** [comment]
那如何给编辑器设置编码格式呢？

**Comment by wangfupeng1988** [comment]
编辑器是网页的一部分，设置 HTML 的编码格式即可。
