### ISSUE TITLE
征集其他富文本编辑器（如百度 ueditor ）使用中的问题和优点

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#42]
如题。

如果你使用了其他富文本编辑器，例如 udeitor kindeditor 等等任何的编辑器，发现了某些问题或者优点，不妨在这里分享出来。

优点我会在wangEditor中加上，缺点我也会对比wangEditor，有的话就修改。

一起为开源软件贡献力量！

**Comment by Trult** [comment]
侧边栏的html使用嵌套的方法感觉会比较好自定义样式
就是 相关的div ul和a标签在同一父元素里面
现在遇到的问题就是dorpMenu相对于btn的定位有点棘手 如果都在同一div里面会简单很多

**Comment by wangfupeng1988** [comment]
@Trult 你的回答貌似跑题了吧，如果有其他疑问或建议，可以另起一题反馈给我。

**Comment by Trult** [comment]
...嘛 发现的某些问题就是自定义样式不是非常简单啊  国内的文本编辑器大部分都有这个缺点的感觉.. 这个也不是完全的bug反馈 只是觉得能这样做会更好 这不符合主题？   
主题就是说编辑器需要改进的地方吧？ 难道我理解错了？

**Comment by liamwang** [comment]
1、全屏时为什么不是100%全屏，在Chrome浏览器输入内容直到出现滚动条时显示有问题，其它浏览器没试。
2、插入图片或表格后，左上角出现的“X”图标点了没反应（chome浏览器）。
3、可以拖动调节高度是一个很实用的功能，貌似没有找到这选项，其它编辑大部分都有的。
4、生成的html代码不是很标准，比如回车的时候是<div>标签，标准的应该是<p>标签。

我有两个网站，一个基于Bootstrap，用的是 summernote 编辑器。另一个网站不是基于Bootstrap，于是想找一个只依赖于 jQuery 的编辑器。对 wangEditor 很感兴趣，UI 我比较喜欢，而且也是轻量型的，符合我的需求。

两个网站 leaball.com 和 geekgist.com，geekgist 正在加入文章发布的功能，苦于找不到合适的编辑器，tinyMCE 太笨重，summernote 依赖于 bootstrap，wangEditor 还不是很成熟，文档也不是很全面。不过我看到你正在努力改进，是真心的想做好这个开源产品，每一个真心做产品的人都是值得尊敬的！

其它编辑器大部分比较丑，支持 IE9 以下的编辑器的，都会毫不犹豫的放弃。我觉得喜欢写文章的人都比较注重体验，用IE678的人基本上可以忽略不记，仅需支持主流较新版本的浏览器即可。倡导使用主流较新浏览器，力所能及从我开始 ^_^。

继续关注 wangEditor，加油。

**Comment by wangfupeng1988** [comment]
@Trult  这个issue的题目是这样的：
>如果你使用了其他富文本编辑器，例如 udeitor kindeditor 等等任何的编辑器，发现了某些问题或者优点，不妨在这里分享出来。

当然，你提出其他建议，也是ok的。

你说的『自定义样式不够简单』，能否具体描述一下：你认为的简单都有哪些功能？我需要量化这些问题。

**Comment by wangfupeng1988** [comment]
@liamwang 感谢对产品提出一些bug和建议，

1. 全屏不能100%的问题，确实是一个小问题，现在已经解决了https://github.com/wangfupeng1988/wangEditor/issues/43

2. 删除图片的叉号，这个问题在部分浏览器上出现过，目前也已经修复了；

3. 拖拽调节高度这个功能目前没有，而且我也不打算增加。我觉得自动随时内容增加高度，用户体验更好；

4. 生成html标准与否，我决定不了，这都是浏览器的命令生成的。

**Comment by jerry-he** [comment]
ueditor缺点，文档较少，文件上传部分找不 到任何文档，虽然自称轻量，但其全功能、去除 ui 后、压缩后的js也将近300k，第一次加载速度极慢。大概需要下载90个文件    

文件这么重且没有好的组件管理方案  默认提供的ueditor 配置文件太复杂    最主要还是文档问题

关于其它编辑器的通用问题，就是工具栏的位置问题，太难使用了，ueditor简直就没法儿自己设置，希望wangeditor吸取

**Comment by wangfupeng1988** [comment]
@jerry-he 很感谢你的建议，包括你提到的工具栏位置的建议，我都会纳入考虑。

**Comment by ouyangshiqiang** [comment]
1、代码插入的时候，如何集成你的 https://github.com/wangfupeng1988/wangHighLighter
2、图片文件上传的时候做的有点复杂,虽然给出了解决方案，图片代码上传可以参考一下http://xheditor.com/ 的上传代码的接口

谢谢

**Comment by wangfupeng1988** [comment]
@ouyangshiqiang 插入代码的高亮，目前可集成 highlighter.js
详细可查看说明文档

**Comment by ouyangshiqiang** [comment]
@wangfupeng1988  我还是喜欢你的 wangHighLighter ，比 Highlighter.js 好

**Comment by wangfupeng1988** [comment]
那个早就不维护了，还是用推荐的`Highlighter ` 吧。目前的版本已经无法集成 `wangHighLighter `

**Comment by ouyangshiqiang** [comment]
好吧

**Comment by lxholding** [comment]
你好，有一个问题，使用源码浏览功能的时候所有代码都在一行里，导致修改源码的时候看起来很费劲，是否能像ueditor等编辑器一样在源码模式下格式化代码一下代码 ：）

**Comment by Sopcce** [comment]
1、插入图片功能很好，但是能否都支持下小图片预览放大（鼠标移入时，显示比较大的效果图）。

上面提到的源码也是看起来不舒服，但是这个功能一般很少用，我可以忽略的，但是图片这个我还是需要的。在选择编辑器上,我还是很纠结的。思前想后。我主要需要的功能是表情、插入代码功能、和基本的加粗、下划线、图片上传、视频连接就足够了。我向往的编辑器也是类似知乎那样简单几个功能就好的。

**Comment by wangfupeng1988** [comment]
@Sopcce 你说的图片预览放大，之前有人问过类似的问题，我已经在文档中给出了解决方案：http://www.kancloud.cn/wangfupeng/wangeditor2/121411

**Comment by wangfupeng1988** [comment]
@lxholding 后续会将编辑器的源码格式化、并使用`codeMirror`美化一下，不过这个问题大家提的少，优先级不高，所有就放在后面了。先解决重要问题。

**Comment by gotanksgn** [comment]
UEditor在带格式粘贴时，与原有格式相差不大，而且兼容任何浏览器，
wangEditor粘贴时，chrome中带格式，但是与原格式有点差别，IE中不带格式。
希望在IE中可以带格式粘贴。

**Comment by yilinyouhun** [comment]
表格的单元格合并……

**Comment by attsion** [comment]
强烈建议加入一个功能，当内容变多时自动增加文本编辑器的高度。

**Comment by wangfupeng1988** [comment]
@attsion 有这个功能，文档中写了

**Comment by attsion** [comment]
自动变长不出滚动条吗？？我在文档中没找到啊？还有服务器能返回json吗？都什么年代了还要返回"text/plan"

**Comment by attsion** [comment]
另，能不能考虑加入前端图片压缩，这个太有用了。

**Comment by wangfupeng1988** [comment]
@attsion 

> 自动变长不出滚动条吗？？我在文档中没找到啊？ 

上面这句啥意思，没看明白。

另外，服务器端返回`json`或者`text/plain`可以根据项目需求而定，在满足需求的基础上，把难度降到最低。

最后，前端图片压缩这个功能，可以考虑加上，回头我调研一下技术方案。多谢反馈~

**Comment by attsion** [comment]
就是 “当内容变多时自动增加文本编辑器的高度” 你说文档里有但是实在没找到啊，另外从cnblogs你刚开始做的时候觉得名字好恶俗就没看好，一直最近看知乎上说起，真没想到已经进化到如此程度了，牛逼！！！

**Comment by wangfupeng1988** [comment]
@attsion  http://www.kancloud.cn/wangfupeng/wangeditor2/113966

**Comment by attsion** [comment]
谢谢确实好使。

**Comment by rookie125** [comment]
@wangfupeng1988 各方面都很不错，但是发现不能预先设置格式再输入文本，这是可以设置吗？还是没有预设置格式后输入文本这个功能的？

**Comment by attsion** [comment]
通过word中直接黏贴的话格式基本都不能识别，希望提供一个带格式的黏贴功能，还有个小问题，在word中黏贴的话最后的末尾会出现一行乱码，不知道是什么问题。

**Comment by wangfupeng1988** [comment]
@rookie125 

> 但是发现不能预先设置格式再输入文本，这是可以设置吗？还是没有预设置格式后输入文本这个功能的？

这个功能暂时没有，也不打算在 v2.x 版本中增加，计划会在 v3.x 即下一次大版本升级时候增加

**Comment by wangfupeng1988** [comment]
@attsion 能否把你所用的word（或者你发现粘贴出问题的word）发送给我一份（我QQ邮箱 642009075#qq.com），然后你用的哪个浏览器？我来验证一下。

另外，IE浏览器目前不支持带格式的粘贴

**Comment by attsion** [comment]
@wangfupeng1988 不好意思最近比较忙，邮件已发。

**Comment by wangfupeng1988** [comment]
> 然后你用的哪个浏览器

@attsion 浏览器信息也很重要

**Comment by rookie125** [comment]
@wangfupeng1988 这是个好东西，不过暂时缺少预设格式功能，期待增加

**Comment by ljkfgh2008** [comment]
风格很不错 但是没有实时预览这个功能

**Comment by wangfupeng1988** [comment]
@ljkfgh2008 预览自己来做就是了，获取内容，弹出个div，不就预览了吗

**Comment by ljeonhack** [comment]
@wangfupeng1988 ue编辑器的附件上传很不错，上传之后还自带各种文件类型的图标！！！

**Comment by 613660067** [comment]
增加一个字数统计与字数限制的设置不错!

**Comment by qtnote** [comment]
希望作者可以给每个插件加上开关配置，比如    编辑区域 link toolbar  编辑器区域 img toolbar  这些。有时候做评论框的时候可以不要

**Comment by 613660067** [comment]
本来就可以配置吧

**Comment by HLTwilight** [comment]
想获取编辑文档的足迹，为每一个p和p的同级标签加上唯一标识，用时间戳作为id，但每次回车换行都只能复制上一条标签的id而不是重新生成，可以在回车换行生成p标签的同时生成id吗？

**Comment by liniu** [comment]
如果能支持markdown 格式那就太完美了。

**Comment by wangfupeng1988** [comment]
@liniu 

> 如果能支持markdown 格式那就太完美了。

看这里 http://www.kancloud.cn/wangfupeng/wangeditor2/119071

**Comment by yuweilan** [comment]
能否支持word等文档粘贴格式保留？

**Comment by wangfupeng1988** [comment]
> 能否支持word等文档粘贴格式保留？
@yuweilan 我目前windows环境有点问题，电脑开机不了，会尽快跟踪这个问题。

**Comment by CrystalZYH** [comment]
我想在其中加入echart 图表，旁边是文字排版

**Comment by wangfupeng1988** [comment]
> 我想在其中加入echart 图表，旁边是文字排版

@CrystalZYH 这个有点复杂，不过通过自定义菜单可以实现，自定义菜单可以看文档。

**Comment by chingo8822** [comment]
希望考虑支持拖拽内容调整位置，这点对用户体验很重要。

**Comment by Ncare** [comment]
能做附件上传吗，类似于UE的。

**Comment by jettyu** [comment]
希望增加一个KindEditor的一键排版功能

**Comment by zhangl10** [comment]
图片上传增加进度条，增加预览功能

**Comment by wangfupeng1988** [comment]
@Ncare 附件上传参见文档中的说明，不支持。

@jettyu 这种复杂的功能，暂时不会去做，目前精力有限，只做核心功能。

@chingo8822 暂时不做拖拽调整内容

@airzhanglin 预览功能暂时不做

v3 也升级一段时间了，接下来 wangEditor 的策略，就是把核心做好、将所有的精力都用到增加编辑器体验上。

**Comment by fengzi2016** [comment]
可以做到让编辑器里的html和text结合，对应的存入后台，最后对应的前端展示，而不是单纯的分别取出它们吗？

**Comment by wangfupeng1988** [comment]
@fengzi2016 没明白你的意思

**Comment by nnntxxx** [comment]
ue的图片上传很好用，拖拽上传，复制上传，

**Comment by ghordonn** [comment]
在编辑器中点击其中一个图片，然后会出现蓝色的可以拖放的框框，然后页面就不能滚动了，  然后想办法退出选中图片状态，编辑器中的内容往下滚动 然后点击下面的一个图片， 然后那个蓝色的可以拖放的框框和点击的图片位置对不上， 这个是什么问题了

**Comment by wangfupeng1988** [comment]
@nnntxxx 会后续更新升级

**Comment by IVANLEE99** [comment]
上传网络图片，没回调函数，

**Comment by wangfupeng1988** [comment]
> 上传网络图片，没回调函数，

好吧，这个下次升级加上

**Comment by HalleyGao** [comment]
需要一个全屏功能，粘贴图片需要实现自动上传，我自己改了一版，凑合能用

**Comment by zhuqingsong59** [comment]
可以在菜单栏中添加字号设置和字体设置功能么

**Comment by wangfupeng1988** [comment]
@zhuqingsong59 字号和字体，应该统一、并通过 css 样式来控制，就像目前的 table code quote 一样

**Comment by iAesop** [comment]
KindEditor最好的功能是图片上传可以很简单地设置使用自己的上传程序，而不需要使用自带的上传程序，这样对你和使用者都好。象要上传到七牛，不需要你费心地去写代码，使用者使用自己的程序来实现这个功能，大家都省心。
editor = K.create('#content',{	uploadJson : '__URL__/upload.php', });
原先以为wangEditor也能这样，现在真正要使用时，才发现不能这样使用自己的上传程序。

**Comment by chinahxf** [comment]
onchange方法，现在只能绑定html的内容，text无法绑定，不知道是我没找到还是没有，看js中用的是获取html的，希望能扩展一下也能绑定text 内容，因为自己用的npm加载的，所以没法改。。。希望作者能扩展一下，谢谢

**Comment by wangfupeng1988** [comment]
@chinahxf 这个问题好解决啊，在 onchange 函数中拿到 html 之后，自己计算出 text ，不就行了？

**Comment by chinahxf** [comment]
嗯已经用js的处理了，还不知道js也可以取出text，长知识了

**Comment by Treagzhao** [comment]
百度的编辑器可以修改图片大小

**Comment by wangfupeng1988** [comment]
@Treagzhao 

> 百度的编辑器可以修改图片大小

该功能，wangEditor 中做了弱化，不会去模拟 word 中那种很复杂的图片、文字的编辑，把不常用的功能隐藏和弱化，让常用的功能更加简洁。

wangEditor 中，选中图片，然后点击“图片”菜单按钮，也可以修改图片大小。

**Comment by chinahxf** [comment]
我用的是七牛的上传，富文本中加入图片后选中然后按图片按钮又出现选择图片的框，并没有编辑图片大小的功能怎么搞呢？

**Comment by wangfupeng1988** [comment]
@chinahxf 这个问题，新建一个 issue 来讨论吧，别在这个 issue 下文

**Comment by Aluluzi** [comment]
ie9无法使用

**Comment by wangfupeng1988** [comment]
@Aluluzi 
> ie9无法使用
v3 开始不再支持 ie9

**Comment by CongAn** [comment]
@wangfupeng1988 我使用中遇到了bug #1224 ，bug只能在_initDom方法中更改，希望能够打散一个大方法，实现原子化方法，便于重写单独的方法修复bug，不必等待更新。

**Comment by wangfupeng1988** [comment]
@CongAn 我周末看下吧，近期业余较忙，相应可能慢，见谅。

**Comment by TonyGGC** [comment]
UEditor 支持图片拖拽， 我们这个好像没有此功能

**Comment by wangfupeng1988** [comment]
@TonyGGC 暂时还不支持，我记录下，后面升级可增加上

**Comment by MrChu** [comment]
建议：
1、工具栏希望增加“**字体**”选项
2、图片插入成功后希望可调整大小，类似UEditor
3、建议工具栏希望增加“**html**”源码与编辑点击切换的功能

问题：
1、单页面多个编辑器，无法设置编辑器的高度。编辑器默认height为300px，我需要的height为180px，最后通过以下样式解决：
`.w-e-text-container {height: 180px !important;}`
`.wang-editor {max-height: 206px;}`
2、单页面多个编辑器，编辑某一内容进行居中时，其他编辑器的内容也同步居中了

谢谢。

**Comment by zhuzhuzzy** [comment]
现在插入表格的功能过于简单了些，希望表格能支持的功能多一点，比如合并单元，单元格背景色，设置边框；个人认为这些应该是表格的基本功能，缺少这俩功能总感觉满足不了基本的编辑需求。
wangEditor不支持这些功能，我又不得不考虑其他的编辑器。结果看了一下其他的富文本编辑器，轻量级的几乎不支持编辑表格，稍微大点的又几乎不能前后端分离，也很难实现自定义图片上传的功能。
如果wangEditor能去做这项工作，是不是在轻量级编辑器里面算比较强大、有特色的了？

**Comment by zhang8h** [comment]
可以自定义增加菜单项吗，不是指增加默认的菜单项；因为我这有一个需求，有个checkbox复选框，这个复选框中我加了一个点击事件的，现在做法是每当需要增加这个复选框时都是从一个特定的位置去复制这个复选框过来。可不可以直接在菜单上自己定义一个图标，然后点击后可以插入特定的内容呢

**Comment by qtpalmtop** [comment]
![image](https://user-images.githubusercontent.com/17633395/38918896-9b6f60b4-4321-11e8-892e-2a620192133a.png)
部分列表不能正常显示

**Comment by IVANLEE99** [comment]
自动保存功能来一个

**Comment by Yos5ef** [comment]
wangEditor可不可以加一个上下标扩展 ，自己改源码的思路是怎么样的。

**Comment by conanxt** [comment]
UEDITOR复制表格后列宽可以拖动，wangEditor貌似还没有这个功能吧

**Comment by maxiao227** [comment]
希望能添加表格拖动功能

**Comment by celineWong7** [comment]
> 现在插入表格的功能过于简单了些，希望表格能支持的功能多一点，比如合并单元，单元格背景色，设置边框；个人认为这些应该是表格的基本功能，缺少这俩功能总感觉满足不了基本的编辑需求。
> wangEditor不支持这些功能，我又不得不考虑其他的编辑器。结果看了一下其他的富文本编辑器，轻量级的几乎不支持编辑表格，稍微大点的又几乎不能前后端分离，也很难实现自定义图片上传的功能。
> 如果wangEditor能去做这项工作，是不是在轻量级编辑器里面算比较强大、有特色的了？

同意丰富下表格的功能：合并单元格、边框设置等。

**Comment by mintonzhang** [comment]
之前，我使用ueditor和kindeditor时 获取html时，可以获取编辑器中的所有内容包括标签。 然后存入数据库。 使用的地方只需要把内容返回即可。 我在使用wangeditor时，发现html和text获取的内容相同，虽然使用html时可以自定义样式。 请问，这样做有什么好处吗？可否添加上一个这样的功能，以兼容从其他富文本编辑器的用户。

**Comment by mintonzhang** [comment]
你好，不好意思。之前用的是https://unpkg.com/wangeditor@3.1.1/release/wangEditor.min.js
我刚刚下载了3.1.1 没有这个问题

**Comment by mintonzhang** [comment]
你好，不好意思。之前用的是https://unpkg.com/wangeditor@3.1.1/release/wangEditor.min.js
我刚刚下载了3.1.1 没有这个问题

**Comment by duzhihao-github** [comment]
希望加入简单的数学公式，现在已经有不错都解决方案。

**Comment by yaoyingkang** [comment]
希望加入文本框内文字查找 替换功能

**Comment by yiiim** [comment]
> @zhuqingsong59 字号和字体，应该统一、并通过 css 样式来控制，就像目前的 table code quote 一样

可是实际情况通常是不是开发人员编辑富文本，编写富文本的人不可能只需要css里定义的几种字号，对于我来说，自定义字号非常重要，这直接导致了我需要去使用2.x的版本。

**Comment by awamwang** [comment]
v4的缩进功能，可不可以也支持table，或者说其他标签，发现p标签包裹的可以缩进，其他的不行

**Comment by ZengYingJ** [comment]
希望加入“选中多行文本修改对齐方式”的功能，同时选中多行文本的情况下，修改对齐方式没有效果，必须一行一行的修改，其他编辑器都是支持的，也比较常见，希望能尽快加入该功能

**Comment by mygithublxx** [comment]
从秀米复制进来的视频被过滤掉了，是为啥

**Comment by ihwf** [comment]
参考ckeditor, 可以完美从word文档复制粘贴任何内容, 包括文字和多张图片混合的时候, 依然能保留文档格式

**Comment by Mowmowj** [comment]
目前支持 拖拽调节文本每行的顺序吗

**Comment by Mowmowj** [comment]
试了下demo好像不行  这个功能不少编辑器实现了

**Comment by wangfupeng1988** [comment]
暂不支持 @Mowmowj
