### ISSUE TITLE
在Vue3中，应该怎样获得editor对象呢？

### ISSUE THREAD

**Issue by myfcag** [wangeditor-team/wangEditor#4201]
在Vue3中，应该怎样获得editor对象呢？

我查看了文档，都是在CDN下，创建时获得editor对象，然后利用这个editor对象进行相关的操作，

而vue3中，是在setup()创建的，我应该怎么在setup()之外，获得一个editor对象呢？

**Comment by myfcag** [comment]
同时，应该怎样才能进行赋值呢？

没有editor对象，赋值也不行，应该可以一并解决吧？

请帮我解答一下，谢谢！

**Comment by wangfupeng1988** [comment]
获取 editor 对象参考这里 wangeditor.com/v5/for-frame.html#使用-1

```js
    // 组件销毁时，也及时销毁编辑器
    onBeforeUnmount(() => {
        const editor = editorRef.value
        if (editor == null) return
        editor.destroy()
    })
```
