### ISSUE TITLE
插入了代码块，但之后中，比如再编辑，不能正确显示 会报错

### ISSUE THREAD

**Issue by feelingseas** [wangeditor-team/wangEditor#4203]
## bug 描述

我用code功能，插入一段代码后，然后再打开这个文章，会报错，就是不能把 getHtml内容生成文章后，入到数据库，然后取出再给到editor。
开始我怀疑是我用法不对，可是插入其他没有code的就可以。
感觉是换行的问题，我手动把 gethtml的内容中的空白（换行）去掉就可以了。

刚开始用，也可能是我没吃透，哪个细节没注意到？（不是bug？）

## 你预期的样子是？

编辑好的文章中的代码可以被正确打开再编辑

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

v5

## demo 能否复现该 bug ？

也不知道算能不能，我把我的数据库中的 内容直接复制到
https://www.wangeditor.com/demo/set-html.html
中的textarea,这样是正常的。

## 最小成本的复现步骤
```
<p><br></p><pre><code >&lt;div&gt;
	&lt;p&gt;this is p&lt;/p&gt;
&lt;/div&gt;</code></pre><p><br></p>
```

//以上内容是editor gethtml后，放到到数据库中的，
但是取出后，{{content}}是内容，就会报错。应该是换行问题（）
// 创建编辑器
```
	const editor = createEditor({
	  selector: '#editor-container',
	  config: editorConfig,
	  mode: 'default', // 或 'simple' 参考下文	
		html:'{{content}}'
	})
```

**Comment by feelingseas** [comment]
也不太会用github，怎么上传图片的。。告诉我一下。

**Comment by wangfupeng1988** [comment]
我看这个 demo http://106.12.198.214:8882/master/examples/parse-html.html

直接赋值你给的代码，点击  setHtml 按钮，不会报错。如下图

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/9583120/168476394-d40b8e22-832f-46f8-ad9b-2cd944e48afc.png">

**Comment by feelingseas** [comment]
> 我看这个 demo http://106.12.198.214:8882/master/examples/parse-html.html
> 
> 直接赋值你给的代码，点击 setHtml 按钮，不会报错。如下图
> 
> <img alt="image" width="1439" src="https://user-images.githubusercontent.com/9583120/168476394-d40b8e22-832f-46f8-ad9b-2cd944e48afc.png">
是呀，我发疑问中也说了，这样是正常的。
我js水平很一般。你主要看我第二个图，以及为什么会报那样的错。关键词：换行？？

**Comment by whxzjxx** [comment]
和我的问题一毛一样，换行导致的。我的是4204

**Comment by wangfupeng1988** [comment]
我需要一个能复现 bug 的 HTML demo ，越简单越好。

**Comment by feelingseas** [comment]
您好。首先非常感谢提供开源产品。


写完了，回头看内容，感觉 好像对您有不敬。真没有的，希望不会影响您的心情。


这个问题，可以说一天内两个人遇到了，应该是真的有问题吧，是确实有bug，还是说明文档没写明？
细节还不够？都很明确了就是 有换行的内容 怎么通过js的方法（不要借助html ，输入到 textarea 再用你的setHtml方法）。
我是本想给你做个demo的，最后我放弃了。为什么放弃，因为感觉这个问题表述很清楚了，我的视频，两个人近期也提到了。


关键词：换行 换行 换行&nbsp;


就说这个内容是不是用你的 方法 存下来的？是还是不是？如果是的话，这个内容 我要怎么再次赋给 editor,就是可以再编辑？是必须要先放到 一个textarea里，再通过js得到这个textarea的value，赋予给edior(这样是可行的，你是一直在这样来证明是ok的)? 还是有别的方法？再次编辑的问题，我看了下文档，我感觉这方面也比较欠缺（也可能是我没有发现）




和数据库其实没关系的。除非你 说下边的文字及内容不是你预期的结果。


<p&gt;<br&gt;</p&gt;<pre&gt;<code class="language-html"&gt;&amp;lt;div&amp;gt;
	&amp;lt;p&amp;gt;this is p&amp;lt;/p&amp;gt;
&amp;lt;/div&amp;gt;</code&gt;</pre&gt;<p&gt;<br&gt;</p&gt;













我也知道打字沟通效率低。可以的话，可以电话沟通一下：18923700665。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月16日(星期一) 上午8:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 插入了代码块，但之后中，比如再编辑，不能正确显示 会报错 (Issue #4203)





 
我需要一个能复现 bug 的 HTML demo ，越简单越好。
