### ISSUE TITLE
视频问题

### ISSUE THREAD

**Issue by whxzjxx** [wangeditor-team/wangEditor#4204]
## bug 描述
```
const editor = E.createEditor({
  selector: '#editor-text-area',
  content: [],
  html: <div data-w-e-type="video" data-w-e-is-void>
<video controls="true"><source src="../uploadfiles/videofiles/20220515185056591.mp4" type="video/mp4"/></video>
</div>,
  config: editorConfig
})
```
没法加载编辑器

## 你预期的样子是？
修改为下面：
```
const editor = E.createEditor({
  selector: '#editor-text-area',
  content: [],
  html: <div data-w-e-type="video" data-w-e-is-void><video controls="true"><source src="../uploadfiles/videofiles/20220515185056591.mp4" type="video/mp4"/></video></div>,
  config: editorConfig
})
```
只要将只要将html：video标签前后的换行符去掉，可以加载编辑器，正常打开视频。

## 系统和浏览器及版本号

win7、win10
chrom浏览器，360浏览器最新版

## wangEditor 版本

wangeditor 5.0.1

## demo 能否复现该 bug ？

不能

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

没有服务器，提供不了不好意思。

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

经过测试，只要将html：video标签前后的换行符去掉，就正常了。

**Comment by wangfupeng1988** [comment]
你用这个 demo https://www.wangeditor.com/demo/set-html.html

把下面这段代码贴到 textarea 中，然后点击 `Set HTML` 按钮，可以生成编辑器，不会报错（只是视频资源 404，这不是 JS 报错）

```
<div data-w-e-type="video" data-w-e-is-void>
<video controls="true"><source src="../uploadfiles/videofiles/20220515185056591.mp4" type="video/mp4"/></video>
</div>
```

如下图

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/9583120/168476554-35617af3-b288-49eb-96e6-4354e848245a.png">

即，带着换行符也可以正常生成编辑器。

**Comment by whxzjxx** [comment]
<div data-w-e-type="video" data-w-e-is-void>
<video controls="true"><source src="../uploadfiles/videofiles/20220515185056591.mp4" type="video/mp4"/></video>
</div>

**Comment by whxzjxx** [comment]
<div data-w-e-type="video" data-w-e-is-void>
<video controls="true"><source src="../uploadfiles/videofiles/20220515185056591.mp4" type="video/mp4"/></video>
</div>
如果提交写到数据库字段中，再次读出，就生成不了编辑器。去掉video前后的换行符，一切正常了。

**Comment by feelingseas** [comment]
你这个跟我的 应该是 一毛一样的错误了。你的issue是4204，我的4203。。看来应该确实是有的问题哦。官方看一下吧。
题主，你也可以试试，你插入代码，看是不是也不正常。

**Comment by whxzjxx** [comment]
嗯，错误一毛一样的。

**Comment by wangfupeng1988** [comment]
不要把数据库牵扯进来，就说用 HTML 如何复现这个 bug ，给一个最简单的 HTML demo 即可。

**Comment by feelingseas** [comment]
朋友 ，你好。你赋值时，用 键盘的左上角的那个点试好像可以避免js中多行赋值的错误。我搜索到的。好像就可以了。
能解决了，官方这方面你也要写到文档中去呀。这个很重要呀。
@wangfupeng1988 
![yinhao](https://user-images.githubusercontent.com/12237706/168567643-e76db972-7ccc-4c34-a7ef-d61aaefea980.png)

**Comment by wangfupeng1988** [comment]
> 朋友 ，你好。你赋值时，用 键盘的左上角的那个点（exc下边 波浪符号对应的 点）替代 单引号，好像可以避免js中多行赋值的错误。我搜索到的。好像就可以了。 能解决了，官方这方面你也要写到文档中去呀。这个很重要呀。 @wangfupeng1988 ![yinhao](https://user-images.githubusercontent.com/12237706/168567643-e76db972-7ccc-4c34-a7ef-d61aaefea980.png)

如你截图。如果把绿色框里的换成单引号，那就是 JS 语法错误了（因为你字符串里就有单引号）。JS 语法错误，编辑器管不了。

**Comment by feelingseas** [comment]
这张图片确实是有引号。但我最开始遇到问题时，是没有引号的。重点是换行。解决有换行的字符串是主要的。
代码中，有单引号正常吗？我认为是正常的。在这种情况下，用户肯定会有错误，这算不算bug？算不算bug不重要，在文档中 应该是有必要说明一下的吧。
我感觉你的意思是 我和这朋友遇到这个问题只是自己的语法？我很不认同。

我正常插入代码，别管有没有单引号，想再编辑时，会导致配置出错，导致异常。这得解决吧。。

你要直接说：我们会在文档中 提示用户，html的初始化用``包裹内容 就行了。我也就不回复你了。
我想问下，你会不会 为此修改文档呢？

**Comment by whxzjxx** [comment]
用 键盘的左上角的那个点（exc下边 波浪符号对应的 点）替代 单引号，我刚测试一切正常了，谢谢你，朋友！也谢谢王福朋，提供开源编辑器。
