### ISSUE TITLE
v-html如何原封不动显示html内容呢

### ISSUE THREAD

**Issue by KDWangBoss** [wangeditor-team/wangEditor#4205]
## 问题描述

*在vue2中使用v-model，编辑器会格式化显示内容，如何配置才能显示从后端获取到的html内容呢*

## wangEditor 版本

*  "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-vue": "^1.0.0",
*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 脚手架创建vue2项目，npm install @wangeditor/editor @wangeditor/editor-for-vue
- ```js
  <template>
      <div style="border: 1px solid #ccc;">
          <Toolbar
              style="border-bottom: 1px solid #ccc"
              :editor="editor"
              :defaultConfig="toolbarConfig"
              :mode="mode"
          />
          <Editor
              style="height: 500px; overflow-y: hidden;"
              v-model="html"
              :defaultConfig="editorConfig"
              :mode="mode"
              @onCreated="onCreated"
          />
      </div>
  </template>
  
  export default {
  	data(){
          editor: null,
          toolbarConfig: {},
          editorConfig: {},
          html: '',
          mode: 'simple'    
      },
      methods: {
          onCreated(editor) {
            this.editor = Object.seal(editor)
  		 
            setTimeout(() => {
              this.html = `<p><div style="color: red;">我是数据</div></p>`
            }, 5000)
              
            setTimeout(() => {
              console.error('获取到的html：', editor.getHtml())
            }, 10000)
          },
      }
  }
  ```
- 页面显示了'我是数据'，需要显示的是`<p><div style="color: red;">我是数据</div></p>`

**Comment by wangfupeng1988** [comment]
就参考这里 https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8

```
mounted() {
        // 模拟 ajax 请求，异步渲染编辑器
        setTimeout(() => {
            this.html = '<p>模拟 Ajax 异步设置内容 HTML</p>'
        }, 1500)
    },
```

**Comment by KDWangBoss** [comment]
这里异步还是会显示解析后的数据，能否加个html按钮，点击后显示带标签的html内容。
像百度编辑器的第一个就是html与text转换

**Comment by wangfupeng1988** [comment]
没懂你的意思

是这个 demo 的样子吗？https://www.wangeditor.com/demo/set-html.html

**Comment by KDWangBoss** [comment]
是的，如果无法解析的话就原标签内容显示
```
<p>wangEditor 只识别 editor.getHtml() 生成的 html 格式，不可以随意自定义 html 代码（html 格式太灵活了，不会全部兼容）</p>
<p>wangEditor can only understand the HTML format from editor.getHtml() , but not all HTML formats.</p>
<p><br></p>
<div style="color: red;">红色字体</div>
```

**Comment by KDWangBoss** [comment]
下面的<div style="color: red;">红色字体</div>无法解析，于是就原文显示
```
<p>wangEditor 只识别 editor.getHtml() 生成的 html 格式，不可以随意自定义 html 代码（html 格式太灵活了，不会全部兼容）</p>
<p>wangEditor can only understand the HTML format from editor.getHtml() , but not all HTML formats.</p>
<p><br></p>
<div style="color: red;">红色字体</div>
```

**Comment by KDWangBoss** [comment]
百度编辑器里面有个html按钮，是不是实现这个功能需要自定义菜单栏，实现一个html与text的转换功能。
预览不能解析的html内容，是不是需要自定义菜单栏，div中v-html绑定不能解析的html

**Comment by KDWangBoss** [comment]
百度编辑器里面有个html按钮，是不是实现这个功能需要自定义菜单栏，实现一个html与text的转换功能。
预览不能解析的html内容，是不是需要自定义菜单栏，div中v-html绑定不能解析的html

**Comment by wangfupeng1988** [comment]
> 百度编辑器里面有个html按钮

你说的是“查看和编辑 HTML”源码吧？

**Comment by wangfupeng1988** [comment]
> 下面的 `<div style="color: red;">红色字体</div>` 无法解析，于是就原文显示

这个在 wangEditor 是不能识别的，可以看看这里的红色文字 https://www.wangeditor.com/v5/content.html#%E8%AE%BE%E7%BD%AE-html
