### ISSUE TITLE
图片插入后， hoverbarKeys内的方法如何配置调用

### ISSUE THREAD

**Issue by liwengxing** [wangeditor-team/wangEditor#4206]
## 问题描述
图片插入后， hoverbarKeys内的方法如何配置调用
图片的编辑，删除，放大缩小等功能都是默认存在的，我需要在点击编辑时执行我的一些逻辑操作

*请输入遇到的问题...*
图片的编辑，删除，放大缩小等功能都是默认存在的，我需要在点击编辑时执行我的一些逻辑操作
## wangEditor 版本
v5
*请输入内容……*

## 是否查阅了文档 ？
是的
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 我需要在点击编辑时执行我的一些逻辑操作

你还需要说清楚你的需求，我才能准确的给你建议。

**Comment by PieDi** [comment]
> > 我需要在点击编辑时执行我的一些逻辑操作
> 
> 你还需要说清楚你的需求，我才能准确的给你建议。

老哥  自定义图片上传 那么  maxFileSize  、allowedFileTypes  这些属性还有效么？

**Comment by wangfupeng1988** [comment]
@PieDi 去看文档

**Comment by liwengxing** [comment]
是图片上传完成后，图片的hoverbarKeys上有编辑功能的，我需要在点击编辑按钮的时候重新调用上传方法然后自动去更改这个图片的src，alt，href，现在遇见的问题就是这个编辑按钮的方法也已经根据hoverbarKeys找到了，但是不知道需要配在代码的哪里才会生效

**Comment by liwengxing** [comment]
是图片上传完成后，图片的hoverbarKeys上有编辑功能的，我需要在点击编辑按钮的时候重新调用上传方法然后自动去更改这个图片的src，alt，href，现在遇见的问题就是这个编辑按钮的方法也已经根据hoverbarKeys找到了，但是不知道需要配在代码的哪里才会生效

**Comment by wangfupeng1988** [comment]
> 我需要在点击编辑按钮的时候重新调用上传方法然后自动去更改这个图片的src，alt，href

@liwengxing 这是菜单的功能，不是 hoverbarkeys 的。hoverbarKeys 仅仅是配置 hoverbar 上显示哪几个菜单，菜单具体的功能它不管。

基于你的描述，你需要去[自定义一个菜单](https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E8%8F%9C%E5%8D%95)，来实现你的自定义功能。
