### ISSUE TITLE
语法高亮支持groovy

### ISSUE THREAD

**Issue by PaulDuChina** [wangeditor-team/wangEditor#4208]
## 功能描述

*语法高亮支持groovy*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

[codemirror](https://codemirror.net/)

**Comment by wangfupeng1988** [comment]
已增加。更新最新版 `@wangeditor/editor` 即可
