### ISSUE TITLE
设置readOnly为true还是可以编辑

### ISSUE THREAD

**Issue by wangkemin** [wangeditor-team/wangEditor#4209]
react中使用wangEditor，版本为5.0.1，设置readOnly，编辑器仍然可以编辑
const editorConfig = {
        placeholder: '请输入内容...',
        readOnly: true,
        MENU_CONF: {
            uploadVideo: {
                server: '/api/upload',
            }
        },
    }

**Comment by wangfupeng1988** [comment]
参考这个 https://github.com/wangeditor-team/wangEditor/issues/4103#issuecomment-1126732068
