### ISSUE TITLE
模拟腾讯文档css和其他CDN失效，导致不能使用

### ISSUE THREAD

**Issue by name0980** [wangeditor-team/wangEditor#4213]
## 问题描述
模拟腾讯文档css和其他CDN失效，导致不能使用，

*请输入遇到的问题...*

## wangEditor 版本
5

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
CDN 失效我也没办法。你有靠谱的 CDN 推荐吗？
