### ISSUE TITLE
增加图片宽高的分别设置，增强图文混排布局设置

### ISSUE THREAD

**Issue by PieDi** [wangeditor-team/wangEditor#4214]
## 功能描述
建议针对图片，新增图片宽高的分别自定义，目前是等比缩放，其次增强图文混排
<img width="814" alt="image" src="https://user-images.githubusercontent.com/19202314/168708790-c0e0b082-cdd4-4b05-baaf-aa1e585b4ac4.png">

## 提炼几个功能点
1、新增图片宽高的分别设定
2、新增图文混排样式设置

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
> 新增图片宽高的分别设定

这个没看懂啥意思。

**Comment by wangfupeng1988** [comment]
> 图文混排样式

这个比较麻烦，近期不打算开发。

**Comment by Amanda827** [comment]
@wangfupeng1988 
就是
![image](https://user-images.githubusercontent.com/39717691/168736062-b0f059c3-4378-478e-a0ce-545b7b831ef3.png)
这个呀。

**Comment by wangfupeng1988** [comment]
@Amanda827 光一个截图没看懂啥意思。点那个“宽度”按钮，有什么效果呢？

**Comment by PieDi** [comment]
> @Amanda827 光一个截图没看懂啥意思。点那个“宽度”按钮，有什么效果呢？

那个宽高 是输入框 分别输入图片的宽度 和   高度

**Comment by wangfupeng1988** [comment]
@PieDi 菜单和工具栏不一样，两个东西。

**Comment by Amanda827** [comment]
> > @Amanda827 光一个截图没看懂啥意思。点那个“宽度”按钮，有什么效果呢？
> 
> 那个宽高 是输入框 分别输入图片的宽度 和 高度
是的，就是可以手动设置上传图片的宽高，这个可以开发吗

**Comment by wangfupeng1988** [comment]
@CaoMengDe-10 这个需求量不大，先待定吧
