### ISSUE TITLE
腾讯文档demo，外层scroll不会随着光标下移一起下移

### ISSUE THREAD

**Issue by Liusiyuan-git** [wangeditor-team/wangEditor#4215]
## 问题描述

在体验demo：腾讯文档时，发现，不断按回车，光标下移，直到光标位置超出屏幕大小，外层的scroll并不会跟着下沉。这就意味着，写文档需要不断手动滑动滚动条才能看见最下面的内容，不符合一般习惯，这个有什么办法解决吗？

## wangEditor 版本

5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

很简单，打开你们的腾讯文档demo，不断按回车让光标下移，直至超出屏幕可视范围即可，观察外层scroll，并不会跟着下移

**Comment by wangfupeng1988** [comment]
复现了，我们有时间看下

**Comment by johnsmith0209** [comment]
+1
PS：如果光标不在可见位置并粘贴内容的话一样不会scroll到可见位置。

**Comment by pb0710** [comment]
+1，编辑内容超出屏幕仍需要手动滚动，比较麻烦。

**Comment by wangfupeng1988** [comment]
这个已经修复，发布了新版本，可等明天（CDN 可能有缓存）试试这个 demo 

https://www.wangeditor.com/demo/like-qq-doc.html

**Comment by Liusiyuan-git** [comment]
请问已经同步到vue的版本了吗

**Comment by Liusiyuan-git** [comment]
@wangfupeng1988  好像vue的版本没有生效哦，请问是这个版本吗：@wangeditor/editor-for-vue: "^5.1.12"

**Comment by wangfupeng1988** [comment]
@Liusiyuan-git 你需要升级 `@wangeditor/editor` 版本即可，和 vue 的没关系

**Comment by Liusiyuan-git** [comment]
@wangfupeng1988 没明白，@wangeditor/editor-for-vue不是 @wangeditor/editor的vue版本么

**Comment by Liusiyuan-git** [comment]
@wangfupeng1988 再请教一下，不能作用到body上的滚动条吗，只能作用到一般的div上？

**Comment by wangfupeng1988** [comment]
> @wangfupeng1988 再请教一下，不能作用到body上的滚动条吗，只能作用到一般的div上？

目前不能，而且一般情况下都有一个 height:100% 的 div 作为容器。很少有直接暴露到 body 上的

**Comment by pb0710** [comment]
发现个问题。首次输入的时候，连续换行光标会跑到页面外。
demo可稳定复现。
https://user-images.githubusercontent.com/43576003/178883918-aad177ee-ebfb-4bc1-9066-103d2e12b9ca.mov

**Comment by wangfupeng1988** [comment]
@pb0710 好，我再继续优化一下。
