### ISSUE TITLE
【官网demo页面】所有子页面无法编辑，编辑器加载失败

### ISSUE THREAD

**Issue by jaluik** [wangeditor-team/wangEditor#4216]
## bug 描述

比如：https://www.wangeditor.com/demo/get-html.html   无法编辑

![image](https://user-images.githubusercontent.com/37829041/168718327-fba959c4-5e31-4d3f-8bb2-2ed360c32268.png)

## 你预期的样子是？

希望可以在示例页面中正常显示编辑器

## 系统和浏览器及版本号

- macOs
- chrome 最新版

**Comment by wangfupeng1988** [comment]
CDN 不稳定。

如要下载 CDN 可看这里的备用地址 https://www.wangeditor.com/v5/installation.html#cdn

如要查看 demo ，可先用这个地址 http://106.12.198.214:8882/main/examples/

**Comment by dhh-chyc** [comment]
修改一下DNS配置吧，可能DNS解析cdn出错了（两个半小时的惨痛教训）

**Comment by jaluik** [comment]
没事我翻墙了。。加了翻墙域名白名单就正常了
