### ISSUE TITLE
在上传图片事件onBeforeUpload中修改了文件的meta信息后，上传是不生效

### ISSUE THREAD

**Issue by hhq0118** [wangeditor-team/wangEditor#4219]
## 问题描述
在上传图片时修改了file.meta中的信息后不生效

*请输入遇到的问题...*

## wangEditor 版本
5.0.1
vue版本2.6.14

*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

在事件onBeforeUpload中修改文件的meta属性，比如file.meta.key = 'xxxxxx'; 然后返回新的file数据，但是在上传文件提交到服务器上时meta.key仍然是空

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
file 对象是浏览器提供的，跟编辑器没啥关系。所以，我怀疑这个问题不是编辑器导致的。

你可以先抛开编辑器，自己弄一个 file 对象，修改一下 meta.key ，然后上传到服务器，试试。
