### ISSUE TITLE
表格删除时会删除单元格

### ISSUE THREAD

**Issue by leidao** [wangeditor-team/wangEditor#4221]
## bug 描述
当表格的单元格内无内容时，从表格外回车，会删除表格的最后一个单元格

## 你预期的样子是？
删除整个表格，而不是删除表格某个单元格

## 系统和浏览器及版本号
谷歌浏览器- 101.0.4951.64（正式版本） (x86_64)

## wangEditor 版本
在官方demo中可以复现

## demo 能否复现该 bug ？
能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

- 步骤一
- 
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/39399843/168833453-76eab1e7-2606-4bbc-a99f-c9a9d93bafc7.png">

- 步骤二
- 
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/39399843/168833594-91756555-9584-447c-a84b-f26fe8323184.png">

- 步骤三

**Comment by wangfupeng1988** [comment]
升级 `@wangeditor/editor` 5.1 版本即可
