### ISSUE TITLE
表格后输入中文回车生成两份文字，删除会报错

### ISSUE THREAD

**Issue by leidao** [wangeditor-team/wangEditor#4222]
## bug 描述

创建一个表格，和表格同行位置指定光标，输入中文回车生成两份文字，删除会报错

## 你预期的样子是？

输入文字正常换行展示，不会出现双份文字

## 系统和浏览器及版本号
谷歌浏览器-101.0.4951.64（正式版本） (x86_64)

## demo 能否复现该 bug ？
能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤
在官方demo中复现

- 步骤一
- 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/39399843/168938098-72e3af2a-f2f1-4d3c-9af8-68f27bf0e9b0.png">

- 步骤二
- 
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/39399843/168938192-29be1d3c-6c02-491d-897f-a573ca9cb80c.png">

- 步骤三
<img width="774" alt="image" src="https://user-images.githubusercontent.com/39399843/168938253-66d21de4-dc46-49a5-b061-90c53d83b002.png">

- 步骤四
- 
<img width="783" alt="image" src="https://user-images.githubusercontent.com/39399843/168938333-74fcee5f-279d-4749-84f7-0088ecf4a547.png">

**Comment by wangfupeng1988** [comment]
升级 `@wangeditor/editor` 5.1 版本，已规避这个问题。
