### ISSUE TITLE
在Vite构建的Vue2项目中 引入失败

### ISSUE THREAD

**Issue by 2383155523** [wangeditor-team/wangEditor#4223]
## 问题描述

在Vite构建的Vue2项目中 引入失败

![报错](https://user-images.githubusercontent.com/58352334/168943141-87806fb0-8ac2-48c9-8f88-6e3ac4d7b510.png)

## wangEditor 版本
    "@wangeditor/editor": "^5.0.1",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- git clone https://gitee.com/like-a-mayfly/vite-vue2-template
- 步骤二
- npm i
- 步骤三
npm run serve

**Comment by liuqh0609** [comment]
链接失效了，是否可以提供一个新链接

**Comment by 2383155523** [comment]
> 链接失效了，是否可以提供一个新链接

已经解决了。。
