### ISSUE TITLE
希望可以支持设置 span contenteditable

### ISSUE THREAD

**Issue by crazy365966834** [wangeditor-team/wangEditor#4224]
## 功能描述

需求是：希望用富文本做一个限制输入的word。仅允许在关键位置输入。我原先想的是通过插入
 `<span contenteditable="true"></span>`的节点，然后获取到Html，去渲染到客户端。
但是，当前V5版本中，如果我设置的html中，有span上标记了 contenteditable=“true”，设置后，再获取的html就丢失该属性了。

比如这样：
`<p>你的名字：<span contenteditable="true">_______________</span></p>`

## 提炼几个功能点

- 设置html，支持定义标签上的 contenteditable 属性
- 
## 可参考的案例
V4 版本是支持设置的。

**Comment by wangfupeng1988** [comment]
v5 版本中需要你自定义扩展这个 elem https://www.wangeditor.com/v5/development.html
