### ISSUE TITLE
视频上传之后的宽高设置

### ISSUE THREAD

**Issue by PieDi** [wangeditor-team/wangEditor#4225]
## 功能描述

建议能否增加像图片一样的宽高设置，不然的话没在编辑器中 我看有宽度450px的设置，正常显示，但是编辑器生成的内容 被发布成页面后，视频就很宽，网页就会左右滑动了

## 提炼几个功能点

- 视频增加宽高设置

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
这个功能正在开发中，如下图

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/9583120/168999575-2ccbc4b6-c228-45ba-8099-4c8874b462f0.png">

**Comment by wangfupeng1988** [comment]
@PieDi 视频尺寸功能开发完了，邀请你来测试 https://github.com/wangeditor-team/wangEditor/issues/4240

**Comment by wangfupeng1988** [comment]
升级 5.1 版本即可 https://www.npmjs.com/package/@wangeditor/editor

**Comment by minkuan** [comment]
@PieDi @wangfupeng1988 增加了下视频上传时百分比宽高设置
<img width="329" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/6381002/78546d6b-2187-4cdc-81f8-a3dfb96ea949">
