### ISSUE TITLE
v5 React项目中没有pasteFilterStyle复制粘贴携带样式，之前v4是有这个功能的

### ISSUE THREAD

**Issue by Crystal1215** [wangeditor-team/wangEditor#4227]
## 复制粘贴携带样式

*v5 React项目中没有pasteFilterStyle复制粘贴携带样式，之前v4是有这个功能的*
## 提炼几个功能点

- 1、word\excel携带样式颜色图片等信息，粘贴到富文本编辑器里就没了
-2、 富文本编辑器里的表格不能选中多行

**Comment by wangfupeng1988** [comment]
v5 中使用 https://www.wangeditor.com/v5/editor-config.html#custompaste

**Comment by a15218378694** [comment]
> ## 复制粘贴携带样式
> _v5 React项目中没有pasteFilterStyle复制粘贴携带样式，之前v4是有这个功能的_
> 
> ## 提炼几个功能点
> * 1、word\excel携带样式颜色图片等信息，粘贴到富文本编辑器里就没了
>   -2、 富文本编辑器里的表格不能选中多行

请问解决了么 ? 我现在要保留样式, 不知道怎么做

**Comment by wangfupeng1988** [comment]
这个已记录，目前尚未解决
