### ISSUE TITLE
onBlur编辑器与按钮同时存在页面上，在编辑器输入完内容直接点击提交，未执行onBlur失去焦点事件。

### ISSUE THREAD

**Issue by maroyfrank** [wangeditor-team/wangEditor#4228]
## 问题描述
![1652862849](https://user-images.githubusercontent.com/97158883/168995228-63f8d2f7-45d1-4eca-a249-96a245b3cfa7.jpg)
*请输入遇到的问题...*
**onBlur编辑器与按钮同时存在页面上，在编辑器输入完内容直接点击提交，未执行onBlur失去焦点事件.但按照正常逻辑，点击按钮后，编辑器就已经失去焦点了，至少原生的js是这样的。**
## wangEditor 版本
![1652863771(1)](https://user-images.githubusercontent.com/97158883/168998380-df9de7d5-6585-4667-91e4-12031f9bdac6.jpg)
*请输入内容……*
![1652863413(1)](https://user-images.githubusercontent.com/97158883/168997143-8ad7b418-628d-42d8-955f-c1d389202ff8.jpg)
![1652864814(1)](https://user-images.githubusercontent.com/97158883/169002305-02394f3b-6e42-49c0-8962-4120ddda8c47.jpg)

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一

<template>
  <div>
    
    <div style="border: 1px solid #ccc;">
        <Toolbar
            style="border-bottom: 1px solid #ccc"
            :editor="editor"
            :defaultConfig="toolbarConfig"
            :mode="mode"
        />
        
        <Editor
            style="height: 500px; overflow-y: hidden;"
            :defaultConfig="editorConfig"
            :mode="mode"
            @onCreated="onCreated"
            @onBlur="getContents"
        />
    </div>
    
    <button @click="btn()">提交</button>
  </div>
</template>
- 步骤二
 /**获取内容 */
        getContents(){
            console.log("编辑器失去焦点了!");
            console.log(this.editor.getHtml());
        },
        /**提交 */
        btn(){
            console.log("按钮被点击了!");
        },
- 步骤三

**Comment by maroyfrank** [comment]
相关代码:
<template>
  <div>
    
    <div style="border: 1px solid #ccc;">
        <Toolbar
            style="border-bottom: 1px solid #ccc"
            :editor="editor"
            :defaultConfig="toolbarConfig"
            :mode="mode"
        />
        
        <Editor
            style="height: 500px; overflow-y: hidden;"
            :defaultConfig="editorConfig"
            :mode="mode"
            @onCreated="onCreated"
            @onBlur="getContents"
        />
    </div>
    
    <button @click="btn()">提交</button>
  </div>
</template>

**Comment by wangfupeng1988** [comment]
再手动执行一下 `editor.blur()` 即可。
