### ISSUE TITLE
vue2 npm引入后，npm run dev 启动错误

### ISSUE THREAD

**Issue by syshenyuan** [wangeditor-team/wangEditor#4229]
Failed to compile with 1 errors                                                                                                                     下午4:38:52

 error  in ./node_modules/@wangeditor/editor/dist/index.esm.js

Module parse failed: Unexpected token (12822:18)
You may need an appropriate loader to handle this file type.
| 
|   const prevLocale = this.locale;
|   this.locale = { ...prevLocale,
|     strings: { ...prevLocale.strings,
|       ...locale.strings

 @ ./node_modules/@wangeditor/editor-for-vue/dist/index.esm.js 1:19-141
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/MyEditor/index.vue
 @ ./src/components/MyEditor/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/operate/systemInformation/index.vue
 @ ./src/views/operate/systemInformation/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8090 webpack/hot/dev-server ./src/main.js

**Comment by wangfupeng1988** [comment]
参考这里 https://github.com/wangeditor-team/wangEditor/issues/4041
