### ISSUE TITLE
在webpack.base.config.js文件里添加了resolve('node_modules/@wangeditor')，还是报Module parse failed: Unexpected token (12822:18) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by fyxiaokeai** [wangeditor-team/wangEditor#4237]
## 问题描述

在webpack.base.config.js文件里添加了resolve('node_modules/@wangeditor')，还是报Module parse failed: Unexpected token (12822:18) You may need an appropriate loader to handle this file type.

## wangEditor 版本

    "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-vue": "^1.0.1",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- package.json
{
  "name": "ares-recruit",
  "version": "1.3.1",
  "description": "a management bases on iview",
  "scripts": {
    "init": "webpack --progress --config build/webpack.dev.config.js",
    "dev": "webpack-dev-server --content-base ./ --open --inline --hot --compress --config build/webpack.dev.config.js",
    "build": "webpack --progress --hide-modules --config build/webpack.prod.config.js",
    "lint": "eslint --fix --ext .js,.vue src",
    "test": "npm run lint"
  },
  "author": "ares",
  "license": "MIT",
  "dependencies": {
    "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-vue": "^1.0.1",
    "area-data": "^5.0.6",
    "axios": "^0.18.0",
    "bcryptjs": "^2.4.3",
    "clipboard": "^2.0.4",
    "countup": "^1.8.2",
    "cropperjs": "^1.2.2",
    "crypto-js": "^3.1.9-1",
    "echarts": "^4.1.0",
    "element-ui": "^2.13.1",
    "html2canvas": "^1.0.0-rc.5",
    "iview-area": "^1.5.16",
    "jquery": "^3.3.1",
    "js-cookie": "^2.2.0",
    "js-file-download": "^0.4.4",
    "jsbarcode": "^3.11.3",
    "jspdf": "^2.5.1",
    "moment": "^2.22.2",
    "portfinder": "^1.0.15",
    "qs": "^6.5.2",
    "rasterizehtml": "^1.2.4",
    "simplemde": "^1.11.2",
    "sortablejs": "^1.7.0",
    "tinymce": "^4.9.4",
    "transformation-matrix": "^1.15.1",
    "tree-vue-component": "^5.4.0",
    "umy-ui": "^1.1.6",
    "ve-charts": "^0.7.4",
    "view-design": "^4.4.0",
    "vue": "^2.6.10",
    "vue-clipboard2": "^0.3.1",
    "vue-layer": "^0.9.7",
    "vue-password": "^1.1.2",
    "vue-router": "^3.0.1",
    "vue-socket.io": "^3.0.7",
    "vue-video-player": "^5.0.2",
    "vue-virtual-scroller": "^0.10.6",
    "vuedraggable": "^2.16.0",
    "vuex": "^3.0.1",
    "vux": "^2.9.1",
    "wangeditor": "^3.1.1",
    "xlsx": "^0.11.17"
  },
  "devDependencies": {
    "@babel/eslint-plugin": "^7.14.5",
    "autoprefixer-loader": "^3.2.0",
    "babel": "^6.23.0",
    "babel-core": "^6.26.1",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^7.1.5",
    "babel-plugin-component": "^1.1.1",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.12.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-stage-3": "^6.24.1",
    "babel-runtime": "^6.11.6",
    "clean-webpack-plugin": "^0.1.17",
    "compression-webpack-plugin": "^1.1.11",
    "copy-webpack-plugin": "^4.3.1",
    "css-hot-loader": "^1.3.5",
    "css-loader": "^0.28.8",
    "ejs-loader": "^0.3.0",
    "es6-promise": "^4.2.4",
    "eslint": "^4.15.0",
    "eslint-config-google": "^0.9.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-html": "^4.0.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.6",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "generate-asset-webpack-plugin": "^0.3.0",
    "happypack": "^4.0.0",
    "html-loader": "^0.5.4",
    "html-webpack-plugin": "^2.28.0",
    "less": "^2.7.3",
    "less-loader": "^4.1.0",
    "semver": "^5.4.1",
    "style-loader": "^0.19.1",
    "unsupported": "^1.1.0",
    "url-loader": "^0.6.2",
    "vue-hot-reload-api": "^2.2.4",
    "vue-html-loader": "^1.2.3",
    "vue-i18n": "^5.0.3",
    "vue-loader": "^12.2.2",
    "vue-style-loader": "^3.0.3",
    "vue-template-compiler": "^2.5.13",
    "vux-loader": "^1.2.9",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.10.1",
    "webpack-merge": "^4.1.1",
    "webpack-uglify-parallel": "^0.1.4",
    "yaml-loader": "^0.5.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

- webpack.base.config.js
const path = require('path');
const os = require('os');
const utils = require('./utils');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HappyPack = require('happypack');
const CompressionPlugin = require("compression-webpack-plugin");
const vueLoaderConfig = require('./vue-loader.conf');
const vuxLoader = require('vux-loader');

var happyThreadPool = HappyPack.ThreadPool({ size: os.cpus().length });
function resolve (dir) {
    return path.join(__dirname, dir);
}
const webpackConfig = {
    entry() {
        // 初始化入口配置
        const entry={
            main: '@/main',
            app: ["babel-polyfill", "./src/main.js"],
            // 'vender-base': '@/vendors/vendors.base.js',
            // 'vender-exten': '@/vendors/vendors.exten.js',
        };
        // // // 所有模块的列表
        // const moduleToBuild = require('./module-conf').getModuleToBuild() || [];
        // // 根据传入的待打包目录名称，构建多入口配置
        // for (let module of moduleToBuild) {
        //     entry[module] = `./src/modules/${module}/main.js`
        // }
        return entry
    },
    output: {
        path: path.resolve(__dirname, '../dist'),
        filename: 'js/[name].js',
        publicPath: '.',
    },
    module: {
        rules: [
            {
                exclude: [
                    path.resolve(__dirname, '../src/modules/hcp-recruit-mobile')
                ]
            },
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: vueLoaderConfig,
                exclude: /node_modules\/(?!(autotrack|dom-utils))|vendor\.dll\.js/
            },
            {
                test: /iview\/.*?js$/,
                loader: 'happypack/loader?id=happybabel',
                exclude: /node_modules/,
                include: [resolve('src'),
                    resolve('test'),
                    resolve('/node_modules/iview/src'),
                    resolve('/node_modules/iview/packages')]
            },

            {
                test: /\.js[x]?$/,
                include: [resolve('src')],
                exclude: /node_modules/,
                loader: 'happypack/loader?id=happybabel'
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                include: [
                    resolve('src'), resolve('test'),
                    resolve('node_modules/_iview@2.7.3@iview/'),
                    resolve('node_modules/_vue-confirm@1.1.1@vue-confirm'),
                    path.resolve(__dirname,'node_modules/socket.io-client'),
                    path.resolve(__dirname,'node_modules/socket.io-parser'),
                    path.resolve(__dirname,'node_modules/vue-socket.io'),
                    resolve('node_modules/vue-socket.io'),
                    resolve('node_modules/@wangeditor')
                ]
            },

            {
                test: /\.js$/,
                loader: 'happypack/loader?id=happybabel',
                include: [resolve('../build'),
                    resolve('../src'),
                    resolve('../node_modules/socket.io-client'),
                    resolve('../node_modules/socket.io-parser'),
                    resolve('../node_modules/vue-socket.io')
                ]

            },
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader?minimize', 'autoprefixer-loader'],
                    fallback: 'style-loader',
                }),
            },
            {
                test: /\.less$/,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader?minimize','autoprefixer-loader', 'less-loader'],
                    fallback: 'style-loader',

                }),
            },
            {
                test: /\.(png|jpe?g|gif|svg|ico)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: utils.assetsPath('img/[name].[hash:7].[ext]')
                }
            },
            {
                test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
                loader: 'url-loader',
                options: {
                    limit: 10000,
                    name: utils.assetsPath('fonts/[name].[ext]')
                }
            },
            {
                test: /\.(html|tpl)$/,
                loader: 'html-loader'
            }
        ]
    },

    plugins: [
        new HappyPack({
            id: 'happybabel',
            loaders: ['babel-loader'],
            threadPool: happyThreadPool,
            verbose: true,
        }),
        new ExtractTextPlugin({filename:  (getPath) => {
                return getPath('css/[name].css').replace('css/js', 'css');
            },
            allChunks: true}),

        new CompressionPlugin ({
            asset: '[path].gz[query]',
            algorithm: 'gzip',
            /* test: new RegExp(
                 '\\.(' +
                 config.build.productionGzipExtensions.join('|') +
                 ')$'
             ),*/
            threshold: 10240,
            // deleteOriginalAssets:true, //删除源文件，不建议
            minRatio: 0.8
        })
    ],
    resolve: {
        extensions: ['.js', '.sass', '.jsx', '.jpg', '.jpeg', '.gif', '.png', '.ico', 'less','.vue','.json'],
        // exclude: ["../src/modules/hcp-recruit-mobile"],
        alias: {
            'vue': 'vue/dist/vue.esm.js',
            '@': resolve('../src')
        }
    }
};
// module.exports = originalConfig;
// const webpackConfig = originalConfig
module.exports = vuxLoader.merge(webpackConfig, {
    plugins: ['vux-ui']
});

**Comment by wangfupeng1988** [comment]
统一在这里讨论吧 https://github.com/wangeditor-team/wangEditor/issues/4041
