### ISSUE TITLE
复制word带标签的内容有时会复制2遍

### ISSUE THREAD

**Issue by F-ch1** [wangeditor-team/wangEditor#4239]
word内容
![image](https://user-images.githubusercontent.com/74720927/169456393-71043397-b4fe-4ae3-9af8-32de548cc39b.png)
复制后
![image](https://user-images.githubusercontent.com/74720927/169456599-ef316e39-565f-404e-b867-db0d5f520005.png)

**Comment by wangfupeng1988** [comment]
word 的问题，我后面再专门看吧，近期没时间弄。

你可以先通过 customPaste 自定义处理 https://www.wangeditor.com/v5/editor-config.html#custompaste
