### ISSUE TITLE
test: 5.1 新功能

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#4240]
## 背景

近期开发了部分新功能，测试通过之后将发布到 5.1 版本中，现邀请你来测试。

### 新增 “换行”菜单

测试地址 http://106.12.198.214:8882/feature-next/examples/default-mode.html

针对：代码块、分割线、表格、视频
点击“换行”菜单（如下图），会在上面新插入一个空行，并光标定位到空行。

<img width="964" alt="image" src="https://user-images.githubusercontent.com/9583120/169463303-d8e5a3ca-239b-4162-b2fa-6d5b157f74f7.png">

###  新增 `setHtml` API

测试地址 http://106.12.198.214:8882/feature-next/examples/parse-html.html

拿到 wangEditor 输出的任意 HTML （即 `editor.getHtml()` 返回值），然后执行 `editor.setHtml('xxx')` 可对编辑器**重新设置**内容。 

可使用 http://106.12.198.214:8882/feature-next/examples/parse-html.html 其中 `setHtml` 按钮进行测试，并查看页面源代码。

注意，编辑器 focus、blur、disabled 都可以使用该 API 。

### 修改视频尺寸

测试地址 http://106.12.198.214:8882/feature-next/examples/upload-video.html

插入、上传一个视频，选中视频，可点击“修改尺寸”菜单（如下图），点击弹出 modal 可修改视频尺寸

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/9583120/169464038-72292946-c72d-4135-b5bc-fbd4a9c40890.png">

另外，视频尺寸变化之后，在控制台获取 `editor.getHtml()` ，然后拷贝粘贴到 http://106.12.198.214:8882/feature-next/examples/parse-html.html ，点击“创建编辑器”按钮，可正常回显视频（尺寸要一致）

### 拖拽表格列宽

先使用 http://localhost:8881/examples/default-mode.html 来测试：
- 新建表格，鼠标放在第一行任意单元格的右侧，可拖拽该列的宽度 （如下图）
- 表格悬浮菜单中 “表头” 和 “自适应宽度” 能正常使用
- 编辑器中表格变化，能实时同步到下面的展示区域

<img width="808" alt="image" src="https://user-images.githubusercontent.com/9583120/169465807-9005d6ad-b948-446b-bf75-a507c4a25b5f.png">

另外，表格宽度变化之后，在控制台获取 `editor.getHtml()` ，然后拷贝粘贴到 http://106.12.198.214:8882/feature-next/examples/parse-html.html ，点击“创建编辑器”按钮，可正常回显表格（列宽要一致）

## 浏览器兼容性

- Chrome
- Firefox
- Edge
- Windows QQ 浏览器

## 测试产出

测试有问题，可直接回复到下面。格式如：

- 功能：xxx
- 操作系统和浏览器版本：xxx
- 复现步骤（可贴截图和代码）
    - aaa
    - bbb
    - ccc

**Comment by PieDi** [comment]
老哥，我看了 视频和图片均是独占一行，暂不支持图文环绕对吧，既然是独占一行，那么建议视频和图片是否都可以设置百分比和具体的数值呢？这样是否更友好一些？很感谢老哥的辛苦支持，我点了上传正常，后续我觉得是否可以优化为 媒体就行了。图片、视频、音频，都是常见的多媒体文件

**Comment by wangfupeng1988** [comment]
@PieDi 感谢反馈，感觉你提的建议非常好~

**Comment by wangfupeng1988** [comment]
已发布 5.1

**Comment by nwdsl1982** [comment]
大佬，视频的尺寸设置只接受数字吗，发现设置为100%会自动变成100，实际在H5显示视频的场景很需要设置为100%呀

**Comment by wangfupeng1988** [comment]
@nwdsl1982 目前只能接受数字。

你再去提交一个新 issue 吧，我后面对此优化一下。

**Comment by nwdsl1982** [comment]
> @nwdsl1982 目前只能接受数字。
> 
> 你再去提交一个新 issue 吧，我后面对此优化一下。

谢谢大佬，后来发现这个问题在H5端通过样式统一处理也可以解决

**Comment by wangfupeng1988** [comment]
> 大佬，视频的尺寸设置只接受数字吗，发现设置为100%会自动变成100，实际在H5显示视频的场景很需要设置为100%呀

@nwdsl1982 事情有变故，看这里 https://github.com/wangeditor-team/wangEditor/issues/4410

**Comment by tangyouwo** [comment]
可以在编辑页面加入
#editor-text-area :deep(video) {
    width: 100%;
}
，可使video样式显示为百分比,img去掉左右。
同时在展示的页面，也在对应的渲染html的地方，写上css
#渲染div的id:deep(video) {
    width: 100%;
}
