### ISSUE TITLE
上传图片

### ISSUE THREAD

**Issue by ANRUN7** [wangeditor-team/wangEditor#4241]
## 问题描述
图片上传问题
*请输入遇到的问题...*
图片上传问题
## wangEditor 版本
5.0.1
*请输入内容……*
5.0.1
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
上传图片在本地跑上传图片可以，到线上就报错
chunk-0b78a822.60feec60.js:18 [Uppy] [15:17:09] u.upload.addEventListener is not a function
![421BDCC4-5A6A-4171-9BCA-E00057EFAE7B](https://user-images.githubusercontent.com/83338317/169474681-64a0dcfb-5398-4c88-89ef-078b57bd1098.png)
 @ chunUncaught (in promise) TypeError: u.upload.addEventListener is not a function
- 步骤一
- 步骤二
- 步骤三

**Comment by ANRUN7** [comment]
![image](https://user-images.githubusercontent.com/83338317/169475274-291ef1c6-dd63-436e-a5f2-cacb568b4bee.png)

**Comment by wangfupeng1988** [comment]
这个问题本地无法复现，我也没办法帮你排查。

**Comment by zyygh12** [comment]
图片上传后，页面自动刷新，这个问题如何解决？谢谢

**Comment by wangfupeng1988** [comment]
@zyygh12 重新提交 issue ，描述清楚复现步骤。

**Comment by tfcp** [comment]
我遇到和他一摸一样的的问题 本地可以 上传线上就报错 5.1.1

**Comment by panyongwei** [comment]
检查是否引入了mock，如果引入了mock的话会把默认的XMLHttpRequest覆盖掉，导致出现该问题

**Comment by taixiangfei** [comment]
> 检查是否引入了mock，如果引入了mock的话会把默认的XMLHttpRequest覆盖掉，导致出现该问题

维护老项目，突然出现这个问题，测试环境没问题，线上居然出问题，懵逼！！！
经查发现原来mock在生产环境一直在使用，估计是之前的人想写!==写错了。。。
`if (process.env.NODE_ENV === 'production') {
  const {
    mockXHR
  } = require('../mock')
  mockXHR()
}`

**Comment by luolin2611** [comment]
这个问题这么久了，还在好心酸啊。

**Comment by luolin2611** [comment]
> 检查是否引入了mock，如果引入了mock的话会把默认的XMLHttpRequest覆盖掉，导致出现该问题

不给解决方案，差评

**Comment by szhang6** [comment]
> > 检查是否引入了mock，如果引入了mock的话会把默认的XMLHttpRequest覆盖掉，导致出现该问题
> 
> 不给解决方案，差评

在项目的 main.js 中，注释掉使用 mock 对象的代码
