### ISSUE TITLE
可以增加 预览功能吗？  pc端可以预览移动端。

### ISSUE THREAD

**Issue by craftlkhugetree** [wangeditor-team/wangEditor#4242]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
预览需要自己写，通过 `editor.getHtml()` 获取 HTML 内容，然后自己实现预览即可。

**Comment by craftlkhugetree** [comment]
谢谢

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月20日 17:30
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [wangeditor-team/wangEditor] 可以增加 预览功能吗？ pc端可以预览移动端。 (Issue #4242)


预览需要自己写，通过 editor.getHtml() 获取 HTML 内容，然后自己实现预览即可。

―
