### ISSUE TITLE
react项目，vite环境，react18, 复制的demo跑不起来

### ISSUE THREAD

**Issue by qw789** [wangeditor-team/wangEditor#4243]
![image](https://user-images.githubusercontent.com/20290766/169488454-74c37f09-d156-49d8-9fd4-837abe311e07.png)

**Comment by hahaaha** [comment]
@qw789 可以先`npm i @babel/runtime-corejs3`解决下，后面会对这种情况进行处理的

**Comment by qw789** [comment]
> @qw789 可以先`npm i @babel/runtime-corejs3`解决下，后面会对这种情况进行处理的

我试试

**Comment by qw789** [comment]
> @qw789 可以先`npm i @babel/runtime-corejs3`解决下，后面会对这种情况进行处理的

临时办法有效
