### ISSUE TITLE
样式设置问题

### ISSUE THREAD

**Issue by Corgis** [wangeditor-team/wangEditor#4244]
我在图片的hoverbarKeys 扩展了一个菜单 旨在自己给图片插入一些样式
![image](https://user-images.githubusercontent.com/13865529/169500675-deee0f6f-b1b3-4478-a087-5dc6926135c4.png)
但结果来看 只有 width 生效了 其他的都没有效果
![image](https://user-images.githubusercontent.com/13865529/169500820-2f959fca-d5a6-46f9-bd89-b7fcf442f987.png)
![image](https://user-images.githubusercontent.com/13865529/169500864-d5d44e4b-201e-4ddc-84a4-f51c019d2bb2.png)

**Comment by wangfupeng1988** [comment]
因为其他的目前都不支持。

可以看这里 https://www.wangeditor.com/v5/node-define.html#%E5%90%84%E7%A7%8D%E8%8A%82%E7%82%B9%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84 ，图片的属性定义。

**Comment by Corgis** [comment]
> 因为其他的目前都不支持。
> 
> 可以看这里 https://www.wangeditor.com/v5/node-define.html#%E5%90%84%E7%A7%8D%E8%8A%82%E7%82%B9%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84 ，图片的属性定义。

感觉您的开源项目，是个很好的项目，我的本意是希望通过给图片自定义一个hoverbarKeys，然后可以实现一些自定义样式的，比如边框啊 间距什么的，那按照您的意思是 目前这种思路不可行么？还是有其他的办法或者api可以实现，十分感谢您

**Comment by Corgis** [comment]
> 因为其他的目前都不支持。
> 
> 可以看这里 https://www.wangeditor.com/v5/node-define.html#%E5%90%84%E7%A7%8D%E8%8A%82%E7%82%B9%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84 ，图片的属性定义。

另外再打扰下，想问下setHtml对样式的支持情况是什么，有列出详细支持情况么？例如您的例子中 我看到<p style="padding-left: 32px;">增加缩进 indent 1</p>这段是可以解析的，但我设置 padding-top:12px; 就无法生效，挺迷惑的，打扰作者百忙中抽空解答 十分感谢

**Comment by wangfupeng1988** [comment]
> 实现一些自定义样式的，比如边框啊 间距什么的

自定义样式，对于编辑器来说增加 image 类型的属性。增加了属性，那相应的其他东西就都得重写，具体参考 https://www.wangeditor.com/v5/development.html 。所以整个过程是比较麻烦的。

**Comment by wangfupeng1988** [comment]
> 想问下setHtml对样式的支持情况是什么，有列出详细支持情况么？

你可以操作编辑器的各个功能，支持的样式，全部都能体现到编辑器的功能里。例如你说的 `padding-top` ，在编辑器上根本就没这个功能，所以也不会默认支持。

**Comment by Corgis** [comment]
恩 好的十分感谢，那我知道能支持什么属性了，感谢答复，另外看了你的视频，说的挺清楚，我看看关于自定义扩展新功能这块能否有什么新思路。

**Comment by hhy1234567** [comment]
> 我在图片的hoverbarKeys 扩展了一个菜单 旨在自己给图片插入一些样式 ![image](https://user-images.githubusercontent.com/13865529/169500675-deee0f6f-b1b3-4478-a087-5dc6926135c4.png) 但结果来看 只有 width 生效了 其他的都没有效果 ![image](https://user-images.githubusercontent.com/13865529/169500820-2f959fca-d5a6-46f9-bd89-b7fcf442f987.png) ![image](https://user-images.githubusercontent.com/13865529/169500864-d5d44e4b-201e-4ddc-84a4-f51c019d2bb2.png)

大佬你那是怎么实现添加宽度的呀我这现在需求只需要添加一个宽度就行了
