### ISSUE TITLE
非BUG，editor.cmd.do()插入图片和视频，tooltip不显示

### ISSUE THREAD

**Issue by ZPLSSSTD** [wangeditor-team/wangEditor#4245]
## 问题描述
这个倒不是BUG，不清楚V5逻辑是如何。因为项目需要，使用了V4版本的editor。在V4中，如果在editor.config.menus中去除image.video两个菜单，会导致跟着两个菜单相关连的tooltip和功能无法被初始化（例如点击图片出现百分比控制和拖拽控制），然后使用editor.cmd.do自定义插入图片和视频后。就无法在对插入的图片进行editor自身的tooltip操作。如果V5也是和V4一样的逻辑，建议作者把这类的功能初始化给独立出来，而不是跟菜单显示隐藏关联在一起。
## wangEditor 版本
wangeditor 4.7.9

## 是否查阅了文档 ？
有
## 最小成本的复现步骤
- 步骤一
- editor.config.menus中去掉image，和video两个菜单
- 步骤二
- 使用editor.cmd.do('insertHTML', '')
- 步骤三
- 在编辑器中点击步骤二添加的video或者image会发现tooltip无法显示，包括拖拽功能也消失。

**Comment by wangfupeng1988** [comment]
v5 发布了，v4 没有精力维护了。

我们都业余维护，精力不够，还请体谅~
