### ISSUE TITLE
是否可以加入打印功能呢

### ISSUE THREAD

**Issue by iMaxSys** [wangeditor-team/wangEditor#4246]
打印应该是一个很常用的功能，是否能在下一版本中加入呢

**Comment by wangfupeng1988** [comment]
目前尚无该计划。

如果你需啊，自己扩展一个菜单 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E8%8F%9C%E5%8D%95 即可。

**Comment by Lonely-lie** [comment]
求大佬加入这个功能  这个功能需求很大

**Comment by cycleccc** [comment]
> 求大佬加入这个功能 这个功能需求很大

指的是window的ctrl+p这种输出pdf类似的吗

**Comment by Lonely-lie** [comment]
对的 就是这个功能 编辑完 我可以打印出来

**Comment by Lonely-lie** [comment]
> > 求大佬加入这个功能 这个功能需求很大
> 
> 指的是window的ctrl+p这种输出pdf类似的吗

对 是这种 主要是想用这个实现审批中的表单打印

**Comment by cycleccc** [comment]
> > > 求大佬加入这个功能 这个功能需求很大
> > 
> > 
> > 指的是window的ctrl+p这种输出pdf类似的吗
> 
> 对 是这种 主要是想用这个实现审批中的表单打印

这个确实没必要加到wangEditor包里的，白白增加了包体积，完全可以通过扩展菜单的方式来实现的，你的意思是不太懂怎么扩展菜单吗，wangEditor有文档以及对应的GitHub demo 仓库可以查看的

**Comment by Chendamao** [comment]
现在是从富文本获取的HTML打印的时候，样式就乱了

**Comment by cycleccc** [comment]
> 现在是从富文本获取的HTML打印的时候，样式就乱了

样式是可以自定义的，输出出来的 HTML 样式很好改。打印的插件也很容易实现。
