### ISSUE TITLE
.net mvc 使用最新5版本的使用问题

### ISSUE THREAD

**Issue by 980545410** [wangeditor-team/wangEditor#4247]
## 问题描述
.net mvc   编辑框赋值的问题
*请输入遇到的问题...*
我这边是用的。net mvc   以前是这样给编辑框赋值的  可以支持
 
                    <div id="edit_Text1" style="border: 1px solid #E5E5E5; width:1100px; "></div>
                    <div id="edit_Text2" style="height:1200px; width:1100px;  border: 1px solid #E5E5E5;"><p>@(new HtmlString(Data.infohtml))</p></div>
但是我想用最新版本的，这样赋值好像无法生成
## wangEditor 版本

*请输入内容……*
我这边是用的。net mvc   以前是这样给编辑框赋值的  可以支持
 
                    <div id="edit_Text1" style="border: 1px solid #E5E5E5; width:1100px; "></div>
                    <div id="edit_Text2" style="height:1200px; width:1100px;  border: 1px solid #E5E5E5;"><p>@(new HtmlString(Data.infohtml))</p></div>
但是我想用最新版本的，这样赋值好像无法生成
## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
是
*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- <div id="edit_Text1" style="border: 1px solid #E5E5E5; width:1100px; "></div>
                    <div id="edit_Text2" style="height:1200px; width:1100px;  border: 1px solid #E5E5E5;"><p>@(new HtmlString(Data.infohtml))</p></div>
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这跟是不是 .net 没关系。

先看看文档吧 https://www.wangeditor.com/v5/content.html#%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AE%B9
