### ISSUE TITLE
关于编辑器加载数据库内容的问题

### ISSUE THREAD

**Issue by ssy189** [wangeditor-team/wangEditor#4250]
数据库内容为：&lt;p&gt;55555&lt;/p&gt;22222
wangeditor4 可以正常加载 55555 和 22222
wangeditor5 则只能成功加载 55555 ，而 22222 在编辑器内是不显示的。但是通过 editor.getHtml() 是可以获取到 22222 的内容。

即：如果数据库的文本内容，不被html标签包裹，是不被 wangeditor5 识别的。但是该问题在 wangeditor4 中并不存在。
希望官方能够改进。

**Comment by wangfupeng1988** [comment]
> 不被html标签包裹

v5 不在支持这种不规范的格式。

另，还想问下，像你提供的 `<p>55555</p>22222` 这种格式，是从哪里产出的呢？

**Comment by ssy189** [comment]
另，还想问下，像你提供的 <p>55555</p>22222 这种格式，是从哪里产出的呢？




答：




采集，我平时会从财经网站上采集过来一些上市公司的基本材料。

采集过来的内容部分内容会只有一句文字。然后直接就写入数据库了。

另外有时候，直接也会手动直接往数据库写入一些没有html标签的词语。




所有，并不是写入数据库的内容都是从wangeditor编辑器产生，之后写入数据库的。

而可能是数据库已经有的内容，但是我需要 wangeditor 来进行后期编辑。 













在 2022-05-22 20:37:50，"王福朋" ***@***.***> 写道：

不被html标签包裹

v5 不在支持这种不规范的格式。

另，还想问下，像你提供的 <p>55555</p>22222 这种格式，是从哪里产出的呢？

**Comment by wangfupeng1988** [comment]
> 所有，并不是写入数据库的内容都是从wangeditor编辑器产生，之后写入数据库的。
> 而可能是数据库已经有的内容，但是我需要 wangeditor 来进行后期编辑。

那你可不仅仅是 `<p>55555</p>22222 ` 这种格式啊，还可能有其他的自定义的 HTML 格式，这个 wangEditor 无法全部解析。

**Comment by ssy189** [comment]
是的，不可能全部都支持各种不标准的格式。


但是，我感觉最低目标，应该需要把内容显示出来吧。 格式可以不支持。但是内容不显示是不是不合适？


但是现在内容都不显示，我感觉应该是个bug。













在 2022-05-23 12:35:51，"王福朋" ***@***.***> 写道：

所有，并不是写入数据库的内容都是从wangeditor编辑器产生，之后写入数据库的。
而可能是数据库已经有的内容，但是我需要 wangeditor 来进行后期编辑。

那你可不仅仅是 <p>55555</p>22222 这种格式啊，还可能有其他的自定义的 HTML 格式，这个 wangEditor 无法全部解析。
