### ISSUE TITLE
建议新增一个formula公式插件视频

### ISSUE THREAD

**Issue by whxzjxx** [wangeditor-team/wangEditor#4251]
建议新增一个formula公式插件视频，谢谢！

**Comment by wangfupeng1988** [comment]
第一，看文档 https://github.com/wangeditor-team/wangEditor-plugin-formula

第二，参考这个 demo https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-formula.html

**Comment by xaigogo** [comment]
感谢分享，参考上述文档和公式，我使用Katex方式渲染公式，

<span data-w-e-type="formula" data-w-e-is-void data-w-e-is-inline data-value="c = \\sum\\sqrt{a^2 + b^2}"></span>

katex.render($(span[data-w-e-type="formula"]).data('value'),  span[data-w-e-type="formula"]);

在创建模式下，编辑框创建(create)内容并提交，在detail页面上，可正常显示渲染后的公式。

但在修改模式下，编辑框(update)内容时，从数据库回填之后，在编辑框内 \\sum  \\sqrt 等被解析成了字符串，而不是Σ 和 根号！

目前没法解决，不知道错在哪，请问下有无  `公式内容从数据库回填再编辑再渲染` 的demo呢？

感谢！

**Comment by whxzjxx** [comment]
但在修改模式下，编辑框(update)内容时，从数据库回填之后，在编辑框内 \sum  \sqrt 等被解析成了字符串，而不是Σ 和 根号！
 
目前没法解决，不知道错在哪，请问下有无  公式内容从数据库回填再编辑再渲染 的demo呢？
 
因为把第一个“\”当成转义字符了，所以无法生成\\sum\\sqrt了。

我觉得研究一下wangeditor v5使用 kityformula比较好。
