### ISSUE TITLE
v5 如何关闭工具栏的提示

### ISSUE THREAD

**Issue by zfjhui** [wangeditor-team/wangEditor#4252]
v5 如何关闭工具栏的提示
![image](https://user-images.githubusercontent.com/40257170/169727273-74152581-e6bd-4bd7-8a2c-dd2e1c1b0150.png)

**Comment by wangfupeng1988** [comment]
目前不能关闭。

为啥需要关闭呢？

**Comment by zfjhui** [comment]
与页面场景不搭,图标本身已经可以体现用途,加了hover 有些多余

**Comment by wangfupeng1988** [comment]
目前没有其他人提这个需求，所以暂时先不开发。照顾大部分用户的需求和学习成本。

**Comment by wangfupeng1988** [comment]
对了，你可以自己通过 CSS 来隐藏掉工具栏。

找到所有 css class 是 `w-e-menu-tooltip-v5` 的 DOM 节点，然后把 `w-e-menu-tooltip-v5` 这个 css class 移除掉。
