### ISSUE TITLE
作为聊天输入框，enter发送的时候，怎么取消enter 换行的默认事件呢

### ISSUE THREAD

**Issue by lyy199212** [wangeditor-team/wangEditor#4254]
## bug 描述

enter发送后，清除编辑框，但是仍然有空行

## 你预期的样子是？

enter发送后，清除编辑框后编辑框为空

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

5.0.1 

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这个需要你自定义扩展功能。

文档参考 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E6%8F%92%E4%BB%B6 

代码逻辑参考 https://github.com/wangeditor-team/wangEditor-plugin-ctrl-enter/blob/main/src/module/plugin.ts

**Comment by lyy199212** [comment]
在react里面怎么注册呢？ 我在useeffect里面在editor为null时注册也不好使呢；
`  useEffect(() => {
    if(!editor){
      console.log('注册！！！！');
      
      Boot.registerModule(ctrlEnterModule)
    }
   

    handleEnter();
    return () => {
      if (editor == null) return;
      editor.destroy();
      setEditor(null);
    };
  }, [editor]);`

**Comment by wangfupeng1988** [comment]
不要在 useEffect 中注册，在组件函数外面注册。

**Comment by lyy199212** [comment]
嗯 是的 试了下可以的 谢谢～

**Comment by zhang-lq** [comment]
这个注册一次，是所有的组件都受影响吗？
