### ISSUE TITLE
加粗文本后面选择其他文本再输入文字会有两个内容被添加

### ISSUE THREAD

**Issue by cyh401** [wangeditor-team/wangEditor#4256]
## bug 描述

*在存在加粗的文本里面，选中加粗文本后后面的文字，再输入文字，会再加粗文字后面也有你后输入的文字且被加粗*

## 你预期的样子是？

*仅在输入的地方正常输入，不要有两个内容被添加*

## 系统和浏览器及版本号

- windows10
- google 101.0.4951.67

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
  输入文本“1234567890”
- 步骤二
  把“23”加粗
- 步骤三
 选中“67”
- 步骤四
  输入文字"是的"
- 步骤五
  结果出现"123是的45是的890"，其中前面的“123是的“被加粗

**Comment by cyh401** [comment]
还有类似的一个问题，不知道是不是一个原因导致的
步骤一
输入文本“1234567890”
步骤二
把“123”加粗
步骤三
删除“45”
步骤四
输入文字"是的"
步骤五
结果出现"123是的是的67890"，其中前面的“123是的“被加粗

**Comment by Jinxishihenian** [comment]
> 还有一个类似的问题，不知道不是一个导致的 步骤一 输入文本“1234567890” 步骤二 把“123”加粗 步骤三 删除“45” 步骤四 输入的原因“是的” 步骤五 结果出现“123是的67890”，前面的“123是的”被加粗

按照你的步骤我也复现了该bug

**Comment by wangfupeng1988** [comment]
代码已合并，待发布

**Comment by wangfupeng1988** [comment]
已发布，更新最新版本 https://www.npmjs.com/package/@wangeditor/editor
