### ISSUE TITLE
上传图片成功后，触发了onProgress事件，但是没有触发onSuccess事件

### ISSUE THREAD

**Issue by ceo-github** [wangeditor-team/wangEditor#4257]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本
"@wangeditor/editor": "^5.0.1",
  "@wangeditor/editor-for-vue": "^1.0.1",

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

`
created() {
		const { editorConfig } = this;
		editorConfig.MENU_CONF["uploadImage"] = {
			fieldName: "file",
			server: "/operation/openresty/uploadfile",
			// 单个文件的最大体积限制
			maxFileSize: 10 * 1024 * 1024, // 10M
			// 最多可上传几个文件，默认为 100
			maxNumberOfFiles: 1,
			// 选择文件时的类型限制，默认为 ['image/*'] 。如不想限制，则设置为 []
			allowedFileTypes: ["image/*"],
			headers: {
				authorization: "1111",
			},
			// 自定义插入图片
			customInsert(res, insertFn) {
				// 从 res 中找到 url alt href ，然后插图图片   insertFn(url, alt, href);
				const {
					result: { downloadUrl: url, fileName: alt },
				} = res;
				insertFn(url, alt);
			},
			// 上传之前触发
			onBeforeUpload(file) {
				// file 选中的文件，格式如 { key: file }
				return file;
			},
			// 上传进度的回调函数
			onProgress(progress) {
				// progress 是 0-100 的数字
				console.log("progress", progress);
			},
			// 单个文件上传成功之后
			onSuccess(file, res) {
                                console.log(898989)
				console.log(`${file.name} 上传成功`, res);
			},
			// 单个文件上传失败
			onFailed(file, res) {
				console.log(`${file.name} 上传失败`, res);
			},
			// 上传错误，或者触发 timeout 超时
			onError(file, err, res) {
				console.log(`${file.name} 上传出错`, err, res);
			},
		};
`

**Comment by ceo-github** [comment]
![image](https://user-images.githubusercontent.com/66871673/169942941-75387612-7cfb-4c16-b7bc-ff30b0620d1e.png)

**Comment by wangfupeng1988** [comment]
参考这个 demo http://106.12.198.214:8882/main/examples/upload-image.html 
触发了 onSuccess
