### ISSUE TITLE
代码块格式怎么处理

### ISSUE THREAD

**Issue by ghd133** [wangeditor-team/wangEditor#4258]
## 问题描述

粘贴代码，再格式化后，输出的html空格和换行都没了

## wangEditor 版本

5.0

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by ghd133** [comment]
![$~BV{%9$S8JZS7NGIW$TWAB](https://user-images.githubusercontent.com/74580268/169943621-5c946954-2caf-41a7-9045-d14f3f3849ed.png)
![2VNWE)HH$IMM%}2%I4}Z)37](https://user-images.githubusercontent.com/74580268/169943720-b3093462-1736-4942-adb3-caf0444000e7.png)
页面回显的时候，代码没有格式，请问我该怎么处理,,

**Comment by wangfupeng1988** [comment]
查一查 prism.js 的用法。wangEditor 产出的格式，正好符合 prism.js

**Comment by wangfupeng1988** [comment]
查一查 prism.js 的用法。wangEditor 产出的格式，正好符合 prism.js
