### ISSUE TITLE
视频设置后的宽高设置

### ISSUE THREAD

**Issue by ceo-github** [wangeditor-team/wangEditor#4259]
## 功能描述

*建议能否增加像图片一样的宽高设置，不仅可以设置宽高，也可以设置百分比，不然的话即使在编辑器中正常显示，生成后的内容发布后，也会不适应，个人觉得百分比可能很重要；看到作者说要发布5.1版本了，什么时候发布呀，新增的功能很好用哦，希望尽快发布*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
如想尽快发布，请参与进来一起测试一下 https://github.com/wangeditor-team/wangEditor/issues/4240 

PS：5.1 版本也不会有视频的百分比
