### ISSUE TITLE
华为手机钉钉内置浏览器，输入内容后placeholder未隐藏，也无法触发onchange事件

### ISSUE THREAD

**Issue by jingxianliu** [wangeditor-team/wangEditor#4260]
## bug 描述

*请输入内容……*
华为手机，钉钉内置浏览器，输入内容后，placeholder未隐藏，也无法触发onchange事件
## 你预期的样子是？
输入内容后，隐藏placeholder，触发onchange事件
*请输入内容……*

## 系统和浏览器及版本号
ELE-AL00
- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？
能， https://www.wangeditor.com/demo/在钉钉内置浏览器中打开
能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一打开钉钉，对话框中输入https://www.wangeditor.com/demo/打开demo
- 步骤二编辑器输入随意文案
- 步骤三

**Comment by wangfupeng1988** [comment]
暂不支持移动端编辑。
