### ISSUE TITLE
图片上传403错误，onError回调参数res为undefined

### ISSUE THREAD

**Issue by tanhh326** [wangeditor-team/wangEditor#4267]

**Comment by wangfupeng1988** [comment]
403 一般是访问的资源没权限，配合服务端查询一下吧

**Comment by tanhh326** [comment]
不是，这个我当然知道，是这样的，我是想调接口的时候能把错误信息显示出来,所以我就自己改了下请求头模拟了下接口错误，但是我通过onError回调拿不到response的值。

**Comment by wangfupeng1988** [comment]
onError 第三个参数是 response

**Comment by tanhh326** [comment]
onError(file, err, res) {
       // 我肯定是看了api文档来的呀，可是我这样报错之后 res 是 undifined，前两个参数都有值
}

**Comment by tanhh326** [comment]
"@wangeditor/editor-for-vue": "^5.1.11"，这是我使用的版本

**Comment by wangfupeng1988** [comment]
你抓包一下，截图我看看：你这个 HTTP 请求返回的状态码是什么？response 是什么？

**Comment by tanhh326** [comment]
就是我那个上传接口是要鉴权的，然后我把token取消了，返回的403，但是拿不到这个res
![image](https://user-images.githubusercontent.com/82007768/170409893-cc1a6ec6-a943-4fef-9e5b-03368c51bd16.png)

![image](https://user-images.githubusercontent.com/82007768/170409772-43a61dc5-d55b-4efe-a4dd-eaac9f1d5bba.png)

![image](https://user-images.githubusercontent.com/82007768/170410005-8f6b6397-ef5b-4d34-9a79-6ed7abadb326.png)

**Comment by wangfupeng1988** [comment]
@tanhh326 要不你使用自定义上传吧，自由控制 https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD

**Comment by tanhh326** [comment]
感谢大佬的耐心解答，我的问题，文档少看了一条 ,ε=(´ο｀*)))

**Comment by wangkemin** [comment]
这个问题我也遇到了，http请求状态码报错的情况下，res是不返回的，是uppy不支持返回res吗，是否可以优化一下
