### ISSUE TITLE
希望从任意网页粘贴图片到富文本编辑器且能正确显示

### ISSUE THREAD

**Issue by LILI-FUN** [wangeditor-team/wangEditor#4268]
## 问题描述

从 https://detail.1688.com/offer/619995666271.html?spm=a2633q.13149856.l2g54p5h.2.7f3c51d0H4hl6l&&object_id=619995666271&udsPoolId=3117505&resourceId=2514165&delivery_pool_type=resource&delivery_pool_id=2514165 ，此网址粘贴商品描述全部内容，有少数图片能够正常展示，大部分不能，请问是为什么

## wangEditor 版本
v5
*请输入内容……*
希望从任意网页粘贴图片到富文本编辑器且能正确显示
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 希望从**任意**网页粘贴图片到富文本编辑器且能正确显示

这个做不到。wangEditor 是富文本编辑器，重点在于从 0 生产内容，而不是其解析其他的内容。
