### ISSUE TITLE
wangEditor 5的代码高亮在编辑器里有效，获取html文本后，保存到数据库，查询后在页面展示，代码高亮失效

### ISSUE THREAD

**Issue by wlcCloud** [wangeditor-team/wangEditor#4269]
## bug 描述

*wangEditor 5的代码高亮在编辑器里有效，获取html文本后，保存到数据库，查询后在页面展示，代码高亮失效，用<div :innerHTML = "previewHtml">*

## 你预期的样子是？

*wangEditor 5的高亮代码，保存到数据库后，在加载到页面上，直接代码高亮就行，不需要其他的操作*

## 系统和浏览器及版本号

- 操作系统：windows10
- 浏览器和版本 Google Chrome  101.0.4951.54（正式版本） 

## wangEditor 版本

*wangEditor V5*

## demo 能否复现该 bug ？

能，通过<div class="wangEditor" :innerHTML="previewHtml"></div>进行预览就可以发现，previewHtml赋值editor.getHtml()

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 :创建一个div，
                              <a-drawer width="900" placement="right" :closable="false" :visible="drawerVisible" @close="onDrawerClose">
                                    <div class="wangEditor" :innerHTML="previewHtml"></div>
                             </a-drawer>
- 步骤二:            const previewHtml = ref();
                          const handlePreviewContent = () => {
                                const html = editor.txt.html();
                                previewHtml.value = html;
                               drawerVisible.value = true;
                          };
- 步骤三：描述，组装div，拿到editor的html内容，赋值给组装的div的innerHTML属性，就可以看到代买高亮没效果了，求教，文档看了一边，没找到相关解决办法

**Comment by wangfupeng1988** [comment]
显示 HTML 时，代码高亮需要自己处理：https://www.wangeditor.com/v5/content.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
