### ISSUE TITLE
vue中安装v5版本，给编辑器赋值中p标签font-size样式失效

### ISSUE THREAD

**Issue by qiulanbook** [wangeditor-team/wangEditor#4271]
## bug 描述

vue中安装v5版本，给编辑器赋值中p标签font-size样式失效，例如赋值：
values: `<p style='font-size:30px'>测试内容</p>`,

## 你预期的样子是？

测试内容这四个字的字体大小是30px

## 系统和浏览器及版本号

- 操作系统  Windows 10 
- 浏览器和版本 Microsoft Edge最新版

## wangEditor 版本

"@wangeditor/editor": "^5.0.1",
 "@wangeditor/editor-for-vue": "^1.0.0",

## demo 能否复现该 bug ？

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
不能用 `30px` ，必须用这几个字号，如下图

<img width="565" alt="image" src="https://user-images.githubusercontent.com/9583120/170193068-a636fab8-39bf-448d-8e7b-f6e33b4ee167.png">
