### ISSUE TITLE
插入表格时，最前面多出了一行<p><br></p>

### ISSUE THREAD

**Issue by WJ23000** [wangeditor-team/wangEditor#4272]
## bug 描述

*<p><br></p><table style=""><tbody><tr><th colSpan="1" rowSpan="1"></th><th colSpan="1" rowSpan="1"></th><th colSpan="1" rowSpan="1"></th></tr><tr><td colSpan="1" rowSpan="1"></td><td colSpan="1" rowSpan="1"></td><td colSpan="1" rowSpan="1"></td></tr></tbody></table><p><br></p>*
## 你预期的样子是？

*<table style=""><tbody><tr><th colSpan="1" rowSpan="1"></th><th colSpan="1" rowSpan="1"></th><th colSpan="1" rowSpan="1"></th></tr><tr><td colSpan="1" rowSpan="1"></td><td colSpan="1" rowSpan="1"></td><td colSpan="1" rowSpan="1"></td></tr></tbody></table><p><br></p>*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请关注 qq 群消息，待发布了 5.1 版本，这个问题将被解决。
