### ISSUE TITLE
editor文本框输入不了

### ISSUE THREAD

**Issue by Ying-L520** [wangeditor-team/wangEditor#4274]
## 问题描述

1. 问题描述：创建的富文本编辑器输入不了文本，受工具栏默认第一个影响。

*请输入遇到的问题...*
<template>
  <div>
    <div style="border: 1px solid #ccc; margin-top: 10px">
      
        <Toolbar
            style="border-bottom: 1px solid #ccc"
            :editor="editor"
            :defaultConfig="toolbarConfig"
        />
      
        <Editor
            style="height: 400px; overflow-y: hidden"
            :defaultConfig="editorConfig"
            v-model="html"
            @onChange="onChange"
            @onCreated="onCreated"
        />
    </div>
  </div>
</template>
 
<script>
import { Editor, Toolbar } from "@wangeditor/editor-for-vue";
import { DomEditor } from '@wangeditor/editor'
 
export default {
  name: "MyEditor",
  components: { Editor, Toolbar },
  props: ['content'],
  data() {
    return {
        editor: null,
        html: "",
        mode: 'simple', // or 'simple'  default
        toolbarConfig: {
            
            /* 显示哪些菜单，如何排序、分组 */ 
            // toolbarKeys: [
            //   'headerSelect', '|', 'bold', 'underline', 'italic', 'color', 'bgColor', '|', 'fontSize', 'fontFamily', 'lineHeight', '|', 'bulletedList', 'numberedList', 'todo', '|', 'emotion', 'insertLink', 'insertTable', 'codeBlock', 'divider', 
            // ], 
            // excludeKeys: [ ], /* 隐藏哪些菜单 */ 
            excludeKeys: [ 
                'headerSelect'
            ]
        },
        editorConfig: {
            placeholder: "",
            // autoFocus: false,
            // readOnly: true, // 只读、不可编辑
            // 所有的菜单配置，都要在 MENU_CONF 属性下
            MENU_CONF: {
                // 配置上传图片
                uploadImage: {
                    base64LimitSize: 10 * 1024 * 1024,
                },
            },
        },
    };
  },
  methods: {
    onCreated(editor) {
      this.editor = Object.seal(editor); // 【注意】一定要用 Object.seal() 否则会报错
    },
    onChange(editor) {
      // console.log("onChange", editor.getHtml() ); // onChange 时获取编辑器最新内容
 
      // const toolbar = DomEditor.getToolbar(editor)
      // console.log("工具栏配置", toolbar.getConfig().toolbarKeys ); // 工具栏配置
    },
    getEditorText() {
      const editor = this.editor;
      if (editor == null) return;
      // console.log(editor.getText()); // 执行 editor API
    },
    printEditorHtml() {
      const editor = this.editor;
      if (editor == null) return;
      // console.log(editor.getHtml()); // 执行 editor API
    },
  },
  mounted() {
    // 模拟 ajax 请求，异步渲染编辑器
    setTimeout(() => {
      this.html = this.content;
    }, 1500);
  },
  beforeDestroy() {
    const editor = this.editor;
    if (editor == null) return;
    editor.destroy(); // 组件销毁时，及时销毁 editor ，重要！！！
  },
};
</script>
 
<style src="@wangeditor/editor/dist/css/style.css"></style>
## wangEditor 版本

*请输入内容……*

- 点击富文本输入框要输入文本的时候，就会运行工具栏的默认的第一个。使文本输入不进去

## 是否查阅了文档 ？
**是**
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

https://user-images.githubusercontent.com/68949011/170212043-f95823dd-babd-40cf-aed0-ff57b90622cc.mp4

![1Z ZN17A)ZFY``FQQ8_D20D](https://user-images.githubusercontent.com/68949011/170212160-444277ac-49ed-49ce-b84d-ad9f2d34bc2e.jpg)
![$7)E6LO J SPYUSFFICT18I](https://user-images.githubusercontent.com/68949011/170212215-aa71835c-4642-47ad-b698-4837831139f9.jpg)

**Comment by wangfupeng1988** [comment]
你可以在以下平台上，创建一个能复现问题的 demo

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by xjccgg** [comment]
想问一下解决了吗，最简单的demo就一直是这样
