### ISSUE TITLE
Unhandled Rejection (Error): Cannot find module '@babel/runtime-corejs3/core-js-stable/json/stringify'

### ISSUE THREAD

**Issue by buyiyanqi1** [wangeditor-team/wangEditor#4275]
我copy
https://www.wangeditor.com/v5/for-frame.html#react
中代码到本地工程时，本地工程是基于默认的antd v5搭建的
提示如下错误
![image](https://user-images.githubusercontent.com/39300349/170213713-d241ec9b-647f-445c-8f85-857f94a7b7d2.png)

**Comment by buyiyanqi1** [comment]
> 参考这个试试 #4243

我刚使用yarn add @babel/runtime-corejs3  方式安装了一下，还是提示同样的错误，还有其他方法么？

**Comment by ChenKun1997** [comment]
> 

你好，你这个问题解决了吗 @buyiyanqi1
