### ISSUE TITLE
5.1.0版本的editor.setHtml()方法怎么用呢？

### ISSUE THREAD

**Issue by ws-ssp** [wangeditor-team/wangEditor#4276]
![image](https://user-images.githubusercontent.com/95567882/170214846-532ddb38-1499-49c2-a3d8-0920f7f9e82f.png)

**Comment by wangfupeng1988** [comment]
就这么用啊。

文档：https://www.wangeditor.com/v5/API.html#sethtml 

demo： 访问 https://www.wangeditor.com/demo/ ，打开浏览器控制台，执行 `editor.setHtml('<p>hello</p>')` 即可

**Comment by ws-ssp** [comment]
ajax返回后能这样回显嘛

**Comment by wangfupeng1988** [comment]
> ajax返回后能这样回显嘛

访问 https://www.wangeditor.com/demo/  ，在控制台执行

```js
setTimeout(() => {
    editor.setHtml('<p>hello</p>')
}, 1000)
```

这跟 ajax 返回的效果是一样的。
