### ISSUE TITLE
使用 clear() 清空编辑器之后，不能立即输入，要切换到别的窗口，再切换回来才可以输入。 

### ISSUE THREAD

**Issue by zhuangziyu** [wangeditor-team/wangEditor#4277]
## 问题描述

*electron中使用时，清空编辑器之后，不能立即输入，要切出窗口，再切换回来才可以正常输入。 *

## wangEditor 版本

*5.0.1*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
使用 editor.clear() 清空之后，无法输入，但插入功能可以。要切出窗口，再切换回来才可以正常输入。

**Comment by wangfupeng1988** [comment]
网页可以吗？ 仅 electron 不行吗？

**Comment by zhuangziyu** [comment]
只在electron中使用，没在网页中用。

**Comment by zhuangziyu** [comment]
只能采取迂回的方法，清楚后，发送消息让窗口隐藏一下在显示，就可以正常输入了。
