### ISSUE TITLE
大佬请问，版本更新到5.x之后，之前的json结构还有需要吗

### ISSUE THREAD

**Issue by wang-cola** [wangeditor-team/wangEditor#4278]
## 问题描述

我在考虑更新本插件，在评估下更新后的改动风险

## wangEditor 版本

我当前使用的版本为0.13.3

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

我现在是用的v5的偏老版本，在后端分别保存了，编辑器生成的html和json数据，页面显示用html，编辑器回显和编辑用json，但是我看现在v5的比较新的版本，只需要一个value={html}就行了，且onchange里获取的也是html，我想请问下，我要是升级版本的话，是不是直接把我直接的json抛弃掉就好了，用之前存起来的html结构就能完美适配新版本

**Comment by wangfupeng1988** [comment]
> 我想请问下，我要是升级版本的话，是不是直接把我直接的json抛弃掉就好了，用之前存起来的html结构就能完美适配新版本

是的，建议放弃 JSON 数据，只存储 HTML 。
