### ISSUE TITLE
自定义内容选中，怎么让工具栏的按钮不禁用

### ISSUE THREAD

**Issue by hmxhydl** [wangeditor-team/wangEditor#4280]
## 问题描述
自定义的拓展选中后工具栏的部分按钮会禁用，但我自定义想要不禁用这些按钮；怎么重写这个isDiabled方法

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

比如@mention插件  选中 @A张三 后 颜色、加粗..这些按钮都是置灰的；

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
之所以禁用，就是不支持。

你解除了禁用，那点击了菜单也不起作用。
