### ISSUE TITLE
粘贴word内容，文本、表格背景色丢失

### ISSUE THREAD

**Issue by hualuosheng** [wangeditor-team/wangEditor#4282]
### parseStyleHtml getStyleValue 判断出错
粘贴过来 css  background:rgb(0,0,255);  直接用 'background-color' key 去判断 sttr，获取不到背景色

<img width="260" alt="1653488339(1)" src="https://user-images.githubusercontent.com/52061107/170285462-2b71df20-2879-49b6-a3b7-22e599403035.png"><img width="258" alt="1653488450(1)" src="https://user-images.githubusercontent.com/52061107/170285542-e7a0c599-3fff-4cc4-af58-ed27dd342fef.png">

**Comment by dengshicheng1996** [comment]
> 

最新版本有支持了吗

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/wangEditor/issues/4340 一起修改

**Comment by wangfupeng1988** [comment]
> 表格背景色丢失

目前 wangEditor 还不支持表格背景色，所以先去搞定文本样式

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本即可
