### ISSUE TITLE
版本4可以回显的内容，版本5无法回显

### ISSUE THREAD

**Issue by 89757zxb** [wangeditor-team/wangEditor#4283]
## 问题描述

版本4可以回显的内容，版本5无法回显

## wangEditor 版本

5.0

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

版本4地址： https://codepen.io/89757zxb/pen/zYRPJZg
版本5地址： https://www.wangeditor.com/demo/set-html.html （将下面内容复制到输入框后，点击setHTML按钮，无法回显内容）

`<div class="ee-contents"> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/7157/055918c2d48d890e32149057374ff206c2c9b1a17b32bddf2160ba32cba0.png" alt="这是产品详细信息图片。" height="1835" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/7635/15911025979d3476eb35450dcde69f7c861bea9c827c15e429b9e7be619a.jpg" alt="这是产品详细信息图片。" height="495" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/ac55/4f9b03870df4354eac0d56e73a37b876ed68dd2bab259bdd5f31b147bf5d.jpg" alt="这是产品详细信息图片。" height="2139" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/c004/d3fa97628cf332a37b5c7dc076694153f43563d09c5f4d0d585d61b5da59.jpg" alt="这是产品详细信息图片。" height="517" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/51f8/85aaa35a309905c61edb170f9281213dbb6378cd85cc21113fbcf54547ac.jpg" alt="这是产品详细信息图片。" height="674" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/ab5f/abbf4cbfa00b6feea99c3a3f9986e36cfd2d3db7cfa8cf70bf0855979e8c.jpg" alt="这是产品详细信息图片。" height="516" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/b735/4a5af6f8b69ae1e5250ba5035c8bc9c5bc5366a443de109a0202a1b9a58b.jpg" alt="这是产品详细信息图片。" height="1816" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/0e17/ebe19faebc66a83eeba99aec6bd6c9e71e19fb19b9803e73bca6ee957d3e.jpg" alt="这是产品详细信息图片。" height="1773" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/cdef/4ad5271e72d71b22afac6ce3dc1e2be99bfb344d89f3a268e9b7d82e6e7c.jpg" alt="这是产品详细信息图片。" height="1890" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/27e8/2919830bc1480b0342a195d374712bd008dd90f0c127b0727f0f7f6207ec.jpg" alt="这是产品详细信息图片。" height="1972" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/2121/7671f60d76316b30582cb7f550628f551a9cc09e74dbe92aff6cac44e24a.png" alt="这是产品详细信息图片。" height="1778" class=""> </div> </div> <div class="ee-module ee-module-image ee-module-type-image ee-module-width-wide"> <div class="ee-image"> <img src="http://image1.coupangcdn.com/image/vendor_inventory/5f59/de247ba692ecf5670e9c8b0d54ff2495b45b2866e083b9ddd54dc9514e01.png" alt="这是产品详细信息图片。" height="883" class=""> </div> </div> </div>`

**Comment by wangfupeng1988** [comment]
v5 不再支持自定义 HTML 格式。

如果你有强烈的自定义 HTML 格式需求，可以继续用 V4

**Comment by 89757zxb** [comment]
> v5 不再支持自定义 HTML 格式。
> 
> 如果你有强烈的自定义 HTML 格式需求，可以继续用 V4

好的谢谢回复~
