### ISSUE TITLE
黏贴word文档内容出现内容重复问题，就这个文档这样

### ISSUE THREAD

**Issue by 532780857** [wangeditor-team/wangEditor#4284]
![image](https://user-images.githubusercontent.com/39074601/170433468-ba6ec442-6eb7-4b26-af44-3b9698787345.png)

**Comment by wangfupeng1988** [comment]
@532780857 粘贴文档中的哪部分内容会重复？详细描述一下复现步骤，以帮助我们更快的排查问题。

**Comment by 532780857** [comment]
直接复制黏贴整个文档1次，内容就重复2次
只要不带有最后一页的图片印章，就不会重复

**Comment by wangfupeng1988** [comment]
该已经解决了，可更新 `@wangeditor/editor` 最新版本

也可以到 demo 中重新测试 https://www.wangeditor.com/demo/
