### ISSUE TITLE
使用组件  word 文档复制过来的内容 还保留样式，但是看demo 上复制后没有保留样式，是需要设置什么参数吗？

### ISSUE THREAD

**Issue by 5852305** [wangeditor-team/wangEditor#4285]
## 问题描述
使用组件  word 文档复制过来的内容 还保留样式，但是看demo 上复制后没有保留样式，是需要设置什么参数吗？
## wangEditor 版本
^5.0.0
## 是否查阅了文档 ？
是
## 最小成本的复现步骤
  复制到编辑器是 会保留缩进，和文字大小
 步骤一
这是官网demo 复制的清除了格式
![image](https://user-images.githubusercontent.com/19222263/170434455-8766598a-e70b-4866-b578-2a74cd917d0f.png)
步骤二 
这是我的编辑器 还保留了字体大小
![image](https://user-images.githubusercontent.com/19222263/170434678-b6f19aa1-d7bd-4442-91d1-19335b629c2c.png)
![image](https://user-images.githubusercontent.com/19222263/170434885-4dbe98d7-9924-4091-ac31-12b67a34bbd7.png)
想实现复制过来后不保留样式

**Comment by wangfupeng1988** [comment]
wangEditor 无法识别自定义的 HTML 格式。可以使用 customPaste 自行处理 https://www.wangeditor.com/v5/editor-config.html#custompaste
