### ISSUE TITLE
输入纯数字/英文  不能正确换行

### ISSUE THREAD

**Issue by liujian891010** [wangeditor-team/wangEditor#4286]
## 问题描述

富文本编辑器 连续输入数字or英文 不能正确换行
插入表格 增加列数   表格未出现期望的滚动条 而是撑大了编辑器container

## wangEditor 版本

5.0.1

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

只输入数字or英文  不换行  不停的撑大container
解决办法 word-break: break-all;

插入表格 增加列数 未出现滚动条 不停的撑大container
未解决

**Comment by wangfupeng1988** [comment]
> 插入表格 增加列数 未出现滚动条 不停的撑大container

升级 v5.1 试试
