### ISSUE TITLE
建议增加首行缩进功能

### ISSUE THREAD

**Issue by guoguoguo0608** [wangeditor-team/wangEditor#4287]
## 功能描述

建议增加首行缩进功能

**Comment by wangfupeng1988** [comment]
你可以通过给编辑器区域的 DOM 自定义 CSS `text-indent` 来实现。

**Comment by mablevi** [comment]
加上之后图片，视频也都带首行缩进了

**Comment by wangfupeng1988** [comment]
@mablevi 前两天有一个类似的问题，我修复了，你升级 `@wangeditor/editor` 最新版试试吧
