### ISSUE TITLE
React版本自定义菜单扩展一个ButtonMenu，exec中可以接受props中的函数「openModal」吗？例如打开一个Ant的弹窗组件「业务表单逻辑」

### ISSUE THREAD

**Issue by aliang1001** [wangeditor-team/wangEditor#4288]
## 问题描述

React版本自定义菜单扩展一个ButtonMenu，exec中可以接受props中的函数「openModal」吗？例如打开一个Ant的弹窗组件「业务表单逻辑」

## wangEditor 版本

5v

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是

## 最小成本的复现步骤

不涉及

**Comment by wangfupeng1988** [comment]
默认不可以。

你可以考虑其他方式来实现，如使用 event-bus 自定义事件等。
