### ISSUE TITLE
使用editor.restoreSelection()的时候，光标返回到编辑器起点

### ISSUE THREAD

**Issue by login766** [wangeditor-team/wangEditor#4289]
## 问题描述
选中选区后使用SlateTransforms.setNodes转换elment类型的时候，如果不执行转换逻辑直接调用editor.restoreSelection()后选区会消失，光标回到起点位置。
## wangEditor 版本
5.0.0
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
是
## 最小成本的复现步骤
setEditorNode (obj) {
    const editor = getEditor(this.editorId)
    if(obj){
        //转换节点属性
        SlateTransforms.setNodes(editor, obj, { mode: 'highest' })
    }
    //恢复选区
    editor.restoreSelection()
}

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
在执行 `editor.restoreSelection()` 之前打印一下 `JSON.stringify(editor.selection)` 看看结果是什么？

**Comment by login766** [comment]
//接收编辑器对象
getNodes (e) {
    this.nodes = JSON.parse(e)
    console.log("自定义组件接收到的selection：" + JSON.stringify(this.nodes.selection))
},

setEditorNode (obj) {
    const editor = getEditor(this.editorId)
    if(obj){
        //转换节点属性
        SlateTransforms.setNodes(editor, obj, { mode: 'highest' })
    }
    console.log("恢复选区之前的selection：" + JSON.stringify(editor.selection))
    //恢复选区
    editor.restoreSelection()
},

自定义组件接收到的selection：{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[1,0],"offset":5}} （子组件日志）
恢复选区之前的selection：{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[1,0],"offset":5}}  （父组件日志）
自定义组件接收到的selection：{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[0,0],"offset":0} （子组件日志）

大概逻辑是这样自定义组件（子组件）接收editor，然后点击某个按钮后会调用父组件editor.restoreSelection()

**Comment by login766** [comment]
this.$emit('setEditorNode', '') //仅恢复选区
this.$emit('setEditorNode', {type: 'paragraph'})  //转换type并恢复选区
怪异的是这两种调用呈现的结果不一样。

**Comment by wangfupeng1988** [comment]
看的乱乱的，selection 咋还不一样呢？

**Comment by login766** [comment]
对啊，就是因为不一样所以比较奇怪。

第一步：
其实逻辑比较简单，子组件getNodes() 接收的是整个onChange中获取的editor
<img width="465" alt="image" src="https://user-images.githubusercontent.com/19322227/170645288-6301b75a-bc0e-40db-8daa-cc60e3e16d2f.png">

第二步：
选择选区后子组件chu fa触发事件调用setEditorNode()
<img width="409" alt="image" src="https://user-images.githubusercontent.com/19322227/170645571-b1436966-b20d-45bd-a511-b8afa5e5310d.png">
<img width="785" alt="image" src="https://user-images.githubusercontent.com/19322227/170645709-33c4acbb-8995-410a-b428-53e12a2ade74.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/19322227/170645526-ad9ec746-dce3-4fa6-9741-c7ee142b847d.png">

前面的日志就是这个过程打印出来的
<img width="774" alt="image" src="https://user-images.githubusercontent.com/19322227/170645987-3162f07b-c1d2-475a-bd07-62935d0b3138.png">

**Comment by login766** [comment]
我增加了一段日志发现editor.restoreSelection()后其实selection没有问题，但是onChange中的selection变成了起点。
<img width="585" alt="image" src="https://user-images.githubusercontent.com/19322227/170646637-fcab4f66-01b6-440e-a89a-05cf21c934ed.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/19322227/170646973-55e8b2cb-53e1-4d77-ba5b-6c2897a6dcb8.png">

**Comment by login766** [comment]
加了setTimeout()后实现了我想要的效果，不知道是否有隐藏的风险
<img width="567" alt="image" src="https://user-images.githubusercontent.com/19322227/170657703-752dade1-e56f-423c-ac22-a9d185042db5.png">
<img width="783" alt="image" src="https://user-images.githubusercontent.com/19322227/170657513-fb7eb2ec-66be-4e07-8f6d-e7f1d0291ee0.png">

**Comment by wangfupeng1988** [comment]
你先这样用着吧，目前我也看不出有啥坑。多测试一下。

**Comment by login766** [comment]
好的，感谢！
另外还想请教下，wangeditor如何实现的**段落与超链接、代码块、引用、有序无序列表、增加减少缩进的互转**
我看wangeditor没有提供相关方法，使用slate该使用哪些方法来写。

**Comment by login766** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/19322227/170671417-24dfe44b-186a-41c2-a887-5b212b2a1966.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/19322227/170671552-941022b5-407e-4fe8-bfb3-ca584723948d.png">

**Comment by wangfupeng1988** [comment]
@login766 没看懂你的问题，去重新提交一个 issue 吧。
