### ISSUE TITLE
wangEditor4，word文本粘贴到IE里保存回显后，不光有内容 还加了一些css代码，怎么办？

### ISSUE THREAD

**Issue by qinyuyan** [wangeditor-team/wangEditor#4290]
## bug 描述
wangEditor4，word文本粘贴到IE里保存回显后，不光有内容 还加了一些css代码，怎么办？

## 你预期的样子是？
没那部分css代码
或者请指教我在源码里哪个地方加自定义过滤方法，大佬的代码太牛了

## 系统和浏览器及版本号

- win10
- IE11

## wangEditor 版本
4.7.15

## demo 能否复现该 bug ？
不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
抱歉，v5 发布之后 v4 没精力再维护了。

业余维护，精力有限，还请体谅~

**Comment by qinyuyan** [comment]
那能不能麻烦告诉我，在源码里哪个地方加自定义过滤方法呢？我可以自己加，就是不知道加哪儿；如果可以，太感谢了！

**Comment by wangfupeng1988** [comment]
@qinyuyan  可以看看这里 https://www.wangeditor.com/v4/pages/06-%E7%B2%98%E8%B4%B4%E8%BF%87%E6%BB%A4/
