### ISSUE TITLE
移动端在钉钉小程序中不能进行富文本编辑，删除失效，工具栏点击也失效

### ISSUE THREAD

**Issue by muyang1992** [wangeditor-team/wangEditor#4291]
## 问题描述

移动端不能进行富文本编辑

## wangEditor 版本5

在移动端上面不能删除文案，上面的工具栏也不能进行编辑

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 钉钉微应用h5小程序，使用，@wangeditor/editor 和@wangeditor/editor-for-vue,开发页面，在移动端钉钉环境，内容输入，placehoder 不会消失，输入内容正常，删除内容失效。
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 移动端不能进行富文本编辑

是的，暂不支持移动端。
