### ISSUE TITLE
vue2实现模拟腾讯文档

### ISSUE THREAD

**Issue by baihongbin** [wangeditor-team/wangEditor#4293]
## 问题描述

*请问模拟腾讯文档怎么实现的？vue2实现的demo有吗？*

## wangEditor 版本

*V5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 无

> 非常感谢~

**Comment by wangfupeng1988** [comment]
参考这个 demo 即可 https://www.wangeditor.com/demo/like-qq-doc.html
就是 HTML 转成 Vue 而已。
