### ISSUE TITLE
配置了maxLength属性导致插入内容时会自动在顶部添加空行

### ISSUE THREAD

**Issue by weirdotl** [wangeditor-team/wangEditor#4294]
## 问题描述

配置了maxLength属性导致插入内容时会自动在顶部添加空行

## wangEditor 版本

5.0.1

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

使用[vue2-wangeditor-demo](https://github.com/wangfupeng1988/vue2-wangeditor-demo)这个项目，在myEditor.vue文件中editorConfig中增加maxLength会出现以上描述问题

**Comment by wangfupeng1988** [comment]
跟 https://github.com/wangeditor-team/wangEditor/issues/4078 问题应该是一样的，目前还在排队解决中
