### ISSUE TITLE
在超链接后面输入文字，输入的文字也加上了链接

### ISSUE THREAD

**Issue by haohao0879** [wangeditor-team/wangEditor#4298]
## 问题描述
在超链接后面输入文字，输入的字也变成超链接了。现在就是想在超链接后面输入的文字不加上超链接

## wangEditor 版本
版本5

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

## 最小成本的复现步骤
1、随便创建一个带有“插入链接”的编辑框；
2、随便输入一段文字，加上链接，确定；
3、在刚才加链接的文字后面直接输入文字，输入的文字也加上链接了。
![99999](https://user-images.githubusercontent.com/58984292/170952640-1c163726-ea71-4ff1-bc6b-a2f537c838c7.png)
![88888](https://user-images.githubusercontent.com/58984292/170952663-20f31183-6cfb-4f9e-9f04-44019439cf81.png)

**Comment by wangfupeng1988** [comment]
这个不好判断。因为正常情况下，超链接文本的修改（删除文本、追加文本）都是通过编辑器来完成的，就像你的操作一样。

你不希望输入时有链接，其他用户可能想要有链接呢 —— 从用户的本能认知上，不好有名的预期分界。

所以，现在编辑器中插入连接时，前后都会有一个空格文本。

**Comment by pigcaso** [comment]
> 这个不好判断。因为正常情况下，超链接文本的修改（删除文本、追加文本）都是通过编辑器来完成的，就像你的操作一样。
> 
> 你不希望输入时有链接，其他用户可能想要有链接呢 —— 从用户的本能认知上，不好有名的预期分界。
> 
> 所以，现在编辑器中插入连接时，前后都会有一个空格文本。

好像输入一段文本，然后全选这一段设置为链接，这种设置超链接的形式没有添加空格
![9GGMBR4O)1PWWBJR~C@$WOL](https://user-images.githubusercontent.com/49849107/193169536-70bc94f5-ff78-4d8a-a54a-7148ea4fc90b.png)

![8)48SKZ)Q_ETG8QLB9J DID](https://user-images.githubusercontent.com/49849107/193169582-d940ccd6-ff99-4ac6-9a6e-2be69f683263.png)
![A7> 这个不好判断。因为正常情况下，超链接文本的修改（删除文本、追加文本）都是通过编辑器来完成的，就像你的操作一样。
> 
> 你不希望输入时有链接，其他用户可能想要有链接呢 —— 从用户的本能认知上，不好有名的预期分界。
> 
> 所以，现在编辑器中插入连接时，前后都会有一个空格文本。

好像输入一段文本，然后全选这一段设置为链接，这种设置超链接的形式没有添加空格
![9GGMBR4O)1PWWBJR~C@$WOL](https://user-images.githubusercontent.com/49849107/193169536-70bc94f5-ff78-4d8a-a54a-7148ea4fc90b.png)

![8)48SKZ)Q_ETG8QLB9J DID](https://user-images.githubusercontent.com/49849107/193169582-d940ccd6-ff99-4ac6-9a6e-2be69f683263.png)
1W%_M6%TS}KATM_WK W](https://user-images.githubusercontent.com/49849107/193169595-67717c29-0781-4c8f-8db5-c03fa4cb48ee.png)
