### ISSUE TITLE
使用editor.scrollToElem方法时 报错

### ISSUE THREAD

**Issue by 5852305** [wangeditor-team/wangEditor#4299]
## 问题描述

*请输入遇到的问题...*

V5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤
点击定位时 报异常
Element (found by id is 'w-e-element-16') is not in editor DOM
![image](https://user-images.githubusercontent.com/19222263/170972528-2b4e8a23-31db-41f8-880f-197ffe762cad.png)

**Comment by wangfupeng1988** [comment]
请描述复现步骤。
