### ISSUE TITLE
对于上传的图片，能够支持点击图片放大的功能。

### ISSUE THREAD

**Issue by GakkiIIIII** [wangeditor-team/wangEditor#4300]
## 功能描述

*对于上传的图片，无法通过点击图片进行放大*

## 提炼几个功能点

- 返回的html标签的中图片，支持鼠标点击放大

## 原型图

*无*

## 可参考的案例

*无*

**Comment by wangfupeng1988** [comment]
在编辑器中，编辑状态下，没有这个功能。你看 word 或其他编辑器，也没有这样的功能。

你说的应该是在查看状态下，而查看 HTML 是你自己渲染的，图片点击发生什么，此时需要你自己去定义。

**Comment by Liusiyuan-git** [comment]
> 在编辑器中，编辑状态下，没有这个功能。你看 word 或其他编辑器，也没有这样的功能。
> 
> 你说的应该是在查看状态下，而查看 HTML 是你自己渲染的，图片点击发生什么，此时需要你自己去定义。

您好，请问具体怎么定义呢？图片点击有暴露出相应的钩子函数么？
