### ISSUE TITLE
谷歌最新版，如果插入span标签。光标会去到末尾

### ISSUE THREAD

**Issue by Evinzj** [wangeditor-team/wangEditor#4302]
## bug 描述

*
#通过代码，插入span标签，光标会去到末尾。（火狐、360极速模式都是正常，谷歌更新到最新版才会出现问题）
this.editor.txt.append('<span data-id="demo" style="color: #409EFF" contentEditable="false">@测试例子&nbsp;</span>');
*

## 你预期的样子是？

*光标正常在span末尾，而不是在当前行的末尾。但输入文字显示位置却是正常*

## 系统和浏览器及版本号

- 操作系统  WIN10
- 浏览器和版本 谷歌 102.0.5005.63（正式版本） （32 位）（最新版）

## wangEditor 版本

*V4*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：this.editor.txt.append('<span data-id="demo" style="color: #409EFF" contentEditable="false">@测试例子&nbsp;</span>');
- 步骤二：
![image](https://user-images.githubusercontent.com/18310796/171081774-e1b8a5dc-7349-4355-b52a-17ed958adc5a.png)

- 步骤三：
![image](https://user-images.githubusercontent.com/18310796/171081879-a6a7b550-3f26-4ce6-8864-fd6be9d96097.png)

**Comment by Evinzj** [comment]
#关键代码
`this.editor.txt.append('<span data-id="demo" style="color: #409EFF" contentEditable="false">@测试例子&nbsp;</span>');`

**Comment by wangfupeng1988** [comment]
v5 发布了，v4 就没精力再维护了。

业余维护，精力有限，还请体谅。

**Comment by Evinzj** [comment]
> v5 发布了，v4 就没精力再维护了。
> 
> 业余维护，精力有限，还请体谅。

谢谢作者回复。给span外面的P标签加 display: inline-block 解决了。但是IE出现了些别的问题。我自己再想办法做些细节处理吧
