### ISSUE TITLE
V5 版本在 win7 系统下输入中文，光标跑到第一行

### ISSUE THREAD

**Issue by Yangjia23** [wangeditor-team/wangEditor#4304]
## bug 描述
win7 系统下，在编辑器中输入中文，然后按下空格，接着输入一个标点符号，再接着输入中文，光标就跑到第一行去了，控制台报错如下

![image](https://user-images.githubusercontent.com/20862209/171164166-4c8d195d-00f4-4be1-8594-15afb9fa552f.png)

## 你预期的样子是？

正常输入，光标不乱跑

## 系统和浏览器及版本号

- 操作系统 ：  win 7
- 浏览器和版本 ： google 65版本 (64位)

## wangEditor 版本
"@wangeditor/editor": "^5.0.1",
"@wangeditor/editor-for-vue": "^1.0.1",

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
下载 https://github.com/wangfupeng1988/vue2-wangeditor-demo 官方 demo 项目，本地运行跑起来后，在虚拟机 win 7 系统中访问链接即可

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
chrome 版本太老了，升级一下吧。
