### ISSUE TITLE
insertKeys 不支持 array，菜单排列不灵活

### ISSUE THREAD

**Issue by coldice945** [wangeditor-team/wangEditor#4305]
## 功能描述

目前 insertKeys 是 object，如果有多个自定义菜单功能按钮，那么只能依次挨个排列展示。如果想穿插着排列，那么是不支持的。

建议 inserKeys 做成 array，以满足对菜单的自定义。（这里要注意的是，如果做成 array，为了兼容之前的数据和版本，应对数据进行判断，如果是 object 则是之前的逻辑。）

如果觉得可行，我可以帮助写这个需求提交 pr。

## 可参考的案例

```ts
const toolbarConfig: Partial<IToolbarConfig> = {
  insertKeys: [{
    index: 5, // 插入的位置，基于当前的 toolbarKeys
    keys: ['menu-key1', 'menu-key2']
  }, {
    index: 10, // 插入的位置，基于当前的 toolbarKeys
    keys: ['menu-key3']
  }, {
    index: 16, // 插入的位置，基于当前的 toolbarKeys
    keys: ['menu-key4']
  }],
}
```

**Comment by wangfupeng1988** [comment]
这样不好计算，而且可能造成歧义。
例如，在 index:5 插入了 2 个菜单，然后接下来 index: 10 到底是哪个位置呢？—— 是基于之前的 keys 还是最新的 keys 呢？
这还仅仅是两个组合，如果多个组合就乱套了。

所以呀，如果想要重新排列菜单，直接重写 `toolbarKeys` 即可 https://www.wangeditor.com/v5/toolbar-config.html#toolbarkeys
