### ISSUE TITLE
字号设置不了18px,20px等

### ISSUE THREAD

**Issue by hhllee** [wangeditor-team/wangEditor#4308]
fontSize中设置了如下字体

editorConfig.MENU_CONF['fontSize'] = {
    fontSizeList: ['12px', '14px', '16px', '18px', '20px', '22px', '24px'],
 };

## wangEditor 版本
"@wangeditor/editor": "^5.0.1",
"@wangeditor/editor-for-react": "^1.0.3",

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
直接设置html为 `<p><span style="font-size: 24px"><strong>加粗</strong></span></p><p><span style="font-size: 16px"><strong>ccccdd</strong></span></p><p><span style="font-size: 18px;">dddd</span></p>`
font-size: 18px 字体不生效

**Comment by wangfupeng1988** [comment]
你重新自定义了 `editorConfig.MENU_CONF['fontSize'] = {....}` 之后，看编辑器菜单栏“字体”的下拉框，生效了没有？

**Comment by hhllee** [comment]
> 你重新自定义了 `editorConfig.MENU_CONF['fontSize'] = {....}` 之后，看编辑器菜单栏“字号”的下拉框，生效了没有？

菜单栏生效了, 能在编辑器中去编辑正确的字体大小,  但是手动设置html内容后比如 `<p><span style="font-size: 18px;">dddd</span></p>` 后就不能正确展示

**Comment by wangfupeng1988** [comment]
已修复，待发布
https://github.com/wangeditor-team/wangEditor/commit/ad38b8ce6dbcff1d65785c8d6701238ad351f562

**Comment by wangfupeng1988** [comment]
已发布，升级 `@wangeditor/editor` 最新版本即可。

**Comment by hhllee** [comment]
> 已发布，升级 `@wangeditor/editor` 最新版本即可。

感谢🙏  经测试已生效

**Comment by czlin** [comment]
> 



> > 已发布，升级 `@wangeditor/editor` 最新版本即可。
> 
> 感谢, 经测试已生效

请问是哪个版本，我升级了5.1.14 还是不生效

**Comment by hhllee** [comment]
> > 
> 
> > > 已发布，升级 `@wangeditor/editor` 最新版本即可。
> > 
> > 
> > 感谢, 经测试已生效
> 
> 请问是哪个版本，我升级了5.1.14 还是不生效

我是5.1.12版本, 显示正常

**Comment by xrjj** [comment]
"@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-react": "^1.0.6",
还是不生效，请明确一下版本
在编辑器中没有问题，只读模式回显的时候自定义的20px字号还是加不上

**Comment by xrjj** [comment]
> 已发布，升级 `@wangeditor/editor` 最新版本即可。
"@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-react": "^1.0.6",
还是不生效，请明确一下版本
在编辑器中没有问题，只读模式回显的时候自定义的20px字号还是加不上
