### ISSUE TITLE
v5版本编辑器api设置了在选区插入文本的insertText，没有找到在选区插入html的api

### ISSUE THREAD

**Issue by xiezhengsu** [wangeditor-team/wangEditor#4310]
## 问题描述

*编辑器api设置了在选区插入文本的insertText，没有找到在选区插入html的api*

## wangEditor 版本

*V5版本*

## 是否查阅了文档 ？
查阅编辑器api目录没有相关说明文档
![image](https://user-images.githubusercontent.com/20297733/171322802-68a6ed54-0fc2-431b-b561-d7adca91b93d.png)

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

**Comment by wangfupeng1988** [comment]
dangerouslyInsertHtml  你截图里就有。
