### ISSUE TITLE
撤销会一行全部撤销，不是一个字符一个字符的撤销

### ISSUE THREAD

**Issue by foxFallingSkies** [wangeditor-team/wangEditor#4312]
在V5版本中撤销会一行全部撤销，不是一个字符一个字符的撤销

**Comment by wangfupeng1988** [comment]
你打字 10 分钟，写了 500 字。结果一撤销全部没有了？—— 你肯定说不是。

那到底是什么呢，如何复现这个问题么？—— 所以，请按照 issue 模板重新提价问题，详细写明各种信息。
