### ISSUE TITLE
回显报错Cannot resolve a DOM point from Slate point

### ISSUE THREAD

**Issue by Chenhaotmac** [wangeditor-team/wangEditor#4314]
## 问题描述

*回显父组件传过来的值会报Uncaught (in promise) Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":17}*

## wangEditor 版本

*5.1.0*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
 在onFocus事件中插入父组件带过来的文本
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 在onFocus事件中插入父组件带过来的文本

增加一个 setTimeout 试试。

**Comment by Chenhaotmac** [comment]
好像可以了，谢谢

**Comment by wxyscode** [comment]
> > 在onFocus事件中插入父组件带过来的文本
> 
> 增加一个 setTimeout 试试。

你好，我加了setTimeout,还是不行。我是打包后回显视频会报这个错。打包前不会

**Comment by wangfupeng1988** [comment]
如果无法快速、稳定的复现 bug ，我也啥解决办法。

**Comment by TangsWang** [comment]
很可能是由于有页面动画，造成渲染延迟。我遇到过，去掉页面动画就好了。
