### ISSUE TITLE
不能输入中文标点符号

### ISSUE THREAD

**Issue by dwll-lorraine** [wangeditor-team/wangEditor#4315]
## bug 描述

*谷歌71.0.3578.98 版本输入中文标点符号后，再次输入字符删除符号后所有功能均不可使用，控制台报错，
cannot resolve a Dom point from slate point：{“path”:[0,1]， “offset”:"240"}*

## 你预期的样子是？

*可以正常输入中文标点符号*

## 系统和浏览器及版本号

- 操作系统 windows
- 浏览器和版本 谷歌71.0.3578.98

## wangEditor 版本

*5.1.0*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

暂无

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  安装谷歌71.0.3578.98版本
- 步骤二打开demo
- 步骤三输入中文字符后输入中文标点符号 然后再输入字符

**Comment by wangfupeng1988** [comment]
升级一下浏览器版本试试吧

**Comment by aoyamaliu** [comment]
苹果版本操作系统出现这个问题，@wangeditor/editor-for-vue 版本有问题

**Comment by wangfupeng1988** [comment]
我就是苹果的电脑，没复现。

**Comment by aoyamaliu** [comment]
<Editor
        :style="{height: `${editable ? 'none':`${editorConfig.initialFrameHeight}`}`,cursor:`${editable ? 'auto':'text'}`}"
        :defaultConfig="editorConfig"
        v-model="inputVal"
        @onChange="onChange"
        @onCreated="onCreated"
        @customPaste="customPaste"
      />
       移除simple模式，恢复正常

**Comment by dwll-lorraine** [comment]
你好，升级浏览器可以解决这个问题，但是低版本浏览器没有解决













在 2022-06-02 15:40:41，"王福朋" ***@***.***> 写道：

升级一下浏览器版本试试吧
