### ISSUE TITLE
复制粘贴网页内容时，只有文字，图片丢失

### ISSUE THREAD

**Issue by LiGuoBi** [wangeditor-team/wangEditor#4316]
## bug 描述

复制网页图文内容时，粘贴时只有文字，图片丢失。
不图文一起，只粘贴图片能正常粘贴。

## 你预期的样子是？

粘贴图文时图片不丢失，像V4版本一样

## 系统和浏览器及版本号

Windows11
Chrome  102.0.5005.63（64 位）

## wangEditor 版本
wangEditor5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

**Comment by wangfupeng1988** [comment]
这要看你粘贴的 HTML 内容是什么。wangEditor 不能识别所有的 HTML 格式，因此有些图片粘贴不出来。
