### ISSUE TITLE
onChange触发问题

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [wangeditor-team/wangEditor#4318]
## 问题描述
在初始化组件的时候触发onChange回调。

## Code
官网code

## 预期
不在组件初始化的时候触发onChange回调

**Comment by wangfupeng1988** [comment]
在组件中加一个“是否初始化”的变量标记区分一下吧，这并不麻烦。

**Comment by ANUGLYPLUGIN** [comment]
> 在组件中加一个“是否初始化”的变量标记区分一下吧，这并不麻烦。

onChange貌似是有闭包问题
