### ISSUE TITLE
建议开发目录功能

### ISSUE THREAD

**Issue by NicolasDevil** [wangeditor-team/wangEditor#4319]
## 功能描述

*建议开发目录功能进入编辑器，随着对大文章需求，向用户提供一个简明的目录，似乎是对文档的常规操作 @daqianduanshuo *

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
参考这个 demo https://www.wangeditor.com/demo/catalog.html

**Comment by NicolasDevil** [comment]
> 参考这个 demo https://www.wangeditor.com/demo/catalog.html

thankU😂
