### ISSUE TITLE
使用 【wangEditor】 删除文本 （Backspace） 时 没有任何的反应 。但是 使用 delete 键 有反应

### ISSUE THREAD

**Issue by Rookieryb** [wangeditor-team/wangEditor#4320]
## 问题描述
使用 【wangEditor】 删除文本 （Backspace） 时 没有任何的反应 。但是 使用 delete 键 有反应

*请输入遇到的问题...*
按照 【官网文档】搭建一个wangEditor 文档后（我是用的是JavaScript），
功能菜单栏 和 编辑器都正常的显示。但是编辑器删除文字时 没有任何的反应（中文、英文、字符等都没反应）。
浏览器使用的是Google 版本 101.0.4951.67（正式版本） （64 位）.

## wangEditor 版本
wangEditor 5

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/46421045/172018556-580b9791-c74a-4fea-868e-0c56198fd184.png)
![image](https://user-images.githubusercontent.com/46421045/172018572-19bb7c95-f117-4947-b334-02da95b3847c.png)

**Comment by wangfupeng1988** [comment]
官网 demo 能复现吗？

你是什么操作系统，什么浏览器，哪个版本？

**Comment by Rookieryb** [comment]
官网 demo 能复现吗？
&nbsp; &nbsp;官网demo 不能复现&nbsp;


你是什么操作系统，什么浏览器，哪个版本？
&nbsp; &nbsp; 版本	Windows 10 专业版
&nbsp; &nbsp; 版本号	21H2
&nbsp; &nbsp; 安装日期&nbsp;&nbsp;	‎2021/‎12/‎18
&nbsp; &nbsp; 操作系统内部版本	19044.1706
&nbsp; &nbsp; 体验	Windows Feature Experience Pack 120.2212.4170.0



&nbsp; &nbsp; Google 浏览器
&nbsp; &nbsp; 版本 102.0.5005.63（正式版本） （64 位）






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月5日(星期天) 上午9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 使用 【wangEditor】 删除文本 （Backspace） 时 没有任何的反应 。但是 使用 delete 键 有反应 (Issue #4320)





 
官网 demo 能复现吗？
 
你是什么操作系统，什么浏览器，哪个版本？

**Comment by Rookieryb** [comment]
> 官网demo https://www.wangeditor.com/demo/ 能复现吗？
> 
> 你是什​​么操作系统，什么浏览器，哪个版本？

问题已找到、和富文本没有任何的关系。是我这个框架（ruoyi）中的一个js （common.js）有一个遮罩层。按下(ESC) 就可以删除了。（ruoyi 代码在common.js 的 171 行）

**Comment by Rookieryb** [comment]
> 官网demo https://www.wangeditor.com/demo/ 能复现吗？
> 
> 你是什​​么操作系统，什么浏览器，哪个版本？

问题已找到

**Comment by Rookieryb** [comment]
> 官网demo https://www.wangeditor.com/demo/ 能复现吗？
> 
> 你是什​​​​么版本什么操作系统，什么浏览器，哪个？

问题已找到
我是用的是 【ruoyi】 框架
ruoyi 框架中 common.js 中有一个方法是 【禁用后退键】
的，这里面判断了 如果不是Input 和 textarea 就不让他删除。_stopit()
所以 wangEditor 删除（backspace键）没有用。
【代码在common.js 中 517 行】 
感谢回复 谢谢

**Comment by Rookieryb** [comment]
ruoyi 框架中 common.js 有一个方法是【禁止后退键】的，

这鉴定了如果不是Input和textarea就不要让他删除了。_stopit()

所以 wangEditor 删除时（退格键）没有用。

【代码在common.js中517行】

**Comment by jiangnull** [comment]
> 我是用的是 【ruoyi】 框架
> 
> ruoyi 框架中 common.js 中有一个方

太感谢了  这问题我找了一天 终于解决了

**Comment by gentmjt-lang** [comment]
太感谢了我也遇到了这个问题，非常有帮助
