### ISSUE TITLE
希望v5版本可以支持图文混排复制粘贴，像v4版本一样

### ISSUE THREAD

**Issue by rawKylin** [wangeditor-team/wangEditor#4321]
## 功能描述

v5版本可以支持图文混排复制粘贴
## 提炼几个功能点

- 支持图文混排复制粘贴

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
v4版本支持图文混排复制粘贴

**Comment by wangfupeng1988** [comment]
该功能暂不支持。

但已记录下，排队开发中，完成时间未知。
