### ISSUE TITLE
图片缩放比例想要75%,如何做

### ISSUE THREAD

**Issue by Ben-ry** [wangeditor-team/wangEditor#4326]
## 问题描述

*图片上传后,缩放比例想要75%,如何来修改? 目前只有3个比例.*

## wangEditor 版本

*5.0*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
自定义菜单 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E8%8F%9C%E5%8D%95
