### ISSUE TITLE
V5 版本添加自定义图片表情包，无法监听“表情”按钮，并自定义点击事件

### ISSUE THREAD

**Issue by xaigogo** [wangeditor-team/wangEditor#4327]
## 问题描述

如题所述，想给V5版本添加自定义图片表情，

基本思路是，

首先把现有 emoji 表情列表直接替换成 图片列表 `["<img class='imgEmoji' src='xxurl'>", ...]`
然后监听 img.imgEmoji 上的点击事件，直接把该img插入到光标处！
只使用JQuery实现！

## wangEditor 版本

V5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

- 步骤一    替换emoji为图片表情,  成功 ！！

```
# 文档方法为：
editorConfig.MENU_CONF['emotion'] = {
    emotions: '😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉'.split(' ') // 数组
}

# 我直接修改为：
editorConfig.MENU_CONF['emotion'] = {
    emotions: ['<img class="imgEmoji" src="imgurl_1">',   '<img class="imgEmoji" src="imgurl_2">', ...]  // 传入img标签数组
}

# 然后点击 emotion 按钮，弹出框内表情包已全部替换为我重新传入的图片表情。
```

- 步骤二 点击图片表情插入编辑区域，出错 ！！

```
# 在editor创建完成后，追加以下JQuery代码
$("img.imgEmoji").on("click", function(){
   console.log("当前点击表情为：", $(this))
   editor.dangerouslyInsertHtml('<img class="imgEmoji" src="imgurl_1">');
})
===>  发现绑定事件无效，点击表情框中的 img.myEmoj时，没有任何响应和log输出！
```

- 步骤三  重新尝试使用文档中的 on 绑定表情按钮点击事件，出错！！
```
# 参考文档中的全屏按钮方法
editor.on('fullScreen', () => { console.log('fullScreen') })

# 自定义表情按钮方法
editor.on('emotions', () => { console.log('emotions') })    

====> 没有任何输出，应该是没有绑定成功，不知道这个写法是否正确， `editor.on('event-key==emotions？', fn)`！
```

- 步骤四  自定义扩展新功能 ，不会 /(ㄒoㄒ)/~~
查看了 自定义扩展新功能： https://www.wangeditor.com/v5/development.html
查看了 v4 版本的实现代码，
但有点难，感觉搞不定.... 

请教下以上思路和方法是否正确，以及如何最简单策略实现自定义图片表情呢

万分感谢！

**Comment by wangfupeng1988** [comment]
```
editorConfig.MENU_CONF['emotion'] = {
    emotions: ['<img class="imgEmoji" src="imgurl_1">',   '<img class="imgEmoji" src="imgurl_2">', ...]  // 传入img标签数组
}
```

emoji 菜单不支持这种配置。

你还是去重新自定义一个菜单吧，别在 emoji 菜单上折腾了。

**Comment by luo772435545** [comment]
自定义菜单，用setHtml 也没法插入到指定位置 @xaigogo 你后面是怎么处理的呢
