### ISSUE TITLE
React onChange 有闭包的问题

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [wangeditor-team/wangEditor#4328]
## bug 描述

onChange闭包

## 你预期的样子是？
和任何组件/html element的onchange函数一样
当外部状态更新时，onChange内部并没有改变，并没有用useCallback
## wangEditor 版本

最新

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤
官网React例子

**Comment by ANUGLYPLUGIN** [comment]
> ## bug 描述
> onChange闭包
> 
> ## 你预期的样子是？
> 和任何组件/html element的onchange函数一样
当外部状态更新时，onChange内部并没有改变，并没有用useCallback
> 
> ## wangEditor 版本
> 最新
> 
> ## demo 能否复现该 bug ？
> 能
> 
> ## 最小成本的复现步骤
> 官网React例子

**Comment by wangfupeng1988** [comment]
可举例说明，如何复现问题。

**Comment by ANUGLYPLUGIN** [comment]
> 可举例说明，如何复现问题。
官方例子
加入count state
onchange永远输出0
```
function MyEditor() {
  const [editor, setEditor] = useState<IDomEditor | null>(null); // 存储 editor 实例
  const [html, setHtml] = useState('<p>hello</p>'); // 编辑器内容
  const [count, setCount] = useState(0);
  // 模拟 ajax 请求，异步设置 html
  useEffect(() => {
    setTimeout(() => {
      setHtml('<p>hello&nbsp;world</p>');
    }, 1500);
  }, []);

  const toolbarConfig = {};
  const editorConfig: Partial<IEditorConfig> = {
    placeholder: '请输入内容...',
  };
  console.log(count);
  // 及时销毁 editor ，重要！
  useEffect(() => {
    return () => {
      if (editor == null) return;
      editor.destroy();
      setEditor(null);
    };
  }, [editor]);

  return (
    <>
      <div style={{ border: '1px solid #ccc', zIndex: 100 }}>
        <Toolbar
          editor={editor}
          defaultConfig={toolbarConfig}
          mode="default"
          style={{ borderBottom: '1px solid #ccc' }}
        />
        <Editor
          defaultConfig={editorConfig}
          value={html}
          onCreated={(e) => {
            setEditor(e);
            setCount(123);
          }}
          onChange={(editor) => {
            console.log(count);
            setHtml(editor.getHtml());
          }}
          mode="default"
          style={{ height: '500px' }}
        />
      </div>
      <div style={{ marginTop: '15px' }}>{html}</div>
    </>
  );
}

export default MyEditor;
```

**Comment by wangfupeng1988** [comment]
联合这个问题一起看看 https://github.com/wangeditor-team/wangEditor/issues/4332

**Comment by ANUGLYPLUGIN** [comment]
> 联合这个问题一起看看 #4332

还有个问题，就是上次提了onChange触发的问题
事实上只要
1. 鼠标点击了editor
2. 初始化
3. 输入东西
就会触发onChange

第一个也不是很合理感觉

**Comment by wangfupeng1988** [comment]
> 还有个问题，就是上次提了onChange触发的问题

@ANUGLYPLUGIN 去重新提交 issue吧，别混在一起说。

**Comment by wangfupeng1988** [comment]
@hahaaha 能否通过组件的改动来解决？尽量不要增加用户的操作成本。

**Comment by hahaaha** [comment]
> @hahaaha 能否通过组件的改动来解决？尽量不要增加用户的操作成本。

好像没什么好的解决办法，这里其实渲染机制的问题上面的回复弄错了

**Comment by hahaaha** [comment]
> @ANUGLYPLUGIN 这里是react hooks的闭包缺陷 可以参考下面的方法解决 <img alt="截屏2022-06-13 18 13 18" width="1042" src="https://user-images.githubusercontent.com/25847662/173331985-c5544e79-aa50-4546-94cf-92838446558a.png">
> 
> ```
> ...
> const [editor, setEditor] = useState<IDomEditor | null>(null)
>   const [curContent, setCurContent] = useState<SlateDescendant[]>([])
>   const [num, setNum] = useState<number>(0)
>   const numRef = useRef(num)
>   // ----------------------- editor config -----------------------
>   const editorConfig: Partial<IEditorConfig> = {}
>   editorConfig.placeholder = '请输入内容...'
>   editorConfig.onCreated = (editor: IDomEditor) => {
>     setNum(num + 2)
>     setEditor(editor)
>   }
>   useEffect(() => {
>     numRef.current = num
>   }, [num])
>   editorConfig.onChange = (editor: IDomEditor) => {
>     console.log(numRef.current)
>     setCurContent(editor.children)
>   }
> ...
> ```
补充下原因不是hooks闭包问题 应该是渲染机制的原因
https://zh-hans.reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function

**Comment by ANUGLYPLUGIN** [comment]
> > @ANUGLYPLUGIN 这里是react hooks的闭包缺陷 可以参考下面的方法解决 <img alt="截屏2022-06-13 18 13 18" width="1042" src="https://user-images.githubusercontent.com/25847662/173331985-c5544e79-aa50-4546-94cf-92838446558a.png">
> > ```
> > ...
> > const [editor, setEditor] = useState<IDomEditor | null>(null)
> >   const [curContent, setCurContent] = useState<SlateDescendant[]>([])
> >   const [num, setNum] = useState<number>(0)
> >   const numRef = useRef(num)
> >   // ----------------------- editor config -----------------------
> >   const editorConfig: Partial<IEditorConfig> = {}
> >   editorConfig.placeholder = '请输入内容...'
> >   editorConfig.onCreated = (editor: IDomEditor) => {
> >     setNum(num + 2)
> >     setEditor(editor)
> >   }
> >   useEffect(() => {
> >     numRef.current = num
> >   }, [num])
> >   editorConfig.onChange = (editor: IDomEditor) => {
> >     console.log(numRef.current)
> >     setCurContent(editor.children)
> >   }
> > ...
> > ```
> 
> 补充下原因不是hooks闭包问题 应该是渲染机制的原因、 具体可以看下官方这里的说明 https://zh-hans.reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/97073795/173720777-5d0ec3af-63bd-4ad3-a102-3709b5025e52.png">

这个描述的不是闭包问题嘛？

**Comment by ANUGLYPLUGIN** [comment]
> @hahaaha 能否通过组件的改动来解决？尽量不要增加用户的操作成本。

https://github.com/wangeditor-team/wangEditor-for-react/blob/main/src/components/Editor.tsx#L71

看了一下代码说一下认识，可能是我理解错了。
editor对象只会生成一次，也就是说onChange函数只会赋予一次，onChange以后无论怎么改变，都没用(闭包)。
所以是不是能加一个
```
useEffect(() => {
   editor.onChange = onChange
}, [onChange])
```
这样的玩意

**Comment by ANUGLYPLUGIN** [comment]
> > > @hahaaha 能否通过组件的改动来解决？尽量不要增加用户的操作成本。
> > 
> > 
> > https://github.com/wangeditor-team/wangEditor-for-react/blob/main/src/components/Editor.tsx#L71
> > 谈一下我的拙见，可能是我理解错了。 editor对象只会生成一次，也就是说onChange函数只会赋予一次，onChange以后无论怎么改变，都没用(闭包)。 所以是不是能加一个
> > ```
> > useEffect(() => {
> >    editor.onChange = onChange
> > }, [onChange])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样的玩意
> > 监听onChange 没法检测到更新吧 onChange函数又没有变化😂

你每次刷新组件onChange肯定会变啊
不然为什么会存在useCallback呢

**Comment by ANUGLYPLUGIN** [comment]
> > > > @ANUGLYPLUGIN 这里是react hooks的闭包缺陷 可以参考下面的方法解决 <img alt="截屏2022-06-13 18 13 18" width="1042" src="https://user-images.githubusercontent.com/25847662/173331985-c5544e79-aa50-4546-94cf-92838446558a.png">
> > > > ```
> > > > ...
> > > > const [editor, setEditor] = useState<IDomEditor | null>(null)
> > > >   const [curContent, setCurContent] = useState<SlateDescendant[]>([])
> > > >   const [num, setNum] = useState<number>(0)
> > > >   const numRef = useRef(num)
> > > >   // ----------------------- editor config -----------------------
> > > >   const editorConfig: Partial<IEditorConfig> = {}
> > > >   editorConfig.placeholder = '请输入内容...'
> > > >   editorConfig.onCreated = (editor: IDomEditor) => {
> > > >     setNum(num + 2)
> > > >     setEditor(editor)
> > > >   }
> > > >   useEffect(() => {
> > > >     numRef.current = num
> > > >   }, [num])
> > > >   editorConfig.onChange = (editor: IDomEditor) => {
> > > >     console.log(numRef.current)
> > > >     setCurContent(editor.children)
> > > >   }
> > > > ...
> > > > ```
> > > 
> > > 
> > > 补充下原因不是hooks闭包问题 应该是渲染机制的原因、 具体可以看下官方这里的说明 https://zh-hans.reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function
> > 
> > 
> > <img alt="image" width="1156" src="https://user-images.githubusercontent.com/97073795/173720777-5d0ec3af-63bd-4ad3-a102-3709b5025e52.png">
> > 感觉这个是在说dep没给对导致的闭包
> 
> 链接中给的是这一部分 <img alt="截屏2022-06-15 22 13 06" width="1050" src="https://user-images.githubusercontent.com/25847662/173849747-43396045-ed7a-47a3-ac91-460820ae1cd1.png">

这个不是每次点击完alert以后，你狂点+1也只会输出点之前的count吗，这个是在讲闭包感觉
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/97073795/173961786-826f2c03-60a5-4bd1-a966-43b66cc94f8b.png">

**Comment by hahaaha** [comment]
> <img alt="截屏2022-06-15 22 13 06" width="1050" src="https://user-images.githubusercontent.com/25847662/173849747-43396045-ed7a-47a3-ac91-460820ae1cd1.png">

对的。。。我的意思就是说的这个
即使是使用effect    onchange里的 count 也还是创建那一刻的

`组件内部的任何函数，包括事件处理函数和 effect，都是从它被创建的那次渲染中被「看到」的`
应该关注下这一句

**Comment by Madridspark** [comment]
这哪叫闭包问题呀，hooks完全没有问题，就是这个编辑器自身的逻辑不符合常理，正常来说 onChange 作为一个传入参，改变肯定是要触发 Effect的，而这个编辑器根本就是不受控的，接受 value 的传入，却不更新 onChange，原来的版本还能更新 config，现在直接所有堵死，只初始化一次。

**Comment by liudichen** [comment]
onChange用ahooks的useMemoizedFn包裹就可以了哈，避免闭包问题
