### ISSUE TITLE
表格使用时，感觉有些功能可以扩充（感谢老哥耗费那么多时间做开源，做解答）

### ISSUE THREAD

**Issue by PieDi** [wangeditor-team/wangEditor#4329]
## 问题描述
1、建议增加表格边框样式设置
2、每一列的宽度目前是auto，建议是根据整体宽度计算拖拽结果的百分比，然后用来处理文字的自动这行。
3、分割线还需要手动点击的二次确认（感觉像是可以添加的交互行为）

## wangEditor 版本

5.1

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/19202314/172366364-cfc7aa66-8353-4d99-9090-30ce747d7679.png">

1、处是添加分割线的二次确认
2、处是现在的表格布局样式，建议是按照用户手动拖拽的宽度固定比例，然后文字自动这行
3、关于表格边框的样式，我目前是拿到 html 文本之后做的全局替换，
在这个编辑器中做好表格，感觉确实需要考虑很多东西，也很耗费精力

**Comment by wangfupeng1988** [comment]
你提的建议非常好！

这些我都记录下来了，将来慢慢排队开发，最近精力不够。

感谢反馈~
