### ISSUE TITLE
点击编辑器外按钮时无法触发onblur事件

### ISSUE THREAD

**Issue by nodiy1982** [wangeditor-team/wangEditor#4330]
## bug 描述
当点击其他处时会正常触发onblur事件，只有点击按钮时不会触发，在按钮的onclick事件调用blur()方法也没有效果

## 你预期的样子是？

焦点在编辑器中时，点击编辑器外按钮，会触发onblur事件

## 系统和浏览器及版本号

- Windows 10专业版 版本19041.264
- 谷歌浏览器 版本 93.0.4577.63

## wangEditor 版本

5.0.1

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

```html
<body>
  <div class="page-container">
      <!-- 编辑器 DOM -->
      <div id="Box" style="border: 1px solid #ccc;">
        <div id="editor-toolbar" style="border-bottom: 1px solid #ccc;"></div>
        <div id="editor-text-area" style="height: 300px"></div>
      </div>
      <button id ="btn">点击</button>
    </div>
  </div>

  <script src="dist/index.js"></script>
  <script>
    const E = window.wangEditor
    var editConfig={
      MENU_CONF: {
        },
        onFocus:(editor) =>{
          console.log("onFocus")
        },
        onBlur:(editor)=>{
          console.log("onBlur")
        }
    }
    window.editor = E.createEditor({
      selector: '#editor-text-area',
      config: editConfig
    })
    
    window.toolbar = E.createToolbar({
      editor,
      selector: '#editor-toolbar',
      config: {}
    })
    var btn=document.querySelector("#btn")
    btn.onclick = (e) =>{
      console.log("btnClick");
      window.editor.blur()
    }
  </script>
</body>
```

**Comment by yu530feng** [comment]
我提交了个PR,   https://github.com/wangeditor-team/wangEditor/pull/4392  可以看一下

**Comment by wangfupeng1988** [comment]
> 我提交了个PR, #4392 可以看一下

已回复 pr

**Comment by yu530feng** [comment]
> > 我提交了个PR, #4392 可以看一下
> 
> 已回复 pr ，试着不行啊

我重新提交了，新的方案有较大的改动

**Comment by yu530feng** [comment]
> @yu530feng 你改动内容较多，我需要抽时间好好看看。这几天没时间看。

改动其实不大的，原onFocusAndOnBlur函数通过监听change事件处理onFocus、onBlur回调的，也因此产生了当前bug（点击按钮没触发change事件（checkbox等也有类似问题）），改用统一调editor的focus和blur方法

**Comment by wangfupeng1988** [comment]
@yu530feng 这是我修改的方案，你可以试试行不行？我计划下周发布一个版本

https://github.com/wangeditor-team/wangEditor/commit/4a1997b9f19cdce9d6aa6ff4e8e13d439b12af05

**Comment by wangfupeng1988** [comment]
问题已经解决，下载最新版本即可 https://www.npmjs.com/package/@wangeditor/editor
