### ISSUE TITLE
V4 版本的 CDN 失效了  

### ISSUE THREAD

**Issue by ChinJie** [wangeditor-team/wangEditor#4331]
## 问题描述
V4 版本的 CDN 失效了  
## wangEditor 版本
V4
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 打不开了
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
https://unpkg.com/wangeditor@latest/dist/wangEditor.min.js
