### ISSUE TITLE
react如何在上传自定义事件中获取editor

### ISSUE THREAD

**Issue by zouzixuan** [wangeditor-team/wangEditor#4332]
![E1D46435C31619815F3E533E95F96366](https://user-images.githubusercontent.com/38025251/172522337-37000bcc-e8b9-4978-8337-76a98f835e4d.jpg)
这事件里的editor就一直是null

**Comment by zouzixuan** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/38025251/172522462-e4af6169-f13f-4aa2-8fba-3e77654616d7.png">
这是dom

**Comment by hahaaha** [comment]
这个问题可以参考下https://github.com/wangeditor-team/wangEditor/issues/4328 下的回复
