### ISSUE TITLE
图片布局、视频布局能力增强

### ISSUE THREAD

**Issue by PieDi** [wangeditor-team/wangEditor#4338]
## 问题描述

老哥，建议是图片布局是修改手动输入百分比，而不是固定的  30%   50%   100% 三个，这样的话图文能力的布局有点弱

## wangEditor 版本

比如，面对现在产品要求发布一个H5页面要求一横排显示三张、两张图片，这样的排版目前支持度不够友好

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

是

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
可以去自定义扩展菜单 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E8%8F%9C%E5%8D%95
