### ISSUE TITLE
修改文本后列表数字不改变

### ISSUE THREAD

**Issue by dengshicheng1996** [wangeditor-team/wangEditor#4339]
## 功能描述
功能列表修改文本颜色后，列表标识颜色不一起改变

## 提炼几个功能点

- 功能1  修改文本为列表后，修改文本颜色，列表标识与文本一致

## 原型图

![image](https://user-images.githubusercontent.com/41374066/172594409-cb00ad05-fe50-4a93-8012-95ce9ae24cb3.png)

## 可参考的案例
腾讯文档
![image](https://user-images.githubusercontent.com/41374066/172594553-c74cbd2b-e8d0-46f6-9539-9706cb6f8b2d.png)

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本
