### ISSUE TITLE
从word粘贴的内容，样式颜色丢失

### ISSUE THREAD

**Issue by dengshicheng1996** [wangeditor-team/wangEditor#4340]
## bug 描述
从word文档复制后的文本样式丢失，如文本增加删除线，文本颜色丢失。如文本增加背景色，文本背景色丢失

## 你预期的样子是？
1.  复制带有删除线&文本颜色的文本，粘贴后颜色与word 一直
2.  复制带有背景色的文本，粘贴后文本带有背景色

## 系统和浏览器及版本号

- 操作系统 macos 15
- 浏览器和版本  google 102.0.5005.61

## wangEditor 版本
官网在线demo，仿腾讯云

## demo 能否复现该 bug ？
能

## 最小成本的复现步骤

- 步骤一  word 文档增加带有删除线和文本颜色的一段文本字，增加一段带有背景色的文本
- 步骤二  复制2段文本至官网仿腾讯云demo
- 步骤三  带有删除线的文本，文本颜色丢失，带有背景色的文本，背景色丢失

**Comment by wangfupeng1988** [comment]
已记录，需排队修改。
