### ISSUE TITLE
使用自定义上传图片,但是传过去的是空的

### ISSUE THREAD

**Issue by 1300130049** [wangeditor-team/wangEditor#4342]
## 问题描述

*使用自定义上传图片,但是传过去的是空的*

## wangEditor 版本

*5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

我感觉可能是我写的不对,想知道正确写法
我用的vue2,没有使用ts
请问vue2,不使用typescript的情况下
怎么实现自定义上传图片
![T1`PJK`LZJBE75S%_2 P)ZF](https://user-images.githubusercontent.com/54137440/172633807-15c7099e-7ada-4939-adea-bd6ee6fb4c47.png)
![image](https://user-images.githubusercontent.com/54137440/172633974-3cf4b78f-0b25-453d-be2b-3fbba8751769.png)
![image](https://user-images.githubusercontent.com/54137440/172634191-b9ba3310-d58f-4da9-be40-d1f9d21b7e45.png)

**Comment by wangfupeng1988** [comment]
看是否和这个 https://github.com/wangeditor-team/wangEditor/issues/4333 问题一样？

**Comment by 1300130049** [comment]
解决了,是fieldName参数没设置,传过去是默认的,所以没获取到,
设置一下fieldName:'file',就可以了
