### ISSUE TITLE
Nodes className

### ISSUE THREAD

**Issue by Homebrew1** [wangeditor-team/wangEditor#4343]
## 功能描述
insertNode 节点 加className
*请输入内容……*
insertNode({ type: 'mention' }) 节点加className
## 提炼几个功能点
在提及的时候。{ type: 'mention' } 需要className { type: 'mention',  className: ' ' }  这样比较好区分
- 功能1
- 功能2
提及分为多种类型 在提及insertNode节点体现类型
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
没懂你的意思。为何需要 className ？什么是“比较好区分”？

**Comment by Homebrew1** [comment]
什么是“比较好区分”？
不同的mention className不一样，每个有不同的样式

**Comment by wangfupeng1988** [comment]
不支持。

你可以参考 mention 来自定义第三方插件。

**Comment by Homebrew1** [comment]
不支持的原因是什么

**Comment by wangfupeng1988** [comment]
因为当前 mention 的数据结构定义中，没有 className 。只有如下

```ts
type EmptyText = {
  text: ''
}
export type MentionElement = {
  type: 'mention'
  value: string
  info: any
  children: EmptyText[] // void 元素必须有一个空 text
}
```

https://github.com/wangeditor-team/wangEditor-plugin-mention/blob/main/src/module/custom-types.ts
