### ISSUE TITLE
onChange触发问题

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [wangeditor-team/wangEditor#4344]
## 问题描述

onChange触发的问题
事实上只要
1. 鼠标点击了editor
2. 初始化
3. 输入东西
就会触发onChange

第一个也不是很合理感觉

**Comment by wangfupeng1988** [comment]
onChange 的定义：内容或者选区变化时触发。

- 内容变化要触发
- 选区变化也要触发（因为后面可能会支持多人协同编辑，多人的选区还能及时同步）

**Comment by ANUGLYPLUGIN** [comment]
> 

主要是重复触发的情况下又闭包没有办法阻止触发多个请求，如果闭包没了，应该会解决。

**Comment by wangfupeng1988** [comment]
> 闭包没有办法阻止触发多个请求

你具体是要在 onChange 里做什么操作？
