### ISSUE TITLE
视频或者图片如何自定义宽高？

### ISSUE THREAD

**Issue by wcs-980718** [wangeditor-team/wangEditor#4345]
## 问题描述

视频或者图片想要自定义宽高？

## wangEditor 版本

5.0

## 是否查阅了文档 ？

文档上没有显示此设置方法

**Comment by wcs-980718** [comment]
想要默认自定义的宽高

**Comment by wangfupeng1988** [comment]
> 想要自定义默认的宽高

这个目前不支持

**Comment by wangfupeng1988** [comment]
最新版本已经支持视频自定义尺寸了

**Comment by wangfupeng1988** [comment]
> 上传之后视频大小显示不全怎么办呀

需改尺寸试试，能显示全吗？

**Comment by delSuper** [comment]
修改尺寸之后可以，但是我想上传完成就显示全该怎么去修改呢

**Comment by wangfupeng1988** [comment]
> 修改尺寸之后可以，但是我想上传完成就显示全该怎么去修改呢

可以待上传完成之后，对这个视频节点修改属性，文档参考 https://www.wangeditor.com/v5/API.html#setnodes

**Comment by davidkingzyb** [comment]
···
SlateTransforms.setNodes(that.editor, {
      // textAlign:'right',
          width:'100%'
   }, {
          mode: 'highest' // 针对最高层级的节点
   })

···
这个方法右对齐可以生效，宽度100%不生效
