### ISSUE TITLE
能否提供一个版本升级的帮助文档

### ISSUE THREAD

**Issue by dengshicheng1996** [wangeditor-team/wangEditor#4346]
## 问题描述
部分用户会存在之前使用其他编辑器的情况，或者使用3 或 4版本的wangedit需要往5版本进行升级。而升级所带来的边界影响未知，对于升级带来的风险带有疑虑，能否提供一个升级帮助文档？

## wangEditor 版本
从v4 到 v5

## 是否查阅了文档 ？
是

**Comment by wangfupeng1988** [comment]
最重要的就一条：如果你没有在 v4 中定义组件，即你仅仅用了 v4 自带的功能，就可以升级了。

其他的参考文档即可，v5 的配置和 v4 的也很像。

**Comment by dengshicheng1996** [comment]
> 最重要的就一条：如果你没有在 v4 中定义组件，即你仅仅用了 v4 自带的功能，就可以升级了。
> 
> 其他的参考文档即可，v5 的配置和 v4 的也很像。

在v4 版本自定义了背景色，字体，字体颜色，格式化，自定义上传图片、自定义表格、文本列表（拓展了类似word 的几种） 这几个功能。同时发现在v5 版本中，除格式刷和文本列表外，其他都做了新的集成。在渲染之前的html 的时候就会出现渲染错误。出现不被解析的标签和样式, 之前的样式也出现了丢失。

![image](https://user-images.githubusercontent.com/41374066/173525988-9c381a02-36b4-45ec-a805-1bcb596e93c5.png)

**Comment by wangfupeng1988** [comment]
按你的需求，那还是建议继续使用 v4

**Comment by dengshicheng1996** [comment]
> 按你的需求，那还是建议继续使用 v4

是否有演进方案的推荐？目前数据库存在的数据都是v4 生成的，想逐渐演进到v5 的版本中去，逐渐替换到数据中不兼容的部分

**Comment by wangfupeng1988** [comment]
> 逐渐替换到数据中不兼容的部分

这个不好替换。因为 v4 当时没限制数据格式，任意的 HTML 都可以粘贴进来。所以，到底有多少不兼容的格式，这个你、我都确定不了。

**Comment by dengshicheng1996** [comment]
> 这个不好替换。因为 v4 当时没限制数据格式，任意的 HTML 都可以粘贴进来。所以，到底有多少不兼容的格式，这个你、我都确定不了。

明白了，笔芯

**Comment by maotingyuan** [comment]
> > 最重要的就一条：如果你没有在 v4 中定义组件，即你仅仅用了 v4 自带的功能，就可以升级了。
> > 其他的参考文档即可，v5 的配置和 v4 的也很像。
> 
> 在v4 版本自定义了背景色，字体，字体颜色，格式化，自定义上传图片、自定义表格、文本列表（拓展了类似word 的几种） 这几个功能。同时发现在v5 版本中，除格式刷和文本列表外，其他都做了新的集成。在渲染之前的html 的时候就会出现渲染错误。出现不被解析的标签和样式, 之前的样式也出现了丢失。

请问下是实现了格式刷的功能吗，能否参考一下
