### ISSUE TITLE
富文本插入图片的时候建议返回插入的图片所在的下标位置

### ISSUE THREAD

**Issue by clgGit** [wangeditor-team/wangEditor#4347]
editor.config.customUploadImg，第二个参数是插入图片，插入图片后没有任何返回；
需求：每次上传完图片，我需要对图片做样式处理，当第二个参数insert到dom后，我要重新获取图片列的dom重新渲染我需要的样式，
当我需要在富文本图片列中插入一张图片，我就没办法知道插入图片的位置进行样式渲染，而是全部都重新渲染我需要的样式
建议：第二个参数插入图片到富文本后可以返回插入所在dom的下标位置

**Comment by wangfupeng1988** [comment]
你是哪个版本？

请找 issue 模板提交，否则不予受理。
