### ISSUE TITLE
vue2点击工具栏报错

### ISSUE THREAD

**Issue by 373579070** [wangeditor-team/wangEditor#4348]
## 问题描述

vue2点击工具栏报错且编辑器无效果，是按照文档教程来的

## wangEditor 版本

5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
每点击一次工具栏按钮，都会报错一次
<img width="532" alt="WX20220609-132743@2x" src="https://user-images.githubusercontent.com/107164081/172770988-5d888664-1dc2-4b7f-923f-e4a94b4518c4.png">

**Comment by wangfupeng1988** [comment]
参考这里的 demo 吧 https://www.wangeditor.com/v5/for-frame.html#vue2 
看这个 demo 能复现吗？
