### ISSUE TITLE
请问怎么在h5页面插入“上传附件”的功能

### ISSUE THREAD

**Issue by mengyingshi** [wangeditor-team/wangEditor#4349]
请问怎么在h5页面插入“上传附件”的功能

**Comment by wangfupeng1988** [comment]
上传附件看这里 https://www.wangeditor.com/v5/plugins.html

 不过，wangEditor 暂时不支持移动端编辑。

**Comment by wangfupeng1988** [comment]
@paulloo 自己加一个 click 事件即可

**Comment by taomin15201212** [comment]
> @paulloo 自己加一个 click 事件即可

请问如何给虚拟dom加上这个click，好像是自动生成的
