### ISSUE TITLE
上传图片的网络图片不知道如何隐藏

### ISSUE THREAD

**Issue by jingjing0711** [wangeditor-team/wangEditor#4350]
## 问题描述
您好，使用的vue2，插件用的5.1.0，使用的是vue2的Demo模板实现，mode='simple'简易模式,，在toolbarConfig中使用excludeKeys隐藏工具栏项目，其他想隐藏的都隐藏掉了，但是上传图片的网络图片不知道如何隐藏，使用editor.getAllMenuKeys()获取到了60个工具栏的key，没有找到隐藏上传网络图片的途径。

## wangEditor 版本

5.1.0

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by jingjing0711** [comment]
您好，使用的vue2，插件用的5.1.0，使用的是vue2的Demo模板实现，mode='simple'简易模式,，在toolbarConfig中使用excludeKeys隐藏工具栏项目，其他想隐藏的都隐藏掉了，但是上传图片的网络图片不知道如何隐藏，使用editor.getAllMenuKeys()获取到了60个工具栏的key，没有找到隐藏上传网络图片的途径。

**Comment by wangfupeng1988** [comment]
通过 `toolbar.getConfig().toolbarKeys` 可以获取到当前菜单栏的菜单配置。

图片是一个菜单组合，key 是 `group-image` 。在 excludeKeys 中加入 `group-image ` 就可以隐藏掉这个菜单组了。

**Comment by 18247033708** [comment]
在菜单栏设置 excludeKeys中加入insertImage

 excludeKeys: [
           'insertImage'
          ]
