### ISSUE TITLE
咨询：v5 获取editor.getHtml()和v4的获取到的不一样。

### ISSUE THREAD

**Issue by zz925625** [wangeditor-team/wangEditor#4351]
## 问题描述

 v5 设置内容 

 this.html = "<\p>Ajax 异步设置内容 HTML<\/p><style>p{color: red;}<\/style>";-----p 加了转义符

然后再获取 editor.getHtml()   返回 <p>Ajax&nbsp;异步设置内容&nbsp;HTML11</p>  自动删除了 html外的其他标签内容。
就获取不到  最外层p标签以外的内容。只能获取到p里面

v4 
 是可以获取到 传  进去的所有内容。

想问：v5就是这种效果吗。

**Comment by wangfupeng1988** [comment]
看这里的红色文字 https://www.wangeditor.com/v5/content.html#%E8%AE%BE%E7%BD%AE-html
