### ISSUE TITLE
如何插入html标签？dangerouslyInsertHtml('<audio controls src=''></audio>');列如我想插入一个音频 ??

### ISSUE THREAD

**Issue by zeroone-code** [wangeditor-team/wangEditor#4352]
如何插入html标签？dangerouslyInsertHtml('<span class="tests">被过滤了</span>'); ??

**Comment by wangfupeng1988** [comment]
wangEditor 现不支持音频。

如有需要，可自定义扩展 https://www.wangeditor.com/v5/development.html

**Comment by wangfupeng1988** [comment]
另外，注意文档中对 dangerouslyInsertHtml 的描述

<img width="827" alt="image" src="https://user-images.githubusercontent.com/9583120/172966033-10cf1e17-e805-4738-8df3-697bd9014f9c.png">
