### ISSUE TITLE
vue 使用了全局reset 重置了样式会使富文本编辑框内加粗、斜体、链接失效等问题

### ISSUE THREAD

**Issue by nsupuxiangjin** [wangeditor-team/wangEditor#4354]
##  问题描述

*vue 使用了全局reset 重置了样式会使富文本编辑框内加粗、斜体、链接失效等问题.*

## wangEditor 版本

*wangEditor v4 v5 都存在这个问题*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- vue 项目全局reset.css 就会出现问题
- 设置了加粗和斜体都无效
![H9L61A2XMENDC3MR)M}4CZK](https://user-images.githubusercontent.com/38774193/173016328-efd1611c-6533-4861-a61c-ff5bac5317ce.png)

**Comment by wangfupeng1988** [comment]
reset.css 是哪里来的？

**Comment by nsupuxiangjin** [comment]
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}

/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure,
footer, header, hgroup, menu, nav, section {
  display: block;
}

body {
  line-height: 1;
}

ol, ul {
  list-style: none;
}

blockquote, q {
  quotes: none;
}

blockquote:before, blockquote:after,
q:before, q:after {
  content: '';
  content: none;
}

table {
  border-collapse: collapse;
  border-spacing: 0;
}html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}

/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure,
footer, header, hgroup, menu, nav, section {
  display: block;
}

body {
  line-height: 1;
}

ol, ul {
  list-style: none;
}

blockquote, q {
  quotes: none;
}

blockquote:before, blockquote:after,
q:before, q:after {
  content: '';
  content: none;
}

table {
  border-collapse: collapse;
  border-spacing: 0;
}

**Comment by wangfupeng1988** [comment]
看你发的代码，不像是这段 css 的影响。

你用 chrome 元素检查工具看看这个节点的样式吧，看是哪个 css 文件导致的加粗失效

![image](https://user-images.githubusercontent.com/9583120/173784014-05ce94fd-33ca-4e5e-b1d6-209185e94d17.png)

**Comment by nsupuxiangjin** [comment]
![32ff21f59fa4f52de70af882f5a97fc](https://user-images.githubusercontent.com/38774193/173787099-7105af5e-2849-4999-a360-ca46a82c7ceb.png)
查了一下！应该是这个属性影响了。我去这个属性就能行了

**Comment by wangfupeng1988** [comment]
你看你截图的右侧 `user agent stylesheet`，这是浏览器默认样式。

你可以新建一个空白 html ，然后只写一个 `<strong>` 标签，看你浏览器是否能正常加粗？

**Comment by fox-half-tian** [comment]
wangeditor 似乎使用的是粗体、斜体这些样式是浏览器默认的。项目通常会加 reset.css 去除默认标签样式带来的影响。这个问题应该如何解决了呢？单独写一个wangeditor样式文件吗？还是已经有了现成的解决方案

> 你看你截图的右侧 `user agent stylesheet`，这是浏览器默认样式。
> 
> 你可以新建一个空白 html ，然后只写一个 `\<strong\>` 标签，看你浏览器是否能正常加粗？

**Comment by YukiChiyoda** [comment]
各位前辈，我的项目没有作任何对strong标签的样式覆写，但加粗显示也失效了。经检查，在editor以外的strong标签是可以正常生效的。还请大佬们指点！<img width="452" height="766" alt="Image" src="https://github.com/user-attachments/assets/6234a822-3837-4151-8353-2dbd15925ded" />
