### ISSUE TITLE
v5的新版中 设置仿宋字体，保存之后，重新打开回显，会把仿宋的css样式删除，但是其他字体没有这种问题

### ISSUE THREAD

**Issue by lalLAL95828** [wangeditor-team/wangEditor#4355]
v5的新版中 设置仿宋字体，保存之后，重新打开回显，会把仿宋的css样式删除，但是其他字体没有这种问题

**Comment by lalLAL95828** [comment]
应该是@wangeditor/editor-for-react有问题

**Comment by wangfupeng1988** [comment]
官网 demo 也可以复现。

https://www.wangeditor.com/demo/set-html.html ，HTML 设置 `<p>你好<span style="font-family: 仿宋;">中国</span></p>`，字体无效

**Comment by Gavin-yh** [comment]
[fix: 部分字体回显问题](https://github.com/wangeditor-team/wangEditor/pull/4370)

**Comment by wangfupeng1988** [comment]
pr 已经合并，待发布
