### ISSUE TITLE
清除格式--无法清除行高

### ISSUE THREAD

**Issue by coralJiao** [wangeditor-team/wangEditor#4356]
## bug 描述

文字清除格式时，无法清除行高
![image](https://user-images.githubusercontent.com/48193126/173043715-48a7e73c-8726-4c8c-ad7d-6eba13c91cc3.png)
![image](https://user-images.githubusercontent.com/48193126/173043775-9ffbef70-26e8-4c28-9e35-8a8a37c2db60.png)

https://www.wangeditor.com/demo/index.html
官网demo即可复现

步骤一：文字设置颜色、背景色、字体、下划线、行高
步骤二：清除格式
结果：行高未清除

**Comment by wangfupeng1988** [comment]
这符合预期。

因为行高是整个段落的，并不是某一段文本的。

同理，你也没法对一个段落中的某几个文本，单独设置行高。
