### ISSUE TITLE
vue2+wangEditor，前端往controller传值p标签丢失问题！

### ISSUE THREAD

**Issue by chensc-spc** [wangeditor-team/wangEditor#4357]
前端post提交，传的值为整个form，若依框架，vue2。
![QQ图片20220611133402](https://user-images.githubusercontent.com/76547803/173174397-3b6645ea-0c59-426f-a5f4-f5ab585ef4f6.png)
![QQ图片20220611133409](https://user-images.githubusercontent.com/76547803/173174402-33dc559e-5c1f-4bf9-8959-057559378882.png)
![QQ图片20220611133419](https://user-images.githubusercontent.com/76547803/173174409-b7695c13-06d1-4f27-a008-9655f5976938.png)

**Comment by wangfupeng1988** [comment]
你需要抓包，看看前端 request 的数据，里面有没有 `<p>` ？

**Comment by chensc-spc** [comment]
![image](https://user-images.githubusercontent.com/76547803/173224193-a319162b-b0cc-4bf6-8549-8f10428ed518.png)

**Comment by wangfupeng1988** [comment]
Request 内容里有 `<p>` ，这符合预期。然后，你就得去服务端找一找问题了
