### ISSUE TITLE
simple模式下，还是出现警告编辑区域高度 < 300px 这可能会导致 modal hoverbar 定位异常。看的好难受，有办法让他不提示吗。初始高度就不想太占位置

### ISSUE THREAD

**Issue by wumiangithub** [wangeditor-team/wangEditor#4358]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考这里给你的答复

https://github.com/wangeditor-team/wangEditor/issues/3796#issuecomment-1152886662

**Comment by bilibili-ayang** [comment]
console.warn = () => {}
