### ISSUE TITLE
请问iframe如何插入，还是说无法插入

### ISSUE THREAD

**Issue by a809820424** [wangeditor-team/wangEditor#4361]
## 问题描述

无法插入iframe

## wangEditor 版本

V5

## 是否查阅了文档 ？

是
 
## 最小成本的复现步骤

 editor.dangerouslyInsertHtml('<iframe  src="http://www.baidu.com"  width="500" height="300"></iframe>')

**Comment by JeasonLaung** [comment]
解决了吗，刚好有个项目需要插入iframe

**Comment by mayday97** [comment]
同问，是否考虑支持插入iframe标签，或者自定义的webcomponent
