### ISSUE TITLE
只读状态下，点击表格，弹出表格操作按钮

### ISSUE THREAD

**Issue by wang1057296609** [wangeditor-team/wangEditor#4364]
## bug 描述
只读状态下，点击表格，弹出表格操作按钮（按钮无法操作状态）

## 期望
只读状态下，点击表格，不弹出表格操作按钮

## 系统和浏览器及版本号
window 谷歌浏览器

## wangEditor 版本
^5.1.1

## 在线 demo
测试文档-http://unicloud.icu/#/document/details?id=62a045b1fd3e320001b7aabf

**Comment by ChenKun1997** [comment]
同问，等一个回复

**Comment by wangfupeng1988** [comment]
已经修复，更新最新版本即可 https://www.npmjs.com/package/@wangeditor/editor
