### ISSUE TITLE
设置内容后会自动在首行增加一个换行标签

### ISSUE THREAD

**Issue by hushed3** [wangeditor-team/wangEditor#4365]
## 问题描述

``` javascript
开启maxLength属性后，设置内容会在第一行增加一对<p><br></p>标签
```
## wangEditor 版本

vue: 2.5.2
@wangeditor/editor: 5.1.1
@wangeditor/editor-for-vue: 1.0.1

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：下载官方demo源码 https://github.com/wangfupeng1988/vue2-wangeditor-demo.git
- 步骤二：设置maxLength属性
- 步骤三：设置内容

**Comment by wangfupeng1988** [comment]
改问题已经记录下了。

统一在这里跟踪 https://github.com/wangeditor-team/wangEditor/issues/4078

**Comment by sksksksskskskssks** [comment]
这个属性是自动开启吗? 我这没有开启 maxLength 都存在这个 bug

**Comment by sksksksskskskssks** [comment]
还有就是在每次编辑内容时, 哪怕我没有动任何一个元素直接点击编辑在<视频|图片|分割线>这些元素下面都会多出现一对 <p><br></p> 标签

**Comment by cycleccc** [comment]
@sksksksskskskssks 视频我在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next)  做了处理，现在不会换行了，图片没有这个问题，分割线的话我后面看看可以加上。具体可以在 [demo](https://cycleccc.github.io/demo/) 试试。

**Comment by sksksksskskskssks** [comment]
@cycleccc 是要转用这个版本的编辑器吗,  以下是我当前用的出现这些 bug 的版本
    "@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-vue": "^5.1.12",

**Comment by sksksksskskskssks** [comment]
@cycleccc 请问一下就是在没有输入内容的情况下自动生成标签 `<p><br></p>` 的问题还存在这个版本中吗

**Comment by cycleccc** [comment]
@sksksksskskskssks 看这个沙盒 demo，取最新版替换即可。
不是自动生成标签，是原来的空`<p><br></p>`没有删掉，转而在下一行生成了新元素。
分割线还没处理，我后面加上，原理相同，没判断空p删除。

**Comment by sksksksskskskssks** [comment]
@cycleccc 哦哦 好的 谢谢解惑

**Comment by cycleccc** [comment]
@sksksksskskskssks 我在 5.3.13 解决了分割线空行的问题。
