### ISSUE TITLE
迁移编辑器,旧数据问题导致报错

### ISSUE THREAD

**Issue by nszm** [wangeditor-team/wangEditor#4366]
## bug 描述

旧数据格式正常但会导致报错:
Error in mounted hook: "Error: Cannot find a descendant at path [0,1] in node

数据如下
```
<p>
    <span style=\"background-color: #C0504D;\">
        <span style=\"background-color: #C0504D;\">
        <span style=\"background-color: #C0504D;\">
                <span style=\"background-color: #C0504D;\">
                    <span style=\"background-color: #C0504D;\"></span>
                </span>
            </span>
        </span>
    </span>
    <span style=\"background-color: #C0504D;\">xx</span>
    <span style=\"background-color: #C0504D;\">xxx
        <span style=\"background-color: #C0504D;\">xxxx</span>
        <span style=\"background-color: #C0504D;\">xxxxx
            <span style=\"background-color: #C0504D;\">xxxxxx</span>
            <span style=\"background-color: #C0504D;\">xxxxx</span>
        </span>
    </span>
</p>
```

## 你预期的样子是？

不报错正常显示

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

v5

## demo 能否复现该 bug ？

不能

## 最小成本的复现步骤

复制上面代码到数据库

**Comment by wangfupeng1988** [comment]
这种格式的 HTML ，v5 不支持。

**Comment by ningblue** [comment]
我也遇到了 ,
`<p><em>xxxxxxx<br/>/home/xxxxxk/xxxxxk目录下边的<br/>xxxxxk.tar.gz<br/></em><em>xxxxxk.tar.gz<br/>xxxxxk.txt<br/>xxxxxk.txt<br/></em><em>xxxxxk.csv<br/></em><em>xxxxxk.csv<br/></em><em>xxxxxk.csv<br/></em>需要下载</p>`

请问这个有没有什么可以做兼容或者兜底的办法

**Comment by wangfupeng1988** [comment]
@ningblue  使用官网 demo https://www.wangeditor.com/demo/index.html ，在浏览器控制台输入如下代码，没有问题

```js
const html = `<p><em>xxxxxxx<br/>/home/xxxxxk/xxxxxk目录下边的<br/>xxxxxk.tar.gz<br/></em><em>xxxxxk.tar.gz<br/>xxxxxk.txt<br/>xxxxxk.txt<br/></em><em>xxxxxk.csv<br/></em><em>xxxxxk.csv<br/></em><em>xxxxxk.csv<br/></em>需要下载</p>`

editor.setHtml(html)
```

**Comment by ningblue** [comment]
`editor.setHtml(html)` 
是的  加了这一行代码 就兼容了~ 多谢

**Comment by ktaoing** [comment]
> `editor.setHtml(html)` 是的加了这一行代码就兼容了~多谢

这句代码加到哪里呢？

**Comment by ktaoing** [comment]
> @ningblue 使用官网 demo https://www.wangeditor.com/demo/index.html ，在浏览器控制台输入如下代码，没有问题
> 
> ```js
> const html = `<p><em>xxxxxxx<br/>/home/xxxxxk/xxxxxk目录下边的<br/>xxxxxk.tar.gz<br/></em><em>xxxxxk.tar.gz<br/>xxxxxk.txt<br/>xxxxxk.txt<br/></em><em>xxxxxk.csv<br/></em><em>xxxxxk.csv<br/></em><em>xxxxxk.csv<br/></em>需要下载</p>`
> 
> editor.setHtml(html)
> ```

请问如何兼容呢？
