### ISSUE TITLE
咨询：想在v4中给表格添加 拖拽列宽的功能。想问问 添加这个功能的 大概思路，流程该怎么做。感谢。

### ISSUE THREAD

**Issue by zz925625** [wangeditor-team/wangEditor#4369]
望大佬指点一下。感谢。感谢。

**Comment by wangfupeng1988** [comment]
v4 的表格就是纯 HTML 的 table 。

所以你百度搜“JS table 拖拽列宽”即可找到常见的开发思路。

**Comment by zz925625** [comment]
我看了v5的表格。想在v4中也实现一下，但v4的table是通过insserHtml直接插入的。对应的事件不知道该怎么添加进去，就是事件不是很好加。想请教个大概思路。

**Comment by wangfupeng1988** [comment]
v4 表格会动态插入、动态删除，这种情况下绑定 DOM 用事件代理（也叫事件委托）比较合适。

可以借这个思路继续想想
