### ISSUE TITLE
编辑器编辑文字时，如果选中修改 光标会跳动，会将之前的文字插入到意想不到的位置，或者将字删除

### ISSUE THREAD

**Issue by 5852305** [wangeditor-team/wangEditor#4372]
## bug 描述

编辑器编辑文字时，如果选中修改 光标会跳动，会将之前的文字插入到意想不到的位置，或者将字删除

## 你预期的样子是？

选中修改内容时，光标不跳动，并保留修改内容

## 系统和浏览器及版本号

- 操作系统  win10
- 浏览器和版本  chrome 102.0.5005.63

## wangEditor 版本

^5.0.0

## demo 能否复现该 bug ？

能

![QQ录屏20220615111235_](https://user-images.githubusercontent.com/19222263/173730078-91111d01-7fca-4d9e-ac0e-38883655742c.gif)

**Comment by wangfupeng1988** [comment]
之前已记录过一个类似问题。

统一在这个 issue 跟踪吧 https://github.com/wangeditor-team/wangEditor/issues/4183
