### ISSUE TITLE
上传视频失败后，再次上传提示 “you can oly upload 1 file” ，从官方源码中查询到上传成功后调用了 removeFile

### ISSUE THREAD

**Issue by namesfang** [wangeditor-team/wangEditor#4374]
## 问题描述

上传视频失败后，再次上传提示 “you can oly upload 1 file” ，从官方源码中查询到上传成功后调用了 removeFile
## wangEditor 版本
v5

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
- 配置上传数量为1，大小为10M；
- 准备2个视频，1个大于10M的，一个小于10M的
- 先上传一个大于10M的视频，然后提示文件超过设置大小，此时不要刷新页面，再上传小于10M的那个

**Comment by Gavin-yh** [comment]
![image](https://user-images.githubusercontent.com/40813001/175263464-0f78bb1b-9ccb-4071-998c-861fe21af107.png)

**Comment by Gavin-yh** [comment]
![image](https://user-images.githubusercontent.com/40813001/175263510-787c4851-10d8-4d4f-a8e8-96fd4d51d7b4.png)
你可以试下这个地址(https://github.com/wangeditor-team/server)的上传demo, 按照步骤没有复现。
