### ISSUE TITLE
v4 版本是否有通过内容获取标题的api

### ISSUE THREAD

**Issue by dengshicheng1996** [wangeditor-team/wangEditor#4377]
## 问题描述
编辑正文，获取改正文段落所属的标题。 如没有api 能否提供解决思路（目前想的是通过offsetTTop来实现）

## wangEditor 版本
4.5.3

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

- 步骤一  存在标题段落等较多的内容
- 步骤二  点击或编辑某段落，获取到段落对应节点的标题

**Comment by wangfupeng1988** [comment]
参考这个 demo https://codepen.io/xiaokyo-the-bold/pen/zYKvgPj
