### ISSUE TITLE
可否增加工具栏配置传入自定义对象自定义默认菜单的功能

### ISSUE THREAD

**Issue by eveningwater** [wangeditor-team/wangEditor#4378]
## 功能描述

toolbarKeys: [
        {
            key: 'fontSize', // 必填
            title: '字号', // 可选
            iconSvg: '<svg>....</svg>', // 可选
        },
        // 继续配置其他菜单...
    ]

如果不传入menuKeys，就表示修改默认字号的配置，iconSVG修改默认字号的下拉图标，title修改为显示标题，例如像fontSize这种可供选择的还可以增加一个自定义配置选择列表，例如:fontSizeList:["13px","14px" ....]
## 提炼几个功能点

-  传入自定义对象配置已知的工具菜单
-  可修改标题和图标
-  对于可供选项的列表也可以自定义配置

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
抱歉，暂不支持。

如有需要自定义，可以去自定义菜单 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E8%8F%9C%E5%8D%95 

按设计原则来说，要对扩展开放、对修改封闭，越改越乱。

**Comment by shadowDDD** [comment]
> 抱歉，暂不支持。
> 
> 如有需要自定义，可以去自定义菜单 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E8%8F%9C%E5%8D%95
> 
> 按设计原则来说，要对扩展开放、对修改封闭，越改越乱。

然而实际上很多自定义需求的工具栏需要修改图标尺寸等，并且工具栏并没有配置已有功能比如插入链接的外部调用事件，这对diy开发造成了极大的困扰，在除你自己的工具栏位置以外的地方想要调用工具栏内部事件很难，这不是封闭修改，这是过度封装，只是个人建议，并不能要求别人只使用你的图标和默认尺寸

**Comment by huangjiaxing** [comment]
+1，希望提供修改工具栏的文案功能。
