### ISSUE TITLE
设置了maxLength 属性，数据回显，有多个表格时显示样式发生合并

### ISSUE THREAD

**Issue by lcmomo** [wangeditor-team/wangEditor#4379]
## bug 描述

*设置了maxLength 属性后，数据回显时，有多个表格时显示样式发生合并*

## 你预期的样子是？

*设置了maxLength ，数据回显时，多个表格样式显示正常*

## 系统和浏览器及版本号

- 操作系统
macOs Catalina 10.15.7
- 浏览器和版本
chrome 102.0.5005.61

## wangEditor 版本

*V5.1.1*

## demo 能否复现该 bug ？

不能（官网没有提供保存数据并回显的demo）

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
编辑器配置maxLength属性
- 步骤二
编辑器中插入多个表格
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/39258456/173806449-2e641640-dea2-4dbb-b900-df2b47086818.png">

- 步骤三
保存编辑器内容（localStorage或者数据库）
- 步骤四
- 回显时，多个表格样式发生合并，只显示为一个hoverbar
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/39258456/173807528-51dbe431-b6a3-42be-b077-4660ee9abfa2.png">

**Comment by wangfupeng1988** [comment]
本地 example 即可复现

**Comment by lcmomo** [comment]
> 本地 example 即可复现

你好，请问下这个大概什么时候可以修复，或者是否有可以临时规避的方法呢

**Comment by wangfupeng1988** [comment]
修复时间不确定。

建议你先临时去掉 maxLength 功能

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本即可
