### ISSUE TITLE
customPaste自定义粘贴里，复制过来的样式内容，打印ClipboardEvent html看样式是有的，但是重新赋值到编辑器就样式丢失

### ISSUE THREAD

**Issue by daifawang** [wangeditor-team/wangEditor#4380]
customPaste自定义粘贴处理，获取粘贴的 htmlevent.clipboardData.getData('text/html')，打印看有样式，然后重新editor.setHtml赋值到编辑器里时候样式又丢了

**Comment by wangfupeng1988** [comment]
看 setHtml 的文档 https://www.wangeditor.com/v5/API.html#sethtml

wangEditor 目前不能支持任意的 HTML 格式，只识别自己产出的 HTML 格式。
例如 `<strong>1234</strong>` 可识别为加粗，而 `<span style="font-weight: bold;">1234</span>` 就不识别。

**Comment by lyy199212** [comment]
用dangerouslyInsertHtml 可以不？我试着也不好使呢

**Comment by wangfupeng1988** [comment]
> 用dangerouslyInsertHtml 可以不？我试着也不好使呢

dangerously —— 危险的，不能保证语义正确。

如果 dangerouslyInsertHtml 好使的话，那 setHtml 也就支持了，没必要双标。
