### ISSUE TITLE
粘贴图文格式的html内容，文本会渲染两次

### ISSUE THREAD

**Issue by yonglijia** [wangeditor-team/wangEditor#4381]
## bug 描述

`<p class="image-wrapper" style="color: rgb(0, 0, 0); PingFang SC&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><img src="https://wdoc-76491.picgzc.qpic.cn/MTY4ODg1ODI2MTI0NDM5Mg_97643_lIf1gbX84kT2VICK_1655280923?w=788&h=602" width="577" height="39px" style="margin-left: 0px; margin-top: 0px; width: 577px; height: 39px; max-width: 604.76px;"></p><span style="color: rgb(0, 0, 0); PingFang SC&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline-block;">测试文本</span>`

## 你预期的样子是？
预期：
<img width="720" alt="image" src="https://user-images.githubusercontent.com/7580923/173893404-0a1cccba-cfb9-4f52-999b-41b10220789a.png">
实际
<img width="735" alt="image" src="https://user-images.githubusercontent.com/7580923/173893360-c94c38ab-ff2e-4177-865d-d0f15bc7e433.png">

## wangEditor 版本

V5.1.0

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤
在这https://www.wangeditor.com/demo/set-html.html就可以复现
把我上面的html片段输入进去，点击setHTML就可以复现

**Comment by yonglijia** [comment]
这个有什么解决方案吗?

**Comment by wangfupeng1988** [comment]
这是一个 bug ，接下来排队解决。不过时间无法给出，业余时间维护，还请体谅。

**Comment by wangfupeng1988** [comment]
经排查，原因是 wangEditor 不支持这种 HTML 的格式：`<span>` 裸露在外面，没有被 `<p>` 包裹。

```html
<p>123 <img src="xxx"/></p><span>hello</span>
```

导致了插入时报错，然后重新插入了一些文本内容，源码如下：

```js
    // ------------- 将 nodes 插入到编辑器 -------------
    if (nodes.length) {
      try {
        e.insertFragment(nodes) // 插入 nodes
      } catch (ex) {
        e.insertText(getPlainText($div[0])) // 意外情况，则插入纯文本
      }
    }
```

综合考虑了下，目前不打算解决这个问题：
- 如果为了解决这个问题把 `catch` 去掉，可能会导致其他新的问题
- 只是重复粘贴了还好（删掉就行），没有丢失内容，也没有报错，没有太严重的影响

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本即可
