### ISSUE TITLE
销毁wangEditor后重新对同一个选择器报错

### ISSUE THREAD

**Issue by chengjunjian2020** [wangeditor-team/wangEditor#4382]
## bug 描述

销毁wangEditor后重新对同一个选择器报错
![image](https://user-images.githubusercontent.com/40468022/173979126-dde1d417-5fe1-4f9d-921b-2a8dbfcf7786.png)

## 你预期的样子是？

期望正常显示不报错

## 系统和浏览器及版本号

- windows10
- chrome 102.0.5005.63

## wangEditor 版本

*5.1.1

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 新建页面然后创建
- 
![image](https://user-images.githubusercontent.com/40468022/173979347-b17a0eff-edbf-4c56-b77c-8a1d905127ff.png)

- 步骤二 切换到另外一个页面又切换回来如果传进来的编辑器DOMid名称一样则报错
- 销毁之后也是这样

**Comment by wangfupeng1988** [comment]
销毁的方式，参考这个 demo https://www.wangeditor.com/v5/for-frame.html#react
