### ISSUE TITLE
有序列表  复制 黏贴 BUG

### ISSUE THREAD

**Issue by liujian891010** [wangeditor-team/wangEditor#4384]
## bug 描述

*有序列表A & B ， 复制B去覆盖A   会导致A 缩进异常  且 返回的html 再次渲染  A丢失~~*

## 你预期的样子是？

*缩进正常 渲染返回的html  两个列表都显示*

## 系统和浏览器及版本号

- windows 11
- chrome 102.0.5005.115

## wangEditor 版本

*5.0.1*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一   有序列表 A & B
- 步骤二   复制B去覆盖A
- 步骤三   输出的HTML 再渲染
- 步骤三   实际- A列表不显示（多了一层 ol 标签）  预期-正常显示列表A & B

**Comment by wangfupeng1988** [comment]
> 步骤一 有序列表 A & B
> 步骤二 复制B去覆盖A

这两步没看懂，具体咋操作？

**Comment by liujian891010** [comment]
> > 步骤一 有序列表 A & B
> > 步骤二 复制B去覆盖A
> 
> 这两步没看懂，具体咋操作？

1、新建两个有序列表
2、选中有序列表B  复制
3、选中有序列表A  黏贴
4、渲染返回的html 
5、有序列表A 丢失？

**Comment by wangfupeng1988** [comment]
你把 B 粘贴到 A 上，不就把 A 覆盖了吗，所以 A 就丢失了呀。

（我可能还是没明白你的操作步骤）

**Comment by wzyMaco** [comment]
确实有bug。
新建： ![image](https://user-images.githubusercontent.com/20431837/175198922-8b30f6c3-edcc-43b3-8c7e-0df13e8eb7c0.png)
选中B复制到A，序号都变成了1，且有缩紧：
![image](https://user-images.githubusercontent.com/20431837/175199103-d06ac72d-c543-4bcf-93d8-fe8149465355.png)
撤销后，B会消失：
![image](https://user-images.githubusercontent.com/20431837/175199404-3fdd37d2-e88c-415d-826c-54af53c4db33.png)

**Comment by wangfupeng1988** [comment]
@wzyMaco 好的，我标记为 bug

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/wangEditor/issues/4645 一起排查

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本
