### ISSUE TITLE
自定义功能成功注册了 但是工具栏没有显示

### ISSUE THREAD

**Issue by blackstar-dzp** [wangeditor-team/wangEditor#4385]
## 问题描述
自定义功能成功注册了 但是工具栏没有显示
*请输入遇到的问题...*
自定义功能成功注册了 但是工具栏没有显示
![image](https://user-images.githubusercontent.com/65488603/174025663-28bb692e-243e-4c77-9c60-f6b17abd8458.png)
![image](https://user-images.githubusercontent.com/65488603/174025844-610e4105-25dc-4425-8c9c-44d170c7ba96.png)
![image](https://user-images.githubusercontent.com/65488603/174025928-a0f3e79d-7846-46b4-ab9f-241f3ab61f4a.png)

## wangEditor 版本
5.1.0
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考这个 demo 源码写一个菜单，看能行吗？

**Comment by blackstar-dzp** [comment]
> 参考这个 demo 源码写一个菜单，看能行吗？

哪个demo呢 我是参考引用那个demo写的.

**Comment by wangfupeng1988** [comment]
@blackstar-dzp 抱歉哈，忘记贴链接了。

这个 demo https://www.wangeditor.com/demo/extend-menu.html
