### ISSUE TITLE
一段html代码，里面的图片为什么加载不出来

### ISSUE THREAD

**Issue by jaychou2012** [wangeditor-team/wangEditor#4388]
## 问题描述

*一段html代码，里面的图片为什么加载不出来*

## wangEditor 版本

*5.1.1*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 将这段代码赋值为编辑器文本：
<p>比如我们常见的“龇牙笑脸”的表情，在 iPhone 上是这样子的：</p> 
   <p><img class="content-image" src="http://pic4.zhimg.com/70/442390e302130862836a141eab089c9f_b.jpg" alt="" /></p> 

就会出现图片无法加载

**Comment by wangfupeng1988** [comment]
你说的“一段html代码”，这个代码是什么？贴出来看看
