### ISSUE TITLE
被section标签和a标签包裹的img标签会被过滤掉，导致很多图片都无法黏贴

### ISSUE THREAD

**Issue by lbnnbs** [wangeditor-team/wangEditor#4389]
## bug 描述

*v5版本，被section标签和a标签包裹的img标签会被过滤掉，导致很多图片都无法黏贴；v4版本没有这个问题*

## 你预期的样子是？

*被section标签和a标签包裹的img标签不要过滤掉，或者提供一个配置项，能按需求配置安全标签过滤*

## 系统和浏览器及版本号

- win10
- firefox 101.0.1

## wangEditor 版本

*v5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/

## 最小成本的复现步骤

（复制黏贴百度或者微信或者新浪等网站的带图片文章，只要文章内图片是被section标签或a标签包裹的，就无法完成黏贴）

**Comment by wangfupeng1988** [comment]
> v5版本，被section标签和a标签包裹的img标签会被过滤掉，

v5 不支持 a 标签里的 img 。

section 标签的可以转换为 div 处理，这个后期可以优化。
