### ISSUE TITLE
鼠标点击Toolbar 浏览器报错

### ISSUE THREAD

**Issue by beihu99** [wangeditor-team/wangEditor#4393]
## 问题描述

VUE3项目，鼠标点击到toolbar时正常是会获取焦点，但是现在点击之后取消了整个富文本的选中状态，并且控制台报了Unable to preventDefault inside passive event listener invocation错误

## wangEditor 版本

 "@wangeditor/editor": "^5.1.1",
"@wangeditor/editor-for-vue": "^5.1.11",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

在项目中使用wangEditor就会报错，配置完全按照vue3在线demo配置
我尝试新创建的基础VUE3项目 然后在使用wangEditor，就无此问题，希望可以在这里解惑，感谢
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/76896485/174417430-75935294-6118-4f2e-a808-b2c32f69fb8f.png">

**Comment by wangfupeng1988** [comment]
用官网 Vue3 的 demo 能否复现这个问题？
https://www.wangeditor.com/v5/for-frame.html#vue3

**Comment by beihu99** [comment]
> 用官网 Vue3 的 demo 能否复现这个问题？ https://www.wangeditor.com/v5/for-frame.html#vue3

我尝试新创建一个基础VUE3的项目，并使用v3的demo进行配置则无此问题
我又尝试将生产的项目App.vue文件中只显示富文本组件，也会出现此问题

**Comment by beihu99** [comment]
问题已解决 是由于项目中引入了 default-passive-events  这个插件导致 注释掉就解决了上述问题
