### ISSUE TITLE
wangEditor v5 图标可自定义替换

### ISSUE THREAD

**Issue by shy5** [wangeditor-team/wangEditor#4395]
## 功能描述

富文本编辑器 默认图标icon现在不能替换，希望可以支持自定义图标

## 提炼几个功能点

- 自定义图标替换

**Comment by wangfupeng1988** [comment]
好的，我记录下吧，排队开发。

这个问题已经有不少人提过了

**Comment by wangfupeng1988** [comment]
@shy5 还想问下，你具体是什么需求，需要替换哪些菜单的 icon ？

目前这些默认的 icon ，那个不满足你的要求？

**Comment by maopixin** [comment]
> @shy5 还想问下，你具体是什么需求，需要替换哪些菜单的 icon ？
> 
> 目前这些默认的 icon ，那个不满足你的要求？

我觉得听满足的，但是产品说：想想办法，不能换也得换
他们的眼睛跟程序员的不一样，我觉得有个图标就行 - -

**Comment by Jess-2021** [comment]
> 

同个类型产品经理

**Comment by Jess-2021** [comment]
> 我觉得挺满足的，但是产品说：想想办法，不能换也得换 他们的眼睛跟程序员的不一样，我觉得有个图标就行 - -

同个类型产品经理
但同时也理解，如果在不同风格的应用上，确实是需要改icon去适应的。
