### ISSUE TITLE
“自定义扩展新功能”部分文档内容少，难以快速自定义

### ISSUE THREAD

**Issue by LiMao00** [wangeditor-team/wangEditor#4397]
## 问题描述

*“自定义扩展新功能”部分文档内容少，难以快速自定义，如如何自定义标签、如何作为行内元素插入、自定义标签的光标问题（是否两侧需要插入空格）*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 完善文档
- 步骤二 代码案例
- 步骤三 或添加 demo 页面

**Comment by wangfupeng1988** [comment]
你说的这都是细节问题。如果都写在文档中，那文档就完全不可读了。

遇到细节问题在这里提问，我每天都会解答。

**Comment by LiMao00** [comment]
> 你说的这都是细节问题。如果都写在文档中，那文档就完全不可读了。
> 
> 遇到细节问题在这里提问，我每天都会解答。

感谢回复！

请问如果想添加自定义标签在当前段落（作为行内元素），是否有其他的配置项
```typescript
function renderSelect(elem: SlateElement, children: VNode[] | null, editor: IDomEditor): VNode {
  const vnode = h('select', {}, [
    h('option', { props: { value: 'volvo' } }, 'volvo'),
    h('option', { props: { value: 'saab' } }, 'saab'),
    h('option', { props: { value: 'mercedes' } }, 'mercedes'),
    h('option', { props: { value: 'audi' } }, 'audi'),
  ]);

  return vnode;
}
const renderElemConf = {
  type: 'sele',
  renderElem: renderSelect,
};
Boot.registerRenderElem(renderElemConf);

<Button
  onClick={() => {
    const node = { type: 'sele', children: [{ text: '' }] };
    editor?.insertNode(node);
  }}
>
  插入 select
</Button>
```
现在的情况是：点击插入，另开新的一个段落
当然我也觉得少了很多东西，可惜查阅文档难以找到答案，请求指出问题，谢谢

**Comment by wangfupeng1988** [comment]
作为行内元素（inline）需要自定义插件，参考代码
https://github.com/wangeditor-team/wangEditor-plugin-mention/blob/main/src/module/plugin.ts#L64

**Comment by LiMao00** [comment]
好的 感谢
