### ISSUE TITLE
上传图片到服务器无法传变量值

### ISSUE THREAD

**Issue by qwangyoucaiq** [wangeditor-team/wangEditor#4399]
## 问题描述
上传图片时，想要在配置里写入变量，但是获取不到this，就无法传值
*请输入遇到的问题...*
![U0 $%0QU`NE3W( GIL(AG)W](https://user-images.githubusercontent.com/88196708/174560245-6e65dd8a-2771-41e9-a5a2-5c08283a1cc8.png)

## wangEditor 版本
^5.1.1
*请输入内容……*
想知道怎么获取值
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是，但是没有找到相关解释
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
在vue中，在date中配置上传图片的信息，然后在上传图片到服务器可以接收父组件的值作为变量
- 步骤一
- 步骤二
- 步骤三

**Comment by Gavin-yh** [comment]
你这里说的this，是指想获取当前vue实例？如果是的话，你这个 const me = this应该放在最外出，而不是放在customUpload这个函数里，这个是内部调用的一个函数。

**Comment by qwangyoucaiq** [comment]
> 你这里说的this，是指想获取当前vue实例？如果是的话，你这个 const me = this应该放在最外出，而不是放在customUpload这个函数里，这个是内部调用的一个函数。

谢谢你，解决了，就是你说的这样，感谢感谢
