### ISSUE TITLE
Uncaught Error: Cannot merge the node at path [0,1] with the previous sibling because it is not the same kind

### ISSUE THREAD

**Issue by Black-Jacki** [wangeditor-team/wangEditor#4400]
## bug 描述

*从^0.15.15版本升级到5.1.1版本后原先的html会报错*
*Uncaught Error: Cannot merge the node at path [0,1] with the previous sibling because it is not the same kind*

## 你预期的样子是？

**

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
- Chrome最新版

## wangEditor 版本

*^5.1.1*

## demo 能否复现该 bug ？

没试过

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

看看这段文本在5.1.1版本的编辑器里是否会报错
```html
<p><span style=\"font-size: 14pt; font-family: 宋体;\">一张50元可以换成</span><span style=\"color: rgb(255, 0, 0);\">（</span><input data-w-e-type=\"fill-blank\" width=\"36px\" index=\"0\" shape=\"paren\"/><span style=\"color: rgb(255, 0, 0);\">）</span>&nbsp;<span style=\"font-size: 14pt; font-family: 宋体;\">张10元，或</span><span style=\"color: rgb(255, 0, 0);\">（</span><input data-w-e-type=\"fill-blank\" width=\"36px\" index=\"1\" shape=\"paren\"/><span style=\"color: rgb(255, 0, 0);\">）</span>&nbsp;<span style=\"font-size: 14pt; font-family: 宋体;\">张5元。</span></p>
```

index.esm.js?cb23:4618 Uncaught Error: Cannot merge the node at path [0,1] with the previous sibling because it is not the same kind: {"type":"formula","value":"dm^2","children":[{"text":""}]} {"text":"   5000 "}

![image](https://user-images.githubusercontent.com/63303518/174606739-a23c4757-0eae-4cbe-a18d-3d9d972ade18.png)

**Comment by Black-Jacki** [comment]
版本回退到老版本就没有问题了，兼容性上应该需要再看一下

**Comment by wangfupeng1988** [comment]
`data-w-e-type=\"fill-blank\"` 这是什么？你自定义的节点吗？

**Comment by lg-git-a** [comment]
怎么回事，解决了吗
