### ISSUE TITLE
无法在 Edge 浏览器下使用，谷歌就没用问题。

### ISSUE THREAD

**Issue by zeroone-code** [wangeditor-team/wangEditor#4401]
我是直接引用的，Edge 无法使用，center8.0  thinkphp6 
<script src="/static/index/js/editor/index.js"></script>

报错：
SCRIPT1028: SCRIPT1028: Expected identifier, string or number

```
    const prevLocale = this.locale;
    this.locale = { ...prevLocale,   //edge 错误指向这行
      strings: { ...prevLocale.strings,
        ...locale.strings
      }
    };
```

**Comment by Gavin-yh** [comment]
可以提供更加完整的代码吗

**Comment by wangfupeng1988** [comment]
官网 demo 可以正常访问吗？

**Comment by zeroone-code** [comment]
> 官网demo可以正常访问吗？

不可以，一样的。

**Comment by zeroone-code** [comment]
> > 官网demo可以正常访问吗？
> 
> 不可以，一样的。可能这个浏览器版本太低了，不清楚，没测试过最新的edge浏览器。 版本是 Microsoft Edge 44.19041.1.0 才装的破解破解系统，百度搜索排前面的，那么估计不少人都是这个版本。

安装新版本edge 正常了，我自己看看，能不能判断浏览器版本算了
