### ISSUE TITLE
解析markdown语法

### ISSUE THREAD

**Issue by kawei3773** [wangeditor-team/wangEditor#4402]
## 功能描述
通过markdown语法来保存内容可以减少数据容量，对于一些markdown爱好者操作起来也比较方便

## 提炼几个功能点

- 内容可以转为markdown语法
- 编辑器可以解析markdown语法

## 可参考的案例

- remirror的MarkdownExtension

**Comment by wangfupeng1988** [comment]
可使用 markdown 插件 https://www.wangeditor.com/v5/plugins.html
