### ISSUE TITLE
英文之间的空格是 &nbsp; 会导致显示时无法自动换行

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#4403]
## bug 描述

在编辑器连续输入英文，如下图。显示时不能默认换行

<img width="1737" alt="image" src="https://user-images.githubusercontent.com/9583120/174706700-c9e9cb52-0e87-4bf0-9c5e-fceae4ed1724.png">

## 你预期的样子是？

英文可以自动换行

## 系统和浏览器及版本号

- Mac OS
-  Chrome

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能 ，如上面的截图

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 用这个 demo  http://localhost:8881/examples/default-mode.html 
- 连续输入英文，看下面的显示

**Comment by liuxueyong123** [comment]
同遇到了这个问题，目前我只能采用 `overflow-wrap: break-word;` 来解决，但是显示出来的有些英文单词被强制换行了

**Comment by wangfupeng1988** [comment]
问题已经解决，下载 https://www.npmjs.com/package/@wangeditor/editor  最新版本即可
