### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Ym-wei** [wangeditor-team/wangEditor#4404]
## bug 描述
`  const editorConfig = {
    placeholder: '请输入内容...',
    MENU_CONF: {
      uploadImage: {
        async customUpload(file, insertFn) {
          const { data } = await apiCommonUploadFile(file)
          const { fileUrl, fileName } = data
          // file 即选中的文件
          // 自己实现上传，并得到图片 url alt href
          // 最后插入图片
          insertFn(fileUrl, fileName, null)
        }
      }
    }
  }`

使用自定义上传图片报错
![image](https://user-images.githubusercontent.com/81805625/174739112-e52cc78e-18f6-42de-bc7a-055b7db42d5b.png)

## 你预期的样子是？
成功回显在编辑器上
*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by Ym-wei** [comment]
此问题已处理, 是因为我的图片地址有问题

**Comment by ZhangYC193** [comment]
> 此问题已处理, 是因为我的图片地址有问题

你好，我也遇见了。大概是什么原因导致的呢
