### ISSUE TITLE
切换语言时无法实时更新

### ISSUE THREAD

**Issue by justiceti** [wangeditor-team/wangEditor#4406]
## 问题描述

*请输入遇到的问题...*

在useEffect中使用i18nChangeLanguage切换语言无法实时更新
![image](https://user-images.githubusercontent.com/13634238/174784085-dac45776-96e0-45f9-be35-af1ffdc63448.png)

## wangEditor 版本

5.1.1

## 是否查阅了文档 ？

是

我查阅了文档及相关issue发现目前还是没有在切换语言后实时更新是吗？或者有什么曲线救国的方案吗？

**Comment by wangfupeng1988** [comment]
> 切换语言时无法实时更新

这个不支持

> 什么曲线救国的方案吗？

切换语言时，重新销毁、创建编辑器。
