### ISSUE TITLE
is:issue is:open 5.1版本 在VUE3中 插入网络图片，报错：Uncaught Error: Cannot find textarea instance by editor

### ISSUE THREAD

**Issue by jiacode** [wangeditor-team/wangEditor#4407]
is:issue is:open 5.1版本 在VUE3中 插入网络图片，报错：Uncaught Error: Cannot find textarea instance by editor

**Comment by wangfupeng1988** [comment]
请按照 issue 模板重新提交 issue 。详细描述复现步骤。

**Comment by wangfupeng1988** [comment]
另：在 vue3 官网 demo 中能否复现这个问题？

https://www.wangeditor.com/v5/for-frame.html#vue3

**Comment by jiacode** [comment]
谢谢，官网上没有问题，换了另外一种写法，解决了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月22日(周三) 下午2:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wangeditor-team/wangEditor] is:issue is:open 5.1版本 在VUE3中 插入网络图片，报错：Uncaught Error: Cannot find textarea instance by editor (Issue #4407)




 
另：在 vue3 官网 demo 中能否复现这个问题？
 
https://www.wangeditor.com/v5/for-frame.html#vue3

**Comment by axolo** [comment]
this.editor = Object.seal(editor)

**Comment by tengerfly** [comment]
> this.editor = Object.seal(editor)
你好，请问你这个是将editor实例做Object.seal处理吗？

**Comment by yuanzhiyong123** [comment]
> 谢谢，官网上没有问题，换了另外一种写法，解决了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月22日(周三) 下午2:44 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wangeditor-team/wangEditor] is:issue is:open 5.1版本 在VUE3中 插入网络图片，报错：Uncaught Error: Cannot find textarea instance by editor (Issue #4407) 另：在 vue3 官网 demo 中能否复现这个问题？ https://www.wangeditor.com/v5/for-frame.html#vue3 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

换了什么写法解决的？我也遇到这个问题了

**Comment by hjiachuang** [comment]
虽然已经被关闭了的旧帖，但是还是觉得有必要说一下给后面踩坑的人看。不一定每个人的原因跟我一样，仅供参考。
盲猜，在vue3中，用了const editor = ref() ，然后在onMounted中把createEditor直接赋值给editor.value。（反正我是这样，除了插入链接报这个错误，其他还挺正常的，没试过插入网络图片和视频，可能只有在需要弹出model的时候会报错，也就插入网络图片，插入网络视频和插入链接这三个会弹model吧。）
废话说多了，说下怎么解决，就是在onMounted的时候，不需要把createEditor的结果返回给editor.value，但是你要存起来，给后面createToolbar用。
然后在createEditor的config中，不是有个onCreated回调嘛，可以拿到创建完毕的editor对象，在这个回调里，把这个editor赋值给你刚才的Ref(editor)。
图片看得懂看，看不懂我也没办法了。
![image](https://github.com/wangeditor-team/wangEditor/assets/37433108/3ba73934-5b48-4c9c-b87a-2ef7a62c3879)

**Comment by enjoy-myLife** [comment]
> 的config中，不是有个onCreated回调嘛，可以拿到创建完毕的editor对象，在这个回调里，把这个editor赋值给你刚才的Ref(editor)。

你解决了这个问题了嘛，目前看下来应该是editor的实例在onCreated之后又发生了变化，导致后面一些列的问题，我这边用ref和shallowRef分别取存储实例之后，后面使用就会有各种错误，你这个Object.seal的原理应该和这个一样

**Comment by promisebai** [comment]
> > 的config中，不是有个onCreated回调嘛，可以拿到创建完毕的editor对象，在这个回调里，把这个editor赋值给你刚才的Ref(editor)。
> 
> 你解决了这个问题了嘛，目前看下来应该是editor的实例在onCreated之后又发生了变化，导致后面一些列的问题，我这边用ref和shallowRef分别取存储实例之后，后面使用就会有各种错误，你这个Object.seal的原理应该和这个一样

官网的vue3示例代码有问题，保存ref的时候，要和vue2一样写：Object.seal(editor)
