### ISSUE TITLE
nuxt的使用

### ISSUE THREAD

**Issue by Katto123** [wangeditor-team/wangEditor#4409]
## 使用nuxt引入的时候遇到了问题

*没有引入成功，不知道是不是因为js文件写错了。
![微信图片_20220622151640](https://user-images.githubusercontent.com/93064650/174968440-8309cf0b-d2c7-4ddf-b073-7cb17eadc605.png)
*

## wangEditor5版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
把你截图代码的第 4 行删掉试试。

**Comment by Katto123** [comment]
> 我修改完后它出现了这个错误
![79316a608fcdbdabdc076684abb8753](https://user-images.githubusercontent.com/93064650/175209504-030f7f59-dbb3-4066-8e24-42915b336369.png)

**Comment by Katto123** [comment]
代码是这样
![b7dd035de8b604a80413b2c4e045d8d](https://user-images.githubusercontent.com/93064650/175209803-9f673626-3e79-42a2-b038-82dba4911f25.png)

**Comment by wangfupeng1988** [comment]
> 我修改完后它出现了这个错误
> ![79316a608fcdbdabdc076684abb8753](https://user-images.githubusercontent.com/93064650/175209504-030f7f59-dbb3-4066-8e24-42915b336369.png)

你说的问题已经复现了，我先标记为 bug ，后面我有时间了看看。

**Comment by wangfupeng1988** [comment]
试试这个方法吧

第一，在 `plugins` 目录下新建 `global.js` ，内容如下

```js
global.document.getElementsByTagName = () => []
global.Element = {}
```

第二，在 nuxt.config.js 中把 global.js 配置到 plugins 中，如

```js
  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    '@/plugins/global.js',
    '@/plugins/antd-ui'
  ],
```

**Comment by clinfc** [comment]
这个问题是你自己错误使用造成的

第一：`Vue.use` 注册的内容必须要带有 `install` 函数，然而 `@wangeditor/editor-for-vue` 并没有做支持，官方文档也没有你这种用法
![image](https://user-images.githubusercontent.com/39868400/179379442-115825f7-6634-45c0-87be-07ffe05a4088.png)
![image](https://user-images.githubusercontent.com/39868400/179379446-b39ae09f-1485-4fd9-8776-12340a783fc5.png)

第二：用法如下
![image](https://user-images.githubusercontent.com/39868400/179379475-a04620e4-3d31-40c6-9ac7-71746dd0d54c.png)

**Comment by Katto123** [comment]
谢谢已经解决啦
![cda34d1f4f399c014ec81d2a6bcc30e](https://user-images.githubusercontent.com/93064650/179659346-3b5e3a7e-f779-4470-84c7-1e2540884544.png)
