### ISSUE TITLE
【问题】编辑器获得焦点时，怎么判断光标的位置是否在内容结尾

### ISSUE THREAD

**Issue by lcmomo** [wangeditor-team/wangEditor#4411]
## 问题描述

*需要再编辑器获得焦点时，判断光标位置，根据不同位置做不同逻辑处理，请问如何判断此时光标位置是否在内容结尾或开头*

## wangEditor 版本

*V5.1.1*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*
编辑器API中未找到相关方法
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
以官网 [demo](https://www.wangeditor.com/demo/) 为例，在浏览器控制台运行如下

```js
const curSelection = editor.selection // 当前选区
const start = wangEditor.SlateEditor.start(editor, []) // 开头选区的位置
const end = wangEditor.SlateEditor.end(editor, []) // 结尾选区的位置
wangEditor.SlateRange.isCollapsed(curSelection) // 判断当前选区是不是合并的（即没有选多个字）
wangEditor.SlatePoint.compare(curSelection.focus, end) // 判断当前选区和结尾是否相等？
wangEditor.SlatePoint.compare(curSelection.anchor, end) // 判断当前选区和开头是否相等？
```

通过以上能力，即可实现你的需求。

另外，如果是 npm 安装，可以这样获取全局变量

```
import { SlateEditor, SlateRange, SlatePoint } from '@wangeditor/editor'
```
