### ISSUE TITLE
v5版本 如何自定义Tooltip

### ISSUE THREAD

**Issue by czlin** [wangeditor-team/wangEditor#4413]
## 问题描述
我想自定义图片点击弹出的Tooltip菜单，v5版本的文档没看到有相关的描述

*请输入遇到的问题...*
我想自定义图片点击弹出的Tooltip菜单，v5版本的文档没看到有相关的描述

## wangEditor 版本
v5.0

*请输入内容……*
我想自定义图片点击弹出的Tooltip菜单，v5版本的文档没看到有相关的描述

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考这里 https://www.wangeditor.com/v5/editor-config.html#hoverbarkeys
