### ISSUE TITLE
希望支持图片能设置link

### ISSUE THREAD

**Issue by hhllee** [wangeditor-team/wangEditor#4414]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
支持。参考 demo https://www.wangeditor.com/demo/ 

如下图

<img width="433" alt="image" src="https://user-images.githubusercontent.com/9583120/175502950-555864ee-8e76-4912-9570-2ab88aa5e80a.png">

**Comment by hhllee** [comment]
是我描述不准确  希望支持如下结构
```
<p><a href="xxxx"><img src="xxxxxx" alt="" /></a></p>
```

**Comment by wangfupeng1988** [comment]
@hhllee 自己对编辑器输出的 HTML 处理一下即可，这并不麻烦。
