### ISSUE TITLE
添加图片居中，居左，居右等位置功能

### ISSUE THREAD

**Issue by GLINLIND** [wangeditor-team/wangEditor#4415]
## 功能描述

*图片能设置居中，居左，居右等位置功能*

## 提炼几个功能点

图片能设置居中，居左，居右等位置功能

## 原型图

![image](https://user-images.githubusercontent.com/61455739/175503630-7c09e273-5067-4b0d-809b-17ee4833f901.png)

## 可参考的案例

Summernote编辑器

**Comment by wangfupeng1988** [comment]
暂不支持。

现在编辑器内的图片不能单独存在，它是 `<p>`内部的一部分，所以图片无法单独进行对其，只能设置 `<p>`对其方式
