### ISSUE TITLE
请问在vue3项目中插入链接总会在文末插入

### ISSUE THREAD

**Issue by WangXueJing999** [wangeditor-team/wangEditor#4416]
## 问题描述
在vue3中使用了wangEditor之后，在输入一行文字之后，对这行文字进行加链接，它会在原本的一行上在加一行。2
而且在对一行中的几个文字进行加链接之后他会加在这行的最后
## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？
是

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 输入步骤一，对步骤一进行插入链接
- 步骤二
- 会有2个步骤一
- 步骤三
想知道这种问题可能是什么原因导致的，并且怎么解决比较好，谢谢

**Comment by wangfupeng1988** [comment]
windows10 chrome 浏览器，在[官网 demo](https://www.wangeditor.com/demo/) 并没有复现你的问题。

请继续补充复现步骤，和浏览器信息。
