### ISSUE TITLE
vite打包上传图片失败。s.upload.addEventListener is not a function 本地没有问题

### ISSUE THREAD

**Issue by ssjshengjie** [wangeditor-team/wangEditor#4417]
## bug 描述
 
*请输入内容……*
vite打包 上传图片显示s.upload.addEventListener is not a function 本地没有问题 通过sourcemap 调试 
 xhr.upload.addEventListener('loadstart', () => {
        this.uppy.log('[XHRUpload] started uploading bundle');
        timer.progress();
      }); 这个有问题
## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统 
- window11
- 浏览器和版本
 chrome 103.0.5060.53 
## wangEditor 版本
 5.1.1
*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
-
- 步骤二
- 步骤三

**Comment by liuqh0609** [comment]
麻烦把vite的打包配置发一下

**Comment by wangfupeng1988** [comment]
直接在这几个平台中提供一个 demo 吧（三选一即可）

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by szhang6** [comment]
I hit this issue, too. Is this problem above solved now?

**Comment by szhang6** [comment]
> I hit this issue, too. Is this problem above solved now?

已解决，解决方法参考这里

https://github.com/wangeditor-team/wangEditor/issues/4241
