### ISSUE TITLE
插入在线图片、视频存在存储型和dom型xss

### ISSUE THREAD

**Issue by sakurawaifu** [wangeditor-team/wangEditor#4418]
## bug 描述

插入在线图片、视频存在存储型和dom型xss

## 你预期的样子是？

编辑器对输入的数据进行消毒，过滤掉恶意内容。

数据输入时虽然不会直接触发xss，但如果不经过消毒，直接存储到数据库，会出现存储型xss。
同样的，做预览功能，也需要对数据进行消毒，否则用innerHTML渲染会出现dom型xss。

## 系统和浏览器及版本号

- 操作系统：Windows 10 Version 21H1 (Build 19043.1706)
- 浏览器和版本：Chrome 102.0.5005.115

## wangEditor 版本

v5.1.1

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

1. 步骤一：插入在线图片、视频，链接填入 `" onerror="alert('xss')`
![image](https://user-images.githubusercontent.com/52623903/175552539-bb7c8ffa-62a4-4053-a5b1-bb6009bf5d59.png)

2. 步骤二：
2.1. 存储型：后台不对数据消毒，直接原样返回给前端。前端使用innerHTML渲染内容。
2.2. dom型：前端不对数据消毒，直接使用原始数据渲染到预览框`<div class="preview"></div>`中
![image](https://user-images.githubusercontent.com/52623903/175551850-4fb794c0-30fc-4f8b-b590-27bae707e7af.png)

**Comment by wangfupeng1988** [comment]
可以临时使用 `checkImage` 进行图片链接检查 https://www.wangeditor.com/v5/menu-config.html#%E5%9B%BE%E7%89%87

同理也有 `checkVideo`

**Comment by wangfupeng1988** [comment]
XSS 消毒范围太大了，编辑器无法做到全部。你可以使用专业的 XSS 处理工具来做。例如 https://www.npmjs.com/package/xss
