### ISSUE TITLE
不能同时初始化中文和英文两个版本富文本框

### ISSUE THREAD

**Issue by xiaoxiao0721** [wangeditor-team/wangEditor#4419]
## bug 描述

*初始化富文本组件时，分别设置不同语言，只会渲染一种语言的富文本*

## 你预期的样子是？

*设置对应语言，渲染不同富文本*

## 系统和浏览器及版本号

- 操作系统  window
- 浏览器和版本  google

## wangEditor 版本

*"@wangeditor/editor-for-vue": "^1.0.1",*

## demo 能否复现该 bug ？
不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 页面同时渲染不同语言的富文本
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
抱歉，不支持同时设置多个语言。
