### ISSUE TITLE
当编辑器无内容时手动输入的内容导出为word出现乱码

### ISSUE THREAD

**Issue by zhangyinn** [wangeditor-team/wangEditor#4420]
## 问题描述

*在angular项目中，当且仅当编辑器无内容时，手动输入的内容导出为word后用word打开文件中文部分出现乱码，wps打开是正常的。另，从另外页面添加内容到编辑器中不会乱码，作修改之后导出也不会乱码，但清空以后再输入内容导出也会乱码*

## wangEditor 版本

*^5.1.1*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一：编辑器为空时输入内容
- 步骤二：导出为word
- 步骤三：用office word打开中文为乱码

**Comment by wangfupeng1988** [comment]
> 步骤一：编辑器为空时输入内容

这一步，编辑器产出的 HTML 内容是什么？

**Comment by zhangyinn** [comment]
编辑器空的时候为空字符串，不带标签的
![image](https://user-images.githubusercontent.com/58025249/175770678-7d519fad-bc19-45dc-8df8-bb2c598ad0b2.png)

**Comment by zhangyinn** [comment]
再输入内容是带标签的html内容，但是导出成doc文件中文会乱码
![image](https://user-images.githubusercontent.com/58025249/175771088-d07ab921-f138-4e2f-8eeb-9737a1809288.png)

**Comment by zhangyinn** [comment]
用的file-saver@2.0.5和html-docx-js-typescript@0.1.5导出word操作的

**Comment by wangfupeng1988** [comment]
第一，看你截图用的是 v4 ，而你提问题时说自己是 v5.1.1 ，版本貌似搞错了

第二，编辑器输出的是 `<p>测试测试测试</p>` 这种 HTML 导出 doc 文件都乱码对吧。我理解，编辑器到处这段 HTML 是符合预期的，会不会是你导出逻辑的问题导致的乱码？或者，你直接别用编辑器，就到处一段字符串 `'<p>测试测试测试</p>'`  ，看会不会有乱码？

**Comment by zhangyinn** [comment]
在这里谢谢大佬的回复了，发现应该是html-docx-js-typescript@0.1.5的asBlob直接转有点小bug，改成手动转的就好了，再次感谢！

**Comment by hupan56** [comment]
> 在这里谢谢大佬的回复，发现应该是html-docx-js-typescript@0.1.5的asBlob直接小bug，改成手动转了有点感谢了，再次感谢！

请问如何手动转解决该bug

**Comment by tenglongwentian** [comment]
@hupan56 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

**Comment by tenglongwentian** [comment]
`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">` @hupan56
