### ISSUE TITLE
“自定义扩展”能否插入类似 ant design 的 ui 组件库的组件

### ISSUE THREAD

**Issue by LiMao00** [wangeditor-team/wangEditor#4421]
## 问题描述

*“自定义扩展”能否插入类似 ant design 的 ui 组件库的组件，并保留组件的原有样式与功能。在 draft.js 中可以实现，所以咨询一下。*

## wangEditor 版本

*^5.1.1*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
  如下图，是 draft.js 的实现，可以插入 ant design 的组件：
  
![image](https://user-images.githubusercontent.com/99939885/175756137-73ccc152-f524-4459-be57-c6f28d48bfa6.png)

可以在装饰器里直接设置返回的 dom：
```
component: (props: any) => {
  return (
    <span contentEditable={false} style={{ padding: '0 5px' }}>
      <Select
        placeholder="Select a person"
        onClick={(e) => {
          e.stopPropagation();
        }}
      >
        // ...
      </Select>
    </span>
  );
},
```
以下是 wangEditor 的实现：
![image](https://user-images.githubusercontent.com/99939885/175756166-fda509be-07ef-430f-a85b-a133dec8d701.png)
虽然可以自定义样式，如果可以插入任意 ui 组件，可能更加得心应手。我好像看过某些文本，有某些依赖包可以把 ui 组件的 dom 转换成 snabbdom 的 h() 形式，也可能是记错了，也可能有其他办法，故此咨询一下。

或者在 snabbdom 的文档上，有 jsx 的写法，不知道可否实现我的需求：
![image](https://user-images.githubusercontent.com/99939885/175757716-05bebeb6-4a49-475c-a0ab-6cd5e31e6d65.png)

感谢！

**Comment by wangfupeng1988** [comment]
draft.js 是直接基于 React 的，它当然可以支持 React 所有的能力，包括 antd

但 wangEditor 不是基于 React 或 Vue 的，所以自定义扩展的功能必须基于传统 DOM 。你可以自定义 DOM 和样式来实现截图的功能，但没法直接用 antd 的组件。
