### ISSUE TITLE
特定html文本转义node时初次渲染与重新赋值结果不同

### ISSUE THREAD

**Issue by as-alt** [wangeditor-team/wangEditor#4422]
## 问题描述

*请输入遇到的问题...*
当示例存在时,将html赋值转义为node时会错乱

初次赋值时无问题
内容为
![image](https://user-images.githubusercontent.com/61306206/175761380-87cada14-7108-4a00-bbf2-c5c5d05ab35b.png)
示例对象的node为
![image](https://user-images.githubusercontent.com/61306206/175761628-727bb8e9-6f1c-41fb-8c82-74951d9aaa60.png)

当清空后，再次赋值时
内容为
![image](https://user-images.githubusercontent.com/61306206/175761401-8766a8e4-558e-44b6-b4b4-f7fdce698e51.png)
示例对象的node为
![image](https://user-images.githubusercontent.com/61306206/175761715-acb2822c-c7d9-4fab-a39e-75af8fb90566.png)

后面会多出一段内容，并且报错
![image](https://user-images.githubusercontent.com/61306206/175761198-05e5de87-84c1-4dc5-b8ea-d5591f4427f4.png)

目前只发现该段html会出现此问题,使用其他html文本时内容正常
## wangEditor 版本
![image](https://user-images.githubusercontent.com/61306206/175761241-aa5cba19-8425-4876-b7fc-b74c30a9b8c8.png)

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 所用代码:
- 
![image](https://user-images.githubusercontent.com/61306206/175761485-cbbbdb2c-b9bd-47ad-b37c-ef3bc7482ed0.png)

- 
![image](https://user-images.githubusercontent.com/61306206/175761790-d15c9a6f-3411-4210-bd55-0b313652d1f6.png)

![image](https://user-images.githubusercontent.com/61306206/175761796-26de38a5-9b6a-4b48-ad1c-2ef763b50245.png)

**Comment by wangfupeng1988** [comment]
你举例的内容太多了，而且是截图，我也不好复现。我没法把你截图的内容全部转换为文字。

你可以把例子精简一下，用最简单的 HTML 来复现这个问题。这样我就容易排查了。

感谢体谅~

**Comment by as-alt** [comment]
我好像找到原因了,图片标签是被a标签包裹起来的，我用官方demo中的setHtml渲染时图片会不显示，删除a标签后没问题
删除前html
`<p style="text-indent: 0px; text-align: start;">开展“不忘初心、牢记使命”主题教育，离不开榜样的力量。习近平总书记在“不忘初心、牢记使命”主题教育工作会议上强调，要宣传那些秉持理想信念、保持崇高境界、坚守初心使命、敢于担当作为的先进典型，形成学习先进、争当先进的良好风尚。</p><p style="text-indent: 0px; text-align: start;">　　《同学》工作室制作推出优秀共产党员系列海报，让我们一起走近他们，学习他们。</p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566272353885687.shtml" target="_blank"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009555247762.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566277019705825.shtml" target="_blank"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009562370658.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566272693887691.shtml" target="_blank"><img src="https://p3.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009563999735.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566276526873805.shtml" target="_blank"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009561534741.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566291719765808.shtml" target="_blank"><img src="https://p2.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009573858066.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/special/zmjcgb/lanhui/" target="_blank"><img src="https://p2.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009571231169.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566280204474839.shtml" target="_blank"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009563375135.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566288186196355.shtml" target="_blank"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009572675695.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/special/zoubihua/" target="_blank"><img src="https://p3.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009570340016.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/special/ljb/" target="_blank"><img src="https://p2.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009565090587.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566293546574942.shtml" target="_blank"><img src="https://p5.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009575289940.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/20/ARTI1566294107054991.shtml" target="_blank"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009580377005.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/special/lbgjng/" target="_blank"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009582335608.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/special/hdn/" target="_blank"><img src="https://p5.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009581435275.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><a href="http://www.12371.cn/2019/08/26/ARTI1566787151870691.shtml" target="_blank"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009585795696.jpg" alt="" data-href="" style=""></a></p><p style="text-indent: 0px; text-align: center;"><strong><br><br></strong></p>`

这个时候的生成的vdom是
![image](https://user-images.githubusercontent.com/61306206/175783593-7150da0c-8325-4826-b8a0-0a75c8b6d29e.png)

删除后
`<p style="text-indent: 0px; text-align: start;">开展“不忘初心、牢记使命”主题教育，离不开榜样的力量。习近平总书记在“不忘初心、牢记使命”主题教育工作会议上强调，要宣传那些秉持理想信念、保持崇高境界、坚守初心使命、敢于担当作为的先进典型，形成学习先进、争当先进的良好风尚。</p><p style="text-indent: 0px; text-align: start;">　　《同学》工作室制作推出优秀共产党员系列海报，让我们一起走近他们，学习他们。</p><p style="text-indent: 0px; text-align: center;"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009555247762.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009562370658.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p3.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009563999735.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009561534741.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p2.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009573858066.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p2.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009571231169.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009563375135.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009572675695.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p3.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009570340016.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p2.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009565090587.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p5.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009575289940.jpg" alt="" data-href="" style="">&lt;</p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009580377005.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009582335608.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p5.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009581435275.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong>【学习先进事迹】</strong></p><p style="text-indent: 0px; text-align: center;"><img src="https://p4.img.cctvpic.com/photoworkspace/contentimg/2019/08/30/2019083009585795696.jpg" alt="" data-href="" style=""></p><p style="text-indent: 0px; text-align: center;"><strong><br><br></strong></p>`

此时生成的vdom是正常的
![image](https://user-images.githubusercontent.com/61306206/175783660-09558052-c453-44d5-bbd4-90ab33d0567e.png)

但是我不太理解的是首次渲染时是正常的，触发onChange事件重新赋值时就会报错，是否问题是我动态监听父组件传值直接设置v-model有关还是因为我第一次传值时实例未生成导致没触发onChange事件有关呢

**Comment by wangfupeng1988** [comment]
> 触发onChange事件重新赋值时就会报错 

用一个最简单的例子来说明复现步骤吧。

**Comment by as-alt** [comment]
我尝试写个demo复现但是没有出现类似的情况，将项目上引用的两个模块重装后问题解决无报错
之前问题的截图看着像之前的html未清空直接在末尾插入了未渲染图片的html
![image](https://user-images.githubusercontent.com/61306206/175798574-a202000a-dd85-423b-bc13-edf9fe26a757.png)
![image](https://user-images.githubusercontent.com/61306206/175798666-a4463c78-3d82-42d9-ad3a-00b05a19e8e9.png)

**Comment by wangfupeng1988** [comment]
如果再遇到，再及时告诉我哈

**Comment by as-alt** [comment]
好的
