### ISSUE TITLE
v5是否支持自定义高亮样式

### ISSUE THREAD

**Issue by YoungWenlong** [wangeditor-team/wangEditor#4423]
## 问题描述

v5是否支持自定义高亮样式，默认的代码块高亮样式满足不了需求，如何使用highlight.js自定义？文档中并没有找到对应的API

## wangEditor 版本

v5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

不需要

**Comment by wangfupeng1988** [comment]
> v5是否支持自定义高亮样式

暂不支持，sorry
