### ISSUE TITLE
标题目录demo存在的问题

### ISSUE THREAD

**Issue by YoungWenlong** [wangeditor-team/wangEditor#4424]
## bug 描述

在官网给的标题目录demo中，如果编辑器内代码块、内容长度过长，不再会显示滚动条，而是宽度无限增加。导航栏也不会自动换行，猜测是flex布局的问题，能否解决此问题，给一个完善的demo？

## 你预期的样子是？

宽度增加，会自动换行或显示滚动条。导航栏会自动换行

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

win10 谷歌浏览器 wangEditor v5版本

*请输入内容……*

官网demo--标题目录

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
好，我继续完善一下

**Comment by wangfupeng1988** [comment]
已修复，刷新 demo 页即可 https://www.wangeditor.com/demo/catalog.html
