### ISSUE TITLE
选中表格后弹出的操作栏挡住上面文字的问题

### ISSUE THREAD

**Issue by ChenKun1997** [wangeditor-team/wangEditor#4425]
## 问题描述

选中表格后，弹出的表格操作栏挡住了文字，使得表格的操作栏也看不太清楚，如图
![image](https://user-images.githubusercontent.com/24249578/175850376-19f36a5b-fd11-43e7-b632-748a66d6fbae.png)

## wangEditor 版本

5.1.1

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

随便插入个表格，选中表格

**Comment by wangfupeng1988** [comment]
官网 demo 无法复现。

请继续补充一下复现步骤。
