### ISSUE TITLE
如何获取选中的图片

### ISSUE THREAD

**Issue by chenxiaohuo** [wangeditor-team/wangEditor#4426]
## 问题描述

想要获取选中的图片进行自定义修改，现在只找到获取选中的text文本内容，是不支持获取选中的图片或者选中部分的html代码吗？

## wangEditor 版本

4.*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

**Comment by wangfupeng1988** [comment]
这个还不支持。

而且 v5 发布之后，v4 将不再继续升级。业余维护，时间有限，还请体谅~

**Comment by wangfupeng1988** [comment]
> 能不能写个v5完整版本的demo，vue 里面怎么添加自定义按钮 刚接触wangeditor 看着文档是挺多 但是没有完整的文档 都是这一块代码 那一块代码的，太零散

https://www.wangeditor.com/demo/extend-menu.html

**Comment by wangfupeng1988** [comment]
完整的代码，这些都是 https://www.wangeditor.com/v5/plugins.html
