### ISSUE TITLE
链接卡片插件和官网给出的效果不一样

### ISSUE THREAD

**Issue by YoungWenlong** [wangeditor-team/wangEditor#4427]
## bug 描述

按照官网给出的链接卡片插件的使用步骤，我得到的效果是下面的样子。我知道我没有获取图片，所以icon显示的是默认的，但是其他样式不一样，希望给出说明
![image](https://user-images.githubusercontent.com/108208950/175869335-58817e0d-7b0b-4ec9-bfe3-1dedaa13d8ad.png)

## 你预期的样子是？

官网给出的效果是这样的，
![image](https://user-images.githubusercontent.com/108208950/175869422-4443a166-fd5d-404b-a43a-806c526b840f.png)

## 系统和浏览器及版本号

v5

官网链接卡片插件demo

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
猜测可能是其他 css 样式污染了这个 DOM 节点。

用浏览器检查工具看看这个灰色的 div ，是否有其他 css 样式的影响？
