### ISSUE TITLE
focus() ts 类型报错

### ISSUE THREAD

**Issue by LiMao00** [wangeditor-team/wangEditor#4428]
## bug 描述

*focus() ts 类型报错：issue 中对于”光标落于结尾处“的解决方案，团队给的是 `editor?.focus(true)`*
![image](https://user-images.githubusercontent.com/99939885/175870958-9900b777-3f74-46ae-9a94-51cb8e8823bd.png)
![image](https://user-images.githubusercontent.com/99939885/175870989-8ff2f92a-e277-4e89-827d-9c3389e9d4be.png)

## 你预期的样子是？

*完善 ts 类型*

## wangEditor 版本

*^5.1.1*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一

```
<Button
  onClick={() => {
    editor?.focus(true);
  }}
>
  focus
</Button>
```

**Comment by wangfupeng1988** [comment]
我复现了，后面优化一下。

你可以先用当前的方式来使用，不影响功能。

**Comment by LiMao00** [comment]
感谢
