### ISSUE TITLE
所有的菜单按钮能否支持自定义svg图标

### ISSUE THREAD

**Issue by gouding** [wangeditor-team/wangEditor#4429]
![image](https://user-images.githubusercontent.com/13016673/175877945-6496e218-0923-47a5-8cd5-5371c9b2be03.png)
这里的所有按钮的图标能否自定义

**Comment by wangfupeng1988** [comment]
暂时不支持。

之前已有其他用户提过，已经记录下该功能了，后面会排队开发。

**Comment by wangfupeng1988** [comment]
另外我好奇问下，你们为何需要自定义呢？感觉哪个图标不合适？

**Comment by zouzixuan** [comment]
![EC7A38E78F4A6DCBD3B22BD99D5895C6](https://user-images.githubusercontent.com/38025251/176398828-4a23e4f3-031d-4784-a04b-65307fbee9a1.jpg)
有这样的需求，很多情况都有啊，产品完全不能理解为什么这个按钮不能改

**Comment by wangfupeng1988** [comment]
@zouzixuan 你截图这个，是你自定义菜单，自定义时可以传入 icon 的，也可以使用文本。

**Comment by SimonGH0STRiley** [comment]
王工，请问现在自定义原生按钮SVG功能开发完成了吗？
