### ISSUE TITLE
工具栏下拉框出错

### ISSUE THREAD

**Issue by lxp26** [wangeditor-team/wangEditor#4430]
## bug 描述

工具栏下拉选项出错
![index](https://user-images.githubusercontent.com/72136016/175896088-2799fe0b-5ad1-45ce-92e7-9aa9664ca76a.png)

## 你预期的样子是？

正常使用

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

wangEditor 5 vue2

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo
[index.zip](https://github.com/wangeditor-team/wangEditor/files/8990096/index.zip)

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

在笔记本非全屏打开

**Comment by wangfupeng1988** [comment]
我在官网没有复现。

请说明你的浏览器和版本，继续补充复现步骤。
