### ISSUE TITLE
自定义字号，替换成小五、五号这种，菜单栏选择生效，但选中之后字体大小不变

### ISSUE THREAD

**Issue by webYouth** [wangeditor-team/wangEditor#4431]
## 问题描述
*复现代码：```editorConfig.MENU_CONF['fontSize'] = {
  fontSizeList: ['小五', '五号', '小四', '四号', '小三', '三号', '小二', '二号', '小一', '一号', '小初', '初号']
}```*
*按照文档的方法自定义字号，替换成小五、五号这种，菜单栏选择生效，但选中之后字体大小不变*

## wangEditor 版本

*"@wangeditor/core": "^1.0.0",
    "@wangeditor/editor": "^5.1.1",
    "@wangeditor/editor-for-vue": "^5.1.12",*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 创建之前运行该代码
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
目前不支持这种方式，只支持 px 单位。

不过你提的也合理，后面我会继续优化，增加对这种方式的支持。

**Comment by webYouth** [comment]
辛苦作者了，pull requests 有什么要求嘛！我想参与进这个优化里面。这个代码我clone到本地了，要配置什么环境才能跑起来呢！望解惑

**Comment by wangfupeng1988** [comment]
@webYouth 本地运行参考 https://github.com/wangeditor-team/wangEditor/blob/master/docs/dev.md

**Comment by webYouth** [comment]
ok

**Comment by wangfupeng1988** [comment]
已支持自定义配置，更新最新版 `@wangeditor/editor` ，然后参考文档 https://www.wangeditor.com/v5/menu-config.html#%E5%AD%97%E5%8F%B7
