### ISSUE TITLE
wangeditor5的editor.focus()没有记忆位置

### ISSUE THREAD

**Issue by jiechi** [wangeditor-team/wangEditor#4434]
## bug 描述

*wangeditor5的`editor.focus()`没有记忆上次位置，每次聚焦到编辑器以后光标位置总是在最前面，或者`editor.focus(true)`总是在最后面
使用场景如：选中编辑器中的某个位置，然后鼠标（光标）离开编辑器，点击编辑器以外的位置 -“将一段文字并插入至编辑器” ，调用 `editor.focus();聚焦到编辑器， 然后editor.dangerouslyInsertHtml(html) 或者 editor.insertText("xxx") `  插入，文本内容被插入到最前面(或最后面)，没有插入到用户上次所在编辑器中的位置
ps:同样的使用场景，在wangeditor4中是没有任何问题的*

## 你预期的样子是？

*`editor.focus()`可以聚焦到上次离开编辑器时的选区位置， editor.insertText("xxx")可以插入到上次离开编辑器选区的位置*

## 系统和浏览器及版本号

- 操作系统 windows11 + VUE2 + element-ui
- 浏览器和版本  Chrome ， 版本 103.0.5060.53（正式版本） （64 位）

## wangEditor 版本

*    "@wangeditor/editor": "5.1.1",
    "@wangeditor/editor-for-vue": "1.0.2",*

## demo 能否复现该 bug ？

能
- 中文 demo https://www.wangeditor.com/demo/

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

## 最小成本的复现步骤
```javascript
editor.focus();
editor.insertText("222")
```
- 步骤一
**打开编辑器，输入“111”，换行换行，输入“333”，光标选中至“111”和“333”之间**
![1.png](https://taihu.ipieuvre.com/uploads/bbsImages/1250/20220627/55ec1536db2ad3e60ea1d901c27b68f0.png)
- 步骤二
**点击编辑器以外的任意位置，离开编辑器**
![2.png](https://taihu.ipieuvre.com/uploads/bbsImages/1250/20220627/f138c1f5aad0a21416e21fb8acbef9c0.png)
- 步骤三
 **打开控制台，执行代码`editor.focus();`聚焦到编辑器, 执行editor.insertText("222")插入内容至编辑器**
![3.png](https://taihu.ipieuvre.com/uploads/bbsImages/1250/20220627/48db066a1f40d13b261fed2537c35f85.png)
- 步骤四
 **效果，文本内容“222”被插入到了最前面，没有按照预期的插入到“111”和“333”之间**
![4.png](https://taihu.ipieuvre.com/uploads/bbsImages/1250/20220627/c1b9de9bd51c0bcc0117d6c2e19f4628.png)

**Comment by wangfupeng1988** [comment]
使用 `editor. restoreSelection()` 试试，这是恢复选区的 API

**Comment by jiechi** [comment]
谢谢~~  是我没有更加仔细的阅读完文档 麻烦你们了
