### ISSUE TITLE
图片更改大小时，保存其height属性能不能更改为auto而不是具体数值

### ISSUE THREAD

**Issue by wadefelix** [wangeditor-team/wangEditor#4435]
## 功能描述

所用版本 wangeditor-4.7.15
更改图片大小时，会将其width height同时保存下来。这个在wangEditor里没啥问题。但是我将编辑好的内容直接又用别的方式渲染时，如果包含图片的容器的宽度不够， 图片就被不等比缩放了。  所以能不能保存图片显示大小时，只保存width的值，将height的值置为auto？

**Comment by wangfupeng1988** [comment]
看你描述，你这个需求是合理的。

不过 v5 发布之后， v4 就没再有精力升级了。业余开发，时间有限，还请体谅~
