### ISSUE TITLE
怎样增加能够自定义的菜单弹出

### ISSUE THREAD

**Issue by guoyiman** [wangeditor-team/wangEditor#4436]
## 功能描述
点击自定义菜单图标后弹出能够自定义的可以进行筛选的产品列表，然后可以将其中一个产品添加至编辑器中

*请输入内容……*
在工具栏中自定义一个工具图标，点击该图标，弹出一个弹出框，里面有搜索栏，类别筛选，产品列表，这些都是可以和公司接口联调的，然后产品列表可以点击选中，选中后添加至编辑器中

## 提炼几个功能点

- 功能1：
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
第一，扩展一个菜单，可参考 [插入链接](https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/link/menu/InsertLink.ts) 菜单。点击菜单弹出一个 modal ，里面实现你说的所有功能。

第二，扩展一个新的 element 用于呈现你的产品信息，可参考 [链接卡片](https://github.com/wangeditor-team/wangEditor-plugin-link-card)  功能。这样在菜单 modal 中可通过 js 把这个 element 插入到编辑器中。

大概思路就是这样的，具体可参考文档 [自定义扩展新功能](https://www.wangeditor.com/v5/development.html)  和 [视频教程](https://www.bilibili.com/video/BV1Y3411A7eb/) 来二次开发。
