### ISSUE TITLE
上传图片后同行不能编辑其他内容

### ISSUE THREAD

**Issue by Tianhainan** [wangeditor-team/wangEditor#4437]
## bug 描述
上传图片后同行不能编辑其他内容

## 你预期的样子是？
上传图片后同行可以编辑其他内容

## 系统和浏览器及版本号
win10
Microsoft Edge  89.0.774.68

## wangEditor 版本
wangEditor5.1.1

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤
上传图片 后直接编辑其他内容
![1656406716893](https://user-images.githubusercontent.com/108331666/176138639-749b906c-ee85-46c0-82f7-b10bdd5b4f98.jpg)

**Comment by Tianhainan** [comment]
鼠标光标问题，需要按右箭头把光标右移一个单位才可以继续编辑

**Comment by wangfupeng1988** [comment]
这符合预期，插入或上传图片之后，编辑器默认选中图片，因此无法输入文字。

不仅仅是 edge ，其他浏览器也这样
