### ISSUE TITLE
使用微信截图截取的图片可以黏贴到富文本编辑区

### ISSUE THREAD

**Issue by insistEQsuccess** [wangeditor-team/wangEditor#4439]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
配置上传图片或 base64 即可实现，官网 demo 就可以

参考文档 https://www.wangeditor.com/v5/menu-config.html#%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87
