### ISSUE TITLE
复制网页中的图文（同时包含图片和文字）到编辑器，图片自动被过滤掉

### ISSUE THREAD

**Issue by MYself2132000** [wangeditor-team/wangEditor#4441]
## bug 描述

*同时选中网页中的文字和图片，进行复制，粘贴到编辑器中，图片没有被渲染出来*

## 你预期的样子是？

*文字图片成功粘贴上去*

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 Chrome 98.0.4758.102

## wangEditor 版本

*    "@wangeditor/editor": "^5.1.1",
    "@wangeditor/editor-for-vue": "^1.0.1"*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 选中网页中的文字和图片，复制一下
- 步骤二 粘贴到编辑器中
- 步骤三

**Comment by wangfupeng1988** [comment]
猜测复制的 HTML 中，图片是被包裹到 `<div>` 或者 `<span>` 里面的。

改问题已经被记录下了，后面统一优化。
