### ISSUE TITLE
editor.dangerouslyInsertHtml 不起效

### ISSUE THREAD

**Issue by html580** [wangeditor-team/wangEditor#4442]
## 问题描述

*请输入遇到的问题...*

## 最小成本的复现步骤

- 步骤一

```
		// 定义菜单 class
		class MyButtonMenu implements IButtonMenu {
			public title = '图片上传';
			public iconSvg =
				'<svg viewBox="0 0 1024 1024"><path d="M959.877 128l0.123 0.123v767.775l-0.123 0.122H64.102l-0.122-0.122V128.123l0.122-0.123h895.775zM960 64H64C28.795 64 0 92.795 0 128v768c0 35.205 28.795 64 64 64h896c35.205 0 64-28.795 64-64V128c0-35.205-28.795-64-64-64zM832 288.01c0 53.023-42.988 96.01-96.01 96.01s-96.01-42.987-96.01-96.01S682.967 192 735.99 192 832 234.988 832 288.01zM896 832H128V704l224.01-384 256 320h64l224.01-192z"></path></svg>';
			public tag = 'button';

			getValue() {
				return '';
			}
			isActive() {
				return false; // or false
			}
			isDisabled() {
				return false; // or true
			}
			exec() {
                               //如果直接这里执行这个方法是可以加入HTML的。
                               editor.value.dangerouslyInsertHtml(`<h1>标题</h1><p>文本 <b>加粗</b></p>`)
                               //但实现场景是我是打开了一个图片选择器，打开了一个图片选择器窗口
				storage.value!.handleStorageDlg('image', '', "上传图片");
			}
		}

		// 定义菜单配置
		const menu1Conf = {
			key: 'diygwimage', // menu key ，唯一。注册之后，可配置到工具栏
			factory() {
				return new MyButtonMenu();
			},
		};

		// 注册到 wangEditor
		Boot.registerMenu(menu1Conf);
```

- 步骤二
找开窗口后，我在打开的窗口执行editor.value.dangerouslyInsertHtml(`<h1>标题</h1><p>文本 <b>加粗</b></p>`) 不起效。
我只能获取当前的HTML代码+加上增加的HTML代码，然后使用setHtml全部重写能起效。
我使用了editorRef.value.setHtml(editorRef.value.getHtml()+`<h1>标题</h1><p>文本 <b>加粗</b></p>`);
![image](https://user-images.githubusercontent.com/4509324/176193591-4004b0b8-ca7b-4641-9900-3ca4ef51a1bb.png)
![image](https://user-images.githubusercontent.com/4509324/176194015-1019e02d-ac29-4736-8f79-b2d67713e45a.png)

--无效插入
`editorRef.value.dangerouslyInsertHtml("<img src='" + file.url + "'/>")`;

--我只能使用这样的方法来插入，有效。
`editorRef.value.setHtml(editorRef.value.getHtml()+"<img src='" + file.url + "'/>")`;
我同时也测试了使用也同样是不起效。
editor.insertText('xxx')

只有完全使用setHtml方法起效。不知道算不算是个BUG。因为相当不需要定位到编辑器里，希望通过别的点击事件来增加html。

**Comment by wangfupeng1988** [comment]
内容有点多，看着有点乱。我试着回答你一下我理解的部分。

首先，如果是编辑器失焦，任何插入都不会生效的。此时需要执行 `editor.restoreSelection()` 来重新获取焦点，然后再执行插入。

> 执行editor.value.dangerouslyInsertHtml(<h1>标题</h1><p>文本 <b>加粗</b></p>) 不起效 

这个我没有复现，你在 [官网 demo](https://www.wangeditor.com/demo/) 浏览器控制台执行 `editor.dangerouslyInsertHtml('<h1>标题</h1><p>文本 <b>加粗</b></p>')` 就可以看到效果

> 插入无效 `editorRef.value.dangerouslyInsertHtml("<img src='" + file.url + "'/>");`

这个我也复现不了，你在 [官网 demo](https://www.wangeditor.com/demo/) 浏览器控制台执行 `editor.dangerouslyInsertHtml('<img src="xxx.png"/>')` 就可以看到效果

> 插入无效 `editor.insertText('xxx')`

这个我也复现不了，你在 [官网 demo](https://www.wangeditor.com/demo/) 浏览器控制台执行 `editor.insertText('xxx')` 就可以看到效果

**Comment by wangfupeng1988** [comment]
一个 API 是否有效，可以在 demo 里尝试，这个环境最纯粹，不收其他的影响。

**Comment by lyraLe** [comment]
> ## 问题描述
> _请输入遇到的问题..._
> 
> ## wangEditor 版本 5.1.1
> ## 最小成本的复现步骤
> * 步骤一
> 
> ```
> 		// 定义菜单 class
> 		class MyButtonMenu implements IButtonMenu {
> 			public title = '图片上传';
> 			public iconSvg =
> 				'<svg viewBox="0 0 1024 1024"><path d="M959.877 128l0.123 0.123v767.775l-0.123 0.122H64.102l-0.122-0.122V128.123l0.122-0.123h895.775zM960 64H64C28.795 64 0 92.795 0 128v768c0 35.205 28.795 64 64 64h896c35.205 0 64-28.795 64-64V128c0-35.205-28.795-64-64-64zM832 288.01c0 53.023-42.988 96.01-96.01 96.01s-96.01-42.987-96.01-96.01S682.967 192 735.99 192 832 234.988 832 288.01zM896 832H128V704l224.01-384 256 320h64l224.01-192z"></path></svg>';
> 			public tag = 'button';
> 
> 			getValue() {
> 				return '';
> 			}
> 			isActive() {
> 				return false; // or false
> 			}
> 			isDisabled() {
> 				return false; // or true
> 			}
> 			exec() {
>                                //如果直接这里执行这个方法是可以加入HTML的。
>                                editor.value.dangerouslyInsertHtml(`<h1>标题</h1><p>文本 <b>加粗</b></p>`)
>                                //但实现场景是我是打开了一个图片选择器，打开了一个图片选择器窗口
> 				storage.value!.handleStorageDlg('image', '', "上传图片");
> 			}
> 		}
> 
> 		// 定义菜单配置
> 		const menu1Conf = {
> 			key: 'diygwimage', // menu key ，唯一。注册之后，可配置到工具栏
> 			factory() {
> 				return new MyButtonMenu();
> 			},
> 		};
> 
> 		// 注册到 wangEditor
> 		Boot.registerMenu(menu1Conf);
> ```
> 
> * 步骤二
>   找开窗口后，我在打开的窗口执行editor.value.dangerouslyInsertHtml(`<h1>标题</h1><p>文本 <b>加粗</b></p>`) 不起效。
>   我只能获取当前的HTML代码+加上增加的HTML代码，然后使用setHtml全部重写能起效。
>   我使用了editorRef.value.setHtml(editorRef.value.getHtml()+`<h1>标题</h1><p>文本 <b>加粗</b></p>`);
>   ![image](https://user-images.githubusercontent.com/4509324/176193591-4004b0b8-ca7b-4641-9900-3ca4ef51a1bb.png)
>   ![image](https://user-images.githubusercontent.com/4509324/176194015-1019e02d-ac29-4736-8f79-b2d67713e45a.png)
> 
> --无效插入 `editorRef.value.dangerouslyInsertHtml("<img src='" + file.url + "'/>")`;
> 
> --我只能使用这样的方法来插入，有效。 `editorRef.value.setHtml(editorRef.value.getHtml()+"<img src='" + file.url + "'/>")`; 我同时也测试了使用也同样是不起效。 editor.insertText('xxx')
> 
> 只有完全使用setHtml方法起效。不知道算不算是个BUG。因为相当不需要定位到编辑器里，希望通过别的点击事件来增加html。

editor.restoreSelection()这个方法执行后，在setTimeout的回调里调用insert
