### ISSUE TITLE
请问一下官方是否有打算支持多人协同？如果我们自己开发多人协同有没有建议从哪里入手？

### ISSUE THREAD

**Issue by Rock-liyi** [wangeditor-team/wangEditor#4443]
## 功能描述

类似飞书、钉钉、语雀的多人协同规则，请问一下，如果我们自己开发的话，应该从哪里入手比较合适？

## 提炼几个功能点

- 多人在线实时编辑
- 冲突自动解决
- 数据实时发送

**Comment by wangfupeng1988** [comment]
近期没有打算。1. 这个开发成本非常高；2. 目前没几个人提这个需求；

如果你要自己开发，建议你选择成熟的方案。可以换其他支持多人协同的编辑器，如 promisMirror

**Comment by cycleccc** [comment]
补一个后续信息：当年这条 issue 里说“建议换成熟方案”，现在如果还在看 wangEditor 体系里的协同能力，实际上可以直接看 `wangEditor-next`。

`wangEditor-next` 现在已经提供了基于 Yjs 的协同方案：
- `@wangeditor-next/yjs`
- `@wangeditor-next/yjs-for-react`
- `@wangeditor-next/yjs-for-vue`

代码位置：
- https://github.com/wangeditor-next/wangEditor-next/tree/master/packages/yjs
- https://github.com/wangeditor-next/wangEditor-next/tree/master/packages/yjs-for-react
- https://github.com/wangeditor-next/wangEditor-next/tree/master/packages/yjs-for-vue

本地 demo：
- `pnpm demo:yjs:react`
- `pnpm demo:yjs:vue3`

相关 issue：
- https://github.com/wangeditor-next/wangEditor-next/issues/165
- https://github.com/wangeditor-next/wangEditor-next/issues/724

所以如果现在要做“类似飞书/语雀的多人协同”，在 wangEditor 这条线上更推荐直接迁到 `wangEditor-next` 的 Yjs 方案，而不是继续围绕旧仓库做二次实现。
