### ISSUE TITLE
粘贴word内容，前面标号会超出编辑区

### ISSUE THREAD

**Issue by HostDay123** [wangeditor-team/wangEditor#4444]
## bug 描述

在word中段落前带有序列标号，选择复制到编辑器的编辑区内后，设置左对齐，出现前面的标号超出编辑区，审查元素出现text-indent:-18pt;的样式。
![L5MMKS3MH)BOC)`1{U7@A~7](https://user-images.githubusercontent.com/48356902/176332540-fcd31c09-ba6e-4984-b979-560da6a4d17e.png)

![IVT2UR7GY@%AT60GYWK~KVX](https://user-images.githubusercontent.com/48356902/176332713-10b5fdab-04b5-4dfe-82e2-3d65c14b9a59.png)

## 你预期的样子是？

预期应该靠着编辑区边完整显示，或按照原有的缩进格式显示，无论如何不应该被遮挡。

## 系统和浏览器及版本号

- 操作系统 windows10
- 浏览器和版本 Google Chrome 版本 102.0.5005.115（正式版本） （64 位）

## wangEditor 版本

5

## demo 能否复现该 bug ？

能，在交流群中询问有其他人同样遇到此情况

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

使用的是官网快速开始步骤搭建，未做其他自定义配置情况下就能出现。

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 复制word中带有序列标号的内容
- 步骤二 在编辑区中粘贴
- 步骤三 在编辑器中设置左对齐

**Comment by HostDay123** [comment]
补充：原因并不是只要有序列标号就会出现此现象，进一步发现只要该段为“悬挂”方式，并且后面的缩进值大于0的情况会出现，其中该值的大小是直接导致text-indent样式为负值的大小。
![image](https://user-images.githubusercontent.com/48356902/176340613-42c1c5f6-0a2f-49e1-a991-e6302aa3c161.png)

**Comment by wangfupeng1988** [comment]
word 粘贴的问题，下个月我一起优化一下。

**Comment by Zy76278** [comment]
> word 粘贴的问题，下个月我一起优化一下。

word里面文章里有图片复制后在富文本里粘贴，图片粘贴不成功，报错：manualHomePage:1 Not allowed to load local resource:“file://...........”

**Comment by wangfupeng1988** [comment]
@Zy76278 看这里 https://juejin.cn/post/7114084537097224199#heading-8

**Comment by wangfupeng1988** [comment]
@HostDay123 text-indent 负值的问题我记得之前修复过了，你再去拿官网 demo 试试 https://www.wangeditor.com/demo/

![](https://user-images.githubusercontent.com/48356902/176332713-10b5fdab-04b5-4dfe-82e2-3d65c14b9a59.png)

**Comment by HostDay123** [comment]
是的，看到已正常

**Comment by HostDay123** [comment]
是的，刚看确实正常显示了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月14日(星期三) 上午10:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 粘贴word内容，前面标号会超出编辑区 (Issue #4444)





 
@HostDay123 text-indent 负值的问题我记得之前修复过了，你再去拿官网 demo 试试 https://www.wangeditor.com/demo/
 

 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
你收到这个是因为你被提到了。消息 ID：<wangeditor-team/wangEditor/issues/4444/1246162853 @ github 。com&gt;
