### ISSUE TITLE
v5版本是否兼容vue3.1.5版本

### ISSUE THREAD

**Issue by bruceZho** [wangeditor-team/wangEditor#4448]
## 问题描述

*在vue3.1.5版本中使用wangeditor时报错*

## wangEditor 版本

*@wangeditor/editor v5.1.1 和 @wangeditor/editor-for-vue v5.1.2*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

-在vue3.1.5版本下的脚手架下
-按照demo的代码操作即可重现，https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8

**Comment by wangfupeng1988** [comment]
具体报错信息是啥？截图看看
