### ISSUE TITLE
光标选中部分文本，使用输入法输入内容，光标跑到行首

### ISSUE THREAD

**Issue by pb0710** [wangeditor-team/wangEditor#4449]
## bug 描述

光标选中部分文本，使用输入法输入内容，光标跑到行首。

https://user-images.githubusercontent.com/43576003/176410118-e49a948a-1e7f-4bbb-bd74-5a6335bab2c5.mov

## 你预期的样子是？

输入法输入内容时光标保持原有位置。

## 系统和浏览器及版本号

- 操作系统 MacOS 12.2.1
- 浏览器和版本 Chrome 102.0.5005.115

## wangEditor 版本 

5.1.1

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
已知 bug https://github.com/wangeditor-team/wangEditor/issues/4183 ，待解决中。
