### ISSUE TITLE
table表的横向滚动问题

### ISSUE THREAD

**Issue by 13675870972** [wangeditor-team/wangEditor#4450]
新版本的table，外层的包裹父容器table-container不见了，实现不了表格的横向滚动了

**Comment by wangfupeng1988** [comment]
"@wangeditor/editor": "^5.0.1",
"@wangeditor/editor-for-vue": "^1.0.1",

这里都升级到最新版本，试试。

**Comment by 13675870972** [comment]
重新卸载后安装的版本是如下两个：
 "@wangeditor/editor": "^0.15.11",
  "@wangeditor/editor-for-vue": "^0.6.13",
这些是不是最新的？

**Comment by 13675870972** [comment]
是本地npm缓存问题，一直没有更新到最新版本，目前已经解决，谢谢
