### ISSUE TITLE
行高默认选中配置

### ISSUE THREAD

**Issue by BingFen72** [wangeditor-team/wangEditor#4451]
## 问题描述

给编辑器配置行高时，无法更改默认选中的默认行高，可以在初始化时更改为自定义的行高吗？

## wangEditor 版本

v5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

- 步骤一
- `window.editor = E.createEditor({
        selector: '#Body',
        html: '<p><br/></p>',
        config: {
            placeholder: '',
            MENU_CONF: {
                uploadImage: {
                    fieldName: 'your-fileName',
                    base64LimitSize: 10 * 1024 * 1024 // 10M 以下插入 base64
                },
                lineHeight: {
                    lineHeightList: ['1','2','3'],
                }
            },
            onChange(editor) {
                //console.log(editor);
                //$("#w-e-textarea-1 p").css('line-height', 1)
            }
        },
        //mode:'simple'
    })`

lineHeight可以设置默认的编辑器行高吗

**Comment by wangfupeng1988** [comment]
参考这个即可 https://github.com/wangeditor-team/wangEditor/issues/4042

**Comment by BingFen72** [comment]
谢谢大佬，在html处输入 ‘<p style="line-height: 1;"></p>’ 即可配置默认行高为1
