### ISSUE TITLE
vue3 单中使用 增加maxLength 后 编辑器内第一行出现空行

### ISSUE THREAD

**Issue by qc5926** [wangeditor-team/wangEditor#4452]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
应该和 https://github.com/wangeditor-team/wangEditor/issues/4078 是一个问题。

下个月我抽时间一起优化吧。统一在上面 issue 里跟踪进度。

**Comment by qc5926** [comment]
好的好的，辛苦了
