### ISSUE TITLE
使用cdn方式引入的编辑器，怎么扩展“上传附件”的菜单和功能

### ISSUE THREAD

**Issue by mengyingshi** [wangeditor-team/wangEditor#4454]
使用此电脑方式引入的编辑器，怎么扩展“上传附件”的菜单和功能？
demo上的“扩展菜单”，不知道在哪里接收上传后的文件地址，并返回渲染到编辑器中。。。。

**Comment by wangfupeng1988** [comment]
> 使用cdn方式引入的编辑器，怎么扩展“上传附件”的菜单和功能

参考这个 demo https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html

**Comment by mengyingshi** [comment]
感谢王哥
