### ISSUE TITLE
react版 默认吐一个<p><br></p>

### ISSUE THREAD

**Issue by JamosLi** [wangeditor-team/wangEditor#4455]
## bug 描述

*请输入内容……*
react版 默认吐一个`<p><br></p>`
## 你预期的样子是？
默认应该吐空
*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 使用 antd 表单 直接取数据
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这符合预期。编辑器默认内容就是一个空行。

如果你有其他需求，可以手动把它替换掉。

**Comment by JamosLi** [comment]
emm  毫无疑问这个是欠妥的。编辑场景无非就是纯编辑和表单编辑，可能还是需要一个表单模式默认吐空的数据。

另外如何开始精简模式呢，react版。

**Comment by wangfupeng1988** [comment]
精简模式文档有，就一个配置，和是否 react 无关

**Comment by SingleShadow** [comment]
在表单里使用的话，这会导致这个字段不会触发非空校验，这显然不合理

**Comment by wangfupeng1988** [comment]
参考这里 https://github.com/wangeditor-team/wangEditor/issues/4619
