### ISSUE TITLE
插入视频后不能编辑段落样式

### ISSUE THREAD

**Issue by wonders2002ok** [wangeditor-team/wangEditor#4456]
## bug 描述

插入视频后不能编辑段落样式（左对齐，右对齐，居中）。菜单变为灰色。

## 你预期的样子是？

插入视频后，在视频div被选中的情况下，可以设置段落样式（左对齐，右对齐，居中）

## 系统和浏览器及版本号

- Win 10
- Chrome 103.0.5060.66 64-bit

## wangEditor 版本

5.1.1

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 插入B站视频
- 菜单栏段落央视部分变为灰色，不能选择

**Comment by wangfupeng1988** [comment]
视频是一个 block 节点，占据整行，无法像 `<p>` 一样操作，编辑器是如此设计的。

你有什么其他需求？想让视频靠左、靠右吗？还是想要“左视频又文字”那种形式？

**Comment by wonders2002ok** [comment]
您好，

我遇到的问题是：在编辑的时候，页面整体宽度为1100px，但是视频窗口大小我设置为800*600px，这样编辑出来阅读的时候视频默认左对齐。如图所示：
[image0.png]

所以我建议如果可以的话，让视频的block节点可以向<p>节点一样设置左右对齐或者居中。会更加符合编辑习惯。

谢谢，
Wallace

发自我的iPhone

在 2022年7月2日，15:37，王福朋 ***@***.***> 写道：

﻿

视频是一个 block 节点，占据整行，无法像 <p> 一样操作，编辑器是如此设计的。

你有什么其他需求？想让视频靠左、靠右吗？还是想要“左视频又文字”那种形式？

**Comment by wangfupeng1988** [comment]
编辑器插入视频之后，输出的 HTML 格式如下

```html
<p>hello</p><div data-w-e-type="video" data-w-e-is-void>
<video controls="true" width="400" height="auto"><source src="https://www.w3school.com.cn/i/movie.ogg" type="video/mp4"/></video>
</div><p><br></p>
```

其实你可对 `<div data-w-e-type="video" data-w-e-is-void>` 自定义一些 CSS 样式，让其中的 `<video>` 居中显示。
这样也可以解决你的问题，而且成本比较低。
