### ISSUE TITLE
粘贴文案后，编辑器内文案颜色变成了白色，同时光标消失

### ISSUE THREAD

**Issue by wangkemin** [wangeditor-team/wangEditor#4457]
## bug 描述

打开控制台，挑选一个请求，选中一个请求中部分路径，粘贴后文字为白色，编辑器内看起来就像没有粘贴成功，同时光标消失了
<img width="973" alt="image" src="https://user-images.githubusercontent.com/20395541/176868311-f733b535-ea71-4fd0-8dee-a0d2956ba09e.png">
<img width="932" alt="image" src="https://user-images.githubusercontent.com/20395541/176868831-ad508436-fde7-4a70-b46b-78f9fc8b98b3.png">

## 你预期的样子是？

粘贴成功并展示成功

## 系统和浏览器及版本号

- mac big sur
- chrome  103.0.5060.53

## wangEditor 版本

5.1.1

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

https://codesandbox.io/s/nifty-morse-2yvegm?file=/src/App.js

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 打开控制台，随意找一个请求，截取请求中部分路径（不带http）
- 步骤二 粘贴到编辑器中
- 步骤三

**Comment by wangfupeng1988** [comment]
已复现，我抽空解决。

**Comment by wangkemin** [comment]
请问这个问题什么时候可以解决呢

**Comment by wangfupeng1988** [comment]
从 chrome 控制台复制内容，这场景很少见啊。所以我优先级就放低了。

你会经常这么使用吗？

**Comment by wangkemin** [comment]
不经常用，是怕有其他场景会复现，同时想了解下大概的解决日期，麻烦了！




王克敏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 粘贴文案后，编辑器内文案颜色变成了白色，同时光标消失 (Issue #4457)





 
从 chrome 控制台复制内容，这场景很少见啊。所以我优先级就放低了。
 
你会经常这么使用吗？
