### ISSUE TITLE
vue 版本遇到问题

### ISSUE THREAD

**Issue by devil1989** [wangeditor-team/wangEditor#4458]
1.api文档非常垃圾，且无js源码可看【你在nodemodules里面的js源码是压缩的】
2.vue2版本的780多k啊，gzip下来还有280来k；这么大你好歹在主页里面提一嘴，提前看到这么大，我也就不在你这上面浪费时间了，我本来还想着，一个富文本编辑框插件，能有多大，200k也捅破天了；就没看大小，业务tm都写完了，一瞅，未压缩780K；阿里的antd-vue，我瘦身+gzip后用到的也就百来K，还能拆开来，自己搞懒加载和预加载把他劣势抹掉，你一个插件780K，怎么拆？
3.在这个上面浪费了大半天，个人感觉挺不值的，文档偷懒，js源码总不要压缩吧；这不是在恶心人么；

**Comment by wangfupeng1988** [comment]
感谢反馈哈，你提的确实都是一些问题。

第一，文档如有困惑、感觉偷懒，还希望你能提供一些具体的建议，否则我也当事者迷，无从下手。

第二，JS 源码可以从 [CDN 链接](https://www.wangeditor.com/v5/installation.html#cdn)查，通过查看源代码可以大概知道 JS的体积。另，即便是压缩代码，也不影响你查看它的体积。

第三，只要是正式的富文本编辑器，体积都很大，复杂度太高了，它和其他类型的产品不一样。你可以去试试其他富文本编辑器，也都差不太多。如果用于 Vue ，可以使用**异步组件**来单独拆分富文本编辑器的页面。

第四，基于你说的体积问题，我也在考虑如何拆分包、按需加载，不过这需要一些时间来整改，近期我还没精力做到。

第五，开源不易，我也是尽量的平衡工作与业余开源的产出，尽可能的提供好的产品给大家。所以，我很希望每一个贡献者（包括提交 issue 的）都不要完全把自己当做一个甲方用户，而是尽量的要把自己当一个参与者，哪怕是提交一些建议呢。这样开源项目才能持续优化。

**Comment by wangfupeng1988** [comment]
收集 wangEditor5 文档 demo 和视频教程的问题和建议 https://github.com/wangeditor-team/wangEditor/issues/4507

有啥具体建议可以在这里写

**Comment by hjp-git** [comment]
![image](https://user-images.githubusercontent.com/69494794/184270274-70d6a79a-7b92-4eb3-b6b4-b0bba837ca4b.png)

vue2 这里得 editor 从哪里来？

**Comment by wangfupeng1988** [comment]
@hjp-git 看文档中的 vue2 demo

**Comment by hjp-git** [comment]
demo里面也没有
