### ISSUE TITLE
我如何从其它富文本框复制内容保持原内容不变

### ISSUE THREAD

**Issue by JHeLiu** [wangeditor-team/wangEditor#4459]
比如 我在 https://www.365editor.com/
编辑了内容 我复制进来 内容被改变了

**Comment by wangfupeng1988** [comment]
给一个具体的例子吧，在这个 365 复制了什么内容，然后粘贴被改变了？—— 我好复现问题。

截个图就行

**Comment by JHeLiu** [comment]
你是随便加点什么内容进去 然后复制过来 好像内容被改变


![image](https://user-images.githubusercontent.com/15246138/176992245-9ad8dda6-4f88-4534-80a1-8bbe0109941c.png)



![image](https://user-images.githubusercontent.com/15246138/176992226-f52358c9-c33e-427e-815c-0db8314d6116.png)

**Comment by wangfupeng1988** [comment]
接下来我会做复制粘贴的优化，但只能保证基本样式（如标题、段落、列表），和图文信息。

即，优化完之后，保证复制过的图文信息都在，不过你这红色背景等特殊的样式，就不会支持了。
