### ISSUE TITLE
怎么重写上传后的展示效果

### ISSUE THREAD

**Issue by gouding** [wangeditor-team/wangEditor#4461]
## 目前上传附件后是这样的效果，及其不方便
![image](https://user-images.githubusercontent.com/13016673/177094269-4ccd05ee-2ed9-4881-af88-eff5620ac8e2.png)

怎么能自定义上传后的展示效果

**Comment by gouding** [comment]
![image](https://user-images.githubusercontent.com/13016673/177094502-756d42ee-faed-4c26-ab5a-e9a096998f41.png)
比如这里要根据不同后缀我们要自定义展示

**Comment by wangfupeng1988** [comment]
fork 插件源码 https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment

然后自己修改 render elem 逻辑 https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment/blob/main/src/module/render-elem.ts
