### ISSUE TITLE
代码编辑,插入,地图载入

### ISSUE THREAD

**Issue by wheakerd** [wangeditor-team/wangEditor#4462]
## 功能描述

*代码编辑,插入,地图载入*

## 提炼几个功能点

- 可编写,插入代码
- 切换渲染画面或者显示代码编辑
- 选择地点,载入地图

## 原型图

![图片](https://user-images.githubusercontent.com/78034820/177097153-10452118-e49f-4baf-b91c-3ea3fa9cd504.png)

## 可参考的案例

*可参考百度富文本编辑器*

**Comment by wangfupeng1988** [comment]
自己扩展即可 https://www.wangeditor.com/v5/development.html
