### ISSUE TITLE
安卓钉钉上无法使用wangEditor，ios可以兼容

### ISSUE THREAD

**Issue by TianhaoHuang** [wangeditor-team/wangEditor#4463]
目前查看源码发现hidePlaceholder方法没有执行，可能handleCompositionStart事件没有执行。

**Comment by wangfupeng1988** [comment]
wangEditor 目前不支持移动端。

**Comment by loo41** [comment]
@TianhaoHuang 这个问题你们最终选择了啥解决方案了。
