### ISSUE TITLE
自定义扩展使用问题

### ISSUE THREAD

**Issue by zsz91** [wangeditor-team/wangEditor#4465]
## 老旧项目使用WangEditor5
在没有node 环境的老旧项目中如何使用wangeditor5的<自定义扩展>功能 拓展按钮菜单
官方文档中需要引入 一些依赖,但是因为没有npm 无法引入.
我参考官方文档中 <安装>CDN的方式引入到我们的项目中的
```
import { Boot, IButtonMenu } from '@wangeditor/editor'
```
## wangEditor 版本
5.x

## 是否查阅了文档 ？
相关文档 
https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E8%8F%9C%E5%8D%95
https://www.wangeditor.com/v5/installation.html#cdn
*是*

## 最小成本的复现步骤
 https://www.wangeditor.com/v5/installation.html#cdn  
使用此方法引入的js 和 css

**Comment by wangfupeng1988** [comment]
> 在没有node 环境的老旧项目中如何使用wangeditor5的<自定义扩展>功能 拓展按钮菜单

参考这个 demo 源码 https://www.wangeditor.com/demo/extend-menu.html

**Comment by zsz91** [comment]
感谢。 已经解决了
