### ISSUE TITLE
按照官网的例子运行报错

### ISSUE THREAD

**Issue by aexiaosong** [wangeditor-team/wangEditor#4466]
## 问题描述

    "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-vue": "^5.1.12",
    "vue": "^3.2.13",
复制官网的VUE3例子，运行报错editor.setHtml is not a function

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> "@wangeditor/editor": "^5.0.1",
> "@wangeditor/editor-for-vue": "^5.1.12",


这俩升级到最新版，试试
