### ISSUE TITLE
maxLength 最大字数对粘贴进的文本无效

### ISSUE THREAD

**Issue by zhudupi** [wangeditor-team/wangEditor#4467]
## bug 描述

设置最大字数maxlength之后，复制进超过最大字数的字，会超出最大字数。

## 你预期的样子是？

自动裁剪到最大字数

## 系统和浏览器及版本号

- 系统版本
win11
- 浏览器和版本
Google Chrome | 103.0.5060.66

## wangEditor 版本

5.1.1

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请继续补充复现步骤。

maxLength 设置为多少？复制了多少文字进去？从哪里复制的？

**Comment by zhudupi** [comment]
> 请继续补充复现步骤。
> 
> maxLength 设置为多少？复制了多少文字进去？从哪里复制的？

我设置的300，自己在记事本里输入超过300字的文字，所有文字都复制进去了。
照理说只要设置的最大字数，复制的时候就应该只截取前面300字才对。目前通过onmaxlength手动截取字数。
官方demo也有这个问题。

**Comment by zhudupi** [comment]
![image](https://user-images.githubusercontent.com/37323664/177452160-b775c6ea-b6c4-43d4-96d5-72557211c99a.png)

**Comment by nickname-undefined** [comment]
这个问题解决了吗？

**Comment by hellozzm** [comment]
> 

同问

**Comment by wangfupeng1988** [comment]
另外，设置 maxLength 之后，插入链接再输入文字也有问题，看 https://github.com/wangeditor-team/wangEditor/issues/4696

**Comment by ChenXiMorningStar** [comment]
> > 请继续补充复现步骤。
> > maxLength 设置为多少？复制了多少文字进去？从哪里复制的？
> 
> 我设置的300，自己在记事本里输入超过300字的文字，所有文字都复制进去了。 照理说只要设置的最大字数，复制的时候就应该只截取前面300字才对。目前通过onmaxlength手动截取字数。 官方demo也有这个问题。

可以分享一下通过onmaxlength手动截取字数的思路吗

**Comment by wangfupeng1988** [comment]
代码已经合并，待发布新版本

**Comment by wangfupeng1988** [comment]
已修复，更新 `@wangeditor/editor` 最新版本试试
