### ISSUE TITLE
wangeditor5的配置写在mounted生命周期中无效，在created或者data中有效

### ISSUE THREAD

**Issue by zhengzheng1998** [wangeditor-team/wangEditor#4471]
## 问题描述

在vue2的项目中，wangeditor5的配置写在mounted生命周期中无效，在created或者data中有效

## wangEditor 版本

"@wangeditor/editor": "^5.1.1",
"vue": "2.6.10",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*  是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
-编辑器
![image](https://user-images.githubusercontent.com/92833009/177458568-4ffe5da7-ce85-4a58-8c67-c6f9ae5b05ae.png)

created生命周期
![image](https://user-images.githubusercontent.com/92833009/177457827-aef4f131-2ebc-49d0-93e6-bbb4ae09aec3.png)

mounted生命周期
![image](https://user-images.githubusercontent.com/92833009/177457891-1d68a89a-d575-4cc5-bff8-796e1a272463.png)

页面显示
![image](https://user-images.githubusercontent.com/92833009/177457917-3c484c53-c900-44c5-be84-df7fa06d9c11.png)

- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
建议直接写在 data 中

**Comment by zhengzheng1998** [comment]
感谢回复！

因为不知道源码，我思考后猜测这些配置在组件内部绑定的时候，不是直接绑定props的值，而是把props的值赋值给data中声明的值，应该是下面这种情况：
![image](https://user-images.githubusercontent.com/92833009/177733910-f6bfa487-5434-499d-95af-0e94aacf63e0.png)
![image](https://user-images.githubusercontent.com/92833009/177734257-9ebbb7ce-7dce-4af9-95f6-452fcfd19502.png)

因为父子组件挂载周期的执行顺序为
父beforeCreate => 父created => 父beforeMount => 子beforeCreate => 子created => 子beforeMount => 子mounted => 父mounted。
所以才会导致配置写在mounted生命周期无效。

那为什么mounted异步加载数据就可以渲染呢？同步的就无效，这不符合父子组件的渲染原理啊。

同步：
![image](https://user-images.githubusercontent.com/92833009/177730683-9935e283-6433-4dfe-9e28-866cde8c46e8.png)
![image](https://user-images.githubusercontent.com/92833009/177731272-be005b79-56c4-4fd0-9572-cc808244c2bf.png)

异步加载：
![image](https://user-images.githubusercontent.com/92833009/177730866-9d57578b-9eb9-4284-9cdc-8c8d65f408dd.png)
![image](https://user-images.githubusercontent.com/92833009/177730926-121dc90a-027d-4b6d-9f65-baa3f14b8691.png)
