### ISSUE TITLE
React版本，自定义扩展功能——注册菜单报错

### ISSUE THREAD

**Issue by linqian02** [wangeditor-team/wangEditor#4477]
## 问题描述

我根据 [自定义扩展功能-selectmenu](https://www.wangeditor.com/v5/development.html#selectmenu) 的步骤，
参考 [菜单源码](https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/header/menu/HeaderSelectMenu.ts) 像注册一个类似【标题】菜单的选择框；

结果报如下错误(抱歉内网开发，无法粘贴代码)：

![f7eb9b7b6498b01f086083fbdd3f6c1](https://user-images.githubusercontent.com/29908531/177716143-6b735024-9eca-45a8-acdb-ac544332b5e1.jpg)

## wangEditor 版本

@wangEditor : 5.1.1
@wangEditor/editor-for-react: 1.0.4

请问是我用法的问题吗

**Comment by linqian02** [comment]
> 删掉 iconSvg 这个属性，试试行吗？

@Yangjia23  还是不行，并不是svg的问题

**Comment by wangfupeng1988** [comment]
@linqian02 那你先不要搞 selectMenu ，参照这个 demo ，添加一个最简单的 buttonMenu 看可以吗？
先跑通流程

https://www.wangeditor.com/demo/extend-menu.html

**Comment by linqian02** [comment]
@wangfupeng1988  不好意思，我的问题。我把tag属性当成唯一key了随便写个字符串了。
如果可以的话把ISelectMunu的这个interface添加一个
`
readonly tag:'select'
`

当然，应该不会有太多人像我一样SB [笑哭]  
谢谢啦！
