### ISSUE TITLE
上传图片如果服务端返回的是一个字符串而不是对象，改如何处理

### ISSUE THREAD

**Issue by ptzzxcl** [wangeditor-team/wangEditor#4478]
## 问题描述

如题：上传图片后端返回的是一个字符串，使用“自定义插入”，

editorConfig.MENU_CONF['uploadImage'] = {
    // 自定义插入图片
    customInsert(res: any, insertFn: InsertFnType) {
        // res 即服务端的返回结果
        // 从 res 中找到 url alt href ，然后插图图片
        insertFn(url, alt, href)
    },
}

此时res获取的是一个空对象；

## wangEditor 版本

v5

## 是否查阅了文档 ？

已查阅

## 最小成本的复现步骤
后端返回格式如：70f20ab1ebf6445faa02d6c08fb1297dnstest ，用 customInsert 方法却不能获取到改字符串序列，请问该如何处理？

**Comment by lancyJD** [comment]
这个必须按照他给的格式返回。不然解析不了。

**Comment by wangfupeng1988** [comment]
> 这个必须按照他给的格式返回。不然解析不了。

这个不对，用 customInsert 可以实现自己解析 res 并插入。

**Comment by wangfupeng1988** [comment]
@ptzzxcl 你把浏览器上传图片的这条 http 请求，它的 response 和 preview 截图看一下。就类似于下图

<img width="758" alt="image" src="https://user-images.githubusercontent.com/9583120/177744169-2c9c8b2f-249d-41ab-909d-bc16c984bd52.png">

**Comment by ptzzxcl** [comment]
@wangfupeng1988  大佬，以下就是上传的截图
![image](https://user-images.githubusercontent.com/35088509/177924991-c4d77da2-5243-43b2-ab20-ee7bd6be3ffc.png)
![image](https://user-images.githubusercontent.com/35088509/177925024-0917654b-2cff-4395-8b44-55736999ab48.png)
![image](https://user-images.githubusercontent.com/35088509/177925049-3ba045b3-612f-4eb2-bee8-65f6cdcfbfff.png)
![image](https://user-images.githubusercontent.com/35088509/177925080-d36ed28f-28b8-4d74-a258-1abba33953ed.png)

**Comment by ptzzxcl** [comment]
@lancyJD  因为后端返回的格式不统一，自定义应该用于解决该问题的吧。应该先拿到后端返回的格式然后自己组装，可是我这边拿不到后台返回的格式，所以无法拼装成固定格式

**Comment by wangfupeng1988** [comment]
你截图差一个“响应”tab。那里面也是字符串吗？

**Comment by wangfupeng1988** [comment]
我复现这个问题了，我下周处理一下。

**Comment by wangfupeng1988** [comment]
@ptzzxcl wangEditor5 上传文件用了 https://uppy.io/docs/xhr-upload/ ，经我测试，目前只能接收 JSON 格式的数据，字符串接收不到。

所以，还是建议你把服务端接口返回格式改一下。

**Comment by ptzzxcl** [comment]
@wangfupeng1988  收到，非常感谢(*^▽^*)
