### ISSUE TITLE
无法去掉菜单上面得上传视频按钮

### ISSUE THREAD

**Issue by imshuo** [wangeditor-team/wangEditor#4479]
## 问题描述

*无法去掉菜单上面得上传视频按钮

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*1*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三
123

**Comment by Yangjia23** [comment]
https://www.wangeditor.com/v5/toolbar-config.html#excludekeys

**Comment by imshuo** [comment]
> https://www.wangeditor.com/v5/toolbar-config.html#excludekeys
全加上了菜单得上传按钮还是在,把所有key都排除了

**Comment by imshuo** [comment]
> https://www.wangeditor.com/v5/toolbar-config.html#excludekeys

![image](https://user-images.githubusercontent.com/52827253/177731657-3f2d2c03-e1c3-49ed-9acf-36d3bab1828e.png)

**Comment by wangfupeng1988** [comment]
如上面的解答，配置 `excludeKeys ` 即可

**Comment by imshuo** [comment]
> 如上面的解答，配置 `excludeKeys ` 即可
哥你就说去掉菜单上的视频得按钮得key是啥把,我试了试没找到 ,或者写个能去掉得配置方法我把60个key都排除了还是有视频按钮

**Comment by wangfupeng1988** [comment]
使用 `toolbar.getConfig().toolbarKeys` 可以看到所有的菜单栏配置，其中就能找到你想要的 key

https://www.wangeditor.com/v5/toolbar-config.html#toolbarkeys

**Comment by imshuo** [comment]
好的谢谢找到了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月8日(星期五) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 无法去掉菜单上面得上传视频按钮 (Issue #4479)





 
使用 toolbar.getConfig().toolbarKeys 可以看到所有的菜单栏配置，其中就能找到你想要的 key
 
https://www.wangeditor.com/v5/toolbar-config.html#toolbarkeys

**Comment by yangjie2021** [comment]
> 使用 `toolbar.getConfig().toolbarKeys` 可以看到所有的菜单栏配置，其中就能找到你想要的 key
> 
> https://www.wangeditor.com/v5/toolbar-config.html#toolbarkeys

我设置了的group-video  这个key，不生效，使用的react版本的

<img width="843" alt="image" src="https://user-images.githubusercontent.com/19945710/190363391-c38dd191-753b-4628-9b12-e424b636c31f.png">

**Comment by qianchengjie** [comment]
React 中使用时如果配置mode="default"时，需要去掉`group-video`
```tsx
// 工具栏配置
  const toolbarConfig: Partial<IToolbarConfig> = {
    excludeKeys: ['group-video'],
  };
```
dom里找到的
<img width="464" alt="image" src="https://user-images.githubusercontent.com/27612520/233103834-2b5be5db-b917-4208-a338-b1934b8f01a0.png">
