### ISSUE TITLE
有没有办法把禁用button变成直接不显示？

### ISSUE THREAD

**Issue by zouzixuan** [wangeditor-team/wangEditor#4481]
![image](https://user-images.githubusercontent.com/38025251/177752307-db001856-4080-4a5d-919a-84db3ba50b02.png)
比如这个自定义的删除，我有时候需要，有时候不需要，，但是需要效果是显隐，而不是禁用

**Comment by wangfupeng1988** [comment]
目前不支持

**Comment by zouzixuan** [comment]
> 

我非常需要这个东西，没有的话就得注册一大堆类型。。

**Comment by wangfupeng1988** [comment]
> 但是需要效果是显隐，而不是禁用

这两个有什么区别吗？禁用、隐藏，不都一样吗。
而且我觉得禁用会更好一些，禁用实名的告诉用户不可用。隐藏了，用户还以为这个功能下架了呢。

**Comment by zouzixuan** [comment]
> > 但是需要效果是显隐，而不是禁用
> 
> 这两个有什么区别吗？禁用、隐藏，不都一样吗。 而且我觉得禁用会更好一些，禁用实名的告诉用户不可用。隐藏了，用户还以为这个功能下架了呢。

注册的增加元素的新按钮，功能十分复杂却相近的场景下，需要这种效果，不然就得换个名字注册。。。

**Comment by zouzixuan** [comment]
> > 但是需要效果是显隐，而不是禁用
> 
> 这两个有什么区别吗？禁用、隐藏，不都一样吗。 而且我觉得禁用会更好一些，禁用实名的告诉用户不可用。隐藏了，用户还以为这个功能下架了呢。

为了显隐部分按钮，我只能注册很多种新的type，但是这些type里面的内容又是相似的

**Comment by wangfupeng1988** [comment]
你还是奔着“隐藏”这个目的去的

我的疑问是：禁用不行吗？为何非要隐藏？

**Comment by zouzixuan** [comment]
> 你还是奔着“隐藏”这个目的去的
> 
> 我的疑问是：禁用不行吗？为何非要隐藏？

因为产品坚持要求隐藏

**Comment by wangfupeng1988** [comment]
那你可以和产品去沟通一下，隐藏不如禁用，会给用户误导。

**Comment by zouzixuan** [comment]
> 那你可以和产品去沟通一下，隐藏不如禁用，会给用户误导。

![image](https://user-images.githubusercontent.com/38025251/180162356-2c54182b-78da-41a4-a8be-4551f5db6025.png)
就是比如这种，他有的要改颜色，有的不需要，然后有的要换行，有的又不需要，产品不希望是禁用，希望是显隐，你理解吧

**Comment by wangfupeng1988** [comment]
你就跟他说：编辑器不支持 ， 你自己也没办法
