### ISSUE TITLE
当setHtml的参数为一个纯数字时，浏览器报错，当内容不带><符号时，无法设置内容

### ISSUE THREAD

**Issue by msker** [wangeditor-team/wangEditor#4486]
## bug 描述

1、设置编辑器内容时（setHtml），如果参数是个纯数字，浏览器报错。
2、设置编辑器内容时（setHtml），如果内容不带><符号时，无法设置内容。

在演示页面可复现！
![image](https://user-images.githubusercontent.com/33039795/177930274-d258e5a2-e919-4f87-8715-cb1502180ca9.png)
![image](https://user-images.githubusercontent.com/33039795/177930646-0f2fa8b8-ff66-4654-90d8-2520bea465aa.png)

**Comment by wangfupeng1988** [comment]
setHtml 必须是 HTML 格式，否则你就用 editor.insertText('xxx')
