### ISSUE TITLE
上传网络图片

### ISSUE THREAD

**Issue by 8392** [wangeditor-team/wangEditor#4487]
## bug 描述

*请输入内容……*
上传网络图片，配置了图片链接，保存后，点击图片，没有跳转到对应的链接，没有触发跳转
## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
图片的链接在 data-href 属性中，如下代码。自己对 img 增加一个 click 事件即可解决。

```
<p><img src="https://www.wangeditor.com/image/logo.png" alt="" data-href="https://www.wangeditor.com/demo/extend-menu.html" style=""/></p>
```
