### ISSUE TITLE
wangEditor5 可以弄多组表情嘛？  像QQ表情那样的一个分组

### ISSUE THREAD

**Issue by meishibiexuejava** [wangeditor-team/wangEditor#4490]
wangEditor5 可以弄多组表情嘛？ 
![QQ图片20220709184253](https://user-images.githubusercontent.com/47138180/178102476-6def7368-767f-4eb0-baaf-7c77b1abb158.png)

相当于这样的？

**Comment by meishibiexuejava** [comment]
看了源码和案例好像  wangEditor5  不行 和网上看的可以的是wangEditor4 ，wangEditor5 真的不行吗？

**Comment by wangfupeng1988** [comment]
v5 默认不再支持分组表情。

可以去自定义扩展菜单  https://www.wangeditor.com/v5/development.html
