### ISSUE TITLE
想在上传图片的时候，使用自己的函数调用上传图片。这个可以怎么使用自己的函数来上传图片呢

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor#4491]
## 问题描述
我在使用uploadImage 上传图片
*请输入遇到的问题...*
![image](https://user-images.githubusercontent.com/13927744/178123745-dd8fbd2c-0448-4938-a493-24156519c837.png)
因为我在跨域的upload 的时候不好处理，直接配路由路基/api/upload上传不行。想在上传图片的时候自己调用函数上传内容。这个可以怎么使用自己的函数来上传图片呢
## wangEditor 版本
v5
*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考文档 https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD ，可以自定义上传，也可以自定义选择图片。
