### ISSUE TITLE
实现一个自定义即时渲染逻辑的 demo 时，调试报错

### ISSUE THREAD

**Issue by Bald-Guy** [wangeditor-team/wangEditor#4493]
## bug 描述

*基于视频教程01-使用入门的代码基础上，在 onChange 的回调函数中仅添加 3 行代码，如下*
```js
editorConfig.onChange = (editor) => {
    // 当编辑器选区、内容变化时，即触发
    console.log('content', editor.children)
    console.log('html', editor.getHtml())
    if (/\d/.test(editor.getHtml())) {
        editor.setHtml('<p>hello world</p>')
    }
}
```
接下来在编辑器中输入任意字符（例：你好世界），当输入任意数字（例：1）之后，编辑器内已有文本变为 hello world，但开发者工具连续报 2 个相同的错误（如下），并且光标出现在 hello 与 world 之间。
```
index.js:21651 Uncaught (in promise) Error: Cannot resolve a DOM node from Slate node: {"text":"hello world"}
    at Object.toDOMNode (index.js:21651:13523)
    at Object.toDOMPoint (index.js:21651:14450)
    at Object.toDOMRange (index.js:21651:14032)
    at index.js:21651:71890
    at index.js:21651:72506
```
## 你预期的样子是？

*当输入的文本中出现数字时，将已有内容替换为 hello world，光标留在最后进行编辑的文本段落最后*

## 系统和浏览器及版本号

- 操作系统：macOS Monterey
- 浏览器和版本：Google Chrome 版本 103.0.5060.53（正式版本） (x86_64)

## wangEditor 版本

*5.1.1*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

[在线 demo](https://codepen.io/bald-guy/pen/poLbNEW)

## 最小成本的复现步骤

见 bug 描述

**Comment by wangfupeng1988** [comment]
你新建一个按钮，点击按钮时直接试行 `editor.setHtml('<p>hello world</p>')` 会否报错？

**Comment by wangfupeng1988** [comment]
你可以加一个 setTimeout 试试，如下

```js
editorConfig.onChange = (editor) => {
    // 当编辑器选区、内容变化时，即触发
    console.log('content', editor.children)
    console.log('html', editor.getHtml())
    if (/\d/.test(editor.getHtml())) {
        setTimeout(() => editor.setHtml('<p>hello world</p>'))
    }
}
```

**Comment by Bald-Guy** [comment]
感谢，没有报错了，虽然依旧不知道是啥原理😂，能 run 就行

**Comment by wangfupeng1988** [comment]
setHtml 会异步更新（像 Vue 和 React），用 setTimeout 隔离

能用就行了
