### ISSUE TITLE
vue3  两个Editor使用同一份数据双向绑定，每次输入完毕自动失去焦点

### ISSUE THREAD

**Issue by MoNaiZi** [wangeditor-team/wangEditor#4494]
## bug 描述

*vue3  兄弟组件Editor使用同一份数据双向绑定，每次输入完毕后双方都自动失去焦点*

## 你预期的样子是？

*不应该输入完字符就自动失去焦点*

## 系统和浏览器及版本号
谷歌浏览器，系统wn11

## wangEditor 版本
*  "vue": "^3.2.13",
   "@wangeditor/editor": "^5.1.1",
    "@wangeditor/editor-for-vue": "^5.1.12",*

## demo 能否复现该 bug ？
能

## 在线 demo
https://codesandbox.io/s/hungry-panka-1wxqqi?file=/src/components/HelloWorld.vue

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
你给的在线 demo ，我打开之后，无法输入内容。

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/9583120/178181849-b466b4bb-096c-433f-89b2-f37615c720cf.png">

**Comment by MoNaiZi** [comment]
> 你给的在线演示，我打开之后，无法输入内容。
> 
> <img alt="图片" width="1791" src="https://user-images.githubusercontent.com/9583120/178181849-b466b4bb-096c-433f-89b2-f37615c720cf.png">
样式问题，你点击请输入内容上面一点就可以了

**Comment by MoNaiZi** [comment]
![image](https://user-images.githubusercontent.com/38249356/178182331-e05ba71c-5e15-4b0d-b233-f140b333b513.png)
样式问题，你点击请输入内容上面一点就可以了

**Comment by liuqh0609** [comment]
参考这里的写法吧，既然都用vue3组件了，就使用vue3的写法来搞就好了，要不然推荐使用vue2组件。参考官网上的案例也可以实现你想要的功能：https://codesandbox.io/s/adoring-yalow-3n0cw6?file=/src/components/note_editor.vue

**Comment by hanlibaby** [comment]
贴一个我自己的做法，就是不要同时使用两个编辑器，只是用一个就好了，在编辑器的onChange事件中调用父组件的方法，在父组件中获取编辑器编辑区域的dom元素，使用v-html展示就好了。

```js
// 编辑器绑定的onChange事件
const handleChange = (editor) => {
  xxxxx....
  emits('modifyValue');
}

// 父组件使用
<WangEditor @modifyValue="handleModelValue">

// 获取dom方法
handleModelValue() {
  // 获取编辑器内容区域，自行调整
  const item = document.querySelector('#editorLeft .editor');
  const div = item.cloneNode(true);
  htmlValue.value = div.innerHTML
}

// 使用
<div class="editorPreview" v-html="htmlValue"></div>
```

**Comment by hakityc** [comment]
> 

谢谢，有用
但是这个v-html不是会有xss攻击风险吗？在输入的时候要有什么规范吗？
