### ISSUE TITLE
在自定义转换代码块功能的时候只返回了两个paragraph

### ISSUE THREAD

**Issue by BB-zhan** [wangeditor-team/wangEditor#4496]
## bug 描述

```js
const editor = this.editor
const CodeElement = {
    type: 'code',
    language: '',
    children: [{
        text: ''
    }]
}
const PreElement = {
    tyep: 'pre',
    children: [CodeElement]
}
console.log(PreElement)
SlateTransforms.setNodes(editor, PreElement)
// 转换当前节点，但是返回的是两个paragraph类型

SlateTransforms.insertNodes(editor, [PreElement])
// 自定义插入节点前面会多出一个paragraph类型，但是代码块类型可以实现
```
![1657526287680](https://user-images.githubusercontent.com/109065366/178216431-620ac4a2-2279-441e-9e52-c7eadba7ac46.png)

![1657526517780](https://user-images.githubusercontent.com/109065366/178216999-f85b4639-0176-4407-8afa-52daffd6cf87.png)

## 你预期的样子是？

预期应该是可以成功转换，且插入节点不会出现不可删除的第一行

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 chrome  102.0.5005.63（正式版本） （32 位）

## wangEditor 版本

wangEditor5
![1657526782338](https://user-images.githubusercontent.com/109065366/178217684-69f230ca-c01a-42a0-ae0b-ae80bfc32f7d.png)

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

可能是
![1657526615446](https://user-images.githubusercontent.com/109065366/178217237-67d17b35-c304-4074-8e88-3eac79538246.png)
的重写有点问题

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
```js
SlateTransforms.setNodes(editor, PreElement)
// 转换当前节点，但是返回的是两个paragraph类型
```

没懂你这一步要干嘛，要转换为什么？

而且，setNodes 的参数也没传对，一般需要三个参数 https://www.wangeditor.com/v5/API.html#setnodes

**Comment by BB-zhan** [comment]
我使用的vue2。就是通过自定义的toolBar绑定自定义函数，toolBar里面的按钮通过this.$emit()触发toolBar组件绑定的函数。
自定义toolBar组件里面的按钮及函数：
![1657546954088](https://user-images.githubusercontent.com/109065366/178278061-b53ae958-6f2e-4692-b833-c6c03b4ad05f.png)
![1657547006366](https://user-images.githubusercontent.com/109065366/178278176-5a86c640-d6ef-4858-b42e-4c8f7e586bd9.png)
组件toolBar绑定的函数：
![1657547066880](https://user-images.githubusercontent.com/109065366/178278352-ac76b868-8559-40d9-a97f-2b6b774cfb75.png)
![1657547160901](https://user-images.githubusercontent.com/109065366/178278688-eab4dba7-6fe6-4cc4-84fd-63df1d98c06d.png)
我想将当前默认行的元素转为代码块
![1657547614245](https://user-images.githubusercontent.com/109065366/178280414-1b951355-0444-40af-9a6b-c2f44b867be5.png)
结果是
![1657547768689](https://user-images.githubusercontent.com/109065366/178280711-43daa115-9580-4345-b3f6-bf1fec6e8dfb.png)

**Comment by wangfupeng1988** [comment]
> 我想将当前默认行的元素转为代码块

你可以参考源码 https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/code-block/menu/CodeBlockMenu.ts 其中的 `changeToCodeBlock` 这个函数
