### ISSUE TITLE
onChange获取纯文本

### ISSUE THREAD

**Issue by lyy199212** [wangeditor-team/wangEditor#4498]
## 问题描述

在onchange事件中想获取纯文本

## wangEditor 版本

v5.0.1

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

react官方示例中，改代码onChange={(editor) => setHtml(editor.getText())}  报错：

SyntaxError: Failed to execute 'querySelectorAll' on 'Document': 'hello world.' is not a valid selector.

**Comment by wangfupeng1988** [comment]
参考这个 https://github.com/wangeditor-team/wangEditor/issues/4493

另外，如果要在 onChange 时 setHtml ，一定要加好判断。否则容易死循环，因为 setHtml 还会继续触发 onChange
