### ISSUE TITLE
如何不跨行插入自定义扩展的元素？

### ISSUE THREAD

**Issue by a1419735487** [wangeditor-team/wangEditor#4499]
## 问题描述

我自定义了一个元素，它可以通过insertNode插入到编辑器中，但所插入的元素是跨行的：
![image](https://user-images.githubusercontent.com/72694814/178237472-b03401d6-9bd1-4272-9473-f6533e07c03e.png)
而我想像链接一样让元素与文字在同一行：
![image](https://user-images.githubusercontent.com/72694814/178237956-f9af410a-eefd-46ea-8d44-68d008243118.png)
所以我尝试使用insertText、dangerouslyInsertHtml、setHtml，但好像都被过滤了没有被解析出来
请问有什么方法解决这个问题呢？

## wangEditor 版本

![image](https://user-images.githubusercontent.com/72694814/178237407-cbc338af-6bb6-4ff8-b9c0-e487a4d6efd1.png)

## 是否查阅了文档 ？

是

**Comment by wangfupeng1988** [comment]
你需要注册一个插件 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E6%8F%92%E4%BB%B6

然后在其中自定义 isInline 方法，参考这里 https://github.com/wangeditor-team/wangEditor-plugin-mention/blob/main/src/module/plugin.ts

---

wangEditor 所有的元素默认都是 block 的，所以要对你这个 elem 设置为 inline ，这样就可以不换行了。
