### ISSUE TITLE
Please help set font options

### ISSUE THREAD

**Issue by arabicmy** [wangeditor-team/wangEditor#4500]
Please help set font options and set editor.setHtml
Hello, I do not know English or Chinese, and I could not figure out how to set and change the fonts. Please put an example and the complete code to set the fonts option, thank you very much.
Also, I could not set the editor.setHtml. Please give an example.
I am new to programming, please help

![image](https://user-images.githubusercontent.com/109036019/178366169-a583a594-9495-408a-9d2e-e6d7e791ec52.png)

**Comment by wangfupeng1988** [comment]
>  set the fonts option

https://www.wangeditor.com/en/v5/menu-config.html#font-family

> setHtml

https://www.wangeditor.com/en/v5/API.html#sethtml

**Comment by arabicmy** [comment]
Thank you very much for the quick reply
Please put a complete example, because I read the previous instructions, but I did not know how to implement them. I copied the instruction and put it in the file and it did not work for me.

`
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>wangEditor default mode</title>
  <link href="https://cdn.bootcdn.net/ajax/libs/normalize/8.0.1/normalize.min.css" rel="stylesheet">
 <link href="https://cdn.jsdelivr.net/npm/@wangeditor/editor@latest/dist/css/style.css" rel="stylesheet">  
  <link href="https://unpkg.com/@wangeditor/editor@latest/dist/css/style.css" rel="stylesheet">
 
</head>

<body>
  <demo-nav title="wangEditor default mode"></demo-nav>
  <div class="page-container">
 
    <div class="page-right">
      
      <div style="border: 1px solid #ccc;">
        <div id="editor-toolbar" style="border-bottom: 1px solid #ccc;"></div>
        <div id="editor-text-area" style="height: 500px"></div>
      </div>

      
      <p style="background-color: #f1f1f1;">
        Text length: <span id="total-length"></span>；
        Selected text length: <span id="selected-length"></span>；
      </p>
    </div>
  </div>

  
  <script src="https://unpkg.com/@wangeditor/editor@latest/dist/index.js"></script>
  <script>
    const E = window.wangEditor

    // 切换语言
    const LANG = location.href.indexOf('lang=en') > 0 ? 'en' : 'en-EN'
    E.i18nChangeLanguage(LANG)

    window.editor = E.createEditor({
      selector: '#editor-text-area',
      html: '<p><br></p>',
      config: {
        placeholder: 'Type here...',
        MENU_CONF: {
          uploadImage: {
            fieldName: 'your-fileName',
            base64LimitSize: 10 * 1024 * 1024 // 10M 以下插入 base64
          }
        },
        onChange(editor) {
          console.log(editor.getHtml())

          // 选中文字
          const selectionText = editor.getSelectionText()
          document.getElementById('selected-length').innerHTML = selectionText.length
          // 全部文字
          const text = editor.getText().replace(/\n|\r/mg, '')
          document.getElementById('total-length').innerHTML = text.length
        }
      }
    })

    window.toolbar = E.createToolbar({
      editor,
      selector: '#editor-toolbar',
      config: {}
    })
  </script>
</body>

</html>`

**Comment by arabicmy** [comment]
Thank you very much for the quick response. I put the code on the page, but it didn't work, and a white page appeared


![image](https://user-images.githubusercontent.com/109036019/178456602-3d37c2e8-8498-425a-bbd0-9065e4e5efd1.png)

![image](https://user-images.githubusercontent.com/109036019/178456835-f77245d2-eb26-4345-8473-0847ba8c0db3.png)

**Comment by arabicmy** [comment]
When I delete the code for uploading images, the font code works, how do I adjust the image upload setting, thank you very much


![image](https://user-images.githubusercontent.com/109036019/178457896-eb79e380-37f0-4a7d-8d68-d34707bfe43a.png)

**Comment by arabicmy** [comment]
The image upload settings are disabled, not activated, although the code is correct, please what is the problem, thank you very much

![image](https://user-images.githubusercontent.com/109036019/178503682-e9977770-d4ac-484b-b179-ed688b7c9117.png)

![image](https://user-images.githubusercontent.com/109036019/178503534-dfb9512c-ebc5-4f3a-bea3-eaecc983f4d9.png)

**Comment by arabicmy** [comment]
Why when I put the php code the image upload feature is disabled, please what is the solution to this problem, when I delete the php code, the image upload feature works correctly.

![image](https://user-images.githubusercontent.com/109036019/178539994-3189d581-de60-4b2e-b1bc-3a8b6f7f5d73.png)

**Comment by wangfupeng1988** [comment]
> I put the code on the page, but it didn't work, and a white page appeared

See the demo page source code https://www.wangeditor.com/demo/index.html?lang=en , it worked

> Upload image

You should add a comma in this place.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/9583120/178625136-b3688b49-d272-48e6-a1c8-7008e96dd454.png">

**Comment by arabicmy** [comment]
Thanks a lot for the replies
How to disable data:image/png;base64
And upload pictures in a folder on the site and what are the settings

![image](https://user-images.githubusercontent.com/109036019/178655781-bd2a0d53-b653-476d-8325-a1fc075e6bd3.png)

**Comment by wangfupeng1988** [comment]
> How to disable data:image/png;base64
> And upload pictures in a folder on the site and what are the settings

https://www.wangeditor.com/en/v5/menu-config.html#upload-image

**Comment by arabicmy** [comment]
Thank you very much. **Can you put a simple example** of uploading an image to a folder on a site?
This is a download file
`<?php
$name=date("Y-m-d-h-i");
if ((($_FILES["file"]["type"] == "image/gif")
|| ($_FILES["file"]["type"] == "image/jpeg")
|| ($_FILES["file"]["type"] == "image/png")
|| ($_FILES["file"]["type"] == "image/pjpeg"))
&& ($_FILES["file"]["size"] < 500*1024*1024))
{
/* create new name file */
$filename   = uniqid() . "-" . time(); // 5dab1961e93a7-1571494241
$extension  = pathinfo( $_FILES["file"]["name"], PATHINFO_EXTENSION ); // jpg
$basename   = $filename . "." . $extension; // 5dab1961e93a7_1571494241.jpg
$_parts = explode( '.',$_FILES["file"] );
$_ext = end( $_parts );
$_extcom = strtolower( $_ext );
$Files=$name.".".$_extcom;
$ext = pathinfo($_FILES['file']['name'], PATHINFO_EXTENSION);
$file_name=$_FILES["file"];
$imagename = $file_name . time() . "." . $ext;
  if ($_FILES["file"]["error"] > 0)
    {
    echo "Return Code: " . $_FILES["file"]["error"] . "<br />";
    }
  else
    {
    if (file_exists("./upload-img/" . $basename))
      {
      echo $basename . " already exists. ";
      }
    else
      {
      move_uploaded_file($_FILES["file"]["tmp_name"],
      "./upload-img/" . $basename);
       #echo "Stored in: " . "./upload-img/" . $basename;
      $picAddr = Array("./upload-img/" . $basename);
      $result = Array('errno' => 0, 'data' => $picAddr);
      echo json_encode($result);
      }
    }
}
else
{
  //echo "Invalid file";
  $picAddr = Array("./upload-img/" . $basename);
  $result = Array('errno' => 1, 'data' => $picAddr);
  echo json_encode($result);
}
?>`

**Comment by wangfupeng1988** [comment]
upload image to server demo https://github.com/wangeditor-team/server

PS: you can translate Chinese to English.

**Comment by arabicmy** [comment]
Thank you very much
This code works for me, but I don't know how to change the image title: (**https://www.wangeditor.com/image/logo.png**) to the file name.
![image](https://user-images.githubusercontent.com/109036019/178715657-e31ca611-dfe2-4ae7-8155-e64da259ba8f.png)

`
uploadImage: {
//base64LimitSize: 0, // 5 * 1024 | 5kb 以下插入 base64
//uploadImgShowBase64: true,    
server: "up5.php",
fieldName: "file",
uploadImgServer: "load-img/",
metaWithUrl: false, // 参数拼接到 url 上
headers: { Accept: 'text/x-json' },
debug: true,
zIndex: 0,
showLinkImgAlt: true,
showLinkImgHref: true,
showLinkImg: true,
maxFileSize: 100 * 1024 * 1024, // 1M
maxNumberOfFiles: 10,
allowedFileTypes: [],
meta: { token: 'xxx', otherKey: 'yyy' },
metaWithUrl: true,
timeout: 500 * 1000, // 5 秒
onBeforeUpload(files) {
console.log('onBeforeUpload', files)
return files 
},
onProgress(progress) {
console.log('onProgress', progress)
},
onSuccess(file, res) {
console.log('onSuccess', file, res)
},
onFailed(file, res) {
alert(res.message)
console.log('onFailed', file, res)
},
onError(file, err, res) {
alert(err.message)
console.error('onError', file, err, res)
},
customInsert(res, insertFn) {
console.log('customInsert', res)
const imgInfo = res.data[0] || {}
const { url, alt, href } = imgInfo
if (!url) throw new Error(`Image url is empty`)
console.log('自己插入图片', url)
insertFn(url, alt, href)
},
customUpload(file, insertFn) {
console.log('customUpload', file)
return new Promise((resolve) => {
setTimeout(() => {
const src = `https://www.wangeditor.com/image/logo.png`
insertFn(src, '百度 logo', src)
resolve('ok')
}, 500)
})
},
},
`
