### ISSUE TITLE
windows 上复制粘贴会多出很多symbol 标签

### ISSUE THREAD

**Issue by TLovers** [wangeditor-team/wangEditor#4504]
## bug 描述
在windows11 随便输入几个字然后粘贴一段纯文本
*请输入内容……*

## 你预期的样子是？
粘贴后没有其他异常的标签

## 系统和浏览器及版本号

- 操作系统
- windows11
- 浏览器和版本
- 谷歌103版本
## wangEditor 版本
"wangeditor": "^4.7.12",
*请输入内容……*
1111111 测试测试
## demo 能否复现该 bug ？
能
-  mac 貌似无法复现
- 我拖拽一张图片上传下 后面我看下怎么补一个在线demo

## 在线 demo
![bug](https://user-images.githubusercontent.com/26561694/178434527-adfdd37a-4301-4c7a-bc8e-f1e76fe68323.png)

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 找一个windows 电脑然后用v4版本， 先复制一段纯文本 然后随便输入几个字
- 步骤二
- 在刚刚输入的文本后面粘贴 一定不能换行粘贴，要在刚刚的文字后面粘贴
- 步骤三
- 粘贴后页面元素多了很多无效的标签比如symbol circle  path 这些svg元素标签

**Comment by wangfupeng1988** [comment]
你用的版本是 v4 吗？

但这个 demo  https://www.wangeditor.com/demo/ 是 v5 的

请先确认好版本

**Comment by TLovers** [comment]
是v4版本

**Comment by wangfupeng1988** [comment]
那很遗憾。v5 发布之后，v4 没有精力维护了。你可以自己过滤一下这些无用标签。

业余开发，精力优先，还请体谅~
