### ISSUE TITLE
代码高亮增加 Vue

### ISSUE THREAD

**Issue by aaamrh** [wangeditor-team/wangEditor#4505]
## 功能描述

React项目中代码块高亮没有vue，也不能选择vue

## 版本
"@wangeditor/editor": "^0.15.11",
"@wangeditor/editor-for-react": "^0.6.23",

## 代码选择配置输出
**editor?.getMenuConfig('codeSelectLang').codeLangs** 结果：

0: {text: 'CSS', value: 'css'}
1: {text: 'HTML', value: 'html'}
2: {text: 'XML', value: 'xml'}
3: {text: 'Javascript', value: 'javascript'}
4: {text: 'Typescript', value: 'typescript'}
5: {text: 'JSX', value: 'jsx'}
6: {text: 'Go', value: 'go'}
7: {text: 'PHP', value: 'php'}
8: {text: 'C', value: 'c'}
9: {text: 'Python', value: 'python'}
10: {text: 'Java', value: 'java'}
11: {text: 'C++', value: 'cpp'}
12: {text: 'C#', value: 'csharp'}
13: {text: 'Visual Basic', value: 'visual-basic'}
14: {text: 'SQL', value: 'sql'}
15: {text: 'Ruby', value: 'ruby'}
16: {text: 'Swift', value: 'swift'}
17: {text: 'Bash', value: 'bash'}
18: {text: 'Markdown', value: 'markdown'}

**Comment by aaamrh** [comment]
查找过一些Primsjs相关资料，可能 markup 语言好像能够高亮vue

**Comment by wangfupeng1988** [comment]
HTML 即可高亮 vue
