### ISSUE TITLE
收集 wangEditor5 文档 demo 和视频教程的问题和建议

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#4507]
如题，

大家有任何问题和建议（仅限文档 demo 和视频教程的），都可以在这里回复，如合理，我近期将优化。

- 文档 https://www.wangeditor.com/
- demo https://www.wangeditor.com/demo/index.html
- 视频教程 https://www.wangeditor.com/v5/video-course.html

**Comment by ddmy** [comment]
建议将部分api使用方式，增加在线可编辑的demo，比如codepen

**Comment by liangtianhua1** [comment]
富文本编辑器在大文本量的时候，回显值会严重卡顿，并且在我切换的时候，或者删除，卡顿感很严重.

**Comment by leidao** [comment]
建议出一些slate的使用教程和自定义插件开发的教程。基本使用看文档都会，自定义插件时和slate相关的知识网上文档少，还多是英文的，更需要文档

**Comment by yimu0001** [comment]
对于现有的类型，比如音视频音频啥的，请允许添加自定义属性，像是视频封面等

**Comment by yimu0001** [comment]
试用新版本的时候，对于自定义弹窗类型按钮，有些疑惑，能否使用组件的方式来实现弹窗，这样也方便

**Comment by Alan-AW** [comment]
在vue2中初始化editor的时候自定义上传图片配置没法动态修改的问题：
比如我在data中配置了上传图片 MENU_CONF.uploadImage{ meta: { imageTitle: 'xxxxxx' } }
这个meta是文档中的“其他自定义参数”，我希望动态的修改他的值传到后端，但是在vue中这个meta的值被改变了，上传的时候并没有改变，仍然是初始化的时候的值，也就是说我在初始化的时候这个meta是空的那么上传的时候他就是空的，哪怕后面被修改了，上传的时候依旧是空的。

**Comment by wangjunjx8868** [comment]
缩进量建议改成 1em,目前默认是2em,2em 在一些浏览器下是4个汉字

**Comment by wangjunjx8868** [comment]
建议增加纯js 使用说明DEMO，有些人不懂ts

**Comment by realhuhu** [comment]
demo里有个生成目录的，但是貌似只能在editor里用，生成的html没有id无法使用那个目录

**Comment by youfeed** [comment]
就是 开始使用能帮 源码编译 依赖 命令行给一下吗？不怕笑话 我折腾了两天源码 跑不起来
`
npm install
npm start
`

**Comment by HostDay123** [comment]
多增加些自定义方面的视频教程和文档，可以尽量细一些，在目前已有的基础上更多的都是需要自己定制化的东西，授人以鱼不如授人以渔。
具体来讲：

1. 比如implements ISelectMenu中需要重写的每个方法具体都是干什么的，会在什么情况下被调用到，在这些方法中一般都会做一些什么样的逻辑处理。
2. 还有一些可以自定义扩展的方法和参数，这些可以在文档中都罗列一下。
3. 在视频和文档中都可以向Slate中深入一下
赞同他的观点
[https://github.com/wangeditor-team/wangEditor/issues/4507#issuecomment-1182673409](url)

**Comment by wangjunjx8868** [comment]
建议增加html源码模式

**Comment by wangfupeng1988** [comment]
> 建议增加html源码模式

默认不会支持。有需要自己自定义开发即可。

**Comment by bjw321** [comment]
有考虑加上上传音频功能么

**Comment by doYbest** [comment]
希望可以有markdown插件的demo和使用

**Comment by lihqi** [comment]
> 就是 开始使用能帮 源码编译 依赖 命令行给一下吗？不怕笑话 我折腾了两天源码 跑不起来 `npm install npm start`

[这里](https://github.com/wangeditor-team/wangEditor/blob/master/docs/dev.md)

**Comment by KingPengZero** [comment]
插入链接的视频，iframe不支持播放啊

https://www.bilibili.com/video/BV1HV4y1E7Mm?share_source=copy_web&vd_source=47a9988ce8fbaddaf8abee08e91d9a3b

<iframe src="//player.bilibili.com/player.html?aid=856364329&bvid=BV1HV4y1E7Mm&cid=784261048&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/19372274/182519796-e09f2af9-bd0d-4f48-ae50-6cf075f76334.png">

**Comment by wcx1978** [comment]
表格功能的橹棒性比较弱。如我稍改了改表内内容。 不知什么原因就再也不能 在 editor 里改的了。 只能看。 我就只能全清空，再把read 出来的版面 复制过去。 再保存又行。   带表格的文章都容易 突发性出问题，随机，没规律。  我在textarear里 从底层稍改改 html 代码，存入字段。后，有时再打开，也edit 不了。 也只能复制粘贴，重整一下。
