### ISSUE TITLE
点击工具栏icon报错：Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by CJonSnow** [wangeditor-team/wangEditor#4508]
## bug 描述
点击工具栏任意图标，浏览器报错（Unable to preventDefault inside passive event listener invocation.），但不影响功能正常使用

## 你预期的样子是？

浏览器没有提示错误

## 系统和浏览器及版本号

- 操作系统  win10
- 浏览器和版本 chrome 版本 103.0.5060.114（正式版本）（64 位）

## wangEditor 版本
"vue": "^3.2.16",
"@wangeditor/editor": "^5.1.2",
 "@wangeditor/editor-for-vue": "^5.1.12",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
- 步骤一 点击工具栏图标
![image](https://user-images.githubusercontent.com/44609646/178466758-8565a3a3-21be-4af6-84c9-0f85bd49dab5.png)
- 步骤二 浏览器发生报错
![image](https://user-images.githubusercontent.com/44609646/178466890-cd0a840c-f375-4557-aac0-dd2153a87240.png)

**Comment by wangfupeng1988** [comment]
请详细描述问题复现步骤
