### ISSUE TITLE
vue3中自定义插件

### ISSUE THREAD

**Issue by qc5926** [wangeditor-team/wangEditor#4509]
## 问题描述

*请输入遇到的问题...*
想自定义字号组件，但是在vue3中没有例子可供参考，大神可否指点一二，万分感谢
## wangEditor 版本
v5.0.0
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 想自定义字号组件

没懂你的需求，你具体想做什么？

**Comment by qc5926** [comment]
现在字号只支持传入像素集合；
我想更改下拉框中显示为汉字和菜单当中的图标
![image](https://user-images.githubusercontent.com/66767805/178625426-7489c1b8-04f7-48fe-a384-ecacffbe24ce.png)

**Comment by wangfupeng1988** [comment]
那你可以参考标题菜单的源码 https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/header
