### ISSUE TITLE
img src引用资源 权限问题

### ISSUE THREAD

**Issue by yuluo-zy** [wangeditor-team/wangEditor#4510]
## 问题描述

大佬你好, 因为上传图片接口上有权限验证, 当我保存img 的 src 之后, 再次渲染的时候, 会因为 img 浏览器线程请求, 而无法携带 token.

想问一下 有什么方法 可以使img 标签的渲染 可以自定义请求

## wangEditor 版本
最新版

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

保存img 的 src 之后, 再次渲染的时候, 会因为 img 浏览器线程请求, 而无法携带 token.

**Comment by wangfupeng1988** [comment]
这个不支持。
