### ISSUE TITLE
点击插入图片等功能弹出窗口因编辑器高度太小显示不全

### ISSUE THREAD

**Issue by linklin7** [wangeditor-team/wangEditor#4511]
## bug 描述

点击“链接”或者“插入图片”等菜单功能时，弹出的窗口在编辑器区域内，当编辑器高度很小时，无法看全弹窗内容，如下图
<img width="526" alt="image" src="https://user-images.githubusercontent.com/7196297/178626627-87dbc0aa-6bcb-44ae-bda4-184a082b2535.png">

## 你预期的样子是？

点击菜单功能弹出的窗口，层级应该高于编辑器本身，不会因为编辑器高度太小而看不全弹窗

## 系统和浏览器及版本号

- 操作系统
- 所有浏览器和版本

## wangEditor 版本

wangEditor 5.1.6

**Comment by wangfupeng1988** [comment]
你可以覆盖一下 `.w-e-modal` 这个 css class 的 `z-index`

如下图

<img width="1607" alt="image" src="https://user-images.githubusercontent.com/9583120/190073325-a931ce55-4622-4d54-93e7-e916d0d25c6a.png">
