### ISSUE TITLE
插入表格问题

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4512]
## bug 描述

编辑器开头输入几个文字，再插入一个表格，把开头输入的几个文字删除，这一行空白就不能删除了

## 你预期的样子是？

将空白可以删除

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本：chrome 103.0.5060.114

## wangEditor 版本

V5最新版本

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
# English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 编辑器开头输入几个文字
- 步骤二
- 插入表格
- 步骤三
- 将编辑器开头的几个文字删除，当前这个空行就不能删除了

**Comment by wangfupeng1988** [comment]
这符合预期。表格上面得留一些位置，方便后续输入。

**Comment by zxueliang** [comment]
等需要的时候再回车呗

**Comment by wangfupeng1988** [comment]
目前不支持删除第一行
