### ISSUE TITLE
图片上传后编辑的时候,如何禁用掉设置图片链接的菜单

### ISSUE THREAD

**Issue by hexu2016** [wangeditor-team/wangEditor#4514]
## 问题描述

图片上传后编辑的时候,如何禁用掉设置图片链接的菜单

## wangEditor 版本

5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

因为是要发布到微信小程序里面的,不可能让用户随便输入连接的,否则发布后也是打不开的

**Comment by wangfupeng1988** [comment]
参考这里 https://www.wangeditor.com/v5/editor-config.html#hoverbarkeys
