### ISSUE TITLE
在Word复制带表格的内容的问题

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4515]
## bug 描述

Word里有表格，表格下面有文字，同时将Word里的表格和下面的文字复制到编辑内，表格下面的文字会在表格的右侧，不在表格下面的问题（非常着急用）

## 你预期的样子是？

表格下面的文字应该就在表格的下面，不要 跑到 表格的右侧

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本：chrome  103.0.5060.114

## wangEditor 版本

V5最新版本

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 将word里插入一个表格，回车输入一行文字
- 步骤二
- 将word里的内容全选复制，粘贴到编辑器里
- 步骤三
- 表格下面的一行文字会在表格的右侧，没在表格的下面

**Comment by wangfupeng1988** [comment]
这个问题刚修复了，你升级 `@wangeditor/editor` 最新版试试
