### ISSUE TITLE
阅读时的一些功能

### ISSUE THREAD

**Issue by a495433** [wangeditor-team/wangEditor#4517]
## 功能描述

仿epub 实现文档阅读中的高亮及其它一些便利性操作

## 提炼几个功能点
在 wangEditor  不用来编辑,只用来展示时

- 功能1 选中部分文字松开鼠标时可以 接收到 事件 
- 1.1 可以通过 事件传递过来的参数  对选中的文字进行高亮 (高亮可以有不同的颜色)
- 1.2 可以通过事件传递过来的参数    editorRef.value.scrollToElem('') 方法  滚动到选中的位置

## 原型图

![3f74ca5f8f011f3d8e2fb879412f00a](https://user-images.githubusercontent.com/15401183/178661974-55e446bf-74b4-455d-8af0-a1ab2e337350.png)

![bf96c6e0bd8b1d70fd5346b9f3a0f5a](https://user-images.githubusercontent.com/15401183/178661998-bedd72fc-c3a8-496c-bb41-c359f57baada.png)

## 可参考的案例
epubjs

**Comment by wangfupeng1988** [comment]
这是个很好的建议！

不过，目前编辑器不支持，而且没有其他人提过这个需求，所以先 pending 吧。我们得先去搞一些优先级搞的任务。
