### ISSUE TITLE
cdn引入控件,提示’Cannot find textarea DOM by selector '#editor-container'‘

### ISSUE THREAD

**Issue by Gu4uG** [wangeditor-team/wangEditor#4519]
## bug 描述
使用cdn引入控件,提示错误
## 你预期的样子是？
<img width="594" alt="image" src="https://user-images.githubusercontent.com/33747645/178694676-da2008be-e1f9-4b44-9fee-8d807b97bb17.png">

## 系统和浏览器及版本号

- 操作系统   macOS
- 浏览器和版本  版本 103.0.5060.114

## wangEditor 版本
cdn最新版
## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

https://stackblitz.com/edit/web-platform-uop5qz?file=index.html
## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
第一，如果用于普通 js 页面，可参考 demo https://www.wangeditor.com/demo/

第二，如果你用于 Vue ，可参考官网的 Vue 组件，不建议用 CDN 方式引入 vue ，很难用
