### ISSUE TITLE
在antd form.list中循环输出多实例，移动表单项位置后多个实例开始互相影响

### ISSUE THREAD

**Issue by elevensky** [wangeditor-team/wangEditor#4521]
## bug 描述

将editor 作为受控组件，放到antd form.list中循环输出多个实例，一旦移动则所涉及的有关实例开始相互影响。

## 你预期的样子是？

独立受控，互不影响

## 系统和浏览器及版本号

- mac pro
- chrome

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

## 在线 demo
https://codesandbox.io/s/react-wangeditor-demo-forked-ey8vfy?file=/src/App.js

## 最小成本的复现步骤

- 添加两个表单项，分别输入对应内容
- 移动位置
- 查看内容

**Comment by hahaaha** [comment]
在 form.item中设置key 即可
可参考 https://codesandbox.io/s/react-wangeditor-demo-forked-r4heov
