### ISSUE TITLE
图片100%会出现水平滚动条

### ISSUE THREAD

**Issue by sakurawaifu** [wangeditor-team/wangEditor#4523]
## 问题描述

将插入的图片设为100%，会导致编辑区域（.w-e-scroll）出现水平滚动条，很不美观，并且导致操作比较不方便。
debug发现是因为.w-e-image-container中设置了margin: 0 10px;。如果去掉就能把水平滚动条消除掉。

请问设置margin: 0 10px是出于什么样的考虑？个人认为应该与边界严格对齐，不应该出现偏移。

## wangEditor 版本

v5.1.7

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

- 步骤一：插入图片
- 步骤二：将图片设为100%
- 步骤三：观察编辑区域，会出现水平滚动条

**Comment by wangfupeng1988** [comment]
> 请问设置margin: 0 10px是出于什么样的考虑？

为了让图片和左右的文字有点间隙，别紧挨在一起。

**Comment by wangfupeng1988** [comment]
这个问题还好，只是样式优化，不是功能问题。

**Comment by fantasy1943** [comment]
> 这个问题还好，只是样式优化，不是功能问题。 先 pending 吧，等我忙完其他 bug ，来看看。

大佬你好，我也遇到了这个样式优化点，这个问题怎么知道现在是否改好了呢，会通知我们吗

**Comment by wangfupeng1988** [comment]
改了就会关闭 issue 的，跟踪这个 issue 状态即可

**Comment by fantasy1943** [comment]
明白了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月11日(星期四) 上午8:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 图片100%会出现水平滚动条 (Issue #4523)





 
改了就会关闭 issue 的，跟踪这个 issue 状态即可

**Comment by wangfupeng1988** [comment]
已修复，请升级最新版 `@wangeditor/editor`
