### ISSUE TITLE
获取已删除的图片

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4525]
## 问题描述

获取已删除的图片，在 [onInsertedImage](https://www.wangeditor.com/v5/menu-config.html#%E5%9B%BE%E7%89%87) 来收集所有上传或者插入的图片，最后保存编辑器内容之前，使用 editor.getElemsByType('image') 获取当前编辑器的所有图片，我想知道的是 保存编辑器之前的事件是什么事件，因为我把 编辑器 封装成了一个组件，保存编辑器内容之前，在这个编辑器组件内进行删除图片。

## wangEditor 版本

V5最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 我想知道的是 保存编辑器之前的事件是什么事件

例如你点击一个按钮，获取 HTML 然后提交给服务端。就这个时机。

**Comment by zxueliang** [comment]
@wangfupeng1988 
点击按钮是在父组件里，我想在 编辑器 的子组件里进行处理，该怎么处理呢

**Comment by wangfupeng1988** [comment]
父子组件通讯，用自定义事件就可以
