### ISSUE TITLE
导出的html中H标签嵌入id属性，便于做目录锚点跳转

### ISSUE THREAD

**Issue by HostDay123** [wangeditor-team/wangEditor#4526]
## 功能描述

*建议在导出html内容的时候，将H标签的id加上，便于做文档的目录跳转。*

## 提炼几个功能点

- 功能1 获取到的html格式文档内容中，H标签加上id属性
- 功能2
- 功能3

## 原型图

*![image](https://user-images.githubusercontent.com/48356902/178934502-d4e3241d-62a0-420e-8274-8706fe6502aa.png)
这是getHtml（）方法获取到的内容，h1标签中并没有id属性。
![image](https://user-images.githubusercontent.com/48356902/178934742-90b74944-5b94-4b48-987e-27761b8aa06a.png)
这是editor.getElemsByTypePrefix('header')方法获取构建出的目录。
**在h标签中加上id属性后便于使用导出的html内容实现类似editor.scrollToElem（）方法实现的功能。**
*

## 可参考的案例

**

**Comment by liujian891010** [comment]
同需要此功能


想给选中的文字 绑定class  or  id~~

点击后  可以自定义操作~~

**Comment by wangfupeng1988** [comment]
> 同需要此功能
> 
> 想给选中的文字 绑定class or id~~
> 
> 点击后 可以自定义操作~~

你说的感觉是另外一些需求，可以单独提交 issue ，别和这个混在一起。

**Comment by HostDay123** [comment]
**还可以有什么办法来解决这个问题？**
查看header的实现，在选择标题后生成的dom无法修改id属性（如下截图位置）
![image](https://user-images.githubusercontent.com/48356902/179434991-f590b142-bb92-45a4-b97a-1a655cf083c5.png)
，都是自动生成w-e-element-x的样式，
现在有两个想法来解决
1. 获取到在创建标题时自动生成的w-e-element-x样式的id属性，在elem-to-html.ts中人为拼接上id属性。但问题在于无法在rwnder-elem.ts中获取到它自动生成的id属性，也无法传到elem-to-html.ts中来获取。
2. 通过自己创建标题的id属性方式，这样可以通过标题内容作为id的方式实现功能。但这个问题在于无法覆盖它自动生成的w-e-element-x样式id，
![image](https://user-images.githubusercontent.com/48356902/179435666-f636dd33-4c28-474b-aa20-5d8cf587446a.png)
![image](https://user-images.githubusercontent.com/48356902/179435703-f19b18ca-be6d-4e2a-99db-61e0f531103e.png)
![image](https://user-images.githubusercontent.com/48356902/179435743-e13ec5de-d1a6-433f-adea-3c034ebe8f10.png)

**Comment by wangfupeng1988** [comment]
@HostDay123 按你提出的问题（在 HTML 中为 header 加 id ），只需要在这里加一个 id 即可，你找错地方了

https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/header/elem-to-html.ts#L10

注意 id 别重复

**Comment by xiajie10** [comment]
@wangfupeng1988 你那个说一下实现过程吗？特别需要这个目录的功能

**Comment by wangfupeng1988** [comment]
我近期可以升级增加上 header id 

大家对 id 有要求吗？例如我弄个随机数作为 id ，是否可以？

**Comment by xiajie10** [comment]
@wangfupeng1988 只要是不同的ID就可以      不会出现相同的ID

**Comment by wangfupeng1988** [comment]
我又考虑一下，目前暂时无法直接内置这个 header id ，原因有二
- id 不能简单粗暴的使用随机数，可能会出现什么坑
- 如果用户传入的 HTML 里本来就有 header id （虽然编辑器不识别），但再生成一个不一样的  id ，就感觉乖乖的

----

所以，大家用这个方法去自定义吧，这样 id 规则可以自己控制：

```js
import { Boot } from '@wangeditor/editor'
// 如果是 CDN 引入，可通过 wangEditor.Boot 获取

function renderH1(slateElem, childrenHtml) {
    const id = `h1-${Math.random().toString().slice(-5)}`
    return `<h1 id="${id}">${childrenHtml}</h1>`
}

Boot.registerElemToHtml({
    type: 'header1',
    elemToHtml: renderH1,
})

// 继续注册 header1 header2 header3 header4 header5

// 要在创建编辑器（或使用 Vue React 组件）之前注册，且全局只能注册一次
```
