### ISSUE TITLE
上传图片报错

### ISSUE THREAD

**Issue by wenreq** [wangeditor-team/wangEditor#4528]
## bug 描述

控制台报错：wangEditor.js?6fad:5095 Uncaught TypeError: Cannot read properties of undefined (reading 'call')

![image](https://user-images.githubusercontent.com/31761376/178952023-4d588a3d-bf3e-4124-8976-2c77be0a6d6c.png)
![1657791143450_1583D313-60B2-4578-A47A-522F72DDFB5A](https://user-images.githubusercontent.com/31761376/178952091-04c99ea0-d9a1-493e-b775-7beaf359c879.png)
![image](https://user-images.githubusercontent.com/31761376/178952126-be7dd03d-838a-409b-9364-1f389bf572bf.png)

**Comment by wangfupeng1988** [comment]
参考这个 demo https://github.com/wangeditor-team/server
