### ISSUE TITLE
在iframe里面使用问题

### ISSUE THREAD

**Issue by ITso-easy** [wangeditor-team/wangEditor#4529]
##作者您好，
##首先感谢你的无私奉献，让开发者有一个很好的工具可以用。
#其次我再使用过程中碰见的问题
#vue.2.0+环境 
#步骤1.按照文档把wangEditor5简单封装成一个功能组件。
#步骤2 在一个.vue的业务功能文件中引入（富文本框）能正常显示
          但是，在这个.vue业务功能文件中有一个iframe标签，我需要把iframe里面的指定input 标签替换成富文本编辑框
         出现不能正常使用情况
##下面问 代码和效果图
![image](https://user-images.githubusercontent.com/29625754/178970625-5c5469e8-157f-41ea-9f66-513e33e9e998.png)
![image](https://user-images.githubusercontent.com/29625754/178970729-02f8a9dc-8aba-4f4b-8828-63c662ffc6ff.png)
#效果如下图
![image](https://user-images.githubusercontent.com/29625754/178970880-3d6590ab-a8fc-440d-bf48-e87250a8579e.png)
![image](https://user-images.githubusercontent.com/29625754/178971055-246aa60d-20dd-4a97-8ad4-b690f5254955.png)
#希望能得到作者的解惑.谢谢。

**Comment by wangfupeng1988** [comment]
没看懂你的问题。

在你的源代码截图中，也没有看到你哪里用了 wangEditor

**Comment by ITso-easy** [comment]
感谢你的回复。



我再最开始引入的这个文件 里面有使用到&nbsp; （引入的文件为下面截图）








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 在iframe里面使用问题 (Issue #4529)





 
没看懂你的问题。
 
在你的源代码截图中，也没有看到你哪里用了 wangEditor

**Comment by ITso-easy** [comment]
#我在开始的时候引入了一个封装的wangEditor组件
![image](https://user-images.githubusercontent.com/29625754/178986971-9becd75d-f364-4235-849f-2a1446407a2f.png)
![image](https://user-images.githubusercontent.com/29625754/178987286-12a84b68-0a92-47eb-a494-6fede1d376f2.png)
zhli这里动态插入
#封装的组件是这样的
![image](https://user-images.githubusercontent.com/29625754/178987122-2193249d-50e5-4458-982f-34eaf3af6454.png)
![image](https://user-images.githubusercontent.com/29625754/178987162-b8769001-6ab8-4319-b148-32303209efa8.png)
![image](https://user-images.githubusercontent.com/29625754/178987195-c8c30b7f-c27a-41c6-bf0a-88dcef878eb0.png)

**Comment by ITso-easy** [comment]
#我在开始的时候引入了一个封装的wangEditor组件
![image](https://user-images.githubusercontent.com/29625754/178989883-1daf711f-8ff5-4a70-ae74-2dba21be621b.png)
#在这里动态插入
![image](https://user-images.githubusercontent.com/29625754/178989949-4009c799-c97d-423b-a63c-95dbfc2097e4.png)
#封装的组件代码在下图
![image](https://user-images.githubusercontent.com/29625754/178990057-5fbf6e61-172b-4752-aba8-e9a10b3b3f9b.png)
![image](https://user-images.githubusercontent.com/29625754/178990098-fcb53c87-97a1-4f75-a991-0878952c23ba.png)
![image](https://user-images.githubusercontent.com/29625754/178990135-d6627620-929b-42e1-b67f-6e0b8533eada.png)

**Comment by wangfupeng1988** [comment]
你这个过程比较复杂，我不好复现你的问题呀。

有没有什么简单、低成本的方式能复现你的问题？例如你写一个最简单的 demo ，能复现问题即可，不要有任何其他无关代码。

**Comment by ITso-easy** [comment]
#先上效果图
![image](https://user-images.githubusercontent.com/29625754/179170439-54957ae5-026c-439a-a4b8-91a800ba4d42.png)
#wangEditor 应用的vue组件
![image](https://user-images.githubusercontent.com/29625754/179170832-384e7080-7c5d-4592-89cd-fa5b6205b7d5.png)
#业务dome 引用上面的vue组件
![image](https://user-images.githubusercontent.com/29625754/179171534-dee635ee-b47c-422f-a18e-c6415a8303a2.png)
以上就是dome实现代码。

**Comment by wangfupeng1988** [comment]
看起来是没有在 iframe 中引用样式。

你在 iframe 中新增一个 style 标签，引入 css 文件试试 https://www.wangeditor.com/v5/installation.html#cdn

**Comment by ITso-easy** [comment]
#我现在做了一个这样的方式动态引入
![image](https://user-images.githubusercontent.com/29625754/179206663-655eaa12-6997-4a11-bfaf-55071288058c.png)
#生成的节点如下图
![image](https://user-images.githubusercontent.com/29625754/179206773-026c9d44-1efa-4755-af6a-e609c9a06cb4.png)
#效果还是不行，是否为为引入的方式有问题？

**Comment by wangfupeng1988** [comment]
动态引入不行的话，你就同步引入，参考这里 https://github.com/wangeditor-team/wangEditor-plugin-formula/blob/main/src/register-custom-elem/index.ts#L24
