### ISSUE TITLE
从其他输入框复制的内容会粘贴两次

### ISSUE THREAD

**Issue by herb100** [wangeditor-team/wangEditor#4530]
## bug 描述

从其他任意输入框复制内容，到 wangeditor 粘贴，会粘贴两次。

产生原因：customPaste 内的 event.preventDefault() 并没有生效，没有阻止默认粘贴，而 customPaste 内也会执行 insertText 插入内容，所以导致粘贴两次。

## wangEditor 版本

*wangeditor^5.1.7*

## 最小成本的复现步骤
- 步骤一
   初始化一个编辑器，配置 customPaste
- 步骤二
  从其他任意输入框复制内容，到 wangeditor 粘贴，会粘贴两次
- 步骤三

**Comment by wangfupeng1988** [comment]
第一，什么浏览器？什么版本

第二，customPaste 怎么写的，把代码贴出来

**Comment by herb100** [comment]
chrome 版本 105.0.5148.2（正式版本）dev (x86_64)
firefox 版本 105.0.5148.2（正式版本）dev (x86_64)

customPaste: (editor, event) => {
    const text = event.clipboardData.getData('text/plain') // 获取粘贴的纯文本
    editor.insertText(text)
    event.preventDefault()
    return false
}

**Comment by wangfupeng1988** [comment]
我是 chrome 浏览器，使用如下代码测试没问题，不会重复粘贴

```js
editorConfig.customPaste = (editor, event) => {
            const text = event.clipboardData.getData('text/plain')
            editor.insertText(text)
       
            return false 
        }
```

**Comment by hellozzm** [comment]
> 我是 chrome 浏览器，使用如下代码测试没问题，不会重复粘贴
> 
> ```js
> editorConfig.customPaste = (editor, event) => {
>             const text = event.clipboardData.getData('text/plain')
>             editor.insertText(text)
>        
>             return false 
>         }
> ```

通过vue的@customPaste就有这个错误

**Comment by wangfupeng1988** [comment]
vue 里不能 `return false` ，文档写的明白

**Comment by kaideng-nmg** [comment]
> 我是 chrome 浏览器，使用如下代码测试没问题，不会重复粘贴
> 
> ```js
> editorConfig.customPaste = (editor, event) => {
>             const text = event.clipboardData.getData('text/plain')
>             editor.insertText(text)
>        
>             return false 
>         }
> ```

我也有同样的问题vue3, v5版本,当复制纯文本内容(比如字母a)的时候就会有这个问题(出现2次)，其他非纯文本的内容就不会有这个问题
