### ISSUE TITLE
从控制台修改contenteditable中的内容无法更新生成的html

### ISSUE THREAD

**Issue by leewhui** [wangeditor-team/wangEditor#4533]
## bug 描述

*打开控制台，从控制台中改变编辑器中的内容，无法同步生成最新的html*

## 你预期的样子是？

*从控制台中改变内容，可以调用onChange事件来生成最新的数据(html)*

## 系统和浏览器及版本号

- 操作系统: macOS Monterey 12.1
- 浏览器和版本: chrome  103.0.5060.114

## wangEditor 版本

*v5的线上demo*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 打开线上demo，可以看到html数据的
- 打开控制台，改变编辑内容

**Comment by wangfupeng1988** [comment]
> 打开控制台，从控制台中改变编辑器中的内容

具体怎么操作的？
