### ISSUE TITLE
vue 封装editor注册菜单时，二次打开页面，菜单exec事件指向如何指向为当前的vue 实例

### ISSUE THREAD

**Issue by WangEbo** [wangeditor-team/wangEditor#4534]
## 问题描述

*请输入遇到的问题...*
注册菜单，exec 执行事件
## wangEditor 版本
5.1.6
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- import { Boot, createEditor, createToolbar } from '@wangeditor/editor';
- if (!Boot.hasPreview) {
        const previewConf = {
	        key: 'preview', // menu key ，唯一。注册之后，可配置到工具栏
	        factory() {
		        return {
			        title: '预览',
			        tag: 'button',
			        iconSvg:'***',
			        getValue() {},
			        isActive() {},
			        isDisabled() {},
			        //注册会将当前 vue 实例的preview 绑定到 preview ，二次生成后，事件依然指向上一个实例
			        exec: self.preview,
		        };
	        },
        };
        // 注册到 wangEditor
        Boot.registerMenu(previewConf);
        Boot.hasPreview = true;
       }
- 步骤二
- createEditor
createToolbar
- 步骤三
- 打开编辑器页面，切换路由，再次打开编辑器页面，

**Comment by WangEbo** [comment]
preview  事件里的 this，始终是指向第一个vue页面实例

**Comment by wangfupeng1988** [comment]
在以下平台创建一个 demo 吧，复现这个问题（三选一即可）
- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/
