### ISSUE TITLE
setHtml()  开头是p标签的话会空一行

### ISSUE THREAD

**Issue by ry0513** [wangeditor-team/wangEditor#4536]
## bug 描述

setHtml()  开头是p标签的话会空一行，改成其他标签则没事（已测div，i，span）

## 你预期的样子是？

不空行

## 系统和浏览器及版本号

- win 11
- google 103.0.5060.114

## wangEditor 版本

"@wangeditor/editor": "^5.1.9",
"@wangeditor/editor-for-vue": "^5.1.12",

## demo 能否复现该 bug ？

能

- 中文 demohttps://www.wangeditor.com/demo/set-html.html

## 最小成本的复现步骤

- 步骤一  直接点击 setHTML 按钮   留白一行
- 步骤二 第一行改成： `<div>我是div标签</div>`   则正常

**Comment by futurelc123** [comment]
我也遇到了同样问题，但是在本地环境没有遇到，只有打包上了测试环境才有问题

**Comment by wangfupeng1988** [comment]
这个问题我复现了，明天就搞定！

**Comment by futurelc123** [comment]
非常感谢，期待您的发版。

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本即可
