### ISSUE TITLE
有序列表和无序列表的缩进和层级的功能

### ISSUE THREAD

**Issue by BB-zhan** [wangeditor-team/wangEditor#4537]
## 功能描述

列表可以缩进，类似于目录一样的
```html
<ul>
    <li>111</li>
    <li>
        <ul>
            <li>111</li>
        </ul>
    </li>
</ul>
<ol>
    <li>111</li>
    <li>
        <ol>
            <li>111</li>
        </ol>
    </li>
</ol>
```
或者
```html
<ul>
    <li>111</li>
    <ul>
        <li>111</li>
    </ul>
</ul>
<ol>
    <li>111</li>
    <ol>
        <li>111</li>
    </ol>
</ol>
```
两种结构的有序列表和无序列表

## 提炼几个功能点

![qq_pic_merged_1657877671129](https://user-images.githubusercontent.com/109065366/179196816-29c09ee9-629b-4bf6-844d-1ee8ef9c5a80.jpg)

![qq_pic_merged_1657876565836](https://user-images.githubusercontent.com/109065366/179193936-b6282df2-8c4a-43f8-8a0c-da477a836084.jpg)

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

有道云笔记：
(https://note.youdao.com/)

**Comment by wangfupeng1988** [comment]
多级列表目前还不支持，早已记录下，近期会开发。

**Comment by zhangdaliang** [comment]
棒

> 多级列表目前还不支持，早已记录下，近期会开发。
