### ISSUE TITLE
文本后面跟图片缩进问题

### ISSUE THREAD

**Issue by yumaopiaoa** [wangeditor-team/wangEditor#4538]
## 问题描述
   
    文本后面跟图片添加缩进，图片也会跟着加上缩进

## wangEditor 版本
  
   v5.13.1

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
    添加一段文本
- 步骤二
    文本后面跟着上传一张图片
- 步骤三
   给文字加上缩进
![image](https://user-images.githubusercontent.com/34874601/179202199-a4603333-13d1-46bb-bcd6-845678fc9f9d.png)

**Comment by wangfupeng1988** [comment]
已复现，会排队解决

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本即可
