### ISSUE TITLE
请问有没有可能为富文本编辑器中的内容添加点击事件

### ISSUE THREAD

**Issue by lcdpz** [wangeditor-team/wangEditor#4539]
## 问题描述

请问有没有可能为富文本中的内容添加点击事件

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

想请问是否有可能自定义实现扩展功能：点击按钮在选中的表格单元格中添加“展开更多”几个字，点击这几个字可以展开收起下一行

**Comment by wangfupeng1988** [comment]
这个目前不会支持，过于个性化的需求了
