### ISSUE TITLE
上传base64图片后,点编辑由于图片地址是base64的内容，页面会卡住很长时间，几乎崩了

### ISSUE THREAD

**Issue by sunkainj** [wangeditor-team/wangEditor#4542]
## bug 描述
上传base64图片后,点编辑由于图片地址是base64的内容，页面会卡住很长时间，几乎崩了

## 你预期的样子是？

希望图片地址要判断是不是base64,如果是的就不用显示了
另增加图片宽度的编辑，用户可以设置为多少像素，这用的地方还挺多的，目前看没法设置为指定宽度

## 系统和浏览器及版本号

- 操作系统win11
- 浏览器和版本chrome103

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
第一，wangEditor 图片上传的配置中 `base64LimitSize` 本来的用意就是：小尺寸图片使用 base64 ，体积大了就上传到服务器

> 第二，希望图片地址要判断是不是base64,如果是的就不用显示了

这个问题你可以在编辑之前，自己判断要编辑的 HTML ，是 base64 就替换为另一个图片 src

> 第三，另增加图片宽度的编辑，用户可以设置为多少像素，这用的地方还挺多的，目前看没法设置为指定宽度

可以自定义一个菜单，参考”修改视频尺寸“的源码

**Comment by sunkainj** [comment]
我上传的图片大小300k左右，你在demo里上传后点编辑试下看







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月16日(星期六) 上午9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 上传base64图片后,点编辑由于图片地址是base64的内容，页面会卡住很长时间，几乎崩了 (Issue #4542)





 
第一，wangEditor 图片上传的配置中 base64LimitSize 本来的用意就是：小尺寸图片使用 base64 ，体积大了就上传到服务器
  
第二，希望图片地址要判断是不是base64,如果是的就不用显示了
  
这个问题你可以在编辑之前，自己判断要编辑的 HTML ，是 base64 就替换为另一个图片 src
  
第三，另增加图片宽度的编辑，用户可以设置为多少像素，这用的地方还挺多的，目前看没法设置为指定宽度
  
可以自定义一个菜单，参考”修改视频尺寸“的源码

**Comment by wangfupeng1988** [comment]
demo 为了演示方便，`base64LimitSize` 设置的很大。

你实际应用时，应该设置的小一些，大的要上传到服务端。
