### ISSUE TITLE
希望能够在插入代码，选择代码语言的时候可以搜索语言

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor#4545]
## 功能描述
插入代码插件配置了多种语言之后，在插入代码的时候，每次选择语言找到对应语音都可能要翻好久。希望该插件可以加上快速检索语言的功能，比如像语雀等插入代码插件这样
*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图
![image](https://user-images.githubusercontent.com/13927744/179406188-73d8002f-f962-4e00-bde6-9ef9cb88c373.png)

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
这是一个很不错的建议。

不过考虑到当前用户反馈的情况，暂不打算支持。精力有限，得先去做更加高优的事情，希望理解。
