### ISSUE TITLE
v4版本的怎么自己控制进度条的显示与隐藏

### ISSUE THREAD

**Issue by wengshuang** [wangeditor-team/wangEditor#4547]
## 问题描述

*v4版本的在上传图片的时候进度条闪了一下就消失了*

## wangEditor 版本

*v4版本*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
v4 不支持
