### ISSUE TITLE
请问大佬用哪个库在react中把"<h1>2343242</h1><p>234</p>"这种生成的html string安全地转换成可以render的html

### ISSUE THREAD

**Issue by simon-zhangmuye** [wangeditor-team/wangEditor#4548]
https://www.wangeditor.com/demo/get-html.html
我在这个页面看到的。
我知道dangerouslySetInnerHTML可以做到，请问大佬有没有什么安全的库可以做到？

**Comment by wangfupeng1988** [comment]
如果真有这种方式，那还要 `dangerouslyInsertHtml` 干嘛呢？

**Comment by simon-zhangmuye** [comment]
@wangfupeng1988 但是dangerouslyInsertHtml不安全呀？我可以添加script，有没有什么好的库或方法。

**Comment by wangfupeng1988** [comment]
不是不安全，不会引入安全隐患。
而是不会保证完全解析语义，有可能会丢失图片、样式等。

这一点要说清楚。

**Comment by simon-zhangmuye** [comment]
@wangfupeng1988 那没有别的办法了吗？是不是只能用dangerouslyInsertHtml？我之前用过react-html-render发现会丢失样式。

**Comment by wangfupeng1988** [comment]
就像粘贴一样，无法保证内容和样式完全一直。不仅 wangEditor ，所有编辑器都做不到。

即便是有专业团队维护的语雀、飞书编辑器，也都是 case-by-case 的去转换，无法用统一的方式来做。
