### ISSUE TITLE
iframe 动态插入wandEditor使用问题

### ISSUE THREAD

**Issue by ITso-easy** [wangeditor-team/wangEditor#4549]
# 继之前的问题； 在开始同步引入styel  入下图
![image](https://user-images.githubusercontent.com/29625754/179442830-2ba67b7f-3b15-4f8a-9b6e-6151bdc45ad9.png)
#创建wangEditor的时候 把样式插入进去
![image](https://user-images.githubusercontent.com/29625754/179442873-84782c8b-a2bf-46d3-88c3-ffc6e06d1e6e.png)
#页面效果展示无没有问题， 功能使用有问题：入下图所示
![1658116201593](https://user-images.githubusercontent.com/29625754/179442967-304216f3-48e5-4450-a7db-6ee41a750a01.jpg)

**Comment by wangfupeng1988** [comment]
什么操作导致了这个 bug ？

你的说明复现步骤。

**Comment by ITso-easy** [comment]
#一共两个问题；
#第一个问题；复现之前的报错；操作如下图所示
![image](https://user-images.githubusercontent.com/29625754/179467392-03a8395c-e287-4daa-8cba-adab7d781830.png)
#第二问题：iframe里面动态插入的 编辑框 操作栏无法使用（未禁用状态）如下图
![image](https://user-images.githubusercontent.com/29625754/179467584-78f3fb85-b053-4d27-b2b1-0fc1fd3ea717.png)

**Comment by ITso-easy** [comment]
那请问第二个问题请问能复现吗，iframe里面动态插入富文本编辑框，操作栏不能使用的问题

**Comment by ITso-easy** [comment]
我打开网址是这样的， 但是我不知道在哪里提交；请问应该怎么操作


涅槃重生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 上午9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] iframe 动态插入wandEditor使用问题 (Issue #4549)





 
你单独弄一个 demo ，仅去实现“iframe里面动态插入富文本编辑框”这个一个功能（别的功能不管），看能复现吗？
 
能的话，提交到这里（三选一）
  
https://codesandbox.io/
 
https://codepen.io/
 
https://stackblitz.com/

**Comment by wangfupeng1988** [comment]
你做一个 demo ，提交到 github ，给我链接也可以

**Comment by ITso-easy** [comment]
我这边网络不太好，github上传不上去。我打了一个压缩包给你。




涅槃重生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 上午10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] iframe 动态插入wandEditor使用问题 (Issue #4549)





 
你做一个 demo ，提交到 github ，给我链接也可以
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

test-project.rar (122.0K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=71313432972698cba4d7b5224431541b06060c0454030051195706035a1c525602001953560453190d540d0650045f0403500205622166405142401f1243095e5152401c1050143409&t=exs_ftn_download&code=4142b1f4

**Comment by wangfupeng1988** [comment]
传到 gitee 或 coding.net 也可以

**Comment by ITso-easy** [comment]
github 地址&nbsp;https://github.com/ITso-easy/iframe-wangEditor


涅槃重生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月20日(星期三) 上午8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] iframe 动态插入wandEditor使用问题 (Issue #4549)





 
传到 gitee 或 coding.net 也可以

**Comment by wangfupeng1988** [comment]
通过你的源码来看 https://github.com/ITso-easy/iframe-wangEditor/blob/main/src/components/home.vue

你是把一个 Vue 组件的 DOM 直接塞到了 iframe 中，也就是把生成了编辑器的 DOM 直接塞到了 iframe 中。
这种方法感觉很不合理，没讲过这样用的。

如果用 iframe ，我还是建议通过 src 来加载。例如你先定义一个前端路由 `/page/editor` ，然后把路由写到 iframe src 中。这样还比较合理。

**Comment by ITso-easy** [comment]
您好作者，在使用你的wangEditor过程中，用到了插件公式wangEditor-plugin-formula



这个弹框让用户自己输入latex语法， 但是用户一般都不知道格式，请问如何改造次弹框 让它有个初始化的模板格式
用户在使用的时候选一个自己想要的公式模板，然后输入值就可以了；
如下图所示这样

非常感谢作者。提供帮助


涅槃重生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 中午1:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] iframe 动态插入wandEditor使用问题 (Issue #4549)





 
Closed #4549 as completed.

**Comment by wangfupeng1988** [comment]
@ITso-easy  看这里 https://github.com/wangeditor-team/wangEditor/issues/4799

**Comment by ITso-easy** [comment]
可是我的业务是这样的，后台返回一个iframe页面的src地址，内容很多，有表单、有表格之类的。前端是通过动态js修改某几个指定的DOM元素，替换成wangEditor。 所以你说的这种方案好像不太适合他，请问有别的替代方案吗


涅槃重生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 上午9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] iframe 动态插入wandEditor使用问题 (Issue #4549)





 
通过你的源码来看 https://github.com/ITso-easy/iframe-wangEditor/blob/main/src/components/home.vue
 
你是把一个 Vue 组件的 DOM 直接塞到了 iframe 中，也就是把生成了编辑器的 DOM 直接塞到了 iframe 中。
 这种方法感觉很不合理，没讲过这样用的。
 
如果用 iframe ，我还是建议通过 src 来加载。例如你先定义一个前端路由 /page/editor ，然后把路由写到 iframe src 中。这样还比较合理。
