### ISSUE TITLE
按住鼠标左键选中并复制的文字，在编辑器首行粘贴报错

### ISSUE THREAD

**Issue by yumaopiaoa** [wangeditor-team/wangEditor#4550]
## bug 描述
    按住鼠标左键往右选中（非三击复制）并复制的文字，在编辑器（空白编辑器）首行粘贴报错

## 你预期的样子是？

    正常插入显示

## 系统和浏览器及版本号

- 操作系统 windows
- 浏览器和版本 chrome 103.0.5060.114

## wangEditor 版本

    5.1.10

## demo 能否复现该 bug ？

能 报错截图
![image](https://user-images.githubusercontent.com/34874601/179444129-321cddf2-b5cf-4742-b00b-5d12b0401a5c.png)

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

## 最小成本的复现步骤
- 步骤一
    找一篇文章用鼠标左键按住右拉复制
- 步骤二
    在编辑器（空白编辑器）首行直接粘贴

**Comment by wangfupeng1988** [comment]
已复现，会紧急修复的。

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本
