### ISSUE TITLE
V4版本字体设置为链接修改不了字体颜色

### ISSUE THREAD

**Issue by USER-LGF** [wangeditor-team/wangEditor#4551]
## bug 描述

*打几个空格然后输入一个字，设置那个字为链接，选中链接字和前面的空格设置字体颜色，发现设置不了颜色*

## 你预期的样子是？

*可以设置链接的字体颜色*

## 系统和浏览器及版本号

- Windows10
- Chrome 103.0.5060.114

## wangEditor 版本

V4

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

- 步骤一  输入几个空格在输入一个字
- 步骤二  将那个字设置为链接
- 步骤三  选中空格和字设置字体颜色不生效

**Comment by wangfupeng1988** [comment]
> 中文 demo https://www.wangeditor.com/demo/

这个 demo 能复现？

**Comment by USER-LGF** [comment]
V4版本的demo能重现 https://codepen.io/xiaokyo-the-bold/pen/ZEpWByR

**Comment by wangfupeng1988** [comment]
哦，我以为你搞错版本了呢。

是这样。V4 的问题目前已经没有精力追踪了，V5 早就发布了，我们也是业余维护，精力实在有限，只能先选择一个版本。
还请体谅。
