### ISSUE TITLE
保留自定义id or class

### ISSUE THREAD

**Issue by liujian891010** [wangeditor-team/wangEditor#4553]
## 功能描述

一段编辑器生成的html    `<p>这是一段文字</p>`

我替换成 `<p>这是一段<span id="myId">文字</span></p> `

使用编辑器渲染  

希望保留 `id="myId"  `

## 提炼几个功能点

- html 自定义的节点  拥有自己的id or class
- 使用编辑器渲染时  希望能保留这些手动添加的id or class 

## 原型图

无

## 可参考的案例

无

**Comment by wangfupeng1988** [comment]
暂不支持。

**Comment by rainbow520lxr** [comment]
v5 支持么

**Comment by wangfupeng1988** [comment]
@rainbow520lxr v5 暂不支持。

**Comment by wangfupeng1988** [comment]
@rainbow520lxr 

> 有什么办法可以对存在表格的内容导出html，并对表格部分输入的类容进行校验么

没看懂什么意思，你重新提交一个 issue 吧。把问题描述清楚，最好能举个例子。
