### ISSUE TITLE
输入汉字和数字的问题

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4554]
## bug 描述

开头输入一些汉字，再输入数字，数字就自动换行的原因，再从汉字后边输入汉字还可以，手动想把汉字和数字整理到一行也不可以

## 你预期的样子是？

数字不要自动换行

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本：chrome 103.0.5060.114

## wangEditor 版本

V5最新版本

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 编辑器开头输入半行中文，再输入数字
- 见附件：
![编辑器](https://user-images.githubusercontent.com/39672406/179652369-ddb889ac-4142-441f-aa71-7b4b25f3f1ae.png)

- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这符合预期，连续数字会被当成一个整体。

如果你想要这种效果，可以对编辑器这个 DOM 元素自定义 css 样式，让它不自动换行。
