### ISSUE TITLE
如何修改工具栏下拉的文字

### ISSUE THREAD

**Issue by comxza** [wangeditor-team/wangEditor#4555]
## 问题描述
![image](https://user-images.githubusercontent.com/21981010/179659236-f986fbf2-db16-40ba-afd7-0996768c68f9.png)
x修改这种鼠标放上去后出现的下拉框文字

*请输入遇到的问题...*
![image](https://user-images.githubusercontent.com/21981010/179659322-bcacbe90-3f9b-426b-91c4-2f29e659f206.png)
我按照文档这个修改 但是不能修改二级的  只能修改一级的

## wangEditor 版本
"@wangeditor/editor": "^5.1.1",
    "@wangeditor/editor-for-vue": "^5.1.12",

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否* 已看

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
暂时没有这个配置

有一个“曲线救国”的方式，在 import 之后，创建编辑器之前，执行如下代码：

```js
i18nGetResources('zh-CN').image.netImage = '网络图片1'
i18nGetResources('zh-CN').uploadImgModule.uploadImage = '上传图片1'
```

https://www.wangeditor.com/v5/i18n.html#%E8%8E%B7%E5%8F%96%E8%AF%AD%E8%A8%80
