### ISSUE TITLE
使用编辑图片功能添加图片链接，但是保存的时候图片链接还是为空

### ISSUE THREAD

**Issue by meicy** [wangeditor-team/wangEditor#4556]
## 问题描述

使用图片的编辑

<img width="358" alt="77777" src="https://user-images.githubusercontent.com/8372901/179689425-b3279255-c447-4074-aec6-9e05a3337faa.png">

弹框里面编辑了图片链接 但是保存的时候依然为空
## wangEditor 版本
"@wangeditor/editor": "^5.1.1",
"@wangeditor/editor-for-react": "^1.0.4",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

已阅读文档

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
1、图片的hoverKeys里面配置有editImage 。
2、文本编辑框里面输入一个图片，光标点到图片上，出现图片编辑
3、编辑框内输入图片的 href 确定保存 （<p><img src=\"https://p0.ssl.qhimgs0.com/t010638fcf9feff2ce2.jpeg\" alt=\"\" data-href=\"\" style=\"\"/></p>
）
4、发现保存的数据跟未添加之前一样（<p><img src=\"https://p0.ssl.qhimgs0.com/t010638fcf9feff2ce2.jpeg\" alt=\"\" data-href=\"\" style=\"\"/></p>
）

**Comment by wangfupeng1988** [comment]
官网 demo 未复现。设置了图片的链接，获取 HTML 是有的。如下图

<img width="1711" alt="image" src="https://user-images.githubusercontent.com/9583120/179701228-3d92e913-651a-45ac-b42e-98cbfe09b331.png">

**Comment by wangfupeng1988** [comment]
我如何复现这个问题？

**Comment by meicy** [comment]
没有问题了，谢谢，是因为editImage API使用错误导致的,在checkImage里面没有返回，另外有一个问题咨询，编辑图片链接之后我看是在img 里面插入了 data-href 标签，除了最后数据的匹配替换之外，我能有什么钩子可以自行插入 <a href=''><img/></a> 这样的结构吗？另外，我么有一个需要对图片进行剪裁后替换图片地址的弹框，这个推荐怎么做呢？

**Comment by wangfupeng1988** [comment]
>` <a href=''><img/></a>`

你要考虑清楚，转换为这种形式，下次再编辑器，那会多出一个链接。数据结构都变了。
当然，如果你只是转换来显示，不再编辑，那没问题。

**Comment by wangfupeng1988** [comment]
图片裁剪用什么工具都无所谓，反正最后就是替换图片地址，就一个 API [setNodes](https://www.wangeditor.com/v5/API.html#setnodes)

**Comment by meicy** [comment]
可能是我没有描述清楚
难点1、目前是想实现，图片通过setNodes 插入文本之后，点击图片直接，想使用自带的 hoverKeys里面的配置的editImage 插入链接，date-href  ，想咨询editImag 有没有哪个方法是可以让我，直接可以编辑完点击确定的时候直接可以像 文本里面插入
`<a href={data-href}><img src={} data-href={}/></a>` 这样的

**Comment by wangfupeng1988** [comment]
`parseImageSrc` 可以让你替换链接

**Comment by wangfupeng1988** [comment]
> 自定义点击图片就高亮，

现在编辑器里面就是这个效果，只不过颜色不一样而已，你可以定义 css 的颜色

**Comment by meicy** [comment]
> > 自定义点击图片就高亮，
> 
> 现在编辑器里面就是这个效果，只不过颜色不一样而已，你可以定义 css 的颜色



> 

`parseImageSrc` 函数里面只返回了 图片的地址，没有返回配置的 `link` 地址，这里没发通过这个函数自定义插入,建议是不是可以加一个参数返回。这样可以拿到href之后自定义返回出去的node

**Comment by meicy** [comment]
> `parseImageSrc` 可以让你替换链接

parseImageSrc 函数里面只返回了 图片的地址，没有返回配置的 link 地址，这里没发通过这个函数自定义插入,建议是不是可以加一个参数返回。这样可以拿到href之后自定义返回出去的node
