### ISSUE TITLE
vue3+ts项目使用wangEditorv5，上传图片使用七牛，如何捕获七牛返回的错误

### ISSUE THREAD

**Issue by douxuefeng666** [wangeditor-team/wangEditor#4557]
## 问题描述

*vue3+ts项目使用wangEditorv5，上传图片使用七牛，如何捕获七牛返回的错误.*

## wangEditor 版本

*v5*

**Comment by wangfupeng1988** [comment]
使用自定义上传 https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0

自定义上传，就需要自己捕获错误，自己弹出错误提示。
