### ISSUE TITLE
在vue3中重写超链接弹窗

### ISSUE THREAD

**Issue by jingjingzhao** [wangeditor-team/wangEditor#4558]
## 问题描述

在vue3项目中使用wangEditor5。想替换到 超链接的默认弹窗，改为自己的vue3 组件（.vue 实现的）。应该如何实现？请指教

是必须要写plugin吗？如果是，plugin中可以直接使用 .vue 组件吗？还是必须翻译为虚拟dom的写法。因为弹窗里有一些逻辑，不只是简单的input，所以改写成虚拟dom会比较麻烦。

## wangEditor 版本

"@wangeditor/editor": "^5.1.10",
"@wangeditor/editor-for-vue": "^5.1.12",
"vue": "^3.2.29",

## 是否查阅了文档 ？

是

**Comment by wangfupeng1988** [comment]
不支持你说的功能。

**Comment by jingjingzhao** [comment]
那如果自己写一个plugin的话，可以复用vue3现有的组件吗？ @wangfupeng1988

**Comment by wangfupeng1988** [comment]
有一种方式可以。

- 你自定义一个菜单，例如这个 demo 源码 https://www.wangeditor.com/demo/extend-menu.html 
- 然后在这菜单的 `exec` 方法中，通过自定义事件来触发某个 Vue 组件显示
- 在这个 Vue 组件的某个按钮点击时，再通过 editor API 把内容插入到编辑器中。插入之前记得先[恢复选区](https://www.wangeditor.com/v5/API.html#restoreselection)

这个方式应该可行
