### ISSUE TITLE
自定义插入图片

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4559]
## 问题描述

自定义插入图片时，怎么获取文件名称？从编辑器的接口里能获取到吗？

## wangEditor 版本

V5最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*，自定义插入图片的接口里 只有 后端返回来的值

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
```js
editorConfig.MENU_CONF['uploadImage'] = {
    // 自定义插入图片
    customInsert(res: any, insertFn: InsertFnType) {
        // res 即服务端的返回结果

        // 从 res 中找到 url alt href ，然后插图图片
        insertFn(url, alt, href)
    },
}
```

从 `res` 参数中获取，`res` 是你服务端返回的数据

**Comment by zxueliang** [comment]
@wangfupeng1988 
customInsert这个方法，可以再加一个file参数吗？在这个file.name获取图片名称可以吗？

**Comment by wangfupeng1988** [comment]
@zxueliang  获取了 file.name 干啥用？执行 insertFn 用吗？

**Comment by zxueliang** [comment]
@wangfupeng1988 
对，执行执行 insertFn 用，后端没有返回图片的名称，所以我想要前端给加这个参数

**Comment by wangfupeng1988** [comment]
弄一个全局变量，在 onBeforeUpload 时记录 fileName ，然后在 customInsert 时读取 fileName

**Comment by zxueliang** [comment]
@wangfupeng1988 
onBeforeUpload 这个函数 里的 file 参数，在获取name 的时候需要key才能知道name ，请问每次上传的key 都是固定的的，如果不固定的话，也获取不到name呀
