### ISSUE TITLE
为什么编辑器样式要给p标签添加margin，这样会导致页面行高和编辑器行高展示不一致

### ISSUE THREAD

**Issue by Jim-Rae** [wangeditor-team/wangEditor#4560]
## 问题描述

为什么编辑器样式要给p标签添加margin，这样会导致页面行高和编辑器行高展示不一致

### 编辑器展示效果

![image](https://user-images.githubusercontent.com/25401068/179725319-fc2e2080-c6c8-4286-a21a-724a842d4f93.png)
![image](https://user-images.githubusercontent.com/25401068/179725395-2d9f5501-19e4-4962-afbd-10e0f32613c8.png)

### 页面渲染效果

![image](https://user-images.githubusercontent.com/25401068/179725562-be96c8b3-cb1f-41f7-be3a-4e14ebfff1fa.png)

**Comment by wangfupeng1988** [comment]
不要 margin 的话，自己写 css 去掉即可
