### ISSUE TITLE
开发环境正常，发布到生产环境后所有插入操作都报错，粘贴也报错，enter也报错没反应

### ISSUE THREAD

**Issue by wssgchungang** [wangeditor-team/wangEditor#4561]
## 问题描述

开发环境正常，发布到生产环境后所有插入操作都报错，粘贴也报错，enter也报错没反应，报错如下图，无法定位
![image](https://user-images.githubusercontent.com/29122164/179755628-c80be374-2df8-48b3-bb9d-bf7c93e2b865.png)
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/29122164/179755628-c80be374-2df8-48b3-bb9d-bf7c93e2b865.png)

**Comment by wangfupeng1988** [comment]
本地打包出来，打包结果在本地运行，也会报错吗？

**Comment by wssgchungang** [comment]
> 本地打包出来，打包结果在本地运行，也会报错吗？

是的
![image](https://user-images.githubusercontent.com/29122164/179880126-841495f3-456e-4f4b-aea0-dca425c072d0.png)

**Comment by wangfupeng1988** [comment]
你是什么框架？

用官网 demo 也这样吗？

**Comment by wssgchungang** [comment]
> 你是什么框架？
> 
> 用官网 demo 也这样吗？

react.  我现在就单单打包 这一个官网demo 也这样
![image](https://user-images.githubusercontent.com/29122164/179885567-a6676087-f431-43ac-9de1-1c0beb45f642.png)

**Comment by hahaaha** [comment]
@wssgchungang 可以提供下代码demo么 我这边测试下来没什么问题

**Comment by wangfupeng1988** [comment]
> @wssgchungang 好的。。。那个这个应该就是配置问题了。。。和组件本身没什么关系。。。具体配置的话需要你自己根据项目调试了

@hahaaha 赶紧高优修复

**Comment by wangfupeng1988** [comment]
@wssgchungang 这我们就无能为力了
