### ISSUE TITLE
使用中遇到的三个问题，帮忙看一看

### ISSUE THREAD

**Issue by Reeyc** [wangeditor-team/wangEditor#4562]
## bug 描述

1.readOnly不能禁用富文本，需要自己手动调用disable()和enable()来实现。
2.清空值富文本没有清空内容，需要自己手动调用clear()来实现。
3.动态设置弹窗内富文本的值，会被覆盖成："\<p>\<br>\</p>\"。

## 你预期的样子是？

*如描述*

## 系统和浏览器及版本号

- 操作系统 Windows
- 浏览器和版本 Chrome

## wangEditor 版本 5.1.11 

*@wangeditor/editor 5.1.11 @wangeditor/editor-for-vue 5.1.12*

## demo 能否复现该 bug ？

能

- 中文 demo https://codesandbox.io/s/young-shape-dzr6eo?file=/src/App.vue

## 在线 demo

*https://codesandbox.io/s/young-shape-dzr6eo?file=/src/App.vue*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 点击开始编辑按钮，复现描述1
- 步骤二
- 点击清空值按钮，复现描述2
- 步骤三
- 点击打开弹窗按钮，复现描述3

**Comment by wangfupeng1988** [comment]
> 1.readOnly不能禁用富文本，需要自己手动调用disable()和enable()来实现。

readOnly 不要动态设置（computed） ，你直接设置一个 true 或者 false 试试

> 清空值富文本没有清空内容，需要自己手动调用clear()来实现。

你的清空操作是什么？ （ demo 打不开，加载超级慢 ）

> 动态设置弹窗内富文本的值，会被覆盖成："<p><br></p>"。

如果你赋值为空字符串，就会被默认赋值为 `<p><br></p>` ，符合预期

**Comment by Reeyc** [comment]
@wangfupeng1988 
1.readOnly不能动弹设置的话，那么封装的富文本如何实现动态切换启用和禁用。
2.我的清空操作就是将Editor组件v-model的值设置为空串或者undefined，都无效果。
3.我没有赋值空字符串，在弹窗打开之前值还是存在的，但在弹出打开之后就变成了`<p><br></p>`。
我的Demo很简洁和详细，我打开Demo很快5秒钟内加载出来

**Comment by wangfupeng1988** [comment]
> 1.readOnly不能动弹设置的话，那么封装的富文本如何实现动态切换启用和禁用。

动态禁用使用 API `editor.disable`

> 2.我的清空操作就是将Editor组件v-model的值设置为空串或者undefined，都无效果。

这是为空行 `<p><br></p>` 试试

> 3.我没有赋值空字符串，在弹窗打开之前值还是存在的，但在弹出打开之后就变成了`<p><br></p>`。

`formState.field2` 要赋值为 HTML 格式，不能是纯文本 `'我是内容'`

如果你觉得使用纯文本方便，那还不如直接使用 `<textarea>` 倒更简单。

PS：demo 我这一直运行不起来，我根据你 demo 源码回复你的。

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/9583120/181136665-6dcf7621-8680-4b4a-b8e2-cd765e8c40b8.png">
