### ISSUE TITLE
点击图片 编辑 弹框的定位

### ISSUE THREAD

**Issue by meicy** [wangeditor-team/wangEditor#4566]
<img width="698" alt="WX20220721-124917@2x" src="https://user-images.githubusercontent.com/8372901/180132104-033ca3dd-9b50-4e8b-b0a2-c19e76090939.png">

**Comment by wangfupeng1988** [comment]
没懂你的意思。

**Comment by meicy** [comment]
就是偶尔 点击图片的编辑  编辑框会再图片的左边，这个时候会导致显示不全的问题

**Comment by wangfupeng1988** [comment]
如何复现这个问题？请写明步骤（按照 issue 模板）
