### ISSUE TITLE
编辑器插入图片

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4571]
## 功能描述
编辑器插入图片后，把图片设置成 50% 后，没有 恢复 图片初始大小的功能

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
撤销

**Comment by zxueliang** [comment]
@wangfupeng1988 
能不能不用这个 撤销 呢？能不能在 30% 的旁边加一个 还原 功能呢

**Comment by wangfupeng1988** [comment]
好建议，我抽空优化一下
