### ISSUE TITLE
自定义菜单功能

### ISSUE THREAD

**Issue by zhangYinfei** [wangeditor-team/wangEditor#4574]
## 问题描述
自定义菜单按照demo教程报错invalid menu{} 

## wangEditor 版本
V5

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
1.在main.js中注册
import {fileManageConf} from "./components/WangEditor/manageFile";

const module = {
  menus: [fileManageConf],
}
Boot.registerModule(attachmentModule,module);
2.定义config文件（js)
import { Boot,IModalMenu } from '@wangeditor/editor'
import fileManageModalMenu from './fileManage/index1'
// 定义菜单 class
class FileManageModal{
  // 菜单配置，代码可参考“插入链接”菜单源码
}
// 定义菜单配置
export const fileManageConf = {
  key: 'file-manage', // menu key ，唯一。注册之后，可配置到工具栏
  factory() {
    return new fileManageModalMenu()
  }
}
// 注册到 wangEditor
Boot.registerMenu(fileManageConf)
3.菜单实现（具体逻辑是linkinsert的实现，还没改，因为报错了）
/**
 * @description insert link menu
 * @author wangfupeng
 */

import { Editor, Range, Node } from 'slate'
import {
  IModalMenu,
  IDomEditor,
  genModalInputElems,
  genModalButtonElems,
  t
} from '@wangeditor/core'
import $, { Dom7Array, DOMElement } from '../../../utils/dom'
import { genRandomStr } from '../../../utils/util'
import { LINK_SVG } from '../../../constants/icon-svg'
import { isMenuDisabled, insertLink } from '../helper'

/**
 * 生成唯一的 DOM ID
 */
function genDomID() {
  return genRandomStr('w-e-file-manage')
}

class fileManageModalMenu implements IModalMenu {
  title = t('file-manage')
  iconSvg = LINK_SVG
  tag = 'button'
  showModal = true // 点击 button 时显示 modal
  modalWidth = 300
  $content = ''
  textInputId = genDomID()
  urlInputId = genDomID()
  buttonId = genDomID()

  getValue(editor) {
    // 插入菜单，不需要 value
    return ''
  }

  isActive(editor) {
    // 任何时候，都不用激活 menu
    return false
  }

  exec(editor, value) {
    // 点击菜单时，弹出 modal 之前，不需要执行其他代码
    // 此处空着即可
  }

  isDisabled(editor) {
    return isMenuDisabled(editor)
  }

  getModalPositionNode(editor) {
    return null // modal 依据选区定位
  }

  getModalContentElem(editor) {
    const { selection } = editor
    const { textInputId, urlInputId, buttonId } = this

    // 获取 input button elem
    const [textContainerElem, inputTextElem] = genModalInputElems(t('link.text'), textInputId)
    const $inputText = $(inputTextElem)
    const [urlContainerElem, inputUrlElem] = genModalInputElems(t('link.url'), urlInputId)
    const $inputUrl = $(inputUrlElem)
    const [buttonContainerElem] = genModalButtonElems(buttonId, t('common.ok'))

    if (this.$content == null) {
      // 第一次渲染
      const $content = $('<div></div>')

      // 绑定事件（第一次渲染时绑定，不要重复绑定）
      $content.on('click', `#${buttonId}`, e => {
        e.preventDefault()
        const text = $content.find(`#${textInputId}`).val()
        const url = $content.find(`#${urlInputId}`).val()
        insertLink(editor, text, url) // 插入链接
        editor.hidePanelOrModal() // 隐藏 modal
      })

      // 记录属性，重要
      this.$content = $content
    }

    const $content = this.$content
    $content.empty() // 先清空内容

    // append inputs and button
    $content.append(textContainerElem)
    $content.append(urlContainerElem)
    $content.append(buttonContainerElem)

    // 设置 input val
    if (selection == null || Range.isCollapsed(selection)) {
      // 选区无内容
      $inputText.val('')
    } else {
      // 选区有内容
      const selectionText = Editor.string(editor, selection)
      $inputText.val(selectionText)
    }
    $inputUrl.val('')

    // focus 一个 input（异步，此时 DOM 尚未渲染）
    setTimeout(() => {
      $inputText.focus()
    })

    return $content[0]
  }
}

export default fileManageModalMenu

**Comment by wangfupeng1988** [comment]
参考这个 demo 源码 https://www.wangeditor.com/demo/extend-menu.html
