### ISSUE TITLE
支持素材库添加到编辑器

### ISSUE THREAD

**Issue by zhangYinfei** [wangeditor-team/wangEditor#4575]
## 功能描述
toolbar支持点击弹出素材库进行插入内容
如视频/图片等素材

## 原型图
![image](https://user-images.githubusercontent.com/49514383/180192123-9f6bbd67-19ec-480a-94b1-4707c1985260.png)

## 可参考的案例
https://xdsoft.net/jodit/pro/#demo

**Comment by wangfupeng1988** [comment]
使用这个来自定义 https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD
