### ISSUE TITLE
图片插入失败的问题

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4577]
## 问题描述

图片上传失败后，怎么在失败函数里清空当前图片，如果不清空的话，再重新上传该图片报错，提示当前图片已经存在的问题

## wangEditor 版本

V5 最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
我看代码中，无论成功还是失败，都清空了图片文件。

> 提示当前图片已经存在的问题

具体的报错截图给我吧，我看看

**Comment by zxueliang** [comment]
@wangfupeng1988 
图片上传失败，再上传当前图片后，报错，见图片
![图片报错](https://user-images.githubusercontent.com/39672406/180345090-6c3a6997-602f-412b-a9cd-be695fdc0570.png)

**Comment by wangfupeng1988** [comment]
你下载、启动这个 demo 试试 https://github.com/wangeditor-team/server

把这个代码文件，如下图改一下，就可以模拟失败的情况

<img width="529" alt="image" src="https://user-images.githubusercontent.com/9583120/180347902-8b475f9d-13d1-40e9-adb5-42286a8ac60f.png">

**Comment by zxueliang** [comment]
@wangfupeng1988 
我是上传成功了，但是在 自定义 插入的时候失败了（比如 变量名写错了，报错了），然后再重新插入当前图片，就报上边截图的问题

**Comment by wangfupeng1988** [comment]
好，我下周去试试

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版试试
