### ISSUE TITLE
能否在编辑内容区添加鼠标移动事件，光标包含的内容区域鼠标移动添加图标

### ISSUE THREAD

**Issue by wumei-jpg** [wangeditor-team/wangEditor#4578]
![image](https://user-images.githubusercontent.com/109733891/180358344-c901852b-1610-446c-8bb7-39bdfb766c52.png)
类似于这样，我可以在光标以上的内容区添加鼠标移动事件，移动时在相对应的行添加一个节点，另外添加节点时会报错不知道是什么原因
// const node = {
        //   type: 'image',
        //   src: 'https://static-test.zcool.cn/git_z/z/images/svg/add-work-icon.svg',
        //   style: { width: '20px', height: '20px' },
        //   children: [{ text: '' }],
        // }
        // editor.insertNode(node)
会报text不能为空

**Comment by wangfupeng1988** [comment]
默认不支持。

你这个需求建议看看 https://editorjs.io/
