### ISSUE TITLE
setHtml或者v-model时，<table/>前后有文字时，后面文字丢失

### ISSUE THREAD

**Issue by zhangyuan0532** [wangeditor-team/wangEditor#4579]
## bug 描述

setHtml或者v-model时，<table/>前后有文字时，后面文字丢失。
例如，输入：
aaaaaaaaaa&lt;table style=&quot;width: auto;&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;th colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/th&gt;&lt;th colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/th&gt;&lt;th colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;
bbbbbbbbbbbbb

最后输出时“bbbbbbbbb”丢失。

## 你预期的样子是？

期望数据正常

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本：chrome

## wangEditor 版本

"@wangeditor/editor": "^5.1.1",
    "@wangeditor/editor-for-vue": "^5.1.12"

## demo 能否复现该 bug ？

能
官网在线demo也有类似问题，“bbbbbbbb”未丢失，但是在表格右下角td内。

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：打开https://www.wangeditor.com/demo/set-html.html
- 步骤二：粘贴入如下内容：
aaaaaaaaaa&lt;table style=&quot;width: auto;&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;th colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/th&gt;&lt;th colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/th&gt;&lt;th colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;td colSpan=&quot;1&quot; rowSpan=&quot;1&quot; width=&quot;auto&quot;&gt;test&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;
bbbbbbbbbbbbb
- 步骤三：bug出现。

**Comment by wangfupeng1988** [comment]
不支持这种格式

你需要把 table 前后的文字，用 `<p>` 包裹
