### ISSUE TITLE
Transforms.removeNodes 以及 Transforms.insertNodes 异步执行 editor获取不到当前选中

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#4580]
作者大大  我自定义了组件 在点击按钮后 使用element弹框后  编辑框失去了焦点 
回调方法 执行Transforms
这个时候Transforms子方法失效了

这个是编辑器失去焦点导致的吗  有什么好办法可以解决这个问题?

**Comment by wangfupeng1988** [comment]
操作之前先恢复选区 https://www.wangeditor.com/v5/API.html#restoreselection

**Comment by beforeBurning** [comment]
解决了 感谢大大指点
