### ISSUE TITLE
wangEditor v5上传本地视频问题

### ISSUE THREAD

**Issue by hongwerff** [wangeditor-team/wangEditor#4581]
## 问题描述

*上传本地视频的时候，视频不可以调整位置，居中等按钮是不可以点的，上面操作栏里，只有撤销和重做可以点击，其他都是灰的，不能点击.*

## wangEditor v5

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
视频默认就是这样的，独占一行

**Comment by hongwerff** [comment]
但是视频显示是居左显示的，我们需要居中显示

**Comment by hongwerff** [comment]
> 但是视频显示是居左显示的，我们需要居中显示

**Comment by hongwerff** [comment]
您好，您可能理解错了我们的问题，我们是希望视频在前台显示是居中的，后台上传的时候，看着是居中，但是前台显示却是居左的，而且回到后台调整，还无法调整，因为上面按钮都是灰的。 Best regards ----------------- 张颖 ／品牌主管 Ying Zhang／Brand Supervisor T: +86 13810067002 ***@***.*** __

**Comment by wangfupeng1988** [comment]
> 但是前台显示却是居左的

显示 HTML 时，自己通过 css 居中即可

```css
div[data-w-e-type="video"] {
    text-align: center;
}
```

**Comment by hongwerff** [comment]
谢谢您的解答，但是我们网站是外包开发的，然后植入您这款编辑器，我们自己不太懂这个。另外我们新闻页面属于弹出显示，查看代码的时候，显示的是主页面所有代码。 现在我们测试就是在后台不修改视频尺寸，就是居中，因为是满屏显示了，只要一改视频尺寸（改小），就是居左，不是居中了。 这个应该算是bug了吧？ Best regards ----------------- 张颖 ／品牌主管 Ying Zhang／B

**Comment by wangfupeng1988** [comment]
如我上次的回复，找个技术人员一改就行了，不麻烦。

**Comment by gochantao2** [comment]
您好，每篇文章可能视频有的居中，有的居左，通过html显示的时候改不就写死了么，希望控制视频位置在编辑器里可以修改

**Comment by gochantao2** [comment]
> 如我上次的回复，找个技术人员一改就行了，不麻烦。

您好，每篇文章可能视频有的居中，有的居左，通过html显示的时候改不就写死了么，希望控制视频位置在编辑器里可以修改
