### ISSUE TITLE
在使用insertNode()插入一个图片节点时，会报错text不能为空

### ISSUE THREAD

**Issue by wumei-jpg** [wangeditor-team/wangEditor#4582]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/109733891/180421825-d88d574c-d167-41fd-abc6-114e36fdcc8b.png">
我只想插入一个图片节点，不想要文本内容，但是text为空时会报错，同时图片可以正常显示，这个应该怎么解决呢

![image](https://user-images.githubusercontent.com/109733891/180422003-1ab91380-2d75-40dd-b948-d5a4f579ca83.png)

**Comment by wangfupeng1988** [comment]
我没有复现。

访问 demo https://www.wangeditor.com/demo/ ，打开浏览器控制台，执行

```js
const img = {"type":"image","src":"https://news-bos.cdn.bcebos.com/mvideo/log-news.png","href":"","alt":"","style":{},"children":[{"text":""}]}
editor.insertNode(img)
```

**Comment by wumei-jpg** [comment]
请问这个渲染的img节点上是否能绑定事件呢

**Comment by wangfupeng1988** [comment]
@wumei-jpg  你如果直接 insertNode ，无法绑定事件。自己通过 dom 绑定吧
