### ISSUE TITLE
请问有获取当前版本号的api吗

### ISSUE THREAD

**Issue by pedoc** [wangeditor-team/wangEditor#4583]
## 问题描述

RT

## wangEditor 版本

5.1.12

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是,未在文档中找到相关资料*

## 最小成本的复现步骤

无

**Comment by wangfupeng1988** [comment]
不懂你的意思？

现在有啥问题吗

**Comment by pedoc** [comment]
就是获取当前库的版本号,比如发布在npm上是``5.1.2``,这个值是否可以通过编辑器(Editor)上的方法或者作为全局方法暴露出来?
比如
```
import * as wangEditor from '@wangeditor/editor-for-vue'

console.log(wangEditor.getVersion()) //output 5.1.2

**Comment by wangfupeng1988** [comment]
暂不支持。
