### ISSUE TITLE
新版本 单元格合并功能还没实现吗

### ISSUE THREAD

**Issue by utopiazeng** [wangeditor-team/wangEditor#4584]
## 功能描述

新版本 单元格合并功能还没实现吗

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
近期没精力做，这个功能太麻烦了，成本太高。

我们业余维护，时间有限，还请体谅~

**Comment by zxueliang** [comment]
那如果在word 里复制过来的表格有合并单元格的，能支持吗

**Comment by wangfupeng1988** [comment]
支持，但不能再拆分

**Comment by frontend-qin** [comment]
> @wangfupeng1988 那如果在word 里复制过来的表格有合并单元格的，能支持吗
支持的
