### ISSUE TITLE
v4版本上传图片的接口报错时怎么关掉自带的alert提示

### ISSUE THREAD

**Issue by wengshuang** [wangeditor-team/wangEditor#4588]
## 问题描述

v4版本上传图片的接口报错时怎么关掉自带的alert提示

## wangEditor 版本

v4

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

看了文档

**Comment by wangfupeng1988** [comment]
v5 早已发布了，v4 已不维护。

业余开发，精力优先，还请体谅
