### ISSUE TITLE
编辑器内是否支持每换行一次会对应一个特定的事件呢，类似于e.target

### ISSUE THREAD

**Issue by wumei-jpg** [wangeditor-team/wangEditor#4589]
![image](https://user-images.githubusercontent.com/109733891/180693099-0bc7a0e9-7474-4061-b95f-018bf138adec.png)
其实就是有这样一个需求，每一行的首行，只要鼠标hover到内容区，就会插入一个insertNode(img),但开始输入内容时，要去掉这个图标，不知到使用这个编辑器是否能实现这个功能呢，和飞书文档功能基本一样

**Comment by wangfupeng1988** [comment]
编辑器默认不支持。

这需要你充分了解编辑器 API 和插件机制，来自己二次开发。

**Comment by wangfupeng1988** [comment]
或者你可以考虑 https://editorjs.io/

**Comment by wumei-jpg** [comment]
换行没有对应的事件，那编辑器内容区是否支持添加自定义事件呢？比如鼠标在一行移入或移出事件？

**Comment by wumei-jpg** [comment]
自定义事件也不能支持吗？比如鼠标在内容节点移入移出

**Comment by wangfupeng1988** [comment]
换行、鼠标移入移出（就是选区变化），这些都支持，但需要你详细了解编辑器 API 和插件机制。

太多了，我无法一个一个跟你说。

**Comment by wumei-jpg** [comment]
幸苦大佬举个栗子（比如给每行内容区添加鼠标移入事件），或者文档中具体哪块有对应的描述～

**Comment by wangfupeng1988** [comment]
哦。。。我理解错误了，是鼠标移入，不是光标。

如果是光标，那就是选区变化。
如果是鼠标，那就是普通的 mouseover mouseenter mouseleave 等 DOM 事件。

**Comment by wumei-jpg** [comment]
那编辑内容区是否可以添加这种鼠标移入移出事件呢？不知道具体怎么添加

**Comment by wangfupeng1988** [comment]
编辑内容区域就是 DOM ，可以添加任何 DOM 事件。通过 addEventListener 添加即可

**Comment by wumei-jpg** [comment]
> 或者你可以考虑https://editorjs.io/

麻烦再问一下，我是否可以在wangeditor的基础上结合editorjs.io进行二次开发呢，主要将它下面图中展示的这个功能开发至wangeditor
![image](https://user-images.githubusercontent.com/109733891/180949901-ddac6230-0785-4d93-bd87-af913b6cf0e7.png)

**Comment by wangfupeng1988** [comment]
> 麻烦再问一下，我是否可以在wangeditor的基础上结合editorjs.io进行二次开发呢，主要将它下面图中展示的这个功能开发至wangeditor

不可以，这俩是两个编辑器。

你直接用 editor.js 就可以呀，它本来就支持这些特性

**Comment by wumei-jpg** [comment]
> > 麻烦再问一下，我是否可以在wangeditor的基础上结合editorjs.io进行二次开发呢，主要将它下面图中展示的这个功能开发至wangeditor
> 
> 不可以，这俩是两个编辑器。
> 
> 你直接用 editor.js 就可以呀，它本来就支持这些特性

好的呢，谢谢

**Comment by wumei-jpg** [comment]
> > 麻烦再问一下，我是否可以在wangeditor的基础上结合editorjs.io进行二次开发呢，主要将它下面图中展示的这个功能开发至wangeditor
> 
> 不可以，这俩是两个编辑器。
> 
> 你直接用 editor.js 就可以呀，它本来就支持这些特性

使用了editor.js但是和我们的业务功能不太符合，对比来看还是wangeditor更好点，除了工具栏通过➕图标展示不支持，请问作者可以内置支持➕图标的实现吗？或者我们在使用wangeditor的基础上可以通过什么插件能去实现它
无内容时：
![image](https://user-images.githubusercontent.com/109733891/182340953-4964555b-7307-4958-870b-ad620e06d189.png)
有内容时：
![image](https://user-images.githubusercontent.com/109733891/182341025-09ecaf12-50a9-4be0-97eb-8945c66d3d1d.png)

**Comment by wangfupeng1988** [comment]
第一，编辑器目前不会默认支持这个；第二，编辑器也没有支持这个的插件。

其实你自己开发也并不麻烦，就是在鼠标 hover 每个段落的时候，在段落左侧显示➕，然后在 hover ➕ 时绘制一个工具栏，点击执行 editor 相应的 API，就这样。

**Comment by wumei-jpg** [comment]
> 第一，编辑器目前不会默认支持这个；第二，编辑器也没有支持这个的插件。
> 
> 其实你自己开发也并不麻烦，就是在鼠标 hover 每个段落的时候，在段落左侧显示➕，然后在 hover ➕ 时绘制一个工具栏，点击执行 editor 相应的 API，就这样。

可是我有什么方法可以获取到一整个段落呢，空内容时每一行都是一个段落，我看文档中的方法都是针对一整个editor而言的，麻烦能不能提供下思路呢

**Comment by wumei-jpg** [comment]
> 

我之前自己实现过，想在鼠标hover到每一行时在左侧用insertNode()插入一个节点，但是有两个问题：
1. 鼠标移入移出只能针对整个编辑器editor添加事件，无法监听到具体的段落上
2. insertNode()上没办法注册点击事件，因为我要在点击图标的时候弹出工具栏
3. 需要将insertNode()插入的图标节点，定位到编辑器外
麻烦作者能否帮我看下这几个问题能不能解决，谢谢了

**Comment by wumei-jpg** [comment]
> > 
> 
> 我之前自己实现过，想在鼠标hover到每一行时在左侧用insertNode()插入一个节点，但是有两个问题：
> 
> 1. 鼠标移入移出只能针对整个编辑器editor添加事件，无法监听到具体的段落上
> 2. insertNode()上没办法注册点击事件，因为我要在点击图标的时候弹出工具栏
> 3. 需要将insertNode()插入的图标节点，定位到编辑器外
>    麻烦作者能否帮我看下这几个问题能不能解决，谢谢了

如果能提供下demo或者相关的解决办法就太感谢了

**Comment by wangfupeng1988** [comment]
> 我之前自己实现过，想在鼠标hover到每一行时在左侧用insertNode()插入一个节点，

感觉你设计的方向就错了。
这个➕图标（以及点击之后弹出的菜单栏）就不应该是编辑器的内容，不应该用 insertNode 插入。
它应该是编辑器以外的内容，然后通过 css 定位到这一行的左侧。

它应该是编辑器以外的内容，你自己随便 DOM 操作即可，不会收到编辑器的任何限制。

**Comment by wumei-jpg** [comment]
> > 我之前自己实现过，想在鼠标hover到每一行时在左侧用insertNode()插入一个节点，
> 
> 感觉你设计的方向就错了。 这个➕图标（以及点击之后弹出的菜单栏）就不应该是编辑器的内容，不应该用 insertNode 插入。 它应该是编辑器以外的内容，然后通过 css 定位到这一行的左侧。
> 
> 它应该是编辑器以外的内容，你自己随便 DOM 操作即可，不会收到编辑器的任何限制。

我是可以定位到编辑器外面，但是怎么让它和编辑器内容联系呢，比如鼠标移动到每个空行时，图标会跟着鼠标走，有内容时鼠标移动到段落，会选中整个段落（整个段落会有个背景色），图标会定位在整个段落的左上方

**Comment by wangfupeng1988** [comment]
> 我是可以定位到编辑器外面，但是怎么让它和编辑器内容联系呢，比如鼠标移动到每个空行时，图标会跟着鼠标走，有内容时鼠标移动到段落，会选中整个段落（整个段落会有个背景色），图标会定位在整个段落的左上方

你说的这些都是基本的 DOM 操作、DOM 事件和 CSS 定位。因为编辑器也都是由一个一个 DOM 节点组成的。

> 有内容时鼠标移动到段落，会选中整个段落（整个段落会有个背景色）

这个不用选中，只给 DOM 临时加一个背景色即可

**Comment by wangfupeng1988** [comment]
说白了吧，你现在不用考虑编辑器，就给你这么一段 HTML ，你如何实现：鼠标 hover 显示➕ ，以及点击➕弹出菜单栏？

```html
<div>
    <h1>标题</h1>
    <p>一段文字</p>
    <p>一段文字</p>
    <p><br></p>
</div>
```
