### ISSUE TITLE
无法预料的空格

### ISSUE THREAD

**Issue by fuxichen** [wangeditor-team/wangEditor#4590]
## 问题描述

新的版本输入`hello world`，通过获取html得到的是`<p>hello world</p><p><br></p>`,输入`hello  world`<--中间两个空格得到的是`<p>hello &nbsp;world</p><p><br></p>`
原来用5.1.1的版本没有这个问题
## wangEditor 版本

5.1.12

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤
在dome
https://www.wangeditor.com/demo/get-html.html
中输入不同数量的连续空格

**Comment by wangfupeng1988** [comment]
这有啥问题吗？ 
两个空格，你预期改输出什么？

**Comment by fuxichen** [comment]
> 这有啥问题吗？ 两个空格，你预期改输出什么？

我预期的结果是输入`hello  world`得到`<p>hello&nbsp;&nbsp;world</p><p><br></p>`
我模仿[官方源码](https://github.com/wangeditor-team/wangEditor/blob/8affb426423f28e04ba60653c5f80768d42c1c58/packages/basic-modules/src/modules/link/helper.ts#L114)自定义了一个按钮插入特殊占位符 `_\u{200d}_` 
![image](https://user-images.githubusercontent.com/17411462/180754437-0cc252ea-859f-485b-8708-4966e8bdeeb7.png)
原来的版本官方源码的114、112行插入的空格是`&nbsp;`，我是根据`&nbsp;<span style="color: white; background-color: rgb(64, 158, 255);"><code>_‍_</code></span>&nbsp;`去匹配占位符的。现在升级新版本后，插入的空格有些情况是` `有些情况下是`&nbsp;`，拿到的HTML是`<p>123 <span style="color: white; background-color: rgb(64, 158, 255);"><code>_‍_</code></span> 123 &nbsp;<span style="color: white; background-color: rgb(64, 158, 255);"><code>_‍_</code></span> 123</p>`，新的版本的结果我在处理数据的时候匹配不出占位符

**Comment by wangfupeng1988** [comment]
> 我预期的结果是输入hello world得到`<p>hello&nbsp;&nbsp;world</p><p><br></p>`

之前就是这样。

这样有一个问题，会导致英文不自动换行。所以，后来改成了现在这种形式。
