### ISSUE TITLE
异步给编辑器赋值的时候，第一行会换行

### ISSUE THREAD

**Issue by kingbetter6** [wangeditor-team/wangEditor#4591]
## bug 描述

*异步回显赋值的时候，第一行会莫名的换行。*

## 你预期的样子是？
*不要第一行换行*

## 系统和浏览器及版本号

- 操作系统 Windows
- 浏览器和版本 谷歌   103.0.5060.114（正式版本） （32 位）

## wangEditor 版本 

*v5 react版本*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 复制官网react demo 
- 步骤二 异步setHtml （标签内容）
- 步骤三 第一行会换行

**Comment by lqfxz520** [comment]
我也遇到同样的问题，当设置的内容包含html标签时会进行换行， 纯文本返回不会

**Comment by wangfupeng1988** [comment]
用这个 demo https://www.wangeditor.com/demo/set-html.html 试试能否复现？

以及，你异步设置的 HTML 内容是什么？

**Comment by lqfxz520** [comment]
> 用这个 demo https://www.wangeditor.com/demo/set-html.html 试试能否复现？
> 
> 以及，你异步设置的 HTML 内容是什么？

我复现不出来，但在自己的项目中100%复现
唯一知道的是，执行editor.setHtml('123')，设置的内容实际是`<p><br></p><p>123</p>`

**Comment by wangfupeng1988** [comment]
升级 `@wangeditor/editor` 最新版本试试

**Comment by lqfxz520** [comment]
> 升级 `@wangeditor/editor` 最新版本试试

更新最新版本就没问题了，非常棒!
