### ISSUE TITLE
react封装组件，如何实现传参

### ISSUE THREAD

**Issue by doYbest** [wangeditor-team/wangEditor#4592]
## 问题描述
在react项目中将编辑器封装之后如何在内容变化时实现页面的传参？我需要在组件使用界面获取编辑器内容

![image](https://user-images.githubusercontent.com/80409408/180713044-288187f5-a112-40b7-9fb6-13447eb6d9c4.png)

![image](https://user-images.githubusercontent.com/80409408/180713177-b39fbfb1-c08e-4fac-848b-2237a93f9caf.png)

## wangEditor 版本

*V5*

## 是否查阅了文档 ？

（文档链接 [[www.wangeditor.com](https://www.wangeditor.com/](https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8-2)) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by doYbest** [comment]
> @doYbest `实现页面的传参 `具体是指 用editor.getHtml()是可以获取编辑器里的内容的

我是将编辑器单独一个文件作为组件引入使用，在组件页面通过editor.getHtml()可以获取内容，但是在组件使用的页面我如何监控编辑器的变化，将组件中编辑器的内容传递到组件使用界面？

**Comment by hahaaha** [comment]
onChange是实时更新的。。。你可以通过一个从外部传递一个事件函数进来。。。通过这个事件把对应的内容传递出去
