### ISSUE TITLE
自定义html

### ISSUE THREAD

**Issue by qq2084470563** [wangeditor-team/wangEditor#4593]
## 问题描述

自定义一个html元素，在页面生成的html是存在这个元素，但是在控制台里看到是一个div标签，怎么解决，不知道是不是哪个渲染环节的问题

## wangEditor 版本

v5

## 是否查阅了文档 ？

是

*是/否*

## 最小成本的复现步骤

[（请告诉我们，如何**最快的**复现该问题？）](url)

- 步骤一 按照引用源码写的模块
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
没看懂你的问题。

**Comment by qq2084470563** [comment]
问题解决了，渲染函数拼错了，但是没有打印出日志，所以节点没有渲染出来，希望日志可以完善一下，
