### ISSUE TITLE
编辑器内容区是否支持添加自定义事件（比如hover事件），我想在移动到每一行内容区的时候获取到这一行对应的事件，在这一行起始位置添加图标，hover图标时显示工具栏浮窗，使用v5版本是否支持呢？

### ISSUE THREAD

**Issue by wumei-jpg** [wangeditor-team/wangEditor#4594]
目前要使用wangeditor实现类似于飞书文档这种功能，不知道是否支持或者作者有没有推荐的开源呢<img width="663" alt="image" src="https://user-images.githubusercontent.com/109733891/180730156-5a169116-361a-4472-a50b-6417b68b436f.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/109733891/180730236-877d2b1e-990f-43bc-bb4d-1b983d137ecc.png">
<img width="676" alt="image" src="https://user-images.githubusercontent.com/109733891/180730305-110f7bb8-e4eb-4cae-b204-49c31bcef921.png">

**Comment by wangfupeng1988** [comment]
看这里 https://github.com/wangeditor-team/wangEditor/issues/4589
