### ISSUE TITLE
向后端发送请求，不传key 值选择文件上传 ，后端收不到key值就拿不到图片信息，会报错，请问如何传key值？

### ISSUE THREAD

**Issue by h11131** [wangeditor-team/wangEditor#4595]
## 问题描述

向后端发送请求，不传key 值选择文件上传 ，后端收不到key值就拿不到图片信息，会报错，请问如何传key值？

## wangEditor 版本

wangEditor 5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/109972315/180801613-6c1f73a9-b6cb-4aef-ba4e-91487eebfb6b.png)

**Comment by h11131** [comment]
1

**Comment by wangfupeng1988** [comment]
参考这里 https://www.wangeditor.com/v5/menu-config.html#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE

可以根据情况，选择在 `meta` 或 `headers` 中传递 key
