### ISSUE TITLE
此贴为了展示在react中更方便的扩展menu，替代原有的modalMenu方案。

### ISSUE THREAD

**Issue by lemondreamtobe** [wangeditor-team/wangEditor#4598]
## 问题描述

原有的modalMenu方案，使用起来非常困难，并且需要自定义modal cotent
这无疑让我们回到了jq的时代，无法活用jsx，这在react应用中让人生痛欲绝。
以下代码，来自官方文档demo
![image](https://user-images.githubusercontent.com/22766436/180916234-fab47712-4d82-4b7c-b4b7-934b033bb280.png)

于是乎，我花了一个早上研究了一下替代方案
当我们想在编辑器的menu上，插入一个按钮，并且这个点击按钮，就会出现弹窗。
最理想的情况并且非耦合的条件下，编辑器配置与弹窗之间的业务应该是完全隔离的。
以下我的应用中实现了，点击自定义扩展的菜单按钮，没错 用的是最简单的button menu。
以下是我整个应用用到的依赖：react antd wangEditor5

## 实现步骤

- 步骤一 封装一个基础的modalMenu 类，控制弹窗的显隐，但不care具体是什么弹窗。
注意，这个menu类本质上还是button menu

```
import ReactDOM from "react-dom/client";

export default class BaseModalMenu {
    id: string = `modal-${Math.random().toString(36).slice(2)}`
    title: string
    tag: string
    $ele: HTMLDivElement;
    $root: any
    ifInit: boolean = false;
    controlShow: (i: boolean) => void = Function.prototype as any;
    
    constructor() {
        this.title = 'My Modal';
        // this.iconSvg = '<svg >...</svg>'; icon
        this.tag = 'button';
        this.$ele = document.createElement('div');
        this.$ele.id = this.id;
        document.body.appendChild(this.$ele);
        this.$root = ReactDOM.createRoot(this.$ele!);
    }

    modalInit = (method) => {

        // 这里把控制react的方法透出
        this.controlShow = method;
    }


    isActive(editor) {
        return false // or false
    }

    isDisabled(editor) {
        return false // or true
    }

    exec(editor, value) {

        if (this.ifInit) {
            this.controlShow(true);
            return;
        }
        // editor.insertText(value)
        this.$root.render(
            value,
        );
        this.ifInit = true;
    }
}
```

- 步骤二 子类 也就是我们的业务类 自己定义需要的什么样子的弹窗，这个类也正是需要注册到编辑器的类
```
import CsModal from '../csModal';
import BaseModalMenu from "./baseModalMenu";

// Extend menu
export default class ModalMenu extends BaseModalMenu {
    constructor() {
        super();
    }

    getValue(editor) {
        return <CsModal onInit={this.modalInit}  />
    }
}

export const myModalMenuConf = {
    key: 'myModalMenu',
    factory() {
        return new ModalMenu()
    }
}
```
业务中的CsModal 是我自己封装了antd的modal组件
```
import { Modal } from 'antd';
import { useEffect, useState } from 'react';

export default function CsModal(props) {
    const [isModalVisible, setIsModalVisible] = useState(true);
    const close = () => {
        setIsModalVisible(false);
    }
    
    useEffect(() => {
        props?.onInit(setIsModalVisible); 
    }, []);
    
    return <Modal title="Basic Modal" visible={isModalVisible} onOk={close} onCancel={close}>
        <p>Some contents...</p>
        <p>Some contents...</p>
        <p>Some contents...</p>
    </Modal>
}
```

- 步骤三 注册 这一步正常的按照文档

```
Boot.registerMenu(myModalMenuConf)
 const toolbarConfig: Partial<IToolbarConfig> = {
            insertKeys: {
                index: 0,
                keys: ['myModalMenu'], // show menu in toolbar
            }
        }
```
## 最终结果
实现了编辑器交互跟react 对接上了，初步实现了简单的button menu也可以做弹窗menu的扩展。
以下是效果图：
![image](https://user-images.githubusercontent.com/22766436/180917267-d74f37cb-6f73-44e9-ad43-d7dba5911906.png)
![image](https://user-images.githubusercontent.com/22766436/180917292-4df5f049-33a3-465b-9ec8-db9d69785cd4.png)

**Comment by wangfupeng1988** [comment]
非常赞！

**Comment by wangfupeng1988** [comment]
我会把这个 issue 放在官方文档中，作为示例。感谢反馈~

**Comment by lemondreamtobe** [comment]
> 非常赞！

哈哈哈，谢谢。
demo中还有不完善的地方，需要在getValue中，把editor带个react组件。
这样，react组件也能使用编辑器api。

**Comment by wangfupeng1988** [comment]
@vvc1998 看报错是菜单 key 重复注册了

**Comment by vvc1998** [comment]
只有这里注册了一次，keys怎么改都报错；
但是报错都是报的下图中的key的名







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月19日(星期五) 下午5:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 此贴为了展示在react中更方便的扩展menu，替代原有的modalMenu方案。 (Issue #4598)





 
@vvc1998 看报错是菜单 key 重复注册了

**Comment by letong520** [comment]
vue 能这样玩吗

**Comment by letong520** [comment]
VUE可以这样实现吗，怎么写

**Comment by superTigery** [comment]
@letong520  vue是怎么实现的？能分享下吗？

**Comment by fantasy1943** [comment]
@lemondreamtobe 感谢大佬分享，但是现在还有跟问题就是这个弹窗这么跟编辑器通信呢？

**Comment by poesky** [comment]
这边分享一下vue2的方案

# 实现步骤
* 步骤一 在index.html创建一个带id的dom
```html
<!DOCTYPE html>
<html lang="">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width,initial-scale=1.0" />
		<link rel="icon" href="<%= BASE_URL %>favicon.ico" />
		<title><%= htmlWebpackPlugin.options.title %></title>
	</head>
	<body>
		<div id="app"></div>
                <!-- 跟new Vue的id一致 -->
                <div id="cubeModal"></div>
	</body>
</html>
```

* 步骤二 封装一个基础的modalMenu 类
```ts
import { IDomEditor, IButtonMenu } from '@wangeditor/editor'
import Vue from "vue"
// 业务组件
import CsModal from "./csModal";

export default class MyButtonMenu implements IButtonMenu {
    title: string;
    tag: string;
    $ele: HTMLDivElement;
    $root: any;
    ifInit: boolean = false;

    constructor() {
        this.title = 'title' // 自定义菜单标题
        this.tag = 'button'
        
        this.$ele = document.createElement('div');
        document.body.appendChild(this.$ele);
        this.$ele.id = "myModal";
        // 在父dom节点创建dom节点
        document.getElementById('cubeModal').appendChild(this.$ele);

        // new一个vue实例
        this.$root = new Vue({ el: "#myModal", render: (h) => { return h(CsModal, { ref: 'myModal' }) } });
    }

    // 点击菜单时触发的函数
    exec(editor: IDomEditor, value: string | boolean) {
        if (this.ifInit) {
            return;
        }
        this.ifInit = true;
    }

    // 获取菜单执行时的 value ，用不到则返回空 字符串或 false
    getValue(editor: IDomEditor): string | boolean {
        this.$root.$refs.myModal.init(editor, this);
        return false
    }

    // 菜单是否需要激活（如选中加粗文本，“加粗”菜单会激活），用不到则返回 false
    isActive(editor: IDomEditor): boolean {  // TS 语法
        return false
    }

    // 菜单是否需要禁用（如选中 H1 ，“引用”菜单被禁用），用不到则返回 false
    isDisabled(editor: IDomEditor): boolean {
        return false
    }
}
```


* 步骤三 自己定义需要的什么样子的弹窗
```ts
export default {
    data() {
        return {
            visible: false,
            editor: "",
            title: "",
        };
    },
    methods: {
        init(editor, { title }) {
            this.visible = true;
            // this.editor = editor;
            this.title = title;
        }
    },
    render() {
        return (
            <el-dialog
                title={this.title}
                visible={this.visible}
                modal={false}
                on-close={() => {
                    this.visible = false;
                }}
            >
                my-dialog
            </el-dialog>
        );
    }
};
```

* 步骤四 注册 这一步正常的按照文档
```ts
Boot.registerMenu(myModalMenuConf)
const toolbarConfig: Partial<IToolbarConfig> = {
    insertKeys: {
        index: 0,
        keys: ['myModalMenu'], // show menu in toolbar
    }
}
```

**Comment by Yung-Sun** [comment]
@fantasy1943 就像 @lemondreamtobe 提到那样，在 getValue 把编辑器传给弹窗就好了吧
![image](https://user-images.githubusercontent.com/67865940/203462182-8b4899c5-6234-46d1-b349-0e3ee42a8c7b.png)

**Comment by fantasy1943** [comment]
@Yung-Sun 感谢大佬指点，我后面也试出来了，就是这样

**Comment by ddq1971130532** [comment]
vue3 + ts，execFn就是你的自定义事件
### // main.ts
![image](https://user-images.githubusercontent.com/51527118/234488500-bd1f152c-5f76-47bb-a868-4749865c5ab7.png)
### // 使用的页面
![image](https://user-images.githubusercontent.com/51527118/234488747-71c64bd2-5e35-477d-bf29-1f25653bd507.png)

![image](https://user-images.githubusercontent.com/51527118/234488715-be851075-9d22-40b6-8e09-a6cb46ca6b87.png)

**Comment by wazehao** [comment]
感谢大佬分享

**Comment by simon-muyezhang** [comment]
@wangfupeng1988 @lemondreamtobe 请问大佬为什么我回报这个错误，代码跟你一模一样。我查看到Object.isExtensible(this);为false。这个是为什么？ 
![image](https://github.com/wangeditor-team/wangEditor/assets/10706610/0e88bd7f-5f9f-4fbc-b577-9b80f90f1725)

**Comment by trowa1234** [comment]
@simon-zhangmuye 报错是因为editor实例是一个不可扩展的冻结对象，报错信息说的很清楚了。
这里应该使用编辑器提供的自定义事件：
触发
![image](https://github.com/wangeditor-team/wangEditor/assets/30816662/743d3113-b042-4be1-85e3-f32fbc408436)

监听。在编辑器onCreated中进行监听
![image](https://github.com/wangeditor-team/wangEditor/assets/30816662/5a59f2c8-95ee-4857-942f-8288713d4d8b)

**Comment by zlrlyy** [comment]
悬停到新增的功能上，没有tooltip了怎么解决？

**Comment by zhongfangsheng** [comment]
> Boot.registerMenu(myModalMenuConf)
组件的注册不要放到editor组件里面，应当放在全局去注册，且在editor组件执行前

**Comment by abigmiu** [comment]
我用的editor.emit 控制弹窗显示

**Comment by Aitaos** [comment]
> 悬停到新增的功能上，没有tooltip了怎么解决？

title 相当于就是tooltip，你需要使用svg

**Comment by lianer3588** [comment]
大佬 请问如果我要在react实现的弹窗组件中使用redux该怎么处理呢？

**Comment by zlrlyy** [comment]
> > 悬停到新增的功能上，没有tooltip了怎么解决？
> 
> title 相当于就是tooltip，你需要使用svg

感谢，已解决

**Comment by lemondreamtobe** [comment]
> 大佬 请问如果我要在react实现的弹窗组件中使用redux该怎么处理呢？

你的弹窗直接connect成容器组件

**Comment by chinahmz** [comment]
> vue3 + ts，execFn就是你的自定义事件
> 
> ### // main.ts
> ![image](https://user-images.githubusercontent.com/51527118/234488500-bd1f152c-5f76-47bb-a868-4749865c5ab7.png)
> 
> ### // 使用的页面
> ![image](https://user-images.githubusercontent.com/51527118/234488747-71c64bd2-5e35-477d-bf29-1f25653bd507.png)
> 
> ![image](https://user-images.githubusercontent.com/51527118/234488715-be851075-9d22-40b6-8e09-a6cb46ca6b87.png)

感谢分享！

**Comment by Pmantou** [comment]
我理解的这块一堆代码本质上其实就是解决一个回调问题，可以直接在editor上挂载一个回调函数，可以让页面中接受到用户点击事件以及区分点击不同类型按钮的key就可以了，只要知道用户的动作，什么都可以实现，其他逻辑都不应该存在

比如
文件1: wangEditor按钮类中exec函数：
	exec(editor, value) {
		editor.onCallback("key");
	}
文件2: 业务页面
	editor.onCallback = (key: string) => {
		console.log(key);
		if(key === "modal"){
		  //打开页面弹窗
		}
	};

**Comment by yatoku** [comment]
接收用户点击事件确实只需要在`exec`函数中添加`editor.emit()`即可，若是需要判断模块的内容是否被删除应该怎么操作呢？

**Comment by QiaoYang0923** [comment]
vue2看这个[https://juejin.cn/post/7426579538455314451](url)
