### ISSUE TITLE
使用wangeditor二次封装的vue组件 v-model 只传img标签的html时报错

### ISSUE THREAD

**Issue by tspandhy** [wangeditor-team/wangEditor#4599]
## 问题描述

*我把wangEditor 封装成vue组件 然后通过v-model进行组件传值  如果传的值里面是html的img标签 比如 "<img src=https://img2.baidu.com/it/u=1814268193,3619863984&fm=253&fmt=auto&app=138&f=JPEG?w=632&h=500 />" 那么点击编辑框里面就会报错如果img前面加上h1标签 就正常，不报错
![image](https://user-images.githubusercontent.com/58933576/180932752-97fb1680-a91c-4057-bf52-5b0112961c9f.png)
 *

## wangEditor 版本

*
![image](https://user-images.githubusercontent.com/58933576/180932917-2b6f4276-db9f-4b59-a9bf-46f07f4b8f1d.png)
*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一在vue里面二次封装 wangeditor 并使用v-model进行传值 
- 步骤二传的值里面只放img标签的html
- 步骤三在父元素里面点击编辑框 就会报错

**Comment by wangfupeng1988** [comment]
你用官网 Vue demo 试试能复现吗？

**Comment by tspandhy** [comment]
在官网的demo中没有问题 ，但是把代码原封不动的搬到我的项目里面 一样会报错，很奇怪，我调试过了，好像是因为编辑器里面的初始值<p><br/></p>不见了 所以是没有最外层的根节点的问题，但是我不明白这个问题产生的原因是什么

**Comment by wangfupeng1988** [comment]
`<img>` 不能直接作为编辑器的节点，需要使用 `<p>` 包裹，这是编辑器的规则。

**Comment by tspandhy** [comment]
可是`<p><br/></p>`不是默认值么，正常来说他不会消失才是对的，可他现在不见了，就算我给编辑器赋空值他也不会消失啊，为什么直接赋img标签他就不行呢，我想问有什么情况是会导致默认值不见得？？？

**Comment by tspandhy** [comment]
需要的话，我可以给你发个demo 看看是哪里出现问题了

**Comment by wangfupeng1988** [comment]
可以在这里做一个 demo （三选一即可），链接发过来

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by tspandhy** [comment]
我不太会用这些在线编程网站，主要是依赖老是装不对，很难装。可以的话，可以给个邮箱么，我直接发一个小demo给你看

**Comment by wangfupeng1988** [comment]
你把 demo 提交到github，然后在 codesandbox 中导入你的 github 项目，就可以启动给一个在线 demo 了

**Comment by tspandhy** [comment]
https://1o42v4-8080.preview.csb.app/index
上面的地址就是在线demo了 打开后 打开控制台 点击编辑框里面就可以看到报错了

**Comment by tspandhy** [comment]
https://codesandbox.io/p/github/tspandhy/demo/draft/romantic-gauss?create=true&import=true&file=%2Fsrc%2FApp.vue
这个是在线编辑器的

**Comment by liuqh0609** [comment]
我把你仓库[demo](https://github.com/tspandhy/demo)，拉到本地之后运行没有复现你所说的问题。不过在你提供的codesandbox中能看到上面的错误。

**Comment by liuqh0609** [comment]
![image](https://user-images.githubusercontent.com/43341115/181492424-d33163b6-de88-43b5-9c90-05224a811bc8.png)

**Comment by liuqh0609** [comment]
你尝试把`@wangeditor/editor`依赖升级到5.1.14试一下

**Comment by liuqh0609** [comment]
https://github.com/tspandhy/demo/pull/1 我给你demo提了pr，你合并之后在本地更新依赖，试一下

**Comment by tspandhy** [comment]
升级依赖是可行的，不报错了，但是还有一个疑问，就是我拿官网的demo到本地运行，我把依赖换成我报错的版本，它一样没有报错，是什么原因呢

**Comment by liuqh0609** [comment]
你可以看下`node_modules`里面实际安装的依赖版本号
