### ISSUE TITLE
编辑器兼容性问题（特别着急）

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4600]
## bug 描述

xp系统 的 chrome浏览器 不支持 该编辑器

## 你预期的样子是？

需要支持

## 系统和浏览器及版本号

- 操作系统：windows XP
- 浏览器和版本： chrome 49.0.2623.112

## wangEditor 版本

V5最新版本

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
xp 不再支持

**Comment by zxueliang** [comment]
@wangfupeng1988 
麻烦支持一下呗，也有可能是哪个函数啥的不支持导致的呢。辛苦了
