### ISSUE TITLE
发布新闻在标签下面添加日期

### ISSUE THREAD

**Issue by wangbingzhi518** [wangeditor-team/wangEditor#4601]
## 问题描述

*我用这个富文本做新闻发布，怎么样在标题下另起一行居中显示日期*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
自行扩展吧，看文档。
