### ISSUE TITLE
希望插入表格可以合并单元格

### ISSUE THREAD

**Issue by lt090004114** [wangeditor-team/wangEditor#4602]
现在wangEditor可以插入表格，但是没法合并单元格，希望能新增该功能

**Comment by wangfupeng1988** [comment]
暂不支持。合并单元格非常复杂，暂无精力开发。业余维护，还请体谅~

不过，你从 word excel 复制粘贴过来的表格，如果其中有合并了的单元格，是可以正常显示的，只是不能再拆分单元格了。
