### ISSUE TITLE
企业微信复制的文本不兼容

### ISSUE THREAD

**Issue by jhh03260318** [wangeditor-team/wangEditor#4603]
## 问题描述

从企业微信复制过来的文本内容不兼容，企业微信的文本格式是由一个p标签和多个br标签包裹的，所以设置其中一行的内容为标题时，会将所有文本都设置成标题。或者设置其中一行文本的行高，也会将所有的文本都设置行高。

## wangEditor 版本

V5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

从企业微信复制一段文本，然后粘贴进富文本中，比如从企业微信复制一段活动规则，复制进富文本中

**Comment by jhh03260318** [comment]
用于vue环境中，我尝试在onChange中用正则匹配掉br标签，然后重新给v-model绑定的值赋值，但是就报错了，报错内容是"Cannot resolve a DOM node from Slate node"

**Comment by wangfupeng1988** [comment]
复制过来的 HTML 具体是什么？

PS：可以通过 [customPaste](https://www.wangeditor.com/v5/editor-config.html#custompaste) 打印出来

**Comment by jhh03260318** [comment]
`'<p>砸金蛋活动规则：<br>1.活动时间： <br>2.活动用户：XXX<br>3.参与用户需登录且认证手机号码后，方可参与活动；<br>4.点击砸开金蛋，即有机会获得亚运相关活动产品、亚运币等；获得的亚运币可在兑换商城进行奖品兑换。</p>'`
复制出来的具体格式是这个样子，我试着用正则将br标签替换掉，然后更改v-model绑定的值，就报错了

**Comment by wangfupeng1988** [comment]
通过这个 demo https://www.wangeditor.com/demo/set-html.html ，按照你给出的 HTML 去解析是没有问题的，不用替换 `<br>` ，如下图

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/9583120/181137139-768c3c1d-d39c-44c9-8dfb-6739de64c415.png">

**Comment by jhh03260318** [comment]
![image](https://user-images.githubusercontent.com/71248504/181153980-3747f1fc-e025-4e39-a495-4bf47ee00175.png)
### **如上图:这种HTML格式我想要改变选中的文本，比如修改文本的标题**


![image](https://user-images.githubusercontent.com/71248504/181154167-41fdba71-6601-4603-bf2b-adbe35d3eaaf.png)
### **如上图:它就会将所有的文本都设置成标题,所以我需要替换`<br>`*

**Comment by wangfupeng1988** [comment]
第一，输入的 HTML 中有 `<br>` ，那编辑器就得按照 HTML 规范来解析 —— 这一点是符合预期的。

第二，如果你想要自行处理，可以通过 [customPaste](https://www.wangeditor.com/v5/editor-config.html#custompaste) 来替换，不要在 onChange 中修改

**Comment by angry-bread** [comment]
我在这个官方提供的react demo也发现不能粘贴企业微信的文本内容
https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js
