### ISSUE TITLE
表格最后一列内容含有链接，会出现多余的空table

### ISSUE THREAD

**Issue by lyraLe** [wangeditor-team/wangEditor#4605]
## bug 描述

*表格最后一列内容含有链接，会出现多余的空table。和去年的[#3580](https://github.com/wangeditor-team/wangEditor/pull/3580)相似*

## 你预期的样子是？

*和没有链接的表格展示相同*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*5.1.12*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
 `<p>hello world</p><table style="width: auto;"><tbody><tr><th colSpan="1" rowSpan="1" width="auto"></th><th colSpan="1" rowSpan="1" width="auto"></th><th colSpan="1" rowSpan="1" width="auto"></th><th colSpan="1" rowSpan="1" width="auto"></th></tr><tr><td colSpan="1" rowSpan="1" width="auto"></td><td colSpan="1" rowSpan="1" width="auto"></td><td colSpan="1" rowSpan="1" width="auto"></td><td colSpan="1" rowSpan="1" width="auto"></td></tr><tr><td colSpan="1" rowSpan="1" width="auto"></td><td colSpan="1" rowSpan="1" width="auto"></td><td colSpan="1" rowSpan="1" width="auto"></td><td colSpan="1" rowSpan="1" width="auto"><a href="地方撒" target="_blank">但是敢死队风格</a></td></tr></tbody></table><p><br></p>`
- 步骤二
在demo的setHtml功能上点击setHTML按钮
- 步骤三
出现多余的表格

**Comment by wangfupeng1988** [comment]
已复现，会高优处理

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版试试吧

demo 还要等一等，CDN 有缓存
