### ISSUE TITLE
目前还没有api支持能重置编辑器配置

### ISSUE THREAD

**Issue by lemondreamtobe** [wangeditor-team/wangEditor#4606]
## 问题描述

在应用中，编辑器的config是会随着应用以及业务改变的。
但是初始化出来的编辑器只有一个。
目前还没有api支持能重置编辑器配置吗？
降级处理成先destory 再re create 有点不优雅

## wangEditor 版本
v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

**Comment by wangfupeng1988** [comment]
你具体哪些配置需要改变？我看能否通过 API 支持
