### ISSUE TITLE
表格内容不选全部选中

### ISSUE THREAD

**Issue by lyraLe** [wangeditor-team/wangEditor#4607]
## bug 描述

*表格填完内容后，希望选中所有的表格内容进行字体样式调整，但是只有偶尔才能选中，大部分时间很难选中所有内容*

## 你预期的样子是？

*能很顺利的选中表格内容，然后进行字体颜色，粗细等的调整*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
新建一个表格，表格内填写内容
- 步骤二
进行表格所有内容的选中操作

**Comment by wangfupeng1988** [comment]
目前不支持。

以为选择表格多个单元格，或者选择表格内的一部分 + 表格外的一部分，再删除会有很多异常 bug 。

所以，为了操作稳定性，先不支持这些，后面再优化吧。
