### ISSUE TITLE
win7系统下输入问题

### ISSUE THREAD

**Issue by sogamix** [wangeditor-team/wangEditor#4608]
## bug 描述

你好，win7系统下，输入文本，再输入中文符号，最后输入空格/回车，中文符号自动被删除，并且光标位置跳到了文本首处；

仅在win7系统上复现

## 你预期的样子是？

  能够正常输入

## 系统和浏览器及版本号

- 操作系统
  
  win7

- 浏览器和版本

  chrome 103.0.5060.134

## wangEditor 版本

  5.0.0

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- win7系统，正常输入文字，输入中文字符，再输入空格/回车

**Comment by wangfupeng1988** [comment]
官网 demo 可复现吗？

另外，你用什么输入法？
