### ISSUE TITLE
预览功能

### ISSUE THREAD

**Issue by BugOS-ly** [wangeditor-team/wangEditor#4609]
## 功能描述

使用wangEditor进行文本编辑, 保存文本内容后, 读取文本内容, 仅仅预览文本内容

## 提炼几个功能点

- 仅预览, 无法修改
- 无菜单栏

## 原型图

与原编辑器的编辑区一致

## 可参考的案例

暂无

**Comment by wangfupeng1988** [comment]
获取 HTML 显示即可，自行开发即可
