### ISSUE TITLE
如何手动清除撤销记录

### ISSUE THREAD

**Issue by antipro7** [wangeditor-team/wangEditor#4610]
## 问题描述

页面展示一个富文本，有一组选项用来切换富文本内显示的内容。切换内容后富文本可以回撤到之前的内容。
不希望每次切换内容就销毁富文本重新创建

## wangEditor 版本

V4

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
第一，切换文章，最好是销毁、然后重新创建编辑器。编辑器是一个非常复杂的软件，内部指不定有啥漏洞 bug ，来回折腾次数多了可能就不那么稳定了，这谁也说不准。销毁重建，就能更好的保证稳定性。

第二，v4 已经没精力维护了，业余维护，时间不够，只能先顾好 v5 ，还请体谅

**Comment by antipro7** [comment]
好的感谢您的回答，确实找了文档和网上的资料，猜测也是没有这个功能，建议更新。
