### ISSUE TITLE
全选后输入中文，有报错（windows QQ 输入法）

### ISSUE THREAD

**Issue by suwei0708** [wangeditor-team/wangEditor#4611]
## bug 描述

*编辑器全选后，使用中文输入法输入内容，会报错，后面无法输入内容。报错内容Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. *

## 你预期的样子是？

*编辑器全选后，使用中文输入法输入内容，显示输入的内容*

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本：Google Chrome 103.0.5060.134（正式版本） （64 位）

## wangEditor 版本

*"@wangeditor/editor": "^5.1.12",
    "@wangeditor/editor-for-vue": "^5.1.12",*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- 官网demo就有这个问题

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 编辑器内输入文字，然后全选，输入法为中文，英文没问题（本人为QQ拼音输入法，中文）
- 步骤二
- 任意输入文字，输入后就会报错

**Comment by wangfupeng1988** [comment]
你如果方便的话，可以再看看搜狗输入法是否报错？我判断下是否和输入法有关系

我是 mac 系统，自己用搜狗输入法 在 chrome 是复现不了的。

**Comment by suwei0708** [comment]
搜狗输入法没有问题，装的最新的12.2.0，看来就是QQ输入法有问题

**Comment by wangfupeng1988** [comment]
好，我先记录下吧，后续排查

**Comment by TGuoW** [comment]
@suwei0708 没有复现。系统和浏览器版本都对得上，QQ输入法是最新的版本

**Comment by suwei0708** [comment]
@TGuoW QQ拼音输入法6.6，确实会有这个问题，这是我家里的电脑，公司的电脑同样会有这个问题。

https://user-images.githubusercontent.com/44421037/181571342-bc0737e6-7edb-47ec-82d2-bd0f53cd92f0.mp4

**Comment by TGuoW** [comment]
@suwei0708 不太好排查，我这边就是最新的6.6，没有办法复现

**Comment by suwei0708** [comment]
@suwei0708 那这个就没办法了，现在测试没用QQ输入法，问题不大
