### ISSUE TITLE
复制粘贴百度文章任意一行，或者标题（复制多行内容不会报错），就会报以下错误， 且再复制其他内容就会一直报错，无法复制粘贴

### ISSUE THREAD

**Issue by momo4520** [wangeditor-team/wangEditor#4612]
## bug 描述
复制粘贴百度文章任意一行，或者标题（复制多行内容不会报错），就会报以下错误， 且再复制其他内容就会一直报错，无法复制粘贴
![image](https://user-images.githubusercontent.com/24591465/181232701-28109b93-f533-4f0b-9799-c40903723460.png)

## 你预期的样子是？

不要报错

## 系统和浏览器及版本号

- win10
- Chrome, 103.0.5060.66（正式版本） （64 位）

## wangEditor 版本

"@wangeditor/editor": "^5.1.6",
"@wangeditor/editor-for-vue": "^5.1.12",

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
第一，你说的“百度文章”是啥？给一个链接

第二，能否在官网 demo 复现？

第三，将 `@wangeditor/editor` 升级到最新版本再试试

**Comment by wangfupeng1988** [comment]
第一，你说的“百度文章”是啥？给一个链接

第二，能否在官网 demo 复现？

第三，将 `@wangeditor/editor` 升级到最新版本再试试

**Comment by momo4520** [comment]
https://mbd.baidu.com/newspage/data/landingsuper?context=%7B%22nid%22%3A%22news_10124454569326154470%22%7D&n_type=-1&p_from=-1&qq-pf-to=pcqq.group

demo不能复现


> 第一，你说的“百度文章”是啥？给一个链接
> 
> 第二，能否在官网 demo 复现？
> 
> 第三，将 `@wangeditor/editor` 升级到最新版本再试试

**Comment by momo4520** [comment]
现在更新到5.1.14版本，复制标题可以，但是现在出现两个问题：
1、再复制粘贴会把之前的内容覆盖掉
2、回车再复制粘贴会报错
![image](https://user-images.githubusercontent.com/24591465/181236722-67af9be1-fd01-4bc8-abca-fbb16799d494.png)

**Comment by momo4520** [comment]
vue版本是：3.2.37

**Comment by momo4520** [comment]
我的代码：
![image](https://user-images.githubusercontent.com/24591465/181237696-d7837d88-88d3-453e-85d4-22eeab9f1462.png)

**Comment by wangfupeng1988** [comment]
在 customPaste 中不要使用 `setHtml` ，`setHtml` 是重置，不是插入。

插入 HTML 要使用 [dangerouslyInsertHtml](https://www.wangeditor.com/v5/API.html#dangerouslyinserthtml)

**Comment by wangfupeng1988** [comment]
你写错了，注意大小写。

**Comment by momo4520** [comment]
> 你写错了，注意大小写。

好的，谢谢大佬，我刚才试了一下，把自定义的去掉，不会报错。

**Comment by momo4520** [comment]
问题解决了，很开心，谢谢大佬这么及时耐心的解答
