### ISSUE TITLE
emoji列表未对齐

### ISSUE THREAD

**Issue by sakurawaifu** [wangeditor-team/wangEditor#4614]
## bug 描述

emoji列表未对齐
![image](https://user-images.githubusercontent.com/52623903/181399470-35a026c3-2617-45da-8cf0-263d8c13ee3f.png)

## 你预期的样子是？

emoji对齐网格
![image](https://user-images.githubusercontent.com/52623903/181399634-8d12f282-b321-4158-b622-2a3ebeed2660.png)

## 系统和浏览器及版本号

- 操作系统 Windows 10 Version 21H1 (Build 19043.1586)
- 浏览器和版本 Chrome 103.0.5060.66

## wangEditor 版本

5.1.12

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

- 步骤一 点开emoji列表
- 步骤二 查看emoji排列情况

**Comment by wangfupeng1988** [comment]
自己定义这个 CSS 样式吧

```css
.w-e-panel-content-emotion {
    /* todo */
}

.w-e-panel-content-emotion li {
    /* todo */
}
```
