### ISSUE TITLE
当我完全使用自定义上传时，没有api能在光标处插入图片

### ISSUE THREAD

**Issue by lemondreamtobe** [wangeditor-team/wangEditor#4615]
## 问题描述

首先，我用exclude keys: [‘group-image’]
禁止掉了原有的图片上传功能。

再用btn按钮菜单，扩展了编辑器的menu。

这个菜单是我自定义的，会打开一个弹窗，调用antd/upload组件
当我upload完了，拿到了地址。
没有找到相关的api能在光标处插入图片。

文档中有一个insertFn
```js
editorConfig.MENU_CONF['uploadImage'] = {
    // 自定义上传
    async customUpload(file: File, insertFn: InsertFnType) {  // TS 语法
    // async customUpload(file, insertFn) {                   // JS 语法
        // file 即选中的文件
        // 自己实现上传，并得到图片 url alt href
        // 最后插入图片
        insertFn(url, alt, href)
    }
}
```
但是我完全使用了自己的上传业务，所以以上的配置是没用的。
本质上还是需要一个api，能在我完成自己的上传时能给我插入到光标。
翻看源码是混淆的 没有找到insertFn源码实现。

目前我只能通过以下方式插入图片
![image](https://user-images.githubusercontent.com/22766436/181403470-67f906fe-3df3-4329-9813-4715ba5224b0.png)
但是会在光标下另起一行，没办法做到灵活。

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

**Comment by wangfupeng1988** [comment]
```js
editor.dangerouslyInsertHtml('<img src="xxx.png" alt="xxx"/>')
```

**Comment by lemondreamtobe** [comment]
> ```js
> // 如果编辑器 blur ，先恢复选区
> editor.restoreSelection()
> 
> // 插入 img - HTML 格式
> editor.dangerouslyInsertHtml('<img src="xxx.png" alt="xxx"/>')
> 
> // 插入 img - JSON 格式（二选一）
> editor.insertNode({
>     type: 'image',
>     src: 'xxx.png',
>     alt: 'xxx',
>     children: [{text: ''}]  // 这一行必须要有！
> })
> ```

感谢！
