### ISSUE TITLE
XP系统兼容性问题

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4616]
## 功能描述

麻烦给看一下 XP 系统  chrome 49.0.2623.112 不支持 富文本编辑器的原因呗
我找到报错的地方了，能帮忙给重写一下这个方法吗？
 这个js（custom-elem.js）的 window.customElements 这个不支持 chrome 54版本以下的
兼容性如下图：
![123](https://user-images.githubusercontent.com/39672406/181409716-e7682774-3d79-41dc-b39e-1d305ccf3856.png)

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
> 这个js（custom-elem.js）的 window.customElements 这个不支持 chrome 54版本以下的

自己加一个 polyfill 吧，兼容一下

**Comment by zxueliang** [comment]
@wangfupeng1988 
polyfill  这个是解决 es6语法的，不能 解决  window.customElements 这个问题啊，麻烦能给重写一下吗，辛苦了

**Comment by wangfupeng1988** [comment]
不对呀，custom-elem.js 只是我 demo 里用的，wangEditor 输出的源码里没有 `customElements` 。

**Comment by zxueliang** [comment]
index.js 的17107行报错误，导致 window.wangEditor 为空
如下图：
![12](https://user-images.githubusercontent.com/39672406/181463219-4b2751a7-7f36-4f1e-8552-2651c901f45d.png)

**Comment by wangfupeng1988** [comment]
对，可能是浏览器不支持这个语法，版本太低了，最新版都 100+ 了

**Comment by zxueliang** [comment]
> 对，可能是浏览器不支持这个语法，版本太低了，最新版都 100+ 了

能给兼容一下嘛，辛苦了，xp 系统确实还有好多人在用

**Comment by wangfupeng1988** [comment]
我们也是业余开发，精力有限，真的顾不了那么多。你看看 issues 列表，还有那么多 bug 没改完呢。
所以请你不要一再追问了，不兼容 xp ，不兼容 chrome 低版本。

如果你真的对 xp 或低版本 chrome 有要求，你可以考虑其他编辑器产品。

**Comment by zxueliang** [comment]
@wangfupeng1988 
打扰一下，我们这边用这种方法解决的XP报错的问题：
1、vue 安装 get-root-node-polyfill ，keyboardevent-key-polyfill 了 这2个插件；
2、在 main.js 里引入 
require("get-root-node-polyfill/implement");
require("keyboardevent-key-polyfill").polyfill();
这2个
3、.browserslistrc  这个文件加入 Chrome > 48 这个；
4、vue.default.config.js  这个文件 加入   transpileDependencies: ["@wangeditor/editor", "@wangeditor/editor-for-vue"]
通过以上方法，解决的
但是 从word复制带表格的内容，表格不显示

**Comment by wangfupeng1988** [comment]
word 复制粘贴，目前无法兼容所有格式，得慢慢支持。

**Comment by zxueliang** [comment]
@wangfupeng1988 
大佬，你的编辑器确实挺好用的。
根据我的解决方案，你那边能帮忙给兼容一下XP 系统嘛？辛苦了

**Comment by wangfupeng1988** [comment]
抱歉，我们不再考虑 xp 系统了。

你找到了方法，你可以 fork 到自己的 github ，然后自己修改，自己发布到 npm  即可。
