### ISSUE TITLE
搜狗输入法+win+在行内元素前输入 = 崩溃报错

### ISSUE THREAD

**Issue by OldDream** [wangeditor-team/wangEditor#4617]
## bug 描述

搜狗输入法+win+在行内元素前选中一段文字，并用搜狗输入法输入中文 = 崩溃报错

## 你预期的样子是？

选中内容被替换为输入法输入的内容

## 系统和浏览器及版本号

- 操作系统 win11
- 浏览器和版本 chrome 103

## wangEditor 版本

直接在官网demo上可复现

## demo 能否复现该 bug ？

能！

- 中文 demo https://www.wangeditor.com/demo/

## 最小成本的复现步骤

- 步骤一 ：输入任意文字+插入超链接
![image](https://user-images.githubusercontent.com/18358438/181422138-8f6c0cad-d558-4641-839a-6ece3334fb24.png)

- 步骤二：选中超链接前的文字
- 
![image](https://user-images.githubusercontent.com/18358438/181422204-1d1b98f5-6452-4ef4-b3c9-17eade7974f2.png)

- 步骤三：用搜狗输入法，键入拼音，即可观察到bug---超链接消失
- 
![image](https://user-images.githubusercontent.com/18358438/181422319-17366b09-cc86-425b-b623-0b576f47372e.png)
![image](https://user-images.githubusercontent.com/18358438/181422367-86b3cc3a-86cf-4176-ba7b-f8f8557eb436.png)

个人感觉这个bug和搜狗输入法的compositionStart/Update/End事件有关，后面的超链接似乎不是关键，只要是个行内元素就行。
SlateJS也有类似问题，可去这里尝试 https://www.slatejs.org/examples/mentions 。

**Comment by TGuoW** [comment]
@OldDream 没有复现。操作系统跟浏览器版本都跟你对得上，QQ输入法是最新的版本

**Comment by OldDream** [comment]
> @OldDream 没有复现。操作系统跟浏览器版本都跟你对得上，搜狗输入法是最新的版本

头疼，我也发现这不是必现，在另一台电脑上，和我同样是win11，同样是chrome103，但是他的搜狗输入法，在输入拼音时，对应的字母会出现在富文本编辑器中-----这样就不会触发bug，但在我的电脑上，输入拼音时，对应的字母不会出现在富文本编辑器中，这会触发bug。
等下我去多找几台电脑试试。

**Comment by OldDream** [comment]
![QQ录屏20220729102619](https://user-images.githubusercontent.com/18358438/181670203-c6db328f-e45f-495b-8332-047012beb373.gif)

**Comment by OldDream** [comment]
换了台电脑，之前提的bug没复现，但是发现了新bug，需要我新开一个issue还是就在这儿提？
附上gif，注意看超链接后面的部分。
![QQ录屏20220729190607](https://user-images.githubusercontent.com/18358438/181747608-e930eac7-cb05-4b97-bb16-cdf06da0ef99.gif)

**Comment by wangfupeng1988** [comment]
新 bug 提交新 issue ，别混在一起。

**Comment by OldDream** [comment]
> 新 bug 提交新 issue ，别混在一起。

👌🏻

**Comment by TGuoW** [comment]
我多试试吧，现在完全正常

**Comment by wangfupeng1988** [comment]
@TGuoW 自己复现不了的，可以发到咱们微信群，让别人帮忙试试。
