### ISSUE TITLE
字符被吃掉，光标错位

### ISSUE THREAD

**Issue by zhm84** [wangeditor-team/wangEditor#4618]
## bug 描述

正常输入文字或字符，按空格或enter键，字符被吃掉，光标错位，但控制台没有报错。
不能稳定复现，但是有好几个用户遇到同样的问题了，打断点debug发现editor.getHtml()返回的内容有点问题；

![图1](https://user-images.githubusercontent.com/57031862/181450846-f49ef2cb-9d78-4172-8cad-2825f0446d07.png)
![图2](https://user-images.githubusercontent.com/57031862/181450871-8346770a-1a22-4f20-9f51-f85556cd787b.png)

## 你预期的样子是？

正常输入内容，光标不错位

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本：chrome 93

## wangEditor 版本

^5.1.1

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤
不太好复现

**Comment by wangfupeng1988** [comment]
升级 `@wangeditor/editor` 最新版本

再持续观察一下吧，找个复现步骤，否则我也不好定位。
