### ISSUE TITLE
editor为空获取value值存在"<p><br></p>"，在表单中无法校验

### ISSUE THREAD

**Issue by WaQuio** [wangeditor-team/wangEditor#4619]
## 问题描述

*editor为空获取value值存在`"<p><br></p>"`，在表单中无法校验其是否输入内容*

## wangEditor 版本

*V3, V4, V5…*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 新建editor
- change事件的value
- 步骤三

**Comment by momo4520** [comment]
好像可以用editor.isEmpty()来判断

**Comment by WaQuio** [comment]
> 好像可以用editor.isEmpty()来判断

这个我看到了， 但是集成在表单里面，就需要根据editor的change事件的value来做验证的嘛，这样做有没有比较合适的做法呢？

**Comment by lp0124** [comment]
我这边也遇到了 值一直不为空，导致小程序侧获取的富文本判定有内容，准备在返回出去的时候replace下

**Comment by wangfupeng1988** [comment]
第一，先参考注册插件的文档 https://www.wangeditor.com/v5/development.html#%E5%8A%AB%E6%8C%81%E7%BC%96%E8%BE%91%E5%99%A8%E4%BA%8B%E4%BB%B6%E5%92%8C%E6%93%8D%E4%BD%9C-%E6%8F%92%E4%BB%B6 

第二，定义一个插件，判断 isEmpty 时，输出空字符串

```js
function withEmptyHtml(editor) {
      const { getHtml } = editor
      const newEditor = editor

      newEditor.getHtml = () => {
        if (newEditor.isEmpty()) {
          return ''
        }
        return getHtml()
      }

      return newEditor
    }
```

第三，把插件注册到 wangEditor （参考文档）

**Comment by lp0124** [comment]
this.$emit('change', this.editor.isEmpty() ? '' : val)

**Comment by WaQuio** [comment]
> 

感谢作者

**Comment by WaQuio** [comment]
> 

这样子不行， 我通过 `import { Editor, Toolbar } from '@wangeditor/editor-for-react';` 
使用的Editor组件
`<Editor
                defaultConfig={editorConfig}
                value={value}
                onCreated={setEditor1}
                onChange={edt => getEditorHtml(edt.getHtml())}
                mode="default"
              />
            </div>`
存在state
`const [editor, setEditor] = useState<IDomEditor | null>(null);`
然后chenge事件里面 `console.log(editor?.isEmpty()) // undefined` 一直都是undefined

**Comment by wangfupeng1988** [comment]
@WaQuio 如果 editor 一直是 undefined ，那你是如何得到 `editor.getHtml()` 的？

**Comment by WaQuio** [comment]
> @WaQuio 如果 editor 一直是 undefined ，那你是如何得到 `editor.getHtml()` 的？
editor.getHtml是在<Editor onChange>事件上，在使用了usestate存入了editor的instance之后再获取editor就是null，使用了useref之后就正常了。可能是react环境导致

**Comment by WaQuio** [comment]
@wangfupeng1988  如果 editor 一直是 undefined ，那你是如何得到 editor.getHtml() 的？
editor.getHtml是在<Editor onChange>的 onChange事件上获取的，在使用了usestate存入了editor的instance之后再获取editor就是null，使用了useref之后就正常了。可能是react环境导致，使用的是官方文档的react demo

**Comment by wangfupeng1988** [comment]
在这里给一个 demo 复现一下吧 （三选一即可）

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by WaQuio** [comment]
@wangfupeng1988  https://codesandbox.io/s/boring-dawn-gdtx1b?file=/src/App.tsx

**Comment by hahaaha** [comment]
@WaQuio 你的例子中
html state 没有设置
```
// 编辑器内容
    const [html, setHtml] = useState('<p>hello</p>')
```
需要把例子中html中的state相关的代码加上

**Comment by WaQuio** [comment]
> @WaQuio 你的例子中 html state 没有设置
> 
> ```
> // 编辑器内容
>     const [html, setHtml] = useState('<p>hello</p>')
> ```
> 
> 需要把例子中html中的state相关的代码加上

https://codesandbox.io/s/boring-dawn-gdtx1b?file=/src/App.tsx
我直接运行你们官网 react demo 结果也是一样。

**Comment by hahaaha** [comment]
@WaQuio 你仔细看看官网例子和你的例子的区别
官网例子中editor是从`onchange`中传递过去的
你的例子里自己传递的是content 
<img width="566" alt="截屏2022-08-08 18 44 16" src="https://user-images.githubusercontent.com/25847662/183400965-e832faa3-688d-48be-8c50-32bd6449bb43.png">

**Comment by aiyangjun923** [comment]
在vue2里面使用了作者的方法，完美解决

**Comment by star-hs** [comment]
> 
没有质问作者的意思，只是提下建议
----
v-model我还什么都没写就给我一个默认的<p><br></p>，会让人感到困惑，习惯性就会认为输入控件没操作的时候和初始值保持一致。如果用插件能解决问题，为啥不直接把这个插件默认注册进来呢，也避免用户一直来问。
---
我感觉大多数要用到富文本编辑器的都不是作为业务的主要功能吧，我们也都是想迅速的找个开源的编辑器解决问题（在此感谢作者造了这个轮子），基本都是迅速看一遍上手文档就使用的，最基本的初始值问题还要来看issue才能解决确实有点奇怪？

**Comment by wangfupeng1988** [comment]
@star-hs 淡定，别想三两天就把富文本编辑器搞定。我开发周期就一年，你不可能快速玩转的。任何编辑器都是这样。

**Comment by csj96** [comment]
存在一个问题，期望作者帮忙解决，谢谢！！
情况是，我需要把数据从其他组件传到编辑器中，在传值过程中，值传进去了，但显示出来的就是` <p><br></p>`，
其他值都是正常的，只有v-model绑定的值自动变成`<p><br></p>`,假如将v-model修改成绑定其他值，其他值就变成`<p><br></p>`，原来的值又恢复正常

**Comment by liangzq1** [comment]
提供一个解决方法，仅供参考。写一个工具函数把html转为文本，换句话说就是移除字符串中的html标签。
![image](https://user-images.githubusercontent.com/45655539/230528218-8326eba3-a2b3-435e-b14b-6ae1f45412fc.png)
在watch editor值的时候，emit之前判断如果为空就return。
![image](https://user-images.githubusercontent.com/45655539/230528401-698b43f1-78cb-4b5f-8bd4-ad322d66e555.png)

**Comment by Xuxiansheng-0424** [comment]
import { DomEditor, Boot } from "@wangeditor/editor";
function withEmptyHtml(editor) {
  const { getHtml } = editor;
  const newEditor = editor;
  newEditor.getHtml = () => {
    if (newEditor.isEmpty()) {
      return "";
    }
    return getHtml();
  };
  return newEditor;
}
Boot.registerPlugin(withEmptyHtml);

**Comment by lxychinese** [comment]
> import { DomEditor, Boot } from "@wangeditor/editor"; function withEmptyHtml(editor) { const { getHtml } = editor; const newEditor = editor; newEditor.getHtml = () => { if (newEditor.isEmpty()) { return ""; } return getHtml(); }; return newEditor; } Boot.registerPlugin(withEmptyHtml);

withEmptyHtml这个方法会自动调用？

**Comment by mishengqiang** [comment]
我在vue里这么校验的
```js
// 校验规则
const rules = reactive<FormRules>({
    title: [
        {
            required: true,
            message: '请填写标题',
            trigger: ['change', 'blur'],
        },
        { max: 140, message: '最多填写140个字', trigger: ['change', 'blur'] },
    ],
    content: [
        {
            required: true,
            message: '请填写内容',
            trigger: ['change', 'blur'],
            transform(value) {
                return htmlToText(value)
                    .trim()
                    .split('')
                    .filter((item) => item !== '\n')
                    .join('');
            },
        },
        {
            max: 1000,
            message: '最多填写1000个字',
            trigger: ['change', 'blur'],
            transform(value) {
                return htmlToText(value)
                    .trim()
                    .split('')
                    .filter((item) => item !== '\n')
                    .join('');
            },
        },
    ],
});



/**
 * html字符串转纯文本
 *
 * @export
 * @param {string} htmlString
 * @return {string}
 */
export function htmlToText(htmlStr: string) {
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = htmlStr;
    return tempDiv.innerText;
}
```
