### ISSUE TITLE
建议增加自定义打印模板功能

### ISSUE THREAD

**Issue by Jonathan-Rao** [wangeditor-team/wangEditor#4620]
## 功能描述

是否可以自定义打印模板，定义变量，根据接口返回的json数据，渲染需要打印的动态数据内容

## 提炼几个功能点

- 自定义模板
- 动态数据渲染

## 可参考的案例

https://qingflow.com/help/docs/6116117a9024630046929287

**Comment by wangfupeng1988** [comment]
暂不支持
