### ISSUE TITLE
onChange方法问题(wangEditor-for-react)

### ISSUE THREAD

**Issue by theDoinb** [wangeditor-team/wangEditor#4621]
## bug 描述

onChange 似乎包含了 onFocus 和 onBlur，编辑器并无修改时，blur 和 focus 都会触发 onChange 方法，单独设置 onBlur 或 onFocus无效

## 你预期的样子是？

-

## 系统和浏览器及版本号

- 操作系统
- window
- 浏览器和版本
- 谷歌101.0.4951.67

## wangEditor 版本

最新

## demo 能否复现该 bug ？

-

## 在线 demo

-

## 最小成本的复现步骤

-

**Comment by wangfupeng1988** [comment]
onChange 不是包含 blue 和 focus ，而是在选区变化时也会触发。这符合预期。

因为后面可能要扩展协同编辑功能，需要这个能力。

**Comment by theDoinb** [comment]
但是不使用 onChange，单独用 onBlur 不会触发这个事件

**Comment by wangfupeng1988** [comment]
你意思是：只配置一个 onBlur （其他回调函数不配置），然后编辑器失焦时，onBlur 不触发？

**Comment by theDoinb** [comment]
是的，不触发
```javascript
<Editor
      value={null}
      onCreated={this.onCreatedRichText}
      onBlur={this.onBlurRichTxt} 
      mode="default"
      style={{ height: '300px', overflowY: 'hidden' }}
    />
```

**Comment by hahaaha** [comment]
@theDoinb onBlur 暂时需要你把他设置在editorconfig 中， 这两天我会将组件进行调试以便它更加好用~

**Comment by AttackXiaoJinJin** [comment]
> onChange 不是包含 blue 和 focus ，而是在选区变化时也会触发。这符合预期。
> 
> 因为后面可能要扩展协同编辑功能，需要这个能力。

那可以把「在选区变化时也会触发」这个功能给手动关闭吗？

**Comment by wangfupeng1988** [comment]
@AttackXiaoJinJin 默认不支持。可以参考这里 https://github.com/wangeditor-team/wangEditor/issues/4729

**Comment by AttackXiaoJinJin** [comment]
> @AttackXiaoJinJin 默认不支持。可以参考这里 #4729

看到了，感谢！
