### ISSUE TITLE
自定义菜单 Uncaught (in promise) Error: Duplicated key 'uploadAttachment' in menu items  

### ISSUE THREAD

**Issue by 965588** [wangeditor-team/wangEditor#4622]
版本5中 vue3 具体是这样的：我在对话框中调用了一个组件Editor 然后关闭对话框 再次打开对话框就报这个错了

**Comment by wangfupeng1988** [comment]
看你报错信息，是重复注册了。

不要重复注册，全局注册一次即可

**Comment by freadman** [comment]
解决没？我也碰到这个问题。

**Comment by wangjunjx8868** [comment]
> 看你报错信息，是重复注册了。
> 
> 不要重复注册，全局注册一次即可

如何全局注册呢？我是vue3

**Comment by daxiang-dev** [comment]
把编辑器封装为组件使用的情况下如何做到全局注册呢？

**Comment by Lrunlin** [comment]
> 把编辑器封装为组件使用的情况下如何做到全局注册呢？

生命周期里面
react的话就useEffect

**Comment by simon-muyezhang** [comment]
@wangjunjx8868 @wangfupeng1988 @Daxiang-Zhang @Lrunlin @965588 
请问各位大佬，我也碰到这个问题，我在react项目中多次用到wangeditor，没有进行封装，
目前如果每个组件都注册的话就会显示Duplicated key 'preview' in menu items，但是如果只注册一次用户首先访问了没有注册的组件也会报错Not found menu item factory by key ‘preview’，请问除了封装还有别的办法吗？

**Comment by laiyameng** [comment]
> 看你报错信息，是重复注册了。
> 
> 不要重复注册，全局注册一次即可

封装成组件，多个页面引用，希望点击菜单时触发的函数是不一样的，传了方法作为参数进去，但是因为只能全局注册一次，导致进另一个页面时，调用的是第一次注册时传的方法

**Comment by Tlionsir** [comment]
关于 《Error: Duplicated key ... 》最简单的解决方案。
![image](https://github.com/wangeditor-team/wangEditor/assets/35832886/2a6590bc-082e-4951-861d-169edb20a306)
