### ISSUE TITLE
wangEditor4 如何实现tab键 有序列表切换

### ISSUE THREAD

**Issue by luxiaodui** [wangeditor-team/wangEditor#4623]
## 问题描述

在使用4版本的时候想实现一个功能发现没办法写,请问有什么好的建议
![image](https://user-images.githubusercontent.com/76798851/181478721-4ba486c8-2ec9-4030-b8e6-0b4e83150077.png)

5版本可以这样写
![image](https://user-images.githubusercontent.com/76798851/181478616-28ba9646-0f54-47bd-bff6-b922374ed3c1.png)

请问4版本如何实现

## wangEditor 版本

3.6.4

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
v4 不再支持开发新功能。

**Comment by luxiaodui** [comment]
> v4 不再支持开发新功能。

不是开发新功能,是想问问4版本有没有实现的办法,或者有没有交流群之类的,我进去问问

**Comment by wangfupeng1988** [comment]
v4 要实现，只能是自己监听键盘事件，自己处理。

官网首页有 qq 群，不过都是用户交流，不负责解答问题

**Comment by luxiaodui** [comment]
> v4 要实现，只能是自己监听键盘事件，自己处理。
> 
> 官网首页有 qq 群，不过都是用户交流，不负责解答问题

我申请qq群了,麻烦通过一下
