### ISSUE TITLE
上传报错时错误提示英文，该如何修改？怎样配置？

### ISSUE THREAD

**Issue by JusticeLiGouDan** [wangeditor-team/wangEditor#4624]
看了文档中的语言配置，但是获取配置后并不包括上传失败相关提示的语言配置，这个应该怎么处理？

**Comment by wangfupeng1988** [comment]
自定义`onFailed` 和 `onError` 即可 https://www.wangeditor.com/v5/menu-config.html#%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0

**Comment by JusticeLiGouDan** [comment]
再问一下。
这个两个方法是可以自定义，但是 并没有阻止  uppy 这个组件的报错，并且已经污染了控制台，可否能修改控制台相关，或者屏蔽错误，自定义错误提示？
然后还想知道是因为什么报错，报错的类型我应该怎么获取？

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/issues/4625 这里回复了
