### ISSUE TITLE
上传图片 onError onFailed  并没有阻止 uppy 这个组件的报错，并且已经污染了控制台

### ISSUE THREAD

**Issue by JusticeLiGouDan** [wangeditor-team/wangEditor#4625]
问一下。
onError，onFailed
这个两个方法是可以自定义，但是 并没有阻止 uppy 这个组件的报错，并且已经污染了控制台，可否能修改控制台相关，或者屏蔽错误，自定义错误提示？
然后再问一下，上传错误时，报错的类型应该获取，我想根据错误类型，进行自定义提示？

**Comment by JusticeLiGouDan** [comment]
比如，限定的文件类型错误，文件大小超过限制之类的

**Comment by wangfupeng1988** [comment]
> onError，onFailed
> 这个两个方法是可以自定义，但是 并没有阻止 uppy 这个组件的报错，并且已经污染了控制台，可否能修改控制台相关，或者屏蔽错误，自定义错误提示？

这个值得优化

**Comment by wangfupeng1988** [comment]
> 然后再问一下，上传错误时，报错的类型应该获取，我想根据错误类型，进行自定义提示？
> 比如，限定的文件类型错误，文件大小超过限制之类的

如果需要这么详细，可以使用自定义上传，文档里有

**Comment by JusticeLiGouDan** [comment]
感谢大佬，以前文档看过了，心想偷一下懒，采用现有的方式处理，所以才想出来的这些问题。
（  已经根据err字符串拦截的方式进行偷懒识别错误 ：)    ）

**Comment by JusticeLiGouDan** [comment]
还有就是，最近阅读你的源码，找到 uppy 这个组件，也阅读了相关的文档，
uppy 这个组件是支持 il8n 配置，是不是可以把 对于uppy 这方面的配置 入口 开放，应该就能解决我这类的问题了，

再次感谢大佬提供的轮子，再次感激

**Comment by wo-de-ping-er** [comment]
> 问一下。 onError，onFailed 这个两个方法是可以自定义，但是 并没有阻止 uppy 这个组件的报错，并且已经污染了控制台，可否能修改控制台相关，或者屏蔽错误，自定义错误提示？ 然后再问一下，上传错误时，报错的类型应该获取，我想根据错误类型，进行自定义提示？

您好，请问一下，污染控制台的错误提示，您是怎么解决的？
