### ISSUE TITLE
插入视频功能存在XSS漏洞

### ISSUE THREAD

**Issue by Maple0-0** [wangeditor-team/wangEditor#4628]
## bug 描述

![2022](https://user-images.githubusercontent.com/88226470/181716925-1c27df83-f038-4495-b1e2-d252fdb43d48.png)

## 你预期的样子是？

过滤用户输入

## 系统和浏览器及版本号

- 操作系统 Windows 10
- 浏览器和版本 chrome

## wangEditor 版本

V5&V4

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://www.wangeditor.com/demo/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
插入视频中使用<iframe>标签，其属性srcdoc及src中可以插入<script>和javascript从而产生XSS漏洞。

**Comment by wangfupeng1988** [comment]
可通过 `checkVideo` 来校验，或通过 `parseVideoSrc`  来转换

https://www.wangeditor.com/v5/menu-config.html#%E8%A7%86%E9%A2%91
