### ISSUE TITLE
如何设置 默认字号、默认行高

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4630]
## 问题描述

如何设置 默认字号、默认行高，
现在 富文本编辑器 默认显示字号是16px，默认字号能否改成其他值？
默认行高 同上

## wangEditor 版本

V5最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/issues/4042 看这里
