### ISSUE TITLE
编辑器内容删除不了

### ISSUE THREAD

**Issue by psy6688** [wangeditor-team/wangEditor#4631]
## 问题描述

输入完文本之后删除不了

## wangEditor 版本
![image](https://user-images.githubusercontent.com/110363458/182058685-e4059ad9-daeb-43c6-959d-550cf73dffef.png)

## 是否查阅了文档 ？

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 新建编辑器
- 步骤二
- 输入内容
- 步骤三
- del 删除  删除不了
- 
![image](https://user-images.githubusercontent.com/110363458/182058803-341b12e1-1a69-4c57-9e93-e1a385f2a1cb.png)

**Comment by wangfupeng1988** [comment]
官网 vue demo 能复现吗？

**Comment by psy6688** [comment]
官网demo 使用没问题 我本地有问题

**Comment by wangfupeng1988** [comment]
那你需要告诉我们复现的步骤，让我们能以**最低成本**复现问题，才能去解决。

**Comment by psy6688** [comment]
我是复制 官网 vue2的demo 
 
只是多加了一个 onChange
  onChange(editor) {
            const editorHtml = editor.getHtml()
            this.$emit('get-html', editorHtml)
        } 
其余没改动

**Comment by liuqh0609** [comment]
麻烦提供一下在线`demo`，我在本地没有复现你的问题:
- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by psy6688** [comment]
控制台 我删除会出现这个警告
![image](https://user-images.githubusercontent.com/110363458/183371452-2c7454a8-1982-44c7-950a-a4ace582088e.png)
装了这个之后 警告没了 但是还是不能删除
![image](https://user-images.githubusercontent.com/110363458/183371570-65738212-4087-4cac-a046-79d59582faab.png)
