### ISSUE TITLE
设置 颜色、字号、字体、行高 不生效的问题

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4632]
## 问题描述

设置 颜色列表、字号列表、字体列表、行高列表 不生效的问题
如下图
![33](https://user-images.githubusercontent.com/39672406/182060344-649a365e-7caa-4a69-ab33-2058cea615dc.png)

## wangEditor 版本

V5最新版本，Windows10，chrome最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
你参考的是哪个文档？

**Comment by zxueliang** [comment]
@wangfupeng1988 
参考的是这个文档：
https://www.wangeditor.com/v5/menu-config.html#%E5%AD%97%E5%8F%B7

**Comment by wangfupeng1988** [comment]
`MENU_CONF` 丢了
