### ISSUE TITLE
富文本编辑如何设置id属性的值

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4633]
## 问题描述

富文本编辑如何设置id属性的值，官方文档只有获取Id的值，没有看到设置id值的方法，能给提供一下吗？因为一个页面可能会有多个编辑器的情况

## wangEditor 版本

V5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
设置 id 的值，直接赋值即可 `editor.id = 'xxx'`

另，如果一个页面有多个编辑器，id 不会冲突的，你可以试试。
