### ISSUE TITLE
vue2中使用v5，一个页面如何创建多个编辑器？

### ISSUE THREAD

**Issue by zznxyn** [wangeditor-team/wangEditor#4634]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
vue2 一个页面如何创建多个 `<div>` ？

**Comment by zznxyn** [comment]
就是使用v5版本，如何在一个vue页面里引入myEditor.vue组件创建多个富文本编辑器
