### ISSUE TITLE
编辑器 默认字体

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4635]
## 问题描述

默认字体目前是 14px，官网demo默认字体是16px，能否一致 都是 16px呢？
如下图：
![33](https://user-images.githubusercontent.com/39672406/182094911-b2d4f435-4e72-4c2d-8d74-56766b859678.png)
这是是咱们编辑器的样式吗？

## wangEditor 版本

V5最新版本
win10，chrome最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
设置默认字号 14px 即可 https://github.com/wangeditor-team/wangEditor/issues/4630
