### ISSUE TITLE
字体大小使用的是px 而复制进来的使用pt 无法回显

### ISSUE THREAD

**Issue by chencheng666** [wangeditor-team/wangEditor#4636]
## 功能描述
字体大小使用的是px 而复制进来的使用pt 无法回显 复制的是wps word的内容
*请输入内容……*
复制的是wps word的内容
## 提炼几个功能点
pt的无法回显到px的内容中
![image](https://user-images.githubusercontent.com/32317552/182098032-f5129f4b-5cc6-49fd-8a04-6f3857f75d3d.png)

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例
钉钉富文本编辑
*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
之前的升级已经解决了这个问题，没来得及回复。

在 demo https://www.wangeditor.com/demo/set-html.html 中测试即可，如下图

<img width="686" alt="image" src="https://user-images.githubusercontent.com/9583120/190305371-655c6fef-3898-4089-8864-0e9dc78e673c.png">

**Comment by chencheng666** [comment]
好的 收到 很赞~


| |
陈成
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年09月15日 ***@***.***> 写道：

之前的升级已经解决了这个问题，没来得及回复。

在 demo https://www.wangeditor.com/demo/set-html.html 中测试即可，如下图

**Comment by 373579070** [comment]
这个把 pt 复制进去 setHtml()，还是变成 px 了，pt 一样还是不支持
