### ISSUE TITLE
parseElemsHtml是否能支持异步？

### ISSUE THREAD

**Issue by fantasy1943** [wangeditor-team/wangEditor#4638]
## 问题描述

*我想在render-elems文件里调用接口，但是试了下conf.renderElem赋值为异步方法就不会渲染节点了，输出都是undefined*

## wangEditor 版本

*最新版*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
第一，renderElem 和 parseElemHtml 是两码事，别搞混了

第二，它们都不支持异步。如果你有异步需求，先自己处理完异步，然后再同步执行它们。
