### ISSUE TITLE
视频元素的体验建议可以跟图片元素保持一致

### ISSUE THREAD

**Issue by lemondreamtobe** [wangeditor-team/wangEditor#4639]
## 问题描述

插入视频元素，无法自如的改变视频元素大小，而且默认自带的auto
在横屏以及竖屏下的体验很差

## wangEditor 版本

V5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

插入视频

![image](https://user-images.githubusercontent.com/22766436/182112864-6326b949-e49b-4030-84d6-ea146302f168.png)

## 期望
希望视频元素的ui操作体验跟图片元素保持一致，能拉动改变大小，动态改变地址等等
![image](https://user-images.githubusercontent.com/22766436/182113131-9a1df109-ce8f-43cb-a7b0-fd9f2f801685.png)

**Comment by wangfupeng1988** [comment]
目前不支持。

待后面再优化吧，当前没太多时间。
