### ISSUE TITLE
parseElemsHtml只能匹配data-w-e-type,不能自定义type属性名

### ISSUE THREAD

**Issue by fantasy1943** [wangeditor-team/wangEditor#4641]
## 问题描述

parseElemsHtml不能匹配card开头的属性,只能匹配data-w-e-type
比如我在parseHtmlConf中配置
const parseHtmlConf = {
  selector: 'span[card-w-e-type="cardJson"]',
  parseElemHtml: parseHtml,
}
在Index.tsx中
 const [html, setHtml] = useState('
\<span card-w-e-type="cardJson"></span>
')
在parseHtml中打日志是不走的，试过换成“data”开头就可以，很奇怪
## wangEditor 版本

*5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
HTML 自定义属性都是 `data-` 开头的，你可以用 `data-card-w-e-type`
