### ISSUE TITLE
getHtml()获取的html，再次setHtml会报错（list 相关）

### ISSUE THREAD

**Issue by zhm84** [wangeditor-team/wangEditor#4645]
## bug 描述
getHtml()获取的html，再次setHtml会报错，且内容不一致；
![image](https://user-images.githubusercontent.com/57031862/182364675-9c4fbac1-d2f4-4eb9-9af5-0b0101fc542b.png)
![image](https://user-images.githubusercontent.com/57031862/182364768-317e30db-d22b-46ba-abcb-da24043e8456.png)

## 你预期的样子是？

不报错，且正确展示；
希望编辑的时候和再次setHtml的时候展示内容一致；

## 系统和浏览器及版本号

- 操作系统：win10
- 浏览器和版本：96.0.4664.45（正式版本） （64 位）

## wangEditor 版本

^5.1.14

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
在编辑器中编辑如下内容
![image](https://user-images.githubusercontent.com/57031862/182364675-9c4fbac1-d2f4-4eb9-9af5-0b0101fc542b.png)
- 步骤二
将步骤一获取的html set回去
![image](https://user-images.githubusercontent.com/57031862/182364768-317e30db-d22b-46ba-abcb-da24043e8456.png)

**Comment by wangfupeng1988** [comment]
wangEditor 目前不支持多级列表。你第一个截图中的多级列表是怎么操作出来的？

**Comment by zhm84** [comment]
> wangEditor 目前不支持多级列表。你第一个截图中的多级列表是怎么操作出来的？

粘贴复制即可；用户的操作是多元的，有很多用户喜欢粘贴复制等操作，导致明明在编辑的时候看到是正常的，等保存之后再次回显就报错了；建议要么编辑的时候就报错，要么回显正常；

第一步：先输入有序列表
![第一步](https://user-images.githubusercontent.com/57031862/182505854-cfd05046-4fac-4c89-9715-4db284f7f795.png)
第二步：粘贴复制后面的序列插入
![第二步](https://user-images.githubusercontent.com/57031862/182505914-ff73f78b-eb60-4c87-843d-3af354431c1e.png)
![第三步2](https://user-images.githubusercontent.com/57031862/182505944-826908a1-e7aa-4130-829b-9c1e205e4b2c.png)

**Comment by wangfupeng1988** [comment]
和 https://github.com/wangeditor-team/wangEditor/issues/4384 一起排查

**Comment by zhm84** [comment]
> 和 #4384 一起排查

这种场景也会报错，麻烦一起排查，测试的时候覆盖一下这种场景。

第一步：如下输入内容
![第一步](https://user-images.githubusercontent.com/57031862/184055903-d77035cb-3c56-4e55-93d6-021ee24c38fe.png)
第二步：选择第二行文本直接复制粘贴覆盖列表
![第二步](https://user-images.githubusercontent.com/57031862/184055960-c0f50aaa-1db8-4534-9414-d96252419a03.png)
![第三步](https://user-images.githubusercontent.com/57031862/184055969-092cf8d2-db94-4964-a1ae-0297a867678a.png)
这种的情况下产生的html回显也会报错
![第四步](https://user-images.githubusercontent.com/57031862/184055999-0596a97f-2181-43cd-9c33-85ad1f93fcca.png)

**Comment by wangfupeng1988** [comment]
@zhm84 感谢反馈。

列表模块我打算重构一下，顺便支持多级列表。等有时间就做。

**Comment by Lonyanzzc** [comment]
@wangfupeng1988 
我这边也有这个问题，我认为这个问题似乎复现频率不算低，也许需要提升一下此bug的优先级，希望您可以对此斟酌一下。

**Comment by wangfupeng1988** [comment]
@Lonyanzzc 感谢反馈。这个绝对是高优问题，等我有时间了会高优处理的。

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本
