### ISSUE TITLE
如果创建 可跳转新链接的 图片富文本

### ISSUE THREAD

**Issue by xiaobo1215** [wangeditor-team/wangEditor#4647]
1: 上传可跳转自定义链接的图片
https://user-images.githubusercontent.com/20086016/182506776-d1d2d60a-8f09-43ad-ad65-02ab4d1ec648.png

用这个创建完的 图片 ，没有被 a标签包裹？

**Comment by wangfupeng1988** [comment]
图片的链接会在 `data-href` 属性中

**Comment by HYhuangyuan** [comment]
那这样生成的富文本是不是需要在使用时候自己添加事件

**Comment by wangfupeng1988** [comment]
是在显示 HTML 时，自行添加事件
