### ISSUE TITLE
可否设置代码块默认语言

### ISSUE THREAD

**Issue by wangyibinwangyi** [wangeditor-team/wangEditor#4650]
## 功能描述

设置代码块点击以后默认显示高亮的语言。我使用的编辑器只是提供python的展示，所以希望让用户每次可以减少一步操作。。。谢谢

## 提炼几个功能点

- 用户点击代码块按钮后，默认显示为列表中的某一种代码，该代码允许指定。

## 原型图

-

## 可参考的案例

-

**Comment by wangfupeng1988** [comment]
这个暂不支持。
