### ISSUE TITLE
关于对编辑器里面的图片自定义编辑的问题和图片自定义上传

### ISSUE THREAD

**Issue by meicy** [wangeditor-team/wangEditor#4651]
## 问题描述

在使用中遇到业务高定制化的需求。
1、需要从自定义的素材库（有数据请求交互的）上传图片 
2、需要自定义图片的高亮以及高亮之后的操作。高亮之后的操作其实无非是对图片的地址更改，图片样式设置，图片的裁剪点位获取（这个可以体现在最后的图片地址上）以及图片的data-href的更改上。

问题：
1、目前通过hoverkeys里面设置images为空之后。去掉了编辑器原本的自定义操作。
2、不知道如何去做，让图片高亮、以及图片的位置信息（已方便展示自定义的高亮框）

## wangEditor 版本

V5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
无需复现

**Comment by wangfupeng1988** [comment]
> 不知道如何去做，让图片高亮、以及图片的位置信息（已方便展示自定义的高亮框）

如果是 css 样式，那定义 css 即可 `.w-e-selected-image-container img { /* todo... */ }`

**Comment by meicy** [comment]
> > 不知道如何去做，让图片高亮、以及图片的位置信息（已方便展示自定义的高亮框）
> 
> 如果是 css 样式，那定义 css 即可 `.w-e-selected-image-container img { /* todo... */ }`

这个样式可以通过这种方式更改，那需要自定义从素材库上传呢？还有自定义图片编辑操作

**Comment by wangfupeng1988** [comment]
> 那需要自定义从素材库上传呢？

看这里 https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD

> 自定义图片编辑操作

这只能自己定义一个 modal 菜单了 https://www.wangeditor.com/v5/development.html#modalmenu
