### ISSUE TITLE
hover弹出框中的工具栏组弹出菜单异常

### ISSUE THREAD

**Issue by WelShen** [wangeditor-team/wangEditor#4652]
## bug 描述

*hover弹出框中的工具栏组，出现只会向上弹出无法向下弹出的情况*

## 你预期的样子是？

*hover弹出框中的工具栏组，在更为靠近顶部的时候，应当向下弹出菜单*

## 系统和浏览器及版本号

-微信游览器
-360急速手机版本2.2.0.100
- 360急速pc 13.5.2020.0

## wangEditor 版本

*^5.1.14*

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*无法在线demo中重现*
![image](https://user-images.githubusercontent.com/105589017/182549735-d46143b1-bde0-4aa6-ab50-a50e8c217f8d.png)

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- vscode安装vue3框架，npm添加wangEditor库
- 使用js创建最简单的模板
- <template>
  <div style="border: 1px solid #ccc">
    <Toolbar style="border-bottom: 1px solid #ccc" :editor="editorRef" :defaultConfig="toolbarConfig" :mode="mode" />
    <Editor style="height: 500px; overflow-y: hidden;" v-model="valueHtml" :defaultConfig="editorConfig" :mode="mode"
      @onCreated="handleCreated" />
  </div>
</template>
<script>
  import '@wangeditor/editor/dist/css/style.css' // 引入 css

  import { onBeforeUnmount, ref, shallowRef, onMounted } from 'vue'
  import { Editor, Toolbar } from '@wangeditor/editor-for-vue'

  export default {
    components: { Editor, Toolbar },
    setup () {
      // 编辑器实例，必须用 shallowRef
      const editorRef = shallowRef()

      // 内容 HTML
      const valueHtml = ref('<p>hello</p>')

      // 模拟 ajax 异步获取内容
      onMounted(() => {
        setTimeout(() => {
          valueHtml.value = '<p>模拟 Ajax 异步设置内容</p>'
        }, 1500)
      })

      const toolbarConfig = {}
      const editorConfig = { placeholder: '请输入内容...' }

      // 组件销毁时，也及时销毁编辑器
      onBeforeUnmount(() => {
        const editor = editorRef.value
        if (editor == null) return
        editor.destroy()
      })

      const handleCreated = (editor) => {
        editorRef.value = editor // 记录 editor 实例，重要！
      }

      return {
        editorRef,
        valueHtml,
        mode: 'default', // 或 'simple'
        toolbarConfig,
        editorConfig,
        handleCreated
      };
    }
  }
</script>

-调试发现问题

**Comment by wangfupeng1988** [comment]
官网 vue3 demo 可以复现吗？

**Comment by WelShen** [comment]
> 官网 vue3 demo 可以复现吗？

可以复现，尤其在使用手机进行调试，我使用了鸿蒙和ios系统的游览器和微信进行了调试，都出现弹出框只向上，不向下弹出的情况，在电脑调试偶尔会出现，复现的情景我无法具体确定

**Comment by wangfupeng1988** [comment]
暂不支持移动端（H5 页面）编辑。
