### ISSUE TITLE
现在只有网络图片和上传图片，之前不是有选择本地图片base64吗？现在怎么设置？

### ISSUE THREAD

**Issue by xiaoxiaoyuanwang** [wangeditor-team/wangEditor#4653]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
看文档，在上传图片配置的地方。
