### ISSUE TITLE
内容设置后，光标位置不对

### ISSUE THREAD

**Issue by caryhgq** [wangeditor-team/wangEditor#4654]
## 问题描述

正常情况下，设置（同步和异步都存在问题）内容后希望光标定位到内容最后，而不是开始位置

## wangEditor 版本

 "@wangeditor/editor": "^5.1.14",
 "@wangeditor/editor-for-vue": "^5.1.12",

## 是否查阅了文档 ？

查看了文档，没有找到解决方法

## 最小成本的复现步骤

官方例子就有问题

[官方例子](https://www.wangeditor.com/demo/get-html.html)
刚进入页面，期望光标在“hello world”最后，而不是开始位置；

![image](https://user-images.githubusercontent.com/6456736/182569384-30287165-3a31-49a3-a617-4fc2590b46f4.png)

[这个例子](https://stackblitz.com/edit/vue3-wangeditor-demo?file=src%2Fcomponents%2FBasicEditor.vue)也是，当内容“模拟 Ajax 异步设置内容”出现时，光标还是位于开始位置

**Comment by wangfupeng1988** [comment]
可以自定义选区位置

```js
import { SlateEditor, SlateTransforms } from '@wangeditor/editor'
// const {  SlateEditor, SlateTransforms } = wangEditor // CDN 方式

const end = SlateEditor.end(editor, [])
SlateTransforms.select(editor, end)
```
