### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'destroy')

### ISSUE THREAD

**Issue by zanderzhg** [wangeditor-team/wangEditor#4655]
## 问题描述

vue3 中切换页面提示 TypeError: Cannot read properties of undefined (reading 'destroy')
```Typescript
onBeforeUnmount(() => {
  const editor = editorRef.value;
  if (editor === null) return;
  editor.destroy();
});
```

## wangEditor 版本

V5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请在下面网站（三选一即可）提供 demo

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/
