### ISSUE TITLE
光标定位问题

### ISSUE THREAD

**Issue by gouding** [wangeditor-team/wangEditor#4656]
现在工具栏是显示在左侧，通过点击编辑区外的按钮展示，但点击后编辑器就失焦了。重新再插入内容只能是开头或结尾。
目前的需求是根据当前所在行然后插入相应内容 ，求解！！！  [感谢]
![image](https://user-images.githubusercontent.com/13016673/182620076-6129207a-0649-43e7-ac7a-134a89dac7ef.png)

**Comment by wangfupeng1988** [comment]
> 根据当前所在行然后插入相应内容 

https://www.wangeditor.com/v5/API.html#restoreselection

**Comment by wangfupeng1988** [comment]
如果你要做这种改动，建议你把文档详细阅读一遍，了解编辑器的每一个 API 。因为你改动较大，这些 API 都有可能用到。

否则，这样一个一个提问，效率太低了。

**Comment by gouding** [comment]
感谢，我刚才重新看了一遍文档，确实是通过restoreselection实现的。

**Comment by gouding** [comment]
> > 根据当前所在行然后插入相应内容
> 
> https://www.wangeditor.com/v5/API.html#restoreselection

你好   再打扰一下
toolbar上的按钮我在点击后，我怎么去监听对应的key呢，我试过自定义事件的方式但key是系统内置的，我这边拿不到。
比如我点`加粗`按钮，我希望能通过一个方法能监听到key为`bold`的的事件被触发了

**Comment by gouding** [comment]
> > 根据当前所在行然后插入相应内容
> 
> https://www.wangeditor.com/v5/API.html#restoreselection

你好   再打扰一下
toolbar上的按钮我在点击后，我怎么去监听对应的key呢，我试过自定义事件的方式但key是系统内置的，我这边拿不到。
比如我点`加粗`按钮，我希望能通过一个方法能监听到key为`bold`的的事件被触发了

**Comment by wangfupeng1988** [comment]
这个不支持。

**Comment by ding2650** [comment]
> 

https://codesandbox.io/s/busy-varahamihira-wpbfcy?file=/src/App.tsx
如果你需要监听ToolBar上的按钮的话，可以尝试下这么做。
