### ISSUE TITLE
工具栏，菜单的hover文案可以修改么？

### ISSUE THREAD

**Issue by lyy199212** [wangeditor-team/wangEditor#4657]
## 问题描述
需要根据需求方的需求，修改菜单hover的文案
<img width="339" alt="image" src="https://user-images.githubusercontent.com/19542683/182774470-e44f168c-781c-4be5-ab4e-c1bd6852ac54.png">

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/issues/4524 这里有

**Comment by lyy199212** [comment]
> #4524 这里有

好的奥 已经曲线救国，哈哈哈哈 谢谢～
