### ISSUE TITLE
复制过来的样式丢失

### ISSUE THREAD

**Issue by meicy** [wangeditor-team/wangEditor#4659]
## bug 描述

从网页或者其它编辑器复制过来的带样式的文本到此编辑器之后样式丢失

## 你预期的样子是？

保留之前的样式

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
"@wangeditor/editor": "^5.1.1",
    "@wangeditor/editor-for-react": "^1.0.4",
## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
比如https://baijiahao.baidu.com/s?id=1740178248000238008 这篇文章，全文复制
标题图片等样式都丢失
![23](https://user-images.githubusercontent.com/8372901/182824186-cadea9f3-3355-4ef9-9808-934dc78a0010.png)

**Comment by wangfupeng1988** [comment]
你预期是：保留之前的样式

那就是：左上交百度 logo 和右上角“百度首页”，复制过去之后，依然再左上角、右上角？网页结构不变，对吧？

**Comment by meicy** [comment]
> 你预期是：保留之前的样式
> 
> 那就是：左上交百度 logo 和右上角“百度首页”，复制过去之后，依然再左上角、右上角？网页结构不变，对吧？

我看过正常的一些编辑器的样式复制都是没有问题对的，除了一些特殊的类似365编辑器这类的，复制过来就会有结构更改，包括图片的不展示，复制过来样式结构的改变等
![1](https://user-images.githubusercontent.com/8372901/182988571-017198b3-6ca6-4d39-b0e4-3d3b8f33207d.png)
![2](https://user-images.githubusercontent.com/8372901/182988703-38335411-3d0d-448e-9e39-a43679a3e841.png)

**Comment by meicy** [comment]
> 你预期是：保留之前的样式
> 
> 那就是：左上交百度 logo 和右上角“百度首页”，复制过去之后，依然再左上角、右上角？网页结构不变，对吧？

同时也提议，可以做一个在线的商用编辑器，这样就可以和这个库直接打通。程序员也会鼓励公司的产品业务使用咋们的在线编辑器

**Comment by wangfupeng1988** [comment]
你上述的那种（三个图片平行排列）的方式，wangEditor5 目前不支持。

v4 应该会支持，因为 V4 对 HTML 结构无要求（因此也会导致很多富文本编辑的诡异 bug）
