### ISSUE TITLE
列表光标错位无法输入内容

### ISSUE THREAD

**Issue by Gerres** [wangeditor-team/wangEditor#4662]
## bug 描述

*vue2环境下使用js的wangeditor出现列表光标错位无法输入bug
描述: 打开编辑器时第一行什么都不输入,直接使用无序列表,然后不输入文字,再回车会切换到下一行,此时再切换到第三行,
然后第三行再插入一个无序列表,此时同样不输入文字,然后按2次退格键, 此时光标会退到第一行,然后再按下回车键,光标就
消失不见,然后再点击文本域获取光标时,会发现光标已经错位,并且无法输入任何文字......*

## 你预期的样子是？

*能够正常使用列表并删除列表*

## 系统和浏览器及版本号

- Windows11
- Chrome - 103.0.5060.134（正式版本） （64 位）

## wangEditor 版本

*v5.1.14*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 描述中已说明如何复现bug, demo案例也可以复现

**Comment by wangfupeng1988** [comment]
已复现，排队修复。

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本
