### ISSUE TITLE
vue2+wangEditor4自定义实现上传图片功能，粘贴图片错误

### ISSUE THREAD

**Issue by wakakakk** [wangeditor-team/wangEditor#4663]
## 问题描述

自定义实现上传图片功能，在粘贴网络上的图片时，出现了一张粘贴后的图片，一张请求上传接口后的图片

## wangEditor 版本

4

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 配置customUploadImg 
- 
![image](https://user-images.githubusercontent.com/66005999/182984185-77f471df-94d7-4105-a1b9-af33ffa33bd0.png)

- 步骤二
- 实现上传图片逻辑
![image](https://user-images.githubusercontent.com/66005999/182984320-24259634-8a32-40da-8b9a-b1da64c41279.png)

- 步骤三
复制网络上的图片到编辑器中，会出现两张
![image](https://user-images.githubusercontent.com/66005999/182984481-77e461f5-6140-4dce-8396-d33c7d5d6fa8.png)

**Comment by wangfupeng1988** [comment]
V5 已经发布几个了。V4 已经不再维护了。

业余维护，时间有限，还请体谅~
