### ISSUE TITLE
选中文字修改会在光标处和选中处同时修改

### ISSUE THREAD

**Issue by moolish** [wangeditor-team/wangEditor#4664]
## bug 描述

输入多行文字，选中部分文字更改，光标在最开始的地方，输入法为中文时，光标会在最开始的地方，输入中文后会变更在选中位置，如果将中文变更为英文则会加在光标处
如果文字中有加粗时，光标位置为最近的加粗字体后，输入中文后会在选中处和光标位置同时增加

## 系统和浏览器及版本号

- macos
- chrome

## wangEditor 版本
 "@wangeditor/editor": "^5.0.1",
 "@wangeditor/editor-for-vue": "^1.0.1",
## demo 能否复现该 bug ？

vue2 demo能够复现

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 输入多行文字 ，并选中部分文字加粗
- 步骤二 选中文字 输入中文

**Comment by wangfupeng1988** [comment]
> "@wangeditor/editor": "^5.0.1",
> "@wangeditor/editor-for-vue": "^1.0.1",

全部升级最新版本试试
