### ISSUE TITLE
表格td自定义扩展属性

### ISSUE THREAD

**Issue by rainbow520lxr** [wangeditor-team/wangEditor#4666]
## 表格td自定义 扩展td的属性td-cell

例如 data-id   { type: table-cell,  id: }， <td  data-id="">  表格节点数据结构添加  { type: table-cell,  id: }

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

**Comment by wangfupeng1988** [comment]
有什么问题？

**Comment by rainbow520lxr** [comment]
无法扩展，有实现案例么，就是内部节点如table-cell自定义扩展属性

**Comment by wangfupeng1988** [comment]
不支持现有 node 属性的扩展
