### ISSUE TITLE
拓展 操作dom给video width:100% 回显宽高自动计算为0

### ISSUE THREAD

**Issue by fjh1610** [wangeditor-team/wangEditor#4668]
## bug 描述

拓展 操作dom给video width:100% 回显宽高自动计算为0

解析富文本内容显示正常 只是在wangEditor 编辑器中显示不出来

## 你预期的样子是？

视频宽度可自适应（百分比）

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

5.14

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

`export default class MyButtonMenu {
    constructor() {
        this.title = "一键排版"
        this.tag = 'button'
    }
    getValue(editor) {
        return editor.getHtml()
    }

    isActive(editor) {
        return false
    }
    isDisabled(editor) {
        return false
    }
    exec(editor, value) {
        let div = document.createElement("div")
        div.innerHTML = value
        let pArr = div.getElementsByTagName("p")
        let vArr = Array.from(div.getElementsByTagName("video"))
        // debugger

        vArr.forEach(video => {

            video.setAttribute("width", "100%")
            // video.setAttribute("height", "100px")
            console.log(video, "vArr");
        })

        Array.from(pArr).forEach(p => {
            let imgArr = Array.from(p.getElementsByTagName("img"))
            if (p.textContent) {

                p.style.cssText = "text-indent:2em;"
                //不支持样式
                // p.style.fontSize = '18px'
                // p.style.margin = '12px 0 15px 0'
                // p.style.letterSpacing = '0px'
                // p.style.fontFamily = '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "WenQuanYi Micro Hei", "Helvetica Neue", "Arial", "sans-serif"'
                const aArr = Array.from(p.getElementsByTagName('a'))
                if (aArr.length > 0) {
                    aArr.forEach(a => {
                        let span = document.createElement("span")
                        span.innerText = a.innerText
                        span.style.color = '#205be6'
                        a.replaceChildren(span)
                    })
                }
            } else if (imgArr.length > 0) {
                p.style.textIndent = "0"
                imgArr.forEach(img => {
                    img.style.width = "100%"
                    img.style.height = "auto"
                })
            }

        })
        editor.setHtml(div.innerHTML)
    }

}`

**Comment by fjh1610** [comment]
vue3 环境下

**Comment by fjh1610** [comment]
![3$ O (2)@@S`_ BK662 Q@L](https://user-images.githubusercontent.com/85326708/183272601-3c4872e7-a63a-425a-a6f7-57d9f2eb7314.jpg)
![XV_310(Q_TMT$6T7G`J26RB](https://user-images.githubusercontent.com/85326708/183272602-0fb86bf6-cbb4-4387-aeb1-102e6c8a0ae4.jpg)
![157D859B-704A-4CCC-823E-4C777D04A86E](https://user-images.githubusercontent.com/85326708/183272627-b2eedafa-3ea2-4d26-b1f2-bbe12c852e27.png)

**Comment by wangfupeng1988** [comment]
> 操作dom给video width:100%

目前视频不支持百分比设置尺寸。

我之前想支持，但开发时遇到一些不好解决的问题（之前有 issue 回复过，忘记哪一条了）就先暂缓了

**Comment by night-peiqi** [comment]
> 

这个还有计划支持吗
