### ISSUE TITLE
自定义插件中嵌套文本框,类似于左边图片,右边文字

### ISSUE THREAD

**Issue by JOJOLIN92** [wangeditor-team/wangEditor#4669]
## 问题描述

请问如何自定义插件中嵌套文本框,类似于左边图片,右边文字输入框是paragraph
![image](https://user-images.githubusercontent.com/110764066/183283923-c27aeb56-6df5-422a-af24-72e4737ea5c0.png)

## wangEditor 版本

"wangeditor": "^4.7.7"

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
https://doodlewind.github.io/slate-doc-cn/walkthroughs/applying-custom-formatting.html
*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 
![image](https://user-images.githubusercontent.com/110764066/183283737-9f2359ee-86a1-4b44-90af-c840b058332e.png)

- 步骤二
- 
![image](https://user-images.githubusercontent.com/110764066/183283766-b8b62dc1-eb68-4061-9361-a616920da5e9.png)

- 步骤三
![image](https://user-images.githubusercontent.com/110764066/183283785-f1c98a50-0a84-4edc-bd92-cfd43372addb.png)

**Comment by wangfupeng1988** [comment]
你先确认一下 wangEditor  的版本。

**Comment by JOJOLIN92** [comment]
> 你先确认一下 wangEditor 的版本。

"name": "@wangeditor/editor",
 "version": "5.1.5",

**Comment by wangfupeng1988** [comment]
看你截图，猜测你不了解 snabbdom `h` 函数中 style 的写法，详细看看文档再来写吧 https://github.com/snabbdom/snabbdom
