### ISSUE TITLE
自定义新元素后回车如何跳出该当前标签

### ISSUE THREAD

**Issue by yuSniper** [wangeditor-team/wangEditor#4670]
## 自定义新元素后回车如何跳出该当前标签

*请输入遇到的问题...*
自定义新元素后输入内容回车换行一直出现重复标签
## wangEditor 版本
最新版本
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/13461661/183296463-fca06eb6-ef5b-4a1b-b518-964f2ab67f9e.png)

**Comment by yuSniper** [comment]
![image](https://user-images.githubusercontent.com/13461661/183296510-d4768abe-059b-47bf-9fc7-f8150951f9b5.png)

**Comment by wangfupeng1988** [comment]
参考 blockquote 对于换行的处理吧 https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/blockquote/plugin.ts#L14
