### ISSUE TITLE
如何给引用标签blockquote添加id或者class

### ISSUE THREAD

**Issue by yuSniper** [wangeditor-team/wangEditor#4671]
## 我想在工具栏中添加 blockquote 的两种引用样式：
例如点击：引用1 ，editor插入\<blockquote class="blockquote-one"\>\</blockquote\>
点击：引用2 ，editor插入\<blockquote class="blockquote-two"\>\</blockquote\>

在插入HTML标签时setHtml() 保留blockquote  的class 属性值 

## wangEditor 版本
最新版本 

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是

**Comment by wangfupeng1988** [comment]
暂不支持自定义 class
