### ISSUE TITLE
自定义内容后的HTML元素id不见了， 是否支持自定义的HTML打标签

### ISSUE THREAD

**Issue by liuyun39** [wangeditor-team/wangEditor#4674]
## 问题描述

*在调用 `editor.setHtml('<p id="test">hello <strong>world</strong></p>')` 设置了内容后， 在页面中查看发现自己打的标记（id）不见了, 见下图： 
![image](https://user-images.githubusercontent.com/74752826/183363463-8866220a-15f3-4c23-b03b-c44b83107514.png)
*

## wangEditor 版本

*v4最新版本*

## 是否查阅了文档 ？
查阅了文档， 没有发现相关介绍

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
在官网上查看按钮： 如下
- 步骤一： 打开该链接 https://www.wangeditor.com/demo/set-html.html
- 步骤二： 输入自定义的id并点击插入内容
- 步骤三：打开浏览器控制台查看dom

**Comment by wangfupeng1988** [comment]
看你截图和 demo 链接，是 v5 不是 v4

**Comment by wangfupeng1988** [comment]
v5 不支持自定义 HTML 属性，包括 id class 等
