### ISSUE TITLE
wangEditor5的toolbar和editor-container现在是默认分开的吗?

### ISSUE THREAD

**Issue by prayjourney** [wangeditor-team/wangEditor#4675]
## 问题描述
wangEditor5的toolbar和editor-container现在是默认分开的吗？
我看到wangEditor5提供的例子，[定义HTML 结构](https://www.wangeditor.com/v5/getting-started.html#%E5%AE%9A%E4%B9%89-html-%E7%BB%93%E6%9E%84)，现在直接是定义两个，一个是toolbar，一个是editor-containter，感觉这样是灵活了，但是不方便啊，有没有像是V4版本的，直接创建一个editor就有一个基本的编辑器了？

## wangEditor 版本
V5.1.4

## 是否查阅了文档 ？
*是*

## 最小成本的复现步骤
- 按照快速开始之中给出的例子，即可。

**Comment by wangfupeng1988** [comment]
这有啥不方便的，多写几行代码而已

**Comment by prayjourney** [comment]
> 这有啥不方便的，多写几行代码而已

好的吧，大佬🥶
