### ISSUE TITLE
请增加emit触发事件的说明

### ISSUE THREAD

**Issue by hauoo** [wangeditor-team/wangEditor#4678]
## 问题描述

使用editor.emit发布事件后，不知道如何接受。已经测试过多种方法。都无效。

## wangEditor 版本

最新的V5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 使用的是VUE2.0环境，在myEditor组件中做原理性的发送
	onChange(editor) { 
			console.log('onChange', editor.getHtml()) 
			
			// console.log(editor.emit)
			editor.emit('hyInsertVideo');
		},
- 在主窗口，做了多种尝试，都收不到事件。尝试1：
						<MyEditor ref="editor1" 
							@hyInsertImage='handleInsertImage'
							@hyInsertVideo='handleInsertVideo'
							></MyEditor> 
- 尝试2
	var events = require('events');
	var eventEmitter = new events.EventEmitter();
	var listner1 = function listner1() {
	   console.log('listner1 executed.');
	}
	eventEmitter.addListener('hyInsertImage', listner1);

	var listner2 = function listner2() {
	   console.log('listner2 executed.');
	}
	eventEmitter.addListener('hyInsertVideo', listner2);
- 尝试3
	var EventEmitter = require('events')

	var ee = new EventEmitter()
	ee.on('hyInsertImage', function (text) {
	  console.log(text)
	  console.log('hyInsertImage...')
	})	
	ee.on('hyInsertVideo', function (text) {
	  console.log(text)
	  console.log('hyInsertVideo...')
	})

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/v5/API.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6

文档说的明白：wangEditor 使用 event-emitter 来做自定义事件。

你直接参考 event-emitter 文档即可

**Comment by hauoo** [comment]
能否给个案例做个参考，实在搞不定。VUE环境下的。谢！！！

**Comment by hauoo** [comment]
收费资源也可以接受

**Comment by wangfupeng1988** [comment]
如果仅是自定义事件的问题，你可以用一个其他的自定义事件 lib ，例如直接使用 event-emitter

**Comment by hauoo** [comment]
感谢回复！wangeditor的老版本好像没有emit这个API。既然已经开发出来了这个功能，我想您也是想让大家多用一用。也就不差一个使用案例的功夫了，对吧？
我现在使用VUE2环境，重新定义了视频与图片菜单，这些都比较顺利，感觉您的软件的确比较好用，不愧于网上的好口碑！
