### ISSUE TITLE
配置了customUpload，截屏到编辑框的时候 自动上传图片发送了

### ISSUE THREAD

**Issue by lyy199212** [wangeditor-team/wangEditor#4679]
## 问题描述

配置了customUpload，截屏到编辑框的时候 自动上传图片发送了，需求是截屏展示在编辑框内

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三
<img width="712" alt="image" src="https://user-images.githubusercontent.com/19542683/183547700-38aeac64-3ea3-4d7e-abaa-d2bc36b44e94.png">

**Comment by wangfupeng1988** [comment]
> 需求是截屏展示在编辑框内

得先上传，才能展示啊

**Comment by lyy199212** [comment]
> 先渲染base64，等发送的时候再上传？ 我看demo是展示的base64的截图呢？

**Comment by wangfupeng1988** [comment]
你可以配置使用 base64 ，文档里有
