### ISSUE TITLE
使用customUpload自定义上传，进度条如何配置

### ISSUE THREAD

**Issue by wangkemin** [wangeditor-team/wangEditor#4680]
## 问题描述

使用customUpload，编辑器自带的进度条消失了，有什么好的方法去设置进度条

## wangEditor 版本

5.1.12

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

`
customUpload: async (file, insertFn) => {
    const formData = new FormData();
    formData.append('file', file);
    request(formData).then((resp) => {
        insertFn(resp.url);
    })
}
`

**Comment by wangfupeng1988** [comment]
参考 https://www.wangeditor.com/v5/API.html#showprogressbar

**Comment by wangkemin** [comment]
> 参考 https://www.wangeditor.com/v5/API.html#showprogressbar

我在customUpload内部拿到的editor对象是null

**Comment by wangfupeng1988** [comment]
> 我在customUpload内部拿到的editor对象是null

你自己查一下吧。

既然都触发 customUpload 了，那肯定是 editor 已经创建了

**Comment by wangkemin** [comment]
> > 我在customUpload内部拿到的editor对象是null
> 
> 你自己查一下吧。
> 
> 既然都触发 customUpload 了，那肯定是 editor 已经创建了

感谢解答，但是参照官网给的例子，拿到的editor对象也是空的，可以看下在线demo
https://codesandbox.io/s/nifty-morse-2yvegm?file=/src/App.js

**Comment by wangfupeng1988** [comment]
这样试试

```js
  const customUploadCallback = useCallback(async (file, insertFn) => {
    console.log(editor);
  }, [editor])

  const toolbarConfig = {};
  const editorConfig = {
    placeholder: "请输入...",
    MENU_CONF: {
      uploadImage: {
        customUpload: customUploadCallback
      }
    }
  };
```

**Comment by QuanHuang** [comment]
遇到了一样的问题，自定义上传方法中拿到的editor始终是null

**Comment by hahaaha** [comment]
@wangkemin 可以看下这个例子里的处理 https://codesandbox.io/s/wandering-dust-re03rm?file=/src/App.js
