### ISSUE TITLE
请问作者是否有多人协同编辑的计划？

### ISSUE THREAD

**Issue by ithanbin** [wangeditor-team/wangEditor#4681]
## 功能描述

*请输入内容……*

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
暂无。

协同编辑，成本较高，但目前没几个用户反馈有这种需求。所以，暂不开发。
