### ISSUE TITLE
如何添加自定义text node属性

### ISSUE THREAD

**Issue by cyh401** [wangeditor-team/wangEditor#4682]
## 问题描述

text node需要添加自定义功能，比如点击按钮插入文本时，需要此文本有一个边框，且该文本可以加粗，加背景等常规功能

## wangEditor 版本

5.1.14

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 希望通过{text:"123",border:true}或者加class这样设置使得实现功能

**Comment by wangfupeng1988** [comment]
你自定义 css 即可，针对编辑器区域内部的 `b` 和 `strong` 标签

**Comment by cyh401** [comment]
不是想修改原本的b标签的样式，而是相当于想要新加一个类似b标签一样的样式类型，给text node添加一个border，对应的文字就会有边框。我试着在text node节点对象上加自定义class，但是好像没得用,这样子{text:"加边框的文字",class:"rich-border"}

**Comment by cyh401** [comment]
或者说有没有insertLink代码看看这里是怎么注册的，我看能不能借鉴

**Comment by cyh401** [comment]
官网文档只有添加无子节点的示例，没有添加有子节点的示例

**Comment by wangfupeng1988** [comment]
你这个需求就比较麻烦了，但也是可以实现的，具体需要参考源码中 [text-style](https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/text-style) 的写法 ，其中：

- [custom-types](https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/text-style/custom-types.ts) 扩展属性值，仅限于 TS 中
- [render-style](https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/text-style/render-style.tsx) 把属性渲染到编辑器
- [style-to-html](https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/text-style/style-to-html.ts) 把属性输出为 HTML
- [parseStyleHtml](https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/text-style/parse-style-html.ts) 解析输入的 HTML

有了以上三个（render-style，style-to-html， parseStyleHtml ）以后，把这三个整理到一个 module 中，参考[这里](https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/text-style/index.ts) （可先忽略其中的 `menus`）

最后通过 `Boot.registerModule(module)` 注册即可，跟这个文档类似 https://www.wangeditor.com/v5/development.html#%E8%A7%A3%E6%9E%90%E6%96%B0%E5%85%83%E7%B4%A0-html-%E5%88%B0%E7%BC%96%E8%BE%91%E5%99%A8

**Comment by cyh401** [comment]
我写了一个文件，不知道是不是这样注册？还有一个问题，"../../utils/dom"这个路径怎么区去呀？
import { VNode, h } from "snabbdom";
import { Boot } from "@wangeditor/editor";
import { Text } from "slate";
import $, { getOuterHTML, getTagName, isPlainText } from "../../utils/dom";

export function renderStyle(node, vnode) {
  console.log(node);
  const { border } = node;
  console.log(vnode);
  let styleVnode = vnode;

  // color bgColor 在另外的菜单

  if (border) {
    styleVnode = <span className="rich-border">{styleVnode}</span>;
  }

  return styleVnode;
}
const renderStyleConf = {
  type: "paragraph", // 新元素 type ，重要！！！
  renderElem: renderStyle,
};

function genStyledHtml(textNode, html) {
  let styledHtml = html;
  const { border } = textNode;
  if (border) styledHtml = `<span className="rich-border">${styledHtml}</span>`;
  return styledHtml;
}

export function styleToHtml(textNode, textHtml) {
  if (!Text.isText(textNode)) return textHtml;

  if (isPlainText(textHtml)) {
    // textHtml 是纯文本，而不是 html tag
    return genStyledHtml(textNode, textHtml);
  }

  // textHtml 是 html tag
  const $text = $(textHtml);
  const tagName = getTagName($text);

  if (tagName === "br") {
    return genStyledHtml(textNode, "<br>");
  }

  let innerHtml = $text.html();
  innerHtml = genStyledHtml(textNode, innerHtml);
  $text.html(innerHtml);
  return getOuterHTML($text);
}

const styleToHtmlConf = {
  type: "paragraph", // 新元素 type ，重要！！！
  renderElem: styleToHtml,
};

function isMatch($text, selector) {
  if ($text.length === 0) return false;

  if ($text[0].matches(selector)) return true;

  if ($text.find(selector).length > 0) return true;

  return false;
}

export function parseStyleHtml(textElem, node, editor) {
  const $text = $(textElem);

  if (!Text.isText(node)) return node;

  const textNode = node;

  // border
  if (isMatch($text, "rich-border")) {
    textNode.border = true;
  }

  return textNode;
}
const parseStyleHtmlConf = {
  type: "paragraph", // 新元素 type ，重要！！！
  renderElem: parseStyleHtml,
};

const module = {
  renderElems: [renderStyleConf ], 
  elemsToHtml: [styleToHtmlConf],
  parseElemsHtml: [parseStyleHtmlConf]
};
Boot.registerModule(module);

**Comment by wangfupeng1988** [comment]
怎么注册，参考给我给出的源码即可
