### ISSUE TITLE
复制内容到编辑器回车会自带缩进

### ISSUE THREAD

**Issue by ranran310** [wangeditor-team/wangEditor#4684]
## bug 描述
![image](https://user-images.githubusercontent.com/75973170/183587557-3c078d6e-5bef-481e-9416-d88655835376.png)
![image](https://user-images.githubusercontent.com/75973170/183587812-b3a0329d-b75e-4549-8c1c-5b565b247d3c.png)

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
只有一个截图。

我该如何复现这个 bug ？

**Comment by ranran310** [comment]
> 只有一个截图。
> 
> 我该如何复现这个bug？

只要复制的文本带着缩进，就会导致换行带缩进，并且再次删除文本有缩进删除不到头
![image](https://user-images.githubusercontent.com/75973170/183603743-58ea185f-3744-4642-a055-d803a873b4c3.png)

**Comment by ranran310** [comment]
如果复制的文本带缩进格式，换行会自带缩进。
如果删除改文本导致删除不到头。
![image](https://user-images.githubusercontent.com/75973170/183604127-eae9df61-8d7b-46bf-9029-88dc06f5ed9b.png)

**Comment by wangfupeng1988** [comment]
你看下，你粘贴的 HTML 具体是什么？通过 customPaste 可以捕获粘贴的 html 内容 https://www.wangeditor.com/v5/editor-config.html#custompaste

注意，不要粘贴太多，重要能复现 bug ，HTML 越简单越好
