### ISSUE TITLE
图片上传服务器返回成功但是前台报错

### ISSUE THREAD

**Issue by Clark2002** [wangeditor-team/wangEditor#4685]
## 问题描述
图片上传服务器返回成功但是前台报错
*请输入遇到的问题...*

## wangEditor 版本
[wangEditor5](https://www.bilibili.com/video/BV1GU4y1q7ob)
*请输入内容……*

## 是否查阅了文档 ？
yes
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤
`<script >
import '@wangeditor/editor/dist/css/style.css' // 引入 css

import { onBeforeUnmount, ref, shallowRef, onMounted } from 'vue'
import { Editor, Toolbar } from '@wangeditor/editor-for-vue'

export default {
    components: { Editor, Toolbar },
    setup() {
        const baseUrl = import.meta.env.VITE_APP_BASE_API;
        // 编辑器实例，必须用 shallowRef
        const editorRef = shallowRef()

        // 内容 HTML
        const valueHtml = ref('<p>hello</p>')

        // 模拟 ajax 异步获取内容
        onMounted(() => {
            setTimeout(() => {
                valueHtml.value = '<p>模拟 Ajax 异步设置内容</p>'
            }, 1500)
        })

        const toolbarConfig = {}
        const editorConfig = { placeholder: '请输入内容...',MENU_CONF: {} }

        // 组件销毁时，也及时销毁编辑器
        onBeforeUnmount(() => {
            const editor = editorRef.value
            if (editor == null) return
            editor.destroy()
        })

        const handleCreated = (editor) => {
            editorRef.value = editor // 记录 editor 实例，重要！
        }
        editorConfig.MENU_CONF['uploadImage'] = {
            server: baseUrl + "/system/oss/upload",
            fieldName: 'file'
        }
        return {
            editorRef,
            valueHtml,
            mode: 'default', // 或 'simple'
            toolbarConfig,
            editorConfig,
            handleCreated
        };
    }
}
</script>

<template>
    <div style="border: 1px solid #ccc">
        <Toolbar style="border-bottom: 1px solid #ccc" :editor="editorRef" :defaultConfig="toolbarConfig"
            :mode="mode" />
        <Editor style="height: 500px; overflow-y: hidden;" v-model="valueHtml" :defaultConfig="editorConfig"
            :mode="mode" @onCreated="handleCreated" />
    </div>
</template>`
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by Clark2002** [comment]
![image](https://user-images.githubusercontent.com/85301636/183616154-6b2310c6-118d-4596-93cd-6f8c2b8c9c4f.png)

**Comment by wangfupeng1988** [comment]
看你截图，返回格式不符合要求，具体看文档 https://www.wangeditor.com/v5/menu-config.html#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%9C%B0%E5%9D%80

如果你无法修改返回格式，可参考文档里的“自定义插入”
