### ISSUE TITLE
两个自定义组件嵌套使用，getHtml获取的模板通过setHtml/dangerouslyInsertHtml更新时只解析出最外层的组件

### ISSUE THREAD

**Issue by Lindom96** [wangeditor-team/wangEditor#4686]
## 问题描述
自定义了两个key组件，嵌套使用，通过菜单能够正常创建组件，内部使用正常；但通过getHtml()获取出html模板后再通过setHtml()更新内容，至解析出第一层的组件。

## wangEditor 版本
```javascript
"@wangeditor/editor": "^5.1.2",
"@wangeditor/editor-for-vue": "^1.0.1",
```

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
通过菜单新建组件，嵌套组件的数据结构及html模板都正常加载
![image](https://user-images.githubusercontent.com/47411585/183614063-54566a79-c1cc-4818-a7ab-874cbdc72a43.png)

- 步骤二
将获取的Html用setHtml更新内容后，只解析出第一层的组件，数据结构也没有内部组件对应的数据结构
![image](https://user-images.githubusercontent.com/47411585/183614816-d506be60-a5c1-455a-9256-dafaf72ea742.png)

## 相关代码
- 父组件```render-elem.js```
![image](https://user-images.githubusercontent.com/47411585/183615987-e1e69eeb-1667-4777-ae10-037752861740.png)
- 父组件```parse-elem-html.js```
![image](https://user-images.githubusercontent.com/47411585/183616345-df3c9fdd-cd90-419c-a465-9ce017b08f24.png)

- 子组件```render-elem.js```
![image](https://user-images.githubusercontent.com/47411585/183616501-8ebe2c63-f2bb-49ed-8fe0-0b8512607a20.png)
- 子组件```parse-elem-html.js```
![image](https://user-images.githubusercontent.com/47411585/183616652-756b67f4-f506-4d25-be05-b7147becccda.png)

**Comment by wangfupeng1988** [comment]
子组件的 parseHtml 函数执行了吗？

如果执行了，最后返回的结果是什么？打印出来看看

**Comment by Lindom96** [comment]
> 子组件的 parseHtml 函数执行了吗？
> 
> 如果执行了，最后返回的结果是什么？打印出来看看
set嵌套的html模板时没有执行子组件的parseHtml，并且父组件parseHtml中的```children```值为[]
![image](https://user-images.githubusercontent.com/47411585/183629876-0462868a-592e-48d7-9d95-6fe21f998d40.png)
通过在父组件```parseHtml.js```内引用子组件的parseHtml方法是可以执行的，打印结果如下
![image](https://user-images.githubusercontent.com/47411585/183630482-e046d7e2-d075-4304-828e-1f1abc61915c.png)
把返回的res设置为父组件parseHtml里的children也不生效

**Comment by wangfupeng1988** [comment]
你能否通过一个最简单的 demo 来复现一下这个问题？越简单越好，不要有任何无关代码。

现在光看截图的代码太多了，不好 debug

**Comment by Lindom96** [comment]
找到问题原因了
父组件```elem-to-html.js```代码如下
```javascript
function imageSingleToHtml(elem) {
  console.log(`Lindom~ToHtml`, { elem })
  const { imgUrl = '' } = imageSingle
  return `<div data-w-e-type="imageSingle" data-w-e-is-void data-w-e-is-inline data-imgUrl="${imgUrl}"><img src="${imgUrl}" /></div>`
}
```
因为```data-w-e-is-void```这个属性导致解析时没有继续子组件，去掉后就能正常解析了
