### ISSUE TITLE
editor-for-vue能否也通过cdn引入

### ISSUE THREAD

**Issue by wuluu** [wangeditor-team/wangEditor#4687]
## 问题
项目上没法使用npm安装依赖，希望能直接在本地引入editor和editor-for-vue

## wangEditor 版本
5.1.1

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
不支持
