### ISSUE TITLE
不聚焦时，菜单栏禁用状态

### ISSUE THREAD

**Issue by lyy199212** [wangeditor-team/wangEditor#4689]
## 问题描述

在没有聚焦的时候，希望可以通过菜单栏进行操作
我看v4是有解决这个问题的，v5还是有这个问题呢
[https://github.com/wangeditor-team/wangEditor/pull/2702](url)
## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
该问题已经记录了 https://github.com/wangeditor-team/wangEditor/issues/4212

**Comment by lyy199212** [comment]
> 该问题已经记录了 #4212

那当前有什么方案可以暂时处理这个问题么？

**Comment by newchen** [comment]
有解决方案嘛? 目前也碰到了这个问题

**Comment by qiuyue11** [comment]
现在有什么方案可以暂时处理这个问题么？ @wangfupeng1988

**Comment by lqw1** [comment]
现在有什么方案可以处理吗？
