### ISSUE TITLE
字体颜色增加16进制的格式

### ISSUE THREAD

**Issue by checkwoodson** [wangeditor-team/wangEditor#4691]
## 功能描述
当前的字体颜色是rgb的方式。
*请输入内容……*
虽然说可以自己配置成16进制，但是如果要把所有的颜色全部加进去感觉又很麻烦， 希望能做个配置项，默认是rgb，可以改成16进制
## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
亦只在toolbarConfig中或者哪里能支持就好了

**Comment by wangfupeng1988** [comment]
rgb 格式有啥问题吗？

**Comment by checkwoodson** [comment]
rgb没有问题，是因为我返回给了后台，然后后台给RichText富文本组件，那边不支持RGB格式，只支持16进制的。

**Comment by wangfupeng1988** [comment]
那你可以让后台自己去把 rgb 转换为 16 进制。

**Comment by Kassell** [comment]
根据我们公司的安卓反馈，安卓不支持style内写rgb的颜色，如果可能建议增加一个配置项支持十六进制和rbg的切换

**Comment by chaozhatian** [comment]
一样 ，也是安卓 不行 ，能不能出一个啊
