### ISSUE TITLE
图片缩放变成100%，底部会出现下拉框

### ISSUE THREAD

**Issue by fantasy1943** [wangeditor-team/wangEditor#4693]
## 问题描述

各位大佬，我试了下https://github.com/wangeditor-team/server这个demo上传图片

，然后把图片缩放变成100%，发现底部会出现下拉框，有什么方法能缩放100%但不出现吗

## wangEditor 版本

*5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

运行上传图片demo,把图片缩放改为100%

**Comment by wangfupeng1988** [comment]
截图看看

**Comment by winsydeny** [comment]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/34545949/184476296-eb488662-daef-42ad-ba3b-fb3302e1bd67.png">
应该是当点击100%后， 编辑器底部会出现横向滚动条！

**Comment by wangfupeng1988** [comment]
我刚发现，该问题已经被记录了 https://github.com/wangeditor-team/wangEditor/issues/4523 

还在排队优化后中
