### ISSUE TITLE
初始进入页面，设置默认值，光标默认文本最前面

### ISSUE THREAD

**Issue by Lzengp** [wangeditor-team/wangEditor#4697]
## 问题描述

初始进入页面，设置默认值，光标默认在文本最前面

## 你预期的样子是？

初始进入页面，光标放在文章末尾的位置，不是文本最前面

## wangEditor 版本

"@wangeditor/editor": "^5.1.14",
"@wangeditor/editor-for-vue": "^1.0.2",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## demo 能否复现该 bug ？
能

中文 demo https://www.wangeditor.com/demo/get-html.html

## 最小成本的复现步骤

- 步骤一 直接进入 https://www.wangeditor.com/demo/get-html.html
- 步骤二 可以观察到光标停在文本最前面
- 步骤三

**Comment by Lzengp** [comment]
已经在[#4083](https://github.com/wangeditor-team/wangEditor/issues/4083)找到方法

待设置完内容之后，执行这个代码

```js
import { SlateEditor } from '@wangeditor/editor'

const endPoint = SlateEditor.end(editor, [])
editor.select(endPoint)
```

**Comment by Lzengp** [comment]
不过为什么不默认设置光标在文档末尾呢，感觉这样挺符合输入习惯的

**Comment by wangfupeng1988** [comment]
如果文档有 1w 字，直接设置在末尾，会导致滚屏，体验不好
