### ISSUE TITLE
已上传成功的视频从数据库读取进行回显失败

### ISSUE THREAD

**Issue by CherishLiuJunping** [wangeditor-team/wangEditor#4698]
## bug 描述

*视频上传成功之后，从数据库读取数据进行回显，回显失败*

*使用官方demo测试效果如下图，video标签消失，source标签在*
![image](https://user-images.githubusercontent.com/19511715/184099204-a2160689-b73d-4c03-b12b-36fccb69ceb5.png)

*本地项目测试效果如下图，video标签及其子标签（节点）全部丢失*
![image](https://user-images.githubusercontent.com/19511715/184098459-bc7ec494-2c1d-4ab2-9675-acad1d1445bc.png)

## 你预期的样子是？

*视频正常回显*

## 系统和浏览器及版本号

- win10
- Chrome Version96.0.4664.45

## wangEditor 版本

*@wangeditor/editor: ^5.1.14,
 @wangeditor/editor-for-vue: ^1.0.2,*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
  打开https://codesandbox.io/s/vue2-wangeditor-demo-forked-4tbd3e?file=/src/components/MyEditor.vue
- 步骤二
 ```
// this.html赋值，例如
this.html = '<p><img src="https://chengduyanfa.obs.cn-east-2.myhuaweicloud.com:443/hg%2Fc248fef689c64271b3bdaeacfdca1385" alt="4286" data-href style /></p><p><br></p><div><video poster controls="true" width="auto" height="auto">&lt;source src="https://chengduyanfa.obs.cn-east-2.myhuaweicloud.com:443/hg%2F11ef390bd82d41ef8ecaed9eba06be73" type="video/mp4"/&gt;</video></div></p>';
```
    
- 步骤三

**Comment by wangfupeng1988** [comment]
参考这个试试 https://github.com/wangeditor-team/server

**Comment by CherishLiuJunping** [comment]
@wangfupeng1988 "参考这个试试 https://github.com/wangeditor-team/server" 这个demo与我所描述的问题不符，这个仓库所提供的demo是视频上传以及上传成功之后的即时回显，这个是没有问题的；我所描述的问题是编辑/查看已保存的包含富文本内容的数据时，从数据库读取记录info, info中包含富文本内容字段,且富文本内容含有图片、视频，图片可正常回显，但视频无法正常回显，将以下html字符串v-model=“info.html”赋值给Editor后，video标签经过Editor处理后丢失了

*Version：
@wangeditor/editor: ^5.1.14,
@wangeditor/editor-for-vue: ^1.0.2,
 "vue": "^2.6.11",*
```
type Info = {
    id: string;
    name: string;
    html: string; // 富文本内容
}
// 富文本内容字段
html： string = '<p><img src="https://chengduyanfa.obs.cn-east-2.myhuaweicloud.com:443/hg%2Fc248fef689c64271b3bdaeacfdca1385" alt="4286" data-href style /></p><p><br></p><div><video poster controls="true" width="auto" height="auto">&lt;source src="https://chengduyanfa.obs.cn-east-2.myhuaweicloud.com:443/hg%2F11ef390bd82d41ef8ecaed9eba06be73" type="video/mp4"/&gt;</video></div></p>';
```

**Comment by wxyscode** [comment]
我和你遇到一样的问题 昨天更新新版本前还可以，应该是他们修复数据回显编辑器自动加入空行这个bug导致的新bug.希望能快一点解决

**Comment by CherishLiuJunping** [comment]
> 我和你遇到一样的问题 昨天更新新版本前还可以，应该是他们修复数据回显编辑器自动加入空行这个bug导致的新bug.希望能快一点解决

同希望

**Comment by CherishLiuJunping** [comment]
> > 我和你遇到一样的问题 昨天更新新版本前还可以，应该是他们修复数据回显编辑器自动加入空行这个bug导致的新bug.希望能快一点解决
> 
> 同希望

刚刚看了一下，上传之后的即时回显也不行了，确实是数据回显自动加入空行了，希望能快一点fix吧

**Comment by wangfupeng1988** [comment]
@CherishLiuJunping 如果是 wangEditor 生成的 HTML，其中的 `<video>` 必须要被 `<div data-w-e-type="video" data-w-e-is-void>...</div>` 包裹着。而我看你发的 HTML 源码中不是这样的。

**Comment by CherishLiuJunping** [comment]
> @CherishLiuJunping 如果是 wangEditor 生成的 HTML，其中的 `<video>` 必须要被 `<div data-w-e-type="video" data-w-e-is-void>...</div>` 包裹着。而我看你发的 HTML 源码中不是这样的，所以 wangEditor 不识别。

v-model=html双向绑定获取到的值没有带有data-w-e-type等属性的div，只有<video>;现在上传之后的即时回显也不行了，确实是数据回显自动加入空行<p><br></p>了

**Comment by CherishLiuJunping** [comment]
> @CherishLiuJunping 如果是 wangEditor 生成的 HTML，其中的 `<video>` 必须要被 `<div data-w-e-type="video" data-w-e-is-void>...</div>` 包裹着。而我看你发的 HTML 源码中不是这样的，所以 wangEditor 不识别。

非常抱歉，标签丢失问题是xss导致的，修改了xss的配置之后视频正常回显，我把xss配置贴出来放到下面，如果有跟我一样碰到相同问题的就可以参考一下，不用来叨扰你了，同时也很感谢耐心回复
```
// 此处进行 xss 攻击过滤
const filterHtml = filterXSS(this.html, {
   stripIgnoreTagBody: ['script'], // 仅去掉指定的不在白名单上的标签
     
   onIgnoreTagAttr(tag: string, name: string, value: any, isWhiteAttr: boolean) {
    // 如果返回一个字符串，则当前属性值将被替换为该字符串
    // 如果不返回任何值，则使用默认的处理方法（删除该属性）
    // 确保属性不丢失
       return value ? `${name}="${value}"` : `${name}`;
   },
   escapeHtml(html: string) {
       return html; // 不做任何处理，默认的代码是html.replace(/</g, "&lt;").replace(/>/g, "&gt;");会导致视频标签或属性丢失
   },
});

```
