### ISSUE TITLE
插件能独立注册

### ISSUE THREAD

**Issue by lancyJD** [wangeditor-team/wangEditor#4699]
## 问题描述
自定义了一个禁用enter按钮事件的插件js   如果一个页面有两个富文本  其中一个禁用了   另外一个也禁用了   Boot 可以实例吗
*请输入遇到的问题...*

## wangEditor 版本
v5

*请输入内容……*
![image](https://user-images.githubusercontent.com/11610702/184280243-10e12de5-c000-41a5-b53e-adcfe77a5c5a.png)

![image](https://user-images.githubusercontent.com/11610702/184280287-9f5e1b19-d935-4cc3-8269-de03a2ea827a.png)

只要有一个注册了 另外一个也注册了。   插件能独立注册吗？
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 只要有一个注册了 另外一个也注册了。 插件能独立注册吗？

暂不支持
