### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by prayjourney** [wangeditor-team/wangEditor#4701]
## bug 描述
在一个模态对话框之中，添加了wangEditorv5，版本是5.1.4，然后报错`Uncaught TypeError: Cannot read properties of null (reading 'length')`，如果将模态对话框显示，放在设置富文本编辑器之前，就会无法弹出模态对话框，如果先弹出，后设置html内容，则可以展示内容，但是仍然报错。editor.setHtml(content); $('#modal').modal();

## 你预期的样子是？
无报错，正常显示，控制台没有其他额外输出，代码的位置，不影响显示情况

## 系统和浏览器及版本号
- 操作系统 ` Win10`: 1909
- 浏览器和版本 `Chrome`: 104.0.5112.81（正式版本） （64 位）

## wangEditor 版本
`wangEditor`: V5.1.4

## demo 能否复现该 bug ？
**不能**

## 最小成本的复现步骤
代码如下，如果把调整到3的下面，就无法弹出模态对话框，如果按照如下的，就能够弹出对话框，但是还是有报错。
```js
    function editRow(id) {
        var rowData = $('#table').bootstrapTable('getRowByUniqueId', id);
        var $updateForm = $('#updateModal form');
        $('input[name=id]', $updateForm).val(rowData.id);
        $('input[name=article]', $updateForm).val(htmlDecode(rowData.articleName));
        $('input[name=titleName]', $updateForm).val(htmlDecode(rowData.titleName));
        $('input[name=productId]', $updateForm).val(rowData.productId);
        $('input[name=productName]', $updateForm).val(htmlDecode(rowData.productName));
        $('#updateModal').modal(); // 1

        let essayContent = rowData.content;  //2
        editorUpdate.setHtml(essayContent); //3
    }
```
![Snipaste_2022-08-12_12-20-59](https://user-images.githubusercontent.com/15311937/184284602-b3a6654b-fce3-446f-b9e8-72130529059f.png)

**Comment by prayjourney** [comment]
另外，发生如上的错误时候，设置的只读模式`readOnly: true`,也是失效的，就能在当前的富文本编辑器里面编辑了

**Comment by wangfupeng1988** [comment]
请提供一个能复现问题的 demo ，以下平台三选一即可

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by prayjourney** [comment]
@wangfupeng1988 ，是这样的，在项目里面，之前使用的是wangEditor4，然后就把富文本，存储在了Mysql数据库里面，后面展示的时候，在后台项目里，直接用wangEditor4展示的，没有什么问题，现在是升级到了wangEditor5，绝大多数的记录在数据库里面的富文本，没有问题，但是有一些有问题，这一部分很少，我后面又使用wangEditor5版本创建了一些文档存储，没有问题，里面包含了a标签，table标签，p标签等，都没有问题，只有这4->5的部分文档有展示的问题，里面有table标签，其他的就没有什么信息了，后面我把存储的文档，贴到这儿一下。

**Comment by wangfupeng1988** [comment]
无论啥情况，我们都需要一个精准的复现步骤
