### ISSUE TITLE
想在uniapp插件市场引入

### ISSUE THREAD

**Issue by blindperson** [wangeditor-team/wangEditor#4702]
## 问题描述
想在uniapp插件市场引入该插件，但是找不到

## wangEditor 版本
any version

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

https://ext.dcloud.net.cn/search?q=wangeditor

- 希望你们可以把你们的插件上传到uniapp插件市场

**Comment by wangfupeng1988** [comment]
wangEditor 暂不支持移动端使用
