### ISSUE TITLE
修改字号时没有变化 ，字号变为默认字号

### ISSUE THREAD

**Issue by zengyuhan503** [wangeditor-team/wangEditor#4703]
## bug 描述
*修改字号时，字号没有变化，并且变为默认字号，且控制台有错误*
```
Unable to preventDefault inside passive event listener invocation.
```

## 你预期的样子是？

*字号变为选择的字号*

## 系统和浏览器及版本号

- 操作系统 ：W11
- 浏览器和版本：谷歌浏览器、版本 104.0.5112.81（正式版本） （64 位）

## wangEditor 版本
* "vue": "^3.0.0",*
* "@wangeditor/editor": "^5.1.14",*
*  "@wangeditor/editor-for-vue": "^5.1.12",*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）
- VUE3.0
- 复制demo，直接使用

**Comment by wangfupeng1988** [comment]
请详细补充复现步骤。
