### ISSUE TITLE
插入html字符串，编辑器无法正常解析格式

### ISSUE THREAD

**Issue by kingll93** [wangeditor-team/wangEditor#4704]
## 问题描述

*插入html字符串，编辑器无法正常解析格式*

## wangEditor 版本

*5.5.1*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

- 步骤一
- 调用setHtml方法插入字符串 edit.vue:58 <div class="js-article" data-v-df804cfc=""><p>文/Ben Give Bankless分析师</p><p>终于，这个时刻到来了。随着Goerli测试网的成功完成，合并的TTD（Terminal Total Difficulty）将为5875000000000000000，预计合并时间在9月15-16日之间。</p><p><img alt="T8kQJ7FGmQEujRbHIa6vSFXO8M21t2ca9OI5iv81.png" src="https://img.jinse.cn/6462905_watermarknone.png" title="6462905"/></p><p>关于合并的好处我们已经讨论够多了，你可能不想再听了，但诸多讨论是有充分理由的。这一事件是<a data-key="eth" class="project">以太坊</a>历史上最重要的催化剂之一，因为它将在多个方面影响网络。</p><p>例如，合并将显著降低以太坊的能源消耗，以缓解批评者对其环境影响的担忧，并使该资产对具有ESG（环境、社会和治理）意识的机构投资者更具吸引力。</p><p>合并还将为协议级别的其他以太坊变更铺平道路，比如区块提议者与构建者的分离。这有助于通过分离区块生产和区块验证来实现MEV提取的民主化，还有EIP-4844提案，这一切将以数量级方式减少rollups交易成本。</p><p>最后，合并将大大增加<a data-key="eth" class="project">ETH</a>资产吸引力。ETH的发行量将减少约90%，可能导致通货紧缩，同时也为质押者提供从其所持资产中获益的能力。</p><p>要想切身参与体验这一重大事件，最明显的办法就是购买ETH，但还有更多你不知道的。对于投资者来说，有无数其他方式可以让他们在风险曲线上获得体验和经验。</p><p>让我们探索<strong>投资者可以利用合并机遇的四种不同收益方式</strong>。</p><h2>1、流动性质押代币</h2><p><strong>例如：LDO、RPL、SWISE</strong></p><p>流动性质押服务是此次合并的最直接受益者，非托管协议可能在转变到PoS后的几个月内出现显著增长。</p><p>流动性质押的价值主张很简单——它允许用户同时完成以下三件事：维护对抵押品的保管，赚取质押奖励，并通过发行流动性质押衍生品（LSD）在DeFi内部部署资产。</p><p>合并将大力加速这些协议的发展，因为合并将通过消除合并前的技术和执行风险来化解质押风险。</p><p>此外，合并全部完成后，加之更明确的提款时间表，也将有助于降低LSD对ETH的交易折扣。Lido的stETH目前估值约为0.963 ETH，但当我在6月写关于Celsius暴雷事件时，回想起当时的stETH脱锚事件，1 stETH约等于0.933 ETH。</p><p>事实是，信标链提款功能在上海网络升级前不得启用，预计将在合并后约6-12个月启用。但合并的规模将降低这种折扣，使用这些协议质让押变得更具吸引力，因为这意味着储户承担的价格风险降低了。</p><p>此外，由于预估质押收益率的增加，流动性质押协议存款可能会增加。今天的信标链验证者只赚取区块奖励。合并后，质押者将能够从MEV获得交易费用和收入。预计这将使质押收益率从目前的约4%大幅提高到6%-12%。</p><p>这些增长驱动应该也会增加流动性质押协议的收入，因为存款、更高的收益率和可能更高的ETH价格（资产收入以ETH计价）将提振它们的收入。</p><p>目前有三种公开交易代币的流动性质押协议：Lido（LDO）、Rocket Pool（RPL）和Stakewise（SWISE）。</p><p>每个代币可在投资组合中扮演不同的角色：</p><p>1）寻求蓝筹股敞口的投资者可能想要看看LDO，因为LDO是信标链最大的实体，占有31.2%的存款份额。Lido在这一细分市场中拥有90.3%的市场份额，在流动性质押领域占有更大份额。该代币目前的交易市值为14.8亿美元，FDV（完全稀释估值）为27亿美元。</p><p>2）以代币为导向的投资者可能会关注Rocket Pool的RPL，这是第二大流动性质押协议，拥有信标链存款1.6%的份额，在流动性质押领域拥有4.5%的份额，市值为46752万美元，FDV为5.193亿美元。RPL在minipool运营商中有一套独特的代币经济学，运营商或通过Roket Pool进行验证的实体需要为每个新的验证器购买价值1.6 ETH的RPL，这将代币需求与RPL的增长联系在一起。这样就将代币的需求与增长联系在了一起。</p><p>3）想要最大化风险并最优化beta币的投资者可以关注下“StakeWise”（SWISE），该代币的交易市值为2666万美元，FDV为1.8945亿美元。虽然该协议仅占信标链和流动性质押存款的0.4%和1.3%的份额，但由于其规模较小和低浮动，它可能是三个中最高的beta币。</p><h2>2、基于事件的DeFi押注</h2><p>购买代币并不是参与合并的唯一途径。精明的市场参与者可以以各种不同的方式利用DeFi进行“叙事交易”，并表达他们针对对不同市场在合并之前、期间和之后会如何反应的观点。</p><p>用户还可以通过在Aave、Compound和Euler等货币市场借入ETH来实现这一目标。为什么？在合并期间，ETH的借款需求可能会有大幅增长，因为投资者将希望积累尽可能多的资产，以便从潜在的基于PoW的以太坊分叉（ETHPOW）中收获“空投”。</p><p>由于这些协议的利率是基于使用情况（即，有多少资产是借来的），借款需求的大幅飙升将导致债权人的存款利率达到难以置信的高水平。Aave V2上ETH的利率曲线在利用率达到70%时开始“扭结”或快速加速。目前该市场的利用率为61.56%，自8月8日以来大幅上涨，这种情况当然有可能发生。</p><p><img alt="JYJW8QwnJsy2b990QWDAxSFJUOv8in04wy5WzXtC.png" src="https://img.jinse.cn/6462909_watermarknone.png" title="6462909"/></p><p>当然，这种策略并非没有风险。在极端情况下，借款需求极高时，将意味着Aave中几乎没有ETH流动性，在借款人还款或更多存款涌入协议之前，债权人可能暂时无法提取资产。</p><p>使用DeFi来表达对合并相关事件观点的第二种方式是使用Voltz Protocol来押注LSD收益率，Voltz Protocol是一种用于利率互换的AMM协议。</p><p>由于合并后的投资回报可能会增加，市场参与者可以使用Voltz通过将ETH作为保证金并购买可变利率stETH或rETH代币来表达这一观点。用户可以利用杠杆放大他们的回报，不过这样做自然会引入相当多的风险，会使他们面临清算的风险。使用任何一种杠杆时都请务必小心！</p><h2>3、收获PoW空投</h2><p>挖矿行业关乎数十亿美元的风险，正如Lucas本周早些时候所写的那样，几乎可以肯定的是，在合并后，将出现一些PoW以太坊实例。众多知名业内人士，如Justin Sun携其交易所Poloniex，已经承诺支持这种硬分叉，并计划上市ETHPOW代币。</p><p>虽然还不清楚这条链是否具有长期可行性，也不清楚ETHPOW会有多大价值，但用户仍然可以通过多种不同方式让自己处于有利位置，以赚取看似必将到来的空投。</p><p>获得空投资格的最简单方法是将ETH存入非托管钱包（Metamask、<a data-key="coinbase" class="project">Coinbase</a> Wallet等）。</p><p>但如果你正在寻找风险更高的机会，还有一种方法是从押注的另一面出发，在货币市场上借入ETH，如果空投的价值大于借入ETH的成本，就可能是有利可图的。不过，这种策略也有相当大的风险。不仅借贷利率可能超过空投的收益，而且如果ETH价格飙升，或其抵押品价值下降，借款人也会被清算。鉴于合并当天出现大规模波动的可能性很高，投资者需要非常谨慎地进行操作。</p><p>投资者可以在不承担任何价格风险的情况下收获空投的另一种方法是，使用永续期货创建一个delta中性ETH头寸。要这样做，用户将购买现货ETH，同时使用CEX或DEX永续期货做空等值的ETH。通过这种方式，用户可以接触ETH，这样他们就可以赚取空投，而不用承担持有该资产带来的价格风险。如果空投的价值超过资金（永续期货头寸持仓成本），这个策略将是有利可图的。</p><p>然而，天下没有免费的午餐。这种策略有很大风险，因为资金（比如借款利率）可能会随着合并方式急剧上升。任何一种像这样的杠杆策略，再加上波动性，都会让用户面临被清算的巨大风险。</p><p>小心行事！</p><h2>4、后续受益者</h2><p>最后，合并后的以太坊将对以太坊经济的其他领域产生变革性影响。</p><p>其中一个受益者是L2，因为向PoS的转变将为可扩展性升级铺平道路（例如EIP-4844），这将通过降低链上存储调用数据的成本，大幅降低终端用户在rollups上的交易费用。通过增加可以在网络上进行交易的用户数量，并解锁创建新的创新dapp的能力，交易费用的减少应该有助于促进L2的应用。</p><p>投资者可以（而且已经开始）通过投资整个L2生态系统来利用这一点，比如L2基础层（OP），或L2原生DeFi项目，如Synthetix（SNX）和GMX，或不同生态系统原生的较小市值项目。不要忘了L2基础设施支持，如Synapse（SYN）和Hop Protocol（HOP）等快速桥接服务。</p><p>合并后将发生变化的另一个领域是MEV。随着区块提议者--构建者分离的实施，MEV的竞争发展动态将发生巨大的变化，这将把区块的生产（决定将哪些交易添加进一个区块中）与区块的验证相分离。</p><p>在MEV堆栈中有许多公开交易的代币项目，可以提供参与这一转变的途径，如Manifold Finance（FOLD）、Rook Protocol（ROOK）和Cow Protocol（COW）。它们仍将成为PoS以太坊的长期受益者。</p><h2>结论：选择适合自己的方式</h2><p>合并正在迅速逼近，有望给以太坊经济带来重大变化，也会伴随着短期的链上混乱。</p><p>最安全的投资方法就是购买ETH。</p><p>但现在已经不像2018年熊市那样了，我们生活在一个DeFi的世界里，投资者可以通过许多其他方法参与合并，无论是在L2还是MEV领域，无论是通过投资/交易流动性质押协议还是合并的长期受益者，或是通过使用DeFi赚取收益或收获ETHPOW空投。</p><p>你将如何参与合并从中获利呢？</p></div> 
- 步骤二
- 编辑器输入框中没有显示图片
- 步骤三
- 将字符串放入html文件中浏览器打开可以正常显示样式及图片

**Comment by wangfupeng1988** [comment]
看下这里的红色文字 https://www.wangeditor.com/v5/content.html#%E8%AE%BE%E7%BD%AE-html
