### ISSUE TITLE
更新最新版本后 编辑器回显内容不显示已经上传的图片和视频

### ISSUE THREAD

**Issue by wxyscode** [wangeditor-team/wangEditor#4705]
## bug 描述更新最新版本后，编辑器回显内容不显示已经上传的图片和视频，未更新前是可以显示的

*请输入内容……*最新版本修复了回显内容编辑器前后自动出现空行的bug，但是导致了图片和视频不能回显的bug，只能回显文本内容

## 你预期的样子是？编辑器回显完整内容，包括文本内容和图片以及视频

*请输入内容……*

## 系统和浏览器及版本号 

- 操作系统
- 浏览器和版本

## wangEditor 版本wangeditor6.13.4

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by Yulingsong** [comment]
请问下咋解决的额，我这也出现这个问题了
