### ISSUE TITLE
上传图片回显后是否可以双击对图片进行操作

### ISSUE THREAD

**Issue by w12qw** [wangeditor-team/wangEditor#4706]
## 问题描述

上传图片回显后是否可以双击对图片进行放大缩小旋转

## wangEditor 版本
"@wangeditor/editor": "^5.1.14",
"@wangeditor/editor-for-vue": "^1.0.2",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
不支持双击。

仅支持拖拽，和相关的菜单

**Comment by w12qw** [comment]
> 
是否支持预览图片功能？类似于tx文档编写后可以预览图片

**Comment by wangfupeng1988** [comment]
暂不支持
