### ISSUE TITLE
请教下大大  SlateTransforms.setNodes 如何添加/删除 一个class

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#4707]
请教下大大  SlateTransforms.setNodes 如何添加/删除 一个class

**Comment by beforeBurning** [comment]
大大您好 我现在有2个需求 
1. 我引入了公式的插件  我需要在公式插件selected状态下添加一些样式 想给他增加一个class  但是我看公式插件他的样式都是用内联样式的形式写入的 这样没有办法二次开发  我尝试把这个库下载下来后直接引入到本地 但是发生了公式渲染2次的问题 不知道是为什么
2. 我引入了链接转换卡片的功能 并且二次开发了这个插件  我想在这个组件点击转换卡片的时候 添加一个loading效果 想使用setNotes方法直接添加一个class 然后加载结束后删除  但是我尝试后发现setNodes好像只能插入内联样式 不能直接插入class 这个也非常的麻烦 请问我应该怎么操作可以插入class

**Comment by wangfupeng1988** [comment]
>  SlateTransforms.setNodes 如何添加/删除 一个class

第一，你得先定义组件模型，让模型去支持 class 这个属性；第二，SlateTransforms.setNodes 来修改模型的属性；
具体可以参考 text-align 或 line-height ，一样的逻辑
