### ISSUE TITLE
自定义节点插入后，节点后面的空白不可选中

### ISSUE THREAD

**Issue by yczkhx** [wangeditor-team/wangEditor#4708]
## 问题描述
注册了一个音频节点，插入后可以正常显示，但是节点后面的部分不可点击和编辑，被迫变成了最后一行
*请输入遇到的问题...*

## wangEditor 版本
5
*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
-

`/*
  定义音频节点类
*/
export type AudioElement = {
  type: 'AudioElement'
  src: string
  children: EmptyText[]
}

/*
  设置音频节点类基本属性
*/
export function withAttachment<T extends IDomEditor>(editor: T) {
  const { isInline, isVoid } = editor;
  const newEditor = editor;

  newEditor.isInline = elem => {
    const type = DomEditor.getNodeType(elem);
    if (type === 'AudioElement') {
      return true;
    } // 针对 type: attachment ，设置为 inline
    return isInline(elem);
  };

  newEditor.isVoid = elem => {
    const type = DomEditor.getNodeType(elem);
    if (type === 'AudioElement') {
      return true;
    } // 针对 type: attachment ，设置为 void
    return isVoid(elem);
  };

  return newEditor; // 返回 newEditor ，重要！！！
}

import { h, VNode } from 'snabbdom';
/**
 * 渲染音频元素到编辑器
 * @param elem 音频元素，即上文的 audio
 * @param children 元素子节点，void 元素可忽略
 * @param editor 编辑器实例
 * @returns vnode 节点（通过 snabbdom.js 的 h 函数生成）
 */
function renderAttachment(elem: SlateElement, children: VNode[] | null, editor: IDomEditor): VNode {
  const newEditor = editor;
  const { src = '' } = elem as AudioElement;

  const iconVnode = h(
    // HTML tag
    'audio',
    // HTML 属性
    {
      props: {
        controls: true,
        src
      }, // HTML 属性，驼峰式写法
      style: {
        width: '100',
        /* 其他... */
      } // HTML style ，驼峰式写法
    }, null
    // img 没有子节点，所以第三个参数不用写
  );
  const attachVnode = h(
    // HTML tag
    'div',
    // HTML 属性、样式、事件
    {
      props: { contentEditable: false }, // HTML 属性，驼峰式写法
      style: { display: 'inline-block' }, // style ，驼峰式写法
    },
    // 子节点
    [ iconVnode ]
  );

  return attachVnode;
}

 type renderConf = {
   type:string,
   renderElem:any
 }
 type htmlConf = {
  type:string,
  elemToHtml:any
}

/*
  设置渲染类基本属性
*/
export const renderElemConf:renderConf = {
  type: 'AudioElement', // 新元素 type ，重要！！！
  renderElem: renderAttachment,
};

/*
  设置音频节点类的输出html函数
*/
function attachmentToHtml(elem: SlateElement, childrenHtml: string): string {
  // 获取元素的数据
  const { src = '' } = elem as AudioElement;

  // 生成 HTML 代码
  const html = `<audio data-w-e-type="AudioElement" data-w-e-is-void data-w-e-is-inline controls src="${src}"></audio>`;

  return html;
}

/*
  设置音频节点类html
*/
export const elemToHtmlConf:htmlConf = {
  type: 'AudioElement', // 新元素的 type ，重要！！！
  elemToHtml: attachmentToHtml,
};`

- 步骤二
- Boot.registerRenderElem(renderElemConf);
Boot.registerElemToHtml(elemToHtmlConf);
- 步骤三
设置了一个button菜单用于点击插入，插入后出现bug
![image](https://user-images.githubusercontent.com/49805134/184329073-6667df8e-3737-46e7-ac6d-e5eacda2d162.png)
红圈内点击没有反应

**Comment by wangfupeng1988** [comment]
你截图的红圈内，那块是哪个组件渲染的？即哪个节点的 renderElem 输出的？

**Comment by yczkhx** [comment]
解决了，忘记注册那个inline的函数了。
不过有了一个新的问题，用inline+void，插入组件后，在这个节点后面打字，英文是正常的，中文就会把这个节点删除

**Comment by wangfupeng1988** [comment]
> 不过有了一个新的问题，用inline+void，插入组件后，在这个节点后面打字，英文是正常的，中文就会把这个节点删除

图片就是 inline + void ，会有这个问题吗？

**Comment by yczkhx** [comment]
图片没有这个问题，但是我这个音频是自定义的，会不会有什么冲突之类的？
我现在必须去掉void才能正常打中文

**Comment by wangfupeng1988** [comment]
那具体我也不太清楚，你可以参考图片的配置，来调试
