### ISSUE TITLE
如何实现编辑器 blur 状态下光标的显示？

### ISSUE THREAD

**Issue by Bald-Guy** [wangeditor-team/wangEditor#4709]
## 问题描述

在移动端自定义的工具栏和工具面板中进行滑动点击等操作（参考示例：腾讯文档、苹果 pages）时，编辑器会失去焦点，同时软键盘收起。
但是为了用户体验，希望用户在工具面板中操作的同时，编辑器的光标显示在最后一次失焦时的位置并且保持闪烁。
看完文档和视频教程，没有找到能够实现这个需求的 API，想请问一下王大大，有没有能在不破坏 wangEditor 的基础上实现这个需求的方案。

## wangEditor 版本

"@wangeditor/editor": "^5.1.14"
"@wangeditor/editor-for-vue": "^5.1.12"

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

功能未实现，尚不可复现，在此提供两张预期的效果图：
![WechatIMG3366](https://user-images.githubusercontent.com/100976053/184331981-fcf54e67-968f-494e-9c11-8cf718782455.png)

![WechatIMG3367](https://user-images.githubusercontent.com/100976053/184332037-cdfcb171-8ee6-49eb-bd4b-d5ac584fd152.png)

**Comment by Bald-Guy** [comment]
已经尝试过的方法：
1.使用 editor.restoreSelection() 会重新弹出键盘，遮挡工具面板；
2.给自定义工具栏上的按钮方法中加入如下代码
```
const end = SlateEditor.end(editorStore.editor, [])
SlateTransforms.select(editorStore.editor, end)
```
光标会以极快的速度显示一下随后消失，代码中用到的好像是Slate的API，我自己不太了解

**Comment by wangfupeng1988** [comment]
第一，wangEditor 目前太支持移动端编辑

第二，编辑器 blur 状态下光标的显示 —— 这个问题正在排队优化中，我目前也没有什么好方案。
