### ISSUE TITLE
请问现在富文本编辑中是不是应该禁止插入链接来防止csrf攻击？

### ISSUE THREAD

**Issue by simon-zhangmuye** [wangeditor-team/wangEditor#4710]
@wangfupeng1988 王老师，请问现在富文本编辑中是不是应该禁止插入链接来防止csrf攻击？

**Comment by wangfupeng1988** [comment]
禁止插入链接？你意思是：直接把链接功能删掉？

**Comment by simon-zhangmuye** [comment]
@wangfupeng1988 我想请问您，在富文本编辑器中允许插入链接是否会导致csrf攻击之类的安全威胁？

**Comment by wangfupeng1988** [comment]
安全威胁当然会有，xss 安全威胁也有的。

富文本编辑器，就无法 100% 完全避免安全威胁。除非你用 `<textarea>`

**Comment by simon-zhangmuye** [comment]
@wangfupeng1988 那么您觉得有没有必要禁止插入link链接？或者禁止那些功能？

**Comment by wangfupeng1988** [comment]
你可以通过菜单配置来禁止这些菜单

然后通过 customPaste 配置，只能粘贴纯文本

这样就可以了

**Comment by simon-zhangmuye** [comment]
@wangfupeng1988 我没有明白您说的意思。你说的安全粘贴是这个吗？
![image](https://user-images.githubusercontent.com/10706610/184779552-0876bb8c-139d-4985-85e9-3f9b3377c3b9.png)

**Comment by simon-zhangmuye** [comment]
@wangfupeng1988 大佬，其实我就想问允许插入链接会不会不安全。我去群里问大家都说没问题。所以想来问问您。或者怎么能够安全的使用富文本编辑器。

**Comment by wangfupeng1988** [comment]
你截图的“粘贴”功能，看着就很安全，没啥隐患啊。

**Comment by wangfupeng1988** [comment]
你可以先测试一下呀，编辑器到底有哪些安全问题？例如这个 https://github.com/wangeditor-team/wangEditor/issues/4628

只要你知道了，那就有解决办法。

你现在问我，我也不知道到底有多少个，安全问题是没有边界的。
