### ISSUE TITLE
图片插入后再插入表格导致图片被覆盖

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#4711]
## bug 描述
先插入一张图片 在图片之后直接插入表格 表格会把图片删除

## 你预期的样子是？
表格应该默认在下方插入

## 系统和浏览器及版本号
- 操作系统 
mac 12.5 (21G72)
- 浏览器和版本
104.0.5112.79（正式版本） (x86_64)

## wangEditor 版本
5.1.14

## demo 能否复现该 bug ？
能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

- 步骤一 插入图片
- 步骤二 插入表格

**Comment by wangfupeng1988** [comment]
已复现

**Comment by wangfupeng1988** [comment]
已修复，请升级最新版 `@wangeditor/editor`
