### ISSUE TITLE
使用wangEditor 时，表情包点击不起作用

### ISSUE THREAD

**Issue by zengyuhan503** [wangeditor-team/wangEditor#4714]
## 问题描述

*使用wangEditor 时，表情包点击不起作用*

## wangEditor 版本

* "@wangeditor/editor-for-vue": "^5.1.12",*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 使用demo

##  报错
* 点击工具类都会出现这个报错*
* index.esm.js?cb23:formatted:30325 Unable to preventDefault inside passive event listener invocation*

## 演示视频

*https://public.skyworthxr.com/files/A90AB6A65AD58424C8DED90B04BAC585.mp4*

**Comment by wangfupeng1988** [comment]
官网 vue demo 可以复现吗？

**Comment by RobinGitHub** [comment]
是不是引入了 import 'default-passive-events' 这个？把这个注释就没有问题了
