### ISSUE TITLE
输入单引号或双引号未转义

### ISSUE THREAD

**Issue by 1zhaoyapeng** [wangeditor-team/wangEditor#4715]
## bug 描述

输入单引号或双引号未转义

## 你预期的样子是？

输入单引号应该是&#39;  而不是''

## 系统和浏览器及版本号

- 操作系统windows
- 浏览器和版本chrome 104.0.5112.81（正式版本） （64 位）

## wangEditor 版本
4.5.2

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
第一，你写的版本是 4.5.2 ，而 demo 是 v5 版本，冲突了。

第二，如果确认是 v5 版本，请详细补充复现的步骤：输入什么文字（截图），输出什么 HTML 

第三，用的什么输入法
