### ISSUE TITLE
vue3下按照官网配置不成功

### ISSUE THREAD

**Issue by imjcoder** [wangeditor-team/wangEditor#4717]
## bug 描述

找不到css样式，并且无法build出来dist目录，官网例子还得自己build？？？希望能提供能运行的例子，谢谢。

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 官网例子还得自己build？？？

什么意思呀，前端项目不得自己 build 吗？哪儿有自动的

**Comment by imjcoder** [comment]
关键是build失败了。。。。。找不到什么东西，你可以下载下来npm run build看看。。。。

**Comment by wangfupeng1988** [comment]
官网 demo 能 build 成功吗？

**Comment by liuqh0609** [comment]
能不能提供一些有效信息？比如你下载的编辑器版本，或者提供有效的代码片段？

**Comment by imjcoder** [comment]
不想麻烦了，换了一个了
