### ISSUE TITLE
如何在编辑框里插入一个不可编辑的内容

### ISSUE THREAD

**Issue by ouweicong** [wangeditor-team/wangEditor#4718]
## 问题描述

*请输入遇到的问题...*
如何在编辑框里插入一个不可编辑的内容，即光标遇到时会跳过该内容，且删除时会整个删除，而不是一个个字删，请问可以实现这个功能吗
## wangEditor 版本
最新
*请输入内容……*

## 是否查阅了文档 ？
查阅了
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
看 [插件](https://www.wangeditor.com/v5/plugins.html) 里：mention，公式，附件 —— 都是你说的形式。

具体实现，参考[文档](https://www.wangeditor.com/v5/development.html)和这些插件的源码吧
