### ISSUE TITLE
将表格复制到富文本框时，只了复制内容，表格格式丢失

### ISSUE THREAD

**Issue by yue-xun** [wangeditor-team/wangEditor#4719]
## bug 描述
将表格复制到富文本框时，只了复制内容，表格格式丢失

## 你预期的样子是？

表格格式不丢失

## 系统和浏览器及版本号

- win10
- Chrome 104.0.5112.81

## wangEditor 版本

*5*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
暂不支持表格样式。无法手动设置，自然就没法粘贴过来。
