### ISSUE TITLE
如何实现点击编辑器外的遮罩层部分，编辑器不消失

### ISSUE THREAD

**Issue by wxyscode** [wangeditor-team/wangEditor#4720]
## 问题描述
需求是点击编辑器外的遮罩层部分，编辑器不消失
*请输入遇到的问题...*
现在的编辑器点击编辑器外的遮罩层部分，编辑器消失
## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
编辑器外的东西，不归我管。
