### ISSUE TITLE
base64上传的图片超过base64LimitSize大小限制，怎样给出前端反馈

### ISSUE THREAD

**Issue by zhl-111** [wangeditor-team/wangEditor#4721]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
超过 base64LimitSize 会触发上传，上传有各种回调函数，这不就是反馈吗
