### ISSUE TITLE
多语言的使用教程

### ISSUE THREAD

**Issue by kunijiwa-8** [wangeditor-team/wangEditor#4722]
文档不够详细

**Comment by wangfupeng1988** [comment]
问题也不够详细。

**Comment by kunijiwa-8** [comment]
vue2中怎么使用这个多语言呢，文档引入不知道在哪里使用，怎么使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月17日(星期三) 上午10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 多语言的使用教程 (Issue #4722)





 
问题也不够详细。

**Comment by wangfupeng1988** [comment]
具体什么功能不会？

如果是切换语言，直接在项目一开始启动时，参照文档引用，切换即可 https://www.wangeditor.com/v5/i18n.html#%E5%88%87%E6%8D%A2%E8%AF%AD%E8%A8%80

**Comment by kunijiwa-8** [comment]
参考引入了，在哪个地方使用不懂，不知道写在哪里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月17日(星期三) 下午3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 多语言的使用教程 (Issue #4722)





 
具体什么功能不会？
 
如果是切换语言，直接在项目一开始启动时，参照文档引用，切换即可 https://www.wangeditor.com/v5/i18n.html#%E5%88%87%E6%8D%A2%E8%AF%AD%E8%A8%80
