### ISSUE TITLE
表格外层虚线点击报错 -无法获取到dom，官方dome此问题可复现。另：可否出一个设置表格宽度的配置，或者使用鼠标拖动宽度

### ISSUE THREAD

**Issue by 18337588370** [wangeditor-team/wangEditor#4723]
## bug 描述
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/32302273/185049129-b24ad0a4-5f52-4655-a5d0-01b896d6624b.png">

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 表格外层虚线点击报错 -无法获取到dom

已知问题 https://github.com/wangeditor-team/wangEditor/issues/4376 ，等待解决

**Comment by wangfupeng1988** [comment]
> 另：可否出一个设置表格宽度的配置，或者使用鼠标拖动宽度 

暂不支持
