### ISSUE TITLE
如何删除已存在的功能？（图片点击 —— 编辑、改变大小等）

### ISSUE THREAD

**Issue by sorakylin** [wangeditor-team/wangEditor#4725]
## 问题描述

如下如所示（官网例），点击图片后弹出的框以及改变大小控件，想要去除的话应该如何做到？

![AGX1 %8TG$Z~9FY(6_8$ET4](https://user-images.githubusercontent.com/38156498/185103711-ac48ad45-7c84-4594-b759-90882602efb5.png)

---

* 上传图片这个功能，点击图片的操作应该是根据开发方业务而定
* 不应该强制指定这样一个控件，因为有可能不需要。比如我只想设置一个详情页、文章页，图片100%是居中展示用，用户能有这么大的自由对图片进行操作就不合理了
* 那么问题来了，没有的功能开发者可以自己加。 这强制给安排上的功能，开发者怎么删？
* 文档中未找到，不知是否可以凭借现有的API解决？如不可以，希望可以提供一个方式 😭

## wangEditor 版本

任意版/最新版

## 是否查阅了文档 ？
查阅了，未找到

## 最小成本的复现步骤

- 上传一张图片
- 点击它

**Comment by newchen** [comment]
+1, 我也碰到了这个问题

**Comment by wangfupeng1988** [comment]
看文档 https://www.wangeditor.com/v5/editor-config.html#hoverbarkeys

**Comment by sorakylin** [comment]
> 看文档 https://www.wangeditor.com/v5/editor-config.html#hoverbarkeys

刚试了，resize控件还是会有的
代码如下，应该是清除掉了image的所有hover效果：
```
editorConfig.hoverbarKeys = {
  'image': {
    // 清空 image 元素的 hoverbar
    menuKeys: [],
  }
}
```

**Comment by wangfupeng1988** [comment]
> resize控件还是会有的

resize 拖拽大小无法去掉。

如果你真的不想要，找到这些 DOM 通过 CSS 隐藏即可

**Comment by Y2zz** [comment]
> > resize控件还是会有的
> 
> resize 拖拽大小无法去掉。
> 
> 如果你真的不想要，找到这些 DOM 通过 CSS 隐藏即可

我认为可以提供一个开关，由开发者决定是否启用该功能
