### ISSUE TITLE
怎么能将默认的<p></P>根节点替换成<span></span>标签？

### ISSUE THREAD

**Issue by 316374157** [wangeditor-team/wangEditor#4727]
## 问题描述

怎么能将默认的`<p></P>`根节点替换成`<span></span>`标签？ p标签默认有样式

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
不支持。

第一层必须是 `<p>` ，然后 `<p>` 内部才能有 `<span>`
