### ISSUE TITLE
重复点击编辑器内容触发onchange事件

### ISSUE THREAD

**Issue by lingyuwai** [wangeditor-team/wangEditor#4729]
## bug 描述

点击编辑器中的内容，会触发编辑器的onChange事件

## 你预期的样子是？

点击编辑器内容未造成内容更新，不应触发onchang事件

## 系统和浏览器及版本号

- 操作系统
- macos
- 浏览器和版本 
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

## wangEditor 版本
5.1.14

*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 任意输入内容
- 步骤二
- 点击输入的内容
- 步骤三
- 控制台会不停的打印编辑器内容

**Comment by wangfupeng1988** [comment]
符合预期。

onChange 触发有两个原因：内容变化 + 选区变化。

你说的应该是选区变化，也会触发 onChange

**Comment by SingleShadow** [comment]
在antd的form表单中，这种无内容变化的onchange会触发这个字段的非空必填校验，因为其他字段的聚焦失焦都没有触发校验，为了保持功能一致性，请问有什么方法可以改写onchange的这种默认行为吗

**Comment by wangfupeng1988** [comment]
> 在antd的form表单中，这种无内容变化的onchange会触发这个字段的非空必填校验，因为其他字段的聚焦失焦都没有触发校验，为了保持功能一致性，请问有什么方法可以改写onchange的这种默认行为吗

可以自己在 onChange 加一个逻辑，每次都获取最新的 `JSON.stringify(editor.chlidren)` ，然后和上一次的对比，看是否 `===` ，来判断内容是否变化。这种字符串对比方式，效率还是比较高的。
