### ISSUE TITLE
菜单点击失效问题 

### ISSUE THREAD

**Issue by GloriaQu** [wangeditor-team/wangEditor#4731]
## bug 描述

有些情况下菜单无法点击，不会生成节点，例如 图片按钮  

## 你预期的样子是？

点击后正常显示弹窗

## 系统和浏览器及版本号

- 操作系统   window
- 浏览器和版本  chrome

## wangEditor 版本

v 4.5.2

## demo 能否复现该 bug ？

偶尔可以

## 在线 demo

无

## 最小成本的复现步骤

我给编辑器配置了  editor.config.focus = false 
据我测试 取消这项配置 菜单问题就会消失 ！！！

**Comment by GloriaQu** [comment]
editor.config.focus = false  不知道这和菜单的事件绑定有什么关联

**Comment by wangfupeng1988** [comment]
v4 版本已经不维护了。

业余维护，精力有限，还请体谅~
