### ISSUE TITLE
增加自定义菜单使用dangerouslyInsertHtml后无法增加自定义属性，建议开放扩展自定义属性

### ISSUE THREAD

**Issue by Gnar-TNT** [wangeditor-team/wangEditor#4732]
## 功能描述

可以为图片、视频、文本或其他元素增加自定义属性,
因为编辑器的内容要到别处处理，而目前的内容不具有任何标识性，不便于针对特殊的内容做处理

###问题截图
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/54994665/185285414-c2f4c0ae-6892-4066-84b2-18148deaacee.png">
![image](https://user-images.githubusercontent.com/54994665/185285482-59ef00c4-91ed-4b8f-8ad2-2ad253f9fef0.png)

**Comment by wangfupeng1988** [comment]
> 可以为图片、视频、文本或其他元素增加自定义属性,

暂不支持
