### ISSUE TITLE
v5版本是否考虑新增135编辑器或者秀米集成插件？

### ISSUE THREAD

**Issue by zhang1024899756** [wangeditor-team/wangEditor#4736]
## 功能描述

v5版本新增135编辑器或者秀米集成插件

## 新增135编辑器或者秀米集成

- 集成135编辑器和秀米
- 编辑的内容回显到wangeditor样式正常
- 反复修改不会出现节点嵌套情况

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
有
https://github.com/font-size/vue-quill-xiumi-135

**Comment by wangfupeng1988** [comment]
暂不考虑。

用的人比较少，且开发成本非常高。

**Comment by zhang1024899756** [comment]
我想尝试下集成该功能，想请作者给一些建议，或者自己的思路，有机会的话我会做成插件形式，希望对wangeditor生态有帮助

**Comment by wangfupeng1988** [comment]
可以通过自定义粘贴来处理 https://www.wangeditor.com/v5/editor-config.html#custompaste

**Comment by NyyCui** [comment]
> 我想尝试下集成该功能，想请作者给一些建议，或者自己的思路，有机会的话我会做成插件形式，希望对wangeditor生态有帮助

大哥，有什么好的解决办法吗👀
