### ISSUE TITLE
关于新增135编辑器或者秀米集成插件

### ISSUE THREAD

**Issue by zhang1024899756** [wangeditor-team/wangEditor#4737]
我想尝试下集成该功能，想请作者给一些建议，或者自己的思路，有机会的话我会做成插件形式，希望对wangeditor生态有帮助

_Originally posted by @zhang1024899756 in https://github.com/wangeditor-team/wangEditor/issues/4736#issuecomment-1220131395_

**Comment by wangfupeng1988** [comment]
看这里 https://github.com/wangeditor-team/wangEditor/issues/4736
