### ISSUE TITLE
editor无法解析特定文本，浏览器报错

### ISSUE THREAD

**Issue by zhaoocean** [wangeditor-team/wangEditor#4738]
## bug 描述

**运用vue3的demo，修改BasicEditor.vue的valueHtml文本内容，无法解析以下文本内容，浏览器报错：**
 const valueHtml = ref('`<font size="4"><b style=""><font face="黑体" style="">项目结果解读：</font></b><span style="font-family: 仿宋;">根据店铺销售额近几月变化</span><span style="font-family: 仿宋;">趋势图，可以看出，近几月店铺销售额呈现下降趋势；而根据</span><span style="font-family: 仿宋;">市场销售额变化</span><span style="font-family: 仿宋;">趋势图，可以看出，行业的销售额</span><span style="font-family: 仿宋;">呈现上升趋势，本店的销售额变化趋势与市场销售额变化趋势不符，</span><span style="font-family: 仿宋;">结合两图可以判断店铺的销售额下降没有受到市场太大的影响，所以不是因为市场因素所导致的店铺销售额下降，而是本身的因素所导致。</span>`')
**浏览器报错截图：**

<img width="761" alt="image" src="https://user-images.githubusercontent.com/18049450/185526505-d0cb62f4-4df9-498e-a396-b6f08530504c.png">

## 你预期的样子是？

可以正常解析文本，不会报错

## 系统和浏览器及版本号

- 操作系统：mac
- 浏览器和版本：谷歌104.0.5112.79

## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

官网vue3版本的demo

## 最小成本的复现步骤

直接用官网vue3版本的demo，替换BasicEditor.vue的valueHtml文本内容即可

**Comment by wangfupeng1988** [comment]
文字要用 `<p>` 来包裹。


另外，wangEditor5 只能识别自己产出的 HTML ，其他 HTML 格式不保证完全解析成功。

**Comment by EazycTee** [comment]
解析错误时，如何捕捉？
