### ISSUE TITLE
请问是否有定制hoverbarKeys的功能，想要实现自定义的hoverbar

### ISSUE THREAD

**Issue by littleCareless** [wangeditor-team/wangEditor#4739]
## 问题描述

想要实现效果如下：
![image](https://user-images.githubusercontent.com/47601009/185527013-1dacb481-5b12-4ec4-8695-2aad6ec338f0.png)

## wangEditor 版本

1.  "@wangeditor/editor": "^5.1.14"
2. "@wangeditor/editor-for-vue": "^5.1.12",

## 是否查阅了文档 ？
我参考了如下文档：
https://www.wangeditor.com/v5/editor-config.html#hoverbarkeys

## 期望：可以传递dom，自定义hoverbar

**Comment by wangfupeng1988** [comment]
第一，你需要先扩展一个组件 https://www.wangeditor.com/v5/development.html

第二，将新组件配置到 hoverbarKeys 中

**Comment by littleCareless** [comment]
> 

看样子并没法实现我上诉的需求啊，buttonMenu、selectMenu、dropPanelMenu、modalMenu 都不能像我上图那样 点击这个组件，直接弹出popup 直接就可以操作。

**Comment by wangfupeng1988** [comment]
能实现的就是如下图所示：自定义菜单 + 配置到某个元素的 hoverbar

![image](https://user-images.githubusercontent.com/9583120/185561787-d807bdf4-86a4-45b3-b118-81714892740e.png)


如果这个也不满足，那就是不支持了。

**Comment by littleCareless** [comment]
> 能实现的就是如下图所示：自定义菜单 + 配置到某个元素的 hoverbar
> 
> ![image](https://user-images.githubusercontent.com/9583120/185561787-d807bdf4-86a4-45b3-b118-81714892740e.png)
> 
> 如果这个也不满足，那就是不支持了。

是的...不支持。总之谢谢回复

**Comment by scaukings** [comment]
这个就是自定义个菜单，然后把菜单的key添加到hoverbarKeys里就可以了。
  例如：
  const editorConfig: Partial<IEditorConfig> = {
    hoverbarKeys: {
      image: {
        menuKeys: ['editImageSize']
      }
    }
  }
editImageSize就是自定义的菜单。
