### ISSUE TITLE
不刷新页面的情况下，可以国际化语言切换吗？

### ISSUE THREAD

**Issue by wm1234566** [wangeditor-team/wangEditor#4741]
## 问题描述

支持不刷新页面的情况下，可以国际化语言切换吗？
如果支持该怎么写呢

我是这样写的

i18nChangeLanguage(Language.language === 'zh' ? 'zh-CN' : 'en')

watch(() => Language.language,

    () => {

        i18nChangeLanguage(Language.language === 'zh' ? 'zh-CN' : 'en')
    }
)

监听语言变化 ，执行官方文档中切换语言的方法
但是，似乎没有切换，也没报错，

## wangEditor 版本

 "@wangeditor/editor": "^5.1.14",
 "@wangeditor/editor-for-vue": "^5.1.12",
 "vue": "^3.2.37",
"vue-i18n": "^9.2.0-beta.40",

## 是否查阅了文档 ？
是

官方文档语言切换如下：

import { i18nChangeLanguage } from '@wangeditor/editor'

// 切换语言 - 'en' 或者 'zh-CN'
i18nChangeLanguage('en')

// 创建编辑器...

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
不支持动态切换语言。

要么刷新页面，要么销毁编辑器然后重建。
