### ISSUE TITLE
关于插入超链接的功能

### ISSUE THREAD

**Issue by wzyMaco** [wangeditor-team/wangEditor#4742]
## 问题描述

*关于插入超链接的功能：在使用超链接时，发现超链接的弹窗不能劫持确定按钮事件，点击确定按钮这个弹窗就被关闭了。
我们想要在确定按钮关闭之前做些逻辑，然后手动关闭弹窗(比如加个next()回调函数)，而不是点击确定按钮后自动关闭弹框。*

## wangEditor 版本

*"@wangeditor/editor": "^5.1.14",
"@wangeditor/editor-for-vue": "^5.1.12",*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
看这里可以满足你的需求吗？ https://www.wangeditor.com/v5/menu-config.html#%E9%93%BE%E6%8E%A5

**Comment by wzyMaco** [comment]
> 看这里可以满足你的需求吗？https://www.wangeditor.com/v5/menu-config.html#%E9%93%BE%E6%8E%A5

目前就是用的这个，但不太满足需求，我们想要校验不通过的时候不关闭弹窗，希望能有回调函数来控制这个关闭弹窗。 源码里面是这样写的，不管校验通没通过都会隐藏弹窗：
<img width="531" alt="企业微信截图_111d2b8a-fafa-4d5d-95f1-ed5506fadd68" src="https://user-images.githubusercontent.com/20431837/185574549-3a32aa3f-9f2d-4a4e-b2ef-dffac6065267.png">

**Comment by wangfupeng1988** [comment]
> 我们想要校验不通过的时候不关闭弹窗

那暂时不支持
