### ISSUE TITLE
vue3 使用v5版本封装组件，一个页面显示两次该组件， 两个实例设置数据，只有最后一个生效

### ISSUE THREAD

**Issue by shenghui-shan** [wangeditor-team/wangEditor#4743]
## bug 描述

*vue3 使用v5版本封装组件，一个页面显示两次该组件， 两个实例设置数据，只有最后一个生效*

## 你预期的样子是？

*两个都生效*

## 系统和浏览器及版本号

- 操作系统
- window 10
- 浏览器和版本
- chrome 103

## wangEditor 版本
"@wangeditor/editor": "5.0.1",
"@wangeditor/editor-for-vue": "^5.1.12",

*请输入内容……*

## demo 能否复现该 bug ？

能

**Comment by liuqh0609** [comment]
没有复现你说的问题，能否提供一个最小复现的demo？或者参考该demo排查一下是否自己代码问题[vue3-demo](https://codesandbox.io/s/magical-keldysh-7fd31i?file=/src/components/Editor.vue)

**Comment by lqc0905** [comment]
你应该在创建一个编辑器，而不是两个编辑器公用一个。
