### ISSUE TITLE
数据传入组件会过滤一部分标签样式

### ISSUE THREAD

**Issue by YXXMMM** [wangeditor-team/wangEditor#4744]
编辑器原有的内容拼上我要加入的样式，传到组件中就会过滤div标签和样式，有没有标签白名单这种的来阻止过滤

**Comment by wangfupeng1988** [comment]
请按照 issue 模板来详细说明问题。

另，请尽量使用专业术语或 API ：如“传到”是具体什么意思，不知道。

**Comment by YXXMMM** [comment]
<p> 活动流程 </p><p><br></p><div><section><section><section style="margin:10px 0;text-align:center;"><section style="display:inline-block;"><section style="display:flex;justify-content:center;align-items:center;flex-direction:column;"><section class="135brush" style="font-size:16px;letter-spacing:1.5px;font-weight:bold;color:#03b16d;"><br><section><section><section style="margin:10px 0;text-align:center;"><section style="display:inline-block;"><section style="display:flex;justify-content:center;align-items:center;flex-direction:column;"><section class="135brush" style="font-size:16px;letter-spacing:1.5px;font-weight:bold;color:#03b16d;"> 活动流程 </section></section><section class="135brush" style="box-shadow:0 -10px 5px -8px rgb(255 196 0);font-size:14px;color:rgb(3, 177, 109,0.2);background-color:#ffffff;margin-top:3px;"> Activity process </section></section></section></section></section><br></section></section></section></section></section></section></div>






传入之后：
 <p> 活动流程 </p><p><br></p><p> 活动流程 </p><p> Activity process <br></p>

**Comment by YXXMMM** [comment]
传入之前：
<p> 活动流程 </p><p><br></p><div><section><section><section style="margin:10px 0;text-align:center;"><section style="display:inline-block;"><section style="display:flex;justify-content:center;align-items:center;flex-direction:column;"><section class="135brush" style="font-size:16px;letter-spacing:1.5px;font-weight:bold;color:#03b16d;"><br><section><section><section style="margin:10px 0;text-align:center;"><section style="display:inline-block;"><section style="display:flex;justify-content:center;align-items:center;flex-direction:column;"><section class="135brush" style="font-size:16px;letter-spacing:1.5px;font-weight:bold;color:#03b16d;"> 活动流程 </section></section><section class="135brush" style="box-shadow:0 -10px 5px -8px rgb(255 196 0);font-size:14px;color:rgb(3, 177, 109,0.2);background-color:#ffffff;margin-top:3px;"> Activity process </section></section></section></section></section><br></section></section></section></section></section></section></div>


传入之后：

 <p> 活动流程 </p><p><br></p><p> 活动流程 </p><p> Activity process <br></p>

**Comment by YXXMMM** [comment]
传入之前：
`<p> 活动流程 </p><p><br></p><div><section><section><section style="margin:10px 0;text-align:center;"><section style="display:inline-block;"><section style="display:flex;justify-content:center;align-items:center;flex-direction:column;"><section class="135brush" style="font-size:16px;letter-spacing:1.5px;font-weight:bold;color:#03b16d;"><br><section><section><section style="margin:10px 0;text-align:center;"><section style="display:inline-block;"><section style="display:flex;justify-content:center;align-items:center;flex-direction:column;"><section class="135brush" style="font-size:16px;letter-spacing:1.5px;font-weight:bold;color:#03b16d;"> 活动流程 </section></section><section class="135brush" style="box-shadow:0 -10px 5px -8px rgb(255 196 0);font-size:14px;color:rgb(3, 177, 109,0.2);background-color:#ffffff;margin-top:3px;"> Activity process </section></section></section></section></section><br></section></section></section></section></section></section></div>`

传入之后：
`<p> 活动流程 </p><p><br></p><p> 活动流程 </p><p> Activity process <br></p>`

**Comment by wangfupeng1988** [comment]
wangEditor 不支持 div 和 section 标签

**Comment by YXXMMM** [comment]
那这个标签能换成什么标签呐

**Comment by wangfupeng1988** [comment]
wangEditor 只能识别它自己生成的 HTML 格式 https://www.wangeditor.com/v5/content.html#%E8%AE%BE%E7%BD%AE-html

其他 HTML 标签和格式，不会保证完全支持

**Comment by YXXMMM** [comment]
那编辑器有转化的功能吗？把代码放进去， wangEditor 生成它自己HTML 格式

**Comment by wangfupeng1988** [comment]
不好转换。

如果能轻松转换，就可以支持了。
