### ISSUE TITLE
ModalForm内使用关闭再打开页面报错

### ISSUE THREAD

**Issue by lppoi** [wangeditor-team/wangEditor#4746]
## 问题描述

在antd pro的 ModalForm中使用 但是关闭modal再打开后页面就报错 **Repeated create toolbar by selector '[object HTMLDivElement]'**
但是页面只有一个toolbar的modal关闭时也有写销毁代码
`this.state.editor.destroy()`
`this.setState({editor:null,feedBackVisit:false})`

## wangEditor 版本

5.1.14

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

尝试重新启动了一个react空项目试了一下好像就正常

**Comment by wangfupeng1988** [comment]
组件销毁时，销毁编辑器了吗？（文档中重点强调过）

**Comment by lppoi** [comment]
有写销毁代码，destory()和state的editor为null 但是再调试器里看editor没有为null只是初始化了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月21日 17:39
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [wangeditor-team/wangEditor] ModalForm内使用关闭再打开页面报错 (Issue #4746)


组件销毁时，销毁编辑器了吗？（文档中重点强调过）

―

**Comment by wangfupeng1988** [comment]
那提供一个简单的 demo 吧

能复现问题即可，不要掺杂其他无关代码

**Comment by lppoi** [comment]
找到原因了，因为antd的Modal加了destroyOnClose关闭销毁元素导致关闭再打开就会报错
https://codesandbox.io/s/romantic-breeze-mpclq4
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月24日 10:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [wangeditor-team/wangEditor] ModalForm内使用关闭再打开页面报错 (Issue #4746)


那提供一个简单的 demo 吧

能复现问题即可，不要掺杂其他无关代码

―

**Comment by apple0407** [comment]
@lppoi 我遇到同样的问题，想请教下你最后是怎么解决的，直接去掉destroyOnClose吗？
另外，我也调试了很久，不太明白为什么destroyOnClose会导致报错，这里面的逻辑是什么
