### ISSUE TITLE
组件渲染的时候会默认获取焦点，我该如何阻止这个默认事件

### ISSUE THREAD

**Issue by CoderHyun** [wangeditor-team/wangEditor#4748]
## 问题描述

组件渲染的时候会默认获取焦点，我该如何阻止这个默认事件

## wangEditor 版本

"@wangeditor/editor": "^5.1.14",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/49948227/185782848-f92a4b80-9175-4a09-9186-4a6a2d2bff6c.png)

- 步骤一
- 使用Editor组件
- 步骤二
- 设置 @onFocus 定义一个方法接受
- 步骤三
- 方法被调用了一次

**Comment by wangfupeng1988** [comment]
增加 autoFocus 配置即可 https://www.wangeditor.com/v5/editor-config.html#autofocus

**Comment by CoderHyun** [comment]
好的，谢谢，找半天没看到，原来就在这🤣
