### ISSUE TITLE
复制内容到编辑器时 复制的内容中如果有2张图片 图片会被重复计算 插入2次一模一样的图片

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#4751]
## bug 描述

复制内容到编辑器时 复制的内容中如果有2张图片 图片会被重复计算 插入2次一模一样的图片

## 你预期的样子是？

插入两张图片

## wangEditor 版本

5.1.14

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤
- 步骤一 在知乎复制一篇文章 文章中有2张图片
- 步骤二 复制到wangEditor后 出现4张图片

**Comment by wangfupeng1988** [comment]
把文章链接提出来吧，然后标明你复制了哪段内容。这样我们才能复现这个 bug 。

**Comment by beforeBurning** [comment]
https://www.zhihu.com/question/561973733/answer/2758323034

请大大参考这篇文章吧
