### ISSUE TITLE
两张图片之间有个空白间隔 是不是<p>p标签导致的?

### ISSUE THREAD

**Issue by INTKILOW** [wangeditor-team/wangEditor#4752]
## bug 描述

# 两个图片有个空白间隔

## 你预期的样子是？

# 两张图片能无缝连接

## 系统和浏览器及版本号

- 操作系统  windows
- 浏览器和版本 版本 104.0.5112.101（正式版本） （64 位）chrome

## wangEditor 版本

wangEditor v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*
无

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 上传图1
- 上传图2
- 中间有个缝隙，不能连一起

**Comment by wangfupeng1988** [comment]
你可以自己改一改 css 样式，覆盖掉当前的样式，把 margin 去掉。如下图

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/9583120/185895789-be5f7395-8ea2-4afe-ae2a-056a2e6fd2f7.png">

**Comment by INTKILOW** [comment]
不好意我说的是垂直方向，不是水平方向

**Comment by INTKILOW** [comment]
> 你可以自己改一改 css 样式，覆盖掉当前的样式，把 margin 去掉。如下图
> 
> <img alt="image" width="1583" src="https://user-images.githubusercontent.com/9583120/185895789-be5f7395-8ea2-4afe-ae2a-056a2e6fd2f7.png">

是垂直方向

**Comment by wangfupeng1988** [comment]
垂直方向，那就是 `<p>` 的样式导致的，也可以通过 css 来修改
