### ISSUE TITLE
点击附件名称 tips 提示的是 查看链接和取消链接

### ISSUE THREAD

**Issue by jingaier** [wangeditor-team/wangEditor#4755]
我自定义一个上传附件，也配置了editor.txt.eventHooks.clickEvents 配的是 查看附件 和取消附件，但是不行
现象：
![82ba6c2ee88f1043b0179b93636e235](https://user-images.githubusercontent.com/22383171/186060010-d82ab833-9a5c-4689-8bf2-895b4c5cb65c.jpg)
部分代码

**Comment by jingaier** [comment]
![b5b30faa2ae2c20bfb1088e7ee1a180](https://user-images.githubusercontent.com/22383171/186060461-4359c68d-b2f1-439f-a472-723501a31f6d.jpg)

**Comment by wangfupeng1988** [comment]
v4 已经不维护了

精力有限，还请体谅
