### ISSUE TITLE
请问未来会增加投票功能吗

### ISSUE THREAD

**Issue by realhuhu** [wangeditor-team/wangEditor#4757]
类似这种
![image](https://user-images.githubusercontent.com/81463123/186099039-c7eb5ed5-a545-4722-af0b-b17696f6a4f1.png)
![image](https://user-images.githubusercontent.com/81463123/186099141-e6d66f40-4424-402f-8d25-f52f1eb4f237.png)

**Comment by wangfupeng1988** [comment]
这个不打算支持
