### ISSUE TITLE
请问怎么支持table合并单元格

### ISSUE THREAD

**Issue by 2530642134** [wangeditor-team/wangEditor#4760]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
暂不支持。

这个功能太复杂了，等有空了再开发，现在精力不够。
