### ISSUE TITLE
在插入html时，部分内容丢失（dangerouslyInsertHtml）

### ISSUE THREAD

**Issue by w453145157** [wangeditor-team/wangEditor#4761]
## 功能描述

*作者您好，我想使用dangerouslyInsertHtml插入一段html，html格式比较随意，我也看了之前提的issue，如果不是使用getHTML获取到的内容，插入可能会有问题。*

## 提炼几个功能点

我现在的想法是，在我项目里重写dangerouslyInsertHtml，这个方法，我看它是在editor实例上挂载的，所以我认为重写是可以的，如下是dangerousInsertHtml的源码
![image](https://user-images.githubusercontent.com/18654990/186355167-6ccb65b9-09d1-4809-9b65-46c8d4055219.png)

如上图所示，PARSE_ELEM_HTML_CONF 这个变量，我是从 ‘@wangeditor/core’引入的，但它一直是空对象，registerModule很明显在之前已经执行过了，这块有点没理解。
是我方式不对么？还是说有什么可以解决我这个问题的办法，辛苦作者大佬解答，实在感谢！

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
> PARSE_ELEM_HTML_CONF 这个变量，我是从 ‘@wangeditor/core’引入的，但它一直是空对象

这个没有暴露出来，所以你获取的是空

**Comment by w453145157** [comment]
谢谢作者回复。所以，重写这个dangerouslyInsertHtml方法不可行吗？

**Comment by w453145157** [comment]
或者说你还有什么解决办法吗？万分感谢大佬回复

**Comment by wangfupeng1988** [comment]
有需要可以重写，但是
- 建议用插件的形式来重写 https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E6%8F%92%E4%BB%B6
- 建议不要再掺杂源码的内容，完全自己实现，否则自己不可控

另外，如果你是考虑粘贴的功能，也可以再看看 customPaste https://www.wangeditor.com/v5/editor-config.html#custompaste
