### ISSUE TITLE
复制粘贴后，getHtml为空

### ISSUE THREAD

**Issue by lyy199212** [wangeditor-team/wangEditor#4764]
## 问题描述
从网页找了一段文案，默认事件的复制粘贴后，用getHtml获取为空；

然后用自定义复制粘贴事件时，editor.dangerouslyInsertHtml(html)后，getHtml还是为空；

## wangEditor 版本

v5.1

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
打印的粘贴的html
![WechatIMG51](https://user-images.githubusercontent.com/19542683/186561029-5f5dfc52-bb9f-41bf-b2e6-6ed96579a625.jpeg)
打印的粘贴的text
![WechatIMG52](https://user-images.githubusercontent.com/19542683/186561042-eb2ea11b-a677-4869-9988-bbfda37c2c47.jpeg)
代码：
![WechatIMG53](https://user-images.githubusercontent.com/19542683/186561191-2fc37838-1f4f-4f18-8fae-a8b68a94d8d4.jpeg)

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
把那段 html 代码贴出来。别截图

**Comment by lyy199212** [comment]
> 把那段 html 代码文本贴出来（别截图）

html: <html>
<body>
<div class="index-module_textWrap_3ygOc index-module_newStyle_lg-fl " style="max-width: 100%; overflow-x: visible; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); margin-top: 24px; font-family: arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="margin-top: 0px !important; margin-right: 0px !important; margin-bottom: 16px; margin-left: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); text-align: justify; visibility: visible;"><span style="max-width: 100%; letter-spacing: 1px; visibility: visible;">《通知》强调，要分区域分条件落实抗高温热害干旱措施，分作物分环节落细稳产增产措施。有灌溉条件的地区，要根据旱情发展形势，落实好深水降温、小水勤灌、流水散热等以水调温关键措施；丘陵岗地、“望天田”、灌区末端等缺乏水源的地区，要通过机械、机井等提水送水，抓住有利时机开展人工增雨，组织社会化专业化服务队集中开展喷施叶面肥、抗旱保水剂等作业；对受灾较重甚至绝收的地块，要适时补种改种红薯、杂粮等晚秋作物，适宜地区的中稻可割茬蓄留再生稻。对高温热害造成结实率下降的中稻，要抓住有限的灌浆时间，科学增施穗粒肥，喷施叶面肥，增强光合作用和灌浆速率，努力增加粒重，弥补结实率下降损失；双季晚稻正处于拔节孕穗期，重点要防范可能发生的伏秋连旱，提前做好抗旱工作预案，提早调度储备水源，适时增施孕穗肥，落实大水孕穗、有水抽穗、寸水促穗、湿润壮粒等水分管理措施，促进生长发育；南方高温区的玉米，要针对水分和养分消耗大的问题，落实“一喷多促”等稳产增产措施。同时，蔬菜、水果、茶叶等作物也要针对高温热害和干旱影响，落实好抗灾减损措施。</span></p><p style="margin: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34);"></p></div><div class="index-module_textWrap_3ygOc index-module_newStyle_lg-fl " style="max-width: 100%; overflow-x: visible; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); margin-top: 24px; font-family: arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="margin: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34);"></p><p style="margin-top: 0px !important; margin-right: 0px !important; margin-bottom: 16px; margin-left: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); text-align: justify;"><span style="max-width: 100%; letter-spacing: 1px;">《通知》要求，要充分发挥农业、水利、气象等专业技术力量作用，科学指导抗御高温热害干旱。农业农村部门要进一步完善抗灾夺丰收的技术指导意见，精细搞好科学抗灾保秋粮指导服务，包省包片工作组和科技小分队要加强工作督促和巡回指导。组织基层干部和农技人员下沉到抗灾减灾一线，带技术带物资蹲点包片，到乡到村到户强化针对性技术指导服务。要发挥农业12316热线电话和三农微信公众号作用，及时解答生产经营主体抗高温热害干旱遇到的技术问题。要指导用好社会化服务补贴资金和种粮农民一次性补贴，支持落实秋粮“一喷多促”等措施，做好抗灾救灾和灾后生产恢复所需物资调剂调运，满足农业生产救灾需要。</span></p></div>
</body>
</html>

**Comment by lyy199212** [comment]
> 把那段 html 代码文本贴出来（别截图）

`html: <html>
<body>
<div class="index-module_textWrap_3ygOc index-module_newStyle_lg-fl " style="max-width: 100%; overflow-x: visible; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); margin-top: 24px; font-family: arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="margin-top: 0px !important; margin-right: 0px !important; margin-bottom: 16px; margin-left: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); text-align: justify; visibility: visible;"><span style="max-width: 100%; letter-spacing: 1px; visibility: visible;">《通知》强调，要分区域分条件落实抗高温热害干旱措施，分作物分环节落细稳产增产措施。有灌溉条件的地区，要根据旱情发展形势，落实好深水降温、小水勤灌、流水散热等以水调温关键措施；丘陵岗地、“望天田”、灌区末端等缺乏水源的地区，要通过机械、机井等提水送水，抓住有利时机开展人工增雨，组织社会化专业化服务队集中开展喷施叶面肥、抗旱保水剂等作业；对受灾较重甚至绝收的地块，要适时补种改种红薯、杂粮等晚秋作物，适宜地区的中稻可割茬蓄留再生稻。对高温热害造成结实率下降的中稻，要抓住有限的灌浆时间，科学增施穗粒肥，喷施叶面肥，增强光合作用和灌浆速率，努力增加粒重，弥补结实率下降损失；双季晚稻正处于拔节孕穗期，重点要防范可能发生的伏秋连旱，提前做好抗旱工作预案，提早调度储备水源，适时增施孕穗肥，落实大水孕穗、有水抽穗、寸水促穗、湿润壮粒等水分管理措施，促进生长发育；南方高温区的玉米，要针对水分和养分消耗大的问题，落实“一喷多促”等稳产增产措施。同时，蔬菜、水果、茶叶等作物也要针对高温热害和干旱影响，落实好抗灾减损措施。</span></p><p style="margin: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34);"></p></div><div class="index-module_textWrap_3ygOc index-module_newStyle_lg-fl " style="max-width: 100%; overflow-x: visible; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); margin-top: 24px; font-family: arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="margin: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34);"></p><p style="margin-top: 0px !important; margin-right: 0px !important; margin-bottom: 16px; margin-left: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); text-align: justify;"><span style="max-width: 100%; letter-spacing: 1px;">《通知》要求，要充分发挥农业、水利、气象等专业技术力量作用，科学指导抗御高温热害干旱。农业农村部门要进一步完善抗灾夺丰收的技术指导意见，精细搞好科学抗灾保秋粮指导服务，包省包片工作组和科技小分队要加强工作督促和巡回指导。组织基层干部和农技人员下沉到抗灾减灾一线，带技术带物资蹲点包片，到乡到村到户强化针对性技术指导服务。要发挥农业12316热线电话和三农微信公众号作用，及时解答生产经营主体抗高温热害干旱遇到的技术问题。要指导用好社会化服务补贴资金和种粮农民一次性补贴，支持落实秋粮“一喷多促”等措施，做好抗灾救灾和灾后生产恢复所需物资调剂调运，满足农业生产救灾需要。</span></p></div>
</body>
</html>`

**Comment by lyy199212** [comment]
> 把那段 html 代码文本贴出来（别截图）

```
html: <html>
<body>
<!--StartFragment--><div class="index-module_textWrap_3ygOc index-module_newStyle_lg-fl " style="max-width: 100%; overflow-x: visible; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); margin-top: 24px; font-family: arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="margin-top: 0px !important; margin-right: 0px !important; margin-bottom: 16px; margin-left: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); text-align: justify; visibility: visible;"><span style="max-width: 100%; letter-spacing: 1px; visibility: visible;">《通知》强调，要分区域分条件落实抗高温热害干旱措施，分作物分环节落细稳产增产措施。有灌溉条件的地区，要根据旱情发展形势，落实好深水降温、小水勤灌、流水散热等以水调温关键措施；丘陵岗地、“望天田”、灌区末端等缺乏水源的地区，要通过机械、机井等提水送水，抓住有利时机开展人工增雨，组织社会化专业化服务队集中开展喷施叶面肥、抗旱保水剂等作业；对受灾较重甚至绝收的地块，要适时补种改种红薯、杂粮等晚秋作物，适宜地区的中稻可割茬蓄留再生稻。对高温热害造成结实率下降的中稻，要抓住有限的灌浆时间，科学增施穗粒肥，喷施叶面肥，增强光合作用和灌浆速率，努力增加粒重，弥补结实率下降损失；双季晚稻正处于拔节孕穗期，重点要防范可能发生的伏秋连旱，提前做好抗旱工作预案，提早调度储备水源，适时增施孕穗肥，落实大水孕穗、有水抽穗、寸水促穗、湿润壮粒等水分管理措施，促进生长发育；南方高温区的玉米，要针对水分和养分消耗大的问题，落实“一喷多促”等稳产增产措施。同时，蔬菜、水果、茶叶等作物也要针对高温热害和干旱影响，落实好抗灾减损措施。</span></p><p style="margin: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34);"></p></div><div class="index-module_textWrap_3ygOc index-module_newStyle_lg-fl " style="max-width: 100%; overflow-x: visible; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); margin-top: 24px; font-family: arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="margin: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34);"></p><p style="margin-top: 0px !important; margin-right: 0px !important; margin-bottom: 16px; margin-left: 0px !important; padding: 0px !important; overflow-y: auto; max-width: 100%; font-size: 18px; line-height: 30px; color: rgb(34, 34, 34); text-align: justify;"><span style="max-width: 100%; letter-spacing: 1px;">《通知》要求，要充分发挥农业、水利、气象等专业技术力量作用，科学指导抗御高温热害干旱。农业农村部门要进一步完善抗灾夺丰收的技术指导意见，精细搞好科学抗灾保秋粮指导服务，包省包片工作组和科技小分队要加强工作督促和巡回指导。组织基层干部和农技人员下沉到抗灾减灾一线，带技术带物资蹲点包片，到乡到村到户强化针对性技术指导服务。要发挥农业12316热线电话和三农微信公众号作用，及时解答生产经营主体抗高温热害干旱遇到的技术问题。要指导用好社会化服务补贴资金和种粮农民一次性补贴，支持落实秋粮“一喷多促”等措施，做好抗灾救灾和灾后生产恢复所需物资调剂调运，满足农业生产救灾需要。</span></p></div><!--EndFragment-->
</body>
</html>
```

**Comment by wangfupeng1988** [comment]
你用 `editor.dangerouslyInsertHtml(html)` 插入这段 html ，看看可以吗？
我这边试着是可以的，用官网 demo

**Comment by lyy199212** [comment]
> 你用 `editor.dangerouslyInsertHtml(html)` 插入这段 html ，看看可以吗？ 我这边试着是可以的，用官网 demo

在编辑框内部渲染是正常的，可是当我用getHtml获取的时候 获取到的为空呢
![WechatIMG54](https://user-images.githubusercontent.com/19542683/186634291-41f3002b-45d7-4fff-9feb-0b74b678cc04.jpeg)

**Comment by wangfupeng1988** [comment]
你确定是 getHtml() 是空，不是 editor 是 undefined  ？

**Comment by lyy199212** [comment]
> 你确定是 getHtml() 是空，不是 editor 是 undefined ？

不是呀 我把html的div标签换成span就可以了 所以不知道是哪里有问题呢

**Comment by wangfupeng1988** [comment]
我在官网 demo 试着，执行 `editor.dangerouslyInsertHtml(html)` 插入你的 HTML 代码，然后再 `editor.getHtml()` 是可以获取的。

你可以去试试。

**Comment by lyy199212** [comment]
> 我在官网 demo 试着，执行 `editor.dangerouslyInsertHtml(html)` 插入你的 HTML 代码，然后再 `editor.getHtml()` 是可以获取的。
> 
> 你可以去试试。

我刚试了下，确实官网是没问题的；然后我发现有区别的地方是编辑器初始化的时候我做了一个registerElemToHtml的初始化；
因为默认的<p><br></p>会产生空行，所以我做了自定义设置；
<img width="789" alt="iShot_2022-08-26_13 33 04" src="https://user-images.githubusercontent.com/19542683/186829352-11e08429-781e-4f0a-a2b3-6dff97f3010e.png">

**Comment by wangfupeng1988** [comment]
你先删掉这个自定义设置吧，先跑通了再说。

**Comment by lyy199212** [comment]
> 你先删掉这个自定义设置吧，先跑通了再说。

我一两个月之前用的时候，遇到因为这个默认的<p></br></p>会有空行，所以我设置了那个html为空就好了；我前几天更新了版本，发现这个问题已经没了，刚好这个设置可以删掉～
感谢大佬～
