### ISSUE TITLE
在内网环境使用wangEditor时报错，window.wangEditor not defined

### ISSUE THREAD

**Issue by snsgsg** [wangeditor-team/wangEditor#4766]
开发者您好！

我在能联网的电脑 A 上使用wangEditor一切正常，在把代码部署到不能连接外网的电脑 B 上后，打开页面发现富文本框无法显示，console 里报错如下图：

![报错信息](https://user-images.githubusercontent.com/16870307/186567724-0edc0dfb-b8db-4554-930e-5c94be439705.jpeg)

报错断点如下图，在实例化window.wangEditor时出错：

![报错断点](https://user-images.githubusercontent.com/16870307/186567893-5d857f93-985e-40cc-80c7-f724b0aa906d.jpeg)

请问有什么办法 在不能通过npm下载的情况下，在不能联网的电脑 B 上正常使用wangEditor吗？

非常感谢！

**Comment by snsgsg** [comment]
在第一张图里可以看到 window 对象没有挂载上 wangEditor

**Comment by wangfupeng1988** [comment]
> 不能联网的电脑 B

那得看这个页面的 wangeditor.js 是不是需要通过网络下载呀。否则，下载不到 js 文件，那自然没有 window.wangEditor

**Comment by snsgsg** [comment]
> 那得看这个页面的 wangeditor.js 是不是需要通过网络下载呀。否则，下载不到 js 文件，那自然没有 window.wangEditor

这个wangEditor.js，指的是textEditorIndex.js，还是另一个文件？我能不能手动把它下载下来？

**Comment by wangfupeng1988** [comment]
就是用 CDN 方式引入的 js 文件啊 https://www.wangeditor.com/v5/installation.html#cdn
