### ISSUE TITLE
请问下迭代更新的计划

### ISSUE THREAD

**Issue by RonkyTang** [wangeditor-team/wangEditor#4767]
## 问题描述

看到整个社区还是发现了不少Bug和待优化的点， 想知道作者是如何安排， 下一步迭代计划是什么样， 需要哪些人帮着WangEditor做哪些事，众人拾柴火焰高的精神吧。

**Comment by RonkyTang** [comment]
> 你对哪个 issue 感兴趣？欢迎主动参与进来

我也是使用者之一, 目前对:https://github.com/wangeditor-team/wangEditor/issues/4716
比较感兴趣, 可以指点一下, 我来操作

**Comment by wangfupeng1988** [comment]
其实没啥可指点的

第一，你要满足这些条件 https://github.com/wangeditor-team/wangEditor/blob/master/docs/join.md#%E5%8A%A0%E5%85%A5%E6%9D%A1%E4%BB%B6

第二，大概了解一下当前的所有源码结果。

然后就可以开始做了
