### ISSUE TITLE
您好，V5版本组件设置H1,表情等功能失效报错，可能是组件和其他组件有兼容性的问题导致

### ISSUE THREAD

**Issue by lichao7314** [wangeditor-team/wangEditor#4768]
![image](https://user-images.githubusercontent.com/10704184/186801469-3b350d55-8644-4179-9fb9-6a912d954683.png)
 我重新新建一个项目使用V5版本组件是可以使用全部功能的，但是我将V5组件引入到项目中却发现组件部分功能失效！无法解决，

在项目中使用V4的版本没有问题，V5的版本无法使用。

提供BUG重现地址（服务器带宽小，首次加载可能慢，见谅）
http://wl.yzjinfo.com/  登录账号 test 密码123123 业务管理/新闻管理

在功能业务管理/新闻管理首页使用的是V5版本编辑器（出现部分功能失效），新建弹出框中用的是V4版本编辑器（可正常使用）
![image](https://user-images.githubusercontent.com/10704184/186802201-42f416e0-da56-4cf5-aef7-83bb14a1dfcc.png)

**Comment by wangfupeng1988** [comment]
官网 demo 能否复现这个问题？如能，请描述复现步骤。

如不能，请提供一个简单的在线 demo 来复现这个问题，以下三选一即可

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/
