### ISSUE TITLE
Vue3的demo复制excel表格内容显示xxx,

### ISSUE THREAD

**Issue by Wujinbo666** [wangeditor-team/wangEditor#4769]
## bug 描述

*Vue3的demo复制excel表格内容显示xxx,*

## 你预期的样子是？

*像vue2的demo一样可以复制表格*

## 系统和浏览器及版本号

- win10
- chrome 版本 101.0.4951.54（正式版本）

## wangEditor 版本

*wangEditor vue3demo*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
看看代码，把其中的 `customPaste` 删掉即可
