### ISSUE TITLE
是否支持json content直接转换成html

### ISSUE THREAD

**Issue by yolocgt** [wangeditor-team/wangEditor#4770]
## 问题描述

*请问大大是否提供了content转换成html的方法。 目前项目中需要将content转为html后进行截图，但需要经过创建editor设置 JSON后才能获取到解析后的html，想有没有提供方法能够直接content转html，而不经过editor这层的渲染呢*

## wangEditor 版本

*5.0.1*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
那你直接存储 HTML 即可，不用管 content

**Comment by youfeed** [comment]
老大 有些方面支持吗？我也是弄的json，为了方便以后扩展给小程序渲染，json友好一些
