### ISSUE TITLE
无序列表，当第一个 li 是图片，回车换行，有bug

### ISSUE THREAD

**Issue by zhangdaliang** [wangeditor-team/wangEditor#4776]
## bug 描述

![image](https://user-images.githubusercontent.com/16433862/187180737-1bb07b86-192e-4843-b64e-e9699ea85934.png)
无序列表 只有一个图片的时候，换行会自动删除掉图片和无序列表，目前看着是换行处理的方法导致的，5.1.14版本
![image](https://user-images.githubusercontent.com/16433862/187180860-5c83a280-b9ee-4230-9fa4-574fff72f69c.png)
我重写修复了 @

**Comment by wangfupeng1988** [comment]
我在官网 demo 未复现你的问题（如下图）

请补充复现的详细步骤

<img width="390" alt="image" src="https://user-images.githubusercontent.com/9583120/187326982-018e3172-f900-4ea6-8177-2dc90bd44906.png">

**Comment by zhangdaliang** [comment]
> 
1、先放一张图片
2、选中当前图片行 变成无序列表
3、在图片末尾点击enter键进行换行
此时会删除当前的无序列表
仅无序列表只有一个list-item时，并且此list-item中只有一张图片时，会出现此情况
因为源码中判断了，list-item的children最后一个元素是不是text是不是空，而图片会自动在同级的children前面和后面都加了一个{text: ''}

**Comment by zhangdaliang** [comment]
> 
1、先放一张图片
2、选中当前图片行 变成无序列表
3、在图片末尾点击enter键进行换行
此时会删除当前的无序列表
仅无序列表只有一个list-item时，并且此list-item中只有一张图片时，会出现此情况
因为源码中判断了，list-item的children最后一个元素是不是text是不是空，而图片会自动在同级的children前面和后面都加了一个{text: ''}

**Comment by wangfupeng1988** [comment]
> > 
> 
> 1、先放一张图片 2、选中当前图片行 变成无序列表 3、在图片末尾点击enter键进行换行 此时会删除当前的无序列表 仅无序列表只有一个list-item时，并且此list-item中只有一张图片时，会出现此情况 因为源码中判断了，list-item的children最后一个元素是不是text是不是空，而图片会自动在同级的children前面和后面都加了一个{text: ''}

已复现。后续解决

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本
