### ISSUE TITLE
wangEditor使用cdn引入，使用网络图片内容校验方法linkImgCheck, 获取不到href的值

### ISSUE THREAD

**Issue by wushal** [wangeditor-team/wangEditor#4780]
## 问题描述

wangEditor使用cdn引入，使用网络图片内容校验方法linkImgCheck, 获取不到href的值

## wangEditor 版本

使用的是cdn引入的方式，https://cdn.jsdelivr.net/npm/wangeditor@latest/dist/wangEditor.min.js

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

查阅了文档，按照文档使用的

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 代码中在wangEditor的config中使用linkImaCheck方法，返回的参数只有图片地址的参数，另外两个参数拿不到
- 步骤二 
- 步骤三

**Comment by wangfupeng1988** [comment]
搞一个能复现问题的 HTML  demo （越简单越好，能复现问题即可），源码贴到这里来，我看看。

**Comment by wushal** [comment]
这个不好弄，我直接截图吧
1、按照文档写的校验网络图片链接的方法
<img width="981" alt="image" src="https://user-images.githubusercontent.com/39685543/187575702-fdb6ce06-5c0d-4e37-90e6-4f43af861f70.png">
2、在使用网络图片时，输入图片地址、描述和链接，在console打印只有图片地址有值，如下图
![image](https://user-images.githubusercontent.com/39685543/187576118-48fa30c0-1012-412a-a911-d86bcfc7a58f.png)
3、编辑器是使用cdn引入，使用的是react umi框架
<img width="736" alt="image" src="https://user-images.githubusercontent.com/39685543/187576360-b4c35af8-4c5a-40ad-a339-fcbb31e375eb.png">

**Comment by wangfupeng1988** [comment]
哦，你这还是 v4 版本的。

v4 版本现已不维护了，业余时间不够，还请体谅

**Comment by wangfupeng1988** [comment]
React 环境推荐使用 v5 版本 https://www.wangeditor.com/v5/for-frame.html#react
