### ISSUE TITLE
scrollToElem 调用报错

### ISSUE THREAD

**Issue by countryMan1993** [wangeditor-team/wangEditor#4781]
## 问题描述

scrollToElem api 调用 报错 

![image](https://user-images.githubusercontent.com/26586400/187403678-9aa6c78e-4049-403c-81a5-1f60d6bb5adb.png)

## wangEditor 版本

@wangeditor/editor： ^5.1.15
@wangeditor/editor-for-vue: ：^1.0.2

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

- 步骤一
 使用vue2 创建模板项目，添加以下项目依赖
@wangeditor/editor
@wangeditor/editor-for-vue
- 步骤二
 使用editor组件，添加change事件 获取 header类型的标题的id
- 步骤三
使用 editor实例的 scrollToElem方法 传入标题 id

**Comment by wangfupeng1988** [comment]
参考这个 demo https://www.wangeditor.com/demo/catalog.html

**Comment by countryMan1993** [comment]
找到原因了 我点击事件用的是demo的例子去做的，目录使用v-html渲染的，然后就会出现这样，后面目录改用循环出来，然后通过click事件调用就正常了，但是editor是同一个啊 我点击事件都能获取到html内容，真的很奇怪🤔
