### ISSUE TITLE
外界图片复制xss怎么解决

### ISSUE THREAD

**Issue by yushengyuan123** [wangeditor-team/wangEditor#4782]
## 问题描述
假如说，外面有一个图片我需要复制进来，但是这个图片有xss代码，
以前v4版本我直接禁用图片复制，这个版本看了下api，整个复制行为变成了自定义化，不知道怎么把这个图片过滤掉比较合适
*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
建议步骤如下

- 在 customPaste 中获取原始的 HTML 
- 统一处理 HTML 的 XSS 风险，如使用 https://www.npmjs.com/package/xss
- 讲处理过后的 HTML 代码插入到编辑器，使用 `editor.dangerouslyInsertHtml(html)`
