### ISSUE TITLE
富文本中包含span标签  数据回显  （不显示)

### ISSUE THREAD

**Issue by m2075498242** [wangeditor-team/wangEditor#4783]
## bug 描述
如果在富文本内容中有span标签包含的内容，数据无法正常回显
*请输入内容……*

## 你预期的样子是？
数据正常回显
*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- windows10
- 浏览器和版本
谷歌 106.0.5231.2
## wangEditor 版本
  "@vuemap/vue-amap": "^1.1.4",
    "@wangeditor/editor": "^5.1.14",
    "@wangeditor/editor-for-vue": "^1.0.2",
*请输入内容……*

## demo 能否复现该 bug ？
可以
能/不能
能
- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo
没有在线的！
*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 先导入一个富文本
- 步骤二 在富文本内容中绑定的v-model属性添加一个死的数据：<span>随便输点内容</span>
- 步骤三 将数据存在数据库，重新加载  数据回显 空白  但是接口数据有

**Comment by wangfupeng1988** [comment]
你要回显的 HTML 内容是什么？贴到这里来，我看下。

PS：HTML 内容越简单越好，只要能复现问题即可

**Comment by m2075498242** [comment]
https://blog.csdn.net/weixin_56694018/article/details/126616727
内容我放在了这里 ，麻烦看一下是bug还是什么问题！！！  麻烦大佬了！

**Comment by wangfupeng1988** [comment]
如下图。这不是标准的 HTML 格式，所以 wangEditor 也不支持。

![image](https://user-images.githubusercontent.com/9583120/187598853-e497d7c5-c9cb-4718-8be7-034290664f1c.png)
