### ISSUE TITLE
在使用wangeditor富文本编辑器，给文字添加超链接，使其可以点击跳转到某个地址。 最后发现在 IOS 的app内，a标签点击跳转没有作用，无法跳转到正确地址。但安卓是可以正常跳转。

### ISSUE THREAD

**Issue by LeslieZhang** [wangeditor-team/wangEditor#4784]
## bug 描述

*在使用wangeditor富文本编辑器，给文字添加超链接，使其可以点击跳转到某个地址。
最后发现在 IOS 的app内，a标签点击跳转没有作用，无法跳转到正确地址。但安卓是可以正常跳转。*

## 你预期的样子是？

*ios的app内也可以正常跳转*

## 系统和浏览器及版本号

- 操作系统 ios
- 浏览器和版本

## wangEditor 版本

*https://unpkg.com/wangeditor@4.7.15/dist/wangEditor.min.js*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 官网在线demo添加超链接
- 步骤二 在ios的app内打开，点击a标签，无法跳转
因为，IOS上的WKWebView默认不会打开target="_blank"的超链接，所以在ios的WKWebView内，点击富文本返回的a标签无法正确跳转。建议超链接不要带上target="_blank"。

**Comment by wangfupeng1988** [comment]
> 建议超链接不要带上target="_blank"

直接去掉 `target="_blank"` 也不行，太绝对了，其他人肯定还是需要的。

你先自己获取 HTML 之后用正则过滤掉 `target="_blank"` 吧
