### ISSUE TITLE
vue3使用时遇到绑定传值问题

### ISSUE THREAD

**Issue by cffycls** [wangeditor-team/wangEditor#4786]
## 问题描述
使用demo组件内容绑定传值问题，初始化正常，提交时内容无变化

*请输入遇到的问题...*
使用组件传值问题
```
<WEditor ref="editorRef" :valueHtml="formData.content" />
```
【框架为element ui+vue3.2】初始化正常，提交时内容无变化

## wangEditor 版本
```
npm list
├──@wangeditor/core@1.1.12
├── @wangeditor/editor-for-vue@5.1.12
├── @wangeditor/editor@5.1.15
```

*请输入内容……*
demo以及视频未表明初始化、向父组件传值的问题

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
使用demo进行绑定传值，完成初始化、父组件动态赋值

**Comment by cffycls** [comment]
已收到
新值更改 editorRef.value.valueHtml

**Comment by wangfupeng1988** [comment]
请提供一个 demo ，能复现问题即可
