### ISSUE TITLE
自定义上传图片无法设置style

### ISSUE THREAD

**Issue by Yuppiezero** [wangeditor-team/wangEditor#4787]
图片上传之后 正常操作是 insertFn(图片地址)，但是发现没有 width：max-width:100%;

然后尝试了
this.editor.dangerouslyInsertHtml(`<img src="${res.data}" style="max-width:100%;">`)

没有效果后尝试
this.editor.insertNode({ type: 'image', src: res.data, style: 'max-width:100%', children: [{ text: '' }] })

结果style 始终不能在 图片节点上显示……

求助 应该如何操作

**Comment by wangfupeng1988** [comment]
不支持自定义 style

如果你想为图片定义 max-width ，你可以通过 CSS 来定义
