### ISSUE TITLE
在插入两个自定义新元素时，鼠标点击两元素中间，光标会消失

### ISSUE THREAD

**Issue by ouweicong** [wangeditor-team/wangEditor#4788]
## 问题描述

*请输入遇到的问题...*
在插入两个连续自定义新元素节点时，鼠标点击两节点中间，光标会消失，会自动选择旁边的节点，使用move移动光标也不行，会失效
## wangEditor 版本
最新版
*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
用insertNode插入新元素节点
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by ouweicong** [comment]
我想把光标定位到两元素中间

**Comment by wangfupeng1988** [comment]
猜测是你节点定义的问题，你可以参考 [插件](https://www.wangeditor.com/v5/plugins.html) 的一些节点定义代码

**Comment by ouweicong** [comment]
![image](https://user-images.githubusercontent.com/106805834/187811302-cf5ad081-11f6-4d53-9af9-624576a17528.png)
像这个两个附件，鼠标点击他们中间光标消失，会自动选择旁边的附件，导致输入不了字

**Comment by shanyi-front** [comment]
哥们最后解决了吗？我也遇到这个问题
