### ISSUE TITLE
没有图片懒加载

### ISSUE THREAD

**Issue by like0121** [wangeditor-team/wangEditor#4789]
需要图片的懒加载功能，因为现在浏览器都支持loading="lazy"这个属性了。

我尝试自定义InsertFnType = (url: string, loading：string，alt: string, href: string, style: string) => void  添加loading属性，然后在insertFn(res.data, 'lazy', ' ', '','width:600px')里添加lazy没有作用，同时那个图片style也不可以修改，完善一下这些功能，真的很实用。

**Comment by zhangdaliang** [comment]
需要图片的懒加载功能，因为现在浏览器都支持loading="lazy"这个属性了。

我尝试自定义InsertFnType = (url: string, loading：string，alt: string, href: string, style: string) => void 添加loading属性，然后在insertFn(res.data, 'lazy', ' ', '','width:600px')里添加lazy没有作用，同时那个图片style也不可以修改，完善一下这些功能，真的很实用。
> 

如果你只是想加个属性 loading='lazy'在img DOM上  可以这么操作
![image](https://user-images.githubusercontent.com/16433862/188038590-67749877-fb03-47df-91ab-bd63d59ff30c.png)

**Comment by wangfupeng1988** [comment]
@zhangdaliang  重写默认的 image render 逻辑，可能会有风险，请一定测试好。

**Comment by zhangdaliang** [comment]
> 重写默认的 image render 逻辑，可能会有风险，请一定测试好。

已经发现了  重写还需要重写拉伸等一系列操作   已经放弃了

**Comment by like0121** [comment]
> 如果你只是想加个属性 loading='lazy'在img DOM上 可以这么操作 ![image](https://user-images.githubusercontent.com/16433862/188038590-67749877-fb03-47df-91ab-bd63d59ff30c.png) 效果： ![image](https://user-images.githubusercontent.com/16433862/188038687-6936a3ac-878c-4c2c-8e47-b60585062dc0.png)

我用正则替换解决了，就是在提交Html代码的时候用正则找到图片替换加入需要加入的属性，也很方便

**Comment by ruuuuuuun** [comment]
> > 如果你只是想加个属性 loading='lazy'在img DOM上 可以这么操作 ![image](https://user-images.githubusercontent.com/16433862/188038590-67749877-fb03-47df-91ab-bd63d59ff30c.png) 效果： ![image](https://user-images.githubusercontent.com/16433862/188038687-6936a3ac-878c-4c2c-8e47-b60585062dc0.png)
> 
> 我用正则替换解决了，就是在提交Html代码的时候用正则找到图片替换加入需要加入的属性，也很方便

这个没用，即使html字符串有`loading="lazy"`，渲染的时候也不会有这个属性

**Comment by Ardanas** [comment]
> > > 如果你只是想加个属性 loading='lazy'在img DOM上 可以这么操作 ![image](https://user-images.githubusercontent.com/16433862/188038590-67749877-fb03-47df-91ab-bd63d59ff30c.png) 效果： ![image](https://user-images.githubusercontent.com/16433862/188038687-6936a3ac-878c-4c2c-8e47-b60585062dc0.png)
> > 
> > 
> > 我用正则替换解决了，就是在提交Html代码的时候用正则找到图片替换加入需要加入的属性，也很方便
> 
> 这个没用，即使html字符串有`loading="lazy"`，渲染的时候也不会有这个属性

是的，有其它办法吗？
