### ISSUE TITLE
在插入两个自定义新元素时，鼠标点击两元素中间，光标会消失

### ISSUE THREAD

**Issue by ouweicong** [wangeditor-team/wangEditor#4791]
## 问题描述

*请输入遇到的问题...*
在插入两个自定义新元素时，鼠标点击两元素中间，光标会消失，自动选择旁边的新元素。选中新元素时，用不了光标移动的api
## wangEditor 版本
最新版

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/106805834/187811968-1caa3fc1-afcb-49f7-9a6c-f8529c260b38.png)
使用上传附件的插件就能复现问题
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/issues/4788 重复了
