### ISSUE TITLE
无序列表和缩进问题

### ISSUE THREAD

**Issue by zhangdaliang** [wangeditor-team/wangEditor#4792]
## bug 描述

1、先写一段文字
2、修改此段文字的缩进
3、将此段文字变成无序列表

此时无序列表的文字头部会有缩进，且无法取消，换行创建新的列表行时，也存在缩进，无法取消
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16433862/187823765-daafa99a-6aba-4dc1-b162-43e2fc1e6630.png">

目前已经通过Boot.registerRenderStyle来解决此问题

另外提个优化点：
Boot.registerRenderStyle并没有返回当前触发的editor对象，所以我无法分辨list-item的父元素是有序列表还是无序列表，目前通过Boot.registerRenderElem+Boot.registerRenderStyle来解决此问题，希望以后能支持

**Comment by wangfupeng1988** [comment]
已修复，升级 `@wangeditor/editor` 最新版本

**Comment by zhangdaliang** [comment]
> 已修复，升级 `@wangeditor/editor` 最新版本

王老师，针对这次新版本的列表功能优化体验有几点问题
1、首先是dom元素不再使用ol ul列表，以及editor的node数据也是直接使用'list-item'作为顶层数据，这种情况下，升级版本将要对历史数据进行处理，dom的自定义处理也需要进行很多修改。
2、我觉得缩进功能的前提是，首先是ul ol整体是列表的情况下，进行的功能拓展。按照现有这种分散的格式，就会出现当列表中间某一项变成普通行时，比如1 2 3变成 1 普通行 3 此时的3就会变成1，因为无法确定3跟上面的1是否有关系，就会造成列表序列断开，而且本身毫无关系的列表，通过删除中间普通行，又会变成有序关系的情况。
3、操作上，目前发现这几点体验上的问题
    空列表换行不自动变普通段了
    列表项删除键删除如果上方是空列表项，光标不会上移而是直接删除掉了上方空列表项
    Tab必须在列表项头部才可进行切换层级

**Comment by wangfupeng1988** [comment]
有问题再去单独提交 issue 吧。每个 issue 只讨论一个问题，别混在一块。
