### ISSUE TITLE
版本v5，点击插入链接时候，出现的框样式发生改变

### ISSUE THREAD

**Issue by baoxing** [wangeditor-team/wangEditor#4793]
## bug 描述
版本v5，点击插入链接时候，出现的框样式发生改变
## 你预期的样子是？

![image](https://user-images.githubusercontent.com/3355896/187847096-1574ea70-9f7b-48c4-abff-61d93ae15302.png)

## 系统和浏览器及版本号

- win10
- chrome104

## wangEditor 版本

    "@wangeditor/editor": "^5.1.14",
    "@wangeditor/editor-for-vue": "^1.0.2",

## demo 能否复现该 bug ？
![image](https://user-images.githubusercontent.com/3355896/187847302-ac094c92-db85-4e80-ae8e-6270665254ea.png)

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
全局样式影响了，自己再重写一下 css 吧。检查一下输入框、button 是哪个 css class
