### ISSUE TITLE
多个编辑器 使用全屏功能层级有问题

### ISSUE THREAD

**Issue by 541110727gdx** [wangeditor-team/wangEditor#4794]
## bug 描述

*多个编辑器 使用全屏功能层级有问题*

## 你预期的样子是？

正常显示

## 系统和浏览器及版本号

- win10
- chrome 104.0.5112.81

## wangEditor 版本

*5.0.1*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 官方demo 多编译器模式 点第一个全屏

**Comment by wangfupeng1988** [comment]
两个编辑器都自定义一下 z-index 试试 https://www.wangeditor.com/v5/getting-started.html#%E5%BC%95%E5%85%A5-css-%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by 541110727gdx** [comment]
嗯嗯 已经解决了   就是看demo也有这个问题 就提一下 后面可以优化一下

> 两个编辑器都自定义一下 z-index 试试 https://www.wangeditor.com/v5/getting-started.html#%E5%BC%95%E5%85%A5-css-%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by wangfupeng1988** [comment]
好的
