### ISSUE TITLE
文字增加超链接，标签格式错误，点击无效果

### ISSUE THREAD

**Issue by 9727kangcheng** [wangeditor-team/wangEditor#4795]
上传成功之后检查元素得到的是`<a href='www.baidu.com' ><a>百度</a></a>`
正常的应该是`<a href='www.baidu.com' >百度</a>`，没有标签嵌套，正常步骤添加超链接，不能稳定复现，但是确实有这样的问题

`<p><a href=\"https://www.baidu.com/Commison" target=\"_blank\"><font color=\"#000000\"></font></a><font color=\"#000000\"><a>Super Rebate</a></font><br/></p>`

**Comment by wangfupeng1988** [comment]
请按照 issue 模板重新提交，否则不予受理
