### ISSUE TITLE
按照vue3的demo做的使用方式配置，但是出现了标题和加粗无效

### ISSUE THREAD

**Issue by Verdicts-ye** [wangeditor-team/wangEditor#4796]
## bug 描述

按照vue3的demo做的使用方式配置，但是出现了标题加粗

## 你预期的样子是？

像demo那样正常使用

## 系统和浏览器及版本号

- 操作系统
-版本	Windows 10 企业版
版本号	21H2
安装日期	‎2022/‎8/‎22
操作系统内部版本	19044.1889
体验	Windows Feature Experience Pack 120.2212.4180.0

- 浏览器和版本
版本 103.0.5060.134（正式版本） （64 位）
[Chrome++](https://github.com/shuax/chrome_plus) 1.5.2 inside
## demo 能否复现该 bug ？

不能

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
```
<template>
   <div class="border" style='border-color:#ccc'>
      <Toolbar style="border-bottom: 1px solid #ccc" :editor="editorRef" :defaultConfig="toolbarConfig"
        mode="default" />
      <Editor style="height: 500px; overflow-y: hidden;" v-model="valueHtml" :defaultConfig="editorConfig"
        mode="default" @onCreated="handleCreated" />
    </div>
</template>
```
```
<script lang="ts" setup>
import '@wangeditor/editor/dist/css/style.css';
import { Editor, Toolbar } from '@wangeditor/editor-for-vue';
// 编辑器实例
const editorRef = shallowRef()
const valueHtml = ref('')
const toolbarConfig = {}
const editorConfig = { placeholder: '请输入内容...' }

// 组件销毁时，也及时销毁编辑器
const handleCreated = (editor) => {
  editorRef.value = editor // 记录 editor 实例
}

onBeforeUnmount(() => {
  const editor = editorRef.value
  if (editor == null) return
  editor.destroy()
})
</script>
```
- 步骤二
![image](https://user-images.githubusercontent.com/50040175/188080341-91dde123-a367-4794-a9da-29270affff59.png)
![image](https://user-images.githubusercontent.com/50040175/188080921-c75f8f9b-9c53-4988-908e-131255a18880.png)

- 步骤三

**Comment by wangfupeng1988** [comment]
浏览器控制台检查一下这个文字的 DOM 结构，是否有 `<strong>` 标签？

![](https://user-images.githubusercontent.com/50040175/188080341-91dde123-a367-4794-a9da-29270affff59.png)

**Comment by LinsonZ** [comment]
有这个标签，通过检查元素看起来样式被覆盖了？
![image](https://user-images.githubusercontent.com/47975986/188272285-4351af21-e552-4906-8559-edad328aa49e.png)

**Comment by Verdicts-ye** [comment]
谢谢,我的问题,我是引入了reset.css覆盖了那些标签.问题已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月4日(星期天) 中午1:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 按照vue3的demo做的使用方式配置，但是出现了标题和加粗无效 (Issue #4796)





 
Closed #4796 as completed.
