### ISSUE TITLE
v5版本yarn build报错

### ISSUE THREAD

**Issue by RonkyTang** [wangeditor-team/wangEditor#4797]
## bug 描述

报错位置在: packages/core/src/upload/createUploader 第102行

## 你预期的样子是？

yarn build 成功

## wangEditor 版本

v5.1.15

## demo 能否复现该 bug ？

能

报错内容是类型不匹配, 我可以在本地修复, 希望作者能在新版本修复:
![image](https://user-images.githubusercontent.com/16137898/188083442-fc71b439-d694-469e-8e41-a1ebc421239c.png)

谢谢

**Comment by wangfupeng1988** [comment]
可能是 TS 版本的问题，我本地暂未复现。

如有复现肯定会修改的，否则没法继续发布新版了。

**Comment by RonkyTang** [comment]
> Collaborator

我试了一下, 确实TS版本问题, 我本地4.8.2, 在有问题的情况参照以下修改即可:
![image](https://user-images.githubusercontent.com/16137898/188273760-967953f1-18b7-47aa-a6cd-fbb9401c78f5.png)

我关闭该issue, 作者看看要不要告知其他用户.

**Comment by wangfupeng1988** [comment]
暂时不用，其他用户直接 build 源码的，几乎没有。
