### ISSUE TITLE
公式插件wangEditor-plugin-formula 使用问题

### ISSUE THREAD

**Issue by ITso-easy** [wangeditor-team/wangEditor#4799]
![image](https://user-images.githubusercontent.com/29625754/188104676-477cb356-268d-4cc2-aea4-951673454813.png)
如何实现入下图所示的模板实例，让用户能快速输入想要的公式格式
![image](https://user-images.githubusercontent.com/29625754/188104979-658cf6fd-895e-4ba0-9d5e-7f4aad4b07ad.png)

**Comment by wangfupeng1988** [comment]
这个需求，建议你自己参考 formula 插件源码，自己单独写一个插件。

**Comment by ITso-easy** [comment]
最近用到wangdEditor  监听事件 ：出现如下问题
![image](https://user-images.githubusercontent.com/29625754/188574797-5f1c5c88-5c4e-4059-bc80-e353fd9ca045.png)
1.blur事件无效，不会触发
2.change事件，只要点击编辑框，获取焦点就会触发

**Comment by wangfupeng1988** [comment]
> 1.blur事件无效，不会触发

去提交一个新的 issue 吧，说明复现步骤

**Comment by wangfupeng1988** [comment]
> 2.change事件，只要点击编辑框，获取焦点就会触发

选区变化也会触发 onChange ，符合预期。
