### ISSUE TITLE
加载编辑器 文件 比较大

### ISSUE THREAD

**Issue by zxueliang** [wangeditor-team/wangEditor#4804]
## 问题描述

Vue2 在 加载 编辑器的时候，打包出来的文件比较大
有什么办法解决这个问题吗？
比如 懒加载 或者 延迟加载 啥的

## wangEditor 版本

V5 最新版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
可以考虑用 Vue 的异步组件
