### ISSUE TITLE
如何改变只读状态中内容得样式

### ISSUE THREAD

**Issue by QQchu** [wangeditor-team/wangEditor#4805]
## 问题描述

*如何改变只读状态中内容得样式*

## wangEditor 版本

*vue3*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*
![image](https://user-images.githubusercontent.com/42673687/188378525-4ab9c77c-df3a-4977-92a3-71654a17284f.png)

**Comment by wangfupeng1988** [comment]
猜测是你自己 css 样式的污染，编辑器没有设置灰色。

**Comment by QQchu** [comment]
> 猜测是你自己 css 样式的污染，编辑器没有设置灰色。

**Comment by QQchu** [comment]
> 猜测是你自己 css 样式的污染，编辑器没有设置灰色。

![image](https://user-images.githubusercontent.com/42673687/188418734-1a949fe2-5863-4570-aece-1a09821d804c.png)
设置不生效。浏览器调试点击相应的块，也没有看到设置背景色样式。我是放在一个弹出框里面的，关闭的瞬间，才可以看到样式显现。
