### ISSUE TITLE
图片上传之后，在编辑区域内如何调整图片大小

### ISSUE THREAD

**Issue by xueling0909** [wangeditor-team/wangEditor#4806]
## 问题描述

图片上传之后，在编辑区域内如何调整图片大小
## wangEditor 版本 4.17.15

没有在文档里查到如何调整图片尺寸大小

不知道是我没找到用对方法，还是本来就无法拖拽调整大小

希望能帮忙看看，感谢

**Comment by wangfupeng1988** [comment]
v4 版本已不再维护了。

业余维护，时间不够，还请体谅
