### ISSUE TITLE
wangEditor 上传附件 插件---plugin-upload-attachment自定义上传附件

### ISSUE THREAD

**Issue by xu-chunxiao** [wangeditor-team/wangEditor#4807]
## 问题描述
使用plugin-upload-attachment自定义上传附件是控制台报错
![1662389966739_09A568E6-90A6-448f-84FB-C291B2746712](https://user-images.githubusercontent.com/67221935/188477098-d93c8db6-3250-457e-bbf4-4b988015e0ae.png)
           Error: Cannot get upload server address
          没有配置上传地址
*请输入遇到的问题...*
使用上传附件插件自定义上传时，代码走不到customUpload方法中,且报错   Error: Cannot get upload server address没有配置上传地址------但是只要改动一点代码（随便一个位置加一个debugger时），重新上传文件，此时能走到自定义上传的方法customUpload中，且能上传附件

  MENU_CONF: {
        // “上传附件”菜单的配置
        uploadAttachment: {
    // “上传附件”菜单的配置
        uploadAttachment: {
          //附件自定义长传
          customUpload(file, insertFn) {
            debugger;
            //附件上传处理，可以进行请求发送，如果加了这个方法，上面的server请求将不会再进行，切记切记!!!!!!!!!
            let formData = new FormData(); //创建格式
            formData.append("imgFile", file); //添加属性
            //这是调用封装的接口
            cim.net.axiosWraper
              .getDataByPost( url, formData)
              .then((res) => {
                debugger;
                let url = `${res.url}`;
                emit("fjdz", url);
                insertFn(`${file.name}`, url); //插入地址
              });
          },
        },
}
}
## wangEditor 版本

wangEditor 5

## 是否查阅了文档 ？
是
[（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）](https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment)

*是/否*

## 最小成本的复现步骤
自定义上传附件时走不到自定义上传的方法customUpload中，但是只要改动一点代码（随便一个位置加一个debugger时），重新上传文件，此时能走到自定义上传的方法customUpload中，且能上传附件

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考这个 demo 吧  https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html

**Comment by xu-chunxiao** [comment]
https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html这个链接好像还是不是自定义上传的吧，用了demo中的 uploadAttachment: {
                            server: fileUrl,
                            fieldName: 'custom-fileName',
                            onInsertedAttachment(elem) {
                                console.log('inserted attachment ---- ', elem)
                            },
                        }
![image](https://user-images.githubusercontent.com/67221935/188568189-8ff019f5-83d0-436a-8d71-7e57539eb1a6.png)
请问一下有自定义上传附件的demo吗

**Comment by wangfupeng1988** [comment]
你现在 demo 源码，自己加一个自定义上传的配置，试试

**Comment by xu-chunxiao** [comment]
![image](https://user-images.githubusercontent.com/67221935/188615033-53212bdc-5992-45c1-84d6-f124b6634596.png)
始终走不到这个自定义的方法里面去
![image](https://user-images.githubusercontent.com/67221935/188615208-5d517b0e-20eb-43f8-8a44-bafe194322ea.png)
请问一下各位大佬这上面的写法哪里有问题啊

**Comment by lyy199212** [comment]
我也遇到同样的问题了呢 不知道解决没?
