### ISSUE TITLE
v5版本中使用dangerouslyInsertHtml接口设置html内容无效

### ISSUE THREAD

**Issue by 1182515377** [wangeditor-team/wangEditor#4808]
## bug 描述

在vue3项目中使用了wangEdit v5版本，获取editor示例后使用dangerouslyInsertHtml接口设置html内容无效，其他接口有效

## 你预期的样子是？

预想：获取实例后，设置非getHtml获取的html内容展示。 实际：设置内容后无效，有没有报错

## 系统和浏览器及版本号

- 操作系统
- window10
- 浏览器和版本
- 谷歌、火狐都不行

## wangEditor 版本

vue项目中：
    "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-vue": "^5.1.11",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

无，估计vue3的版本设置dangerouslyInsertHtml都无效果

**Comment by wangfupeng1988** [comment]
dangerouslyInsertHtml 传入的 html 内容是什么？贴到这里

**Comment by 1182515377** [comment]
editor.dangerouslyInsertHtml(`<h1>标题</h1><p>文本 <b>加粗</b></p>`)

已升级到最新版本，vue版本为3.2.25 。 使用vue语法糖

**Comment by 1182515377** [comment]
const handleCreated = (editor:any) => {
        editorRef.value = editor 
        console.log(editor)
        editor.dangerouslyInsertHtml(`<h1>标题</h1><p>文本 <b>加粗</b></p>`) // 设置内容无效
       },

**Comment by 1182515377** [comment]
我尝试过了，vue3用setup语法糖无法通过dangerouslyInsertHtm设置内容，用非语法糖就可以。但发现一个问题就是：当autoFocus为false时，无法通过dangerouslyInsertHtm设置内容

**Comment by wangfupeng1988** [comment]
打开这个 demo https://www.wangeditor.com/demo/ ，进入控制台，执行

```
editor.dangerouslyInsertHtml(`<h1>标题</h1><p>文本 <b>加粗</b></p>`)
```

是可以插入的

**Comment by wangfupeng1988** [comment]
> 当autoFocus为false时，无法通过dangerouslyInsertHtm设置内容

是的，本就这么设计。
 
你可以先执行 `editor.focus()` 再插入内容
