### ISSUE TITLE
V5字体问题

### ISSUE THREAD

**Issue by touyingzideren1** [wangeditor-team/wangEditor#4810]
we v5(非vue)中如何在不显示工具栏的情况设置其默认字体

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/issues/4042

**Comment by touyingzideren1** [comment]
他在插入图片之后字体会变成最初默认的,而非配置默认的,

**Comment by wangfupeng1988** [comment]
> 他在插入图片之后字体会变成最初默认的,而非配置默认的,

这个再待优化吧
