### ISSUE TITLE
Vue使用customBrowseAndUpload插入poster无效

### ISSUE THREAD

**Issue by finham** [wangeditor-team/wangEditor#4812]
## bug 描述

Vue使用customBrowseAndUpload插入poster无效

## 你预期的样子是？

insertFn(url, poster)，但是最终查看DOM，只有poster标签，并没有属性值

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

5.1.15

## demo 能否复现该 bug ？

customBrowseAndUpload 方法必现

**Comment by wangfupeng1988** [comment]
把你关于 `customBrowseAndUpload ` 的配置代码贴出来吧，我看看

**Comment by finham** [comment]
customBrowseAndUpload(insertFn) {
    this.dialogVisible = true; //我有个自定义对话框进行上传
    let i = setInterval(() => {
        if (this.url && this.clickConfirm) { // 需要用户点击对话框的确定后才插入视频
            console.log("insertFn", this.url, this.poster)
            insertFn(this.url, this.poster) 
            this.clickConfirm = false; //还有一些重置动作
            clearInterval(i)
        }
    })
}

**Comment by finham** [comment]
![image](https://user-images.githubusercontent.com/52123941/188604153-8bc233d7-abb3-43c5-a5cf-f3e0b14af1f4.png)

我看了下源码，不清楚问题是否是上述截图所示，该代码位于：packages/video-module/src/module/helper/insert-video.ts

**Comment by finham** [comment]
试了一下，整个方法只有一句代码，插入一条互联网的url和poster，也是没有poster的

**Comment by finham** [comment]
在vue示例demo中 https://codesandbox.io/s/vue2-wangeditor-demo-forked-547zsf?file=/src/components/MyEditor.vue 重写uploadVideo: { customBrowseAndUpload: xxxx } 是能复现的，poster没有生效

**Comment by wangfupeng1988** [comment]
已复现。我有空了去排查。

**Comment by wangfupeng1988** [comment]
你可以先用 insertNode 代替 insertFn ，示例如下

```js
const videoNode = {
    type: "video",
    src: "https://www.w3school.com.cn/i/movie.ogg",
    poster: "https://www.baidu.com/img/flexible/logo/pc/result@2.png",
    children: [{ text: '' }]
}
editor.insertNode(videoNode)
```

**Comment by finham** [comment]
好的，感谢！

**Comment by wangfupeng1988** [comment]
已修复，请升级最新版 `@wangeditor/editor`

**Comment by finham** [comment]
好的，感谢开发者！


另外我想请问一下，在wangEditor里插入视频时会默认增加一个换行，请问这个是可以设置的吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月15日(周四) 下午4:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wangeditor-team/wangEditor] Vue使用customBrowseAndUpload插入poster无效 (Issue #4812)




 
Closed #4812 as completed.

**Comment by wangfupeng1988** [comment]
> 另外我想请问一下，在wangEditor里插入视频时会默认增加一个换行，请问这个是可以设置的吗？

使用 `customInsert ` ，插入视频后，再插入一个空行即可。

**Comment by finham** [comment]
哈哈开发者你误会了，我是说插入视频时wangEditor会默认加一个换行，导致不是插入在光标的位置，我不想要增加这个换行，有没有什么方法可以去掉。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月23日(周五) 中午12:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wangeditor-team/wangEditor] Vue使用customBrowseAndUpload插入poster无效 (Issue #4812)

**Comment by wangfupeng1988** [comment]
这个不行，因为视频下面还要输入文字，就得有一个空行存在。

**Comment by finham** [comment]
插入视频默认是插入在文章末尾，而非光标所在位置，这个有地方可以设置吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月23日(周五) 中午1:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wangeditor-team/wangEditor] Vue使用customBrowseAndUpload插入poster无效 (Issue #4812)




 
这个不行，因为视频下面还要输入文字，就得有一个空行存在。

**Comment by wangfupeng1988** [comment]
> 插入视频默认是插入在文章末尾，而非光标所在位置，这个有地方可以设置吗？

暂不支持，可自己通过插件定义，具体阅读文档
