### ISSUE TITLE
使用富文本编辑-监听事件问题

### ISSUE THREAD

**Issue by ITso-easy** [wangeditor-team/wangEditor#4813]
##按文档操作 监听事件 editor.on('event-key', fn) 在使用中发现问题如下
*1.监听blur事件无效
*2.监听change事件的时候，只要编辑框获取焦点就会触发， 失去焦点也会触发该事件
### 复现步骤
*1.按照文档提交的demo （vue.2.0环境）
![image](https://user-images.githubusercontent.com/29625754/188588316-86f97891-adb6-4236-a348-37747c83531f.png)

在onCreatedfangs方法中 写监听方法 
![image](https://user-images.githubusercontent.com/29625754/188588365-dc37d9c9-76bc-4149-8b5d-b2cbd481ab89.png)

**Comment by wangfupeng1988** [comment]
> 1.监听blur事件无效

试试这种方式可以吗？ https://www.wangeditor.com/v5/editor-config.html#onblur

**Comment by wangfupeng1988** [comment]
> 2.监听change事件的时候，只要编辑框获取焦点就会触发， 失去焦点也会触发该事件

选区变化也会触发 onChange

**Comment by ITso-easy** [comment]
按文档操作
![image](https://user-images.githubusercontent.com/29625754/189013907-6bef75bb-23bc-4ad7-9b9f-9ac237b5c9c8.png)
引入这个 IEditorConfig   控制台打印问undefined

![image](https://user-images.githubusercontent.com/29625754/189014094-31423897-a6cf-47af-81ba-21615b31f803.png)
![image](https://user-images.githubusercontent.com/29625754/189014118-d38a8ce7-2390-4c1d-a03f-06ed59b857e1.png)

**Comment by wangfupeng1988** [comment]
你用 JS 还是 TS ？

**Comment by ITso-easy** [comment]
我用的是JS

**Comment by ITso-easy** [comment]
vue.2.0

**Comment by wangfupeng1988** [comment]
那你用 JS 的代码即可，文档中都有注释啊

![](https://user-images.githubusercontent.com/29625754/189013907-6bef75bb-23bc-4ad7-9b9f-9ac237b5c9c8.png)

**Comment by ITso-easy** [comment]
代码初始化了一个配置
![image](https://user-images.githubusercontent.com/29625754/189083826-c8abc93b-3dc3-45fa-941f-105b9f7ba52c.png)
![image](https://user-images.githubusercontent.com/29625754/189083888-600c1788-289d-4abf-a0d1-d9666db4edc3.png)
![image](https://user-images.githubusercontent.com/29625754/189084116-1895c567-9661-4bf1-9d07-4efee21d03ce.png)
按文档试这样使用配置吧 
![image](https://user-images.githubusercontent.com/29625754/189084231-7a7ace70-4cbb-43c3-84b6-7a564c3997f2.png)
出现这个报错

**Comment by wangfupeng1988** [comment]
再好好看看文档吧，Vue 组件那部分。

**Comment by ITso-easy** [comment]
请问一下如果要把工具栏和编辑框分开 ；把工具栏单独组成组件，和编辑框形成一对多的关系可以实现吗，
问题如下图
1.点击第一个编辑框的时候，工具栏成灰色，不能编辑状态

2.点击第二个编辑框的时候工具栏可用

期望：不管点击哪个编辑框，工具栏都可用




涅槃重生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月9日(星期五) 上午8:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 使用富文本编辑-监听事件问题 (Issue #4813)





 
再好好看看文档吧，Vue 组件那部分。
