### ISSUE TITLE
自定义selectMenu如何定义选项宽度

### ISSUE THREAD

**Issue by RobertHan215** [wangeditor-team/wangEditor#4814]
## 问题描述

根据样例自定义了一个selectMenu，有些描述会比较长，增加了width，但是下来选项的宽度不会变

## wangEditor 版本

5.1.15

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

**Comment by wangfupeng1988** [comment]
需要提供一个 demo ，一个 HTML 文件即可，参考 https://www.wangeditor.com/demo/extend-menu-select.html
