### ISSUE TITLE
编辑器事件回调时机问题

### ISSUE THREAD

**Issue by zhangdaliang** [wangeditor-team/wangEditor#4816]
问题描述：

在实际开发中，进入编辑状态的时候，onChange会调用一次，并且onChange会比onFocus先调用，并且此时onChange里面获取editor的isFocused()返回true
![image](https://user-images.githubusercontent.com/16433862/188814370-fad26de8-b1ff-49eb-9dc6-01d8740e471e.png)
![image](https://user-images.githubusercontent.com/16433862/188814371-023b292d-d1f7-44e7-86da-5e6f3bdbc584.png)

期望结果：
1、进入编辑状态时，仅触发onFocus
2、当数据确实进行变化时，再触发onChange

**Comment by wangfupeng1988** [comment]
选区变化会触发 onChange

如果仅仅想通过内容变化判断 onChange ，可以通过对比当前和上次的 `JSON.stringify(editor.children)` 是否一样。
字符串对比效率很高。

**Comment by zhangdaliang** [comment]
> 
感谢王老师😁
