### ISSUE TITLE
我在升级editor的时候发现并不那么顺手，建议“元素”实现无侵入式扩展

### ISSUE THREAD

**Issue by zhangjindong** [wangeditor-team/wangEditor#4818]
## 问题描述

*我在升级editor的时候发现并不那么顺手。*

## wangEditor 版本

*原版本*
```
    "@wangeditor/core": "^1.0.1",
    "@wangeditor/editor": "^5.0.1",
    "@wangeditor/editor-for-react": "^1.0.2",
```
*新版本*
```
    "@wangeditor/core": "^1.1.12",
    "@wangeditor/editor": "^5.1.15",
    "@wangeditor/editor-for-react": "^1.0.5",
```

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

参考 commit [feat: 表格拖拽列宽
](https://github.com/wangeditor-team/wangEditor/commit/46ea2c0f831b03ebca5fddfd59d682fed0b3476e)，我发现table的数据结构变了，fullwidth变为 width；renderElems 也变成了三个[renderTableConf, renderTableRowConf, renderTableCellConf]; 因此导致我自己写的两个hoverbarKeys （ border:none   , .border-divider-top , .border-divider-bottom）需要重新写 这三个方法重新覆盖。

建议：针对元素设计一个插件式或面向切面的代码。无非就是 html -> element ->  html 的过程，提供三个钩子 paseHTML(dom, beforeElement), render(Element,beforevnode),tohtml( Element,beforevnode );每个钩子都可以类似链式调用，不需要覆盖，实现无侵入扩展。

**Comment by wangfupeng1988** [comment]
没看懂。

`导致我自己写的两个hoverbarKeys` 这句话什么意思？你是自定义菜单了吗？

**Comment by zhangjindong** [comment]
> 没看懂。
> 
> `导致我自己写的两个hoverbarKeys` 这句话什么意思？你是自定义菜单了吗？

对的，table中加了两个功能。升级后还得重写下面的方法

![image](https://user-images.githubusercontent.com/5567162/189009366-0337be51-35ea-409c-a869-98095c5ad719.png)
![image](https://user-images.githubusercontent.com/5567162/189009398-88b40a56-7235-4715-82b5-b785983bb04e.png)
![image](https://user-images.githubusercontent.com/5567162/189009495-733e70e8-7483-44a5-8210-01018b4f3224.png)

**Comment by wangfupeng1988** [comment]
哦，好的。后面我升级时注意兼容性。
