### ISSUE TITLE
customPaste 自定义粘贴 样式失效

### ISSUE THREAD

**Issue by meicy** [wangeditor-team/wangEditor#4822]
## 问题描述

*customPaste 自定义粘贴 样式失效*

## wangEditor 版本

*"@wangeditor/editor": "^5.1.1",
    "@wangeditor/editor-for-react": "^1.0.4",*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
editorConfig.customPaste = (ed, event) => {
        const html = event.clipboardData.getData('text/html') 
        console.log('html',html)
        ed.dangerouslyInsertHtml(html)
    }
如上配置editorConfig 的自定义粘贴。

从https://www.135editor.com/ 上面复制了一个模板过来。
![b2299fc637377d8b07080a2a22d4a895](https://user-images.githubusercontent.com/8372901/188895444-8911536a-d5fb-487e-992e-8b2ee7ce69f9.png)
这是正常展示的样式，但是，在wangeditor里面样式还是乱掉了。

**Comment by wangfupeng1988** [comment]
`dangerouslyInsertHtml` 不能保证样式完全一样。

如果你要 100% 还原 135编辑器的样式，wangEditor5 不支持。可以考虑用 wangEditor4

**Comment by meicy** [comment]
> `dangerouslyInsertHtml` 不能保证样式完全一样。
> 
> 如果你要 100% 还原 135编辑器的样式，wangEditor5 不支持。可以考虑用 wangEditor4

hi，你好这边，我们考虑降级到4版本，但是碰到一个二次开发的问题，我想重写4版本的图片编辑的，这边我看4的文章没有相关的钩子，想说作者这边有什么思路么？

**Comment by wangfupeng1988** [comment]
v4 我已没时间维护了。业余时间不够，还请体谅

**Comment by a15218378694** [comment]
> > `dangerouslyInsertHtml` 不能保证样式完全一样。
> > 如果你要 100% 还原 135编辑器的样式，wangEditor5 不支持。可以考虑用 wangEditor4
> 
> hi，你好这边，我们考虑降级到4版本，但是碰到一个二次开发的问题，我想重写4版本的图片编辑的，这边我看4的文章没有相关的钩子，想说作者这边有什么思路么？ eventHooks.imgClickEvents 这个么？

请问解决了吗
