### ISSUE TITLE
nuxt 2.0 maxLength 插件不按预期工作

### ISSUE THREAD

**Issue by lirongrong-github** [wangeditor-team/wangEditor#4823]
## bug 描述

*`insertFragment` 函数 不触发(普通的vue2.0 项目可以正常工作) 可能时我引入错误  请查看 `components/Editor/index.vue`  `initEditor`*

## 你预期的样子是？

*希望 `insertFragment` 正常工作*

## 系统和浏览器及版本号

- 操作系统 win11
- 浏览器和版本 Google Chrome | 105.0.5195.102（正式版本） （64 位）

## wangEditor 版本

*5.1.15*

## demo 能否复现该 bug ？

能

## 在线 demo

https://stackblitz.com/edit/nuxt-starter-asmzjh?file=pages/index.vue

## 最小成本的复现步骤

- 步骤一 复制浏览器的文本内容
- 步骤二 粘贴至编辑器中 控制台没有任何输出
- 步骤三 复制编辑器中刚才粘贴的任意长度内容 在粘贴  正常输出

**Comment by wangfupeng1988** [comment]
是必须配置了 maxLength ，才会复现这个 bug 吗？

如没有 maxLength ，会复现吗？

**Comment by lirongrong-github** [comment]
其实写的这个demo 和 maxLength 都没有关系了。  我是把源码中的maxLength拿出来做了一个自定义plugin  发现 在粘贴页面的文本时不会正确的触发 `components/Editor/module/maxLength/index.js`  中的 ` e.insertFragment` 可以查看控制台 的console.log

### 最小成本的复现步骤
- 步骤一 复制demo COPY HERE 的文本内容
- 步骤二 粘贴至编辑器中 浏览器控制台没有任何输出(` e.insertFragment` 没有触发)
- 步骤三 复制编辑器中刚才粘贴的任意长度内容 在粘贴 正常输出(` e.insertFragment` 正常触发)

*抱歉没有正确的表达问题*？
