### ISSUE TITLE
v4版本上线遇到的问题在本地无法复现

### ISSUE THREAD

**Issue by DHuihui** [wangeditor-team/wangEditor#4824]
## 问题描述

*请输入遇到的问题...*
项目上线后出现白色背景色
## wangEditor 版本

*v4*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
*没有查到相关bug*
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

 *先输入一段文字，将光标移到文字前面，按下回车，再按下删除按钮。元素审查后发现p标签里增加了一个span标签，并且多了一个背景色为白色的样式。不知道能不能复现成功，因为我是项目上线之后才会有这个问题，在本地启动的项目是无法复现的。*

**Comment by wangfupeng1988** [comment]
v4 已经不再维护了，业余时间不够，还请体谅
