### ISSUE TITLE
升级5.0.1至5.1.0时遇到一些问题

### ISSUE THREAD

**Issue by twosugar** [wangeditor-team/wangEditor#4827]
## 问题描述

项目运行报错，TypeError: document.getElementsByTagName is not a function

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/42201025/189275645-657ad645-32bc-42c8-8206-d251c77bbb2b.png">

## wangEditor 版本

5.1.0

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤
node16环境，5.0.1升级到5.1.0

**Comment by wangfupeng1988** [comment]
如何复现？请描述最低成本的复现步骤
