### ISSUE TITLE
如何设置一键首行缩进

### ISSUE THREAD

**Issue by 373579070** [wangeditor-team/wangEditor#4828]
## 问题描述

如何设置一键首行缩进

## wangEditor 版本

5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

this.editor.select([]) // 全选
this.editor.addMark('indent', '2em')
SlateTransforms.setNodes(this.editor, {
  indent: '2em',
}, {
  mode: 'highest' // 针对最高层级的节点
})

以上两个方法都不能设置到首行缩进，应该如何处理

**Comment by wangfupeng1988** [comment]
初始化编辑器时，html （或 Vue 组件中的 defaultHtml） 赋值 `<p style="text-indent: 2em;"></p>` 试试。
