### ISSUE TITLE
给文字添加超链接,默认生成的a标签都有target ,怎么配置不新窗口打开超链接

### ISSUE THREAD

**Issue by web-xp** [wangeditor-team/wangEditor#4830]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
暂不支持。

你可以对生成的 html 自己替换，去掉 target
