### ISSUE TITLE
在Vue3中注册新菜单Bug

### ISSUE THREAD

**Issue by a1943703375** [wangeditor-team/wangEditor#4831]
## bug 描述
注册新菜单在vue3中，跳转路由后再返回编辑器界面，出现菜单Key值重复的问题，导致编辑器无法显示

![E{T8N)YQ%I9S%`)%UM_2M8Y](https://user-images.githubusercontent.com/59081482/189681990-6805939c-2bae-4516-b287-26d7655dc54f.png)

## 你预期的样子是？
在跳转路由且返回编辑器界面后，编辑器正常显示

## 系统和浏览器及版本号
win11 21H2

User-Agent  :  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33

## wangEditor 版本

wangeditor/editor  :  5.1.15  
 wangeditor/editor-for-vue  :  5.1.12

## demo 能否复现该 bug ？

不能

## 最小成本的复现步骤
1.  创建菜单class 实现接口IButtonMenu
2.  注册菜单到editor，且key值取固定值如  key = ‘menu1’
3. 通过vue-router的router-view，跳转同级的其他组件，然后返回编辑器组件。

## 目前我的解决方法
在Menu中添加属性key，并且在构造函数中给key赋一个随机值。

const menu = new Menu();

const menu1 = {
  key : menu.key 
  factory() {
        return menu;
  },
}

Boot.registerMenu(menu1);

**Comment by a1943703375** [comment]
有没有可能是destory()方法没有删除彻底

**Comment by xshiny** [comment]
你可以只在main.js文件中进行全局注册，其他文件中不用注册
import { Boot } from '@wangeditor/editor'
import attachmentModule from '@wangeditor/plugin-upload-attachment'
// 注册。要在创建编辑器之前注册，且只能注册一次，不可重复注册。
Boot.registerModule(attachmentModule)

**Comment by enjoy-myLife** [comment]
> 你可以只在main.js文件中进行全局注册，其他文件中不用注册 import { Boot } from '@wangeditor/editor' import attachmentModule from '@wangeditor/plugin-upload-attachment' // 注册。要在创建编辑器之前注册，且只能注册一次，不可重复注册。 Boot.registerModule(attachmentModule)

遇到个很离谱的事情，我再注册之前通过Boot.plugin是判断插件是否存在，结果重新刷新页面进入的时候竟然判断插件存在，大无语事件
