### ISSUE TITLE
使用@wangeditor/plugin-formula生成的<span data-w-e-type="formula" ... data-value="1+1="></span>怎么直接展示在前台

### ISSUE THREAD

**Issue by ysypnbh** [wangeditor-team/wangEditor#4832]
## 问题描述
现在就是有一个问题 生成好的公式代码已经放在数据库了， 但是要在网页上展示需要怎么做 类似与readonly， 可以不依赖wangeditor 进行运行, vue版本 3，或者保存成base64 图片也可以，最好还是通过公式转换成功，最好是可以在基础上转换，将来可能还要用在微信小程序，[我看了这个](https://github.com/wangeditor-team/wangEditor/issues/3965#issuecomment-1077472634) 还是没有搞懂什么意思，希望有人可以给一个demo给我，感激不尽😘😘😘
我通过这个可以在前端展示, 但是这个只是针对已生成好的公式
```
<span v-html="html"></span>
import katex from "katex/dist/katex.mjs";
  import "katex/dist/katex.min.css"
var html = katex.renderToString("c = \\pm\\sqrt{a^2 + b^2}", {
    throwOnError: false
  });
```

## wangEditor 版本

"@wangeditor/editor": "^5.1.14",
"@wangeditor/editor-for-vue": "^5.1.12",
"@wangeditor/plugin-formula": "^1.0.11",

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

```
  let s = `<span data-w-e-type="formula" data-w-e-is-void data-w-e-is-inline data-value="1+1="></span>`;
```

**Comment by wangfupeng1988** [comment]
抱歉，这个插件只能支持 `<span data-w-e-type="formula" data-w-e-is-void data-w-e-is-inline data-value="1+1="></span>` 这种格式。

如果不符合你的要求，你可以：
- 自己吧 `<span>...` 这种格式转换为其他格式
- 自己冲洗各一个 formula 插件，自定义你想要的输出格式
