### ISSUE TITLE
Editor/Toolbar组件能否增加className属性

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [wangeditor-team/wangEditor#4833]
## 功能描述

希望 Editor/Toolbar 组件增加 className 属性，而不是使用 style

<img width="890" alt="image" src="https://user-images.githubusercontent.com/26433572/189798687-4ba3a807-3c6d-4ce5-9fbb-d143d39dc8a5.png">

<img width="794" alt="image" src="https://user-images.githubusercontent.com/26433572/189798715-a8a8ea3d-f967-4e1c-b91c-35618c632ed0.png">

https://zh-hans.reactjs.org/docs/dom-elements.html#style

![image](https://user-images.githubusercontent.com/26433572/189798997-67a4b18c-c1fc-4a5c-91a6-45e7c0552d68.png)

## 提炼几个功能点

```
import { Editor, Toolbar } from '@wangeditor/editor-for-react';

        <Toolbar
          className={xxx}
        />
        <Editor
          className={xxx}
        />
```

**Comment by hahaaha** [comment]
@AttackXiaoJinJin 你的版本的是1.0.5版本么。。。最新版本是支持的

**Comment by AttackXiaoJinJin** [comment]
> @AttackXiaoJinJin 你的版本的是1.0.5版本么。。。最新版本是支持的

噢噢，看到了，但每次发包，能带上 changelog 吗，不然不知道更新了啥新功能。。

https://github.com/wangeditor-team/wangEditor-for-react/releases/tag/v1.0.5

我先 close 了，感谢！

**Comment by hahaaha** [comment]
@AttackXiaoJinJin 后续发包我加下changelog
