### ISSUE TITLE
获取已删除的图片逻辑错误

### ISSUE THREAD

**Issue by axolo** [wangeditor-team/wangEditor#4834]
## 功能描述

文档中“获取已删除的图片”逻辑错误，未考虑原文含图片被删除的情况。

若原始已有内容中存在图片，则应将原始图片列表纳入计算。

## 提炼几个功能点

- 获取原有图片列表
- 纳入全部图片之中
- 已删除图片 = 全部图片 - 新增图片

## 原型图

无

## 可参考的案例

无

**Comment by wangfupeng1988** [comment]
那可以在编辑前后，分别通过 `getElementsByType` 获取图片元素 https://www.wangeditor.com/v5/API.html#getelemsbytype

最后在保存时，做 diff ，就可以找出哪些图片被删除了。
