### ISSUE TITLE
v4升级到v5后工具栏没有样式

### ISSUE THREAD

**Issue by DHuihui** [wangeditor-team/wangEditor#4835]
## 问题描述

*v4升级到v5之后工具栏没有样式，但是功能是正常的，也没有报错*

## wangEditor 版本

*v5.1.15*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是,没有查到相关问题*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

-  在git上clone的demo，项目用的是vue+iview
- 
![image](https://user-images.githubusercontent.com/37361111/189826809-5503958a-4b0d-4964-ad90-e0a0c44c425c.png)

**Comment by wangfupeng1988** [comment]
目测是没有引入 css 

参考官网 vue 的 demo 吧

**Comment by DHuihui** [comment]
引入了css，但是现在鼠标经过效果被遮挡了
![image](https://user-images.githubusercontent.com/37361111/190035728-a6409d37-6233-4a69-bfdb-4cf623469b05.png)

**Comment by wangfupeng1988** [comment]
你来这里做一个 demo 吧。能复现问题即可，demo 越简单越好

以下三选一

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/
