### ISSUE TITLE
table点击进入编辑editor.isFocused()问题

### ISSUE THREAD

**Issue by zhangdaliang** [wangeditor-team/wangEditor#4836]
问题描述：

1、如果编辑器存在table表格，点击table表格中某一项（必须），使编辑器进入编辑状态
2、此时同步查看onFocus回调中editor的editor.isFocused()返回值为false，异步返回为true
3、仅table会出现此情况
![image](https://user-images.githubusercontent.com/16433862/189829197-dd7b713a-1320-47b5-9a66-c50461a69e6d.png)
![image](https://user-images.githubusercontent.com/16433862/189829539-9033fa7e-cc75-4f05-99bb-0b0954bb2e12.png)
![image](https://user-images.githubusercontent.com/16433862/189829564-6de5975c-3aa6-44d8-8b17-da0e8c9890d2.png)

**Comment by wangfupeng1988** [comment]
已修复，请升级最新版 `@wangeditor/editor`
