### ISSUE TITLE
图片上传配置的自定义插入会导致onSuccess与onFailed失效

### ISSUE THREAD

**Issue by shikangsheng** [wangeditor-team/wangEditor#4837]
## bug 描述

*因为服务端 response body 格式不一致，所以采用自定义插入图片，结果导致onSuccess与onFailed失效*

## 你预期的样子是？

**采用自定义插入图片，onSuccess与onFailed生效

## 系统和浏览器及版本号

- Win11 21H2
- Microsoft Edge 版本 105.0.1343.33 (正式版本) (64 位)

## wangEditor 版本

*wangEditor V5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 采用自定义插入图片
- 步骤二
- 步骤三

**Comment by shikangsheng** [comment]
感谢作者，忘了说，视频上传配置也是这个问题-------- 原始邮件 --------发件人： 王福朋 ***@***.***>日期： 2022年9月13日周二 下午4:33收件人： wangeditor-team/wangEditor ***@***.***>抄送： 天上月 ***@***.***>, Author ***@***.***>主    题： Re: [wangeditor-team/wangEditor] 图片上传配置的自定义插入会导致onSuccess与onFailed失效 (Issue #4837)

已复现。

你可以先在 customInsert 中处理回调，待我修复完之后，我在这里回复你。

**Comment by wangfupeng1988** [comment]
@shikangsheng 好的，我到时一起看

**Comment by wangfupeng1988** [comment]
已修复，请升级最新版 `@wangeditor/editor`

**Comment by shikangsheng** [comment]
好的，感谢作者-------- 原始邮件 --------发件人： 王福朋 ***@***.***>日期： 2022年9月15日周四 下午4:04收件人： wangeditor-team/wangEditor ***@***.***>抄送： 天上月 ***@***.***>, Mention ***@***.***>主    题： Re: [wangeditor-team/wangEditor] 图片上传配置的自定义插入会导致onSuccess与onFailed失效 (Issue #4837)

已修复，请升级最新版 @wangeditor/editor

**Comment by shikangsheng** [comment]
作者你好，我已将版本更新到5.1.16，但配置自定义插入图片后回调函数依旧不起作用


从 Windows 版邮件发送

发件人: 王福朋
发送时间: 2022年9月15日 16:04
收件人: wangeditor-team/wangEditor
抄送: 天上月; Mention
主题: Re: [wangeditor-team/wangEditor] 图片上传配置的自定义插入会导致onSuccess与onFailed失效 (Issue #4837)

已修复，请升级最新版 @wangeditor/editor

**Comment by wangfupeng1988** [comment]
试试这个 demo 可以吗？ https://github.com/wangeditor-team/server
