### ISSUE TITLE
上传图片后默认style未设置width="100%"导致图片无法宽度100%填充。

### ISSUE THREAD

**Issue by mayuxian** [wangeditor-team/wangEditor#4839]
## 上传图片后默认style未设置width="100%"导致图片无法宽度100%填充。

*当自定义上传图片后，代码如下：*
``` javascript
  config.MENU_CONF['uploadImage'] = { 
    // 自定义上传
    async customUpload(
      file: File,
      insertFn: (url: string, alt?: string, href?: string) => void
    ) {
      const url = await uploader.uploadAsync(file, file.name)
      insertFn(url, '', url)
    },
  }
```
图片toHtml之后为<img  style=''/>，style的宽度样式默认未设置100%，导致图片宽度默认不是全部填充，在手机端展示时，图片宽度和超出手机的宽度。 同时style样式对象不可扩展，也暂未找到可以单独设置style的api。

## 你预期的样子是？

*img的elemToHtml中将width默认设置成100%，也可以兼容PC端和移动端展示*

## 系统和浏览器及版本号

- window 10
- chrome  v105.0.5195.102

## wangEditor 版本

*v5.1.15*

## demo 能否复现该 bug ？

能 
 

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by zhangdaliang** [comment]
不一定非要用insertFn来插入
组装一个imageNode 自己插入
![image](https://user-images.githubusercontent.com/16433862/189860691-5414eb77-94c8-4f4f-9fb6-ddd7b3b3b784.png)

**Comment by wangfupeng1988** [comment]
> 上传图片后默认style未设置width="100%"导致图片无法宽度100%填充

默认是这样的，不会设置宽度。

**Comment by zhangdaliang** [comment]
> > > 上传图片后默认style未设置width="100%"导致图片无法宽度100%填充
> > 
> > 
> > 默认是这样的，不会设置宽度。
> > 有什么办法给他加一下样式吗作者大佬react里面
> > ![image](https://user-images.githubusercontent.com/57971548/199188092-c7e7803c-7364-476f-b465-7e6c32fd35e5.png)
> 
> 上面这个朋友说的使用insertNode插入行不通报找不到这个方法 ![image](https://user-images.githubusercontent.com/57971548/199188449-d7270889-ecaf-4a0e-925a-a2a071a9080a.png)

您好  你上传完成之后 通过闭包 把图片地址传到你的组件内部
在这个函数作用域内， 没有editor对象的
在你组件内部，你已经拿到了图片的地址，你可以做任何事情

**Comment by yonghua-wu** [comment]
> 

既然编辑器在插入图片时默认只有30%、50%、100%的宽度，那为什么不给个默认值呢？

**Comment by mayuxian** [comment]
@wangfupeng1988 我的建议和 @yonghua-wu 一致，首次插入图片默认了100%的宽度，若用户不更改，是不是应该保持一致，给个默认值100%。如果不设置，则是不是应该在100%增加个“原始图片大小”的选项。

**Comment by 123luoxu** [comment]
// 返回数据
                    let src = res.result.imageUrl[0]
                    // insertFn(src)
                    // 自定义上传图片宽度                    
                    const node = {type: "image",  src ,style: { width: "100%" }, children: [{ text: "" }],};           
                    this.editor.insertNode(node);                    
                    this.$message({type: "success",message: "上传成功", });
