### ISSUE TITLE
react中我该如何动态修改editor配置，每次监听配置变化重新render，editor会报错。

### ISSUE THREAD

**Issue by xiaohehennuli** [wangeditor-team/wangEditor#4840]
## 问题描述

react中我该如何动态修改editor配置，每次监听配置变化重新render，editor会报错。
## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 每当max（富文本最大输入长度）发生变化的时候，重新生成key，销毁组件从新render
-![image](https://user-images.githubusercontent.com/48360574/189867030-136e6081-a937-497c-84de-634e198ae61b.png)
- 步骤二
- 绑定key到组件
- ![image](https://user-images.githubusercontent.com/48360574/189867191-d8c65868-f3f9-4b4e-abb7-6f44654a7898.png)
- 步骤三
- 外部传参
- ![image](https://user-images.githubusercontent.com/48360574/189867482-7ea98580-cf1f-400c-85b0-b3f9f69e283f.png)
- 步骤四
- 报错信息
-<img width="1493" alt="image" src="https://user-images.githubusercontent.com/48360574/189867610-d30b8843-233e-431d-882e-f8b806270772.png">

**Comment by xiaohehennuli** [comment]
工具栏可以用这种方法更新，editor就会报错。不知道咋回事

**Comment by wangfupeng1988** [comment]
为何要传入 key 属性？ `<Editor>` 组件不需要这个属性

**Comment by xiaohehennuli** [comment]
这个key是我用来重新渲染组件的，react中组件的key发生变化会重新渲染组件。

**Comment by xiaohehennuli** [comment]
每次外部配置发生改变我就去改变这个key，重新渲染editor就报错了，或者我有什么其他办法当组件配置更新时，我去渲染组件

**Comment by hahaaha** [comment]
@xiaohehennuli 有可以复现的demo么。。。我这边没有复现出来
