### ISSUE TITLE
源码中 `genPatchFn` 为什么没有初始化 `attributesModule`呢？

### ISSUE THREAD

**Issue by dream-unicorn** [wangeditor-team/wangEditor#4841]
## 问题描述
![image](https://user-images.githubusercontent.com/52687004/190047059-6dac2883-0093-4554-977d-edbf6355c2ca.png)

我在定义新元素的时候发现 h函数传 svg 无效，查看源码，发现没有初始化 `attributesModule`

## wangEditor 版本 v5

**请问是出于什么考虑而没有加上这个呢**

## 是否查阅了文档 ？
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E6%96%B0%E5%85%83%E7%B4%A0) ）

*是*

**Comment by wangfupeng1988** [comment]
我有空加一下

**Comment by dream-unicorn** [comment]
感谢作者

**Comment by dream-unicorn** [comment]
> 我有空加一下

感谢回复

**Comment by wangfupeng1988** [comment]
已修复，请升级最新版 `@wangeditor/editor`

**Comment by dream-unicorn** [comment]
> 已修复，请升级最新版 `@wangeditor/editor`

感谢作者
