### ISSUE TITLE
v5版本在vue3使用时表格的基本样式要手动添加，否则在页面引用的时候表格是没有样式

### ISSUE THREAD

**Issue by Prometheusxiao** [wangeditor-team/wangEditor#4842]
## 功能描述

*在使用表格时，如果把获得的数据直接放到web页面时，表格没有样式，比较丑，所以建议增加点功能，能编辑表格基本的样式。*

## 提炼几个功能点

- 功能1：边框线大小与颜色。
- 功能2：表头的背景颜色。
- 功能3：表内容的背景颜色。

## 原型图

*无*

## 可参考的案例

*无*

**Comment by wangfupeng1988** [comment]
这些建议早已记录了。

后续有空了我再加。
