### ISSUE TITLE
editor.getHtml()方法获取html内容，'<' 和  '>' 字符被替换成了 ‘&lt;’ 和 ‘&gt;’

### ISSUE THREAD

**Issue by lcmomo** [wangeditor-team/wangEditor#4843]
## 问题描述

*使用editor.getHtml() 方法，"<"和">" 被转义为了"&lt ; " "&gt ; "..*

## wangEditor 版本

*5.1.11*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
官网【获取html】demo
 https://www.wangeditor.com/demo/get-html.html
- 步骤二
- 输入文本中包含<和>字符
- 步骤三
输出的html内容中，"<"和">" 被转义为了“&lt;  “和”&gt; “

**Comment by wangfupeng1988** [comment]
这个符合预期。要方式 XSS 攻击。
