### ISSUE TITLE
有点击整个toolbar事件回调函数吗？

### ISSUE THREAD

**Issue by yangjie2021** [wangeditor-team/wangEditor#4848]
## 问题描述
使用react版本的toolbar，工具栏漂浮内容上方的，点击工具栏的任何一个位置都会触发父元素的点击事件，想阻止事件冒泡，但是没找到回调函数
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/19945710/190547811-211bd00c-5898-4f28-adb3-bd0bdca17cce.png">
## wangEditor 版本
"@wangeditor/editor": "^5.1.16",
"@wangeditor/editor-for-react": "^1.0.5",

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

- 工具栏漂浮内容上方，点击工具栏的任何一个位置
- 没有回调函数

**Comment by wangfupeng1988** [comment]
“父元素”是什么？你的组件结构是什么样子的，把 JSX 结构发一下看看。

**Comment by yangjie2021** [comment]
> “父元素”是什么？你的组件结构是什么样子的，把 JSX 结构发一下看看。

就是父级div

<img width="706" alt="image" src="https://user-images.githubusercontent.com/19945710/190564231-b1aa78ad-13e2-455f-b67a-9c4f68466f6e.png">

**Comment by yangjie2021** [comment]
> “父元素”是什么？你的组件结构是什么样子的，把 JSX 结构发一下看看。

就是父级div

<img width="706" alt="image" src="https://user-images.githubusercontent.com/19945710/190564231-b1aa78ad-13e2-455f-b67a-9c4f68466f6e.png">

**Comment by yangjie2021** [comment]
> “父元素”是什么？你的组件结构是什么样子的，把 JSX 结构发一下看看。

就是父级div
<img width="706" alt="image" src="https://user-images.githubusercontent.com/19945710/190564231-b1aa78ad-13e2-455f-b67a-9c4f68466f6e.png">

**Comment by yangjie2021** [comment]
> “父元素”是什么？你的组件结构是什么样子的，把 JSX 结构发一下看看。

就是父级div

<img width="706" alt="image" src="https://user-images.githubusercontent.com/19945710/190564231-b1aa78ad-13e2-455f-b67a-9c4f68466f6e.png">

**Comment by yangjie2021** [comment]
> “父元素”是什么？你的组件结构是什么样子的，把 JSX 结构发一下看看。
如图所示，onClick事件对toolbar标签不起作用
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/19945710/190564646-32b4cabf-7d48-43f9-a2d1-b85b000776bd.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/19945710/190564698-b4096e8b-a427-4ab1-b50e-91165d909a5f.png">

**Comment by yangjie2021** [comment]
有暴露回调函数吗，我写个阻止冒泡就好了，看源码头疼，，，写了90%了，哎，，，在线急等大神指点，，，

**Comment by wangfupeng1988** [comment]
先加一层 div 阻止冒泡吧，如下图

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/9583120/190574277-8dfa7dc8-38ff-4828-ac77-e11a58baeded.png">

**Comment by yangjie2021** [comment]
试过了 ，不行，因为外层的点击实际上是react-sortable这个插件触发的，这个插件好像有bug，我再定位定位，谢谢你啦

**Comment by yangjie2021** [comment]
问题已解决，react-sortable插件点击的事件不是通过click触发的，而是pointerdown和mousedown，我开始阻止错了事件，现在好了，谢谢大神~
