### ISSUE TITLE
建议添加锚点功能

### ISSUE THREAD

**Issue by HHaoWang** [wangeditor-team/wangEditor#4849]
## 功能描述

就像TinyMCE一样，可以增加锚点，方便在长文章编写时作者可以维护一个目录以便快速导航

## 功能点

- 锚点支持

## 可参考的案例

* [TinyMCE](https://www.tiny.cloud/) 首页示例-Insert-Anchor

**Comment by wangfupeng1988** [comment]
参考 https://www.wangeditor.com/demo/catalog.html
