### ISSUE TITLE
node v18: Error loading tslib helper library

### ISSUE THREAD

**Issue by OrrinHatch** [wangeditor-team/wangEditor#4851]
## 问题描述

*当我在本地运行yarn dev时发生了一个错误*

## wangEditor 版本

*最新 latest*

## 是否查阅了文档 ？
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 将node版本提升到17.0.0以上版本, tslib包不支持node v17.0.0以上版本
- [tslib iss#286](https://github.com/ezolenko/rollup-plugin-typescript2/issues/286)

**Comment by wangfupeng1988** [comment]
你是指运行源码吗？

**Comment by wushuang5112** [comment]
这个问题我也遇到了，怎么没说解决方法就关闭了？
