### ISSUE TITLE
设置自定义字体后，getHTML返回值无法正常回显（v5）

### ISSUE THREAD

**Issue by LonHon** [wangeditor-team/wangEditor#4852]
## 关键字
v5  getHTML  自定义字体

## bug 描述

设置自定义字体的内容，再次渲染会丢失字体样式span、黑体、宋体等能正常回显

---

![图1](https://user-images.githubusercontent.com/19330620/190686281-ebe0c574-1ec3-46b4-a563-11314ee345ad.png)

顶部显示getHTML 返回值，在下图 createEditor() 时候作为 ’html‘ 值，此时会丢失该设置字体的 span

---

![image](https://user-images.githubusercontent.com/19330620/190688638-1c4b9042-8af0-443a-b8d3-6a802404fc97.png)

---

此时会丢失字体span

![图2](https://user-images.githubusercontent.com/19330620/190686637-acddf25d-6efa-4b7e-b2c3-28c9a11a4f40.png)

## 你预期的样子是？

期望能将getHTML获取的值原样显示

***or能告知此处format移除自定义字体的逻辑和相关代码处***

## wangEditor 版本

[v](tag: @wangeditor/editor@5.1.15)

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/set-html.html
## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
在 [demo](https://www.wangeditor.com/demo/get-html.html) 中设置一个字体，getHtml 得到的 HTML 有正常的`引号`。如下

```html
<p>hello <span style="font-family: 黑体;">world</span></p>
```

而你 getHtml 获取的 HTML中，字体那里不是`引号`，而是 `&quot;`（如下图）。

![](https://user-images.githubusercontent.com/19330620/190686281-ebe0c574-1ec3-46b4-a563-11314ee345ad.png)

**Comment by lisirgo** [comment]
@LonHon   我这边也复现了楼上的问题，主要原因是引入中间带空格的新字体后（比如PingFang SC、Microsoft YaHei、Helvetica Neue等），再经过getHtml()方法会自动转译为&quot；，而之所以 @wangfupeng1988  没有复现是因为目前编辑器中的字体都是中文，不包含中间带空格的状态。
我目前的处理方式是在提交后端之前通过content.replace(/&quot;/gi, ''); 进行处理的；

**Comment by liushaofenggithub** [comment]
&quot问题我也遇到了，firefox浏览器getHtml不会又&quot,chrome和edge会，请问有好的解决办法吗

**Comment by liushaofenggithub** [comment]
这个问题就是因为字体中间有空格，比如 Times New Roman这种，getHtml()就会把前后加上&quto，得到的结果是&qutoTimes New Roman&quto，firefox浏览器可以得到正常结果，chrome不行，烦请大佬看下

**Comment by LonHon** [comment]
贴一个自己的解决方案，也是手动替换掉文本来处理的。

@liushaofenggithub 可以看看

![image](https://user-images.githubusercontent.com/19330620/196323449-b2ae67aa-2007-410a-b3b3-543bb8822e9d.png)
