### ISSUE TITLE
拷贝含表格的内容进编辑区后显示出现表格样式异常问题

### ISSUE THREAD

**Issue by felixwu18** [wangeditor-team/wangEditor#4853]
[8.21水岸东里项目登记公告（定稿）(1).docx](https://github.com/wangeditor-team/wangEditor/files/9591368/8.21.1.docx)
## bug 描述

从本地word文档拷贝含表格的内容时，拷贝进编辑区域会出现表格样式异常

## 你预期的样子是？

显示为原文档内表格的样式状态

## 系统和浏览器及版本号

- 操作系统  
        mac or windows
- 浏览器和版本 
       Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)

## wangEditor 版本

       "@wangeditor/editor": "^5.1.14",
       "@wangeditor/editor-for-vue": "^1.0.2",

## demo 能否复现该 bug ？
       能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- `https://codepen.io/`
- https://stackblitz.com/

## 最小成本的复现步骤

</div></body></html>
文档显示情况：
<img width="1059" alt="test" src="https://user-images.githubusercontent.com/38354886/190850389-a7d2d3f3-14b8-4f72-a8af-0f3930524e30.png">

拷贝改内容进编辑区后显示情况：
<img width="1265" alt="test2" src="https://user-images.githubusercontent.com/38354886/190850421-fc586aca-7b9f-4a67-a58c-430997e1b4ae.png">

**Comment by wangfupeng1988** [comment]
wangEditor 无法完全还原 word 样式，暂时只能先保证内容一致。

样式，等后面有时间再慢慢优化。

**Comment by felixwu18** [comment]
> 
谢谢，如果我们可以零时修复下样式，建议从哪个部分或如何着手呢
