### ISSUE TITLE
提交的视频无法清空

### ISSUE THREAD

**Issue by hanhuafeng** [wangeditor-team/wangEditor#4854]
## bug 描述

我为wangEditor做了一个双向绑定，然后清空了绑定的内容，但是在上一次上传的视频内容未被清空

## 你预期的样子是？

初始化成最开始的编辑框

## 系统和浏览器及版本号

- 操作系统
  macos monterey
- 浏览器和版本
  谷歌浏览器 103.0.5060.134

## wangEditor 版本

5.1.18

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 绑定wangEditor的内容
   例如绑定一个html
- 在wangEditor中上传视频
- `this.html = ''`或者 `this.html = '<p><br></p>'`
- 再次查看wangEditor，会发现其他内容都被清空了，但是视频区域未清空

**Comment by wangfupeng1988** [comment]
`再次查看wangEditor` 这里的“再次”是什么时机？是执行了 `this.html = '<p><br></p>'` 之后吗？
