### ISSUE TITLE
输入文字时，回车后行距过大，看html是新增了一个div，有什么办法不新增或调小行距

### ISSUE THREAD

**Issue by Evinzj** [wangeditor-team/wangEditor#4855]
回车后行距过大，看html是新增了一个div，有什么办法不新增或调小行距

**Comment by wangfupeng1988** [comment]
请按照 issue 模板提交问题，否则不予受理

**Comment by Evinzj** [comment]
已解决，修改换行都的div样式，具体如下
`.w-e-text-container .placeholder{
		top: 0px;
	}
	.w-e-text p, .w-e-text h1, .w-e-text h2, .w-e-text h3, .w-e-text h4, .w-e-text h5, .w-e-text table, .w-e-text pre{
		margin: 0;
	}`
