### ISSUE TITLE
建议可以在需要设置颜色的地方添加色盘，增强可选择性

### ISSUE THREAD

**Issue by phidiaLam** [wangeditor-team/wangEditor#4857]
## 功能描述

*字体颜色那边可以选择色盘*

## 提炼几个功能点

- 可以让使用者自定义颜色

## 原型图
类似与这种的色盘
![image](https://user-images.githubusercontent.com/67498817/190949677-39d31652-4a22-4129-b379-923807563d9f.png)

**Comment by wangfupeng1988** [comment]
感谢反馈

这个早已记录，目前没时间做

**Comment by xxiaobai-ran** [comment]
支持用户自己开发吗？这个功能很需要啊
