### ISSUE TITLE
根据步骤安装并运行demo失败报错

### ISSUE THREAD

**Issue by fdj0926** [wangeditor-team/wangEditor#4858]
## 问题描述
Module parse failed: Unexpected token
*请输入遇到的问题...*

## wangEditor 版本
wangEditor5
*请输入内容……*
Module parse failed: Unexpected token (12886:18)
You may need an appropriate loader to handle this file type.
|
|   const prevLocale = this.locale;
|   this.locale = { ...prevLocale,
|     strings: { ...prevLocale.strings,
|       ...locale.strings

 @ ./node_modules/@wangeditor/editor-for-vue/dist/index.esm.js 1:19-103
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/view/Tests.vue
 @ ./src/view/Tests.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js 
## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 安装两个组件
- 步骤二
- 复制源代码
- 步骤三
- 运行然后报错

**Comment by wangfupeng1988** [comment]
参考官网 Vue demo 源码即可
