### ISSUE TITLE
在保存删除的图片时

### ISSUE THREAD

**Issue by fdj0926** [wangeditor-team/wangEditor#4861]
## 问题描述

*请输入遇到的问题...*

我用的vue2，在提交编辑器的时候可以通过this.editor.getElemsByType('image')获取当前的图片，所有的图片则通过onInsertedImage(imageNode)来实现，但是怎么用数组来接收所有的图片呢？我所有的图片allName放在data里，该怎么赋值呢？
```
 MENU_CONF: {
          insertImage: {
            // 插入图片
            onInsertedImage(imageNode) {
              if (imageNode == null) return
              const { src, alt, url, href } = imageNode
              // const allName1 = []
              // allName1.push(alt)
              this.allName1.push(alt)
              console.log('inserted image', src, alt, url, href)
              
            },
```
他会显示allName1未定义，因为他俩都在data中
## wangEditor 版本
v5

*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

**Comment by wangfupeng1988** [comment]
你这是 vue 或者 js 的问题，不是 wangEditor API 或 bug

你的项目环境，上下文我不知道，我也解决不了。
