### ISSUE TITLE
是否可以采用iframe隔离内容区域，就像tinymce编辑器一样。目前内容区域样式很容易受到外界影响

### ISSUE THREAD

**Issue by ice-musru** [wangeditor-team/wangEditor#4863]
## 问题描述

内容区域样式，很容易受到外界css影响。一般项目都会引入一些reset样式，比如h1,h2等样式的粗体处理没有了。直接导致编辑器内的样式也受到影响

## wangEditor 版本

最新的版本

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
wangEditor 没有采用 iframe 的模式。

如有大量 css 污染，可考虑使用 shadow DOM 方式 https://github.com/wangeditor-team/wangEditor/blob/master/packages/editor/examples/shadow-dom.html
