### ISSUE TITLE
高亮工具栏

### ISSUE THREAD

**Issue by wumei-jpg** [wangeditor-team/wangEditor#4865]
## 问题描述
请问我如果添加了几个自定义工具栏按钮（图标是从数组中渲染来的），设置格式也正常，我怎么在设置完格式后高亮工具栏呢
<img width="533" alt="image" src="https://user-images.githubusercontent.com/109733891/191155265-fc464bb6-69d6-49c9-9a83-5a50ff02ef80.png">

**Comment by wangfupeng1988** [comment]
什么叫“高亮工具栏”？

**Comment by wumei-jpg** [comment]
> 什么叫“高亮工具栏”？

比如点击加粗按钮时，加粗图标会变灰色，点击链接时，链接图标变灰色，再点击应用了相应格式的选区后，对应的图标会添加上背景色（高亮）

**Comment by wangfupeng1988** [comment]
这是菜单里的 `isActive` 和 `isDisabled` 两个方法决定的，可以参考“引用”菜单源码 https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/blockquote/menu/BlockquoteMenu.ts
