### ISSUE TITLE
svg格式图片无法在编辑器显示

### ISSUE THREAD

**Issue by xufenghu** [wangeditor-team/wangEditor#4867]
## bug 描述
svg格式图片无法在编辑器显示 html有这个图片节点  就是没办法正常回显  png格式的图片 是正常的
已经下载最新版本的5.0.1 版本了

## 你预期的样子是？
svg可以正常显示  和 png格式一样

## 系统和浏览器及版本号
windows系统  浏览器是谷歌

## wangEditor 版本
@wangeditor/editor是5.0.1 版本

**Comment by wangfupeng1988** [comment]
参考这里的回复 https://github.com/wangeditor-team/wangEditor/issues/4864
