### ISSUE TITLE
script引入

### ISSUE THREAD

**Issue by Simon-liezi** [wangeditor-team/wangEditor#4868]
## 问题描述

*请输入遇到的问题...*
在使用script引入wangeditor5时，报错：Object.defineProperty() cannot be used on an Immer draft
## wangEditor 版本
wangEditor5
*请输入内容……*
因为特殊情况，必须再vue2项目中使用script标签引入wangEtditor组件，然后在elementUI表单打开时再创建该组件
创建完以后我第一次打字没有问题，然后第二次打字开始就会报以上错误，并且无法删除
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤因为特殊情况，必须在vue2项目中使用script标签引入wangEtditor组件，然后在elementUI表单打开时再创建该组件
- 步骤二创建完以后我第一次打字没有问题，然后第二次打字开始就会报以上错误，并且无法删除
- 步骤三

**Comment by waerly** [comment]
遇到了同样问题

**Comment by ddIvan** [comment]
一样的问题 纯js页面下使用 设置了html后 开始编辑就会报错
