### ISSUE TITLE
批量上传图片时，并未按照选择顺序插入图片

### ISSUE THREAD

**Issue by vinokobe** [wangeditor-team/wangEditor#4869]
## 问题描述

*上传图片使用自定义上传，批量上传图片时，并未按照选择顺序插入图片*

## wangEditor 版本

*@wangeditor/editor": "5.0.1", "@wangeditor/editor-for-vue": "1.0.1"*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 1.批量选择多张图片上传
- 2.图片插入的顺序和用户选择的顺序不一致

**Comment by wangfupeng1988** [comment]
下载、启动这个 demo  https://github.com/wangeditor-team/server ，可以复现吗？
