### ISSUE TITLE
自定义图片上传如何实现图片插入到编辑器？

### ISSUE THREAD

**Issue by coderlcb** [wangeditor-team/wangEditor#4870]
## 问题描述

上代码
```
editorConfig.MENU_CONF!['uploadImage'] = {
  // 自定义上传
  async customUpload(file: File, insertFn: InsertFnType) {
    console.log(file)
    const form = new FormData()
    form.set('file', file)
    uploadImage(form)
      .then(({ status, url, alt, href }) => {
        console.log(status)
        if (status === 200) {
          message.success('上传成功！')
          //上传成功
          insertFn(url, alt, href)
        }
      })
      .catch(() => {
        message.success('上传失败！')
      })
  },
}
```
成功上传并返回了自定义的res `{status,url,alt,href }`,如何把文件插入到编辑器呢？

## wangEditor 版本

    "@wangeditor/editor": "^5.1.18",
    "@wangeditor/editor-for-vue": "^5.1.12",

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

无

**Comment by wangfupeng1988** [comment]
你把代码改成如下的样子（先不管上传，先插入一张百度 logo 图片试试），看能成功吗？

```js
async customUpload(file: File, insertFn: InsertFnType) {
    insertFn('https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png', '百度', 'https://www.baidu.com/')
  },
```

**Comment by coderlcb** [comment]
> 你把代码改成如下的样子（先不管上传，先插入一张百度 logo 图片试试），看能成功吗？
> 
> ```js
> async customUpload(file: File, insertFn: InsertFnType) {
>     insertFn('https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png', '百度', 'https://www.baidu.com/')
>   },
> ```

可以成功，但是为什么我请求返回的参数都是有的，就是把变量放进去就失效

**Comment by wangfupeng1988** [comment]
`insertFn` 测试成功了，剩下的就只能靠你自己调试了

**Comment by a15218378694** [comment]
> > 你把代码改成如下的样子（先不管上传，先插入一张百度 logo 图片试试），看能成功吗？
> > ```js
> > async customUpload(file: File, insertFn: InsertFnType) {
> >     insertFn('https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png', '百度', 'https://www.baidu.com/')
> >   },
> > ```
> 
> 可以成功，但是为什么我请求返回的参数都是有的，就是把变量放进去就失效

请问这问题解决了吗

**Comment by coderlcb** [comment]
> > > 你把代码改成如下的样子（先不管上传，先插入一张百度 logo 图片试试），看能成功吗？
> > > ```js
> > > async customUpload(file: File, insertFn: InsertFnType) {
> > >     insertFn('https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png', '百度', 'https://www.baidu.com/')
> > >   },
> > > ```
> > 
> > 
> > 可以成功，但是为什么我请求返回的参数都是有的，就是把变量放进去就失效
> 
> 请问这问题解决了吗

我的问题是后端返回的参数拼写错了，正常按格式返回的话是没问题的。
