### ISSUE TITLE
绘图工具绘制的图片  用wangEditor编辑器的api插入后 无法显示

### ISSUE THREAD

**Issue by xufenghu** [wangeditor-team/wangEditor#4871]
## bug 描述

绘图工具绘制的图片  用wangEditor编辑器的api插入后 无法显示

## 你预期的样子是？
绘制的图片 可以 正常插入到编辑器中显示

## 系统和浏览器及版本号
windows系统

## wangEditor 版本
5.1.18版本

## demo 能否复现该 bug ？

不能

**Comment by wangfupeng1988** [comment]
什么图片？

什么 API ？

**Comment by xufenghu** [comment]
不管是png还是svg的图片  用dangerouslyInsertHtml插入  都无法显示

**Comment by wangfupeng1988** [comment]
在 https://www.wangeditor.com/demo/ ，打开浏览器控制台，执行如下代码

```js
editor.dangerouslyInsertHtml('<img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"/>')
```

可以插入图片到编辑器

**Comment by xufenghu** [comment]
svg可以插入吗    我现在 需要 插入svg图片

**Comment by wangfupeng1988** [comment]
svg 暂不支持
