### ISSUE TITLE
内容包含 换行 时候setHtml bug

### ISSUE THREAD

**Issue by fancyhejianyang** [wangeditor-team/wangEditor#4872]
## bug 描述

*场景为：多个编辑文本切换 显示在编辑器上，一旦内容包含换行时 切换会报错*

## 你预期的样子是？

*正常切换 setHTML*

## 系统和浏览器及版本号

- win10
- Chrome 105.0.5195.127

## wangEditor 版本

 Editor ：最新版或者V5

## demo 能否复现该 bug ？

能

- 中文 [demo https://www.wangeditor.com/demo/](https://js-ju99up.stackblitz.io/)https://js-ju99up.stackblitz.io//
- English [demo https://www.wangeditor.com/demo/?lang=en](https://js-ju99up.stackblitz.io/)https://js-ju99up.stackblitz.io//

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://js-ju99up.stackblitz.io//
- https://stackblitz.com/edit/js-ju99up?file=index.js （代码版）

## 最小成本的复现步骤

- 步骤一 随便输入内容abc，保存
- 步骤二 随便输入内容 def + 含换行 保存
- 步骤三 随便输入内容ghi + 换行， 保存 （此时有temp1 temp2 temp3）
- 步骤四 点击temp3 鼠标点击内容至换行处
- 步骤五 点击temp2 （能够正常切换html 内容 “def ...”）
- 步骤六 点击temp1 （html没更新，控制台有报错）可多次切换 temp1 2 3 穿插focus状态

**Comment by fancyhejianyang** [comment]
![1663728916790](https://user-images.githubusercontent.com/17957478/191404053-70efee4b-9aee-4fda-bafa-ff6bd7b4f860.jpg)

**Comment by wangfupeng1988** [comment]
根据你的步骤操作，没复现这个 bug 呀。如下图

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/9583120/191418090-9a978c2f-80a3-43b8-a940-8acc07d32df7.png">

**Comment by fancyhejianyang** [comment]
https://user-images.githubusercontent.com/17957478/191941474-82ed0fb8-07af-4cec-ba48-bf5b0b547447.mp4
@wangfupeng1988
