### ISSUE TITLE
求问：怎么将node转化成虚拟DOM？

### ISSUE THREAD

**Issue by leidao** [wangeditor-team/wangEditor#4874]
## 问题描述

我在编辑器A创建了一个模版（模版中有一些自定义元素），想在编辑器B中使用该模版，我拿到模版的node，我想把这些node转成虚拟DOM使用或者直接在自定义插件的render-elem中使用node节点。直接使用`SlateTransforms.insertNodes(editor, nodeList)`并不符合我的期望，我是想把模版包裹在一个不可编辑的容器中作为一个整体，请问有什么api可以帮到我。

## wangEditor 版本

5.1.18

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
没太看懂你的问题。

**Comment by wangfupeng1988** [comment]
> 我是想把模版包裹在一个不可编辑的容器中作为一个整体，请问有什么api可以帮到我

这一点，可以参考官方插件的源码 https://www.wangeditor.com/v5/plugins.html

“公式” “附件” “链接卡片” 这些，都是包裹再一个不可编辑器的容器中

**Comment by leidao** [comment]
我想在自定义元素中使用内置的renderElement方法把node转成VNode节点，但是我在导出renderElement时遇到了报错，请问怎么解决
![image](https://user-images.githubusercontent.com/39399843/191491305-03bffd10-2293-41ac-b977-722b6ca3b9d8.png)

**Comment by wangfupeng1988** [comment]
> 把node转成VNode节点

这个得自己写，通过 `h` 函数（具体看文档）

**Comment by leidao** [comment]
我已经实现了对应的自定义元素“render-elem”。
我重新复述下自己的需求吧，我先写好了n个自定义元素，然后根据不同的选择操作生成了模版（n个自定义元素和文本等数据的集合），拿到了该模版对应的node数据，需要根据要求“循环”展示模版的内容并且让模版内容不可编辑，所以我需要在写一个“循环模版”的自定义元素，该元素的子html是模版里内容不定的自定义元素。我在查看了wangEditor的源码后想直接调用renderElement方法获取模版里n个自定义元素的虚拟DOM，现在问题是renderElement没有导出，不知道该怎么拿到该函数，目前是把wangeditor源码放入自己的项目中，但该方法不方便后续升级wangeditor
