### ISSUE TITLE
编辑保存再查看报错 Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0

### ISSUE THREAD

**Issue by liuxionghui** [wangeditor-team/wangEditor#4875]
## bug 描述

*编辑保存再查看报错 Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统 ：windows 10
- 浏览器和版本 google chrome 66.0.3359.170

## wangEditor 版本

*5.1.1*

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 插入网络图片，路径填写111点击保存请求接口
- 步骤二 再次查看该富文本，点击编辑
- 步骤三 页面显示空白，控制台报错，接口有数据返回

**Comment by liuxionghui** [comment]
![image](https://user-images.githubusercontent.com/40048259/191649589-e0e93a8e-e659-4381-9bcf-892dec40ad78.png)

**Comment by liuxionghui** [comment]
在本地显示正常，测试环境才会报错

**Comment by wangfupeng1988** [comment]
> 步骤一 插入网络图片，路径填写111点击保存请求接口

保存的 HTML 内容是什么？

**Comment by liuxionghui** [comment]
"＜p>您好！＜/p><p>【$(proiectName)〕寿已于S(actualTradingDay)确认到账，请查看洋情。 1111</p><p>
&nbsp: &nbsp;系统链接： &nbsp;<a href="$(ncmsUtl)" target="">$(acmsName) =/a></p><p style='text-align: center;’>提醒：本邮件为
皆理不统自动发送，请勿回复。</p><p><br></p>"

**Comment by liuxionghui** [comment]
`"＜p>您好！＜/p><p>【$(prome)〕寿资已于S(actgDay)确认到账，请登灵查看洋情。 1111</p><p>&nbsp: &nbsp;系统链接： &nbsp;<a href="$(nctl)" target="">$(acame) =/a></p><p style='text-align: center;’>提醒：本邮件为不统自动发送，请勿回复。</p><p><br></p>"`

**Comment by liuxionghui** [comment]
现在测试就随便在编辑区输入个11保存再查看都报错了

**Comment by liuxionghui** [comment]
上面那个html块查看详情后面那些1111就是后面加的，保存，再点编辑就是空白，控制台就报红

**Comment by wangfupeng1988** [comment]
> `＜p>您好！＜/p><p>【$(prome)〕寿资已于S(actgDay)确认到账，请登灵查看洋情。 1111</p><p>&nbsp: &nbsp;系统链接： &nbsp;<a href="$(nctl)" target="">$(acame) =/a></p><p style='text-align: center;’>提醒：本邮件为不统自动发送，请勿回复。</p><p><br></p>`

不知道你是怎么给编辑器赋值的，在这个 demo https://www.wangeditor.com/demo/set-html.html 中，用这段 HTML 设置编辑器内容，是正常的。

**Comment by wangfupeng1988** [comment]
还有，这个 `<a href="$(nctl)" target="">$(acame) =/a>` 格式有问题呀

这是编辑器输出的内容吗？是的话，怎么输出这段内容？

**Comment by liuxionghui** [comment]
> 还有，这个 `<a href="$(nctl)" target="">$(acame) =/a>` 格式有问题呀
> 
> 这是编辑器输出的内容吗？是的话，怎么输出这段内容？

那个符号其实是${} 手机扫描没扫正确， 这个格式是能正常显示的，我刚刚又反复操作了一遍，富文本是放在饿了么ui里面抽屉里面的（el-drawer）每次关闭这个抽屉我都会清空内容，大概率是清空这个动作有问题，我是直接把富文本的v-model设置成了“<p>hello</hello>”了，是不是这个操作有问题，要必须用文档里写到的editor. clear(),或者清空之后要销毁富文本，下次打开重新创建富文本才行？

**Comment by liuxionghui** [comment]
> 还有，这个 `<a href="$(nctl)" target="">$(acame) =/a>` 格式有问题呀
> 
> 这是编辑器输出的内容吗？是的话，怎么输出这段内容？

那个符号其实是${} 手机扫描没扫正确， 这个格式是能正常显示的，我刚刚又反复操作了一遍，富文本是放在饿了么ui里面抽屉里面的（el-drawer）每次关闭这个抽屉我都会清空内容，大概率是清空这个动作有问题，我是直接把富文本的v-model设置成了“<p>hello</hello>”了，是不是这个操作有问题，要必须用文档里写到的editor. clear(),或者清空之后要销毁富文本，下次打开重新创建富文本才行？

**Comment by liuxionghui** [comment]
> 那个hello是用p标签包裹的，尖括号被过滤了，用小括号代替一下（p）hello（/p）

**Comment by liuxionghui** [comment]
> > 还有，这个 `<a href="$(nctl)" target="">$(acame) =/a>` 格式有问题呀
> > 这是编辑器输出的内容吗？是的话，怎么输出这段内容？
> 
> 那个符号其实是${} 手机扫描没扫正确， 这个格式是能正常显示的，我刚刚又反复操作了一遍，富文本是放在饿了么ui里面抽屉里面的（el-drawer）每次关闭这个抽屉我都会清空内容，大概率是清空这个动作有问题，我是直接把富文本的v-model设置成了“
> 
> hello”了，是不是这个操作有问题，要必须用文档里写到的editor. clear(),或者清空之后要销毁富文本，下次打开重新创建富文本才行？

那个hello是用p标签包裹的，尖括号被过滤了，用小括号代替一下（p）hello（/p）

**Comment by wangfupeng1988** [comment]
> `<a href="$(nctl)" target="">$(acame) =/a> `

无论你怎么操作的，得到的 HTML 语法是错误的

**Comment by liuxionghui** [comment]
> 还有，这个 `<a href="$(nctl)" target="">$(acame) =/a>` 格式有问题呀
> 
> 这是编辑器输出的内容吗？是的话，怎么输出这段内容？

这不是编辑器输出的内容，是我在下方加了个文本域显示html结构用的，编辑器显示的是一个超链接点击可以修改链接

**Comment by liuxionghui** [comment]
> > `<a href="$(nctl)" target="">$(acame) =/a> `
> 
> 无论你怎么操作的，得到的 HTML 语法是错误的

这不是编辑器输出的内容，是我在下方加了个文本域显示html结构用的，编辑器显示的是一个超链接点击可以修改链接

**Comment by liuxionghui** [comment]
v-model绑定的html结构两个标签之前不能有回车符号吗，因为我刚刚试了只有一个p标签怎么操作都不会出问题的，不是一个标签的时候就出问题了，区别就是中间有个回车符号

**Comment by liuxionghui** [comment]
![Uploading image.png…]()

**Comment by liuxionghui** [comment]
![image](https://user-images.githubusercontent.com/40048259/191941793-3cec5cdc-8411-407f-9e25-d7ef671eb493.png)

**Comment by wangfupeng1988** [comment]
有新的因素，可以再重新提交新 issue 。混在一起讨论内容太多了
