### ISSUE TITLE
版本4.7.9 复制浏览器文本粘贴进editor后，自动携带了<br/>，且输入中文字符异常

### ISSUE THREAD

**Issue by jance-hui** [wangeditor-team/wangEditor#4876]
## bug 描述

复制浏览器文字时，如复制 `你好` ，editor.config.pasteTextHandle  方法中获取到的值是 `你好`。

editor.config.onchange 方法 中获取到的值应该是 `<p>你好</p>`，但实际情况却是 `<p>你好<br/></p>`

将复制的文本保存后，再次打开时（HTML为原先输入的 `<p>你好<br/></p>` ），此时在文字后方输入中文符号（如 `。`），页面会展示两个`。。`，且不会触发 editor.config.onchange 方法。但是在文字后方输入其他文字，则不会出现问题。

经过进一步测试，若想要在 `<p>你好<br/></p>` 后方输入中文符号，需先手工回车换行，再删除方可录入。此时HTML中的  `<br/>` 已移除

> 注：如果粘贴浏览器文本后直接录入中文符号没有问题，但保存后再次打开修改就不行

## 你预期的样子是？

浏览器粘贴的文本应去除  `<br/>` 

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 edge浏览器最新版

## wangEditor 版本

v4.7.9

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

### 问题一：无法输入中文字符
- 步骤一：创建一个editor（v4.7.9），设置默认HTML值，如 `<p>你好<br/></p>` 
- 步骤二：在后方输入中文字符串，如 `。`

### 问题二：粘贴浏览器文本异常
- 步骤一：创建一个editor（v4.7.9），无默认HTML值
- 步骤二：从其他浏览器页面粘贴部分文字
- 步骤三：查看粘贴的文本值 editor.config.pasteTextHandle
- 步骤四：查看实际的HTML值 editor.config.onchange

![SN7_ 1N 51YZ`C)XSQ0 8{R](https://user-images.githubusercontent.com/43159982/191652672-e22710cb-7748-45f4-8b4e-a199005e2f00.png)

**Comment by wangfupeng1988** [comment]
vv4 已经不再维护了。

业余时间不够，目前只能维护 v5。还请体谅~
