### ISSUE TITLE
源码中导出了RENDER_ELEM_CONF，我导入打印时发现是个空对象

### ISSUE THREAD

**Issue by leidao** [wangeditor-team/wangEditor#4879]
## 功能描述

我看在源码core/render中定义了常量“RENDER_ELEM_CONF”并且导出了，我在项目中导入该常量发现是个空对象，请问该怎么获取该对象，我是想获取该常量上所有插件的对应type上的renderElems函数方法

## 提炼几个功能点

![image](https://user-images.githubusercontent.com/39399843/191695180-09ddfe38-0255-41bf-88aa-56282c9701c0.png)

![image](https://user-images.githubusercontent.com/39399843/191694921-6893857e-d10d-4f4e-8734-c5e4ac27c55f.png)

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by leidao** [comment]
找到原因了，查看了源码后发现必须在wangeditor/editor中进行按需导出，作者是否可以把node2Vnode函数也进行导出

**Comment by leidao** [comment]
找到原因了，查看了源码后发现必须在wangeditor/editor中进行按需导出，作者是否可以把node2Vnode函数也进行导出
![image](https://user-images.githubusercontent.com/39399843/191718862-1b5d985a-bc60-4a4e-b46a-00382de0feb2.png)

**Comment by wangfupeng1988** [comment]
这个对二次开发没有用，你想用来干嘛？

PS：导出的模块越少越好，没用的就不导出，减少用户学习成本。

**Comment by leidao** [comment]
我在编辑器A中定义了一个模版，如下图：
![image](https://user-images.githubusercontent.com/39399843/191883295-e7ce6e0f-4b64-4a71-9c1e-f03ecc42c9c7.png)
我需要在编辑器B中循环显示这个模版并且让该模版不可修改，效果如下：
![image](https://user-images.githubusercontent.com/39399843/191883516-8f88073f-c8fd-4551-84ee-dd8c3029eb49.png)
因此我需要node2Vnode这个函数，如下图：
![image](https://user-images.githubusercontent.com/39399843/191883698-addc454d-a2b3-4260-abfc-3e578616c19f.png)

**Comment by wangfupeng1988** [comment]
你这个截图应该是自定义的 [renderElem](https://www.wangeditor.com/v5/development.html#%E5%9C%A8%E7%BC%96%E8%BE%91%E5%99%A8%E4%B8%AD%E6%B8%B2%E6%9F%93%E6%96%B0%E5%85%83%E7%B4%A0) 对吧

![](https://user-images.githubusercontent.com/39399843/191883698-addc454d-a2b3-4260-abfc-3e578616c19f.png)

你看下文档里，renderElem 函数的第二个参数 `children` 本身就是 vnode 类型的，不需要你在遍历、转为 vnode （你画红框的部分）

**Comment by leidao** [comment]
我换了一个思路，不在去自定义元素内操作node，而是在外部使用提供的slate的api做node的替换，之前的问题已经解决了，感觉作者的支持。
