### ISSUE TITLE
如何让自定义的元素像普通文本一样能加粗、加颜色

### ISSUE THREAD

**Issue by Kevin-Loeng** [wangeditor-team/wangEditor#4880]
## 问题描述

*请输入遇到的问题...*
本人仿照[“formula 公式”插件 ](https://github.com/wangeditor-team/wangEditor-plugin-formula)，写了一个插入sql变量的功能，定义了一个元素为sql变量，现在遇到的问题是：
在选中这个自定义元素时，字体加粗菜单、字体颜色菜单等不可用，无法给这个元素里的文字加粗、加字体颜色等。
请问如何实现这个功能呢，让自定义的元素像普通文本一样能加粗、加颜色等。
![示意图](https://i.ibb.co/GWTqscy/2022-09-22-8-51-18.png "示意图")
## wangEditor 版本

5.1.2

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
  把[“formula 公式”插件 ](https://github.com/wangeditor-team/wangEditor-plugin-formula)的源码下载下来
- 步骤二
  按照README.md 运行yarn install 和 yarn dev
- 步骤三
  在富文本框里插入公式，并尝试给公式加粗或加字体颜色

**Comment by wangfupeng1988** [comment]
默认的“加粗”菜单是给文本用的，而你自定义的 elem 不是文本。

所以，你还需要自定义菜单，自定义这个 elem 的加粗样式，自己去实现这一套。

**Comment by Kevin-Loeng** [comment]
> 默认的“加粗”菜单是给文本用的，而你自定义的 elem 不是文本。
> 

[https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/link](https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/link)
感谢回复，
但我看了这个link的源码，link也是自己定义的elem，为什么可以对link加粗？

**Comment by Kevin-Loeng** [comment]
> 默认的“加粗”菜单是给文本用的，而你自定义的 elem 不是文本。
> 

[https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/link](https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/link)
感谢回复，
但我看了这个link的源码，link也是自己定义的elem，为什么可以对link加粗？

**Comment by wangfupeng1988** [comment]
link 元素不是 void 元素，它有 children （内部是 text 节点）

而你自定义的元素模拟的是“数学公式”，是 void 元素，它内部没有 text 节点
