### ISSUE TITLE
基于富文本编译器开发电子病历编译器

### ISSUE THREAD

**Issue by chuanxinLiu** [wangeditor-team/wangEditor#4882]
## 功能描述

*目前国内电子病历编译器长期被都昌（目前国内做的最好的厂商）垄断，收费昂贵；开源的电子病历编译器只有SoDiaoEditor，是基于Ueditor开发的但是实际落地经验不多。可否根据目前最新的wangEditor开发电子病历编译器*

## 提炼几个功能点

- 病历书写
- 多种模式：编辑，只读，留痕等
- 导入导出xml
- ....

## 原型图（都昌编译器）

*![image](https://user-images.githubusercontent.com/50171308/191917741-8fc9a2ea-8548-478f-b1d1-d15ef81fa9be.png)*

## 可参考的案例

*SoDiaoEditor：https://github.com/tlzzu/SoDiaoEditor*
*都昌编译器：http://www.dcwriter.cn:6788/index.html*

**Comment by wangfupeng1988** [comment]
电子病历和富文本编辑器不一样，它是有严格格式控制的，且多种空间都自定义。

如果你想自研，建议找一个编辑器内核（slate.js proseMirror.js 等）自行开发。

PS：如果要兼容 IE 浏览器，那坑会比较多

**Comment by wangfupeng1988** [comment]
我想了解这个电子病历编辑器的需求是怎样的，如果有兴趣交流，可以把联系方式发到我邮箱 wangfupeng1988@163.com
