### ISSUE TITLE
有/无序列表tab不能缩进成2级，tab后shift+tab不能退回

### ISSUE THREAD

**Issue by u373693041** [wangeditor-team/wangEditor#4883]
## bug 描述

有/无序列表tab不能缩进成2级，tab后shift+tab不能退回

## 你预期的样子是？
像quill这样
![20220923162332](https://user-images.githubusercontent.com/48196776/191920292-f9c405a2-08ce-4a19-a0ad-e2afbc3c0edf.gif)

## 系统和浏览器及版本号

- 操作系统 
windows11

- 浏览器和版本 
Microsoft Edge
版本 105.0.1343.42 (正式版本) (64 位)

## wangEditor 版本

5.1.18

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en
![20220923162046](https://user-images.githubusercontent.com/48196776/191919806-cd97b6fc-6d80-4f51-b140-c2a56c997255.gif)

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：创建一个有/无序列表
- 步骤二：按TAB
- 步骤三：再按shift+tab

**Comment by wangfupeng1988** [comment]
这个功能正在开发中

**Comment by wangfupeng1988** [comment]
升级 `@wangeditor/editor` 最新版本，已增加多级列表功能。

**Comment by wangfupeng1988** [comment]
> tab后shift+tab不能退回

没有支持这个快捷键。使用删除键，可以退回
