### ISSUE TITLE
vue2项目引入使用过程中显示找不到getEditor和removeEditor

### ISSUE THREAD

**Issue by Klayt11** [wangeditor-team/wangEditor#4885]
## 问题描述

*vue2项目引入使用过程中显示找不到getEditor和removeEditor*
![image](https://user-images.githubusercontent.com/49483537/191938598-715795ef-2a1b-4db1-955b-9955307a6fed.png)

## wangEditor 版本

"@wangeditor/editor": "^0.13.4",
"@wangeditor/editor-for-vue": "^1.0.2"

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

``<template>
  <div style="border: 1px solid #ccc; z-index: 100">
    
    <Toolbar
      :editor-id="editorId"
      :default-config="toolbarConfig"
      style="border-bottom: 1px solid #ccc"
    />
    
    <Editor
      :editor-id="editorId"
      :default-config="editorConfig"
      :default-content="getDefaultContent"
      style="height: 500px"
      @onChange="onChange"/>
  </div>
</template>
import { Editor, Toolbar, getEditor, removeEditor } from '@wangeditor/editor-for-vue'
export default {
  name: 'MyEditor',
  components: { Editor, Toolbar },
  props: {
    // 编辑器的默认内容，只在初始化时使用
    defaultContent: {
      type: Array,
      required: false
    },
    editorConfig: {
      type: Object,
      required: true
    },
    toolbarConfig: {
      type: Object,
      required: false
    },
    batchId: {
      type: String,
      default: ''
    }
  },
  data() {
    return {
      editorId: `wangEditor-${Math.random().toString()}` // 定义一个编辑器 id ，要求：全局唯一且不变。重要！！！
      // batchId: ''
    }
  },
  computed: {
    getDefaultContent() {
      return cloneDeep(this.defaultContent) // 深拷贝，重要！！！
    }
  },
  created() {},
  beforeDestroy() {
    try {
      const editor = getEditor(this.editorId)
      if (editor == null) return
      editor.destroy() // 组件销毁时，及时销毁编辑器 ，重要！！！
      removeEditor(this.editorId)
    } catch (e) {
      console.log(e)
    }
  },
  methods: {
    onChange(editor) {
      this.$emit('change', editor)
    },
    clear() {
      const editor = getEditor(this.editorId)
      if (editor == null) return
      editor.clear()
    }
  }
}
</script>
<style src="@wangeditor/editor/dist/css/style.css"></style>

`<template>
  <div style="border: 1px solid #ccc; z-index: 100">
    
    <Toolbar
      :editor-id="editorId"
      :default-config="toolbarConfig"
      style="border-bottom: 1px solid #ccc"
    />
    
    <Editor
      :editor-id="editorId"
      :default-config="editorConfig"
      :default-content="getDefaultContent"
      style="height: 500px"
      @onChange="onChange"/>
  </div>
</template>`

**Comment by wangfupeng1988** [comment]
> "@wangeditor/editor": "^0.13.4",
> "@wangeditor/editor-for-vue": "^1.0.2"

这俩升级最新版本

然后参考文档的写法 https://www.wangeditor.com/v5/for-frame.html#vue2

**Comment by Klayt11** [comment]
这能向下兼容吗&nbsp;&nbsp;
项目用的vue2.5.17版本&nbsp;&nbsp;


我看最新时支持vue3的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月24日(星期六) 中午12:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] vue2项目引入使用过程中显示找不到getEditor和removeEditor (Issue #4885)





  
***@***.***/editor": "^0.13.4",
 ***@***.***/editor-for-vue": "^1.0.2"
  
这俩升级最新版本
 
然后参考文档的写法 https://www.wangeditor.com/v5/for-frame.html#vue2

**Comment by wangfupeng1988** [comment]
@Klayt11 兼容 vue2 vue3 ，具体看文档
