### ISSUE TITLE
Problem calling text from php sql database

### ISSUE THREAD

**Issue by Arabiain** [wangeditor-team/wangEditor#4886]
Problem calling text from php sql database
Please how do I solve the problem I tried every way it didn't work fetching texts to the editor.

![image](https://user-images.githubusercontent.com/8568779/192095280-785c1ed7-2ab6-4d96-a939-acd89cd9cfb7.png)

![image](https://user-images.githubusercontent.com/8568779/192095305-716f073b-a8ec-49a0-a2ef-6e851ff6e6f0.png)

**Comment by Arabiain** [comment]
![image](https://user-images.githubusercontent.com/8568779/192096052-ea11877c-8e79-4ca8-9dbb-28bf7e0883a9.png)

**Comment by wangfupeng1988** [comment]
PHP 代码我不了解。

**Comment by Arabiain** [comment]
`<?php
try{
$pdo = new PDO("mysql:host=localhost;dbname=demo", "root", "");
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch(PDOException $e){
die("ERROR: Could not connect. " . $e->getMessage());
}
try{
$sql = "SELECT * FROM Book_Text WHERE id='150'";  
$result = $pdo->query($sql);
if($result->rowCount() > 0){
while($row = $result->fetch()){
$Text=$row['Text_book'];
}
unset($result);
} else{
echo "No records matching your query were found.";
}
} catch(PDOException $e){
die("ERROR: Could not able to execute $sql. " . $e->getMessage());
}
unset($pdo);
?>
`

![image](https://user-images.githubusercontent.com/8568779/192162717-f7bafbf3-1c69-4097-b6e7-d2c442677d3f.png)

![image](https://user-images.githubusercontent.com/8568779/192162762-8d2b0d49-9a47-4521-bc05-f4ad9de39b35.png)


![image](https://user-images.githubusercontent.com/8568779/192162783-14024b9f-9c20-4f91-86aa-ff08d0752292.png)

**Comment by wangfupeng1988** [comment]
看你截图的报错，这明显是 JS 的语法错误，不是 editor 的 API 或使用错误。

自己调试一下吧。

**Comment by altriri** [comment]
Please help and write a specific example to call the data from the database with the complete java script code

**Comment by wangfupeng1988** [comment]
这里有各种 demo https://www.wangeditor.com/demo/
