### ISSUE TITLE
自定义插件是否可以重写移动光标-键盘左右健的事件

### ISSUE THREAD

**Issue by leidao** [wangeditor-team/wangEditor#4889]
## 问题描述

我想在自定义插件时重写移动光标 -> 重写onKeydown事件，但是在editor上没有导出onKeydown事件，请问有其他合适的api么
![image](https://user-images.githubusercontent.com/39399843/192206741-da4ee339-6f14-4c7b-8929-05646378a65a.png)

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
重写 editor [API](https://www.wangeditor.com/v5/API.html) 参考[插件](https://www.wangeditor.com/v5/development.html#%E5%8A%AB%E6%8C%81%E7%BC%96%E8%BE%91%E5%99%A8%E4%BA%8B%E4%BB%B6%E5%92%8C%E6%93%8D%E4%BD%9C-%E6%8F%92%E4%BB%B6)

如果你想自由的增加 DOM 事件，只能自己通过 DOM 的方式添加，编辑器不支持
