### ISSUE TITLE
如何动态修改菜单名称和图标

### ISSUE THREAD

**Issue by freadman** [wangeditor-team/wangEditor#4890]
## 问题描述

比如我自定义一个“繁简转换”的功能，默认图标显示“简”，点击后执行转换为简体的函数，同时图标转换为“繁”，但是不知道怎么动态修改菜单名称和图标。

## wangEditor 版本

V5

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

无

**Comment by wangfupeng1988** [comment]
简体/繁体，应该用多语言 https://www.wangeditor.com/v5/i18n.html

**Comment by wangfupeng1988** [comment]
菜单图标目前不支持修改

如果真的需要该，可以通过 DOM 方式来替换。每个菜单的 DOM 节点都有 `data-menu-key` 属性，可以通过这个来查找替换。
