### ISSUE TITLE
vue2.6.12版本，安装时出问题

### ISSUE THREAD

**Issue by cz8828723** [wangeditor-team/wangEditor#4891]
## 问题描述

vue2.6.12版本，安装时出问题，package-lock.json文件中，vue版本被篡改为2.7.10，导致启动项目报错（vue和vue-template-compiler版本不统一）

## wangEditor 版本

"@wangeditor/editor": "^5.1.18",
"@wangeditor/editor-for-vue": "^1.0.2",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 npm安装@wangeditor/editor和@wangeditor/editor-for-vue
- 步骤二 启动项目报错
- 步骤三

**Comment by liuqh0609** [comment]
我这里看了一下vue@2.6.11版本在安装依赖的时候lock文件里面锁的版本也是2.7.10（在没装editor相关包的情况下），所以应该不是编辑器包相关的问题。
你可以确认下lock文件在未安装编辑器相关包之前的vue版本，或者查看node_modules文件中实际安装的vue版本号是多少

**Comment by liuqh0609** [comment]
或者给您提供一个解决方案：
重新安装指定版本`@2.6.12`的`vue`和`vue-template-compiler`的包（重新锁定lock文件中的版本）。

造成问题的原因：
猜测造成您这种问题的估计是你重新`install`了vue版本，而且没有指定版本号，导致`^2.6.12`匹配到了符合`semver`规则的`2.7.10`版本

**Comment by cz8828723** [comment]
@liuqh0609  我这边看到在没装editor之前，lock文件中的vue版本是正常的，安装过后更改为2.7.10，然后重装vue指定版本2.6.14，控制台会有警告：
![4)46~$D9`LX(QE(S)ZXB 9S](https://user-images.githubusercontent.com/27753088/192412775-efef60a2-fce9-425d-87f8-2317e69f3190.jpg)
。我测了两个项目，好像用vue2.6.14之后版本安装editor就没问题（测过2.6.14，其它的没测过）。

**Comment by liuqh0609** [comment]
> @liuqh0609 我这边看到在没装editor之前，lock文件中的vue版本是正常的，安装过后更改为2.7.10，然后重装vue指定版本2.6.14，控制台会有警告： ![4)46~$D9`LX(QE(S)ZXB 9S](https://user-images.githubusercontent.com/27753088/192412775-efef60a2-fce9-425d-87f8-2317e69f3190.jpg) 。我测了两个项目，好像用vue2.6.14之后版本安装editor就没问题（测过2.6.14，其它的没测过）。

恩这个我忽略了，editor-for-vue这个包对vue版本有要求
![image](https://user-images.githubusercontent.com/43341115/192413101-4687033d-9e10-4525-b2ca-3630f2fc8c34.png)
2.6.14版本的vue会对你的项目产生影响吗？如果没影响可以用2.6.14及其以上的版本

**Comment by cz8828723** [comment]
好的，感谢，我重装为2.6.12后，目前没有影响使用。另外，要在vue中使用editor，是必须安装editor-for-vue吗？

**Comment by liuqh0609** [comment]
> 好的，感谢，我重装为2.6.12后，目前没有影响使用。另外，要在vue中使用editor，是必须安装editor-for-vue吗？

不是必须使用。
editor-for-vue的目的就是为了让用户快速在vue项目中使用，省去用户自己封装editor的一些步骤。你也可以自己使用editor包自己搞一个vue组件

**Comment by cz8828723** [comment]
谢谢
