### ISSUE TITLE
自定义菜单 Uncaught (in promise) Error: Duplicated key 'xxx' in menu items

### ISSUE THREAD

**Issue by freadman** [wangeditor-team/wangEditor#4892]
## bug 描述

使用Vue3的dialog弹窗组件中嵌入了编辑器，编辑器中使用了扩展菜单。
第一次弹窗没问题，把弹窗关闭再打开，就报这个错。

知道这个是全局注册重复注册错误，但是没搞明白怎么就重复了，弹窗关闭后编辑器不是销毁了吗？我在代码里做了这个销毁的
`// 组件销毁时，也及时销毁编辑器
onBeforeUnmount(() => {
  const editor = editorRef.value;
  if (editor == null) {
    return;
  }
  editor.destroy();
});`

而且实际也是进入了这个生命周期的。
为什么再次打开时报错了呢？要如何处理？

## 你预期的样子是？

不报错

## 系统和浏览器及版本号

- 操作系统
Chrome 105.0.5195.125

## wangEditor 版本
V5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
重复注册菜单，跟销毁编辑器，两者没关系。

你在哪里注册了菜单？可以在这行代码打断点，看看是否重复执行了？

**Comment by freadman** [comment]
> 重复注册菜单，跟销毁编辑器，两者没关系。
> 
> 你在哪里注册了菜单？可以在这行代码打断点，看看是否重复执行了？

我把编辑器封装为了共用组件reEditor，菜单在这个组件注册的，dialog引入了reEditor。
怎么样才能避免重复注册呢？我是按官方教程添加自定义菜单的啊，这是代码：
`// 自定义菜单：查看源码
const viewSourceConf: any = {
  key: "view_source", // 定义 menu key ：要保证唯一、不重复（重要）
  factory() {
    return new ViewSourceMenu(); // 把 `YourMenuClass` 替换为你菜单的 class
  }
};
// 自定义菜单：繁简转换
const zhTranConf: any = {
  key: "zh_tran", // 定义 menu key ：要保证唯一、不重复（重要）
  factory() {
    return new ZhTranMenu(); // 把 `YourMenuClass` 替换为你菜单的 class
  }
};

// 注册自定义菜单
const module: Partial<IModuleConf> = {
  menus: [viewSourceConf, zhTranConf]
};
Boot.registerModule(module);`

**Comment by wangfupeng1988** [comment]
import 以后直接注册，不要在组件的生命周期中注册。参考这里 https://github.com/wangfupeng1988/vue2-wangeditor-demo/blob/master/src/components/MyEditorWithMention.vue#L36

**Comment by youngIdiot** [comment]
大佬我的也是这个问题，我扩展了一个上传附件到菜单，只在一个页面正常，去其他页面的编辑器就报错
`import { Boot } from "@wangeditor/editor";
import attachmentModule from "@wangeditor/plugin-upload-attachment";
Boot.registerModule(attachmentModule);
export default {
  components: { Editor, Toolbar, Sticky },
  data() {
    return {
      editor: null,
      toolbarConfig: {
        insertKeys: {
          index: 21,
          keys: ["uploadAttachment"],
        },
      },
      mode: "default", //标准模式 or 'simple'简洁模式
      loading: false,
    
      editorConfig: {
        placeholder: "请输入内容...",
        MENU_CONF: {
          uploadAttachment: {
            title: "上传附件",
            fieldName: "file",
            // 超时时间
            timeout: 100 * 1000,
            customUpload: this.update, // 上传
          },
          uploadImage: {
            fieldName: "file",
            server: `http://localhost:9000/uploadImage/editor`,
          },
        },
      },
    };
  },
  created() {
    if (this.$route.params && this.$route.params.id) {
      const id = this.$route.params && this.$route.params.id;
      this.getByIdInfo(id);
    }   
  },
  methods: {
    onCreated(editor) {
      this.editor = Object.seal(editor); // 一定要用 Object.seal() ，否则会报错
    },

    update(file, insertFn) {
      console.log("file1", file);
      let formData = new FormData();
      formData.append("file", file);
      console.log(formData);
      coverPhoto.uploadFile(formData).then((response) => {
        insertFn(response.data.name, response.data.url);
      });
    },
 
  beforeDestroy() {
    const editor = this.editor;
    if (editor == null) return;
    editor.destroy(); // 组件销毁时，及时销毁编辑器
  },`

**Comment by gengweihuang** [comment]
我在main.js这边进行注册就可以解决这个问题。
组件那边不要Boot.registerModule(formulaModule)

**Comment by LoveRecall** [comment]
重新再写一个 
<script>
Boot.registerModule(Module)
</script>

这样你代码里有两个script了，这是可以解决的

**Comment by Yutianyudaodao** [comment]
> import 以后直接注册，不要在组件的生命周期中注册。参考这里 https://github.com/wangfupeng1988/vue2-wangeditor-demo/blob/master/src/components/MyEditorWithMention.vue#L36

我这边需要在new的时候传this进去，不能在顶部插入，怎么弄呢
const myMenuConf = {
  key: 'insertGoods',
  factory: function () {
    return new MyMenuClass(that)
  }
}

**Comment by changzhengithub** [comment]
就是这个注册明显没有考虑多场景的使用情况，全局只能注册一次，但是触发按钮的回调是每次都不一样的，里面又不能获取当前组件上下文，就导致只能使用全局的emit事件或者vuex这样的笨方法来各自触发事件。

**Comment by changzhengithub** [comment]
我觉的只要提供一个方法来获取全局已经注册过的菜单就可以解决了

**Comment by lxccc812** [comment]
> 我在main.js这边进行注册就可以解决这个问题。 组件那边不要Boot.registerModule(formulaModule)

解决了么

**Comment by lxccc812** [comment]
> 大佬我的也是这个问题，我扩展了一个上传附件到菜单，只在一个页面正常，去其他页面的编辑器就报错 `import { Boot } from "@wangeditor/editor"; import attachmentModule from "@wangeditor/plugin-upload-attachment"; Boot.registerModule(attachmentModule); export default { components: { Editor, Toolbar, Sticky }, data() { return { editor: null, toolbarConfig: { insertKeys: { index: 21, keys: ["uploadAttachment"], }, }, mode: "default", //标准模式 or 'simple'简洁模式 loading: false,
> 
> ```
>   editorConfig: {
>     placeholder: "请输入内容...",
>     MENU_CONF: {
>       uploadAttachment: {
>         title: "上传附件",
>         fieldName: "file",
>         // 超时时间
>         timeout: 100 * 1000,
>         customUpload: this.update, // 上传
>       },
>       uploadImage: {
>         fieldName: "file",
>         server: `http://localhost:9000/uploadImage/editor`,
>       },
>     },
>   },
> };
> ```
> 
> }, created() { if (this.$route.params && this.$route.params.id) { const id = this.$route.params && this.$route.params.id; this.getByIdInfo(id); } }, methods: { onCreated(editor) { this.editor = Object.seal(editor); // 一定要用 Object.seal() ，否则会报错 },
> 
> ```
> update(file, insertFn) {
>   console.log("file1", file);
>   let formData = new FormData();
>   formData.append("file", file);
>   console.log(formData);
>   coverPhoto.uploadFile(formData).then((response) => {
>     insertFn(response.data.name, response.data.url);
>   });
> },
> ```
> 
> beforeDestroy() { const editor = this.editor; if (editor == null) return; editor.destroy(); // 组件销毁时，及时销毁编辑器 },`

解决了么

**Comment by lxccc812** [comment]
如何在创建编辑器之前注册，插件引入，菜单注册，都是在同一个 <script setup></script> 中书写的，放到onMounted中注册么？

**Comment by lxccc812** [comment]
在页面中手动销毁组件，也不行，还是存在重复注册的问题

**Comment by pengzhiqiang110** [comment]
> 我在main.js这边进行注册就可以解决这个问题。 组件那边不要Boot.registerModule(formulaModule)

我在 main.js里面注册，但是需要const emit = defineEmits(['handleSave'])
传递事件，发现还是不行 事件传递不了
