### ISSUE TITLE
您好，个人建议增加一下字号字体等默认值配置的功能

### ISSUE THREAD

**Issue by FennX** [wangeditor-team/wangEditor#4893]
## 功能描述

如标题，字号字体行高这种的建议增加默认值配置的功能

## 提炼几个功能点
个人认为可以放在MENU_CONF下
MENU_CONF: {
   fontSize: { defaultValue: '9pt', fontSizeList }
},

**Comment by zjp123** [comment]
这个解决没啊，你就关了
