### ISSUE TITLE
placeholder预设值跟内容跟中文汉字重叠在一起

### ISSUE THREAD

**Issue by 18508409531** [wangeditor-team/wangEditor#4897]
## bug 描述
placeholder预设值跟内容跟中文汉字重叠在一起。我看作者已经在4.0.8解决过这个问题，我使用的是v5+版本也有这个问题。
也是搜狗输入法输入中文时重叠，字母跟数字可以。输入中文时不触发onChange事件。

![image](https://user-images.githubusercontent.com/35060559/192515850-0a94822b-3bb1-4bb1-8b67-032dc0dc9e13.png)

## 你预期的样子是？
输入汉字时不显示placeholder预设值

## 系统和浏览器及版本号
- win10操作系统
- 浏览器和版本Chrome63
## wangEditor 版本
  wangEditor: v5+版本

## demo 能否复现该 bug ？

能

## 在线 demo
无

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 使用Chrome63版本浏览器打开demo地址
- 输入中文

**Comment by wangfupeng1988** [comment]
你的 chrome 版本太低了，v5不再支持这么低的版本了

**Comment by sxy98** [comment]
同样问题出现在国产化浏览器，83的Chromium内核，能不能解决一下呢

**Comment by yj-liuzepeng** [comment]
这个问题还存在，有什么好的解决方案吗
