### ISSUE TITLE
建议编辑器菜单默认激活配置

### ISSUE THREAD

**Issue by freadman** [wangeditor-team/wangEditor#4898]
## 功能描述

目前编辑器的菜单需要点击编辑器输入框才激活，默认禁用，存在几个问题：
1、习惯：这种方式第一次看到，不太习惯；
2、需求：有些场景是需要激活编辑器的，比如我目前做的一个”查看源码“的插件，逻辑是点击查看源码，将编辑器的输入框隐藏，然后展示了自己添加的输入框，那问题来了，没有编辑器输入框了，菜单被禁用了，编辑源码后想换回编辑器的输入框，回不去了。

## 提炼几个功能点

- 编辑器菜单是否默认激活可配置；
- 最好能够提供”查看源码“插件（本质是编辑源码）

## 原型图

无

## 可参考的案例

无

**Comment by wangfupeng1988** [comment]
> 点击编辑器输入框才激活，默认禁用

这个后续优化，之前已经记录下来了

**Comment by wangfupeng1988** [comment]
> 2、需求：有些场景是需要激活编辑器的，比如我目前做的一个”查看源码“的插件，逻辑是点击查看源码，将编辑器的输入框隐藏，然后展示了自己添加的输入框，那问题来了，没有编辑器输入框了，菜单被禁用了，编辑源码后想换回编辑器的输入框，回不去了。

可使用 `alwaysEnable = true` ，参考“全屏”菜单 https://github.com/wangeditor-team/wangEditor/blob/master/packages/basic-modules/src/modules/full-screen/menu/FullScreen.ts

**Comment by wangfupeng1988** [comment]
> 最好能够提供”查看源码“插件（本质是编辑源码）

这个目前不会提供，自行扩展吧。
