### ISSUE TITLE
新版本列表问题

### ISSUE THREAD

**Issue by zhangdaliang** [wangeditor-team/wangEditor#4899]
问题描述：
1、空列表换行不自动变普通段了
2、列表项删除键删除如果上方是空列表项，光标不会上移而是直接删除掉了上方空列表项
3、Tab必须在列表项头部才可进行切换层级
4、现有这种分散的格式，就会出现当列表中间某一项变成普通行时，比如1 2 3变成 1 普通行 3 此时的3就会变成1，因为无法确定3跟上面的1是否有关系，就会造成列表序列断开，而且本身毫无关系的列表，通过删除中间普通行，又会变成有序关系的情况。
5、列表可以无限Tab缩进下一级
建议：列表项还是需要包裹在ul ol中，避免多个列表之间关系模糊，目前我这边是通过获取当前list-item的父node确定当前li的level，可参考以下效果。
![image](https://user-images.githubusercontent.com/16433862/192665797-0aca809c-1a5d-4451-81c7-531d43118e06.png)

**Comment by wangfupeng1988** [comment]
> 1、空列表换行不自动变普通段了

删除空列表即可

**Comment by wangfupeng1988** [comment]
> 2、列表项删除键删除如果上方是空列表项，光标不会上移而是直接删除掉了上方空列表项

这个我记录下，后续优化

**Comment by wangfupeng1988** [comment]
> 3、Tab必须在列表项头部才可进行切换层级

故意这么设置的。在列表尾部、中间，依然可以使用  tab 输入空格

**Comment by wangfupeng1988** [comment]
> 4、现有这种分散的格式，就会出现当列表中间某一项变成普通行时，比如1 2 3变成 1 普通行 3 此时的3就会变成1，因为无法确定3跟上面的1是否有关系，就会造成列表序列断开，而且本身毫无关系的列表，通过删除中间普通行，又会变成有序关系的情况。

这个我没看懂，你单独提交 issue 吧，举个例子。

**Comment by wangfupeng1988** [comment]
> 5、列表可以无限Tab缩进下一级

不做限制，用户自由操作即可

**Comment by wangfupeng1988** [comment]
> 建议：列表项还是需要包裹在ul ol中，避免多个列表之间关系模糊，目前我这边是通过获取当前list-item的父node确定当前li的level，可参考以下效果。

包裹层级过多会有很多 bug ，稳定性不好，这次重构就修复了 list 相关的近 10 个 bug 

你如果喜欢这种嵌套的模式，可以继续使用你的方法。

**Comment by zhangdaliang** [comment]
> > 建议：列表项还是需要包裹在ul ol中，避免多个列表之间关系模糊，目前我这边是通过获取当前list-item的父node确定当前li的level，可参考以下效果。
> 
> 包裹层级过多会有很多 bug ，稳定性不好，这次重构就修复了 list 相关的近 10 个 bug
> 
> 你如果喜欢这种嵌套的模式，可以继续使用你的方法。

我也想到嵌套多级可能造成的问题，我这种方式只有两级 ul或ol -> li，跟新版本的列表一样，通过计算确定每一个层级的序号和margin-left，使它看起来像是多层级。

**Comment by zhangdaliang** [comment]
> > 4、现有这种分散的格式，就会出现当列表中间某一项变成普通行时，比如1 2 3变成 1 普通行 3 此时的3就会变成1，因为无法确定3跟上面的1是否有关系，就会造成列表序列断开，而且本身毫无关系的列表，通过删除中间普通行，又会变成有序关系的情况。
> 
> 这个我没看懂，你单独提交 issue 吧，举个例子。

好的
