### ISSUE TITLE
Table 组件index.js:21657 Uncaught Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0     at Object.toSlatePoint

### ISSUE THREAD

**Issue by zhangjindong** [wangeditor-team/wangEditor#4900]
https://github.com/wangeditor-team/wangEditor/blob/7d255e08138c7e4bb18991e4fa903059d9aa6d97/packages/core/src/editor/dom-editor.ts#L491

场景：table的使用时；
异常：当 parentNode 为colgroup时，会偶发性的报错。

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5567162/192673158-e8537ec6-752f-4e08-a5a6-9e3f7039f310.png">

**Comment by zhangjindong** [comment]
看起来和这个问题同源；
https://github.com/wangeditor-team/wangEditor/issues/4376#issue-1271725171

**Comment by 2627238826** [comment]
我也复现了，请问啥时候解决呢
![image](https://user-images.githubusercontent.com/13739670/192680458-556c6fe7-f4f4-4eac-9cfd-e6405287999b.png)

**Comment by wangfupeng1988** [comment]
需要写一个具体的复现步骤。

**Comment by 2627238826** [comment]
> 需要提供一个具体的复现步骤。

https://github.com/wangeditor-team/wangEditor/issues/4376#issue-1271725171

**Comment by wangfupeng1988** [comment]
4376 已经记录，有时间了就修改
