### ISSUE TITLE
无法粘贴内容到编辑器；粘贴出现重复行； 遇到这2个BUG

### ISSUE THREAD

**Issue by jqsl2012** [wangeditor-team/wangEditor#4903]
是v5版本；

### 1. 无法粘贴内容到编辑器

都是app端，夸克浏览器，从别的地方，比如微信聊天记录、手机自带的便签、公众号文章等里面复制内容到编辑器，手机端夸克浏览器会出现内容粘贴进编辑器，但是getHtml()为空的情况，作者可以通过这个描述来复现BUG，100%出现。一定要在编辑器里面长按，出现粘贴2个字后，点粘贴。100%出现，我试过很多次了，我的朋友也试过很多次，是100%必出的。

### 2. 粘贴出现重复行

也是从别处复制内容，粘贴到 欢太浏览器(oppo手机自带浏览器)，就会出现。

**Comment by wangfupeng1988** [comment]
移动端，目前支持不好。编辑器体验也不好。
