### ISSUE TITLE
自定义菜单无法与VUE组件传递参数

### ISSUE THREAD

**Issue by letong520** [wangeditor-team/wangEditor#4906]
## 功能描述

公司有基于VUE做的图片选择器组件，添加自定义菜单后，无法控制图片选择器的弹出与关闭，选择图片后的参数也无法插入到内容中

## 提炼几个功能点

- 自定义菜单点击时能够有自定义回调，并且能够实现参数互传

## 原型图

![image](https://user-images.githubusercontent.com/109790245/192754780-5de4a76b-9da3-4afb-879e-03e4d2c8f969.png)

## 期望
点击“插入图片”后弹出组件，选择图片后能够将图片插入内容中

## 可参考的案例

https://github.com/wangeditor-team/wangEditor/issues/4598

**Comment by wangfupeng1988** [comment]
> 点击“插入图片”后弹出组件

这个肯定是可以实现的，参考你提到的 4598 issue 即可

**Comment by letong520** [comment]
研究了一早上完美搞定，非常感谢
