### ISSUE TITLE
自定义粘贴事件当复制的word内容包含一级标题时，获取不到rtf数据

### ISSUE THREAD

**Issue by white-0419** [wangeditor-team/wangEditor#4909]
## bug 描述

*自定义粘贴事件中，当复制的word内容包含一级标题时，使用 event.clipboardData.getData('text/rtf')，获取不到rtf数据，显示为空*

## 你预期的样子是？

*可以获取到rtf数据*

## 系统和浏览器及版本号

-win10
- 谷歌105.0.5195.127

## wangEditor 版本

*5.1.14*

## demo 能否复现该 bug ？

不能

## 在线 demo

https://codepen.io/white-0602/pen/rNvJPJP

## 最小成本的复现步骤

- 步骤一：新建一个word，输入一段文字，将其设置为一级标题
- 步骤二：复制粘贴至富文本中
- 步骤三：打印自定义粘贴事件中的rtf

**Comment by wangfupeng1988** [comment]
编辑器中就是使用原生 event 参数获取的，没做自己的处理。

这样，你自己搞一个 HTML demo ，在 `<div contenteditable="true"></div>` 中监听粘贴事件，看看能否获取 rtf 数据？

**Comment by white-0419** [comment]
感谢回复，尝试过后确实获取不到。
最近在做复制word图片和文字内容至富文本框，目前主要功能已实现；但一旦遇到一级标题，就获取不到rtf数据，请问您有什么好的解决方案能指点一下吗？
我的思路是
①先获取html和rtf，然后找到html中的所有img标签，提取src；
②从rtf中获取图片数据集合，转成base64
③将src和base64一一替换
④在img标签外添加div标签，因为在span中图片会被过滤掉
⑤将处理好的html数据给富文本编辑器。

**Comment by white-0419** [comment]
感谢回复，尝试过后确实获取不到。
最近在做复制word图片和文字内容至富文本框，目前主要功能已实现；但一旦遇到一级标题，就获取不到rtf数据，请问您有什么好的解决方案能指点一下吗？
我的思路是
①先获取html和rtf，然后找到html中的所有img标签，提取src；
②从rtf中获取图片数据集合，转成base64
③将src和base64一一替换
④在img标签外添加div标签，因为在span中图片会被过滤掉
⑤将处理好的html数据给富文本编辑器。

**Comment by wangfupeng1988** [comment]
没啥好办法，其实就你说的这些。

**Comment by white-0419** [comment]
好的，谢谢您
