### ISSUE TITLE
页面引入组件显示“编辑区域高度 < 300px 这可能会导致 modal hoverbar 定位异常”；

### ISSUE THREAD

**Issue by Qinhongxin** [wangeditor-team/wangEditor#4911]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
有啥问题？

**Comment by Qinhongxin** [comment]
浏览器控制台报了这个错，我根据文档修改编辑区的高度也无法解决这个问题。定位异常，导致输入的内容无法被识别到

**Comment by wangfupeng1988** [comment]
官网 demo 就没有这个提示，根据 demo 改一下

**Comment by LBipanda** [comment]
> 浏览器控制台报了这个错，我根据文档修改编辑区的高度也无法解决这个问题。定位异常，导致输入的内容无法被识别到

你解决这个问题了吗？我设置高度超过300，还是报这个警告
