### ISSUE TITLE
Added a search and replace feature for some text

### ISSUE THREAD

**Issue by altriri** [wangeditor-team/wangEditor#4912]
Welcome
After trying this editor, I found that it is the best text editor and very excellent. Thank you very much, but it needs some necessary features, including:
Added a search and replace feature for some text, formatting, and colors. Sometimes I need to search for numbers and replace them with a specific color and style.
Add a feature to copy a specific format such as a color and apply it directly with simple steps.

**Comment by wangfupeng1988** [comment]
抱歉，这些暂不支持。
