### ISSUE TITLE
如何在插入图片时给图片添加crossorigin属性？

### ISSUE THREAD

**Issue by earlyCloud** [wangeditor-team/wangEditor#4913]
## 问题描述

*如题*

## wangEditor 版本

*5.1.14*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
编辑器暂不支持。

可以在生成 HTML 后，用正则表达式替换上。
