### ISSUE TITLE
如何用enter回车而不是shift+enter?

### ISSUE THREAD

**Issue by heweicong** [wangeditor-team/wangEditor#4914]
## 问题描述

*请输入遇到的问题...*
只能用shift+enter回车
## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
该问题已经记录了 https://github.com/wangeditor-team/wangEditor/issues/4301
