### ISSUE TITLE
React版本的标题菜单展开方向不会随光标调整，推测是React版本的CSS原因

### ISSUE THREAD

**Issue by PrinOrange** [wangeditor-team/wangEditor#4915]
## bug 描述

wangEditor的[React版本](https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js)选择标题菜单永远只是向上展开，不会随光标调整展开方向。

[原生js版本的demo](https://www.wangeditor.com/demo/index.html)中的效果是符合预期的，选择一段文字后弹出的标题菜单，方向会根据是否划到顶端和划到底端，决定向下展开还是向上展开。
当光标在顶端时，会向下展开
![image](https://user-images.githubusercontent.com/73331790/193270571-62eebdaf-3265-4114-9812-38b6824248e6.png)

当光标在底端时，向上展开
![image](https://user-images.githubusercontent.com/73331790/193270698-8e21a63e-846b-4d25-ae1d-39f8bdc53a31.png)

但是，React版本无论是在个人项目还是[官方项目的Demo](https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js)上，**无论如何都是向上展开的，划到顶后也不会向下展开。**
![image](https://user-images.githubusercontent.com/73331790/193270973-f88edaaf-860c-485e-b3c3-395c62b61032.png)

所以，React版本中会导致一个问题，就是标题菜单很可能会被别的元素覆盖掉。
![1](https://user-images.githubusercontent.com/73331790/193271281-dde72e80-7b90-4e3c-ac63-712bfd08cf83.png)

**我尝试着检查了下这个问题，推测，很可能是CSS的原因。**

我用devtools检查了下标题菜单的CSS，
这个是原生js版本的CSS
![image](https://user-images.githubusercontent.com/73331790/193272116-a1406bf3-4284-488a-9fa5-e9362780b979.png)
这个是React版本的CSS
![image](https://user-images.githubusercontent.com/73331790/193271878-b2d1e8f8-da06-456f-8ce0-4131c586dce6.png)

发现React版本的CSS，比原生版本的CSS多了一条`.w-e-bar-bottom`的类规则。

所以我推测，可能是原生js版本之前出现过这个问题，修复后，React版本的CSS没有及时跟上，所以希望React版本也修复这个问题。

## 你预期的样子是？

让React版本的标题菜单能像原生js版本的标题菜单一样，根据光标位置，调整展开方向。

## 系统和浏览器及版本号

- Windows 10
- Chrome系浏览器 v100+

## wangEditor 版本

在React项目中安装了这两个包：
 "@wangeditor/editor": "^5.1.20",
 "@wangeditor/editor-for-react": "^1.0.5",

## demo 能否复现该 bug ？

可以。

## 最小成本的复现步骤

打开[React版本的demo](https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js)，先打出一行字，并鼠标选中它，在弹出的菜单中选择标题，观察展开方向，永远是向上展开，而不是向下展开。
但是在[原生js版本的demo](https://www.wangeditor.com/demo/index.html)中，是向下展开的。

**Comment by hahaaha** [comment]
@PrinOrange 你把react版本的demo宽度拉大一些，这个是因为太窄了导致的
