### ISSUE TITLE
Cannot read properties of null (reading 'getConfig')

### ISSUE THREAD

**Issue by lengyibai** [wangeditor-team/wangEditor#4916]
![image](https://user-images.githubusercontent.com/74140255/193318899-13b1a463-3aea-4b00-8fca-667a8c6aaa1c.png)
![image](https://user-images.githubusercontent.com/74140255/193318907-4d036a2f-accb-48df-9bf8-2961fdb61477.png)
![image](https://user-images.githubusercontent.com/74140255/193318943-90f85fd0-428f-41fc-8dcd-907c52b3ec58.png)

**Comment by wangfupeng1988** [comment]
猜测 editior 是 null 

可以参考官网的 demo ，看看如何执行 editor API （既然可以执行 API ，editor 肯定不是 null）
