### ISSUE TITLE
无法实现像ueditor一样可以粘贴推文形式的html

### ISSUE THREAD

**Issue by BurstLink35** [wangeditor-team/wangEditor#4918]
## 问题描述

wangEditor无法实现像ueditor一样可以粘贴推文形式的html
ueditor效果：
![O 08FHZNOK1`DS)O162Y D](https://user-images.githubusercontent.com/82110281/193576133-a5ede44b-87b6-461a-9754-f384f6a8c983.jpg)
wangEditor效果：
![7FE(K}$BQ8OA8%7S08HZ_M9](https://user-images.githubusercontent.com/82110281/193576156-a8084a11-68dc-414b-a8ff-9c7edaa1826a.jpg)

## wangEditor 版本

5.1

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

**Comment by wangfupeng1988** [comment]
不默认支持

要实现这一点需要你自定义组件，具体看文档，或参考官网的插件，

**Comment by BurstLink35** [comment]
请问可以说一下具体在文档的哪一部分吗 谢谢

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E6%96%B0%E5%85%83%E7%B4%A0  这里

可以实现的各种效果，参考插件 https://www.wangeditor.com/v5/plugins.html
