### ISSUE TITLE
普通html+js如何使用插件

### ISSUE THREAD

**Issue by rain-sjh** [wangeditor-team/wangEditor#4921]
## 问题描述

普通html+js如何使用插件啊,我想使用附件功能,但是没有相关文档

## wangEditor 版本

v5

## 是否查阅了文档 ？

是

## 最小成本的复现步骤
- 步骤一
- 引入CDN
- 步骤二
- 使用基础功能都很顺利,但是想实现上传附件功能,不需要太复杂,上传后显示链接即可

**Comment by wangfupeng1988** [comment]
参考这个 https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html
