### ISSUE TITLE
上传图片后修改图片尺寸

### ISSUE THREAD

**Issue by zhangYinfei0927** [wangeditor-team/wangEditor#4922]
## 功能描述
如图，图片上传后修改尺寸目前有30%，50%，100%的选项；
能否多加几个选项或者修改其中一个选项

![1665199612023](https://user-images.githubusercontent.com/115332655/194685902-2f22ad05-5f5a-41b5-81a3-534f0d0e807c.png)

**Comment by zhangYinfei0927** [comment]
或者有没有可能拖动图片的时候改的不是具体的px值而是百分比呢
以及视频的尺寸设置只能固定值不可以百分比
感谢回复~

**Comment by wangfupeng1988** [comment]
默认不支持

如有需要可以自定义扩展菜单，具体看文档 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E6%96%B0%E8%8F%9C%E5%8D%95
