### ISSUE TITLE
插入html，html里面带了table标签，编辑器没有识别出来

### ISSUE THREAD

**Issue by fengjujiao** [wangeditor-team/wangEditor#4923]
## 问题描述

*插入html，html里面带了table标签，编辑器没有识别出来，变成了几个span标签*

## 是否已查阅文档？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

- 步骤一
- 将此段html插入编辑区
```
<p class="zhc-p zhc-title2">请点击对应选项分别查询:
</p><div class="zhc-form"><table class="zhc-table zhc-formtableA"><tbody><tr><td><a href="javascript:void(0);" onclick=AutoSendMsg("查询开户行名称")>查询开户行名称</a></td></tr><tr><td class="zhc-tdbtm"><a href="javascript:void(0);" onclick=AutoSendMsg("查询开户支行地址")>查询开户行地址</a></td></tr></tbody></table></div>
```
- 步骤二
- 编辑区的table标签没有了，只有几个span标签了
- 步骤三

**Comment by fengjujiao** [comment]
原文标签内容
`<p class="zhc-p zhc-title2">请点击对应选项分别查询:
</p><div class="zhc-form"><table class="zhc-table zhc-formtableA"><tbody><tr><td><a href="javascript:void(0);" onclick=AutoSendMsg("查询开户行名称")>查询开户行名称</a></td></tr><tr><td class="zhc-tdbtm"><a href="javascript:void(0);" onclick=AutoSendMsg("查询开户支行地址")>查询开户行地址</a></td></tr></tbody></table></div>`

**Comment by fengjujiao** [comment]
原文内容标签：
'<p class="zhc-p zhc-title2">请点击对应选项分别查询:
</p><div class="zhc-form"><table class="zhc-table zhc-formtableA"><tbody><tr><td><a href="javascript:void(0);" onclick=AutoSendMsg("查询开户行名称")>查询开户行名称</a></td></tr><tr><td class="zhc-tdbtm"><a href="javascript:void(0);" onclick=AutoSendMsg("查询开户支行地址")>查询开户行地址</a></td></tr></tbody></table></div>'

**Comment by wangfupeng1988** [comment]
div 内部的标签，暂时无法精细处理
