### ISSUE TITLE
`editor.clear()` 不能清掉编辑器内的视频

### ISSUE THREAD

**Issue by wadefelix** [wangeditor-team/wangEditor#4924]
## bug 描述

视频时通过 videoUpload 插入的，后调用 `editor.clear()`， 编辑器内的文本被清除了（符合预期），但是 视频还在没有被清除（不符预期吧）；

- 操作系统 windows 10
- 浏览器和版本 Microsoft Edge
版本 106.0.1370.34 (正式版本) (64 位)

## wangEditor 版本

wangEditor 版本  5.1.20

**Comment by wangfupeng1988** [comment]
升级 `@wangeditor/editor` 最新版本试试
