### ISSUE TITLE
鼠标选中多行文本，直接修改内容，会重复显示修改的内容

### ISSUE THREAD

**Issue by xpx-github** [wangeditor-team/wangEditor#4925]
## bug 描述

鼠标选中多行文本，然后直接修改文本，会重复显示修改的内容

## 你预期的样子是？

鼠标选中多行文本，然后直接修改文本，能像word一样正常显示修改后的文本

## 系统和浏览器及版本号

- MacBookPro
- Chrome 106.0.5249.61（正式版本） (x86_64)

## wangEditor 版本

wangEditor5

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

- 步骤一 鼠标选中多行文本
- 步骤二 修改文本内容（打汉字）

**Comment by wangfupeng1988** [comment]
我用 Mac Chrome 在官网 demo https://www.wangeditor.com/demo/ 没有复现

你再详细描述一下吧，截几个图贴一下。
