### ISSUE TITLE
insertHtml后立即getHtml，结果不对

### ISSUE THREAD

**Issue by zhm84** [wangeditor-team/wangEditor#4927]
## 问题描述

在最新版wangeditor中，insertHtml后立即getHtml，得到的html和我insert进去的不一致。
insert的html包含列表（ul  ol  li）时，会有上述问题，其他标签没有问题

![insert和get的html不一样](https://user-images.githubusercontent.com/57031862/194749334-4a756c28-3f41-4d52-a4c7-db11eb38ee10.png)

![insert和get的html不一样2](https://user-images.githubusercontent.com/57031862/194749315-8369e1cf-2627-4f40-9e8e-8effe31feca4.png)

## wangEditor 版本

^5.1.21

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
进入https://www.wangeditor.com/demo/
打开控制台
在控制台输入以下内容
![insert和get的html不一样](https://user-images.githubusercontent.com/57031862/194749137-9913cb05-20ae-4a66-b2fc-7db2e5aa5be0.png)

**Comment by wangfupeng1988** [comment]
使用异步吧，如下

```js
editor.dangerouslyInsertHtml('<ol><li>hello</li></ol>');
setTimeout(() => {
    console.log('html:', editor.getHtml());
});
```
