### ISSUE TITLE
设置完默认的行高字体大小之后，数据回显不回来，怎么处理

### ISSUE THREAD

**Issue by lizhengpeng** [wangeditor-team/wangEditor#4928]
## 问题描述

*设置完默认的行高字体大小之后，数据回显不回来*

## wangEditor 版本

*5.0.1*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

**Comment by lizhengpeng** [comment]
![image](https://user-images.githubusercontent.com/25368303/194768401-6f13b23e-6c62-4941-a04a-95e763f50995.png)

**Comment by wangfupeng1988** [comment]
`数据回显不回来` —— 这句话具体什么意思？截个图看看

**Comment by lizhengpeng** [comment]
> 
![image](https://user-images.githubusercontent.com/25368303/194802510-28fb2629-1e6a-4e27-b996-f88540a494d9.png)
我这样配置之后，输入没问题，但是当我点击编辑，想再次显示回来原来的数据的时候，显示不出来

**Comment by lizhengpeng** [comment]
回显回来的是带标签的数据<p>类似这种的</p>,然后用defaultHtml回绑，无法显示

**Comment by wangfupeng1988** [comment]
defaultHtml 和 defaultContent 不能共存。

如果你想使用 HTML 形式来设置默认的行高、字体，就得在 HTML 上设置，这里有写 https://github.com/wangeditor-team/wangEditor/issues/4042

**Comment by wbs99** [comment]
> ![image](https://user-images.githubusercontent.com/25368303/194768401-6f13b23e-6c62-4941-a04a-95e763f50995.png)

![image](https://github.com/user-attachments/assets/bddb5f2e-f520-4010-a520-1908d55abbfa)
v5 的情况下，使用 html 格式，这样设置默认字体大小行高即可，不要通过 jsonContent 的方式
