### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Arabiain** [wangeditor-team/wangEditor#4929]
Welcome
Keyboard shortcuts don't work for me, save and undo doesn't work

Ctrl+S
Ctrl+Z

Is there a way to activate the spelling checker?

**Comment by wangfupeng1988** [comment]
`Ctrl+S` —— Not support yet, you need to implement by yourself

`Ctrl+Z` —— I don't know how to recurrent this bug, need more details.

Activate the spelling checker? —— Not support yet.
