### ISSUE TITLE
css污染导致下划线和加粗在编辑时不显示效果。

### ISSUE THREAD

**Issue by helloJeeee** [wangeditor-team/wangEditor#4932]
## bug 描述

css污染导致下划线和加粗在编辑时不显示效果。

## 你预期的样子是？

css隔离

## wangEditor 版本

最新
## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 添加全局css
- *, body, dd, div, dl, dt, form, h2, h3, h4, h5, h6, input, li, p, select, span, strong h1, table, ul {
                font-weight: 100;
            }
加粗就会没有效果 通过unset也无法隔离这个问题

添加
a, i, img, li, span, strong {
            display: inline-block;
        }
下划线就会没有效果，但是可以通过unset去隔离

**Comment by wangfupeng1988** [comment]
暂不支持

css 问题需要你自己处理
