### ISSUE TITLE
Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by panghaoyuan** [wangeditor-team/wangEditor#4933]
## 问题描述

*wengEdit 老数据写入编辑器时报错*

报错信息为

`Cannot read properties of null (reading 'length')`

## wangEditor 版本

"@wangeditor/editor": "5.1.14",
"@wangeditor/editor-for-react": "1.0.4",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

@wangeditor/editor-for-react的1.0.4 版本的 refactor改动导致不兼容老数据
[1.0.4改动内容](https://github.com/wangeditor-team/wangEditor-for-react/commit/92c064d37689f9269595b12c7fdb08f50671c52d#diff-847f65a492b37b234130c1d8298df19552725d96ae9fdb77a9b32246ce2a574cL61-R61)

复现地址
https://codesandbox.io/s/wangedit-demo-9vu31h

修改package.json中的 @wangeditor/editor-for-react 即可复现  1.0.3(无问题) <=> 1.04(有问题)

**Comment by panghaoyuan** [comment]
> @arliang 更新到1.0.6可以插入了，但最好数据格式要标准化掉。。。你给的数据中的img 需要用p包起来

**Comment by panghaoyuan** [comment]
## 问题
@hahaaha  换成1.0.6报错误啊? 
`Cannot resolve a DOM node from Slate node: {"text":""}`
![image](https://user-images.githubusercontent.com/28645409/199385360-6096bb3e-fb70-45e1-9c4e-848bf0e97306.png)

## 疑问
demo中提供的数据是 wangEditor低版本生成的。官方有提供数据格式化工具吗？能让低版本数据标准化到高版本。

**Comment by hahaaha** [comment]
@panghaoyuan 保存的提示依然保存。。。毕竟还是要让你知道数据上有一些问题的。。。只是不再会在导致白屏了。。。你在网页中不开控制台是不受影响的。。。demo中的数据只要将img包在p中即可
高版本也是遵循html结构的。。。所以像你这种情况还是比较少的。。。如果后续这种情况多。。。我们会考虑提供相应的工具的

**Comment by huangjiaxing** [comment]
> @panghaoyuan 保存的提示依然保存。。。毕竟还是要让你知道数据上有一些问题的。。。只是不再会在导致白屏了。。。你在网页中不开控制台是不受影响的。。。demo中的数据只要将img包在p中即可 高版本也是遵循html结构的。。。所以像你这种情况还是比较少的。。。如果后续这种情况多。。。我们会考虑提供相应的工具的

我们也遇到了这个情况，v4的数据跟v5版本不兼容。 比如这个数据是v4的getHtml保存的`<p>中国大陆地区均支持发货，港澳台以及国外目前不支持发货</p><p><b><font size="2" color="#ff3333">tips：</font></b></p><font color="#ff3333"><b>大陆地区可以下单就是可以发货哦</b></font><br/>`。 但放在v5里面，使用setHtml就会报错了

**Comment by dlystar** [comment]
您好，我这边也是遇到一样的问题，希望能提供一个数据格式化的工具，目前我们的富文本会承载邮件的内容，由于邮件的内容格式很复杂，导致富文本报错，但我们又罗列不了不规范的html，导致问题无法解决
