### ISSUE TITLE
上传视频  使用谷歌浏览器不能正常上传

### ISSUE THREAD

**Issue by chenpinzhong** [wangeditor-team/wangEditor#4934]
## bug 描述

上传视频  使用谷歌浏览器不能正常上传 但是使用 Edge 正常上传

## 你预期的样子是？

与Edge 一样能上传

## 系统和浏览器及版本号

系统 WIN10
Chrome 已是最新版本
版本 106.0.5249.103（正式版本） （64 位

## wangEditor 版本
      "@wangeditor/editor": "^5.1.15",
      "@wangeditor/editor-for-react": "^1.0.4",

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.d2wd.com/admin/product_manage/add

## 最小成本的复现步骤

上传视频 功能 使用 Edge 成功 谷歌失败

**Comment by wangfupeng1988** [comment]
你试试这个 demo https://github.com/wangeditor-team/server 在 chrome 可以吗？

**Comment by chenpinzhong** [comment]
这个 可以

**Comment by wangfupeng1988** [comment]
我试着你给的 demo ，可以上传成功的，如下图

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/9583120/195007066-0ab01244-998c-43e1-ab7c-f73a2141958d.png">

**Comment by chenpinzhong** [comment]
我刚刚试了 也可以了 
应该是 浏览器 问题了
