### ISSUE TITLE
表格不能居中及没有边框

### ISSUE THREAD

**Issue by leidao** [wangeditor-team/wangEditor#4937]
## 功能描述

表格不能设置居中并且表格获取的html没有border，在导出时样式不正确，建议增加对这两项的配置功能

## 原型图
期望：
![image](https://user-images.githubusercontent.com/39399843/195008530-d76c7d07-68c7-42cb-b2d3-7c8160fb1ad5.png)
现在：
![image](https://user-images.githubusercontent.com/39399843/195008583-f76f0566-32a5-42f3-ba11-88ec8485a01f.png)

**Comment by wangfupeng1988** [comment]
> 表格不能设置居中

这个是哪里体现的，我没看到

**Comment by wangfupeng1988** [comment]
> 表格获取的html没有border

表格显示时，样式需要自己处理，可参考这个 [demo](https://www.wangeditor.com/demo/get-html.html) 的网页源码

**Comment by Arapay** [comment]
表格整体没法居中
