### ISSUE TITLE
如何区分modal类型

### ISSUE THREAD

**Issue by kaideng-nmg** [wangeditor-team/wangEditor#4938]
## 问题描述

*想要区分每个modal的类型，如果知道当前的modal是编辑图片的modal还是编辑链接的modal*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/40782150/195050659-07e83b10-882d-428f-acbe-5fe97b905eee.png">
目前使用的判断modal名称的方式来判断当前的modal类型，请问有其他更好的方法吗

**Comment by wangfupeng1988** [comment]
暂没有其他方式
