### ISSUE TITLE
上传多张图片连续排列，删除后面一张图片，前面一张图片默认会选中

### ISSUE THREAD

**Issue by codercqw** [wangeditor-team/wangEditor#4939]
## 问题描述

上传多张图片连续排列，删除后面一张图片，前面一张图片默认会选中，如何取消默认选中呢？

## wangEditor 版本

5.1.21

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

文档demo可复现

**Comment by wangfupeng1988** [comment]
默认不支持，你需要通过自定义插件来重写 `deleteBackward` API

文档参考

https://www.wangeditor.com/v5/API.html#deletebackward

https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E6%8F%92%E4%BB%B6

**Comment by codercqw** [comment]
感谢大佬回复，已经解决这个问题了。
$textArea.on('keydown', event => {
          if (event.keyCode == 8 || event.keyCode == 46) {
            setTimeout(() => {
              // 解决连续多张图片排列，删除后面一张图片会默认选中前面一张图片的问题
              this.editor.move(1);
            });
          }
        });
