### ISSUE TITLE
上传图片后，选中图片配置图片链接，但是展示富文本html时点击图片没有跳转

### ISSUE THREAD

**Issue by weidongdiao** [wangeditor-team/wangEditor#4940]
## bug 描述

*上传图片后，选中图片配置图片链接，但是展示富文本html时点击图片没有跳转，看获取到的html代码里只在img里增加了data-href，没有用<a>标签包上*

## 你预期的样子是？

*点击图片，可以自行跳转配置的图片链接*

## 系统和浏览器及版本号

- windows/mac
- Chrome

## wangEditor 版本

*V5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*无需*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 上传图片后，选中图片配置图片链接
- 通过editor.getHtml()方法获取html内容并在浏览器展示
- 点击图片后无反应
- 预期是可以直接跳转配置的图片链接

**Comment by wangfupeng1988** [comment]
自定义一个 click 事件即可，点击图片时获取 data-href 并用 JS 跳转。

**Comment by weidongdiao** [comment]
对于页面可以，但是如果发送到邮箱里要如何处理才可以自动打开data-href里的链接呢

**Comment by wangfupeng1988** [comment]
可以自己转换一下 html ，把带有 data-href 的 img 替换为 a 标签
