### ISSUE TITLE
V5设置部分编辑器自带字体后，再setHtml()样式失效

### ISSUE THREAD

**Issue by xXxJoKoxXx** [wangeditor-team/wangEditor#4941]
## bug 描述

我在编辑器中将文字字体设置为"Times new Roman"或"Courier New"时会添加“&quote;”字符，保存该段html字符串后，查看时重新将该段html字符串通过editor.setHtml()传入编辑器，但是字体设置为"Times new Roman"样式的文字没有正确显示该样式。

## 你预期的样子是？

1. 在编辑器中设置为"Times new Roman"或"Courier New"时font-family样式不会添加多余“&quote;”字符；
2. 设置了"Times new Roman"或"Courier New"时font-family样式通过editor.setHtml()传入编辑器后样式能够正确显示。

## 系统和浏览器及版本号

- 操作系统
-  Windows 7
- 浏览器和版本
- Google Chrome V106.0.5249.103（正式版本） （64 位）

## wangEditor 版本

wangEditor Version 5 

## demo 能否复现该 bug ？

能（通过demo能看到设置字体为"Times new Roman"或"Courier New"后的font-family中的“&quote”字符，将该段字符重新setHtml()后即可复现）

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- 复现条件相对较简单，暂不编写在线demo，辛苦了！

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 在官网demo中将“hello world”设置字体格式为“Times New Roman”
- 步骤二 复制该段文字的html代码
- 步骤三 使用
```
editor.setHtml(‘<p><span style="font-family: &quot;Times New Roman&quot;;">hello world</span></p><p><br></p>’)
```

**Comment by wangfupeng1988** [comment]
升级 `@wangeditor/editor` 最新版试试

**Comment by xXxJoKoxXx** [comment]
好的，感谢大大
