### ISSUE TITLE
editor注册ButtonMenu时，点击事件失效

### ISSUE THREAD

**Issue by LemonGirlTYJ** [wangeditor-team/wangEditor#4943]
## 问题描述

使用react函数组件开发，在注册ButtonMenu时，触发exec事件通过useState改变某一个变量的数值。
发现第一次 created editor时，通过exec事件绑定的useState可以正常触发。但是第二次created editor时，通过exec事件绑定的useState就不触发，但是确实是触发了点击

## wangEditor 版本

 "@wangeditor/editor": "^5.1.20",
 "@wangeditor/editor-for-react": "^1.0.5",

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 但是第二次created editor时，通过exec事件绑定的useState就不触发，但是确实是触发了点击

那此时的 exec 事件有没有被调用？

**Comment by LemonGirlTYJ** [comment]
exec 事件有被调用，但是useState不触发

**Comment by wangfupeng1988** [comment]
给一个在线 demo 看看吧

以下平台三选一即可

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by LemonGirlTYJ** [comment]
https://codesandbox.io/s/sleepy-framework-ozkuj9?file=/src/index.js

**Comment by hahaaha** [comment]
@LemonGirlTYJ 检查下是不是有什么闭包问题
