### ISSUE TITLE
hoverbar 有些功能不用可以设置隐藏或者禁用吗

### ISSUE THREAD

**Issue by Volcanione** [wangeditor-team/wangEditor#4944]
![image](https://user-images.githubusercontent.com/20943196/195311207-25a1cc1a-af95-408c-ab4a-fccb3c1b9db6.png)
我有一个功能只需要用到link工具，其他的不需要，怎么删掉呢

**Comment by wangfupeng1988** [comment]
看文档的 hoverbarkeys 的配置
