### ISSUE TITLE
Error: Repeated create toolbar by selector '[object HTMLDivElement]

### ISSUE THREAD

**Issue by zrj513** [wangeditor-team/wangEditor#4945]
## Error: Repeated create toolbar by selector '[object HTMLDivElement]'

*使用的是ant design pro，在components  #组件中使用了wangeditor,提交正常，在主页面刷新时出现错误提示*
*
Error: Repeated create toolbar by selector '[object HTMLDivElement]'
▶ 2 stack frames were collapsed.
(anonymous function)
./src/components/Toolbar.tsx:22
  19 | const ref = useRef<HTMLDivElement>(null)
  20 | 
  21 | useEffect(() => {
> 22 |   if (ref.current == null) return
     | ^  23 |   if (editor == null) return
  24 | 
  25 |   wangEditor.createToolbar({
View compiled
▶ 13 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.`*

## wangeditor 版本：
"@wangeditor/editor": "^5.1.21",
"@wangeditor/editor-for-react": "^1.0.5",

相关代码，DetailForm中的代码
  const [editor, setEditor] = useState<IDomEditor | null>(null);

  const [html, setHtml] = useState('<p>hello</p>');

  const toolbarConfig: Partial<IToolbarConfig> = { }
  const editorConfig: Partial<IEditorConfig> = {
    placeholder: '请输入内容...',
    onCreated(editor) { setEditor(editor) }, // 记录下 editor 实例，重要！
    MENU_CONF: {
      uploadImage: {  // 配置图片上传服务器
        server: globalConstant.API_HOST+'/api/cssorder/upload',
        allowedFileTypes: ['image/*'],
        fieldName:'myFile',
        maxNumberOfFiles: 1,  // 单次最多上传一个文件
        // 单个文件上传成功之后
        onSuccess(file: File) {
            message.success(`${file.name} 上传成功`)  // antd的message组件
        },
        // 单个文件上传失败
        onFailed(file: File) {
            message.error(`${file.name} 上传失败`)  // antd的message组件
        },
        // 上传错误，或者触发 timeout 超时
        onError(file: File, err: any) {
            message.error(`${file.name} 上传出错`+String(err))  // antd的message组件
        },
    }
    }
  }

  useEffect(() => {
    // 模拟 ajax 异步设置 value
    setTimeout(() => {
        setHtml('');
    }, 1500)
  }, []);

  useEffect(() => {
    // 组件销毁时，销毁 editor
    return () => {
      if (editor == null) return
      editor.destroy()
      setEditor(null)
    }
  }, [editor]);

<div style={{ border: '1px solid #ccc', zIndex: 100}}>
          <Toolbar
              editor={editor}
              defaultConfig={toolbarConfig}
              style={{ borderBottom: '1px solid #ccc' }}
          />
          <Editor
            defaultConfig={editorConfig}
            style={{ height: '400px', overflowY: 'hidden' }}
          />
    </div>
## 查阅了文档 

（文档链接 [https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8-2](https://www.wangeditor.com/v5/for-frame.html#%E4%BD%BF%E7%94%A8-2) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 主页面index.tsx中  点击  弹出一个components /OrderForm.tsx
- 主页面
   const success = await handleAdd(value);
          if (success) {
            handleErrorModalVisible(false);
            if (actionRef.current) {
              actionRef.current.reload();
            }
       }
- 步骤二
- 提交后，刷新时会复现错误信息
- 步骤三

**Comment by wangfupeng1988** [comment]
看报错的现象，应该是在组件销毁时，没有及时销毁 editor ，你再继续 debug 一下吧。
