### ISSUE TITLE
扩展菜单时可以在富文本内容中插入特定内容

### ISSUE THREAD

**Issue by LemonGirlTYJ** [wangeditor-team/wangEditor#4946]
## 功能描述

扩展菜单时可以在页面中插入卡片，例如我导入了一个商品sku，希望可以在富文本里面显示一个商品卡片来占位。可以没有点击事件，需要支持可以删除。

## 提炼几个功能点

- 功能1
- 功能2
- 功能3

## 原型图
<img width="426" alt="image" src="https://user-images.githubusercontent.com/19466784/195494803-d02ef6fd-5aa7-4bbe-b3ec-674e011235b4.png">

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*

**Comment by wangfupeng1988** [comment]
自己开发即可。具体参考“链接卡片”这个插件，和你的很像 https://www.wangeditor.com/v5/plugins.html
