### ISSUE TITLE
增加缩进，段落字体对不齐

### ISSUE THREAD

**Issue by Asiamonae** [wangeditor-team/wangEditor#4947]
## bug 描述

设置字体字号后在增加缩进，段落字体对不齐，以下是生成的html
`<p style="text-indent: 2em;"><span style="color: rgb(82, 83, 83); background-color: rgb(255, 255, 255); font-size: 18px; font-family: 宋体;">市五届人大一次会议以来的五年，是我市发展进程中极不平凡的五年。我们坚持以习近平新时代中国特色社会主义思想为指导，深入学习贯彻习近平总书记对广西工作系列重要指示精神，认真落实自治区党委政府决策部署和市委的工作要求，解放思想、改革创新、扩大开放、担当实干，解决了一批长期想解决而没有解决的困难问题，办成了一批打基础、利长远的大事要事，发展速度保持全区领先，“十三五”规划目标任务总体完成，本届政府工作圆满收官。</span></p><p style="text-indent: 2em;"><br></p>`
效果：
![image](https://user-images.githubusercontent.com/26755700/195537169-f692e3e8-11a9-4324-8b03-2d34ed8919ed.png)

也期望能有方法能自定义p 标签的样式

**Comment by wangfupeng1988** [comment]
请按照 issue 模板提交问题，否则不予受理。
