### ISSUE TITLE
maxLength问题

### ISSUE THREAD

**Issue by Steryn** [wangeditor-team/wangEditor#4949]
## bug 描述

复制大段中文文本的时候，maxLenth长度超出，依然可以继续复制进去，并没有阻断输入

## 你预期的样子是？

阻断输入

## 系统和浏览器及版本号

- MAC OS
- chrome

## wangEditor 版本

最新版本

## demo 能否复现该 bug ？

能

**Comment by Steryn** [comment]
https://www.wangeditor.com/demo/max-length.html

**Comment by Steryn** [comment]
https://www.wangeditor.com/demo/max-length.html
官网maxlength案例可复现

**Comment by wangfupeng1988** [comment]
> 复制大段中文文本的时候

复制了什么？给一个具体的例子，方便我复现
