### ISSUE TITLE
设置选中节点的属性，获取已设置的html，没有发生变化

### ISSUE THREAD

**Issue by Asiamonae** [wangeditor-team/wangEditor#4950]
## bug 描述

通过setNodes设置节点属性之后，获取节点对应的 DOM 节点，和获取对应的html，发现DOM节点发生了变化，而生成的html没有发生变化
代码段：
`  
        SlateTransforms.setNodes(editor, {
            fontSize: '16px',
            textAlign: 'left'
          })
         console.log(editor.toDOMNode(node))
         console.log(editor.getHtml())
`
打印结果：
![image](https://user-images.githubusercontent.com/26755700/195569596-c6e416d3-3654-46b1-aaa0-ff08927dd205.png)

## 你预期的样子是？
期望能正常显示

## wangEditor 版本
  "@wangeditor/editor": "^5.1.21",
  "@wangeditor/editor-for-vue": "^1.0.2",

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
这样试试

```js
SlateTransforms.setNodes(editor, { fontSize: '16px', textAlign: 'left' });
console.log(editor.toDOMNode(node));
setTimeout(() => {
    console.log(editor.getHtml());
});
```

**Comment by Asiamonae** [comment]
> 这样试试
> 
> ```js
> SlateTransforms.setNodes(editor, { fontSize: '16px', textAlign: 'left' });
> console.log(editor.toDOMNode(node));
> setTimeout(() => {
>     console.log(editor.getHtml());
> });
> ```

不行

**Comment by wangfupeng1988** [comment]
我看错了。

设置 textAlign 使用 setNodes 这没问题。而设置 fontSize 需要 `editor.addMark('fontSize', '16px')`

**Comment by Asiamonae** [comment]
> 我看错了。
> 
> 设置 textAlign 使用 setNodes 这没问题。而设置 fontSize 需要 `editor.addMark('fontSize', '16px')`

不得，会莫名进入一堆循环，页面直接卡死

**Comment by wangfupeng1988** [comment]
> 进入一堆循环，页面直接卡死

这个我不知道如何复现。

**Comment by Asiamonae** [comment]
> > 进入一堆循环，页面直接卡死
> 
> 这个我不知道如何复现，需要补充复现步骤。

![image](https://user-images.githubusercontent.com/26755700/196373117-7d1dc88d-d754-4658-a6a2-8c50c70c8557.png)

**Comment by wangfupeng1988** [comment]
在 onChange 中设置，那不死循环才怪呢。
就类似在 Vue 组件的 update 生命周期中去修改 data，肯定死循环啊。

**Comment by Asiamonae** [comment]
> Collaborator
嗯。。。我之前的理解是选中内容会发生变化，所以放在change里处理，那应该放哪里呢？我是小白，指导一下呗

**Comment by wangfupeng1988** [comment]
> 选中内容会发生变化 

你意思是选中几个文字，这些文字要立马编程 16px 吗？

不太理解你的需求

**Comment by Asiamonae** [comment]
> > 选中内容会发生变化
> 
> 你意思是选中几个文字，这些文字要立马编程 16px 吗？
> 
> 不太理解你的需求

是的，就是这样，选中后，我要设置P标签成16px（具体为什么这样设置，因为我们后续要根据这个死设置生成固定格式的word文档），所以我想知道这个设置不放在change里的话应该放在哪？

**Comment by Asiamonae** [comment]
> 
还是说我先不设置，在生成之前在改变P标签的样式

**Comment by wangfupeng1988** [comment]
看看这个能解决吗 https://github.com/wangeditor-team/wangEditor/issues/4042
