### ISSUE TITLE
在链接后面添加文本，该文本成为链接的一部分

### ISSUE THREAD

**Issue by plilion** [wangeditor-team/wangEditor#4951]
## bug 描述

选中一段文本，然后添加链接，然后后面继续输入文本，输入的文本成为链接的一部分了

## 你预期的样子是？

输入的文本不成为链接的一部分

## 系统和浏览器及版本号

- mac 10.15.7 
- chrome 105.0.5195.125

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

官方的demo 上就能复现

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

输入文本然后选中
为该文本添加链接
在该文本后面继续添加文字

**Comment by wangfupeng1988** [comment]
这个之间已经记录下了，但目前没有啥好手段。因为不好判断。

你的预期是想输出纯文本，但可能有些人预期是想增加链接的文字 —— 这没有一个判断标准。

我继续跟踪着吧。

**Comment by plilion** [comment]
如果是判断标准，无法确定的话
要么在配置的时候让开发者进行配置，
要么让用户在使用的时候，进行决定
