### ISSUE TITLE
文本和链接一起粘贴进富文本，链接失效变成纯文本

### ISSUE THREAD

**Issue by coralJiao** [wangeditor-team/wangEditor#4952]
## bug 描述

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/48193126/195606014-cc46c616-ca9d-40f1-ab5e-c03d3e38be98.png">

单独粘贴链接，链接有效；文本+链接一起粘贴，链接不高亮也不能点击，成为了纯文本

## 你预期的样子是？
链接正常高亮，点击可跳转

## 系统和浏览器及版本号
Google Chrome
版本 105.0.5195.125（正式版本）

## wangEditor 版本
官网在线版本：https://www.wangeditor.com/demo/index.html

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  负责 文本+链接
- 步骤二  粘贴到富文本

**Comment by wangfupeng1988** [comment]
你用 [customPaste](https://www.wangeditor.com/v5/editor-config.html#custompaste) 监听一下，自己粘贴的 HTML 内容是什么？ 这要根据 HTML 内容来分析问题。
