### ISSUE TITLE
上传图片配置，配置了，但一直报没有配置上传地址

### ISSUE THREAD

**Issue by siitry** [wangeditor-team/wangEditor#4953]
## 问题描述

*上传图片配置，配置了，但一直报没有配置上传地址*

## wangEditor 版本

*上传图片配置，配置了，但一直报没有配置上传地址*

## 是否查阅了文档 ？

查看过了，没找到解决方式

**Comment by wangfupeng1988** [comment]
在这里回复吧 https://github.com/wangeditor-team/server/issues/3
