### ISSUE TITLE
自定義上傳圖片，新增id屬性

### ISSUE THREAD

**Issue by CCYO** [wangeditor-team/wangEditor#4954]
## 功能描述

自定義上傳圖片，後端會於資料庫建立圖片資料，並響應插入圖片需要的alt, src, href。

但後續若有更新圖片 alt, src, href 時，因後端資料庫也需一併更新，是否能除了alt, src, href外，也提供一個id屬性，作為後端辨認該圖片數據id使用，或是以現況來說，能如何自行為此功能作擴展呢？

## 提炼几个功能点

- 新增圖片元素id屬性

**Comment by wangfupeng1988** [comment]
暂不支持。

**Comment by codercqw** [comment]
我是把数据存在data-href里面 然后用的时候再读取
