### ISSUE TITLE
editor.getHtml() 获取图片内容不准确

### ISSUE THREAD

**Issue by yl196356303** [wangeditor-team/wangEditor#4955]
## bug 描述

手动插入图片当图片数量大于2时 editor.getHtml() 获取图片内容不准确
<p><img src="https://static.xiongmaomart.cn/mall/634919dc7acc66004f2a498c.jpg" alt="" data-href="" style="width: 100%;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100%;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919c47acc66004f2a4982.jpg" alt="" data-href="" style="width: 100%;"/><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100%;"/></p>

## 你预期的样子是？

<p><img src="https://static.xiongmaomart.cn/mall/634919dc7acc66004f2a498c.jpg" alt="" data-href="" style="width: 100%;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100%;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919c47acc66004f2a4982.jpg" alt="" data-href="" style="width: 100%;"/></p>

## 系统和浏览器及版本号

无关

## wangEditor 版本

"@wangeditor/editor": "5.1.18",
"@wangeditor/editor-for-react": "1.0.5",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

https://codesandbox.io/s/react-wangeditor-demo-forked-ucnbf4?file=/src/components/MyEditor.js

## 最小成本的复现步骤

复现步骤点击 insert test 打开控制台即可看到错误打印

**Comment by wangfupeng1988** [comment]
> 点击 insert test 打开控制台即可看到错误打印

点击了“insert text”按钮，并没有打印报错。如下图

<img width="1440" alt="截屏2022-10-15 下午2 35 36" src="https://user-images.githubusercontent.com/9583120/195973062-963ad633-eb8c-473c-9f18-c3b030c15641.png">

**Comment by yl196356303** [comment]
哦哦 搞错了 是这个版本 "@wangeditor/editor": "5.1.18",
"@wangeditor/editor-for-react": "1.0.5",

**Comment by wangfupeng1988** [comment]
看着和你题目中的版本一样啊？

**Comment by yl196356303** [comment]
我后面改的 你现在进去看就能复现

**Comment by wangfupeng1988** [comment]
我重新试了 demo ，依然没有报错

<img width="1768" alt="image" src="https://user-images.githubusercontent.com/9583120/196071710-67f0cdd8-050b-4679-a6a8-9a463e03caa4.png">

**Comment by yl196356303** [comment]
不是报错，是editor.getHtml() 获取不对
期望：
<p><img src="https://static.xiongmaomart.cn/mall/634919dc7acc66004f2a498c.jpg" alt="" data-href="" style="width: 100%;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100%;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919c47acc66004f2a4982.jpg" alt="" data-href="" style="width: 100%;"/></p>
实际获取错误：
<p><img src="https://static.xiongmaomart.cn/mall/634919dc7acc66004f2a498c.jpg" alt="" data-href="" style="width: 100%;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100%;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919c47acc66004f2a4982.jpg" alt="" data-href="" style="width: 100%;"/><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100%;"/></p>

**Comment by yl196356303** [comment]
当图片数量大于2张时，插入图片会导致图片顺序错乱
