### ISSUE TITLE
V4版本文档完善建议

### ISSUE THREAD

**Issue by Birdyqaq** [wangeditor-team/wangEditor#4956]
## 问题描述

v4版本在h5中使用 与ios 安卓交互  实现视频插入带封面 没有使用原有的视频上传方法  使用cmd do 插入video标签 发现直接插入存在bug 可以正常插入 但是会出现无法删除视频的情况  阅读源码发现 原有视频上传方法也是采用cmd do插入 但是加了一个标签在后面\<\p data-we-empty-p=""> <br><\/\p\> 在后面 加了之后 插入视频正常无bug   V4文档这块没有提及能否在文档中说明这点 方便后续大家使用起来方便

## wangEditor 版本
V4

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
v4 已经不再维护。

业余时间有限，还请体谅~
