### ISSUE TITLE
与包default-passive-events冲突

### ISSUE THREAD

**Issue by Rackar** [wangeditor-team/wangEditor#4958]
## bug 描述

Vue项目中同时安装了 default-passive-events 包，点击修改文字颜色，会出现报错信息
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

## 你预期的样子是？

正常操作

## 系统和浏览器及版本号

本地及沙盒都有出现

## wangEditor 版本

    "@wangeditor/editor": "5.1.21",
    "@wangeditor/editor-for-vue": "5.1.12",

## demo 能否复现该 bug ？

不能，沙盒中加入冲突包可以复现

## 在线 demo

*已制作DEMO*

https://stackblitz.com/edit/vue3-wangeditor-demo-xvf73k?file=src%2Fmain.js

## 最小成本的复现步骤

1. 选中文字，点击修改文字颜色，无效果。
2. 本地报错 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by Rackar** [comment]
报错提示与 #4508 一样，怀疑同一问题

**Comment by liuqh0609** [comment]
已经确定问题，`default-passive-events ``该包会重写`addEventListener`事件的`options.passive`参数为`true`，导致` `preventDefault()`失效。
已经修复，关注版本更新即可。

**Comment by wangfupeng1988** [comment]
升级 `@wangeditor/editor` 最新版本试试

**Comment by Rackar** [comment]
收到，非常感谢

**Comment by qzy5830** [comment]
最新版本还是会报错啊
