### ISSUE TITLE
保存之后再次查看Cannot resolve a Slate node from DOM node: [object HTMLSpanElement]

### ISSUE THREAD

**Issue by zhangYinfei** [wangeditor-team/wangEditor#4959]
## 问题描述
富文本为一个公共的组件，在页面引用，首次添加时正常运行，保存之后点击再次修改会报错Cannot resolve a Slate node from DOM node: [object HTMLSpanElement]
![image](https://user-images.githubusercontent.com/49514383/196025704-0a4f7594-2395-4ec0-a788-7395f0e5a740.png)

## wangEditor 版本
"@wangeditor/editor": "^5.1.18",
"@wangeditor/editor-for-vue": "^1.0.2",

## 是否查阅了文档 ？
是

## 最小成本的复现步骤

引用赋值时：
<WangEditor
    v-model="form.description"
    @contentChange="getContent"
></WangEditor>

getContent(editor) {
     if (editor.isEmpty()) {
      this.form.description = null;
    }
    this.form.description = editor.getHtml();
},

editor组件：
onChange(editor) {
    this.$emit("contentChange", editor);
},

**Comment by wangfupeng1988** [comment]
可以提供一个复现的 demo 吗？能复现即可，demo 越简单越好

再以下平台提供 demo ，三选一即可

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by lindow2009** [comment]
遇到了同样的问题，官网demo改的，请看看怎么回事
