### ISSUE TITLE
editor.getHtml() 获取图片值不准确

### ISSUE THREAD

**Issue by yl196356303** [wangeditor-team/wangEditor#4962]
## bug 描述

手动插入图片当图片数量大于2时 editor.getHtml() 获取图片值不准确
```
<p><img src="https://static.xiongmaomart.cn/mall/634919dc7acc66004f2a498c.jpg" alt="" data-href="" style="width: 100px;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100px;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919c47acc66004f2a4982.jpg" alt="" data-href="" style="width: 100px;"/><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100px;"/></p>
```

## 你预期的样子是？

控制台打印：
```
<p><img src="https://static.xiongmaomart.cn/mall/634919dc7acc66004f2a498c.jpg" alt="" data-href="" style="width: 100px;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919d37acc66004f2a4987.jpg" alt="" data-href="" style="width: 100px;"/></p><p><img src="https://static.xiongmaomart.cn/mall/634919c47acc66004f2a4982.jpg" alt="" data-href="" style="width: 100px;"/></p> 
```
## 系统和浏览器及版本号

无关

## wangEditor 版本

"@wangeditor/editor": "5.1.18",
"@wangeditor/editor-for-react": "1.0.5",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

https://codesandbox.io/s/react-wangeditor-demo-forked-ucnbf4?file=/src/components/MyEditor.js

## 最小成本的复现步骤

复现步骤点击 insert test 查看控制台打印

**Comment by wangfupeng1988** [comment]
你来这个 demo 试试 https://www.wangeditor.com/demo/get-html.html 

如下图，在编辑器手动插入几张图片，看看下面获取的 HTML 是不是和编辑器里的顺序一致？

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/9583120/196311098-b62567b4-eab6-4b67-8892-cc32ebaa0d6b.png">

**Comment by yl196356303** [comment]
不知道demo的版本是多少，demo似乎很难复现我提供的在线demo操作

**Comment by wangfupeng1988** [comment]
demo 就是最新版本的。你升级一下 `@wangeditor/editor` 最新版本试试
