### ISSUE TITLE
如何能加入字间距这个功能 letter space

### ISSUE THREAD

**Issue by dongfengtaoadmin** [wangeditor-team/wangEditor#4963]
## 问题描述
我想自己尝试使用扩展来增加字间距 letter space
*请输入遇到的问题...*

## wangEditor 版本
v5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 我是使用的react开发的  但是在进行扩展的时候总是报错
- 步骤二
- 
![image](https://user-images.githubusercontent.com/89253615/196116556-72facc93-91a5-413f-a201-78721d5a3d2a.png)
[@](url)
- 步骤三
想知道如何用react开发扩展功能

**Comment by wangfupeng1988** [comment]
看截图的错误提示：重复注册 menu
