### ISSUE TITLE
想通过wangeditor 增加字间距功能！！！很想被解决 希望王福朋老师可以辛苦看一下 万分感谢

### ISSUE THREAD

**Issue by dongfengtaoadmin** [wangeditor-team/wangEditor#4965]
## 问题描述
想加一个可以增加字间距的DropPanel组件
*请输入遇到的问题...*
通过 SlateTransforms.setNodes 但是编辑器里面还是没有生效我是还差哪一步呢？
## wangEditor 版本
v5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
是
*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 通过 SlateTransforms.setNodes 但是编辑器里面还是没有生效我是还差哪一步呢？
- 
<img width="485" alt="image" src="https://user-images.githubusercontent.com/89253615/196163704-b86c0968-43b6-4410-a83a-2d348b825eda.png">

![image](https://user-images.githubusercontent.com/89253615/196163665-4d1bdabd-b39b-42f3-b857-d91332c4524a.png)

- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
不是随便一个属性 setNodes 就可以生效的，你得让编辑器认识这个属性

例如 lineHeight ，就需要很多关于它的代码，让编辑器能识别它，https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/line-height 

另，自定义样式，二次开发并不常用，所以我也没有写到文档里。你只能参考代码来看看。有问题再来回复我。

**Comment by dongfengtaoadmin** [comment]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/89253615/196352767-ba98ee6b-d542-4c07-be86-cc6b4e6195a5.png">
感觉像是这个 需要在注册的时候把对应的样式注册进去，我尝试着用你的方式给加了一个类似的js版本 但是报错 信息如下：
![image](https://user-images.githubusercontent.com/89253615/196353159-9e09dd83-f368-499b-a878-44d990425c5f.png)
想知道如何用js注册上对应的自定义样式呢？

**Comment by dongfengtaoadmin** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/89253615/196353608-d7a03805-61bb-43ec-b46c-596653f32744.png">

感觉像是这个 需要在注册的时候把对应的样式注册进去，我尝试着用你的方式给加了一个类似的js版本 但是报错 信息如下：
![image](https://user-images.githubusercontent.com/89253615/196353705-49b2bece-1dc0-4567-a421-334329a3499b.png)

我想知道如何才能把自定义样式给注册进去呢？ 因为字间距的场景还是蛮多的，现在我就差自定义间距样式了

**Comment by dongfengtaoadmin** [comment]
嗯呢 我可以慢慢调试 但是我想知道renderStyle应该传什么格式的  而且我的方向是不是对的
<img width="559" alt="image" src="https://user-images.githubusercontent.com/89253615/196381684-fc3e0150-ea3a-4016-b461-cb1d5e43b562.png">

**Comment by wangfupeng1988** [comment]
参考 line-height 模块就可以了，一样的。

**Comment by meicy** [comment]
> 不是随便一个属性 setNodes 就可以生效的，你得让编辑器认识这个属性
> 
> 例如 lineHeight ，就需要很多关于它的代码，让编辑器能识别它，https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/line-height
> 
> 另，自定义样式，二次开发并不常用，所以我也没有写到文档里。你只能参考代码来看看。有问题再来回复我。

模仿 https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/line-height 写的字间距，不同于
const module: Partial<IModuleConf> = {   // TS 语法
// const module = {                      // JS 语法

  menus: [menu1Conf, menu2Conf, menu3Conf],

  // 其他功能，下文讲解...
}
Boot.registerModule(module)
这种方式，请问这个怎么注册到编辑器里面呢

**Comment by Liuone** [comment]
@dongfengtaoadmin @meicy 可以看下你们关于字间距这块的代码嘛，现在我也很急需字间距这个需求，我用的是vue2，有点无从下手

**Comment by QHSsss** [comment]
> @dongfengtaoadmin @meicy 可以看下你们关于字间距这块的代码嘛，现在我也很急需字间距这个需求，我用的是vue2，有点无从下手

你可以参考参考这个 不过这个是vue3写的  稍微改一下就好了
https://blog.csdn.net/weixin_43436640/article/details/140269298

**Comment by Liuone** [comment]
> > @dongfengtaoadmin @meicy 可以看下你们关于字间距这块的代码嘛，现在我也很急需字间距这个需求，我用的是vue2，有点无从下手
> 
> 你可以参考参考这个 不过这个是vue3写的 稍微改一下就好了 https://blog.csdn.net/weixin_43436640/article/details/140269298

好的，谢谢
