### ISSUE TITLE
设置不可编辑无效

### ISSUE THREAD

**Issue by 1954418428** [wangeditor-team/wangEditor#4967]
![image](https://user-images.githubusercontent.com/60101171/196729334-d37db2fe-964c-4d3b-b01a-b63169fb88d6.png)
要显示的内容被重新赋值后 还是可以编辑的。如果没被赋值，就只在创建ref时赋值，就不可被编辑

**Comment by wangfupeng1988** [comment]
按照 issue 模板，给一个在线 demo 


- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/
