### ISSUE TITLE
当外层用流动布局flex时， 内部文本会被影响<p>不能自动换行，导致编辑区域撑大，超出屏幕

### ISSUE THREAD

**Issue by TangsWang** [wangeditor-team/wangEditor#4968]
## bug 描述

*当外层用流动布局flex时， 内部文本会被影响<p>不能自动换行，导致编辑区域撑大，超出屏幕*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统   
- win 10
- 浏览器和版本
- 任意, chrome,edge,firefox

## wangEditor 版本
最新版本.
*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
给一个 demo 吧

或者贴一段关键性的代码，说明 DOM 层级结构，以及哪一个节点用了 flex
