### ISSUE TITLE
关于<span><img src="xxx"/> hello</span>不识别问题

### ISSUE THREAD

**Issue by webhaoge** [wangeditor-team/wangEditor#4969]
## 问题描述

<span><img src="xxx"/> hello</span>
这种图片不被识别   但是之前老版本ueditor编辑的文章图片都是这种格式
我这边试了 修改粘贴逻辑  没有效果  图片依然出不来  应该如何解决

## wangEditor 版本

"@wangeditor/editor": "^5.1.14",
"@wangeditor/editor-for-vue": "^5.1.10",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

**Comment by wangfupeng1988** [comment]
这是非规范的 HTML 格式，v5 不再识别。

可通过 customPaste 来自行处理，优化 HTML 格式 https://www.wangeditor.com/v5/editor-config.html#custompaste
