### ISSUE TITLE
大佬们，问个上传图片的问题

### ISSUE THREAD

**Issue by zhangpeng16488** [wangeditor-team/wangEditor#4972]
## 上传图片的问题

*我在本地上传图片，图片是可以上传成功的，但是url和href那些值是在后台拼接好再返回的，是吧，比如上传到D盘，那么url和href怎么返回啊，在本地有这个问题的，谢谢您。*

## wangEditor 版本

*5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
> 比如上传到D盘，那么url和href怎么返回啊

这是服务端的问题
