### ISSUE TITLE
粘贴内容和图片失败

### ISSUE THREAD

**Issue by 15835917434** [wangeditor-team/wangEditor#4973]
## bug 描述

粘贴word里的文字和图片到编辑器里后，图片不显示

## 你预期的样子是？

粘贴word里的文字和图片到编辑器里后，图片可以正常上传到远程服务器且显示正常

## 系统和浏览器及版本号

windows
-谷歌浏览器

## wangEditor 版本

wangeditor5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
默认暂不支持粘贴 word 图片。

可以自己通过 customPaste 来优化 https://www.wangeditor.com/v5/editor-config.html#custompaste
