### ISSUE TITLE
代码没有更新，但是线上编辑器报错

### ISSUE THREAD

**Issue by doYbest** [wangeditor-team/wangEditor#4974]
## bug 描述

之前没有问题，没有改过代码，但是代码莫名报错,下面是报错
![image](https://user-images.githubusercontent.com/80409408/197333153-5c1c5eb6-2ed2-4ff1-99ce-839162bbe36b.png)

这是后台返回的信息
‘
![image](https://user-images.githubusercontent.com/80409408/197333198-99e496e8-675d-4377-94ec-61c7e9dc9877.png)

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- window
-谷歌浏览器

## wangEditor 版本

"@wangeditor/editor": "^5.1.22",

## demo 能否复现该 bug ？

能

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

https://em4gxz.codesandbox.io/

**Comment by wangfupeng1988** [comment]
把 demo 源码地址发出来

**Comment by doYbest** [comment]
> 地址

https://codesandbox.io/s/em4gxz

**Comment by doYbest** [comment]
https://bbpncc.csb.app/
这个demo新加了一种情况 @wangfupeng1988

**Comment by wangfupeng1988** [comment]
> 发现包裹一个p标签就可以

是的，需要 p 标签
