### ISSUE TITLE
上传图片时，【网络图片】选项，有三个要填写的，其中【图片地址】和【图片链接】是重复的吗？有什么区别？

### ISSUE THREAD

**Issue by medmin** [wangeditor-team/wangEditor#4976]
## 问题描述

上传图片时，【网络图片】选项，有三个要填写的，其中【图片地址】和【图片链接】是重复的吗？有什么区别？
这俩容易让人困惑，该选哪个

## wangEditor 版本

<img width="524" alt="Screen Shot 2022-10-22 at 3 40 48 PM" src="https://user-images.githubusercontent.com/16820635/197364860-23d2efa7-541b-4a1a-9c93-604bc8de137d.png">

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

无

**Comment by wangfupeng1988** [comment]
图片地址，是 src

图片链接，是你点击图片想要跳转的地址

**Comment by ka3hun9** [comment]
图片链接在img的标签上添加了data-href, 并没有直接使用a标签包裹img标签, 这样做有什么讲究吗?

**Comment by xiaobo1215** [comment]
对？有什么考虑么？是不是需求 自己 对 有 data-href 的 img ，使用a 包裹？

**Comment by wenston** [comment]
网络图片到了编辑器里之后，尺寸变小了，变模糊了，被压缩了是怎么回事
