### ISSUE TITLE
如何手动触发工具栏

### ISSUE THREAD

**Issue by changzhengithub** [wangeditor-team/wangEditor#4978]
## 问题描述
比如我想自定义一个按钮，点击后自动触发工具栏里对应的某个菜单，通过editor实例对象手动触发，而不需要亲自点击。
## wangEditor 版本
"@wangeditor/editor": "^5.1.22"

## 是否查阅了文档 ？
是

**Comment by wangfupeng1988** [comment]
默认不支持。

这么多菜单，每个菜单背后的逻辑都不一样，而且是由许多逻辑组成的。
所以，需要实现什么功能，只能你自己通过 editor [API](https://www.wangeditor.com/v5/API.html) 去二次开发
