### ISSUE TITLE
老数据不支持

### ISSUE THREAD

**Issue by maojie0047** [wangeditor-team/wangEditor#4979]
## bug 描述

v3版本产生的列表嵌套数据例如
<ol start="1">
    <li>
        <div>查询员工
            <span>
                <strong>在职状态</strong>
            </span>：</div>
        <ol>
            <li>
                <div>若在职，继续步骤2；</div>
            </li>
            <li>
                <div>若非在禁用；</div>
            </li>
        </ol>
    </li>
</ol>

在v5版本中展示不出来，v5也没有办法编辑例如这样的列表
1.一级列表一级列表
   1.二级二级
   2.二级二级
2.一级列表一级列表
   1.二级二级
   2.二级二级

## 你预期的样子是？

支持列表嵌套，列表的一项也可以是个列表

## 系统和浏览器及版本号

无关
## wangEditor 版本

v5

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by wangfupeng1988** [comment]
v3 当时不支持多级列表的。

这种数据格式不再支持。可以自己先处理一下，再设置到 v5 中
