### ISSUE TITLE
如何实现这种提及功能

### ISSUE THREAD

**Issue by changzhengithub** [wangeditor-team/wangEditor#4980]
## 问题描述
如下图所示，我想实现像石墨文档一样的提及功能，输入一个 / 然后像 `hoverbarKeys` 这种该如何实现，有没有好的建议，谢谢。
![image](https://user-images.githubusercontent.com/35087343/197436648-e02d56bd-13ac-4512-86d9-7b98f9b577eb.png)

**Comment by wangfupeng1988** [comment]
可以参考 mention 插件的源码 https://github.com/wangeditor-team/wangEditor-plugin-mention

**Comment by wangfupeng1988** [comment]
重点在于使用 wangEditor 插件机制，劫持 `insertText` API ，如果输入的是 `/` 则弹出自己定义的 modal 

就像这里 https://github.com/wangeditor-team/wangEditor-plugin-mention/blob/main/src/module/plugin.ts#L20

**Comment by changzhengithub** [comment]
> 

就像mention提及插件，输入劫持/和弹窗可以简单实现，但是点击里面的按钮直接触发工具栏菜单，现在没有这种功能。这种该如何去模仿点击菜单栏来实现，添加mark和设置节点属性都是要手动选中才能对文本进行设置，如何不选中就可以模拟实现。

**Comment by wangfupeng1988** [comment]
> 点击里面的按钮直接触发工具栏菜单

目前没有这种 API 。其实工具栏的菜单也是手写代码实现的，你可以通过 editor API 来实现任何功能。

> 如何不选中就可以模拟实现

可以先通过 API 设置需要的选区，然后执行样式操作，再取消选区。
