### ISSUE TITLE
复制粘贴出现追加内容问题

### ISSUE THREAD

**Issue by yezongyang** [wangeditor-team/wangEditor#4981]
## bug 描述

复制粘贴出现追加内容问题

## 你预期的样子是？

正常粘贴

## 系统和浏览器及版本号

- 操作系统
Mac

- 浏览器和版本
Chrome 105.0.5195.125

## wangEditor 版本
4.7.15

## 在线 demo
https://codesandbox.io/s/ecstatic-blackwell-nnltwk?file=/src/App.vue

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 首先command + C 拷贝一段文字
- 步骤二
- 富文本框内输入一段文字。command + A 选中文本框文字，按住command键不要松开，command + V 粘贴，会出现追加内容。

重点复现就是 command键不要松开

**Comment by wangfupeng1988** [comment]
v4 已不再支持。

业余时间有限，还请体谅~
