### ISSUE TITLE
富文本显示问题

### ISSUE THREAD

**Issue by zhangjiahe666** [wangeditor-team/wangEditor#4982]
## 问题描述

*编辑器中不能显示md格式内容，输入后直接显示效果。希望就像github上面这样，一个输入，一个预览*

## wangEditor 版本

*5版本*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by wangfupeng1988** [comment]
有 markdown 插件 https://www.wangeditor.com/v5/plugins.html

预览，你需要自己实现
