### ISSUE TITLE
Bug:富文本里录入中文冒号后，异常问题。

### ISSUE THREAD

**Issue by xunyiyiyi** [wangeditor-team/wangEditor#4984]
## bug 描述
https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js
录入框内容里录入内容包含中文冒号（：）的字符串，报错：Cannot resolve a DOM point from Slate point: {"path":[1,0],"offset":11}
录入中文冒号后直接回车，冒号会丢失。
*请输入内容……*
场景1.录入内容：测试数据：123   ，报错：
场景2.录入内容：测试数据：   然后回车，发现控件里的内容是：测试数据 ，冒号丢失了。
## 你预期的样子是？
场景1：测试数据：123
场景2：测试数据：
*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本
V5
*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
什么浏览器，什么版本？什么中文输入法？

**Comment by ghost** [comment]
> 什么浏览器，什么版本？什么中文输入法？

chrome，66版本，微软拼音的中文字符和数字/搜狗输入法的中文字符都获取不到
