### ISSUE TITLE
wangeditor配合vue+antd开发时，创建编辑器不输入销毁编辑器，会出现无法获得编辑器实例的错误

### ISSUE THREAD

**Issue by leoafl** [wangeditor-team/wangEditor#4985]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
请提供一个在线 demo ，或详细描述复现步骤

**Comment by xixiaa** [comment]
在antdv3的modal里放置一个form表单，表单中包含wangEditor插件，将顶部带换行的word内容粘贴进编辑框中，关闭modal弹窗，再次打开，再次关闭时就会报错
![image](https://user-images.githubusercontent.com/39577780/197985709-8be3aa91-5828-4f95-b66b-a04e69c53949.png)
![image](https://user-images.githubusercontent.com/39577780/197985877-0e03e563-418b-4adb-9951-2744ce9d2fa1.png)
![image](https://user-images.githubusercontent.com/39577780/197985969-c2249453-5185-4eac-b15a-816a88e139b4.png)

**Comment by wangfupeng1988** [comment]
来一个在线 demo 吧

**Comment by xixiaa** [comment]
怎么删除editor的children数组中text为空的children对象
![image](https://user-images.githubusercontent.com/39577780/198170797-1df3ff04-ae92-41c3-b314-918c3b43be3a.png)

**Comment by wangfupeng1988** [comment]
@xixiaa 不能随意修改内部数据，否则会导致意外的错误。要做啥，通过 editor API 操作，具体看文档。
