### ISSUE TITLE
自定义了插入音频 使用dangerouslyInsertHtml 无法插入html片段到文本域中

### ISSUE THREAD

**Issue by yaqingshan** [wangeditor-team/wangEditor#4986]
## 问题描述

*自定义了插入音频 使用dangerouslyInsertHtml 无法插入html片段到文本域中*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 自定义上传音频按钮

**Comment by wangfupeng1988** [comment]
请提供一个在线 demo

**Comment by jysunshine** [comment]
![image](https://user-images.githubusercontent.com/117065398/198949441-efbfa314-2cab-460b-8399-128e67efdbc0.png)

官网控制台输入：editor.dangerouslyInsertHtml(`<span data-w-e-type="audio" data-w-e-is-inline data-w-e-is-void><audio controls="controls" src="" ></audio></span>`) 插入空行，应该是0分0秒的音频播放器

**Comment by wangfupeng1988** [comment]
你的 audio 元素是怎么定义的？或者有没有定义？

PS：相关文档 https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E6%96%B0%E5%85%83%E7%B4%A0

**Comment by jysunshine** [comment]
您好，我已收到，尽快给您回复。
