### ISSUE TITLE
v5版本，Vue3文档demo，设置html后，光标不是在最后

### ISSUE THREAD

**Issue by 17175216777** [wangeditor-team/wangEditor#4989]
## bug 描述

*v5版本，Vue3官方文档，延迟设置html后（使用valueHtml.value = ""和editorRef.value.setHtml('')方式)，光标都是在最开始。
导致将html内容更换为code时（`<pre><code class="language-python">def func():
    print(123)</code></pre><p><br></p>`），设置成功后控制台会报错。
Uncaught Error: Cannot get the leaf node at path [0,0] because it refers to a non-leaf node: [object Object]*

## 你预期的样子是？

*设置成功后光标在最后，控值台不报错*

## 系统和浏览器及版本号

- win10
- Chrome 106.0.5249.119

## wangEditor 版本

*V5*

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 复制文档中vue3 demo代码
- 将<p>模拟 Ajax 异步设置内容</p>改为<pre><code class="language-python">def func():
    print(123)</code></pre><p><br></p>

**Comment by liuqh0609** [comment]
首行插入的话可以通过添加一个空行来规避这个问题。
`<p></p><pre><code class="language-python">def func(): print(123)</code></pre><p><br></p>`

**Comment by 17175216777** [comment]
谢谢，我有发现这样解决。但是样式就变了，那光标不是在末尾算是默认的吗。但是demo示例(https://www.wangeditor.com/demo/index.html)中就不会出现这个问题。

**Comment by liuqh0609** [comment]
> 谢谢，我有发现这样解决。但是样式就变了，那光标不是在末尾算是默认的吗。但是demo示例([https://www.wangeditor.com/demo/index.html)中就不会出现这个问题。](https://www.wangeditor.com/demo/index.html)%E4%B8%AD%E5%B0%B1%E4%B8%8D%E4%BC%9A%E5%87%BA%E7%8E%B0%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%E3%80%82)

恩恩，可以先用上面的方法解决一下，这个问题我会继续跟进
