### ISSUE TITLE
react wangEditorV5 使用自定义上传附件功能，报没有配置上传地址的错误

### ISSUE THREAD

**Issue by Charlespater** [wangeditor-team/wangEditor#4991]
## 问题描述

react wangEditorV5 使用自定义上传附件功能，报没有配置上传地址的错误

## wangEditor 版本
        "@wangeditor/editor": "^5.1.22",
        "@wangeditor/editor-for-react": "^1.0.6",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

根据上传附件插件文档操作，在自定义上传附件，选择附件后，报没有配置上传地址的错误。（自定义上传图片没问题）

![image](https://user-images.githubusercontent.com/50410763/197924709-39bc7dac-ccff-4c6f-9135-a6ff6cea579a.png)

![image](https://user-images.githubusercontent.com/50410763/197924739-41b83271-0c6d-48e8-9b78-c9569c73239f.png)

**Comment by Charlespater** [comment]
改为系统内置Server，也报这个错误
![image](https://user-images.githubusercontent.com/50410763/197925829-21b59b60-a2e1-496f-b58f-109cc91bc7cb.png)

**Comment by noenif** [comment]
> 改为系统内置Server，也报这个错误 ![image](https://user-images.githubusercontent.com/50410763/197925829-21b59b60-a2e1-496f-b58f-109cc91bc7cb.png)

请问老哥,你最后是怎么解决的

**Comment by Charlespater** [comment]
if (Boot.plugins.length < 13) {
&nbsp; Boot.registerModule(attachmentModule);
}




组件外层加上这个判断
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月8日(星期四) 中午11:19
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] react wangEditorV5 使用自定义上传附件功能，报没有配置上传地址的错误 (Issue #4991)





  
改为系统内置Server，也报这个错误 
  
请问老哥,你最后是怎么解决的
