### ISSUE TITLE
customPaste粘贴问题

### ISSUE THREAD

**Issue by codercqw** [wangeditor-team/wangEditor#4992]
## bug 描述

从微信，钉钉，浏览器控制台复制的内容粘贴到富文本，默认事件阻止不了，会粘贴两份内容。

## 你预期的样子是？

只粘贴一份内容

## 系统和浏览器及版本号

- windows
- 谷歌浏览器 版本 106.0.5249.119（正式版本） （64 位）

## wangEditor 版本

5.1.21

## demo 能否复现该 bug ？

能

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/s/vue2-wangeditor-demo-forked-sj8fdn?file=/src/components/MyEditor.vue

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 从微信或者钉钉右键复制消息
- 粘贴到富文本中

**Comment by wangfupeng1988** [comment]
没仔细看文档 https://www.wangeditor.com/v5/for-frame.html#%E9%85%8D%E7%BD%AE-1 

vue 里不能 `return false` ，而是 `callback(false)`
