### ISSUE TITLE
TypeError: E is not a constructor

### ISSUE THREAD

**Issue by 1214368261** [wangeditor-team/wangEditor#4993]
## bug 描述
    const E = window.wangEditor
    const editor = new E('#editor')

新版本视乎已经不支持通过构造函数创建editor
看过相关的Issue
作者似乎都在建议去下载官方demo 官方demo确实没问题
纯js使用方式是通过createEditor进行创建的
我将官方的demo下载下来在底下加上
 const editor = new E('#editor')就报错了
TypeError: E is not a constructor

**Comment by wangfupeng1988** [comment]
新版的写法不能用 `new E(..)` 了，不支持了
