### ISSUE TITLE
自定义语言

### ISSUE THREAD

**Issue by wykaipeng** [wangeditor-team/wangEditor#4994]
## 问题描述
自定义语言失不生效
## wangEditor 版本
v4
![微信截图_20221027140022](https://user-images.githubusercontent.com/44160254/198203876-101b0aab-e6fe-48ac-8294-bf8b2d0f3ff4.png)
![image](https://user-images.githubusercontent.com/44160254/198224888-0d0fc73d-7167-42c6-9d53-e35ed7a99b87.png)
## 是否查阅了文档 ？
是

## 最小成本的复现步骤

![微信截图_20221027140432](https://user-images.githubusercontent.com/44160254/198204223-dfb7446a-ccfd-444f-b5dd-3601c7c96292.png)

**Comment by wykaipeng** [comment]
![image](https://user-images.githubusercontent.com/44160254/198224395-943bb193-b9ec-44af-8e14-2f34bcd8fa9a.png)

**Comment by wangfupeng1988** [comment]
v4 版本已经不在维护

业余时间不够，请体谅~
