### ISSUE TITLE
不支持<svg>

### ISSUE THREAD

**Issue by dingshaohua-cn** [wangeditor-team/wangEditor#4995]
## bug 描述
自定义公式引入的时候，公式的有些部分是svg，通过自定义渲染方式已经插入到编辑器内容里的 但是这部分svg并不会显示

**Comment by wangfupeng1988** [comment]
这个问题之前记录了，排队修改。

**Comment by Xiaoxiaojunn** [comment]
现在依然不能支持svg 我用的是vue2的demo
