### ISSUE TITLE
设置了maxLength，复制粘贴时，当粘贴的内容长度大于maxLength，无法粘贴

### ISSUE THREAD

**Issue by lcmomo** [wangeditor-team/wangEditor#4999]
## 问题描述

*设置了maxLength，复制粘贴时，当粘贴的内容长度大于maxLength，无法粘贴*

## wangEditor 版本

*@wangeditor/editor@5.1.22*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
 官网maxLength示例（https://www.wangeditor.com/demo/max-length.html）
maxLength: 30
- 步骤二
复制内容长度大于30的内容，粘贴进编辑区域
- 步骤三
复制的内容无法粘贴

期望粘贴时，如果粘贴内容长度大于maxLength，截取maxLength的长度可以粘贴进编辑区

是否有可实现的替代方法

**Comment by wangfupeng1988** [comment]
暂不支持。目前只能做到：如果超出了不粘贴。

**Comment by lcmomo** [comment]
> 暂不支持。目前只能做到：如果超出了不粘贴。

那如果需要实现在粘贴时，如果粘贴内容长度大于maxLength，截取maxLength的长度可以粘贴进编辑区这样的功能，当前版本有没有可行的办法还活着解决思路呢

**Comment by wangfupeng1988** [comment]
@lcmomo 没有简单的方法，其实我们对于 maxLength 也是很犯难，很多地方不好处理，所以为了保证稳定性，只能先这样来。如果考虑太精细，就会有很多 bug 隐患。
