### ISSUE TITLE
请问我在开发自定义插件的时候 总是遇到一个报错 请问应该怎么避免

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#5005]
报错: Cannot get the end point in the node at path [ X ] because it has no end text node

我在开发自定义组件的时候总是遇到这样的报错 结束文本节点 请问这个一般是哪儿没有处理好导致的  

万分感谢

**Comment by wangfupeng1988** [comment]
光凭这个错误信息，我不知道。

**Comment by beforeBurning** [comment]
大大 请问下 如何可以获取到当前焦点所在的path?

**Comment by beforeBurning** [comment]
let currentPath
    const nodeEntries = SlateEditor.nodes(this.currentEditor, {
      match: (node: SlateNode) => {  // TS syntax
        if (SlateElement.isElement(node)) {
          if (node.type === 'paragraph') {
            return true // 匹配 paragraph
          }
        }
        return false
      },
      universal: true,
    })
    for (let nodeEntry of nodeEntries) {
      const [node, path] = nodeEntry
      currentPath = path
      break;
    }
    console.log(currentPath)
    
我现在使用这种方法获取当前的焦点   请问我这样做合理吗?

**Comment by wangfupeng1988** [comment]
> 大大 请问下 如何可以获取到当前焦点所在的path?

editor.selection 即可看到
