### ISSUE TITLE
有一段奇怪的html字符串无法立即解析，延迟后则可成功解析。

### ISSUE THREAD

**Issue by likaixuan** [wangeditor-team/wangEditor#5006]
## bug 描述

一段html字符串（在线demo中定义了该字符串），如果将该字符串直接定义在变量中则会报以下错误，加延迟则可正确解析。
![image](https://user-images.githubusercontent.com/17825609/198829564-e291901c-42af-417b-8d7c-f03b3005898c.png)

## 你预期的样子是？

不加延迟也可以成功解析

## wangEditor 版本

5.1.12

## demo 能否复现该 bug ？
能

## 在线 demo
fork的wangEditor 官方demo
- https://stackblitz.com/edit/vue3-wangeditor-demo-7ty3s1?file=src%2Fcomponents%2FBasicEditor.vue

## 最小成本的复现步骤

- 步骤一
   打开在线demo - https://stackblitz.com/edit/vue3-wangeditor-demo-7ty3s1?file=src%2Fcomponents%2FBasicEditor.vue
- 步骤二
   默认是加延迟正确解析的结果
![image](https://user-images.githubusercontent.com/17825609/198829807-aee48e66-5767-4c96-9018-37ff2bc3684b.png)

- 步骤三
  将正确情况注释掉，启用错误情况代码即可复现
![image](https://user-images.githubusercontent.com/17825609/198829853-7fcde4a7-89ff-4cf5-931f-27753e1c1706.png)

**Comment by liuqh0609** [comment]
![image](https://user-images.githubusercontent.com/43341115/199144871-20b1364d-37d6-4858-b321-a075501333f2.png)
目测是因为首次挂载组件的时候，value属性值过长导致的vue渲染失败，不是editor的问题  :)

**Comment by likaixuan** [comment]
@liuqh0609 我现在是通过中间变量，加延迟来解决的问题，如果是vue问题，那么为什么这段长value可以绑定文本域呢
```
<wangEditor :model-value="html"/>
data(){
  return {
     html:''
  }
},
watch:{
    modelValue:{
      immediate:true,
      handler(val) {
        this.$nextTick(()=>{
          this.html = val
        })
      }
    }
  },
```

**Comment by liuqh0609** [comment]
> @liuqh0609 我现在是通过中间变量，加延迟来解决的问题，如果是vue问题，那么为什么这段长value可以绑定文本域呢
> 
> ```
> <wangEditor :model-value="html"/>
> data(){
>   return {
>      html:''
>   }
> },
> watch:{
>     modelValue:{
>       immediate:true,
>       handler(val) {
>         this.$nextTick(()=>{
>           this.html = val
>         })
>       }
>     }
>   },
> ```

这个首次挂载组件的时候也不是用的你的长文本吧？你的初始值html不是个空字符串吗？ 你这段代码首次挂载的时候html是个空字符串，watch到变化后再调用$nextTick去触发的re-render

**Comment by liuqh0609** [comment]
猜测是这样的~

**Comment by likaixuan** [comment]
> > @liuqh0609 我现在是通过中间变量，加延迟来解决的问题，如果是vue问题，那么为什么这段长value可以绑定文本域呢
> > ```
> > <wangEditor :model-value="html"/>
> > data(){
> >   return {
> >      html:''
> >   }
> > },
> > watch:{
> >     modelValue:{
> >       immediate:true,
> >       handler(val) {
> >         this.$nextTick(()=>{
> >           this.html = val
> >         })
> >       }
> >     }
> >   },
> > ```
> 
> 这个首次挂载组件的时候也不是用的你的长文本吧？你的初始值html不是个空字符串吗？ 你这段代码首次挂载的时候html是个空字符串，watch到变化后再调用$nextTick去触发的re-render

我这是不得已而为之的，如果直接将这段长value绑定到editor的model-value就会报错了，通过中间变量加延迟是我想出来的hack手段，目前至少是能用了，我把这段长文本试过几个其他的富文本是没有问题的，但是目前那些富文本编辑器都不如wang干净，好用。
