### ISSUE TITLE
能否升级slatejs 版本到最新

### ISSUE THREAD

**Issue by plilion** [wangeditor-team/wangEditor#5009]
## 问题描述

我开发是基于electron 12 当前最新版本的wangeditor 在该electron版本上有个问题
当行末尾是一个inline void 元素时，就比如说 metion 插件，光标无法选中行末，而是直接选中 void 元素
我这边测试了，slatejs 给的官方metion 示例 在electron 12 上是没有问题的，

所以能否将 slate 升级到最新
或者我自己拉代码 自己进行升级， 这样的话，我该怎么做
## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
当做 bug 记录，我近期没有时间修复，得等等

**Comment by wangfupeng1988** [comment]
> 或者我自己拉代码 自己进行升级， 这样的话，我该怎么做

开发文档参考这里 https://github.com/wangeditor-team/wangEditor/blob/master/docs/dev.md

**Comment by plilion** [comment]
问题解决了，不是slate版本问题，只需要在包裹inline void元素的那个节点上添加margin: 0 1px
