### ISSUE TITLE
在工具栏设置字体大小后，输入三段文字，再分别设置H1-H5标题，H3-H5标题的字体变的一样大了

### ISSUE THREAD

**Issue by zhangyueteng87** [wangeditor-team/wangEditor#5010]
## bug 描述

在工具栏设置字体大小后，输入三段文字，再分别设置H1-H5标题，H1-H5标题的字体变的一样大了

## 你预期的样子是？

H1-H5字体大小不受设置字体大小影响

## 系统和浏览器及版本号

- 操作系统：windows
- 浏览器和版本:chrome

## wangEditor 版本 

版本为5.1.22

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤
打开官网demo,设置字体大小，然后输入三行文字，再分别设置为标题H1-H5任意标题
![`%AGS NM1NRX7G(D@(`~GIG](https://user-images.githubusercontent.com/17950122/198869026-22799c96-1f40-4027-8e2c-8c8149ed6446.png)

**Comment by wangfupeng1988** [comment]
我也是 chrome 浏览器，用官网 demo 看是正常的，H1 - H5 逐步字体变小。（现在不方便截图）

**Comment by yuxiu27** [comment]
@wangfupeng1988 h1-h5在编辑器里面的展示样式，可以预览的时候显示出来么，预览的时候不再设置样式

**Comment by wangfupeng1988** [comment]
> h1-h5在编辑器里面的展示样式

编辑器没有对 h1 - h5 设置任何样式，都是浏览器的默认样式

**Comment by zhangyueteng87** [comment]
> 我也是 chrome 浏览器，用官网 demo 看是正常的，H1 - H5 逐步字体变小。（现在不方便截图）



> 我也是 chrome 浏览器，用官网 demo 看是正常的，H1 - H5 逐步字体变小。（现在不方便截图）

要先设置字体大小，然后再设置H1 - H5

**Comment by zhangyueteng87** [comment]
> 我也是 chrome 浏览器，用官网 demo 看是正常的，H1 - H5 逐步字体变小。（现在不方便截图）
1. 设置字体大小 为17px
2. 然后输入三行文字，
3. 第一行设置成H1,第二行设置成H2, 第三行设置成H3
然后就会出现H1,H2,H3标题一样大了

**Comment by wangfupeng1988** [comment]
> 设置字体大小 为17px

你咋设置的，编辑器里没有 17px

**Comment by loringray** [comment]
headerSelect 栏是不是不能自定义 H 标签，比如删除掉 H4、H5 相关标签之类？ 只能通过重写一个自定义菜单来重做 一个类似 headerSelect 功能吗？

**Comment by loringray** [comment]
headerSelect 栏是不是不能自定义 H 标签，比如删除掉 H4、H5 相关标签之类？ 只能通过重写一个自定义菜单来重做 一个类似 headerSelect 功能吗？

**Comment by zhangyueteng87** [comment]
> 
在默认字体大小下，输入三行字，再分别设置H标签，H标签字体大小都是正常的，
但是如果先设置字体大小，输入三行字，再分别设置H标签，H标签的字体大小就一样了

**Comment by zhangyueteng87** [comment]
> > 设置字体大小 为17px
> 
> 你咋设置的，编辑器里没有 17px

在默认字体大小下，输入三行字，再分别设置H标签，H标签字体大小都是正常的，
但是如果先设置字体大小，输入三行字，再分别设置H标签，H标签的字体大小就一样了

**Comment by wangfupeng1988** [comment]
你咋设置的，编辑器里没有 17px
