### ISSUE TITLE
insertNodes 不能添加图片

### ISSUE THREAD

**Issue by 304338620** [wangeditor-team/wangEditor#5011]
## wangEditor 版本
5.1.22
*请输入内容……*

调用inserNodes 图片node 结构是 
```js
 {
        type: 'image',
        src: 'https://picb4.photophoto.cn/39/678/39678534_1.jpg',
        style:{
            width: '100px',
            height: '100px'
        },
        children: [{ text: '' }]
    },
```
其余得都可以插入，图片能插入到编辑器种

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
我在 demo 可以插入。看如下

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/9583120/199020454-cb0614e1-5765-4d29-a852-75b053d6bcc4.png">

**Comment by 304338620** [comment]
单张图片是没有问题得，如果是多个节点就不可以插入图片



可以看我在demo上得代码,我用分批次插入暂时实现了需求，不过还是希望可以实现这个功能


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] insertNodes 不能添加图片 (Issue #5011)





 
我在 demo 可以插入。看如下

**Comment by 304338620** [comment]
> 如果你实现不了，请提供详细的复现步骤。

![image](https://user-images.githubusercontent.com/42160786/199460226-f1a3c644-758b-4556-81df-d603a0a9027d.png)
这是demo上得代码图片，我看上面好像没有显示出来

**Comment by wangfupeng1988** [comment]
@304338620 image 要在 paragraph 内部

**Comment by 304338620** [comment]
我试了下，放到这个里面确实可以了，谢谢解答，这个能不能在文档中加下，文档中好像没有看到这个描述


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 上午8:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] insertNodes 不能添加图片 (Issue #5011)





 
@304338620 image 要在 paragraph 内部
