### ISSUE TITLE
DomEditor.getHoverbar获取结果为null

### ISSUE THREAD

**Issue by faith1224** [wangeditor-team/wangEditor#5013]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本
5.0
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤
菜单的

hoverbarKeys: {
        button: {
          menuKeys: ['editButton', 'deleteButton'],
        },
      },
编辑器元素选中能展示hoverbar，但是DomEditor.getHoverbar(editor)获取结果为null
想问下DomEditor.getHoverbar的前置条件是什么或者有没有demo什么的
麻烦大佬
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 但是DomEditor.getHoverbar(editor)获取结果为null

editor 是不是 null ？？

**Comment by faith1224** [comment]
editor获取的到，不是null

**Comment by wangfupeng1988** [comment]
你提供给一个在线 demo 吧。
