### ISSUE TITLE
Could not completely normalize the editor after 252 iterations!

### ISSUE THREAD

**Issue by sqllinfo** [wangeditor-team/wangEditor#5014]
## 问题描述

你好，我实在做自定义菜单的时候遇到的这个问题
![image](https://user-images.githubusercontent.com/21186265/199177302-3c0b8837-6eb0-46e7-9900-9cd3282fa598.png)

我用的是v5版本的编辑器，框架是vue2 ，
自定义的菜单我是参照着写的。
![image](https://user-images.githubusercontent.com/21186265/199178266-344ad5b0-012e-4ded-aa19-8ea85e501e50.png)

结果是 数据是插入到了 编辑器的，样式也看着没问题。但是一直报这个错。文档翻了半天 也不知道怎么解决。所以发上来让大佬指一个方向

**Comment by wangfupeng1988** [comment]
提供一个在线 demo 吧。以下平台三选一

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by sqllinfo** [comment]
不好意思  才看到。我检查到是我注册了多个自定义菜单，但是只写了一个plugin 文件 来劫持isInline和 isViod  冲突，所以出了问题 ，但是如果写多个plugin文件  注册的时候又不能和renderElems 这种文件以数组的形式注册进去   这种应该怎么处理呢。我翻了很多次文档和demo 代码  看到好像都是只写了一个自定义菜单的注册

**Comment by sqllinfo** [comment]
`
function withKnot(editor) {
  const { isInline,isVoid } = editor
  const newEditor = editor

  // 重写 isInline
  newEditor.isInline = elem => {
    const type = DomEditor.getNodeType(elem)
    if (type === 'knots') {
      return true
    }
    return isInline(elem)
  }
  
  // 重写 isVoid
  newEditor.isVoid  = elem => {
    const type = DomEditor.getNodeType(elem)
    if (type === 'knots') {
      return true
    }
    return isVoid (elem)
  }
  // 重写 isInline
  newEditor.isInline = elem => {
    const type = DomEditor.getNodeType(elem)
    if (type === 'chapters') {
      return true
    }
    return isInline(elem)
  }
  
  // 重写 isVoid
  newEditor.isVoid  = elem => {
    const type = DomEditor.getNodeType(elem)
    if (type === 'chapters') {
      return true
    }
    return isVoid (elem)
  }
  
  // 返回 editor ，重要！
  return newEditor
}

export default withKnot`

**Comment by wangfupeng1988** [comment]
> 注册了多个自定义菜单，但是只写了一个plugin 文件

这个太正常了，随便找个插件源码（如 [上传附件](https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment/blob/main/src/module/index.ts)） ，都有这种模式：多个菜单，一个 plugin

**Comment by wangfupeng1988** [comment]
> 我自己做了很多个 类似上传附件 数学公式 等等的功能

那就一个模块一个模块的单独注册，别混在一起。
