### ISSUE TITLE
自定义了粘贴，就覆盖掉了复制粘贴图片走上传图片这个逻辑

### ISSUE THREAD

**Issue by maojie0047** [wangeditor-team/wangEditor#5018]
## 问题描述

自定义了粘贴，就覆盖掉了复制粘贴图片走上传图片这个逻辑

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

1.editorConfig.customPaste = function (editor, event) {
//自定义了粘贴逻辑，
//阻止了默认粘贴行为
event.preventDefault();
 return false;
请问我怎么写复制粘贴走上传图片这个逻辑啊

}

**Comment by wangfupeng1988** [comment]
首先，你要获取到粘贴的内容，并从内容得到图片。从这里开始，先自己探索一下。

**Comment by maojie0047** [comment]
> 
感谢大佬，已经解决了

**Comment by sumaa007** [comment]
> 

大佬，这里遇见了个问题，我自定义粘贴，我同时复制图片和文字，但是图片所在那个节点是text/html，不是单独的节点，kind 并不是 file, 
所以这里我需要怎么处理能正常识别到那个img标签呢，求解答

**Comment by FirthTuckman** [comment]
onEditorPaste: (editor, event) => {
	let text = event.clipboardData.getData('text/plain')
	if (text != '') editor.insertText(event.clipboardData.getData('text/plain')) && event.preventDefault()
	return false
}

**Comment by firthtuckman** [comment]
```
onEditorPaste: (editor, event) => {
    let text = event.clipboardData.getData('text/plain')
    if (text.trim() != '') {
	  editor.insertText(text)
	  event.preventDefault()
    }
    return false
}
```
