### ISSUE TITLE
开发环境中文输入法的时候，输入@！#￥%等特殊符号第一遍会连续输入两个相同的字符（例如：@@），删除后再输入就好了，

### ISSUE THREAD

**Issue by chenxxing** [wangeditor-team/wangEditor#5019]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/9583120/199404296-5e025c88-532e-40ea-83dc-c1e78c24644e.png">

没复现。请补充复现步骤
