### ISSUE TITLE
自定义buttonmenu点击时需要触发文件选取和自有的图片上传一样的功能

### ISSUE THREAD

**Issue by hhy1234567** [wangeditor-team/wangEditor#5020]
## 问题描述
react使用wangEditor图片上传时没有办法设置style，想自定义扩展一个上传图片但是没有办法像自带上传一样自定义完一个按钮去触发文件选取框

## wangEditor 版本
"@wangeditor/editor": "^5.1.18",
"@wangeditor/editor-for-react": "^1.0.5",

## 是否查阅了文档 ？
已查阅文档没有找到相关自定义menu按钮去触发上传选取框的api
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
自定义一个ButtonMenu需要点击就触发文件选取
（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考这个 demo  https://www.wangeditor.com/demo/extend-menu.html

在源码中的 `exec` 函数中，去触发即可。
