### ISSUE TITLE
使用H1-H5标题定义标签 菜单栏中的加粗也会添加w-e-active类名变得高亮

### ISSUE THREAD

**Issue by xiazhigithub** [wangeditor-team/wangEditor#5024]
## 问题描述

使用H1-H5标题定义标签 菜单栏中的加粗也会添加w-e-active类名变得高亮 如何才能标签添加标题菜单栏只有标题选中状态

## wangEditor 版本

^4.6.3

## 是否查阅了文档 ？
是
https://www.wangeditor.com/

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
只需要光标停留在添加一个H1-H5标题的标签上 菜单栏中的加粗也会被添加上选中的类名
怎样才能在标题类标签中去除菜单栏加粗的高亮类名

- 步骤一
- 步骤二
- 步骤三
<img width="434" alt="WeChatff1f7b61f1c86448c04fbc8f80f29c29" src="https://user-images.githubusercontent.com/37658532/199441305-a922c9cb-6830-41c1-bb42-9c878061092a.png">

**Comment by wangfupeng1988** [comment]
v4 已经不再维护。业余时间不够，请体谅
