### ISSUE TITLE
取消加粗后，输入拼音时，拼音还是加粗状态！！！斜体、下划线同理

### ISSUE THREAD

**Issue by Leo-Smith** [wangeditor-team/wangEditor#5025]
## bug 描述

*中文输入时，先选择：加粗，然后输入：你好，再取消：加粗，最后输入：你好的拼音，拼音还是加粗状态*

## 你预期的样子是？

*取消加粗、斜体、下划线后，再中文输入拼音时，拼音为取消后的状态*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 选择加粗，输入你好
- 步骤二
- 取消加粗，输入你好的拼音，这时候拼音还是加粗状态
- 步骤三
<img width="447" alt="截屏2022-11-01 下午7 13 22" src="https://user-images.githubusercontent.com/20123187/199671596-10eef38a-fb3e-4515-95d2-aaf45313d656.png">

**Comment by wangfupeng1988** [comment]
只是拼音加粗？还是最终的汉字也加粗？

**Comment by Leo-Smith** [comment]
是的，取消加粗后，再次输入时的拼音还是加粗！！

**Comment by Leo-Smith** [comment]
@wangfupeng1988 麻烦看下，如何解决？

**Comment by wangfupeng1988** [comment]
> 是的，取消加粗后，再次输入时的拼音还是加粗！！


只是拼音加粗？还是最终的汉字也加粗？

**Comment by Leo-Smith** [comment]
@wangfupeng1988 对，只是拼音加粗了！

**Comment by wangfupeng1988** [comment]
> @wangfupeng1988 对，只是拼音加粗了！

那这个问题先待定吧，不是啥大事儿。
