### ISSUE TITLE
如何手动调整文本框大小呢？类似textarea的resize

### ISSUE THREAD

**Issue by heweicong** [wangeditor-team/wangEditor#5026]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本
    "@wangeditor/editor": "^5.1.21",
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
DOM 样式都是自己定义的，自己写 CSS 定义尺寸即可。

**Comment by heweicong** [comment]
实现这个功能很难？

**Comment by heweicong** [comment]
> DOM 样式都是自己定义的，自己写 CSS 定义尺寸即可。

实现这个功能很难？

**Comment by wangfupeng1988** [comment]
不难啊，写几句 css 即可

**Comment by heweicong** [comment]
需求是用户自己调整 不是程序员自己写死css 就像textarea右下角的功能一样 无语.....

**Comment by wangfupeng1988** [comment]
> 需求是用户自己调整 不是程序员自己写死css 就像textarea右下角的功能一样 无语.....

这也需要你自己实现
