### ISSUE TITLE
图片尺寸大小的设置能自定义配置吗

### ISSUE THREAD

**Issue by TaurusPeople** [wangeditor-team/wangEditor#5029]
![image](https://user-images.githubusercontent.com/103545274/199911533-d8591e8d-ea22-4b66-b32e-521a3e4ac7e6.png)
例如原来只有30%，50%，100%，我想在原有的基础上增加一个15%这样的

**Comment by wangfupeng1988** [comment]
自定义菜单，具体参考文档
