### ISSUE TITLE
需要获取光标前的内容

### ISSUE THREAD

**Issue by hsdr** [wangeditor-team/wangEditor#5031]
需要获取光标前的内容

需要获取光标前的内容，比如 123光标456 ，即拿到123
## wangEditor 版本
5.0.0

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
如果你当前只有 `<p>123 光标 456</p>` 那比较简单。

执行 `editor.selection` ，即可获取 path ，即这个元素的位置。然后通过 offset 获取光标的位置，然后你就可以计算拿到 `123`

-----

如果你的 HTML 结构更加复杂，那就需要自己分各种情况计算了。
