### ISSUE TITLE
外部如何替换富文本内节点文本

### ISSUE THREAD

**Issue by gleams** [wangeditor-team/wangEditor#5032]
## 问题描述

1. 文本编辑器和外部功能联动：
- 文本编辑器内容是：徐徐如生，（错别字要求高亮显示）
- 外部展示错误的文字列表， 徐徐如生-> 栩栩如生 [替换] [忽略]
- 需要实现的功能是：
   - 点击[替换]按钮，替换富文本内的错误文字
   -  点击[忽略]按钮，取消高亮

- 现状：通过自定义元素实现高亮，
## wangEditor 版本
v5

## 是否查阅了文档 ？

查阅了文档滚动功能已经实现，自定义元素已经实现，

*是/否*

## 最小成本的复现步骤

- 怎么实现替换、和忽略功能

**Comment by wangfupeng1988** [comment]
这个比较复杂，我一时也梳理不清楚

感觉和代码高亮差不多，可以参考源码看看 https://github.com/wangeditor-team/wangEditor/tree/master/packages/code-highlight

**Comment by ByronYan01** [comment]
> ## 问题描述
> 1. 文本编辑器和外部功能联动：
> 
> * 文本编辑器内容是：徐徐如生，（错别字要求高亮显示）
> * 外部展示错误的文字列表， 徐徐如生-> 栩栩如生 [替换] [忽略]
> * 需要实现的功能是：
>   
>   * 点击[替换]按钮，替换富文本内的错误文字
>   * 点击[忽略]按钮，取消高亮
> * 现状：通过自定义元素实现高亮，
> 
> ## wangEditor 版本
> v5
> 
> ## 是否查阅了文档 ？
> 查阅了文档滚动功能已经实现，自定义元素已经实现，
> 
> _是/否_
> 
> ## 最小成本的复现步骤
> * 怎么实现替换、和忽略功能

请问实现了吗，能分享一下大概思路嘛
