### ISSUE TITLE
如何在不选中文本的情况下，可以获取光标之前的内容

### ISSUE THREAD

**Issue by hsdr** [wangeditor-team/wangEditor#5033]
## 问题描述

开发中，需要边输入边把富文本输入的内容传送给后台，但因为每次输入的位置不一定在末尾，不能将所有文本内容全部传送，只需将光标之前的内容传送。比如输入‘456’后将光标放在‘4'前面，再次输入'123'，如何获取‘123’?
## wangEditor 版本

v5

## 是否查阅了文档 ？

是（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

## 最小成本的复现步骤

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
https://github.com/wangeditor-team/wangEditor/issues/5031 和这个重复了
