### ISSUE TITLE
点击代码块时 ，选择语言的弹出框在上方出现，只能看到部分语言选项，大部分被工具栏所遮挡

### ISSUE THREAD

**Issue by seven4233** [wangeditor-team/wangEditor#5034]
## bug 描述
点击代码块时 ，选择语言的弹出框在上方出现，只能看到部分语言选项，大部分被工具栏所遮挡

## 你预期的样子是？

能看到所有选项，及弹出框应该在当前位置的下方出现，而不应该是在上方，

## 系统和浏览器及版本号

- 操作系统  win11
- 浏览器和版本  : Microsoft Edge
 版本 107.0.1418.35 (正式版本) (64 位)

## wangEditor 版本
v5

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
截个图看看。

**Comment by seven4233** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月5日(星期六) 晚上9:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 点击代码块时 ，选择语言的弹出框在上方出现，只能看到部分语言选项，大部分被工具栏所遮挡 (Issue #5034)





 
截个图看看。

**Comment by wangfupeng1988** [comment]
没看到截图

**Comment by seven4233** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月6日(星期天) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 点击代码块时 ，选择语言的弹出框在上方出现，只能看到部分语言选项，大部分被工具栏所遮挡 (Issue #5034)





 
没看到截图

**Comment by 1034148617** [comment]
我也碰到类似问题，当编辑器处于非全屏模式下，代码块位置在屏幕中央，选择语言的时候部分选择被工具栏遮挡了
![image](https://user-images.githubusercontent.com/43312659/201616189-7ceb4d04-705a-406b-ba52-9d1283a70a48.png)

**Comment by zhaofuwei** [comment]
css自己设置下就好了， 
Editor组件上设置id为 oEditor
#oEditor{
        overflow-y: unset !important;
    } 
就ok了
![image](https://user-images.githubusercontent.com/40260369/219545879-2a5337fc-4ad4-4dd4-b4b6-ab8d579e8185.png)
