### ISSUE TITLE
如何实现通过配置editor的baseurl，图片使用相对地址

### ISSUE THREAD

**Issue by 1044834962** [wangeditor-team/wangEditor#5035]
## 问题描述

如何实现通过配置editor的baseurl，图片使用相对地址
比如：图片地址为：https://www.baidu.com/aaa.jpg
通过配置editor的*baseurl*为https://www.baidu.com
使得图片的url可以设置为/aaa.jpg

## wangEditor 版本

*"@wangeditor/core": "^1.1.14",
    "@wangeditor/editor": "^5.1.18",
    "@wangeditor/editor-for-vue": "^5.1.12",
    "@wangeditor/plugin-ctrl-enter": "^1.1.2",*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

无

**Comment by wangfupeng1988** [comment]
暂不支持。
