### ISSUE TITLE
请问wangeditor支持插入自定义内容吗（插入react组件）

### ISSUE THREAD

**Issue by nwa2018** [wangeditor-team/wangEditor#5036]
## 问题描述

请问wangeditor支持插入自定义内容吗（插入react组件），如何支持，业务在灵活性上更为强大

**Comment by wangfupeng1988** [comment]
插入自定义内容，但需要自己写 render 定义，具体看文档

不支持 react 或 vue 组件 https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E6%96%B0%E5%85%83%E7%B4%A0

**Comment by nwa2018** [comment]
> 插入自定义内容，但需要自己写 render 定义，具体看文档
> 
> 不支持 react 或 vue 组件 https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E6%96%B0%E5%85%83%E7%B4%A0

感谢

**Comment by nwa2018** [comment]
> 插入自定义内容，但需要自己写 render 定义，具体看文档
> 
> 不支持 react 或 vue 组件 https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E6%96%B0%E5%85%83%E7%B4%A0

![image](https://user-images.githubusercontent.com/38412001/200224352-8436a58e-83cf-487f-a07f-0af14baa87e3.png)

通过这种返回仅包含 id 的 vnode，并通过 `ReactDOM.render` 的嫁接方式可以实现渲染 `React` 组件 / `Vue` 组件，这种做法推荐吗？ `WangEditor` 是否考虑暴露方法让用户自行渲染编辑器的 组件而不是通过 snapdom 进行渲染

**Comment by wangfupeng1988** [comment]
> 是否考虑暴露方法让用户自行渲染编辑器

不支持
