### ISSUE TITLE
内容切换经常报错Cannot find a descendant at path [3] in node: {"children":[{"type":"paragraph","children":[{"text":""}]}],

### ISSUE THREAD

**Issue by changzhengithub** [wangeditor-team/wangEditor#5037]
## 问题描述
在vue中创建好富文本后，通过this.editor.setHtml(text)动态的更新内容，只要多更新几次总是报这个 `Cannot find a descendant at path [3] in node: {"children":[{"type":"paragraph","children":[{"text":""}]}], 错误，特别是里面含有代码块为Python类型和其他类型的代码块相互切换时最容易报错。使用clear清楚也不行。

## wangEditor 版本
"@wangeditor/editor": "^5.1.22",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤
就像下面点击左侧，获取接口内容进行设置。
![image](https://user-images.githubusercontent.com/35087343/200174305-58f76e60-5dab-41a5-8aac-49a76c226856.png)

**Comment by changzhengithub** [comment]
我该如何正确动态更新内容

**Comment by leidao** [comment]
在获取接口内容后先设置编辑器获取焦点（editor.select([0, 0])或者editor.focus()）在进行editor.setHtml(text)内容回显

**Comment by wangfupeng1988** [comment]
@changzhengithub 提供一个在线 demo 复现这个问题吧。

以下平台三选一即可

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by bbhxwl** [comment]
很奇怪，时不时的出现这个问题。没办法用。

**Comment by gushenyi123** [comment]
我也遇见了这个问题，也不知道问题出在哪里

**Comment by bbhxwl** [comment]
> 我也遇见了这个问题，也不知道问题出在哪里

我已经换其他的用了。

**Comment by ruinb0w** [comment]
> 

现在用的什么?

**Comment by ghost** [comment]
> > 我也遇见了这个问题，也不知道问题出在哪里
> 
> 我已经换其他的用了。

现在用的什么?

**Comment by sunkebkn8** [comment]
这个问题真的特别烦

**Comment by hh-cat** [comment]
我解决这个问题的办法是，每次显示富文本编辑器的时候使用v-if，每次都创建一个新的实例。如果editor组件没有销毁的话，第一次显示内容是正常的，后续的就报错了。

**Comment by ZongYan30** [comment]
每次都创建一个新的实例,

> 我解决这个问题的办法是，每次显示富文本编辑器的时候使用v-if，每次都创建一个新的实例。如果编辑器组件没有调查的话，第一次显示内容是正常的，后续的就报错了。
我是在模态框中，点击编辑按钮之后，打开模态框，然后接口返回的数据使用setHtml()设置，就会报Cannot find ascendant at path [3] in node:,我也想试着去每次打开模态框都重新创建，但是官方文档没有对应的创建API,只有destory()

**Comment by AlberCham** [comment]
我是在每次成功渲染了编辑器之后，再给编辑器加上内容，能解决这个bug

**Comment by fanzhongke** [comment]
我是本地可以，部署线上就报错了，而且不能删除，配置栏有时禁用有时可用
