### ISSUE TITLE
wangeditorV4 版本升级至 V5 版本后，使用 setHtml 方法无法正常渲染 table 表格

### ISSUE THREAD

**Issue by qlHuo** [wangeditor-team/wangEditor#5039]
## bug 描述

V4 版本下的 table 表格在 V5 版本下无法正常渲染。

## 你预期的样子是？

期望V5版本可以兼容V4版本的table，可以正常渲染。

## 系统和浏览器及版本号

- 操作系统
 windows
- 浏览器和版本
 Google Chrome | 89.0.4389.90 (正式版本) （64 位）

## wangEditor 版本
升级前是 wangEditor 4.7.15
升级后使用的是：
 "@wangeditor/editor": "^5.1.22",
 "@wangeditor/editor-for-vue": "^1.0.2",

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

目前发现有两种情况：

1. table外包裹了h标签。这种情况是因为在v4版本设置的表格时生成的html标签。在v5版本使用 setHtml 无法正常渲染，demo 也无法渲染
```html
<h2 id="91yg4">定位</h2><h2><table><tbody><tr><th><font size="3"><span style="font-weight: bolder;">概览</span><br/></font></th><th><span style="font-weight: bolder;"><font size="3">统计</font></span></th></tr><tr style="height: 22.5pt;"><td style="padding: 2.25pt 3.75pt; height: 22.5pt; border-bottom-width: 1pt; border-right-width: 1pt; border-left: 1pt solid rgb(204, 204, 204); border-image: initial; border-top: none;"><font size="3">侧重项目级信息</font></td><td style="padding: 2.25pt 3.75pt; height: 22.5pt; border-bottom-width: 1pt; border-right-width: 1pt; border-top: none; border-left: none;"><font size="3">侧重业务各环节数据<br/></font></td></tr><tr style="height: 22.5pt;"><td style="padding: 2.25pt 3.75pt; height: 22.5pt; border-bottom-width: 1pt; border-right-width: 1pt; border-left: 1pt solid rgb(204, 204, 204); border-image: initial; border-top: none;"><p><font size="3">侧重项目过程即时展示</font></p></td><td style="padding: 2.25pt 3.75pt; height: 22.5pt; border-bottom-width: 1pt; border-right-width: 1pt; border-top: none; border-left: none;"><font size="3">侧重阶段性结果分析<br/></font></td></tr><tr style="height: 22.5pt;"><td style="padding: 2.25pt 3.75pt; height: 22.5pt; border-bottom-width: 1pt; border-right-width: 1pt; border-left: 1pt solid rgb(204, 204, 204); border-image: initial; border-top: none;"><font size="3">侧重简单描述性统计</font></td><td style="padding: 2.25pt 3.75pt; height: 22.5pt; border-bottom-width: 1pt; border-right-width: 1pt; border-top: none; border-left: none;"><font size="3">可自定义较为复杂的数据分析</font></td></tr><tr style="height: 22.5pt;"><td style="padding: 2.25pt 3.75pt; height: 22.5pt; border-bottom-width: 1pt; border-right-width: 1pt; border-left: 1pt solid rgb(204, 204, 204); border-image: initial; border-top: none;"><font size="3">面向角色：所有项目成员<br/></font></td><td style="padding: 2.25pt 3.75pt; height: 22.5pt; border-bottom-width: 1pt; border-right-width: 1pt; border-top: none; border-left: none;"><font size="3">面向角色：管理者、业务负责人<br/></font></td></tr></tbody></table><br/></h2>
```

**demo中测试**

![image](https://user-images.githubusercontent.com/49195759/200241085-8114713c-cf28-44d5-b6d6-974f7ee44622.png)

**demo控制台中测试**

![image](https://user-images.githubusercontent.com/49195759/200241251-3afd8630-5d61-48e5-acaf-476b8e54e312.png)

2. table 外层包裹了两层 div 时，使用 editor.setHtml() 方法无法正常渲染，但是在demo中可以渲染成功（demo控制台使用editor.setHtml 无法成功）。。
```html
<div><table><tbody><tr><th>类目</th><th>内容</th><th>日期</th><th>工时</th><th>人员</th><th>其他</th><th>备注</th></tr><tr><td>AAAA</td><td><p>BBBB</p></td><td>CCCC</td><td>DDDD</td><td>EEEE</td><td>FFFF</td></tr></tbody></table></div></div></div>
```

**demo中测试**

![image](https://user-images.githubusercontent.com/49195759/200240439-e4ea89ca-6472-4c37-a4b1-764713ad7098.png)

**demo控制台中测试**

![image](https://user-images.githubusercontent.com/49195759/200240652-d8445d4e-07c6-4f9c-a64d-7f9b289ad496.png)

**Comment by wangfupeng1988** [comment]
> table外包裹了h标签。

> table 外层包裹了两层 div 时

这些都是非常规 HTML 格式，v5 不支持。

**Comment by qlHuo** [comment]
> 
好吧，我目前是用自定义扩展的方式 在 setHtml 方法中用正则做了处理。

这些非常规的 HTML 格式是从 V4 版本中生成的，官方是否可以考虑一下兼容旧版本的格式呢？

**Comment by wangfupeng1988** [comment]
我也想兼容啊，但难度太大了，而且情况不可枚举。

因为  v4 兼容所有 HTML 格式
