### ISSUE TITLE
vue2引用上传附件功能报错

### ISSUE THREAD

**Issue by jysunshine** [wangeditor-team/wangEditor#5040]
## 问题描述
vue2引用上传附件功能报错

*请输入遇到的问题...*
npm install @wangeditor/plugin-upload-attachment 没报错
import attachmentModule from '@wangeditor/plugin-upload-attachment' 引入后报错，报错如下图
![image](https://user-images.githubusercontent.com/117065398/200243691-0328b169-f9ca-45f3-aac4-4d2b31900af4.png)

## wangEditor 版本
5.1.22

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by jysunshine** [comment]
已解决，升级了版本
npm install babel-loader @babel/core @babel/preset-env -D

**Comment by liuqh0609** [comment]
你可以先尝试手动安装该包试一下，看是否还有报错:
`npm i --save-dev @babel/preset-env`

**Comment by callqh** [comment]
试试指定一下版本`7.13.12`,或者删除node_modules重新安装
