### ISSUE TITLE
vue安装完引入就报错

### ISSUE THREAD

**Issue by Stars-and-sea** [wangeditor-team/wangEditor#5041]
## bug 描述
引入Editor或者Toolbar就报错
![QQ截图20221107145445](https://user-images.githubusercontent.com/82701276/200245139-c08c5e84-bc00-4b0d-88fb-18b3e2ea533b.png)

## 你预期的样子是？
不报错
## 系统和浏览器及版本号
chrome 版本 107.0.5304.88（正式版本） （64 位）
win10专业版 1903  18362.239
vue 2.7

## wangEditor 版本
"@wangeditor/editor": "^5.1.22"
 "@wangeditor/editor-for-vue": "^1.0.2"

## demo 能否复现该 bug ？
稳定复现

## 在线 demo
由于数据保密问题，提供不了

## 最小成本的复现步骤
安装完  引入就报错

**Comment by Stars-and-sea** [comment]
最开始用着都没问题的，然后过了几天突然就出现这个报错了，也没有改过相关得代码

**Comment by Stars-and-sea** [comment]
已经在vue.config.js里面加上了一下代码，依然报同样的错
![QQ截图20221107161026](https://user-images.githubusercontent.com/82701276/200258638-1d9475ad-7a1b-4f26-ad2f-dddbea1179eb.png)
![QQ截图20221107161036](https://user-images.githubusercontent.com/82701276/200258683-6eb25414-be2a-440d-827d-2b770e580256.png)

**Comment by wangfupeng1988** [comment]
> 安装完 引入就报错

参考官网提供的 Vue demo 吧。

----

或者提供详细的复现步骤，否则我也不知道怎么复现。
