### ISSUE TITLE
调用editor.focus()，未弹出键盘

### ISSUE THREAD

**Issue by Leo-Smith** [wangeditor-team/wangEditor#5043]
## bug 描述

*用手机微信打开demo，在onMounted后，延迟300毫秒，调用editor.focus()，软键盘未弹出*

## 你预期的样子是？

*在onMounted后，延迟300毫秒，调用editor.focus()，软键盘正常弹出，相应的onFocus方法回调*

## 系统和浏览器及版本号

- 操作系统 iOS
- 浏览器和版本 微信内打开demo

## wangEditor 版本

*5.1.22*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一 本地运行demo，在onMounted中延迟300毫秒，调用editor.focus()
- 步骤二 同wifi下，用手机微信打开demo页面
- 步骤三 软键盘没有弹出

**Comment by wangfupeng1988** [comment]
目前不支持 移动端 编辑器。
