### ISSUE TITLE
为什么输入中文标点符号，getHtml（）里面会不显示标点符号

### ISSUE THREAD

**Issue by xxlhello** [wangeditor-team/wangEditor#5044]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
输入了什么符号？几个图

另外，什么输入法，什么浏览器，什么版本

**Comment by xxlhello** [comment]
就简单输入句号。。。搜狗输入法，谷歌浏览器版本 72.0.3626.121（正式版本）

**Comment by wangfupeng1988** [comment]
低版本浏览器对字符有 bug，这是已知问题。目前尚无时间修复

你看能不能找个最新版的 chrome 试试，看有这个问题吗
