### ISSUE TITLE
onFocus 只响应一次 onBlur一次都没响应

### ISSUE THREAD

**Issue by 13430390652** [wangeditor-team/wangEditor#5045]
<Editor 
       @onFocus="onFocus"
       @onBlur="onBlur"
/>

 // 第一点输入框时有输出，点击其它元素再点击输入框时，这个函数就不生效了
onFocus(editor) { console.log('onFocus', editor) }, 

// 这个函数一次都不生效
onBlur(editor) { console.log('onBlur', editor) },

望解决，谢谢！

**Comment by wangfupeng1988** [comment]
请按照 issue 模板详细提交。
