### ISSUE TITLE
select()方法调用有问题 

### ISSUE THREAD

**Issue by kangnajSN** [wangeditor-team/wangEditor#5046]
## 问题描述

*请输入遇到的问题...*
select()调用之后使用getSelectionText()方法无法获取到当前选区的内容、但是selectAll()方法可以

## wangEditor 版本
@wangeditor/editor-for-vue 5.1.12
*请输入内容……*

## 是否查阅了文档 ？
yes
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 编辑器选择一段文字、在编辑器之外使用按钮更改样式
- 步骤二 点击按钮想清除原先选中的样式、先调用 editor.focus() 聚焦、然后调用 select() 无法选中
- 步骤三 报错 Cannot resolve a DOM point from Slate point: {"path":[5,0],"offset":40}

**Comment by kangnajSN** [comment]
![1667894629099](https://user-images.githubusercontent.com/46366457/200508425-c29456c5-9846-41d3-912b-a798e252ac3d.jpg)

**Comment by kangnajSN** [comment]
![image](https://user-images.githubusercontent.com/46366457/200508626-917edc0a-a454-436e-9466-6d9153cbad30.png)

**Comment by kangnajSN** [comment]
![image](https://user-images.githubusercontent.com/46366457/200508883-652d95e0-8d10-413e-811f-2da5bff55612.png)
selectAll()  则可以选中

**Comment by wangfupeng1988** [comment]
请提供一个在线 demo 。

以下三选一即可

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by kangnajSN** [comment]
https://codesandbox.io/s/frosty-scooby-zwwfsw?file=/src/App.vue

**Comment by kangnajSN** [comment]
https://codesandbox.io/s/frosty-scooby-zwwfsw?file=/src/App.vue


久等了、麻烦您看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月8日(星期二) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] select()方法调用有问题  (Issue #5046)





 
请提供一个在线 demo 。
 
以下三选一即可
  
https://codesandbox.io/
 
https://codepen.io/
 
https://stackblitz.com/

**Comment by kangnajSN** [comment]
![image](https://user-images.githubusercontent.com/46366457/200533132-8ff122b1-6282-46a6-a88c-2b3372397a99.png)
![image](https://user-images.githubusercontent.com/46366457/200533228-eacdbb08-5dd7-457f-9e7a-f64c765e94a1.png)
刚刚又尝试了一番、发现当我把path中的[5, 0] 改成 [0,0]就可以正常获取

**Comment by kangnajSN** [comment]
![image](https://user-images.githubusercontent.com/46366457/200533583-8b754c6a-c60c-4661-9e1d-04d5f8081bfd.png)
可以正常选择第一行

**Comment by kangnajSN** [comment]
> 是的，第一行的 path 是 `[0]`

但是除了第一行能选中、其他都不可以、很奇怪

**Comment by wangfupeng1988** [comment]
其他的，你得找到这个节点的 path ，即可选中

**Comment by kangnajSN** [comment]
我用的是 this.editor.selection 获取的位置信息、这个不对吗？或者我应该通过什么样的代码才能实现我想要的功能？

**Comment by wangfupeng1988** [comment]
如下图，在官网 demo 中，想要选中第二行的两个字母，就执行这个代码即可

```js
const s = {"anchor":{"path":[1,0],"offset":1},"focus":{"path":[1,0],"offset":3}};
editor.select(s);
```

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/9583120/200782406-e2d19a09-0248-4924-bf83-3494b6243f3e.png">
