### ISSUE TITLE
昨天提过引入就报错的问题，今天发现了问题关键点

### ISSUE THREAD

**Issue by Stars-and-sea** [wangeditor-team/wangEditor#5049]
## 问题描述
https://github.com/wangeditor-team/wangEditor/issues/5041#event-7752318183
以上是上次问题描述
我之前用的没问题，也没人改过相关的代码，但是后面就突然发现了这个报错
我通过代码回退找到了出问题的版本，经过对比发现应该是下面的问题造成的
我最开始在Array的原型链上直接自定义了一个remove方法，这个时候用编辑器是没问题的
后来我遇到一个问题，有一些代码里面用for in 遍历了数组，导致了一些功能出现了警告，我排查问题发现，for in遍历数组会把数组原型链上的方法和属性也给遍历出来，虽然用for in 遍历数组是不被推荐的，但是为了防止这种情况造成问题，我就将自定义的remove方法设置成了不可枚举的，然后就导致了上述问题。
![QQ截图20221108220113](https://user-images.githubusercontent.com/82701276/200584510-8a8cda01-254e-4cfe-a9d3-f118f709bd66.jpg)

## wangEditor 版本

"@wangeditor/editor": "^5.1.22",
    "@wangeditor/editor-for-vue": "^1.0.2",

## 是否查阅了文档 ？

是，查阅了，最开始我都是可以正常使用的

## 最小成本的复现步骤

加入如下代码
const remove = function (value) {
  let index = this.indexOf(value)
  if (index > -1) {
    this.splice(index, 1)
  }
  return index
}
Object.defineProperty(Array.prototype, 'remove', {
  value: remove,
  enumerable: false,
})

然后
import { Editor, Toolbar } from '@wangeditor/editor-for-vue'
引入就会报错，不需要注册实例化

**Comment by Stars-and-sea** [comment]
![image](https://user-images.githubusercontent.com/82701276/200586146-86562bf3-4f13-4ab5-b5e8-dd9ad76c2dfb.png)
这是报错信息

**Comment by wangfupeng1988** [comment]
> 在Array的原型链上直接自定义了一个remove方法

这会污染全局的，建议不要这样做

**Comment by Stars-and-sea** [comment]
> > 在Array的原型链上直接自定义了一个remove方法
> 
> 这会污染全局的，建议不要这样做



> > 在Array的原型链上直接自定义了一个remove方法
> 
> 这会污染全局的，建议不要这样做
主要是我直接在Array的prototype上定义久没有问题
但是我先定义一个函数，然后把他挂到Array的prototype上去，并且设置成不可枚举就出错了

**Comment by wangfupeng1988** [comment]
不要修改全局的东西。
