### ISSUE TITLE
图片是否可以按长或宽自由拖拽缩放图片

### ISSUE THREAD

**Issue by nian-x** [wangeditor-team/wangEditor#5053]
## 问题描述
富文本上传完图片之后，只能按等比例拖拽缩放图片，无法按长宽自由拖拽缩放图片
## wangEditor 版本
@wangeditor/editor@5.1.22
## 是否查阅了文档 ？
是的
## 最小成本的复现步骤
<img width="671" alt="image" src="https://user-images.githubusercontent.com/117791371/200722463-feb6fefd-7c07-45be-8f26-c53a2e490ec7.png">

**Comment by wangfupeng1988** [comment]
不支持
