### ISSUE TITLE
onSuccess(file,res)  在成功回调函数中修改res的url属性后，编辑器内部显示的图片仍是回调修改前的

### ISSUE THREAD

**Issue by SK-Luffa** [wangeditor-team/wangEditor#5054]
## 

*请输入遇到的1问题...*
onSuccess(file,res)  在成功回调函数中修改res的url属性后，编辑器内部显示的图片仍是回调修改前的
## wangEditor 版本

*请输入内容……*
^5.1.22
## 是否查阅了文档 ？
yes
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
上传一个file:二进制
- 步骤一
- 正常上传到服务器的一张图片
- 步骤二
- 返回的res前没有拼接域名
- 步骤三
- 在onSuccess中为res.data.url = "域名" + res.data.url;

**Comment by wangfupeng1988** [comment]
onSuccess 只是一个回调，不支持你修改 res 数据。

你这种情况推荐使用 自定义插入 https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD

**Comment by SK-Luffa** [comment]
收到，非常感谢您提供的信息！------------------------------------------------------------------
***@***.***>
日　期：2022年11月09日 13:44:13
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [wangeditor-team/wangEditor] onSuccess(file,res) 在成功回调函数中修改res的url属性后，编辑器内部显示的图片仍是回调修改前的 (Issue #5054)

onSuccess 只是一个回调，不支持你修改 res 数据。
你这种情况推荐使用 自定义插入 https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD
