### ISSUE TITLE
请问如何自定义粘贴内容去除样式

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#5057]
作者大大 看了之前你的回复 使用 https://www.wangeditor.com/v5/editor-config.html#custompaste 来处理 
现在遇到一个问题 如果我的粘贴内容是包含多种形式的 比如说 代码块 之类的 那么我在获取内容的时候 只能使用
`const html = event.clipboardData.getData('text/html') `
那么在插入内容的时候 insertText 会直接把源码插入进来 而不会解析html  请问我应该怎么做才能在去除style标签的基础上 保留code等html元素

**Comment by wangfupeng1988** [comment]
使用 `editor.dangerouslyInsertHtml` 

但它不会识别所有的 HTML 格式，所以需要你自行处理
