### ISSUE TITLE
可否提供一下V5集成 plupload 或者 webuploader

### ISSUE THREAD

**Issue by redmangame** [wangeditor-team/wangEditor#5058]
## 功能描述

可否提供一下V5集成 plupload 或者 webuploader的教程，网上有V2 V3的教程，但是没有V5版本的，我们这边上传的文件比较大，需要类似 plupload的分片上传，以前用的ckeditor现在换到wangEditorV5了，急求，跪求！

**Comment by wangfupeng1988** [comment]
想要分片上传，你直接用 “自定义上传”吧，所有事情自己操作，想用什么工具就用什么。

文档参考 https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD
