### ISSUE TITLE
vue3，父子组件传值，改变不了placeholder的默认值

### ISSUE THREAD

**Issue by coder-zhangfan** [wangeditor-team/wangEditor#5059]
## 问题描述
父子组件传值，改变不了placeholder的默认值

## wangEditor 版本
5.1.22

## 是否查阅了文档 ？
是

## 最小成本的复现步骤
- 步骤一
- 
![1667980659909_10B8B747-5B72-458e-9FFD-6DDA494EE749](https://user-images.githubusercontent.com/48230413/200781857-1ec9b07f-c7d7-41ed-a584-243403e5f3f8.png)

- 步骤二
- 
![1667980728355_71F12B23-323E-4b8c-B022-424D71CB6CA1](https://user-images.githubusercontent.com/48230413/200781880-d58b74a8-24ed-4dbc-a3c6-6c438f36ffe0.png)

- 步骤三
![1667980782331_E1AEB87C-AEE1-4d2a-908E-F3B52CD84CCE](https://user-images.githubusercontent.com/48230413/200781908-6175afde-60be-46ad-ab1f-7778e697c27b.png)

**Comment by andyzhang0511** [comment]
OK  thanks
