### ISSUE TITLE
富文本内容对空格进行替换为&nbsp,撤销会失效，且失去焦点

### ISSUE THREAD

**Issue by nian-x** [wangeditor-team/wangEditor#5061]
## bug 描述

富文本内容对空格进行替换为&nbsp,撤销会失效，且失去焦点

## 你预期的样子是？

撤销正常生效，且不会失去焦点

## 系统和浏览器及版本号

- 操作系统 mac os
- 浏览器和版本  Chrome 99.0.4844.83

## wangEditor 版本
@wangeditor/editor @5.1.22

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

https://codesandbox.io/s/distracted-hoover-6tpu8w?file=/src/App.js

## 最小成本的复现步骤
如在线demo所示，输入空格或者tab键，之后cmd + Z

**Comment by wangfupeng1988** [comment]
> 如在线demo所示，输入空格或者tab键，之后cmd + Z

我试着正常。撤销成功，且没有失焦。

**Comment by nian-x** [comment]
可查看在线demo：https://codesandbox.io/s/distracted-hoover-6tpu8w?file=/src/App.js，百分百必现

https://user-images.githubusercontent.com/117791371/200979180-efbc49d6-b927-408d-84e4-38ba670632ca.mov

**Comment by nian-x** [comment]
这边有一段对富文本的value中空格和\t进行replace的操作
<img width="650" alt="image" src="https://user-images.githubusercontent.com/117791371/200981022-aebee39e-bbfd-43c2-800e-ed31fcebdaf1.png">

**Comment by wangfupeng1988** [comment]
你在官网 demo 可以复现 bug 吗？

**Comment by nian-x** [comment]
对官方demo的value值中的空格替换为&nbsp也能复现

**Comment by nian-x** [comment]
> 

对官方demo的value值中的空格替换为&nbsp也能复现

**Comment by wangfupeng1988** [comment]
首先，不做任何替换，能否复现？
其次，再说为什么要替换。

这俩分开说
