### ISSUE TITLE
请问如何配置这个选中后菜单?

### ISSUE THREAD

**Issue by ExtJSFantasy** [wangeditor-team/wangEditor#5063]
## 问题描述
<img width="482" alt="image" src="https://user-images.githubusercontent.com/23393091/200867884-abf53065-03e4-41e9-ae73-5905240bf703.png">

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
看这里 https://www.wangeditor.com/v5/editor-config.html#hoverbarkeys 

```js
editorConfig.hoverbarKeys = {
    'link': {
        // 重写 text 元素的 hoverbar
        text: ['menu1', 'menu2', 'menu3'],
    },
}
```
