### ISSUE TITLE
vuecli项目使用遇到

### ISSUE THREAD

**Issue by afan0228** [wangeditor-team/wangEditor#5064]
## 问题描述
问题如下：
![image](https://user-images.githubusercontent.com/8581365/200977199-048931d4-8e40-4dfc-b431-066571a1af83.png)
![image](https://user-images.githubusercontent.com/8581365/200977278-17993a5d-8899-4980-880d-c50e6a3661aa.png)

## wangEditor 版本
![image](https://user-images.githubusercontent.com/8581365/200977341-86651d81-1994-4a10-bbfd-4fbd01780403.png)

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
参考官网 vue demo

**Comment by afan0228** [comment]
官网vue demo知道没问题，而且在一个新工程下用有没事，就是之前老项目出这问题，不知道哪里配置有问题还是版本兼容问题……

**Comment by wangfupeng1988** [comment]
需要你提供一个在线 demo 。以下平台三选一

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/
