### ISSUE TITLE
无法处理div包裹的图片文件

### ISSUE THREAD

**Issue by qiphon** [wangeditor-team/wangEditor#5065]
const html = `<p>微软推哦的肥肉体育</p><div class=\"media-wrap image-wrap\"><img id=\"1667549685062_2\" title=\"995d9dfa4e264e4fbfd9eeceb94486c6.jpg\" alt=\"995d9dfa4e264e4fbfd9eeceb94486c6.jpg\" poster=\"\" src=\"http://static.runoob.com/images/demo/demo2.jpg\"/></div>`
        debugger
        editor.setHtml(html)

使用这段HTML调试即可复现，把div 改为 p 标签即可解决

**Comment by wangfupeng1988** [comment]
setHtml 只识别 wangEditor 输出的 HTML 格式。不支持 div 包裹 img

**Comment by wangfupeng1988** [comment]
>  div 包裹 img

可以用 `editor.dangerouslyInsertHtml(html)` 试试
