### ISSUE TITLE
如何让自定义菜单,不被禁用,类似全屏显示

### ISSUE THREAD

**Issue by MagicReader** [wangeditor-team/wangEditor#5066]
## 问题描述

*请输入遇到的问题...*
想让自定义菜单按钮-"一键复制",在菜单栏禁用的情况下,仍然可以点击.
类似全屏显示按钮的效果
![image](https://user-images.githubusercontent.com/33999813/200994545-d895a46a-6b49-4077-9320-9bee295e1006.png)

自定义菜单代码:
`import { Message } from 'element-ui'
import { Boot } from '@wangeditor/editor'

export function registerCustomMenu() {
  Boot.registerMenu(myCopyMenuConf)
}

//  自定义菜单 - 一键复制
const myCopyMenuConf = {
  key: 'my-copy', // 定义 menu key ：要保证唯一、不重复（重要）
  factory() {
    return new MyCopyButtonMenu() // 把 `YourMenuClass` 替换为你菜单的 class
  }
}
class MyCopyButtonMenu {
  constructor() {
    this.title = '一键复制' // 自定义菜单标题
    this.iconSvg = '<span style="display: flex;align-items: center;"><svg t="1668045894544" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2727" width="200" height="200"><path d="M720 192h-544A80.096 80.096 0 0 0 96 272v608C96 924.128 131.904 960 176 960h544c44.128 0 80-35.872 80-80v-608C800 227.904 764.128 192 720 192z m16 688c0 8.8-7.2 16-16 16h-544a16 16 0 0 1-16-16v-608a16 16 0 0 1 16-16h544a16 16 0 0 1 16 16v608z" p-id="2728"></path><path d="M848 64h-544a32 32 0 0 0 0 64h544a16 16 0 0 1 16 16v608a32 32 0 1 0 64 0v-608C928 99.904 892.128 64 848 64z" p-id="2729"></path><path d="M608 360H288a32 32 0 0 0 0 64h320a32 32 0 1 0 0-64zM608 520H288a32 32 0 1 0 0 64h320a32 32 0 1 0 0-64zM480 678.656H288a32 32 0 1 0 0 64h192a32 32 0 1 0 0-64z" p-id="2730"></path></svg>&nbsp;一键复制</span>'
    this.tag = 'button'
  }

  // 获取菜单执行时的 value ，用不到则返回空 字符串或 false
  getValue(editor) {
    return false
  }

  // 菜单是否需要激活（如选中加粗文本，“加粗”菜单会激活），用不到则返回 false
  isActive(editor) {
    return false
  }

  // 菜单是否需要禁用（如选中 H1 ，“引用”菜单被禁用），用不到则返回 false
  isDisabled(editor) {
    return false
  }

  // 点击菜单时触发的函数
  // value 即 this.value(editor) 的返回值
  async exec(editor, value) {
    if (this.isDisabled(editor)) return
    try {
      const html = editor.getHtml()
      this.copyEdit(html)
      Message.success({
        duration: 1500,
        message: '复制成功'
      })
    } catch (e) {
      Message.error({
        duration: 2000,
        message: '复制失败'
      })
      console.error('富文本一键复制失败', e)
    }
  }

  copyEdit(val) {
    const copyHandler = this.copys(val)
    document.addEventListener('copy', copyHandler)
    document.execCommand('copy')
    removeEventListener('copy', copyHandler)
  }

  copys(article) {
    return function (event) {
      event.clipboardData.setData('text/html', article)
      event.preventDefault()
    }
  }
}
`

**Comment by MagicReader** [comment]
通过阅读FullScreen类源码,已经解决问题.
设置类属性alwaysEnable为true即可.
![image](https://user-images.githubusercontent.com/33999813/200996813-f95a9b46-d0ab-4733-9075-3c9648814d25.png)
![image](https://user-images.githubusercontent.com/33999813/200996779-3565d41f-1024-4094-b8ea-124ab8b366da.png)

**Comment by asher-fire** [comment]
oh，dude，thank you

**Comment by hhhyyyy99** [comment]
如果是已经配置好了的的菜单要怎么去扩展呢，还是自己去写一次把默认的覆盖掉吗？例如blod
