### ISSUE TITLE
点击下载附件的按钮浏览器打开了

### ISSUE THREAD

**Issue by jysunshine** [wangeditor-team/wangEditor#5067]
## 问题描述
关于上传附件现有两个问题
1、编辑器设置只读（readOnly:true），附件的下载按钮就不显示了
2、点击附件的下载按钮直接打开了

产品需求：B端编辑器可以上传音视频、图片、附件、生成目录，C端展示音视频、图片、目录，附件点击下载

*请输入遇到的问题...*

## wangEditor 版本
v5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
“上传附件”插件只包含基础功能，再多的功能，需要你自己重新扩展自己的插件。可以参考“上传附件”插件的源码
