### ISSUE TITLE
editor.select(newSelection) 使用时的问题

### ISSUE THREAD

**Issue by shenX1998** [wangeditor-team/wangEditor#5068]
## 问题描述

const newSelection = {
  anchor: { path: [1,0], offset:8 },
  focus: { path: [1,0], offset:10 }
}
path只传一个参数或者不传参数的时候 无法选中指定位置的文字

## wangEditor 版本
"@wangeditor/editor": "^5.1.22"
"@wangeditor/editor-for-vue": "^1.0.2"

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

editor.select({
    anchor: { path: [0], offset: 2 },
    focus: { path: [0], offset: 4 }
})

**Comment by wangfupeng1988** [comment]
那肯定啊。`path: [0]` 不能定位到文本节点。
