### ISSUE TITLE
自定义扩展的元素在编辑其他内容的时候会报错并消失

### ISSUE THREAD

**Issue by Muze-GitHub** [wangeditor-team/wangEditor#5070]
## 问题描述

我自定义了一个新功能并且通过insertNode插入编辑器内，编辑器内能正常渲染
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/57588594/201278347-1fb267ee-7ac2-4866-8870-7c650f02e79c.png">
，获取到的html也是我定义的，但是当鼠标移动到这个自定义元素上的时候就会报错，
<img width="742" alt="image" src="https://user-images.githubusercontent.com/57588594/201278810-e1b19c91-988a-4329-86b9-a414f8ca09ab.png">
当我编辑内容的时候，这个元素就会消失
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/57588594/201279452-64824a74-609b-43ca-ac15-f59f01c44d5e.png">
请问这个错误应该定位到哪里
## wangEditor 版本

5.1.21

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
定义一个新的扩展元素，插入编辑器能正常渲染
- 步骤二
在编辑区域内输入文字
- 步骤三
扩展元素展示异常并报错

**Comment by wangfupeng1988** [comment]
光看截图我也看不出啥问题来。

你参考链接卡片的源码吧 https://github.com/wangeditor-team/wangEditor-plugin-link-card

**Comment by Githezhenping** [comment]
我也是这问题，一模一样
