### ISSUE TITLE
文章内容出现div标签，渲染内容会屏蔽掉所有html标签

### ISSUE THREAD

**Issue by MaLuxray** [wangeditor-team/wangEditor#5071]
## 问题描述

*内容如果出现`div`标签的话，那么显示的话，所有和`html`相关的标签都不会显示*

## wangEditor 版本

*V5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

- 任意`html`文本新增`div`即可复现

**Comment by wangfupeng1988** [comment]
不支持完全解析 div 里面的内容。
