### ISSUE TITLE
SelectMenu's iconSvg is not working

### ISSUE THREAD

**Issue by wadefelix** [wangeditor-team/wangEditor#5074]
## bug 描述

设置SelectMenu的iconSvg属性，但显示不出来

## 系统和浏览器及版本号

- 操作系统 win11
- 浏览器和版本 Microsoft Edge 版本 107.0.1418.42 (正式版本) (64 位)

## wangEditor 版本

最新版

## demo 能否复现该 bug ？

能
https://www.wangeditor.com/demo/extend-menu-select.html 这个demo源码就不能

**Comment by wangfupeng1988** [comment]
SelectMenu 没有 icon
