### ISSUE TITLE
上传图片成功后报错

### ISSUE THREAD

**Issue by ChenJunsen** [wangeditor-team/wangEditor#5076]
## bug 描述

上传图片到自定义服务器。图片是上传成功了。然后报这个错:
![image](https://user-images.githubusercontent.com/22163218/201530316-ba516024-8513-4d4d-9887-c42d0920d4ae.png)

## 你预期的样子是？

看报错，走的是success。但是没有显示链接。理论上，上传完后会在编辑框里面显示上传的图像。现在是白板。

## 系统和浏览器及版本号

- 操作系统
![image](https://user-images.githubusercontent.com/22163218/201530389-598c1f74-e413-44c9-b24e-075d51975b70.png)

- 浏览器和版本
![image](https://user-images.githubusercontent.com/22163218/201530411-a040b9af-3e53-4a41-9123-403549a4157e.png)

## wangEditor 版本

![image](https://user-images.githubusercontent.com/22163218/201530428-7543ca6e-abf8-42fa-85b0-1ea4fd18b79f.png)

*请输入内容……*

## demo 能否复现该 bug ？

能

不确定是否是bug.
我的配置如下:
`this.editor.getConfig().MENU_CONF['uploadImage'] = {
        server: this.uploadAction,
        // 小于该值就插入 base64 格式（而不上传），默认为 0
        base64LimitSize: 5 * 1024, // 5K
        // form-data fieldName ，默认值 'wangeditor-uploaded-image'
        fieldName: 'music-ticket',
        // 单个文件的最大体积限制，默认为 2M
        maxFileSize: 8 * 1024 * 1024, // 8M
        // 最多可上传几个文件，默认为 100
        maxNumberOfFiles: 20,
        // 选择文件时的类型限制，默认为 ['image/*'] 。如不想限制，则设置为 []
        allowedFileTypes: ['image/*'],
        // 自定义上传参数，例如传递验证的 token 等。参数会被添加到 formData 中，一起上传到服务端。
        // meta: {
        //   token: 'xxx',
        //   otherKey: 'yyy'
        // },
        // 将 meta 拼接到 url 参数中，默认 false
        metaWithUrl: false,
        // 自定义增加 http  header
        // headers: {
        //   Accept: 'text/x-json',
        //   otherKey: 'xxx'
        // },
        // 跨域是否传递 cookie ，默认为 false
        withCredentials: true,
        // 超时时间，默认为 10 秒
        timeout: 5 * 1000 // 5 秒
      }`

**Comment by dylan0503** [comment]
请问这个是什么原因导致的，配置的不对嘛
