### ISSUE TITLE
设置值的bug

### ISSUE THREAD

**Issue by Moxin520** [wangeditor-team/wangEditor#5080]
## bug 描述

*清空-》设置值=》清空=》设置值   反复几次控制台就会报错 Error:Cannot find a descendant at path [5] in node:{ .... *

## 你预期的样子是？

*不应该出现这个报错*

## 系统和浏览器及版本号

- 操作系统   win10
- 浏览器和版本  edge107

## wangEditor 版本

*5.1.23*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一   editor.clear()
- 步骤二  setHtml(....)
- 步骤三 editor.clear()
- 反复操作就会出现

**Comment by wangfupeng1988** [comment]
在官网 demo 没有复现。如下图

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/9583120/201802494-f9a3ced3-e193-43f4-9159-3b9e2a47ee41.png">

**Comment by Moxin520** [comment]
不停将setHtml设置值与clearAllText()方法交替使用&nbsp; &nbsp;重复六到七次 一定会复现此问题


或者我的写法上有什么问题嘛?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 上午9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 设置值的bug (Issue #5080)





 
在官网 demo 没有复现。如下图

**Comment by sechi747** [comment]
说一下我的解决方法：我使用了vue2框架，在<Editor>组件上用v-model绑定了一个值，在调用接口之前先把这个绑定的值清空再去setHtml()就可以了

**Comment by bbhxwl** [comment]
> 说一下我的解决方法：我使用了vue2框架，在组件上用v-model绑定了一个值，在调用接口之前先把这个绑定的值清空再去setHtml()就可以了

直接v-model绑定不行么？

**Comment by Moxin520** [comment]
我用的是react18&nbsp; ,不过应该是同理的,我去试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor] 设置值的bug (Issue #5080)





  
说一下我的解决方法：我使用了vue2框架，在组件上用v-model绑定了一个值，在调用接口之前先把这个绑定的值清空再去setHtml()就可以了
  
直接v-model绑定不行么？
