### ISSUE TITLE
编辑器API不生效

### ISSUE THREAD

**Issue by 204065248** [wangeditor-team/wangEditor#5082]
## bug 描述

我在制作一个斜线菜单插件，在菜单的回调函数中使用编辑器api不生效，也不报错

## 你预期的样子是？

`editor.deleteBackward("line");` API删除当前行的内容

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

```
    "@wangeditor/editor": "^5.1.22",
    "@wangeditor/editor-for-react": "^1.0.6",
```

## demo 能否复现该 bug ？

不能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

第一步：重写编辑器的insertText函数
第二步：在该函数中使用snabbdom库创建dom挂载到页面中
第三步：在创建的dom添加click事件
第四步：在事件中调用编辑器API

**Comment by wangfupeng1988** [comment]
> 在创建的dom添加click事件

你确定这个 click 事件被触发了吗？

**Comment by 204065248** [comment]
触发了，不是所有函数都失效。比如setHtml就正常

**Comment by 204065248** [comment]
在click事件外正常调用
![image](https://user-images.githubusercontent.com/17307843/201811349-57ced74b-8bae-480e-a9a8-739f86c71017.png)
在click事件里面无法正常调用
![image](https://user-images.githubusercontent.com/17307843/201814792-d12712aa-1f18-49e5-94f0-61146406c445.png)

**Comment by 204065248** [comment]
在编辑器的onCreated回调函数里也失败
![image](https://user-images.githubusercontent.com/17307843/201816717-a574fcd9-09e2-4548-9ff0-c276781deb32.png)

**Comment by 204065248** [comment]
好奇怪，我给页面增加了一个div元素，div元素里点击click去添加文字也是失败的，是我使用方式不对吗。我是想做一个类似于toolbar的工具，不是渲染html到编辑器里面。求解。
![image](https://user-images.githubusercontent.com/17307843/201845571-722f25be-ea81-4715-a76b-c40b8a34f1ef.png)
![image](https://user-images.githubusercontent.com/17307843/201845620-fac6800c-0973-4620-82fd-384482d91c91.png)

**Comment by 204065248** [comment]
> > 第三步：在创建的dom添加click事件
> 
> 你确定这个 click 事件真的被触发了吗？

大佬帮忙看看

**Comment by wangfupeng1988** [comment]
试试这样行吗

```js
setTimeout(() => { editor.insertText('123') })
```

**Comment by wangfupeng1988** [comment]
试试这样行吗

```js
setTimeout(() => { editor.insertText('123') })
```

**Comment by 204065248** [comment]
> ```js
> setTimeout(() => { editor.insertText('123') })
> ```

![image](https://user-images.githubusercontent.com/17307843/201848266-f0d1ad61-c542-49ac-947f-e32e63ac1f53.png)
还是不行
![image](https://user-images.githubusercontent.com/17307843/201848330-4162e30c-f417-4a13-9907-1fd9e0724de2.png)

**Comment by wangfupeng1988** [comment]
那只能是提供一个在线 demo 了，用最简单的 demo 能复现问题即可

以下平台三选一即可

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/
