### ISSUE TITLE
添加附件上传报错Duplicated key 'uploadAttachment' in menu items导致页面显示不出

### ISSUE THREAD

**Issue by jiafeng1575** [wangeditor-team/wangEditor#5083]
## 问题描述

![image](https://user-images.githubusercontent.com/31758961/201885969-9fdaeae8-1be2-4aa4-b0e6-0b2d5eceb082.png)

Duplicated key 'uploadAttachment' in menu items 

## wangEditor 版本

*5.1.23*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

![image](https://user-images.githubusercontent.com/31758961/201885488-9f7be2b8-7154-4025-9599-d940534c8252.png)
![image](https://user-images.githubusercontent.com/31758961/201885764-82a8174a-8e0e-481b-a4df-4fbb39cbe985.png)

**Comment by wangfupeng1988** [comment]
给一个在线 demo 吧，复现这个问题。

以下平台三选一即可

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by Tlionsir** [comment]
关于 《Error: Duplicated key ... 》最简单的解决方案。
![image](https://github.com/wangeditor-team/wangEditor/assets/35832886/2a6590bc-082e-4951-861d-169edb20a306)
