### ISSUE TITLE
插入链接后 无法继续跟随编辑

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#5084]
## bug 描述
插入链接后 无法继续在链接后正常编辑 链接之后的文字将全部是链接标题  

## 你预期的样子是？
链接的开始和结束位置 应该不计入链接编辑标题之中

## wangEditor 版本
5.1.23

## demo 能否复现该 bug ？
能

- 步骤一 插入链接
- 步骤二 插入链接后在链接后方继续编辑

**Comment by wangfupeng1988** [comment]
这个问题之前有人提出过，目前不好判断。

连接后面输入，到底应该属于链接，还是应该属于后面的文本？—— 没有一个判断标准。

所以先不改。

**Comment by beforeBurning** [comment]
大大您好
个人愚见 觉得可以参考一下知乎  知乎是在链接的开始和结束位置不计入链接编辑 只有中间部分为链接编辑
