### ISSUE TITLE
动态插入node位置错误 

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#5085]
作者大大您好 我在使用 Transforms.insertNodes 
在文本中转换部分为链接 (二次开发了原有的插入链接功能) 在一段文字中 插入linkNode 但是我没办法插入到文字的中间 每次插入都在文字的开端部分 
看了您的源码  您直接deleteFragment删除原有数据后insertNodes(linkNode) 就实现了 
我使用了同样的方法但是并不能达到您的效果 请问我有哪些地方需要注意的?
使用 insertText插入文字是可以正确插入到想要的位置的

谢大大指点

**Comment by wangfupeng1988** [comment]
你这个 linkNode 是 inline 元素吧？（不是 block 元素）

**Comment by beforeBurning** [comment]
function genLinkNode(url: string, text?: string): LinkElement {
    const linkNode: LinkElement = {
        type: 'link',
        url: replaceSymbols(url),
        children: text ? [{ text }] : [],
    }
    return linkNode
}
大大 我的生成的方式和你源码中是一样的

**Comment by beforeBurning** [comment]
刚刚试了一下  我从Transforms.insertNodes(editor, linkNode) 替换为 editor.insertNode(linkNode) 居然就可以正常插入了 请教一下这2个插入有什么本质上的区别吗?

**Comment by wangfupeng1988** [comment]
按理说，这里没啥区别

不过没关系，能用就行
