### ISSUE TITLE
vue 从txt中复制内容粘贴会重复

### ISSUE THREAD

**Issue by Yang-KaiXin** [wangeditor-team/wangEditor#5088]
## bug 描述

*vue 从txt中复制内容粘贴会重复*

## 你预期的样子是？

*不重复*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*5*

## demo 能否复现该 bug ？

不能
配置了复制内容过滤属性customPaste
- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
我怎么复现呢？给提供一个在线 demo 吧
