### ISSUE TITLE
如何去掉这个警告：编辑区域高度 < 300px 这可能会导致 modal hoverbar 定位异常 Textarea height < 300px . This may be cause modal and hoverbar position error 

### ISSUE THREAD

**Issue by zcf19960503** [wangeditor-team/wangEditor#5091]
![image](https://user-images.githubusercontent.com/40545975/202398491-35a8b8da-373c-42e4-8f2a-ac73717f090b.png)

**Comment by wangfupeng1988** [comment]
编辑器高度 >= 300px 即可

**Comment by zfzfzzf** [comment]
如果设置了srcoll为false后，并设置了minHeight，应该怎么去掉
