### ISSUE TITLE
使用dangerouslyInsertHtml丢失原有的格式

### ISSUE THREAD

**Issue by myth984** [wangeditor-team/wangEditor#5094]
## 问题描述

使用dangerouslyInsertHtml丢失原有的格式
例如 居中/字体加粗/颜色等等等等一系列问题

## wangEditor 版本

        "@wangeditor/editor": "^5.1.22",
        "@wangeditor/editor-for-vue": "^1.0.2",

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
```javascript
const html = `<div data-bulb-node-id="5825-1655176319106" data-block-type="paragraph" class="css-1osjald" style="text-align: center;"><span data-bulb-node-id="daS1-1668739295457"><span class="bold font-size" style="font-weight: bold; font-size: 26px; padding-top: 1px; padding-bottom: 1px;">202211-黑色月度策略</span></span></div>`
this.editor.dangerouslyInsertHtml(html);
```
- 步骤二
- 步骤三

**Comment by myth984** [comment]
疑似丢失行内style

**Comment by wangfupeng1988** [comment]
不支持自定义的 style 和 class

**Comment by wenda10086** [comment]
@wangfupeng1988 请问不支持自定义style和class的话，我现添加一个自定义像素大小的文字，该怎么做呢

**Comment by wangfupeng1988** [comment]
用这种方式 

```html
<p>hello <span style="font-size: 13px;">world</span></p>
```
