### ISSUE TITLE
clipboardData.getData('text/rtf')获取不到doc文档复制过来的内容

### ISSUE THREAD

**Issue by wenda10086** [wangeditor-team/wangEditor#5095]
## 问题描述

1.我想要自定义粘贴word文档的图片，将doc文档全部复制粘贴到wangEditor时，customPaste方法的event.clipboardData.getData('text/rtf')为空
2.doc文档中存在一号字体，有没有通过自定义插件方法实现复制过去字体大小基本不变，或者说如何自定义支持其它号字体

## wangEditor 版本

5.1.23

## 是否查阅了文档 ？

是（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

- 步骤一：新建一个doc文档，在文档中输入内容和图片
- 步骤二：复制doc文档的内容，粘贴到富文本编辑器中
- 步骤三：打印event.clipboardData.getData('text/rtf')，为空

**Comment by wenda10086** [comment]
event.clipboardData.getData('text/html')是有内容的
但是我想要获取图片的内容用于上传给后台
而text/html只会获取到图片的绝对路径
我的代码参考了[https://juejin.cn/post/7144335819275255845](https://juejin.cn/post/7144335819275255845)
rtf打印为空

**Comment by wangfupeng1988** [comment]
这个 event 就是 DOM 事件原生的 event 参数，和编辑器无关的。

你可以自己搞一个可编辑的 div ，监听 paste 事件试试，能够获取  `event.clipboardData.getData('text/rtf')`

```html
<div contenteditable="true">可编辑器的 div</div>
```

**Comment by hmxxmh** [comment]
> event.clipboardData.getData('text/html')是有内容的 但是我想要获取图片的内容用于上传给后台 而text/html只会获取到图片的绝对路径 我的代码参考了https://juejin.cn/post/7144335819275255845 rtf打印为空
这个问题解决了吗，我这情况跟你一样的，也是想取word图片内容上传服务器，想知道你这边怎么解决rtf为空的情况

**Comment by hmxxmh** [comment]
@wenda10086
