### ISSUE TITLE
关于禁用编辑框的配置方法

### ISSUE THREAD

**Issue by God-Myw** [wangeditor-team/wangEditor#5099]
## 问题描述

使用\<ReactWEditor  config={{}}  />组件时从config属性源码里找不到禁用编辑框的配置属性

## wangEditor 版本

^5.1.20

## 是否查阅了文档 ？

是

## 最小成本的复现步骤

import React from 'react'
import '@wangeditor/editor/dist/css/style.css'
import ReactWEditor from 'wangeditor-for-react';
function MyEditor() {
    return (
        <>
            <div style={{ border: '1px solid #ccc', zIndex: 100, marginTop: '15px'}}>
                \<ReactWEditor
                    config={{}}
                />
            </div>
        </>
    )
}

export default MyEditor

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/v5/editor-config.html#readonly
