### ISSUE TITLE
vue2本地运行正常，线上环境报错

### ISSUE THREAD

**Issue by zhaomenglu** [wangeditor-team/wangEditor#5100]
## 问题描述

本地开发可以正常，但是打包到线上环境报错
![image](https://user-images.githubusercontent.com/39189837/203225156-6bb5a4e7-d0ea-4402-81ca-ed9c2c73bca5.png)

## wangEditor 版本

wangeditor：5.1.23
@wangeditor/editor-for-vue：1.0.2

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
vue2.0+webpack3

**Comment by wangfupeng1988** [comment]
你的想办法在本地复现，否则我们也不从下手。

**Comment by wangfupeng1988** [comment]
另外，webpack3 有一个很常见的问题 https://github.com/wangeditor-team/wangEditor/issues/4041 不知道对你是否有帮助

**Comment by zhaomenglu** [comment]
> 另外，webpack3 有一个很常见的问题 #4041 不知道对你是否有帮助

这个我添加了之后本地就可以正常运行了，但是不知道怎么打包到线上之后不就报那个错，我也很郁闷，本地都正常。。会不会是有需要配置的打包的配置吗webpack里，这个报错点进去是这种，
![image](https://user-images.githubusercontent.com/39189837/203236521-9a9f092c-8376-48af-a356-69b17ffd7425.png)

**Comment by wangfupeng1988** [comment]
按理说没关系，4 和 5 可以同时存在

**Comment by liyf7218** [comment]
我也遇到了这个问题，按照 #4041 的步骤改了一遍，没有效果
请问一下 @zhaomenglu ， “TypeError: l is not a function” 这个问题，到底解决了吗？

**Comment by xiefangqing** [comment]
相同问题，之前也是本地不能运行，然后https://github.com/wangeditor-team/wangEditor/issues/4041 解决。
但打包后报错：TypeError: l is not a function

**Comment by williambao** [comment]
@wangfupeng1988  按 #4041  加了 resolve('node_modules/@wangeditor') 后，本地正常运行。 但是npm run build打包后放到线上，不报错，而是整个编辑框是空的...
![CleanShot 2023-04-22 at 21 16 36@2x](https://user-images.githubusercontent.com/779521/233787386-3570ea3c-dc91-4122-aa9b-f5ce163f669f.png)

**Comment by TnTZard** [comment]
> @wangfupeng1988 按 #4041 加了 resolve('node_modules/@wangEditor') 后，本地正常运行。 但是npm run build打包后放到线上，不报错，而是整个编辑框是空的... ![CleanShot 2023-04-22 at 21 16 36@2x](https://user-images.githubusercontent.com/779521/233787386-3570ea3c-dc91-4122-aa9b-f5ce163f669f.png)

我遇到一样的情况，显示效果和你一样，会报 TypeError: l is not a function 这个错误，你可能build之后没有打印console日志，我们应该是一样的问题，vue2 + webpack3

**Comment by zhang0ZGC** [comment]
楼主这个问题你现在解决了嘛🤣

**Comment by wyp-serve** [comment]
我也是这个问题，找不到解决办法呀。

**Comment by CapitalYing** [comment]
我也是部署后富文本是空的但没有报错
