### ISSUE TITLE
react类式组件开发

### ISSUE THREAD

**Issue by God-Myw** [wangeditor-team/wangEditor#5101]
## 功能描述

react函数式组件开发如何转类式组件开发?

## 提炼几个功能点

可以使用react类式组件进行开发

## 原型图

原型图不做改变

## 可参考的案例

https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js

**Comment by wangfupeng1988** [comment]
参考这里 https://github.com/wangeditor-team/wangEditor-for-react/tree/main/example/pages
