### ISSUE TITLE
编辑器默认内容为<p><br /></p>

### ISSUE THREAD

**Issue by tiancaixiaobaozi** [wangeditor-team/wangEditor#5102]
## 问题描述

*编辑器默认内容为`<p><br /></p>`，我想在没输入内容的情况下，默认值为空字符串 ‘’ ; 通过setHtml、clear也无法实现*
![1](https://user-images.githubusercontent.com/22486120/203458327-7f4406b4-bad2-4c42-924e-402bb9aca52c.jpg)

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

*是*

**Comment by wangfupeng1988** [comment]
> 编辑器默认内容为`<p><br /></p>`

是的，默认就是这样。有其他需求，你可以在获取 HTML 之后自行过滤处理。
