### ISSUE TITLE
视频插入菜单无法修改

### ISSUE THREAD

**Issue by ReginYuan** [wangeditor-team/wangEditor#5103]
## 问题描述
在上传视频是只有插入链接和封面，没有自定义插入视频的菜单项，我修改了但是不生效
*请输入遇到的问题...*

## wangEditor 版本
5.1.18
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*  已阅读官方文档

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
安装并修改默认视频上传菜单项
- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/v5/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD-1 看文档
