### ISSUE TITLE
编辑图片  图片过大时，编辑框定位问题

### ISSUE THREAD

**Issue by haibaiDS** [wangeditor-team/wangEditor#5104]
## bug 描述

*当上传图片比较大时，即编辑器被铺满情况下，点击图片编辑，未出现编辑框或编辑框定位错误*

## 你预期的样子是？

*图片铺满情况下，点击图片编辑，编辑框出现在该图片上面，以图片显示区域的左侧或右侧为坐标点*

## 系统和浏览器及版本号

- 操作系统    Windows 10
- 浏览器和版本  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

## wangEditor 版本

*wangEditor 5*

## demo 能否复现该 bug ？

能，如图
![image](https://user-images.githubusercontent.com/32355157/203517509-3c8a4f6a-ee36-49ed-abca-40d7d930dd98.png)

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一   进入 https://www.wangeditor.com/demo/index.html， 默认模式
- 步骤二   上传一张大图，使其铺满或超过编辑器
- 步骤三    点击图片 编辑

**Comment by wangfupeng1988** [comment]
可以先临时用这个配置 https://www.wangeditor.com/v5/toolbar-config.html#modalappendtobody

**Comment by haibaiDS** [comment]
> 可以先临时用这个配置 https://www.wangeditor.com/v5/toolbar-config.html#modalappendtobody

好的，感谢！

**Comment by WangQingye** [comment]
> 可以先临时用这个配置 https://www.wangeditor.com/v5/toolbar-config.html#modalappendtobody

我也遇到了这个问题，用了这个配置过后，modal跑到编辑器外面去了，可能受我自己的CSS影响，后来加了个样式解决了
  .w-e-modal {
    right: 0 !important;
  }

**Comment by yzk214806293** [comment]
5版本没有这个pasteFilterStyle方法了吗 没有的话 拿什么替代
