### ISSUE TITLE
增强对图片的排版功能

### ISSUE THREAD

**Issue by sdlddr** [wangeditor-team/wangEditor#5105]
## 功能描述

*CKEditor5、TinyMce等国外富文本编辑器，早已实现在图片的浮云编辑框里提供浮动左/右对齐、居中对齐、给图片下方直接加文字注释等更丰富的排版功能，希望国产wangEditor也能加上*

## 提炼几个功能点

- 选中图片后，图片编辑浮动栏中，增加“左/右对齐”、“居中对齐”、“给图片下方直接加文字注释”的排版功能
- “左/右对齐” 相当于加上float:left/right这样的css样式，完美实现图文混排，
- “给图片下方直接加文字注释”：直接在图片下方出现注释文字输入位，所见即所得

## 原型图

*涉及到 UI 改动的功能，请一定提供原型图。原型图能表明功能即可，不要求规范和美观*
左/右对齐的排版效果、图片下方文字注释的效果如CKEditor5链接中效果所示：
[CKEditor5中的同类效果](https://ckeditor.com/ckeditor-5/demo/)

## 可参考的案例

*是否已有可参考的案例（如其他编辑器），有的话请给出链接*
[CKEditor5中的同类效果](https://ckeditor.com/ckeditor-5/demo/)

**Comment by wangfupeng1988** [comment]
暂不支持

**Comment by gooflow** [comment]
近期是否有做改造的计划？

**Comment by wangfupeng1988** [comment]
显示不难，但再结合各种编辑操作，就麻烦了。

近期没精力做。
