### ISSUE TITLE
如何具体用prism.js在展示时让代码块内容高亮

### ISSUE THREAD

**Issue by onetiaoxianfish** [wangeditor-team/wangEditor#5107]
## 问题描述

*无法做到代码块高亮，求大佬指点下*

## wangEditorV5

*不清楚如何具体去实现prism在展示内容时代码块高亮，根据网上查询的各种方法，最终并不能实现高亮的效果。
Prism.highlight（）方法再次去渲染回显的html格式，会导致内容无法再被v-html正常渲染，输出的会是<p></p>类似这样带有标签的语句*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 npm install prismjs -S
- 步骤二npm install babel-plugin-prismjs -D
- 步骤三import Prism from "prismjs";
 在钩子函数mounted中添加
 Prism.highlightAll()
(参考的此链接[https://blog.csdn.net/qq_33625873/article/details/109149091](https://blog.csdn.net/qq_33625873/article/details/109149091)),以及其他类似的

**Comment by wangfupeng1988** [comment]
https://www.wangeditor.com/demo/code-highlight.html 看这里
