### ISSUE TITLE
无法达到设置引用的排版处理

### ISSUE THREAD

**Issue by sdlddr** [wangeditor-team/wangEditor#5111]
## bug 描述

*我想把选中的多行文字（各行有不同对齐方式包含左/中/右对齐）加到一个引用容器中：选中多行后点击引用，结果是各行文字分别被包到不同的引用容器下了*

## 你预期的样子是？

*能支持将选中的多行文字加到同一个引用容器中*

## 系统和浏览器及版本号

- 操作系统 WIN11
- chrome、edge最新版本

## wangEditor 版本

*5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*官网demo上就能复现*

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 输入多行文字
- 可选：对其中几行文字做右/居中对齐
- 选中多行文字，点击“引用”按钮，发现每行文字各被包入了各自的引用容器中

**Comment by wangfupeng1988** [comment]
是的，默认这样。

你可以在 引用块 中回车换行，那样会有你想要的效果

<img width="407" alt="image" src="https://user-images.githubusercontent.com/9583120/203880081-0aaffb62-4e8a-43e0-b8fa-b0c74b6cd6e8.png">

**Comment by sdlddr** [comment]
但是，我想让引用块中，第二行变居中，第三行变右对齐。

**Comment by wangfupeng1988** [comment]
> 但是，我想让引用块中，第二行变居中，第三行变右对齐。

不支持。
