### ISSUE TITLE
全选内容后，使用QQ拼音中文输入法输入会100%报错卡死

### ISSUE THREAD

**Issue by Mec1750** [wangeditor-team/wangEditor#5112]
## bug 描述

当编辑器内有内容时，全选内容后，使用QQ拼音中文输入法输入会100%报错卡死

## 你预期的样子是？

全选后，使用QQ拼音中文输入法正常输入，不报错

## 系统和浏览器及版本号

- 操作系统
win10
- 浏览器和版本
chrome 107.0.5304.107
## wangEditor 版本
wangEditor v5

## demo 能否复现该 bug ？

能

## 在线 demo
官方文档中的demo，就能100%复现该问题：
https://codesandbox.io/s/vue2-wangeditor-demo-forked-4so7ij
https://www.wangeditor.com/demo/index.html

## 最小成本的复现步骤

情况1：当编辑器内有内容时，全选所有内容后，直接用QQ拼音中文输入法输入，会立即报错

情况2：当编辑器内没有内容时，使用鼠标选中编辑器区域，按下鼠标左键拖动超过最左边后，松开鼠标左键，然后使用QQ拼音中文输入法输入，会出现报错

**Comment by wangfupeng1988** [comment]
我这只有搜狗拼音输法，复现不了。。。
