### ISSUE TITLE
vue3无法获取getConfig

### ISSUE THREAD

**Issue by jiejie-color** [wangeditor-team/wangEditor#5115]
## bug 描述
我是第一次提建议，大佬请多多包涵
1,vue2使用的是editor作为实例对象，vue3用的是editorRef，文档并没有做出提示
![image](https://user-images.githubusercontent.com/78398040/203886559-59eeaf86-8066-4964-80ab-0c4828820d13.png)
2.我用文档建议的方法找curToolbarConfig,找不到报错，说Cannot read properties of null (reading 'getConfig')
![image](https://user-images.githubusercontent.com/78398040/203886661-dd89fe96-5753-4c70-9c55-a482eb6eb6b9.png)
3.我找到问题了
![image](https://user-images.githubusercontent.com/78398040/203889122-b2f324f6-4702-4383-884d-35b35c91bfa8.png)
zhe'yang这样写就没错了，可是文档并没有说明要用nextTick在vue3中，我觉得这对初学者来说非常不友好

1.建议官网改一下实例，提示vue3的同学用nextTick()，要不获取不到dom，还应在声明周期页面挂在完后执行，官网示例容易误导新手。

2.为什么获取工具栏的默认配置这么麻烦呢，我觉得直接在Toolbar组件暴露一个方法，父组件可以直接调用实时查看Toolbar组件内部的菜单栏这样更好

## 你预期的样子是？
可以找到curToolbarConfig 查看工具栏的默认配置。

## 系统和浏览器及版本号
mac egde浏览器

## wangEditor 版本
v5

## demo 能否复现该 bug ？
我不知道

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*
不好意思大佬，第一次提建议，不太会
- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  
![image](https://user-images.githubusercontent.com/78398040/203887549-2e5655a1-521d-4778-9db1-7e391652108d.png)
查看官网，我不知道说的对不对
- 步骤二
创建vue3项目实现一下，感谢大佬，跪谢

**Comment by wangfupeng1988** [comment]
好的，感谢反馈~
