### ISSUE TITLE
自定义粘贴在某些浏览器下无法阻止默认粘贴

### ISSUE THREAD

**Issue by feifei19870827** [wangeditor-team/wangEditor#5117]
## 问题描述
自定义粘贴方法customPaste里面event.preventDefault()在谷歌浏览器下不起作用，同样的内容会粘贴两次，火狐浏览器没有此问题。
谷歌浏览器版本号：107.0.5304.108（正式版本）（64位）
火狐浏览器版本号：106.0.5（64位）

## wangEditor 版本
4.7.11

## 是否查阅了文档 ？
查阅了官网文档以及网上说的一些可能存在的问题

## 最小成本的复现步骤
参考问题描述

**Comment by wangfupeng1988** [comment]
v4 已经不再维护了

精力有限，还请体谅~

**Comment by luo772435545** [comment]
v5一样有这样的问题
