### ISSUE TITLE
最新版本自定义上传视频按照官方配置insertFn(url,poster) 封面未插入

### ISSUE THREAD

**Issue by zzcypz** [wangeditor-team/wangEditor#5118]
## bug 描述

最新版本VUE.JS3.0 TS 自定义上传视频按照官方配置insertFn(url,poster) 封面未插入

## 你预期的样子是？

应该有视频封面，html video节点应该配置POSTER

## 系统和浏览器及版本号

- WIN11
- GOOGLE  105.0.5195.127

## wangEditor 版本

"@wangeditor/editor": "^5.1.1",
 "@wangeditor/editor-for-vue": "^5.1.12",

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤
type VideoInsertFnType = (url: string, poster: string) => void
state.editorConfig.MENU_CONF['uploadVideo'] = {
        fieldName: 'file',
        onProgress(progress: number) {
            NProgress.inc()
        },
        async customUpload(file: File, insertFn: VideoInsertFnType) {
            NProgress.configure({ showSpinner: true })
            NProgress.start()
            let fd = new FormData()
            fd.append('file', file)
            state.loading = true
            fileUpload(fd)
                .then((res) => {
                    console.log('上传视频', res.data)
                    if (res.code == 1) {
                        let poster = 'http://admin.baoxiaojia.dingsenhulian.com/uploadFile/1596051044679421952.jpg'
                        insertFn(res.data.previewUrl, poster)
                    }
                    NProgress.done()
                    state.loading = false
                })
                .catch((err) => {
                    NProgress.done()
                    state.loading = false
                })
        },
    }

**Comment by wangfupeng1988** [comment]
> "@wangeditor/editor": "^5.1.1",

升级一下最新的版本试试。
