### ISSUE TITLE
表格删除不掉

### ISSUE THREAD

**Issue by IANER88** [wangeditor-team/wangEditor#5119]
## bug 描述
表格删除不掉
*请输入内容……*

## 你预期的样子是？

*请输入内容……*
![DV7{D8EG3~G (ZRUJS7YWLE](https://user-images.githubusercontent.com/109190427/204082878-ffc767a3-e4f7-4858-9efe-6c410f788d51.png)

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
如何复现？
