### ISSUE TITLE
分割线跟文本不对齐

### ISSUE THREAD

**Issue by ntmxglrtayl03** [wangeditor-team/wangEditor#5120]
## 问题描述
分割线跟文本不对齐

*请输入遇到的问题...*
![image](https://user-images.githubusercontent.com/114506067/204092953-06194021-cfd6-478a-9916-840949a7c96f.png)
## wangEditor 版本
"@wangeditor/editor-for-vue": "^1.0.2",
*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 添加一个分割线

**Comment by wangfupeng1988** [comment]
刻意这么设置的样式

你可以执行修改、覆盖这个分割线的 CSS样式

**Comment by ntmxglrtayl03** [comment]
建议设置左右两边的padding设置为0，既保留了选中样式又能对齐（个人感觉，不对齐看起来比较别扭 😂 ） 
padding: 20px 0;
