### ISSUE TITLE
如何在nuxt.js项目中使用

### ISSUE THREAD

**Issue by hw-git** [wangeditor-team/wangEditor#5121]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
遇到什么问题了吗？

**Comment by hw-git** [comment]
不知道在nuxt项目中如何引入发自我的荣耀手机-------- 原始邮件 --------发件人： 王福朋 ***@***.***>日期： 2022年11月27日周日 13:20收件人： wangeditor-team/wangEditor ***@***.***>抄送： 胡伟 ***@***.***>, Author ***@***.***>主    题： Re: [wangeditor-team/wangEditor] 如何在nuxt.js项目中使用 (Issue #5121)

遇到什么问题了吗？

**Comment by wangfupeng1988** [comment]
跟 vue 一样的
