### ISSUE TITLE
export 'default' (imported as 't') was not found in 'vue'

### ISSUE THREAD

**Issue by wtlsky** [wangeditor-team/wangEditor#5122]
## bug 描述

![image](https://user-images.githubusercontent.com/15212547/204127547-29ffa0ae-27c4-4a71-9a3c-2d1ac5fa6f3d.png)

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

![image](https://user-images.githubusercontent.com/15212547/204127567-1f7b6007-6638-4bd2-99ce-7727308e4c02.png)

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

webpack5 + vue 3.2.13 + electron 13.0.0

**Comment by wangfupeng1988** [comment]
光 vue3 （没有 electron ） 会不会报错？
