### ISSUE TITLE
在vite项目中使用，输入的文本内容在文本框中是居中的，且光标位置和placeholder的文本位置对不上

### ISSUE THREAD

**Issue by KaZusAzzzzz** [wangeditor-team/wangEditor#5123]
## 问题描述
输入的文本内容在文本框中是居中的，且光标位置和placeholder的文本位置对不上
## wangEditor 版本
v5.x
## 是否查阅了文档 ？
是
## 最小成本的复现步骤

- 在webstorm中用vite初始化一个项目，安装Element-ui组件

- 将文档中Demo示例的代码原封不动的复制下来制作成一个组件

- 在页面中新建一个表单结构，并将这个组件插入<el-form-item ></el-form-item>标签中
![QQ截图20221127220254](https://user-images.githubusercontent.com/100470866/204139364-1056f0ae-3c37-4e83-a77b-064a41704ae3.png)
- 错误如图
![`RT{4H@JT_W0FUB73SM ~Y](https://user-images.githubusercontent.com/100470866/204139395-5f2ab688-8c9d-4807-93ea-59fb3055734c.png)

**Comment by wangfupeng1988** [comment]
> 输入的文本内容在文本框中是居中的

可自己改一下 css 样式。

**Comment by wangfupeng1988** [comment]
> 光标位置和placeholder的文本位置对不上

这是一个待优化的点，之前已经记录。

**Comment by KaZusAzzzzz** [comment]
> > 输入的文本内容在文本框中是居中的
> 
> 可自己改一下 CSS 样式。
哦，好的，我看到问题的来源了，谢谢
