### ISSUE TITLE
wangeditor 不支持在next.js中使用？

### ISSUE THREAD

**Issue by codersmoixan** [wangeditor-team/wangEditor#5124]
`
import React, { useState, useEffect } from 'react'
import { Editor, Toolbar } from '@wangeditor/editor-for-react'
import { IDomEditor, IEditorConfig, IToolbarConfig } from '@wangeditor/editor'
import '@wangeditor/editor/dist/css/style.css'

function ShareEditor() {
  const [editor, setEditor] = useState<IDomEditor | null>(null)
  const [html, setHtml] = useState('<p>hello</p>')

  // 工具栏配置
  const toolbarConfig: Partial<IToolbarConfig> = { }

  // 编辑器配置
  const editorConfig: Partial<IEditorConfig> = {
    placeholder: '请输入内容...',

  }

  useEffect(() => {
    return () => {
      if (editor === null) return
      editor.destroy()
      setEditor(null)
    }
  }, [editor])

  return (
    <>
      <div style={{ border: '1px solid #ccc', zIndex: 100}}>
        <Toolbar
          editor={editor}
          defaultConfig={toolbarConfig}
          mode="default"
          style={{ borderBottom: '1px solid #ccc' }}
        />
        <Editor
          defaultComfig={editorConfig}
          value={html}
          onCreated={setEditor}
          onChange={(editor: IDomEditor) => setHtml(editor.getHtml())}
          mode="default"
          style={{ height: '500px', overflowY: 'hidden' }}
        />
      </div>
      <div style={{ marginTop: '15px' }}>
        {html}
      </div>
    </>
  )
}

export default ShareEditor
`

<img width="462" alt="image" src="https://user-images.githubusercontent.com/57893797/204142058-cda6cc50-70e4-4c23-9b44-463043a7e994.png">

**Comment by wangfupeng1988** [comment]
@hahaaha 有没有 nextjs 的 demo ？

**Comment by hahaaha** [comment]
有的 https://github.com/hahaaha/wangeditorV5-nextjs-demo 可以参考下这个demo

**Comment by codersmoixan** [comment]
ok 谢谢
