### ISSUE TITLE
请教一下关于插入代码的问题

### ISSUE THREAD

**Issue by beforeBurning** [wangeditor-team/wangEditor#5125]
作者大大 您好 请问我应该如何二次开发插入代码功能 增加新的语言支持 我现在增加后 新的语言没办法成功渲染出来  看代码中没有渲染出class token xxx  
请教大大我应该怎么增加这个class

**Comment by wangfupeng1988** [comment]
> 增加新的语言支持

不能自己增加，需要我们统一增加 https://www.wangeditor.com/v5/menu-config.html#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE

你想增加哪个语言？

**Comment by beforeBurning** [comment]
这就比较尴尬了  我的需求想增加所有的语言

**Comment by beforeBurning** [comment]
作者大大 这个修改麻烦吗  大概修改哪儿 我现在使用的patch修改的部分代码  把/packages/code-highlight/src/menu/config.ts里面的genCodeLangs方法增加齐全 和prism.ts的import增加齐全  请问我还需要修改哪儿的代码   
我的需求需要增加的语言太多 担心耽误您太多时间  麻烦您指点一下 我自己改一下

**Comment by wangfupeng1988** [comment]
增加语言，不太好直接扩展，因为它需要引入这个语言的一些高亮模块，源码参考 https://github.com/wangeditor-team/wangEditor/blob/master/packages/code-highlight/src/vendor/prism.ts 

而且，增加语言太多，会影响编辑器打包的体积，所以默认只有常用的几种语言。

如果你想增加太多语言，那不太方便扩展。
