### ISSUE TITLE
insertNode插入的node自定义属性无效

### ISSUE THREAD

**Issue by jessietang** [wangeditor-team/wangEditor#5126]
![image](https://user-images.githubusercontent.com/17528743/204212749-14450ae2-8e2b-4044-9b48-b5e57422fbab.png)
看文档写的可以自定义属性。例如，我想使用insertNode插入视频，并给视频元素添加自定义属性id和diyAttr，代码如下：
`
const node = {
        type: "video",
        poster: "",
        src: "XXX",
        children: [{ text: "" }],
        id: "1",
        diyAttr: "test1",
      };
 this.editor.insertNode(node);
`
生成的html如下：
`
<video poster="" controls="true" width="auto" height="auto"><source src="XXX" type="video/mp4"/></video>
`
没有想要的自定义属性id或者diyAttr等。
想请教一下作者大大，是设计如此，还是我使用上有问题呢？或者请问有木有其他方法可以实现我的自定义属性需求呢？

**Comment by wangfupeng1988** [comment]
自定义属性需要参考这里 https://www.wangeditor.com/v5/development.html#%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84
