### ISSUE TITLE
如何配置上传视频的默认尺寸

### ISSUE THREAD

**Issue by ljstc123123** [wangeditor-team/wangEditor#5129]
#上传视频的默认尺寸#
上传视频显示的尺寸非常小
*wangEditor5*
*如何设置上传视频的默认尺寸*
## 是否查阅了文档 ？
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
*是*
## 最小成本的复现步骤
- 步骤一 除了上传地址其它全默认配置

**Comment by wangfupeng1988** [comment]
不支持

**Comment by ljstc123123** [comment]
那这个尺寸有什么规律吗,为什么同一个视频上传的时候高度只有30多,插入视频的时候高度有900

**Comment by ljstc123123** [comment]
找到原因了,跟封面的尺寸挂钩

**Comment by gochantao2** [comment]
可以在插入视频后手动设置尺寸
`
                       // 自定义插入视频
                        customInsert(res, insertFn) {                  // JS 语法
                            // res 即服务端的返回结果
                            var ossUrlPrefix = that.$ossUrlPrefix
                            console.log('自定义插入res==', res)
                            // 从 res 中找到 url alt href ，然后插入视频
                            insertFn(ossUrlPrefix + res.data.url, '', '')
                            // 修改插入后的视频尺寸
                            setTimeout(() => {
                                Transforms.setNodes(
                                    that.editor,
                                    { width: '300', height: 'auto' },
                                    {
                                        match: n => DomEditor.checkNodeType(n, 'video'),
                                    }
                                )
                            }, 100)
                        },
`

**Comment by gochantao2** [comment]
// 自定义插入视频
                        customInsert(res, insertFn) {                  // JS 语法
                            // res 即服务端的返回结果
                            var ossUrlPrefix = that.$ossUrlPrefix
                            console.log('自定义插入res==', res)
                            // 从 res 中找到 url alt href ，然后插入视频
                            insertFn(ossUrlPrefix + res.data.url, '', '')
                            // 修改插入后的视频尺寸
                            setTimeout(() => {
                                Transforms.setNodes(
                                    that.editor,
                                    { width: '300', height: 'auto' },
                                    {
                                        match: n => DomEditor.checkNodeType(n, 'video'),
                                    }
                                )
                            }, 100)
                        },

**Comment by gochantao2** [comment]
```javascript
                      // 自定义插入视频
                      customInsert(res, insertFn) {                  // JS 语法
                          // res 即服务端的返回结果
                          var ossUrlPrefix = that.$ossUrlPrefix
                          console.log('自定义插入res==', res)
                          // 从 res 中找到 url alt href ，然后插入视频
                          insertFn(ossUrlPrefix + res.data.url, '', '')
                          // 修改插入后的视频尺寸
                          setTimeout(() => {
                              Transforms.setNodes(
                                  that.editor,
                                  { width: '300', height: 'auto' },
                                  {
                                      match: n => DomEditor.checkNodeType(n, 'video'),
                                  }
                              )
                          }, 100)
                      },
```

**Comment by wusj975** [comment]
> ```js
>                       // 自定义插入视频
>                       customInsert(res, insertFn) {                  // JS 语法
>                           // res 即服务端的返回结果
>                           var ossUrlPrefix = that.$ossUrlPrefix
>                           console.log('自定义插入res==', res)
>                           // 从 res 中找到 url alt href ，然后插入视频
>                           insertFn(ossUrlPrefix + res.data.url, '', '')
>                           // 修改插入后的视频尺寸
>                           setTimeout(() => {
>                               Transforms.setNodes(
>                                   that.editor,
>                                   { width: '300', height: 'auto' },
>                                   {
>                                       match: n => DomEditor.checkNodeType(n, 'video'),
>                                   }
>                               )
>                           }, 100)
>                       },
> ```

 var ossUrlPrefix = that.$ossUrlPrefix 这个that在哪定义的呢？
