### ISSUE TITLE
上传图片格式

### ISSUE THREAD

**Issue by feifei19870827** [wangeditor-team/wangEditor#5130]
## 问题描述

你好，请问上传图片能上传gif格式的吗？

## wangEditor 版本

最新版

## 是否查阅了文档 ？

是

## 最小成本的复现步骤
点击上传图片，选择gif格式

**Comment by wangfupeng1988** [comment]
默认支持的，看这里 https://www.wangeditor.com/v5/menu-config.html#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE 的 `allowedFileTypes `
