### ISSUE TITLE
有的文章的图片可以复制，有的图片不能复制

### ISSUE THREAD

**Issue by itshizhan** [wangeditor-team/wangEditor#5131]
## bug 描述

大部分网站的文章中的图片都可以复制。

但是百度相关网站上的文章图片复制，都没有格式。如下述网站，复制其中的图片，格式全部丢失，且里面的图片不能复制。
https://mbd.baidu.com/newspage/data/landingsuper?context=%7B%22nid%22%3A%22news_9964699060124202745%22%7D&n_type=-1&p_from=-1

## 你预期的样子是？

可以复制图片

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

最新版本

## demo 能否复现该 bug ？

可以

**Comment by wangfupeng1988** [comment]
> 有的文章的图片可以复制，有的图片不能复制

是的，因为不同文章的 HTML 格式不一样。例如 `<div><div><img></div></div>` 就不能识别图片

**Comment by itshizhan** [comment]
这个自己可以处理吗

**Comment by wangfupeng1988** [comment]
> 这个自己可以处理吗

可以呀，https://www.wangeditor.com/v5/editor-config.html#custompaste

PS：这个工作比较麻烦。你想，如果很简单，我就直接做上了，不会故意不支持。

**Comment by Y2zz** [comment]
> > 有的文章的图片可以复制，有的图片不能复制
> 
> 是的，因为不同文章的 HTML 格式不一样。例如 `<div><div><img></div></div>` 就不能识别图片

是否可以提取`<img />`，然后输出成 `<p><img /></p>` 会更合适一些？

**Comment by 18588883583** [comment]
请求这个解决了吗

**Comment by cycleccc** [comment]
@18588883583 div套img的情况把字符串使用前先过滤一遍把img外层的div删掉。

**Comment by 18588883583** [comment]
> @18588883583 div套img的情况把字符串使用前先过滤一遍把img外层的div删掉。

不太好过滤，我是直接复制淘宝交易快照放进去。img标签外层有可能是a标签，又可能是span标签，也有可能是多层嵌套，div,span,a等等
