### ISSUE TITLE
v5版本，后端往html结构里面设置 id 或者class , 但在前端页面或者谷歌控制台的dom结构都没显示出来

### ISSUE THREAD

**Issue by yw8820** [wangeditor-team/wangEditor#5134]
## bug 描述

*请输入内容……*
<p id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">yyyyyyyyy，不可以随意自定义 html 代码（html 格式太灵活了，不会全部兼容）</p>
<p>wangEditor can only understand the HTML format from editor.getHtml() , but not all HTML formats.</p>
<p><br></p>

## 你预期的样子是？
<p id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">yyyyyyyyy，不可以随意自定义 html 代码（html 格式太灵活了，不会全部兼容）</p>
<p>wangEditor can only understand the HTML format from editor.getHtml() , but not all HTML formats.</p>
<p><br></p>

*实际内容……*
实际在控制台的dom 结构里面，没渲染出id

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
- 谷歌

## wangEditor 版本 
v5版本

*请输入内容……*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
不支持 id 和 class 属性

**Comment by dong-hx** [comment]
> 不支持 id 和 class 属性

请问要如何做能支持呢

**Comment by cycleccc** [comment]
> > 不支持 id 和 class 属性
> 
> 请问要如何做能支持呢

要使用id和class做更多的处理吗，现有版本只有粘贴进编辑器就会被转为 slate 的统一格式 ，这是 normalization 的必须路径

**Comment by dong-hx** [comment]
> > > 不支持 id 和 class 属性
> > 
> > 
> > 请问要如何做能支持呢
> 
> 要使用id和class做更多的处理吗，现有版本只有粘贴进编辑器就会被转为 slate 的统一格式 ，这是 normalization 的必须路径

是的，因为要做插入html并支持取消插入的操作，我想通过id去匹配到插入的html字符串，请问有别的实现方案吗？

**Comment by cycleccc** [comment]
> > > > 不支持 id 和 class 属性
> > > 
> > > 
> > > 请问要如何做能支持呢
> > 
> > 
> > 要使用id和class做更多的处理吗，现有版本只有粘贴进编辑器就会被转为 slate 的统一格式 ，这是 normalization 的必须路径
> 
> 是的，因为要做插入html并支持取消插入的操作，我想通过id去匹配到插入的html字符串，请问有别的实现方案吗？

取消插入？插入指的是复制粘贴这种操作吗，还是setHtml的操作
或许可以通过将插入的html改为特殊的块来实现。具体实现可以看官网有教程，[自制插件](https://www.wangeditor.com/v5/plugins.html)
