### ISSUE TITLE
图片加链接编译的链接 v-html 识别不了

### ISSUE THREAD

**Issue by about369** [wangeditor-team/wangEditor#5136]
**_图片加链接编译的链接 v-html 识别不了_**

****
## wangEditor 版本
 v5
*这是v-htnl 要编译的
```
<p>21<img src="http://business/1/2022/12/01/9c0e420221201161745147.png" alt="" data-href="www.baidu.com" style=""/></p>
```
识别不了 data-href 实现链接跳转*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
![image](https://user-images.githubusercontent.com/73218403/205002114-697e1e43-197e-4135-9aad-081e83c81861.png)

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 识别不了 data-href 实现链接跳转

自己加一个 click 事件来处理吧
