### ISSUE TITLE
移动端中间层实现，是否可以提供一些API可以直接调用一些功能，现在全在menu中，不方便原生调用

### ISSUE THREAD

**Issue by SheTieJun** [wangeditor-team/wangEditor#5137]
## 功能描述

提供移动端中间层API

## 提炼几个功能点

提供一些API用于直接调用，
setBold
setStrikeThrough
setSubscript
setSuperscript
setUnderline
setItalic.
clear？
...

## 原型图

无

## 可参考的案例

 https://github.com/SheTieJun/wangEditor-Android 
目前自己基于wangEditor有简单实现一版,如果侵权，我会私有化项目

功能实现借鉴的： https://github.com/wasabeef/richeditor-android

由于懂的前端技术只有皮毛，很多功能是很粗糙实现的，

**Comment by wangfupeng1988** [comment]
参考这里 https://www.wangeditor.com/v5/API.html

例如你说的 setBold 其实就是 `editor.addMark` ，你说的 clear 就是 `editor.clear`

**Comment by SheTieJun** [comment]
> 参考这里 https://www.wangeditor.com/v5/API.html
> 
> 例如你说的 setBold 其实就是 `editor.addMark` ，你说的 clear 就是 `editor.clear`
谢谢回复~
其实api文档我看了很多遍的，基础用法基本了解，目前而言主要是2个问题：
1. 一个方法自动反选的处理，有些处理有点困难，有些已经抄menu实现了，有些太复杂了抄不来，或者简化功能实现。
2. 这里的`clear`的我其实想问的是清除格式（橡皮檫）

**Comment by wangfupeng1988** [comment]
能通过 API 实现的，都不算复杂

真正复杂的是哪些不好实现的，例如粘贴保留/过滤 css 样式（考虑各种 HTML 结构）
