### ISSUE TITLE
上传视频超过限制大小没有任何提示也没有报错

### ISSUE THREAD

**Issue by helloJeeee** [wangeditor-team/wangEditor#5138]
## bug 描述

上传视频超过限制大小没有任何提示也没有报错

## 你预期的样子是？

能够有提示
## 系统和浏览器及版本号
edge
- 操作系统
- 浏览器和版本

## wangEditor 版本

lastest

我设置了上传视频的最大限制，超过限制了视频确实不会上传但是也没有任何提示，使用onBeforeUpload事件，获取到的file参数也没有大小可以进行判断，我希望在超过配置的视频大小及数量时，能够有一个提示信息。

**Comment by wangfupeng1988** [comment]
> 使用onBeforeUpload事件，获取到的file参数也没有大小可以进行判断

打印一下 `file.size` ，是多少？

**Comment by helloJeeee** [comment]
> > 使用onBeforeUpload事件，获取到的file参数也没有大小可以进行判断
> 
> 打印一下 `file.size` ，是多少？

![image](https://user-images.githubusercontent.com/108055048/205204819-4085701e-13f0-4896-8367-5b1832b60388.png)
file对象没有size这个属性

**Comment by wangfupeng1988** [comment]
注意看这个数据格式

<img width="427" alt="image" src="https://user-images.githubusercontent.com/9583120/205223409-0c15ef05-f44c-4528-8844-fab10ca4b96d.png">

**Comment by helloJeeee** [comment]
> 注意看这个数据格式。如下图
> 
> <img alt="image" width="427" src="https://user-images.githubusercontent.com/9583120/205223409-0c15ef05-f44c-4528-8844-fab10ca4b96d.png">

不好意思~我还是无法理解你的意思，我截图中打印的就是onBeforeUpload(file)中的这个file参数，里面是没有相关的信息

**Comment by Germxu** [comment]
很明显你打印的并不是File, 而且你使用的是v5版本吗, v4版本的视频 size 是有个 bug 的, 你需要限制100M的话并不是 100\*1024\*1024而是 100*1024, 不过v4 版本并没有onBeforeUpload
![20230307225133](https://i.imgur.com/C6aGmEm.png)
@wangfupeng1988 这是4.7.15源码里的视频校验, 相比图片代码少除了个1024导致的 size 限制 bug
