### ISSUE TITLE
4版本升级5遇到的困惑

### ISSUE THREAD

**Issue by lydat** [wangeditor-team/wangEditor#5140]
## 问题描述

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

看不明白4版本中的这些元素，分别对应5版本当中的哪些参数获取（没有专门升级文档）

编辑区域 DOM 节点 **editor.$textElem.elems[0]** ，元素 id editor.textElemId

菜单栏 DOM 节点 **editor.$toolbarElem.elems[0]** ，元素 id editor.toolbarElemId

**Comment by wangfupeng1988** [comment]
你获取这两个 DOM 节点要干嘛？
