### ISSUE TITLE
关于目录锚点问题

### ISSUE THREAD

**Issue by NicolasDevil** [wangeditor-team/wangEditor#5142]
## 问题描述

根据示例中catalog得描述，我做出了如下业务

```
const { SlateNode } = require('@wangeditor/editor')
const headers = this.editor.getElemsByTypePrefix('header')
const HEADERS = headers.map(header => {
          const text = SlateNode.string(header)
          const { id, type } = header
          return { lableId: id, lableHeader: type, lableContext: text }
})
```
运行以上代码我得到了如下结构数组
![image](https://user-images.githubusercontent.com/52849338/205271195-742335cc-7d33-4eb1-9b78-71a89bb57396.png)

使用`editor.getHtml()`方法得到得数据中h1-h6标签是没有id得，请问作者如何使`editor.getHtml()`中得h标签得id和`HEADER()`方法中的ID对应，我需要实现目录锚点功能

我已查阅相关[issue](https://github.com/wangeditor-team/wangEditor/issues/4526)中关于此类问题得描述，作者可能认为楼主得目的是自定义header标签ID，所以给出的解决方案为：
```
Boot.registerElemToHtml({
        type: 'header2',
        elemToHtml: (slateElem, childrenHtml) => HEADERS(slateElem, childrenHtml, 2)
})
```

使用这种方案是可以对`editor.getHtml()`中h标签添加自定义的id，但是和`editor.getElemsByTypePrefix('header')`方案得到的id不一致，请问编辑器有针对此种需求的方案吗

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

*是*

**Comment by wangfupeng1988** [comment]
> this.editor.getElemsByTypePrefix('header')

这个只是在编辑器中使用目录和锚点，不是显示 HTML 时

**Comment by wangfupeng1988** [comment]
如果要在显示 HTML 时使用锚点，你需要根据获取的 HTML 自己得到所有 header ，然后再做锚点

**Comment by NicolasDevil** [comment]
> 如果要在显示 HTML 时使用锚点，你需要根据获取的 HTML 自己得到所有 header ，然后再做锚点

建议`editor.getHtml()`输出带有id的h标签，要不然还得逐字分析生成目录JSON，这对目录需求十分繁琐，特别是服务端渲染时
