### ISSUE TITLE
safair浏览器兼容插入图片指定位置

### ISSUE THREAD

**Issue by jiejie-color** [wangeditor-team/wangEditor#5143]
## bug 描述

safari浏览器在插入图片的时候不能插入指定光标位置，edge浏览器可以
![image](https://user-images.githubusercontent.com/78398040/205421069-45ef7176-3e5e-41aa-83be-50f7fb6c4cdb.png)

## 你预期的样子是？
safari浏览器在插入图片的时候能插入指定光标位置，框架可以兼容safari

## 系统和浏览器及版本号
safari浏览器

- 操作系统
- mac
- 浏览器和版本
版本15.6.1 (17613.3.9.1.16)
## wangEditor 版本
  "@wangeditor/editor": "^5.0.1",
*请输入内容……*

**Comment by wangfupeng1988** [comment]
> "@wangeditor/editor": "^5.0.1",

升级到最新版本试试，看可以吗

**Comment by jiejie-color** [comment]
不行额，作者打打有试过吗，有什么比较好的方法吗

**Comment by jiejie-color** [comment]
> 

还是不行啊

**Comment by wangfupeng1988** [comment]
使用官网 demo ，输入一段文字，然后把光标放在红色箭头的位置（如下图）

在 safari 控制台执行如下代码，即可实现

```js
editor.insertText('xxx')
editor.insertNode({type: 'image', src: 'xxx.png', children: [{text: ''}]})
```

<img width="619" alt="image" src="https://user-images.githubusercontent.com/9583120/205781726-d2038c4b-3c4a-4da3-8b38-48c9c4d8da3d.png">

**Comment by jiejie-color** [comment]
> ```js
> editor.insertText('xxx')
> editor.insertNode({type: 'image', src: 'xxx.png', children: [{text: ''}]})
> ```
你这个是不是vue3 版本的吧我是用的是vue3  好像  editorRef.value.insertText("xxx"); 这都不太好使，insertText这个api好像没用

**Comment by jiejie-color** [comment]
> 

我在项目试了一下，在控制台操控editor对象是管用的 ，可是在项目里
![Uploading image.png…]()
这样就不管用了

**Comment by jiejie-color** [comment]
这是egde
![image](https://user-images.githubusercontent.com/78398040/205795992-8957e3ee-0fbd-4319-854d-04397a8813f3.png)
safair 自动跑到了
![image](https://user-images.githubusercontent.com/78398040/205796189-f8e3fd29-bc20-438d-ac92-1a06556fb54a.png)
 最前面

**Comment by jiejie-color** [comment]
我明白了，他这个光标需要在safair浏览器手动控制聚焦和失焦，现在我的问题已经解决了

**Comment by wangfupeng1988** [comment]
> 手动控制聚焦

可以使用 `editor.restoreSelection()` https://www.wangeditor.com/v5/API.html#restoreselection
