### ISSUE TITLE
在上传图片的onError以及onBefore中如果获取状态呢？然后根据状态反馈出是由于图片尺寸太大或图片上传超时造成的问题呢？

### ISSUE THREAD

**Issue by baimansong** [wangeditor-team/wangEditor#5146]
## 问题描述

*在上传图片的onError以及onBefore中如果获取状态呢？然后根据状态反馈出是由于图片尺寸太大或图片上传超时造成的问题呢？*

## wangEditor 版本

*在上传图片的onError以及onBefore中如果获取状态呢？然后根据状态反馈出是由于图片尺寸太大或图片上传超时造成的问题呢？*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
没懂，获取什么状态？可以举例说明

**Comment by baimansong** [comment]
我用的自定义上传图片，需求搞定了！！谢谢
&nbsp;


猴子请来的救兵
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 上午8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangeditor-team/wangEditor] 在上传图片的onError以及onBefore中如果获取状态呢？然后根据状态反馈出是由于图片尺寸太大或图片上传超时造成的问题呢？ (Issue #5146)





 
没懂，获取什么状态？可以举例说明
