### ISSUE TITLE
v3升级到v5兼容性问题

### ISSUE THREAD

**Issue by bfclouds** [wangeditor-team/wangEditor#5150]
## 问题描述

*现在线上使用的是3版本；是否能够升级到5版本，且保证能够编辑之前v3版本的html数据&保证样式一致*

## wangEditor 版本

*v3升级到v5*

## 是否查阅了文档 ？
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤
*无*

**Comment by wangfupeng1988** [comment]
v5 不能支持所有的 HTML 格式和属性，而 v3 不限制 HTML 格式和属性。

而也正是因为 v3 不限制，所以才有很多 bug 。两者需要权衡

建议你看看当前遗留的所有 issues ，然后再决定是否升级。
