### ISSUE TITLE
设置文本字体大小设置生效  但数据回填的时候  字体大小样式被清空了  其他样式还是存在

### ISSUE THREAD

**Issue by 313392073** [wangeditor-team/wangEditor#5152]
![image](https://user-images.githubusercontent.com/26107293/205785779-d60d0cbd-834e-425b-9f6a-6a4ebbfb65e6.png)

**Comment by 313392073** [comment]
麻烦王大佬 看看

**Comment by wangfupeng1988** [comment]
把 `\"` 转译为 `"`试试
