### ISSUE TITLE
是否能够类似插入部分自定义元素不走 history（undo redo）

### ISSUE THREAD

**Issue by loringray** [wangeditor-team/wangEditor#5157]
## 问题描述

*是否能够类似插入部分自定义元素不走 history（undo redo）*

目前看 wangEditor 文档里边好像没提及。
看 Slate 文档里边有个 HistoryEditor...

看 Slate-History 里面 HistoryEditor 的withoutSaving 和 withoutMerging 是否可行额

应用场景：
1. 插入图片/视频封面图，但是 undo/redo 的时候不走该部分逻辑。
2. 类似插入一些自定义元素或特殊操作等等。

## wangEditor 版本

*5.1.23*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
暂不支持

**Comment by senola** [comment]
> 暂不支持

有支持计划吗？也遇到这个问题？
