### ISSUE TITLE
无法解析html

### ISSUE THREAD

**Issue by YaoXiangMei** [wangeditor-team/wangEditor#5159]
## bug 描述

const content1 = `<div><img style="max-width:100%; height:auto;max-width: 100%; height: auto;" src="https://qn.myas.maissy.net/1670384065451/u=2763645735,2016465681&fm=193&f=GIF.jpg" width="1080" height="auto" /></div>`

const content2 = `<img style="max-width:100%; height:auto;max-width: 100%; height: auto;" src="https://qn.myas.maissy.net/1670384065451/u=2763645735,2016465681&fm=193&f=GIF.jpg" width="1080" height="auto" />`

**使用变量content1设置默认值或者使用dangerouslyInsertHtml这个api来设置时无效果，使用变量content2 则是正确的**
## 你预期的样子是？

能正确渲染图片

## wangEditor 版本

"@wangeditor/editor": "^5.1.23"
 "@wangeditor/editor-for-vue": "^5.1.12"

## demo 能否复现该 bug ？

能

## 在线 demo

https://codesandbox.io/s/stupefied-germain-m97i8b?file=/src/App.vue:510-519

**Comment by zhang-wanli** [comment]
遇到了同样的问题，似乎去掉外边的div就可以读出来，加上之后图片就消失了

**Comment by wangfupeng1988** [comment]
官网 demo 是可以的，如下图

<img width="1786" alt="image" src="https://user-images.githubusercontent.com/9583120/206410683-f77eebaa-e7d6-4dbf-b117-4e6156777db8.png">

**Comment by YaoXiangMei** [comment]
我把官网的html扒拉下来本地试了，使用 dangerouslyInsertHtml插入是没有问题，E.createEditor({html: content1})创建时传入就有问题 @wangfupeng1988

**Comment by wangfupeng1988** [comment]
`E.createEditor({html: content1})` 只能识别 wangEditor 输出的 HTML 格式（wangEditor 不会输出 `<div>`）

**Comment by YaoXiangMei** [comment]
content1的外层div缓存span标签，dangerouslyInsertHtml也识别不了...

**Comment by wangfupeng1988** [comment]
是的。dangerouslyInsertHtml 无法识别所有 HTML 格式，因为不可枚举。

可以 div 套 span ，再套 span ，再套 100 个 span —— 这咋识别
