### ISSUE TITLE
使用富文本组件回显内容时，会自动加上表格样式的边框

### ISSUE THREAD

**Issue by xuyigong** [wangeditor-team/wangEditor#5161]
## bug 描述

*通过该富文本组件保存的内容再通过该组件回显时，如果第一次打开的是不包含表格元素的内容时是正常的，但是只要一打开过有包含表格内容时，再打开不包含表格元素的时候就会在最外层自动加上了表格边框的样式，而且再多次打开包含表格元素的内容时，会多次添加*

## 你预期的样子是？

*与之前保存的样式一致才行*

## 系统和浏览器及版本号

- 操作系统 win10 专业版
- 浏览器和版本 Microsoft edge 107.0.1418.62 (正式版本) (64 位)

## wangEditor 版本

*5.1.23*

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
> 再打开
> 再多次打开

你说的“打开”是什么意思？是 setHtml 吗？

**Comment by xuyigong** [comment]
组件已经被创建后，多次setHtml()的原因造成的，每次回显内容时，重新创建富文本组件就能解决

**Comment by changzhengithub** [comment]
我也出现同样问题，使用富文本回显，表格外面会自带一层边框。
![image](https://user-images.githubusercontent.com/35087343/208246994-8b5a0197-6751-4a86-b7f5-8d981b7affc4.png)

**Comment by gushenyi123** [comment]
各位后面是怎么解决的？我也遇见这个问题了

**Comment by gushenyi123** [comment]
> 组件已经被创建后，多次setHtml()的原因造成的，每次回显内容时，重新创建富文本组件就能解决

大佬，你解决了么？我也遇见这个问题了

**Comment by lg-git-a** [comment]
我真是服了，处理没处理，有没有办法，问题就关闭了？
