### ISSUE TITLE
dangerouslyInsertHtml使用时，添加title属性不生效

### ISSUE THREAD

**Issue by wuyuyuqiu** [wangeditor-team/wangEditor#5162]
## 问题描述

*请输入遇到的问题...*
给富文本制作插入注释功能时，使用dangerouslyInsertHtml添加span标签，同时添加title属性不生效

## wangEditor 版本
5.1.22
*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by wangfupeng1988** [comment]
不支持自定义 HTML 属性
