### ISSUE TITLE
官网demo问题--插入的表格在光标的下一行，未能与光标所在行对齐

### ISSUE THREAD

**Issue by guichun68** [wangeditor-team/wangEditor#5164]
## bug 描述

试用demo时发现 使用工具栏中的插入表格按钮插入任意n行n列表格时，表格起始位置插入在了光标所在行的下一行了，而非光标所在行。
但是同样的demo，在官网（https://www.wangeditor.com/demo/index.html）是会显示在首行的（简洁模式），是没问题的。
将代码拷贝到本地react环境运行，也有同样的问题。

## 你预期的样子是？
表格插入到光标所在行。

## 系统和浏览器及版本号
win10 chrome 

- 操作系统： win10
- 浏览器和版本  chrome 105.0.5195.127

## wangEditor 版本 
 5.0.1

## demo 能否复现该 bug ？

能

- 中文 demo https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js

## 在线 demo

https://codesandbox.io/s/react-wangeditor-demo-unvron?file=/src/components/MyEditor.js

## 最小成本的复现步骤

- 步骤一  打开sandbox网址，待页面加载完毕后，光标放入首行，点击插入表格按钮（随意n行n列）
- 步骤二 发现插入的表格起始位置不在首行

**Comment by guichun68** [comment]
同样的代码，我本地运行也是同样的问题（跟sandbox里一样）

**Comment by wangfupeng1988** [comment]
升级最新版本试试吧，官网 demo 可以插入到首行（如果首行是空段落）

当然，如果首行有内容，那就无法继续插入表格，只能插入到第二行。
