### ISSUE TITLE
在vitepress中引入@wangeditor/editor-for-vue编译报错Element is not defined

### ISSUE THREAD

**Issue by tomiaa12** [wangeditor-team/wangEditor#5172]
## 问题描述

*在vitepress中引入@wangeditor/editor-for-vue编译报错Element is not defined，在config设置了ssr.noExternal为`[
        "@wangeditor/editor-for-vue",
        "@wangeditor/editor/dist/css/style.css",
      ]`还是没用，组件也用了`<ClientOnly>`包裹也没用*

## wangEditor 版本

*"@wangeditor/editor-for-vue": "^5.1.12"*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 引入 @wangeditor/editor-for-vue 或者组件依赖了 @wangeditor/editor-for-vue
- npm run build

**Comment by haiting** [comment]
> ## 问题描述
> _在vitepress中引入@wangeditor/editor-for-vue编译报错Element is not defined，在config设置了ssr.noExternal为`[ "@wangeditor/editor-for-vue", "@wangeditor/editor/dist/css/style.css", ]`还是没用，组件也用了`<ClientOnly>`包裹也没用_
> 
> ## wangEditor 版本
> _"@wangeditor/editor-for-vue": "^5.1.12"_
> 
> ## 是否查阅了文档 ？
> （文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
> 
> _是_
> 
> ## 最小成本的复现步骤
> （请告诉我们，如何**最快的**复现该问题？）
> 
> * 引入 @wangeditor/editor-for-vue 或者组件依赖了 @wangeditor/editor-for-vue
> * npm run build

遇到同样的问题。。。。

**Comment by haiting** [comment]
我用了一个比较傻的办法，就是把用到editor插件的代码（组件），直接搬到docs下，docs直接引用

**Comment by fanzihui** [comment]
在使用 nuxt3 中遇到了同样的问题, 
![image](https://user-images.githubusercontent.com/8360311/210958516-814567c3-5f23-46ce-9223-2751206febc1.png)

**Comment by ushier** [comment]
+1 nuxt3中同样这个问题

**Comment by fanzihui** [comment]
> +1 nuxt3中同样这个问题

可以使用 ClientOnly 解决

**Comment by yangdong520** [comment]
> 并不能解决呢

**Comment by yangdong520** [comment]
ClientOnly 试了下，并没有解决

**Comment by xkloveme** [comment]
```
import { Boot } from '@wangeditor/editor'
onMounted(() => {
  nextTick(() => {
    Boot.registerMenu(menuConf)
    Boot.registerMenu(FormatPaintMenuConf)
    Boot.registerPlugin(withSelect)
  })
})``` Boot 需要放在nextTick里

**Comment by pocketChao** [comment]
> ## 问题描述
> _在vitepress中引入@wangeditor/editor-for-vue编译报错Element is not defined，在config设置了ssr.noExternal为`[ "@wangeditor/editor-for-vue", "@wangeditor/editor/dist/css/style.css", ]`还是没用，组件也用了`<ClientOnly>`包裹也没用_
> 
> ## wangEditor 版本
> _"@wangeditor/editor-for-vue": "^5.1.12"_
> 
> ## 是否查阅了文档 ？
> （文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）
> 
> _是_
> 
> ## 最小成本的复现步骤
> （请告诉我们，如何**最快的**复现该问题？）
> 
> * 引入 @wangeditor/editor-for-vue 或者组件依赖了 @wangeditor/editor-for-vue
> * npm run build

麻烦问下解决了么  nuxt3 遇到了同样的问题

**Comment by lily1115** [comment]
在wangeditor组件里面 比如RichEditor.vue 文件名 改为RichEditor.client.vue 就行了 nuxt3文档上面有写 第三方组件 不想服务端渲染可以这样加

**Comment by wspromise** [comment]
解决了吗
