### ISSUE TITLE
关于二次开发

### ISSUE THREAD

**Issue by beforeburning** [wangeditor-team/wangEditor#5173]
请教一下作者 我在fork项目后如何二次开发比较合适? 我想修改basic-modules内相关的代码 我修改后如何打包使用?

**Comment by wangfupeng1988** [comment]
可以参考这些文档 https://github.com/wangeditor-team/wangEditor/tree/master/docs

**Comment by wangfupeng1988** [comment]
> fork项目后如何二次开发比较合适

你都 fork 项目了，那 fork 之后就是你自己的项目，你可以随意修改，都行。
