### ISSUE TITLE
插入自定义Void元素后无法继续输入英文，中文输入后并入到自定义的元素里

### ISSUE THREAD

**Issue by w1922616586** [wangeditor-team/wangEditor#5182]
## 问题描述

*插入自定义Void元素后无法继续输入英文，中文输入后并入到自定义的元素里.*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 解压附件  附件中已包含node_modules   在目录下执行 gulp demoServe
- 步骤二 ./freemarker/index.js 为注册新元素代码
- 步骤三 ./freemarker/index.html 为创建编辑器代码
[demoedit.zip](https://github.com/wangeditor-team/wangEditor/files/10235570/demoedit.zip)

**Comment by w1922616586** [comment]
期望帮忙看看  谢谢 Thanks♪(･ω･)ﾉ

**Comment by w1922616586** [comment]
参考插入附件代码后发现在renderAttachment中加入marginLeft与marginRight后可正常输入

**Comment by w1922616586** [comment]
添加padding也可以

**Comment by woaixiaobo** [comment]
还是不行
