### ISSUE TITLE
参考line-height 自定义字间距扩展遇到问题  

### ISSUE THREAD

**Issue by meicy** [wangeditor-team/wangEditor#5210]
## 问题描述
可以正常注册，筛选出字间距，但是发现没有效果，
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现
在不同项目里面表现不同，
![temp](https://user-images.githubusercontent.com/8372901/209940269-5b5e375f-e88c-4751-9251-1f1b16fb18b9.png)

在低版本项目里面报错
![209928956-41d8a27d-5a0d-4837-a751-60767b769da2](https://user-images.githubusercontent.com/8372901/209940299-b574a8e6-aa39-4c07-9a9b-b6dfca162487.png)

**Comment by meicy** [comment]
Boot.registerMenu(letterSpaceing) 通过这种方式注册接口没有效果，希望被指导

**Comment by meicy** [comment]
已经解决,但是碰到另外一个问题，在
`"react": "^18.0.2",
    "react-app-polyfill": "^3.0.0",
    "react-app-rewired": "^2.2.1",
    "react-dev-utils": "^12.0.0",
    "react-dom": "^18.0.2",
"@wangeditor/core": "1.1.11",
    "@wangeditor/editor": "^5.1.14",
    "@wangeditor/editor-for-react": "^1.0.4",
"dom7": "^4.0.4",
`
这个版本下面跑的时候我整个都是正常的，组件也正常可以设置字间距

但是我在项目中

`
"react": "^16.12.0",
    "react-dom": "^16.12.0"
"@wangeditor/editor": "^5.1.14",
    "@wangeditor/editor-for-react": "^1.0.4",
    "@wangeditor/core": "1.1.11",
"dom7": "^4.0.4"
`
这个版本里面跑的时候
// import { letterSpacingMenuConf } from './letterSpacing/menu'
// import letterSpacing from './letterSpacing'
// Boot.registerMenu(letterSpacingMenuConf)  这个可以正常显示 
// Boot.registerPlugin(letterSpacing) //报错

**Comment by meicy** [comment]
这个应该是wangeditor 与低版本的系统的兼容问题，包括react-dom/client 没有等问题

**Comment by eliaszon** [comment]
哥你怎么拓展的，能贴代码参考吗~我这拓展遇到问题一直没解决成功
