### ISSUE TITLE
直接复制线上vue3的demo代码报文件代码没有暴露出来

### ISSUE THREAD

**Issue by miss-tree** [wangeditor-team/wangEditor#5214]
## bug 描述
![1672646024039](https://user-images.githubusercontent.com/45055914/210205697-94b6cb5f-3fbe-4641-9853-b05098150f99.jpg)
![1672646080390](https://user-images.githubusercontent.com/45055914/210205780-fe51ce51-8584-46bb-8337-032053363f2b.jpg)

## 你预期的样子是？
正常执行代码

## wangEditor 版本
v5.1.23

**Comment by yj-liuzepeng** [comment]
是不是没有安装 yarn add @wangeditor/editor-for-vue@next
或者删了依赖重新装下试

**Comment by miss-tree** [comment]
之前删掉重装还是不是

后来测试用你的 
yarn add @wangeditor/editor-for-vue@next- 或者npm install @wangeditor/editor-for-vue@next --save
方法是可以的没问题
估计是vue3和vite结合使用的问题

**Comment by miss-tree** [comment]
已解决
