### ISSUE TITLE
vue3中初始化成功，但是无法输入

### ISSUE THREAD

**Issue by QuietHear** [wangeditor-team/wangEditor#5232]
## bug 描述

vue3中初始化成功，但是无法输入

## 你预期的样子是？

正常输入

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 chrome103.0.5060.66

## wangEditor 版本

    "@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-vue": "^5.1.12",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

![image](https://user-images.githubusercontent.com/26731808/211967339-77e05c3e-52d6-4fa3-9d5e-8348174c0500.png)

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 跳转到该表单路由，出现当前错误，且无光标
![image](https://user-images.githubusercontent.com/26731808/211967339-77e05c3e-52d6-4fa3-9d5e-8348174c0500.png)
- 刷新当前页面，恢复正常输入

**Comment by leekinm** [comment]
这个问题得到解决了吗？我遇到的问题是，用的[官网vue3在线demo](https://www.wangeditor.com/v5/for-frame.html#vue3)，初始化没有报错，但是富文本界面没有展示。

![image](https://user-images.githubusercontent.com/32029251/218969945-468ba871-02cc-4034-83a1-c1d8c7be892c.png)
