### ISSUE TITLE
insertText api失效

### ISSUE THREAD

**Issue by codercqw** [wangeditor-team/wangEditor#5235]
## 问题描述
insertText api失效
*请输入遇到的问题...*
使用insertText不生效 （setHtml功能是正常的）
## wangEditor 版本
"@wangeditor/editor": "^5.1.23",
"@wangeditor/editor-for-vue": "^1.0.2",
## 是否查阅了文档 ？
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一 
![image](https://user-images.githubusercontent.com/42881193/212062805-d8b08a67-4cb4-45ed-ae62-932373ddae92.png)

- 步骤二
![image](https://user-images.githubusercontent.com/42881193/212062863-94c4ad5d-8f3e-4faa-9777-aea54941ef4d.png)

- 步骤三
![image](https://user-images.githubusercontent.com/42881193/212062911-7d0be1cd-e8a5-4473-a798-f2cd1a4946af.png)

- 步骤四
![image](https://user-images.githubusercontent.com/42881193/212063077-e5d38774-a183-4eb0-95dc-5ec83cdcd6fb.png)

**Comment by codercqw** [comment]
已解决 先调用一下聚焦的api就好了

**Comment by codercqw** [comment]
已解决

**Comment by aogg** [comment]
不对，没有聚焦为什么就不可以写入了，这是bug
