### ISSUE TITLE
wangEditor5 emoji 太过古老

### ISSUE THREAD

**Issue by mingmingzhao1204** [wangeditor-team/wangEditor#5248]
## 问题描述
wangEditor5 emoji 太过古老，请问支持使用图片方式吗？和 wangEditor4 一样

## wangEditor 版本

wangEditor5

## 是否查阅了文档 ？
是

**Comment by wangfupeng1988** [comment]
暂不支持。

可以自定义扩展菜单 https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E6%96%B0%E8%8F%9C%E5%8D%95

**Comment by mingmingzhao1204** [comment]
好的
