### ISSUE TITLE
光标丢失，且无法输入，官网DEMO必现

### ISSUE THREAD

**Issue by w3cways** [wangeditor-team/wangEditor#5257]
## bug 描述

插入图片+中文文字，选中中文文字后再输入中文，按ESC取消输入后，编辑器就出问题了

## 你预期的样子是？

按照上述步骤后能正常输入

## 系统和浏览器及版本号

- 操作系统：WINDOW10
- 浏览器和版本：Chrome 版本 109.0.5414.75（正式版本） （64 位）

## wangEditor 版本

官网DEMO

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一：插入图片+中文文字
- 步骤二：选中中文文字后再输入中文

- 步骤三：按ESC取消输入后，再次输入文字

附视频
https://user-images.githubusercontent.com/6859510/215728172-98bea1a9-ed4a-4671-a1c0-fe8a85aa8cd5.mp4

**Comment by townechow** [comment]
光标聚焦在了图片上下不来，需要更改行属性之后才能重新获得光标，比如设为列表🤣🤣

**Comment by w3cways** [comment]
@wangfupeng1988 这个问题会安排人解决不，一旦出现这个问题，编辑器就用不了啊

**Comment by mr-wiggless** [comment]
@w3cways 麻烦问下，最后怎么解决的？

**Comment by w3cways** [comment]
> @w3cways 麻烦问下，最后怎么解决的？

fork后二开了（可以看我主页），只保留basic-modules、core、editor，如果只在浏览器下用没问题；如果electron下使用的话，搜狗输入法会有问题（需要联系搜狗官方把你打包的应用名添加到搜狗输入法的白名单）
