### ISSUE TITLE
问题确认：官方网站中，关于wangEditor5是否支持IE浏览器不太明确，请确认！

### ISSUE THREAD

**Issue by yonguoli** [wangeditor-team/wangEditor#5261]
## 问题描述

我想在ruoyi-vue项目中使用wangEditor，但由于客户需要使用IE浏览器，结合官方信息，有写”不支持IE“，有写”支持IE10+“，因此我想通过官方确认一下到底支持到IE几？

## wangEditor 版本

wangEditor5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

无需复现，只是感觉官方文档描述不说，需要确认

**Comment by e-x-p** [comment]
不支持IE，源码上有给提示

**Comment by yonguoli** [comment]
好的，明确了。谢谢解答！
