### ISSUE TITLE
找不到模块“@wangeditor/editor-for-vue”或其相应的类型声明

### ISSUE THREAD

**Issue by yexiaodong** [wangeditor-team/wangEditor#5352]
## bug 描述

vue3 + typescript时，引入提示：找不到模块“@wangeditor/editor-for-vue”或其相应的类型声明

代码：
import { Editor, Toolbar } from '@wangeditor/editor-for-vue'

## 你预期的样子是？

无错误警告

## 系统和浏览器及版本号

- win10
- chrome 111

## wangEditor 版本

"@wangeditor/editor": "^5.1.22",
"@wangeditor/editor-for-vue": "^5.1.12",

**Comment by yexiaodong** [comment]
已解决：https://www.wangeditor.com/v5/for-ts.html

**Comment by MasayumeKTYA** [comment]
![image](https://github.com/wangeditor-team/wangEditor/assets/108180290/9f502a66-3472-4563-979a-e8bb5c239f23)
依然报该错误

**Comment by MasayumeKTYA** [comment]
![image](https://github.com/wangeditor-team/wangEditor/assets/108180290/bf8b372b-be6a-4c32-b3cb-03615e62ce06)

依然报该错误

**Comment by MasayumeKTYA** [comment]
搜了一下 已解决 ts版本问题
![image](https://github.com/wangeditor-team/wangEditor/assets/108180290/4ff93a8a-ee5f-432a-821d-85569db89eb9)
5的b版本需要在tsconfig.json内修改
![image](https://github.com/wangeditor-team/wangEditor/assets/108180290/9329ed41-a674-4940-8edf-da8c2de8a53d)
 "moduleResolution": "node",

**Comment by herozzm** [comment]
依然不行

**Comment by Azzellz** [comment]
我也是这样...

**Comment by yunposui** [comment]
"paths": {"@wangeditor/editor-for-vue": [ "node_modules/@wangeditor/editor-for-vue/dist/src/index.d.ts"]}
这个暂时解决标红问题
