### ISSUE TITLE
打包发布的时间提示Element报错，刷新也报错

### ISSUE THREAD

**Issue by gaoseng** [wangeditor-team/wangEditor#5369]
## 发布或者刷新的时候提示element undefined
ReferenceError: Element is not defined
node_modules/@wangeditor/editor/dist/index.js:23656:8723

## 最小成本的复现步骤

- 刷新页面
- 使用react next部署

**Comment by mengliuliu** [comment]
你好，解决了吗，我也遇到了这个问题

**Comment by weijunext** [comment]
next要引入next/dynamic，配置{ ssr: false}，参考DEMO：https://github.com/hahaaha/wangeditorV5-nextjs-demo
