### ISSUE TITLE
使用wangeditor5时，报错 Unable to find a host window element for this editor

### ISSUE THREAD

**Issue by yeershao** [wangeditor-team/wangEditor#5384]
## bug 描述

使用wangeditor时，点击编辑页面，弹出富文本编辑器，但是会报错Unable to find a host window element for this editor，导致回显的内容为空。
这是报错信息。
![88fced988f3095b38e51cd6cabd296d](https://user-images.githubusercontent.com/31960271/228419247-89e83314-cbad-459b-af88-134ca2d62872.jpg)

很奇怪的是，在本地开发不会出现这个问题，在开发环境会出现这个错误

## 你预期的样子是？

希望能够正常使用，报错信息没有。知道怎么解决这个问题以及原因

## 系统和浏览器及版本号

- 操作系统 : windows 10
- 浏览器和版本: chrome, 108.0.5359.125

## wangEditor 版本

*@wangeditor/editor:5.1.23  @wangeditor/editor-for-react:1.0.6*

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

## 最小成本的复现步骤

开发完成后，上线了就可以。

**Comment by LCTcode** [comment]
同样碰到这个问题，我的解决方法是在回显的内容外面包裹一个 div 元素。就可以回显了，但是样式和图片，链接等回显的时候没有出现。

**Comment by yeershao** [comment]
> 

我也在外面包裹了一层div，但是没有解决。我发现是我在setHtml的时候，如果html的初始值是空字符串，编辑器就会报错。所以我暂时的解决方法是在useLayoutEffect里面，等富文本渲染完成设置html就可以了。

**Comment by SteveCGC** [comment]
有人解决吗，我这也报这个错

**Comment by SteveCGC** [comment]
一开始是<strong>标签必然报这个错，是框架的问题

**Comment by SteveCGC** [comment]
`<strong>`标签必然报错

**Comment by yeershao** [comment]
> `\<strong\>`标签必然报错

我还没排查到问题，我是线上才会出现这个报错，本地是不会的

**Comment by SteveCGC** [comment]
> > `\<strong\>`标签必然报错
> 
> 我还没排查到问题，我是线上才会出现这个报错，本地是不会的

`<strong>`标签开头，必然报错，例如`<strong>hello</strong>`

**Comment by yeershao** [comment]
> > > `\<strong\>`标签必然报错
> > 
> > 
> > 我还没排查到问题，我是线上才会出现这个报错，本地是不会的
> 
> `\<strong\>`标签开头，必然报错，例如`\<strong\>hello\</strong\>`

刚刚试了一下，没有出现你说的这个问题。。。  我回显了加粗的字符串，也是正常的。

**Comment by SteveCGC** [comment]
> > > > `\<strong\>`标签必然报错
> > > 
> > > 
> > > 我还没排查到问题，我是线上才会出现这个报错，本地是不会的
> > 
> > 
> > `\<strong\>`标签开头，必然报错，例如`\<strong\>hello\</strong\>`
> 
> 刚刚试了一下，没有出现你说的这个问题。。。 我回显了加粗的字符串，也是正常的。

https://github.com/wangeditor-team/wangEditor/issues/5432

**Comment by xiaoxiong77** [comment]
> > 
> 
> 我也在外面包裹了一层div，但是没有解决。我发现是我在setHtml的时候，如果html的初始值是空字符串，编辑器就会报错。所以我暂时的解决方法是在useLayoutEffect里面，等富文本渲染完成设置html就可以了。

请问是有解决吗？我尝试了，还是不能解决

**Comment by yeershao** [comment]
> > > 
> > 
> > 
> > 我也在外面包裹了一层div，但是没有解决。我发现是我在setHtml的时候，如果html的初始值是空字符串，编辑器就会报错。所以我暂时的解决方法是在useLayoutEffect里面，等富文本渲染完成设置html就可以了。
> 
> 请问是有解决吗？我尝试了，还是不能解决

我就是按照上面的方法解决的，你可以排查一下你的代码是否正常渲染富文本了

**Comment by dyan1992** [comment]
编辑器defaultConfig  默认的autoFocus 要设置为 false ，试了一下解决了

**Comment by Michel-Yang** [comment]
`<p><h3><span style=\"font-weight: bold;\">公积金-同城转移</span></h3><span style=\"font-weight: bold;\">一、受理条件:</span><br>职工住房公积金账户在本市范围内不同单位之间的转移。<br>1、职工的个人住房公积金账户应为封存状态<br>2、由转入单位申请办理。<br><span style=\"color: rgb(194, 79, 74);\">3、专办员办理业务时,需同时确认职工本公积金年度的缴存基数,转移后本公积金年度内不可再次调整转移职工缴存基数。</span><br><span style=\"font-weight: bold;\">二、办理渠道:</span><br>单位专办员可通过“深圳市住房和建设局网站-住房公积金服务-在线办理入口-数字证书/企业电子印章/专办员登录(刷脸方式)”登录单位公积金账户,选择“菜单-职工管理-新增职工-同城转移-添加”自助办理同城转移业务。<br><span style=\"font-weight: bold;\">三、详情请查看办事指南:</span><br>1、申请人可通过“深圳市住房和建设局网站-住房公积金服务-办事指南”进行查询。<br>2、申请人可关注“深圳市住房和建设局”微信公众号,选择“业务办理-公积金办事指南”进行查询。</p>`   以上代码结构回显必报错
