### ISSUE TITLE
自定义插件光标和删除问题

### ISSUE THREAD

**Issue by Didiwei1314** [wangeditor-team/wangEditor#5390]
## 自定义插件

*拼音插件用的标签是<ruby data-w-e-type="pinyin" data-w-e-is-inline> 装 <rp>(</rp><rt>zhuang</rt><rp>)</rp></ruby>`<ruby data-w-e-type="pinyin" data-w-e-is-inline> 装 <rp>(</rp><rt>zhuang</rt><rp>)</rp></ruby>`，插入后光标位置怎么修正，怎样把这些标签整个识别为一个整体 *

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by LittleSource** [comment]
为什么关闭，问题解决了吗
