### ISSUE TITLE
富文本内容重复插入

### ISSUE THREAD

**Issue by QC2168** [wangeditor-team/wangEditor#5391]
## bug 描述

在输入文本后，重复出现文本内容

## 你预期的样子是？

选择文字之后，再输入内容，将选中的文字替换成输入的内容

## 系统和浏览器及版本号

- 操作系统 win10
- 浏览器和版本 Chrome Version 111.0.5563.147 (Official Build) (64-bit)

## wangEditor 版本

`5.1.14`

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

触发该bug的前提条件是输入 粗体文本+普通文本

之后选中富文本的`粗体文本+普通文本`后，再输入文本即可复现

**Comment by QC2168** [comment]
![wangeditor](https://user-images.githubusercontent.com/82024018/229045146-ee5cc42b-891c-4840-a792-08491bd0597a.gif)

**Comment by QC2168** [comment]
目前算是解决了，从上图中富文本显示的是“**测您好**您好试”，但实际上，富文本绑定的值是“测您好试”，由于我项目中是使用`Vue`封装了一层，直接在`watch`函数中执行`setHtml`，更新富文本编辑器内容就好了

**Comment by RiverThrimp** [comment]
上面的结果可以理解为 在监听v-model的data数据如果有数据变化就重新赋值一次
如果是其他的框架就是在onchange事件中去获得一下html然后再设置一下这样是对应的这个data来解决的吧
