### ISSUE TITLE
添加网络图片时出现404，但这个图片链接是可以访问的

### ISSUE THREAD

**Issue by LiYZHe** [wangeditor-team/wangEditor#5409]
## bug 描述

*我在使用添加网络图片功能的时候出现了404，然后在官网的demo中添加也是404，如果单独访问这个图片链接是没问题的（https://lmg.jj20.com/up/allimg/1114/050R1105319/21050Q05319-1-1200.jpg）*

## 你预期的样子是？

*希望图片可以添加到富文本中*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*5.1.23*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  点击网络图片按钮
- 步骤二  粘贴 https://lmg.jj20.com/up/allimg/tp09/210F2125KLK0-0-lp.jpg
- 步骤三 点击确定，查看network发现是404，如果图片单拎出来是可以访问的

**Comment by WangQuan-cn** [comment]
比较奇怪，我用Chrome102，在官网的地址中，第一次粘贴时F12控制台显示404，再次粘贴或者刷新网页、清空浏览器缓存之后，均可以正常显示贴入的图片了，后续一直无法复现问题。

另外请注意😀使用markdown语法将URL图片地址括起来，防止URL包含非期望的额外字符

使用的楼主图片地址：<https://lmg.jj20.com/up/allimg/1114/050R1105319/21050Q05319-1-1200.jpg>

**Comment by duminghong** [comment]
有没有一种可能是人家开防盗链了呢🐶

**Comment by LiYZHe** [comment]
的确是因为防盗链，之前缺乏这方面的知识
