### ISSUE TITLE
customPaste无法阻止浏览器默认粘贴

### ISSUE THREAD

**Issue by luo772435545** [wangeditor-team/wangEditor#5410]
## bug 描述

customPaste无法阻止浏览器默认粘贴

## 你预期的样子是？

customPaste在使用
event.preventDefault();
return false;
后阻止浏览器默认粘贴

## 系统和浏览器及版本号
win10 
谷歌
- 操作系统
- win10
- 浏览器和版本
- 谷歌 版本 102.0.5005.22

## wangEditor 版本
"@wangeditor/editor": "^5.1.23",

## 最小成本的复现步骤
import { Editor, Toolbar } from "@wangeditor/editor-for-vue";
<Editor
      ...
      @customPaste="handleCustomPaste"
 />
const handleCustomPaste = async (editor: IDomEditor, event: ClipboardEvent) => {
    event.preventDefault();
    return false;
}
然后复制地址栏，粘贴

**Comment by chf-gh** [comment]
我也出现了，定制只黏贴文本后可以阻止浏览器，但是如果从记事本复制文本时会出现黏贴2次问题
``` javascript
const text = event?.clipboardData.getData('text/plain') // 获取粘贴的纯文本 
editor.insertText(text) 
event.preventDefault() 
return false
```

**Comment by luo772435545** [comment]
> 我也出现了，定制只黏贴文本后可以阻止浏览器，但是如果从记事本复制文本时会出现黏贴2次问题
> 
> ```js
> const text = event?.clipboardData.getData('text/plain') // 获取粘贴的纯文本 
> editor.insertText(text) 
> event.preventDefault() 
> return false
> ```

后来排查是写法问题，vue需要另外的写法，不能直接return false

**Comment by chf-gh** [comment]
> > 我也出现了，定制只黏贴文本后可以阻止浏览器，但是如果从记事本复制文本时会出现黏贴2次问题
> > ```js
> > const text = event?.clipboardData.getData('text/plain') // 获取粘贴的纯文本 
> > editor.insertText(text) 
> > event.preventDefault() 
> > return false
> > ```
> 
> 后来排查是写法问题，vue需要另外的写法，不能直接return false

大佬，应该怎么写呢？

**Comment by luo772435545** [comment]
> > > 我也出现了，定制只黏贴文本后可以阻止浏览器，但是如果从记事本复制文本时会出现黏贴2次问题
> > > ```js
> > > const text = event?.clipboardData.getData('text/plain') // 获取粘贴的纯文本 
> > > editor.insertText(text) 
> > > event.preventDefault() 
> > > return false
> > > ```
> > 
> > 
> > 后来排查是写法问题，vue需要另外的写法，不能直接return false
> 
> 大佬，应该怎么写呢？

有第三个参数callback，callback(false); 这样

**Comment by chf-gh** [comment]
> > > > 我也出现了，定制只黏贴文本后可以阻止浏览器，但是如果从记事本复制文本时会出现黏贴2次问题
> > > > ```js
> > > > const text = event?.clipboardData.getData('text/plain') // 获取粘贴的纯文本 
> > > > editor.insertText(text) 
> > > > event.preventDefault() 
> > > > return false
> > > > ```
> > > 
> > > 
> > > 后来排查是写法问题，vue需要另外的写法，不能直接return false
> > 
> > 
> > 大佬，应该怎么写呢？
> 
> 有第三个参数callback，callback(false); 这样

666，可以用，解决了我的问题，感谢大佬
