### ISSUE TITLE
表格不能清空

### ISSUE THREAD

**Issue by 15808060087** [wangeditor-team/wangEditor#5444]
## 问题描述

数据中有表格回显后，通过设置this.editor.setHtml('')或者this.editor.setHtml('<p><br></p>')不能清空表格

## wangEditor 版本

"@wangeditor/editor": "^5.1.23",
   "@wangeditor/editor-for-vue": "^1.0.2"

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 点击查看或者修改数据，弹出数据框，数据中带有表格回显后
- 
![image](https://user-images.githubusercontent.com/94597914/234236158-0ec0ceed-6ffa-4649-b1da-afbe2af413ff.png)
- 关闭弹出框后，点击新增，重置了对应的字段为''(空字符串)但是表格还是清空不了
![image](https://user-images.githubusercontent.com/94597914/234235709-cfa3dea4-51de-4c3a-920d-67c686ed1e59.png)

**Comment by MrYu0411** [comment]
有解决嘛 我也碰到这种问题了
