### ISSUE TITLE
editor-for-vue导入组件Editor,Toolbar是any类型

### ISSUE THREAD

**Issue by thelonelyDreamer** [wangeditor-team/wangEditor#5454]
## 问题描述
import { Editor,Toolbar } from '@wangeditor/editor-for-vue'
editor-for-vue导入组件Editor,Toolbar是any类型，引起typescipt类型检查报错
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
import { Editor,Toolbar } from '@wangeditor/editor-for-vue'

typescript 相关配置如下
"strict": true,
 "noImplicitAny": true,
然后vscode提示错误 导入的组件时any类型,查阅了官方文档，typesript支持和vue示例中并未给出相关的解决方案

**Comment by thelonelyDreamer** [comment]
解决方案：
declare module '@wangeditor/editor-for-vue'{
    export class Editor{}
    export class Toolbar{}    
}

**Comment by ZongYan30** [comment]
> 解决方案： declare module '@wangeditor/editor-for-vue'{ export class Editor{} export class Toolbar{} }

我来补充一下，新建的custom.d.ts文件,该文件使用上方的代码:
declare module '@wangeditor/editor-for-vue'{
export class Editor{}
export class Toolbar{}
}

然后注意:这个是需要tsconfig.json中includes配置项需要包含到这个custom.d.ts文件的，这样就解决了。
原理:
是因为wangEditor的package.json中出现了冲突，types和exports配置项让TS感到迷惑，而默认的index.esm.js文件导出的ToolBar等被推断为any类型，TS产生了报错。
