### ISSUE TITLE
设置 HTML 包含 <video> 标签时，检查元素发现无 <video> 标签

### ISSUE THREAD

**Issue by gochantao2** [wangeditor-team/wangEditor#5456]
## bug 描述

*在官网设置 html 的 demo 中，添加以下代码，编辑器无法回显视频*
```javascript
<p><span style="font-size: 29px; font-family: 仿宋;">测试视频问题</span></p>
<p style="text-align: center;"><img src="http://10.200.31.155:9000/marry-backend/admin/2023/05/06/b4a29a223f0d41cb914890811dc5d9f6.jpg" alt="" style="width: 190.39px;height: 281.36px;"></p>
<div> 
 <video poster="" controls="true" width="300" height="auto">
  <source src="http://10.200.31.155:9000/marry-backend/admin/2023/05/06/6b1a873fa9bf49daa358dfdde3cc447f.mp4" type="video/mp4">
 </video> 
</div>
```

## 你预期的样子是？

*能正常展示视频*

## 系统和浏览器及版本号

- 操作系统  window10
- 浏览器和版本  Edge 112.0.1722.68  Chrome 100.0.4896.75

## wangEditor 版本

*@wangeditor/editor": "^5.1.23*

## demo 能否复现该 bug ？

能，直接使用官网 demo

- 中文 demo https://www.wangeditor.com/demo/set-html.html

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  复制上面的测试代码到 https://www.wangeditor.com/demo/set-html.html 文本框
- 步骤二 点击 set HTML按钮即可复现

**Comment by gochantao2** [comment]
找到原因了，需要在video标签外包一个带有 ‘data-w-e-type="video" data-w-e-is-void’属性的div
```html
<p><span style="font-size: 29px; font-family: 仿宋;">测试视频问题</span></p>
<p style="text-align: center;"><img src="http://10.200.31.155:9000/marry-backend/admin/2023/05/06/b4a29a223f0d41cb914890811dc5d9f6.jpg" alt="" style="width: 190.39px;height: 281.36px;"></p>
<div data-w-e-type="video" data-w-e-is-void> 
 <video poster="" controls="true" width="300" height="auto">
  <source src="http://10.200.31.155:9000/marry-backend/admin/2023/05/06/6b1a873fa9bf49daa358dfdde3cc447f.mp4" type="video/mp4">
 </video> 
</div>
```

**Comment by zhao186** [comment]
我也遇到这个代码，我的代码是
 <video controls="true" width="auto" height="auto">
       <source src="${item.url}" type="video/mp4"/>
 </video>

新建时，富文本为空值的时候dangerouslyInsertHtml可以插入视频，编辑时dangerouslyInsertHtml就无法插入，无论什么时候，编辑或新增，setHtml就都可以插入一个视频，按你说的才解决
