### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by weijiang1994** [wangeditor-team/wangEditor#5457]
## 问题描述
内容回显的时候代码无法高亮显示
*请输入遇到的问题...*
我在编辑器编辑的时候，代码块是可以正常高亮显示的，但是保存后在网页显示的时候就没有高亮显示了，网页我也引入了highlight.js的样式了。
## wangEditor 版本

*wangeditor: 5.1.23*
*wangeditor-for-vue: 1.0.2*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by ry0513** [comment]
代码高亮需要自行处理，可以看下文档说明：https://www.wangeditor.com/v5/content.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F，

**Comment by weijiang1994** [comment]
多谢，已经解决了。
