### ISSUE TITLE
 emit('update:content', value) 卡死

### ISSUE THREAD

**Issue by lxychinese** [wangeditor-team/wangEditor#5460]
## bug 描述

 插入代码块卡死  CPU飙升 控制台没有报错
我用了组件数据传递 emit('update:content', value) 

插入表格 报错  Cannot find a descendant at path [0,1]  拖动表格长度卡死

如果编辑器输入一些内容后 又可以了   如果编辑器是空的  稳定重现

 @onChange="handleChange"
const handleChange = (editor) => {
      const value = editor.getHtml();
      emit('update:content', value);
    };

## 你预期的样子是？

正常 不要卡死系统

## 系统和浏览器及版本号

- Chrome 100以上

## wangEditor 版本

    "@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-vue": "^5.1.12",
    "vue": "3.2.21",

## demo 能否复现该 bug ？

不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 文本框不要输入任务内容
- 监听@onChange="handleChange" 
-  handleChange里用  emit('update:content', value);
- 此时再点工具栏插入代码块  浏览器直接卡死 CPU飙升

**Comment by chaiyouxiu** [comment]
确实复现了，我项目页面现在也卡死了
