### ISSUE TITLE
请问可以把 `ImageWidthBaseClass` export 出来不，我需要给图片增加 75% 的缩放选项。

### ISSUE THREAD

**Issue by giiska** [wangeditor-team/wangEditor#5465]
## 功能描述

非常感谢大佬开发的这个编辑器！

请问可以把 `ImageWidthBaseClass` export 出来不，我需要给图片增加 75% 的缩放选项。
然后我可以通过
```
const defaultImageKeys = Boot.editorConfig.hoverbarKeys?.image.menuKeys;
if (defaultImageKeys?.length) {
  defaultImageKeys.splice(2, 0, 'imageWidth301');
}
const editorConfig = {
  hoverbarKeys: {
    image: {
      menuKeys: defaultImageKeys,
    },
  },
};
```
完成增加一个或多个图片缩放选项。当然，如果你可以把缩放级别做成可以配置那更好！

## 提炼几个功能点

把 `ImageWidthBaseClass` export 出来

## 原型图

无

## 可参考的案例

<img width="498" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/5893693/346e52e3-3eaa-40ac-865e-faad1ddfd0e0">

**Comment by jiangzenong** [comment]
<img width="533" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/96042252/c355da44-ee65-46b3-9241-54d54a22ee33">
<img width="489" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/96042252/32d8b717-688f-46f5-946e-22d7588ef014">
<img width="185" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/96042252/25c071b4-2e30-41b8-a50c-5ae6e82544c2">
<img width="313" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/96042252/b78a1219-6ff2-4984-abad-4ec44dadf6ad">
