### ISSUE TITLE
初始化 value 如果是错误的 html 则会导致页面白屏

### ISSUE THREAD

**Issue by crazyair** [wangeditor-team/wangEditor#5468]
## bug 描述

*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

以下2个都可

https://stackblitz.com/edit/react-kadwse?file=demo.tsx
https://codesandbox.io/s/an-niu-lei-xing-antd-5-4-5-forked-0sknox?file=/demo.tsx:0-729

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

将`useState(html)`解除注释，则会看到效果

**Comment by crazyair** [comment]
@wangfupeng1988 有空看看吗

**Comment by hahaaha** [comment]
@crazyair 要用div包起来

**Comment by crazyair** [comment]
> @crazyair 要用div包起来

包在哪里，麻烦贴下代码示意

**Comment by hahaaha** [comment]
这样子 `<div><td><span>test</span></td></div>`

**Comment by crazyair** [comment]
> 这样子 `<div><td><span>test</span></td></div>`

我的意思是用户在编辑器上编辑内容，电脑没电关机后导致的 html 是上面那样子的，我不能手动给他包个 div 吧？

**Comment by hahaaha** [comment]
这种的不应该去做数据清洗么 本身编辑器里只支持div这种形式的发自我的 iPhone在 2023年5月18日，18:17，叶枫 ***@***.***> 写道：﻿

这样子 <div><td><span>test</span></td></div>

我的意思是用户在编辑器上编辑内容，点击关机后导致的 html 是上面那样子的，我不能手动给他包个 div 吧？

**Comment by crazyair** [comment]
> 这种的不应该去做数据清洗么 本身编辑器里只支持div这种形式的发自我的 iPhone在 2023年5月18日，18:17，叶枫 ***@***.***> 写道：﻿ 这样子 <div><td><span>test</span></td></div> 我的意思是用户在编辑器上编辑内容，点击关机后导致的 html 是上面那样子的，我不能手动给他包个 div 吧？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

这个 html 只是我是示意，用户真实的 html 是另外的样子
