### ISSUE TITLE
编辑器不能支持android 8

### ISSUE THREAD

**Issue by gaoseng** [wangeditor-team/wangEditor#5473]
## 问题描述

在移动端使用过程中，发现android 8 不支持一些功能，如图片上传。 报错说语法太高级，应该是内部代码没编译成es5

## wangEditor 版本

v5

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

**Comment by hahaaha** [comment]
这个不建议在移动端使用
