### ISSUE TITLE
按照文档获取toolbar.getConfig()结果为null

### ISSUE THREAD

**Issue by simon-muyezhang** [wangeditor-team/wangEditor#5502]
根据文档https://www.wangeditor.com/v5/toolbar-config.html#getconfig
![image](https://github.com/wangeditor-team/wangEditor/assets/10706610/ba8c07ac-a8d7-4360-8c86-7087d136dcd6)
这里获取的currToolConfig为null

import '@wangeditor/editor/dist/css/style.css' // 引入 css
import React, { useState, useEffect } from 'react'
import { Editor, Toolbar } from '@wangeditor/editor-for-react'
import { DomEditor } from '@wangeditor/editor'

function MyEditor() {
    // editor 实例
    const [editor, setEditor] = useState(null)                   // JS 语法

    // 编辑器内容
    const [html, setHtml] = useState('<p>hello</p>')

    // 工具栏配置
    const toolbar = DomEditor.getToolbar(editor)
    const curToolbarConfig = toolbar.getConfig()
    console.log(curToolbarConfig) // 当前菜单排序和分组
    const toolbarConfig = {}  

    // 及时销毁 editor ，重要！
    useEffect(() => {
        return () => {
            if (editor == null) return
            editor.destroy()
            setEditor(null)
        }
    }, [editor])

    return (
        <>
            <div style={{ border: '1px solid #ccc', zIndex: 100 }}>
                <Toolbar
                    editor={editor}
                    defaultConfig={toolbarConfig}
                    mode="default"
                    style={{ borderBottom: '1px solid #ccc' }}
                />
                <Editor
                    defaultConfig={editorConfig}
                    value={html}
                    onCreated={setEditor}
                    onChange={editor => setHtml(editor.getHtml())}
                    mode="default"
                    style={{ height: '500px', overflowY: 'hidden' }}
                />
            </div>
            <div style={{ marginTop: '15px' }}>
                {html}
            </div>
        </>
    )
}

export default MyEditor

**Comment by cxhcmc** [comment]
在React 里 DomEditor.getToolbar(editor); 恒等于空了，写在哪都不好使

**Comment by coder-huo** [comment]
DomEditor.getToolbar(editor) 结果为空的问题，找到办法了吗？
