### ISSUE TITLE
内容居中对齐失败

### ISSUE THREAD

**Issue by HelenSilas** [wangeditor-team/wangEditor#5550]
## bug 描述
输入文本后设置了居中对齐或者右对齐，保存成功后并没有设置居中样式

## 你预期的样子是？
保存成功后再次打开应该是自己设置的对齐方式

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本
chorme
## wangEditor 版本
v4.7.15

## 最小成本的复现步骤
输入文本后内容后“测试信息”设置居中对齐保存，控制台打印的html是 <p>测试信息</p>

**Comment by HelenSilas** [comment]
控制台打印的内容： 只有p标签包含内容测试信息，没有相关样式内容

**Comment by HelenSilas** [comment]
通过editor.$textElem.elems[0] 直接获取dom元素

**Comment by simon-muyezhang** [comment]
@HelenSilas 哥们，我也碰到同样的问题了，请问你是如何解决的？
