### ISSUE TITLE
输入框与编辑器在同一个页面造成的问题

### ISSUE THREAD

**Issue by shehuiren132** [wangeditor-team/wangEditor#5553]
## 问题描述

*当编辑器中输入内容后，再点击输入框，由于编辑器未销毁造成输入框的输入出现问题，该如何解决呢？使用了disable（）与readOnly都不能解决*

## wangEditor 版本

*vue2 @wangeditor/editor-for-vue1.0.2*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by shehuiren132** [comment]
![image](https://github.com/wangeditor-team/wangEditor/assets/106672362/74975c6a-1ad5-4ae0-b435-362fc0554a7d)

**Comment by camilleLin** [comment]
最后是怎么解决的呢

**Comment by shehuiren132** [comment]
上面的输入框用:value绑定数据
