### ISSUE TITLE
对元素增加了draggable属性

### ISSUE THREAD

**Issue by Mk-web1012** [wangeditor-team/wangEditor#5584]
## 问题描述
对每一个段落增加了draggable属性，使之可以拖动，且写了一些方法可以进行排序，但是数据并没有更改

*请输入遇到的问题...*
如何去更新该数据呢，目前想到的方案是获取更改后的html，清空页面数据，再次插入该dom数据，但是消耗较大，且插入设置后会导致多出一行

## wangEditor 版本
5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by Morii120** [comment]
怎么实现兄弟 我想要实现类似的功能
