### ISSUE TITLE
富文本框当有高度，会滚动时候，设置字体颜色的弹框被遮盖

### ISSUE THREAD

**Issue by paoyideyun** [wangeditor-team/wangEditor#5589]
## bug 描述
富文本框当有高度，会滚动时候，设置字体颜色的弹框被遮盖
*请输入内容……*

## 你预期的样子是？

*请输入内容……*

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能/不能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo
![Uploading image.png…]()

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

**Comment by 22007127** [comment]
方便问一下这个问题是如何解决的吗？我这边也遇到了这个问题
