### ISSUE TITLE
无法同时将word文档的文本与图片一起复制进编辑器,此时图片并不会上传与回显

### ISSUE THREAD

**Issue by AlstonZhuang** [wangeditor-team/wangEditor#5593]
## 问题描述

*如何将word文档中的文本与图片同时复制进入wangeditor,此时图片可以被上传并回显?
目前我只能单独复制一张图片放入编辑器中实现上传与回显,对于同时复制word文档中的文本与图片进入编辑器时文本可正常显示,图片不会上传*

## wangEditor 版本
最新版
*2023*

## 是否查阅了文档 ？
是

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 打开具有wangeditor编辑器的页面,打开调试工具的newwork,注意观察图片放进去时的资源请求
- 打开一份具有文本与图片的word文档,将一段文本与图片一起复制下来放入wangeditor编辑器中,查看network
- 步骤二
- 此时观察newwork,发现出现了图片的加载然后报错,
file:///C:/Users/Hujf/AppData/Local/Temp/ksohtml42092/wps1.jpg.这应该是读取本地文件出错,同时并未进行图片上传的请求
- 步骤三

**Comment by xiaoshanweb** [comment]
请问解决了吗，我也碰到这个问题了

**Comment by AlstonZhuang** [comment]
解决了，需要自定义复制粘贴。具体代码我这儿拿不出来



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月30日 13:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器,此时图片并不会上传与回显 (Issue #5593) |

请问解决了吗，我也碰到这个问题了

**Comment by xiaoshanweb** [comment]
> 
是用customPaste自定义吗，我这边除了文字图片要一起粘贴，还要求表格里也支持带图片粘贴

**Comment by AlstonZhuang** [comment]
加我微信交流




| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月30日 14:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器,此时图片并不会上传与回显 (Issue #5593) |

是用customPaste自定义吗，我这边除了文字图片要一起粘贴，还要求表格里也支持带图片粘贴

**Comment by Gao-Gordon** [comment]
麻烦问一下你是怎么解决的

**Comment by AlstonZhuang** [comment]
这个你需要看到代码才行，不然我说了原理你也不好实现。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月01日 09:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器,此时图片并不会上传与回显 (Issue #5593) |

麻烦问一下你是怎么解决的

**Comment by Gao-Gordon** [comment]
代码可以通过什么途径看到

**Comment by xiaoshanweb** [comment]
> 加我微信交流 | | ***@***.*** | | ***@***.*** |
> [……](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年08月30日 14:17 | | 营养 | ***@***.***> | | 抄送至| ***@***.***>***@***.***> | | 主题 | 回复: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器，此时图片并不会上传与回显（Issue #5593） | 是用自定义粘贴自定义吗，我要求除了文字图片要一起粘贴，还要求表格里也支持带图片粘贴 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：***@***.***>

请问怎么加呀，没看到您的微信号在哪🧐

**Comment by dantes1844** [comment]
> > 加我微信交流 | | _**@**_.*** | | _**@**_.*** |
> > [……](#)
> > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2023年08月30日 14:17 | | 营养 | _**@**_.**_> | | 抄送至| _**@**_._**>**_@_**.**_> | | 主题 | 回复: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器，此时图片并不会上传与回显（Issue #5593） | 是用自定义粘贴自定义吗，我要求除了文字图片要一起粘贴，还要求表格里也支持带图片粘贴 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：_**@**_.***>
> 
> 请问怎么加呀，没看到您的微信号在哪🧐

请问解决了吗， 提供个思路可以吗

**Comment by AlstonZhuang** [comment]
UTInheritor  请加我这个微信，不过代码我得回去找一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月07日 14:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器,此时图片并不会上传与回显 (Issue #5593) |

加我微信交流 | | @.*** | | @.*** |
……
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年08月30日 14:17 | | 营养 | _@**._> | | 抄送至| ***@***.***>@.> | | 主题 | 回复: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器，此时图片并不会上传与回显（Issue #5593） | 是用自定义粘贴自定义吗，我要求除了文字图片要一起粘贴，还要求表格里也支持带图片粘贴 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：@_.*>

请问怎么加呀，没看到您的微信号在哪🧐

请问解决了吗， 提供个思路可以吗

**Comment by xiaoshanweb** [comment]
> > > 加我微信交流 | | _**@**_.*** | | _**@**_.*** |
> > > [……](#)
> > > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2023年08月30日 14:17 | | 营养 | _**@**_.**_> | | 抄送至| _**@**_._**>**_@_**.**_> | | 主题 | 回复: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器，此时图片并不会上传与回显（Issue #5593） | 是用自定义粘贴自定义吗，我要求除了文字图片要一起粘贴，还要求表格里也支持带图片粘贴 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：_**@**_.***>
> > 
> > 
> > 请问怎么加呀，没看到您的微信号在哪🧐
> 
> 请问解决了吗， 提供个思路可以吗

换了个插件，CKEditor4，但是这个插件只支持office办公软件，wps的不支持。

**Comment by AlstonZhuang** [comment]
UTInheritor  请您加我这个微信，加的时候备注一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月07日 20:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器,此时图片并不会上传与回显 (Issue #5593) |

加我微信交流 | | @.*** | | @.*** |
……
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年08月30日 14:17 | | 营养 | _@**._> | | 抄送至| ***@***.***>@.> | | 主题 | 回复: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器，此时图片并不会上传与回显（Issue #5593） | 是用自定义粘贴自定义吗，我要求除了文字图片要一起粘贴，还要求表格里也支持带图片粘贴 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：@_.*>

请问怎么加呀，没看到您的微信号在哪🧐

请问解决了吗， 提供个思路可以吗

换了个插件，CKEditor4，但是这个插件只支持office办公软件，wps的不支持。

**Comment by xiaoshanweb** [comment]
> UTInheritor 请加我这个微信，不过代码我得回去找一下
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年10月07日 14:56 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器,此时图片并不会上传与回显 (Issue #5593) | 加我微信交流 | | @.*** | | @.*** | …… ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年08月30日 14:17 | | 营养 | _@**._> | | 抄送至| ***@***.***>@.> | | 主题 | 回复: [wangeditor-team/wangEditor] 无法同时将word文档的文本与图片一起复制进编辑器，此时图片并不会上传与回显（Issue #5593） | 是用自定义粘贴自定义吗，我要求除了文字图片要一起粘贴，还要求表格里也支持带图片粘贴 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您创作了该主题。消息 ID：@_.*> 请问怎么加呀，没看到您的微信号在哪🧐 请问解决了吗， 提供个思路可以吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

好的，感谢

**Comment by Aoyia** [comment]
这个问题盖楼盖下来愣是没有一行代码，真是气煞人也。大神们倒是说说怎么解决，可急坏了

**Comment by ivan0525** [comment]
咋还邮件呢

**Comment by Swarz** [comment]
咋解决的

**Comment by cycleccc** [comment]
### 原因
这个是 wps 的锅，单个图片复制的时候是单张图片，多个复制 wps 自己定义的复制逻辑转出了 html 内容把图片的src 改成了 file:///C:\ 本地路径的格式，这个格式在浏览器只能展示个  空占位符图片。（有图片但是  src 是本地路径，没法展示）

### 解决方法
在复制进来后过滤更换 富文本中 的 file:/// 值。

**Comment by wjw020206** [comment]
我的做法是如果文档内中包含 file:/// 的值，提示图片粘贴失败，并阻止输入

```js
// newValue 是你获取到的富文本的内容
if ( !newValue.includes('file:///') ) {
  // 正常处理....
} else {
  // editorRef 是编辑器实例，调撤销方法，起到阻止图片插入的效果
  editorRef.value.undo();
}
```

**Comment by panxin226** [comment]
> ### 原因
> 这个是 wps 的锅，单个图片复制的时候是单张图片，多个复制 wps 自己定义的复制逻辑转出了 html 内容把图片的src 改成了 file:///C:\ 本地路径的格式，这个格式在浏览器只能展示个 空占位符图片。（有图片但是 src 是本地路径，没法展示）
> 
> ### 解决方法
> 在复制进来后过滤更换 富文本中 的 file:/// 值。

关键这个怎么替换file:///的值啊？我们单个图片是直接上传到服务器里面的
![image](https://github.com/user-attachments/assets/d8155721-6a9d-46c8-b838-701066a85301)

**Comment by yutons3112** [comment]
我写了一个“[从Word导入](https://github.com/yutons3112/wangEditor-plugin-import-from-word/blob/main/README.md)”的插件，直接从Word文档导入，解决图片上传问题，欢迎fork，欢迎试用
![demo](https://github.com/user-attachments/assets/6d3fdcf7-0800-43c5-bafc-885011d05c58)
