### ISSUE TITLE
VUE中，当我设置了编辑器scroll为false且设置了min-height为300以上的时候，会弹出警告

### ISSUE THREAD

**Issue by zfzfzzf** [wangeditor-team/wangEditor#5597]
## bug 描述

*VUE中，当我设置了编辑器scroll为false且设置了min-height为300以上的时候，会弹出警告*

## 你预期的样子是？

*不会弹出警告*

## 系统和浏览器及版本号

- W11
- 谷歌

## wangEditor 版本

*V5*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
![1690274706108](https://github.com/wangeditor-team/wangEditor/assets/128294177/d68f3fbf-2360-4fda-a289-e8a902e52c72)

- 步骤二
- 步骤三

**Comment by yanerdyr** [comment]
这个问题解决了吗？我看还是会有warning
