### ISSUE TITLE
征集移动断富文本编辑器的设计建议

### ISSUE THREAD

**Issue by wangfupeng1988** [wangeditor-team/wangEditor#56]
近期计划开始设计移动端的富文本编辑器，在此征求大家的建议和意见。只要是关于富文本编辑器的，随便写，无论是代码开发还是界面设计，还是目前市场的需求，还是用户体验的需要，都行，来着不惧。

**注意，不要写无关内容**

---

另外，在此说一下我自己的想法，我觉得移动端的编辑器和PC web端肯定是不一样的，要适应手机屏幕和手指操作，就必须做出调整，在此我将参考以下三个案例：有道云笔记、印象笔记和iOS备忘录

![img_1019](https://cloud.githubusercontent.com/assets/9583120/10532214/231e7a3c-73ee-11e5-9292-ae66d456bcf9.PNG)

![img_1020](https://cloud.githubusercontent.com/assets/9583120/10532215/25daf296-73ee-11e5-8968-00e83345a043.PNG)

**Comment by yo846tt** [comment]
我觉得吧！移动端的编辑需要的功能只需要几个功能，表情、图片、附件（即文件）这三个主要功能和其他几个次要功能就可以了，如文字加粗、加颜色（居中居左居右？）。不过移动端编辑器还是用textarea？

**Comment by Greenmzc** [comment]
移动编辑器应该弱化文字的比重，偏重图片和表情部分，减少配置按钮，做成响应式的，另外能备有几套常用模板最好了

**Comment by wangfupeng1988** [comment]
@yo846tt 

附件不打算加，附件不应该集成在编辑其中，另外自己做就可以了。例如网易邮箱的移动端，附件就是在外面。

另外，用 textarea 没什么不好的，而且会方便form提交。

**Comment by wangfupeng1988** [comment]
@Greenmzc 

模板？可以举几个例子吗

**Comment by Greenmzc** [comment]
现在新建word都会出现几个常用的模板供用户选择，可以帮助用户快速搭建文本框架，节省时间。可以征集一下大家的使用文本频度。

**Comment by mhyailz** [comment]
移动编辑器依赖于一个移动端的前端框架。我了解到目前有mui，jingle，frozenui，framework7这些框架，其中framework7维护文档可能比较全面。不知道你会实现编辑器和哪种框架结合，或者有其它的方式 实现？

**Comment by wangfupeng1988** [comment]
@Greenmzc 
你觉得这种模板，是应该编辑器插件来做的事儿吗？
编辑器只提供一个赋值的接口，需要什么样的模板，项目中自己来实现。
我只关注核心部分！

**Comment by wangfupeng1988** [comment]
@mhyailz 
编辑器本身不需要复杂的UI设计，所以我不像依赖于任何框架，就像之前wangEditor依赖于bootstrap，后来弃用了，没必要。
但是为了兼容性、开发复杂度的一些问题，我还是需要依赖于一个最轻量化的zepto，其他的都不需要依赖。

至于和框架的结合问题，我相信一个优秀的框架，肯定能很容易融合进去原生的东西。否则，我觉得你自己用着这个框架也不舒服。

**Comment by mhyailz** [comment]
@wangfupeng1988 同意你说的编辑器本身尽量不依赖框架，轻量。如果像商品评论，微博文字这种对排版要求不高，文字图片内容不多的富文本、UI确实不复杂并且能较好的融合别的框架。但有些编辑篇幅较大的文章，偏文艺写作的app，编辑排版的样式和最终呈现的样式是否一致就显得很重要。富文本UI觉得ZERO那款app的文本编辑挺好的，逼格也挺高，楼主可以看看是否有可参考的。![zj8kjib4 _ 34q 8plhcuu](https://cloud.githubusercontent.com/assets/2506136/10537615/a24a31d4-7425-11e5-93e0-1a4d306264b9.png)

**Comment by wangfupeng1988** [comment]
@mhyailz 从你说的我倒是想到了一点，应该调研一下手机端富文本应用的场景。例如微博客发布、商品评论、笔记书写这一些。恩，应该调研一下。

**Comment by liniu** [comment]
保持轻量，少依赖很关键，这是其他很多文本编辑器的弱点

**Comment by lomoalbert** [comment]
建议加上链接功能, 对我而言必不可少.

**Comment by upupzealot** [comment]
文字、图片（相册选取）就好了，其他花里胡哨的并不是十分关键。
不过特别希望有的一个功能是：**移动光标**的功能呢，就是可以将现在的光标前移或后移一格。
有时候想在已有的内容中间插入一些东西，但是手指太大点不准，很痛苦！

**Comment by liygheart** [comment]
建议：输入一个链接地址，编辑器可以自动识别并转换成超链接

**Comment by alansuhe** [comment]
1.加入上传图片的裁剪功能，请参考：[picture cut](http://picturecut.tuyoshi.com.br/)
2.现在手机照片都是好几兆一张，可以在图片上传前有机会在js端进行尺寸压缩控制，减小上传文件

**Comment by inotgaoshou** [comment]
支持多图片上传啊，ueditor和kindeditor都支持的，这个功能很有用。

**Comment by wangfupeng1988** [comment]
@inotgaoshou 

> 支持多图片上传啊，ueditor和kindeditor都支持的，这个功能很有用。

这个问题，单独提交一个issue，并描述问题的详情。编辑器是支持多图片上传的，你如果用着有问题，请说明哪里、什么问题等。

**Comment by wangfupeng1988** [comment]
> 1. 楼主在优化移动端编辑器时

移动端坑太多，而且用户太少，不值得做，仅仅用 JS 也做不好，因此放弃

> 2、如果能加上简单的图片裁切和旋转功能就更好了

编辑器升级 v3 之后，力求简洁明了，以最小的成本满足 80% 用户的需求，剩下 20% 的其他需求暂时不支持。

**Comment by luduanfeng** [comment]
建议：
虽然你上面回复了changbb 的建议，但是我还是希望能加入图片裁切功能，经常用到。

**Comment by wangfupeng1988** [comment]
@mdaima 图片裁切暂时不会加，绝大部分用户没有给我提这个需求，不会为少数用户做高成本的改动。

**Comment by harryyuanfeng** [comment]
请问现在移动端有适配css了嘛？

**Comment by lanxiaoyuan** [comment]
web端怎么把word图文一起复制到wangEditor里

**Comment by shizongger** [comment]
来了，从慕课网的视频和文章过来的，mark一下。

**Comment by xiaofei9070** [comment]
有道云代码模块很好用
