### ISSUE TITLE
dangerouslyInsertHtml 无效 vue3 语法script-setup 这个情况下无效

### ISSUE THREAD

**Issue by LIZAOYUEYUENIAO** [wangeditor-team/wangEditor#5654]
## bug 描述

dangerouslyInsertHtml 无效 vue3 语法糖script-setup 这个情况下无效

官网vue3的demo 复制过来 改成 script-setup 这种形式的这个api调用无效，insertText也一样

## 你预期的样子是？

dangerouslyInsertHtml有效

## 系统和浏览器及版本号

- 操作系统 
-  window
- 浏览器和版本 
- 谷歌  vue3.3

## wangEditor 版本

5

## demo 能否复现该 bug ？

不能

**Comment by adeNpe** [comment]
后来是怎么解决的呢
