### ISSUE TITLE
Nuxt3使用wangEditor无法粘贴图片

### ISSUE THREAD

**Issue by 11003** [wangeditor-team/wangEditor#5664]
## 版本
```
    "@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-vue": "^5.1.12",
```

**Comment by WGinit** [comment]
可以把粘贴图片转base64 格式显示：

editorConfig.MENU_CONF.uploadImage.base64LimitSize = 50 * 1024  // 最大50kb内的图片会显示

**Comment by 11003** [comment]
> 可以把粘贴图片转base64 格式显示：
> 
> editorConfig.MENU_CONF.uploadImage.base64LimitSize = 50 * 1024 // 最大50kb内的图片会显示

谢谢~~！
