### ISSUE TITLE
插入视频  视频样式丑陋   大小修改后 直接通过vhtml展示 变形

### ISSUE THREAD

**Issue by wx-528** [wangeditor-team/wangEditor#5681]
## bug 描述

*请输入内容……*
页面自定义插入视频  视频标签占比太大  通过点击修改尺寸按钮后   整个富文本框展示视频标签不是居中
## 你预期的样子是？

*请输入内容……*
预期是插入式有个合适大小   那个修改尺寸的按钮应该可以选择开启关闭
## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

*请输入内容……*
win7   chrome  版本 109.0.5414.74
## demo 能否复现该 bug ？

能/不能
能
- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/
就是一个最低配置的富文本框自定义插入视频 然后在文本中显示    视频可以是用手机拍的    选择本地上传

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一  
- 步骤二
- 步骤三

**Comment by zzx1314** [comment]
这个项目不维护了，兄弟

**Comment by Iamwuduo** [comment]
这个富文本编辑器需要在前端加一些样式来做限制，例如图片与视频这些，最好是在前端增加max-width:100%的样式。

**Comment by wx-528** [comment]
> 这个富文本编辑器需要在前端加一些样式来做限制，例如图片与视频这些，最好是在前端增加max-width:100%的样式。
