### ISSUE TITLE
自定义按钮插入button标签，但是却插入了span标签

### ISSUE THREAD

**Issue by dufei1122** [wangeditor-team/wangEditor#5685]
## bug 描述

*自定义按钮插入button标签，但是却插入了span标签*

## 你预期的样子是？

*插入button标签，如“/<button type="button"><span>保存</span></button>/“，两个斜杠中间的内容*

## 系统和浏览器及版本号

- Win10 专业版 64位
- Chrome 103

## wangEditor 版本

*4.7.8*

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*内部系统，无法外网访问*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 打开demo
- 使光标聚焦到编辑器内
- 打开F12，输入document.execCommand('insertHTML', false, '/<button><span>保存</span></button>/');

**Comment by wangchenyi1996** [comment]
请问下 这个问题解决了吗

**Comment by dufei1122** [comment]
解决了在 2024年7月4日，14:15，王承毅 ***@***.***> 写道：﻿
请问下 这个问题解决了吗
