### ISSUE TITLE
设置默认字体后再在编辑器中更改文本的H1~H5标签会产生样式冲突

### ISSUE THREAD

**Issue by cycleccc** [wangeditor-team/wangEditor#5817]
> > > const defaultContent = { fontFamily:'宋体', lineHeight:18 } @end-cycle 是这样吗修改吗，可以具体一点吗
> > 
> > 
> > @HelloJZP 最好是看一下 相关 issure #4042 或是查看sandbox链接 vue2：[codesandbox.io/p/sandbox/vue2-wangeditor-demo-forked-67fh5s](https://codesandbox.io/p/sandbox/vue2-wangeditor-demo-forked-67fh5s) react：[codesandbox.io/p/sandbox/react-wangeditor-demo-forked-59c48n](https://codesandbox.io/p/sandbox/react-wangeditor-demo-forked-59c48n)
> 
> 在[#4042](https://github.com/wangeditor-team/wangEditor/issues/4042)中，有人提到这样会修改H1-H5的字体大小[@zhangyueteng87](https://github.com/wangeditor-team/wangEditor/issues/4042#issuecomment-1296070205)，我也出现了相同的情况，楼下的回复是自己的样式污染了H1-H5，但是dom显示是内联样式到H1下面的span上面去了 ![image](https://private-user-images.githubusercontent.com/70753359/316359735-9b1f21d7-dec7-400c-9873-fa278bf4810b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjA4MzQsIm5iZiI6MTcxMTYyMDUzNCwicGF0aCI6Ii83MDc1MzM1OS8zMTYzNTk3MzUtOWIxZjIxZDctZGVjNy00MDBjLTk4NzMtZmEyNzhiZjQ4MTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDEwMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NjNhZjM0YmE3MjVjNmZiYmFjMzU0ZDE4MDg4YzM0ZGU5YjM5Mjg5NWZjMWI1MjI1ZjJhMDMzOWY4YjA5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2lgRF8XQXJ_rW49o9pUh-GjRVLCsmXQ1Hq1b0ogDJGo)

对的，用 jsonContent 来配置，最终会设置 font-size 到 data-slate-node 节点从而影响到 H1-H5 的样式，这涉及到 wangeditor 的底层 slate 依赖的层级渲染 ，wangeditor 的 默认字号、默认字体原理还是清空样式，使用 jsoncontent 只能做到上层覆盖（渲染在上层），会和H1-H5标签冲突。
确实需要有更好的实现，可能需要更改源代码。

_Originally posted by @end-cycle in https://github.com/wangeditor-team/wangEditor/issues/5796#issuecomment-2024876663_

**Comment by cycleccc** [comment]
## 问题描述

设置默认字体后再在编辑器中更改文本的H1~H5标签会产生样式冲突

## wangEditor 版本

v5@latest

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

是

## 最小成本的复现步骤

根据issue#4042的教程或根据issue5796的demo可以复现

- 步骤一
设置jsonContent或html的默认值
```javascript
          const jsonContent = [
            {
              type: "paragraph",
              children: [{ text: "试试是不是黑体" }],
            // fontSize: "48px",
            fontFamily: "黑体",
            lineheight: 3,
          },
```
- 步骤二
在createEditor时传入参数jsonContent为content
- 步骤三
在浏览器中设置文本的H1~h5标签

**Comment by cycleccc** [comment]
经过对WangEditor 源码中 content 的初始化、自定义munu的初始化、以及富文本编辑器的使用理解后

我认为这可能不是一个bug，而算是一种特性，因为在修改标签为h1后再设置该段的字体，一样会使h1标签的大小被子标签的font-size覆盖。

**Comment by twx0909** [comment]
解决了吗

**Comment by cycleccc** [comment]
@twx0909 后续没有去处理，我上一条评论也解释了为什么不去处理，是因为假如设置了默认字号50px那就代表富文本的字段默认就是带着这个50px的，就算在外面套一层h标签，h标签的大小也会被fontsize覆盖。按语义上来说，被覆盖并没有问题。

如果有不同的观点或解决方案的话欢迎讨论

**Comment by cycleccc** [comment]
@twx0909 有需要的话可以在  [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 提 issue
