### ISSUE TITLE
如何上传图片(自定义样式)

### ISSUE THREAD

**Issue by L1mit1337** [wangeditor-team/wangEditor#5859]
## 问题描述
如题
*请输入遇到的问题...*
我在数据库发现style是留着的想必应该可以自定义样式 找了半天文档没有说。。。。 
![image](https://github.com/wangeditor-team/wangEditor/assets/63892863/80d7ffaf-371f-433a-8a15-2bbfa9f38ea4)
![image](https://github.com/wangeditor-team/wangEditor/assets/63892863/2fdba5f7-2446-43a7-843f-7d7f06ee97fe)

## wangEditor 版本

*请输入内容……*
V5 FOR VUE3
## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
暂时还不支持自定义样式，你看的源码中的是自定义回调以及配置等

**Comment by L1mit1337** [comment]
> 暂时还不支持自定义样式，你看的源码中的是自定义回调以及配置等

我前端这边加上样式了 换种思路解决了
![image](https://github.com/wangeditor-team/wangEditor/assets/63892863/895b50e1-6494-4301-b610-d830f0ff9e10)
