### ISSUE TITLE
限制了文本字数，最后获取的文本长度确实是在字数内，但是页面上又显示超出

### ISSUE THREAD

**Issue by yang2022** [wangeditor-team/wangEditor#5888]
## bug 描述

限制了文本字数，开启了复制粘贴，最后获取的文本长度确实是在字数内，但是页面上又显示超出
<img width="646" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/48640837/d7727fa6-d977-4df5-8d04-06a77c158a65">

## 你预期的样子是？

文本长度显示在字数限制内

## 系统和浏览器及版本号

- 操作系统  mac
- 浏览器和版本 谷歌浏览器

## wangEditor 版本

*请输入内容……*

## demo 能否复现该 bug ？

能

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
复制粘贴文字到最大长度，直到被拦截
- 步骤二
回车键，复制粘贴随便一个网址
- 步骤三
再回车键，复制粘贴随便一个网址，此时页面显示有网址，字符长度超过限制

**Comment by cycleccc** [comment]
你好，能在[wangeditor-next](https://github.com/cycleccc/wangEditor-next)试试看是否还有这个问题吗，
你可以在 readme 里，找到对应的 沙盒 demo 试验是否会复现这个bug。
我以前修复过这个 bug ，你可以试试是否在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next)还会出现这个bug

**Comment by yang2022** [comment]
我是在vue3的沙盒里重试了，仍然出现了相同的情况，本地使用的版本是[wangeditor-next](https://github.com/cycleccc/wangEditor-next)
<img width="1440" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/48640837/40040373-8bd3-4045-86ab-e14d96e25c71">

**Comment by cycleccc** [comment]
收到，这复制粘贴这一块，因为浏览器的复制规则，有很多种情况需要覆盖处理，这个我应该很快能修复，这周之内解决。

不过另提一句，推荐使用 [next-vue3](https://stackblitz.com/edit/vue3-wangeditor-demo-8emmc7?file=src%2FApp.vue) 沙盒测试，后续的维护都在[wangeditor-next](https://github.com/cycleccc/wangEditor-next) 相关版本里了。

我等空下来就试一下复现。

**Comment by cycleccc** [comment]
你好，我已经发布了最新[wangeditor-next](https://github.com/cycleccc/wangEditor-next)新版本，对 maxlength 情况下的 链接插入的几种情况做了处理，刚刚在[vue3-maxlength-demo](https://stackblitz.com/edit/vue3-wangeditor-demo-k973ga?file=src%2FApp.vue) 中测试了没有问题。你可以切换 该 demo 中对应的 editor 和 editor-for-vue 版本解决这个 bug

**Comment by yang2022** [comment]
可以了，多谢大佬

**Comment by cycleccc** [comment]
okk,能解决问题就行，这个issue没问题的话就可以关闭了，后续有其它问题可以到[wangeditor-next-issue](https://github.com/cycleccc/wangEditor-next/issues)提。

**Comment by cycleccc** [comment]
顺便，方便的话麻烦到[wangeditor-next](https://github.com/cycleccc/wangEditor-next)点个star，这是我持续维护和改进这个项目的动力😆

**Comment by yang2022** [comment]
star了😄
