### ISSUE TITLE
img显示不出来

### ISSUE THREAD

**Issue by yangnanle** [wangeditor-team/wangEditor#5891]
## 问题描述

*在渲染时，img标签不显示，只有几行空格*
![image](https://github.com/wangeditor-team/wangEditor/assets/151699136/8270d128-07ff-4a85-bf6e-9f96ad036e3f)

## wangEditor 版本

*^5.1.23*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 我在提供的在线demo中，添加，打开就可以看到：https://stackblitz.com/edit/vue3-wangeditor-demo-gcltbp?file=src%2Fcomponents%2FBasicEditor.vue
- 步骤二
- 如果没有，我的修改，请将原来的模拟ajax请求赋值改成：
```
      setTimeout(() => {
        valueHtml.value = `<p>模拟 Ajax 异步设置内容</p>
        <p><img src="https://i0.hdslb.com/bfs/archive/77c9304d7e040b72e1ec24c33175b47ece9c3b6b.jpg" alt=""></p>
        <table border="1">  
        <thead>  
            <tr>  
                <th>姓名</th>  
                <th>年龄</th>  
                <th>职业</th>  
            </tr>  
        </thead>  
        <tbody>  
            <tr>  
                <td>张三</td>  
                <td>30</td>  
                <td>工程师</td>  
            </tr>  
            <tr>  
                <td>李四</td>  
                <td>25</td>  
                <td>设计师</td>  
            </tr>  
            <tr>  
                <td>王五</td>  
                <td>28</td>  
                <td>教师</td>  
            </tr>  
        </tbody>  
    </table>  `;
      }, 1500);
    });
```

**Comment by cycleccc** [comment]
https://www.jyshare.com/front-end/61/ 你的 src 403 呀，随便换一个就显示了
![image](https://github.com/wangeditor-team/wangEditor/assets/62703840/a9fd483b-6a9f-4a78-8c08-8c5a0f6d7489)

**Comment by yangnanle** [comment]
解决了，这个地址是从百度图片中随便拿的图片链接，单独点开是可以看到的，没有多想，十分感谢~
![image](https://github.com/wangeditor-team/wangEditor/assets/151699136/29548796-f684-4772-bc22-7129fa125afe)

**Comment by cycleccc** [comment]
OK,没问题的话就可以关闭这个 issue 了
