### ISSUE TITLE
如何设置菜单hover后tooltip的文字？

### ISSUE THREAD

**Issue by liubiliubi** [wangeditor-team/wangEditor#5893]
![image](https://github.com/wangeditor-team/wangEditor/assets/145520617/4dc425a6-7336-4885-9ec4-6d3c2c9c8876)

**Comment by cycleccc** [comment]
自定义时设置title即可
![image](https://github.com/wangeditor-team/wangEditor/assets/62703840/ccb6aaa6-08c5-4349-ad2a-fac433be79aa)

**Comment by shangcj1992** [comment]
怎么解决的。

> ###
> ** ** 评论了 [2024 年 7 月 3 日](#issuecomment-2205051351)

这个方式。没有解决呀。。。

**Comment by cycleccc** [comment]
> 怎么解决的。
> 
> > ** ** 评论了 [2024 年 7 月 3 日](#issuecomment-2205051351)
> 
> 这个方式。没有解决呀。。。

自定义菜单 hover 字段展示有问题吗
