### ISSUE TITLE
编辑区渲染html效果不好

### ISSUE THREAD

**Issue by yangnanle** [wangeditor-team/wangEditor#5894]
## 渲染编辑区

*在编辑区，给定HTML后，渲染出来的效果很不好，会产生很多空白也就是p，但是在https://www.wangeditor.com/demo/set-html.html 就可以正常显示*

## wangEditor 版本

*最新版本*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 可以下载demo：https://github.com/yangnanle/wangeditor_question

希望可以得到解决，在此先感谢~

**Comment by cycleccc** [comment]
类似这个例子吗https://stackblitz.com/edit/stackblitz-starters-45sfub?file=package.json

**Comment by cycleccc** [comment]
提个小建议，可以用 codesandbox 或 stackblitz 快捷导入github项目，用沙盒比较快。

**Comment by yangnanle** [comment]
@cycleccc  不算很像，是在vue3中使用，我放到了stackblitz上，方便看看嘛https://stackblitz.com/~/github.com/yangnanle/wangeditor_question

**Comment by cycleccc** [comment]
https://stackblitz.com/edit/vue3-wangeditor-demo-ovdsmr?file=src%2Fcomponents%2FBasicEditor.vue
试试比较一下，这两个 demo 的差异，看下哪里导致的

**Comment by cycleccc** [comment]
回复不一定很及时，最近在看另一个棘手的 bug。

**Comment by cycleccc** [comment]
> https://stackblitz.com/edit/vue3-wangeditor-demo-ovdsmr?file=src%2Fcomponents%2FBasicEditor.vue 试试比较一下，这两个 demo 的差异，看下哪里导致的

这个 demo 里用的 wangeidtor-next，但是成因应该和这个没关系，我没在 next 版本里做全局 sethtml 渲染的修改。

**Comment by cycleccc** [comment]
另提一句，方便的话可以给 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 点个 star，这对我继续维护wangeditor 很重要。

**Comment by yangnanle** [comment]
@cycleccc 这两个区别在于：我是将wangeditor封装起来了，绑定的valueHtml是父传过去，然后就有这个问题，但是不明白是什么原理造成的？

**Comment by yangnanle** [comment]
> 另提一句，方便的话可以给 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 点个 star，这对我继续维护wangeditor 很重要。

okk

**Comment by cycleccc** [comment]
![image](https://github.com/wangeditor-team/wangEditor/assets/62703840/4f5fdb11-560d-499a-9500-ad2a791c4945)
传递的过程中回车转成了  \n ，在wangeditor中\n会转成 `<p><br/></p>`

**Comment by yangnanle** [comment]
> ![image](https://private-user-images.githubusercontent.com/62703840/345709778-4f5fdb11-560d-499a-9500-ad2a791c4945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzI0MDAsIm5iZiI6MTcyMDA3MjEwMCwicGF0aCI6Ii82MjcwMzg0MC8zNDU3MDk3NzgtNGY1ZmRiMTEtNTYwZC00OTlhLTk1MDAtYWQyYTc5MWM0OTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA1NDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OGQyZTNiNjYxZDQ4YTQyYzM4MTE2MzgxM2E3YmUyMGE4M2VmMzcxYzZmZDQ5MWVmMzI5NWQ3ZTRjMGZmMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.taA6KUS5bTaKuoKa0CsgghWL-d22JbOoYSYe8kV31OQ) 传递的过程中回车转成了 \n ，在wangeditor中\n会转成 `<p><br/></p>`

中间就只赋值，没有进行其他操作，这样也会导致嘛？还是说获取html值，不适合由父组件传递

**Comment by cycleccc** [comment]
研究了一下，太久没写 vue 了，不能给出确切的答案，应该和 wangeditor 没关系 ，试试使用 .replace(/\n/g, '') 过滤一下模板字符串再传递？

**Comment by yangnanle** [comment]
> 研究了一下，太久没写 vue 了，不能给出确切的答案，应该和 wangeditor 没关系 ，试试使用 .replace(/\n/g, '') 过滤一下模板字符串再传递？

解决了，```.replace(/\n/, '')```，加上g会导致表格内容缺失，感谢感谢~
