### ISSUE TITLE
视频在编辑态是居中的，但运行态是靠左

### ISSUE THREAD

**Issue by xiaodi0003** [wangeditor-team/wangEditor#5895]
操作步骤：
1、在编辑态插入一个视频元素，地址填https://www.w3school.com.cn/i/video/shanghai.mp4
2、修改视频的宽度为200
3、看到的结果如图，预期效果是编辑态和运行态的居中模式相同

<img width="1499" alt="image" src="https://github.com/wangeditor-team/wangEditor/assets/12879615/c52000af-1681-4035-a005-b73df03f713d">

**Comment by cycleccc** [comment]
这个在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 已修改，如有需要可在 查看 readme 中的沙盒demo可行后，替换 包及修改版本。

**Comment by cycleccc** [comment]
不替换包的话也可以，自己维护一份 css 规则就行，但是要后续都统一这个 css 规则。具体看 [自定义样式](https://www.wangeditor.com/v5/content.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by cycleccc** [comment]
这个 issue 是老问题了，如果可以解决你的问题的话，麻烦解决后记得关闭 issue ，感谢🙏

**Comment by xiaodi0003** [comment]
感谢答复
