### ISSUE TITLE
使用insertKeys时无法插入自定义菜单，控制台报错xxxx

### ISSUE THREAD

**Issue by lunarlooppp** [wangeditor-team/wangEditor#5900]
## 问题描述

*使用insertKeys时无法插入自定义菜单，控制台报错xxxx没有定义*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
使用这段配置绑定ToolBar组件
`const toolbarConfig = {
  insertKeys: {
    index: 30, // 插入的位置，基于当前的 toolbarKeys
    keys: ["g-catalog"]
  },`
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
截图、视频、最小复现

**Comment by cycleccc** [comment]
自定义菜单正确定义了吗，得先确保自定义菜单正确定义注册了才行。

**Comment by lunarlooppp** [comment]
> 自定义菜单正确定义了吗，得先确保自定义菜单正确定义注册了才行。

![f9bfd04e1ce9b683a2acd937a93ae5fc](https://github.com/wangeditor-team/wangEditor/assets/108122767/d6aba136-86cd-42df-ad3f-5393c52f7bf4)
这是报错，应该是没有正确定义注册自定义菜单，但是我没找到文档在哪里注册自定义菜单
是这个吗
![1bb14dcb1c2a8ac2d44da857e3f7cfde](https://github.com/wangeditor-team/wangEditor/assets/108122767/79b1e397-02a2-41fc-90ca-4cc141d70a55)

**Comment by lunarlooppp** [comment]
![703fcb9912a8317f65b4964466568d53](https://github.com/wangeditor-team/wangEditor/assets/108122767/0fb77e2f-86ad-43f4-8661-2042c0aa7b21)
![15569b79192323f3ea18a839bca527a8](https://github.com/wangeditor-team/wangEditor/assets/108122767/be8f7de8-7f24-4870-bbfe-37a6eaee3518)

**Comment by cycleccc** [comment]
https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E6%96%B0%E8%8F%9C%E5%8D%95 按照文档以及 demo 实现自定义菜单

**Comment by lunarlooppp** [comment]
> https://www.wangeditor.com/v5/development.html#%E6%B3%A8%E5%86%8C%E6%96%B0%E8%8F%9C%E5%8D%95 按照文档以及 demo 实现自定义菜单

明白了，感谢

**Comment by cycleccc** [comment]
如果觉得官方文档有什么可以改进的话可以到 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 提 issue，我最近打算重构一下文档。
