### ISSUE TITLE
dangerouslyInsertHtml 在safari无效果，在chrome和firefox下正常。

### ISSUE THREAD

**Issue by zituocn** [wangeditor-team/wangEditor#5909]
## bug 描述

dangerouslyInsertHtml 在safari无效果，在chrome和firefox下正常。

## 你预期的样子是？

都能正常

## 系统和浏览器及版本号

- macos 
- safari 17.5

## wangEditor 版本

5.15.1

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

无

## 最小成本的复现步骤

调用  dangerouslyInsertHtml api，在此环境中操作失败。也无控制台错误。

**Comment by cycleccc** [comment]
有点奇怪，dangerouslyInsertHtml api 在 wangeditor 内部也是会使用的，像是粘贴富文本内容就会调用 dangerouslyInsertHtml 
我没有 mac 设备，要查这个 bug 可能不太方便。

**Comment by zituocn** [comment]
在相同的代码情况下，chrome和firefox均正常。
setHtml等函数也正常。

**Comment by zituocn** [comment]
暂时使用原始菜单上的btn，配置customBrowseAndUpload  解决问题。

之前走新菜单的方式，在safari下未解决。
