### ISSUE TITLE
上传图片报错

### ISSUE THREAD

**Issue by whoqq** [wangeditor-team/wangEditor#5914]
## 问题描述
我已经设置了Server但却仍然提示没有配置
![屏幕截图 2024-07-27 111407](https://github.com/user-attachments/assets/9ca3ca9a-82eb-4be3-bc3d-11a210ad5c88)
![屏幕截图 2024-07-27 111424](https://github.com/user-attachments/assets/370e00e6-815f-43d7-87db-867d0e418701)
*请输入遇到的问题...*
我已经配置了Server，但却报错没有配置
## wangEditor 版本
V3

*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
这个问题没法回答你，v3 现在没有维护了，只有 v5 还在维护

**Comment by whoqq** [comment]
> 这个问题没法回答你，v3 现在没有维护了，只有 v5 还在维护

现在才看到打错了，就是V5
