### ISSUE TITLE
图片上传出现问题

### ISSUE THREAD

**Issue by whoqq** [wangeditor-team/wangEditor#5915]
## 问题描述
我已经配置了后端上传服务器的接口，但却仍然提示我没有配置
![屏幕截图 2024-07-27 111407](https://github.com/user-attachments/assets/238cccd7-085d-49aa-9bdb-81bbbf5102e4)
![屏幕截图 2024-07-27 111424](https://github.com/user-attachments/assets/34dd7884-d5d2-4393-9a45-9dc5d5e8059f)

*请输入遇到的问题...*
我已经配置了后端上传服务器的接口，但却仍然提示我没有配置

## wangEditor 版本
V5
*请输入内容……*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*
是
## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
参照wangEditor 的 server 的 demo 试试吧

**Comment by cycleccc** [comment]
https://github.com/wangeditor-team/server

**Comment by whoqq** [comment]
> https://github.com/wangeditor-team/server

解决了，参考的这个https://blog.csdn.net/taogugu/article/details/124241151

**Comment by zqxxjs** [comment]
建议看下文档的如何自定配置上传
贴下我的vue3相关代码给你看看,uploadApi是自定义的上传方法，接受两个参数，第一个参数的file是必选的，第二个参数是进度参数可以不填
```
      type InsertFnType = (url: string, alt?: string, href?: string) => void;
      const customUpload = (file: File, insertFn: Function | InsertFnType) => {
        uploadApi({ file }, progressProps).then((res: AxiosResponse<Result<string>>) => {
          const funcKw = insertFn.toString();
          const fileUrl = res.data.result.data[0];//服务返回的文件http链接
          if (funcKw.includes('(t7, n5)')) {
            //如果是上传附件，区分标识就是方法toString后包含'(t7, n5)'
            insertFn(file.name, fileUrl);
          } else {
            insertFn(fileUrl);
          }
        });
      };
      MENU_CONF: {
          uploadImage: { customUpload },
          uploadVideo: { customUpload },
          uploadAttachment: { customUpload },
        },
```
