### ISSUE TITLE
工具栏中的标题选择是否可以添加H6标签

### ISSUE THREAD

**Issue by yangnanle** [wangeditor-team/wangEditor#5928]
## 功能描述

*标题选项中，希望支持H6标签*

> 使用时，发现不支持h6，语雀,、印象笔记这类基本都支持h6，希望可以支持

## 提炼几个功能点

- 标题选项中，添加H6标签选项

**Comment by cycleccc** [comment]
已在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 实现 可在 [demo](https://cycleccc.github.io/demo/) 查看

**Comment by yangnanle** [comment]
> 已在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 实现 可在 [demo](https://cycleccc.github.io/demo/) 查看

哈喽，未在[demo](https://cycleccc.github.io/demo/)中发现H6标签；在wangeditor-next提供的vue3[demo](https://stackblitz.com/edit/vue3-wangeditor-demo-8emmc7)中并未发现有H6。
![image](https://github.com/user-attachments/assets/17a8b72a-2287-495c-bbb3-703f25cba504)

**Comment by cycleccc** [comment]
提到 dev 分支忘合到 master 了
现在合，最近会再发版

**Comment by yangnanle** [comment]
好的呢
