### ISSUE TITLE
撤销功能

### ISSUE THREAD

**Issue by yangnanle** [wangeditor-team/wangEditor#5932]
## 问题描述

*项目需求是，点击切页的时候，编辑区的内容要切换，但是一旦切页，点击撤销的时候会是上一页的内容，不符合逻辑*

## wangEditor 版本

*v5*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）
> [测试链接](https://stackblitz.com/~/github.com/yangnanle/wangeditor_question?file=src/views/pageEditor.vue&folder=vscode-remote%3A%2F%2Fwebcontainer%2Fhome%2Fyangnanle%2Fwangeditor_question)

- 点击进行切页
- 成功之后，点击撤销

> 因为页码可能会有很多，几百页之类，如果每次获取内容之后，销毁创建编辑器，感觉不太合理，想问有没有其他的解决方案

**Comment by cycleccc** [comment]
切换页码是丢弃旧的 history 能满足需求吗？
可以尝试使用 

``` javascript
editor.history.undos.length = 0;
editor.history.redos.length = 0;
```
清除历史

**Comment by yangnanle** [comment]
不生效，在切换页码时，先清除了历史，再获取数据不起作用[demo](https://stackblitz.com/~/github.com/yangnanle/wangeditor_question?file=src/views/pageEditor.vue&folder=vscode-remote%3A%2F%2Fwebcontainer%2Fhome%2Fyangnanle%2Fwangeditor_question)

**Comment by cycleccc** [comment]
wangeditor  内置的 历史管理是 slate-history ，slate-history 没有内置 clear history api，可能得后续试试 魔改一个 clear history

可以试试多编辑器，点击下一页时另外创建一个编辑器，单独维护一份 history
参考以下demo和代码：
https://cycleccc.github.io/demo/multi-editor.html
https://github.com/end-cycle/wangEditor/blob/fde2a69e34abde08a209211c2643f6c5071ee233/packages/editor/examples/multi-editors.html#L57

**Comment by yangnanle** [comment]
如果页码很多时，需要创建n份编辑器，这个思路和每次切换页码销毁创建差不多，创建销毁可能更方便一些，那么每次切页销毁重新创建，会有不适嘛？

**Comment by cycleccc** [comment]
应该没什么问题，担心性能问题的话可以用开发者工具开性能分析看看

**Comment by yangnanle** [comment]
好的，目前测试未出现什么问题，感谢~
