### ISSUE TITLE
使用DomEditor.getToolbar(editor)获取到的toolbar是个null

### ISSUE THREAD

**Issue by 1353723767** [wangeditor-team/wangEditor#5935]
我按照文档中的方式获取toolbar.getConfig()，但是toolbar会是个null，请问需要怎么处理？
![image](https://github.com/user-attachments/assets/dfe80749-c1a9-41dc-a7bc-2c0b3fc43253)
![image](https://github.com/user-attachments/assets/10aca735-1bad-46d8-99b6-572239f1af60)

**Comment by cycleccc** [comment]
在 getConfig 前 editor 有值吗，如果 editor 是 null 的话 获取到的 toolbar 也是 null

**Comment by 1353723767** [comment]
> 在 getConfig 前 editor 有值吗，如果 editor 是 null 的话 获取到的 toolbar 也是 null

editor是有值的，在编辑器实例化函数里面去使用的
![image](https://github.com/user-attachments/assets/82f2d791-a2cb-4abb-ab7d-596d36b91059)

**Comment by cycleccc** [comment]
在  onChange 拿 toolbar config 吧，created 的时候 toolbar 还没创建好，EDITOR_TO_TOOLBAR map 里 editor 对应的 toolbar 还没创建好

**Comment by 1353723767** [comment]
> 在 onChange 拿 toolbar config 吧，created 的时候 toolbar 还没创建好，EDITOR_TO_TOOLBAR map 里 editor 对应的 toolbar 还没创建好

明白了，谢谢

**Comment by cycleccc** [comment]
在 https://cycleccc.github.io/docs/guide/toolbar-config#getconfig 做了文档补充

这个 issue 没问题的话可以关闭了。
