### ISSUE TITLE
在进行"type-check": "vue-tsc --build --force"时，在import {Editor, Toolbar} from '@wangeditor/editor-for-vue'时，无法找到editor-for-vue的声明文件，已经做了npm install还是不行 

### ISSUE THREAD

**Issue by myflie** [wangeditor-team/wangEditor#5948]
## 问题描述

*在进行"type-check": "vue-tsc --build --force"时，在import {Editor, Toolbar} from '@wangeditor/editor-for-vue'时，无法找到editor-for-vue的声明文件，已经做了npm install还是不行*

## wangEditor 版本

*5.1.12*

## 是否查阅了文档 ？

（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 安装wangEditor 
- 组件引入import {Editor, Toolbar} from '@wangeditor/editor-for-vue'
- 进行"type-check": "vue-tsc --build --force"

**Comment by cycleccc** [comment]
https://github.com/wangeditor-team/wangEditor-for-vue3/issues/23
看这个
