### ISSUE TITLE
暂不支持。

### ISSUE THREAD

**Issue by panxin226** [wangeditor-team/wangEditor#5961]
大佬，现在表格支持合并单元格了吗？

              暂不支持。

这个功能太复杂了，等有空了再开发，现在精力不够。

_Originally posted by @wangfupeng1988 in https://github.com/wangeditor-team/wangEditor/issues/4760#issuecomment-1225329071_

**Comment by cycleccc** [comment]
表格合并转 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 使用

**Comment by panxin226** [comment]
> 表格合并转 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 使用
可以把wangEditor 直接升级成wandEditor -next使用吗？，打开之前wangEditor 做的表格，尝试拖拽之后页面卡死
