### ISSUE TITLE
合并单元格之后的表格列宽拖拽问题

### ISSUE THREAD

**Issue by panxin226** [wangeditor-team/wangEditor#5962]
## 问题描述
我从word文档合并单元格之后，复制粘贴到编辑器里面，只可以拖拽第一行列宽，下面行的列宽无法拖拽。而且拖动第一行，后面几行的列宽变化不规律。然后我加了td的拖拽列宽后，拖拽就变得很难用，经常拖不动。
![无标题](https://github.com/user-attachments/assets/a77f28d3-9ba7-43d1-823a-4e3e7af9a9c7)

*请输入遇到的问题...*

## wangEditor 版本

*请输入内容……*

## 是否查阅了文档 ？
是
（文档链接 [www.wangeditor.com](https://www.wangeditor.com/) ）

*是/否*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
- 步骤二
- 步骤三

**Comment by cycleccc** [comment]
github 可以拖拽上传 word 附件，是在 wangeidtor 复现的还是在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) [demo](https://cycleccc.github.io/demo/) 复现的呢？

**Comment by panxin226** [comment]
[新建 Microsoft Word 文档.docx](https://github.com/user-attachments/files/17112600/Microsoft.Word.docx)
是在wangeidtor里面复现

**Comment by panxin226** [comment]
> github 可以拖拽上传 word 附件，是在 wangeidtor 复现的还是在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) [demo](https://cycleccc.github.io/demo/) 复现的呢？
[新建 Microsoft Word 文档.docx](https://github.com/user-attachments/files/17112673/Microsoft.Word.docx)
是在wangeidtor里面复现
