### ISSUE TITLE
选中区域同时选中了有序/无序列表与表格单元格时，进行删除操作后的报错问题

### ISSUE THREAD

**Issue by JerryLin233** [wangeditor-team/wangEditor#5970]
## bug 描述

选中区域同时选中了有序/无序列表与表格单元格时，进行删除操作后的报错问题

## 你预期的样子是？

无异常行为

## 系统和浏览器及版本号

- 操作系统
- 浏览器和版本

## wangEditor 版本

5.1.23 稳定复现
试了5.0.1不会报错

## demo 能否复现该 bug ？

能

- 中文 demo https://www.wangeditor.com/demo/
- English demo https://www.wangeditor.com/demo/?lang=en

## 在线 demo

*请尽量提供在线 demo （推荐以下网站），帮助我们最低成本复现 bug*

- https://codesandbox.io/
- https://codepen.io/
- https://stackblitz.com/

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

![image](https://github.com/user-attachments/assets/a28d3911-0905-4f0e-a671-a131ffeb8029)

选中删除后报错：
![image](https://github.com/user-attachments/assets/9cc4ec2b-829c-47ec-865a-59a80744852f)
![image](https://github.com/user-attachments/assets/4dbd79b6-bb27-4e9c-a074-1fdd50d808a9)

**Comment by cycleccc** [comment]
已在 [wangeditor-next](https://github.com/cycleccc/wangEditor-next) 修复
