### ISSUE TITLE
富文本 3.x 测试ie11 复制黏贴功能，功能不能正常使用。有解决办法么？

### ISSUE THREAD

**Issue by haschild** [wangeditor-team/wangEditor#793]
我是直接在官网dome里测试。

我使用IE浏览器的版本是：11.91610586.0

**Comment by wangfupeng1988** [comment]
这个问题我现在已知，正在高优解决，计划2-3个小版本更新这个问题，请关注升级提醒。每次升级修复的问题记录在 https://github.com/wangfupeng1988/wangEditor/blob/master/ISSUE.md

**Comment by haschild** [comment]
好的，会持续关注的。

**Comment by UltimateRedx** [comment]
记事本中第一次复制过来的文本集中在初始化的<p></p>里面了，第二次之后才有换行格式。这个问题是这在说这个吗 @wangfupeng1988

**Comment by ShiHongyun** [comment]
@wangfupeng1988 IE11复制粘贴的问题有计划什么时候可以解决掉吗

**Comment by haschild** [comment]
@wangfupeng1988  大佬先解决IE的复制黏贴嘛，等着发版本呢。

**Comment by wangfupeng1988** [comment]
已排到升级计划中，近期会升级，计划最晚下个周末解决。抱歉让各位久等了，感谢各位的支持。

**Comment by wangfupeng1988** [comment]
10.0.13版本新增了`editor.customConfig.pasteTextHandle`可自定义处理粘贴的内容 https://www.kancloud.cn/wangfupeng/wangeditor3/448202

**Comment by UltramanWeiLai** [comment]
V4 即将发布，已解决该问题，感谢反馈
